Dash Core: src/qt/splashscreen.cpp File Reference
splashscreen.cpp File Reference
#include "splashscreen.h"
#include "guiutil.h"
#include "networkstyle.h"
#include "clientversion.h"
#include "init.h"
#include "util.h"
#include "ui_interface.h"
#include "version.h"
#include <QApplication>
#include <QCloseEvent>
#include <QDesktopWidget>
#include <QPainter>
Functions
static void InitMessage (SplashScreen *splash, const std::string &message)
static void ShowProgress (SplashScreen *splash, const std::string &title, int nProgress)
static void SetProgressBreakAction (SplashScreen *splash, const std::function< void(void)> &action)
Function Documentation
InitMessage()
static void InitMessage (SplashScreen * splash, const std::string & message) static
Definition at line 136 of file splashscreen.cpp.
Referenced by ShowProgress(), SplashScreen::subscribeToCoreSignals(), and SplashScreen::unsubscribeFromCoreSignals().
SetProgressBreakAction()
static void SetProgressBreakAction (SplashScreen * splash, const std::function< void(void)> & action) static
Definition at line 155 of file splashscreen.cpp.
Referenced by SplashScreen::subscribeToCoreSignals().
ShowProgress()
static void ShowProgress (SplashScreen * splash, const std::string & title, int nProgress) static
Definition at line 145 of file splashscreen.cpp.
References InitMessage(), and strprintf.
Referenced by SplashScreen::subscribeToCoreSignals(), and SplashScreen::unsubscribeFromCoreSignals().