Dash Core: src/privatesend.cpp File Reference
privatesend.cpp File Reference
#include "privatesend.h"
#include "activemasternode.h"
#include "consensus/validation.h"
#include "governance.h"
#include "init.h"
#include "instantx.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "masternodeman.h"
#include "messagesigner.h"
#include "script/sign.h"
#include "txmempool.h"
#include "util.h"
#include "utilmoneystr.h"
#include <boost/lexical_cast.hpp>
Functions
void ThreadCheckPrivateSend (CConnman &connman)
Function Documentation
ThreadCheckPrivateSend()
void ThreadCheckPrivateSend (CConnman & connman)
Definition at line 439 of file privatesend.cpp.
References activeMasternode, CMasternodeMan::Check(), CInstantSend::CheckAndRemove(), CMasternodeMan::CheckAndRemove(), CMasternodePayments::CheckAndRemove(), CMasternodeMan::DoFullVerificationStep(), CGovernanceManager::DoMaintenance(), fLiteMode, fMasterNode, governance, instantsend, CMasternodeSync::IsBlockchainSynced(), CActiveMasternode::ManageState(), MASTERNODE_MIN_MNP_SECONDS, masternodeSync, MilliSleep(), mnodeman, mnpayments, CMasternodeMan::ProcessMasternodeConnections(), CMasternodeSync::ProcessTick(), RenameThread(), and ShutdownRequested().
Referenced by AppInit2().