Dash Core: src/wallet/walletdb.cpp File Reference
walletdb.cpp File Reference
#include "wallet/walletdb.h"
#include "base58.h"
#include "consensus/validation.h"
#include "validation.h"
#include "protocol.h"
#include "serialize.h"
#include "sync.h"
#include "util.h"
#include "utiltime.h"
#include "wallet/wallet.h"
#include <boost/filesystem.hpp>
#include <boost/foreach.hpp>
#include <boost/scoped_ptr.hpp>
#include <boost/thread.hpp>
Classes
class CWalletScanState
Functions
bool ReadKeyValue (CWallet *pwallet, CDataStream &ssKey, CDataStream &ssValue, CWalletScanState &wss, string &strType, string &strErr)
static bool IsKeyType (string strType)
void ThreadFlushWalletDB (const string &strFile)
bool BackupWallet (const CWallet &wallet, const string &strDest)
bool AutoBackupWallet (CWallet *wallet, std::string strWalletFile, std::string &strBackupWarning, std::string &strBackupError)
Variables
static uint64_t nAccountingEntryNumber = 0
Function Documentation
AutoBackupWallet()
bool AutoBackupWallet (CWallet * wallet, std::string strWalletFile, std::string & strBackupWarning, std::string & strBackupError)
Definition at line 946 of file walletdb.cpp.
References _(), BackupWallet(), cs_main, CWallet::cs_wallet, GUIUtil::dateTimeStr(), DateTimeStrFormat(), error(), GetBackupsDir(), GetDataDir(), GetTime(), CCryptoKeyStore::IsLocked(), CWallet::KeypoolCountExternalKeys(), LOCK2, LogPrintf, CWallet::nKeysLeftSinceAutoBackup, nWalletBackups, PAIRTYPE, strprintf, CWallet::strWalletFile, and wallet.
Referenced by AppInit2(), CPrivateSendClient::CheckAutomaticBackup(), and OverviewPage::privateSendStatus().
BackupWallet()
bool BackupWallet (const CWallet & wallet, const string & strDest)
Definition at line 904 of file walletdb.cpp.
References bitdb, CDBEnv::CheckpointLSN(), CDBEnv::CloseDb(), CDBEnv::cs_db, CWallet::fFileBacked, GetDataDir(), LOCK, LogPrintf, CDBEnv::mapFileUseCount, MilliSleep(), CWallet::strWalletFile, and wallet.
Referenced by AutoBackupWallet(), WalletModel::backupWallet(), and backupwallet().
IsKeyType()
static bool IsKeyType (string strType) static
Definition at line 641 of file walletdb.cpp.
Referenced by CWalletDB::LoadWallet(), and CWalletDB::Recover().
ReadKeyValue()
bool ReadKeyValue (CWallet * pwallet, CDataStream & ssKey, CDataStream & ssValue, CWalletScanState & wss, string & strType, string & strErr)
Definition at line 350 of file walletdb.cpp.
References CWallet::AddToWallet(), CheckTransaction(), CDataStream::empty(), CWalletScanState::fAnyUnordered, CWalletScanState::fIsEncrypted, CBitcoinAddress::Get(), Hash(), base_blob< BITS >::IsNull(), CValidationState::IsValid(), CKey::Load(), CWallet::LoadCryptedKey(), CWallet::LoadCScript(), CWallet::LoadDestData(), CWallet::LoadHDPubKey(), CWallet::LoadKey(), CWallet::LoadKeyMetadata(), CWallet::LoadKeyPool(), CWallet::LoadWatchOnly(), CWallet::mapAddressBook, CWallet::mapMasterKeys, nAccountingEntryNumber, CWalletScanState::nCKeys, CWalletScanState::nFileVersion, CWalletScanState::nKeyMeta, CWalletScanState::nKeys, CWallet::nMasterKeyMaxID, CWallet::nOrderPosNext, CWallet::nTimeFirstKey, CWallet::SetCryptedHDChain(), CWallet::SetHDChain(), strprintf, CWallet::vchDefaultKey, CWalletKey::vchPrivKey, and CWalletScanState::vWalletUpgrade.
Referenced by CWalletDB::LoadWallet(), and CWalletDB::Recover().
ThreadFlushWalletDB()
void ThreadFlushWalletDB (const string & strFile)
Definition at line 842 of file walletdb.cpp.
References bitdb, CDBEnv::CheckpointLSN(), CDBEnv::CloseDb(), CDBEnv::cs_db, DEFAULT_FLUSHWALLET, GetBoolArg(), GetTime(), GetTimeMillis(), LogPrint(), CDBEnv::mapFileUseCount, MilliSleep(), nWalletDBUpdated, RenameThread(), and TRY_LOCK.
Referenced by AppInit2().
Variable Documentation
nAccountingEntryNumber
uint64_t nAccountingEntryNumber = 0 static
Definition at line 26 of file walletdb.cpp.
Referenced by ReadKeyValue(), and CWalletDB::WriteAccountingEntry_Backend().