Dash Core: CDarksendBroadcastTx Class Reference
CDarksendBroadcastTx Class Reference
Helper class to store mixing transaction (tx) information.
#include <privatesend.h>
Public Member Functions
CDarksendBroadcastTx ()
CDarksendBroadcastTx (CTransaction tx, COutPoint outpoint, int64_t sigTime)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
operator bool () const
bool Sign ()
bool CheckSignature (const CPubKey &pubKeyMasternode)
void SetConfirmedHeight (int nConfirmedHeightIn)
bool IsExpired (int nHeight)
Public Attributes
CTransaction tx
CTxIn vin
std::vector< unsigned char > vchSig
int64_t sigTime
ADD_SERIALIZE_METHODS
Private Attributes
int nConfirmedHeight
Friends
bool operator== (const CDarksendBroadcastTx &a, const CDarksendBroadcastTx &b)
bool operator!= (const CDarksendBroadcastTx &a, const CDarksendBroadcastTx &b)
Detailed Description
Helper class to store mixing transaction (tx) information.
Definition at line 211 of file privatesend.h.
Constructor & Destructor Documentation
CDarksendBroadcastTx() [1/2]
CDarksendBroadcastTx::CDarksendBroadcastTx () inline
Definition at line 224 of file privatesend.h.
Referenced by operator bool().
CDarksendBroadcastTx() [2/2]
CDarksendBroadcastTx::CDarksendBroadcastTx (CTransaction tx, COutPoint outpoint, int64_t sigTime) inline
Definition at line 232 of file privatesend.h.
Member Function Documentation
CheckSignature()
bool CDarksendBroadcastTx::CheckSignature (const CPubKey & pubKeyMasternode)
Definition at line 90 of file privatesend.cpp.
References CTransaction::GetHash(), LogPrintf, sigTime, base_blob< BITS >::ToString(), tx, vchSig, and CMessageSigner::VerifyMessage().
Referenced by ProcessMessage(), and Sign().
IsExpired()
bool CDarksendBroadcastTx::IsExpired (int nHeight)
Definition at line 103 of file privatesend.cpp.
References nConfirmedHeight.
operator bool()
CDarksendBroadcastTx::operator bool () const inline explicit
Definition at line 258 of file privatesend.h.
References CDarksendBroadcastTx().
SerializationOp()
template<typename Stream , typename Operation > void CDarksendBroadcastTx::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 243 of file privatesend.h.
References READWRITE, sigTime, tx, vchSig, and vin.
SetConfirmedHeight()
void CDarksendBroadcastTx::SetConfirmedHeight (int nConfirmedHeightIn) inline
Definition at line 266 of file privatesend.h.
References nConfirmedHeight.
Sign()
bool CDarksendBroadcastTx::Sign ()
Definition at line 76 of file privatesend.cpp.
References activeMasternode, CheckSignature(), fMasterNode, CTransaction::GetHash(), CActiveMasternode::keyMasternode, LogPrintf, CActiveMasternode::pubKeyMasternode, CMessageSigner::SignMessage(), sigTime, base_blob< BITS >::ToString(), tx, and vchSig.
Referenced by CPrivateSendServer::CommitFinalTransaction().
Friends And Related Function Documentation
operator!=
bool operator!= (const CDarksendBroadcastTx & a, const CDarksendBroadcastTx & b) friend
Definition at line 254 of file privatesend.h.
operator==
bool operator== (const CDarksendBroadcastTx & a, const CDarksendBroadcastTx & b) friend
Definition at line 250 of file privatesend.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CDarksendBroadcastTx::ADD_SERIALIZE_METHODS
Definition at line 240 of file privatesend.h.
nConfirmedHeight
int CDarksendBroadcastTx::nConfirmedHeight private
Definition at line 216 of file privatesend.h.
Referenced by IsExpired(), and SetConfirmedHeight().
sigTime
int64_t CDarksendBroadcastTx::sigTime
Definition at line 222 of file privatesend.h.
Referenced by CheckSignature(), SerializationOp(), and Sign().
tx
CTransaction CDarksendBroadcastTx::tx
Definition at line 219 of file privatesend.h.
Referenced by CPrivateSend::AddDSTX(), CheckSignature(), SerializationOp(), and Sign().
vchSig
std::vector<unsigned char> CDarksendBroadcastTx::vchSig
Definition at line 221 of file privatesend.h.
Referenced by CheckSignature(), SerializationOp(), and Sign().
vin
CTxIn CDarksendBroadcastTx::vin
Definition at line 220 of file privatesend.h.
Referenced by ProcessMessage(), and SerializationOp().
The documentation for this class was generated from the following files:
src/privatesend.h
src/privatesend.cpp