Dash Core: CAddressUnspentKey Struct Reference
CAddressUnspentKey Struct Reference
#include <spentindex.h>
Public Member Functions
size_t GetSerializeSize (int nType, int nVersion) const
template<typename Stream >
void Serialize (Stream &s, int nType, int nVersion) const
template<typename Stream >
void Unserialize (Stream &s, int nType, int nVersion)
CAddressUnspentKey (unsigned int addressType, uint160 addressHash, uint256 txid, size_t indexValue)
CAddressUnspentKey ()
void SetNull ()
Public Attributes
unsigned int type
uint160 hashBytes
uint256 txhash
size_t index
Detailed Description
Definition at line 160 of file spentindex.h.
Constructor & Destructor Documentation
CAddressUnspentKey() [1/2]
CAddressUnspentKey::CAddressUnspentKey (unsigned int addressType, uint160 addressHash, uint256 txid, size_t indexValue) inline
Definition at line 184 of file spentindex.h.
References hashBytes, index, txhash, and type.
CAddressUnspentKey() [2/2]
CAddressUnspentKey::CAddressUnspentKey () inline
Definition at line 191 of file spentindex.h.
References SetNull().
Member Function Documentation
GetSerializeSize()
size_t CAddressUnspentKey::GetSerializeSize (int nType, int nVersion) const inline
Definition at line 166 of file spentindex.h.
Serialize()
template<typename Stream > void CAddressUnspentKey::Serialize (Stream & s, int nType, int nVersion) const inline
Definition at line 170 of file spentindex.h.
References hashBytes, index, ser_writedata32(), ser_writedata8(), base_blob< BITS >::Serialize(), txhash, and type.
SetNull()
void CAddressUnspentKey::SetNull () inline
Definition at line 195 of file spentindex.h.
References hashBytes, index, base_blob< BITS >::SetNull(), txhash, and type.
Referenced by CAddressUnspentKey().
Unserialize()
template<typename Stream > void CAddressUnspentKey::Unserialize (Stream & s, int nType, int nVersion) inline
Definition at line 177 of file spentindex.h.
References hashBytes, index, ser_readdata32(), ser_readdata8(), txhash, type, and base_blob< BITS >::Unserialize().
Member Data Documentation
hashBytes
uint160 CAddressUnspentKey::hashBytes
Definition at line 162 of file spentindex.h.
Referenced by CAddressUnspentKey(), Serialize(), SetNull(), and Unserialize().
index
size_t CAddressUnspentKey::index
Definition at line 164 of file spentindex.h.
Referenced by CAddressUnspentKey(), Serialize(), SetNull(), and Unserialize().
txhash
uint256 CAddressUnspentKey::txhash
Definition at line 163 of file spentindex.h.
Referenced by CAddressUnspentKey(), Serialize(), SetNull(), and Unserialize().
type
unsigned int CAddressUnspentKey::type
Definition at line 161 of file spentindex.h.
Referenced by CAddressUnspentKey(), Serialize(), SetNull(), and Unserialize().
The documentation for this struct was generated from the following file:
src/spentindex.h