Dash Core: src/noui.cpp File Reference
noui.cpp File Reference
#include "noui.h"
#include "ui_interface.h"
#include "util.h"
#include <cstdio>
#include <stdint.h>
#include <string>
Functions
static bool noui_ThreadSafeMessageBox (const std::string &message, const std::string &caption, unsigned int style)
static bool noui_ThreadSafeQuestion (const std::string &, const std::string &message, const std::string &caption, unsigned int style)
static void noui_InitMessage (const std::string &message)
void noui_connect ()
Function Documentation
noui_connect()
void noui_connect ()
Definition at line 53 of file noui.cpp.
References CClientUIInterface::InitMessage, noui_InitMessage(), noui_ThreadSafeMessageBox(), noui_ThreadSafeQuestion(), CClientUIInterface::ThreadSafeMessageBox, CClientUIInterface::ThreadSafeQuestion, and uiInterface.
Referenced by main().
noui_InitMessage()
static void noui_InitMessage (const std::string & message) static
Definition at line 48 of file noui.cpp.
References LogPrintf.
Referenced by noui_connect().
noui_ThreadSafeMessageBox()
static bool noui_ThreadSafeMessageBox (const std::string & message, const std::string & caption, unsigned int style) static
Definition at line 16 of file noui.cpp.
References _(), LogPrintf, CClientUIInterface::MSG_ERROR, CClientUIInterface::MSG_INFORMATION, CClientUIInterface::MSG_WARNING, and CClientUIInterface::SECURE.
Referenced by noui_connect(), and noui_ThreadSafeQuestion().
noui_ThreadSafeQuestion()
static bool noui_ThreadSafeQuestion (const std::string & , const std::string & message, const std::string & caption, unsigned int style) static
Definition at line 43 of file noui.cpp.
References noui_ThreadSafeMessageBox().
Referenced by noui_connect().