Dash Core: src/privatesend-server.cpp File Reference
privatesend-server.cpp File Reference
#include "privatesend-server.h"
#include "activemasternode.h"
#include "consensus/validation.h"
#include "core_io.h"
#include "init.h"
#include "masternode-sync.h"
#include "masternodeman.h"
#include "script/interpreter.h"
#include "txmempool.h"
#include "util.h"
#include "utilmoneystr.h"
Functions
void ThreadCheckPrivateSendServer (CConnman &connman)
Variables
CPrivateSendServer privateSendServer
Function Documentation
ThreadCheckPrivateSendServer()
void ThreadCheckPrivateSendServer (CConnman & connman)
Definition at line 873 of file privatesend-server.cpp.
References CPrivateSendServer::CheckForCompleteQueue(), CPrivateSendServer::CheckTimeout(), fLiteMode, CMasternodeSync::IsBlockchainSynced(), masternodeSync, MilliSleep(), privateSendServer, RenameThread(), and ShutdownRequested().
Referenced by AppInit2().
Variable Documentation
privateSendServer
CPrivateSendServer privateSendServer
Definition at line 17 of file privatesend-server.cpp.
Referenced by getpoolinfo(), ProcessMessage(), and ThreadCheckPrivateSendServer().