Dash Core: CAddrDB Class Reference
CAddrDB Class Reference
Access to the (IP) address database (peers.dat)
#include <addrdb.h>
Public Member Functions
CAddrDB ()
bool Write (const CAddrMan &addr)
bool Read (CAddrMan &addr)
bool Read (CAddrMan &addr, CDataStream &ssPeers)
Private Attributes
boost::filesystem::path pathAddr
Detailed Description
Access to the (IP) address database (peers.dat)
Definition at line 81 of file addrdb.h.
Constructor & Destructor Documentation
CAddrDB()
CAddrDB::CAddrDB ()
Definition at line 116 of file addrdb.cpp.
References GetDataDir(), and pathAddr.
Member Function Documentation
Read() [1/2]
bool CAddrDB::Read (CAddrMan & addr)
Definition at line 159 of file addrdb.cpp.
References CDataStream::begin(), CLIENT_VERSION, CDataStream::end(), error(), Hash(), pathAddr, and SER_DISK.
Referenced by CConnman::Start().
Read() [2/2]
bool CAddrDB::Read (CAddrMan & addr, CDataStream & ssPeers)
Definition at line 197 of file addrdb.cpp.
References CAddrMan::Clear(), error(), FLATDATA, and Params().
Write()
bool CAddrDB::Write (const CAddrMan & addr)
Definition at line 121 of file addrdb.cpp.
References CDataStream::begin(), CLIENT_VERSION, CDataStream::end(), error(), FileCommit(), fileout, FLATDATA, GetDataDir(), GetRandBytes(), Hash(), Params(), pathAddr, RenameOver(), SER_DISK, and strprintf.
Referenced by CConnman::DumpAddresses().
Member Data Documentation
pathAddr
boost::filesystem::path CAddrDB::pathAddr private
Definition at line 84 of file addrdb.h.
Referenced by CAddrDB(), Read(), and Write().
The documentation for this class was generated from the following files:
src/addrdb.h
src/addrdb.cpp