Dash Core: WalletModel Class Reference
WalletModel Class Reference
Interface to Bitcoin wallet from Qt view code.
#include <walletmodel.h>
Classes
struct SendCoinsReturn
class UnlockContext
Public Types
enum StatusCode {
OK, InvalidAmount, InvalidAddress, AmountExceedsBalance,
AmountWithFeeExceedsBalance, DuplicateAddress, TransactionCreationFailed, TransactionCommitFailed,
AbsurdFee, PaymentRequestExpired
}
enum EncryptionStatus { Unencrypted, Locked, UnlockedForMixingOnly, Unlocked }
Public Slots
void updateStatus ()
void updateTransaction ()
void updateAddressBook (const QString &address, const QString &label, bool isMine, const QString &purpose, int status)
void updateWatchOnlyFlag (bool fHaveWatchonly)
void pollBalanceChanged ()
Signals
void balanceChanged (const CAmount &balance, const CAmount &unconfirmedBalance, const CAmount &immatureBalance, const CAmount &anonymizedBalance, const CAmount &watchOnlyBalance, const CAmount &watchUnconfBalance, const CAmount &watchImmatureBalance)
void encryptionStatusChanged (int status)
void requireUnlock (bool fForMixingOnly=false)
void message (const QString &title, const QString &message, unsigned int style)
void coinsSent (CWallet *wallet, SendCoinsRecipient recipient, QByteArray transaction)
void showProgress (const QString &title, int nProgress)
void notifyWatchonlyChanged (bool fHaveWatchonly)
Public Member Functions
WalletModel (const PlatformStyle *platformStyle, CWallet *wallet, OptionsModel *optionsModel, QObject *parent=0)
~WalletModel ()
OptionsModel * getOptionsModel ()
AddressTableModel * getAddressTableModel ()
TransactionTableModel * getTransactionTableModel ()
RecentRequestsTableModel * getRecentRequestsTableModel ()
CAmount getBalance (const CCoinControl *coinControl=NULL) const
CAmount getUnconfirmedBalance () const
CAmount getImmatureBalance () const
CAmount getAnonymizedBalance () const
bool haveWatchOnly () const
CAmount getWatchBalance () const
CAmount getWatchUnconfirmedBalance () const
CAmount getWatchImmatureBalance () const
EncryptionStatus getEncryptionStatus () const
bool validateAddress (const QString &address)
SendCoinsReturn prepareTransaction (WalletModelTransaction &transaction, const CCoinControl *coinControl=NULL)
SendCoinsReturn sendCoins (WalletModelTransaction &transaction)
bool setWalletEncrypted (bool encrypted, const SecureString &passphrase)
bool setWalletLocked (bool locked, const SecureString &passPhrase=SecureString(), bool fMixing=false)
bool changePassphrase (const SecureString &oldPass, const SecureString &newPass)
bool backupWallet (const QString &filename)
UnlockContext requestUnlock (bool fForMixingOnly=false)
bool getPubKey (const CKeyID &address, CPubKey &vchPubKeyOut) const
bool havePrivKey (const CKeyID &address) const
void getOutputs (const std::vector< COutPoint > &vOutpoints, std::vector< COutput > &vOutputs)
bool isSpent (const COutPoint &outpoint) const
void listCoins (std::map< QString, std::vector< COutput > > &mapCoins) const
bool isLockedCoin (uint256 hash, unsigned int n) const
void lockCoin (COutPoint &output)
void unlockCoin (COutPoint &output)
void listLockedCoins (std::vector< COutPoint > &vOutpts)
void loadReceiveRequests (std::vector< std::string > &vReceiveRequests)
bool saveReceiveRequest (const std::string &sAddress, const int64_t nId, const std::string &sRequest)
bool transactionCanBeAbandoned (uint256 hash) const
bool abandonTransaction (uint256 hash) const
bool hdEnabled () const
Private Member Functions
void subscribeToCoreSignals ()
void unsubscribeFromCoreSignals ()
void checkBalanceChanged ()
Private Attributes
CWallet * wallet
bool fHaveWatchOnly
bool fForceCheckBalanceChanged
OptionsModel * optionsModel
AddressTableModel * addressTableModel
TransactionTableModel * transactionTableModel
RecentRequestsTableModel * recentRequestsTableModel
CAmount cachedBalance
CAmount cachedUnconfirmedBalance
CAmount cachedImmatureBalance
CAmount cachedAnonymizedBalance
CAmount cachedWatchOnlyBalance
CAmount cachedWatchUnconfBalance
CAmount cachedWatchImmatureBalance
EncryptionStatus cachedEncryptionStatus
int cachedNumBlocks
int cachedTxLocks
int cachedPrivateSendRounds
QTimer * pollTimer
Detailed Description
Interface to Bitcoin wallet from Qt view code.
Definition at line 106 of file walletmodel.h.
Member Enumeration Documentation
EncryptionStatus
enum WalletModel::EncryptionStatus
Enumerator
Unencrypted
Locked
UnlockedForMixingOnly
Unlocked
Definition at line 128 of file walletmodel.h.
StatusCode
enum WalletModel::StatusCode
Enumerator
OK
InvalidAmount
InvalidAddress
AmountExceedsBalance
AmountWithFeeExceedsBalance
DuplicateAddress
TransactionCreationFailed
TransactionCommitFailed
AbsurdFee
PaymentRequestExpired
Definition at line 114 of file walletmodel.h.
Constructor & Destructor Documentation
WalletModel()
WalletModel::WalletModel (const PlatformStyle * platformStyle, CWallet * wallet, OptionsModel * optionsModel, QObject * parent = 0) explicit
Definition at line 37 of file walletmodel.cpp.
References addressTableModel, fForceCheckBalanceChanged, fHaveWatchOnly, CBasicKeyStore::HaveWatchOnly(), MODEL_UPDATE_DELAY, pollBalanceChanged(), pollTimer, recentRequestsTableModel, subscribeToCoreSignals(), transactionTableModel, and wallet.
~WalletModel()
WalletModel::~WalletModel ()
Definition at line 68 of file walletmodel.cpp.
References unsubscribeFromCoreSignals().
Member Function Documentation
abandonTransaction()
bool WalletModel::abandonTransaction (uint256 hash) const
Definition at line 757 of file walletmodel.cpp.
References CWallet::AbandonTransaction(), cs_main, CWallet::cs_wallet, LOCK2, and wallet.
Referenced by TransactionView::abandonTx().
backupWallet()
bool WalletModel::backupWallet (const QString & filename)
Definition at line 506 of file walletmodel.cpp.
References BackupWallet(), and wallet.
Referenced by WalletView::backupWallet().
balanceChanged
void WalletModel::balanceChanged (const CAmount & balance, const CAmount & unconfirmedBalance, const CAmount & immatureBalance, const CAmount & anonymizedBalance, const CAmount & watchOnlyBalance, const CAmount & watchUnconfBalance, const CAmount & watchImmatureBalance) signal
Referenced by checkBalanceChanged().
changePassphrase()
bool WalletModel::changePassphrase (const SecureString & oldPass, const SecureString & newPass)
Definition at line 495 of file walletmodel.cpp.
References CWallet::ChangeWalletPassphrase(), CWallet::cs_wallet, LOCK, CCryptoKeyStore::Lock(), and wallet.
Referenced by AskPassphraseDialog::accept().
checkBalanceChanged()
void WalletModel::checkBalanceChanged () private
Definition at line 160 of file walletmodel.cpp.
References balanceChanged(), cachedAnonymizedBalance, cachedBalance, cachedImmatureBalance, cachedTxLocks, cachedUnconfirmedBalance, cachedWatchImmatureBalance, cachedWatchOnlyBalance, cachedWatchUnconfBalance, getAnonymizedBalance(), getBalance(), getImmatureBalance(), getUnconfirmedBalance(), getWatchBalance(), getWatchImmatureBalance(), getWatchUnconfirmedBalance(), haveWatchOnly(), and nCompleteTXLocks.
Referenced by pollBalanceChanged(), and sendCoins().
coinsSent
void WalletModel::coinsSent (CWallet * wallet, SendCoinsRecipient recipient, QByteArray transaction) signal
Referenced by sendCoins().
encryptionStatusChanged
void WalletModel::encryptionStatusChanged (int status) signal
Referenced by updateStatus().
getAddressTableModel()
AddressTableModel * WalletModel::getAddressTableModel ()
Definition at line 432 of file walletmodel.cpp.
References addressTableModel.
Referenced by TransactionTableModel::addressColor(), SendCoinsDialog::coinControlChangeEdited(), TransactionTableModel::data(), TransactionView::editLabel(), TransactionTableModel::lookupAddress(), SendCoinsEntry::on_addressBookButton_clicked(), SignVerifyMessageDialog::on_addressBookButton_SM_clicked(), SignVerifyMessageDialog::on_addressBookButton_VM_clicked(), ReceiveCoinsDialog::on_receiveButton_clicked(), CoinControlDialog::setModel(), WalletView::setWalletModel(), SendCoinsEntry::updateLabel(), and CoinControlDialog::updateView().
getAnonymizedBalance()
CAmount WalletModel::getAnonymizedBalance () const
Definition at line 91 of file walletmodel.cpp.
References CWallet::GetAnonymizedBalance(), and wallet.
Referenced by checkBalanceChanged(), SendCoinsDialog::setModel(), OverviewPage::setWalletModel(), and SendCoinsDialog::updateDisplayUnit().
getBalance()
CAmount WalletModel::getBalance (const CCoinControl * coinControl = NULL) const
Definition at line 73 of file walletmodel.cpp.
References CWallet::AvailableCoins(), COutput::fSpendable, CWallet::GetBalance(), COutput::i, COutput::tx, vCoins, CTransaction::vout, and wallet.
Referenced by checkBalanceChanged(), prepareTransaction(), SendCoinsDialog::setModel(), OverviewPage::setWalletModel(), and SendCoinsDialog::updateDisplayUnit().
getEncryptionStatus()
WalletModel::EncryptionStatus WalletModel::getEncryptionStatus () const
Definition at line 447 of file walletmodel.cpp.
References CCryptoKeyStore::IsCrypted(), CCryptoKeyStore::IsLocked(), Locked, Unencrypted, Unlocked, UnlockedForMixingOnly, and wallet.
Referenced by SendCoinsDialog::on_sendButton_clicked(), MasternodeList::on_startAllButton_clicked(), MasternodeList::on_startButton_clicked(), MasternodeList::on_startMissingButton_clicked(), requestUnlock(), OverviewPage::togglePrivateSend(), WalletView::unlockWallet(), WalletView::updateEncryptionStatus(), and updateStatus().
getImmatureBalance()
CAmount WalletModel::getImmatureBalance () const
Definition at line 101 of file walletmodel.cpp.
References CWallet::GetImmatureBalance(), and wallet.
Referenced by checkBalanceChanged(), SendCoinsDialog::setModel(), OverviewPage::setWalletModel(), and SendCoinsDialog::updateDisplayUnit().
getOptionsModel()
OptionsModel * WalletModel::getOptionsModel ()
Definition at line 427 of file walletmodel.cpp.
References optionsModel.
Referenced by TransactionView::changedAmount(), DarksendConfig::clickBasic(), DarksendConfig::clickHigh(), DarksendConfig::clickMax(), SendCoinsDialog::coinControlUpdateLabels(), TransactionView::computeSum(), TransactionTableModel::data(), RecentRequestsTableModel::data(), TransactionView::exportClicked(), TransactionTableModel::formatTxAmount(), RecentRequestsTableModel::getAmountTitle(), ReceiveCoinsDialog::on_receiveButton_clicked(), ReceiveCoinsDialog::on_recentRequestsView_doubleClicked(), SendCoinsDialog::on_sendButton_clicked(), WalletView::processNewTransaction(), SendCoinsDialog::processSendCoinsReturn(), RecentRequestsTableModel::RecentRequestsTableModel(), SendCoinsDialog::send(), SendCoinsDialog::setBalance(), SendCoinsEntry::setModel(), TransactionView::setModel(), CoinControlDialog::setModel(), SendCoinsDialog::setModel(), ReceiveCoinsDialog::setModel(), OverviewPage::SetupTransactionList(), OverviewPage::setWalletModel(), TransactionTableModel::TransactionTableModel(), TransactionTableModel::updateAmountColumnTitle(), SendCoinsEntry::updateDisplayUnit(), ReceiveCoinsDialog::updateDisplayUnit(), OverviewPage::updateDisplayUnit(), SendCoinsDialog::updateDisplayUnit(), SendCoinsDialog::updateFeeMinimizedLabel(), CoinControlDialog::updateLabels(), SendCoinsDialog::updateMinFeeLabel(), SendCoinsDialog::updateSmartFeeLabel(), and CoinControlDialog::updateView().
getOutputs()
void WalletModel::getOutputs (const std::vector< COutPoint > & vOutpoints, std::vector< COutput > & vOutputs)
Definition at line 643 of file walletmodel.cpp.
References cs_main, CWallet::cs_wallet, COutPoint::hash, LOCK2, CWallet::mapWallet, COutPoint::n, and wallet.
Referenced by CoinControlDialog::updateLabels().
getPubKey()
bool WalletModel::getPubKey (const CKeyID & address, CPubKey & vchPubKeyOut) const
Definition at line 632 of file walletmodel.cpp.
References CWallet::GetPubKey(), and wallet.
Referenced by CoinControlDialog::updateLabels().
getRecentRequestsTableModel()
RecentRequestsTableModel * WalletModel::getRecentRequestsTableModel ()
Definition at line 442 of file walletmodel.cpp.
References recentRequestsTableModel.
Referenced by ReceiveCoinsDialog::copyColumnToClipboard(), ReceiveCoinsDialog::copyURI(), ReceiveCoinsDialog::on_receiveButton_clicked(), ReceiveCoinsDialog::on_recentRequestsView_doubleClicked(), ReceiveCoinsDialog::on_removeRequestButton_clicked(), ReceiveCoinsDialog::on_showRequestButton_clicked(), ReceiveCoinsDialog::selectedRow(), and ReceiveCoinsDialog::setModel().
getTransactionTableModel()
TransactionTableModel * WalletModel::getTransactionTableModel ()
Definition at line 437 of file walletmodel.cpp.
References transactionTableModel.
Referenced by TransactionView::abandonTx(), WalletView::processNewTransaction(), TransactionView::setModel(), OverviewPage::SetupTransactionList(), and WalletView::setWalletModel().
getUnconfirmedBalance()
CAmount WalletModel::getUnconfirmedBalance () const
Definition at line 96 of file walletmodel.cpp.
References CWallet::GetUnconfirmedBalance(), and wallet.
Referenced by checkBalanceChanged(), SendCoinsDialog::setModel(), OverviewPage::setWalletModel(), and SendCoinsDialog::updateDisplayUnit().
getWatchBalance()
CAmount WalletModel::getWatchBalance () const
Definition at line 111 of file walletmodel.cpp.
References CWallet::GetWatchOnlyBalance(), and wallet.
Referenced by checkBalanceChanged(), SendCoinsDialog::setModel(), OverviewPage::setWalletModel(), and SendCoinsDialog::updateDisplayUnit().
getWatchImmatureBalance()
CAmount WalletModel::getWatchImmatureBalance () const
Definition at line 121 of file walletmodel.cpp.
References CWallet::GetImmatureWatchOnlyBalance(), and wallet.
Referenced by checkBalanceChanged(), SendCoinsDialog::setModel(), OverviewPage::setWalletModel(), and SendCoinsDialog::updateDisplayUnit().
getWatchUnconfirmedBalance()
CAmount WalletModel::getWatchUnconfirmedBalance () const
Definition at line 116 of file walletmodel.cpp.
References CWallet::GetUnconfirmedWatchOnlyBalance(), and wallet.
Referenced by checkBalanceChanged(), SendCoinsDialog::setModel(), OverviewPage::setWalletModel(), and SendCoinsDialog::updateDisplayUnit().
havePrivKey()
bool WalletModel::havePrivKey (const CKeyID & address) const
Definition at line 637 of file walletmodel.cpp.
References CWallet::HaveKey(), and wallet.
Referenced by SendCoinsDialog::coinControlChangeEdited().
haveWatchOnly()
bool WalletModel::haveWatchOnly () const
Definition at line 106 of file walletmodel.cpp.
References fHaveWatchOnly.
Referenced by checkBalanceChanged(), TransactionView::exportClicked(), TransactionView::setModel(), and OverviewPage::setWalletModel().
hdEnabled()
bool WalletModel::hdEnabled () const
Definition at line 763 of file walletmodel.cpp.
References CWallet::IsHDEnabled(), and wallet.
Referenced by WalletView::setWalletModel().
isLockedCoin()
bool WalletModel::isLockedCoin (uint256 hash, unsigned int n) const
Definition at line 700 of file walletmodel.cpp.
References cs_main, CWallet::cs_wallet, CWallet::IsLockedCoin(), LOCK2, and wallet.
Referenced by CoinControlDialog::buttonToggleLockClicked(), CoinControlDialog::showMenu(), and CoinControlDialog::updateView().
isSpent()
bool WalletModel::isSpent (const COutPoint & outpoint) const
Definition at line 656 of file walletmodel.cpp.
References cs_main, CWallet::cs_wallet, COutPoint::hash, CWallet::IsSpent(), LOCK2, COutPoint::n, and wallet.
Referenced by CoinControlDialog::updateLabels().
listCoins()
void WalletModel::listCoins (std::map< QString, std::vector< COutput > > & mapCoins) const
Definition at line 663 of file walletmodel.cpp.
References CWallet::AvailableCoins(), cs_main, CWallet::cs_wallet, ExtractDestination(), COutput::fSpendable, COutPoint::hash, COutput::i, CWallet::IsChange(), CWallet::IsMine(), ISMINE_SPENDABLE, CWallet::ListLockedCoins(), LOCK2, CWallet::mapWallet, COutPoint::n, COutput::tx, vCoins, CTransaction::vin, CTransaction::vout, and wallet.
Referenced by CoinControlDialog::updateView().
listLockedCoins()
void WalletModel::listLockedCoins (std::vector< COutPoint > & vOutpts)
Definition at line 718 of file walletmodel.cpp.
References cs_main, CWallet::cs_wallet, CWallet::ListLockedCoins(), LOCK2, and wallet.
Referenced by CoinControlDialog::updateLabelLocked().
loadReceiveRequests()
void WalletModel::loadReceiveRequests (std::vector< std::string > & vReceiveRequests)
Definition at line 724 of file walletmodel.cpp.
References CWallet::cs_wallet, CAddressBookData::destdata, LOCK, CWallet::mapAddressBook, PAIRTYPE, and wallet.
Referenced by RecentRequestsTableModel::RecentRequestsTableModel().
lockCoin()
void WalletModel::lockCoin (COutPoint & output)
Definition at line 706 of file walletmodel.cpp.
References cs_main, CWallet::cs_wallet, LOCK2, CWallet::LockCoin(), and wallet.
Referenced by CoinControlDialog::buttonToggleLockClicked(), and CoinControlDialog::lockCoin().
message
void WalletModel::message (const QString & title, const QString & message, unsigned int style) signal
Referenced by prepareTransaction().
notifyWatchonlyChanged
void WalletModel::notifyWatchonlyChanged (bool fHaveWatchonly) signal
Referenced by updateWatchOnlyFlag().
pollBalanceChanged
void WalletModel::pollBalanceChanged () slot
Definition at line 134 of file walletmodel.cpp.
References cachedNumBlocks, cachedPrivateSendRounds, cachedTxLocks, chainActive, checkBalanceChanged(), cs_main, CWallet::cs_wallet, fForceCheckBalanceChanged, CChain::Height(), nCompleteTXLocks, CPrivateSendClient::nPrivateSendRounds, privateSendClient, transactionTableModel, TRY_LOCK, TransactionTableModel::updateConfirmations(), and wallet.
Referenced by WalletModel().
prepareTransaction()
WalletModel::SendCoinsReturn WalletModel::prepareTransaction (WalletModelTransaction & transaction, const CCoinControl * coinControl = NULL)
Definition at line 218 of file walletmodel.cpp.
References AbsurdFee, SendCoinsRecipient::address, SendCoinsRecipient::amount, AmountExceedsBalance, AmountWithFeeExceedsBalance, COIN, CWallet::CreateTransaction(), cs_main, CWallet::cs_wallet, DuplicateAddress, SendCoinsRecipient::fSubtractFeeFromAmount, getBalance(), PaymentRequestPlus::getDetails(), WalletModelTransaction::getPossibleKeyChange(), WalletModelTransaction::getRecipients(), GetScriptForDestination(), CSporkManager::GetSporkValue(), WalletModelTransaction::getTransaction(), CTransaction::GetValueOut(), InvalidAddress, InvalidAmount, PaymentRequestPlus::IsInitialized(), CCryptoKeyStore::IsLocked(), LOCK2, maxTxFee, message(), CClientUIInterface::MSG_ERROR, CClientUIInterface::MSG_WARNING, WalletModelTransaction::newPossibleKeyChange(), OK, SendCoinsRecipient::paymentRequest, WalletModelTransaction::reassignAmounts(), WalletModelTransaction::setTransactionFee(), SPORK_5_INSTANTSEND_MAX_VALUE, sporkManager, TransactionCreationFailed, validateAddress(), CTransaction::vin, wallet, and CTxLockRequest::WARN_MANY_INPUTS.
Referenced by SendCoinsDialog::send().
requestUnlock()
WalletModel::UnlockContext WalletModel::requestUnlock (bool fForMixingOnly = false)
Definition at line 578 of file walletmodel.cpp.
References getEncryptionStatus(), Locked, requireUnlock(), Unlocked, and UnlockedForMixingOnly.
Referenced by AddressTableModel::addRow(), SendCoinsDialog::on_sendButton_clicked(), SignVerifyMessageDialog::on_signMessageButton_SM_clicked(), MasternodeList::on_startAllButton_clicked(), MasternodeList::on_startButton_clicked(), MasternodeList::on_startMissingButton_clicked(), and OverviewPage::togglePrivateSend().
requireUnlock
void WalletModel::requireUnlock (bool fForMixingOnly = false) signal
Referenced by requestUnlock().
saveReceiveRequest()
bool WalletModel::saveReceiveRequest (const std::string & sAddress, const int64_t nId, const std::string & sRequest)
Definition at line 733 of file walletmodel.cpp.
References CWallet::AddDestData(), CWallet::cs_wallet, CWallet::EraseDestData(), CBitcoinAddress::Get(), LOCK, and wallet.
Referenced by RecentRequestsTableModel::addNewRequest(), and RecentRequestsTableModel::removeRows().
sendCoins()
WalletModel::SendCoinsReturn WalletModel::sendCoins (WalletModelTransaction & transaction)
Definition at line 353 of file walletmodel.cpp.
References SendCoinsRecipient::address, checkBalanceChanged(), coinsSent(), CWallet::CommitTransaction(), cs_main, CWallet::cs_wallet, g_connman, CBitcoinAddress::Get(), PaymentRequestPlus::getDetails(), WalletModelTransaction::getPossibleKeyChange(), WalletModelTransaction::getRecipients(), WalletModelTransaction::getTransaction(), PaymentRequestPlus::IsInitialized(), SendCoinsRecipient::label, LOCK, LOCK2, CWallet::mapAddressBook, SendCoinsRecipient::message, OK, SendCoinsRecipient::paymentRequest, PaymentRequestExpired, PROTOCOL_VERSION, SER_NETWORK, PaymentRequestPlus::SerializeToString(), CWallet::SetAddressBook(), CDataStream::size(), TransactionCommitFailed, NetMsgType::TX, NetMsgType::TXLOCKREQUEST, PaymentServer::verifyExpired(), CWalletTx::vOrderForm, and wallet.
Referenced by SendCoinsDialog::send().
setWalletEncrypted()
bool WalletModel::setWalletEncrypted (bool encrypted, const SecureString & passphrase)
Definition at line 467 of file walletmodel.cpp.
References CWallet::EncryptWallet(), and wallet.
Referenced by AskPassphraseDialog::accept().
setWalletLocked()
bool WalletModel::setWalletLocked (bool locked, const SecureString & passPhrase = SecureString(), bool fMixing = false)
Definition at line 481 of file walletmodel.cpp.
References CCryptoKeyStore::Lock(), CWallet::Unlock(), and wallet.
Referenced by AskPassphraseDialog::accept(), and WalletView::lockWallet().
showProgress
void WalletModel::showProgress (const QString & title, int nProgress) signal
subscribeToCoreSignals()
void WalletModel::subscribeToCoreSignals () private
Definition at line 557 of file walletmodel.cpp.
References NotifyAddressBookChanged(), CWallet::NotifyAddressBookChanged, NotifyKeyStoreStatusChanged(), CCryptoKeyStore::NotifyStatusChanged, NotifyTransactionChanged(), CWallet::NotifyTransactionChanged, NotifyWatchonlyChanged(), CWallet::NotifyWatchonlyChanged, ShowProgress(), CWallet::ShowProgress, and wallet.
Referenced by WalletModel().
transactionCanBeAbandoned()
bool WalletModel::transactionCanBeAbandoned (uint256 hash) const
Definition at line 748 of file walletmodel.cpp.
References cs_main, CWallet::cs_wallet, CMerkleTx::GetDepthInMainChain(), CWallet::GetWalletTx(), CWalletTx::InMempool(), CMerkleTx::isAbandoned(), LOCK2, and wallet.
Referenced by TransactionView::contextualMenu().
unlockCoin()
void WalletModel::unlockCoin (COutPoint & output)
Definition at line 712 of file walletmodel.cpp.
References cs_main, CWallet::cs_wallet, LOCK2, CWallet::UnlockCoin(), and wallet.
Referenced by CoinControlDialog::buttonToggleLockClicked(), and CoinControlDialog::unlockCoin().
unsubscribeFromCoreSignals()
void WalletModel::unsubscribeFromCoreSignals () private
Definition at line 567 of file walletmodel.cpp.
References NotifyAddressBookChanged(), CWallet::NotifyAddressBookChanged, NotifyKeyStoreStatusChanged(), CCryptoKeyStore::NotifyStatusChanged, NotifyTransactionChanged(), CWallet::NotifyTransactionChanged, NotifyWatchonlyChanged(), CWallet::NotifyWatchonlyChanged, ShowProgress(), CWallet::ShowProgress, and wallet.
Referenced by ~WalletModel().
updateAddressBook
void WalletModel::updateAddressBook (const QString & address, const QString & label, bool isMine, const QString & purpose, int status) slot
Definition at line 199 of file walletmodel.cpp.
References addressTableModel, and AddressTableModel::updateEntry().
updateStatus
void WalletModel::updateStatus () slot
Definition at line 126 of file walletmodel.cpp.
References cachedEncryptionStatus, encryptionStatusChanged(), and getEncryptionStatus().
updateTransaction
void WalletModel::updateTransaction () slot
Definition at line 193 of file walletmodel.cpp.
References fForceCheckBalanceChanged.
updateWatchOnlyFlag
void WalletModel::updateWatchOnlyFlag (bool fHaveWatchonly) slot
Definition at line 206 of file walletmodel.cpp.
References fHaveWatchOnly, and notifyWatchonlyChanged().
validateAddress()
bool WalletModel::validateAddress (const QString & address)
Definition at line 212 of file walletmodel.cpp.
References CBitcoinAddress::IsValid().
Referenced by AddressTableModel::addRow(), prepareTransaction(), and SendCoinsEntry::validate().
Member Data Documentation
addressTableModel
AddressTableModel* WalletModel::addressTableModel private
Definition at line 228 of file walletmodel.h.
Referenced by getAddressTableModel(), updateAddressBook(), and WalletModel().
cachedAnonymizedBalance
CAmount WalletModel::cachedAnonymizedBalance private
Definition at line 236 of file walletmodel.h.
Referenced by checkBalanceChanged().
cachedBalance
CAmount WalletModel::cachedBalance private
Definition at line 233 of file walletmodel.h.
Referenced by checkBalanceChanged().
cachedEncryptionStatus
EncryptionStatus WalletModel::cachedEncryptionStatus private
Definition at line 240 of file walletmodel.h.
Referenced by updateStatus().
cachedImmatureBalance
CAmount WalletModel::cachedImmatureBalance private
Definition at line 235 of file walletmodel.h.
Referenced by checkBalanceChanged().
cachedNumBlocks
int WalletModel::cachedNumBlocks private
Definition at line 241 of file walletmodel.h.
Referenced by pollBalanceChanged().
cachedPrivateSendRounds
int WalletModel::cachedPrivateSendRounds private
Definition at line 243 of file walletmodel.h.
Referenced by pollBalanceChanged().
cachedTxLocks
int WalletModel::cachedTxLocks private
Definition at line 242 of file walletmodel.h.
Referenced by checkBalanceChanged(), and pollBalanceChanged().
cachedUnconfirmedBalance
CAmount WalletModel::cachedUnconfirmedBalance private
Definition at line 234 of file walletmodel.h.
Referenced by checkBalanceChanged().
cachedWatchImmatureBalance
CAmount WalletModel::cachedWatchImmatureBalance private
Definition at line 239 of file walletmodel.h.
Referenced by checkBalanceChanged().
cachedWatchOnlyBalance
CAmount WalletModel::cachedWatchOnlyBalance private
Definition at line 237 of file walletmodel.h.
Referenced by checkBalanceChanged().
cachedWatchUnconfBalance
CAmount WalletModel::cachedWatchUnconfBalance private
Definition at line 238 of file walletmodel.h.
Referenced by checkBalanceChanged().
fForceCheckBalanceChanged
bool WalletModel::fForceCheckBalanceChanged private
Definition at line 222 of file walletmodel.h.
Referenced by pollBalanceChanged(), updateTransaction(), and WalletModel().
fHaveWatchOnly
bool WalletModel::fHaveWatchOnly private
Definition at line 221 of file walletmodel.h.
Referenced by haveWatchOnly(), updateWatchOnlyFlag(), and WalletModel().
optionsModel
OptionsModel* WalletModel::optionsModel private
Definition at line 226 of file walletmodel.h.
Referenced by getOptionsModel().
pollTimer
QTimer* WalletModel::pollTimer private
Definition at line 245 of file walletmodel.h.
Referenced by WalletModel().
recentRequestsTableModel
RecentRequestsTableModel* WalletModel::recentRequestsTableModel private
Definition at line 230 of file walletmodel.h.
Referenced by getRecentRequestsTableModel(), and WalletModel().
transactionTableModel
TransactionTableModel* WalletModel::transactionTableModel private
Definition at line 229 of file walletmodel.h.
Referenced by getTransactionTableModel(), pollBalanceChanged(), and WalletModel().
wallet
CWallet* WalletModel::wallet private
Definition at line 220 of file walletmodel.h.
Referenced by abandonTransaction(), backupWallet(), changePassphrase(), getAnonymizedBalance(), getBalance(), getEncryptionStatus(), getImmatureBalance(), getOutputs(), getPubKey(), getUnconfirmedBalance(), getWatchBalance(), getWatchImmatureBalance(), getWatchUnconfirmedBalance(), havePrivKey(), hdEnabled(), isLockedCoin(), isSpent(), listCoins(), listLockedCoins(), loadReceiveRequests(), lockCoin(), pollBalanceChanged(), prepareTransaction(), saveReceiveRequest(), sendCoins(), setWalletEncrypted(), setWalletLocked(), subscribeToCoreSignals(), transactionCanBeAbandoned(), unlockCoin(), unsubscribeFromCoreSignals(), WalletModel(), and WalletModel::UnlockContext::~UnlockContext().
The documentation for this class was generated from the following files:
src/qt/walletmodel.h
src/qt/walletmodel.cpp