Dash Core: CBitcoinLevelDBLogger Class Reference
CBitcoinLevelDBLogger Class Reference
Public Member Functions
virtual void Logv (const char *format, va_list ap) override
Detailed Description
Definition at line 19 of file dbwrapper.cpp.
Member Function Documentation
Logv()
virtual void CBitcoinLevelDBLogger::Logv (const char * format, va_list ap) inline override virtual
Definition at line 23 of file dbwrapper.cpp.
References base, tinyformat::detail::format(), LogAcceptCategory(), and LogPrintStr().
The documentation for this class was generated from the following file:
src/dbwrapper.cpp