Dash Core: CTransaction Class Reference
CTransaction Class Reference
The basic transaction that is broadcasted on the network and contained in blocks.
#include <transaction.h>
Public Member Functions
CTransaction ()
Construct a CTransaction that qualifies as IsNull()
CTransaction (const CMutableTransaction &tx)
Convert a CMutableTransaction into a CTransaction.
CTransaction & operator= (const CTransaction &tx)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
bool IsNull () const
const uint256 & GetHash () const
CAmount GetValueOut () const
double ComputePriority (double dPriorityInputs, unsigned int nTxSize=0) const
unsigned int CalculateModifiedSize (unsigned int nTxSize=0) const
unsigned int GetTotalSize () const
Get the total transaction size in bytes, including witness data.
bool IsCoinBase () const
std::string ToString () const
Public Attributes
const int32_t nVersion
const std::vector< CTxIn > vin
const std::vector< CTxOut > vout
const uint32_t nLockTime
ADD_SERIALIZE_METHODS
Static Public Attributes
static const int32_t CURRENT_VERSION =1
static const int32_t MAX_STANDARD_VERSION =2
Private Member Functions
void UpdateHash () const
Private Attributes
const uint256 hash
Memory only.
Friends
bool operator== (const CTransaction &a, const CTransaction &b)
bool operator!= (const CTransaction &a, const CTransaction &b)
Detailed Description
The basic transaction that is broadcasted on the network and contained in blocks.
A transaction can contain multiple inputs and outputs.
Definition at line 209 of file transaction.h.
Constructor & Destructor Documentation
CTransaction() [1/2]
CTransaction::CTransaction ()
Construct a CTransaction that qualifies as IsNull()
Definition at line 97 of file transaction.cpp.
CTransaction() [2/2]
CTransaction::CTransaction (const CMutableTransaction & tx)
Convert a CMutableTransaction into a CTransaction.
Definition at line 99 of file transaction.cpp.
References UpdateHash().
Member Function Documentation
CalculateModifiedSize()
unsigned int CTransaction::CalculateModifiedSize (unsigned int nTxSize = 0) const
Definition at line 132 of file transaction.cpp.
References GetSerializeSize(), PROTOCOL_VERSION, SER_NETWORK, and vin.
Referenced by ComputePriority(), and CTxMemPoolEntry::CTxMemPoolEntry().
ComputePriority()
double CTransaction::ComputePriority (double dPriorityInputs, unsigned int nTxSize = 0) const
Definition at line 124 of file transaction.cpp.
References CalculateModifiedSize().
Referenced by CWallet::CreateTransaction(), and CCoinsViewCache::GetPriority().
GetHash()
const uint256& CTransaction::GetHash () const inline
Definition at line 261 of file transaction.h.
References hash.
Referenced by CInstantSend::AcceptLockRequest(), AcceptToMemoryPool(), AcceptToMemoryPoolWorker(), CTxMemPool::addAddressIndex(), AddCoins(), CPrivateSend::AddDSTX(), CTxMemPool::addSpentIndex(), CWallet::AddToWallet(), CWallet::AddToWalletIfInvolvingMe(), AppInit2(), blockToJSON(), CheckBlock(), CDarksendBroadcastTx::CheckSignature(), CPrivateSendServer::CommitFinalTransaction(), CWallet::CommitTransaction(), ConnectBlock(), CWallet::CountInputsWithAmount(), CPrivateSendClient::CreateDenominated(), CreateNewBlock(), CInstantSend::CreateTxLockCandidate(), TransactionRecord::decomposeTransaction(), DisconnectBlock(), DisconnectTip(), TransactionDesc::FormatTxStatus(), getblocktemplate(), CWallet::GetCollateralTxDSIn(), CTxLockCandidate::GetHash(), CWallet::GetMasternodeOutpointAndKeys(), CWallet::GetOutpointAndKeysFromOutput(), GetTransaction(), gettxoutproof(), gobject(), CInstantSend::IsEnoughOrphanVotesForTx(), IsRBFOptIn(), CBloomFilter::IsRelevantAndUpdate(), CTxLockRequest::IsValid(), ListReceived(), listunspent(), CPrivateSendClient::MakeCollateralAmounts(), masternode(), mempoolToJSON(), CZMQPublishHashTransactionNotifier::NotifyTransaction(), CZMQPublishRawTransactionNotifier::NotifyTransaction(), CZMQPublishHashTransactionLockNotifier::NotifyTransactionLock(), CZMQPublishRawTransactionLockNotifier::NotifyTransactionLock(), mempoolentry_txid::operator()(), CompareTxMemPoolEntryByScore::operator()(), OutputTxHash(), ProcessMessage(), CBlockPolicyEstimator::processTransaction(), CInstantSend::ProcessTxLockRequest(), CWallet::ReacceptWalletTransactions(), CInstantSend::RejectLockRequest(), CConnman::RelayTransaction(), CTxMemPool::remove(), CTxMemPool::removeConflicts(), CTxMemPool::removeForBlock(), CWalletDB::ReorderTransactions(), CWallet::ResendWalletTransactionsBefore(), CWallet::SelectCoins(), CWallet::SelectCoinsByDenominations(), CWallet::SelectCoinsDark(), sendfrom(), sendmany(), sendrawtransaction(), CDarksendBroadcastTx::Sign(), CPrivateSendClient::SignFinalTransaction(), CInstantSend::SyncTransaction(), CPrivateSend::SyncTransaction(), TransactionDesc::toHTML(), ToString(), CInstantSend::TryToFinalizeLockCandidate(), TxToJSON(), TxToUniv(), CoinControlDialog::updateLabels(), CoinControlDialog::updateView(), and WalletTxToJSON().
GetTotalSize()
unsigned int CTransaction::GetTotalSize () const
Get the total transaction size in bytes, including witness data.
"Total Size" defined in BIP141 and BIP144.
Returns
Total transaction size in bytes
Definition at line 150 of file transaction.cpp.
References GetSerializeSize(), PROTOCOL_VERSION, and SER_NETWORK.
Referenced by TransactionDesc::toHTML().
GetValueOut()
CAmount CTransaction::GetValueOut () const
Definition at line 112 of file transaction.cpp.
References MoneyRange(), and vout.
Referenced by AcceptToMemoryPoolWorker(), Consensus::CheckTxInputs(), ConnectBlock(), CTxMemPoolEntry::CTxMemPoolEntry(), TransactionRecord::decomposeTransaction(), gettransaction(), CMasternodeBlockPayees::IsTransactionValid(), CTxLockRequest::IsValid(), CSuperblock::IsValid(), WalletModel::prepareTransaction(), and TransactionDesc::toHTML().
IsCoinBase()
bool CTransaction::IsCoinBase () const inline
Definition at line 283 of file transaction.h.
References vin.
Referenced by AcceptToMemoryPoolWorker(), AddCoins(), AreInputsStandard(), CWallet::AvailableCoins(), CheckBlock(), CheckInputs(), CheckTransaction(), ConnectBlock(), TransactionRecord::decomposeTransaction(), DisconnectBlock(), DisconnectTip(), CWallet::GetAddressBalances(), getblocktemplate(), GetP2SHSigOpCount(), CCoinsViewCache::GetPriority(), getreceivedbyaccount(), getreceivedbyaddress(), CCoinsViewCache::GetValueIn(), CCoinsViewCache::HaveInputs(), ListReceived(), ListTransactions(), CWallet::ReacceptWalletTransactions(), CWallet::SelectCoinsGrouppedByAddresses(), TransactionRecord::showTransaction(), CInstantSend::SyncTransaction(), CPrivateSend::SyncTransaction(), TransactionDesc::toHTML(), TxToJSON(), TxToUniv(), UpdateCoins(), TransactionRecord::updateStatus(), and WalletTxToJSON().
IsNull()
bool CTransaction::IsNull () const inline
Definition at line 257 of file transaction.h.
References vin, and vout.
operator=()
CTransaction & CTransaction::operator= (const CTransaction & tx)
Definition at line 103 of file transaction.cpp.
References hash, nLockTime, nVersion, vin, and vout.
SerializationOp()
template<typename Stream , typename Operation > void CTransaction::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 247 of file transaction.h.
References nLockTime, nVersion, READWRITE, UpdateHash(), vin, and vout.
ToString()
std::string CTransaction::ToString () const
Definition at line 155 of file transaction.cpp.
References GetHash(), nLockTime, nVersion, strprintf, vin, and vout.
Referenced by CPrivateSendServer::ChargeRandomFees(), CPrivateSendServer::CommitFinalTransaction(), CWallet::CommitTransaction(), IsBlockPayeeValid(), CGovernanceObject::IsCollateralValid(), CPrivateSend::IsCollateralValid(), CTxLockRequest::IsValid(), and TransactionDesc::toHTML().
UpdateHash()
void CTransaction::UpdateHash () const private
Definition at line 92 of file transaction.cpp.
References hash, and SerializeHash().
Referenced by CTransaction(), and SerializationOp().
Friends And Related Function Documentation
operator!=
bool operator!= (const CTransaction & a, const CTransaction & b) friend
Definition at line 293 of file transaction.h.
operator==
bool operator== (const CTransaction & a, const CTransaction & b) friend
Definition at line 288 of file transaction.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CTransaction::ADD_SERIALIZE_METHODS
Definition at line 244 of file transaction.h.
CURRENT_VERSION
const int32_t CTransaction::CURRENT_VERSION =1 static
Definition at line 218 of file transaction.h.
Referenced by AddOrphanTx(), IsStandardTx(), and MutateTxVersion().
hash
const uint256 CTransaction::hash private
Memory only.
Definition at line 213 of file transaction.h.
Referenced by GetHash(), operator=(), and UpdateHash().
MAX_STANDARD_VERSION
const int32_t CTransaction::MAX_STANDARD_VERSION =2 static
Definition at line 224 of file transaction.h.
Referenced by IsStandardTx().
nLockTime
const uint32_t CTransaction::nLockTime
Definition at line 234 of file transaction.h.
Referenced by TransactionSignatureChecker::CheckLockTime(), TransactionDesc::FormatTxStatus(), CPrivateSend::IsCollateralValid(), IsFinalTx(), operator=(), SerializationOp(), ToString(), TxToJSON(), TxToUniv(), and TransactionRecord::updateStatus().
nVersion
const int32_t CTransaction::nVersion
Definition at line 231 of file transaction.h.
Referenced by AcceptToMemoryPoolWorker(), CalculateSequenceLocks(), TransactionSignatureChecker::CheckSequence(), IsStandardTx(), operator=(), CMerkleTx::SerializationOp(), SerializationOp(), ToString(), TxToJSON(), and TxToUniv().
vin
const std::vector<CTxIn> CTransaction::vin
Definition at line 232 of file transaction.h.
Referenced by AcceptToMemoryPoolWorker(), CTxMemPool::addAddressIndex(), CTxMemPool::addSpentIndex(), CWallet::AddToWallet(), CWallet::AddToWalletIfInvolvingMe(), CTxMemPool::addUnchecked(), AreInputsStandard(), CTxMemPool::CalculateMemPoolAncestors(), CalculateModifiedSize(), CalculateSequenceLocks(), CTxMemPool::check(), CheckBlock(), CheckInputs(), TransactionSignatureChecker::CheckLockTime(), TransactionSignatureChecker::CheckSequence(), CheckSequenceLocks(), CheckTransaction(), Consensus::CheckTxInputs(), CWallet::CommitTransaction(), ConnectBlock(), CInstantSend::CreateTxLockCandidate(), TransactionRecord::decomposeTransaction(), DisconnectBlock(), CWallet::FundTransaction(), CWallet::GetAddressGroupings(), getblocktemplate(), CWallet::GetConflicts(), CWallet::GetDebit(), GetLegacySigOpCount(), CTxLockRequest::GetMaxSignatures(), CTxLockRequest::GetMinFee(), GetP2SHSigOpCount(), CCoinsViewCache::GetPriority(), CWallet::GetRealOutpointPrivateSendRounds(), CCoinsViewCache::GetValueIn(), CTxMemPool::HasNoInputsOf(), CCoinsViewCache::HaveInputs(), IsCoinBase(), CPrivateSend::IsCollateralValid(), CInstantSend::IsEnoughOrphanVotesForTx(), IsFinalTx(), IsNull(), CBloomFilter::IsRelevantAndUpdate(), IsStandardTx(), CTxLockRequest::IsValid(), WalletModel::listCoins(), mempoolToJSON(), MutateTxSign(), operator=(), WalletModel::prepareTransaction(), CInstantSend::ProcessTxLockRequest(), RecursiveDynamicUsage(), CTxMemPool::removeConflicts(), CTxMemPool::removeForReorg(), CInstantSend::ResolveConflicts(), SerializationOp(), SignalsOptInRBF(), SignatureHash(), CWallet::SyncTransaction(), TransactionDesc::toHTML(), ToString(), CTxMemPool::TrimToSize(), TxToJSON(), TxToUniv(), and UpdateCoins().
vout
const std::vector<CTxOut> CTransaction::vout
Definition at line 233 of file transaction.h.
Referenced by AcceptToMemoryPoolWorker(), CTxMemPool::addAddressIndex(), AddCoins(), CWallet::AddToWallet(), CWallet::AvailableCoins(), CTxMemPool::check(), CheckTransaction(), ConnectBlock(), CWallet::ConvertList(), CWallet::CountInputsWithAmount(), TransactionRecord::decomposeTransaction(), DisconnectBlock(), fundrawtransaction(), CWallet::FundTransaction(), GetAccountAddress(), CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), WalletModel::getBalance(), CWallet::GetChange(), CCoinsViewMemPool::GetCoin(), CWallet::GetCollateralTxDSIn(), CWallet::GetCredit(), CWallet::GetDebit(), CWallet::GetKeyBirthTimes(), GetLegacySigOpCount(), CWallet::GetOutpointAndKeysFromOutput(), CWallet::GetRealOutpointPrivateSendRounds(), getreceivedbyaccount(), getreceivedbyaddress(), GetValueOut(), CGovernanceObject::IsCollateralValid(), CPrivateSend::IsCollateralValid(), CWallet::IsDenominated(), CWallet::IsMine(), IsNull(), CBloomFilter::IsRelevantAndUpdate(), IsStandardTx(), CMasternodeBlockPayees::IsTransactionValid(), CWalletTx::IsTrusted(), CTxLockRequest::IsValid(), CSuperblock::IsValid(), less_then_denom(), WalletModel::listCoins(), ListReceived(), listunspent(), operator=(), WalletModelTransaction::reassignAmounts(), RecursiveDynamicUsage(), CTxMemPool::remove(), CWallet::SelectCoins(), CWallet::SelectCoinsByDenominations(), CWallet::SelectCoinsDark(), CWallet::SelectCoinsGrouppedByAddresses(), CWallet::SelectCoinsMinConf(), sendrawtransaction(), SerializationOp(), SignatureHash(), SignSignature(), TransactionDesc::toHTML(), ToString(), TxToJSON(), TxToUniv(), CoinControlDialog::updateLabels(), and CoinControlDialog::updateView().
The documentation for this class was generated from the following files:
src/primitives/transaction.h
src/primitives/transaction.cpp