Dash Core: src/masternode-payments.cpp File Reference
masternode-payments.cpp File Reference
#include "activemasternode.h"
#include "governance-classes.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "masternodeman.h"
#include "messagesigner.h"
#include "netfulfilledman.h"
#include "spork.h"
#include "util.h"
#include <boost/lexical_cast.hpp>
Functions
bool IsBlockValueValid (const CBlock &block, int nBlockHeight, CAmount blockReward, std::string &strErrorRet)
IsBlockValueValid.
bool IsBlockPayeeValid (const CTransaction &txNew, int nBlockHeight, CAmount blockReward)
void FillBlockPayments (CMutableTransaction &txNew, int nBlockHeight, CAmount blockReward, CTxOut &txoutMasternodeRet, std::vector< CTxOut > &voutSuperblockRet)
std::string GetRequiredPaymentsString (int nBlockHeight)
Variables
CMasternodePayments mnpayments
Object for who's going to get paid on which blocks.
CCriticalSection cs_vecPayees
CCriticalSection cs_mapMasternodeBlocks
CCriticalSection cs_mapMasternodePaymentVotes
Function Documentation
FillBlockPayments()
void FillBlockPayments (CMutableTransaction & txNew, int nBlockHeight, CAmount blockReward, CTxOut & txoutMasternodeRet, std::vector< CTxOut > & voutSuperblockRet)
Definition at line 210 of file masternode-payments.cpp.
References CSuperblockManager::CreateSuperblock(), CMasternodePayments::FillBlockPayee(), CSporkManager::IsSporkActive(), CSuperblockManager::IsSuperblockTriggered(), LogPrint(), mnpayments, SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, CTxOut::ToString(), and CMutableTransaction::ToString().
Referenced by CreateNewBlock().
GetRequiredPaymentsString()
std::string GetRequiredPaymentsString (int nBlockHeight)
Definition at line 227 of file masternode-payments.cpp.
References CSuperblockManager::GetRequiredPaymentsString(), CMasternodePayments::GetRequiredPaymentsString(), CSuperblockManager::IsSuperblockTriggered(), and mnpayments.
Referenced by masternode().
IsBlockPayeeValid()
bool IsBlockPayeeValid (const CTransaction & txNew, int nBlockHeight, CAmount blockReward)
Definition at line 132 of file masternode-payments.cpp.
References fDebug, CChainParams::GetConsensus(), CSporkManager::IsSporkActive(), CSuperblockManager::IsSuperblockTriggered(), CMasternodeSync::IsSynced(), CMasternodePayments::IsTransactionValid(), CSuperblockManager::IsValid(), LogPrint(), LogPrintf, masternodeSync, mnpayments, Consensus::Params::nBudgetPaymentsCycleBlocks, Consensus::Params::nBudgetPaymentsStartBlock, Consensus::Params::nBudgetPaymentsWindowBlocks, Consensus::Params::nSuperblockStartBlock, Params(), SPORK_13_OLD_SUPERBLOCK_FLAG, SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT, SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, and CTransaction::ToString().
Referenced by ConnectBlock().
IsBlockValueValid()
bool IsBlockValueValid (const CBlock & block, int nBlockHeight, CAmount blockReward, std::string & strErrorRet)
IsBlockValueValid.
TODO: all 4 functions do not belong here really, they should be refactored/moved somewhere (main.cpp ?)
Determine if coinbase outgoing created money is the correct value
Why is this needed?
In Dash some blocks are superblocks, which output much higher amounts of coins
Otherblocks are 10% lower in outgoing value, so in total, no extra coins are created
When non-superblocks are detected, the normal schedule should be maintained
Definition at line 35 of file masternode-payments.cpp.
References fDebug, CChainParams::GetConsensus(), CSuperblock::GetPaymentsLimit(), CSporkManager::IsSporkActive(), CSuperblockManager::IsSuperblockTriggered(), CMasternodeSync::IsSynced(), CSuperblockManager::IsValid(), CSuperblock::IsValidBlockHeight(), LogPrint(), LogPrintf, masternodeSync, Consensus::Params::nBudgetPaymentsCycleBlocks, Params(), SPORK_13_OLD_SUPERBLOCK_FLAG, SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, strprintf, and CBlock::vtx.
Referenced by ConnectBlock().
Variable Documentation
cs_mapMasternodeBlocks
CCriticalSection cs_mapMasternodeBlocks
Definition at line 21 of file masternode-payments.cpp.
Referenced by CMasternodePayments::AddPaymentVote(), CMasternodePayments::CheckAndRemove(), CMasternodePayments::CheckPreviousBlockVotes(), CMasternodePayments::Clear(), CMasternodePayments::GetRequiredPaymentsString(), CMasternodePayments::IsScheduled(), CMasternodePayments::IsTransactionValid(), ProcessGetData(), CMasternodePayments::RequestLowDataPaymentBlocks(), CMasternodePayments::Sync(), and CMasternode::UpdateLastPaid().
cs_mapMasternodePaymentVotes
CCriticalSection cs_mapMasternodePaymentVotes
Definition at line 22 of file masternode-payments.cpp.
Referenced by CMasternodePayments::AddPaymentVote(), CMasternodePayments::CanVote(), CMasternodePayments::CheckAndRemove(), CMasternodePayments::CheckPreviousBlockVotes(), CMasternodePayments::Clear(), CMasternodePayments::HasVerifiedPaymentVote(), and CMasternodePayments::ProcessMessage().
cs_vecPayees
CCriticalSection cs_vecPayees
Definition at line 20 of file masternode-payments.cpp.
Referenced by CMasternodeBlockPayees::AddPayee(), CMasternodeBlockPayees::GetBestPayee(), CMasternodeBlockPayees::GetRequiredPaymentsString(), CMasternodeBlockPayees::HasPayeeWithVotes(), and CMasternodeBlockPayees::IsTransactionValid().
mnpayments
CMasternodePayments mnpayments
Object for who's going to get paid on which blocks.
Definition at line 18 of file masternode-payments.cpp.
Referenced by AlreadyHave(), AppInit2(), CMasternode::Check(), ComputeBlockVersion(), CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), CMasternodePayments::FillBlockPayee(), FillBlockPayments(), CMasternodeMan::FindRandomNotInVec(), getblocktemplate(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetRequiredPaymentsString(), IsBlockPayeeValid(), CMasternodePaymentVote::IsValid(), PrepareShutdown(), ProcessGetData(), ProcessMessage(), CMasternodeSync::ProcessTick(), CMasternodeBroadcast::SimpleCheck(), ThreadCheckPrivateSend(), CDSNotificationInterface::UpdatedBlockTip(), CMasternodeMan::UpdateLastPaid(), and CMasternode::UpdateLastPaid().