Dash Core: CAlert Class Reference
CAlert Class Reference
An alert is a combination of a serialized CUnsignedAlert and a signature.
#include <alert.h>
Public Member Functions
CAlert ()
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
void SetNull ()
bool IsNull () const
uint256 GetHash () const
bool IsInEffect () const
bool Cancels (const CAlert &alert) const
bool AppliesTo (int nVersion, const std::string &strSubVerIn) const
bool AppliesToMe () const
bool RelayTo (CNode *pnode, CConnman &connman) const
bool Sign ()
bool CheckSignature (const std::vector< unsigned char > &alertKey) const
bool ProcessAlert (const std::vector< unsigned char > &alertKey, bool fThread=true)
Public Member Functions inherited from CUnsignedAlert
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
void SetNull ()
std::string ToString () const
Static Public Member Functions
static void Notify (const std::string &strMessage, bool fThread)
static CAlert getAlertByHash (const uint256 &hash)
Public Attributes
std::vector< unsigned char > vchMsg
std::vector< unsigned char > vchSig
ADD_SERIALIZE_METHODS
Public Attributes inherited from CUnsignedAlert
int nVersion
int64_t nRelayUntil
int64_t nExpiration
int nID
int nCancel
std::set< int > setCancel
int nMinVer
int nMaxVer
std::set< std::string > setSubVer
int nPriority
std::string strComment
std::string strStatusBar
std::string strReserved
ADD_SERIALIZE_METHODS
Detailed Description
An alert is a combination of a serialized CUnsignedAlert and a signature.
Definition at line 77 of file alert.h.
Constructor & Destructor Documentation
CAlert()
CAlert::CAlert () inline
Definition at line 83 of file alert.h.
References SetNull().
Member Function Documentation
AppliesTo()
bool CAlert::AppliesTo (int nVersion, const std::string & strSubVerIn) const
Definition at line 115 of file alert.cpp.
AppliesToMe()
bool CAlert::AppliesToMe () const
Definition at line 123 of file alert.cpp.
References CLIENT_NAME, CLIENT_VERSION, FormatSubVersion(), and PROTOCOL_VERSION.
Referenced by GetWarnings().
Cancels()
bool CAlert::Cancels (const CAlert & alert) const
Definition at line 108 of file alert.cpp.
References CUnsignedAlert::nID.
Referenced by ProcessAlert().
CheckSignature()
bool CAlert::CheckSignature (const std::vector< unsigned char > & alertKey) const
Definition at line 170 of file alert.cpp.
References error(), Hash(), PROTOCOL_VERSION, SER_NETWORK, and CPubKey::Verify().
getAlertByHash()
CAlert CAlert::getAlertByHash (const uint256 & hash) static
Definition at line 182 of file alert.cpp.
References cs_mapAlerts, LOCK, and mapAlerts.
Referenced by ClientModel::updateAlert().
GetHash()
uint256 CAlert::GetHash () const
Definition at line 98 of file alert.cpp.
References Hash().
IsInEffect()
bool CAlert::IsInEffect () const
Definition at line 103 of file alert.cpp.
References GetAdjustedTime().
Referenced by ProcessAlert().
IsNull()
bool CAlert::IsNull () const
Definition at line 93 of file alert.cpp.
Referenced by ClientModel::updateAlert().
Notify()
void CAlert::Notify (const std::string & strMessage, bool fThread) static
Definition at line 271 of file alert.cpp.
References GetArg(), runCommand(), and SanitizeString().
Referenced by CheckForkWarningConditions(), and UpdateTip().
ProcessAlert()
bool CAlert::ProcessAlert (const std::vector< unsigned char > & alertKey, bool fThread = true)
Definition at line 194 of file alert.cpp.
References Cancels(), cs_mapAlerts, CT_DELETED, CT_NEW, IsInEffect(), LOCK, LogPrint(), mapAlerts, CUnsignedAlert::nID, CClientUIInterface::NotifyAlertChanged, PAIRTYPE, and uiInterface.
RelayTo()
bool CAlert::RelayTo (CNode * pnode, CConnman & connman) const
Definition at line 128 of file alert.cpp.
References NetMsgType::ALERT, GetAdjustedTime(), CNode::nVersion, CConnman::PushMessage(), CNode::setKnown, and CNode::strSubVer.
Referenced by ProcessMessage().
SerializationOp()
template<typename Stream , typename Operation > void CAlert::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 91 of file alert.h.
References READWRITE, vchMsg, and vchSig.
SetNull()
void CAlert::SetNull ()
Definition at line 86 of file alert.cpp.
References CUnsignedAlert::SetNull().
Referenced by CAlert().
Sign()
bool CAlert::Sign ()
Definition at line 149 of file alert.cpp.
References CDataStream::begin(), CLIENT_VERSION, CDataStream::end(), GetArg(), Hash(), SER_NETWORK, and CKey::Sign().
Referenced by ThreadSendAlert().
Member Data Documentation
ADD_SERIALIZE_METHODS
CAlert::ADD_SERIALIZE_METHODS
Definition at line 88 of file alert.h.
vchMsg
std::vector<unsigned char> CAlert::vchMsg
Definition at line 80 of file alert.h.
Referenced by SerializationOp().
vchSig
std::vector<unsigned char> CAlert::vchSig
Definition at line 81 of file alert.h.
Referenced by SerializationOp().
The documentation for this class was generated from the following files:
src/alert.h
src/alert.cpp