Dash Core: CScript Class Reference
CScript Class Reference
Serialized script, used inside transaction inputs and outputs.
#include <script.h>
Public Member Functions
CScript ()
CScript (const CScript &b)
CScript (const_iterator pbegin, const_iterator pend)
CScript (std::vector< unsigned char >::const_iterator pbegin, std::vector< unsigned char >::const_iterator pend)
CScript (const unsigned char *pbegin, const unsigned char *pend)
CScript & operator+= (const CScript &b)
CScript (int64_t b)
CScript (opcodetype b)
CScript (const CScriptNum &b)
CScript (const std::vector< unsigned char > &b)
CScript & operator<< (int64_t b)
CScript & operator<< (opcodetype opcode)
CScript & operator<< (const CScriptNum &b)
CScript & operator<< (const std::vector< unsigned char > &b)
CScript & operator<< (const CScript &b)
bool GetOp (iterator &pc, opcodetype &opcodeRet, std::vector< unsigned char > &vchRet)
bool GetOp (iterator &pc, opcodetype &opcodeRet)
bool GetOp (const_iterator &pc, opcodetype &opcodeRet, std::vector< unsigned char > &vchRet) const
bool GetOp (const_iterator &pc, opcodetype &opcodeRet) const
bool GetOp2 (const_iterator &pc, opcodetype &opcodeRet, std::vector< unsigned char > *pvchRet) const
int FindAndDelete (const CScript &b)
int Find (opcodetype op) const
unsigned int GetSigOpCount (bool fAccurate) const
Pre-version-0.6, Bitcoin always counted CHECKMULTISIGs as 20 sigops.
unsigned int GetSigOpCount (const CScript &scriptSig) const
Accurately count sigOps, including sigOps in pay-to-script-hash transactions:
bool IsPayToPublicKeyHash () const
bool IsPayToScriptHash () const
bool IsPushOnly (const_iterator pc) const
Called by IsStandardTx and P2SH/BIP62 VerifyScript (which makes it consensus-critical).
bool IsPushOnly () const
bool IsUnspendable () const
Returns whether the script is guaranteed to fail at execution, regardless of the initial stack.
void clear ()
Public Member Functions inherited from prevector< N, T, Size, Diff >
void assign (size_type n, const T &val)
template<typename InputIterator >
void assign (InputIterator first, InputIterator last)
prevector ()
prevector (size_type n)
prevector (size_type n, const T &val=T())
template<typename InputIterator >
prevector (InputIterator first, InputIterator last)
prevector (const prevector< N, T, Size, Diff > &other)
prevector & operator= (const prevector< N, T, Size, Diff > &other)
size_type size () const
bool empty () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t capacity () const
T & operator[] (size_type pos)
const T & operator[] (size_type pos) const
void resize (size_type new_size)
void reserve (size_type new_capacity)
void shrink_to_fit ()
void clear ()
iterator insert (iterator pos, const T &value)
void insert (iterator pos, size_type count, const T &value)
template<typename InputIterator >
void insert (iterator pos, InputIterator first, InputIterator last)
iterator erase (iterator pos)
iterator erase (iterator first, iterator last)
void push_back (const T &value)
void pop_back ()
T & front ()
const T & front () const
T & back ()
const T & back () const
void swap (prevector< N, T, Size, Diff > &other)
~prevector ()
bool operator== (const prevector< N, T, Size, Diff > &other) const
bool operator!= (const prevector< N, T, Size, Diff > &other) const
bool operator< (const prevector< N, T, Size, Diff > &other) const
size_t allocated_memory () const
Static Public Member Functions
static int DecodeOP_N (opcodetype opcode)
Encode/decode small integers:
static opcodetype EncodeOP_N (int n)
Protected Member Functions
CScript & push_int64 (int64_t n)
Friends
CScript operator+ (const CScript &a, const CScript &b)
Additional Inherited Members
Public Types inherited from prevector< N, T, Size, Diff >
typedef Size size_type
typedef Diff difference_type
typedef T value_type
typedef value_type & reference
typedef const value_type & const_reference
typedef value_type * pointer
typedef const value_type * const_pointer
Detailed Description
Serialized script, used inside transaction inputs and outputs.
Definition at line 376 of file script.h.
Constructor & Destructor Documentation
CScript() [1/9]
CScript::CScript () inline
Definition at line 396 of file script.h.
CScript() [2/9]
CScript::CScript (const CScript & b) inline
Definition at line 397 of file script.h.
CScript() [3/9]
CScript::CScript (const_iterator pbegin, const_iterator pend) inline
Definition at line 398 of file script.h.
CScript() [4/9]
CScript::CScript (std::vector< unsigned char >::const_iterator pbegin, std::vector< unsigned char >::const_iterator pend) inline
Definition at line 399 of file script.h.
CScript() [5/9]
CScript::CScript (const unsigned char * pbegin, const unsigned char * pend) inline
Definition at line 400 of file script.h.
CScript() [6/9]
CScript::CScript (int64_t b) inline
Definition at line 415 of file script.h.
References operator<<().
CScript() [7/9]
CScript::CScript (opcodetype b) inline explicit
Definition at line 417 of file script.h.
References operator<<().
CScript() [8/9]
CScript::CScript (const CScriptNum & b) inline explicit
Definition at line 418 of file script.h.
References operator<<().
CScript() [9/9]
CScript::CScript (const std::vector< unsigned char > & b) inline explicit
Definition at line 419 of file script.h.
References operator<<().
Member Function Documentation
clear()
void CScript::clear () inline
Definition at line 641 of file script.h.
Referenced by MutateTxSign(), CTxOut::SetNull(), CAddressUnspentValue::SetNull(), signrawtransaction(), SignStep(), and Solver().
DecodeOP_N()
static int CScript::DecodeOP_N (opcodetype opcode) inline static
Encode/decode small integers:
Definition at line 556 of file script.h.
References OP_0, OP_1, and OP_16.
Referenced by Solver().
EncodeOP_N()
static opcodetype CScript::EncodeOP_N (int n) inline static
Definition at line 563 of file script.h.
References OP_0, and OP_1.
Referenced by GetScriptForMultisig().
Find()
int CScript::Find (opcodetype op) const inline
Definition at line 598 of file script.h.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), and GetOp().
FindAndDelete()
int CScript::FindAndDelete (const CScript & b) inline
Definition at line 571 of file script.h.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::empty(), prevector< N, T, Size, Diff >::end(), GetOp(), prevector< N, T, Size, Diff >::insert(), and prevector< N, T, Size, Diff >::size().
Referenced by EvalScript().
GetOp() [1/4]
bool CScript::GetOp (iterator & pc, opcodetype & opcodeRet, std::vector< unsigned char > & vchRet) inline
Definition at line 476 of file script.h.
References prevector< N, T, Size, Diff >::begin(), and GetOp2().
Referenced by EvalScript(), ExtractPubKey(), Find(), FindAndDelete(), GetSigOpCount(), CBloomFilter::IsRelevantAndUpdate(), ScriptToAsmStr(), and Solver().
GetOp() [2/4]
bool CScript::GetOp (iterator & pc, opcodetype & opcodeRet) inline
Definition at line 485 of file script.h.
References prevector< N, T, Size, Diff >::begin(), and GetOp2().
GetOp() [3/4]
bool CScript::GetOp (const_iterator & pc, opcodetype & opcodeRet, std::vector< unsigned char > & vchRet) const inline
Definition at line 493 of file script.h.
References GetOp2().
GetOp() [4/4]
bool CScript::GetOp (const_iterator & pc, opcodetype & opcodeRet) const inline
Definition at line 498 of file script.h.
References GetOp2().
GetOp2()
bool CScript::GetOp2 (const_iterator & pc, opcodetype & opcodeRet, std::vector< unsigned char > * pvchRet) const inline
Definition at line 503 of file script.h.
References prevector< N, T, Size, Diff >::end(), OP_INVALIDOPCODE, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, ReadLE16(), and ReadLE32().
Referenced by FormatScript(), and GetOp().
GetSigOpCount() [1/2]
unsigned int CScript::GetSigOpCount (bool fAccurate) const
Pre-version-0.6, Bitcoin always counted CHECKMULTISIGs as 20 sigops.
With pay-to-script-hash, that changed: CHECKMULTISIGs serialized in scriptSigs are counted more accurately, assuming they are of the form ... OP_N CHECKMULTISIG ...
Definition at line 155 of file script.cpp.
References MAX_PUBKEYS_PER_MULTISIG, OP_1, OP_16, OP_CHECKMULTISIG, OP_CHECKMULTISIGVERIFY, OP_CHECKSIG, OP_CHECKSIGVERIFY, and OP_INVALIDOPCODE.
Referenced by GetLegacySigOpCount(), GetP2SHSigOpCount(), and GetSigOpCount().
GetSigOpCount() [2/2]
unsigned int CScript::GetSigOpCount (const CScript & scriptSig) const
Accurately count sigOps, including sigOps in pay-to-script-hash transactions:
... and return its opcount:
Definition at line 179 of file script.cpp.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), GetOp(), GetSigOpCount(), and OP_16.
IsPayToPublicKeyHash()
bool CScript::IsPayToPublicKeyHash () const
Definition at line 203 of file script.cpp.
References OP_CHECKSIG, OP_DUP, OP_EQUALVERIFY, and OP_HASH160.
Referenced by CTxMemPool::addAddressIndex(), CTxMemPool::addSpentIndex(), ConnectBlock(), DisconnectBlock(), CGovernanceObject::IsCollateralValid(), and CPrivateSend::IsCollateralValid().
IsPayToScriptHash()
bool CScript::IsPayToScriptHash () const
Definition at line 214 of file script.cpp.
References OP_EQUAL, and OP_HASH160.
Referenced by CTxMemPool::addAddressIndex(), CTxMemPool::addSpentIndex(), ConnectBlock(), DisconnectBlock(), listunspent(), Solver(), and VerifyScript().
IsPushOnly() [1/2]
bool CScript::IsPushOnly (const_iterator pc) const
Called by IsStandardTx and P2SH/BIP62 VerifyScript (which makes it consensus-critical).
Definition at line 223 of file script.cpp.
References OP_16.
Referenced by IsStandardTx(), Solver(), and VerifyScript().
IsPushOnly() [2/2]
bool CScript::IsPushOnly () const
Definition at line 240 of file script.cpp.
IsUnspendable()
bool CScript::IsUnspendable () const inline
Returns whether the script is guaranteed to fail at execution, regardless of the initial stack.
This allows outputs to be pruned instantly when entering the UTXO set.
Definition at line 636 of file script.h.
References prevector< N, T, Size, Diff >::begin(), MAX_SCRIPT_SIZE, OP_RETURN, and prevector< N, T, Size, Diff >::size().
Referenced by CWalletTx::GetAmounts(), CTxOut::GetDustThreshold(), CGovernanceObject::IsCollateralValid(), and ScriptToAsmStr().
operator+=()
CScript& CScript::operator+= (const CScript & b) inline
Definition at line 402 of file script.h.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), and prevector< N, T, Size, Diff >::insert().
operator<<() [1/5]
CScript& CScript::operator<< (int64_t b) inline
Definition at line 422 of file script.h.
References push_int64().
Referenced by CScript().
operator<<() [2/5]
CScript& CScript::operator<< (opcodetype opcode) inline
Definition at line 424 of file script.h.
References prevector< N, T, Size, Diff >::end(), and prevector< N, T, Size, Diff >::insert().
operator<<() [3/5]
CScript& CScript::operator<< (const CScriptNum & b) inline
Definition at line 432 of file script.h.
References CScriptNum::getvch().
operator<<() [4/5]
CScript& CScript::operator<< (const std::vector< unsigned char > & b) inline
Definition at line 438 of file script.h.
References prevector< N, T, Size, Diff >::end(), prevector< N, T, Size, Diff >::insert(), OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, WriteLE16(), and WriteLE32().
operator<<() [5/5]
CScript& CScript::operator<< (const CScript & b) inline
Definition at line 467 of file script.h.
push_int64()
CScript& CScript::push_int64 (int64_t n) inline protected
Definition at line 379 of file script.h.
References OP_0, OP_1, prevector< N, T, Size, Diff >::push_back(), and CScriptNum::serialize().
Referenced by operator<<().
Friends And Related Function Documentation
operator+
CScript operator+ (const CScript & a, const CScript & b) friend
Definition at line 408 of file script.h.
The documentation for this class was generated from the following files:
src/script/script.h
src/script/script.cpp