Dash Core: CTxLockRequest Class Reference
CTxLockRequest Class Reference
#include <instantx.h>
Public Member Functions
CTxLockRequest ()=default
CTxLockRequest (const CTransaction &tx)
bool IsValid () const
CAmount GetMinFee () const
int GetMaxSignatures () const
operator bool () const
Public Member Functions inherited from CTransaction
CTransaction ()
Construct a CTransaction that qualifies as IsNull()
CTransaction (const CMutableTransaction &tx)
Convert a CMutableTransaction into a CTransaction.
CTransaction & operator= (const CTransaction &tx)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
bool IsNull () const
const uint256 & GetHash () const
CAmount GetValueOut () const
double ComputePriority (double dPriorityInputs, unsigned int nTxSize=0) const
unsigned int CalculateModifiedSize (unsigned int nTxSize=0) const
unsigned int GetTotalSize () const
Get the total transaction size in bytes, including witness data.
bool IsCoinBase () const
std::string ToString () const
Static Public Attributes
static const int WARN_MANY_INPUTS = 100
Static Public Attributes inherited from CTransaction
static const int32_t CURRENT_VERSION =1
static const int32_t MAX_STANDARD_VERSION =2
Static Private Attributes
static const CAmount MIN_FEE = 0.0001 * COIN
Additional Inherited Members
Public Attributes inherited from CTransaction
const int32_t nVersion
const std::vector< CTxIn > vin
const std::vector< CTxOut > vout
const uint32_t nLockTime
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 121 of file instantx.h.
Constructor & Destructor Documentation
CTxLockRequest() [1/2]
CTxLockRequest::CTxLockRequest () default
Referenced by operator bool().
CTxLockRequest() [2/2]
CTxLockRequest::CTxLockRequest (const CTransaction & tx) inline
Definition at line 130 of file instantx.h.
Member Function Documentation
GetMaxSignatures()
int CTxLockRequest::GetMaxSignatures () const
Definition at line 988 of file instantx.cpp.
References COutPointLock::SIGNATURES_TOTAL, and CTransaction::vin.
Referenced by TransactionDesc::FormatTxStatus(), and CInstantSend::ProcessTxLockVote().
GetMinFee()
CAmount CTxLockRequest::GetMinFee () const
Definition at line 982 of file instantx.cpp.
References MIN_FEE, and CTransaction::vin.
Referenced by CWallet::CreateTransaction(), and IsValid().
IsValid()
bool CTxLockRequest::IsValid () const
Definition at line 929 of file instantx.cpp.
References chainActive, CheckFinalTx(), COIN, cs_main, CTransaction::GetHash(), GetMinFee(), CSporkManager::GetSporkValue(), GetUTXOCoin(), CTransaction::GetValueOut(), CChain::Height(), INSTANTSEND_CONFIRMATIONS_REQUIRED, LOCK, LogPrint(), Coin::nHeight, CTxOut::nValue, Coin::out, CTxIn::prevout, SPORK_5_INSTANTSEND_MAX_VALUE, sporkManager, base_blob< BITS >::ToString(), CTransaction::ToString(), COutPoint::ToStringShort(), CTransaction::vin, CTransaction::vout, and WARN_MANY_INPUTS.
Referenced by AcceptToMemoryPoolWorker(), and CInstantSend::CreateTxLockCandidate().
operator bool()
CTxLockRequest::operator bool () const inline explicit
Definition at line 136 of file instantx.h.
References CTxLockRequest().
Member Data Documentation
MIN_FEE
const CAmount CTxLockRequest::MIN_FEE = 0.0001 * COIN static private
Definition at line 124 of file instantx.h.
Referenced by GetMinFee().
WARN_MANY_INPUTS
const int CTxLockRequest::WARN_MANY_INPUTS = 100 static
Definition at line 127 of file instantx.h.
Referenced by IsValid(), and WalletModel::prepareTransaction().
The documentation for this class was generated from the following files:
src/instantx.h
src/instantx.cpp