Dash Core: src/bench/Examples.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
Examples.cpp File Reference
#include "bench.h"
#include "validation.h"
#include "utiltime.h"
#include <math.h>
Functions
static void Sleep100ms (benchmark::State &state)
BENCHMARK (Sleep100ms)
static void Trig (benchmark::State &state)
BENCHMARK (Trig)
Variables
volatile double sum = 0.0
Function Documentation
BENCHMARK() [1/2]
BENCHMARK (Sleep100ms)
BENCHMARK() [2/2]
BENCHMARK (Trig)
Sleep100ms()
static void Sleep100ms (benchmark::State & state) static
Definition at line 11 of file Examples.cpp.
References benchmark::State::KeepRunning(), and MilliSleep().
Trig()
static void Trig (benchmark::State & state) static
Definition at line 25 of file Examples.cpp.
References benchmark::State::KeepRunning(), and sum.
Variable Documentation
sum
volatile double sum = 0.0
Definition at line 23 of file Examples.cpp.
Referenced by run_benchmark(), TrafficGraphData::sumEach3Samples(), test_ec_combine(), test_ge(), and Trig().
Released under the MIT license