Dash Core: src/arith_uint256.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
arith_uint256.cpp File Reference
#include "arith_uint256.h"
#include "uint256.h"
#include "utilstrencodings.h"
#include "crypto/common.h"
#include <stdio.h>
#include <string.h>
Functions
uint256 ArithToUint256 (const arith_uint256 &a)
arith_uint256 UintToArith256 (const uint256 &a)
Function Documentation
ArithToUint256()
uint256 ArithToUint256 (const arith_uint256 & a)
Definition at line 247 of file arith_uint256.cpp.
References base_blob< BITS >::begin(), base_uint< BITS >::pn, base_uint< BITS >::WIDTH, and WriteLE32().
Referenced by CMasternode::CalculateScore(), base_uint< 256 >::GetHex(), RelayAddress(), SendMessages(), and CGovernanceManager::UpdateCurrentWatchdog().
UintToArith256()
arith_uint256 UintToArith256 (const uint256 & a)
Definition at line 254 of file arith_uint256.cpp.
References base_blob< BITS >::begin(), base_uint< BITS >::pn, ReadLE32(), and base_uint< BITS >::WIDTH.
Referenced by BitcoinMiner(), CalculateNextWorkRequired(), CMasternode::CalculateScore(), CheckProofOfWork(), ConnectBlock(), DarkGravityWave(), GetNextWorkRequiredBTC(), CSuperblock::GetPaymentsLimit(), IsInitialBlockDownload(), KimotoGravityWell(), sortProposalsByVotes::operator()(), RelayAddress(), SendMessages(), base_uint< 256 >::SetHex(), and CGovernanceManager::UpdateCurrentWatchdog().
Released under the MIT license