Dash Core: src/base58.cpp File Reference
base58.cpp File Reference
#include "base58.h"
#include "hash.h"
#include "uint256.h"
#include <assert.h>
#include <stdint.h>
#include <string.h>
#include <vector>
#include <string>
#include <boost/variant/apply_visitor.hpp>
#include <boost/variant/static_visitor.hpp>
Functions
bool DecodeBase58 (const char *psz, std::vector< unsigned char > &vch)
std::string EncodeBase58 (const unsigned char *pbegin, const unsigned char *pend)
std::string EncodeBase58 (const std::vector< unsigned char > &vch)
bool DecodeBase58 (const std::string &str, std::vector< unsigned char > &vchRet)
std::string EncodeBase58Check (const std::vector< unsigned char > &vchIn)
bool DecodeBase58Check (const char *psz, std::vector< unsigned char > &vchRet)
bool DecodeBase58Check (const std::string &str, std::vector< unsigned char > &vchRet)
Variables
static const char * pszBase58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
Function Documentation
DecodeBase58() [1/2]
bool DecodeBase58 (const char * psz, std::vector< unsigned char > & vchRet)
Decode a base58-encoded string (psz) into a byte vector (vchRet). return true if decoding is successful. psz cannot be NULL.
Definition at line 21 of file base58.cpp.
Referenced by DecodeBase58(), and DecodeBase58Check().
DecodeBase58() [2/2]
bool DecodeBase58 (const std::string & str, std::vector< unsigned char > & vchRet)
Decode a base58-encoded string (str) into a byte vector (vchRet). return true if decoding is successful.
Definition at line 116 of file base58.cpp.
DecodeBase58Check() [1/2]
bool DecodeBase58Check (const char * psz, std::vector< unsigned char > & vchRet) inline
Decode a base58-encoded string (psz) that includes a checksum into a byte vector (vchRet), return true if decoding is successful
Definition at line 130 of file base58.cpp.
Referenced by DecodeBase58Check(), and CBase58Data::SetString().
DecodeBase58Check() [2/2]
bool DecodeBase58Check (const std::string & str, std::vector< unsigned char > & vchRet) inline
Decode a base58-encoded string (str) that includes a checksum into a byte vector (vchRet), return true if decoding is successful
Definition at line 147 of file base58.cpp.
EncodeBase58() [1/2]
std::string EncodeBase58 (const unsigned char * pbegin, const unsigned char * pend)
Why base-58 instead of standard base-64 encoding?
Don't want 0OIl characters that look the same in some fonts and could be used to create visually identical looking data.
A string with non-alphanumeric characters is not as easily accepted as input.
E-mail usually won't line-break if there's no punctuation to break at.
Double-clicking selects the whole string as one word if it's all alphanumeric. Encode a byte sequence as a base58-encoded string. pbegin and pend cannot be NULL, unless both are.
Definition at line 71 of file base58.cpp.
Referenced by EncodeBase58(), and EncodeBase58Check().
EncodeBase58() [2/2]
std::string EncodeBase58 (const std::vector< unsigned char > & vch)
Encode a byte vector as a base58-encoded string
Definition at line 111 of file base58.cpp.
EncodeBase58Check()
std::string EncodeBase58Check (const std::vector< unsigned char > & vchIn)
Encode a byte vector into a base58-encoded string, including checksum
Definition at line 121 of file base58.cpp.
Referenced by CBase58Data::ToString().
Variable Documentation
pszBase58
const char* pszBase58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz" static
All alphanumeric characters except for "0", "I", "O", and "l"
Definition at line 19 of file base58.cpp.
Referenced by DecodeBase58(), and EncodeBase58().