Dash Core: src/secp256k1/src/bench_recover.c File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bench_recover.c File Reference
#include "include/secp256k1.h"
#include "include/secp256k1_recovery.h"
#include "util.h"
#include "bench.h"
Classes
struct bench_recover_data
Functions
void bench_recover (void *arg)
void bench_recover_setup (void *arg)
int main (void)
Function Documentation
bench_recover()
void bench_recover (void * arg)
Definition at line 18 of file bench_recover.c.
References CHECK, bench_recover_data::ctx, bench_recover_data::msg, SECP256K1_EC_COMPRESSED, secp256k1_ec_pubkey_serialize(), secp256k1_ecdsa_recover(), secp256k1_ecdsa_recoverable_signature_parse_compact(), and bench_recover_data::sig.
Referenced by main().
bench_recover_setup()
void bench_recover_setup (void * arg)
Definition at line 39 of file bench_recover.c.
References bench_recover_data::msg, and bench_recover_data::sig.
Referenced by main().
main()
int main (void)
Definition at line 51 of file bench_recover.c.
References bench_recover(), bench_recover_setup(), bench_recover_data::ctx, run_benchmark(), secp256k1_context_create(), secp256k1_context_destroy(), and SECP256K1_CONTEXT_VERIFY.
Released under the MIT license