Dash Core: src/crypto/ctaes/bench.c File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bench.c File Reference
#include <stdio.h>
#include <math.h>
#include "sys/time.h"
#include "ctaes.h"
Functions
static double gettimedouble (void)
static void print_number (double x)
static void run_benchmark (char *name, void(*benchmark)(void *), void(*setup)(void *), void(*teardown)(void *), void *data, int count, int iter)
static void bench_AES128_init (void *data)
static void bench_AES128_encrypt_setup (void *data)
static void bench_AES128_encrypt (void *data)
static void bench_AES128_decrypt (void *data)
static void bench_AES192_init (void *data)
static void bench_AES192_encrypt_setup (void *data)
static void bench_AES192_encrypt (void *data)
static void bench_AES192_decrypt (void *data)
static void bench_AES256_init (void *data)
static void bench_AES256_encrypt_setup (void *data)
static void bench_AES256_encrypt (void *data)
static void bench_AES256_decrypt (void *data)
int main (void)
Function Documentation
bench_AES128_decrypt()
static void bench_AES128_decrypt (void * data) static
Definition at line 82 of file bench.c.
References AES128_decrypt(), and ctx.
Referenced by main().
bench_AES128_encrypt()
static void bench_AES128_encrypt (void * data) static
Definition at line 73 of file bench.c.
References AES128_encrypt(), and ctx.
Referenced by main().
bench_AES128_encrypt_setup()
static void bench_AES128_encrypt_setup (void * data) static
Definition at line 67 of file bench.c.
References AES128_init(), and ctx.
Referenced by main().
bench_AES128_init()
static void bench_AES128_init (void * data) static
Definition at line 59 of file bench.c.
References AES128_init(), and ctx.
Referenced by main().
bench_AES192_decrypt()
static void bench_AES192_decrypt (void * data) static
Definition at line 114 of file bench.c.
References AES192_decrypt(), and ctx.
Referenced by main().
bench_AES192_encrypt()
static void bench_AES192_encrypt (void * data) static
Definition at line 105 of file bench.c.
References AES192_encrypt(), and ctx.
Referenced by main().
bench_AES192_encrypt_setup()
static void bench_AES192_encrypt_setup (void * data) static
Definition at line 99 of file bench.c.
References AES192_init(), and ctx.
Referenced by main().
bench_AES192_init()
static void bench_AES192_init (void * data) static
Definition at line 91 of file bench.c.
References AES192_init(), and ctx.
Referenced by main().
bench_AES256_decrypt()
static void bench_AES256_decrypt (void * data) static
Definition at line 147 of file bench.c.
References AES256_decrypt(), and ctx.
Referenced by main().
bench_AES256_encrypt()
static void bench_AES256_encrypt (void * data) static
Definition at line 138 of file bench.c.
References AES256_encrypt(), and ctx.
Referenced by main().
bench_AES256_encrypt_setup()
static void bench_AES256_encrypt_setup (void * data) static
Definition at line 132 of file bench.c.
References AES256_init(), and ctx.
Referenced by main().
bench_AES256_init()
static void bench_AES256_init (void * data) static
Definition at line 123 of file bench.c.
References AES256_init(), and ctx.
Referenced by main().
gettimedouble()
static double gettimedouble (void) static
Definition at line 7 of file bench.c.
Referenced by run_benchmark().
main()
int main (void)
Definition at line 156 of file bench.c.
References bench_AES128_decrypt(), bench_AES128_encrypt(), bench_AES128_encrypt_setup(), bench_AES128_init(), bench_AES192_decrypt(), bench_AES192_encrypt(), bench_AES192_encrypt_setup(), bench_AES192_init(), bench_AES256_decrypt(), bench_AES256_encrypt(), bench_AES256_encrypt_setup(), bench_AES256_init(), and run_benchmark().
print_number()
static void print_number (double x) static
Definition at line 13 of file bench.c.
References tinyformat::printf().
Referenced by run_benchmark().
run_benchmark()
static void run_benchmark (char * name, void(*)(void *) benchmark, void(*)(void *) setup, void(*)(void *) teardown, void * data, int count, int iter) static
Definition at line 26 of file bench.c.
References count, gettimedouble(), name, print_number(), tinyformat::printf(), and sum.
Referenced by main().
Released under the MIT license