Dash Core: src/bench/poly1305.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
poly1305.cpp File Reference
#include <iostream>
#include <vector>
#include <bench/bench.h>
#include <crypto/poly1305.h>
Functions
static void POLY1305 (benchmark::State &state, size_t buffersize)
static void POLY1305_64BYTES (benchmark::State &state)
static void POLY1305_256BYTES (benchmark::State &state)
static void POLY1305_1MB (benchmark::State &state)
BENCHMARK (POLY1305_64BYTES)
BENCHMARK (POLY1305_256BYTES)
BENCHMARK (POLY1305_1MB)
Variables
static constexpr uint64_t BUFFER_SIZE_TINY = 64
static constexpr uint64_t BUFFER_SIZE_SMALL = 256
static constexpr uint64_t BUFFER_SIZE_LARGE = 1024*1024
Function Documentation
BENCHMARK() [1/3]
BENCHMARK (POLY1305_64BYTES)
BENCHMARK() [2/3]
BENCHMARK (POLY1305_256BYTES)
BENCHMARK() [3/3]
BENCHMARK (POLY1305_1MB)
POLY1305()
static void POLY1305 (benchmark::State & state, size_t buffersize) static
Definition at line 16 of file poly1305.cpp.
References benchmark::State::KeepRunning(), poly1305_auth(), POLY1305_KEYLEN, and POLY1305_TAGLEN.
Referenced by POLY1305_1MB(), POLY1305_256BYTES(), and POLY1305_64BYTES().
POLY1305_1MB()
static void POLY1305_1MB (benchmark::State & state) static
Definition at line 35 of file poly1305.cpp.
References BUFFER_SIZE_LARGE, and POLY1305().
POLY1305_256BYTES()
static void POLY1305_256BYTES (benchmark::State & state) static
Definition at line 30 of file poly1305.cpp.
References BUFFER_SIZE_SMALL, and POLY1305().
POLY1305_64BYTES()
static void POLY1305_64BYTES (benchmark::State & state) static
Definition at line 25 of file poly1305.cpp.
References BUFFER_SIZE_TINY, and POLY1305().
Variable Documentation
BUFFER_SIZE_LARGE
constexpr uint64_t BUFFER_SIZE_LARGE = 1024*1024 static
Definition at line 14 of file poly1305.cpp.
Referenced by POLY1305_1MB().
BUFFER_SIZE_SMALL
constexpr uint64_t BUFFER_SIZE_SMALL = 256 static
Definition at line 13 of file poly1305.cpp.
Referenced by POLY1305_256BYTES().
BUFFER_SIZE_TINY
constexpr uint64_t BUFFER_SIZE_TINY = 64 static
Definition at line 12 of file poly1305.cpp.
Referenced by POLY1305_64BYTES().
Released under the MIT license