Dash Core: src/secp256k1/src/bench_internal.c File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
bench_internal.c File Reference
#include <stdio.h>
#include "include/secp256k1.h"
#include "util.h"
#include "hash_impl.h"
#include "num_impl.h"
#include "field_impl.h"
#include "group_impl.h"
#include "scalar_impl.h"
#include "ecmult_const_impl.h"
#include "ecmult_impl.h"
#include "bench.h"
#include "secp256k1.c"
Classes
struct bench_inv_t
Functions
void bench_setup (void *arg)
void bench_scalar_add (void *arg)
void bench_scalar_negate (void *arg)
void bench_scalar_sqr (void *arg)
void bench_scalar_mul (void *arg)
void bench_scalar_inverse (void *arg)
void bench_scalar_inverse_var (void *arg)
void bench_field_normalize (void *arg)
void bench_field_normalize_weak (void *arg)
void bench_field_mul (void *arg)
void bench_field_sqr (void *arg)
void bench_field_inverse (void *arg)
void bench_field_inverse_var (void *arg)
void bench_field_sqrt_var (void *arg)
void bench_group_double_var (void *arg)
void bench_group_add_var (void *arg)
void bench_group_add_affine (void *arg)
void bench_group_add_affine_var (void *arg)
void bench_ecmult_wnaf (void *arg)
void bench_wnaf_const (void *arg)
void bench_sha256 (void *arg)
void bench_hmac_sha256 (void *arg)
void bench_rfc6979_hmac_sha256 (void *arg)
void bench_context_verify (void *arg)
void bench_context_sign (void *arg)
int have_flag (int argc, char **argv, char *flag)
int main (int argc, char **argv)
Function Documentation
bench_context_sign()
void bench_context_sign (void * arg)
Definition at line 294 of file bench_internal.c.
References secp256k1_context_create(), secp256k1_context_destroy(), and SECP256K1_CONTEXT_SIGN.
Referenced by main().
bench_context_verify()
void bench_context_verify (void * arg)
Definition at line 286 of file bench_internal.c.
References secp256k1_context_create(), secp256k1_context_destroy(), and SECP256K1_CONTEXT_VERIFY.
Referenced by main().
bench_ecmult_wnaf()
void bench_ecmult_wnaf (void * arg)
Definition at line 230 of file bench_internal.c.
References bench_inv_t::scalar_x, bench_inv_t::scalar_y, secp256k1_ecmult_wnaf(), secp256k1_scalar_add(), WINDOW_A, and bench_inv_t::wnaf.
Referenced by main().
bench_field_inverse()
void bench_field_inverse (void * arg)
Definition at line 164 of file bench_internal.c.
References bench_inv_t::fe_x, bench_inv_t::fe_y, secp256k1_fe_add(), and secp256k1_fe_inv().
Referenced by main().
bench_field_inverse_var()
void bench_field_inverse_var (void * arg)
Definition at line 174 of file bench_internal.c.
References bench_inv_t::fe_x, bench_inv_t::fe_y, secp256k1_fe_add(), and secp256k1_fe_inv_var().
Referenced by main().
bench_field_mul()
void bench_field_mul (void * arg)
Definition at line 146 of file bench_internal.c.
References bench_inv_t::fe_x, bench_inv_t::fe_y, and secp256k1_fe_mul().
Referenced by main().
bench_field_normalize()
void bench_field_normalize (void * arg)
Definition at line 128 of file bench_internal.c.
References bench_inv_t::fe_x, and secp256k1_fe_normalize().
Referenced by main().
bench_field_normalize_weak()
void bench_field_normalize_weak (void * arg)
Definition at line 137 of file bench_internal.c.
References bench_inv_t::fe_x, and secp256k1_fe_normalize_weak().
Referenced by main().
bench_field_sqr()
void bench_field_sqr (void * arg)
Definition at line 155 of file bench_internal.c.
References bench_inv_t::fe_x, and secp256k1_fe_sqr().
Referenced by main().
bench_field_sqrt_var()
void bench_field_sqrt_var (void * arg)
Definition at line 184 of file bench_internal.c.
References bench_inv_t::fe_x, bench_inv_t::fe_y, secp256k1_fe_add(), and secp256k1_fe_sqrt_var().
Referenced by main().
bench_group_add_affine()
void bench_group_add_affine (void * arg)
Definition at line 212 of file bench_internal.c.
References bench_inv_t::ge_y, bench_inv_t::gej_x, and secp256k1_gej_add_ge().
Referenced by main().
bench_group_add_affine_var()
void bench_group_add_affine_var (void * arg)
Definition at line 221 of file bench_internal.c.
References bench_inv_t::ge_y, bench_inv_t::gej_x, and secp256k1_gej_add_ge_var().
Referenced by main().
bench_group_add_var()
void bench_group_add_var (void * arg)
Definition at line 203 of file bench_internal.c.
References bench_inv_t::gej_x, bench_inv_t::gej_y, and secp256k1_gej_add_var().
Referenced by main().
bench_group_double_var()
void bench_group_double_var (void * arg)
Definition at line 194 of file bench_internal.c.
References bench_inv_t::gej_x, and secp256k1_gej_double_var().
Referenced by main().
bench_hmac_sha256()
void bench_hmac_sha256 (void * arg)
Definition at line 263 of file bench_internal.c.
References bench_inv_t::data, secp256k1_hmac_sha256_finalize(), secp256k1_hmac_sha256_initialize(), and secp256k1_hmac_sha256_write().
Referenced by main().
bench_rfc6979_hmac_sha256()
void bench_rfc6979_hmac_sha256 (void * arg)
Definition at line 275 of file bench_internal.c.
References bench_inv_t::data, secp256k1_rfc6979_hmac_sha256_generate(), and secp256k1_rfc6979_hmac_sha256_initialize().
Referenced by main().
bench_scalar_add()
void bench_scalar_add (void * arg)
Definition at line 59 of file bench_internal.c.
References bench_inv_t::scalar_x, bench_inv_t::scalar_y, and secp256k1_scalar_add().
Referenced by main().
bench_scalar_inverse()
void bench_scalar_inverse (void * arg)
Definition at line 108 of file bench_internal.c.
References bench_inv_t::scalar_x, bench_inv_t::scalar_y, secp256k1_scalar_add(), and secp256k1_scalar_inverse().
Referenced by main().
bench_scalar_inverse_var()
void bench_scalar_inverse_var (void * arg)
Definition at line 118 of file bench_internal.c.
References bench_inv_t::scalar_x, bench_inv_t::scalar_y, secp256k1_scalar_add(), and secp256k1_scalar_inverse_var().
Referenced by main().
bench_scalar_mul()
void bench_scalar_mul (void * arg)
Definition at line 86 of file bench_internal.c.
References bench_inv_t::scalar_x, bench_inv_t::scalar_y, and secp256k1_scalar_mul().
Referenced by main().
bench_scalar_negate()
void bench_scalar_negate (void * arg)
Definition at line 68 of file bench_internal.c.
References bench_inv_t::scalar_x, and secp256k1_scalar_negate().
Referenced by main().
bench_scalar_sqr()
void bench_scalar_sqr (void * arg)
Definition at line 77 of file bench_internal.c.
References bench_inv_t::scalar_x, and secp256k1_scalar_sqr().
Referenced by main().
bench_setup()
void bench_setup (void * arg)
Definition at line 30 of file bench_internal.c.
References CHECK, bench_inv_t::data, bench_inv_t::fe_x, bench_inv_t::fe_y, bench_inv_t::ge_x, bench_inv_t::ge_y, bench_inv_t::gej_x, bench_inv_t::gej_y, memcpy(), bench_inv_t::scalar_x, bench_inv_t::scalar_y, secp256k1_fe_set_b32(), secp256k1_ge_set_xo_var(), secp256k1_gej_set_ge(), and secp256k1_scalar_set_b32().
Referenced by main().
bench_sha256()
void bench_sha256 (void * arg)
Definition at line 251 of file bench_internal.c.
References bench_inv_t::data, secp256k1_sha256_finalize(), secp256k1_sha256_initialize(), and secp256k1_sha256_write().
Referenced by main().
bench_wnaf_const()
void bench_wnaf_const (void * arg)
Definition at line 240 of file bench_internal.c.
References bench_inv_t::scalar_x, bench_inv_t::scalar_y, secp256k1_scalar_add(), secp256k1_wnaf_const(), WINDOW_A, and bench_inv_t::wnaf.
Referenced by main().
have_flag()
int have_flag (int argc, char ** argv, char * flag)
Definition at line 303 of file bench_internal.c.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 318 of file bench_internal.c.
References bench_context_sign(), bench_context_verify(), bench_ecmult_wnaf(), bench_field_inverse(), bench_field_inverse_var(), bench_field_mul(), bench_field_normalize(), bench_field_normalize_weak(), bench_field_sqr(), bench_field_sqrt_var(), bench_group_add_affine(), bench_group_add_affine_var(), bench_group_add_var(), bench_group_double_var(), bench_hmac_sha256(), bench_rfc6979_hmac_sha256(), bench_scalar_add(), bench_scalar_inverse(), bench_scalar_inverse_var(), bench_scalar_mul(), bench_scalar_negate(), bench_scalar_sqr(), bench_setup(), bench_sha256(), bench_wnaf_const(), have_flag(), and run_benchmark().
Released under the MIT license