Dash Core: src/secp256k1/src/bench_sign.c File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
bench_sign.c File Reference
#include "include/secp256k1.h"
#include "util.h"
#include "bench.h"
Classes
struct bench_sign_t
Functions
static void bench_sign_setup (void *arg)
static void bench_sign (void *arg)
int main (void)
Function Documentation
bench_sign()
static void bench_sign (void * arg) static
Definition at line 29 of file bench_sign.c.
References CHECK, bench_sign_t::ctx, bench_sign_t::key, bench_sign_t::msg, secp256k1_ecdsa_sign(), and secp256k1_ecdsa_signature_serialize_der().
Referenced by main().
bench_sign_setup()
static void bench_sign_setup (void * arg) static
Definition at line 17 of file bench_sign.c.
References bench_sign_t::key, and bench_sign_t::msg.
Referenced by main().
main()
int main (void)
Definition at line 47 of file bench_sign.c.
References bench_sign(), bench_sign_setup(), bench_sign_t::ctx, run_benchmark(), secp256k1_context_create(), secp256k1_context_destroy(), and SECP256K1_CONTEXT_SIGN.
Released under the MIT license