Dash Core: src/bench/base58.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
base58.cpp File Reference
#include <bench/bench.h>
#include <validation.h>
#include <base58.h>
#include <array>
#include <vector>
#include <string>
Functions
static void Base58Encode (benchmark::State &state)
static void Base58CheckEncode (benchmark::State &state)
static void Base58Decode (benchmark::State &state)
BENCHMARK (Base58Encode)
BENCHMARK (Base58CheckEncode)
BENCHMARK (Base58Decode)
Function Documentation
Base58CheckEncode()
static void Base58CheckEncode (benchmark::State & state) static
Definition at line 30 of file base58.cpp.
References EncodeBase58Check(), and benchmark::State::KeepRunning().
Base58Decode()
static void Base58Decode (benchmark::State & state) static
Definition at line 47 of file base58.cpp.
References DecodeBase58(), and benchmark::State::KeepRunning().
Base58Encode()
static void Base58Encode (benchmark::State & state) static
Definition at line 15 of file base58.cpp.
References EncodeBase58(), and benchmark::State::KeepRunning().
BENCHMARK() [1/3]
BENCHMARK (Base58Encode)
BENCHMARK() [2/3]
BENCHMARK (Base58CheckEncode)
BENCHMARK() [3/3]
BENCHMARK (Base58Decode)
Released under the MIT license