Dash Core: src/secp256k1/src/bench_verify.c File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bench_verify.c File Reference
#include <stdio.h>
#include <string.h>
#include "include/secp256k1.h"
#include "util.h"
#include "bench.h"
Classes
struct benchmark_verify_t
Functions
static void benchmark_verify (void *arg)
int main (void)
Function Documentation
benchmark_verify()
static void benchmark_verify (void * arg) static
Definition at line 33 of file bench_verify.c.
References CHECK, benchmark_verify_t::ctx, benchmark_verify_t::msg, benchmark_verify_t::pubkey, benchmark_verify_t::pubkeylen, secp256k1_ec_pubkey_parse(), secp256k1_ecdsa_signature_parse_der(), secp256k1_ecdsa_verify(), benchmark_verify_t::sig, and benchmark_verify_t::siglen.
Referenced by main().
main()
int main (void)
Definition at line 82 of file bench_verify.c.
References benchmark_verify(), CHECK, benchmark_verify_t::ctx, benchmark_verify_t::key, benchmark_verify_t::msg, benchmark_verify_t::pubkey, benchmark_verify_t::pubkeylen, run_benchmark(), secp256k1_context_create(), secp256k1_context_destroy(), SECP256K1_CONTEXT_SIGN, SECP256K1_CONTEXT_VERIFY, SECP256K1_EC_COMPRESSED, secp256k1_ec_pubkey_create(), secp256k1_ec_pubkey_serialize(), secp256k1_ecdsa_sign(), secp256k1_ecdsa_signature_serialize_der(), benchmark_verify_t::sig, and benchmark_verify_t::siglen.
Released under the MIT license