Dash Core: src/bench/chacha_poly_aead.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
chacha_poly_aead.cpp File Reference
#include <iostream>
#include <bench/bench.h>
#include <crypto/chacha_poly_aead.h>
#include <crypto/poly1305.h>
#include <hash.h>
#include <limits>
#include <assert.h>
Functions
static void CHACHA20_POLY1305_AEAD (benchmark::State &state, size_t buffersize, bool include_decryption)
static void CHACHA20_POLY1305_AEAD_64BYTES_ONLY_ENCRYPT (benchmark::State &state)
static void CHACHA20_POLY1305_AEAD_256BYTES_ONLY_ENCRYPT (benchmark::State &state)
static void CHACHA20_POLY1305_AEAD_1MB_ONLY_ENCRYPT (benchmark::State &state)
static void CHACHA20_POLY1305_AEAD_64BYTES_ENCRYPT_DECRYPT (benchmark::State &state)
static void CHACHA20_POLY1305_AEAD_256BYTES_ENCRYPT_DECRYPT (benchmark::State &state)
static void CHACHA20_POLY1305_AEAD_1MB_ENCRYPT_DECRYPT (benchmark::State &state)
static void HASH (benchmark::State &state, size_t buffersize)
static void HASH_64BYTES (benchmark::State &state)
static void HASH_256BYTES (benchmark::State &state)
static void HASH_1MB (benchmark::State &state)
BENCHMARK (CHACHA20_POLY1305_AEAD_64BYTES_ONLY_ENCRYPT)
BENCHMARK (CHACHA20_POLY1305_AEAD_256BYTES_ONLY_ENCRYPT)
BENCHMARK (CHACHA20_POLY1305_AEAD_1MB_ONLY_ENCRYPT)
BENCHMARK (CHACHA20_POLY1305_AEAD_64BYTES_ENCRYPT_DECRYPT)
BENCHMARK (CHACHA20_POLY1305_AEAD_256BYTES_ENCRYPT_DECRYPT)
BENCHMARK (CHACHA20_POLY1305_AEAD_1MB_ENCRYPT_DECRYPT)
BENCHMARK (HASH_64BYTES)
BENCHMARK (HASH_256BYTES)
BENCHMARK (HASH_1MB)
Variables
static constexpr uint64_t BUFFER_SIZE_TINY = 64
static constexpr uint64_t BUFFER_SIZE_SMALL = 256
static constexpr uint64_t BUFFER_SIZE_LARGE = 1024 * 1024
static const unsigned char k1 [32] = {0}
static const unsigned char k2 [32] = {0}
static ChaCha20Poly1305AEAD aead (k1, 32, k2, 32)
Function Documentation
BENCHMARK() [1/9]
BENCHMARK (CHACHA20_POLY1305_AEAD_64BYTES_ONLY_ENCRYPT)
BENCHMARK() [2/9]
BENCHMARK (CHACHA20_POLY1305_AEAD_256BYTES_ONLY_ENCRYPT)
BENCHMARK() [3/9]
BENCHMARK (CHACHA20_POLY1305_AEAD_1MB_ONLY_ENCRYPT)
BENCHMARK() [4/9]
BENCHMARK (CHACHA20_POLY1305_AEAD_64BYTES_ENCRYPT_DECRYPT)
BENCHMARK() [5/9]
BENCHMARK (CHACHA20_POLY1305_AEAD_256BYTES_ENCRYPT_DECRYPT)
BENCHMARK() [6/9]
BENCHMARK (CHACHA20_POLY1305_AEAD_1MB_ENCRYPT_DECRYPT)
BENCHMARK() [7/9]
BENCHMARK (HASH_64BYTES)
BENCHMARK() [8/9]
BENCHMARK (HASH_256BYTES)
BENCHMARK() [9/9]
BENCHMARK (HASH_1MB)
CHACHA20_POLY1305_AEAD()
static void CHACHA20_POLY1305_AEAD (benchmark::State & state, size_t buffersize, bool include_decryption) static
Definition at line 25 of file chacha_poly_aead.cpp.
References aead, CHACHA20_POLY1305_AEAD_AAD_LEN, CHACHA20_ROUND_OUTPUT, ChaCha20Poly1305AEAD::Crypt(), ChaCha20Poly1305AEAD::GetLength(), benchmark::State::KeepRunning(), and POLY1305_TAGLEN.
Referenced by CHACHA20_POLY1305_AEAD_1MB_ENCRYPT_DECRYPT(), CHACHA20_POLY1305_AEAD_1MB_ONLY_ENCRYPT(), CHACHA20_POLY1305_AEAD_256BYTES_ENCRYPT_DECRYPT(), CHACHA20_POLY1305_AEAD_256BYTES_ONLY_ENCRYPT(), CHACHA20_POLY1305_AEAD_64BYTES_ENCRYPT_DECRYPT(), and CHACHA20_POLY1305_AEAD_64BYTES_ONLY_ENCRYPT().
CHACHA20_POLY1305_AEAD_1MB_ENCRYPT_DECRYPT()
static void CHACHA20_POLY1305_AEAD_1MB_ENCRYPT_DECRYPT (benchmark::State & state) static
Definition at line 85 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_LARGE, and CHACHA20_POLY1305_AEAD().
CHACHA20_POLY1305_AEAD_1MB_ONLY_ENCRYPT()
static void CHACHA20_POLY1305_AEAD_1MB_ONLY_ENCRYPT (benchmark::State & state) static
Definition at line 70 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_LARGE, and CHACHA20_POLY1305_AEAD().
CHACHA20_POLY1305_AEAD_256BYTES_ENCRYPT_DECRYPT()
static void CHACHA20_POLY1305_AEAD_256BYTES_ENCRYPT_DECRYPT (benchmark::State & state) static
Definition at line 80 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_SMALL, and CHACHA20_POLY1305_AEAD().
CHACHA20_POLY1305_AEAD_256BYTES_ONLY_ENCRYPT()
static void CHACHA20_POLY1305_AEAD_256BYTES_ONLY_ENCRYPT (benchmark::State & state) static
Definition at line 65 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_SMALL, and CHACHA20_POLY1305_AEAD().
CHACHA20_POLY1305_AEAD_64BYTES_ENCRYPT_DECRYPT()
static void CHACHA20_POLY1305_AEAD_64BYTES_ENCRYPT_DECRYPT (benchmark::State & state) static
Definition at line 75 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_TINY, and CHACHA20_POLY1305_AEAD().
CHACHA20_POLY1305_AEAD_64BYTES_ONLY_ENCRYPT()
static void CHACHA20_POLY1305_AEAD_64BYTES_ONLY_ENCRYPT (benchmark::State & state) static
Definition at line 60 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_TINY, and CHACHA20_POLY1305_AEAD().
HASH()
static void HASH (benchmark::State & state, size_t buffersize) static
Definition at line 92 of file chacha_poly_aead.cpp.
References benchmark::State::KeepRunning(), CHash256::OUTPUT_SIZE, and CHash256::Write().
Referenced by HASH_1MB(), HASH_256BYTES(), and HASH_64BYTES().
HASH_1MB()
static void HASH_1MB (benchmark::State & state) static
Definition at line 110 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_LARGE, and HASH().
HASH_256BYTES()
static void HASH_256BYTES (benchmark::State & state) static
Definition at line 105 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_SMALL, and HASH().
HASH_64BYTES()
static void HASH_64BYTES (benchmark::State & state) static
Definition at line 100 of file chacha_poly_aead.cpp.
References BUFFER_SIZE_TINY, and HASH().
Variable Documentation
aead
ChaCha20Poly1305AEAD aead(k1, 32, k2, 32) static
Referenced by CHACHA20_POLY1305_AEAD().
BUFFER_SIZE_LARGE
constexpr uint64_t BUFFER_SIZE_LARGE = 1024 * 1024 static
Definition at line 18 of file chacha_poly_aead.cpp.
Referenced by CHACHA20_POLY1305_AEAD_1MB_ENCRYPT_DECRYPT(), CHACHA20_POLY1305_AEAD_1MB_ONLY_ENCRYPT(), and HASH_1MB().
BUFFER_SIZE_SMALL
constexpr uint64_t BUFFER_SIZE_SMALL = 256 static
Definition at line 17 of file chacha_poly_aead.cpp.
Referenced by CHACHA20_POLY1305_AEAD_256BYTES_ENCRYPT_DECRYPT(), CHACHA20_POLY1305_AEAD_256BYTES_ONLY_ENCRYPT(), and HASH_256BYTES().
BUFFER_SIZE_TINY
constexpr uint64_t BUFFER_SIZE_TINY = 64 static
Definition at line 16 of file chacha_poly_aead.cpp.
Referenced by CHACHA20_POLY1305_AEAD_64BYTES_ENCRYPT_DECRYPT(), CHACHA20_POLY1305_AEAD_64BYTES_ONLY_ENCRYPT(), and HASH_64BYTES().
k1
const unsigned char k1[32] = {0} static
Definition at line 20 of file chacha_poly_aead.cpp.
Referenced by SaltedHasherImpl< std::pair< uint256, N > >::CalcHash(), SaltedHasherImpl< std::pair< N, uint256 > >::CalcHash(), SaltedHasherImpl< uint256 >::CalcHash(), CSipHasher::CSipHasher(), llmq::CRecoveredSigsDb::GetRecoveredSigByHash(), MurmurHash3(), llmq::CRecoveredSigsDb::RemoveRecoveredSig(), SipHashUint256(), SipHashUint256Extra(), llmq::CRecoveredSigsDb::WriteRecoveredSig(), and llmq::CRecoveredSigsDb::WriteVoteForId().
k2
const unsigned char k2[32] = {0} static
Definition at line 21 of file chacha_poly_aead.cpp.
Referenced by llmq::CRecoveredSigsDb::AddVoteTimeKeys(), llmq::CRecoveredSigsDb::GetRecoveredSigByHash(), llmq::CRecoveredSigsDb::RemoveRecoveredSig(), llmq::CRecoveredSigsDb::WriteRecoveredSig(), and llmq::CRecoveredSigsDb::WriteVoteForId().
Released under the MIT license