Dash Core: src/bench/chacha20.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
chacha20.cpp File Reference
#include <iostream>
#include <bench/bench.h>
#include <hash.h>
#include <crypto/chacha20.h>
Functions
static void CHACHA20 (benchmark::State &state, size_t buffersize)
static void CHACHA20_64BYTES (benchmark::State &state)
static void CHACHA20_256BYTES (benchmark::State &state)
static void CHACHA20_1MB (benchmark::State &state)
BENCHMARK (CHACHA20_64BYTES)
BENCHMARK (CHACHA20_256BYTES)
BENCHMARK (CHACHA20_1MB)
Variables
static const uint64_t BUFFER_SIZE_TINY = 64
static const uint64_t BUFFER_SIZE_SMALL = 256
static const uint64_t BUFFER_SIZE_LARGE = 1024*1024
Function Documentation
BENCHMARK() [1/3]
BENCHMARK (CHACHA20_64BYTES)
BENCHMARK() [2/3]
BENCHMARK (CHACHA20_256BYTES)
BENCHMARK() [3/3]
BENCHMARK (CHACHA20_1MB)
CHACHA20()
static void CHACHA20 (benchmark::State & state, size_t buffersize) static
Definition at line 16 of file chacha20.cpp.
References ctx, and benchmark::State::KeepRunning().
Referenced by CHACHA20_1MB(), CHACHA20_256BYTES(), and CHACHA20_64BYTES().
CHACHA20_1MB()
static void CHACHA20_1MB (benchmark::State & state) static
Definition at line 39 of file chacha20.cpp.
References BUFFER_SIZE_LARGE, and CHACHA20().
CHACHA20_256BYTES()
static void CHACHA20_256BYTES (benchmark::State & state) static
Definition at line 34 of file chacha20.cpp.
References BUFFER_SIZE_SMALL, and CHACHA20().
CHACHA20_64BYTES()
static void CHACHA20_64BYTES (benchmark::State & state) static
Definition at line 29 of file chacha20.cpp.
References BUFFER_SIZE_TINY, and CHACHA20().
Variable Documentation
BUFFER_SIZE_LARGE
const uint64_t BUFFER_SIZE_LARGE = 1024*1024 static
Definition at line 14 of file chacha20.cpp.
Referenced by CHACHA20_1MB().
BUFFER_SIZE_SMALL
const uint64_t BUFFER_SIZE_SMALL = 256 static
Definition at line 13 of file chacha20.cpp.
Referenced by CHACHA20_256BYTES().
BUFFER_SIZE_TINY
const uint64_t BUFFER_SIZE_TINY = 64 static
Definition at line 12 of file chacha20.cpp.
Referenced by CHACHA20_64BYTES().
Released under the MIT license