Dash Core: src/bench/bls.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bls.cpp File Reference
#include <bench/bench.h>
#include <random.h>
#include <bls/bls_worker.h>
#include <utiltime.h>
#include <iostream>
Functions
void InitBLSTests ()
void CleanupBLSTests ()
static void BuildTestVectors (size_t count, size_t invalidCount, BLSPublicKeyVector &pubKeys, BLSSecretKeyVector &secKeys, BLSSignatureVector &sigs, std::vector< uint256 > &msgHashes, std::vector< bool > &invalid)
static void BLSPubKeyAggregate_Normal (benchmark::State &state)
static void BLSSecKeyAggregate_Normal (benchmark::State &state)
static void BLSSign_Normal (benchmark::State &state)
static void BLSVerify_Normal (benchmark::State &state)
static void BLSVerify_LargeBlock (size_t txCount, benchmark::State &state)
static void BLSVerify_LargeBlock1000 (benchmark::State &state)
static void BLSVerify_LargeBlock10000 (benchmark::State &state)
static void BLSVerify_LargeBlockSelfAggregated (size_t txCount, benchmark::State &state)
static void BLSVerify_LargeBlockSelfAggregated1000 (benchmark::State &state)
static void BLSVerify_LargeBlockSelfAggregated10000 (benchmark::State &state)
static void BLSVerify_LargeAggregatedBlock (size_t txCount, benchmark::State &state)
static void BLSVerify_LargeAggregatedBlock1000 (benchmark::State &state)
static void BLSVerify_LargeAggregatedBlock10000 (benchmark::State &state)
static void BLSVerify_LargeAggregatedBlock1000PreVerified (benchmark::State &state)
static void BLSVerify_Batched (benchmark::State &state)
static void BLSVerify_BatchedParallel (benchmark::State &state)
Variables
CBLSWorker blsWorker
Function Documentation
BLSPubKeyAggregate_Normal()
static void BLSPubKeyAggregate_Normal (benchmark::State & state) static
Definition at line 54 of file bls.cpp.
References CBLSPublicKey::AggregateInsecure(), CBLSSecretKey::GetPublicKey(), benchmark::State::KeepRunning(), and CBLSSecretKey::MakeNewKey().
BLSSecKeyAggregate_Normal()
static void BLSSecKeyAggregate_Normal (benchmark::State & state) static
Definition at line 69 of file bls.cpp.
References CBLSSecretKey::AggregateInsecure(), CBLSSecretKey::GetPublicKey(), benchmark::State::KeepRunning(), and CBLSSecretKey::MakeNewKey().
BLSSign_Normal()
static void BLSSign_Normal (benchmark::State & state) static
Definition at line 84 of file bls.cpp.
References CBLSSecretKey::GetPublicKey(), GetRandHash(), benchmark::State::KeepRunning(), CBLSSecretKey::MakeNewKey(), and CBLSSecretKey::Sign().
BLSVerify_Batched()
static void BLSVerify_Batched (benchmark::State & state) static
Definition at line 248 of file bls.cpp.
References CBLSSignature::AggregateInsecure(), BuildTestVectors(), benchmark::State::KeepRunning(), and CBLSSignature::VerifyInsecureAggregated().
BLSVerify_BatchedParallel()
static void BLSVerify_BatchedParallel (benchmark::State & state) static
Definition at line 304 of file bls.cpp.
References CBLSWorker::AsyncVerifySig(), blsWorker, BuildTestVectors(), CBLSWorker::IsAsyncVerifyInProgress(), benchmark::State::KeepRunning(), and MilliSleep().
BLSVerify_LargeAggregatedBlock()
static void BLSVerify_LargeAggregatedBlock (size_t txCount, benchmark::State & state) static
Definition at line 175 of file bls.cpp.
References CBLSSignature::AggregateInsecure(), BuildTestVectors(), benchmark::State::KeepRunning(), and CBLSSignature::VerifyInsecureAggregated().
Referenced by BLSVerify_LargeAggregatedBlock1000(), and BLSVerify_LargeAggregatedBlock10000().
BLSVerify_LargeAggregatedBlock1000()
static void BLSVerify_LargeAggregatedBlock1000 (benchmark::State & state) static
Definition at line 192 of file bls.cpp.
References BLSVerify_LargeAggregatedBlock().
BLSVerify_LargeAggregatedBlock10000()
static void BLSVerify_LargeAggregatedBlock10000 (benchmark::State & state) static
Definition at line 197 of file bls.cpp.
References BLSVerify_LargeAggregatedBlock().
BLSVerify_LargeAggregatedBlock1000PreVerified()
static void BLSVerify_LargeAggregatedBlock1000PreVerified (benchmark::State & state) static
Definition at line 202 of file bls.cpp.
References CBLSSignature::AggregateInsecure(), BuildTestVectors(), GetRandInt(), benchmark::State::KeepRunning(), CBLSSignature::SubInsecure(), and CBLSSignature::VerifyInsecureAggregated().
BLSVerify_LargeBlock()
static void BLSVerify_LargeBlock (size_t txCount, benchmark::State & state) static
Definition at line 122 of file bls.cpp.
References BuildTestVectors(), and benchmark::State::KeepRunning().
Referenced by BLSVerify_LargeBlock1000(), and BLSVerify_LargeBlock10000().
BLSVerify_LargeBlock1000()
static void BLSVerify_LargeBlock1000 (benchmark::State & state) static
Definition at line 139 of file bls.cpp.
References BLSVerify_LargeBlock().
BLSVerify_LargeBlock10000()
static void BLSVerify_LargeBlock10000 (benchmark::State & state) static
Definition at line 144 of file bls.cpp.
References BLSVerify_LargeBlock().
BLSVerify_LargeBlockSelfAggregated()
static void BLSVerify_LargeBlockSelfAggregated (size_t txCount, benchmark::State & state) static
Definition at line 149 of file bls.cpp.
References CBLSSignature::AggregateInsecure(), BuildTestVectors(), benchmark::State::KeepRunning(), and CBLSSignature::VerifyInsecureAggregated().
Referenced by BLSVerify_LargeBlockSelfAggregated1000(), and BLSVerify_LargeBlockSelfAggregated10000().
BLSVerify_LargeBlockSelfAggregated1000()
static void BLSVerify_LargeBlockSelfAggregated1000 (benchmark::State & state) static
Definition at line 165 of file bls.cpp.
References BLSVerify_LargeBlockSelfAggregated().
BLSVerify_LargeBlockSelfAggregated10000()
static void BLSVerify_LargeBlockSelfAggregated10000 (benchmark::State & state) static
Definition at line 170 of file bls.cpp.
References BLSVerify_LargeBlockSelfAggregated().
BLSVerify_Normal()
static void BLSVerify_Normal (benchmark::State & state) static
Definition at line 97 of file bls.cpp.
References BuildTestVectors(), and benchmark::State::KeepRunning().
BuildTestVectors()
static void BuildTestVectors (size_t count, size_t invalidCount, BLSPublicKeyVector & pubKeys, BLSSecretKeyVector & secKeys, BLSSignatureVector & sigs, std::vector< uint256 > & msgHashes, std::vector< bool > & invalid) static
Definition at line 24 of file bls.cpp.
References count, GetRandHash(), CBLSSecretKey::MakeNewKey(), and CBLSSecretKey::Sign().
Referenced by BLSVerify_Batched(), BLSVerify_BatchedParallel(), BLSVerify_LargeAggregatedBlock(), BLSVerify_LargeAggregatedBlock1000PreVerified(), BLSVerify_LargeBlock(), BLSVerify_LargeBlockSelfAggregated(), and BLSVerify_Normal().
CleanupBLSTests()
void CleanupBLSTests ()
Definition at line 19 of file bls.cpp.
References blsWorker, and CBLSWorker::Stop().
Referenced by main().
InitBLSTests()
void InitBLSTests ()
Definition at line 14 of file bls.cpp.
References blsWorker, and CBLSWorker::Start().
Referenced by main().
Variable Documentation
blsWorker
CBLSWorker blsWorker
Definition at line 12 of file bls.cpp.
Referenced by BLSVerify_BatchedParallel(), CleanupBLSTests(), and InitBLSTests().
Released under the MIT license