Dash Core: src/qt/bitcoingui.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
bitcoingui.cpp File Reference
#include "bitcoingui.h"
#include "bitcoinunits.h"
#include "clientmodel.h"
#include "guiconstants.h"
#include "guiutil.h"
#include "modaloverlay.h"
#include "networkstyle.h"
#include "notificator.h"
#include "openuridialog.h"
#include "optionsdialog.h"
#include "optionsmodel.h"
#include "platformstyle.h"
#include "rpcconsole.h"
#include "utilitydialog.h"
#include "chainparams.h"
#include "init.h"
#include "ui_interface.h"
#include "util.h"
#include "masternode-sync.h"
#include "masternodelist.h"
#include <iostream>
#include <QAction>
#include <QApplication>
#include <QDateTime>
#include <QDesktopWidget>
#include <QDragEnterEvent>
#include <QListWidget>
#include <QMenuBar>
#include <QMessageBox>
#include <QMimeData>
#include <QProgressDialog>
#include <QSettings>
#include <QShortcut>
#include <QStackedWidget>
#include <QStatusBar>
#include <QStyle>
#include <QTimer>
#include <QToolBar>
#include <QVBoxLayout>
#include <QTextDocument>
#include <QUrl>
Functions
static bool ThreadSafeMessageBox (BitcoinGUI *gui, const std::string &message, const std::string &caption, unsigned int style)
Function Documentation
ThreadSafeMessageBox()
static bool ThreadSafeMessageBox (BitcoinGUI * gui, const std::string & message, const std::string & caption, unsigned int style) static
Definition at line 1419 of file bitcoingui.cpp.
References GUIUtil::blockingGUIThreadConnection(), and CClientUIInterface::MODAL.
Referenced by BitcoinGUI::subscribeToCoreSignals(), and BitcoinGUI::unsubscribeFromCoreSignals().
Released under the MIT license