Dash Core: src/bls/bls_ies.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bls_ies.cpp File Reference
#include <bls/bls_ies.h>
#include <hash.h>
#include <random.h>
#include <streams.h>
#include <crypto/aes.h>
Functions
template<typename Out >
static bool EncryptBlob (const void *in, size_t inSize, Out &out, const void *symKey, const void *iv)
template<typename Out >
static bool DecryptBlob (const void *in, size_t inSize, Out &out, const void *symKey, const void *iv)
Function Documentation
DecryptBlob()
template<typename Out > static bool DecryptBlob (const void * in, size_t inSize, Out & out, const void * symKey, const void * iv) static
Definition at line 24 of file bls_ies.cpp.
References AES256CBCDecrypt::Decrypt().
Referenced by CBLSIESEncryptedBlob::Decrypt(), and CBLSIESMultiRecipientBlobs::Decrypt().
EncryptBlob()
template<typename Out > static bool EncryptBlob (const void * in, size_t inSize, Out & out, const void * symKey, const void * iv) static
Definition at line 14 of file bls_ies.cpp.
References AES256CBCEncrypt::Encrypt().
Referenced by CBLSIESEncryptedBlob::Encrypt(), and CBLSIESMultiRecipientBlobs::Encrypt().
Released under the MIT license