Dash Core: src/bls/bls.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bls.cpp File Reference
#include <bls/bls.h>
#include <hash.h>
#include <random.h>
#include <tinyformat.h>
#include <support/allocators/mt_pooled_secure.h>
#include <assert.h>
#include <string.h>
Functions
static void create_secure_allocator ()
static mt_pooled_secure_allocator< uint8_t > & get_secure_allocator ()
static void * secure_allocate (size_t n)
static void secure_free (void *p)
bool BLSInit ()
Variables
static std::once_flag init_flag
static mt_pooled_secure_allocator< uint8_t > * secure_allocator_instance
Function Documentation
BLSInit()
bool BLSInit ()
Definition at line 466 of file bls.cpp.
References secure_allocate(), and secure_free().
Referenced by InitSanityCheck(), and main().
create_secure_allocator()
static void create_secure_allocator () static
Definition at line 430 of file bls.cpp.
References LockedPoolManager::Instance(), and secure_allocator_instance.
Referenced by get_secure_allocator().
get_secure_allocator()
static mt_pooled_secure_allocator<uint8_t>& get_secure_allocator () static
Definition at line 441 of file bls.cpp.
References create_secure_allocator(), init_flag, and secure_allocator_instance.
Referenced by secure_allocate(), and secure_free().
secure_allocate()
static void* secure_allocate (size_t n) static
Definition at line 447 of file bls.cpp.
References get_secure_allocator().
Referenced by BLSInit().
secure_free()
static void secure_free (void * p) static
Definition at line 454 of file bls.cpp.
References get_secure_allocator().
Referenced by BLSInit().
Variable Documentation
init_flag
std::once_flag init_flag static
Definition at line 428 of file bls.cpp.
Referenced by get_secure_allocator().
secure_allocator_instance
mt_pooled_secure_allocator<uint8_t>* secure_allocator_instance static
Definition at line 429 of file bls.cpp.
Referenced by create_secure_allocator(), and get_secure_allocator().
Released under the MIT license