Dash Core: src/bls/bls.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bls.h File Reference
#include <hash.h>
#include <serialize.h>
#include <uint256.h>
#include <utilstrencodings.h>
#include <chiabls/bls.hpp>
#include <chiabls/privatekey.hpp>
#include <chiabls/publickey.hpp>
#include <chiabls/signature.hpp>
#include <array>
#include <mutex>
#include <unistd.h>
Classes
class CBLSWrapper< ImplType, _SerSize, C >
class CBLSId
class CBLSSecretKey
class CBLSPublicKey
class CBLSSignature
class CBLSLazyWrapper< BLSObject >
Macros
#define BLS_CURVE_ID_SIZE 32
#define BLS_CURVE_SECKEY_SIZE 32
#define BLS_CURVE_PUBKEY_SIZE 48
#define BLS_CURVE_SIG_SIZE 96
Typedefs
typedef CBLSLazyWrapper< CBLSSignature > CBLSLazySignature
typedef CBLSLazyWrapper< CBLSPublicKey > CBLSLazyPublicKey
typedef CBLSLazyWrapper< CBLSSecretKey > CBLSLazySecretKey
typedef std::vector< CBLSId > BLSIdVector
typedef std::vector< CBLSPublicKey > BLSVerificationVector
typedef std::vector< CBLSPublicKey > BLSPublicKeyVector
typedef std::vector< CBLSSecretKey > BLSSecretKeyVector
typedef std::vector< CBLSSignature > BLSSignatureVector
typedef std::shared_ptr< BLSIdVector > BLSIdVectorPtr
typedef std::shared_ptr< BLSVerificationVector > BLSVerificationVectorPtr
typedef std::shared_ptr< BLSPublicKeyVector > BLSPublicKeyVectorPtr
typedef std::shared_ptr< BLSSecretKeyVector > BLSSecretKeyVectorPtr
typedef std::shared_ptr< BLSSignatureVector > BLSSignatureVectorPtr
Functions
bool BLSInit ()
Macro Definition Documentation
BLS_CURVE_ID_SIZE
#define BLS_CURVE_ID_SIZE 32
Definition at line 25 of file bls.h.
BLS_CURVE_PUBKEY_SIZE
#define BLS_CURVE_PUBKEY_SIZE 48
Definition at line 27 of file bls.h.
BLS_CURVE_SECKEY_SIZE
#define BLS_CURVE_SECKEY_SIZE 32
Definition at line 26 of file bls.h.
BLS_CURVE_SIG_SIZE
#define BLS_CURVE_SIG_SIZE 96
Definition at line 28 of file bls.h.
Typedef Documentation
BLSIdVector
typedef std::vector<CBLSId> BLSIdVector
Definition at line 464 of file bls.h.
BLSIdVectorPtr
typedef std::shared_ptr<BLSIdVector> BLSIdVectorPtr
Definition at line 470 of file bls.h.
BLSPublicKeyVector
typedef std::vector<CBLSPublicKey> BLSPublicKeyVector
Definition at line 466 of file bls.h.
BLSPublicKeyVectorPtr
typedef std::shared_ptr<BLSPublicKeyVector> BLSPublicKeyVectorPtr
Definition at line 472 of file bls.h.
BLSSecretKeyVector
typedef std::vector<CBLSSecretKey> BLSSecretKeyVector
Definition at line 467 of file bls.h.
BLSSecretKeyVectorPtr
typedef std::shared_ptr<BLSSecretKeyVector> BLSSecretKeyVectorPtr
Definition at line 473 of file bls.h.
BLSSignatureVector
typedef std::vector<CBLSSignature> BLSSignatureVector
Definition at line 468 of file bls.h.
BLSSignatureVectorPtr
typedef std::shared_ptr<BLSSignatureVector> BLSSignatureVectorPtr
Definition at line 474 of file bls.h.
BLSVerificationVector
typedef std::vector<CBLSPublicKey> BLSVerificationVector
Definition at line 465 of file bls.h.
BLSVerificationVectorPtr
typedef std::shared_ptr<BLSVerificationVector> BLSVerificationVectorPtr
Definition at line 471 of file bls.h.
CBLSLazyPublicKey
typedef CBLSLazyWrapper<CBLSPublicKey> CBLSLazyPublicKey
Definition at line 460 of file bls.h.
CBLSLazySecretKey
typedef CBLSLazyWrapper<CBLSSecretKey> CBLSLazySecretKey
Definition at line 461 of file bls.h.
CBLSLazySignature
typedef CBLSLazyWrapper<CBLSSignature> CBLSLazySignature
Definition at line 459 of file bls.h.
Function Documentation
BLSInit()
bool BLSInit ()
Definition at line 466 of file bls.cpp.
References secure_allocate(), and secure_free().
Referenced by InitSanityCheck(), and main().
Released under the MIT license