Dash Core: src/bls/bls_worker.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bls_worker.cpp File Reference
#include <bls/bls_worker.h>
#include <hash.h>
#include <serialize.h>
#include <util.h>
Classes
struct Aggregator< T >
struct VectorAggregator< T >
struct ContributionVerifier
struct ContributionVerifier::BatchState
Functions
template<typename T >
bool VerifyVectorHelper (const std::vector< T > &vec, size_t start, size_t count)
template<typename T >
std::pair< std::function< void(const T &)>, std::future< T > > BuildFutureDoneCallback ()
template<typename T >
std::pair< std::function< void(T)>, std::future< T > > BuildFutureDoneCallback2 ()
template<typename T >
void AsyncAggregateHelper (ctpl::thread_pool &workerPool, const std::vector< T > &vec, size_t start, size_t count, bool parallel, std::function< void(const T &)> doneCallback)
Function Documentation
AsyncAggregateHelper()
template<typename T > void AsyncAggregateHelper (ctpl::thread_pool & workerPool, const std::vector< T > & vec, size_t start, size_t count, bool parallel, std::function< void(const T &)> doneCallback)
Definition at line 635 of file bls_worker.cpp.
References count, Aggregator< T >::Start(), and VerifyVectorHelper().
Referenced by CBLSWorker::AsyncAggregatePublicKeys(), CBLSWorker::AsyncAggregateSecretKeys(), and CBLSWorker::AsyncAggregateSigs().
BuildFutureDoneCallback()
template<typename T > std::pair<std::function<void(const T&)>, std::future<T> > BuildFutureDoneCallback ()
Definition at line 31 of file bls_worker.cpp.
BuildFutureDoneCallback2()
template<typename T > std::pair<std::function<void(T)>, std::future<T> > BuildFutureDoneCallback2 ()
Definition at line 40 of file bls_worker.cpp.
VerifyVectorHelper()
template<typename T > bool VerifyVectorHelper (const std::vector< T > & vec, size_t start, size_t count)
Definition at line 12 of file bls_worker.cpp.
References count.
Referenced by AsyncAggregateHelper(), CBLSWorker::VerifySecretKeyVector(), CBLSWorker::VerifySignatureVector(), and CBLSWorker::VerifyVerificationVector().
Released under the MIT license