Dash Core: src/compat/byteswap.h File Reference
byteswap.h File Reference
#include <stdint.h>
Functions
uint16_t bswap_16 (uint16_t x)
uint32_t bswap_32 (uint32_t x)
uint64_t bswap_64 (uint64_t x)
Function Documentation
bswap_16()
uint16_t bswap_16 (uint16_t x) inline
Definition at line 36 of file byteswap.h.
Referenced by be16toh().
bswap_32()
uint32_t bswap_32 (uint32_t x) inline
Definition at line 43 of file byteswap.h.
Referenced by be32toh(), and htobe32().
bswap_64()
uint64_t bswap_64 (uint64_t x) inline
Definition at line 51 of file byteswap.h.
Referenced by be64toh(), and htobe64().