Dash Core: src/bench/ccoins_caching.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
ccoins_caching.cpp File Reference
#include <bench/bench.h>
#include <coins.h>
#include <policy/policy.h>
#include <wallet/crypter.h>
#include <vector>
Functions
static std::vector< CMutableTransaction > SetupDummyInputs (CBasicKeyStore &keystoreRet, CCoinsViewCache &coinsRet)
static void CCoinsCaching (benchmark::State &state)
BENCHMARK (CCoinsCaching)
Function Documentation
BENCHMARK()
BENCHMARK (CCoinsCaching)
CCoinsCaching()
static void CCoinsCaching (benchmark::State & state) static
Definition at line 56 of file ccoins_caching.cpp.
References AreInputsStandard(), CENT, CCoinsViewCache::GetValueIn(), benchmark::State::KeepRunning(), OP_1, SetupDummyInputs(), CMutableTransaction::vin, and CMutableTransaction::vout.
SetupDummyInputs()
static std::vector<CMutableTransaction> SetupDummyInputs (CBasicKeyStore & keystoreRet, CCoinsViewCache & coinsRet) static
Definition at line 20 of file ccoins_caching.cpp.
References AddCoins(), CKeyStore::AddKey(), CENT, GetScriptForDestination(), CKey::MakeNewKey(), OP_CHECKSIG, and ToByteVector().
Referenced by CCoinsCaching().
Released under the MIT license