Dash Core: src/bench/checkqueue.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
checkqueue.cpp File Reference
#include <bench/bench.h>
#include <util.h>
#include <validation.h>
#include <checkqueue.h>
#include <prevector.h>
#include <vector>
#include <boost/thread/thread.hpp>
#include <random.h>
Functions
static void CCheckQueueSpeed (benchmark::State &state)
static void CCheckQueueSpeedPrevectorJob (benchmark::State &state)
BENCHMARK (CCheckQueueSpeed)
BENCHMARK (CCheckQueueSpeedPrevectorJob)
Variables
static const int MIN_CORES = 2
static const size_t BATCHES = 101
static const size_t BATCH_SIZE = 30
static const int PREVECTOR_SIZE = 28
static const unsigned int QUEUE_BATCH_SIZE = 128
Function Documentation
BENCHMARK() [1/2]
BENCHMARK (CCheckQueueSpeed)
BENCHMARK() [2/2]
BENCHMARK (CCheckQueueSpeedPrevectorJob)
CCheckQueueSpeed()
static void CCheckQueueSpeed (benchmark::State & state) static
Definition at line 23 of file checkqueue.cpp.
References CCheckQueueControl< T >::Add(), BATCH_SIZE, BATCHES, GetNumCores(), benchmark::State::KeepRunning(), MIN_CORES, QUEUE_BATCH_SIZE, and CCheckQueueControl< T >::Wait().
CCheckQueueSpeedPrevectorJob()
static void CCheckQueueSpeedPrevectorJob (benchmark::State & state) static
Definition at line 64 of file checkqueue.cpp.
References CCheckQueueControl< T >::Add(), BATCH_SIZE, BATCHES, GetNumCores(), benchmark::State::KeepRunning(), MIN_CORES, PREVECTOR_SIZE, QUEUE_BATCH_SIZE, FastRandomContext::randrange(), prevector< N, T, Size, Diff >::resize(), prevector< N, T, Size, Diff >::swap(), and CCheckQueueControl< T >::Wait().
Variable Documentation
BATCH_SIZE
const size_t BATCH_SIZE = 30 static
Definition at line 20 of file checkqueue.cpp.
Referenced by CCheckQueueSpeed(), and CCheckQueueSpeedPrevectorJob().
BATCHES
const size_t BATCHES = 101 static
Definition at line 19 of file checkqueue.cpp.
Referenced by CCheckQueueSpeed(), and CCheckQueueSpeedPrevectorJob().
MIN_CORES
const int MIN_CORES = 2 static
Definition at line 18 of file checkqueue.cpp.
Referenced by CCheckQueueSpeed(), and CCheckQueueSpeedPrevectorJob().
PREVECTOR_SIZE
const int PREVECTOR_SIZE = 28 static
Definition at line 21 of file checkqueue.cpp.
Referenced by CCheckQueueSpeedPrevectorJob().
QUEUE_BATCH_SIZE
const unsigned int QUEUE_BATCH_SIZE = 128 static
Definition at line 22 of file checkqueue.cpp.
Referenced by CCheckQueueSpeed(), and CCheckQueueSpeedPrevectorJob().
Released under the MIT license