Dash Core: CVerifyDB Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CVerifyDB Class Reference
RAII wrapper for VerifyDB: Verify consistency of the block and coin databases.
#include <validation.h>
Public Member Functions
CVerifyDB ()
~CVerifyDB ()
bool VerifyDB (const CChainParams &chainparams, CCoinsView *coinsview, int nCheckLevel, int nCheckDepth)
Detailed Description
RAII wrapper for VerifyDB: Verify consistency of the block and coin databases.
Definition at line 426 of file validation.h.
Constructor & Destructor Documentation
CVerifyDB()
CVerifyDB::CVerifyDB ()
Definition at line 4243 of file validation.cpp.
References _(), CClientUIInterface::ShowProgress, and uiInterface.
~CVerifyDB()
CVerifyDB::~CVerifyDB ()
Definition at line 4248 of file validation.cpp.
References CClientUIInterface::ShowProgress, and uiInterface.
Member Function Documentation
VerifyDB()
bool CVerifyDB::VerifyDB (const CChainParams & chainparams, CCoinsView * coinsview, int nCheckLevel, int nCheckDepth)
Definition at line 4253 of file validation.cpp.
References _(), BLOCK_HAVE_DATA, chainActive, CheckBlock(), CChainState::ConnectBlock(), cs_main, DISCONNECT_FAILED, DISCONNECT_UNCLEAN, CChainState::DisconnectBlock(), CCoinsViewCache::DynamicMemoryUsage(), error(), evoDb, FormatStateMessage(), fPruneMode, g_chainstate, CCoinsViewCache::GetBestBlock(), CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), CBlockIndex::GetUndoPos(), CChain::Height(), CDiskBlockPos::IsNull(), LOCK, LogPrintf, nCoinCacheUsage, CChain::Next(), CBlockIndex::nHeight, CBlockIndex::nStatus, pcoinsTip, CBlockIndex::pprev, ReadBlockFromDisk(), CClientUIInterface::ShowProgress, ShutdownRequested(), CChain::Tip(), base_blob< BITS >::ToString(), uiInterface, and CBlock::vtx.
Referenced by verifychain().
The documentation for this class was generated from the following files:
src/validation.h
src/validation.cpp
Released under the MIT license