Dash Core: ReceiveCoinsDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
ReceiveCoinsDialog Class Reference
Dialog for requesting payment of bitcoins.
#include <receivecoinsdialog.h>
Public Types
enum ColumnWidths { DATE_COLUMN_WIDTH = 130, LABEL_COLUMN_WIDTH = 120, AMOUNT_MINIMUM_COLUMN_WIDTH = 180, MINIMUM_COLUMN_WIDTH = 130 }
Public Slots
void clear ()
void reject () override
void accept () override
Public Member Functions
ReceiveCoinsDialog (QWidget *parent=0)
~ReceiveCoinsDialog ()
void setModel (WalletModel *model)
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event) override
Private Slots
void on_receiveButton_clicked ()
void on_showRequestButton_clicked ()
void on_removeRequestButton_clicked ()
void on_recentRequestsView_doubleClicked (const QModelIndex &index)
void recentRequestsView_selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
void updateDisplayUnit ()
void showMenu (const QPoint &point)
void copyURI ()
void copyLabel ()
void copyMessage ()
void copyAmount ()
Private Member Functions
QModelIndex selectedRow ()
void copyColumnToClipboard (int column)
virtual void resizeEvent (QResizeEvent *event) override
Private Attributes
Ui::ReceiveCoinsDialog * ui
GUIUtil::TableViewLastColumnResizingFixer * columnResizingFixer
WalletModel * model
QMenu * contextMenu
Detailed Description
Dialog for requesting payment of bitcoins.
Definition at line 29 of file receivecoinsdialog.h.
Member Enumeration Documentation
ColumnWidths
enum ReceiveCoinsDialog::ColumnWidths
Enumerator
DATE_COLUMN_WIDTH
LABEL_COLUMN_WIDTH
AMOUNT_MINIMUM_COLUMN_WIDTH
MINIMUM_COLUMN_WIDTH
Definition at line 34 of file receivecoinsdialog.h.
Constructor & Destructor Documentation
ReceiveCoinsDialog()
ReceiveCoinsDialog::ReceiveCoinsDialog (QWidget * parent = 0) explicit
Definition at line 22 of file receivecoinsdialog.cpp.
References GUIUtil::Bold, clear(), contextMenu, copyAmount(), copyLabel(), copyMessage(), copyURI(), GUIUtil::Normal, GUIUtil::setFont(), showMenu(), ui, and GUIUtil::updateFonts().
~ReceiveCoinsDialog()
ReceiveCoinsDialog::~ReceiveCoinsDialog ()
Definition at line 94 of file receivecoinsdialog.cpp.
References ui.
Member Function Documentation
accept
void ReceiveCoinsDialog::accept () override slot
Definition at line 112 of file receivecoinsdialog.cpp.
References clear().
clear
void ReceiveCoinsDialog::clear () slot
Definition at line 99 of file receivecoinsdialog.cpp.
References ui, and updateDisplayUnit().
Referenced by accept(), on_receiveButton_clicked(), ReceiveCoinsDialog(), and reject().
copyAmount
void ReceiveCoinsDialog::copyAmount () private slot
Definition at line 269 of file receivecoinsdialog.cpp.
References RecentRequestsTableModel::Amount, and copyColumnToClipboard().
Referenced by ReceiveCoinsDialog().
copyColumnToClipboard()
void ReceiveCoinsDialog::copyColumnToClipboard (int column) private
Definition at line 225 of file receivecoinsdialog.cpp.
References RecentRequestsTableModel::data(), WalletModel::getRecentRequestsTableModel(), model, selectedRow(), and GUIUtil::setClipboard().
Referenced by copyAmount(), copyLabel(), and copyMessage().
copyLabel
void ReceiveCoinsDialog::copyLabel () private slot
Definition at line 257 of file receivecoinsdialog.cpp.
References copyColumnToClipboard(), and RecentRequestsTableModel::Label.
Referenced by ReceiveCoinsDialog().
copyMessage
void ReceiveCoinsDialog::copyMessage () private slot
Definition at line 263 of file receivecoinsdialog.cpp.
References copyColumnToClipboard(), and RecentRequestsTableModel::Message.
Referenced by ReceiveCoinsDialog().
copyURI
void ReceiveCoinsDialog::copyURI () private slot
Definition at line 244 of file receivecoinsdialog.cpp.
References RecentRequestsTableModel::entry(), GUIUtil::formatBitcoinURI(), WalletModel::getRecentRequestsTableModel(), model, selectedRow(), and GUIUtil::setClipboard().
Referenced by ReceiveCoinsDialog().
keyPressEvent()
void ReceiveCoinsDialog::keyPressEvent (QKeyEvent * event) override protected virtual
Definition at line 196 of file receivecoinsdialog.cpp.
References on_receiveButton_clicked(), and ui.
on_receiveButton_clicked
void ReceiveCoinsDialog::on_receiveButton_clicked () private slot
Definition at line 125 of file receivecoinsdialog.cpp.
References RecentRequestsTableModel::addNewRequest(), AddressTableModel::addRow(), clear(), WalletModel::getAddressTableModel(), WalletModel::getOptionsModel(), WalletModel::getRecentRequestsTableModel(), model, AddressTableModel::Receive, and ui.
Referenced by keyPressEvent().
on_recentRequestsView_doubleClicked
void ReceiveCoinsDialog::on_recentRequestsView_doubleClicked (const QModelIndex & index) private slot
Definition at line 147 of file receivecoinsdialog.cpp.
References RecentRequestsTableModel::entry(), WalletModel::getOptionsModel(), WalletModel::getRecentRequestsTableModel(), model, ReceiveRequestDialog::setInfo(), and ReceiveRequestDialog::setModel().
Referenced by on_showRequestButton_clicked().
on_removeRequestButton_clicked
void ReceiveCoinsDialog::on_removeRequestButton_clicked () private slot
Definition at line 176 of file receivecoinsdialog.cpp.
References WalletModel::getRecentRequestsTableModel(), model, RecentRequestsTableModel::removeRows(), and ui.
on_showRequestButton_clicked
void ReceiveCoinsDialog::on_showRequestButton_clicked () private slot
Definition at line 165 of file receivecoinsdialog.cpp.
References WalletModel::getRecentRequestsTableModel(), model, on_recentRequestsView_doubleClicked(), and ui.
recentRequestsView_selectionChanged
void ReceiveCoinsDialog::recentRequestsView_selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) private slot
Definition at line 157 of file receivecoinsdialog.cpp.
References ui.
Referenced by setModel().
reject
void ReceiveCoinsDialog::reject () override slot
Definition at line 107 of file receivecoinsdialog.cpp.
References clear().
resizeEvent()
void ReceiveCoinsDialog::resizeEvent (QResizeEvent * event) override private virtual
Definition at line 190 of file receivecoinsdialog.cpp.
References columnResizingFixer, RecentRequestsTableModel::Message, and GUIUtil::TableViewLastColumnResizingFixer::stretchColumnWidth().
selectedRow()
QModelIndex ReceiveCoinsDialog::selectedRow () private
Definition at line 212 of file receivecoinsdialog.cpp.
References WalletModel::getRecentRequestsTableModel(), model, and ui.
Referenced by copyColumnToClipboard(), copyURI(), and showMenu().
setModel()
void ReceiveCoinsDialog::setModel (WalletModel * model)
Definition at line 64 of file receivecoinsdialog.cpp.
References RecentRequestsTableModel::Amount, AMOUNT_MINIMUM_COLUMN_WIDTH, columnResizingFixer, RecentRequestsTableModel::Date, DATE_COLUMN_WIDTH, WalletModel::getOptionsModel(), WalletModel::getRecentRequestsTableModel(), RecentRequestsTableModel::Label, LABEL_COLUMN_WIDTH, model, recentRequestsView_selectionChanged(), RecentRequestsTableModel::sort(), ui, and updateDisplayUnit().
Referenced by WalletView::setWalletModel().
showMenu
void ReceiveCoinsDialog::showMenu (const QPoint & point) private slot
Definition at line 235 of file receivecoinsdialog.cpp.
References contextMenu, and selectedRow().
Referenced by ReceiveCoinsDialog().
updateDisplayUnit
void ReceiveCoinsDialog::updateDisplayUnit () private slot
Definition at line 117 of file receivecoinsdialog.cpp.
References OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), model, and ui.
Referenced by clear(), and setModel().
Member Data Documentation
columnResizingFixer
GUIUtil::TableViewLastColumnResizingFixer* ReceiveCoinsDialog::columnResizingFixer private
Definition at line 56 of file receivecoinsdialog.h.
Referenced by resizeEvent(), and setModel().
contextMenu
QMenu* ReceiveCoinsDialog::contextMenu private
Definition at line 58 of file receivecoinsdialog.h.
Referenced by ReceiveCoinsDialog(), and showMenu().
model
WalletModel* ReceiveCoinsDialog::model private
Definition at line 57 of file receivecoinsdialog.h.
Referenced by copyColumnToClipboard(), copyURI(), on_receiveButton_clicked(), on_recentRequestsView_doubleClicked(), on_removeRequestButton_clicked(), on_showRequestButton_clicked(), selectedRow(), setModel(), and updateDisplayUnit().
ui
Ui::ReceiveCoinsDialog* ReceiveCoinsDialog::ui private
Definition at line 55 of file receivecoinsdialog.h.
Referenced by clear(), keyPressEvent(), on_receiveButton_clicked(), on_removeRequestButton_clicked(), on_showRequestButton_clicked(), ReceiveCoinsDialog(), recentRequestsView_selectionChanged(), selectedRow(), setModel(), updateDisplayUnit(), and ~ReceiveCoinsDialog().
The documentation for this class was generated from the following files:
src/qt/receivecoinsdialog.h
src/qt/receivecoinsdialog.cpp
Released under the MIT license