Dash Core: CBitcoinSecret Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CBitcoinSecret Class Reference
A base58-encoded secret key.
#include <base58.h>
Public Member Functions
void SetKey (const CKey &vchSecret)
CKey GetKey ()
bool IsValid () const
bool SetString (const char *pszSecret)
bool SetString (const std::string &strSecret)
CBitcoinSecret (const CKey &vchSecret)
CBitcoinSecret ()
Public Member Functions inherited from CBase58Data
bool SetString (const char *psz, unsigned int nVersionBytes=1)
bool SetString (const std::string &str)
std::string ToString () const
int CompareTo (const CBase58Data &b58) const
bool operator== (const CBase58Data &b58) const
bool operator<= (const CBase58Data &b58) const
bool operator>= (const CBase58Data &b58) const
bool operator< (const CBase58Data &b58) const
bool operator> (const CBase58Data &b58) const
Additional Inherited Members
Protected Types inherited from CBase58Data
typedef std::vector< unsigned char, zero_after_free_allocator< unsigned char > > vector_uchar
the actually encoded data
Protected Member Functions inherited from CBase58Data
CBase58Data ()
void SetData (const std::vector< unsigned char > &vchVersionIn, const void *pdata, size_t nSize)
void SetData (const std::vector< unsigned char > &vchVersionIn, const unsigned char *pbegin, const unsigned char *pend)
Protected Attributes inherited from CBase58Data
std::vector< unsigned char > vchVersion
the version byte(s)
vector_uchar vchData
Detailed Description
A base58-encoded secret key.
Definition at line 126 of file base58.h.
Constructor & Destructor Documentation
CBitcoinSecret() [1/2]
CBitcoinSecret::CBitcoinSecret (const CKey & vchSecret) inline
Definition at line 135 of file base58.h.
References SetKey().
CBitcoinSecret() [2/2]
CBitcoinSecret::CBitcoinSecret () inline
Definition at line 136 of file base58.h.
Member Function Documentation
GetKey()
CKey CBitcoinSecret::GetKey ()
Definition at line 314 of file base58.cpp.
References CKey::Set(), and CBase58Data::vchData.
Referenced by CMessageSigner::GetKeysFromSecret(), importelectrumwallet(), importprivkey(), importwallet(), MutateTxSign(), and signrawtransaction().
IsValid()
bool CBitcoinSecret::IsValid () const
Definition at line 322 of file base58.cpp.
References CChainParams::Base58Prefix(), Params(), CChainParams::SECRET_KEY, CBase58Data::vchData, and CBase58Data::vchVersion.
Referenced by SetString().
SetKey()
void CBitcoinSecret::SetKey (const CKey & vchSecret)
Definition at line 306 of file base58.cpp.
References CKey::begin(), CKey::IsCompressed(), CKey::IsValid(), Params(), CChainParams::SECRET_KEY, CBase58Data::SetData(), CKey::size(), and CBase58Data::vchData.
Referenced by CBitcoinSecret().
SetString() [1/2]
bool CBitcoinSecret::SetString (const char * pszSecret)
Definition at line 329 of file base58.cpp.
References IsValid(), and CBase58Data::SetString().
Referenced by CGovernanceKey::GetKey(), CMessageSigner::GetKeysFromSecret(), importelectrumwallet(), importprivkey(), importwallet(), MutateTxSign(), SetString(), and signrawtransaction().
SetString() [2/2]
bool CBitcoinSecret::SetString (const std::string & strSecret)
Definition at line 334 of file base58.cpp.
References SetString().
The documentation for this class was generated from the following files:
src/base58.h
src/base58.cpp
Released under the MIT license