Dash Core: OptionsModel Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
OptionsModel Class Reference
Interface from Qt to configuration data structure for Bitcoin client.
#include <optionsmodel.h>
Public Types
enum OptionID {
StartAtStartup, HideTrayIcon, MinimizeToTray, MapPortUPnP,
MinimizeOnClose, ProxyUse, ProxyIP, ProxyPort,
ProxyUseTor, ProxyIPTor, ProxyPortTor, DisplayUnit,
ThirdPartyTxUrls, Digits, Theme, FontFamily,
FontScale, FontWeightNormal, FontWeightBold, Language,
CoinControlFeatures, ThreadsScriptVerif, DatabaseCache, SpendZeroConfChange,
ShowMasternodesTab, PrivateSendEnabled, ShowAdvancedPSUI, ShowPrivateSendPopups,
LowKeysWarning, PrivateSendRounds, PrivateSendAmount, PrivateSendMultiSession,
Listen, OptionIDRowCount
}
Signals
void displayUnitChanged (int unit)
void privateSendEnabledChanged ()
void privateSendRoundsChanged ()
void privateSentAmountChanged ()
void advancedPSUIChanged (bool)
void coinControlFeaturesChanged (bool)
void hideTrayIconChanged (bool)
Public Member Functions
OptionsModel (QObject *parent=0, bool resetSettings=false)
void Init (bool resetSettings=false)
void Reset ()
int rowCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setDisplayUnit (const QVariant &value)
Updates current unit in memory, settings and emits displayUnitChanged(newUnit) signal.
bool getHideTrayIcon () const
bool getMinimizeToTray () const
bool getMinimizeOnClose () const
int getDisplayUnit () const
QString getThirdPartyTxUrls () const
bool getProxySettings (QNetworkProxy &proxy) const
bool getCoinControlFeatures () const
bool getShowAdvancedPSUI ()
const QString & getOverriddenByCommandLine ()
void emitPrivateSendEnabledChanged ()
void setRestartRequired (bool fRequired)
bool isRestartRequired () const
Public Attributes
bool resetSettingsOnShutdown {false}
Private Member Functions
void addOverriddenOption (const std::string &option)
void checkAndMigrate ()
Private Attributes
bool fHideTrayIcon
bool fMinimizeToTray
bool fMinimizeOnClose
QString language
int nDisplayUnit
QString strThirdPartyTxUrls
bool fCoinControlFeatures
bool fShowAdvancedPSUI
QString strOverriddenByCommandLine
Detailed Description
Interface from Qt to configuration data structure for Bitcoin client.
To Qt, the options are presented as a list with the different options laid out vertically. This can be changed to a tree once the settings become sufficiently complex.
Definition at line 25 of file optionsmodel.h.
Member Enumeration Documentation
OptionID
enum OptionsModel::OptionID
Enumerator
StartAtStartup
HideTrayIcon
MinimizeToTray
MapPortUPnP
MinimizeOnClose
ProxyUse
ProxyIP
ProxyPort
ProxyUseTor
ProxyIPTor
ProxyPortTor
DisplayUnit
ThirdPartyTxUrls
Digits
Theme
FontFamily
FontScale
FontWeightNormal
FontWeightBold
Language
CoinControlFeatures
ThreadsScriptVerif
DatabaseCache
SpendZeroConfChange
ShowMasternodesTab
PrivateSendEnabled
ShowAdvancedPSUI
ShowPrivateSendPopups
LowKeysWarning
PrivateSendRounds
PrivateSendAmount
PrivateSendMultiSession
Listen
OptionIDRowCount
Definition at line 32 of file optionsmodel.h.
Constructor & Destructor Documentation
OptionsModel()
OptionsModel::OptionsModel (QObject * parent = 0, bool resetSettings = false) explicit
Definition at line 36 of file optionsmodel.cpp.
References Init().
Member Function Documentation
addOverriddenOption()
void OptionsModel::addOverriddenOption (const std::string & option) private
Definition at line 42 of file optionsmodel.cpp.
References gArgs, ArgsManager::GetArg(), and strOverriddenByCommandLine.
Referenced by Init().
advancedPSUIChanged
void OptionsModel::advancedPSUIChanged (bool) signal
Referenced by setData().
checkAndMigrate()
void OptionsModel::checkAndMigrate () private
Definition at line 670 of file optionsmodel.cpp.
References CLIENT_VERSION, GetDefaultProxyAddress(), and nDefaultDbCache.
Referenced by Init().
coinControlFeaturesChanged
void OptionsModel::coinControlFeaturesChanged (bool) signal
Referenced by setData().
data()
QVariant OptionsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 297 of file optionsmodel.cpp.
References CoinControlFeatures, DatabaseCache, Digits, DisplayUnit, fCoinControlFeatures, fHideTrayIcon, fMinimizeOnClose, fMinimizeToTray, FontFamily, FontScale, FontWeightBold, FontWeightNormal, fShowAdvancedPSUI, GetProxySetting(), GUIUtil::GetStartOnSystemStartup(), HideTrayIcon, ProxySetting::ip, Language, Listen, LowKeysWarning, MapPortUPnP, MinimizeOnClose, MinimizeToTray, nDisplayUnit, ProxySetting::port, PrivateSendAmount, PrivateSendEnabled, PrivateSendMultiSession, PrivateSendRounds, ProxyIP, ProxyIPTor, ProxyPort, ProxyPortTor, ProxyUse, ProxyUseTor, ShowAdvancedPSUI, ShowMasternodesTab, ShowPrivateSendPopups, SpendZeroConfChange, StartAtStartup, strThirdPartyTxUrls, GUIUtil::supportedWeightToIndex(), Theme, ThirdPartyTxUrls, ThreadsScriptVerif, and GUIUtil::weightFromArg().
displayUnitChanged
void OptionsModel::displayUnitChanged (int unit) signal
Referenced by setDisplayUnit().
emitPrivateSendEnabledChanged()
void OptionsModel::emitPrivateSendEnabledChanged ()
Definition at line 653 of file optionsmodel.cpp.
References privateSendEnabledChanged().
getCoinControlFeatures()
bool OptionsModel::getCoinControlFeatures () const inline
Definition at line 85 of file optionsmodel.h.
References fCoinControlFeatures.
Referenced by SendCoinsDialog::send(), SendCoinsDialog::setModel(), and SendCoinsDialog::useAvailableBalance().
getDisplayUnit()
int OptionsModel::getDisplayUnit () const inline
Definition at line 82 of file optionsmodel.h.
References nDisplayUnit.
Referenced by TransactionView::changedAmount(), TransactionView::computeSum(), RecentRequestsTableModel::data(), TransactionTableModel::data(), TransactionView::exportClicked(), TransactionTableModel::formatTxAmount(), RecentRequestsTableModel::getAmountTitle(), WalletView::processNewTransaction(), PaymentServer::processPaymentRequest(), SendCoinsDialog::processSendCoinsReturn(), SendCoinsDialog::send(), SendCoinsDialog::setBalance(), UnitDisplayStatusBarControl::setOptionsModel(), TransactionTableModel::TransactionTableModel(), ReceiveRequestDialog::update(), TransactionTableModel::updateAmountColumnTitle(), SendCoinsEntry::updateDisplayUnit(), ReceiveCoinsDialog::updateDisplayUnit(), OverviewPage::updateDisplayUnit(), SendCoinsDialog::updateDisplayUnit(), SendCoinsDialog::updateFeeMinimizedLabel(), CoinControlDialog::updateLabels(), SendCoinsDialog::updateMinFeeLabel(), SendCoinsDialog::updateSmartFeeLabel(), and CoinControlDialog::updateView().
getHideTrayIcon()
bool OptionsModel::getHideTrayIcon () const inline
Definition at line 79 of file optionsmodel.h.
References fHideTrayIcon.
Referenced by BitcoinGUI::setClientModel().
getMinimizeOnClose()
bool OptionsModel::getMinimizeOnClose () const inline
Definition at line 81 of file optionsmodel.h.
References fMinimizeOnClose.
Referenced by BitcoinGUI::closeEvent().
getMinimizeToTray()
bool OptionsModel::getMinimizeToTray () const inline
Definition at line 80 of file optionsmodel.h.
References fMinimizeToTray.
Referenced by BitcoinGUI::changeEvent().
getOverriddenByCommandLine()
const QString& OptionsModel::getOverriddenByCommandLine () inline
Definition at line 87 of file optionsmodel.h.
References strOverriddenByCommandLine.
Referenced by OptionsDialog::setModel().
getProxySettings()
bool OptionsModel::getProxySettings (QNetworkProxy & proxy) const
Definition at line 635 of file optionsmodel.cpp.
References CService::GetPort(), GetProxy(), NET_IPV4, proxyType::proxy, and CNetAddr::ToStringIP().
Referenced by PaymentServer::initNetManager().
getShowAdvancedPSUI()
bool OptionsModel::getShowAdvancedPSUI () inline
Definition at line 86 of file optionsmodel.h.
References fShowAdvancedPSUI.
Referenced by OverviewPage::setWalletModel().
getThirdPartyTxUrls()
QString OptionsModel::getThirdPartyTxUrls () const inline
Definition at line 83 of file optionsmodel.h.
References strThirdPartyTxUrls.
Referenced by TransactionView::setModel().
hideTrayIconChanged
void OptionsModel::hideTrayIconChanged (bool) signal
Referenced by Init(), and setData().
Init()
void OptionsModel::Init (bool resetSettings = false)
Definition at line 48 of file optionsmodel.cpp.
References addOverriddenOption(), checkAndMigrate(), BitcoinUnits::DASH, DEFAULT_LISTEN, DEFAULT_PRIVATESEND_AMOUNT, DEFAULT_PRIVATESEND_MULTISESSION, DEFAULT_PRIVATESEND_ROUNDS, DEFAULT_SCRIPTCHECK_THREADS, DEFAULT_UPNP, fCoinControlFeatures, fHideTrayIcon, fMinimizeOnClose, fMinimizeToTray, GUIUtil::fontFamilyToString(), CPrivateSendClientManager::fPrivateSendMultiSession, fShowAdvancedPSUI, gArgs, ArgsManager::GetArg(), GetDefaultProxyAddress(), GUIUtil::getDefaultTheme(), GUIUtil::getFontFamilyDefault(), GUIUtil::getFontScaleDefault(), GUIUtil::getFontWeightBoldDefault(), GUIUtil::getFontWeightNormalDefault(), hideTrayIconChanged(), language, nDefaultDbCache, nDisplayUnit, CPrivateSendClientManager::nPrivateSendAmount, CPrivateSendClientManager::nPrivateSendRounds, privateSendClient, Reset(), setRestartRequired(), ArgsManager::SoftSetArg(), ArgsManager::SoftSetBoolArg(), strThirdPartyTxUrls, and GUIUtil::weightToArg().
Referenced by OptionsModel().
isRestartRequired()
bool OptionsModel::isRestartRequired () const
Definition at line 664 of file optionsmodel.cpp.
Referenced by OptionsDialog::clearStatusLabel(), and OptionsDialog::setModel().
privateSendEnabledChanged
void OptionsModel::privateSendEnabledChanged () signal
Referenced by emitPrivateSendEnabledChanged(), setData(), and OverviewPage::setWalletModel().
privateSendRoundsChanged
void OptionsModel::privateSendRoundsChanged () signal
Referenced by setData().
privateSentAmountChanged
void OptionsModel::privateSentAmountChanged () signal
Referenced by setData().
Reset()
void OptionsModel::Reset ()
Definition at line 244 of file optionsmodel.cpp.
References BackupSettings(), GetDataDir(), GUIUtil::GetStartOnSystemStartup(), and GUIUtil::SetStartOnSystemStartup().
Referenced by Init(), and OptionsDialog::on_resetButton_clicked().
rowCount()
int OptionsModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 259 of file optionsmodel.cpp.
References OptionIDRowCount.
setData()
bool OptionsModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Definition at line 399 of file optionsmodel.cpp.
References advancedPSUIChanged(), CoinControlFeatures, coinControlFeaturesChanged(), DatabaseCache, Digits, DisplayUnit, fCoinControlFeatures, fHideTrayIcon, fMinimizeOnClose, fMinimizeToTray, FontFamily, FontScale, FontWeightBold, FontWeightNormal, CPrivateSendClientManager::fPrivateSendMultiSession, fShowAdvancedPSUI, GetProxySetting(), HideTrayIcon, hideTrayIconChanged(), Language, Listen, LowKeysWarning, MapPort(), MapPortUPnP, MinimizeOnClose, MinimizeToTray, CPrivateSendClientManager::nPrivateSendAmount, CPrivateSendClientManager::nPrivateSendRounds, PrivateSendAmount, privateSendClient, PrivateSendEnabled, privateSendEnabledChanged(), PrivateSendMultiSession, PrivateSendRounds, privateSendRoundsChanged(), privateSentAmountChanged(), ProxyIP, ProxyIPTor, ProxyPort, ProxyPortTor, ProxyUse, ProxyUseTor, setDisplayUnit(), SetProxySetting(), setRestartRequired(), GUIUtil::SetStartOnSystemStartup(), ShowAdvancedPSUI, ShowMasternodesTab, ShowPrivateSendPopups, SpendZeroConfChange, StartAtStartup, strThirdPartyTxUrls, GUIUtil::supportedWeightFromIndex(), Theme, ThirdPartyTxUrls, ThreadsScriptVerif, and GUIUtil::weightToArg().
setDisplayUnit()
void OptionsModel::setDisplayUnit (const QVariant & value)
Updates current unit in memory, settings and emits displayUnitChanged(newUnit) signal.
Definition at line 624 of file optionsmodel.cpp.
References displayUnitChanged(), and nDisplayUnit.
Referenced by UnitDisplayStatusBarControl::onMenuSelection(), and setData().
setRestartRequired()
void OptionsModel::setRestartRequired (bool fRequired)
Definition at line 658 of file optionsmodel.cpp.
Referenced by Init(), and setData().
Member Data Documentation
fCoinControlFeatures
bool OptionsModel::fCoinControlFeatures private
Definition at line 103 of file optionsmodel.h.
Referenced by data(), getCoinControlFeatures(), Init(), and setData().
fHideTrayIcon
bool OptionsModel::fHideTrayIcon private
Definition at line 97 of file optionsmodel.h.
Referenced by data(), getHideTrayIcon(), Init(), and setData().
fMinimizeOnClose
bool OptionsModel::fMinimizeOnClose private
Definition at line 99 of file optionsmodel.h.
Referenced by data(), getMinimizeOnClose(), Init(), and setData().
fMinimizeToTray
bool OptionsModel::fMinimizeToTray private
Definition at line 98 of file optionsmodel.h.
Referenced by data(), getMinimizeToTray(), Init(), and setData().
fShowAdvancedPSUI
bool OptionsModel::fShowAdvancedPSUI private
Definition at line 104 of file optionsmodel.h.
Referenced by data(), getShowAdvancedPSUI(), Init(), and setData().
language
QString OptionsModel::language private
Definition at line 100 of file optionsmodel.h.
Referenced by Init().
nDisplayUnit
int OptionsModel::nDisplayUnit private
Definition at line 101 of file optionsmodel.h.
Referenced by data(), getDisplayUnit(), Init(), and setDisplayUnit().
resetSettingsOnShutdown
bool OptionsModel::resetSettingsOnShutdown {false}
Definition at line 93 of file optionsmodel.h.
Referenced by OptionsDialog::on_resetButton_clicked(), and BitcoinApplication::~BitcoinApplication().
strOverriddenByCommandLine
QString OptionsModel::strOverriddenByCommandLine private
Definition at line 106 of file optionsmodel.h.
Referenced by addOverriddenOption(), and getOverriddenByCommandLine().
strThirdPartyTxUrls
QString OptionsModel::strThirdPartyTxUrls private
Definition at line 102 of file optionsmodel.h.
Referenced by data(), getThirdPartyTxUrls(), Init(), and setData().
The documentation for this class was generated from the following files:
src/qt/optionsmodel.h
src/qt/optionsmodel.cpp
Released under the MIT license