Dash Core: CBlockIndex Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBlockIndex Class Reference
The block chain is a tree shaped structure starting with the genesis block at the root, with each block potentially having multiple candidates to be the next block.
#include <chain.h>
Public Member Functions
void SetNull ()
CBlockIndex ()
CBlockIndex (const CBlockHeader &block)
CDiskBlockPos GetBlockPos () const
CDiskBlockPos GetUndoPos () const
CBlockHeader GetBlockHeader () const
uint256 GetBlockHash () const
int64_t GetBlockTime () const
int64_t GetBlockTimeMax () const
int64_t GetMedianTimePast () const
std::string ToString () const
bool IsValid (enum BlockStatus nUpTo=BLOCK_VALID_TRANSACTIONS) const
Check whether this block index entry is valid up to the passed validity level.
bool RaiseValidity (enum BlockStatus nUpTo)
Raise the validity level of this block index entry.
void BuildSkip ()
Build the skiplist pointer for this entry.
CBlockIndex * GetAncestor (int height)
Efficiently find an ancestor of this block.
const CBlockIndex * GetAncestor (int height) const
Public Attributes
const uint256 * phashBlock
pointer to the hash of the block, if any. Memory is owned by this CBlockIndex
CBlockIndex * pprev
pointer to the index of the predecessor of this block
CBlockIndex * pskip
pointer to the index of some further predecessor of this block
int nHeight
height of the entry in the chain. The genesis block has height 0
int nFile
Which # file this block is stored in (blk?????.dat)
unsigned int nDataPos
Byte offset within blk?????.dat where this block's data is stored.
unsigned int nUndoPos
Byte offset within rev?????.dat where this block's undo data is stored.
arith_uint256 nChainWork
(memory only) Total amount of work (expected number of hashes) in the chain up to and including this block
unsigned int nTx
Number of transactions in this block.
unsigned int nChainTx
(memory only) Number of transactions in the chain up to and including this block.
uint32_t nStatus
Verification status of this block. See enum BlockStatus.
int32_t nVersion
block header
uint256 hashMerkleRoot
uint32_t nTime
uint32_t nBits
uint32_t nNonce
int32_t nSequenceId
(memory only) Sequential id assigned to distinguish order in which blocks are received.
unsigned int nTimeMax
(memory only) Maximum nTime in the chain up to and including this block.
Static Public Attributes
static constexpr int nMedianTimeSpan = 11
Detailed Description
The block chain is a tree shaped structure starting with the genesis block at the root, with each block potentially having multiple candidates to be the next block.
A blockindex may have multiple pprev pointing to it, but at most one of them can be part of the currently active branch.
Definition at line 170 of file chain.h.
Constructor & Destructor Documentation
CBlockIndex() [1/2]
CBlockIndex::CBlockIndex () inline
Definition at line 245 of file chain.h.
References SetNull().
CBlockIndex() [2/2]
CBlockIndex::CBlockIndex (const CBlockHeader & block) inline explicit
Definition at line 250 of file chain.h.
References CBlockHeader::hashMerkleRoot, hashMerkleRoot, CBlockHeader::nBits, nBits, CBlockHeader::nNonce, nNonce, CBlockHeader::nTime, nTime, CBlockHeader::nVersion, nVersion, and SetNull().
Member Function Documentation
BuildSkip()
void CBlockIndex::BuildSkip ()
Build the skiplist pointer for this entry.
Definition at line 115 of file chain.cpp.
References GetAncestor(), GetSkipHeight(), nHeight, pprev, and pskip.
Referenced by CChainState::LoadBlockIndex().
GetAncestor() [1/2]
CBlockIndex * CBlockIndex::GetAncestor (int height)
Efficiently find an ancestor of this block.
Definition at line 110 of file chain.cpp.
Referenced by CChainState::ActivateBestChainStep(), CWallet::BlockUntilSyncedToCurrentChain(), CDeterministicMNManager::BuildNewListFromBlock(), BuildSkip(), CalculateSequenceLocks(), llmq::CheckLLMQCommitment(), CheckSequenceLocks(), llmq::CChainLocksHandler::Cleanup(), CChainState::ConnectBlock(), llmq::CChainLocksHandler::EnforceBestChainLock(), llmq::CQuorumManager::EnsureQuorumConnections(), CChain::FindFork(), getchaintxstats(), CChain::GetLocator(), llmq::CQuorumBlockProcessor::GetMinedCommitmentsUntilBlock(), GetNextWorkRequiredBTC(), AbstractThresholdConditionChecker::GetStateFor(), AbstractThresholdConditionChecker::GetStateSinceHeightFor(), AbstractThresholdConditionChecker::GetStateStatisticsFor(), llmq::CInstantSendManager::HandleFullyConfirmedBlock(), llmq::CChainLocksHandler::InternalHasChainLock(), llmq::CChainLocksHandler::InternalHasConflictingChainLock(), LastCommonAncestor(), llmq::CQuorumBlockProcessor::ProcessMessage(), CChainState::ReplayBlocks(), llmq::CDKGSessionHandler::UpdatedBlockTip(), and llmq::CInstantSendManager::UpdatedBlockTip().
GetAncestor() [2/2]
const CBlockIndex * CBlockIndex::GetAncestor (int height) const
Definition at line 83 of file chain.cpp.
References GetSkipHeight(), nHeight, pprev, and pskip.
GetBlockHash()
uint256 CBlockIndex::GetBlockHash () const inline
Definition at line 292 of file chain.h.
References phashBlock.
Referenced by llmq::CChainLocksHandler::AcceptedBlockHeader(), CChainState::ActivateBestChain(), llmq::CInstantSendManager::AddNonLockedTx(), llmq::CLLMQUtils::AddQuorumProbeConnections(), CWallet::AddToWalletIfInvolvingMe(), AlreadyHave(), CDeterministicMNList::ApplyDiff(), llmq::CChainLocksHandler::BlockConnected(), CWallet::BlockConnected(), llmq::CChainLocksHandler::BlockDisconnected(), blockheaderToJSON(), BlockNotifyCallback(), BlockTipChanged(), blockToJSON(), BOOST_FIXTURE_TEST_CASE(), CDeterministicMNManager::BuildNewListFromBlock(), llmq::CQuorumManager::BuildQuorumFromCommitment(), llmq::CLLMQUtils::CalcDeterministicWatchConnections(), CDiskBlockIndex::CDiskBlockIndex(), CChainState::CheckBlockIndex(), llmq::CInstantSendManager::CheckCanLock(), CDeterministicMNManager::CleanupCache(), CChainState::ConnectBlock(), CChainState::ConnectTip(), BlockAssembler::CreateNewBlock(), CChainState::DisconnectBlock(), CChainState::DisconnectTip(), llmq::CChainLocksHandler::DoInvalidateBlock(), dumpwallet(), llmq::CChainLocksHandler::EnforceBestChainLock(), llmq::CLLMQUtils::EnsureQuorumConnections(), llmq::CQuorumManager::EnsureQuorumConnections(), llmq::CLLMQUtils::GetAllQuorumMembers(), getbestblockhash(), getblockchaininfo(), getblockhash(), GetBlockHeader(), getblockstats(), getblocktemplate(), ClientModel::getLastBlockHash(), CDeterministicMNManager::GetListForBlock(), CChain::GetLocator(), llmq::CQuorumManager::GetQuorum(), GetTransaction(), gettxout(), llmq::CDKGSessionManager::GetVerifiedContribution(), llmq::CDKGSession::Init(), llmq::CChainLocksHandler::InternalHasChainLock(), llmq::CChainLocksHandler::InternalHasConflictingChainLock(), InvalidChainFound(), listsinceblock(), CChainState::LoadBlockIndex(), CBlockTreeDB::LoadBlockIndexGuts(), LoadChainTip(), CZMQPublishHashBlockNotifier::NotifyBlock(), CZMQPublishRawBlockNotifier::NotifyBlock(), CZMQPublishHashChainLockNotifier::NotifyChainLock(), CZMQPublishRawChainLockNotifier::NotifyChainLock(), CZMQPublishRawChainLockSigNotifier::NotifyChainLock(), llmq::CDKGSession::PreVerifyMessage(), CDeterministicMNManager::ProcessBlock(), ProcessGetBlockData(), ProcessHeadersMessage(), llmq::CInstantSendManager::ProcessInstantSendLock(), ProcessMessage(), llmq::CInstantSendManager::ProcessNewTransaction(), ReadBlockFromDisk(), CChainState::ReplayBlocks(), rest_getutxos(), CChainState::RollforwardBlock(), RPCNotifyBlockChange(), llmq::CQuorumManager::ScanQuorums(), llmq::CDKGSession::SendCommitment(), llmq::CDKGSession::SendComplaint(), llmq::CDKGSession::SendContributions(), llmq::CDKGSession::SendJustification(), PeerLogicValidation::SendMessages(), CMerkleTx::SetMerkleBranch(), ToString(), llmq::CChainLocksHandler::TrySignChainTip(), TxToJSON(), llmq::CQuorumBlockProcessor::UndoBlock(), PeerLogicValidation::UpdatedBlockTip(), CMasternodeSync::UpdatedBlockTip(), llmq::CDKGSessionHandler::UpdatedBlockTip(), UpdateTip(), llmq::CQuorumBlockProcessor::UpgradeDB(), CDeterministicMNManager::UpgradeDBIfNeeded(), CDeterministicMNManager::UpgradeDiff(), CVerifyDB::VerifyDB(), WriteUndoDataForBlock(), llmq::CDKGSessionManager::WriteVerifiedSkContribution(), and llmq::CDKGSessionManager::WriteVerifiedVvecContribution().
GetBlockHeader()
CBlockHeader CBlockIndex::GetBlockHeader () const inline
Definition at line 279 of file chain.h.
References GetBlockHash(), CBlockHeader::hashMerkleRoot, hashMerkleRoot, CBlockHeader::hashPrevBlock, CBlockHeader::nBits, nBits, CBlockHeader::nNonce, nNonce, CBlockHeader::nTime, nTime, CBlockHeader::nVersion, nVersion, and pprev.
Referenced by getblockheader(), and getblockheaders().
GetBlockPos()
CDiskBlockPos CBlockIndex::GetBlockPos () const inline
Definition at line 261 of file chain.h.
References BLOCK_HAVE_DATA, nDataPos, CDiskBlockPos::nFile, nFile, CDiskBlockPos::nPos, and nStatus.
Referenced by BOOST_FIXTURE_TEST_CASE(), ReadBlockFromDisk(), and WriteTxIndexDataForBlock().
GetBlockTime()
int64_t CBlockIndex::GetBlockTime () const inline
Definition at line 297 of file chain.h.
References nTime.
Referenced by BlockRequestAllowed(), BlockTipChanged(), CalculateNextWorkRequired(), CWallet::CreateWalletFromFile(), DarkGravityWave(), dumpwallet(), GetBlockScriptFlags(), getblockstats(), ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), ClientModel::getLastBlockDate(), GetMedianTimePast(), GetNetworkHashPS(), GetNextWorkRequired(), GetNextWorkRequiredBTC(), GuessVerificationProgress(), importmulti(), importwallet(), InvalidChainFound(), IsCurrentForFeeEstimation(), IsInitialBlockDownload(), KimotoGravityWell(), LoadChainTip(), ProcessGetBlockData(), ProcessMessage(), PeerLogicValidation::SendMessages(), TxToJSON(), and UpdateTip().
GetBlockTimeMax()
int64_t CBlockIndex::GetBlockTimeMax () const inline
Definition at line 302 of file chain.h.
References nTimeMax.
Referenced by BOOST_FIXTURE_TEST_CASE(), and CWallet::RescanFromTime().
GetMedianTimePast()
int64_t CBlockIndex::GetMedianTimePast () const inline
Definition at line 309 of file chain.h.
References GetBlockTime(), nMedianTimeSpan, and pprev.
Referenced by blockheaderToJSON(), blockToJSON(), CalculateSequenceLocks(), CheckFinalTx(), ContextualCheckBlock(), ContextualCheckBlockHeader(), BlockAssembler::CreateNewBlock(), EvaluateSequenceLocks(), getblockchaininfo(), getblockstats(), getblocktemplate(), getchaintxstats(), AbstractThresholdConditionChecker::GetStateFor(), importmulti(), and UpdateTime().
GetUndoPos()
CDiskBlockPos CBlockIndex::GetUndoPos () const inline
Definition at line 270 of file chain.h.
References BLOCK_HAVE_UNDO, CDiskBlockPos::nFile, nFile, CDiskBlockPos::nPos, nStatus, and nUndoPos.
Referenced by CVerifyDB::VerifyDB(), and WriteUndoDataForBlock().
IsValid()
bool CBlockIndex::IsValid (enum BlockStatus nUpTo = BLOCK_VALID_TRANSACTIONS) const inline
Check whether this block index entry is valid up to the passed validity level.
Definition at line 332 of file chain.h.
References BLOCK_FAILED_MASK, BLOCK_VALID_MASK, and nStatus.
Referenced by BlockRequestAllowed(), CChainState::ConnectBlock(), llmq::CChainLocksHandler::EnforceBestChainLock(), getblocktemplate(), CChainState::LoadBlockIndex(), CChainState::PreciousBlock(), ProcessHeadersMessage(), ProcessMessage(), and submitblock().
RaiseValidity()
bool CBlockIndex::RaiseValidity (enum BlockStatus nUpTo) inline
Raise the validity level of this block index entry.
Returns true if the validity was changed.
Definition at line 342 of file chain.h.
References BLOCK_FAILED_MASK, BLOCK_VALID_MASK, and nStatus.
Referenced by CChainState::AddToBlockIndex(), CChainState::ConnectBlock(), and CChainState::ReceivedBlockTransactions().
SetNull()
void CBlockIndex::SetNull () inline
Definition at line 222 of file chain.h.
References hashMerkleRoot, nBits, nChainTx, nChainWork, nDataPos, nFile, nHeight, nNonce, nSequenceId, nStatus, nTime, nTimeMax, nTx, nUndoPos, nVersion, phashBlock, pprev, and pskip.
Referenced by CBlockIndex().
ToString()
std::string CBlockIndex::ToString () const inline
Definition at line 323 of file chain.h.
References GetBlockHash(), hashMerkleRoot, nHeight, pprev, strprintf, and base_blob< BITS >::ToString().
Referenced by ClientModel::getLastBlockHash(), CBlockTreeDB::LoadBlockIndexGuts(), ReadBlockFromDisk(), and CDiskBlockIndex::ToString().
Member Data Documentation
hashMerkleRoot
uint256 CBlockIndex::hashMerkleRoot
Definition at line 211 of file chain.h.
Referenced by blockheaderToJSON(), CBlockIndex(), CDiskBlockIndex::GetBlockHash(), GetBlockHeader(), CBlockTreeDB::LoadBlockIndexGuts(), CDiskBlockIndex::SerializationOp(), SetNull(), and ToString().
nBits
uint32_t CBlockIndex::nBits
Definition at line 213 of file chain.h.
Referenced by blockheaderToJSON(), CalculateNextWorkRequired(), CBlockIndex(), CChainState::ConnectBlock(), BlockAssembler::CreateNewBlock(), DarkGravityWave(), CDiskBlockIndex::GetBlockHash(), GetBlockHeader(), GetBlockProof(), getblockstats(), GetDifficulty(), GetNextWorkRequired(), GetNextWorkRequiredBTC(), KimotoGravityWell(), CBlockTreeDB::LoadBlockIndexGuts(), CDiskBlockIndex::SerializationOp(), and SetNull().
nChainTx
unsigned int CBlockIndex::nChainTx
(memory only) Number of transactions in the chain up to and including this block.
This value will be non-zero only if and only if transactions for this block and all its parents are available. Change to 64-bit type when necessary; won't happen before 2030
Definition at line 204 of file chain.h.
Referenced by CChainState::CheckBlockIndex(), CChainState::FindMostWorkChain(), getchaintxstats(), GuessVerificationProgress(), CChainState::LoadBlockIndex(), CChainState::PreciousBlock(), CChainState::ReceivedBlockTransactions(), SetNull(), and UpdateTip().
nChainWork
arith_uint256 CBlockIndex::nChainWork
(memory only) Total amount of work (expected number of hashes) in the chain up to and including this block
Definition at line 195 of file chain.h.
Referenced by CChainState::AcceptBlock(), CChainState::ActivateBestChainStep(), CChainState::AddToBlockIndex(), blockheaderToJSON(), blockToJSON(), CChainState::CheckBlockIndex(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), CChainState::ConnectBlock(), PeerLogicValidation::ConsiderEviction(), CChainState::FindMostWorkChain(), getblockchaininfo(), GetBlockProofEquivalentTime(), GetNetworkHashPS(), InvalidChainFound(), IsInitialBlockDownload(), CChainState::LoadBlockIndex(), CChainState::PreciousBlock(), ProcessHeadersMessage(), ProcessMessage(), SetNull(), and UpdateTip().
nDataPos
unsigned int CBlockIndex::nDataPos
Byte offset within blk?????.dat where this block's data is stored.
Definition at line 189 of file chain.h.
Referenced by GetBlockPos(), CBlockTreeDB::LoadBlockIndexGuts(), PruneOneBlockFile(), CChainState::ReceivedBlockTransactions(), CDiskBlockIndex::SerializationOp(), and SetNull().
nFile
int CBlockIndex::nFile
Which # file this block is stored in (blk?????.dat)
Definition at line 186 of file chain.h.
Referenced by GetBlockPos(), GetUndoPos(), LoadBlockIndexDB(), CBlockTreeDB::LoadBlockIndexGuts(), PruneOneBlockFile(), CChainState::ReceivedBlockTransactions(), CDiskBlockIndex::SerializationOp(), SetNull(), and WriteUndoDataForBlock().
nHeight
int CBlockIndex::nHeight
height of the entry in the chain. The genesis block has height 0
Definition at line 183 of file chain.h.
Referenced by CChainState::AcceptBlock(), CMasternodeSync::AcceptedBlockHeader(), llmq::CChainLocksHandler::AcceptedBlockHeader(), CChainState::ActivateBestChain(), CChainState::ActivateBestChainStep(), CDeterministicMNList::ApplyDiff(), CPrivateSend::BlockConnected(), llmq::CInstantSendManager::BlockDisconnected(), blockheaderToJSON(), BlockTipChanged(), blockToJSON(), CWallet::BlockUntilSyncedToCurrentChain(), CDeterministicMNManager::BuildNewListFromBlock(), BuildSimplifiedMNListDiff(), BuildSkip(), CChainState::CheckBlockIndex(), llmq::CInstantSendManager::CheckCanLock(), CheckCbTx(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), llmq::CheckLLMQCommitment(), CheckProRegTx(), CheckProUpRegTx(), CheckSequenceLocks(), CheckSpecialTx(), CChainState::ConnectBlock(), CChainState::ConnectTip(), CChain::Contains(), ContextualCheckBlock(), ContextualCheckBlockHeader(), ContextualCheckTransaction(), BlockAssembler::CreateNewBlock(), CWallet::CreateWalletFromFile(), DarkGravityWave(), CChainState::DisconnectBlock(), llmq::CChainLocksHandler::EnforceBestChainLock(), llmq::CQuorumManager::EnsureQuorumConnections(), EvaluateSequenceLocks(), FindFilesToPrune(), FindFilesToPruneManual(), CChain::FindFork(), CChainState::FindMostWorkChain(), GetAncestor(), getblockchaininfo(), GetBlockScriptFlags(), getblockstats(), getblocktemplate(), getchaintips(), getchaintxstats(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), CMerkleTx::GetDepthInMainChain(), ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), CDeterministicMNManager::GetListForBlock(), CChain::GetLocator(), llmq::CQuorumBlockProcessor::GetMinedCommitmentsUntilBlock(), GetNetworkHashPS(), GetNextWorkRequired(), GetNextWorkRequiredBTC(), GetSpendHeight(), AbstractThresholdConditionChecker::GetStateFor(), AbstractThresholdConditionChecker::GetStateSinceHeightFor(), AbstractThresholdConditionChecker::GetStateStatisticsFor(), gettxout(), llmq::CInstantSendManager::HandleFullyConfirmedBlock(), IncrementExtraNonce(), CActiveMasternodeManager::Init(), llmq::CDKGSession::Init(), llmq::CDKGSessionHandler::InitNewQuorum(), llmq::CChainLocksHandler::InternalHasChainLock(), llmq::CChainLocksHandler::InternalHasConflictingChainLock(), InvalidChainFound(), CGovernanceObject::IsCollateralValid(), IsCurrentForFeeEstimation(), CDeterministicMNManager::IsDIP3Enforced(), CPrivateSendBroadcastTx::IsExpired(), KimotoGravityWell(), LastCommonAncestor(), listsinceblock(), CChainState::LoadBlockIndex(), CBlockTreeDB::LoadBlockIndexGuts(), CWallet::MarkConflicted(), masternode_winners(), PeerLogicValidation::NewPoWValidBlock(), CChain::Next(), CWallet::NotifyChainLock(), CMasternodeSync::NotifyHeaderTip(), CompareBlocksByHeight::operator()(), llmq::CQuorumBlockProcessor::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), ProcessGetBlockData(), ProcessHeadersMessage(), llmq::CInstantSendManager::ProcessInstantSendLock(), llmq::CQuorumBlockProcessor::ProcessMessage(), ProcessMessage(), llmq::CInstantSendManager::ProcessNewTransaction(), pruneblockchain(), CChainState::ReplayBlocks(), rescanblockchain(), CWallet::RescanFromTime(), CChainState::ResetBlockFailureFlags(), CChainState::RollforwardBlock(), RPCNotifyBlockChange(), CWallet::ScanForWalletTransactions(), PeerLogicValidation::SendMessages(), CDiskBlockIndex::SerializationOp(), SetNull(), CChain::SetTip(), SoftForkMajorityDesc(), TestBlockValidity(), ToString(), llmq::CChainLocksHandler::TrySignChainTip(), TxToJSON(), llmq::CQuorumBlockProcessor::UndoBlock(), CDeterministicMNManager::UndoBlock(), CDSNotificationInterface::UpdatedBlockTip(), PeerLogicValidation::UpdatedBlockTip(), CActiveMasternodeManager::UpdatedBlockTip(), llmq::CDKGSessionManager::UpdatedBlockTip(), CMasternodeSync::UpdatedBlockTip(), llmq::CDKGSessionHandler::UpdatedBlockTip(), llmq::CInstantSendManager::UpdatedBlockTip(), CPrivateSendClientManager::UpdatedBlockTip(), CGovernanceManager::UpdatedBlockTip(), UpdateMempoolForReorg(), UpdateTip(), CDeterministicMNManager::UpgradeDiff(), and CVerifyDB::VerifyDB().
nMedianTimeSpan
constexpr int CBlockIndex::nMedianTimeSpan = 11 static
Definition at line 307 of file chain.h.
Referenced by GetMedianTimePast().
nNonce
uint32_t CBlockIndex::nNonce
Definition at line 214 of file chain.h.
Referenced by blockheaderToJSON(), CBlockIndex(), CDiskBlockIndex::GetBlockHash(), GetBlockHeader(), CBlockTreeDB::LoadBlockIndexGuts(), CDiskBlockIndex::SerializationOp(), and SetNull().
nSequenceId
int32_t CBlockIndex::nSequenceId
(memory only) Sequential id assigned to distinguish order in which blocks are received.
Definition at line 217 of file chain.h.
Referenced by CChainState::AddToBlockIndex(), CChainState::CheckBlockIndex(), CChainState::PreciousBlock(), CChainState::ReceivedBlockTransactions(), and SetNull().
nStatus
uint32_t CBlockIndex::nStatus
Verification status of this block. See enum BlockStatus.
Definition at line 207 of file chain.h.
Referenced by CChainState::AcceptBlock(), CChainState::AcceptBlockHeader(), CChainState::CheckBlockIndex(), CWallet::CreateWalletFromFile(), CChainState::FindMostWorkChain(), getblockchaininfo(), GetBlockChecked(), GetBlockPos(), getblocktemplate(), getrawtransaction(), GetUndoPos(), CChainState::InvalidateBlock(), CChainState::InvalidBlockFound(), IsValid(), CChainState::LoadBlockIndex(), LoadBlockIndexDB(), CBlockTreeDB::LoadBlockIndexGuts(), ProcessHeadersMessage(), ProcessMessage(), PruneOneBlockFile(), RaiseValidity(), CChainState::ReceivedBlockTransactions(), rescanblockchain(), CChainState::ResetBlockFailureFlags(), rest_block(), CDiskBlockIndex::SerializationOp(), SetNull(), submitblock(), CVerifyDB::VerifyDB(), and WriteUndoDataForBlock().
nTime
uint32_t CBlockIndex::nTime
Definition at line 212 of file chain.h.
Referenced by AddTx(), AppInitMain(), blockheaderToJSON(), CBlockIndex(), CChainState::ConnectBlock(), CDiskBlockIndex::GetBlockHash(), GetBlockHeader(), GetBlockTime(), getchaintxstats(), CChainState::LoadBlockIndex(), CBlockTreeDB::LoadBlockIndexGuts(), masternodelist(), CDiskBlockIndex::SerializationOp(), and SetNull().
nTimeMax
unsigned int CBlockIndex::nTimeMax
(memory only) Maximum nTime in the chain up to and including this block.
Definition at line 220 of file chain.h.
Referenced by GetBlockTimeMax(), CChainState::LoadBlockIndex(), and SetNull().
nTx
unsigned int CBlockIndex::nTx
Number of transactions in this block.
Note: in a potential headers-first mode, this number cannot be relied upon
Definition at line 199 of file chain.h.
Referenced by CChainState::AcceptBlock(), blockheaderToJSON(), blockToJSON(), CChainState::CheckBlockIndex(), CWallet::CreateWalletFromFile(), GetBlockChecked(), CChainState::LoadBlockIndex(), CBlockTreeDB::LoadBlockIndexGuts(), ProcessMessage(), CChainState::ReceivedBlockTransactions(), rest_block(), CDiskBlockIndex::SerializationOp(), and SetNull().
nUndoPos
unsigned int CBlockIndex::nUndoPos
Byte offset within rev?????.dat where this block's undo data is stored.
Definition at line 192 of file chain.h.
Referenced by GetUndoPos(), CBlockTreeDB::LoadBlockIndexGuts(), PruneOneBlockFile(), CChainState::ReceivedBlockTransactions(), CDiskBlockIndex::SerializationOp(), SetNull(), and WriteUndoDataForBlock().
nVersion
int32_t CBlockIndex::nVersion
block header
Definition at line 210 of file chain.h.
Referenced by blockheaderToJSON(), CBlockIndex(), WarningBitsConditionChecker::Condition(), CDiskBlockIndex::GetBlockHash(), GetBlockHeader(), CBlockTreeDB::LoadBlockIndexGuts(), CDiskBlockIndex::SerializationOp(), SetNull(), and UpdateTip().
phashBlock
const uint256* CBlockIndex::phashBlock
pointer to the hash of the block, if any. Memory is owned by this CBlockIndex
Definition at line 174 of file chain.h.
Referenced by AddTx(), CheckForkWarningConditions(), CChainState::ConnectBlock(), GetBlockHash(), getchaintips(), CPrivateSendBroadcastTx::IsExpired(), and SetNull().
pprev
CBlockIndex* CBlockIndex::pprev
pointer to the index of the predecessor of this block
Definition at line 177 of file chain.h.
Referenced by CChainState::AcceptBlock(), CChainState::AcceptBlockHeader(), CChainState::ActivateBestChainStep(), CWallet::BlockConnected(), blockheaderToJSON(), blockToJSON(), BuildSkip(), CDiskBlockIndex::CDiskBlockIndex(), llmq::CChainLocksHandler::CheckActiveState(), CChainState::CheckBlockIndex(), CheckCbTxMerkleRoots(), CheckForkWarningConditionsOnNewFork(), CheckSequenceLocks(), CDeterministicMNManager::CleanupCache(), WarningBitsConditionChecker::Condition(), CChainState::ConnectBlock(), CChainState::ConnectTip(), CWallet::CreateWalletFromFile(), DarkGravityWave(), CChainState::DisconnectBlock(), CChainState::DisconnectTip(), llmq::CChainLocksHandler::EnforceBestChainLock(), EvaluateSequenceLocks(), CChain::FindFork(), CChainState::FindMostWorkChain(), GetAncestor(), getblockchaininfo(), GetBlockHeader(), GetBlockScriptFlags(), getblockstats(), CDeterministicMNManager::GetListForBlock(), GetMedianTimePast(), GetNetworkHashPS(), GetNextWorkRequiredBTC(), AbstractThresholdConditionChecker::GetStateFor(), AbstractThresholdConditionChecker::GetStateStatisticsFor(), CChainState::InvalidateBlock(), KimotoGravityWell(), LastCommonAncestor(), listsinceblock(), CChainState::LoadBlockIndex(), CBlockTreeDB::LoadBlockIndexGuts(), PeerLogicValidation::NewPoWValidBlock(), CDeterministicMNManager::ProcessBlock(), ProcessHeadersMessage(), ProcessSpecialTxsInBlock(), PruneOneBlockFile(), CChainState::ReceivedBlockTransactions(), CChainState::ReplayBlocks(), rescanblockchain(), CChainState::ResetBlockFailureFlags(), PeerLogicValidation::SendMessages(), SetNull(), CChain::SetTip(), ToString(), llmq::CChainLocksHandler::TrySignChainTip(), llmq::CQuorumBlockProcessor::UndoBlock(), CDeterministicMNManager::UndoBlock(), CActiveMasternodeManager::UpdatedBlockTip(), PeerLogicValidation::UpdatedBlockTip(), llmq::CInstantSendManager::UpdatedBlockTip(), UpdateTip(), CVerifyDB::VerifyDB(), and WriteUndoDataForBlock().
pskip
CBlockIndex* CBlockIndex::pskip
pointer to the index of some further predecessor of this block
Definition at line 180 of file chain.h.
Referenced by BuildSkip(), CChainState::CheckBlockIndex(), GetAncestor(), and SetNull().
The documentation for this class was generated from the following files:
src/chain.h
src/chain.cpp
Released under the MIT license