Dash Core: CBLSSecretKey Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSSecretKey Class Reference
#include <bls.h>
Public Member Functions
CBLSSecretKey ()
void AggregateInsecure (const CBLSSecretKey &o)
void MakeNewKey ()
bool SecretKeyShare (const std::vector< CBLSSecretKey > &msk, const CBLSId &id)
CBLSPublicKey GetPublicKey () const
CBLSSignature Sign (const uint256 &hash) const
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const C &r) const
bool operator!= (const C &r) const
Public Member Functions inherited from CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >
CBLSWrapper ()
CBLSWrapper (const CBLSWrapper &ref)=default
CBLSWrapper (CBLSWrapper &&ref)
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const CBLSSecretKey &r) const
bool operator!= (const CBLSSecretKey &r) const
bool IsValid () const
void SetBuf (const void *buf, size_t size)
void SetBuf (const T &buf)
void Reset ()
void GetBuf (void *buf, size_t size) const
void GetBuf (T &buf) const
const uint256 & GetHash () const
void UpdateHash () const
bool SetHexStr (const std::string &str)
void Serialize (CSizeComputer &s) const
void Serialize (Stream &s) const
void Unserialize (Stream &s, bool checkMalleable=true)
bool CheckMalleable (void *buf, size_t size) const
std::string ToString () const
Static Public Member Functions
static CBLSSecretKey AggregateInsecure (const std::vector< CBLSSecretKey > &sks)
Protected Member Functions
bool InternalSetBuf (const void *buf)
bool InternalGetBuf (void *buf) const
Protected Member Functions inherited from CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >
constexpr size_t GetSerSize () const
Additional Inherited Members
Static Public Attributes inherited from CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >
static const size_t SerSize
Protected Attributes inherited from CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >
bls::PrivateKey impl
bool fValid
uint256 cachedHash
Detailed Description
Definition at line 238 of file bls.h.
Constructor & Destructor Documentation
CBLSSecretKey()
CBLSSecretKey::CBLSSecretKey () inline
Definition at line 245 of file bls.h.
Referenced by AggregateInsecure().
Member Function Documentation
AggregateInsecure() [1/2]
void CBLSSecretKey::AggregateInsecure (const CBLSSecretKey & o)
Definition at line 74 of file bls.cpp.
References CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::impl, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::IsValid(), and CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::UpdateHash().
Referenced by BLSSecKeyAggregate_Normal().
AggregateInsecure() [2/2]
CBLSSecretKey CBLSSecretKey::AggregateInsecure (const std::vector< CBLSSecretKey > & sks) static
Definition at line 81 of file bls.cpp.
References CBLSSecretKey(), CBLSWrapper< ImplType, _SerSize, C >::fValid, CBLSWrapper< ImplType, _SerSize, C >::impl, and CBLSWrapper< ImplType, _SerSize, C >::UpdateHash().
GetPublicKey()
CBLSPublicKey CBLSSecretKey::GetPublicKey () const
Definition at line 147 of file bls.cpp.
References CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::CBLSPublicKey, CBLSWrapper< ImplType, _SerSize, C >::fValid, CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::impl, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::IsValid(), and CBLSWrapper< ImplType, _SerSize, C >::UpdateHash().
Referenced by AppInitMain(), CBLSWorker::AsyncVerifyContributionShare(), bls_fromsecret(), bls_generate(), BLSPubKeyAggregate_Normal(), BLSSecKeyAggregate_Normal(), BLSSign_Normal(), CBLSIESEncryptedBlob::Encrypt(), CBLSIESMultiRecipientBlobs::InitEncrypt(), llmq::CDKGSession::SendCommitment(), ContributionVerifier::Verify(), and CBLSWorker::VerifyContributionShare().
InternalGetBuf()
bool CBLSSecretKey::InternalGetBuf (void * buf) const protected virtual
Implements CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >.
Definition at line 68 of file bls.cpp.
References CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::impl.
InternalSetBuf()
bool CBLSSecretKey::InternalSetBuf (const void * buf) protected virtual
Implements CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >.
Definition at line 58 of file bls.cpp.
References CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::impl.
MakeNewKey()
void CBLSSecretKey::MakeNewKey ()
Definition at line 102 of file bls.cpp.
References CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::fValid, GetStrongRandBytes(), CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::impl, and CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::UpdateHash().
Referenced by bls_generate(), BLSPubKeyAggregate_Normal(), BLSSecKeyAggregate_Normal(), BLSSign_Normal(), BuildTestVectors(), CBLSIESEncryptedBlob::Encrypt(), CBLSIESMultiRecipientBlobs::InitEncrypt(), llmq::CDKGSession::SendCommitment(), llmq::CDKGSession::SendContributions(), and llmq::CDKGSession::SendJustification().
operator!=()
bool CBLSWrapper< ImplType, _SerSize, C >::operator!= inline
Definition at line 89 of file bls.h.
operator=() [1/2]
CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= default
operator=() [2/2]
CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= inline
Definition at line 77 of file bls.h.
operator==()
bool CBLSWrapper< ImplType, _SerSize, C >::operator== inline
Definition at line 85 of file bls.h.
SecretKeyShare()
bool CBLSSecretKey::SecretKeyShare (const std::vector< CBLSSecretKey > & msk, const CBLSId & id)
Definition at line 118 of file bls.cpp.
References base_blob< BITS >::begin(), CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::fValid, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::impl, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), and CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::UpdateHash().
Sign()
CBLSSignature CBLSSecretKey::Sign (const uint256 & hash) const
Definition at line 160 of file bls.cpp.
References base_blob< BITS >::begin(), CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::CBLSSignature, CBLSWrapper< ImplType, _SerSize, C >::fValid, CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::impl, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< bls::PrivateKey, BLS_CURVE_SECKEY_SIZE, CBLSSecretKey >::IsValid(), and CBLSWrapper< ImplType, _SerSize, C >::UpdateHash().
Referenced by CBLSWorker::AsyncSign(), BLSSign_Normal(), BuildTestVectors(), llmq::CDKGSession::SendCommitment(), CGovernanceVote::Sign(), CGovernanceObject::Sign(), and llmq::CSigSharesManager::Sign().
The documentation for this class was generated from the following files:
src/bls/bls.h
src/bls/bls.cpp
Released under the MIT license