Dash Core: test_framework.script.CScript Class Reference
test_framework.script.CScript Class Reference
Public Member Functions
def __add__ (self, other)
def join (self, iterable)
def __new__ (cls, value=b'')
def raw_iter (self)
def __iter__ (self)
def __repr__ (self)
def GetSigOpCount (self, fAccurate)
Private Member Functions
def __coerce_instance (cls, other)
Detailed Description
Serialized script
A bytes subclass, so you can use this directly whenever bytes are accepted.
Note that this means that indexing does *not* work - you'll get an index by
byte rather than opcode. This format was chosen for efficiency so that the
general case would not require creating a lot of little CScriptOP objects.
iter(script) however does iterate by opcode.
Definition at line 641 of file script.py.
Member Function Documentation
__add__()
def test_framework.script.CScript.__add__ (self, other)
Definition at line 672 of file script.py.
__coerce_instance()
def test_framework.script.CScript.__coerce_instance (cls, other) private
Definition at line 652 of file script.py.
Referenced by test_framework.script.CScript.__add__(), and test_framework.script.CScript.__new__().
__iter__()
def test_framework.script.CScript.__iter__ (self)
'Cooked' iteration
Returns either a CScriptOP instance, an integer, or bytes, as
appropriate.
See raw_iter() if you need to distinguish the different possible
PUSHDATA encodings.
Definition at line 755 of file script.py.
__new__()
def test_framework.script.CScript.__new__ (cls, value = b'')
Definition at line 687 of file script.py.
__repr__()
def test_framework.script.CScript.__repr__ (self)
Definition at line 775 of file script.py.
GetSigOpCount()
def test_framework.script.CScript.GetSigOpCount (self, fAccurate)
Get the SigOp count.
fAccurate - Accurately count CHECKMULTISIG, see BIP16 for details.
Note that this is consensus-critical.
Definition at line 804 of file script.py.
join()
def test_framework.script.CScript.join (self, iterable)
Definition at line 683 of file script.py.
Referenced by test_framework.script.CScript.__new__(), and test_framework.script.CScript.__repr__().
raw_iter()
def test_framework.script.CScript.raw_iter (self)
Raw iteration
Yields tuples of (opcode, data, sop_idx) so that the different possible
PUSHDATA encodings can be accurately distinguished, as well as
determining the exact opcode byte indexes. (sop_idx)
Definition at line 698 of file script.py.
Referenced by test_framework.script.CScript.__iter__(), and test_framework.script.CScript.GetSigOpCount().
The documentation for this class was generated from the following file:
qa/rpc-tests/test_framework/script.py