Dash Core: CAccount Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CAccount Class Reference
Account information.
#include <wallet.h>
Public Member Functions
CAccount ()
void SetNull ()
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
Public Attributes
CPubKey vchPubKey
ADD_SERIALIZE_METHODS
Detailed Description
Account information.
Stored in wallet with key "acc"+string account name.
Definition at line 1080 of file wallet.h.
Constructor & Destructor Documentation
CAccount()
CAccount::CAccount () inline
Definition at line 1085 of file wallet.h.
References SetNull().
Member Function Documentation
SerializationOp()
template<typename Stream , typename Operation > void CAccount::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 1098 of file wallet.h.
References READWRITE, SER_GETHASH, and vchPubKey.
SetNull()
void CAccount::SetNull () inline
Definition at line 1090 of file wallet.h.
References vchPubKey.
Referenced by CAccount(), and CWalletDB::ReadAccount().
Member Data Documentation
ADD_SERIALIZE_METHODS
CAccount::ADD_SERIALIZE_METHODS
Definition at line 1095 of file wallet.h.
vchPubKey
CPubKey CAccount::vchPubKey
Definition at line 1083 of file wallet.h.
Referenced by GetAccountAddress(), SerializationOp(), and SetNull().
The documentation for this class was generated from the following file:
src/wallet/wallet.h
Released under the MIT license