Dash Core: EditAddressDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
EditAddressDialog Class Reference
Dialog for editing an address and associated information.
#include <editaddressdialog.h>
Public Types
enum Mode { NewReceivingAddress, NewSendingAddress, EditReceivingAddress, EditSendingAddress }
Public Slots
void accept ()
Public Member Functions
EditAddressDialog (Mode mode, QWidget *parent)
~EditAddressDialog ()
void setModel (AddressTableModel *model)
void loadRow (int row)
QString getAddress () const
void setAddress (const QString &address)
Private Member Functions
bool saveCurrentRow ()
Private Attributes
Ui::EditAddressDialog * ui
QDataWidgetMapper * mapper
Mode mode
AddressTableModel * model
QString address
Detailed Description
Dialog for editing an address and associated information.
Definition at line 22 of file editaddressdialog.h.
Member Enumeration Documentation
Mode
enum EditAddressDialog::Mode
Enumerator
NewReceivingAddress
NewSendingAddress
EditReceivingAddress
EditSendingAddress
Definition at line 27 of file editaddressdialog.h.
Constructor & Destructor Documentation
EditAddressDialog()
EditAddressDialog::EditAddressDialog (Mode mode, QWidget * parent) explicit
Definition at line 15 of file editaddressdialog.cpp.
References EditReceivingAddress, EditSendingAddress, mapper, mode, NewReceivingAddress, NewSendingAddress, GUIUtil::setupAddressWidget(), and ui.
~EditAddressDialog()
EditAddressDialog::~EditAddressDialog ()
Definition at line 48 of file editaddressdialog.cpp.
References ui.
Member Function Documentation
accept
void EditAddressDialog::accept () slot
Definition at line 94 of file editaddressdialog.cpp.
References AddressTableModel::DUPLICATE_ADDRESS, AddressTableModel::getEditStatus(), AddressTableModel::INVALID_ADDRESS, AddressTableModel::KEY_GENERATION_FAILURE, model, AddressTableModel::NO_CHANGES, AddressTableModel::OK, saveCurrentRow(), ui, and AddressTableModel::WALLET_UNLOCK_FAILURE.
getAddress()
QString EditAddressDialog::getAddress () const
Definition at line 136 of file editaddressdialog.cpp.
References address.
Referenced by AddressBookPage::on_newAddress_clicked().
loadRow()
void EditAddressDialog::loadRow (int row)
Definition at line 64 of file editaddressdialog.cpp.
References mapper.
Referenced by TransactionView::editLabel(), and AddressBookPage::onEditAction().
saveCurrentRow()
bool EditAddressDialog::saveCurrentRow () private
Definition at line 69 of file editaddressdialog.cpp.
References address, AddressTableModel::addRow(), EditReceivingAddress, EditSendingAddress, mapper, mode, model, NewReceivingAddress, NewSendingAddress, AddressTableModel::Receive, AddressTableModel::Send, and ui.
Referenced by accept().
setAddress()
void EditAddressDialog::setAddress (const QString & address)
Definition at line 141 of file editaddressdialog.cpp.
References address, and ui.
Referenced by TransactionView::editLabel().
setModel()
void EditAddressDialog::setModel (AddressTableModel * model)
Definition at line 53 of file editaddressdialog.cpp.
References AddressTableModel::Address, AddressTableModel::Label, mapper, model, and ui.
Referenced by TransactionView::editLabel(), AddressBookPage::on_newAddress_clicked(), and AddressBookPage::onEditAction().
Member Data Documentation
address
QString EditAddressDialog::address private
Definition at line 54 of file editaddressdialog.h.
Referenced by getAddress(), saveCurrentRow(), and setAddress().
mapper
QDataWidgetMapper* EditAddressDialog::mapper private
Definition at line 50 of file editaddressdialog.h.
Referenced by EditAddressDialog(), loadRow(), saveCurrentRow(), and setModel().
mode
Mode EditAddressDialog::mode private
Definition at line 51 of file editaddressdialog.h.
Referenced by EditAddressDialog(), and saveCurrentRow().
model
AddressTableModel* EditAddressDialog::model private
Definition at line 52 of file editaddressdialog.h.
Referenced by accept(), saveCurrentRow(), and setModel().
ui
Ui::EditAddressDialog* EditAddressDialog::ui private
Definition at line 49 of file editaddressdialog.h.
Referenced by accept(), EditAddressDialog(), saveCurrentRow(), setAddress(), setModel(), and ~EditAddressDialog().
The documentation for this class was generated from the following files:
src/qt/editaddressdialog.h
src/qt/editaddressdialog.cpp
Released under the MIT license