Dash Core: PaymentServer Class Reference
PaymentServer Class Reference
#include <paymentserver.h>
Public Slots
void uiReady ()
void fetchPaymentACK (CWallet *wallet, SendCoinsRecipient recipient, QByteArray transaction)
void handleURIOrFile (const QString &s)
Signals
void receivedPaymentRequest (SendCoinsRecipient)
void receivedPaymentACK (const QString &paymentACKMsg)
void message (const QString &title, const QString &message, unsigned int style)
Public Member Functions
PaymentServer (QObject *parent, bool startLocalServer=true)
~PaymentServer ()
void setOptionsModel (OptionsModel *optionsModel)
Static Public Member Functions
static void ipcParseCommandLine (int argc, char *argv[])
static bool ipcSendCommandLine ()
static void LoadRootCAs (X509_STORE *store=NULL)
static X509_STORE * getCertStore ()
static bool verifyNetwork (const payments::PaymentDetails &requestDetails)
static bool verifyExpired (const payments::PaymentDetails &requestDetails)
static bool verifySize (qint64 requestSize)
static bool verifyAmount (const CAmount &requestAmount)
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event)
Private Slots
void handleURIConnection ()
void netRequestFinished (QNetworkReply *)
void reportSslErrors (QNetworkReply *, const QList< QSslError > &)
void handlePaymentACK (const QString &paymentACKMsg)
Private Member Functions
bool processPaymentRequest (const PaymentRequestPlus &request, SendCoinsRecipient &recipient)
void fetchRequest (const QUrl &url)
void initNetManager ()
Static Private Member Functions
static bool readPaymentRequestFromFile (const QString &filename, PaymentRequestPlus &request)
Private Attributes
bool saveURIs
QLocalServer * uriServer
QNetworkAccessManager * netManager
OptionsModel * optionsModel
Detailed Description
Definition at line 58 of file paymentserver.h.
Constructor & Destructor Documentation
PaymentServer()
PaymentServer::PaymentServer (QObject * parent, bool startLocalServer = true)
Definition at line 301 of file paymentserver.cpp.
~PaymentServer()
PaymentServer::~PaymentServer ()
Definition at line 339 of file paymentserver.cpp.
Member Function Documentation
eventFilter()
bool PaymentServer::eventFilter (QObject * object, QEvent * event) protected
Definition at line 349 of file paymentserver.cpp.
fetchPaymentACK
void PaymentServer::fetchPaymentACK (CWallet * wallet, SendCoinsRecipient recipient, QByteArray transaction) slot
Definition at line 624 of file paymentserver.cpp.
fetchRequest()
void PaymentServer::fetchRequest (const QUrl & url) private
Definition at line 614 of file paymentserver.cpp.
Referenced by handleURIOrFile().
getCertStore()
X509_STORE * PaymentServer::getCertStore () static
Definition at line 812 of file paymentserver.cpp.
Referenced by TransactionDesc::toHTML().
handlePaymentACK
void PaymentServer::handlePaymentACK (const QString & paymentACKMsg) private slot
Definition at line 758 of file paymentserver.cpp.
Referenced by PaymentServer().
handleURIConnection
void PaymentServer::handleURIConnection () private slot
Definition at line 479 of file paymentserver.cpp.
Referenced by PaymentServer().
handleURIOrFile
void PaymentServer::handleURIOrFile (const QString & s) slot
Definition at line 403 of file paymentserver.cpp.
Referenced by eventFilter(), handleURIConnection(), and uiReady().
initNetManager()
void PaymentServer::initNetManager () private
Definition at line 364 of file paymentserver.cpp.
Referenced by uiReady().
ipcParseCommandLine()
void PaymentServer::ipcParseCommandLine (int argc, char * argv[]) static
Definition at line 205 of file paymentserver.cpp.
Referenced by main().
ipcSendCommandLine()
bool PaymentServer::ipcSendCommandLine () static
Definition at line 268 of file paymentserver.cpp.
Referenced by main().
LoadRootCAs()
void PaymentServer::LoadRootCAs (X509_STORE * store = NULL) static
Definition at line 114 of file paymentserver.cpp.
Referenced by BitcoinApplication::initializeResult().
message
void PaymentServer::message (const QString & title, const QString & message, unsigned int style) signal
Definition at line 206 of file moc_paymentserver.cpp.
Referenced by handlePaymentACK(), handleURIOrFile(), netRequestFinished(), processPaymentRequest(), and reportSslErrors().
netRequestFinished
void PaymentServer::netRequestFinished (QNetworkReply * reply) private slot
Definition at line 679 of file paymentserver.cpp.
Referenced by initNetManager().
processPaymentRequest()
bool PaymentServer::processPaymentRequest (const PaymentRequestPlus & request, SendCoinsRecipient & recipient) private
Definition at line 522 of file paymentserver.cpp.
Referenced by handleURIOrFile(), and netRequestFinished().
readPaymentRequestFromFile()
bool PaymentServer::readPaymentRequestFromFile (const QString & filename, PaymentRequestPlus & request) static private
Definition at line 504 of file paymentserver.cpp.
Referenced by handleURIOrFile(), and ipcParseCommandLine().
receivedPaymentACK
void PaymentServer::receivedPaymentACK (const QString & paymentACKMsg) signal
Definition at line 199 of file moc_paymentserver.cpp.
Referenced by netRequestFinished(), and PaymentServer().
receivedPaymentRequest
void PaymentServer::receivedPaymentRequest (SendCoinsRecipient _t1) signal
Definition at line 192 of file moc_paymentserver.cpp.
Referenced by handleURIOrFile(), and netRequestFinished().
reportSslErrors
void PaymentServer::reportSslErrors (QNetworkReply * reply, const QList< QSslError > & errs) private slot
Definition at line 741 of file paymentserver.cpp.
Referenced by initNetManager().
setOptionsModel()
void PaymentServer::setOptionsModel (OptionsModel * optionsModel)
Definition at line 753 of file paymentserver.cpp.
uiReady
void PaymentServer::uiReady () slot
Definition at line 391 of file paymentserver.cpp.
verifyAmount()
bool PaymentServer::verifyAmount (const CAmount & requestAmount) static
Definition at line 800 of file paymentserver.cpp.
Referenced by processPaymentRequest().
verifyExpired()
bool PaymentServer::verifyExpired (const payments::PaymentDetails & requestDetails) static
Definition at line 776 of file paymentserver.cpp.
Referenced by processPaymentRequest(), and WalletModel::sendCoins().
verifyNetwork()
bool PaymentServer::verifyNetwork (const payments::PaymentDetails & requestDetails) static
Definition at line 764 of file paymentserver.cpp.
Referenced by processPaymentRequest().
verifySize()
bool PaymentServer::verifySize (qint64 requestSize) static
Definition at line 788 of file paymentserver.cpp.
Referenced by netRequestFinished(), and readPaymentRequestFromFile().
Member Data Documentation
netManager
QNetworkAccessManager* PaymentServer::netManager private
Definition at line 143 of file paymentserver.h.
Referenced by fetchPaymentACK(), fetchRequest(), and initNetManager().
optionsModel
OptionsModel* PaymentServer::optionsModel private
Definition at line 145 of file paymentserver.h.
Referenced by initNetManager(), processPaymentRequest(), and setOptionsModel().
saveURIs
bool PaymentServer::saveURIs private
Definition at line 140 of file paymentserver.h.
Referenced by handleURIOrFile(), and uiReady().
uriServer
QLocalServer* PaymentServer::uriServer private
Definition at line 141 of file paymentserver.h.
Referenced by handleURIConnection(), and PaymentServer().
The documentation for this class was generated from the following files:
src/qt/paymentserver.h
src/qt/moc_paymentserver.cpp
src/qt/paymentserver.cpp