Dash Core: payments::X509Certificates Class Reference
payments::X509Certificates Class Reference
#include <paymentrequest.pb.h>
Public Member Functions
X509Certificates ()
virtual ~X509Certificates ()
X509Certificates (const X509Certificates &from)
X509Certificates & operator= (const X509Certificates &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline ::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (X509Certificates *other)
X509Certificates * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const X509Certificates &from)
void MergeFrom (const X509Certificates &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
int certificate_size () const
void clear_certificate ()
const ::std::string & certificate (int index) const
inline ::std::string * mutable_certificate (int index)
void set_certificate (int index, const ::std::string &value)
void set_certificate (int index, const char *value)
void set_certificate (int index, const void *value, size_t size)
inline ::std::string * add_certificate ()
void add_certificate (const ::std::string &value)
void add_certificate (const char *value)
void add_certificate (const void *value, size_t size)
const ::google::protobuf::RepeatedPtrField< ::std::string > & certificate () const
inline ::google::protobuf::RepeatedPtrField< ::std::string > * mutable_certificate ()
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const X509Certificates & default_instance ()
Static Public Attributes
static const int kCertificateFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint32 _has_bits_ [1]
int _cached_size_
::google::protobuf::RepeatedPtrField< ::std::string > certificate_
Static Private Attributes
static X509Certificates * default_instance_ = NULL
Friends
void protobuf_AddDesc_paymentrequest_2eproto ()
void protobuf_AssignDesc_paymentrequest_2eproto ()
void protobuf_ShutdownFile_paymentrequest_2eproto ()
Detailed Description
Definition at line 442 of file paymentrequest.pb.h.
Constructor & Destructor Documentation
X509Certificates() [1/2]
payments::X509Certificates::X509Certificates ()
Definition at line 1502 of file paymentrequest.pb.cc.
Referenced by New().
~X509Certificates()
payments::X509Certificates::~X509Certificates () virtual
Definition at line 1524 of file paymentrequest.pb.cc.
X509Certificates() [2/2]
payments::X509Certificates::X509Certificates (const X509Certificates & from)
Definition at line 1511 of file paymentrequest.pb.cc.
Member Function Documentation
add_certificate() [1/4]
std::string * payments::X509Certificates::add_certificate () inline
Definition at line 1608 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
add_certificate() [2/4]
void payments::X509Certificates::add_certificate (const ::std::string & value) inline
Definition at line 1611 of file paymentrequest.pb.h.
add_certificate() [3/4]
void payments::X509Certificates::add_certificate (const char * value) inline
Definition at line 1615 of file paymentrequest.pb.h.
add_certificate() [4/4]
void payments::X509Certificates::add_certificate (const void * value, size_t size) inline
Definition at line 1619 of file paymentrequest.pb.h.
ByteSize()
int payments::X509Certificates::ByteSize () const
Definition at line 1640 of file paymentrequest.pb.cc.
certificate() [1/2]
const ::std::string & payments::X509Certificates::certificate (int index) const inline
Definition at line 1587 of file paymentrequest.pb.h.
Referenced by PaymentRequestPlus::getMerchant().
certificate() [2/2]
const ::google::protobuf::RepeatedPtrField<::std::string > & payments::X509Certificates::certificate () const inline
Definition at line 1624 of file paymentrequest.pb.h.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
certificate_size()
int payments::X509Certificates::certificate_size () const inline
Definition at line 1581 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentRequestPlus::getMerchant(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Clear()
void payments::X509Certificates::Clear ()
Definition at line 1555 of file paymentrequest.pb.cc.
Referenced by CopyFrom().
clear_certificate()
void payments::X509Certificates::clear_certificate () inline
Definition at line 1584 of file paymentrequest.pb.h.
CopyFrom() [1/2]
void payments::X509Certificates::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1679 of file paymentrequest.pb.cc.
Referenced by operator=().
CopyFrom() [2/2]
void payments::X509Certificates::CopyFrom (const X509Certificates & from)
Definition at line 1685 of file paymentrequest.pb.cc.
default_instance()
const X509Certificates & payments::X509Certificates::default_instance () static
Definition at line 1544 of file paymentrequest.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * payments::X509Certificates::descriptor () static
Definition at line 1539 of file paymentrequest.pb.cc.
GetCachedSize()
int payments::X509Certificates::GetCachedSize () const inline
Definition at line 483 of file paymentrequest.pb.h.
GetMetadata()
google::protobuf::Metadata payments::X509Certificates::GetMetadata () const
Definition at line 1705 of file paymentrequest.pb.cc.
InitAsDefaultInstance()
void payments::X509Certificates::InitAsDefaultInstance () private
Definition at line 1508 of file paymentrequest.pb.cc.
Referenced by payments::protobuf_AddDesc_paymentrequest_2eproto().
IsInitialized()
bool payments::X509Certificates::IsInitialized () const
Definition at line 1691 of file paymentrequest.pb.cc.
MergeFrom() [1/2]
void payments::X509Certificates::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1661 of file paymentrequest.pb.cc.
Referenced by CopyFrom(), and X509Certificates().
MergeFrom() [2/2]
void payments::X509Certificates::MergeFrom (const X509Certificates & from)
Definition at line 1673 of file paymentrequest.pb.cc.
MergePartialFromCodedStream()
bool payments::X509Certificates::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1561 of file paymentrequest.pb.cc.
mutable_certificate() [1/2]
std::string * payments::X509Certificates::mutable_certificate (int index) inline
Definition at line 1591 of file paymentrequest.pb.h.
mutable_certificate() [2/2]
google::protobuf::RepeatedPtrField<::std::string > * payments::X509Certificates::mutable_certificate () inline
Definition at line 1629 of file paymentrequest.pb.h.
mutable_unknown_fields()
inline ::google::protobuf::UnknownFieldSet* payments::X509Certificates::mutable_unknown_fields () inline
Definition at line 458 of file paymentrequest.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
New()
X509Certificates * payments::X509Certificates::New () const
Definition at line 1551 of file paymentrequest.pb.cc.
operator=()
X509Certificates& payments::X509Certificates::operator= (const X509Certificates & from) inline
Definition at line 449 of file paymentrequest.pb.h.
SerializeWithCachedSizes()
void payments::X509Certificates::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1607 of file paymentrequest.pb.cc.
SerializeWithCachedSizesToArray()
google::protobuf::uint8 * payments::X509Certificates::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1623 of file paymentrequest.pb.cc.
set_certificate() [1/3]
void payments::X509Certificates::set_certificate (int index, const ::std::string & value) inline
Definition at line 1595 of file paymentrequest.pb.h.
set_certificate() [2/3]
void payments::X509Certificates::set_certificate (int index, const char * value) inline
Definition at line 1599 of file paymentrequest.pb.h.
set_certificate() [3/3]
void payments::X509Certificates::set_certificate (int index, const void * value, size_t size) inline
Definition at line 1603 of file paymentrequest.pb.h.
SetCachedSize()
void payments::X509Certificates::SetCachedSize (int size) const private
Definition at line 1534 of file paymentrequest.pb.cc.
SharedCtor()
void payments::X509Certificates::SharedCtor () private
Definition at line 1518 of file paymentrequest.pb.cc.
Referenced by X509Certificates().
SharedDtor()
void payments::X509Certificates::SharedDtor () private
Definition at line 1529 of file paymentrequest.pb.cc.
Referenced by ~X509Certificates().
Swap()
void payments::X509Certificates::Swap (X509Certificates * other)
Definition at line 1696 of file paymentrequest.pb.cc.
unknown_fields()
const ::google::protobuf::UnknownFieldSet& payments::X509Certificates::unknown_fields () const inline
Definition at line 454 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
protobuf_AddDesc_paymentrequest_2eproto
void protobuf_AddDesc_paymentrequest_2eproto () friend
Definition at line 201 of file paymentrequest.pb.cc.
Referenced by default_instance().
protobuf_AssignDesc_paymentrequest_2eproto
void protobuf_AssignDesc_paymentrequest_2eproto () friend
Definition at line 45 of file paymentrequest.pb.cc.
protobuf_ShutdownFile_paymentrequest_2eproto
void protobuf_ShutdownFile_paymentrequest_2eproto () friend
Definition at line 184 of file paymentrequest.pb.cc.
Member Data Documentation
_cached_size_
int payments::X509Certificates::_cached_size_ mutable private
Definition at line 517 of file paymentrequest.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
_has_bits_
::google::protobuf::uint32 payments::X509Certificates::_has_bits_[1] private
Definition at line 516 of file paymentrequest.pb.h.
Referenced by Clear(), SharedCtor(), and Swap().
_unknown_fields_
::google::protobuf::UnknownFieldSet payments::X509Certificates::_unknown_fields_ private
Definition at line 514 of file paymentrequest.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
certificate_
::google::protobuf::RepeatedPtrField< ::std::string> payments::X509Certificates::certificate_ private
Definition at line 518 of file paymentrequest.pb.h.
Referenced by add_certificate(), certificate(), certificate_size(), Clear(), clear_certificate(), MergeFrom(), mutable_certificate(), set_certificate(), and Swap().
default_instance_
X509Certificates * payments::X509Certificates::default_instance_ = NULL static private
Definition at line 524 of file paymentrequest.pb.h.
Referenced by default_instance(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_AssignDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), and SharedDtor().
kCertificateFieldNumber
const int payments::X509Certificates::kCertificateFieldNumber = 1 static
Definition at line 498 of file paymentrequest.pb.h.
The documentation for this class was generated from the following files:
src/qt/paymentrequest.pb.h
src/qt/paymentrequest.pb.cc