Dash Core: CBLSId Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSId Class Reference
#include <bls.h>
Public Member Functions
CBLSId ()
void SetInt (int x)
void SetHash (const uint256 &hash)
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const C &r) const
bool operator!= (const C &r) const
Public Member Functions inherited from CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >
CBLSWrapper ()
CBLSWrapper (const CBLSWrapper &ref)=default
CBLSWrapper (CBLSWrapper &&ref)
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const CBLSId &r) const
bool operator!= (const CBLSId &r) const
bool IsValid () const
void SetBuf (const void *buf, size_t size)
void SetBuf (const T &buf)
void Reset ()
void GetBuf (void *buf, size_t size) const
void GetBuf (T &buf) const
const uint256 & GetHash () const
void UpdateHash () const
bool SetHexStr (const std::string &str)
void Serialize (CSizeComputer &s) const
void Serialize (Stream &s) const
void Unserialize (Stream &s, bool checkMalleable=true)
bool CheckMalleable (void *buf, size_t size) const
std::string ToString () const
Static Public Member Functions
static CBLSId FromInt (int64_t i)
static CBLSId FromHash (const uint256 &hash)
Protected Member Functions
bool InternalSetBuf (const void *buf)
bool InternalGetBuf (void *buf) const
Protected Member Functions inherited from CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >
constexpr size_t GetSerSize () const
Additional Inherited Members
Static Public Attributes inherited from CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >
static const size_t SerSize
Protected Attributes inherited from CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >
uint256 impl
bool fValid
uint256 cachedHash
Detailed Description
Definition at line 218 of file bls.h.
Constructor & Destructor Documentation
CBLSId()
CBLSId::CBLSId () inline
Definition at line 225 of file bls.h.
Member Function Documentation
FromHash()
CBLSId CBLSId::FromHash (const uint256 & hash) static
Definition at line 51 of file bls.cpp.
References SetHash().
Referenced by llmq::CQuorum::GetPubKeyShare(), and llmq::CSigSharesManager::TryRecoverSig().
FromInt()
CBLSId CBLSId::FromInt (int64_t i) static
Definition at line 44 of file bls.cpp.
References SetInt().
InternalGetBuf()
bool CBLSId::InternalGetBuf (void * buf) const protected virtual
Implements CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >.
Definition at line 24 of file bls.cpp.
References base_blob< BITS >::begin(), CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::impl, and memcpy().
InternalSetBuf()
bool CBLSId::InternalSetBuf (const void * buf) protected virtual
Implements CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >.
Definition at line 18 of file bls.cpp.
References base_blob< BITS >::begin(), CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::impl, and memcpy().
operator!=()
bool CBLSWrapper< ImplType, _SerSize, C >::operator!= inline
Definition at line 89 of file bls.h.
operator=() [1/2]
CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= inline
Definition at line 77 of file bls.h.
operator=() [2/2]
CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= default
operator==()
bool CBLSWrapper< ImplType, _SerSize, C >::operator== inline
Definition at line 85 of file bls.h.
SetHash()
void CBLSId::SetHash (const uint256 & hash)
Definition at line 37 of file bls.cpp.
References CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::fValid, CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::impl, and CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::UpdateHash().
Referenced by FromHash().
SetInt()
void CBLSId::SetInt (int x)
Definition at line 30 of file bls.cpp.
References CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::fValid, CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::impl, base_blob< BITS >::SetHex(), strprintf, and CBLSWrapper< uint256, BLS_CURVE_ID_SIZE, CBLSId >::UpdateHash().
Referenced by FromInt().
The documentation for this class was generated from the following files:
src/bls/bls.h
src/bls/bls.cpp
Released under the MIT license