Dash Core: CoinControlDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CoinControlDialog Class Reference
#include <coincontroldialog.h>
Public Member Functions
CoinControlDialog (QWidget *parent=0)
~CoinControlDialog ()
void setModel (WalletModel *model)
Static Public Member Functions
static void updateLabels (WalletModel *, QDialog *)
static CCoinControl * coinControl ()
static void usePrivateSend (bool fUsePrivateSend)
Static Public Attributes
static QList< CAmount > payAmounts
static bool fSubtractFeeFromAmount = false
Private Types
enum {
COLUMN_CHECKBOX = 0, COLUMN_AMOUNT, COLUMN_LABEL, COLUMN_ADDRESS,
COLUMN_PRIVATESEND_ROUNDS, COLUMN_DATE, COLUMN_CONFIRMATIONS
}
enum { TxHashRole = Qt::UserRole, VOutRole }
enum Mode { Mode::NORMAL, Mode::PRIVATESEND }
Private Slots
void showMenu (const QPoint &)
void copyAmount ()
void copyLabel ()
void copyAddress ()
void copyTransactionHash ()
void lockCoin ()
void unlockCoin ()
void clipboardQuantity ()
void clipboardAmount ()
void clipboardFee ()
void clipboardAfterFee ()
void clipboardBytes ()
void clipboardLowOutput ()
void clipboardChange ()
void radioTreeMode (bool)
void radioListMode (bool)
void viewItemChanged (QTreeWidgetItem *, int)
void headerSectionClicked (int)
void buttonBoxClicked (QAbstractButton *)
void buttonSelectAllClicked ()
void buttonToggleLockClicked ()
void updateLabelLocked ()
void on_hideButton_clicked ()
Private Member Functions
void sortView (int, Qt::SortOrder)
void updateView ()
Private Attributes
Ui::CoinControlDialog * ui
WalletModel * model
int sortColumn
Qt::SortOrder sortOrder
QMenu * contextMenu
QTreeWidgetItem * contextMenuItem
QAction * copyTransactionHashAction
QAction * lockAction
QAction * unlockAction
bool fHideAdditional {true}
Static Private Attributes
static CoinControlDialog::Mode mode {CoinControlDialog::Mode::NORMAL}
Friends
class CCoinControlWidgetItem
Detailed Description
Definition at line 40 of file coincontroldialog.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
COLUMN_CHECKBOX
COLUMN_AMOUNT
COLUMN_LABEL
COLUMN_ADDRESS
COLUMN_PRIVATESEND_ROUNDS
COLUMN_DATE
COLUMN_CONFIRMATIONS
Definition at line 75 of file coincontroldialog.h.
anonymous enum
anonymous enum private
Enumerator
TxHashRole
VOutRole
Definition at line 86 of file coincontroldialog.h.
Mode
enum CoinControlDialog::Mode strong private
Enumerator
NORMAL
PRIVATESEND
Definition at line 94 of file coincontroldialog.h.
Constructor & Destructor Documentation
CoinControlDialog()
CoinControlDialog::CoinControlDialog (QWidget * parent = 0) explicit
Definition at line 46 of file coincontroldialog.cpp.
References GUIUtil::Bold, buttonBoxClicked(), buttonSelectAllClicked(), buttonToggleLockClicked(), clipboardAfterFee(), clipboardAmount(), clipboardBytes(), clipboardChange(), clipboardFee(), clipboardLowOutput(), clipboardQuantity(), COLUMN_ADDRESS, COLUMN_AMOUNT, COLUMN_CHECKBOX, COLUMN_CONFIRMATIONS, COLUMN_DATE, COLUMN_LABEL, COLUMN_PRIVATESEND_ROUNDS, contextMenu, copyAddress(), copyAmount(), copyLabel(), copyTransactionHash(), copyTransactionHashAction, GUIUtil::disableMacFocusRect(), headerSectionClicked(), lockAction, lockCoin(), radioListMode(), radioTreeMode(), GUIUtil::setFont(), showMenu(), sortView(), ui, unlockAction, unlockCoin(), GUIUtil::updateFonts(), and viewItemChanged().
~CoinControlDialog()
CoinControlDialog::~CoinControlDialog ()
Definition at line 167 of file coincontroldialog.cpp.
References sortColumn, sortOrder, and ui.
Member Function Documentation
buttonBoxClicked
void CoinControlDialog::buttonBoxClicked (QAbstractButton * button) private slot
Definition at line 190 of file coincontroldialog.cpp.
References done, and ui.
Referenced by CoinControlDialog().
buttonSelectAllClicked
void CoinControlDialog::buttonSelectAllClicked () private slot
Definition at line 197 of file coincontroldialog.cpp.
References coinControl(), COLUMN_CHECKBOX, model, ui, CCoinControl::UnSelectAll(), and updateLabels().
Referenced by CoinControlDialog().
buttonToggleLockClicked
void CoinControlDialog::buttonToggleLockClicked () private slot
Definition at line 219 of file coincontroldialog.cpp.
References coinControl(), COLUMN_ADDRESS, COLUMN_CHECKBOX, base_blob< BITS >::data, fHideAdditional, GUIUtil::getIcon(), WalletModel::isFullyMixed(), WalletModel::isLockedCoin(), CCoinControl::IsUsingPrivateSend(), WalletModel::lockCoin(), model, GUIUtil::RED, TxHashRole, ui, uint256S(), WalletModel::unlockCoin(), updateLabelLocked(), updateLabels(), and VOutRole.
Referenced by CoinControlDialog().
clipboardAfterFee
void CoinControlDialog::clipboardAfterFee () private slot
Definition at line 362 of file coincontroldialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
clipboardAmount
void CoinControlDialog::clipboardAmount () private slot
Definition at line 350 of file coincontroldialog.cpp.
References GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
clipboardBytes
void CoinControlDialog::clipboardBytes () private slot
Definition at line 368 of file coincontroldialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
clipboardChange
void CoinControlDialog::clipboardChange () private slot
Definition at line 380 of file coincontroldialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
clipboardFee
void CoinControlDialog::clipboardFee () private slot
Definition at line 356 of file coincontroldialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
clipboardLowOutput
void CoinControlDialog::clipboardLowOutput () private slot
Definition at line 374 of file coincontroldialog.cpp.
References GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
clipboardQuantity
void CoinControlDialog::clipboardQuantity () private slot
Definition at line 344 of file coincontroldialog.cpp.
References GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
coinControl()
CCoinControl * CoinControlDialog::coinControl () static
Definition at line 679 of file coincontroldialog.cpp.
References mode, NORMAL, and CCoinControl::UsePrivateSend().
Referenced by buttonSelectAllClicked(), buttonToggleLockClicked(), SendCoinsDialog::clear(), SendCoinsDialog::coinControlChangeChecked(), SendCoinsDialog::coinControlChangeEdited(), SendCoinsDialog::coinControlFeatureChanged(), SendCoinsDialog::coinControlUpdateLabels(), SendCoinsDialog::send(), updateLabels(), updateView(), SendCoinsDialog::useAvailableBalance(), and viewItemChanged().
copyAddress
void CoinControlDialog::copyAddress () private slot
Definition at line 306 of file coincontroldialog.cpp.
References COLUMN_ADDRESS, contextMenuItem, GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
copyAmount
void CoinControlDialog::copyAmount () private slot
Definition at line 291 of file coincontroldialog.cpp.
References COLUMN_AMOUNT, contextMenuItem, BitcoinUnits::removeSpaces(), and GUIUtil::setClipboard().
Referenced by CoinControlDialog().
copyLabel
void CoinControlDialog::copyLabel () private slot
Definition at line 297 of file coincontroldialog.cpp.
References COLUMN_LABEL, contextMenuItem, GUIUtil::setClipboard(), and ui.
Referenced by CoinControlDialog().
copyTransactionHash
void CoinControlDialog::copyTransactionHash () private slot
Definition at line 315 of file coincontroldialog.cpp.
References COLUMN_ADDRESS, contextMenuItem, GUIUtil::setClipboard(), and TxHashRole.
Referenced by CoinControlDialog().
headerSectionClicked
void CoinControlDialog::headerSectionClicked (int logicalIndex) private slot
Definition at line 395 of file coincontroldialog.cpp.
References COLUMN_ADDRESS, COLUMN_CHECKBOX, COLUMN_LABEL, sortColumn, sortOrder, sortView(), and ui.
Referenced by CoinControlDialog().
lockCoin
void CoinControlDialog::lockCoin () private slot
Definition at line 321 of file coincontroldialog.cpp.
References COLUMN_ADDRESS, COLUMN_CHECKBOX, contextMenuItem, GUIUtil::getIcon(), WalletModel::lockCoin(), model, GUIUtil::RED, TxHashRole, uint256S(), updateLabelLocked(), and VOutRole.
Referenced by CoinControlDialog().
on_hideButton_clicked
void CoinControlDialog::on_hideButton_clicked () private slot
Definition at line 473 of file coincontroldialog.cpp.
References fHideAdditional, model, updateLabels(), and updateView().
radioListMode
void CoinControlDialog::radioListMode (bool checked) private slot
Definition at line 423 of file coincontroldialog.cpp.
References model, and updateView().
Referenced by CoinControlDialog().
radioTreeMode
void CoinControlDialog::radioTreeMode (bool checked) private slot
Definition at line 416 of file coincontroldialog.cpp.
References model, and updateView().
Referenced by CoinControlDialog().
setModel()
void CoinControlDialog::setModel (WalletModel * model)
Definition at line 177 of file coincontroldialog.cpp.
References WalletModel::getAddressTableModel(), WalletModel::getOptionsModel(), model, updateLabelLocked(), updateLabels(), and updateView().
Referenced by SendCoinsDialog::coinControlButtonClicked().
showMenu
void CoinControlDialog::showMenu (const QPoint & point) private slot
Definition at line 256 of file coincontroldialog.cpp.
References COLUMN_ADDRESS, contextMenu, contextMenuItem, copyTransactionHashAction, base_blob< BITS >::data, WalletModel::isLockedCoin(), lockAction, model, TxHashRole, ui, uint256S(), unlockAction, and VOutRole.
Referenced by CoinControlDialog().
sortView()
void CoinControlDialog::sortView (int column, Qt::SortOrder order) private
Definition at line 386 of file coincontroldialog.cpp.
References sortColumn, sortOrder, and ui.
Referenced by CoinControlDialog(), headerSectionClicked(), and updateView().
unlockCoin
void CoinControlDialog::unlockCoin () private slot
Definition at line 334 of file coincontroldialog.cpp.
References COLUMN_ADDRESS, COLUMN_CHECKBOX, contextMenuItem, model, TxHashRole, uint256S(), WalletModel::unlockCoin(), updateLabelLocked(), and VOutRole.
Referenced by CoinControlDialog().
updateLabelLocked
void CoinControlDialog::updateLabelLocked () private slot
Definition at line 461 of file coincontroldialog.cpp.
References WalletModel::listLockedCoins(), model, and ui.
Referenced by buttonToggleLockClicked(), lockCoin(), setModel(), and unlockCoin().
updateLabels()
void CoinControlDialog::updateLabels (WalletModel * model, QDialog * dialog) static
Definition at line 480 of file coincontroldialog.cpp.
References ASYMP_UTF8, coinControl(), BitcoinUnits::DASH, dustRelayFee, ExtractDestination(), feeEstimator, BitcoinUnits::formatWithUnit(), fSubtractFeeFromAmount, OptionsModel::getDisplayUnit(), GetMinimumFee(), WalletModel::getOptionsModel(), WalletModel::getOutputs(), WalletModel::getPubKey(), GUIUtil::getThemedStyleQString(), CPubKey::IsCompressed(), IsDust(), WalletModel::isSpent(), CCoinControl::ListSelected(), mempool, MIN_CHANGE, model, payAmounts, GUIUtil::TS_ERROR, CCoinControl::UnSelect(), and CMutableTransaction::vout.
Referenced by buttonSelectAllClicked(), buttonToggleLockClicked(), SendCoinsDialog::coinControlUpdateLabels(), on_hideButton_clicked(), setModel(), and viewItemChanged().
updateView()
void CoinControlDialog::updateView () private
Definition at line 692 of file coincontroldialog.cpp.
References CCoinControlWidgetItem, coinControl(), COLUMN_ADDRESS, COLUMN_AMOUNT, COLUMN_CHECKBOX, COLUMN_CONFIRMATIONS, COLUMN_DATE, COLUMN_LABEL, COLUMN_PRIVATESEND_ROUNDS, GUIUtil::dateTimeStr(), EncodeDestination(), ExtractDestination(), CPrivateSendClientManager::fEnablePrivateSend, fHideAdditional, BitcoinUnits::format(), WalletModel::getAddressTableModel(), OptionsModel::getDisplayUnit(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), GUIUtil::getIcon(), WalletModel::getOptionsModel(), WalletModel::getRealOutpointPrivateSendRounds(), CWalletTx::GetTxTime(), COutput::i, CPrivateSend::IsCollateralAmount(), CPrivateSend::IsDenominatedAmount(), WalletModel::isFullyMixed(), WalletModel::isLockedCoin(), AddressTableModel::labelForAddress(), WalletModel::listCoins(), LogAcceptCategory(), mode, model, COutput::nDepth, NORMAL, PRIVATESEND, BCLog::PRIVATESEND, privateSendClient, GUIUtil::RED, sortColumn, sortOrder, sortView(), CMerkleTx::tx, COutput::tx, TxHashRole, ui, CCoinControl::UnSelect(), and VOutRole.
Referenced by on_hideButton_clicked(), radioListMode(), radioTreeMode(), and setModel().
usePrivateSend()
void CoinControlDialog::usePrivateSend (bool fUsePrivateSend) static
Definition at line 674 of file coincontroldialog.cpp.
References mode, NORMAL, and PRIVATESEND.
Referenced by SendCoinsDialog::showEvent().
viewItemChanged
void CoinControlDialog::viewItemChanged (QTreeWidgetItem * item, int column) private slot
Definition at line 430 of file coincontroldialog.cpp.
References coinControl(), COLUMN_ADDRESS, COLUMN_CHECKBOX, base_blob< BITS >::data, model, CCoinControl::Select(), TxHashRole, ui, uint256S(), CCoinControl::UnSelect(), updateLabels(), and VOutRole.
Referenced by CoinControlDialog().
Friends And Related Function Documentation
CCoinControlWidgetItem
friend class CCoinControlWidgetItem friend
Definition at line 92 of file coincontroldialog.h.
Referenced by updateView().
Member Data Documentation
contextMenu
QMenu* CoinControlDialog::contextMenu private
Definition at line 64 of file coincontroldialog.h.
Referenced by CoinControlDialog(), and showMenu().
contextMenuItem
QTreeWidgetItem* CoinControlDialog::contextMenuItem private
Definition at line 65 of file coincontroldialog.h.
Referenced by copyAddress(), copyAmount(), copyLabel(), copyTransactionHash(), lockCoin(), showMenu(), and unlockCoin().
copyTransactionHashAction
QAction* CoinControlDialog::copyTransactionHashAction private
Definition at line 66 of file coincontroldialog.h.
Referenced by CoinControlDialog(), and showMenu().
fHideAdditional
bool CoinControlDialog::fHideAdditional {true} private
Definition at line 70 of file coincontroldialog.h.
Referenced by buttonToggleLockClicked(), on_hideButton_clicked(), and updateView().
fSubtractFeeFromAmount
bool CoinControlDialog::fSubtractFeeFromAmount = false static
Definition at line 55 of file coincontroldialog.h.
Referenced by SendCoinsDialog::coinControlUpdateLabels(), and updateLabels().
lockAction
QAction* CoinControlDialog::lockAction private
Definition at line 67 of file coincontroldialog.h.
Referenced by CoinControlDialog(), and showMenu().
mode
CoinControlDialog::Mode CoinControlDialog::mode {CoinControlDialog::Mode::NORMAL} static private
Definition at line 99 of file coincontroldialog.h.
Referenced by coinControl(), updateView(), and usePrivateSend().
model
WalletModel* CoinControlDialog::model private
Definition at line 60 of file coincontroldialog.h.
Referenced by buttonSelectAllClicked(), buttonToggleLockClicked(), lockCoin(), on_hideButton_clicked(), radioListMode(), radioTreeMode(), setModel(), showMenu(), unlockCoin(), updateLabelLocked(), updateLabels(), updateView(), and viewItemChanged().
payAmounts
QList< CAmount > CoinControlDialog::payAmounts static
Definition at line 53 of file coincontroldialog.h.
Referenced by SendCoinsDialog::coinControlUpdateLabels(), and updateLabels().
sortColumn
int CoinControlDialog::sortColumn private
Definition at line 61 of file coincontroldialog.h.
Referenced by headerSectionClicked(), sortView(), updateView(), and ~CoinControlDialog().
sortOrder
Qt::SortOrder CoinControlDialog::sortOrder private
Definition at line 62 of file coincontroldialog.h.
Referenced by headerSectionClicked(), sortView(), updateView(), and ~CoinControlDialog().
ui
Ui::CoinControlDialog* CoinControlDialog::ui private
Definition at line 59 of file coincontroldialog.h.
Referenced by buttonBoxClicked(), buttonSelectAllClicked(), buttonToggleLockClicked(), clipboardAfterFee(), clipboardAmount(), clipboardBytes(), clipboardChange(), clipboardFee(), clipboardLowOutput(), clipboardQuantity(), CoinControlDialog(), copyAddress(), copyLabel(), headerSectionClicked(), showMenu(), sortView(), updateLabelLocked(), updateView(), viewItemChanged(), and ~CoinControlDialog().
unlockAction
QAction* CoinControlDialog::unlockAction private
Definition at line 68 of file coincontroldialog.h.
Referenced by CoinControlDialog(), and showMenu().
The documentation for this class was generated from the following files:
src/qt/coincontroldialog.h
src/qt/coincontroldialog.cpp
Released under the MIT license