Dash Core: CMasternodeConfig::CMasternodeEntry Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodeConfig::CMasternodeEntry Class Reference
#include <masternodeconfig.h>
Public Member Functions
CMasternodeEntry (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex)
const std::string & getAlias () const
void setAlias (const std::string &alias)
const std::string & getOutputIndex () const
void setOutputIndex (const std::string &outputIndex)
const std::string & getPrivKey () const
void setPrivKey (const std::string &privKey)
const std::string & getTxHash () const
void setTxHash (const std::string &txHash)
const std::string & getIp () const
void setIp (const std::string &ip)
Private Attributes
std::string alias
std::string ip
std::string privKey
std::string txHash
std::string outputIndex
Detailed Description
Definition at line 17 of file masternodeconfig.h.
Constructor & Destructor Documentation
CMasternodeEntry()
CMasternodeConfig::CMasternodeEntry::CMasternodeEntry (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex) inline
Definition at line 27 of file masternodeconfig.h.
References alias, ip, outputIndex, privKey, and txHash.
Member Function Documentation
getAlias()
const std::string& CMasternodeConfig::CMasternodeEntry::getAlias () const inline
Definition at line 35 of file masternodeconfig.h.
References alias.
Referenced by gobject(), masternode(), masternodebroadcast(), MasternodeList::StartAlias(), MasternodeList::StartAll(), and MasternodeList::updateMyNodeList().
getIp()
const std::string& CMasternodeConfig::CMasternodeEntry::getIp () const inline
Definition at line 67 of file masternodeconfig.h.
References ip.
Referenced by masternode(), masternodebroadcast(), MasternodeList::StartAlias(), MasternodeList::StartAll(), and MasternodeList::updateMyNodeList().
getOutputIndex()
const std::string& CMasternodeConfig::CMasternodeEntry::getOutputIndex () const inline
Definition at line 43 of file masternodeconfig.h.
References outputIndex.
Referenced by AppInit2(), gobject(), masternode(), masternodebroadcast(), MasternodeList::StartAlias(), MasternodeList::StartAll(), and MasternodeList::updateMyNodeList().
getPrivKey()
const std::string& CMasternodeConfig::CMasternodeEntry::getPrivKey () const inline
Definition at line 51 of file masternodeconfig.h.
References privKey.
Referenced by gobject(), masternode(), masternodebroadcast(), MasternodeList::StartAlias(), and MasternodeList::StartAll().
getTxHash()
const std::string& CMasternodeConfig::CMasternodeEntry::getTxHash () const inline
Definition at line 59 of file masternodeconfig.h.
References txHash.
Referenced by AppInit2(), gobject(), masternode(), masternodebroadcast(), MasternodeList::StartAlias(), MasternodeList::StartAll(), and MasternodeList::updateMyNodeList().
setAlias()
void CMasternodeConfig::CMasternodeEntry::setAlias (const std::string & alias) inline
Definition at line 39 of file masternodeconfig.h.
References alias.
setIp()
void CMasternodeConfig::CMasternodeEntry::setIp (const std::string & ip) inline
Definition at line 71 of file masternodeconfig.h.
References ip.
setOutputIndex()
void CMasternodeConfig::CMasternodeEntry::setOutputIndex (const std::string & outputIndex) inline
Definition at line 47 of file masternodeconfig.h.
References outputIndex.
setPrivKey()
void CMasternodeConfig::CMasternodeEntry::setPrivKey (const std::string & privKey) inline
Definition at line 55 of file masternodeconfig.h.
References privKey.
setTxHash()
void CMasternodeConfig::CMasternodeEntry::setTxHash (const std::string & txHash) inline
Definition at line 63 of file masternodeconfig.h.
References txHash.
Member Data Documentation
alias
std::string CMasternodeConfig::CMasternodeEntry::alias private
Definition at line 20 of file masternodeconfig.h.
Referenced by CMasternodeEntry(), getAlias(), and setAlias().
ip
std::string CMasternodeConfig::CMasternodeEntry::ip private
Definition at line 21 of file masternodeconfig.h.
Referenced by CMasternodeEntry(), getIp(), and setIp().
outputIndex
std::string CMasternodeConfig::CMasternodeEntry::outputIndex private
Definition at line 24 of file masternodeconfig.h.
Referenced by CMasternodeEntry(), getOutputIndex(), and setOutputIndex().
privKey
std::string CMasternodeConfig::CMasternodeEntry::privKey private
Definition at line 22 of file masternodeconfig.h.
Referenced by CMasternodeEntry(), getPrivKey(), and setPrivKey().
txHash
std::string CMasternodeConfig::CMasternodeEntry::txHash private
Definition at line 23 of file masternodeconfig.h.
Referenced by CMasternodeEntry(), getTxHash(), and setTxHash().
The documentation for this class was generated from the following file:
src/masternodeconfig.h
Released under the MIT license