Dash Core: CZMQAbstractNotifier Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CZMQAbstractNotifier Class Reference abstract
#include <zmqabstractnotifier.h>
Public Member Functions
CZMQAbstractNotifier ()
virtual ~CZMQAbstractNotifier ()
std::string GetType () const
void SetType (const std::string &t)
std::string GetAddress () const
void SetAddress (const std::string &a)
virtual bool Initialize (void *pcontext)=0
virtual void Shutdown ()=0
virtual bool NotifyBlock (const CBlockIndex *pindex)
virtual bool NotifyChainLock (const CBlockIndex *pindex, const llmq::CChainLockSig &clsig)
virtual bool NotifyTransaction (const CTransaction &transaction)
virtual bool NotifyTransactionLock (const CTransaction &transaction, const llmq::CInstantSendLock &islock)
virtual bool NotifyGovernanceVote (const CGovernanceVote &vote)
virtual bool NotifyGovernanceObject (const CGovernanceObject &object)
virtual bool NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx)
Static Public Member Functions
template<typename T >
static CZMQAbstractNotifier * Create ()
Protected Attributes
void * psocket
std::string type
std::string address
Detailed Description
Definition at line 22 of file zmqabstractnotifier.h.
Constructor & Destructor Documentation
CZMQAbstractNotifier()
CZMQAbstractNotifier::CZMQAbstractNotifier () inline
Definition at line 25 of file zmqabstractnotifier.h.
~CZMQAbstractNotifier()
CZMQAbstractNotifier::~CZMQAbstractNotifier () virtual
Definition at line 9 of file zmqabstractnotifier.cpp.
References psocket.
Member Function Documentation
Create()
template<typename T > static CZMQAbstractNotifier* CZMQAbstractNotifier::Create () inline static
Definition at line 29 of file zmqabstractnotifier.h.
GetAddress()
std::string CZMQAbstractNotifier::GetAddress () const inline
Definition at line 36 of file zmqabstractnotifier.h.
References address.
Referenced by CZMQNotificationInterface::Initialize(), and CZMQNotificationInterface::Shutdown().
GetType()
std::string CZMQAbstractNotifier::GetType () const inline
Definition at line 34 of file zmqabstractnotifier.h.
References type.
Referenced by CZMQNotificationInterface::Initialize(), and CZMQNotificationInterface::Shutdown().
Initialize()
virtual bool CZMQAbstractNotifier::Initialize (void * pcontext) pure virtual
Implemented in CZMQAbstractPublishNotifier.
Referenced by CZMQNotificationInterface::Initialize().
NotifyBlock()
bool CZMQAbstractNotifier::NotifyBlock (const CBlockIndex * pindex) virtual
Reimplemented in CZMQPublishRawBlockNotifier, and CZMQPublishHashBlockNotifier.
Definition at line 14 of file zmqabstractnotifier.cpp.
Referenced by CZMQNotificationInterface::UpdatedBlockTip().
NotifyChainLock()
bool CZMQAbstractNotifier::NotifyChainLock (const CBlockIndex * pindex, const llmq::CChainLockSig & clsig) virtual
Reimplemented in CZMQPublishRawChainLockSigNotifier, CZMQPublishRawChainLockNotifier, and CZMQPublishHashChainLockNotifier.
Definition at line 19 of file zmqabstractnotifier.cpp.
Referenced by CZMQNotificationInterface::NotifyChainLock().
NotifyGovernanceObject()
bool CZMQAbstractNotifier::NotifyGovernanceObject (const CGovernanceObject & object) virtual
Reimplemented in CZMQPublishRawGovernanceObjectNotifier, and CZMQPublishHashGovernanceObjectNotifier.
Definition at line 39 of file zmqabstractnotifier.cpp.
Referenced by CZMQNotificationInterface::NotifyGovernanceObject().
NotifyGovernanceVote()
bool CZMQAbstractNotifier::NotifyGovernanceVote (const CGovernanceVote & vote) virtual
Reimplemented in CZMQPublishRawGovernanceVoteNotifier, and CZMQPublishHashGovernanceVoteNotifier.
Definition at line 34 of file zmqabstractnotifier.cpp.
Referenced by CZMQNotificationInterface::NotifyGovernanceVote().
NotifyInstantSendDoubleSpendAttempt()
bool CZMQAbstractNotifier::NotifyInstantSendDoubleSpendAttempt (const CTransaction & currentTx, const CTransaction & previousTx) virtual
Reimplemented in CZMQPublishRawInstantSendDoubleSpendNotifier, and CZMQPublishHashInstantSendDoubleSpendNotifier.
Definition at line 44 of file zmqabstractnotifier.cpp.
Referenced by CZMQNotificationInterface::NotifyInstantSendDoubleSpendAttempt().
NotifyTransaction()
bool CZMQAbstractNotifier::NotifyTransaction (const CTransaction & transaction) virtual
Reimplemented in CZMQPublishRawTransactionNotifier, and CZMQPublishHashTransactionNotifier.
Definition at line 24 of file zmqabstractnotifier.cpp.
Referenced by CZMQNotificationInterface::TransactionAddedToMempool().
NotifyTransactionLock()
bool CZMQAbstractNotifier::NotifyTransactionLock (const CTransaction & transaction, const llmq::CInstantSendLock & islock) virtual
Reimplemented in CZMQPublishRawTransactionLockSigNotifier, CZMQPublishRawTransactionLockNotifier, and CZMQPublishHashTransactionLockNotifier.
Definition at line 29 of file zmqabstractnotifier.cpp.
Referenced by CZMQNotificationInterface::NotifyTransactionLock().
SetAddress()
void CZMQAbstractNotifier::SetAddress (const std::string & a) inline
Definition at line 37 of file zmqabstractnotifier.h.
References address.
Referenced by CZMQNotificationInterface::Create().
SetType()
void CZMQAbstractNotifier::SetType (const std::string & t) inline
Definition at line 35 of file zmqabstractnotifier.h.
References type.
Referenced by CZMQNotificationInterface::Create().
Shutdown()
virtual void CZMQAbstractNotifier::Shutdown () pure virtual
Implemented in CZMQAbstractPublishNotifier.
Referenced by CZMQNotificationInterface::NotifyChainLock(), CZMQNotificationInterface::NotifyGovernanceObject(), CZMQNotificationInterface::NotifyGovernanceVote(), CZMQNotificationInterface::NotifyInstantSendDoubleSpendAttempt(), CZMQNotificationInterface::NotifyTransactionLock(), CZMQNotificationInterface::Shutdown(), CZMQNotificationInterface::TransactionAddedToMempool(), and CZMQNotificationInterface::UpdatedBlockTip().
Member Data Documentation
address
std::string CZMQAbstractNotifier::address protected
Definition at line 54 of file zmqabstractnotifier.h.
Referenced by GetAddress(), CZMQAbstractPublishNotifier::Initialize(), SetAddress(), and CZMQAbstractPublishNotifier::Shutdown().
psocket
void* CZMQAbstractNotifier::psocket protected
Definition at line 52 of file zmqabstractnotifier.h.
Referenced by CZMQAbstractPublishNotifier::Initialize(), CZMQAbstractPublishNotifier::SendMessage(), CZMQAbstractPublishNotifier::Shutdown(), and ~CZMQAbstractNotifier().
type
std::string CZMQAbstractNotifier::type protected
Definition at line 53 of file zmqabstractnotifier.h.
Referenced by GetType(), and SetType().
The documentation for this class was generated from the following files:
src/zmq/zmqabstractnotifier.h
src/zmq/zmqabstractnotifier.cpp
Released under the MIT license