Dash Core: CWalletDB Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CWalletDB Class Reference
Access to the wallet database (wallet.dat)
#include <walletdb.h>
Public Member Functions
CWalletDB (const std::string &strFilename, const char *pszMode="r+", bool fFlushOnClose=true)
bool WriteName (const std::string &strAddress, const std::string &strName)
bool EraseName (const std::string &strAddress)
bool WritePurpose (const std::string &strAddress, const std::string &purpose)
bool ErasePurpose (const std::string &strAddress)
bool WriteTx (uint256 hash, const CWalletTx &wtx)
bool EraseTx (uint256 hash)
bool WriteKey (const CPubKey &vchPubKey, const CPrivKey &vchPrivKey, const CKeyMetadata &keyMeta)
bool WriteCryptedKey (const CPubKey &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret, const CKeyMetadata &keyMeta)
bool WriteMasterKey (unsigned int nID, const CMasterKey &kMasterKey)
bool WriteCScript (const uint160 &hash, const CScript &redeemScript)
bool WriteWatchOnly (const CScript &script)
bool EraseWatchOnly (const CScript &script)
bool WriteBestBlock (const CBlockLocator &locator)
bool ReadBestBlock (CBlockLocator &locator)
bool WriteOrderPosNext (int64_t nOrderPosNext)
bool WriteDefaultKey (const CPubKey &vchPubKey)
bool ReadPool (int64_t nPool, CKeyPool &keypool)
bool WritePool (int64_t nPool, const CKeyPool &keypool)
bool ErasePool (int64_t nPool)
bool WriteMinVersion (int nVersion)
bool WriteAccountingEntry_Backend (const CAccountingEntry &acentry)
This writes directly to the database, and will not update the CWallet's cached accounting entries! Use wallet.AddAccountingEntry instead, to write and update its caches.
bool ReadAccount (const std::string &strAccount, CAccount &account)
bool WriteAccount (const std::string &strAccount, const CAccount &account)
bool WriteDestData (const std::string &address, const std::string &key, const std::string &value)
Write destination data key,value tuple to database.
bool EraseDestData (const std::string &address, const std::string &key)
Erase destination data tuple from wallet database.
CAmount GetAccountCreditDebit (const std::string &strAccount)
void ListAccountCreditDebit (const std::string &strAccount, std::list< CAccountingEntry > &acentries)
DBErrors ReorderTransactions (CWallet *pwallet)
DBErrors LoadWallet (CWallet *pwallet)
DBErrors FindWalletTx (CWallet *pwallet, std::vector< uint256 > &vTxHash, std::vector< CWalletTx > &vWtx)
DBErrors ZapWalletTx (CWallet *pwallet, std::vector< CWalletTx > &vWtx)
bool WriteHDChain (const CHDChain &chain)
write the hdchain model (external chain child index counter)
bool WriteCryptedHDChain (const CHDChain &chain)
bool WriteHDPubKey (const CHDPubKey &hdPubKey, const CKeyMetadata &keyMeta)
Public Member Functions inherited from CDB
void Flush ()
void Close ()
bool TxnBegin ()
bool TxnCommit ()
bool TxnAbort ()
bool ReadVersion (int &nVersion)
bool WriteVersion (int nVersion)
Static Public Member Functions
static bool Recover (CDBEnv &dbenv, const std::string &filename, bool fOnlyKeys)
static bool Recover (CDBEnv &dbenv, const std::string &filename)
Static Public Member Functions inherited from CDB
static bool Rewrite (const std::string &strFile, const char *pszSkip=NULL)
Private Member Functions
CWalletDB (const CWalletDB &)
void operator= (const CWalletDB &)
bool WriteAccountingEntry (const uint64_t nAccEntryNum, const CAccountingEntry &acentry)
Additional Inherited Members
Protected Member Functions inherited from CDB
CDB (const std::string &strFilename, const char *pszMode="r+", bool fFlushOnCloseIn=true)
~CDB ()
template<typename K , typename T >
bool Read (const K &key, T &value)
template<typename K , typename T >
bool Write (const K &key, const T &value, bool fOverwrite=true)
template<typename K >
bool Erase (const K &key)
template<typename K >
bool Exists (const K &key)
Dbc * GetCursor ()
int ReadAtCursor (Dbc *pcursor, CDataStream &ssKey, CDataStream &ssValue, unsigned int fFlags=DB_NEXT)
Protected Attributes inherited from CDB
Db * pdb
std::string strFile
DbTxn * activeTxn
bool fReadOnly
bool fFlushOnClose
Detailed Description
Access to the wallet database (wallet.dat)
Definition at line 78 of file walletdb.h.
Constructor & Destructor Documentation
CWalletDB() [1/2]
CWalletDB::CWalletDB (const std::string & strFilename, const char * pszMode = "r+", bool fFlushOnClose = true) inline
Definition at line 81 of file walletdb.h.
CWalletDB() [2/2]
CWalletDB::CWalletDB (const CWalletDB &) private
Member Function Documentation
EraseDestData()
bool CWalletDB::EraseDestData (const std::string & address, const std::string & key)
Erase destination data tuple from wallet database.
Definition at line 1158 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::DelAddressBook(), and CWallet::EraseDestData().
EraseName()
bool CWalletDB::EraseName (const std::string & strAddress)
Definition at line 38 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::DelAddressBook().
ErasePool()
bool CWalletDB::ErasePool (int64_t nPool)
Definition at line 168 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::KeepKey(), and CWallet::NewKeyPool().
ErasePurpose()
bool CWalletDB::ErasePurpose (const std::string & strAddress)
Definition at line 52 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::DelAddressBook().
EraseTx()
bool CWalletDB::EraseTx (uint256 hash)
Definition at line 64 of file walletdb.cpp.
References nWalletDBUpdated.
EraseWatchOnly()
bool CWalletDB::EraseWatchOnly (const CScript & script)
Definition at line 126 of file walletdb.cpp.
References nWalletDBUpdated.
FindWalletTx()
DBErrors CWalletDB::FindWalletTx (CWallet * pwallet, std::vector< uint256 > & vTxHash, std::vector< CWalletTx > & vWtx)
Definition at line 759 of file walletdb.cpp.
References CLIENT_VERSION, CWallet::cs_wallet, DB_CORRUPT, DB_LOAD_OK, DB_NONCRITICAL_ERROR, DB_TOO_NEW, CWallet::LoadMinVersion(), LOCK, LogPrintf, SER_DISK, and CWallet::vchDefaultKey.
GetAccountCreditDebit()
CAmount CWalletDB::GetAccountCreditDebit (const std::string & strAccount)
Definition at line 200 of file walletdb.cpp.
References CAccountingEntry::nCreditDebit.
Referenced by GetAccountBalance().
ListAccountCreditDebit()
void CWalletDB::ListAccountCreditDebit (const std::string & strAccount, std::list< CAccountingEntry > & acentries)
Definition at line 212 of file walletdb.cpp.
References CLIENT_VERSION, SER_DISK, and CAccountingEntry::strAccount.
LoadWallet()
DBErrors CWalletDB::LoadWallet (CWallet * pwallet)
Definition at line 648 of file walletdb.cpp.
References CLIENT_VERSION, CWallet::cs_wallet, DB_CORRUPT, DB_LOAD_OK, DB_NEED_REWRITE, DB_NONCRITICAL_ERROR, DB_TOO_NEW, CWalletScanState::fAnyUnordered, CWalletScanState::fIsEncrypted, IsKeyType(), CWallet::KeypoolCountExternalKeys(), CWallet::laccentries, CWallet::LoadMinVersion(), LOCK, LogPrintf, CWallet::mapWallet, CWalletScanState::nCKeys, CWalletScanState::nFileVersion, CWalletScanState::nKeyMeta, CWalletScanState::nKeys, CWallet::nKeysLeftSinceAutoBackup, CAccountingEntry::nOrderPos, CWallet::nTimeFirstKey, ReadKeyValue(), SER_DISK, SoftSetBoolArg(), CWallet::vchDefaultKey, CWalletScanState::vWalletUpgrade, and CWallet::wtxOrdered.
Referenced by CWallet::LoadWallet().
operator=()
void CWalletDB::operator= (const CWalletDB &) private
ReadAccount()
bool CWalletDB::ReadAccount (const std::string & strAccount, CAccount & account)
Definition at line 179 of file walletdb.cpp.
References CAccount::SetNull().
Referenced by GetAccountAddress().
ReadBestBlock()
bool CWalletDB::ReadBestBlock (CBlockLocator & locator)
Definition at line 139 of file walletdb.cpp.
References CBlockLocator::vHave.
Referenced by AppInit2().
ReadPool()
bool CWalletDB::ReadPool (int64_t nPool, CKeyPool & keypool)
Definition at line 157 of file walletdb.cpp.
Referenced by GetOldestKeyInPool(), LoadReserveKeysToSet(), and CWallet::ReserveKeyFromKeyPool().
Recover() [1/2]
bool CWalletDB::Recover (CDBEnv & dbenv, const std::string & filename, bool fOnlyKeys) static
Definition at line 1066 of file walletdb.cpp.
References CLIENT_VERSION, CWallet::cs_wallet, CDBEnv::dbenv, GetTime(), IsKeyType(), LOCK, LogPrintf, ReadKeyValue(), CDBEnv::Salvage(), SER_DISK, strprintf, and CDBEnv::TxnBegin().
Referenced by Recover(), and CWallet::Verify().
Recover() [2/2]
bool CWalletDB::Recover (CDBEnv & dbenv, const std::string & filename) static
Definition at line 1147 of file walletdb.cpp.
References Recover().
ReorderTransactions()
DBErrors CWalletDB::ReorderTransactions (CWallet * pwallet)
Definition at line 255 of file walletdb.cpp.
References CWallet::cs_wallet, DB_LOAD_FAIL, DB_LOAD_OK, CTransaction::GetHash(), LOCK, CWallet::mapWallet, CAccountingEntry::nEntryNo, CWalletTx::nOrderPos, CAccountingEntry::nOrderPos, CWallet::nOrderPosNext, CAccountingEntry::nTime, and CWalletTx::nTimeReceived.
WriteAccount()
bool CWalletDB::WriteAccount (const std::string & strAccount, const CAccount & account)
Definition at line 185 of file walletdb.cpp.
Referenced by GetAccountAddress().
WriteAccountingEntry()
bool CWalletDB::WriteAccountingEntry (const uint64_t nAccEntryNum, const CAccountingEntry & acentry) private
Definition at line 190 of file walletdb.cpp.
References CAccountingEntry::strAccount.
WriteAccountingEntry_Backend()
bool CWalletDB::WriteAccountingEntry_Backend (const CAccountingEntry & acentry)
This writes directly to the database, and will not update the CWallet's cached accounting entries! Use wallet.AddAccountingEntry instead, to write and update its caches.
Definition at line 195 of file walletdb.cpp.
References nAccountingEntryNumber.
Referenced by CWallet::AddAccountingEntry().
WriteBestBlock()
bool CWalletDB::WriteBestBlock (const CBlockLocator & locator)
Definition at line 132 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::SetBestChain().
WriteCryptedHDChain()
bool CWalletDB::WriteCryptedHDChain (const CHDChain & chain)
Definition at line 1170 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::SetCryptedHDChain().
WriteCryptedKey()
bool CWalletDB::WriteCryptedKey (const CPubKey & vchPubKey, const std::vector< unsigned char > & vchCryptedSecret, const CKeyMetadata & keyMeta)
Definition at line 87 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::AddCryptedKey().
WriteCScript()
bool CWalletDB::WriteCScript (const uint160 & hash, const CScript & redeemScript)
Definition at line 114 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::AddCScript().
WriteDefaultKey()
bool CWalletDB::WriteDefaultKey (const CPubKey & vchPubKey)
Definition at line 151 of file walletdb.cpp.
References nWalletDBUpdated.
WriteDestData()
bool CWalletDB::WriteDestData (const std::string & address, const std::string & key, const std::string & value)
Write destination data key,value tuple to database.
Definition at line 1152 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::AddDestData().
WriteHDChain()
bool CWalletDB::WriteHDChain (const CHDChain & chain)
write the hdchain model (external chain child index counter)
Definition at line 1164 of file walletdb.cpp.
References nWalletDBUpdated.
WriteHDPubKey()
bool CWalletDB::WriteHDPubKey (const CHDPubKey & hdPubKey, const CKeyMetadata & keyMeta)
Definition at line 1182 of file walletdb.cpp.
References CHDPubKey::extPubKey, nWalletDBUpdated, and CExtPubKey::pubkey.
Referenced by CWallet::AddHDPubKey().
WriteKey()
bool CWalletDB::WriteKey (const CPubKey & vchPubKey, const CPrivKey & vchPrivKey, const CKeyMetadata & keyMeta)
Definition at line 70 of file walletdb.cpp.
References CPubKey::begin(), CPubKey::end(), Hash(), nWalletDBUpdated, and CPubKey::size().
Referenced by CWallet::AddKeyPubKey().
WriteMasterKey()
bool CWalletDB::WriteMasterKey (unsigned int nID, const CMasterKey & kMasterKey)
Definition at line 108 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::ChangeWalletPassphrase().
WriteMinVersion()
bool CWalletDB::WriteMinVersion (int nVersion)
Definition at line 174 of file walletdb.cpp.
Referenced by CWallet::SetMinVersion().
WriteName()
bool CWalletDB::WriteName (const std::string & strAddress, const std::string & strName)
Definition at line 32 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::SetAddressBook().
WriteOrderPosNext()
bool CWalletDB::WriteOrderPosNext (int64_t nOrderPosNext)
Definition at line 145 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::IncOrderPosNext().
WritePool()
bool CWalletDB::WritePool (int64_t nPool, const CKeyPool & keypool)
Definition at line 162 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::TopUpKeyPool().
WritePurpose()
bool CWalletDB::WritePurpose (const std::string & strAddress, const std::string & purpose)
Definition at line 46 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::SetAddressBook().
WriteTx()
bool CWalletDB::WriteTx (uint256 hash, const CWalletTx & wtx)
Definition at line 58 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWalletTx::WriteToDisk().
WriteWatchOnly()
bool CWalletDB::WriteWatchOnly (const CScript & script)
Definition at line 120 of file walletdb.cpp.
References nWalletDBUpdated.
Referenced by CWallet::AddWatchOnly().
ZapWalletTx()
DBErrors CWalletDB::ZapWalletTx (CWallet * pwallet, std::vector< CWalletTx > & vWtx)
Definition at line 825 of file walletdb.cpp.
References DB_CORRUPT, and DB_LOAD_OK.
Referenced by CWallet::ZapWalletTx().
The documentation for this class was generated from the following files:
src/wallet/walletdb.h
src/wallet/walletdb.cpp
Released under the MIT license