Dash Core: QtRPCTimerBase Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
QtRPCTimerBase Class Reference
Class for handling RPC timers (used for e.g.
Public Member Functions
QtRPCTimerBase (boost::function< void(void)> &func, int64_t millis)
~QtRPCTimerBase ()
Public Member Functions inherited from RPCTimerBase
virtual ~RPCTimerBase ()
Private Slots
void timeout ()
Private Attributes
QTimer timer
boost::function< void(void)> func
Detailed Description
Class for handling RPC timers (used for e.g.
re-locking the wallet after a timeout)
Definition at line 88 of file rpcconsole.cpp.
Constructor & Destructor Documentation
QtRPCTimerBase()
QtRPCTimerBase::QtRPCTimerBase (boost::function< void(void)> & func, int64_t millis) inline
Definition at line 92 of file rpcconsole.cpp.
References timeout(), and timer.
~QtRPCTimerBase()
QtRPCTimerBase::~QtRPCTimerBase () inline
Definition at line 99 of file rpcconsole.cpp.
Member Function Documentation
timeout
void QtRPCTimerBase::timeout () inline private slot
Definition at line 101 of file rpcconsole.cpp.
References func.
Referenced by QtRPCTimerBase().
Member Data Documentation
func
boost::function<void(void)> QtRPCTimerBase::func private
Definition at line 104 of file rpcconsole.cpp.
Referenced by timeout().
timer
QTimer QtRPCTimerBase::timer private
Definition at line 103 of file rpcconsole.cpp.
Referenced by QtRPCTimerBase().
The documentation for this class was generated from the following file:
src/qt/rpcconsole.cpp
Released under the MIT license