Dash Core: CBatchedLogger Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBatchedLogger Class Reference
#include <batchedlogger.h>
Public Member Functions
CBatchedLogger (uint64_t _category, const std::string &_header)
virtual ~CBatchedLogger ()
template<typename... Args>
void Batch (const std::string &fmt, const Args &... args)
void Flush ()
Private Attributes
bool accept
std::string header
std::string msg
Detailed Description
Definition at line 10 of file batchedlogger.h.
Constructor & Destructor Documentation
CBatchedLogger()
CBatchedLogger::CBatchedLogger (uint64_t _category, const std::string & _header)
Definition at line 8 of file batchedlogger.cpp.
~CBatchedLogger()
CBatchedLogger::~CBatchedLogger () virtual
Definition at line 13 of file batchedlogger.cpp.
References Flush().
Member Function Documentation
Batch()
template<typename... Args> void CBatchedLogger::Batch (const std::string & fmt, const Args &... args) inline
Definition at line 21 of file batchedlogger.h.
References accept, msg, and strprintf.
Referenced by llmq::CDKGSession::Contribute(), llmq::CDKGSession::FinalizeCommitments(), llmq::CDKGSession::Init(), llmq::CDKGSession::PreVerifyMessage(), llmq::CDKGSession::ReceiveMessage(), llmq::CDKGSession::SendCommitment(), llmq::CDKGSession::SendComplaint(), llmq::CDKGSession::SendContributions(), llmq::CDKGSession::SendJustification(), llmq::CDKGSession::VerifyAndCommit(), llmq::CDKGSession::VerifyAndComplain(), llmq::CDKGSession::VerifyAndJustify(), llmq::CDKGSession::VerifyConnectionAndMinProtoVersions(), and llmq::CDKGSession::VerifyPendingContributions().
Flush()
void CBatchedLogger::Flush ()
Definition at line 18 of file batchedlogger.cpp.
References accept, header, LogPrintStr(), msg, and strprintf.
Referenced by llmq::CDKGSession::FinalizeCommitments(), llmq::CDKGSession::SendCommitment(), llmq::CDKGSession::SendComplaint(), llmq::CDKGSession::SendContributions(), llmq::CDKGSession::SendJustification(), llmq::CDKGSession::VerifyAndCommit(), llmq::CDKGSession::VerifyAndComplain(), llmq::CDKGSession::VerifyAndJustify(), and ~CBatchedLogger().
Member Data Documentation
accept
bool CBatchedLogger::accept private
Definition at line 13 of file batchedlogger.h.
Referenced by Batch(), and Flush().
header
std::string CBatchedLogger::header private
Definition at line 14 of file batchedlogger.h.
Referenced by Flush().
msg
std::string CBatchedLogger::msg private
Definition at line 15 of file batchedlogger.h.
Referenced by Batch(), and Flush().
The documentation for this class was generated from the following files:
src/batchedlogger.h
src/batchedlogger.cpp
Released under the MIT license