Dash Core: CMessageSigner Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMessageSigner Class Reference
Helper class for signing messages and checking their signatures.
#include <messagesigner.h>
Static Public Member Functions
static bool GetKeysFromSecret (const std::string strSecret, CKey &keyRet, CPubKey &pubkeyRet)
Set the private/public key values, returns true if successful.
static bool SignMessage (const std::string strMessage, std::vector< unsigned char > &vchSigRet, const CKey key)
Sign the message, returns true if successful.
static bool VerifyMessage (const CPubKey pubkey, const std::vector< unsigned char > &vchSig, const std::string strMessage, std::string &strErrorRet)
Verify the message signature, returns true if succcessful.
Detailed Description
Helper class for signing messages and checking their signatures.
Definition at line 12 of file messagesigner.h.
Member Function Documentation
GetKeysFromSecret()
bool CMessageSigner::GetKeysFromSecret (const std::string strSecret, CKey & keyRet, CPubKey & pubkeyRet) static
Set the private/public key values, returns true if successful.
Definition at line 12 of file messagesigner.cpp.
References CBitcoinSecret::GetKey(), CKey::GetPubKey(), and CBitcoinSecret::SetString().
Referenced by AppInit2(), gobject(), and CSporkMessage::Sign().
SignMessage()
bool CMessageSigner::SignMessage (const std::string strMessage, std::vector< unsigned char > & vchSigRet, const CKey key) static
Sign the message, returns true if successful.
Definition at line 24 of file messagesigner.cpp.
References CHashWriter::GetHash(), SER_GETHASH, CHashSigner::SignHash(), and strMessageMagic.
Referenced by CMasternodeMan::ProcessVerifyReply(), CMasternodeMan::SendVerifyReply(), CMasternodePing::Sign(), CSporkMessage::Sign(), CGovernanceVote::Sign(), CMasternodePaymentVote::Sign(), CDarksendQueue::Sign(), CTxLockVote::Sign(), CGovernanceObject::Sign(), CDarksendBroadcastTx::Sign(), and CMasternodeBroadcast::Sign().
VerifyMessage()
bool CMessageSigner::VerifyMessage (const CPubKey pubkey, const std::vector< unsigned char > & vchSig, const std::string strMessage, std::string & strErrorRet) static
Verify the message signature, returns true if succcessful.
Definition at line 33 of file messagesigner.cpp.
References CHashWriter::GetHash(), SER_GETHASH, strMessageMagic, and CHashSigner::VerifyHash().
Referenced by CMasternodePing::CheckSignature(), CSporkMessage::CheckSignature(), CMasternodePaymentVote::CheckSignature(), CDarksendQueue::CheckSignature(), CTxLockVote::CheckSignature(), CGovernanceObject::CheckSignature(), CDarksendBroadcastTx::CheckSignature(), CMasternodeBroadcast::CheckSignature(), CGovernanceVote::IsValid(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), CMasternodeMan::SendVerifyReply(), CMasternodePing::Sign(), CSporkMessage::Sign(), CGovernanceVote::Sign(), CMasternodePaymentVote::Sign(), CTxLockVote::Sign(), CGovernanceObject::Sign(), and CMasternodeBroadcast::Sign().
The documentation for this class was generated from the following files:
src/messagesigner.h
src/messagesigner.cpp
Released under the MIT license