Dash Core: cxxtimer::Timer Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
cxxtimer::Timer Class Reference
This class works as a stopwatch.
#include <cxxtimer.hpp>
Public Member Functions
Timer (bool start=false)
Constructor.
Timer (const Timer &other)=default
Copy constructor.
Timer (Timer &&other)=default
Transfer constructor.
virtual ~Timer ()=default
Destructor.
Timer & operator= (const Timer &other)=default
Assignment operator by copy.
Timer & operator= (Timer &&other)=default
Assignment operator by transfer.
void start ()
Start/resume the timer.
void stop ()
Stop/pause the timer.
void reset ()
Reset the timer.
template<class duration_t = std::chrono::milliseconds>
duration_t::rep count () const
Return the elapsed time.
Private Attributes
bool started_
bool paused_
std::chrono::steady_clock::time_point reference_
std::chrono::duration< long double > accumulated_
Detailed Description
This class works as a stopwatch.
Definition at line 38 of file cxxtimer.hpp.
Constructor & Destructor Documentation
Timer() [1/3]
cxxtimer::Timer::Timer (bool start = false) inline
Constructor.
Parameters
start If true, the timer is started just after construction. Otherwise, it will not be automatically started.
Definition at line 131 of file cxxtimer.hpp.
References start().
Timer() [2/3]
cxxtimer::Timer::Timer (const Timer & other) default
Copy constructor.
Parameters
other The object to be copied.
Timer() [3/3]
cxxtimer::Timer::Timer (Timer && other) default
Transfer constructor.
Parameters
other The object to be transfered.
~Timer()
virtual cxxtimer::Timer::~Timer () virtual default
Destructor.
Member Function Documentation
count()
template<class duration_t > duration_t::rep cxxtimer::Timer::count () const
Return the elapsed time.
Parameters
duration_t The duration type used to return the time elapsed. If not specified, it returns the time as represented by std::chrono::milliseconds.
Returns
The elapsed time.
Definition at line 170 of file cxxtimer.hpp.
References count.
Referenced by llmq::CQuorumManager::BuildQuorumContributions(), llmq::CDKGSession::Contribute(), llmq::CDKGSession::FinalizeCommitments(), llmq::CInstantSendManager::ProcessPendingInstantSendLocks(), llmq::CSigningManager::ProcessPendingRecoveredSigs(), llmq::CSigSharesManager::ProcessPendingSigShares(), llmq::CSigSharesManager::ProcessPendingSigSharesFromNode(), llmq::CDKGSession::ReceiveMessage(), llmq::CDKGSession::SendCommitment(), llmq::CDKGSession::SendContributions(), llmq::CSigSharesManager::Sign(), llmq::CQuorum::StartCachePopulatorThread(), llmq::CSigSharesManager::TryRecoverSig(), llmq::CDKGSession::VerifyAndComplain(), and llmq::CDKGSession::VerifyPendingContributions().
operator=() [1/2]
Timer& cxxtimer::Timer::operator= (const Timer & other) default
Assignment operator by copy.
Parameters
other The object to be copied.
Returns
A reference to this object.
operator=() [2/2]
Timer& cxxtimer::Timer::operator= (Timer && other) default
Assignment operator by transfer.
Parameters
other The object to be transferred.
Returns
A reference to this object.
reset()
void cxxtimer::Timer::reset () inline
Reset the timer.
Definition at line 160 of file cxxtimer.hpp.
start()
void cxxtimer::Timer::start () inline
Start/resume the timer.
Definition at line 140 of file cxxtimer.hpp.
Referenced by Timer().
stop()
void cxxtimer::Timer::stop () inline
Stop/pause the timer.
Definition at line 152 of file cxxtimer.hpp.
Referenced by llmq::CQuorumManager::BuildQuorumContributions(), llmq::CDKGSession::FinalizeCommitments(), llmq::CInstantSendManager::ProcessPendingInstantSendLocks(), llmq::CSigningManager::ProcessPendingRecoveredSigs(), llmq::CSigSharesManager::ProcessPendingSigShares(), llmq::CSigSharesManager::ProcessPendingSigSharesFromNode(), llmq::CDKGSession::ReceiveMessage(), and llmq::CDKGSession::SendCommitment().
Member Data Documentation
accumulated_
std::chrono::duration<long double> cxxtimer::Timer::accumulated_ private
Definition at line 125 of file cxxtimer.hpp.
paused_
bool cxxtimer::Timer::paused_ private
Definition at line 123 of file cxxtimer.hpp.
reference_
std::chrono::steady_clock::time_point cxxtimer::Timer::reference_ private
Definition at line 124 of file cxxtimer.hpp.
started_
bool cxxtimer::Timer::started_ private
Definition at line 122 of file cxxtimer.hpp.
The documentation for this class was generated from the following file:
src/cxxtimer.hpp
Released under the MIT license