Dash Core: payments::Payment Class Reference
payments::Payment Class Reference
#include <paymentrequest.pb.h>
Public Member Functions
Payment ()
virtual ~Payment ()
Payment (const Payment &from)
Payment & operator= (const Payment &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline ::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Payment *other)
Payment * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Payment &from)
void MergeFrom (const Payment &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_merchant_data () const
void clear_merchant_data ()
const ::std::string & merchant_data () const
void set_merchant_data (const ::std::string &value)
void set_merchant_data (const char *value)
void set_merchant_data (const void *value, size_t size)
inline ::std::string * mutable_merchant_data ()
inline ::std::string * release_merchant_data ()
void set_allocated_merchant_data (::std::string *merchant_data)
int transactions_size () const
void clear_transactions ()
const ::std::string & transactions (int index) const
inline ::std::string * mutable_transactions (int index)
void set_transactions (int index, const ::std::string &value)
void set_transactions (int index, const char *value)
void set_transactions (int index, const void *value, size_t size)
inline ::std::string * add_transactions ()
void add_transactions (const ::std::string &value)
void add_transactions (const char *value)
void add_transactions (const void *value, size_t size)
const ::google::protobuf::RepeatedPtrField< ::std::string > & transactions () const
inline ::google::protobuf::RepeatedPtrField< ::std::string > * mutable_transactions ()
int refund_to_size () const
void clear_refund_to ()
const ::payments::Output & refund_to (int index) const
inline ::payments::Output * mutable_refund_to (int index)
inline ::payments::Output * add_refund_to ()
const ::google::protobuf::RepeatedPtrField< ::payments::Output > & refund_to () const
inline ::google::protobuf::RepeatedPtrField< ::payments::Output > * mutable_refund_to ()
bool has_memo () const
void clear_memo ()
const ::std::string & memo () const
void set_memo (const ::std::string &value)
void set_memo (const char *value)
void set_memo (const char *value, size_t size)
inline ::std::string * mutable_memo ()
inline ::std::string * release_memo ()
void set_allocated_memo (::std::string *memo)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Payment & default_instance ()
Static Public Attributes
static const int kMerchantDataFieldNumber = 1
static const int kTransactionsFieldNumber = 2
static const int kRefundToFieldNumber = 3
static const int kMemoFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_merchant_data ()
void clear_has_merchant_data ()
void set_has_memo ()
void clear_has_memo ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint32 _has_bits_ [1]
int _cached_size_
::std::string * merchant_data_
::google::protobuf::RepeatedPtrField< ::std::string > transactions_
::google::protobuf::RepeatedPtrField< ::payments::Output > refund_to_
::std::string * memo_
Static Private Attributes
static Payment * default_instance_ = NULL
Friends
void protobuf_AddDesc_paymentrequest_2eproto ()
void protobuf_AssignDesc_paymentrequest_2eproto ()
void protobuf_ShutdownFile_paymentrequest_2eproto ()
Detailed Description
Definition at line 528 of file paymentrequest.pb.h.
Constructor & Destructor Documentation
Payment() [1/2]
payments::Payment::Payment ()
Definition at line 1723 of file paymentrequest.pb.cc.
Referenced by New().
~Payment()
payments::Payment::~Payment () virtual
Definition at line 1747 of file paymentrequest.pb.cc.
Payment() [2/2]
payments::Payment::Payment (const Payment & from)
Definition at line 1732 of file paymentrequest.pb.cc.
Member Function Documentation
add_refund_to()
payments::Output * payments::Payment::add_refund_to () inline
Definition at line 1783 of file paymentrequest.pb.h.
Referenced by PaymentServer::fetchPaymentACK(), and MergePartialFromCodedStream().
add_transactions() [1/4]
std::string * payments::Payment::add_transactions () inline
Definition at line 1742 of file paymentrequest.pb.h.
Referenced by PaymentServer::fetchPaymentACK(), and MergePartialFromCodedStream().
add_transactions() [2/4]
void payments::Payment::add_transactions (const ::std::string & value) inline
Definition at line 1745 of file paymentrequest.pb.h.
add_transactions() [3/4]
void payments::Payment::add_transactions (const char * value) inline
Definition at line 1749 of file paymentrequest.pb.h.
add_transactions() [4/4]
void payments::Payment::add_transactions (const void * value, size_t size) inline
Definition at line 1753 of file paymentrequest.pb.h.
ByteSize()
int payments::Payment::ByteSize () const
Definition at line 1972 of file paymentrequest.pb.cc.
Referenced by PaymentServer::fetchPaymentACK().
Clear()
void payments::Payment::Clear ()
Definition at line 1784 of file paymentrequest.pb.cc.
Referenced by CopyFrom().
clear_has_memo()
void payments::Payment::clear_has_memo () inline private
Definition at line 1805 of file paymentrequest.pb.h.
Referenced by clear_memo(), release_memo(), and set_allocated_memo().
clear_has_merchant_data()
void payments::Payment::clear_has_merchant_data () inline private
Definition at line 1645 of file paymentrequest.pb.h.
Referenced by clear_merchant_data(), release_merchant_data(), and set_allocated_merchant_data().
clear_memo()
void payments::Payment::clear_memo () inline
Definition at line 1808 of file paymentrequest.pb.h.
clear_merchant_data()
void payments::Payment::clear_merchant_data () inline
Definition at line 1648 of file paymentrequest.pb.h.
clear_refund_to()
void payments::Payment::clear_refund_to () inline
Definition at line 1772 of file paymentrequest.pb.h.
clear_transactions()
void payments::Payment::clear_transactions () inline
Definition at line 1718 of file paymentrequest.pb.h.
CopyFrom() [1/2]
void payments::Payment::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 2044 of file paymentrequest.pb.cc.
Referenced by operator=().
CopyFrom() [2/2]
void payments::Payment::CopyFrom (const Payment & from)
Definition at line 2050 of file paymentrequest.pb.cc.
default_instance()
const Payment & payments::Payment::default_instance () static
Definition at line 1773 of file paymentrequest.pb.cc.
Referenced by payments::PaymentACK::InitAsDefaultInstance().
descriptor()
const ::google::protobuf::Descriptor * payments::Payment::descriptor () static
Definition at line 1768 of file paymentrequest.pb.cc.
GetCachedSize()
int payments::Payment::GetCachedSize () const inline
Definition at line 569 of file paymentrequest.pb.h.
GetMetadata()
google::protobuf::Metadata payments::Payment::GetMetadata () const
Definition at line 2074 of file paymentrequest.pb.cc.
has_memo()
bool payments::Payment::has_memo () const inline
Definition at line 1799 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_merchant_data()
bool payments::Payment::has_merchant_data () const inline
Definition at line 1639 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
InitAsDefaultInstance()
void payments::Payment::InitAsDefaultInstance () private
Definition at line 1729 of file paymentrequest.pb.cc.
Referenced by payments::protobuf_AddDesc_paymentrequest_2eproto().
IsInitialized()
bool payments::Payment::IsInitialized () const
Definition at line 2056 of file paymentrequest.pb.cc.
memo()
const ::std::string & payments::Payment::memo () const inline
Definition at line 1814 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_memo().
merchant_data()
const ::std::string & payments::Payment::merchant_data () const inline
Definition at line 1654 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_merchant_data().
MergeFrom() [1/2]
void payments::Payment::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 2017 of file paymentrequest.pb.cc.
Referenced by CopyFrom(), and Payment().
MergeFrom() [2/2]
void payments::Payment::MergeFrom (const Payment & from)
Definition at line 2029 of file paymentrequest.pb.cc.
MergePartialFromCodedStream()
bool payments::Payment::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1803 of file paymentrequest.pb.cc.
mutable_memo()
std::string * payments::Payment::mutable_memo () inline
Definition at line 1842 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_merchant_data()
std::string * payments::Payment::mutable_merchant_data () inline
Definition at line 1682 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_refund_to() [1/2]
payments::Output * payments::Payment::mutable_refund_to (int index) inline
Definition at line 1779 of file paymentrequest.pb.h.
mutable_refund_to() [2/2]
google::protobuf::RepeatedPtrField<::payments::Output > * payments::Payment::mutable_refund_to () inline
Definition at line 1793 of file paymentrequest.pb.h.
mutable_transactions() [1/2]
std::string * payments::Payment::mutable_transactions (int index) inline
Definition at line 1725 of file paymentrequest.pb.h.
mutable_transactions() [2/2]
google::protobuf::RepeatedPtrField<::std::string > * payments::Payment::mutable_transactions () inline
Definition at line 1763 of file paymentrequest.pb.h.
mutable_unknown_fields()
inline ::google::protobuf::UnknownFieldSet* payments::Payment::mutable_unknown_fields () inline
Definition at line 544 of file paymentrequest.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
New()
Payment * payments::Payment::New () const
Definition at line 1780 of file paymentrequest.pb.cc.
operator=()
Payment& payments::Payment::operator= (const Payment & from) inline
Definition at line 535 of file paymentrequest.pb.h.
refund_to() [1/2]
const ::payments::Output & payments::Payment::refund_to (int index) const inline
Definition at line 1775 of file paymentrequest.pb.h.
refund_to() [2/2]
const ::google::protobuf::RepeatedPtrField<::payments::Output > & payments::Payment::refund_to () const inline
Definition at line 1788 of file paymentrequest.pb.h.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
refund_to_size()
int payments::Payment::refund_to_size () const inline
Definition at line 1769 of file paymentrequest.pb.h.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
release_memo()
std::string * payments::Payment::release_memo () inline
Definition at line 1850 of file paymentrequest.pb.h.
release_merchant_data()
std::string * payments::Payment::release_merchant_data () inline
Definition at line 1690 of file paymentrequest.pb.h.
SerializeWithCachedSizes()
void payments::Payment::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1892 of file paymentrequest.pb.cc.
SerializeWithCachedSizesToArray()
google::protobuf::uint8 * payments::Payment::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1930 of file paymentrequest.pb.cc.
set_allocated_memo()
void payments::Payment::set_allocated_memo (::std::string * memo) inline
Definition at line 1860 of file paymentrequest.pb.h.
set_allocated_merchant_data()
void payments::Payment::set_allocated_merchant_data (::std::string * merchant_data) inline
Definition at line 1700 of file paymentrequest.pb.h.
set_has_memo()
void payments::Payment::set_has_memo () inline private
Definition at line 1802 of file paymentrequest.pb.h.
Referenced by mutable_memo(), set_allocated_memo(), and set_memo().
set_has_merchant_data()
void payments::Payment::set_has_merchant_data () inline private
Definition at line 1642 of file paymentrequest.pb.h.
Referenced by mutable_merchant_data(), set_allocated_merchant_data(), and set_merchant_data().
set_memo() [1/3]
void payments::Payment::set_memo (const ::std::string & value) inline
Definition at line 1818 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_memo() [2/3]
void payments::Payment::set_memo (const char * value) inline
Definition at line 1826 of file paymentrequest.pb.h.
set_memo() [3/3]
void payments::Payment::set_memo (const char * value, size_t size) inline
Definition at line 1834 of file paymentrequest.pb.h.
set_merchant_data() [1/3]
void payments::Payment::set_merchant_data (const ::std::string & value) inline
Definition at line 1658 of file paymentrequest.pb.h.
Referenced by PaymentServer::fetchPaymentACK(), and MergeFrom().
set_merchant_data() [2/3]
void payments::Payment::set_merchant_data (const char * value) inline
Definition at line 1666 of file paymentrequest.pb.h.
set_merchant_data() [3/3]
void payments::Payment::set_merchant_data (const void * value, size_t size) inline
Definition at line 1674 of file paymentrequest.pb.h.
set_transactions() [1/3]
void payments::Payment::set_transactions (int index, const ::std::string & value) inline
Definition at line 1729 of file paymentrequest.pb.h.
set_transactions() [2/3]
void payments::Payment::set_transactions (int index, const char * value) inline
Definition at line 1733 of file paymentrequest.pb.h.
set_transactions() [3/3]
void payments::Payment::set_transactions (int index, const void * value, size_t size) inline
Definition at line 1737 of file paymentrequest.pb.h.
SetCachedSize()
void payments::Payment::SetCachedSize (int size) const private
Definition at line 1763 of file paymentrequest.pb.cc.
SharedCtor()
void payments::Payment::SharedCtor () private
Definition at line 1739 of file paymentrequest.pb.cc.
Referenced by Payment().
SharedDtor()
void payments::Payment::SharedDtor () private
Definition at line 1752 of file paymentrequest.pb.cc.
Referenced by ~Payment().
Swap()
void payments::Payment::Swap (Payment * other)
Definition at line 2062 of file paymentrequest.pb.cc.
transactions() [1/2]
const ::std::string & payments::Payment::transactions (int index) const inline
Definition at line 1721 of file paymentrequest.pb.h.
transactions() [2/2]
const ::google::protobuf::RepeatedPtrField<::std::string > & payments::Payment::transactions () const inline
Definition at line 1758 of file paymentrequest.pb.h.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
transactions_size()
int payments::Payment::transactions_size () const inline
Definition at line 1715 of file paymentrequest.pb.h.
Referenced by ByteSize(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
unknown_fields()
const ::google::protobuf::UnknownFieldSet& payments::Payment::unknown_fields () const inline
Definition at line 540 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
protobuf_AddDesc_paymentrequest_2eproto
void protobuf_AddDesc_paymentrequest_2eproto () friend
Definition at line 201 of file paymentrequest.pb.cc.
Referenced by default_instance().
protobuf_AssignDesc_paymentrequest_2eproto
void protobuf_AssignDesc_paymentrequest_2eproto () friend
Definition at line 45 of file paymentrequest.pb.cc.
protobuf_ShutdownFile_paymentrequest_2eproto
void protobuf_ShutdownFile_paymentrequest_2eproto () friend
Definition at line 184 of file paymentrequest.pb.cc.
Member Data Documentation
_cached_size_
int payments::Payment::_cached_size_ mutable private
Definition at line 643 of file paymentrequest.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
_has_bits_
::google::protobuf::uint32 payments::Payment::_has_bits_[1] private
Definition at line 642 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), clear_has_memo(), clear_has_merchant_data(), has_memo(), has_merchant_data(), MergeFrom(), set_has_memo(), set_has_merchant_data(), SharedCtor(), and Swap().
_unknown_fields_
::google::protobuf::UnknownFieldSet payments::Payment::_unknown_fields_ private
Definition at line 640 of file paymentrequest.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
default_instance_
Payment * payments::Payment::default_instance_ = NULL static private
Definition at line 653 of file paymentrequest.pb.h.
Referenced by default_instance(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_AssignDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), and SharedDtor().
kMemoFieldNumber
const int payments::Payment::kMemoFieldNumber = 4 static
Definition at line 624 of file paymentrequest.pb.h.
kMerchantDataFieldNumber
const int payments::Payment::kMerchantDataFieldNumber = 1 static
Definition at line 584 of file paymentrequest.pb.h.
kRefundToFieldNumber
const int payments::Payment::kRefundToFieldNumber = 3 static
Definition at line 612 of file paymentrequest.pb.h.
kTransactionsFieldNumber
const int payments::Payment::kTransactionsFieldNumber = 2 static
Definition at line 596 of file paymentrequest.pb.h.
memo_
::std::string* payments::Payment::memo_ private
Definition at line 647 of file paymentrequest.pb.h.
Referenced by Clear(), clear_memo(), memo(), mutable_memo(), release_memo(), set_allocated_memo(), set_memo(), SharedCtor(), SharedDtor(), and Swap().
merchant_data_
::std::string* payments::Payment::merchant_data_ private
Definition at line 644 of file paymentrequest.pb.h.
Referenced by Clear(), clear_merchant_data(), merchant_data(), mutable_merchant_data(), release_merchant_data(), set_allocated_merchant_data(), set_merchant_data(), SharedCtor(), SharedDtor(), and Swap().
refund_to_
::google::protobuf::RepeatedPtrField< ::payments::Output > payments::Payment::refund_to_ private
Definition at line 646 of file paymentrequest.pb.h.
Referenced by add_refund_to(), Clear(), clear_refund_to(), MergeFrom(), mutable_refund_to(), refund_to(), refund_to_size(), and Swap().
transactions_
::google::protobuf::RepeatedPtrField< ::std::string> payments::Payment::transactions_ private
Definition at line 645 of file paymentrequest.pb.h.
Referenced by add_transactions(), Clear(), clear_transactions(), MergeFrom(), mutable_transactions(), set_transactions(), Swap(), transactions(), and transactions_size().
The documentation for this class was generated from the following files:
src/qt/paymentrequest.pb.h
src/qt/paymentrequest.pb.cc