Dash Core: llmq::CDKGSession Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CDKGSession Class Reference
The DKG session is a single instance of the DKG process.
#include <quorums_dkgsession.h>
Public Member Functions
CDKGSession (const Consensus::LLMQParams &_params, CBLSWorker &_blsWorker, CDKGSessionManager &_dkgManager)
bool Init (const CBlockIndex *pindexQuorum, const std::vector< CDeterministicMNCPtr > &mns, const uint256 &_myProTxHash)
size_t GetMyMemberIndex () const
void Contribute (CDKGPendingMessages &pendingMessages)
The following sets of methods are for the first 4 phases handled in the session.
void SendContributions (CDKGPendingMessages &pendingMessages)
bool PreVerifyMessage (const uint256 &hash, const CDKGContribution &qc, bool &retBan) const
void ReceiveMessage (const uint256 &hash, const CDKGContribution &qc, bool &retBan)
void VerifyPendingContributions ()
void VerifyAndComplain (CDKGPendingMessages &pendingMessages)
void VerifyConnectionAndMinProtoVersions ()
void SendComplaint (CDKGPendingMessages &pendingMessages)
bool PreVerifyMessage (const uint256 &hash, const CDKGComplaint &qc, bool &retBan) const
void ReceiveMessage (const uint256 &hash, const CDKGComplaint &qc, bool &retBan)
void VerifyAndJustify (CDKGPendingMessages &pendingMessages)
void SendJustification (CDKGPendingMessages &pendingMessages, const std::set< uint256 > &forMembers)
bool PreVerifyMessage (const uint256 &hash, const CDKGJustification &qj, bool &retBan) const
void ReceiveMessage (const uint256 &hash, const CDKGJustification &qj, bool &retBan)
void VerifyAndCommit (CDKGPendingMessages &pendingMessages)
void SendCommitment (CDKGPendingMessages &pendingMessages)
bool PreVerifyMessage (const uint256 &hash, const CDKGPrematureCommitment &qc, bool &retBan) const
void ReceiveMessage (const uint256 &hash, const CDKGPrematureCommitment &qc, bool &retBan)
std::vector< CFinalCommitment > FinalizeCommitments ()
bool AreWeMember () const
void MarkBadMember (size_t idx)
void RelayInvToParticipants (const CInv &inv) const
CDKGMember * GetMember (const uint256 &proTxHash) const
Private Attributes
const Consensus::LLMQParams & params
CBLSWorker & blsWorker
CBLSWorkerCache cache
CDKGSessionManager & dkgManager
const CBlockIndex * pindexQuorum
std::vector< std::unique_ptr< CDKGMember > > members
std::map< uint256, size_t > membersMap
std::set< uint256 > relayMembers
BLSVerificationVectorPtr vvecContribution
BLSSecretKeyVector skContributions
BLSIdVector memberIds
std::vector< BLSVerificationVectorPtr > receivedVvecs
BLSSecretKeyVector receivedSkContributions
uint256 myProTxHash
CBLSId myId
size_t myIdx {(size_t)-1}
CCriticalSection invCs
std::map< uint256, CDKGContribution > contributions
std::map< uint256, CDKGComplaint > complaints
std::map< uint256, CDKGJustification > justifications
std::map< uint256, CDKGPrematureCommitment > prematureCommitments
std::vector< size_t > pendingContributionVerifications
std::set< uint256 > validCommitments
Friends
class CDKGSessionHandler
class CDKGSessionManager
class CDKGLogger
Detailed Description
The DKG session is a single instance of the DKG process.
It is owned and called by CDKGSessionHandler, which passes received DKG messages to the session. The session is not persistent and will loose it's state (the whole object is discarded) when it finishes (after the mining phase) or is aborted.
When incoming contributions are received and the verification vector is valid, it is passed to CDKGSessionManager which will store it in the evo DB. Secret key contributions which are meant for the local member are also passed to CDKGSessionManager to store them in the evo DB. If verification of the SK contribution initially fails, it is not passed to CDKGSessionManager. If the justification phase later gives a valid SK contribution from the same member, it is then passed to CDKGSessionManager and after this handled the same way.
The contributions stored by CDKGSessionManager are then later loaded by the quorum instances and used for signing sessions, but only if the local node is a member of the quorum.
Definition at line 239 of file quorums_dkgsession.h.
Constructor & Destructor Documentation
CDKGSession()
llmq::CDKGSession::CDKGSession (const Consensus::LLMQParams & _params, CBLSWorker & _blsWorker, CDKGSessionManager & _dkgManager) inline
Definition at line 286 of file quorums_dkgsession.h.
Member Function Documentation
AreWeMember()
bool llmq::CDKGSession::AreWeMember () const inline
Definition at line 335 of file quorums_dkgsession.h.
References base_blob< BITS >::IsNull(), and myProTxHash.
Referenced by Contribute(), FinalizeCommitments(), ReceiveMessage(), SendCommitment(), SendComplaint(), SendContributions(), SendJustification(), VerifyAndCommit(), VerifyAndComplain(), and VerifyAndJustify().
Contribute()
void llmq::CDKGSession::Contribute (CDKGPendingMessages & pendingMessages)
The following sets of methods are for the first 4 phases handled in the session.
The flow of message calls is identical for all phases:
Execute local action (e.g. create/send own contributions)
PreVerify incoming messages for this phase. Preverification means that everything from the message is checked that does not require too much resources for verification. This specifically excludes all CPU intensive BLS operations.
CDKGSessionHandler will collect pre verified messages in batches and perform batched BLS signature verification on these.
ReceiveMessage is called for each pre verified message with a valid signature. ReceiveMessage is also responsible for further verification of validity (e.g. validate vvecs and SK contributions).
Definition at line 140 of file quorums_dkgsession.cpp.
References AreWeMember(), CBatchedLogger::Batch(), blsWorker, cxxtimer::Timer::count(), CBLSWorker::GenerateContributions(), memberIds, params, SendContributions(), skContributions, Consensus::LLMQParams::threshold, and vvecContribution.
FinalizeCommitments()
std::vector< CFinalCommitment > llmq::CDKGSession::FinalizeCommitments ()
Definition at line 1192 of file quorums_dkgsession.cpp.
References CBLSSignature::AggregateSecure(), AreWeMember(), CBatchedLogger::Batch(), llmq::CLLMQUtils::BuildCommitmentHash(), cxxtimer::Timer::count(), llmq::CFinalCommitment::CountSigners(), llmq::CFinalCommitment::CountValidMembers(), CBatchedLogger::Flush(), llmq::CFinalCommitment::llmqType, members, membersMap, llmq::CFinalCommitment::membersSig, Consensus::LLMQParams::minSize, params, prematureCommitments, llmq::CFinalCommitment::quorumHash, llmq::CFinalCommitment::quorumPublicKey, llmq::CFinalCommitment::quorumSig, llmq::CFinalCommitment::quorumVvecHash, CBLSSignature::Recover(), llmq::CFinalCommitment::signers, cxxtimer::Timer::stop(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), validCommitments, and llmq::CFinalCommitment::validMembers.
GetMember()
CDKGMember * llmq::CDKGSession::GetMember (const uint256 & proTxHash) const
Definition at line 1289 of file quorums_dkgsession.cpp.
References members, and membersMap.
Referenced by llmq::BatchVerifyMessageSigs(), PreVerifyMessage(), and ReceiveMessage().
GetMyMemberIndex()
size_t llmq::CDKGSession::GetMyMemberIndex () const inline
Definition at line 291 of file quorums_dkgsession.h.
References myIdx.
Init()
bool llmq::CDKGSession::Init (const CBlockIndex * pindexQuorum, const std::vector< CDeterministicMNCPtr > & mns, const uint256 & _myProTxHash)
Definition at line 92 of file quorums_dkgsession.cpp.
References CBatchedLogger::Batch(), CBlockIndex::GetBlockHash(), llmq::CLLMQUtils::GetQuorumRelayMembers(), llmq::CDKGDebugManager::InitLocalSessionStatus(), base_blob< BITS >::IsNull(), memberIds, members, membersMap, Consensus::LLMQParams::minSize, myId, myIdx, myProTxHash, CBlockIndex::nHeight, params, pindexQuorum, llmq::quorumDKGDebugManager, receivedSkContributions, receivedVvecs, relayMembers, and Consensus::LLMQParams::type.
MarkBadMember()
void llmq::CDKGSession::MarkBadMember (size_t idx)
Definition at line 1298 of file quorums_dkgsession.cpp.
References members, params, llmq::quorumDKGDebugManager, Consensus::LLMQParams::type, and llmq::CDKGDebugManager::UpdateLocalMemberStatus().
Referenced by ReceiveMessage(), VerifyAndCommit(), VerifyAndComplain(), and VerifyAndJustify().
PreVerifyMessage() [1/4]
bool llmq::CDKGSession::PreVerifyMessage (const uint256 & hash, const CDKGContribution & qc, bool & retBan) const
Definition at line 213 of file quorums_dkgsession.cpp.
References CBatchedLogger::Batch(), blsWorker, llmq::CDKGContribution::contributions, CBlockIndex::GetBlockHash(), GetMember(), members, params, pindexQuorum, llmq::CDKGContribution::proTxHash, llmq::CDKGContribution::quorumHash, Consensus::LLMQParams::threshold, CBLSWorker::VerifyVerificationVector(), and llmq::CDKGContribution::vvec.
Referenced by llmq::ProcessPendingMessageBatch().
PreVerifyMessage() [2/4]
bool llmq::CDKGSession::PreVerifyMessage (const uint256 & hash, const CDKGComplaint & qc, bool & retBan) const
Definition at line 528 of file quorums_dkgsession.cpp.
References llmq::CDKGComplaint::badMembers, CBatchedLogger::Batch(), llmq::CDKGComplaint::complainForMembers, CBlockIndex::GetBlockHash(), GetMember(), params, pindexQuorum, llmq::CDKGComplaint::proTxHash, llmq::CDKGComplaint::quorumHash, and Consensus::LLMQParams::size.
PreVerifyMessage() [3/4]
bool llmq::CDKGSession::PreVerifyMessage (const uint256 & hash, const CDKGJustification & qj, bool & retBan) const
Definition at line 725 of file quorums_dkgsession.cpp.
References CBatchedLogger::Batch(), llmq::CDKGJustification::contributions, CBlockIndex::GetBlockHash(), GetMember(), members, pindexQuorum, llmq::CDKGJustification::proTxHash, and llmq::CDKGJustification::quorumHash.
PreVerifyMessage() [4/4]
bool llmq::CDKGSession::PreVerifyMessage (const uint256 & hash, const CDKGPrematureCommitment & qc, bool & retBan) const
Definition at line 1046 of file quorums_dkgsession.cpp.
References CBatchedLogger::Batch(), llmq::CDKGPrematureCommitment::CountValidMembers(), CBlockIndex::GetBlockHash(), GetMember(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), members, Consensus::LLMQParams::minSize, params, pindexQuorum, llmq::CDKGPrematureCommitment::proTxHash, llmq::CDKGPrematureCommitment::quorumHash, llmq::CDKGPrematureCommitment::quorumSig, llmq::CDKGPrematureCommitment::sig, Consensus::LLMQParams::size, and llmq::CDKGPrematureCommitment::validMembers.
ReceiveMessage() [1/4]
void llmq::CDKGSession::ReceiveMessage (const uint256 & hash, const CDKGContribution & qc, bool & retBan)
Definition at line 261 of file quorums_dkgsession.cpp.
References activeMasternodeInfo, AreWeMember(), CBatchedLogger::Batch(), CActiveMasternodeInfo::blsKeyOperator, llmq::CDKGContribution::contributions, contributions, cxxtimer::Timer::count(), dkgManager, GetMember(), invCs, LOCK, MarkBadMember(), members, MSG_QUORUM_CONTRIB, myIdx, params, pendingContributionVerifications, pindexQuorum, PROTOCOL_VERSION, llmq::CDKGContribution::proTxHash, llmq::quorumDKGDebugManager, receivedSkContributions, receivedVvecs, RelayInvToParticipants(), llmq::ShouldSimulateError(), base_blob< BITS >::ToString(), Consensus::LLMQParams::type, llmq::CDKGDebugManager::UpdateLocalMemberStatus(), VerifyPendingContributions(), llmq::CDKGContribution::vvec, and llmq::CDKGSessionManager::WriteVerifiedVvecContribution().
Referenced by llmq::ProcessPendingMessageBatch().
ReceiveMessage() [2/4]
void llmq::CDKGSession::ReceiveMessage (const uint256 & hash, const CDKGComplaint & qc, bool & retBan)
Definition at line 570 of file quorums_dkgsession.cpp.
References AreWeMember(), llmq::CDKGComplaint::badMembers, CBatchedLogger::Batch(), llmq::CDKGComplaint::complainForMembers, complaints, GetMember(), invCs, LOCK, MarkBadMember(), members, MSG_QUORUM_COMPLAINT, myIdx, params, llmq::CDKGComplaint::proTxHash, llmq::quorumDKGDebugManager, RelayInvToParticipants(), base_blob< BITS >::ToString(), Consensus::LLMQParams::type, and llmq::CDKGDebugManager::UpdateLocalMemberStatus().
ReceiveMessage() [3/4]
void llmq::CDKGSession::ReceiveMessage (const uint256 & hash, const CDKGJustification & qj, bool & retBan)
Definition at line 783 of file quorums_dkgsession.cpp.
References AreWeMember(), CBLSWorker::AsyncVerifyContributionShare(), CBatchedLogger::Batch(), blsWorker, llmq::CDKGJustification::contributions, cxxtimer::Timer::count(), dkgManager, GetMember(), invCs, justifications, LOCK, MarkBadMember(), members, MSG_QUORUM_JUSTIFICATION, myId, params, pindexQuorum, llmq::CDKGJustification::proTxHash, llmq::quorumDKGDebugManager, receivedSkContributions, receivedVvecs, RelayInvToParticipants(), base_blob< BITS >::ToString(), Consensus::LLMQParams::type, llmq::CDKGDebugManager::UpdateLocalMemberStatus(), and llmq::CDKGSessionManager::WriteVerifiedSkContribution().
ReceiveMessage() [4/4]
void llmq::CDKGSession::ReceiveMessage (const uint256 & hash, const CDKGPrematureCommitment & qc, bool & retBan)
Definition at line 1108 of file quorums_dkgsession.cpp.
References CBatchedLogger::Batch(), CBLSWorkerCache::BuildPubKeyShare(), CBLSWorkerCache::BuildQuorumVerificationVector(), cache, cxxtimer::Timer::count(), llmq::CDKGPrematureCommitment::CountValidMembers(), dkgManager, GetMember(), llmq::CDKGPrematureCommitment::GetSignHash(), llmq::CDKGSessionManager::GetVerifiedContributions(), invCs, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), LOCK, members, MSG_QUORUM_PREMATURE_COMMITMENT, params, pindexQuorum, prematureCommitments, llmq::CDKGPrematureCommitment::proTxHash, llmq::quorumDKGDebugManager, llmq::CDKGPrematureCommitment::quorumPublicKey, llmq::CDKGPrematureCommitment::quorumSig, llmq::CDKGPrematureCommitment::quorumVvecHash, RelayInvToParticipants(), SerializeHash(), skContributions, cxxtimer::Timer::stop(), base_blob< BITS >::ToString(), Consensus::LLMQParams::type, llmq::CDKGDebugManager::UpdateLocalMemberStatus(), validCommitments, llmq::CDKGPrematureCommitment::validMembers, and CBLSSignature::VerifyInsecure().
RelayInvToParticipants()
void llmq::CDKGSession::RelayInvToParticipants (const CInv & inv) const
Definition at line 1311 of file quorums_dkgsession.cpp.
References g_connman, invCs, base_blob< BITS >::IsNull(), LOCK, CNode::PushInventory(), CNode::qwatch, relayMembers, and CNode::verifiedProRegTxHash.
Referenced by ReceiveMessage().
SendCommitment()
void llmq::CDKGSession::SendCommitment (CDKGPendingMessages & pendingMessages)
Definition at line 931 of file quorums_dkgsession.cpp.
References activeMasternodeInfo, CBLSWorkerCache::AggregateSecretKeys(), AreWeMember(), CBatchedLogger::Batch(), base_blob< BITS >::begin(), CActiveMasternodeInfo::blsKeyOperator, llmq::CLLMQUtils::BuildCommitmentHash(), CBLSWorkerCache::BuildQuorumVerificationVector(), cache, cxxtimer::Timer::count(), llmq::CDKGPrematureCommitment::CountValidMembers(), dkgManager, CBatchedLogger::Flush(), CBlockIndex::GetBlockHash(), CBLSWrapper< ImplType, _SerSize, C >::GetBuf(), CBLSSecretKey::GetPublicKey(), GetRandInt(), llmq::CDKGSessionManager::GetVerifiedContributions(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), llmq::CDKGPrematureCommitment::llmqType, CBLSSecretKey::MakeNewKey(), members, Consensus::LLMQParams::minSize, myProTxHash, params, pindexQuorum, llmq::CDKGPrematureCommitment::proTxHash, llmq::CDKGPendingMessages::PushPendingMessage(), llmq::quorumDKGDebugManager, llmq::CDKGPrematureCommitment::quorumHash, llmq::CDKGPrematureCommitment::quorumPublicKey, llmq::CDKGPrematureCommitment::quorumSig, llmq::CDKGPrematureCommitment::quorumVvecHash, SerializeHash(), CBLSWrapper< ImplType, _SerSize, C >::SetBuf(), llmq::ShouldSimulateError(), llmq::CDKGPrematureCommitment::sig, CBLSSecretKey::Sign(), skContributions, cxxtimer::Timer::stop(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), Consensus::LLMQParams::type, llmq::CDKGDebugManager::UpdateLocalSessionStatus(), and llmq::CDKGPrematureCommitment::validMembers.
Referenced by VerifyAndCommit().
SendComplaint()
void llmq::CDKGSession::SendComplaint (CDKGPendingMessages & pendingMessages)
Definition at line 485 of file quorums_dkgsession.cpp.
References activeMasternodeInfo, AreWeMember(), llmq::CDKGComplaint::badMembers, CBatchedLogger::Batch(), CActiveMasternodeInfo::blsKeyOperator, llmq::CDKGComplaint::complainForMembers, CBatchedLogger::Flush(), CBlockIndex::GetBlockHash(), llmq::CDKGComplaint::GetSignHash(), llmq::CDKGComplaint::llmqType, members, myProTxHash, params, pindexQuorum, llmq::CDKGComplaint::proTxHash, llmq::CDKGPendingMessages::PushPendingMessage(), llmq::quorumDKGDebugManager, llmq::CDKGComplaint::quorumHash, llmq::CDKGComplaint::sig, Consensus::LLMQParams::type, and llmq::CDKGDebugManager::UpdateLocalSessionStatus().
Referenced by VerifyAndComplain().
SendContributions()
void llmq::CDKGSession::SendContributions (CDKGPendingMessages & pendingMessages)
Definition at line 160 of file quorums_dkgsession.cpp.
References activeMasternodeInfo, AreWeMember(), CBatchedLogger::Batch(), CActiveMasternodeInfo::blsKeyOperator, llmq::CDKGContribution::contributions, cxxtimer::Timer::count(), CBatchedLogger::Flush(), CBlockIndex::GetBlockHash(), llmq::CDKGContribution::GetSignHash(), llmq::CDKGContribution::llmqType, CBLSSecretKey::MakeNewKey(), members, myIdx, myProTxHash, params, pindexQuorum, PROTOCOL_VERSION, llmq::CDKGContribution::proTxHash, llmq::CDKGPendingMessages::PushPendingMessage(), llmq::quorumDKGDebugManager, llmq::CDKGContribution::quorumHash, llmq::ShouldSimulateError(), llmq::CDKGContribution::sig, skContributions, Consensus::LLMQParams::type, llmq::CDKGDebugManager::UpdateLocalSessionStatus(), llmq::CDKGContribution::vvec, and vvecContribution.
Referenced by Contribute().
SendJustification()
void llmq::CDKGSession::SendJustification (CDKGPendingMessages & pendingMessages, const std::set< uint256 > & forMembers)
Definition at line 676 of file quorums_dkgsession.cpp.
References activeMasternodeInfo, AreWeMember(), CBatchedLogger::Batch(), CActiveMasternodeInfo::blsKeyOperator, llmq::CDKGJustification::contributions, CBatchedLogger::Flush(), CBlockIndex::GetBlockHash(), llmq::CDKGJustification::GetSignHash(), llmq::CDKGJustification::llmqType, CBLSSecretKey::MakeNewKey(), members, myIdx, myProTxHash, params, pindexQuorum, llmq::CDKGJustification::proTxHash, llmq::CDKGPendingMessages::PushPendingMessage(), llmq::quorumDKGDebugManager, llmq::CDKGJustification::quorumHash, llmq::ShouldSimulateError(), llmq::CDKGJustification::sig, skContributions, Consensus::LLMQParams::type, and llmq::CDKGDebugManager::UpdateLocalSessionStatus().
Referenced by VerifyAndJustify().
VerifyAndCommit()
void llmq::CDKGSession::VerifyAndCommit (CDKGPendingMessages & pendingMessages)
Definition at line 888 of file quorums_dkgsession.cpp.
References AreWeMember(), CBatchedLogger::Batch(), CBatchedLogger::Flush(), MarkBadMember(), members, and SendCommitment().
VerifyAndComplain()
void llmq::CDKGSession::VerifyAndComplain (CDKGPendingMessages & pendingMessages)
Definition at line 409 of file quorums_dkgsession.cpp.
References AreWeMember(), CBatchedLogger::Batch(), cxxtimer::Timer::count(), CBatchedLogger::Flush(), MarkBadMember(), members, SendComplaint(), VerifyConnectionAndMinProtoVersions(), and VerifyPendingContributions().
VerifyAndJustify()
void llmq::CDKGSession::VerifyAndJustify (CDKGPendingMessages & pendingMessages)
Definition at line 636 of file quorums_dkgsession.cpp.
References AreWeMember(), CBatchedLogger::Batch(), complaints, Consensus::LLMQParams::dkgBadVotesThreshold, CBatchedLogger::Flush(), MarkBadMember(), members, myIdx, params, and SendJustification().
VerifyConnectionAndMinProtoVersions()
void llmq::CDKGSession::VerifyConnectionAndMinProtoVersions ()
Definition at line 447 of file quorums_dkgsession.cpp.
References CBatchedLogger::Batch(), g_connman, GetAdjustedTime(), CMasternodeMetaMan::GetMetaInfo(), llmq::CLLMQUtils::IsAllMembersConnectedEnabled(), base_blob< BITS >::IsNull(), members, MIN_MASTERNODE_PROTO_VERSION, mmetaman, myProTxHash, CNode::nVersion, params, Consensus::LLMQParams::type, and CNode::verifiedProRegTxHash.
Referenced by VerifyAndComplain().
VerifyPendingContributions()
void llmq::CDKGSession::VerifyPendingContributions ()
Definition at line 360 of file quorums_dkgsession.cpp.
References CBatchedLogger::Batch(), blsWorker, cxxtimer::Timer::count(), dkgManager, members, myId, params, pendingContributionVerifications, pindexQuorum, llmq::quorumDKGDebugManager, receivedSkContributions, receivedVvecs, skContributions, Consensus::LLMQParams::type, llmq::CDKGDebugManager::UpdateLocalMemberStatus(), CBLSWorker::VerifyContributionShares(), and llmq::CDKGSessionManager::WriteVerifiedSkContribution().
Referenced by ReceiveMessage(), and VerifyAndComplain().
Friends And Related Function Documentation
CDKGLogger
friend class CDKGLogger friend
Definition at line 243 of file quorums_dkgsession.h.
CDKGSessionHandler
friend class CDKGSessionHandler friend
Definition at line 241 of file quorums_dkgsession.h.
CDKGSessionManager
friend class CDKGSessionManager friend
Definition at line 242 of file quorums_dkgsession.h.
Member Data Documentation
blsWorker
CBLSWorker& llmq::CDKGSession::blsWorker private
Definition at line 248 of file quorums_dkgsession.h.
Referenced by Contribute(), PreVerifyMessage(), ReceiveMessage(), and VerifyPendingContributions().
cache
CBLSWorkerCache llmq::CDKGSession::cache private
Definition at line 249 of file quorums_dkgsession.h.
Referenced by ReceiveMessage(), and SendCommitment().
complaints
std::map<uint256, CDKGComplaint> llmq::CDKGSession::complaints private
Definition at line 276 of file quorums_dkgsession.h.
Referenced by ReceiveMessage(), and VerifyAndJustify().
contributions
std::map<uint256, CDKGContribution> llmq::CDKGSession::contributions private
Definition at line 275 of file quorums_dkgsession.h.
Referenced by ReceiveMessage().
dkgManager
CDKGSessionManager& llmq::CDKGSession::dkgManager private
Definition at line 250 of file quorums_dkgsession.h.
Referenced by ReceiveMessage(), SendCommitment(), and VerifyPendingContributions().
invCs
CCriticalSection llmq::CDKGSession::invCs mutable private
Definition at line 274 of file quorums_dkgsession.h.
Referenced by ReceiveMessage(), and RelayInvToParticipants().
justifications
std::map<uint256, CDKGJustification> llmq::CDKGSession::justifications private
Definition at line 277 of file quorums_dkgsession.h.
Referenced by ReceiveMessage().
memberIds
BLSIdVector llmq::CDKGSession::memberIds private
Definition at line 261 of file quorums_dkgsession.h.
Referenced by Contribute(), and Init().
members
std::vector<std::unique_ptr<CDKGMember> > llmq::CDKGSession::members private
Definition at line 255 of file quorums_dkgsession.h.
Referenced by FinalizeCommitments(), GetMember(), Init(), MarkBadMember(), PreVerifyMessage(), ReceiveMessage(), SendCommitment(), SendComplaint(), SendContributions(), SendJustification(), VerifyAndCommit(), VerifyAndComplain(), VerifyAndJustify(), VerifyConnectionAndMinProtoVersions(), and VerifyPendingContributions().
membersMap
std::map<uint256, size_t> llmq::CDKGSession::membersMap private
Definition at line 256 of file quorums_dkgsession.h.
Referenced by FinalizeCommitments(), GetMember(), and Init().
myId
CBLSId llmq::CDKGSession::myId private
Definition at line 267 of file quorums_dkgsession.h.
Referenced by Init(), ReceiveMessage(), and VerifyPendingContributions().
myIdx
size_t llmq::CDKGSession::myIdx {(size_t)-1} private
Definition at line 268 of file quorums_dkgsession.h.
Referenced by GetMyMemberIndex(), Init(), ReceiveMessage(), SendContributions(), SendJustification(), and VerifyAndJustify().
myProTxHash
uint256 llmq::CDKGSession::myProTxHash private
Definition at line 266 of file quorums_dkgsession.h.
Referenced by AreWeMember(), Init(), SendCommitment(), SendComplaint(), SendContributions(), SendJustification(), and VerifyConnectionAndMinProtoVersions().
params
const Consensus::LLMQParams& llmq::CDKGSession::params private
Definition at line 246 of file quorums_dkgsession.h.
Referenced by Contribute(), FinalizeCommitments(), Init(), MarkBadMember(), PreVerifyMessage(), ReceiveMessage(), SendCommitment(), SendComplaint(), SendContributions(), SendJustification(), VerifyAndJustify(), VerifyConnectionAndMinProtoVersions(), and VerifyPendingContributions().
pendingContributionVerifications
std::vector<size_t> llmq::CDKGSession::pendingContributionVerifications private
Definition at line 280 of file quorums_dkgsession.h.
Referenced by ReceiveMessage(), and VerifyPendingContributions().
pindexQuorum
const CBlockIndex* llmq::CDKGSession::pindexQuorum private
Definition at line 252 of file quorums_dkgsession.h.
Referenced by Init(), PreVerifyMessage(), ReceiveMessage(), SendCommitment(), SendComplaint(), SendContributions(), SendJustification(), and VerifyPendingContributions().
prematureCommitments
std::map<uint256, CDKGPrematureCommitment> llmq::CDKGSession::prematureCommitments private
Definition at line 278 of file quorums_dkgsession.h.
Referenced by FinalizeCommitments(), and ReceiveMessage().
receivedSkContributions
BLSSecretKeyVector llmq::CDKGSession::receivedSkContributions private
Definition at line 264 of file quorums_dkgsession.h.
Referenced by Init(), ReceiveMessage(), and VerifyPendingContributions().
receivedVvecs
std::vector<BLSVerificationVectorPtr> llmq::CDKGSession::receivedVvecs private
Definition at line 262 of file quorums_dkgsession.h.
Referenced by Init(), ReceiveMessage(), and VerifyPendingContributions().
relayMembers
std::set<uint256> llmq::CDKGSession::relayMembers private
Definition at line 257 of file quorums_dkgsession.h.
Referenced by Init(), and RelayInvToParticipants().
skContributions
BLSSecretKeyVector llmq::CDKGSession::skContributions private
Definition at line 259 of file quorums_dkgsession.h.
Referenced by Contribute(), ReceiveMessage(), SendCommitment(), SendContributions(), SendJustification(), and VerifyPendingContributions().
validCommitments
std::set<uint256> llmq::CDKGSession::validCommitments private
Definition at line 283 of file quorums_dkgsession.h.
Referenced by FinalizeCommitments(), and ReceiveMessage().
vvecContribution
BLSVerificationVectorPtr llmq::CDKGSession::vvecContribution private
Definition at line 258 of file quorums_dkgsession.h.
Referenced by Contribute(), and SendContributions().
The documentation for this class was generated from the following files:
src/llmq/quorums_dkgsession.h
src/llmq/quorums_dkgsession.cpp
Released under the MIT license