Dash Core: CKeePassIntegrator Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CKeePassIntegrator Class Reference
#include <keepass.h>
Classes
class CKeePassEntry
class CKeePassRequest
class CKeePassResponse
Public Member Functions
CKeePassIntegrator ()
void init ()
void rpcAssociate (std::string &strId, SecureString &sKeyBase64)
SecureString retrievePassphrase ()
void updatePassphrase (const SecureString &sWalletPassphrase)
Static Public Member Functions
static SecureString generateKeePassKey ()
Private Member Functions
void doHTTPPost (const std::string &strRequest, int &nStatus, std::string &strResponse)
void rpcTestAssociation (bool bTriggerUnlock)
std::vector< CKeePassEntry > rpcGetLogins ()
void rpcSetLogin (const SecureString &sWalletPass, const SecureString &sEntryId)
Static Private Member Functions
static SecureString generateRandomKey (size_t nSize)
static std::string constructHTTPPost (const std::string &strMsg, const std::map< std::string, std::string > &mapRequestHeaders)
Private Attributes
bool bIsActive
unsigned int nPort
SecureString sKeyBase64
SecureString sKey
SecureString sUrl
std::string strKeePassId
std::string strKeePassEntryName
Static Private Attributes
static const int KEEPASS_CRYPTO_KEY_SIZE = 32
static const int KEEPASS_CRYPTO_BLOCK_SIZE = 16
static const int KEEPASS_HTTP_CONNECT_TIMEOUT = 30
static const char * KEEPASS_HTTP_HOST = "localhost"
Detailed Description
Definition at line 18 of file keepass.h.
Constructor & Destructor Documentation
CKeePassIntegrator()
CKeePassIntegrator::CKeePassIntegrator ()
Definition at line 93 of file keepass.cpp.
References bIsActive, DEFAULT_KEEPASS_HTTP_PORT, nPort, sKey, sKeyBase64, and sUrl.
Member Function Documentation
constructHTTPPost()
std::string CKeePassIntegrator::constructHTTPPost (const std::string & strMsg, const std::map< std::string, std::string > & mapRequestHeaders) static private
Definition at line 242 of file keepass.cpp.
References FormatFullVersion(), and PAIRTYPE.
doHTTPPost()
void CKeePassIntegrator::doHTTPPost (const std::string & strRequest, int & nStatus, std::string & strResponse) private
Definition at line 292 of file keepass.cpp.
References base, DEFAULT_KEEPASS_HTTP_PORT, UniValue::empty(), FormatFullVersion(), UniValue::get_obj(), UniValue::get_str(), HTTP_BAD_REQUEST, HTTP_INTERNAL_SERVER_ERROR, HTTP_NOT_FOUND, http_request_done(), KEEPASS_HTTP_CONNECT_TIMEOUT, KEEPASS_HTTP_HOST, LogPrint(), UniValue::read(), strprintf, and UniValue::VSTR.
Referenced by rpcAssociate(), rpcGetLogins(), rpcSetLogin(), and rpcTestAssociation().
generateKeePassKey()
SecureString CKeePassIntegrator::generateKeePassKey () static
Definition at line 533 of file keepass.cpp.
References EncodeBase64Secure(), generateRandomKey(), KEEPASS_CRYPTO_KEY_SIZE, sKey, and sKeyBase64.
Referenced by keepass().
generateRandomKey()
SecureString CKeePassIntegrator::generateRandomKey (size_t nSize) static private
Definition at line 229 of file keepass.cpp.
References GetRandBytes(), RandAddSeedPerfmon(), and sKey.
Referenced by generateKeePassKey(), CKeePassIntegrator::CKeePassRequest::init(), and rpcAssociate().
init()
void CKeePassIntegrator::init ()
Definition at line 104 of file keepass.cpp.
References bIsActive, DecodeBase64Secure(), DEFAULT_KEEPASS_HTTP_PORT, GetArg(), GetBoolArg(), nPort, sKey, sKeyBase64, strKeePassEntryName, strKeePassId, and sUrl.
Referenced by AppInit2().
retrievePassphrase()
SecureString CKeePassIntegrator::retrievePassphrase ()
Definition at line 579 of file keepass.cpp.
References rpcGetLogins(), sKey, strKeePassEntryName, and strKeePassId.
Referenced by CWallet::ChangeWalletPassphrase(), and CWallet::Unlock().
rpcAssociate()
void CKeePassIntegrator::rpcAssociate (std::string & strId, SecureString & sKeyBase64)
Definition at line 540 of file keepass.cpp.
References CKeePassIntegrator::CKeePassRequest::addStrParameter(), doHTTPPost(), EncodeBase64Secure(), generateRandomKey(), CKeePassIntegrator::CKeePassRequest::getJson(), CKeePassIntegrator::CKeePassResponse::getStr(), CKeePassIntegrator::CKeePassResponse::getSuccess(), itostr(), KEEPASS_CRYPTO_KEY_SIZE, LogPrint(), sKey, and sKeyBase64.
Referenced by keepass().
rpcGetLogins()
std::vector< CKeePassIntegrator::CKeePassEntry > CKeePassIntegrator::rpcGetLogins () private
Definition at line 440 of file keepass.cpp.
References CKeePassIntegrator::CKeePassRequest::addStrParameter(), DecodeBase64Secure(), doHTTPPost(), CKeePassIntegrator::CKeePassResponse::getEntries(), CKeePassIntegrator::CKeePassRequest::getJson(), CKeePassIntegrator::CKeePassResponse::getSuccess(), itostr(), LogPrint(), sKey, sKeyBase64, strKeePassId, and sUrl.
Referenced by retrievePassphrase(), and updatePassphrase().
rpcSetLogin()
void CKeePassIntegrator::rpcSetLogin (const SecureString & sWalletPass, const SecureString & sEntryId) private
Definition at line 484 of file keepass.cpp.
References CKeePassIntegrator::CKeePassRequest::addStrParameter(), DecodeBase64Secure(), doHTTPPost(), CKeePassIntegrator::CKeePassRequest::getJson(), CKeePassIntegrator::CKeePassResponse::getSuccess(), itostr(), LogPrint(), sKey, sKeyBase64, strKeePassId, and sUrl.
Referenced by updatePassphrase().
rpcTestAssociation()
void CKeePassIntegrator::rpcTestAssociation (bool bTriggerUnlock) private
Definition at line 427 of file keepass.cpp.
References CKeePassIntegrator::CKeePassRequest::addStrParameter(), doHTTPPost(), CKeePassIntegrator::CKeePassRequest::getJson(), LogPrint(), and sKey.
updatePassphrase()
void CKeePassIntegrator::updatePassphrase (const SecureString & sWalletPassphrase)
Definition at line 613 of file keepass.cpp.
References rpcGetLogins(), rpcSetLogin(), sKey, strKeePassEntryName, and strKeePassId.
Referenced by CWallet::ChangeWalletPassphrase(), CWallet::EncryptWallet(), and keepass().
Member Data Documentation
bIsActive
bool CKeePassIntegrator::bIsActive private
Definition at line 25 of file keepass.h.
Referenced by CKeePassIntegrator(), and init().
KEEPASS_CRYPTO_BLOCK_SIZE
const int CKeePassIntegrator::KEEPASS_CRYPTO_BLOCK_SIZE = 16 static private
Definition at line 21 of file keepass.h.
Referenced by CKeePassIntegrator::CKeePassRequest::init().
KEEPASS_CRYPTO_KEY_SIZE
const int CKeePassIntegrator::KEEPASS_CRYPTO_KEY_SIZE = 32 static private
Definition at line 20 of file keepass.h.
Referenced by generateKeePassKey(), and rpcAssociate().
KEEPASS_HTTP_CONNECT_TIMEOUT
const int CKeePassIntegrator::KEEPASS_HTTP_CONNECT_TIMEOUT = 30 static private
Definition at line 22 of file keepass.h.
Referenced by doHTTPPost().
KEEPASS_HTTP_HOST
const char * CKeePassIntegrator::KEEPASS_HTTP_HOST = "localhost" static private
Definition at line 23 of file keepass.h.
Referenced by doHTTPPost().
nPort
unsigned int CKeePassIntegrator::nPort private
Definition at line 26 of file keepass.h.
Referenced by CKeePassIntegrator(), and init().
sKey
SecureString CKeePassIntegrator::sKey private
Definition at line 28 of file keepass.h.
Referenced by CKeePassIntegrator::CKeePassRequest::addStrParameter(), CKeePassIntegrator(), CKeePassIntegrator::CKeePassResponse::decrypt(), generateKeePassKey(), generateRandomKey(), init(), retrievePassphrase(), rpcAssociate(), rpcGetLogins(), rpcSetLogin(), rpcTestAssociation(), and updatePassphrase().
sKeyBase64
SecureString CKeePassIntegrator::sKeyBase64 private
Definition at line 27 of file keepass.h.
Referenced by CKeePassIntegrator(), generateKeePassKey(), init(), rpcAssociate(), rpcGetLogins(), and rpcSetLogin().
strKeePassEntryName
std::string CKeePassIntegrator::strKeePassEntryName private
Definition at line 32 of file keepass.h.
Referenced by init(), retrievePassphrase(), and updatePassphrase().
strKeePassId
std::string CKeePassIntegrator::strKeePassId private
Definition at line 31 of file keepass.h.
Referenced by init(), retrievePassphrase(), rpcGetLogins(), rpcSetLogin(), and updatePassphrase().
sUrl
SecureString CKeePassIntegrator::sUrl private
Definition at line 29 of file keepass.h.
Referenced by CKeePassIntegrator(), init(), rpcGetLogins(), and rpcSetLogin().
The documentation for this class was generated from the following files:
src/keepass.h
src/keepass.cpp
Released under the MIT license