Dash Core: llmq::CDKGDebugStatus Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CDKGDebugStatus Class Reference
#include <quorums_debug.h>
Public Member Functions
UniValue ToJson (int detailLevel) const
Public Attributes
int64_t nTime {0}
std::map< Consensus::LLMQType, CDKGDebugSessionStatus > sessions
Detailed Description
Definition at line 78 of file quorums_debug.h.
Member Function Documentation
ToJson()
UniValue llmq::CDKGDebugStatus::ToJson (int detailLevel) const
Definition at line 119 of file quorums_debug.cpp.
References DateTimeStrFormat(), CChainParams::GetConsensus(), Consensus::Params::llmqs, nTime, Pair(), Params(), UniValue::push_back(), sessions, and UniValue::VOBJ.
Referenced by quorum_dkgstatus().
Member Data Documentation
nTime
int64_t llmq::CDKGDebugStatus::nTime {0}
Definition at line 81 of file quorums_debug.h.
Referenced by llmq::CDKGDebugManager::ResetLocalSessionStatus(), ToJson(), llmq::CDKGDebugManager::UpdateLocalMemberStatus(), and llmq::CDKGDebugManager::UpdateLocalSessionStatus().
sessions
std::map<Consensus::LLMQType, CDKGDebugSessionStatus> llmq::CDKGDebugStatus::sessions
Definition at line 83 of file quorums_debug.h.
Referenced by llmq::CDKGDebugManager::InitLocalSessionStatus(), llmq::CDKGDebugManager::ResetLocalSessionStatus(), ToJson(), llmq::CDKGDebugManager::UpdateLocalMemberStatus(), and llmq::CDKGDebugManager::UpdateLocalSessionStatus().
The documentation for this class was generated from the following files:
src/llmq/quorums_debug.h
src/llmq/quorums_debug.cpp
Released under the MIT license