Dash Core: NetEventsInterface Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
NetEventsInterface Class Reference abstract
Interface for message handling.
#include <net.h>
Public Member Functions
virtual bool ProcessMessages (CNode *pnode, std::atomic< bool > &interrupt)=0
virtual bool SendMessages (CNode *pnode, std::atomic< bool > &interrupt)=0
virtual void InitializeNode (CNode *pnode)=0
virtual void FinalizeNode (NodeId id, bool &update_connection_time)=0
Detailed Description
Interface for message handling.
Definition at line 665 of file net.h.
Member Function Documentation
FinalizeNode()
virtual void NetEventsInterface::FinalizeNode (NodeId id, bool & update_connection_time) pure virtual
Implemented in PeerLogicValidation.
Referenced by CConnman::DeleteNode().
InitializeNode()
virtual void NetEventsInterface::InitializeNode (CNode * pnode) pure virtual
Implemented in PeerLogicValidation.
Referenced by CConnman::AcceptConnection(), and CConnman::OpenNetworkConnection().
ProcessMessages()
virtual bool NetEventsInterface::ProcessMessages (CNode * pnode, std::atomic< bool > & interrupt) pure virtual
Implemented in PeerLogicValidation.
Referenced by CConnman::ThreadMessageHandler().
SendMessages()
virtual bool NetEventsInterface::SendMessages (CNode * pnode, std::atomic< bool > & interrupt) pure virtual
Implemented in PeerLogicValidation.
Referenced by CConnman::ThreadMessageHandler().
The documentation for this class was generated from the following file:
src/net.h
Released under the MIT license