Dash Core: AmountSpinBox Class Reference
AmountSpinBox Class Reference
Signals
void valueChanged ()
Public Member Functions
AmountSpinBox (QWidget *parent)
QValidator::State validate (QString &text, int &pos) const
void fixup (QString &input) const
CAmount value (bool *valid_out=0) const
void setValue (const CAmount &value)
void stepBy (int steps)
void setDisplayUnit (int unit)
void setSingleStep (const CAmount &step)
QSize minimumSizeHint () const
Protected Member Functions
bool event (QEvent *event)
StepEnabled stepEnabled () const
Private Member Functions
CAmount parse (const QString &text, bool *valid_out=0) const
Private Attributes
int currentUnit
CAmount singleStep
QSize cachedMinimumSizeHint
Detailed Description
QSpinBox that uses fixed-point numbers internally and uses our own formatting/parsing functions.
Definition at line 20 of file bitcoinamountfield.cpp.
Constructor & Destructor Documentation
AmountSpinBox()
AmountSpinBox::AmountSpinBox (QWidget * parent) inline explicit
Definition at line 25 of file bitcoinamountfield.cpp.
Member Function Documentation
event()
bool AmountSpinBox::event (QEvent * event) inline protected
Definition at line 152 of file bitcoinamountfield.cpp.
fixup()
void AmountSpinBox::fixup (QString & input) const inline
Definition at line 45 of file bitcoinamountfield.cpp.
minimumSizeHint()
QSize AmountSpinBox::minimumSizeHint () const inline
Definition at line 94 of file bitcoinamountfield.cpp.
parse()
CAmount AmountSpinBox::parse (const QString & text, bool * valid_out = 0) const inline private
Parse a string into a number of base monetary units and return validity.
Note
Must return 0 if !valid.
Definition at line 137 of file bitcoinamountfield.cpp.
Referenced by fixup(), validate(), and value().
setDisplayUnit()
void AmountSpinBox::setDisplayUnit (int unit) inline
Definition at line 76 of file bitcoinamountfield.cpp.
Referenced by BitcoinAmountField::unitChanged().
setSingleStep()
void AmountSpinBox::setSingleStep (const CAmount & step) inline
Definition at line 89 of file bitcoinamountfield.cpp.
Referenced by BitcoinAmountField::setSingleStep().
setValue()
void AmountSpinBox::setValue (const CAmount & value) inline
Definition at line 61 of file bitcoinamountfield.cpp.
Referenced by setDisplayUnit(), BitcoinAmountField::setValue(), and stepBy().
stepBy()
void AmountSpinBox::stepBy (int steps) inline
Definition at line 67 of file bitcoinamountfield.cpp.
stepEnabled()
StepEnabled AmountSpinBox::stepEnabled () const inline protected
Definition at line 167 of file bitcoinamountfield.cpp.
validate()
QValidator::State AmountSpinBox::validate (QString & text, int & pos) const inline
Definition at line 35 of file bitcoinamountfield.cpp.
value()
CAmount AmountSpinBox::value (bool * valid_out = 0) const inline
Definition at line 56 of file bitcoinamountfield.cpp.
Referenced by setDisplayUnit(), setValue(), stepBy(), stepEnabled(), and BitcoinAmountField::value().
valueChanged
void AmountSpinBox::valueChanged () signal
Referenced by AmountSpinBox(), and setValue().
Member Data Documentation
cachedMinimumSizeHint
QSize AmountSpinBox::cachedMinimumSizeHint mutable private
Definition at line 130 of file bitcoinamountfield.cpp.
Referenced by minimumSizeHint().
currentUnit
int AmountSpinBox::currentUnit private
Definition at line 128 of file bitcoinamountfield.cpp.
Referenced by fixup(), parse(), setDisplayUnit(), and setValue().
singleStep
CAmount AmountSpinBox::singleStep private
Definition at line 129 of file bitcoinamountfield.cpp.
Referenced by setSingleStep(), and stepBy().
The documentation for this class was generated from the following file:
src/qt/bitcoinamountfield.cpp