Dash Core: CDSNotificationInterface Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CDSNotificationInterface Class Reference
#include <dsnotificationinterface.h>
Public Member Functions
CDSNotificationInterface (CConnman &connmanIn)
virtual ~CDSNotificationInterface ()=default
void InitializeCurrentBlockTip ()
Protected Member Functions
void AcceptedBlockHeader (const CBlockIndex *pindexNew) override
void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload) override
void SynchronousUpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload) override
Same as UpdatedBlockTip, but called from the caller's thread.
void UpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload) override
Notifies listeners of updated block chain tip.
void TransactionAddedToMempool (const CTransactionRef &tx, int64_t nAcceptTime) override
Notifies listeners of a transaction having been added to mempool.
void BlockConnected (const std::shared_ptr< const CBlock > &pblock, const CBlockIndex *pindex, const std::vector< CTransactionRef > &vtxConflicted) override
Notifies listeners of a block being connected.
void BlockDisconnected (const std::shared_ptr< const CBlock > &pblock, const CBlockIndex *pindexDisconnected) override
Notifies listeners of a block being disconnected.
void NotifyMasternodeListChanged (bool undo, const CDeterministicMNList &oldMNList, const CDeterministicMNListDiff &diff) override
void NotifyChainLock (const CBlockIndex *pindex, const llmq::CChainLockSig &clsig) override
Protected Member Functions inherited from CValidationInterface
virtual void TransactionRemovedFromMempool (const CTransactionRef &ptx)
Notifies listeners of a transaction leaving mempool.
virtual void NotifyTransactionLock (const CTransaction &tx, const llmq::CInstantSendLock &islock)
virtual void NotifyGovernanceVote (const CGovernanceVote &vote)
virtual void NotifyGovernanceObject (const CGovernanceObject &object)
virtual void NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx)
virtual void SetBestChain (const CBlockLocator &locator)
Notifies listeners of the new active block chain on-disk.
virtual void ResendWalletTransactions (int64_t nBestBlockTime, CConnman *connman)
Tells listeners to broadcast their data.
virtual void BlockChecked (const CBlock &, const CValidationState &)
Notifies listeners of a block validation result.
virtual void NewPoWValidBlock (const CBlockIndex *pindex, const std::shared_ptr< const CBlock > &block)
Notifies listeners that a block which builds directly on our current tip has been received and connected to the headers tree, though not validated yet.
friend void ::RegisterValidationInterface (CValidationInterface *)
friend void ::UnregisterValidationInterface (CValidationInterface *)
friend void ::UnregisterAllValidationInterfaces ()
Private Attributes
CConnman & connman
Detailed Description
Definition at line 10 of file dsnotificationinterface.h.
Constructor & Destructor Documentation
CDSNotificationInterface()
CDSNotificationInterface::CDSNotificationInterface (CConnman & connmanIn) inline explicit
Definition at line 13 of file dsnotificationinterface.h.
~CDSNotificationInterface()
virtual CDSNotificationInterface::~CDSNotificationInterface () virtual default
Member Function Documentation
AcceptedBlockHeader()
void CDSNotificationInterface::AcceptedBlockHeader (const CBlockIndex * pindexNew) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 31 of file dsnotificationinterface.cpp.
References CMasternodeSync::AcceptedBlockHeader(), llmq::CChainLocksHandler::AcceptedBlockHeader(), llmq::chainLocksHandler, and masternodeSync.
BlockConnected()
void CDSNotificationInterface::BlockConnected (const std::shared_ptr< const CBlock > & block, const CBlockIndex * pindex, const std::vector< CTransactionRef > & txnConflicted) override protected virtual
Notifies listeners of a block being connected.
Provides a vector of transactions evicted from the mempool as a result.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 84 of file dsnotificationinterface.cpp.
References llmq::CChainLocksHandler::BlockConnected(), llmq::CInstantSendManager::BlockConnected(), CPrivateSend::BlockConnected(), llmq::chainLocksHandler, and llmq::quorumInstantSendManager.
BlockDisconnected()
void CDSNotificationInterface::BlockDisconnected (const std::shared_ptr< const CBlock > & block, const CBlockIndex * pindexDisconnected) override protected virtual
Notifies listeners of a block being disconnected.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 99 of file dsnotificationinterface.cpp.
References llmq::CChainLocksHandler::BlockDisconnected(), llmq::CInstantSendManager::BlockDisconnected(), CPrivateSend::BlockDisconnected(), llmq::chainLocksHandler, and llmq::quorumInstantSendManager.
InitializeCurrentBlockTip()
void CDSNotificationInterface::InitializeCurrentBlockTip ()
Definition at line 24 of file dsnotificationinterface.cpp.
References chainActive, cs_main, IsInitialBlockDownload(), LOCK, SynchronousUpdatedBlockTip(), CChain::Tip(), and UpdatedBlockTip().
Referenced by ThreadImport().
NotifyChainLock()
void CDSNotificationInterface::NotifyChainLock (const CBlockIndex * pindex, const llmq::CChainLockSig & clsig) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 112 of file dsnotificationinterface.cpp.
References llmq::CInstantSendManager::NotifyChainLock(), CPrivateSend::NotifyChainLock(), and llmq::quorumInstantSendManager.
NotifyHeaderTip()
void CDSNotificationInterface::NotifyHeaderTip (const CBlockIndex * pindexNew, bool fInitialDownload) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 37 of file dsnotificationinterface.cpp.
References connman, masternodeSync, and CMasternodeSync::NotifyHeaderTip().
NotifyMasternodeListChanged()
void CDSNotificationInterface::NotifyMasternodeListChanged (bool undo, const CDeterministicMNList & oldMNList, const CDeterministicMNListDiff & diff) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 106 of file dsnotificationinterface.cpp.
References governance, CMNAuth::NotifyMasternodeListChanged(), and CGovernanceManager::UpdateCachesAndClean().
SynchronousUpdatedBlockTip()
void CDSNotificationInterface::SynchronousUpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload) override protected virtual
Same as UpdatedBlockTip, but called from the caller's thread.
Reimplemented from CValidationInterface.
Definition at line 42 of file dsnotificationinterface.cpp.
References deterministicMNManager.
Referenced by InitializeCurrentBlockTip().
TransactionAddedToMempool()
void CDSNotificationInterface::TransactionAddedToMempool (const CTransactionRef & ptxn, int64_t nAcceptTime) override protected virtual
Notifies listeners of a transaction having been added to mempool.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 77 of file dsnotificationinterface.cpp.
References llmq::chainLocksHandler, llmq::quorumInstantSendManager, llmq::CChainLocksHandler::TransactionAddedToMempool(), llmq::CInstantSendManager::TransactionAddedToMempool(), and CPrivateSend::TransactionAddedToMempool().
UpdatedBlockTip()
void CDSNotificationInterface::UpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload) override protected virtual
Notifies listeners of updated block chain tip.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 50 of file dsnotificationinterface.cpp.
References llmq::chainLocksHandler, connman, Consensus::Params::DIP0001Height, fDIP0001ActiveAtTip, fDisableGovernance, CChainParams::GetConsensus(), governance, masternodeSync, CBlockIndex::nHeight, Params(), privateSendClient, llmq::quorumDKGSessionManager, llmq::quorumInstantSendManager, llmq::quorumManager, llmq::CDKGSessionManager::UpdatedBlockTip(), CMasternodeSync::UpdatedBlockTip(), llmq::CQuorumManager::UpdatedBlockTip(), llmq::CChainLocksHandler::UpdatedBlockTip(), llmq::CInstantSendManager::UpdatedBlockTip(), CPrivateSendClientManager::UpdatedBlockTip(), CGovernanceManager::UpdatedBlockTip(), and CPrivateSend::UpdatedBlockTip().
Referenced by InitializeCurrentBlockTip().
Member Data Documentation
connman
CConnman& CDSNotificationInterface::connman private
Definition at line 32 of file dsnotificationinterface.h.
Referenced by NotifyHeaderTip(), and UpdatedBlockTip().
The documentation for this class was generated from the following files:
src/dsnotificationinterface.h
src/dsnotificationinterface.cpp
Released under the MIT license