Dash Core: CHashWriter Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CHashWriter Class Reference
A writer stream (for serialization) that computes a 256-bit hash.
#include <hash.h>
Public Member Functions
CHashWriter (int nTypeIn, int nVersionIn)
int GetType () const
int GetVersion () const
void write (const char *pch, size_t size)
uint256 GetHash ()
template<typename T >
CHashWriter & operator<< (const T &obj)
Private Attributes
CHash256 ctx
const int nType
const int nVersion
Detailed Description
A writer stream (for serialization) that computes a 256-bit hash.
Definition at line 184 of file hash.h.
Constructor & Destructor Documentation
CHashWriter()
CHashWriter::CHashWriter (int nTypeIn, int nVersionIn) inline
Definition at line 193 of file hash.h.
Member Function Documentation
GetHash()
uint256 CHashWriter::GetHash () inline
Definition at line 203 of file hash.h.
References ctx, and CHash256::Finalize().
Referenced by llmq::CLLMQUtils::BuildCommitmentHash(), llmq::CLLMQUtils::BuildSignHash(), CSimplifiedMNListEntry::CalcHash(), CalcTxInputsHash(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::CBLSWrapper(), CGovernanceObject::GetHash(), llmq::CInstantSendLock::GetRequestId(), CSporkMessage::GetSignatureHash(), CSporkMessage::GetSignerKeyID(), llmq::CDKGContribution::GetSignHash(), GetUTXOStats(), llmq::MakeQuorumKey(), SignVerifyMessageDialog::on_signMessageButton_SM_clicked(), SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked(), llmq::CDKGPendingMessages::PushPendingMessage(), SerializeHash(), SignatureHash(), CMessageSigner::SignMessage(), signmessage(), signmessagewithprivkey(), CGovernanceVote::UpdateHash(), CBLSLazyWrapper< CBLSSignature >::UpdateHash(), CMessageSigner::VerifyMessage(), and verifymessage().
GetType()
int CHashWriter::GetType () const inline
Definition at line 195 of file hash.h.
References nType.
GetVersion()
int CHashWriter::GetVersion () const inline
Definition at line 196 of file hash.h.
References nVersion.
operator<<()
template<typename T > CHashWriter& CHashWriter::operator<< (const T & obj) inline
Definition at line 210 of file hash.h.
References Serialize().
write()
void CHashWriter::write (const char * pch, size_t size) inline
Definition at line 198 of file hash.h.
References ctx, and CHash256::Write().
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::CBLSWrapper(), llmq::CDKGPendingMessages::PushPendingMessage(), CHashVerifier< Source >::read(), and CBLSLazyWrapper< CBLSSignature >::UpdateHash().
Member Data Documentation
ctx
CHash256 CHashWriter::ctx private
Definition at line 187 of file hash.h.
Referenced by GetHash(), and write().
nType
const int CHashWriter::nType private
Definition at line 189 of file hash.h.
Referenced by GetType().
nVersion
const int CHashWriter::nVersion private
Definition at line 190 of file hash.h.
Referenced by GetVersion().
The documentation for this class was generated from the following file:
src/hash.h
Released under the MIT license