Dash Core: CZMQPublishHashGovernanceVoteNotifier Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CZMQPublishHashGovernanceVoteNotifier Class Reference
#include <zmqpublishnotifier.h>
Public Member Functions
bool NotifyGovernanceVote (const CGovernanceVote &vote) override
Public Member Functions inherited from CZMQAbstractPublishNotifier
bool SendMessage (const char *command, const void *data, size_t size)
bool Initialize (void *pcontext) override
void Shutdown () override
Public Member Functions inherited from CZMQAbstractNotifier
CZMQAbstractNotifier ()
virtual ~CZMQAbstractNotifier ()
std::string GetType () const
void SetType (const std::string &t)
std::string GetAddress () const
void SetAddress (const std::string &a)
virtual bool NotifyBlock (const CBlockIndex *pindex)
virtual bool NotifyChainLock (const CBlockIndex *pindex, const llmq::CChainLockSig &clsig)
virtual bool NotifyTransaction (const CTransaction &transaction)
virtual bool NotifyTransactionLock (const CTransaction &transaction, const llmq::CInstantSendLock &islock)
virtual bool NotifyGovernanceObject (const CGovernanceObject &object)
virtual bool NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx)
Additional Inherited Members
Static Public Member Functions inherited from CZMQAbstractNotifier
template<typename T >
static CZMQAbstractNotifier * Create ()
Protected Attributes inherited from CZMQAbstractNotifier
void * psocket
std::string type
std::string address
Detailed Description
Definition at line 57 of file zmqpublishnotifier.h.
Member Function Documentation
NotifyGovernanceVote()
bool CZMQPublishHashGovernanceVoteNotifier::NotifyGovernanceVote (const CGovernanceVote & vote) override virtual
Reimplemented from CZMQAbstractNotifier.
Definition at line 200 of file zmqpublishnotifier.cpp.
References base_blob< BITS >::begin(), CGovernanceVote::GetHash(), base_blob< BITS >::GetHex(), LogPrint, MSG_HASHGVOTE, CZMQAbstractPublishNotifier::SendMessage(), and BCLog::ZMQ.
The documentation for this class was generated from the following files:
src/zmq/zmqpublishnotifier.h
src/zmq/zmqpublishnotifier.cpp
Released under the MIT license