Dash Core: JSONUTF8StringFilter Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
JSONUTF8StringFilter Class Reference
#include <univalue_utffilter.h>
Public Member Functions
JSONUTF8StringFilter (std::string &s)
void push_back (unsigned char ch)
void push_back_u (unsigned int codepoint)
bool finalize ()
Private Member Functions
void append_codepoint (unsigned int codepoint)
Private Attributes
std::string & str
bool is_valid
unsigned int codepoint
int state
unsigned int surpair
Detailed Description
Definition at line 9 of file univalue_utffilter.h.
Constructor & Destructor Documentation
JSONUTF8StringFilter()
JSONUTF8StringFilter::JSONUTF8StringFilter (std::string & s) inline
Definition at line 12 of file univalue_utffilter.h.
Member Function Documentation
append_codepoint()
void JSONUTF8StringFilter::append_codepoint (unsigned int codepoint) inline private
Definition at line 94 of file univalue_utffilter.h.
References codepoint, and str.
Referenced by push_back_u().
finalize()
bool JSONUTF8StringFilter::finalize () inline
Definition at line 71 of file univalue_utffilter.h.
References is_valid, state, and surpair.
Referenced by getJsonToken().
push_back()
void JSONUTF8StringFilter::push_back (unsigned char ch) inline
Definition at line 17 of file univalue_utffilter.h.
References codepoint, is_valid, push_back_u(), state, and str.
Referenced by getJsonToken().
push_back_u()
void JSONUTF8StringFilter::push_back_u (unsigned int codepoint) inline
Definition at line 45 of file univalue_utffilter.h.
References append_codepoint(), codepoint, is_valid, state, and surpair.
Referenced by getJsonToken(), and push_back().
Member Data Documentation
codepoint
unsigned int JSONUTF8StringFilter::codepoint private
Definition at line 81 of file univalue_utffilter.h.
Referenced by append_codepoint(), push_back(), and push_back_u().
is_valid
bool JSONUTF8StringFilter::is_valid private
Definition at line 79 of file univalue_utffilter.h.
Referenced by finalize(), push_back(), and push_back_u().
state
int JSONUTF8StringFilter::state private
Definition at line 82 of file univalue_utffilter.h.
Referenced by finalize(), push_back(), and push_back_u().
str
std::string& JSONUTF8StringFilter::str private
Definition at line 78 of file univalue_utffilter.h.
Referenced by append_codepoint(), and push_back().
surpair
unsigned int JSONUTF8StringFilter::surpair private
Definition at line 92 of file univalue_utffilter.h.
Referenced by finalize(), and push_back_u().
The documentation for this class was generated from the following file:
src/univalue/lib/univalue_utffilter.h
Released under the MIT license