Dash Core: benchmark::BenchRunner Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
benchmark::BenchRunner Class Reference
#include <bench.h>
Public Member Functions
BenchRunner (std::string name, BenchFunction func)
Static Public Member Functions
static void RunAll (duration elapsedTimeForOne=std::chrono::seconds(1))
Private Types
typedef std::map< std::string, BenchFunction > BenchmarkMap
Static Private Member Functions
static BenchmarkMap & benchmarks ()
Detailed Description
Definition at line 79 of file bench.h.
Member Typedef Documentation
BenchmarkMap
typedef std::map<std::string, BenchFunction> benchmark::BenchRunner::BenchmarkMap private
Definition at line 81 of file bench.h.
Constructor & Destructor Documentation
BenchRunner()
benchmark::BenchRunner::BenchRunner (std::string name, benchmark::BenchFunction func)
Definition at line 17 of file bench.cpp.
References name.
Member Function Documentation
benchmarks()
benchmark::BenchRunner::BenchmarkMap & benchmark::BenchRunner::benchmarks () static private
Definition at line 12 of file bench.cpp.
RunAll()
void benchmark::BenchRunner::RunAll (benchmark::duration elapsedTimeForOne = std::chrono::seconds(1)) static
Definition at line 23 of file bench.cpp.
References perf_fini(), and perf_init().
Referenced by main().
The documentation for this class was generated from the following files:
src/bench/bench.h
src/bench/bench.cpp
Released under the MIT license