Dash Core: PlatformStyle Class Reference
PlatformStyle Class Reference
#include <platformstyle.h>
Public Member Functions
const QString & getName () const
bool getImagesOnButtons () const
bool getUseExtraSpacing () const
QColor TextColor () const
QColor SingleColor () const
QImage SingleColorImage (const QString &filename) const
QIcon SingleColorIcon (const QString &filename) const
QIcon SingleColorIcon (const QIcon &icon) const
QIcon TextColorIcon (const QString &filename) const
QIcon TextColorIcon (const QIcon &icon) const
Static Public Member Functions
static const PlatformStyle * instantiate (const QString &platformId)
Private Member Functions
PlatformStyle (const QString &name, bool imagesOnButtons, bool colorizeIcons, bool useExtraSpacing)
Private Attributes
QString name
bool imagesOnButtons
bool colorizeIcons
bool useExtraSpacing
QColor singleColor
QColor textColor
Detailed Description
Definition at line 13 of file platformstyle.h.
Constructor & Destructor Documentation
PlatformStyle()
PlatformStyle::PlatformStyle (const QString & name, bool imagesOnButtons, bool colorizeIcons, bool useExtraSpacing) private
Definition at line 76 of file platformstyle.cpp.
Referenced by instantiate().
Member Function Documentation
getImagesOnButtons()
bool PlatformStyle::getImagesOnButtons () const inline
Definition at line 21 of file platformstyle.h.
Referenced by AddressBookPage::AddressBookPage(), ReceiveCoinsDialog::ReceiveCoinsDialog(), RPCConsole::RPCConsole(), SendCoinsDialog::SendCoinsDialog(), and WalletView::WalletView().
getName()
const QString& PlatformStyle::getName () const inline
Definition at line 19 of file platformstyle.h.
Referenced by BitcoinApplication::initializeResult().
getUseExtraSpacing()
bool PlatformStyle::getUseExtraSpacing () const inline
Definition at line 22 of file platformstyle.h.
Referenced by SendCoinsEntry::SendCoinsEntry(), and TransactionView::TransactionView().
instantiate()
const PlatformStyle * PlatformStyle::instantiate (const QString & platformId) static
Get style associated with provided platform name, or 0 if not known
Definition at line 132 of file platformstyle.cpp.
Referenced by BitcoinApplication::BitcoinApplication().
SingleColor()
QColor PlatformStyle::SingleColor () const inline
Definition at line 25 of file platformstyle.h.
Referenced by SingleColorIcon(), SingleColorImage(), and UnitDisplayStatusBarControl::UnitDisplayStatusBarControl().
SingleColorIcon() [1/2]
QIcon PlatformStyle::SingleColorIcon (const QString & filename) const
Colorize an icon (given filename) with the icon color
Definition at line 108 of file platformstyle.cpp.
Referenced by TxViewDelegate::paint(), BitcoinGUI::setAdditionalDataSyncProgress(), BitcoinGUI::setNumBlocks(), and BitcoinGUI::updateNetworkState().
SingleColorIcon() [2/2]
QIcon PlatformStyle::SingleColorIcon (const QIcon & icon) const
Colorize an icon (given object) with the icon color
Definition at line 115 of file platformstyle.cpp.
SingleColorImage()
QImage PlatformStyle::SingleColorImage (const QString & filename) const
Colorize an image (given filename) with the icon color
Definition at line 101 of file platformstyle.cpp.
TextColor()
QColor PlatformStyle::TextColor () const inline
Definition at line 24 of file platformstyle.h.
Referenced by TextColorIcon().
TextColorIcon() [1/2]
QIcon PlatformStyle::TextColorIcon (const QString & filename) const
Colorize an icon (given filename) with the text color
Definition at line 122 of file platformstyle.cpp.
TextColorIcon() [2/2]
QIcon PlatformStyle::TextColorIcon (const QIcon & icon) const
Colorize an icon (given object) with the text color
Definition at line 127 of file platformstyle.cpp.
Member Data Documentation
colorizeIcons
bool PlatformStyle::colorizeIcons private
Definition at line 47 of file platformstyle.h.
Referenced by instantiate(), PlatformStyle(), SingleColorIcon(), and SingleColorImage().
imagesOnButtons
bool PlatformStyle::imagesOnButtons private
Definition at line 46 of file platformstyle.h.
Referenced by getImagesOnButtons(), and instantiate().
name
QString PlatformStyle::name private
Definition at line 45 of file platformstyle.h.
Referenced by getName().
singleColor
QColor PlatformStyle::singleColor private
Definition at line 49 of file platformstyle.h.
Referenced by PlatformStyle(), and SingleColor().
textColor
QColor PlatformStyle::textColor private
Definition at line 50 of file platformstyle.h.
Referenced by PlatformStyle(), and TextColor().
useExtraSpacing
bool PlatformStyle::useExtraSpacing private
Definition at line 48 of file platformstyle.h.
Referenced by getUseExtraSpacing(), and instantiate().
The documentation for this class was generated from the following files:
src/qt/platformstyle.h
src/qt/platformstyle.cpp