Dash Core: payments::Output Class Reference
payments::Output Class Reference
#include <paymentrequest.pb.h>
Public Member Functions
Output ()
virtual ~Output ()
Output (const Output &from)
Output & operator= (const Output &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline ::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (Output *other)
Output * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const Output &from)
void MergeFrom (const Output &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_amount () const
void clear_amount ()
inline ::google::protobuf::uint64 amount () const
void set_amount (::google::protobuf::uint64 value)
bool has_script () const
void clear_script ()
const ::std::string & script () const
void set_script (const ::std::string &value)
void set_script (const char *value)
void set_script (const void *value, size_t size)
inline ::std::string * mutable_script ()
inline ::std::string * release_script ()
void set_allocated_script (::std::string *script)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const Output & default_instance ()
Static Public Attributes
static const int kAmountFieldNumber = 1
static const int kScriptFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_amount ()
void clear_has_amount ()
void set_has_script ()
void clear_has_script ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint32 _has_bits_ [1]
int _cached_size_
::google::protobuf::uint64 amount_
::std::string * script_
Static Private Attributes
static Output * default_instance_ = NULL
Friends
void protobuf_AddDesc_paymentrequest_2eproto ()
void protobuf_AssignDesc_paymentrequest_2eproto ()
void protobuf_ShutdownFile_paymentrequest_2eproto ()
Detailed Description
Definition at line 45 of file paymentrequest.pb.h.
Constructor & Destructor Documentation
Output() [1/2]
payments::Output::Output ()
Definition at line 260 of file paymentrequest.pb.cc.
Referenced by New().
~Output()
payments::Output::~Output () virtual
Definition at line 284 of file paymentrequest.pb.cc.
Output() [2/2]
payments::Output::Output (const Output & from)
Definition at line 269 of file paymentrequest.pb.cc.
Member Function Documentation
amount()
google::protobuf::uint64 payments::Output::amount () const inline
Definition at line 772 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentRequestPlus::getPayTo(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
ByteSize()
int payments::Output::ByteSize () const
Definition at line 434 of file paymentrequest.pb.cc.
Clear()
void payments::Output::Clear ()
Definition at line 318 of file paymentrequest.pb.cc.
Referenced by CopyFrom().
clear_amount()
void payments::Output::clear_amount () inline
Definition at line 768 of file paymentrequest.pb.h.
clear_has_amount()
void payments::Output::clear_has_amount () inline private
Definition at line 765 of file paymentrequest.pb.h.
Referenced by clear_amount().
clear_has_script()
void payments::Output::clear_has_script () inline private
Definition at line 789 of file paymentrequest.pb.h.
Referenced by clear_script(), release_script(), and set_allocated_script().
clear_script()
void payments::Output::clear_script () inline
Definition at line 792 of file paymentrequest.pb.h.
CopyFrom() [1/2]
void payments::Output::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 489 of file paymentrequest.pb.cc.
Referenced by operator=().
CopyFrom() [2/2]
void payments::Output::CopyFrom (const Output & from)
Definition at line 495 of file paymentrequest.pb.cc.
default_instance()
const Output & payments::Output::default_instance () static
Definition at line 307 of file paymentrequest.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * payments::Output::descriptor () static
Definition at line 302 of file paymentrequest.pb.cc.
GetCachedSize()
int payments::Output::GetCachedSize () const inline
Definition at line 86 of file paymentrequest.pb.h.
GetMetadata()
google::protobuf::Metadata payments::Output::GetMetadata () const
Definition at line 517 of file paymentrequest.pb.cc.
has_amount()
bool payments::Output::has_amount () const inline
Definition at line 759 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_script()
bool payments::Output::has_script () const inline
Definition at line 783 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
InitAsDefaultInstance()
void payments::Output::InitAsDefaultInstance () private
Definition at line 266 of file paymentrequest.pb.cc.
Referenced by payments::protobuf_AddDesc_paymentrequest_2eproto().
IsInitialized()
bool payments::Output::IsInitialized () const
Definition at line 501 of file paymentrequest.pb.cc.
MergeFrom() [1/2]
void payments::Output::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 464 of file paymentrequest.pb.cc.
Referenced by CopyFrom(), and Output().
MergeFrom() [2/2]
void payments::Output::MergeFrom (const Output & from)
Definition at line 476 of file paymentrequest.pb.cc.
MergePartialFromCodedStream()
bool payments::Output::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 331 of file paymentrequest.pb.cc.
mutable_script()
std::string * payments::Output::mutable_script () inline
Definition at line 826 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_unknown_fields()
inline ::google::protobuf::UnknownFieldSet* payments::Output::mutable_unknown_fields () inline
Definition at line 61 of file paymentrequest.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
New()
Output * payments::Output::New () const
Definition at line 314 of file paymentrequest.pb.cc.
operator=()
Output& payments::Output::operator= (const Output & from) inline
Definition at line 52 of file paymentrequest.pb.h.
release_script()
std::string * payments::Output::release_script () inline
Definition at line 834 of file paymentrequest.pb.h.
script()
const ::std::string & payments::Output::script () const inline
Definition at line 798 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentRequestPlus::getPayTo(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_script().
SerializeWithCachedSizes()
void payments::Output::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 390 of file paymentrequest.pb.cc.
SerializeWithCachedSizesToArray()
google::protobuf::uint8 * payments::Output::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 411 of file paymentrequest.pb.cc.
set_allocated_script()
void payments::Output::set_allocated_script (::std::string * script) inline
Definition at line 844 of file paymentrequest.pb.h.
set_amount()
void payments::Output::set_amount (::google::protobuf::uint64 value) inline
Definition at line 776 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_has_amount()
void payments::Output::set_has_amount () inline private
Definition at line 762 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream(), and set_amount().
set_has_script()
void payments::Output::set_has_script () inline private
Definition at line 786 of file paymentrequest.pb.h.
Referenced by mutable_script(), set_allocated_script(), and set_script().
set_script() [1/3]
void payments::Output::set_script (const ::std::string & value) inline
Definition at line 802 of file paymentrequest.pb.h.
Referenced by PaymentServer::fetchPaymentACK(), and MergeFrom().
set_script() [2/3]
void payments::Output::set_script (const char * value) inline
Definition at line 810 of file paymentrequest.pb.h.
set_script() [3/3]
void payments::Output::set_script (const void * value, size_t size) inline
Definition at line 818 of file paymentrequest.pb.h.
SetCachedSize()
void payments::Output::SetCachedSize (int size) const private
Definition at line 297 of file paymentrequest.pb.cc.
SharedCtor()
void payments::Output::SharedCtor () private
Definition at line 276 of file paymentrequest.pb.cc.
Referenced by Output().
SharedDtor()
void payments::Output::SharedDtor () private
Definition at line 289 of file paymentrequest.pb.cc.
Referenced by ~Output().
Swap()
void payments::Output::Swap (Output * other)
Definition at line 507 of file paymentrequest.pb.cc.
unknown_fields()
const ::google::protobuf::UnknownFieldSet& payments::Output::unknown_fields () const inline
Definition at line 57 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
protobuf_AddDesc_paymentrequest_2eproto
void protobuf_AddDesc_paymentrequest_2eproto () friend
Definition at line 201 of file paymentrequest.pb.cc.
Referenced by default_instance().
protobuf_AssignDesc_paymentrequest_2eproto
void protobuf_AssignDesc_paymentrequest_2eproto () friend
Definition at line 45 of file paymentrequest.pb.cc.
protobuf_ShutdownFile_paymentrequest_2eproto
void protobuf_ShutdownFile_paymentrequest_2eproto () friend
Definition at line 184 of file paymentrequest.pb.cc.
Member Data Documentation
_cached_size_
int payments::Output::_cached_size_ mutable private
Definition at line 127 of file paymentrequest.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
_has_bits_
::google::protobuf::uint32 payments::Output::_has_bits_[1] private
Definition at line 126 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), clear_has_amount(), clear_has_script(), has_amount(), has_script(), IsInitialized(), MergeFrom(), set_has_amount(), set_has_script(), SharedCtor(), and Swap().
_unknown_fields_
::google::protobuf::UnknownFieldSet payments::Output::_unknown_fields_ private
Definition at line 124 of file paymentrequest.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
amount_
::google::protobuf::uint64 payments::Output::amount_ private
Definition at line 128 of file paymentrequest.pb.h.
Referenced by amount(), Clear(), clear_amount(), MergePartialFromCodedStream(), set_amount(), SharedCtor(), and Swap().
default_instance_
Output * payments::Output::default_instance_ = NULL static private
Definition at line 135 of file paymentrequest.pb.h.
Referenced by default_instance(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_AssignDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), and SharedDtor().
kAmountFieldNumber
const int payments::Output::kAmountFieldNumber = 1 static
Definition at line 101 of file paymentrequest.pb.h.
kScriptFieldNumber
const int payments::Output::kScriptFieldNumber = 2 static
Definition at line 108 of file paymentrequest.pb.h.
script_
::std::string* payments::Output::script_ private
Definition at line 129 of file paymentrequest.pb.h.
Referenced by Clear(), clear_script(), mutable_script(), release_script(), script(), set_allocated_script(), set_script(), SharedCtor(), SharedDtor(), and Swap().
The documentation for this class was generated from the following files:
src/qt/paymentrequest.pb.h
src/qt/paymentrequest.pb.cc