Dash Core: DefaultRequestHandler Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
DefaultRequestHandler Class Reference
Process default single requests.
Public Member Functions
UniValue PrepareRequest (const std::string &method, const std::vector< std::string > &args) override
UniValue ProcessReply (const UniValue &reply) override
Detailed Description
Process default single requests.
Definition at line 283 of file dash-cli.cpp.
Member Function Documentation
PrepareRequest()
UniValue DefaultRequestHandler::PrepareRequest (const std::string & method, const std::vector< std::string > & args) inline override virtual
Implements BaseRequestHandler.
Definition at line 285 of file dash-cli.cpp.
References DEFAULT_NAMED, gArgs, ArgsManager::GetBoolArg(), JSONRPCRequestObj(), RPCConvertNamedValues(), and RPCConvertValues().
ProcessReply()
UniValue DefaultRequestHandler::ProcessReply (const UniValue & reply) inline override virtual
Implements BaseRequestHandler.
Definition at line 296 of file dash-cli.cpp.
References UniValue::get_obj().
The documentation for this class was generated from the following file:
src/dash-cli.cpp
Released under the MIT license