Dash Core: CHashVerifier< Source > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CHashVerifier< Source > Class Template Reference
Reads data from an underlying stream, while hashing the read data.
#include <hash.h>
Public Member Functions
CHashVerifier (Source *source_)
void read (char *pch, size_t nSize)
void ignore (size_t nSize)
template<typename T >
CHashVerifier< Source > & operator>> (T &obj)
Public Member Functions inherited from CHashWriter
CHashWriter (int nTypeIn, int nVersionIn)
int GetType () const
int GetVersion () const
void write (const char *pch, size_t size)
uint256 GetHash ()
template<typename T >
CHashWriter & operator<< (const T &obj)
Private Attributes
Source * source
Detailed Description
template<typename Source>
class CHashVerifier< Source >
Reads data from an underlying stream, while hashing the read data.
Definition at line 219 of file hash.h.
Constructor & Destructor Documentation
CHashVerifier()
template<typename Source> CHashVerifier< Source >::CHashVerifier (Source * source_) inline explicit
Definition at line 225 of file hash.h.
Member Function Documentation
ignore()
template<typename Source> void CHashVerifier< Source >::ignore (size_t nSize) inline
Definition at line 233 of file hash.h.
References CHashVerifier< Source >::read().
operator>>()
template<typename Source> template<typename T > CHashVerifier<Source>& CHashVerifier< Source >::operator>> (T & obj) inline
Definition at line 244 of file hash.h.
References Unserialize().
read()
template<typename Source> void CHashVerifier< Source >::read (char * pch, size_t nSize) inline
Definition at line 227 of file hash.h.
References CHashVerifier< Source >::source, and CHashWriter::write().
Referenced by CHashVerifier< Source >::ignore().
Member Data Documentation
source
template<typename Source> Source* CHashVerifier< Source >::source private
Definition at line 222 of file hash.h.
Referenced by CHashVerifier< Source >::read().
The documentation for this class was generated from the following file:
src/hash.h
Released under the MIT license