Dash Core: CBanDB Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CBanDB Class Reference
Access to the banlist database (banlist.dat)
#include <addrdb.h>
Public Member Functions
CBanDB ()
bool Write (const banmap_t &banSet)
bool Read (banmap_t &banSet)
Private Attributes
boost::filesystem::path pathBanlist
Detailed Description
Access to the banlist database (banlist.dat)
Definition at line 93 of file addrdb.h.
Constructor & Destructor Documentation
CBanDB()
CBanDB::CBanDB ()
Definition at line 19 of file addrdb.cpp.
References GetDataDir(), and pathBanlist.
Member Function Documentation
Read()
bool CBanDB::Read (banmap_t & banSet)
Definition at line 62 of file addrdb.cpp.
References CDataStream::begin(), CLIENT_VERSION, CDataStream::end(), error(), FLATDATA, Hash(), Params(), pathBanlist, and SER_DISK.
Referenced by CConnman::Start().
Write()
bool CBanDB::Write (const banmap_t & banSet)
Definition at line 24 of file addrdb.cpp.
References CDataStream::begin(), CLIENT_VERSION, CDataStream::end(), error(), FileCommit(), fileout, FLATDATA, GetDataDir(), GetRandBytes(), Hash(), Params(), pathBanlist, RenameOver(), SER_DISK, and strprintf.
Referenced by CConnman::DumpBanlist().
Member Data Documentation
pathBanlist
boost::filesystem::path CBanDB::pathBanlist private
Definition at line 96 of file addrdb.h.
Referenced by CBanDB(), Read(), and Write().
The documentation for this class was generated from the following files:
src/addrdb.h
src/addrdb.cpp
Released under the MIT license