Dash Core: BitcoinGUI Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
BitcoinGUI Class Reference
Bitcoin GUI main class.
#include <bitcoingui.h>
Classes
struct IncomingTransactionMessage
Public Slots
void setNumConnections (int count)
Set number of connections shown in the UI.
void setNetworkActive (bool networkActive)
Set network state shown in the UI.
void handleRestart (QStringList args)
Get restart command-line parameters and request restart.
void setNumBlocks (int count, const QDateTime &blockDate, const QString &blockHash, double nVerificationProgress, bool headers)
Set number of blocks and last block date shown in the UI.
void setAdditionalDataSyncProgress (double nSyncProgress)
Set additional data sync status shown in the UI.
void message (const QString &title, const QString &message, unsigned int style, bool *ret=nullptr)
Notify the user of an event from the core network or transaction handling code.
Signals
void receivedURI (const QString &uri)
Signal raised when a URI was entered or dragged to the GUI.
void requestedRestart (QStringList args)
Restart handling.
Public Member Functions
BitcoinGUI (const NetworkStyle *networkStyle, QWidget *parent=0)
~BitcoinGUI ()
void setClientModel (ClientModel *clientModel)
Set the client model.
Public Attributes
bool enableWallet
Static Public Attributes
static const QString DEFAULT_WALLET = "~Default"
Display name for default wallet name.
static const std::string DEFAULT_UIPLATFORM
Protected Member Functions
void changeEvent (QEvent *e)
void closeEvent (QCloseEvent *event)
void showEvent (QShowEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
bool eventFilter (QObject *object, QEvent *event)
Private Slots
void optionsClicked ()
Show configuration dialog.
void aboutClicked ()
Show about dialog.
void showDebugWindow ()
Show debug window.
void showInfo ()
Show debug window and set focus to the appropriate tab.
void showConsole ()
void showGraph ()
void showPeers ()
void showRepair ()
void showConfEditor ()
Open external (default) editor with dash.conf.
void showBackups ()
Show folder with wallet backups in default file browser.
void showHelpMessageClicked ()
Show help message dialog.
void showPrivateSendHelpClicked ()
Show PrivateSend help message dialog.
void trayIconActivated (QSystemTrayIcon::ActivationReason reason)
Handle tray icon clicked.
void showNormalIfMinimized (bool fToggleHidden=false)
Show window if hidden, unminimize when minimized, rise when obscured or show if hidden and fToggleHidden is true.
void toggleHidden ()
Simply calls showNormalIfMinimized(true) for use in SLOT() macro.
void detectShutdown ()
called by a timer to check if fRequestShutdown has been set
void showProgress (const QString &title, int nProgress)
Show progress dialog e.g.
void setTrayIconVisible (bool)
When hideTrayIcon setting is changed in OptionsModel hide or show the icon accordingly.
void toggleNetworkActive ()
Toggle networking.
void showModalOverlay ()
void updatePrivateSendVisibility ()
void updateWidth ()
Private Member Functions
void startSpinner ()
Start the spinner animation in the status bar if it's not running and if labelBlocksIcon is visible.
void stopSpinner ()
Stop the spinner animation in the status bar.
void startConnectingAnimation ()
Start the connecting animation.
void stopConnectingAnimation ()
Stop the connecting animation.
void createActions ()
Create the main UI actions.
void createMenuBar ()
Create the menu bar and sub-menus.
void createToolBars ()
Create the toolbars.
void createTrayIcon (const NetworkStyle *networkStyle)
Create system tray icon and notification.
void createIconMenu (QMenu *pmenu)
Create system tray menu (or setup the dock menu)
void setWalletActionsEnabled (bool enabled)
Enable or disable all wallet-related actions.
void subscribeToCoreSignals ()
Connect core signals to GUI client.
void unsubscribeFromCoreSignals ()
Disconnect core signals from GUI client.
void updateNetworkState ()
Update UI with latest network info from model.
void updateHeadersSyncProgressLabel ()
void updateProgressBarVisibility ()
void updateToolBarShortcuts ()
Private Attributes
ClientModel * clientModel
WalletFrame * walletFrame
UnitDisplayStatusBarControl * unitDisplayControl
QLabel * labelWalletEncryptionIcon
QLabel * labelWalletHDStatusIcon
QLabel * labelConnectionsIcon
QLabel * labelBlocksIcon
QLabel * progressBarLabel
QProgressBar * progressBar
QProgressDialog * progressDialog
QMenuBar * appMenuBar
QToolButton * overviewAction
QToolButton * historyAction
QToolButton * masternodeAction
QAction * quitAction
QToolButton * sendCoinsAction
QAction * sendCoinsMenuAction
QToolButton * privateSendCoinsAction
QAction * privateSendCoinsMenuAction
QAction * usedSendingAddressesAction
QAction * usedReceivingAddressesAction
QAction * signMessageAction
QAction * verifyMessageAction
QAction * aboutAction
QToolButton * receiveCoinsAction
QAction * receiveCoinsMenuAction
QAction * optionsAction
QAction * toggleHideAction
QAction * encryptWalletAction
QAction * backupWalletAction
QAction * changePassphraseAction
QAction * unlockWalletAction
QAction * lockWalletAction
QAction * aboutQtAction
QAction * openInfoAction
QAction * openRPCConsoleAction
QAction * openGraphAction
QAction * openPeersAction
QAction * openRepairAction
QAction * openConfEditorAction
QAction * showBackupsAction
QAction * openAction
QAction * showHelpMessageAction
QAction * showPrivateSendHelpAction
QSystemTrayIcon * trayIcon
QMenu * trayIconMenu
QMenu * dockIconMenu
Notificator * notificator
RPCConsole * rpcConsole
HelpMessageDialog * helpMessageDialog
ModalOverlay * modalOverlay
QButtonGroup * tabGroup
QTimer * timerSpinner
Timer to update the spinner animation in the status bar periodically.
QTimer * timerConnecting
Timer to update the connection icon during connecting phase.
std::list< IncomingTransactionMessage > incomingTransactions
QTimer * incomingTransactionsTimer
Detailed Description
Bitcoin GUI main class.
This class represents the main window of the Bitcoin UI. It communicates with both the client and wallet models to give the user an up-to-date view of the current core state.
Definition at line 49 of file bitcoingui.h.
Constructor & Destructor Documentation
BitcoinGUI()
BitcoinGUI::BitcoinGUI (const NetworkStyle * networkStyle, QWidget * parent = 0) explicit
Definition at line 83 of file bitcoingui.cpp.
References HelpMessageDialog::cmdline, createActions(), createMenuBar(), createToolBars(), createTrayIcon(), enableWallet, gArgs, ArgsManager::GetArg(), NetworkStyle::getTitleAddText(), NetworkStyle::getTrayAndWindowIcon(), helpMessageDialog, incomingTransactionsTimer, WalletModel::isWalletEnabled(), labelBlocksIcon, labelConnectionsIcon, labelWalletEncryptionIcon, labelWalletHDStatusIcon, modalOverlay, progressBar, progressBarLabel, rpcConsole, setWalletActionsEnabled(), showModalOverlay(), showPeers(), subscribeToCoreSignals(), unitDisplayControl, and walletFrame.
~BitcoinGUI()
BitcoinGUI::~BitcoinGUI ()
Definition at line 282 of file bitcoingui.cpp.
References appMenuBar, MacDockIconHandler::cleanup(), rpcConsole, tabGroup, trayIcon, and unsubscribeFromCoreSignals().
Member Function Documentation
aboutClicked
void BitcoinGUI::aboutClicked () private slot
Show about dialog.
Definition at line 927 of file bitcoingui.cpp.
References HelpMessageDialog::about, and clientModel.
Referenced by createActions().
changeEvent()
void BitcoinGUI::changeEvent (QEvent * e) protected
Definition at line 1441 of file bitcoingui.cpp.
References clientModel, GUIUtil::getIcon(), OptionsModel::getMinimizeToTray(), ClientModel::getOptionsModel(), GUIUtil::GREEN, CMasternodeSync::IsSynced(), labelBlocksIcon, masternodeSync, STATUSBAR_ICONSIZE, and updateNetworkState().
closeEvent()
void BitcoinGUI::closeEvent (QCloseEvent * event) protected
Definition at line 1474 of file bitcoingui.cpp.
References clientModel, OptionsModel::getMinimizeOnClose(), ClientModel::getOptionsModel(), and rpcConsole.
createActions()
void BitcoinGUI::createActions () private
Create the main UI actions.
Definition at line 383 of file bitcoingui.cpp.
References aboutAction, aboutClicked(), aboutQtAction, backupWalletAction, changePassphraseAction, encryptWalletAction, handleRestart(), historyAction, lockWalletAction, masternodeAction, GUIUtil::Normal, openAction, openConfEditorAction, openGraphAction, openInfoAction, openPeersAction, openRepairAction, openRPCConsoleAction, optionsAction, optionsClicked(), overviewAction, privateSendCoinsAction, privateSendCoinsMenuAction, quitAction, receiveCoinsAction, receiveCoinsMenuAction, rpcConsole, sendCoinsAction, sendCoinsMenuAction, GUIUtil::setFont(), showBackups(), showBackupsAction, showConfEditor(), showConsole(), showGraph(), showHelpMessageAction, showHelpMessageClicked(), showInfo(), showNormalIfMinimized(), showPeers(), showPrivateSendHelpAction, showPrivateSendHelpClicked(), showRepair(), signMessageAction, tabGroup, toggleHidden(), toggleHideAction, unlockWalletAction, GUIUtil::updateFonts(), usedReceivingAddressesAction, usedSendingAddressesAction, verifyMessageAction, and walletFrame.
Referenced by BitcoinGUI().
createIconMenu()
void BitcoinGUI::createIconMenu (QMenu * pmenu) private
Create system tray menu (or setup the dock menu)
Definition at line 868 of file bitcoingui.cpp.
References openConfEditorAction, openGraphAction, openInfoAction, openPeersAction, openRepairAction, openRPCConsoleAction, optionsAction, privateSendCoinsMenuAction, quitAction, receiveCoinsMenuAction, sendCoinsMenuAction, showBackupsAction, signMessageAction, toggleHideAction, and verifyMessageAction.
Referenced by setClientModel().
createMenuBar()
void BitcoinGUI::createMenuBar () private
Create the menu bar and sub-menus.
Definition at line 597 of file bitcoingui.cpp.
References aboutAction, aboutQtAction, appMenuBar, backupWalletAction, changePassphraseAction, encryptWalletAction, help(), lockWalletAction, openAction, openConfEditorAction, openGraphAction, openInfoAction, openPeersAction, openRepairAction, openRPCConsoleAction, optionsAction, quitAction, showBackupsAction, showHelpMessageAction, showPrivateSendHelpAction, signMessageAction, unlockWalletAction, usedReceivingAddressesAction, usedSendingAddressesAction, verifyMessageAction, and walletFrame.
Referenced by BitcoinGUI().
createToolBars()
void BitcoinGUI::createToolBars () private
Create the toolbars.
Definition at line 654 of file bitcoingui.cpp.
References historyAction, masternodeAction, overviewAction, privateSendCoinsAction, receiveCoinsAction, sendCoinsAction, and walletFrame.
Referenced by BitcoinGUI().
createTrayIcon()
void BitcoinGUI::createTrayIcon (const NetworkStyle * networkStyle) private
Create system tray icon and notification.
Definition at line 858 of file bitcoingui.cpp.
References NetworkStyle::getTitleAddText(), NetworkStyle::getTrayAndWindowIcon(), notificator, and trayIcon.
Referenced by BitcoinGUI().
detectShutdown
void BitcoinGUI::detectShutdown () private slot
called by a timer to check if fRequestShutdown has been set
Definition at line 1728 of file bitcoingui.cpp.
References rpcConsole, and ShutdownRequested().
dragEnterEvent()
void BitcoinGUI::dragEnterEvent (QDragEnterEvent * event) protected
Definition at line 1596 of file bitcoingui.cpp.
dropEvent()
void BitcoinGUI::dropEvent (QDropEvent * event) protected
Definition at line 1603 of file bitcoingui.cpp.
References receivedURI().
eventFilter()
bool BitcoinGUI::eventFilter (QObject * object, QEvent * event) protected
Definition at line 1615 of file bitcoingui.cpp.
References progressBar, and progressBarLabel.
handleRestart
void BitcoinGUI::handleRestart (QStringList args) slot
Get restart command-line parameters and request restart.
Definition at line 1814 of file bitcoingui.cpp.
References requestedRestart(), and ShutdownRequested().
Referenced by createActions().
message
void BitcoinGUI::message (const QString & title, const QString & message, unsigned int style, bool * ret = nullptr) slot
Notify the user of an event from the core network or transaction handling code.
Parameters
[in] title the message box / notification title
[in] message the displayed text
[in] style modality and style definitions (icon and used buttons - buttons only for message boxes)
See also
CClientUIInterface::MessageBoxFlags
Parameters
[in] ret pointer to a bool that will be modified to whether Ok was clicked (modal only)
Definition at line 1381 of file bitcoingui.cpp.
References CClientUIInterface::BTN_MASK, Notificator::Critical, CClientUIInterface::ICON_ERROR, CClientUIInterface::ICON_WARNING, Notificator::Information, CClientUIInterface::MODAL, CClientUIInterface::MSG_ERROR, CClientUIInterface::MSG_INFORMATION, CClientUIInterface::MSG_WARNING, notificator, Notificator::notify(), showNormalIfMinimized(), and Notificator::Warning.
Referenced by setClientModel().
optionsClicked
void BitcoinGUI::optionsClicked () private slot
Show configuration dialog.
Definition at line 912 of file bitcoingui.cpp.
References OptionsDialog::appearanceChanged(), clientModel, enableWallet, ClientModel::getOptionsModel(), OptionsDialog::setModel(), updatePrivateSendVisibility(), and updateWidth().
Referenced by createActions().
receivedURI
void BitcoinGUI::receivedURI (const QString & uri) signal
Signal raised when a URI was entered or dragged to the GUI.
Referenced by dropEvent().
requestedRestart
void BitcoinGUI::requestedRestart (QStringList args) signal
Restart handling.
Referenced by handleRestart().
setAdditionalDataSyncProgress
void BitcoinGUI::setAdditionalDataSyncProgress (double nSyncProgress) slot
Set additional data sync status shown in the UI.
Definition at line 1325 of file bitcoingui.cpp.
References clientModel, GUIUtil::getIcon(), ClientModel::getLastBlockDate(), ClientModel::getLastBlockHash(), ClientModel::getNumBlocks(), ClientModel::getNumConnections(), CMasternodeSync::GetSyncStatus(), ClientModel::getVerificationProgress(), GUIUtil::GREEN, CMasternodeSync::IsBlockchainSynced(), CMasternodeSync::IsSynced(), labelBlocksIcon, masternodeSync, progressBar, progressBarLabel, setNumBlocks(), WalletFrame::showOutOfSyncWarning(), startSpinner(), STATUSBAR_ICONSIZE, stopSpinner(), updateProgressBarVisibility(), and walletFrame.
Referenced by setClientModel(), setNumBlocks(), and updateNetworkState().
setClientModel()
void BitcoinGUI::setClientModel (ClientModel * clientModel)
Set the client model.
The client model represents the part of the core that communicates with the P2P network, and is wallet-agnostic.
Definition at line 705 of file bitcoingui.cpp.
References clientModel, createIconMenu(), dockIconMenu, ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), OptionsModel::getHideTrayIcon(), ClientModel::getLastBlockDate(), ClientModel::getLastBlockHash(), ClientModel::getNumBlocks(), ClientModel::getNumConnections(), ClientModel::getOptionsModel(), ClientModel::getVerificationProgress(), MacDockIconHandler::instance(), message(), modalOverlay, rpcConsole, setAdditionalDataSyncProgress(), WalletFrame::setClientModel(), RPCConsole::setClientModel(), ModalOverlay::setKnownBestHeight(), setNetworkActive(), setNumBlocks(), setNumConnections(), UnitDisplayStatusBarControl::setOptionsModel(), setTrayIconVisible(), showProgress(), toggleHideAction, trayIcon, trayIconActivated(), trayIconMenu, unitDisplayControl, updateNetworkState(), updatePrivateSendVisibility(), and walletFrame.
Referenced by BitcoinApplication::initializeResult(), and BitcoinApplication::requestShutdown().
setNetworkActive
void BitcoinGUI::setNetworkActive (bool networkActive) slot
Set network state shown in the UI.
Definition at line 1128 of file bitcoingui.cpp.
References updateNetworkState().
Referenced by setClientModel().
setNumBlocks
void BitcoinGUI::setNumBlocks (int count, const QDateTime & blockDate, const QString & blockHash, double nVerificationProgress, bool headers) slot
Set number of blocks and last block date shown in the UI.
Definition at line 1209 of file bitcoingui.cpp.
References BLOCK_SOURCE_DISK, BLOCK_SOURCE_NETWORK, BLOCK_SOURCE_NONE, BLOCK_SOURCE_REINDEX, clientModel, count, fDisableGovernance, GUIUtil::formatNiceTimeOffset(), CPrivateSendClientManager::fPrivateSendRunning, ClientModel::getBlockSource(), ModalOverlay::hideForever(), CMasternodeSync::IsBlockchainSynced(), CMasternodeSync::IsSynced(), labelBlocksIcon, masternodeSync, modalOverlay, privateSendClient, progressBar, progressBarLabel, setAdditionalDataSyncProgress(), ModalOverlay::setKnownBestHeight(), ModalOverlay::showHide(), WalletFrame::showOutOfSyncWarning(), ModalOverlay::tipUpdate(), updateHeadersSyncProgressLabel(), updateProgressBarVisibility(), and walletFrame.
Referenced by setAdditionalDataSyncProgress(), setClientModel(), and updateNetworkState().
setNumConnections
void BitcoinGUI::setNumConnections (int count) slot
Set number of connections shown in the UI.
Definition at line 1123 of file bitcoingui.cpp.
References updateNetworkState().
Referenced by setClientModel().
setTrayIconVisible
void BitcoinGUI::setTrayIconVisible (bool fHideTrayIcon) private slot
When hideTrayIcon setting is changed in OptionsModel hide or show the icon accordingly.
Definition at line 1761 of file bitcoingui.cpp.
References trayIcon.
Referenced by setClientModel().
setWalletActionsEnabled()
void BitcoinGUI::setWalletActionsEnabled (bool enabled) private
Enable or disable all wallet-related actions.
Definition at line 829 of file bitcoingui.cpp.
References backupWalletAction, changePassphraseAction, encryptWalletAction, CPrivateSendClientManager::fEnablePrivateSend, historyAction, masternodeAction, openAction, overviewAction, privateSendClient, privateSendCoinsAction, privateSendCoinsMenuAction, receiveCoinsAction, receiveCoinsMenuAction, sendCoinsAction, sendCoinsMenuAction, signMessageAction, usedReceivingAddressesAction, usedSendingAddressesAction, and verifyMessageAction.
Referenced by BitcoinGUI().
showBackups
void BitcoinGUI::showBackups () private slot
Show folder with wallet backups in default file browser.
Definition at line 976 of file bitcoingui.cpp.
References GUIUtil::showBackups().
Referenced by createActions().
showConfEditor
void BitcoinGUI::showConfEditor () private slot
Open external (default) editor with dash.conf.
Definition at line 971 of file bitcoingui.cpp.
References GUIUtil::openConfigfile().
Referenced by createActions().
showConsole
void BitcoinGUI::showConsole () private slot
Definition at line 947 of file bitcoingui.cpp.
References rpcConsole, RPCConsole::setTabFocus(), showDebugWindow(), and RPCConsole::TAB_CONSOLE.
Referenced by createActions().
showDebugWindow
void BitcoinGUI::showDebugWindow () private slot
Show debug window.
Definition at line 936 of file bitcoingui.cpp.
References GUIUtil::bringToFront(), and rpcConsole.
Referenced by showConsole(), showGraph(), showInfo(), showPeers(), and showRepair().
showEvent()
void BitcoinGUI::showEvent (QShowEvent * event) protected
Definition at line 1497 of file bitcoingui.cpp.
References aboutAction, openGraphAction, openInfoAction, openPeersAction, openRepairAction, openRPCConsoleAction, optionsAction, and updateWidth().
showGraph
void BitcoinGUI::showGraph () private slot
Definition at line 953 of file bitcoingui.cpp.
References rpcConsole, RPCConsole::setTabFocus(), showDebugWindow(), and RPCConsole::TAB_GRAPH.
Referenced by createActions().
showHelpMessageClicked
void BitcoinGUI::showHelpMessageClicked () private slot
Show help message dialog.
Definition at line 981 of file bitcoingui.cpp.
References helpMessageDialog.
Referenced by createActions().
showInfo
void BitcoinGUI::showInfo () private slot
Show debug window and set focus to the appropriate tab.
Definition at line 941 of file bitcoingui.cpp.
References rpcConsole, RPCConsole::setTabFocus(), showDebugWindow(), and RPCConsole::TAB_INFO.
Referenced by createActions().
showModalOverlay
void BitcoinGUI::showModalOverlay () private slot
Definition at line 1769 of file bitcoingui.cpp.
References ModalOverlay::isLayerVisible(), modalOverlay, progressBar, and ModalOverlay::toggleVisibility().
Referenced by BitcoinGUI().
showNormalIfMinimized
void BitcoinGUI::showNormalIfMinimized (bool fToggleHidden = false) private slot
Show window if hidden, unminimize when minimized, rise when obscured or show if hidden and fToggleHidden is true.
Definition at line 1711 of file bitcoingui.cpp.
References GUIUtil::bringToFront(), clientModel, and GUIUtil::isObscured().
Referenced by createActions(), message(), and toggleHidden().
showPeers
void BitcoinGUI::showPeers () private slot
Definition at line 959 of file bitcoingui.cpp.
References rpcConsole, RPCConsole::setTabFocus(), showDebugWindow(), and RPCConsole::TAB_PEERS.
Referenced by BitcoinGUI(), and createActions().
showPrivateSendHelpClicked
void BitcoinGUI::showPrivateSendHelpClicked () private slot
Show PrivateSend help message dialog.
Definition at line 986 of file bitcoingui.cpp.
References clientModel, and HelpMessageDialog::pshelp.
Referenced by createActions().
showProgress
void BitcoinGUI::showProgress (const QString & title, int nProgress) private slot
Show progress dialog e.g.
for verifychain
Definition at line 1738 of file bitcoingui.cpp.
References progressDialog.
Referenced by setClientModel().
showRepair
void BitcoinGUI::showRepair () private slot
Definition at line 965 of file bitcoingui.cpp.
References rpcConsole, RPCConsole::setTabFocus(), showDebugWindow(), and RPCConsole::TAB_REPAIR.
Referenced by createActions().
startConnectingAnimation()
void BitcoinGUI::startConnectingAnimation () private
Start the connecting animation.
Definition at line 340 of file bitcoingui.cpp.
References GUIUtil::getIcon(), GUIUtil::ICON_ALTERNATIVE_COLOR, labelConnectionsIcon, GUIUtil::ORANGE, STATUSBAR_ICONSIZE, and timerConnecting.
Referenced by updateNetworkState().
startSpinner()
void BitcoinGUI::startSpinner () private
Start the spinner animation in the status bar if it's not running and if labelBlocksIcon is visible.
Definition at line 301 of file bitcoingui.cpp.
References GUIUtil::getIcon(), labelBlocksIcon, MOVIES_PATH, GUIUtil::ORANGE, SPINNER_FRAMES, STATUSBAR_ICONSIZE, and timerSpinner.
Referenced by setAdditionalDataSyncProgress(), and updateNetworkState().
stopConnectingAnimation()
void BitcoinGUI::stopConnectingAnimation () private
Stop the connecting animation.
Definition at line 374 of file bitcoingui.cpp.
References timerConnecting.
Referenced by updateNetworkState().
stopSpinner()
void BitcoinGUI::stopSpinner () private
Stop the spinner animation in the status bar.
Definition at line 331 of file bitcoingui.cpp.
References timerSpinner.
Referenced by setAdditionalDataSyncProgress(), and updateNetworkState().
subscribeToCoreSignals()
void BitcoinGUI::subscribeToCoreSignals () private
Connect core signals to GUI client.
Definition at line 1792 of file bitcoingui.cpp.
References CClientUIInterface::ThreadSafeMessageBox, ThreadSafeMessageBox(), CClientUIInterface::ThreadSafeQuestion, and uiInterface.
Referenced by BitcoinGUI().
toggleHidden
void BitcoinGUI::toggleHidden () private slot
Simply calls showNormalIfMinimized(true) for use in SLOT() macro.
Definition at line 1723 of file bitcoingui.cpp.
References showNormalIfMinimized().
Referenced by createActions(), and trayIconActivated().
toggleNetworkActive
void BitcoinGUI::toggleNetworkActive () private slot
Toggle networking.
Definition at line 1806 of file bitcoingui.cpp.
References clientModel, ClientModel::getNetworkActive(), and ClientModel::setNetworkActive().
trayIconActivated
void BitcoinGUI::trayIconActivated (QSystemTrayIcon::ActivationReason reason) private slot
Handle tray icon clicked.
Definition at line 896 of file bitcoingui.cpp.
References toggleHidden().
Referenced by setClientModel().
unsubscribeFromCoreSignals()
void BitcoinGUI::unsubscribeFromCoreSignals () private
Disconnect core signals from GUI client.
Definition at line 1799 of file bitcoingui.cpp.
References CClientUIInterface::ThreadSafeMessageBox, ThreadSafeMessageBox(), CClientUIInterface::ThreadSafeQuestion, and uiInterface.
Referenced by ~BitcoinGUI().
updateHeadersSyncProgressLabel()
void BitcoinGUI::updateHeadersSyncProgressLabel () private
Definition at line 1133 of file bitcoingui.cpp.
References clientModel, CChainParams::GetConsensus(), ClientModel::getHeaderTipHeight(), ClientModel::getHeaderTipTime(), GetTime(), HEADER_HEIGHT_DELTA_SYNC, Consensus::Params::nPowTargetSpacing, Params(), and progressBarLabel.
Referenced by setNumBlocks().
updateNetworkState()
void BitcoinGUI::updateNetworkState () private
Update UI with latest network info from model.
Definition at line 1061 of file bitcoingui.cpp.
References clientModel, count, GUIUtil::getIcon(), ClientModel::getLastBlockDate(), ClientModel::getLastBlockHash(), ClientModel::getNetworkActive(), ClientModel::getNumBlocks(), ClientModel::getNumConnections(), ClientModel::getVerificationProgress(), GUIUtil::GREEN, GUIUtil::ICON_ALTERNATIVE_COLOR, CMasternodeSync::IsSynced(), labelBlocksIcon, labelConnectionsIcon, masternodeSync, GUIUtil::ORANGE, GUIUtil::RED, setAdditionalDataSyncProgress(), setNumBlocks(), startConnectingAnimation(), startSpinner(), STATUSBAR_ICONSIZE, stopConnectingAnimation(), stopSpinner(), and updateProgressBarVisibility().
Referenced by changeEvent(), setClientModel(), setNetworkActive(), and setNumConnections().
updatePrivateSendVisibility
void BitcoinGUI::updatePrivateSendVisibility () private slot
Definition at line 1157 of file bitcoingui.cpp.
References CPrivateSendClientManager::fEnablePrivateSend, privateSendClient, privateSendCoinsMenuAction, showPrivateSendHelpAction, updateToolBarShortcuts(), and updateWidth().
Referenced by optionsClicked(), and setClientModel().
updateProgressBarVisibility()
void BitcoinGUI::updateProgressBarVisibility () private
Definition at line 1142 of file bitcoingui.cpp.
References clientModel, ClientModel::getNetworkActive(), ClientModel::getNumConnections(), CMasternodeSync::IsSynced(), masternodeSync, progressBar, and progressBarLabel.
Referenced by setAdditionalDataSyncProgress(), setNumBlocks(), and updateNetworkState().
updateToolBarShortcuts()
void BitcoinGUI::updateToolBarShortcuts () private
Definition at line 1192 of file bitcoingui.cpp.
References tabGroup.
Referenced by updatePrivateSendVisibility().
updateWidth
void BitcoinGUI::updateWidth () private slot
Definition at line 1173 of file bitcoingui.cpp.
References tabGroup.
Referenced by optionsClicked(), showEvent(), and updatePrivateSendVisibility().
Member Data Documentation
aboutAction
QAction* BitcoinGUI::aboutAction private
Definition at line 113 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and showEvent().
aboutQtAction
QAction* BitcoinGUI::aboutQtAction private
Definition at line 123 of file bitcoingui.h.
Referenced by createActions(), and createMenuBar().
appMenuBar
QMenuBar* BitcoinGUI::appMenuBar private
Definition at line 100 of file bitcoingui.h.
Referenced by createMenuBar(), and ~BitcoinGUI().
backupWalletAction
QAction* BitcoinGUI::backupWalletAction private
Definition at line 119 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and setWalletActionsEnabled().
changePassphraseAction
QAction* BitcoinGUI::changePassphraseAction private
Definition at line 120 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and setWalletActionsEnabled().
clientModel
ClientModel* BitcoinGUI::clientModel private
Definition at line 88 of file bitcoingui.h.
Referenced by aboutClicked(), changeEvent(), closeEvent(), optionsClicked(), setAdditionalDataSyncProgress(), setClientModel(), setNumBlocks(), showNormalIfMinimized(), showPrivateSendHelpClicked(), toggleNetworkActive(), updateHeadersSyncProgressLabel(), updateNetworkState(), and updateProgressBarVisibility().
DEFAULT_UIPLATFORM
const std::string BitcoinGUI::DEFAULT_UIPLATFORM static
Initial value:
=
        "other"
Definition at line 55 of file bitcoingui.h.
Referenced by HelpMessageDialog::HelpMessageDialog(), BitcoinApplication::initializeResult(), and GUIUtil::loadStyleSheet().
DEFAULT_WALLET
const QString BitcoinGUI::DEFAULT_WALLET = "~Default" static
Display name for default wallet name.
Uses tilde to avoid name collisions in the future with additional wallets
Definition at line 54 of file bitcoingui.h.
Referenced by BitcoinApplication::initializeResult().
dockIconMenu
QMenu* BitcoinGUI::dockIconMenu private
Definition at line 137 of file bitcoingui.h.
Referenced by setClientModel().
enableWallet
bool BitcoinGUI::enableWallet
Definition at line 77 of file bitcoingui.h.
Referenced by BitcoinGUI(), and optionsClicked().
encryptWalletAction
QAction* BitcoinGUI::encryptWalletAction private
Definition at line 118 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and setWalletActionsEnabled().
helpMessageDialog
HelpMessageDialog* BitcoinGUI::helpMessageDialog private
Definition at line 140 of file bitcoingui.h.
Referenced by BitcoinGUI(), and showHelpMessageClicked().
historyAction
QToolButton* BitcoinGUI::historyAction private
Definition at line 102 of file bitcoingui.h.
Referenced by createActions(), createToolBars(), and setWalletActionsEnabled().
incomingTransactions
std::list<IncomingTransactionMessage> BitcoinGUI::incomingTransactions private
Definition at line 170 of file bitcoingui.h.
incomingTransactionsTimer
QTimer* BitcoinGUI::incomingTransactionsTimer private
Definition at line 171 of file bitcoingui.h.
Referenced by BitcoinGUI().
labelBlocksIcon
QLabel* BitcoinGUI::labelBlocksIcon private
Definition at line 95 of file bitcoingui.h.
Referenced by BitcoinGUI(), changeEvent(), setAdditionalDataSyncProgress(), setNumBlocks(), startSpinner(), and updateNetworkState().
labelConnectionsIcon
QLabel* BitcoinGUI::labelConnectionsIcon private
Definition at line 94 of file bitcoingui.h.
Referenced by BitcoinGUI(), startConnectingAnimation(), and updateNetworkState().
labelWalletEncryptionIcon
QLabel* BitcoinGUI::labelWalletEncryptionIcon private
Definition at line 92 of file bitcoingui.h.
Referenced by BitcoinGUI().
labelWalletHDStatusIcon
QLabel* BitcoinGUI::labelWalletHDStatusIcon private
Definition at line 93 of file bitcoingui.h.
Referenced by BitcoinGUI().
lockWalletAction
QAction* BitcoinGUI::lockWalletAction private
Definition at line 122 of file bitcoingui.h.
Referenced by createActions(), and createMenuBar().
masternodeAction
QToolButton* BitcoinGUI::masternodeAction private
Definition at line 103 of file bitcoingui.h.
Referenced by createActions(), createToolBars(), and setWalletActionsEnabled().
modalOverlay
ModalOverlay* BitcoinGUI::modalOverlay private
Definition at line 141 of file bitcoingui.h.
Referenced by BitcoinGUI(), setClientModel(), setNumBlocks(), and showModalOverlay().
notificator
Notificator* BitcoinGUI::notificator private
Definition at line 138 of file bitcoingui.h.
Referenced by createTrayIcon(), and message().
openAction
QAction* BitcoinGUI::openAction private
Definition at line 131 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and setWalletActionsEnabled().
openConfEditorAction
QAction* BitcoinGUI::openConfEditorAction private
Definition at line 129 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), and createMenuBar().
openGraphAction
QAction* BitcoinGUI::openGraphAction private
Definition at line 126 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and showEvent().
openInfoAction
QAction* BitcoinGUI::openInfoAction private
Definition at line 124 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and showEvent().
openPeersAction
QAction* BitcoinGUI::openPeersAction private
Definition at line 127 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and showEvent().
openRepairAction
QAction* BitcoinGUI::openRepairAction private
Definition at line 128 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and showEvent().
openRPCConsoleAction
QAction* BitcoinGUI::openRPCConsoleAction private
Definition at line 125 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and showEvent().
optionsAction
QAction* BitcoinGUI::optionsAction private
Definition at line 116 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and showEvent().
overviewAction
QToolButton* BitcoinGUI::overviewAction private
Definition at line 101 of file bitcoingui.h.
Referenced by createActions(), createToolBars(), and setWalletActionsEnabled().
privateSendCoinsAction
QToolButton* BitcoinGUI::privateSendCoinsAction private
Definition at line 107 of file bitcoingui.h.
Referenced by createActions(), createToolBars(), and setWalletActionsEnabled().
privateSendCoinsMenuAction
QAction* BitcoinGUI::privateSendCoinsMenuAction private
Definition at line 108 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), setWalletActionsEnabled(), and updatePrivateSendVisibility().
progressBar
QProgressBar* BitcoinGUI::progressBar private
Definition at line 97 of file bitcoingui.h.
Referenced by BitcoinGUI(), eventFilter(), setAdditionalDataSyncProgress(), setNumBlocks(), showModalOverlay(), and updateProgressBarVisibility().
progressBarLabel
QLabel* BitcoinGUI::progressBarLabel private
Definition at line 96 of file bitcoingui.h.
Referenced by BitcoinGUI(), eventFilter(), setAdditionalDataSyncProgress(), setNumBlocks(), updateHeadersSyncProgressLabel(), and updateProgressBarVisibility().
progressDialog
QProgressDialog* BitcoinGUI::progressDialog private
Definition at line 98 of file bitcoingui.h.
Referenced by showProgress().
quitAction
QAction* BitcoinGUI::quitAction private
Definition at line 104 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), and createMenuBar().
receiveCoinsAction
QToolButton* BitcoinGUI::receiveCoinsAction private
Definition at line 114 of file bitcoingui.h.
Referenced by createActions(), createToolBars(), and setWalletActionsEnabled().
receiveCoinsMenuAction
QAction* BitcoinGUI::receiveCoinsMenuAction private
Definition at line 115 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), and setWalletActionsEnabled().
rpcConsole
RPCConsole* BitcoinGUI::rpcConsole private
Definition at line 139 of file bitcoingui.h.
Referenced by BitcoinGUI(), closeEvent(), createActions(), detectShutdown(), setClientModel(), showConsole(), showDebugWindow(), showGraph(), showInfo(), showPeers(), showRepair(), and ~BitcoinGUI().
sendCoinsAction
QToolButton* BitcoinGUI::sendCoinsAction private
Definition at line 105 of file bitcoingui.h.
Referenced by createActions(), createToolBars(), and setWalletActionsEnabled().
sendCoinsMenuAction
QAction* BitcoinGUI::sendCoinsMenuAction private
Definition at line 106 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), and setWalletActionsEnabled().
showBackupsAction
QAction* BitcoinGUI::showBackupsAction private
Definition at line 130 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), and createMenuBar().
showHelpMessageAction
QAction* BitcoinGUI::showHelpMessageAction private
Definition at line 132 of file bitcoingui.h.
Referenced by createActions(), and createMenuBar().
showPrivateSendHelpAction
QAction* BitcoinGUI::showPrivateSendHelpAction private
Definition at line 133 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and updatePrivateSendVisibility().
signMessageAction
QAction* BitcoinGUI::signMessageAction private
Definition at line 111 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and setWalletActionsEnabled().
tabGroup
QButtonGroup* BitcoinGUI::tabGroup private
Definition at line 142 of file bitcoingui.h.
Referenced by createActions(), updateToolBarShortcuts(), updateWidth(), and ~BitcoinGUI().
timerConnecting
QTimer* BitcoinGUI::timerConnecting private
Timer to update the connection icon during connecting phase.
Definition at line 156 of file bitcoingui.h.
Referenced by startConnectingAnimation(), and stopConnectingAnimation().
timerSpinner
QTimer* BitcoinGUI::timerSpinner private
Timer to update the spinner animation in the status bar periodically.
Definition at line 149 of file bitcoingui.h.
Referenced by startSpinner(), and stopSpinner().
toggleHideAction
QAction* BitcoinGUI::toggleHideAction private
Definition at line 117 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), and setClientModel().
trayIcon
QSystemTrayIcon* BitcoinGUI::trayIcon private
Definition at line 135 of file bitcoingui.h.
Referenced by createTrayIcon(), setClientModel(), setTrayIconVisible(), and ~BitcoinGUI().
trayIconMenu
QMenu* BitcoinGUI::trayIconMenu private
Definition at line 136 of file bitcoingui.h.
Referenced by setClientModel().
unitDisplayControl
UnitDisplayStatusBarControl* BitcoinGUI::unitDisplayControl private
Definition at line 91 of file bitcoingui.h.
Referenced by BitcoinGUI(), and setClientModel().
unlockWalletAction
QAction* BitcoinGUI::unlockWalletAction private
Definition at line 121 of file bitcoingui.h.
Referenced by createActions(), and createMenuBar().
usedReceivingAddressesAction
QAction* BitcoinGUI::usedReceivingAddressesAction private
Definition at line 110 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and setWalletActionsEnabled().
usedSendingAddressesAction
QAction* BitcoinGUI::usedSendingAddressesAction private
Definition at line 109 of file bitcoingui.h.
Referenced by createActions(), createMenuBar(), and setWalletActionsEnabled().
verifyMessageAction
QAction* BitcoinGUI::verifyMessageAction private
Definition at line 112 of file bitcoingui.h.
Referenced by createActions(), createIconMenu(), createMenuBar(), and setWalletActionsEnabled().
walletFrame
WalletFrame* BitcoinGUI::walletFrame private
Definition at line 89 of file bitcoingui.h.
Referenced by BitcoinGUI(), createActions(), createMenuBar(), createToolBars(), setAdditionalDataSyncProgress(), setClientModel(), and setNumBlocks().
The documentation for this class was generated from the following files:
src/qt/bitcoingui.h
src/qt/bitcoingui.cpp
Released under the MIT license