Dash Core: OverviewPage Class Reference
OverviewPage Class Reference
#include <overviewpage.h>
Public Slots
void privateSendStatus ()
void setBalance (const CAmount &balance, const CAmount &unconfirmedBalance, const CAmount &immatureBalance, const CAmount &anonymizedBalance, const CAmount &watchOnlyBalance, const CAmount &watchUnconfBalance, const CAmount &watchImmatureBalance)
Signals
void transactionClicked (const QModelIndex &index)
void outOfSyncWarningClicked ()
Public Member Functions
OverviewPage (const PlatformStyle *platformStyle, QWidget *parent=0)
~OverviewPage ()
void setClientModel (ClientModel *clientModel)
void setWalletModel (WalletModel *walletModel)
void showOutOfSyncWarning (bool fShow)
Private Slots
void togglePrivateSend ()
void privateSendAuto ()
void privateSendReset ()
void privateSendInfo ()
void updateDisplayUnit ()
void updatePrivateSendProgress ()
void updateAdvancedPSUI (bool fShowAdvancedPSUI)
void handleTransactionClicked (const QModelIndex &index)
void updateAlerts (const QString &warnings)
void updateWatchOnlyLabels (bool showWatchOnly)
void handleOutOfSyncWarningClicks ()
Private Member Functions
void SetupTransactionList (int nNumItems)
void DisablePrivateSendCompletely ()
Private Attributes
QTimer * timer
Ui::OverviewPage * ui
ClientModel * clientModel
WalletModel * walletModel
CAmount currentBalance
CAmount currentUnconfirmedBalance
CAmount currentImmatureBalance
CAmount currentAnonymizedBalance
CAmount currentWatchOnlyBalance
CAmount currentWatchUnconfBalance
CAmount currentWatchImmatureBalance
int nDisplayUnit
bool fShowAdvancedPSUI
TxViewDelegate * txdelegate
std::unique_ptr< TransactionFilterProxy > filter
Detailed Description
Overview ("home") page widget
Definition at line 28 of file overviewpage.h.
Constructor & Destructor Documentation
OverviewPage()
OverviewPage::OverviewPage (const PlatformStyle * platformStyle, QWidget * parent = 0) explicit
Definition at line 124 of file overviewpage.cpp.
~OverviewPage()
OverviewPage::~OverviewPage ()
Definition at line 196 of file overviewpage.cpp.
Member Function Documentation
DisablePrivateSendCompletely()
void OverviewPage::DisablePrivateSendCompletely () private
Definition at line 668 of file overviewpage.cpp.
Referenced by OverviewPage(), and privateSendStatus().
handleOutOfSyncWarningClicks
void OverviewPage::handleOutOfSyncWarningClicks () private slot
Definition at line 191 of file overviewpage.cpp.
handleTransactionClicked
void OverviewPage::handleTransactionClicked (const QModelIndex & index) private slot
Definition at line 185 of file overviewpage.cpp.
Referenced by OverviewPage().
outOfSyncWarningClicked
void OverviewPage::outOfSyncWarningClicked () signal
Definition at line 217 of file moc_overviewpage.cpp.
Referenced by handleOutOfSyncWarningClicks().
privateSendAuto
void OverviewPage::privateSendAuto () private slot
Definition at line 575 of file overviewpage.cpp.
Referenced by setWalletModel().
privateSendInfo
void OverviewPage::privateSendInfo () private slot
Definition at line 587 of file overviewpage.cpp.
Referenced by setWalletModel().
privateSendReset
void OverviewPage::privateSendReset () private slot
Definition at line 579 of file overviewpage.cpp.
Referenced by setWalletModel().
privateSendStatus
void OverviewPage::privateSendStatus () slot
Definition at line 455 of file overviewpage.cpp.
Referenced by OverviewPage(), and ~OverviewPage().
setBalance
void OverviewPage::setBalance (const CAmount & balance, const CAmount & unconfirmedBalance, const CAmount & immatureBalance, const CAmount & anonymizedBalance, const CAmount & watchOnlyBalance, const CAmount & watchUnconfBalance, const CAmount & watchImmatureBalance) slot
Definition at line 202 of file overviewpage.cpp.
Referenced by setWalletModel(), and updateDisplayUnit().
setClientModel()
void OverviewPage::setClientModel (ClientModel * clientModel)
Definition at line 262 of file overviewpage.cpp.
Referenced by WalletView::setClientModel().
SetupTransactionList()
void OverviewPage::SetupTransactionList (int nNumItems) private
Definition at line 650 of file overviewpage.cpp.
Referenced by updateAdvancedPSUI().
setWalletModel()
void OverviewPage::setWalletModel (WalletModel * walletModel)
Definition at line 273 of file overviewpage.cpp.
Referenced by WalletView::setWalletModel().
showOutOfSyncWarning()
void OverviewPage::showOutOfSyncWarning (bool fShow)
Definition at line 323 of file overviewpage.cpp.
Referenced by OverviewPage(), and WalletView::showOutOfSyncWarning().
togglePrivateSend
void OverviewPage::togglePrivateSend () private slot
Definition at line 592 of file overviewpage.cpp.
Referenced by setWalletModel().
transactionClicked
void OverviewPage::transactionClicked (const QModelIndex & index) signal
Definition at line 210 of file moc_overviewpage.cpp.
Referenced by handleTransactionClicked().
updateAdvancedPSUI
void OverviewPage::updateAdvancedPSUI (bool fShowAdvancedPSUI) private slot
Definition at line 437 of file overviewpage.cpp.
Referenced by setWalletModel().
updateAlerts
void OverviewPage::updateAlerts (const QString & warnings) private slot
Definition at line 317 of file overviewpage.cpp.
Referenced by setClientModel().
updateDisplayUnit
void OverviewPage::updateDisplayUnit () private slot
Definition at line 301 of file overviewpage.cpp.
Referenced by setWalletModel().
updatePrivateSendProgress
void OverviewPage::updatePrivateSendProgress () private slot
Definition at line 330 of file overviewpage.cpp.
Referenced by privateSendStatus(), setBalance(), and setWalletModel().
updateWatchOnlyLabels
void OverviewPage::updateWatchOnlyLabels (bool showWatchOnly) private slot
Definition at line 242 of file overviewpage.cpp.
Referenced by setWalletModel().
Member Data Documentation
clientModel
ClientModel* OverviewPage::clientModel private
Definition at line 52 of file overviewpage.h.
Referenced by privateSendStatus(), and setClientModel().
currentAnonymizedBalance
CAmount OverviewPage::currentAnonymizedBalance private
Definition at line 57 of file overviewpage.h.
Referenced by setBalance(), updateDisplayUnit(), and updatePrivateSendProgress().
currentBalance
CAmount OverviewPage::currentBalance private
Definition at line 54 of file overviewpage.h.
Referenced by setBalance(), togglePrivateSend(), updateDisplayUnit(), and updatePrivateSendProgress().
currentImmatureBalance
CAmount OverviewPage::currentImmatureBalance private
Definition at line 56 of file overviewpage.h.
Referenced by setBalance(), and updateDisplayUnit().
currentUnconfirmedBalance
CAmount OverviewPage::currentUnconfirmedBalance private
Definition at line 55 of file overviewpage.h.
Referenced by setBalance(), and updateDisplayUnit().
currentWatchImmatureBalance
CAmount OverviewPage::currentWatchImmatureBalance private
Definition at line 60 of file overviewpage.h.
Referenced by setBalance(), and updateDisplayUnit().
currentWatchOnlyBalance
CAmount OverviewPage::currentWatchOnlyBalance private
Definition at line 58 of file overviewpage.h.
Referenced by setBalance(), and updateDisplayUnit().
currentWatchUnconfBalance
CAmount OverviewPage::currentWatchUnconfBalance private
Definition at line 59 of file overviewpage.h.
Referenced by setBalance(), and updateDisplayUnit().
filter
std::unique_ptr<TransactionFilterProxy> OverviewPage::filter private
Definition at line 65 of file overviewpage.h.
Referenced by handleTransactionClicked(), and SetupTransactionList().
fShowAdvancedPSUI
bool OverviewPage::fShowAdvancedPSUI private
Definition at line 62 of file overviewpage.h.
Referenced by privateSendStatus(), updateAdvancedPSUI(), and updatePrivateSendProgress().
nDisplayUnit
int OverviewPage::nDisplayUnit private
Definition at line 61 of file overviewpage.h.
Referenced by setBalance(), togglePrivateSend(), updateDisplayUnit(), and updatePrivateSendProgress().
timer
QTimer* OverviewPage::timer private
Definition at line 50 of file overviewpage.h.
Referenced by OverviewPage(), and ~OverviewPage().
txdelegate
TxViewDelegate* OverviewPage::txdelegate private
Definition at line 64 of file overviewpage.h.
Referenced by OverviewPage(), and updateDisplayUnit().
ui
Ui::OverviewPage* OverviewPage::ui private
Definition at line 51 of file overviewpage.h.
Referenced by DisablePrivateSendCompletely(), OverviewPage(), privateSendStatus(), setBalance(), SetupTransactionList(), setWalletModel(), showOutOfSyncWarning(), togglePrivateSend(), updateAdvancedPSUI(), updateAlerts(), updateDisplayUnit(), updatePrivateSendProgress(), updateWatchOnlyLabels(), and ~OverviewPage().
walletModel
WalletModel* OverviewPage::walletModel private
Definition at line 53 of file overviewpage.h.
Referenced by SetupTransactionList(), setWalletModel(), togglePrivateSend(), and updateDisplayUnit().
The documentation for this class was generated from the following files:
src/qt/overviewpage.h
src/qt/moc_overviewpage.cpp
src/qt/overviewpage.cpp