Dash Core: CSimplifiedMNList Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CSimplifiedMNList Class Reference
#include <simplifiedmns.h>
Public Member Functions
CSimplifiedMNList ()
CSimplifiedMNList (const std::vector< CSimplifiedMNListEntry > &smlEntries)
CSimplifiedMNList (const CDeterministicMNList &dmnList)
uint256 CalcMerkleRoot (bool *pmutated=nullptr) const
Public Attributes
std::vector< std::unique_ptr< CSimplifiedMNListEntry > > mnList
Detailed Description
Definition at line 74 of file simplifiedmns.h.
Constructor & Destructor Documentation
CSimplifiedMNList() [1/3]
CSimplifiedMNList::CSimplifiedMNList () inline
Definition at line 80 of file simplifiedmns.h.
CSimplifiedMNList() [2/3]
CSimplifiedMNList::CSimplifiedMNList (const std::vector< CSimplifiedMNListEntry > & smlEntries) explicit
Definition at line 55 of file simplifiedmns.cpp.
References mnList.
CSimplifiedMNList() [3/3]
CSimplifiedMNList::CSimplifiedMNList (const CDeterministicMNList & dmnList) explicit
Definition at line 67 of file simplifiedmns.cpp.
References CDeterministicMNList::ForEachMN(), CDeterministicMNList::GetAllMNsCount(), and mnList.
Member Function Documentation
CalcMerkleRoot()
uint256 CSimplifiedMNList::CalcMerkleRoot (bool * pmutated = nullptr) const
Definition at line 81 of file simplifiedmns.cpp.
References ComputeMerkleRoot(), and mnList.
Referenced by CalcCbTxMerkleRootMNList().
Member Data Documentation
mnList
std::vector<std::unique_ptr<CSimplifiedMNListEntry> > CSimplifiedMNList::mnList
Definition at line 77 of file simplifiedmns.h.
Referenced by CalcCbTxMerkleRootMNList(), CalcMerkleRoot(), and CSimplifiedMNList().
The documentation for this class was generated from the following files:
src/evo/simplifiedmns.h
src/evo/simplifiedmns.cpp
Released under the MIT license