Dash Core: OptionsDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
OptionsDialog Class Reference
Preferences dialog.
#include <optionsdialog.h>
Signals
void appearanceChanged ()
void proxyIpChecks (QValidatedLineEdit *pUiProxyIp, int nProxyPort)
Public Member Functions
OptionsDialog (QWidget *parent, bool enableWallet)
~OptionsDialog ()
void setModel (OptionsModel *model)
void setMapper ()
Private Slots
void showPage (int index)
custom tab buttons clicked
void setOkButtonState (bool fState)
void on_resetButton_clicked ()
void on_okButton_clicked ()
void on_cancelButton_clicked ()
void on_hideTrayIcon_stateChanged (int fState)
void showRestartWarning (bool fPersistent=false)
void clearStatusLabel ()
void updateProxyValidationState ()
void updateDefaultProxyNets ()
void updatePrivateSendVisibility ()
void updateWidth ()
Private Member Functions
void showEvent (QShowEvent *event) override
Private Attributes
Ui::OptionsDialog * ui
OptionsModel * model
QDataWidgetMapper * mapper
QButtonGroup pageButtons
QString previousTheme
AppearanceWidget * appearance
bool fPrivateSendEnabledPrev {false}
Detailed Description
Preferences dialog.
Definition at line 37 of file optionsdialog.h.
Constructor & Destructor Documentation
OptionsDialog()
OptionsDialog::OptionsDialog (QWidget * parent, bool enableWallet) explicit
check if the locale name consists of 2 parts (language_country)
display language strings as "language - country (locale name)", e.g. "German - Germany (de)"
display language strings as "language (locale name)", e.g. "German (de)"
Definition at line 34 of file optionsdialog.cpp.
References appearance, AppearanceWidget::appearanceChanged(), appearanceChanged(), GUIUtil::Bold, GUIUtil::disableMacFocusRect(), CPrivateSendClientManager::fEnablePrivateSend, fPrivateSendEnabledPrev, GetNumCores(), mapper, MAX_SCRIPTCHECK_THREADS, nMaxDbCache, nMinDbCache, pageButtons, privateSendClient, GUIUtil::setFont(), showPage(), ui, GUIUtil::updateFonts(), updatePrivateSendVisibility(), updateProxyValidationState(), and updateWidth().
~OptionsDialog()
OptionsDialog::~OptionsDialog ()
Definition at line 187 of file optionsdialog.cpp.
References ui.
Member Function Documentation
appearanceChanged
void OptionsDialog::appearanceChanged () signal
Referenced by BitcoinGUI::optionsClicked(), and OptionsDialog().
clearStatusLabel
void OptionsDialog::clearStatusLabel () private slot
Definition at line 395 of file optionsdialog.cpp.
References OptionsModel::isRestartRequired(), model, showRestartWarning(), and ui.
Referenced by showRestartWarning(), and updateProxyValidationState().
on_cancelButton_clicked
void OptionsDialog::on_cancelButton_clicked () private slot
Definition at line 360 of file optionsdialog.cpp.
on_hideTrayIcon_stateChanged
void OptionsDialog::on_hideTrayIcon_stateChanged (int fState) private slot
Definition at line 365 of file optionsdialog.cpp.
References ui.
on_okButton_clicked
void OptionsDialog::on_okButton_clicked () private slot
Definition at line 347 of file optionsdialog.cpp.
References AppearanceWidget::accept(), appearance, GetWallets(), HasWallets(), mapper, CPrivateSendClientManager::nCachedNumBlocks, privateSendClient, and updateDefaultProxyNets().
on_resetButton_clicked
void OptionsDialog::on_resetButton_clicked () private slot
Definition at line 328 of file optionsdialog.cpp.
References model, OptionsModel::Reset(), and OptionsModel::resetSettingsOnShutdown.
proxyIpChecks
void OptionsDialog::proxyIpChecks (QValidatedLineEdit * pUiProxyIp, int nProxyPort) signal
setMapper()
void OptionsDialog::setMapper ()
Definition at line 258 of file optionsdialog.cpp.
References OptionsModel::CoinControlFeatures, OptionsModel::DatabaseCache, OptionsModel::Digits, OptionsModel::DisplayUnit, OptionsModel::HideTrayIcon, OptionsModel::Language, OptionsModel::Listen, OptionsModel::LowKeysWarning, mapper, OptionsModel::MapPortUPnP, OptionsModel::MinimizeOnClose, OptionsModel::MinimizeToTray, OptionsModel::PrivateSendAmount, OptionsModel::PrivateSendEnabled, OptionsModel::PrivateSendMultiSession, OptionsModel::PrivateSendRounds, OptionsModel::ProxyIP, OptionsModel::ProxyIPTor, OptionsModel::ProxyPort, OptionsModel::ProxyPortTor, OptionsModel::ProxyUse, OptionsModel::ProxyUseTor, OptionsModel::ShowAdvancedPSUI, OptionsModel::ShowMasternodesTab, OptionsModel::ShowPrivateSendPopups, OptionsModel::SpendZeroConfChange, OptionsModel::StartAtStartup, OptionsModel::ThirdPartyTxUrls, OptionsModel::ThreadsScriptVerif, and ui.
Referenced by setModel().
setModel()
void OptionsDialog::setModel (OptionsModel * model)
Definition at line 192 of file optionsdialog.cpp.
References appearance, CPrivateSendClientManager::fEnablePrivateSend, OptionsModel::getOverriddenByCommandLine(), OptionsModel::isRestartRequired(), mapper, model, privateSendClient, setMapper(), AppearanceWidget::setModel(), showRestartWarning(), ui, updateDefaultProxyNets(), and updateWidth().
Referenced by BitcoinGUI::optionsClicked().
setOkButtonState
void OptionsDialog::setOkButtonState (bool fState) private slot
Definition at line 323 of file optionsdialog.cpp.
References ui.
Referenced by updateProxyValidationState().
showEvent()
void OptionsDialog::showEvent (QShowEvent * event) override private
Definition at line 470 of file optionsdialog.cpp.
References updateWidth().
showPage
void OptionsDialog::showPage (int index) private slot
custom tab buttons clicked
Definition at line 305 of file optionsdialog.cpp.
References GUIUtil::Bold, GUIUtil::Normal, pageButtons, GUIUtil::setFont(), ui, and GUIUtil::updateFonts().
Referenced by OptionsDialog().
showRestartWarning
void OptionsDialog::showRestartWarning (bool fPersistent = false) private slot
Definition at line 378 of file optionsdialog.cpp.
References clearStatusLabel(), GUIUtil::getThemedStyleQString(), GUIUtil::TS_ERROR, and ui.
Referenced by clearStatusLabel(), and setModel().
updateDefaultProxyNets
void OptionsDialog::updateDefaultProxyNets () private slot
Definition at line 420 of file optionsdialog.cpp.
References GetProxy(), NET_IPV4, NET_IPV6, NET_TOR, proxyType::proxy, CNetAddr::ToStringIP(), CService::ToStringPort(), and ui.
Referenced by on_okButton_clicked(), and setModel().
updatePrivateSendVisibility
void OptionsDialog::updatePrivateSendVisibility () private slot
Definition at line 442 of file optionsdialog.cpp.
References CPrivateSendClientManager::fEnablePrivateSend, privateSendClient, and ui.
Referenced by OptionsDialog().
updateProxyValidationState
void OptionsDialog::updateProxyValidationState () private slot
Definition at line 403 of file optionsdialog.cpp.
References clearStatusLabel(), GUIUtil::getThemedStyleQString(), QValidatedLineEdit::isValid(), setOkButtonState(), GUIUtil::TS_ERROR, and ui.
Referenced by OptionsDialog().
updateWidth
void OptionsDialog::updateWidth () private slot
Definition at line 452 of file optionsdialog.cpp.
References pageButtons.
Referenced by OptionsDialog(), setModel(), and showEvent().
Member Data Documentation
appearance
AppearanceWidget* OptionsDialog::appearance private
Definition at line 79 of file optionsdialog.h.
Referenced by on_okButton_clicked(), OptionsDialog(), and setModel().
fPrivateSendEnabledPrev
bool OptionsDialog::fPrivateSendEnabledPrev {false} private
Definition at line 80 of file optionsdialog.h.
Referenced by OptionsDialog().
mapper
QDataWidgetMapper* OptionsDialog::mapper private
Definition at line 76 of file optionsdialog.h.
Referenced by on_okButton_clicked(), OptionsDialog(), setMapper(), and setModel().
model
OptionsModel* OptionsDialog::model private
Definition at line 75 of file optionsdialog.h.
Referenced by clearStatusLabel(), on_resetButton_clicked(), and setModel().
pageButtons
QButtonGroup OptionsDialog::pageButtons private
Definition at line 77 of file optionsdialog.h.
Referenced by OptionsDialog(), showPage(), and updateWidth().
previousTheme
QString OptionsDialog::previousTheme private
Definition at line 78 of file optionsdialog.h.
ui
Ui::OptionsDialog* OptionsDialog::ui private
Definition at line 74 of file optionsdialog.h.
Referenced by clearStatusLabel(), on_hideTrayIcon_stateChanged(), OptionsDialog(), setMapper(), setModel(), setOkButtonState(), showPage(), showRestartWarning(), updateDefaultProxyNets(), updatePrivateSendVisibility(), updateProxyValidationState(), and ~OptionsDialog().
The documentation for this class was generated from the following files:
src/qt/optionsdialog.h
src/qt/optionsdialog.cpp
Released under the MIT license