Dash Core: CAutoBitSet Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CAutoBitSet Class Reference
Serializes either as a CFixedBitSet or CFixedVarIntsBitSet, depending on which would give a smaller size.
#include <serialize.h>
Public Member Functions
CAutoBitSet (std::vector< bool > &vecIn, size_t sizeIn)
template<typename Stream >
void Serialize (Stream &s) const
template<typename Stream >
void Unserialize (Stream &s)
Protected Attributes
std::vector< bool > & vec
size_t size
Detailed Description
Serializes either as a CFixedBitSet or CFixedVarIntsBitSet, depending on which would give a smaller size.
Definition at line 533 of file serialize.h.
Constructor & Destructor Documentation
CAutoBitSet()
CAutoBitSet::CAutoBitSet (std::vector< bool > & vecIn, size_t sizeIn) inline explicit
Definition at line 540 of file serialize.h.
Member Function Documentation
Serialize()
template<typename Stream > void CAutoBitSet::Serialize (Stream & s) const inline
Definition at line 543 of file serialize.h.
References FIXEDBITSET, FIXEDVARINTSBITSET, GetSerializeSize(), ser_writedata8(), size, and vec.
Unserialize()
template<typename Stream > void CAutoBitSet::Unserialize (Stream & s) inline
Definition at line 560 of file serialize.h.
References FIXEDBITSET, FIXEDVARINTSBITSET, ser_readdata8(), size, and vec.
Member Data Documentation
size
size_t CAutoBitSet::size protected
Definition at line 537 of file serialize.h.
Referenced by Serialize(), and Unserialize().
vec
std::vector<bool>& CAutoBitSet::vec protected
Definition at line 536 of file serialize.h.
Referenced by Serialize(), and Unserialize().
The documentation for this class was generated from the following file:
src/serialize.h
Released under the MIT license