Dash Core: NetworkStyle Class Reference
NetworkStyle Class Reference
#include <networkstyle.h>
Public Member Functions
const QString & getAppName () const
const QIcon & getAppIcon () const
const QPixmap & getSplashImage () const
const QIcon & getTrayAndWindowIcon () const
const QString & getTitleAddText () const
Static Public Member Functions
static const NetworkStyle * instantiate (const QString &networkId)
Private Member Functions
NetworkStyle (const QString &appName, const int iconColorHueShift, const int iconColorSaturationReduction, const char *titleAddText)
void rotateColors (QImage &img, const int iconColorHueShift, const int iconColorSaturationReduction)
Private Attributes
QString appName
QIcon appIcon
QPixmap splashImage
QIcon trayAndWindowIcon
QString titleAddText
Detailed Description
Definition at line 14 of file networkstyle.h.
Constructor & Destructor Documentation
NetworkStyle()
NetworkStyle::NetworkStyle (const QString & appName, const int iconColorHueShift, const int iconColorSaturationReduction, const char * titleAddText) private
Definition at line 61 of file networkstyle.cpp.
Referenced by instantiate().
Member Function Documentation
getAppIcon()
const QIcon& NetworkStyle::getAppIcon () const inline
Definition at line 21 of file networkstyle.h.
Referenced by BitcoinGUI::BitcoinGUI().
getAppName()
const QString& NetworkStyle::getAppName () const inline
Definition at line 20 of file networkstyle.h.
getSplashImage()
const QPixmap& NetworkStyle::getSplashImage () const inline
Definition at line 22 of file networkstyle.h.
getTitleAddText()
const QString& NetworkStyle::getTitleAddText () const inline
Definition at line 24 of file networkstyle.h.
Referenced by BitcoinGUI::BitcoinGUI(), BitcoinGUI::createTrayIcon(), and SplashScreen::SplashScreen().
getTrayAndWindowIcon()
const QIcon& NetworkStyle::getTrayAndWindowIcon () const inline
Definition at line 23 of file networkstyle.h.
Referenced by BitcoinGUI::BitcoinGUI(), and BitcoinGUI::createTrayIcon().
instantiate()
const NetworkStyle * NetworkStyle::instantiate (const QString & networkId) static
Get style associated with provided BIP70 network id, or 0 if not known
Definition at line 99 of file networkstyle.cpp.
Referenced by main().
rotateColors()
void NetworkStyle::rotateColors (QImage & img, const int iconColorHueShift, const int iconColorSaturationReduction) private
Definition at line 26 of file networkstyle.cpp.
Referenced by NetworkStyle().
Member Data Documentation
appIcon
QIcon NetworkStyle::appIcon private
Definition at line 30 of file networkstyle.h.
Referenced by getAppIcon(), and NetworkStyle().
appName
QString NetworkStyle::appName private
Definition at line 29 of file networkstyle.h.
Referenced by getAppName(), instantiate(), and NetworkStyle().
splashImage
QPixmap NetworkStyle::splashImage private
Definition at line 31 of file networkstyle.h.
Referenced by getSplashImage(), and NetworkStyle().
titleAddText
QString NetworkStyle::titleAddText private
Definition at line 33 of file networkstyle.h.
Referenced by getTitleAddText(), and instantiate().
trayAndWindowIcon
QIcon NetworkStyle::trayAndWindowIcon private
Definition at line 32 of file networkstyle.h.
Referenced by getTrayAndWindowIcon(), and NetworkStyle().
The documentation for this class was generated from the following files:
src/qt/networkstyle.h
src/qt/networkstyle.cpp