Dash Core: tinyformat::detail::FormatIterator Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
tinyformat::detail::FormatIterator Class Reference
#include <tinyformat.h>
Public Types
enum ExtraFormatFlags {
Flag_None = 0, Flag_TruncateToPrecision = 1<<0, Flag_SpacePadPositive = 1<<1, Flag_VariableWidth = 1<<2,
Flag_VariablePrecision = 1<<3
}
Public Member Functions
FormatIterator (std::ostream &out, const char *fmt)
void finish ()
~FormatIterator ()
template<typename T >
void accept (const T &value)
template<typename T >
TINYFORMAT_NOINLINE void accept (const T &value)
Private Member Functions
FormatIterator (const FormatIterator &)
FormatIterator & operator= (const FormatIterator &)
Static Private Member Functions
static int parseIntAndAdvance (const char *&c)
template<typename T >
static bool formatCStringTruncate (std::ostream &, const T &, std::streamsize)
static const char * printFormatStringLiteral (std::ostream &out, const char *fmt)
static const char * streamStateFromFormat (std::ostream &out, unsigned int &extraFlags, const char *fmtStart, int variableWidth, int variablePrecision)
Private Attributes
std::ostream & m_out
const char * m_fmt
unsigned int m_extraFlags
bool m_wantWidth
bool m_wantPrecision
int m_variableWidth
int m_variablePrecision
std::streamsize m_origWidth
std::streamsize m_origPrecision
std::ios::fmtflags m_origFlags
char m_origFill
Detailed Description
Definition at line 440 of file tinyformat.h.
Member Enumeration Documentation
ExtraFormatFlags
enum tinyformat::detail::FormatIterator::ExtraFormatFlags
Enumerator
Flag_None
Flag_TruncateToPrecision
Flag_SpacePadPositive
Flag_VariableWidth
Flag_VariablePrecision
Definition at line 444 of file tinyformat.h.
Constructor & Destructor Documentation
FormatIterator() [1/2]
tinyformat::detail::FormatIterator::FormatIterator (std::ostream & out, const char * fmt) inline
Definition at line 454 of file tinyformat.h.
~FormatIterator()
tinyformat::detail::FormatIterator::~FormatIterator () inline
Definition at line 478 of file tinyformat.h.
References m_origFill, m_origFlags, m_origPrecision, m_origWidth, and m_out.
FormatIterator() [2/2]
tinyformat::detail::FormatIterator::FormatIterator (const FormatIterator &) private
Member Function Documentation
accept() [1/2]
template<typename T > void tinyformat::detail::FormatIterator::accept (const T & value)
accept() [2/2]
template<typename T > TINYFORMAT_NOINLINE void tinyformat::detail::FormatIterator::accept (const T & value)
Definition at line 585 of file tinyformat.h.
References Flag_None, Flag_SpacePadPositive, Flag_TruncateToPrecision, Flag_VariablePrecision, Flag_VariableWidth, formatCStringTruncate(), tinyformat::formatValue(), tinyformat::detail::convertToInt< T, convertible >::invoke(), m_extraFlags, m_fmt, m_out, m_variablePrecision, m_variableWidth, m_wantPrecision, m_wantWidth, printFormatStringLiteral(), and streamStateFromFormat().
finish()
void tinyformat::detail::FormatIterator::finish () inline
Definition at line 469 of file tinyformat.h.
References m_fmt, m_out, printFormatStringLiteral(), and TINYFORMAT_ERROR.
Referenced by tinyformat::detail::format().
formatCStringTruncate()
template<typename T > static bool tinyformat::detail::FormatIterator::formatCStringTruncate (std::ostream & , const T & , std::streamsize) inline static private
Definition at line 505 of file tinyformat.h.
Referenced by accept().
operator=()
FormatIterator& tinyformat::detail::FormatIterator::operator= (const FormatIterator &) private
parseIntAndAdvance()
static int tinyformat::detail::FormatIterator::parseIntAndAdvance (const char *& c) inline static private
Definition at line 493 of file tinyformat.h.
Referenced by streamStateFromFormat().
printFormatStringLiteral()
static const char* tinyformat::detail::FormatIterator::printFormatStringLiteral (std::ostream & out, const char * fmt) inline static private
Definition at line 533 of file tinyformat.h.
Referenced by accept(), and finish().
streamStateFromFormat()
const char * tinyformat::detail::FormatIterator::streamStateFromFormat (std::ostream & out, unsigned int & extraFlags, const char * fmtStart, int variableWidth, int variablePrecision) inline static private
Definition at line 668 of file tinyformat.h.
References Flag_None, Flag_SpacePadPositive, Flag_TruncateToPrecision, Flag_VariablePrecision, Flag_VariableWidth, parseIntAndAdvance(), and TINYFORMAT_ERROR.
Referenced by accept().
Member Data Documentation
m_extraFlags
unsigned int tinyformat::detail::FormatIterator::m_extraFlags private
Definition at line 568 of file tinyformat.h.
Referenced by accept().
m_fmt
const char* tinyformat::detail::FormatIterator::m_fmt private
Definition at line 567 of file tinyformat.h.
Referenced by accept(), and finish().
m_origFill
char tinyformat::detail::FormatIterator::m_origFill private
Definition at line 578 of file tinyformat.h.
Referenced by ~FormatIterator().
m_origFlags
std::ios::fmtflags tinyformat::detail::FormatIterator::m_origFlags private
Definition at line 577 of file tinyformat.h.
Referenced by ~FormatIterator().
m_origPrecision
std::streamsize tinyformat::detail::FormatIterator::m_origPrecision private
Definition at line 576 of file tinyformat.h.
Referenced by ~FormatIterator().
m_origWidth
std::streamsize tinyformat::detail::FormatIterator::m_origWidth private
Definition at line 575 of file tinyformat.h.
Referenced by ~FormatIterator().
m_out
std::ostream& tinyformat::detail::FormatIterator::m_out private
Definition at line 566 of file tinyformat.h.
Referenced by accept(), finish(), and ~FormatIterator().
m_variablePrecision
int tinyformat::detail::FormatIterator::m_variablePrecision private
Definition at line 573 of file tinyformat.h.
Referenced by accept().
m_variableWidth
int tinyformat::detail::FormatIterator::m_variableWidth private
Definition at line 572 of file tinyformat.h.
Referenced by accept().
m_wantPrecision
bool tinyformat::detail::FormatIterator::m_wantPrecision private
Definition at line 571 of file tinyformat.h.
Referenced by accept().
m_wantWidth
bool tinyformat::detail::FormatIterator::m_wantWidth private
Definition at line 570 of file tinyformat.h.
Referenced by accept().
The documentation for this class was generated from the following file:
src/tinyformat.h
Released under the MIT license