Dash Core: COutPoint Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
COutPoint Class Reference
An outpoint - a combination of a transaction hash and an index n into its vout.
#include <transaction.h>
Public Member Functions
COutPoint ()
COutPoint (uint256 hashIn, uint32_t nIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
void SetNull ()
bool IsNull () const
std::string ToString () const
std::string ToStringShort () const
Public Attributes
uint256 hash
uint32_t n
ADD_SERIALIZE_METHODS
Friends
bool operator< (const COutPoint &a, const COutPoint &b)
bool operator== (const COutPoint &a, const COutPoint &b)
bool operator!= (const COutPoint &a, const COutPoint &b)
Detailed Description
An outpoint - a combination of a transaction hash and an index n into its vout.
Definition at line 15 of file transaction.h.
Constructor & Destructor Documentation
COutPoint() [1/2]
COutPoint::COutPoint () inline
Definition at line 21 of file transaction.h.
References SetNull().
COutPoint() [2/2]
COutPoint::COutPoint (uint256 hashIn, uint32_t nIn) inline
Definition at line 22 of file transaction.h.
References hash, and n.
Member Function Documentation
IsNull()
bool COutPoint::IsNull () const inline
Definition at line 33 of file transaction.h.
References hash, base_blob< BITS >::IsNull(), and n.
Referenced by CPrivateSendServer::AddEntry(), CheckTransaction(), and CTxIn::ToString().
SerializationOp()
template<typename Stream , typename Operation > void COutPoint::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 27 of file transaction.h.
References hash, n, and READWRITE.
SetNull()
void COutPoint::SetNull () inline
Definition at line 32 of file transaction.h.
References hash, n, and base_blob< BITS >::SetNull().
Referenced by COutPoint().
ToString()
std::string COutPoint::ToString () const
Definition at line 12 of file transaction.cpp.
References hash, n, strprintf, and base_blob< BITS >::ToString().
Referenced by CTxLockVote::CheckSignature(), and CTxIn::ToString().
ToStringShort()
std::string COutPoint::ToStringShort () const
Definition at line 17 of file transaction.cpp.
References hash, n, strprintf, and base_blob< BITS >::ToString().
Referenced by CMasternodeMan::AskForMN(), CMasternode::Check(), CMasternodePing::CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CMasternodeMan::CheckSameAddr(), CMasternodePing::CheckSignature(), CMasternodePaymentVote::CheckSignature(), CTxLockVote::CheckSignature(), CMasternodeMan::FindRandomNotInVec(), getpoolinfo(), CGovernanceObject::GetSignatureMessage(), gobject(), CGovernanceVote::IsValid(), CTxLockRequest::IsValid(), CMasternodePaymentVote::IsValid(), CTxLockVote::IsValid(), CGovernanceObject::IsValidLocally(), CPrivateSendClient::JoinExistingQueue(), masternode(), masternodebroadcast(), masternodelist(), CGovernanceManager::MasternodeRateCheck(), CMasternodePayments::ProcessBlock(), ProcessMessage(), CInstantSend::ProcessTxLockRequest(), CInstantSend::ProcessTxLockVote(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), CGovernanceObject::ProcessVote(), CGovernanceManager::ProcessVote(), CInstantSend::ResolveConflicts(), CActiveMasternode::SendMasternodePing(), CGovernanceVote::Sign(), CMasternodePaymentVote::Sign(), CTxLockVote::Sign(), CGovernanceObject::Sign(), CPrivateSendClient::SignFinalTransaction(), CMasternodePing::SimpleCheck(), CMasternodeBroadcast::SimpleCheck(), CPrivateSendClient::StartNewQueue(), CMasternodePaymentVote::ToString(), CDarksendQueue::ToString(), CMasternodeBroadcast::Update(), CMasternode::UpdateLastPaid(), CMasternodeMan::UpdateMasternodeList(), CInstantSend::Vote(), and voteraw().
Friends And Related Function Documentation
operator!=
bool operator!= (const COutPoint & a, const COutPoint & b) friend
Definition at line 45 of file transaction.h.
operator<
bool operator< (const COutPoint & a, const COutPoint & b) friend
Definition at line 35 of file transaction.h.
operator==
bool operator== (const COutPoint & a, const COutPoint & b) friend
Definition at line 40 of file transaction.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
COutPoint::ADD_SERIALIZE_METHODS
Definition at line 24 of file transaction.h.
hash
uint256 COutPoint::hash
Definition at line 18 of file transaction.h.
Referenced by CWallet::AbandonTransaction(), AcceptToMemoryPoolWorker(), CTxMemPool::addAddressIndex(), AddOrphanTx(), CTxMemPool::addSpentIndex(), CWallet::AddToWallet(), ApplyTxInUndo(), CTxMemPool::check(), CMasternodeBroadcast::CheckOutpoint(), CWallet::CommitTransaction(), ConnectBlock(), CWallet::ConvertList(), COutPoint(), DisconnectBlock(), EraseOrphanTx(), CTxMemPool::exists(), CWallet::GetAddressGroupings(), getblocktemplate(), CCoinsViewMemPool::GetCoin(), CWallet::GetDebit(), WalletModel::getOutputs(), CWallet::GetRealOutpointPrivateSendRounds(), GetUTXOStats(), CWallet::IsDenominated(), CMasternode::IsInputAssociatedWithPubkey(), CWallet::IsMine(), IsNull(), WalletModel::isSpent(), CWalletTx::IsTrusted(), WalletModel::listCoins(), listlockunspent(), CWallet::LockCoin(), CWallet::MarkConflicted(), mempoolToJSON(), CompareInputBIP69::operator()(), CTxMemPool::removeForReorg(), CWallet::SelectCoins(), SerializationOp(), SetNull(), CWallet::SyncTransaction(), ToString(), ToStringShort(), CTxMemPool::TrimToSize(), TxInErrorToJSON(), TxToJSON(), TxToUniv(), and CWallet::UnlockCoin().
n
uint32_t COutPoint::n
Definition at line 19 of file transaction.h.
Referenced by AccessByTxid(), CTxMemPool::addAddressIndex(), CTxMemPool::addSpentIndex(), CTxMemPool::check(), ConnectBlock(), CWallet::ConvertList(), COutPoint(), DisconnectBlock(), CTxMemPool::exists(), CWallet::GetAddressGroupings(), CCoinsViewMemPool::GetCoin(), CWallet::GetDebit(), WalletModel::getOutputs(), CWallet::GetRealOutpointPrivateSendRounds(), GetUTXOStats(), CWallet::IsDenominated(), CWallet::IsMine(), IsNull(), WalletModel::isSpent(), CWalletTx::IsTrusted(), WalletModel::listCoins(), listlockunspent(), CompareInputBIP69::operator()(), CWallet::SelectCoins(), SerializationOp(), SetNull(), ToString(), ToStringShort(), TxInErrorToJSON(), TxToJSON(), TxToUniv(), and CCoinsViewDB::Upgrade().
The documentation for this class was generated from the following files:
src/primitives/transaction.h
src/primitives/transaction.cpp
Released under the MIT license