Dash Core: CDeterministicMN Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CDeterministicMN Class Reference
#include <deterministicmns.h>
Public Member Functions
CDeterministicMN ()=delete
CDeterministicMN (uint64_t _internalId)
CDeterministicMN (const CDeterministicMN &mn, uint64_t _internalId)
template<typename Stream >
CDeterministicMN (deserialize_type, Stream &s)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, bool oldFormat)
template<typename Stream >
void Serialize (Stream &s) const
template<typename Stream >
void Unserialize (Stream &s, bool oldFormat=false)
uint64_t GetInternalId () const
std::string ToString () const
void ToJson (UniValue &obj) const
Public Attributes
uint256 proTxHash
COutPoint collateralOutpoint
uint16_t nOperatorReward
CDeterministicMNStateCPtr pdmnState
Private Attributes
uint64_t internalId {std::numeric_limits<uint64_t>::max()}
Detailed Description
Definition at line 189 of file deterministicmns.h.
Constructor & Destructor Documentation
CDeterministicMN() [1/4]
CDeterministicMN::CDeterministicMN () delete
CDeterministicMN() [2/4]
CDeterministicMN::CDeterministicMN (uint64_t _internalId) inline
Definition at line 196 of file deterministicmns.h.
CDeterministicMN() [3/4]
CDeterministicMN::CDeterministicMN (const CDeterministicMN & mn, uint64_t _internalId) inline
Definition at line 202 of file deterministicmns.h.
References internalId.
CDeterministicMN() [4/4]
template<typename Stream > CDeterministicMN::CDeterministicMN (deserialize_type , Stream & s) inline
Definition at line 209 of file deterministicmns.h.
Member Function Documentation
GetInternalId()
uint64_t CDeterministicMN::GetInternalId () const
Definition at line 68 of file deterministicmns.cpp.
References internalId.
SerializationOp()
template<typename Stream , typename Operation > void CDeterministicMN::SerializationOp (Stream & s, Operation ser_action, bool oldFormat) inline
Definition at line 221 of file deterministicmns.h.
References collateralOutpoint, internalId, nOperatorReward, pdmnState, proTxHash, READWRITE, and VARINT.
Referenced by Unserialize().
Serialize()
template<typename Stream > void CDeterministicMN::Serialize (Stream & s) const inline
Definition at line 233 of file deterministicmns.h.
References NCONST_PTR().
ToJson()
void CDeterministicMN::ToJson (UniValue & obj) const
Definition at line 80 of file deterministicmns.cpp.
References UniValue::clear(), collateralOutpoint, EncodeDestination(), ExtractDestination(), GetUTXOCoin(), COutPoint::hash, COutPoint::n, nOperatorReward, Coin::out, Pair(), pdmnState, proTxHash, UniValue::push_back(), CTxOut::scriptPubKey, UniValue::setObject(), and base_blob< BITS >::ToString().
ToString()
std::string CDeterministicMN::ToString () const
Definition at line 75 of file deterministicmns.cpp.
References collateralOutpoint, nOperatorReward, pdmnState, proTxHash, strprintf, base_blob< BITS >::ToString(), and COutPoint::ToStringShort().
Unserialize()
template<typename Stream > void CDeterministicMN::Unserialize (Stream & s, bool oldFormat = false) inline
Definition at line 239 of file deterministicmns.h.
References SerializationOp().
Member Data Documentation
collateralOutpoint
COutPoint CDeterministicMN::collateralOutpoint
Definition at line 215 of file deterministicmns.h.
Referenced by SerializationOp(), ToJson(), and ToString().
internalId
uint64_t CDeterministicMN::internalId {std::numeric_limits<uint64_t>::max()} private
Definition at line 192 of file deterministicmns.h.
Referenced by CDeterministicMN(), GetInternalId(), and SerializationOp().
nOperatorReward
uint16_t CDeterministicMN::nOperatorReward
Definition at line 216 of file deterministicmns.h.
Referenced by SerializationOp(), ToJson(), and ToString().
pdmnState
CDeterministicMNStateCPtr CDeterministicMN::pdmnState
Definition at line 217 of file deterministicmns.h.
Referenced by CompareByLastPaid_GetHeight(), SerializationOp(), ToJson(), and ToString().
proTxHash
uint256 CDeterministicMN::proTxHash
Definition at line 214 of file deterministicmns.h.
Referenced by CompareByLastPaid(), SerializationOp(), ToJson(), and ToString().
The documentation for this class was generated from the following files:
src/evo/deterministicmns.h
src/evo/deterministicmns.cpp
Released under the MIT license