Dash Core: TransactionDesc Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
TransactionDesc Class Reference
Provide a human-readable extended HTML description of a transaction.
#include <transactiondesc.h>
Static Public Member Functions
static QString toHTML (CWallet *wallet, CWalletTx &wtx, TransactionRecord *rec, int unit)
Private Member Functions
TransactionDesc ()
Static Private Member Functions
static QString FormatTxStatus (const CWalletTx &wtx)
Detailed Description
Provide a human-readable extended HTML description of a transaction.
Definition at line 18 of file transactiondesc.h.
Constructor & Destructor Documentation
TransactionDesc()
TransactionDesc::TransactionDesc () inline private
Definition at line 26 of file transactiondesc.h.
Member Function Documentation
FormatTxStatus()
QString TransactionDesc::FormatTxStatus (const CWalletTx & wtx) static private
Definition at line 27 of file transactiondesc.cpp.
References AssertLockHeld, chainActive, CheckFinalTx(), cs_main, GUIUtil::dateTimeStr(), GetAdjustedTime(), CMerkleTx::GetDepthInMainChain(), CTransaction::GetHash(), CTxLockRequest::GetMaxSignatures(), CWalletTx::GetRequestCount(), CInstantSend::GetTransactionLockSignatures(), CInstantSend::HasTxLockRequest(), CChain::Height(), CWalletTx::InMempool(), instantsend, CMerkleTx::isAbandoned(), CInstantSend::IsLockedInstantSendTransaction(), CInstantSend::IsTxLockCandidateTimedOut(), LOCKTIME_THRESHOLD, CTransaction::nLockTime, and CWalletTx::nTimeReceived.
Referenced by toHTML().
toHTML()
QString TransactionDesc::toHTML (CWallet * wallet, CWalletTx & wtx, TransactionRecord * rec, int unit) static
Definition at line 74 of file transactiondesc.cpp.
References TransactionRecord::address, COINBASE_MATURITY, cs_main, CWallet::cs_wallet, GUIUtil::dateTimeStr(), ExtractDestination(), fDebug, BitcoinUnits::formatHtmlWithUnit(), TransactionRecord::formatSubTxId(), FormatTxStatus(), CBitcoinAddress::Get(), CMerkleTx::GetBlocksToMaturity(), PaymentServer::getCertStore(), CWalletTx::GetChange(), CCoinsViewCache::GetCoin(), CWalletTx::GetCredit(), CWallet::GetCredit(), CWalletTx::GetDebit(), CWallet::GetDebit(), CTransaction::GetHash(), PaymentRequestPlus::getMerchant(), CWalletTx::GetRequestCount(), CTransaction::GetTotalSize(), CWalletTx::GetTxTime(), CTransaction::GetValueOut(), GUIUtil::HtmlEscape(), TransactionRecord::idx, CTransaction::IsCoinBase(), CMerkleTx::IsInMainChain(), IsMine(), CWallet::IsMine(), ISMINE_ALL, ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, CBitcoinAddress::IsValid(), LOCK2, CWallet::mapAddressBook, CWalletTx::mapValue, CTxOut::nValue, Coin::out, PAIRTYPE, PaymentRequestPlus::parse(), pcoinsTip, CTxIn::prevout, CTxOut::scriptPubKey, CTransaction::ToString(), CTransaction::vin, CWalletTx::vOrderForm, CTransaction::vout, and wallet.
Referenced by TransactionTablePriv::describe().
The documentation for this class was generated from the following files:
src/qt/transactiondesc.h
src/qt/transactiondesc.cpp
Released under the MIT license