Dash Core: CPrivateSendBroadcastTx Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CPrivateSendBroadcastTx Class Reference
Helper class to store mixing transaction (tx) information.
#include <privatesend.h>
Public Member Functions
CPrivateSendBroadcastTx ()
CPrivateSendBroadcastTx (const CTransactionRef &_tx, COutPoint _outpoint, int64_t _sigTime)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
operator bool () const
uint256 GetSignatureHash () const
bool Sign ()
bool CheckSignature (const CBLSPublicKey &blsPubKey) const
void SetConfirmedHeight (int nConfirmedHeightIn)
bool IsExpired (const CBlockIndex *pindex)
bool IsValidStructure ()
Public Attributes
CTransactionRef tx
COutPoint masternodeOutpoint
std::vector< unsigned char > vchSig
int64_t sigTime
ADD_SERIALIZE_METHODS
Private Attributes
int nConfirmedHeight
Friends
bool operator== (const CPrivateSendBroadcastTx &a, const CPrivateSendBroadcastTx &b)
bool operator!= (const CPrivateSendBroadcastTx &a, const CPrivateSendBroadcastTx &b)
Detailed Description
Helper class to store mixing transaction (tx) information.
Definition at line 291 of file privatesend.h.
Constructor & Destructor Documentation
CPrivateSendBroadcastTx() [1/2]
CPrivateSendBroadcastTx::CPrivateSendBroadcastTx () inline
Definition at line 304 of file privatesend.h.
Referenced by operator bool().
CPrivateSendBroadcastTx() [2/2]
CPrivateSendBroadcastTx::CPrivateSendBroadcastTx (const CTransactionRef & _tx, COutPoint _outpoint, int64_t _sigTime) inline
Definition at line 313 of file privatesend.h.
Member Function Documentation
CheckSignature()
bool CPrivateSendBroadcastTx::CheckSignature (const CBLSPublicKey & blsPubKey) const
Definition at line 110 of file privatesend.cpp.
References GetSignatureHash(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), LogPrint, BCLog::PRIVATESEND, CBLSWrapper< ImplType, _SerSize, C >::SetBuf(), vchSig, and CBLSSignature::VerifyInsecure().
Referenced by ProcessMessage().
GetSignatureHash()
uint256 CPrivateSendBroadcastTx::GetSignatureHash () const
Definition at line 90 of file privatesend.cpp.
References SerializeHash().
Referenced by CheckSignature(), and Sign().
IsExpired()
bool CPrivateSendBroadcastTx::IsExpired (const CBlockIndex * pindex)
Definition at line 124 of file privatesend.cpp.
References llmq::chainLocksHandler, llmq::CChainLocksHandler::HasChainLock(), nConfirmedHeight, CBlockIndex::nHeight, and CBlockIndex::phashBlock.
IsValidStructure()
bool CPrivateSendBroadcastTx::IsValidStructure ()
Definition at line 132 of file privatesend.cpp.
References CPrivateSend::GetMaxPoolParticipants(), CPrivateSend::GetMinPoolParticipants(), CPrivateSend::IsDenominatedAmount(), PRIVATESEND_ENTRY_MAX_SIZE, and tx.
Referenced by ProcessMessage().
operator bool()
CPrivateSendBroadcastTx::operator bool () const inline explicit
Definition at line 343 of file privatesend.h.
References CPrivateSendBroadcastTx().
SerializationOp()
template<typename Stream , typename Operation > void CPrivateSendBroadcastTx::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 325 of file privatesend.h.
References masternodeOutpoint, READWRITE, SER_GETHASH, sigTime, tx, and vchSig.
SetConfirmedHeight()
void CPrivateSendBroadcastTx::SetConfirmedHeight (int nConfirmedHeightIn) inline
Definition at line 353 of file privatesend.h.
References nConfirmedHeight.
Sign()
bool CPrivateSendBroadcastTx::Sign ()
Definition at line 95 of file privatesend.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsKeyOperator, fMasternodeMode, CBLSWrapper< ImplType, _SerSize, C >::GetBuf(), GetSignatureHash(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), and vchSig.
Referenced by CPrivateSendServer::CommitFinalTransaction().
Friends And Related Function Documentation
operator!=
bool operator!= (const CPrivateSendBroadcastTx & a, const CPrivateSendBroadcastTx & b) friend
Definition at line 339 of file privatesend.h.
operator==
bool operator== (const CPrivateSendBroadcastTx & a, const CPrivateSendBroadcastTx & b) friend
Definition at line 335 of file privatesend.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CPrivateSendBroadcastTx::ADD_SERIALIZE_METHODS
Definition at line 322 of file privatesend.h.
masternodeOutpoint
COutPoint CPrivateSendBroadcastTx::masternodeOutpoint
Definition at line 300 of file privatesend.h.
Referenced by ProcessMessage(), and SerializationOp().
nConfirmedHeight
int CPrivateSendBroadcastTx::nConfirmedHeight private
Definition at line 296 of file privatesend.h.
Referenced by IsExpired(), and SetConfirmedHeight().
sigTime
int64_t CPrivateSendBroadcastTx::sigTime
Definition at line 302 of file privatesend.h.
Referenced by SerializationOp().
tx
CTransactionRef CPrivateSendBroadcastTx::tx
Definition at line 299 of file privatesend.h.
Referenced by CPrivateSend::AddDSTX(), IsValidStructure(), ProcessMessage(), and SerializationOp().
vchSig
std::vector<unsigned char> CPrivateSendBroadcastTx::vchSig
Definition at line 301 of file privatesend.h.
Referenced by CheckSignature(), SerializationOp(), and Sign().
The documentation for this class was generated from the following files:
src/privatesend/privatesend.h
src/privatesend/privatesend.cpp
Released under the MIT license