Dash Core: MacDockIconHandler Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
MacDockIconHandler Class Reference
macOS-specific Dock icon handler.
#include <macdockiconhandler.h>
Signals
void dockIconClicked ()
Static Public Member Functions
static MacDockIconHandler * instance ()
static void cleanup ()
Private Member Functions
MacDockIconHandler ()
Detailed Description
macOS-specific Dock icon handler.
Definition at line 12 of file macdockiconhandler.h.
Constructor & Destructor Documentation
MacDockIconHandler()
MacDockIconHandler::MacDockIconHandler () private
Definition at line 32 of file macdockiconhandler.mm.
References setupDockClickHandler().
Referenced by instance().
Member Function Documentation
cleanup()
void MacDockIconHandler::cleanup () static
Definition at line 44 of file macdockiconhandler.mm.
References s_instance.
Referenced by BitcoinGUI::~BitcoinGUI().
dockIconClicked
void MacDockIconHandler::dockIconClicked () signal
Referenced by dockClickHandler().
instance()
MacDockIconHandler * MacDockIconHandler::instance () static
Definition at line 37 of file macdockiconhandler.mm.
References MacDockIconHandler(), and s_instance.
Referenced by BitcoinGUI::setClientModel().
The documentation for this class was generated from the following files:
src/qt/macdockiconhandler.h
src/qt/macdockiconhandler.mm
Released under the MIT license