Dash Core: CKeyHolderStorage Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CKeyHolderStorage Class Reference
#include <privatesend-util.h>
Public Member Functions
CScript AddKey (CWallet *pwalletIn)
void KeepAll ()
void ReturnAll ()
Private Attributes
std::vector< std::unique_ptr< CKeyHolder > > storage
CCriticalSection cs_storage
Detailed Description
Definition at line 28 of file privatesend-util.h.
Member Function Documentation
AddKey()
CScript CKeyHolderStorage::AddKey (CWallet * pwalletIn)
Definition at line 41 of file privatesend-util.cpp.
References cs_storage, LOCK, LogPrintf, and storage.
Referenced by CPrivateSendClientSession::PrepareDenominate().
KeepAll()
void CKeyHolderStorage::KeepAll ()
Definition at line 52 of file privatesend-util.cpp.
References cs_storage, LOCK, LogPrintf, and storage.
Referenced by CPrivateSendClientSession::CompletedTransaction().
ReturnAll()
void CKeyHolderStorage::ReturnAll ()
Definition at line 69 of file privatesend-util.cpp.
References cs_storage, LOCK, LogPrintf, and storage.
Referenced by CPrivateSendClientSession::CheckTimeout(), CPrivateSendClientSession::CompletedTransaction(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientSession::PrepareDenominate(), CPrivateSendClientSession::ProcessPoolStateUpdate(), CPrivateSendClientSession::ResetPool(), CPrivateSendClientSession::SendDenominate(), and CPrivateSendClientSession::SignFinalTransaction().
Member Data Documentation
cs_storage
CCriticalSection CKeyHolderStorage::cs_storage mutable private
Definition at line 32 of file privatesend-util.h.
Referenced by AddKey(), KeepAll(), and ReturnAll().
storage
std::vector<std::unique_ptr<CKeyHolder> > CKeyHolderStorage::storage private
Definition at line 31 of file privatesend-util.h.
Referenced by AddKey(), KeepAll(), and ReturnAll().
The documentation for this class was generated from the following files:
src/privatesend/privatesend-util.h
src/privatesend/privatesend-util.cpp
Released under the MIT license