Dash Core: immer::dvektor< T, B, MemoryPolicy > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::dvektor< T, B, MemoryPolicy > Class Template Reference
#include <dvektor.hpp>
Public Types
using value_type = T
using reference = const T &
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using const_reference = const T &
using iterator = detail::dvektor::iterator< T, B, MemoryPolicy >
using const_iterator = iterator
using reverse_iterator = std::reverse_iterator< iterator >
Public Member Functions
dvektor ()=default
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
std::size_t size () const
bool empty () const
reference operator[] (size_type index) const
dvektor push_back (value_type value) const
dvektor assoc (std::size_t idx, value_type value) const
template<typename FnT >
dvektor update (std::size_t idx, FnT &&fn) const
Private Types
using impl_t = detail::dvektor::impl< T, B, MemoryPolicy >
Private Member Functions
dvektor (impl_t impl)
Private Attributes
impl_t impl_ = detail::dvektor::empty<T, B, MemoryPolicy>
Detailed Description
template<typename T, int B = 5, typename MemoryPolicy = default_memory_policy>
class immer::dvektor< T, B, MemoryPolicy >
Definition at line 19 of file dvektor.hpp.
Member Typedef Documentation
const_iterator
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::const_iterator = iterator
Definition at line 31 of file dvektor.hpp.
const_reference
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::const_reference = const T&
Definition at line 28 of file dvektor.hpp.
difference_type
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::difference_type = std::ptrdiff_t
Definition at line 27 of file dvektor.hpp.
impl_t
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::impl_t = detail::dvektor::impl<T, B, MemoryPolicy> private
Definition at line 21 of file dvektor.hpp.
iterator
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::iterator = detail::dvektor::iterator<T, B, MemoryPolicy>
Definition at line 30 of file dvektor.hpp.
reference
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::reference = const T&
Definition at line 25 of file dvektor.hpp.
reverse_iterator
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 32 of file dvektor.hpp.
size_type
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::size_type = std::size_t
Definition at line 26 of file dvektor.hpp.
value_type
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> using immer::dvektor< T, B, MemoryPolicy >::value_type = T
Definition at line 24 of file dvektor.hpp.
Constructor & Destructor Documentation
dvektor() [1/2]
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> immer::dvektor< T, B, MemoryPolicy >::dvektor () default
dvektor() [2/2]
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> immer::dvektor< T, B, MemoryPolicy >::dvektor (impl_t impl) inline private
Definition at line 59 of file dvektor.hpp.
Member Function Documentation
assoc()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> dvektor immer::dvektor< T, B, MemoryPolicy >::assoc (std::size_t idx, value_type value) const inline
Definition at line 51 of file dvektor.hpp.
References immer::detail::dvektor::impl< T, B, MP >::assoc(), and immer::dvektor< T, B, MemoryPolicy >::impl_.
begin()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> iterator immer::dvektor< T, B, MemoryPolicy >::begin () const inline
Definition at line 36 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::impl_.
Referenced by immer::dvektor< T, B, MemoryPolicy >::rend().
empty()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> bool immer::dvektor< T, B, MemoryPolicy >::empty () const inline
Definition at line 43 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::impl_, and immer::detail::dvektor::impl< T, B, MP >::size.
end()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> iterator immer::dvektor< T, B, MemoryPolicy >::end () const inline
Definition at line 37 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::impl_.
Referenced by immer::dvektor< T, B, MemoryPolicy >::rbegin().
operator[]()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> reference immer::dvektor< T, B, MemoryPolicy >::operator[] (size_type index) const inline
Definition at line 45 of file dvektor.hpp.
References immer::detail::dvektor::impl< T, B, MP >::get(), and immer::dvektor< T, B, MemoryPolicy >::impl_.
push_back()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> dvektor immer::dvektor< T, B, MemoryPolicy >::push_back (value_type value) const inline
Definition at line 48 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::impl_, and immer::detail::dvektor::impl< T, B, MP >::push_back().
rbegin()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> reverse_iterator immer::dvektor< T, B, MemoryPolicy >::rbegin () const inline
Definition at line 39 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::end().
rend()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> reverse_iterator immer::dvektor< T, B, MemoryPolicy >::rend () const inline
Definition at line 40 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::begin().
size()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> std::size_t immer::dvektor< T, B, MemoryPolicy >::size () const inline
Definition at line 42 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::impl_, and immer::detail::dvektor::impl< T, B, MP >::size.
update()
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> template<typename FnT > dvektor immer::dvektor< T, B, MemoryPolicy >::update (std::size_t idx, FnT && fn) const inline
Definition at line 55 of file dvektor.hpp.
References immer::dvektor< T, B, MemoryPolicy >::impl_, and immer::detail::dvektor::impl< T, B, MP >::update().
Member Data Documentation
impl_
template<typename T , int B = 5, typename MemoryPolicy = default_memory_policy> impl_t immer::dvektor< T, B, MemoryPolicy >::impl_ = detail::dvektor::empty<T, B, MemoryPolicy> private
Definition at line 60 of file dvektor.hpp.
Referenced by immer::dvektor< T, B, MemoryPolicy >::assoc(), immer::dvektor< T, B, MemoryPolicy >::begin(), immer::dvektor< T, B, MemoryPolicy >::empty(), immer::dvektor< T, B, MemoryPolicy >::end(), immer::dvektor< T, B, MemoryPolicy >::operator[](), immer::dvektor< T, B, MemoryPolicy >::push_back(), immer::dvektor< T, B, MemoryPolicy >::size(), and immer::dvektor< T, B, MemoryPolicy >::update().
The documentation for this class was generated from the following file:
src/immer/experimental/dvektor.hpp
Released under the MIT license