Dash Core: CGovernanceVoting Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CGovernanceVoting Class Reference
Governance Voting.
#include <governance-vote.h>
Static Public Member Functions
static vote_outcome_enum_t ConvertVoteOutcome (std::string strVoteOutcome)
static vote_signal_enum_t ConvertVoteSignal (std::string strVoteSignal)
static std::string ConvertOutcomeToString (vote_outcome_enum_t nOutcome)
static std::string ConvertSignalToString (vote_signal_enum_t nSignal)
Detailed Description
Governance Voting.
Static class for accessing governance data
Definition at line 75 of file governance-vote.h.
Member Function Documentation
ConvertOutcomeToString()
std::string CGovernanceVoting::ConvertOutcomeToString (vote_outcome_enum_t nOutcome) static
Definition at line 13 of file governance-vote.cpp.
References VOTE_OUTCOME_ABSTAIN, VOTE_OUTCOME_NO, VOTE_OUTCOME_NONE, and VOTE_OUTCOME_YES.
Referenced by CGovernanceVote::GetVoteString(), and CGovernanceVote::ToString().
ConvertSignalToString()
std::string CGovernanceVoting::ConvertSignalToString (vote_signal_enum_t nSignal) static
Definition at line 29 of file governance-vote.cpp.
References VOTE_SIGNAL_CUSTOM1, VOTE_SIGNAL_CUSTOM10, VOTE_SIGNAL_CUSTOM11, VOTE_SIGNAL_CUSTOM12, VOTE_SIGNAL_CUSTOM13, VOTE_SIGNAL_CUSTOM14, VOTE_SIGNAL_CUSTOM15, VOTE_SIGNAL_CUSTOM16, VOTE_SIGNAL_CUSTOM17, VOTE_SIGNAL_CUSTOM18, VOTE_SIGNAL_CUSTOM19, VOTE_SIGNAL_CUSTOM2, VOTE_SIGNAL_CUSTOM20, VOTE_SIGNAL_CUSTOM3, VOTE_SIGNAL_CUSTOM4, VOTE_SIGNAL_CUSTOM5, VOTE_SIGNAL_CUSTOM6, VOTE_SIGNAL_CUSTOM7, VOTE_SIGNAL_CUSTOM8, VOTE_SIGNAL_CUSTOM9, VOTE_SIGNAL_DELETE, VOTE_SIGNAL_ENDORSED, VOTE_SIGNAL_FUNDING, VOTE_SIGNAL_NONE, VOTE_SIGNAL_NOOP1, VOTE_SIGNAL_NOOP10, VOTE_SIGNAL_NOOP11, VOTE_SIGNAL_NOOP2, VOTE_SIGNAL_NOOP3, VOTE_SIGNAL_NOOP4, VOTE_SIGNAL_NOOP5, VOTE_SIGNAL_NOOP6, VOTE_SIGNAL_NOOP7, VOTE_SIGNAL_NOOP8, VOTE_SIGNAL_NOOP9, and VOTE_SIGNAL_VALID.
Referenced by CGovernanceObject::ProcessVote(), and CGovernanceVote::ToString().
ConvertVoteOutcome()
vote_outcome_enum_t CGovernanceVoting::ConvertVoteOutcome (std::string strVoteOutcome) static
Definition at line 148 of file governance-vote.cpp.
References VOTE_OUTCOME_ABSTAIN, VOTE_OUTCOME_NO, VOTE_OUTCOME_NONE, and VOTE_OUTCOME_YES.
Referenced by gobject(), and voteraw().
ConvertVoteSignal()
vote_signal_enum_t CGovernanceVoting::ConvertVoteSignal (std::string strVoteSignal) static
Definition at line 163 of file governance-vote.cpp.
References LogPrintf, VOTE_SIGNAL_CUSTOM20, VOTE_SIGNAL_DELETE, VOTE_SIGNAL_ENDORSED, VOTE_SIGNAL_FUNDING, VOTE_SIGNAL_NONE, and VOTE_SIGNAL_VALID.
Referenced by gobject(), and voteraw().
The documentation for this class was generated from the following files:
src/governance-vote.h
src/governance-vote.cpp
Released under the MIT license