Dash Core: CBLSPublicKey Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSPublicKey Class Reference
#include <bls.h>
Public Member Functions
CBLSPublicKey ()
void AggregateInsecure (const CBLSPublicKey &o)
bool PublicKeyShare (const std::vector< CBLSPublicKey > &mpk, const CBLSId &id)
bool DHKeyExchange (const CBLSSecretKey &sk, const CBLSPublicKey &pk)
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const C &r) const
bool operator!= (const C &r) const
Public Member Functions inherited from CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >
CBLSWrapper ()
CBLSWrapper (const CBLSWrapper &ref)=default
CBLSWrapper (CBLSWrapper &&ref)
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const CBLSPublicKey &r) const
bool operator!= (const CBLSPublicKey &r) const
bool IsValid () const
void SetBuf (const void *buf, size_t size)
void SetBuf (const T &buf)
void Reset ()
void GetBuf (void *buf, size_t size) const
void GetBuf (T &buf) const
const uint256 & GetHash () const
void UpdateHash () const
bool SetHexStr (const std::string &str)
void Serialize (CSizeComputer &s) const
void Serialize (Stream &s) const
void Unserialize (Stream &s, bool checkMalleable=true)
bool CheckMalleable (void *buf, size_t size) const
std::string ToString () const
Static Public Member Functions
static CBLSPublicKey AggregateInsecure (const std::vector< CBLSPublicKey > &pks)
Protected Member Functions
bool InternalSetBuf (const void *buf)
bool InternalGetBuf (void *buf) const
Protected Member Functions inherited from CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >
constexpr size_t GetSerSize () const
Friends
class CBLSSecretKey
class CBLSSignature
Additional Inherited Members
Static Public Attributes inherited from CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >
static const size_t SerSize
Protected Attributes inherited from CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >
bls::PublicKey impl
bool fValid
uint256 cachedHash
Detailed Description
Definition at line 263 of file bls.h.
Constructor & Destructor Documentation
CBLSPublicKey()
CBLSPublicKey::CBLSPublicKey () inline
Definition at line 273 of file bls.h.
Referenced by AggregateInsecure().
Member Function Documentation
AggregateInsecure() [1/2]
void CBLSPublicKey::AggregateInsecure (const CBLSPublicKey & o)
Definition at line 191 of file bls.cpp.
References CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::impl, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::IsValid(), and CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::UpdateHash().
Referenced by BLSPubKeyAggregate_Normal(), and CBLSBatchVerifier< SourceId, MessageId >::VerifyBatchInsecure().
AggregateInsecure() [2/2]
CBLSPublicKey CBLSPublicKey::AggregateInsecure (const std::vector< CBLSPublicKey > & pks) static
Definition at line 198 of file bls.cpp.
References CBLSPublicKey(), CBLSWrapper< ImplType, _SerSize, C >::fValid, CBLSWrapper< ImplType, _SerSize, C >::impl, and CBLSWrapper< ImplType, _SerSize, C >::UpdateHash().
DHKeyExchange()
bool CBLSPublicKey::DHKeyExchange (const CBLSSecretKey & sk, const CBLSPublicKey & pk)
Definition at line 247 of file bls.cpp.
References CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::fValid, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::impl, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), and CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::UpdateHash().
Referenced by CBLSIESEncryptedBlob::Decrypt(), CBLSIESMultiRecipientBlobs::Decrypt(), and CBLSIESEncryptedBlob::Encrypt().
InternalGetBuf()
bool CBLSPublicKey::InternalGetBuf (void * buf) const protected virtual
Implements CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >.
Definition at line 185 of file bls.cpp.
References CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::impl.
InternalSetBuf()
bool CBLSPublicKey::InternalSetBuf (const void * buf) protected virtual
Implements CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >.
Definition at line 175 of file bls.cpp.
References CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::impl.
operator!=()
bool CBLSWrapper< ImplType, _SerSize, C >::operator!= inline
Definition at line 89 of file bls.h.
operator=() [1/2]
CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= default
operator=() [2/2]
CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= inline
Definition at line 77 of file bls.h.
operator==()
bool CBLSWrapper< ImplType, _SerSize, C >::operator== inline
Definition at line 85 of file bls.h.
PublicKeyShare()
bool CBLSPublicKey::PublicKeyShare (const std::vector< CBLSPublicKey > & mpk, const CBLSId & id)
Definition at line 218 of file bls.cpp.
References base_blob< BITS >::begin(), CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::fValid, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::impl, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), and CBLSWrapper< bls::PublicKey, BLS_CURVE_PUBKEY_SIZE, CBLSPublicKey >::UpdateHash().
Referenced by CBLSWorker::AsyncVerifyContributionShare(), CBLSWorker::BuildPubKeyShare(), ContributionVerifier::Verify(), and CBLSWorker::VerifyContributionShare().
Friends And Related Function Documentation
CBLSSecretKey
friend class CBLSSecretKey friend
Definition at line 265 of file bls.h.
CBLSSignature
friend class CBLSSignature friend
Definition at line 266 of file bls.h.
The documentation for this class was generated from the following files:
src/bls/bls.h
src/bls/bls.cpp
Released under the MIT license