Dash Core: CHash256 Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CHash256 Class Reference
A hasher class for Bitcoin's 256-bit hash (double SHA-256).
#include <hash.h>
Public Member Functions
void Finalize (unsigned char hash[OUTPUT_SIZE])
CHash256 & Write (const unsigned char *data, size_t len)
CHash256 & Reset ()
Static Public Attributes
static const size_t OUTPUT_SIZE = CSHA256::OUTPUT_SIZE
Private Attributes
CSHA256 sha
Detailed Description
A hasher class for Bitcoin's 256-bit hash (double SHA-256).
Definition at line 35 of file hash.h.
Member Function Documentation
Finalize()
void CHash256::Finalize (unsigned char hash[OUTPUT_SIZE]) inline
Definition at line 41 of file hash.h.
References CSHA256::Finalize(), CSHA256::OUTPUT_SIZE, CSHA256::Reset(), sha, and CSHA256::Write().
Referenced by CHashWriter::GetHash(), CNetMessage::GetMessageHash(), and Hash().
Reset()
CHash256& CHash256::Reset () inline
Definition at line 52 of file hash.h.
References CSHA256::Reset(), and sha.
Write()
CHash256& CHash256::Write (const unsigned char * data, size_t len) inline
Definition at line 47 of file hash.h.
References sha, and CSHA256::Write().
Referenced by EvalScript(), Hash(), HASH(), HASH_DSHA256(), HASH_DSHA256_0032b(), HASH_DSHA256_0032b_single(), HASH_DSHA256_0080b_single(), HASH_DSHA256_0128b_single(), HASH_DSHA256_0512b_single(), HASH_DSHA256_1024b_single(), HASH_DSHA256_2048b_single(), CNetMessage::readData(), CKey::VerifyPubKey(), and CHashWriter::write().
Member Data Documentation
OUTPUT_SIZE
const size_t CHash256::OUTPUT_SIZE = CSHA256::OUTPUT_SIZE static
Definition at line 39 of file hash.h.
Referenced by HASH().
sha
CSHA256 CHash256::sha private
Definition at line 37 of file hash.h.
Referenced by Finalize(), Reset(), and Write().
The documentation for this class was generated from the following file:
src/hash.h
Released under the MIT license