Dash Core: org.bitcoin.NativeSecp256k1Test Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
org.bitcoin.NativeSecp256k1Test Class Reference
This class holds test cases defined for testing this library.
Static Public Member Functions
static void testVerifyPos () throws AssertFailException
This tests verify() for a valid signature.
static void testVerifyNeg () throws AssertFailException
This tests verify() for a non-valid signature.
static void testSecKeyVerifyPos () throws AssertFailException
This tests secret key verify() for a valid secretkey.
static void testSecKeyVerifyNeg () throws AssertFailException
This tests secret key verify() for an invalid secretkey.
static void testPubKeyCreatePos () throws AssertFailException
This tests public key create() for a valid secretkey.
static void testPubKeyCreateNeg () throws AssertFailException
This tests public key create() for a invalid secretkey.
static void testSignPos () throws AssertFailException
This tests sign() for a valid secretkey.
static void testSignNeg () throws AssertFailException
This tests sign() for a invalid secretkey.
static void testPrivKeyTweakAdd_1 () throws AssertFailException
This tests private key tweak-add.
static void testPrivKeyTweakMul_1 () throws AssertFailException
This tests private key tweak-mul.
static void testPrivKeyTweakAdd_2 () throws AssertFailException
This tests private key tweak-add uncompressed.
static void testPrivKeyTweakMul_2 () throws AssertFailException
This tests private key tweak-mul uncompressed.
static void testRandomize () throws AssertFailException
This tests seed randomization.
static void testCreateECDHSecret () throws AssertFailException
static void main (String[] args) throws AssertFailException
Detailed Description
This class holds test cases defined for testing this library.
Definition at line 12 of file NativeSecp256k1Test.java.
Member Function Documentation
main()
static void org.bitcoin.NativeSecp256k1Test.main (String [] args) throws AssertFailException inline static
Definition at line 180 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.cleanup(), org.bitcoin.Secp256k1Context.isEnabled(), org.bitcoin.NativeSecp256k1Test.testCreateECDHSecret(), org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakAdd_1(), org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakAdd_2(), org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakMul_1(), org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakMul_2(), org.bitcoin.NativeSecp256k1Test.testPubKeyCreateNeg(), org.bitcoin.NativeSecp256k1Test.testPubKeyCreatePos(), org.bitcoin.NativeSecp256k1Test.testRandomize(), org.bitcoin.NativeSecp256k1Test.testSecKeyVerifyNeg(), org.bitcoin.NativeSecp256k1Test.testSecKeyVerifyPos(), org.bitcoin.NativeSecp256k1Test.testSignNeg(), org.bitcoin.NativeSecp256k1Test.testSignPos(), org.bitcoin.NativeSecp256k1Test.testVerifyNeg(), and org.bitcoin.NativeSecp256k1Test.testVerifyPos().
testCreateECDHSecret()
static void org.bitcoin.NativeSecp256k1Test.testCreateECDHSecret () throws AssertFailException inline static
Definition at line 170 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.createECDHSecret().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testPrivKeyTweakAdd_1()
static void org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakAdd_1 () throws AssertFailException inline static
This tests private key tweak-add.
Definition at line 116 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.privKeyTweakAdd().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testPrivKeyTweakAdd_2()
static void org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakAdd_2 () throws AssertFailException inline static
This tests private key tweak-add uncompressed.
Definition at line 140 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.pubKeyTweakAdd().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testPrivKeyTweakMul_1()
static void org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakMul_1 () throws AssertFailException inline static
This tests private key tweak-mul.
Definition at line 128 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.privKeyTweakMul().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testPrivKeyTweakMul_2()
static void org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakMul_2 () throws AssertFailException inline static
This tests private key tweak-mul uncompressed.
Definition at line 152 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.pubKeyTweakMul().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testPubKeyCreateNeg()
static void org.bitcoin.NativeSecp256k1Test.testPubKeyCreateNeg () throws AssertFailException inline static
This tests public key create() for a invalid secretkey.
Definition at line 80 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.computePubkey().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testPubKeyCreatePos()
static void org.bitcoin.NativeSecp256k1Test.testPubKeyCreatePos () throws AssertFailException inline static
This tests public key create() for a valid secretkey.
Definition at line 69 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.computePubkey().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testRandomize()
static void org.bitcoin.NativeSecp256k1Test.testRandomize () throws AssertFailException inline static
This tests seed randomization.
Definition at line 164 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.randomize().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testSecKeyVerifyNeg()
static void org.bitcoin.NativeSecp256k1Test.testSecKeyVerifyNeg () throws AssertFailException inline static
This tests secret key verify() for an invalid secretkey.
Definition at line 57 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.secKeyVerify().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testSecKeyVerifyPos()
static void org.bitcoin.NativeSecp256k1Test.testSecKeyVerifyPos () throws AssertFailException inline static
This tests secret key verify() for a valid secretkey.
Definition at line 45 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.secKeyVerify().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testSignNeg()
static void org.bitcoin.NativeSecp256k1Test.testSignNeg () throws AssertFailException inline static
This tests sign() for a invalid secretkey.
Definition at line 104 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.sign().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testSignPos()
static void org.bitcoin.NativeSecp256k1Test.testSignPos () throws AssertFailException inline static
This tests sign() for a valid secretkey.
Definition at line 91 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.sign().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testVerifyNeg()
static void org.bitcoin.NativeSecp256k1Test.testVerifyNeg () throws AssertFailException inline static
This tests verify() for a non-valid signature.
Definition at line 31 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.verify().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
testVerifyPos()
static void org.bitcoin.NativeSecp256k1Test.testVerifyPos () throws AssertFailException inline static
This tests verify() for a valid signature.
Definition at line 18 of file NativeSecp256k1Test.java.
References org.bitcoin.NativeSecp256k1.verify().
Referenced by org.bitcoin.NativeSecp256k1Test.main().
The documentation for this class was generated from the following file:
src/secp256k1/src/java/org/bitcoin/NativeSecp256k1Test.java
Released under the MIT license