Dash Core: WalletInit Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
WalletInit Class Reference
Public Member Functions
std::string GetHelpString (bool showDebug) override
Return the wallets help message.
bool ParameterInteraction () override
Wallets parameter interaction.
void RegisterRPC (CRPCTable &tableRPC) override
Register wallet RPCs.
bool Verify () override
Responsible for reading and validating the -wallet arguments and verifying the wallet database.
bool Open () override
Load wallet databases.
void Start (CScheduler &scheduler) override
Complete startup of wallets.
void Flush () override
Flush all wallets in preparation for shutdown.
void Stop () override
Stop all wallets. Wallets will be flushed first.
void Close () override
Close all wallets.
void AutoLockMasternodeCollaterals () override
void InitPrivateSendSettings () override
void InitKeePass () override
bool InitAutoBackup () override
Public Member Functions inherited from WalletInitInterface
virtual ~WalletInitInterface ()
Detailed Description
Definition at line 22 of file init.cpp.
Member Function Documentation
AutoLockMasternodeCollaterals()
void WalletInit::AutoLockMasternodeCollaterals () override virtual
Implements WalletInitInterface.
Definition at line 400 of file init.cpp.
References GetWallets().
Close()
void WalletInit::Close () override virtual
Close all wallets.
Implements WalletInitInterface.
Definition at line 392 of file init.cpp.
References GetWallets(), and RemoveWallet().
Flush()
void WalletInit::Flush () override virtual
Flush all wallets in preparation for shutdown.
Implements WalletInitInterface.
Definition at line 373 of file init.cpp.
References CPrivateSendClientManager::fEnablePrivateSend, CPrivateSendClientManager::fPrivateSendRunning, GetWallets(), privateSendClient, and CPrivateSendClientManager::ResetPool().
GetHelpString()
std::string WalletInit::GetHelpString (bool showDebug) override virtual
Return the wallets help message.
Implements WalletInitInterface.
Definition at line 64 of file init.cpp.
References _(), CURRENCY_UNIT, DEFAULT_DISCARD_FEE, DEFAULT_FALLBACK_FEE, DEFAULT_FLUSHWALLET, DEFAULT_KEEPASS_HTTP_PORT, DEFAULT_KEYPOOL_SIZE, DEFAULT_PRIVATESEND_AMOUNT, DEFAULT_PRIVATESEND_AUTOSTART, DEFAULT_PRIVATESEND_DENOMS_GOAL, DEFAULT_PRIVATESEND_DENOMS_HARDCAP, DEFAULT_PRIVATESEND_MULTISESSION, DEFAULT_PRIVATESEND_ROUNDS, DEFAULT_PRIVATESEND_SESSIONS, DEFAULT_SPEND_ZEROCONF_CHANGE, DEFAULT_TRANSACTION_MINFEE, DEFAULT_TX_CONFIRM_TARGET, DEFAULT_USE_HD_WALLET, DEFAULT_WALLET_DBLOGSIZE, DEFAULT_WALLET_PRIVDB, DEFAULT_WALLET_REJECT_LONG_CHAINS, DEFAULT_WALLETBROADCAST, FormatMoney(), CFeeRate::GetFeePerK(), HelpMessageGroup(), HelpMessageOpt(), MAX_PRIVATESEND_AMOUNT, MAX_PRIVATESEND_DENOMS_GOAL, MAX_PRIVATESEND_DENOMS_HARDCAP, MAX_PRIVATESEND_ROUNDS, MAX_PRIVATESEND_SESSIONS, MIN_PRIVATESEND_AMOUNT, MIN_PRIVATESEND_DENOMS_GOAL, MIN_PRIVATESEND_DENOMS_HARDCAP, MIN_PRIVATESEND_ROUNDS, MIN_PRIVATESEND_SESSIONS, nWalletBackups, payTxFee, and strprintf.
InitAutoBackup()
bool WalletInit::InitAutoBackup () override virtual
Implements WalletInitInterface.
Definition at line 439 of file init.cpp.
References CWallet::InitAutoBackup().
InitKeePass()
void WalletInit::InitKeePass () override virtual
Implements WalletInitInterface.
Definition at line 434 of file init.cpp.
References CKeePassIntegrator::init(), and keePassInt.
InitPrivateSendSettings()
void WalletInit::InitPrivateSendSettings () override virtual
Implements WalletInitInterface.
Definition at line 408 of file init.cpp.
References DEFAULT_PRIVATESEND_AMOUNT, DEFAULT_PRIVATESEND_AUTOSTART, DEFAULT_PRIVATESEND_DENOMS_GOAL, DEFAULT_PRIVATESEND_DENOMS_HARDCAP, DEFAULT_PRIVATESEND_MULTISESSION, DEFAULT_PRIVATESEND_ROUNDS, DEFAULT_PRIVATESEND_SESSIONS, false, CPrivateSendClientManager::fEnablePrivateSend, CPrivateSendClientManager::fPrivateSendMultiSession, CPrivateSendClientManager::fPrivateSendRunning, gArgs, ArgsManager::GetArg(), ArgsManager::GetBoolArg(), GetWallets(), HasWallets(), LogPrintf, MAX_PRIVATESEND_AMOUNT, MAX_PRIVATESEND_DENOMS_GOAL, MAX_PRIVATESEND_DENOMS_HARDCAP, MAX_PRIVATESEND_ROUNDS, MAX_PRIVATESEND_SESSIONS, MIN_PRIVATESEND_AMOUNT, MIN_PRIVATESEND_DENOMS_GOAL, MIN_PRIVATESEND_DENOMS_HARDCAP, MIN_PRIVATESEND_ROUNDS, MIN_PRIVATESEND_SESSIONS, CPrivateSendClientManager::nPrivateSendAmount, CPrivateSendClientManager::nPrivateSendDenomsGoal, CPrivateSendClientManager::nPrivateSendDenomsHardCap, CPrivateSendClientManager::nPrivateSendRounds, CPrivateSendClientManager::nPrivateSendSessions, and privateSendClient.
Open()
bool WalletInit::Open () override virtual
Load wallet databases.
Implements WalletInitInterface.
Definition at line 340 of file init.cpp.
References AddWallet(), CWallet::CreateWalletFromFile(), DEFAULT_DISABLE_WALLET, gArgs, ArgsManager::GetArgs(), ArgsManager::GetBoolArg(), GetWalletDir(), and LogPrintf.
ParameterInteraction()
bool WalletInit::ParameterInteraction () override virtual
Wallets parameter interaction.
Implements WalletInitInterface.
Definition at line 124 of file init.cpp.
References _(), AmountErrMsg(), AmountHighWarn(), bSpendZeroConfChange, DEFAULT_BLOCKSONLY, DEFAULT_DISABLE_WALLET, DEFAULT_PRIVATESEND_DENOMS_GOAL, DEFAULT_PRIVATESEND_DENOMS_HARDCAP, DEFAULT_SPEND_ZEROCONF_CHANGE, DEFAULT_TX_CONFIRM_TARGET, CWallet::fallbackFee, ArgsManager::ForceRemoveArg(), gArgs, ArgsManager::GetArg(), ArgsManager::GetArgs(), ArgsManager::GetBoolArg(), CFeeRate::GetFeePerK(), HIGH_MAX_TX_FEE, HIGH_TX_FEE_PER_KB, InitError(), InitWarning(), ArgsManager::IsArgSet(), IsHex(), itostr(), LogPrintf, CWallet::m_discard_rate, maxTxFee, minRelayTxFee, CWallet::minTxFee, nTxConfirmTarget, ParseMoney(), payTxFee, ArgsManager::SoftSetArg(), ArgsManager::SoftSetBoolArg(), strprintf, and CFeeRate::ToString().
RegisterRPC()
void WalletInit::RegisterRPC (CRPCTable & tableRPC) override virtual
Register wallet RPCs.
Implements WalletInitInterface.
Definition at line 282 of file init.cpp.
References DEFAULT_DISABLE_WALLET, gArgs, ArgsManager::GetBoolArg(), and RegisterWalletRPCCommands().
Start()
void WalletInit::Start (CScheduler & scheduler) override virtual
Complete startup of wallets.
Implements WalletInitInterface.
Definition at line 358 of file init.cpp.
References CPrivateSendClientManager::DoMaintenance(), CPrivateSendClientManager::fEnablePrivateSend, fMasternodeMode, g_connman, GetWallets(), MaybeCompactWalletDB(), privateSendClient, CScheduler::scheduleEvery(), and scheduler.
Stop()
void WalletInit::Stop () override virtual
Stop all wallets. Wallets will be flushed first.
Implements WalletInitInterface.
Definition at line 385 of file init.cpp.
References GetWallets().
Verify()
bool WalletInit::Verify () override virtual
Responsible for reading and validating the -wallet arguments and verifying the wallet database.
Implements WalletInitInterface.
Definition at line 291 of file init.cpp.
References _(), DEFAULT_DISABLE_WALLET, gArgs, ArgsManager::GetArg(), ArgsManager::GetArgs(), ArgsManager::GetBoolArg(), GetWalletDir(), InitError(), CClientUIInterface::InitMessage, InitWarning(), ArgsManager::IsArgSet(), LogPrintf, strprintf, uiInterface, and CWallet::Verify().
The documentation for this class was generated from the following file:
src/wallet/init.cpp
Released under the MIT license