Dash Core: CacheMap< K, V, Size > Class Template Reference
CacheMap< K, V, Size > Class Template Reference
#include <cachemap.h>
Public Types
typedef Size size_type
typedef CacheItem< K, V > item_t
typedef std::list< item_t > list_t
typedef list_t::iterator list_it
typedef list_t::const_iterator list_cit
typedef std::map< K, list_it > map_t
typedef map_t::iterator map_it
typedef map_t::const_iterator map_cit
Public Member Functions
CacheMap (size_type nMaxSizeIn=0)
CacheMap (const CacheMap< K, V > &other)
void Clear ()
void SetMaxSize (size_type nMaxSizeIn)
size_type GetMaxSize () const
size_type GetSize () const
void Insert (const K &key, const V &value)
bool HasKey (const K &key) const
bool Get (const K &key, V &value) const
void Erase (const K &key)
const list_t & GetItemList () const
CacheMap< K, V > & operator= (const CacheMap< K, V > &other)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
Public Attributes
ADD_SERIALIZE_METHODS
Private Member Functions
void PruneLast ()
void RebuildIndex ()
Private Attributes
size_type nMaxSize
size_type nCurrentSize
list_t listItems
map_t mapIndex
Detailed Description
template<typename K, typename V, typename Size = uint32_t>
class CacheMap< K, V, Size >
Map like container that keeps the N most recently added items
Definition at line 46 of file cachemap.h.
Member Typedef Documentation
item_t
template<typename K, typename V, typename Size = uint32_t> typedef CacheItem<K,V> CacheMap< K, V, Size >::item_t
Definition at line 51 of file cachemap.h.
list_cit
template<typename K, typename V, typename Size = uint32_t> typedef list_t::const_iterator CacheMap< K, V, Size >::list_cit
Definition at line 57 of file cachemap.h.
list_it
template<typename K, typename V, typename Size = uint32_t> typedef list_t::iterator CacheMap< K, V, Size >::list_it
Definition at line 55 of file cachemap.h.
list_t
template<typename K, typename V, typename Size = uint32_t> typedef std::list<item_t> CacheMap< K, V, Size >::list_t
Definition at line 53 of file cachemap.h.
map_cit
template<typename K, typename V, typename Size = uint32_t> typedef map_t::const_iterator CacheMap< K, V, Size >::map_cit
Definition at line 63 of file cachemap.h.
map_it
template<typename K, typename V, typename Size = uint32_t> typedef map_t::iterator CacheMap< K, V, Size >::map_it
Definition at line 61 of file cachemap.h.
map_t
template<typename K, typename V, typename Size = uint32_t> typedef std::map<K, list_it> CacheMap< K, V, Size >::map_t
Definition at line 59 of file cachemap.h.
size_type
template<typename K, typename V, typename Size = uint32_t> typedef Size CacheMap< K, V, Size >::size_type
Definition at line 49 of file cachemap.h.
Constructor & Destructor Documentation
CacheMap() [1/2]
template<typename K, typename V, typename Size = uint32_t> CacheMap< K, V, Size >::CacheMap (size_type nMaxSizeIn = 0) inline
Definition at line 75 of file cachemap.h.
CacheMap() [2/2]
template<typename K, typename V, typename Size = uint32_t> CacheMap< K, V, Size >::CacheMap (const CacheMap< K, V > & other) inline
Definition at line 82 of file cachemap.h.
Member Function Documentation
Clear()
template<typename K, typename V, typename Size = uint32_t> void CacheMap< K, V, Size >::Clear () inline
Definition at line 91 of file cachemap.h.
Referenced by CGovernanceManager::Clear(), and CGovernanceManager::RebuildIndexes().
Erase()
template<typename K, typename V, typename Size = uint32_t> void CacheMap< K, V, Size >::Erase (const K & key) inline
Definition at line 144 of file cachemap.h.
Referenced by CGovernanceManager::UpdateCachesAndClean().
Get()
template<typename K, typename V, typename Size = uint32_t> bool CacheMap< K, V, Size >::Get (const K & key, V & value) const inline
Definition at line 133 of file cachemap.h.
Referenced by CGovernanceManager::HaveVoteForHash(), and CGovernanceManager::SerializeVoteForHash().
GetItemList()
template<typename K, typename V, typename Size = uint32_t> const list_t& CacheMap< K, V, Size >::GetItemList () const inline
Definition at line 155 of file cachemap.h.
Referenced by CGovernanceManager::UpdateCachesAndClean().
GetMaxSize()
template<typename K, typename V, typename Size = uint32_t> size_type CacheMap< K, V, Size >::GetMaxSize () const inline
Definition at line 103 of file cachemap.h.
GetSize()
template<typename K, typename V, typename Size = uint32_t> size_type CacheMap< K, V, Size >::GetSize () const inline
Definition at line 107 of file cachemap.h.
Referenced by CGovernanceManager::GetVoteCount(), and CGovernanceManager::ToString().
HasKey()
template<typename K, typename V, typename Size = uint32_t> bool CacheMap< K, V, Size >::HasKey (const K & key) const inline
Definition at line 127 of file cachemap.h.
Referenced by CGovernanceManager::ConfirmInventoryRequest(), and CGovernanceManager::ProcessVote().
Insert()
template<typename K, typename V, typename Size = uint32_t> void CacheMap< K, V, Size >::Insert (const K & key, const V & value) inline
Definition at line 111 of file cachemap.h.
Referenced by CGovernanceManager::AddInvalidVote(), CGovernanceManager::ProcessVote(), and CGovernanceManager::RebuildIndexes().
operator=()
template<typename K, typename V, typename Size = uint32_t> CacheMap<K,V>& CacheMap< K, V, Size >::operator= (const CacheMap< K, V > & other) inline
Definition at line 159 of file cachemap.h.
PruneLast()
template<typename K, typename V, typename Size = uint32_t> void CacheMap< K, V, Size >::PruneLast () inline private
Definition at line 182 of file cachemap.h.
Referenced by CacheMap< uint256, CGovernanceVote >::Insert().
RebuildIndex()
template<typename K, typename V, typename Size = uint32_t> void CacheMap< K, V, Size >::RebuildIndex () inline private
Definition at line 193 of file cachemap.h.
Referenced by CacheMap< uint256, CGovernanceVote >::CacheMap(), CacheMap< uint256, CGovernanceVote >::operator=(), and CacheMap< uint256, CGovernanceVote >::SerializationOp().
SerializationOp()
template<typename K, typename V, typename Size = uint32_t> template<typename Stream , typename Operation > void CacheMap< K, V, Size >::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 171 of file cachemap.h.
SetMaxSize()
template<typename K, typename V, typename Size = uint32_t> void CacheMap< K, V, Size >::SetMaxSize (size_type nMaxSizeIn) inline
Definition at line 98 of file cachemap.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
template<typename K, typename V, typename Size = uint32_t> CacheMap< K, V, Size >::ADD_SERIALIZE_METHODS
Definition at line 168 of file cachemap.h.
listItems
template<typename K, typename V, typename Size = uint32_t> list_t CacheMap< K, V, Size >::listItems private
Definition at line 70 of file cachemap.h.
Referenced by CacheMap< uint256, CGovernanceVote >::Clear(), CacheMap< uint256, CGovernanceVote >::Erase(), CacheMap< uint256, CGovernanceVote >::GetItemList(), CacheMap< uint256, CGovernanceVote >::Insert(), CacheMap< uint256, CGovernanceVote >::operator=(), CacheMultiMap< uint256, vote_time_pair_t >::operator=(), CacheMap< uint256, CGovernanceVote >::PruneLast(), CacheMap< uint256, CGovernanceVote >::RebuildIndex(), and CacheMap< uint256, CGovernanceVote >::SerializationOp().
mapIndex
template<typename K, typename V, typename Size = uint32_t> map_t CacheMap< K, V, Size >::mapIndex private
Definition at line 72 of file cachemap.h.
Referenced by CacheMap< uint256, CGovernanceVote >::Clear(), CacheMap< uint256, CGovernanceVote >::Erase(), CacheMap< uint256, CGovernanceVote >::Get(), CacheMap< uint256, CGovernanceVote >::HasKey(), CacheMap< uint256, CGovernanceVote >::Insert(), CacheMap< uint256, CGovernanceVote >::PruneLast(), and CacheMap< uint256, CGovernanceVote >::RebuildIndex().
nCurrentSize
template<typename K, typename V, typename Size = uint32_t> size_type CacheMap< K, V, Size >::nCurrentSize private
Definition at line 68 of file cachemap.h.
Referenced by CacheMap< uint256, CGovernanceVote >::Clear(), CacheMap< uint256, CGovernanceVote >::Erase(), CacheMap< uint256, CGovernanceVote >::GetSize(), CacheMap< uint256, CGovernanceVote >::Insert(), CacheMap< uint256, CGovernanceVote >::operator=(), CacheMultiMap< uint256, vote_time_pair_t >::operator=(), CacheMap< uint256, CGovernanceVote >::PruneLast(), and CacheMap< uint256, CGovernanceVote >::SerializationOp().
nMaxSize
template<typename K, typename V, typename Size = uint32_t> size_type CacheMap< K, V, Size >::nMaxSize private
Definition at line 66 of file cachemap.h.
Referenced by CacheMap< uint256, CGovernanceVote >::GetMaxSize(), CacheMap< uint256, CGovernanceVote >::Insert(), CacheMap< uint256, CGovernanceVote >::operator=(), CacheMultiMap< uint256, vote_time_pair_t >::operator=(), CacheMap< uint256, CGovernanceVote >::SerializationOp(), and CacheMap< uint256, CGovernanceVote >::SetMaxSize().
The documentation for this class was generated from the following file:
src/cachemap.h