Dash Core: CMasternodePayments Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodePayments Class Reference
#include <masternode-payments.h>
Public Member Functions
CMasternodePayments ()
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
void Clear ()
bool AddPaymentVote (const CMasternodePaymentVote &vote)
bool HasVerifiedPaymentVote (uint256 hashIn)
bool ProcessBlock (int nBlockHeight, CConnman &connman)
void CheckPreviousBlockVotes (int nPrevBlockHeight)
void Sync (CNode *node, CConnman &connman)
void RequestLowDataPaymentBlocks (CNode *pnode, CConnman &connman)
void CheckAndRemove ()
bool GetBlockPayee (int nBlockHeight, CScript &payee)
bool IsTransactionValid (const CTransaction &txNew, int nBlockHeight)
bool IsScheduled (CMasternode &mn, int nNotBlockHeight)
bool CanVote (COutPoint outMasternode, int nBlockHeight)
int GetMinMasternodePaymentsProto ()
void ProcessMessage (CNode *pfrom, std::string &strCommand, CDataStream &vRecv, CConnman &connman)
std::string GetRequiredPaymentsString (int nBlockHeight)
void FillBlockPayee (CMutableTransaction &txNew, int nBlockHeight, CAmount blockReward, CTxOut &txoutMasternodeRet)
FillBlockPayee.
std::string ToString () const
int GetBlockCount ()
int GetVoteCount ()
bool IsEnoughData ()
int GetStorageLimit ()
void UpdatedBlockTip (const CBlockIndex *pindex, CConnman &connman)
Public Attributes
std::map< uint256, CMasternodePaymentVote > mapMasternodePaymentVotes
std::map< int, CMasternodeBlockPayees > mapMasternodeBlocks
std::map< COutPoint, int > mapMasternodesLastVote
std::map< COutPoint, int > mapMasternodesDidNotVote
ADD_SERIALIZE_METHODS
Private Attributes
const float nStorageCoeff
const int nMinBlocksToStore
int nCachedBlockHeight
Detailed Description
Definition at line 167 of file masternode-payments.h.
Constructor & Destructor Documentation
CMasternodePayments()
CMasternodePayments::CMasternodePayments () inline
Definition at line 184 of file masternode-payments.h.
Member Function Documentation
AddPaymentVote()
bool CMasternodePayments::AddPaymentVote (const CMasternodePaymentVote & vote)
Definition at line 467 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, GetBlockHash(), CMasternodePaymentVote::GetHash(), HasVerifiedPaymentVote(), LOCK2, mapMasternodeBlocks, mapMasternodePaymentVotes, and CMasternodePaymentVote::nBlockHeight.
Referenced by ProcessBlock(), and ProcessMessage().
CanVote()
bool CMasternodePayments::CanVote (COutPoint outMasternode, int nBlockHeight)
Definition at line 245 of file masternode-payments.cpp.
References cs_mapMasternodePaymentVotes, LOCK, and mapMasternodesLastVote.
Referenced by ProcessMessage().
CheckAndRemove()
void CMasternodePayments::CheckAndRemove ()
Definition at line 632 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, GetStorageLimit(), CMasternodeSync::IsBlockchainSynced(), LOCK2, LogPrint(), LogPrintf, mapMasternodeBlocks, mapMasternodePaymentVotes, masternodeSync, CMasternodePaymentVote::nBlockHeight, nCachedBlockHeight, and ToString().
Referenced by ThreadCheckPrivateSend().
CheckPreviousBlockVotes()
void CMasternodePayments::CheckPreviousBlockVotes (int nPrevBlockHeight)
Definition at line 780 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, ExtractDestination(), CMasternodeMan::GetMasternodeRanks(), GetMinMasternodePaymentsProto(), CMasternodeSync::IsWinnersListSynced(), LOCK2, LogPrint(), mapMasternodeBlocks, mapMasternodePaymentVotes, mapMasternodesDidNotVote, masternodeSync, mnodeman, MNPAYMENTS_SIGNATURES_TOTAL, strprintf, and CBase58Data::ToString().
Referenced by UpdatedBlockTip().
Clear()
void CMasternodePayments::Clear ()
Definition at line 238 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, cs_mapMasternodePaymentVotes, LOCK2, mapMasternodeBlocks, and mapMasternodePaymentVotes.
FillBlockPayee()
void CMasternodePayments::FillBlockPayee (CMutableTransaction & txNew, int nBlockHeight, CAmount blockReward, CTxOut & txoutMasternodeRet)
FillBlockPayee.
Fill Masternode ONLY payment block
Definition at line 264 of file masternode-payments.cpp.
References ExtractDestination(), GetBlockPayee(), CPubKey::GetID(), GetMasternodePayment(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetScriptForDestination(), LogPrintf, mnodeman, mnpayments, masternode_info_t::pubKeyCollateralAddress, CBase58Data::ToString(), and CMutableTransaction::vout.
Referenced by FillBlockPayments().
GetBlockCount()
int CMasternodePayments::GetBlockCount () inline
Definition at line 217 of file masternode-payments.h.
References mapMasternodeBlocks.
Referenced by IsEnoughData().
GetBlockPayee()
bool CMasternodePayments::GetBlockPayee (int nBlockHeight, CScript & payee)
Definition at line 436 of file masternode-payments.cpp.
References mapMasternodeBlocks.
Referenced by ComputeBlockVersion(), and FillBlockPayee().
GetMinMasternodePaymentsProto()
int CMasternodePayments::GetMinMasternodePaymentsProto ()
Definition at line 300 of file masternode-payments.cpp.
References CSporkManager::IsSporkActive(), MIN_MASTERNODE_PAYMENT_PROTO_VERSION_1, MIN_MASTERNODE_PAYMENT_PROTO_VERSION_2, SPORK_10_MASTERNODE_PAY_UPDATED_NODES, and sporkManager.
Referenced by CMasternode::Check(), CheckPreviousBlockVotes(), CMasternodeMan::CountEnabled(), CMasternodeMan::CountMasternodes(), CMasternodeMan::FindRandomNotInVec(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), CMasternodePaymentVote::IsValid(), ProcessBlock(), ProcessMessage(), CMasternodeSync::ProcessTick(), CMasternodePaymentVote::Relay(), and CMasternodeBroadcast::SimpleCheck().
GetRequiredPaymentsString()
std::string CMasternodePayments::GetRequiredPaymentsString (int nBlockHeight)
Definition at line 610 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, LOCK, and mapMasternodeBlocks.
Referenced by GetRequiredPaymentsString().
GetStorageLimit()
int CMasternodePayments::GetStorageLimit ()
Definition at line 1009 of file masternode-payments.cpp.
References mnodeman, nMinBlocksToStore, nStorageCoeff, and CMasternodeMan::size().
Referenced by CheckAndRemove(), IsEnoughData(), ProcessMessage(), CMasternodeSync::ProcessTick(), RequestLowDataPaymentBlocks(), and CMasternodeMan::UpdateLastPaid().
GetVoteCount()
int CMasternodePayments::GetVoteCount () inline
Definition at line 218 of file masternode-payments.h.
References mapMasternodePaymentVotes.
Referenced by IsEnoughData().
HasVerifiedPaymentVote()
bool CMasternodePayments::HasVerifiedPaymentVote (uint256 hashIn)
Definition at line 488 of file masternode-payments.cpp.
References cs_mapMasternodePaymentVotes, LOCK, and mapMasternodePaymentVotes.
Referenced by AddPaymentVote(), ProcessGetData(), and Sync().
IsEnoughData()
bool CMasternodePayments::IsEnoughData ()
Definition at line 1002 of file masternode-payments.cpp.
References GetBlockCount(), GetStorageLimit(), GetVoteCount(), MNPAYMENTS_SIGNATURES_REQUIRED, and MNPAYMENTS_SIGNATURES_TOTAL.
Referenced by CMasternodeSync::ProcessTick().
IsScheduled()
bool CMasternodePayments::IsScheduled (CMasternode & mn, int nNotBlockHeight)
Definition at line 447 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, CPubKey::GetID(), GetScriptForDestination(), CMasternodeSync::IsMasternodeListSynced(), LOCK, mapMasternodeBlocks, masternodeSync, nCachedBlockHeight, and masternode_info_t::pubKeyCollateralAddress.
Referenced by CMasternodeMan::GetNextMasternodeInQueueForPayment().
IsTransactionValid()
bool CMasternodePayments::IsTransactionValid (const CTransaction & txNew, int nBlockHeight)
Definition at line 621 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, LOCK, and mapMasternodeBlocks.
Referenced by IsBlockPayeeValid().
ProcessBlock()
bool CMasternodePayments::ProcessBlock (int nBlockHeight, CConnman & connman)
Definition at line 715 of file masternode-payments.cpp.
References activeMasternode, AddPaymentVote(), ExtractDestination(), fLiteMode, fMasterNode, CPubKey::GetID(), CMasternodeMan::GetMasternodeRank(), GetMinMasternodePaymentsProto(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), GetScriptForDestination(), CMasternodeSync::IsMasternodeListSynced(), LogPrint(), LogPrintf, masternodeSync, mnodeman, MNPAYMENTS_SIGNATURES_TOTAL, CActiveMasternode::outpoint, CTxIn::prevout, masternode_info_t::pubKeyCollateralAddress, CBase58Data::ToString(), COutPoint::ToStringShort(), and masternode_info_t::vin.
Referenced by UpdatedBlockTip().
ProcessMessage()
void CMasternodePayments::ProcessMessage (CNode * pfrom, std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 306 of file masternode-payments.cpp.
References CNetFulfilledRequestManager::AddFulfilledRequest(), AddPaymentVote(), CNode::addr, CMasternodeMan::AskForMN(), CMasternodeSync::BumpAssetLastTime(), CanVote(), cs_mapMasternodePaymentVotes, ExtractDestination(), fLiteMode, uint256::GetHash(), CNode::GetId(), CMasternodeMan::GetMasternodeInfo(), GetMinMasternodePaymentsProto(), GetStorageLimit(), CNetFulfilledRequestManager::HasFulfilledRequest(), CNode::id, CMasternodeSync::IsMasternodeListSynced(), CMasternodeSync::IsSynced(), LOCK, LogPrint(), LogPrintf, mapMasternodePaymentVotes, NetMsgType::MASTERNODEPAYMENTSYNC, NetMsgType::MASTERNODEPAYMENTVOTE, masternodeSync, Misbehaving(), mnodeman, nCachedBlockHeight, netfulfilledman, CNode::nVersion, masternode_info_t::pubKeyMasternode, CNode::setAskFor, Sync(), base_blob< BITS >::ToString(), and CBase58Data::ToString().
Referenced by ProcessMessage().
RequestLowDataPaymentBlocks()
void CMasternodePayments::RequestLowDataPaymentBlocks (CNode * pnode, CConnman & connman)
Definition at line 913 of file masternode-payments.cpp.
References chainActive, cs_main, cs_mapMasternodeBlocks, DBG, CBlockIndex::GetBlockHash(), GetBlockHash(), NetMsgType::GETDATA, GetStorageLimit(), CMasternodePayee::GetVoteCount(), CNode::id, CMasternodeSync::IsMasternodeListSynced(), LOCK2, LogPrintf, mapMasternodeBlocks, masternodeSync, MAX_INV_SZ, MNPAYMENTS_SIGNATURES_REQUIRED, MNPAYMENTS_SIGNATURES_TOTAL, MSG_MASTERNODE_PAYMENT_BLOCK, nCachedBlockHeight, CBlockIndex::nHeight, CBlockIndex::pprev, CConnman::PushMessage(), and CChain::Tip().
Referenced by CMasternodeSync::ProcessTick().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodePayments::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 189 of file masternode-payments.h.
References mapMasternodeBlocks, mapMasternodePaymentVotes, and READWRITE.
Sync()
void CMasternodePayments::Sync (CNode * node, CConnman & connman)
Definition at line 887 of file masternode-payments.cpp.
References cs_mapMasternodeBlocks, CMasternodePayee::GetVoteHashes(), HasVerifiedPaymentVote(), CNode::id, CMasternodeSync::IsWinnersListSynced(), LOCK, LogPrintf, mapMasternodeBlocks, MASTERNODE_SYNC_MNW, masternodeSync, MSG_MASTERNODE_PAYMENT_VOTE, nCachedBlockHeight, CNode::PushInventory(), CConnman::PushMessage(), and NetMsgType::SYNCSTATUSCOUNT.
Referenced by ProcessMessage().
ToString()
std::string CMasternodePayments::ToString () const
Definition at line 992 of file masternode-payments.cpp.
References mapMasternodeBlocks, and mapMasternodePaymentVotes.
Referenced by CheckAndRemove().
UpdatedBlockTip()
void CMasternodePayments::UpdatedBlockTip (const CBlockIndex * pindex, CConnman & connman)
Definition at line 1014 of file masternode-payments.cpp.
References CheckPreviousBlockVotes(), LogPrint(), nCachedBlockHeight, CBlockIndex::nHeight, and ProcessBlock().
Referenced by CDSNotificationInterface::UpdatedBlockTip().
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodePayments::ADD_SERIALIZE_METHODS
Definition at line 186 of file masternode-payments.h.
mapMasternodeBlocks
std::map<int, CMasternodeBlockPayees> CMasternodePayments::mapMasternodeBlocks
Definition at line 180 of file masternode-payments.h.
Referenced by AddPaymentVote(), AlreadyHave(), CheckAndRemove(), CheckPreviousBlockVotes(), Clear(), GetBlockCount(), GetBlockPayee(), GetRequiredPaymentsString(), IsScheduled(), IsTransactionValid(), ProcessGetData(), RequestLowDataPaymentBlocks(), SerializationOp(), Sync(), ToString(), and CMasternode::UpdateLastPaid().
mapMasternodePaymentVotes
std::map<uint256, CMasternodePaymentVote> CMasternodePayments::mapMasternodePaymentVotes
Definition at line 179 of file masternode-payments.h.
Referenced by AddPaymentVote(), AlreadyHave(), CheckAndRemove(), CheckPreviousBlockVotes(), Clear(), GetVoteCount(), HasVerifiedPaymentVote(), ProcessGetData(), ProcessMessage(), SerializationOp(), and ToString().
mapMasternodesDidNotVote
std::map<COutPoint, int> CMasternodePayments::mapMasternodesDidNotVote
Definition at line 182 of file masternode-payments.h.
Referenced by CheckPreviousBlockVotes().
mapMasternodesLastVote
std::map<COutPoint, int> CMasternodePayments::mapMasternodesLastVote
Definition at line 181 of file masternode-payments.h.
Referenced by CanVote().
nCachedBlockHeight
int CMasternodePayments::nCachedBlockHeight private
Definition at line 176 of file masternode-payments.h.
Referenced by CheckAndRemove(), IsScheduled(), ProcessMessage(), RequestLowDataPaymentBlocks(), Sync(), and UpdatedBlockTip().
nMinBlocksToStore
const int CMasternodePayments::nMinBlocksToStore private
Definition at line 173 of file masternode-payments.h.
Referenced by GetStorageLimit().
nStorageCoeff
const float CMasternodePayments::nStorageCoeff private
Definition at line 171 of file masternode-payments.h.
Referenced by GetStorageLimit().
The documentation for this class was generated from the following files:
src/masternode-payments.h
src/masternode-payments.cpp
Released under the MIT license