Dash Core: llmq::CSigSharesNodeState Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CSigSharesNodeState Class Reference
#include <quorums_signing_shares.h>
Classes
struct Session
struct SessionInfo
Public Member Functions
Session & GetOrCreateSessionFromShare (const CSigShare &sigShare)
Session & GetOrCreateSessionFromAnn (const CSigSesAnn &ann)
Session * GetSessionBySignHash (const uint256 &signHash)
Session * GetSessionByRecvId (uint32_t sessionId)
bool GetSessionInfoByRecvId (uint32_t sessionId, SessionInfo &retInfo)
void RemoveSession (const uint256 &signHash)
Public Attributes
std::unordered_map< uint256, Session, StaticSaltedHasher > sessions
std::unordered_map< uint32_t, Session * > sessionByRecvId
uint32_t nextSendSessionId {1}
SigShareMap< CSigShare > pendingIncomingSigShares
SigShareMap< int64_t > requestedSigShares
bool banned {false}
Detailed Description
Definition at line 294 of file quorums_signing_shares.h.
Member Function Documentation
GetOrCreateSessionFromAnn()
CSigSharesNodeState::Session & llmq::CSigSharesNodeState::GetOrCreateSessionFromAnn (const CSigSesAnn & ann)
Definition at line 128 of file quorums_signing_shares.cpp.
References llmq::CLLMQUtils::BuildSignHash(), llmq::CSigSesAnn::id, llmq::InitSession(), llmq::CSigSesAnn::llmqType, llmq::CSigSesAnn::msgHash, llmq::CSigSesAnn::quorumHash, and sessions.
GetOrCreateSessionFromShare()
CSigSharesNodeState::Session & llmq::CSigSharesNodeState::GetOrCreateSessionFromShare (const CSigShare & sigShare)
Definition at line 119 of file quorums_signing_shares.cpp.
References llmq::CSigShare::GetSignHash(), llmq::InitSession(), and sessions.
GetSessionByRecvId()
CSigSharesNodeState::Session * llmq::CSigSharesNodeState::GetSessionByRecvId (uint32_t sessionId)
Definition at line 147 of file quorums_signing_shares.cpp.
References sessionByRecvId.
Referenced by GetSessionInfoByRecvId().
GetSessionBySignHash()
CSigSharesNodeState::Session * llmq::CSigSharesNodeState::GetSessionBySignHash (const uint256 & signHash)
Definition at line 138 of file quorums_signing_shares.cpp.
References sessions.
Referenced by llmq::CSigSharesManager::ForceReAnnouncement().
GetSessionInfoByRecvId()
bool llmq::CSigSharesNodeState::GetSessionInfoByRecvId (uint32_t sessionId, SessionInfo & retInfo)
Definition at line 156 of file quorums_signing_shares.cpp.
References GetSessionByRecvId(), llmq::CSigSharesNodeState::SessionInfo::id, llmq::CSigSharesNodeState::SessionInfo::llmqType, llmq::CSigSharesNodeState::SessionInfo::msgHash, llmq::CSigSharesNodeState::SessionInfo::quorum, llmq::CSigSharesNodeState::SessionInfo::quorumHash, and llmq::CSigSharesNodeState::SessionInfo::signHash.
RemoveSession()
void llmq::CSigSharesNodeState::RemoveSession (const uint256 & signHash)
Definition at line 172 of file quorums_signing_shares.cpp.
References llmq::SigShareMap< T >::EraseAllForSignHash(), pendingIncomingSigShares, requestedSigShares, sessionByRecvId, and sessions.
Member Data Documentation
banned
bool llmq::CSigSharesNodeState::banned {false}
Definition at line 334 of file quorums_signing_shares.h.
nextSendSessionId
uint32_t llmq::CSigSharesNodeState::nextSendSessionId {1}
Definition at line 329 of file quorums_signing_shares.h.
pendingIncomingSigShares
SigShareMap<CSigShare> llmq::CSigSharesNodeState::pendingIncomingSigShares
Definition at line 331 of file quorums_signing_shares.h.
Referenced by RemoveSession().
requestedSigShares
SigShareMap<int64_t> llmq::CSigSharesNodeState::requestedSigShares
Definition at line 332 of file quorums_signing_shares.h.
Referenced by RemoveSession().
sessionByRecvId
std::unordered_map<uint32_t, Session*> llmq::CSigSharesNodeState::sessionByRecvId
Definition at line 328 of file quorums_signing_shares.h.
Referenced by GetSessionByRecvId(), and RemoveSession().
sessions
std::unordered_map<uint256, Session, StaticSaltedHasher> llmq::CSigSharesNodeState::sessions
Definition at line 326 of file quorums_signing_shares.h.
Referenced by GetOrCreateSessionFromAnn(), GetOrCreateSessionFromShare(), GetSessionBySignHash(), and RemoveSession().
The documentation for this class was generated from the following files:
src/llmq/quorums_signing_shares.h
src/llmq/quorums_signing_shares.cpp
Released under the MIT license