Dash Core: llmq::CSigSharesInv Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CSigSharesInv Class Reference
#include <quorums_signing_shares.h>
Public Member Functions
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
void Init (size_t size)
bool IsSet (uint16_t quorumMember) const
void Set (uint16_t quorumMember, bool v)
void SetAll (bool v)
void Merge (const CSigSharesInv &inv2)
size_t CountSet () const
std::string ToString () const
Public Attributes
uint32_t sessionId {(uint32_t)-1}
std::vector< bool > inv
Detailed Description
Definition at line 100 of file quorums_signing_shares.h.
Member Function Documentation
CountSet()
size_t llmq::CSigSharesInv::CountSet () const
Definition at line 45 of file quorums_signing_shares.cpp.
References count, and inv.
Init()
void llmq::CSigSharesInv::Init (size_t size)
Definition at line 69 of file quorums_signing_shares.cpp.
References inv.
Referenced by llmq::InitSession(), and llmq::CBatchedSigShares::ToInvString().
IsSet()
bool llmq::CSigSharesInv::IsSet (uint16_t quorumMember) const
Definition at line 74 of file quorums_signing_shares.cpp.
References inv.
Merge()
void llmq::CSigSharesInv::Merge (const CSigSharesInv & inv2)
Definition at line 36 of file quorums_signing_shares.cpp.
References inv.
SerializationOp()
template<typename Stream , typename Operation > ADD_SERIALIZE_METHODS void llmq::CSigSharesInv::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 110 of file quorums_signing_shares.h.
References AUTOBITSET, COMPACTSIZE, inv, READWRITE, sessionId, and VARINT.
Set()
void llmq::CSigSharesInv::Set (uint16_t quorumMember, bool v)
Definition at line 80 of file quorums_signing_shares.cpp.
References inv.
SetAll()
void llmq::CSigSharesInv::SetAll (bool v)
Definition at line 86 of file quorums_signing_shares.cpp.
References inv.
Referenced by llmq::CSigSharesManager::ForceReAnnouncement().
ToString()
std::string llmq::CSigSharesInv::ToString () const
Definition at line 50 of file quorums_signing_shares.cpp.
References inv, and strprintf.
Referenced by llmq::CSigSharesManager::ProcessMessageGetSigShares(), llmq::CSigSharesManager::ProcessMessageSigSharesInv(), and llmq::CBatchedSigShares::ToInvString().
Member Data Documentation
inv
std::vector<bool> llmq::CSigSharesInv::inv
Definition at line 104 of file quorums_signing_shares.h.
Referenced by CountSet(), Init(), IsSet(), Merge(), SerializationOp(), Set(), SetAll(), llmq::CBatchedSigShares::ToInvString(), ToString(), and llmq::CSigSharesManager::VerifySigSharesInv().
sessionId
uint32_t llmq::CSigSharesInv::sessionId {(uint32_t)-1}
Definition at line 103 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::ProcessMessageGetSigShares(), llmq::CSigSharesManager::ProcessMessageSigSharesInv(), and SerializationOp().
The documentation for this class was generated from the following files:
src/llmq/quorums_signing_shares.h
src/llmq/quorums_signing_shares.cpp
Released under the MIT license