Dash Core: CHDChain Class Reference
CHDChain Class Reference
#include <hdchain.h>
Public Member Functions
CHDChain ()
CHDChain (const CHDChain &other)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
void swap (CHDChain &first, CHDChain &second)
CHDChain & operator= (CHDChain from)
bool SetNull ()
bool IsNull () const
void SetCrypted (bool fCryptedIn)
bool IsCrypted () const
void Debug (std::string strName) const
bool SetMnemonic (const SecureVector &vchMnemonic, const SecureVector &vchMnemonicPassphrase, bool fUpdateID)
bool SetMnemonic (const SecureString &ssMnemonic, const SecureString &ssMnemonicPassphrase, bool fUpdateID)
bool GetMnemonic (SecureVector &vchMnemonicRet, SecureVector &vchMnemonicPassphraseRet) const
bool GetMnemonic (SecureString &ssMnemonicRet, SecureString &ssMnemonicPassphraseRet) const
bool SetSeed (const SecureVector &vchSeedIn, bool fUpdateID)
SecureVector GetSeed () const
uint256 GetID () const
uint256 GetSeedHash ()
void DeriveChildExtKey (uint32_t nAccountIndex, bool fInternal, uint32_t nChildIndex, CExtKey &extKeyRet)
void AddAccount ()
bool GetAccount (uint32_t nAccountIndex, CHDAccount &hdAccountRet)
bool SetAccount (uint32_t nAccountIndex, const CHDAccount &hdAccount)
size_t CountAccounts ()
Public Attributes
ADD_SERIALIZE_METHODS
Private Attributes
int nVersion
uint256 id
bool fCrypted
SecureVector vchSeed
SecureVector vchMnemonic
SecureVector vchMnemonicPassphrase
std::map< uint32_t, CHDAccount > mapAccounts
CCriticalSection cs_accounts
Static Private Attributes
static const int CURRENT_VERSION = 1
Detailed Description
Definition at line 28 of file hdchain.h.
Constructor & Destructor Documentation
CHDChain() [1/2]
CHDChain::CHDChain () inline
Definition at line 48 of file hdchain.h.
CHDChain() [2/2]
CHDChain::CHDChain (const CHDChain & other) inline
Definition at line 49 of file hdchain.h.
Member Function Documentation
AddAccount()
void CHDChain::AddAccount ()
Definition at line 178 of file hdchain.cpp.
CountAccounts()
size_t CHDChain::CountAccounts ()
Definition at line 203 of file hdchain.cpp.
Referenced by dumpwallet(), and getwalletinfo().
Debug()
void CHDChain::Debug (std::string strName) const
Definition at line 42 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), CCryptoKeyStore::EncryptHDChain(), and CWallet::GenerateNewHDChain().
DeriveChildExtKey()
void CHDChain::DeriveChildExtKey (uint32_t nAccountIndex, bool fInternal, uint32_t nChildIndex, CExtKey & extKeyRet)
Definition at line 151 of file hdchain.cpp.
Referenced by CWallet::DeriveNewChildKey(), and CWallet::GetKey().
GetAccount()
bool CHDChain::GetAccount (uint32_t nAccountIndex, CHDAccount & hdAccountRet)
Definition at line 184 of file hdchain.cpp.
Referenced by CWallet::DeriveNewChildKey(), dumpwallet(), and getwalletinfo().
GetID()
uint256 CHDChain::GetID () const inline
Definition at line 111 of file hdchain.h.
Referenced by CWallet::AddHDPubKey(), CCryptoKeyStore::DecryptHDChain(), CWallet::DeriveNewChildKey(), CCryptoKeyStore::EncryptHDChain(), CWallet::EncryptWallet(), CWallet::GetDecryptedHDChain(), CWallet::GetKey(), getwalletinfo(), CCryptoKeyStore::Unlock(), and validateaddress().
GetMnemonic() [1/2]
bool CHDChain::GetMnemonic (SecureVector & vchMnemonicRet, SecureVector & vchMnemonicPassphraseRet) const
Definition at line 107 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), dumphdinfo(), dumpwallet(), and CCryptoKeyStore::EncryptHDChain().
GetMnemonic() [2/2]
bool CHDChain::GetMnemonic (SecureString & ssMnemonicRet, SecureString & ssMnemonicPassphraseRet) const
Definition at line 118 of file hdchain.cpp.
GetSeed()
SecureVector CHDChain::GetSeed () const
Definition at line 141 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), dumphdinfo(), dumpwallet(), CCryptoKeyStore::EncryptHDChain(), and CWallet::EncryptWallet().
GetSeedHash()
uint256 CHDChain::GetSeedHash ()
Definition at line 146 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), CWallet::DeriveNewChildKey(), CCryptoKeyStore::EncryptHDChain(), CWallet::EncryptWallet(), CWallet::GetDecryptedHDChain(), CWallet::GetKey(), SetMnemonic(), SetSeed(), and CCryptoKeyStore::Unlock().
IsCrypted()
bool CHDChain::IsCrypted () const
Definition at line 37 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), CCryptoKeyStore::EncryptHDChain(), CCryptoKeyStore::SetCryptedHDChain(), and CCryptoKeyStore::SetHDChain().
IsNull()
bool CHDChain::IsNull () const
Definition at line 27 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), CCryptoKeyStore::EncryptHDChain(), CWallet::EncryptWallet(), CBasicKeyStore::GetHDChain(), CCryptoKeyStore::GetHDChain(), SetMnemonic(), SetNull(), SetSeed(), and CCryptoKeyStore::Unlock().
operator=()
CHDChain& CHDChain::operator= (CHDChain from) inline
Definition at line 89 of file hdchain.h.
SerializationOp()
template<typename Stream , typename Operation > void CHDChain::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 61 of file hdchain.h.
SetAccount()
bool CHDChain::SetAccount (uint32_t nAccountIndex, const CHDAccount & hdAccount)
Definition at line 193 of file hdchain.cpp.
Referenced by CWallet::DeriveNewChildKey().
SetCrypted()
void CHDChain::SetCrypted (bool fCryptedIn)
Definition at line 32 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), and CCryptoKeyStore::EncryptHDChain().
SetMnemonic() [1/2]
bool CHDChain::SetMnemonic (const SecureVector & vchMnemonic, const SecureVector & vchMnemonicPassphrase, bool fUpdateID)
Definition at line 72 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), CCryptoKeyStore::EncryptHDChain(), and CWallet::GenerateNewHDChain().
SetMnemonic() [2/2]
bool CHDChain::SetMnemonic (const SecureString & ssMnemonic, const SecureString & ssMnemonicPassphrase, bool fUpdateID)
Definition at line 77 of file hdchain.cpp.
SetNull()
bool CHDChain::SetNull ()
Definition at line 12 of file hdchain.cpp.
Referenced by CHDChain(), and CCryptoKeyStore::EncryptHDChain().
SetSeed()
bool CHDChain::SetSeed (const SecureVector & vchSeedIn, bool fUpdateID)
Definition at line 130 of file hdchain.cpp.
Referenced by CCryptoKeyStore::DecryptHDChain(), CCryptoKeyStore::EncryptHDChain(), and CWallet::GenerateNewHDChain().
swap()
void CHDChain::swap (CHDChain & first, CHDChain & second) inline
Definition at line 74 of file hdchain.h.
Referenced by operator=().
Member Data Documentation
ADD_SERIALIZE_METHODS
CHDChain::ADD_SERIALIZE_METHODS
Definition at line 59 of file hdchain.h.
cs_accounts
CCriticalSection CHDChain::cs_accounts mutable private
Definition at line 44 of file hdchain.h.
Referenced by AddAccount(), CountAccounts(), GetAccount(), SerializationOp(), SetAccount(), and SetNull().
CURRENT_VERSION
const int CHDChain::CURRENT_VERSION = 1 static private
Definition at line 31 of file hdchain.h.
Referenced by SetNull().
fCrypted
bool CHDChain::fCrypted private
Definition at line 36 of file hdchain.h.
Referenced by Debug(), IsCrypted(), SetCrypted(), SetNull(), and swap().
id
uint256 CHDChain::id private
Definition at line 34 of file hdchain.h.
Referenced by GetID(), and swap().
mapAccounts
std::map<uint32_t, CHDAccount> CHDChain::mapAccounts private
Definition at line 42 of file hdchain.h.
Referenced by AddAccount(), CountAccounts(), GetAccount(), SerializationOp(), SetAccount(), SetNull(), and swap().
nVersion
int CHDChain::nVersion private
Definition at line 32 of file hdchain.h.
Referenced by SerializationOp(), SetNull(), and swap().
vchMnemonic
SecureVector CHDChain::vchMnemonic private
Definition at line 39 of file hdchain.h.
Referenced by Debug(), GetMnemonic(), SerializationOp(), SetMnemonic(), SetNull(), and swap().
vchMnemonicPassphrase
SecureVector CHDChain::vchMnemonicPassphrase private
Definition at line 40 of file hdchain.h.
Referenced by Debug(), GetMnemonic(), SerializationOp(), SetMnemonic(), SetNull(), and swap().
vchSeed
SecureVector CHDChain::vchSeed private
Definition at line 38 of file hdchain.h.
Referenced by Debug(), DeriveChildExtKey(), GetSeed(), GetSeedHash(), IsNull(), SerializationOp(), SetMnemonic(), SetNull(), SetSeed(), and swap().
The documentation for this class was generated from the following files:
src/hdchain.h
src/hdchain.cpp