Dash Core: CEvoDBScopedCommitter Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CEvoDBScopedCommitter Class Reference
#include <evodb.h>
Public Member Functions
CEvoDBScopedCommitter (CEvoDB &_evoDB)
~CEvoDBScopedCommitter ()
void Commit ()
void Rollback ()
Private Attributes
CEvoDB & evoDB
bool didCommitOrRollback {false}
Detailed Description
Definition at line 18 of file evodb.h.
Constructor & Destructor Documentation
CEvoDBScopedCommitter()
CEvoDBScopedCommitter::CEvoDBScopedCommitter (CEvoDB & _evoDB) explicit
Definition at line 9 of file evodb.cpp.
~CEvoDBScopedCommitter()
CEvoDBScopedCommitter::~CEvoDBScopedCommitter ()
Definition at line 14 of file evodb.cpp.
References didCommitOrRollback, and Rollback().
Member Function Documentation
Commit()
void CEvoDBScopedCommitter::Commit ()
Definition at line 20 of file evodb.cpp.
References CEvoDB::CommitCurTransaction(), didCommitOrRollback, and evoDB.
Rollback()
void CEvoDBScopedCommitter::Rollback ()
Definition at line 27 of file evodb.cpp.
References didCommitOrRollback, evoDB, and CEvoDB::RollbackCurTransaction().
Referenced by ~CEvoDBScopedCommitter().
Member Data Documentation
didCommitOrRollback
bool CEvoDBScopedCommitter::didCommitOrRollback {false} private
Definition at line 22 of file evodb.h.
Referenced by Commit(), Rollback(), and ~CEvoDBScopedCommitter().
evoDB
CEvoDB& CEvoDBScopedCommitter::evoDB private
Definition at line 21 of file evodb.h.
Referenced by Commit(), and Rollback().
The documentation for this class was generated from the following files:
src/evo/evodb.h
src/evo/evodb.cpp
Released under the MIT license