Dash Core: QValidatedLineEdit Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
QValidatedLineEdit Class Reference
Line edit that can be marked as "invalid" to show input validation feedback.
#include <qvalidatedlineedit.h>
Public Slots
void setValid (bool valid)
void setEnabled (bool enabled)
Signals
void validationDidChange (QValidatedLineEdit *validatedLineEdit)
Public Member Functions
QValidatedLineEdit (QWidget *parent)
void clear ()
void setCheckValidator (const QValidator *v)
bool isValid ()
Protected Member Functions
void focusInEvent (QFocusEvent *evt)
void focusOutEvent (QFocusEvent *evt)
Private Slots
void markValid ()
void checkValidity ()
Private Attributes
bool valid
const QValidator * checkValidator
Detailed Description
Line edit that can be marked as "invalid" to show input validation feedback.
When marked as invalid, it will get a red background until it is focused.
Definition at line 13 of file qvalidatedlineedit.h.
Constructor & Destructor Documentation
QValidatedLineEdit()
QValidatedLineEdit::QValidatedLineEdit (QWidget * parent) explicit
Definition at line 10 of file qvalidatedlineedit.cpp.
References markValid().
Member Function Documentation
checkValidity
void QValidatedLineEdit::checkValidity () private slot
Definition at line 79 of file qvalidatedlineedit.cpp.
References checkValidator, setValid(), and validationDidChange().
Referenced by focusOutEvent(), and setEnabled().
clear()
void QValidatedLineEdit::clear ()
Definition at line 57 of file qvalidatedlineedit.cpp.
References setValid().
focusInEvent()
void QValidatedLineEdit::focusInEvent (QFocusEvent * evt) protected
Definition at line 36 of file qvalidatedlineedit.cpp.
References setValid().
focusOutEvent()
void QValidatedLineEdit::focusOutEvent (QFocusEvent * evt) protected
Definition at line 44 of file qvalidatedlineedit.cpp.
References checkValidity().
isValid()
bool QValidatedLineEdit::isValid ()
Definition at line 111 of file qvalidatedlineedit.cpp.
References checkValidator, and valid.
Referenced by OptionsDialog::updateProxyValidationState().
markValid
void QValidatedLineEdit::markValid () private slot
Definition at line 51 of file qvalidatedlineedit.cpp.
References setValid().
Referenced by QValidatedLineEdit().
setCheckValidator()
void QValidatedLineEdit::setCheckValidator (const QValidator * v)
Definition at line 106 of file qvalidatedlineedit.cpp.
References checkValidator.
Referenced by GUIUtil::setupAddressWidget().
setEnabled
void QValidatedLineEdit::setEnabled (bool enabled) slot
Definition at line 63 of file qvalidatedlineedit.cpp.
References checkValidity(), and setValid().
setValid
void QValidatedLineEdit::setValid (bool valid) slot
Definition at line 18 of file qvalidatedlineedit.cpp.
References STYLE_INVALID, and valid.
Referenced by checkValidity(), clear(), focusInEvent(), markValid(), and setEnabled().
validationDidChange
void QValidatedLineEdit::validationDidChange (QValidatedLineEdit * validatedLineEdit) signal
Referenced by checkValidity().
Member Data Documentation
checkValidator
const QValidator* QValidatedLineEdit::checkValidator private
Definition at line 29 of file qvalidatedlineedit.h.
Referenced by checkValidity(), isValid(), and setCheckValidator().
valid
bool QValidatedLineEdit::valid private
Definition at line 28 of file qvalidatedlineedit.h.
Referenced by isValid(), and setValid().
The documentation for this class was generated from the following files:
src/qt/qvalidatedlineedit.h
src/qt/qvalidatedlineedit.cpp
Released under the MIT license