Dash Core: CDBIterator Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CDBIterator Class Reference
#include <dbwrapper.h>
Public Member Functions
CDBIterator (const CDBWrapper &_parent, leveldb::Iterator *_piter)
~CDBIterator ()
bool Valid ()
void SeekToFirst ()
template<typename K >
void Seek (const K &key)
void Next ()
template<typename K >
bool GetKey (K &key)
unsigned int GetKeySize ()
template<typename V >
bool GetValue (V &value)
unsigned int GetValueSize ()
Private Attributes
const CDBWrapper & parent
leveldb::Iterator * piter
Detailed Description
Definition at line 115 of file dbwrapper.h.
Constructor & Destructor Documentation
CDBIterator()
CDBIterator::CDBIterator (const CDBWrapper & _parent, leveldb::Iterator * _piter) inline
Parameters
[in] _parent Parent CDBWrapper instance.
[in] _piter The original leveldb iterator.
Definition at line 127 of file dbwrapper.h.
~CDBIterator()
CDBIterator::~CDBIterator ()
Definition at line 192 of file dbwrapper.cpp.
References piter.
Member Function Documentation
GetKey()
template<typename K > bool CDBIterator::GetKey (K & key) inline
Definition at line 145 of file dbwrapper.h.
References CLIENT_VERSION, piter, and SER_DISK.
GetKeySize()
unsigned int CDBIterator::GetKeySize () inline
Definition at line 156 of file dbwrapper.h.
References piter.
GetValue()
template<typename V > bool CDBIterator::GetValue (V & value) inline
Definition at line 160 of file dbwrapper.h.
References CLIENT_VERSION, dbwrapper_private::GetObfuscateKey(), parent, piter, SER_DISK, and CDataStream::Xor().
GetValueSize()
unsigned int CDBIterator::GetValueSize () inline
Definition at line 172 of file dbwrapper.h.
References piter.
Next()
void CDBIterator::Next ()
Definition at line 195 of file dbwrapper.cpp.
References piter.
Seek()
template<typename K > void CDBIterator::Seek (const K & key) inline
Definition at line 135 of file dbwrapper.h.
References CLIENT_VERSION, CDataStream::data(), DBWRAPPER_PREALLOC_KEY_SIZE, piter, CDataStream::reserve(), SER_DISK, and CDataStream::size().
SeekToFirst()
void CDBIterator::SeekToFirst ()
Definition at line 194 of file dbwrapper.cpp.
References piter.
Valid()
bool CDBIterator::Valid ()
Definition at line 193 of file dbwrapper.cpp.
References piter.
Member Data Documentation
parent
const CDBWrapper& CDBIterator::parent private
Definition at line 118 of file dbwrapper.h.
Referenced by GetValue().
piter
leveldb::Iterator* CDBIterator::piter private
Definition at line 119 of file dbwrapper.h.
Referenced by GetKey(), GetKeySize(), GetValue(), GetValueSize(), Next(), Seek(), SeekToFirst(), Valid(), and ~CDBIterator().
The documentation for this class was generated from the following files:
src/dbwrapper.h
src/dbwrapper.cpp
Released under the MIT license