Dash Core: ModalOverlay Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
ModalOverlay Class Reference
Modal overlay to display information about the chain-sync state.
#include <modaloverlay.h>
Public Slots
void tipUpdate (int count, const QDateTime &blockDate, double nVerificationProgress)
void setKnownBestHeight (int count, const QDateTime &blockDate)
void toggleVisibility ()
void showHide (bool hide=false, bool userRequested=false)
void closeClicked ()
void hideForever ()
bool isLayerVisible () const
Public Member Functions
ModalOverlay (QWidget *parent)
~ModalOverlay ()
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *ev)
bool event (QEvent *ev)
Tracks parent widget changes.
Private Attributes
Ui::ModalOverlay * ui
int bestHeaderHeight
QDateTime bestHeaderDate
QVector< QPair< qint64, double > > blockProcessTime
bool layerIsVisible
bool userClosed
bool foreverHidden
Detailed Description
Modal overlay to display information about the chain-sync state.
Definition at line 19 of file modaloverlay.h.
Constructor & Destructor Documentation
ModalOverlay()
ModalOverlay::ModalOverlay (QWidget * parent) explicit
Definition at line 15 of file modaloverlay.cpp.
References blockProcessTime, GUIUtil::Bold, closeClicked(), GUIUtil::getIcon(), GUIUtil::ORANGE, GUIUtil::setFont(), ui, and GUIUtil::updateFonts().
~ModalOverlay()
ModalOverlay::~ModalOverlay ()
Definition at line 48 of file modaloverlay.cpp.
References ui.
Member Function Documentation
closeClicked
void ModalOverlay::closeClicked () slot
Definition at line 187 of file modaloverlay.cpp.
References showHide(), and userClosed.
Referenced by ModalOverlay().
event()
bool ModalOverlay::event (QEvent * ev) protected
Tracks parent widget changes.
Definition at line 70 of file modaloverlay.cpp.
eventFilter()
bool ModalOverlay::eventFilter (QObject * obj, QEvent * ev) protected
Definition at line 53 of file modaloverlay.cpp.
References layerIsVisible.
hideForever
void ModalOverlay::hideForever () slot
Definition at line 193 of file modaloverlay.cpp.
References foreverHidden.
Referenced by BitcoinGUI::setNumBlocks().
isLayerVisible
bool ModalOverlay::isLayerVisible () const inline slot
Definition at line 36 of file modaloverlay.h.
References layerIsVisible.
Referenced by BitcoinGUI::showModalOverlay().
setKnownBestHeight
void ModalOverlay::setKnownBestHeight (int count, const QDateTime & blockDate) slot
Definition at line 83 of file modaloverlay.cpp.
References bestHeaderDate, bestHeaderHeight, and count.
Referenced by BitcoinGUI::setClientModel(), and BitcoinGUI::setNumBlocks().
showHide
void ModalOverlay::showHide (bool hide = false, bool userRequested = false) slot
Definition at line 165 of file modaloverlay.cpp.
References foreverHidden, layerIsVisible, and userClosed.
Referenced by closeClicked(), BitcoinGUI::setNumBlocks(), and toggleVisibility().
tipUpdate
void ModalOverlay::tipUpdate (int count, const QDateTime & blockDate, double nVerificationProgress) slot
Definition at line 91 of file modaloverlay.cpp.
References bestHeaderDate, bestHeaderHeight, blockProcessTime, count, GUIUtil::formatNiceTimeOffset(), CChainParams::GetConsensus(), HEADER_HEIGHT_DELTA_SYNC, Consensus::Params::nPowTargetSpacing, Params(), and ui.
Referenced by BitcoinGUI::setNumBlocks().
toggleVisibility
void ModalOverlay::toggleVisibility () slot
Definition at line 158 of file modaloverlay.cpp.
References layerIsVisible, showHide(), and userClosed.
Referenced by BitcoinGUI::showModalOverlay().
Member Data Documentation
bestHeaderDate
QDateTime ModalOverlay::bestHeaderDate private
Definition at line 45 of file modaloverlay.h.
Referenced by setKnownBestHeight(), and tipUpdate().
bestHeaderHeight
int ModalOverlay::bestHeaderHeight private
Definition at line 44 of file modaloverlay.h.
Referenced by setKnownBestHeight(), and tipUpdate().
blockProcessTime
QVector<QPair<qint64, double> > ModalOverlay::blockProcessTime private
Definition at line 46 of file modaloverlay.h.
Referenced by ModalOverlay(), and tipUpdate().
foreverHidden
bool ModalOverlay::foreverHidden private
Definition at line 49 of file modaloverlay.h.
Referenced by hideForever(), and showHide().
layerIsVisible
bool ModalOverlay::layerIsVisible private
Definition at line 47 of file modaloverlay.h.
Referenced by eventFilter(), isLayerVisible(), showHide(), and toggleVisibility().
ui
Ui::ModalOverlay* ModalOverlay::ui private
Definition at line 43 of file modaloverlay.h.
Referenced by ModalOverlay(), tipUpdate(), and ~ModalOverlay().
userClosed
bool ModalOverlay::userClosed private
Definition at line 48 of file modaloverlay.h.
Referenced by closeClicked(), showHide(), and toggleVisibility().
The documentation for this class was generated from the following files:
src/qt/modaloverlay.h
src/qt/modaloverlay.cpp
Released under the MIT license