Dash Core: CClientUIInterface Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CClientUIInterface Class Reference
Signals for UI communication.
#include <ui_interface.h>
Public Types
enum MessageBoxFlags {
ICON_INFORMATION = 0, ICON_WARNING = (1U << 0), ICON_ERROR = (1U << 1), ICON_MASK = (ICON_INFORMATION | ICON_WARNING | ICON_ERROR),
BTN_OK = 0x00000400U, BTN_YES = 0x00004000U, BTN_NO = 0x00010000U, BTN_ABORT = 0x00040000U,
BTN_RETRY = 0x00080000U, BTN_IGNORE = 0x00100000U, BTN_CLOSE = 0x00200000U, BTN_CANCEL = 0x00400000U,
BTN_DISCARD = 0x00800000U, BTN_HELP = 0x01000000U, BTN_APPLY = 0x02000000U, BTN_RESET = 0x04000000U,
BTN_MASK, MODAL = 0x10000000U, SECURE = 0x40000000U, MSG_INFORMATION = ICON_INFORMATION,
MSG_WARNING = (ICON_WARNING | BTN_OK | MODAL), MSG_ERROR = (ICON_ERROR | BTN_OK | MODAL)
}
Flags for CClientUIInterface::ThreadSafeMessageBox.
Public Attributes
boost::signals2::signal< bool(const std::string &message, const std::string &caption, unsigned int style), boost::signals2::last_value< bool > > ThreadSafeMessageBox
Show message box.
boost::signals2::signal< bool(const std::string &message, const std::string &noninteractive_message, const std::string &caption, unsigned int style), boost::signals2::last_value< bool > > ThreadSafeQuestion
If possible, ask the user a question.
boost::signals2::signal< void(const std::string &message)> InitMessage
Progress message during initialization.
boost::signals2::signal< void(int newNumConnections)> NotifyNumConnectionsChanged
Number of network connections changed.
boost::signals2::signal< void(bool networkActive)> NotifyNetworkActiveChanged
Network activity state changed.
boost::signals2::signal< void()> NotifyAlertChanged
Status bar alerts changed.
boost::signals2::signal< void(CWallet *wallet)> LoadWallet
A wallet has been loaded.
boost::signals2::signal< void(const std::string &title, int nProgress, bool resume_possible)> ShowProgress
Show progress e.g.
boost::signals2::signal< void(bool, const CBlockIndex *)> NotifyBlockTip
New block has been accepted.
boost::signals2::signal< void(bool, const CBlockIndex *)> NotifyHeaderTip
Best header has changed.
boost::signals2::signal< void(const CDeterministicMNList &)> NotifyMasternodeListChanged
Masternode list has changed.
boost::signals2::signal< void(double nSyncProgress)> NotifyAdditionalDataSyncProgressChanged
Additional data sync progress changed.
boost::signals2::signal< void(void)> BannedListChanged
Banlist did change.
Detailed Description
Signals for UI communication.
Definition at line 28 of file ui_interface.h.
Member Enumeration Documentation
MessageBoxFlags
enum CClientUIInterface::MessageBoxFlags
Flags for CClientUIInterface::ThreadSafeMessageBox.
Enumerator
ICON_INFORMATION
ICON_WARNING
ICON_ERROR
ICON_MASK
Mask of all available icons in CClientUIInterface::MessageBoxFlags This needs to be updated, when icons are changed there!
BTN_OK
These values are taken from qmessagebox.h "enum StandardButton" to be directly usable.
BTN_YES
BTN_NO
BTN_ABORT
BTN_RETRY
BTN_IGNORE
BTN_CLOSE
BTN_CANCEL
BTN_DISCARD
BTN_HELP
BTN_APPLY
BTN_RESET
BTN_MASK
Mask of all available buttons in CClientUIInterface::MessageBoxFlags This needs to be updated, when buttons are changed there!
MODAL
Force blocking, modal message box dialog (not just OS notification)
SECURE
Do not print contents of message to debug log.
MSG_INFORMATION
Predefined combinations for certain default usage cases.
MSG_WARNING
MSG_ERROR
Definition at line 32 of file ui_interface.h.
Member Data Documentation
BannedListChanged
boost::signals2::signal<void (void)> CClientUIInterface::BannedListChanged
Banlist did change.
Definition at line 117 of file ui_interface.h.
Referenced by CConnman::Ban(), CConnman::ClearBanned(), ClientModel::subscribeToCoreSignals(), CConnman::SweepBanned(), CConnman::Unban(), and ClientModel::unsubscribeFromCoreSignals().
InitMessage
boost::signals2::signal<void (const std::string &message)> CClientUIInterface::InitMessage
Progress message during initialization.
Definition at line 82 of file ui_interface.h.
Referenced by AppInitMain(), CWallet::CreateWalletFromFile(), main(), noui_connect(), CConnman::Start(), SplashScreen::subscribeToCoreSignals(), CWallet::TopUpKeyPool(), SplashScreen::unsubscribeFromCoreSignals(), and WalletInit::Verify().
LoadWallet
boost::signals2::signal<void (CWallet* wallet)> CClientUIInterface::LoadWallet
A wallet has been loaded.
Definition at line 96 of file ui_interface.h.
Referenced by CWallet::CreateWalletFromFile(), SplashScreen::subscribeToCoreSignals(), and SplashScreen::unsubscribeFromCoreSignals().
NotifyAdditionalDataSyncProgressChanged
boost::signals2::signal<void (double nSyncProgress)> CClientUIInterface::NotifyAdditionalDataSyncProgressChanged
Additional data sync progress changed.
Definition at line 114 of file ui_interface.h.
Referenced by CMasternodeSync::ProcessTick(), CMasternodeSync::Reset(), ClientModel::subscribeToCoreSignals(), CMasternodeSync::SwitchToNextAsset(), and ClientModel::unsubscribeFromCoreSignals().
NotifyAlertChanged
boost::signals2::signal<void ()> CClientUIInterface::NotifyAlertChanged
Status bar alerts changed.
Definition at line 93 of file ui_interface.h.
Referenced by AlertNotify(), ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyBlockTip
boost::signals2::signal<void (bool, const CBlockIndex *)> CClientUIInterface::NotifyBlockTip
New block has been accepted.
Definition at line 105 of file ui_interface.h.
Referenced by CChainState::ActivateBestChain(), AppInitMain(), CChainState::InvalidateBlock(), OnRPCStarted(), OnRPCStopped(), ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyHeaderTip
boost::signals2::signal<void (bool, const CBlockIndex *)> CClientUIInterface::NotifyHeaderTip
Best header has changed.
Definition at line 108 of file ui_interface.h.
Referenced by NotifyHeaderTip(), ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyMasternodeListChanged
boost::signals2::signal<void (const CDeterministicMNList&)> CClientUIInterface::NotifyMasternodeListChanged
Masternode list has changed.
Definition at line 111 of file ui_interface.h.
Referenced by CDeterministicMNManager::ProcessBlock(), ClientModel::subscribeToCoreSignals(), CDeterministicMNManager::UndoBlock(), and ClientModel::unsubscribeFromCoreSignals().
NotifyNetworkActiveChanged
boost::signals2::signal<void (bool networkActive)> CClientUIInterface::NotifyNetworkActiveChanged
Network activity state changed.
Definition at line 88 of file ui_interface.h.
Referenced by CConnman::SetNetworkActive(), ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyNumConnectionsChanged
boost::signals2::signal<void (int newNumConnections)> CClientUIInterface::NotifyNumConnectionsChanged
Number of network connections changed.
Definition at line 85 of file ui_interface.h.
Referenced by CConnman::NotifyNumConnectionsChanged(), ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
ShowProgress
boost::signals2::signal<void (const std::string &title, int nProgress, bool resume_possible)> CClientUIInterface::ShowProgress
Show progress e.g.
for verifychain. resume_possible indicates shutting down now will result in the current progress action resuming upon restart.
Definition at line 102 of file ui_interface.h.
Referenced by CVerifyDB::CVerifyDB(), CChainState::ReplayBlocks(), SplashScreen::subscribeToCoreSignals(), ClientModel::subscribeToCoreSignals(), SplashScreen::unsubscribeFromCoreSignals(), ClientModel::unsubscribeFromCoreSignals(), CCoinsViewDB::Upgrade(), CVerifyDB::VerifyDB(), and CVerifyDB::~CVerifyDB().
ThreadSafeMessageBox
boost::signals2::signal<bool (const std::string& message, const std::string& caption, unsigned int style), boost::signals2::last_value<bool> > CClientUIInterface::ThreadSafeMessageBox
Show message box.
Definition at line 76 of file ui_interface.h.
Referenced by AddTimeData(), CConnman::Bind(), CCoinsViewErrorCatcher::GetCoin(), InitError(), InitHTTPAllowList(), InitHTTPServer(), InitRPCAuthentication(), InitWarning(), noui_connect(), CConnman::Start(), BitcoinGUI::subscribeToCoreSignals(), and BitcoinGUI::unsubscribeFromCoreSignals().
ThreadSafeQuestion
boost::signals2::signal<bool (const std::string& message, const std::string& noninteractive_message, const std::string& caption, unsigned int style), boost::signals2::last_value<bool> > CClientUIInterface::ThreadSafeQuestion
If possible, ask the user a question.
If not, falls back to ThreadSafeMessageBox(noninteractive_message, caption, style) and returns false.
Definition at line 79 of file ui_interface.h.
Referenced by AppInitMain(), noui_connect(), BitcoinGUI::subscribeToCoreSignals(), and BitcoinGUI::unsubscribeFromCoreSignals().
The documentation for this class was generated from the following file:
src/ui_interface.h
Released under the MIT license