Dash Core: prevector< N, T, Size, Diff > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
prevector< N, T, Size, Diff > Class Template Reference
Implements a drop-in replacement for std::vector<T> which stores up to N elements directly (without heap allocation).
#include <prevector.h>
Classes
class const_iterator
class const_reverse_iterator
union direct_or_indirect
class iterator
class reverse_iterator
Public Types
typedef Size size_type
typedef Diff difference_type
typedef T value_type
typedef value_type & reference
typedef const value_type & const_reference
typedef value_type * pointer
typedef const value_type * const_pointer
Public Member Functions
void assign (size_type n, const T &val)
template<typename InputIterator >
void assign (InputIterator first, InputIterator last)
prevector ()
prevector (size_type n)
prevector (size_type n, const T &val=T())
template<typename InputIterator >
prevector (InputIterator first, InputIterator last)
prevector (const prevector< N, T, Size, Diff > &other)
prevector (prevector< N, T, Size, Diff > &&other)
prevector & operator= (const prevector< N, T, Size, Diff > &other)
prevector & operator= (prevector< N, T, Size, Diff > &&other)
size_type size () const
bool empty () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t capacity () const
T & operator[] (size_type pos)
const T & operator[] (size_type pos) const
void resize (size_type new_size)
void reserve (size_type new_capacity)
void shrink_to_fit ()
void clear ()
iterator insert (iterator pos, const T &value)
void insert (iterator pos, size_type count, const T &value)
template<typename InputIterator >
void insert (iterator pos, InputIterator first, InputIterator last)
void resize_uninitialized (size_type new_size)
iterator erase (iterator pos)
iterator erase (iterator first, iterator last)
void push_back (const T &value)
void pop_back ()
T & front ()
const T & front () const
T & back ()
const T & back () const
void swap (prevector< N, T, Size, Diff > &other)
~prevector ()
bool operator== (const prevector< N, T, Size, Diff > &other) const
bool operator!= (const prevector< N, T, Size, Diff > &other) const
bool operator< (const prevector< N, T, Size, Diff > &other) const
size_t allocated_memory () const
value_type * data ()
const value_type * data () const
Static Public Member Functions
template<typename V >
static void assign_to (const_iterator b, const_iterator e, V &v)
Private Member Functions
T * direct_ptr (difference_type pos)
const T * direct_ptr (difference_type pos) const
T * indirect_ptr (difference_type pos)
const T * indirect_ptr (difference_type pos) const
bool is_direct () const
void change_capacity (size_type new_capacity)
T * item_ptr (difference_type pos)
const T * item_ptr (difference_type pos) const
void fill (T *dst, ptrdiff_t count)
void fill (T *dst, ptrdiff_t count, const T &value)
template<typename InputIterator >
void fill (T *dst, InputIterator first, InputIterator last)
void fill (T *dst, const_iterator first, const_iterator last)
void fill (T *dst, const T *src, ptrdiff_t count)
Private Attributes
size_type _size
union prevector::direct_or_indirect _union
Detailed Description
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t>
class prevector< N, T, Size, Diff >
Implements a drop-in replacement for std::vector<T> which stores up to N elements directly (without heap allocation).
The types Size and Diff are used to store element counts, and can be any unsigned + signed type.
Storage layout is either:
Direct allocation:
Size _size: the number of used elements (between 0 and N)
T direct[N]: an array of N elements of type T (only the first _size are initialized).
Indirect allocation:
Size _size: the number of used elements plus N + 1
Size capacity: the number of allocated elements
T* indirect: a pointer to an array of capacity elements of type T (only the first _size are initialized).
The data type T must be movable by memmove/realloc(). Once we switch to C++, move constructors can be used instead.
Definition at line 39 of file prevector.h.
Member Typedef Documentation
const_pointer
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> typedef const value_type* prevector< N, T, Size, Diff >::const_pointer
Definition at line 47 of file prevector.h.
const_reference
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> typedef const value_type& prevector< N, T, Size, Diff >::const_reference
Definition at line 45 of file prevector.h.
difference_type
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> typedef Diff prevector< N, T, Size, Diff >::difference_type
Definition at line 42 of file prevector.h.
pointer
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> typedef value_type* prevector< N, T, Size, Diff >::pointer
Definition at line 46 of file prevector.h.
reference
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> typedef value_type& prevector< N, T, Size, Diff >::reference
Definition at line 44 of file prevector.h.
size_type
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> typedef Size prevector< N, T, Size, Diff >::size_type
Definition at line 41 of file prevector.h.
value_type
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> typedef T prevector< N, T, Size, Diff >::value_type
Definition at line 43 of file prevector.h.
Constructor & Destructor Documentation
prevector() [1/6]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector< N, T, Size, Diff >::prevector () inline
Definition at line 266 of file prevector.h.
prevector() [2/6]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector< N, T, Size, Diff >::prevector (size_type n) inline explicit
Definition at line 268 of file prevector.h.
References prevector< N, T, Size, Diff >::resize().
prevector() [3/6]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector< N, T, Size, Diff >::prevector (size_type n, const T & val = T()) inline explicit
Definition at line 272 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::fill(), and prevector< N, T, Size, Diff >::item_ptr().
prevector() [4/6]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> template<typename InputIterator > prevector< N, T, Size, Diff >::prevector (InputIterator first, InputIterator last) inline
Definition at line 279 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::fill(), and prevector< N, T, Size, Diff >::item_ptr().
prevector() [5/6]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector< N, T, Size, Diff >::prevector (const prevector< N, T, Size, Diff > & other) inline
Definition at line 286 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::end(), prevector< N, T, Size, Diff >::fill(), prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
prevector() [6/6]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector< N, T, Size, Diff >::prevector (prevector< N, T, Size, Diff > && other) inline
Definition at line 293 of file prevector.h.
References prevector< N, T, Size, Diff >::swap().
~prevector()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector< N, T, Size, Diff >::~prevector () inline
Definition at line 489 of file prevector.h.
References prevector< N, T, Size, Diff >::_union, prevector< N, T, Size, Diff >::clear(), prevector< N, T, Size, Diff >::direct_or_indirect::indirect, and prevector< N, T, Size, Diff >::is_direct().
Member Function Documentation
allocated_memory()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> size_t prevector< N, T, Size, Diff >::allocated_memory () const inline
Definition at line 543 of file prevector.h.
References prevector< N, T, Size, Diff >::_union, prevector< N, T, Size, Diff >::direct_or_indirect::capacity, and prevector< N, T, Size, Diff >::is_direct().
Referenced by memusage::DynamicUsage().
assign() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::assign (size_type n, const T & val) inline
Definition at line 246 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::clear(), prevector< N, T, Size, Diff >::fill(), and prevector< N, T, Size, Diff >::item_ptr().
Referenced by prevector< N, T, Size, Diff >::operator=().
assign() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> template<typename InputIterator > void prevector< N, T, Size, Diff >::assign (InputIterator first, InputIterator last) inline
Definition at line 256 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::clear(), prevector< N, T, Size, Diff >::fill(), and prevector< N, T, Size, Diff >::item_ptr().
assign_to()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> template<typename V > static void prevector< N, T, Size, Diff >::assign_to (const_iterator b, const_iterator e, V & v) inline static
Definition at line 560 of file prevector.h.
References memmove().
Referenced by CScript::GetOp2(), and PrevectorAssignTo().
back() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> T& prevector< N, T, Size, Diff >::back () inline
Definition at line 476 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
back() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const T& prevector< N, T, Size, Diff >::back () const inline
Definition at line 480 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
begin() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> iterator prevector< N, T, Size, Diff >::begin () inline
Definition at line 318 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
Referenced by CTxMemPool::addAddressIndex(), addmultisigaddress(), CTxMemPool::addSpentIndex(), CBloomFilter::CheckScript(), CChainState::ConnectBlock(), createmultisig(), CScriptCompressor::Decompress(), CChainState::DisconnectBlock(), dumpwallet(), EvalScript(), ExtractPubKey(), CScript::Find(), CScript::FindAndDelete(), FormatScript(), getblocktemplate(), CScript::GetOp(), CScript::GetSigOpCount(), Hash160(), prevector< N, T, Size, Diff >::insert(), CScript::IsPushOnly(), CScript::IsUnspendable(), listunspent(), CProRegTx::MakeSignString(), CScript::operator+=(), prevector< N, T, Size, Diff >::operator<(), prevector< N, T, Size, Diff >::operator=(), prevector< N, T, Size, Diff >::operator==(), prevector< N, T, Size, Diff >::prevector(), PrevectorAssign(), PrevectorAssignTo(), ProduceSignature(), ScriptPubKeyToUniv(), ScriptToAsmStr(), Serialize_impl(), SignStep(), Solver(), TxInErrorToJSON(), TxToUniv(), and validateaddress().
begin() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const_iterator prevector< N, T, Size, Diff >::begin () const inline
Definition at line 319 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
capacity()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> size_t prevector< N, T, Size, Diff >::capacity () const inline
Definition at line 328 of file prevector.h.
References prevector< N, T, Size, Diff >::_union, prevector< N, T, Size, Diff >::direct_or_indirect::capacity, and prevector< N, T, Size, Diff >::is_direct().
Referenced by prevector< N, T, Size, Diff >::assign(), prevector< N, T, Size, Diff >::insert(), prevector< N, T, Size, Diff >::push_back(), prevector< N, T, Size, Diff >::reserve(), prevector< N, T, Size, Diff >::resize(), and prevector< N, T, Size, Diff >::resize_uninitialized().
change_capacity()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::change_capacity (size_type new_capacity) inline private
Definition at line 166 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::_union, prevector< N, T, Size, Diff >::direct_or_indirect::capacity, prevector< N, T, Size, Diff >::direct_ptr(), prevector< N, T, Size, Diff >::direct_or_indirect::indirect, prevector< N, T, Size, Diff >::indirect_ptr(), prevector< N, T, Size, Diff >::is_direct(), memcpy(), and prevector< N, T, Size, Diff >::size().
Referenced by prevector< N, T, Size, Diff >::assign(), prevector< N, T, Size, Diff >::insert(), prevector< N, T, Size, Diff >::prevector(), prevector< N, T, Size, Diff >::push_back(), prevector< N, T, Size, Diff >::reserve(), prevector< N, T, Size, Diff >::resize(), prevector< N, T, Size, Diff >::resize_uninitialized(), and prevector< N, T, Size, Diff >::shrink_to_fit().
clear()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::clear () inline
Definition at line 371 of file prevector.h.
References prevector< N, T, Size, Diff >::resize().
Referenced by prevector< N, T, Size, Diff >::assign(), CScript::clear(), PrevectorClear(), Unserialize_impl(), and prevector< N, T, Size, Diff >::~prevector().
data() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> value_type* prevector< N, T, Size, Diff >::data () inline
Definition at line 551 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
Referenced by CFlatData::CFlatData(), CScriptCompressor::Decompress(), and Serialize_impl().
data() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const value_type* prevector< N, T, Size, Diff >::data () const inline
Definition at line 555 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
direct_ptr() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> T* prevector< N, T, Size, Diff >::direct_ptr (difference_type pos) inline private
Definition at line 160 of file prevector.h.
References prevector< N, T, Size, Diff >::_union, and prevector< N, T, Size, Diff >::direct_or_indirect::direct.
Referenced by prevector< N, T, Size, Diff >::change_capacity(), and prevector< N, T, Size, Diff >::item_ptr().
direct_ptr() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const T* prevector< N, T, Size, Diff >::direct_ptr (difference_type pos) const inline private
Definition at line 161 of file prevector.h.
References prevector< N, T, Size, Diff >::_union, and prevector< N, T, Size, Diff >::direct_or_indirect::direct.
empty()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> bool prevector< N, T, Size, Diff >::empty () const inline
Definition at line 314 of file prevector.h.
References prevector< N, T, Size, Diff >::size().
Referenced by CScript::FindAndDelete(), and Serialize_impl().
end() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> iterator prevector< N, T, Size, Diff >::end () inline
Definition at line 320 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
Referenced by CTxMemPool::addAddressIndex(), addmultisigaddress(), CTxMemPool::addSpentIndex(), CBloomFilter::CheckScript(), CChainState::ConnectBlock(), createmultisig(), CChainState::DisconnectBlock(), dumpwallet(), prevector< N, T, Size, Diff >::erase(), EvalScript(), CScript::Find(), CScript::FindAndDelete(), FormatScript(), getblocktemplate(), CScript::GetOp2(), CScript::GetSigOpCount(), Hash160(), CScript::IsPushOnly(), listunspent(), CProRegTx::MakeSignString(), CScript::operator+=(), prevector< N, T, Size, Diff >::operator<(), CScript::operator<<(), prevector< N, T, Size, Diff >::operator=(), prevector< N, T, Size, Diff >::operator==(), ParseScript(), prevector< N, T, Size, Diff >::pop_back(), prevector< N, T, Size, Diff >::prevector(), ProduceSignature(), prevector< N, T, Size, Diff >::resize(), prevector< N, T, Size, Diff >::resize_uninitialized(), ScriptPubKeyToUniv(), ScriptToAsmStr(), Serialize_impl(), SignStep(), Solver(), TxInErrorToJSON(), TxToUniv(), and validateaddress().
end() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const_iterator prevector< N, T, Size, Diff >::end () const inline
Definition at line 321 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
erase() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> iterator prevector< N, T, Size, Diff >::erase (iterator pos) inline
Definition at line 429 of file prevector.h.
Referenced by prevector< N, T, Size, Diff >::pop_back(), prevector< N, T, Size, Diff >::resize(), and prevector< N, T, Size, Diff >::resize_uninitialized().
erase() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> iterator prevector< N, T, Size, Diff >::erase (iterator first, iterator last) inline
Definition at line 433 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::end(), and memmove().
fill() [1/5]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::fill (T * dst, ptrdiff_t count) inline private
Definition at line 200 of file prevector.h.
References count.
Referenced by prevector< N, T, Size, Diff >::assign(), prevector< N, T, Size, Diff >::fill(), prevector< N, T, Size, Diff >::insert(), prevector< N, T, Size, Diff >::prevector(), and prevector< N, T, Size, Diff >::resize().
fill() [2/5]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::fill (T * dst, ptrdiff_t count, const T & value) inline private
Definition at line 213 of file prevector.h.
References count.
fill() [3/5]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> template<typename InputIterator > void prevector< N, T, Size, Diff >::fill (T * dst, InputIterator first, InputIterator last) inline private
Definition at line 220 of file prevector.h.
fill() [4/5]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::fill (T * dst, const_iterator first, const_iterator last) inline private
Definition at line 228 of file prevector.h.
References count, and prevector< N, T, Size, Diff >::fill().
fill() [5/5]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::fill (T * dst, const T * src, ptrdiff_t count) inline private
Definition at line 233 of file prevector.h.
References count, and memmove().
front() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> T& prevector< N, T, Size, Diff >::front () inline
Definition at line 468 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
front() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const T& prevector< N, T, Size, Diff >::front () const inline
Definition at line 472 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
indirect_ptr() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> T* prevector< N, T, Size, Diff >::indirect_ptr (difference_type pos) inline private
Definition at line 162 of file prevector.h.
References prevector< N, T, Size, Diff >::_union, and prevector< N, T, Size, Diff >::direct_or_indirect::indirect.
Referenced by prevector< N, T, Size, Diff >::change_capacity(), and prevector< N, T, Size, Diff >::item_ptr().
indirect_ptr() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const T* prevector< N, T, Size, Diff >::indirect_ptr (difference_type pos) const inline private
Definition at line 163 of file prevector.h.
References prevector< N, T, Size, Diff >::_union, and prevector< N, T, Size, Diff >::direct_or_indirect::indirect.
insert() [1/3]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> iterator prevector< N, T, Size, Diff >::insert (iterator pos, const T & value) inline
Definition at line 375 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::item_ptr(), memmove(), and prevector< N, T, Size, Diff >::size().
Referenced by CScript::FindAndDelete(), CScript::operator+=(), CScript::operator<<(), and ParseScript().
insert() [2/3]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::insert (iterator pos, size_type count, const T & value) inline
Definition at line 388 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), count, prevector< N, T, Size, Diff >::fill(), prevector< N, T, Size, Diff >::item_ptr(), memmove(), and prevector< N, T, Size, Diff >::size().
insert() [3/3]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> template<typename InputIterator > void prevector< N, T, Size, Diff >::insert (iterator pos, InputIterator first, InputIterator last) inline
Definition at line 401 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), count, prevector< N, T, Size, Diff >::fill(), prevector< N, T, Size, Diff >::item_ptr(), memmove(), and prevector< N, T, Size, Diff >::size().
is_direct()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> bool prevector< N, T, Size, Diff >::is_direct () const inline private
Definition at line 164 of file prevector.h.
References prevector< N, T, Size, Diff >::_size.
Referenced by prevector< N, T, Size, Diff >::allocated_memory(), prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::item_ptr(), prevector< N, T, Size, Diff >::size(), and prevector< N, T, Size, Diff >::~prevector().
item_ptr() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> T* prevector< N, T, Size, Diff >::item_ptr (difference_type pos) inline private
Definition at line 197 of file prevector.h.
References prevector< N, T, Size, Diff >::direct_ptr(), prevector< N, T, Size, Diff >::indirect_ptr(), and prevector< N, T, Size, Diff >::is_direct().
Referenced by prevector< N, T, Size, Diff >::assign(), prevector< N, T, Size, Diff >::back(), prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::data(), prevector< N, T, Size, Diff >::end(), prevector< N, T, Size, Diff >::front(), prevector< N, T, Size, Diff >::insert(), prevector< N, T, Size, Diff >::operator[](), prevector< N, T, Size, Diff >::prevector(), prevector< N, T, Size, Diff >::push_back(), prevector< N, T, Size, Diff >::rbegin(), prevector< N, T, Size, Diff >::rend(), prevector< N, T, Size, Diff >::resize(), and prevector< N, T, Size, Diff >::resize_uninitialized().
item_ptr() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const T* prevector< N, T, Size, Diff >::item_ptr (difference_type pos) const inline private
Definition at line 198 of file prevector.h.
References prevector< N, T, Size, Diff >::direct_ptr(), prevector< N, T, Size, Diff >::indirect_ptr(), and prevector< N, T, Size, Diff >::is_direct().
operator!=()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> bool prevector< N, T, Size, Diff >::operator!= (const prevector< N, T, Size, Diff > & other) const inline
Definition at line 516 of file prevector.h.
operator<()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> bool prevector< N, T, Size, Diff >::operator< (const prevector< N, T, Size, Diff > & other) const inline
Definition at line 520 of file prevector.h.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), and prevector< N, T, Size, Diff >::size().
operator=() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector& prevector< N, T, Size, Diff >::operator= (const prevector< N, T, Size, Diff > & other) inline
Definition at line 297 of file prevector.h.
References prevector< N, T, Size, Diff >::assign(), prevector< N, T, Size, Diff >::begin(), and prevector< N, T, Size, Diff >::end().
operator=() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> prevector& prevector< N, T, Size, Diff >::operator= (prevector< N, T, Size, Diff > && other) inline
Definition at line 305 of file prevector.h.
References prevector< N, T, Size, Diff >::swap().
operator==()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> bool prevector< N, T, Size, Diff >::operator== (const prevector< N, T, Size, Diff > & other) const inline
Definition at line 499 of file prevector.h.
References prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), and prevector< N, T, Size, Diff >::size().
operator[]() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> T& prevector< N, T, Size, Diff >::operator[] (size_type pos) inline
Definition at line 336 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
operator[]() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const T& prevector< N, T, Size, Diff >::operator[] (size_type pos) const inline
Definition at line 340 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
pop_back()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::pop_back () inline
Definition at line 464 of file prevector.h.
References prevector< N, T, Size, Diff >::end(), and prevector< N, T, Size, Diff >::erase().
push_back()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::push_back (const T & value) inline
Definition at line 455 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
Referenced by WalletModel::prepareTransaction(), CScript::push_int64(), sendmany(), and SendMoney().
rbegin() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> reverse_iterator prevector< N, T, Size, Diff >::rbegin () inline
Definition at line 323 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
rbegin() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const_reverse_iterator prevector< N, T, Size, Diff >::rbegin () const inline
Definition at line 324 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
rend() [1/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> reverse_iterator prevector< N, T, Size, Diff >::rend () inline
Definition at line 325 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
rend() [2/2]
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> const_reverse_iterator prevector< N, T, Size, Diff >::rend () const inline
Definition at line 326 of file prevector.h.
References prevector< N, T, Size, Diff >::item_ptr().
reserve()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::reserve (size_type new_capacity) inline
Definition at line 361 of file prevector.h.
References prevector< N, T, Size, Diff >::capacity(), and prevector< N, T, Size, Diff >::change_capacity().
Referenced by CScript::operator+=().
resize()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::resize (size_type new_size) inline
Definition at line 344 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::end(), prevector< N, T, Size, Diff >::erase(), prevector< N, T, Size, Diff >::fill(), prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
Referenced by CCheckQueueSpeedPrevectorJob(), prevector< N, T, Size, Diff >::clear(), CScriptCompressor::Decompress(), prevector< N, T, Size, Diff >::prevector(), PrevectorAssign(), PrevectorAssignTo(), PrevectorClear(), PrevectorDestructor(), PrevectorResize(), and CScriptCompressor::Unserialize().
resize_uninitialized()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::resize_uninitialized (size_type new_size) inline
Definition at line 414 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::end(), prevector< N, T, Size, Diff >::erase(), prevector< N, T, Size, Diff >::item_ptr(), and prevector< N, T, Size, Diff >::size().
Referenced by Unserialize_impl().
shrink_to_fit()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::shrink_to_fit () inline
Definition at line 367 of file prevector.h.
References prevector< N, T, Size, Diff >::change_capacity(), and prevector< N, T, Size, Diff >::size().
Referenced by CScript::clear().
size()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> size_type prevector< N, T, Size, Diff >::size () const inline
Definition at line 310 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, and prevector< N, T, Size, Diff >::is_direct().
Referenced by CBasicKeyStore::AddCScript(), prevector< N, T, Size, Diff >::back(), CFlatData::CFlatData(), prevector< N, T, Size, Diff >::change_capacity(), CreateMultisigRedeemscript(), prevector< N, T, Size, Diff >::empty(), prevector< N, T, Size, Diff >::end(), EvalScript(), PaymentServer::fetchPaymentACK(), CScript::FindAndDelete(), prevector< N, T, Size, Diff >::insert(), CScript::IsPayToPublicKey(), CScript::IsPayToPublicKeyHash(), CScript::IsPayToScriptHash(), IsStandard(), IsStandardTx(), CScriptCompressor::IsToKeyID(), CScriptCompressor::IsToPubKey(), CScriptCompressor::IsToScriptID(), CScript::IsUnspendable(), CWallet::LoadCScript(), MutateTxAddOutMultiSig(), MutateTxAddOutScript(), CScript::operator+=(), prevector< N, T, Size, Diff >::operator<(), prevector< N, T, Size, Diff >::operator==(), prevector< N, T, Size, Diff >::prevector(), prevector< N, T, Size, Diff >::push_back(), prevector< N, T, Size, Diff >::rbegin(), prevector< N, T, Size, Diff >::resize(), prevector< N, T, Size, Diff >::resize_uninitialized(), CScriptCompressor::Serialize(), Serialize_impl(), prevector< N, T, Size, Diff >::shrink_to_fit(), and Solver().
swap()
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> void prevector< N, T, Size, Diff >::swap (prevector< N, T, Size, Diff > & other) inline
Definition at line 484 of file prevector.h.
References prevector< N, T, Size, Diff >::_size, and prevector< N, T, Size, Diff >::_union.
Referenced by CCheckQueueSpeedPrevectorJob(), prevector< N, T, Size, Diff >::operator=(), and prevector< N, T, Size, Diff >::prevector().
Member Data Documentation
_size
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> size_type prevector< N, T, Size, Diff >::_size private
Definition at line 151 of file prevector.h.
Referenced by prevector< N, T, Size, Diff >::assign(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::erase(), prevector< N, T, Size, Diff >::insert(), prevector< N, T, Size, Diff >::is_direct(), prevector< N, T, Size, Diff >::prevector(), prevector< N, T, Size, Diff >::push_back(), prevector< N, T, Size, Diff >::resize(), prevector< N, T, Size, Diff >::resize_uninitialized(), prevector< N, T, Size, Diff >::size(), and prevector< N, T, Size, Diff >::swap().
_union
template<unsigned int N, typename T, typename Size = uint32_t, typename Diff = int32_t> union prevector::direct_or_indirect prevector< N, T, Size, Diff >::_union private
Referenced by prevector< N, T, Size, Diff >::allocated_memory(), prevector< N, T, Size, Diff >::capacity(), prevector< N, T, Size, Diff >::change_capacity(), prevector< N, T, Size, Diff >::direct_ptr(), prevector< N, T, Size, Diff >::indirect_ptr(), prevector< N, T, Size, Diff >::swap(), and prevector< N, T, Size, Diff >::~prevector().
The documentation for this class was generated from the following file:
src/prevector.h
Released under the MIT license