Dash Core: CTestNetParams Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CTestNetParams Class Reference
Testnet (v3)
Public Member Functions
CTestNetParams ()
Public Member Functions inherited from CChainParams
const Consensus::Params & GetConsensus () const
const CMessageHeader::MessageStartChars & MessageStart () const
int GetDefaultPort () const
const CBlock & GenesisBlock () const
const CBlock & DevNetGenesisBlock () const
bool DefaultConsistencyChecks () const
Default value for -checkmempool and -checkblockindex argument.
bool RequireStandard () const
Policy: Filter transactions that do not match well-defined patterns.
bool RequireRoutableExternalIP () const
Require addresses specified with "-externalip" parameter to be routable.
uint64_t PruneAfterHeight () const
bool MineBlocksOnDemand () const
Make miner stop after a block is found.
bool AllowMultipleAddressesFromGroup () const
Allow multiple addresses to be selected from the same network group (e.g.
bool AllowMultiplePorts () const
Allow nodes with the same address and multiple ports.
int LLMQConnectionRetryTimeout () const
How long to wait until we allow retrying of a LLMQ connection.
std::string NetworkIDString () const
Return the BIP70 network string (main, test or regtest)
const std::vector< std::string > & DNSSeeds () const
Return the list of hostnames to look up for DNS seeds.
const std::vector< unsigned char > & Base58Prefix (Base58Type type) const
int ExtCoinType () const
const std::vector< SeedSpec6 > & FixedSeeds () const
const CCheckpointData & Checkpoints () const
const ChainTxData & TxData () const
void UpdateVersionBitsParameters (Consensus::DeploymentPos d, int64_t nStartTime, int64_t nTimeout, int64_t nWindowSize, int64_t nThresholdStart, int64_t nThresholdMin, int64_t nFalloffCoeff)
void UpdateDIP3Parameters (int nActivationHeight, int nEnforcementHeight)
void UpdateBudgetParameters (int nMasternodePaymentsStartBlock, int nBudgetPaymentsStartBlock, int nSuperblockStartBlock)
void UpdateSubsidyAndDiffParams (int nMinimumDifficultyBlocks, int nHighSubsidyBlocks, int nHighSubsidyFactor)
void UpdateLLMQChainLocks (Consensus::LLMQType llmqType)
void UpdateLLMQTestParams (int size, int threshold)
void UpdateLLMQDevnetParams (int size, int threshold)
int PoolMinParticipants () const
int PoolNewMinParticipants () const
int PoolMaxParticipants () const
int PoolNewMaxParticipants () const
int FulfilledRequestExpireTime () const
const std::vector< std::string > & SporkAddresses () const
int MinSporkKeys () const
bool BIP9CheckMasternodesUpgraded () const
Additional Inherited Members
Public Types inherited from CChainParams
enum Base58Type {
PUBKEY_ADDRESS, SCRIPT_ADDRESS, SECRET_KEY, EXT_PUBLIC_KEY,
EXT_SECRET_KEY, MAX_BASE58_TYPES
}
Protected Member Functions inherited from CChainParams
CChainParams ()
Protected Attributes inherited from CChainParams
Consensus::Params consensus
CMessageHeader::MessageStartChars pchMessageStart
int nDefaultPort
uint64_t nPruneAfterHeight
std::vector< std::string > vSeeds
std::vector< unsigned char > base58Prefixes [MAX_BASE58_TYPES]
int nExtCoinType
std::string strNetworkID
CBlock genesis
CBlock devnetGenesis
std::vector< SeedSpec6 > vFixedSeeds
bool fDefaultConsistencyChecks
bool fRequireStandard
bool fRequireRoutableExternalIP
bool fMineBlocksOnDemand
bool fAllowMultipleAddressesFromGroup
bool fAllowMultiplePorts
int nLLMQConnectionRetryTimeout
CCheckpointData checkpointData
ChainTxData chainTxData
int nPoolMinParticipants
int nPoolNewMinParticipants
int nPoolMaxParticipants
int nPoolNewMaxParticipants
int nFulfilledRequestExpireTime
std::vector< std::string > vSporkAddresses
int nMinSporkKeys
bool fBIP9CheckMasternodesUpgraded
Detailed Description
Testnet (v3)
Definition at line 475 of file chainparams.cpp.
Constructor & Destructor Documentation
CTestNetParams()
CTestNetParams::CTestNetParams () inline
Definition at line 477 of file chainparams.cpp.
References ARRAYLEN, CChainParams::base58Prefixes, Consensus::Params::BIP34Hash, Consensus::Params::BIP34Height, Consensus::Params::BIP65Height, Consensus::Params::BIP66Height, Consensus::BIP9Deployment::bit, CChainParams::chainTxData, CChainParams::checkpointData, COIN, CChainParams::consensus, CreateGenesisBlock(), Consensus::Params::defaultAssumeValid, Consensus::DEPLOYMENT_BIP147, Consensus::DEPLOYMENT_CSV, Consensus::DEPLOYMENT_DIP0001, Consensus::DEPLOYMENT_DIP0003, Consensus::DEPLOYMENT_DIP0008, Consensus::DEPLOYMENT_REALLOC, Consensus::DEPLOYMENT_TESTDUMMY, Consensus::Params::DIP0001Height, Consensus::Params::DIP0003EnforcementHash, Consensus::Params::DIP0003EnforcementHeight, Consensus::Params::DIP0003Height, CChainParams::EXT_PUBLIC_KEY, CChainParams::EXT_SECRET_KEY, CChainParams::fAllowMultipleAddressesFromGroup, CChainParams::fAllowMultiplePorts, CChainParams::fBIP9CheckMasternodesUpgraded, CChainParams::fDefaultConsistencyChecks, CChainParams::fMineBlocksOnDemand, Consensus::Params::fPowAllowMinDifficultyBlocks, Consensus::Params::fPowNoRetargeting, CChainParams::fRequireRoutableExternalIP, CChainParams::fRequireStandard, CChainParams::genesis, CBlockHeader::GetHash(), Consensus::Params::hashGenesisBlock, CBlockHeader::hashMerkleRoot, llmq400_60, llmq400_85, llmq50_60, Consensus::LLMQ_400_60, Consensus::LLMQ_400_85, Consensus::LLMQ_50_60, Consensus::Params::llmqs, Consensus::Params::llmqTypeChainLocks, Consensus::Params::llmqTypeInstantSend, Consensus::Params::nBudgetPaymentsCycleBlocks, Consensus::Params::nBudgetPaymentsStartBlock, Consensus::Params::nBudgetPaymentsWindowBlocks, CChainParams::nDefaultPort, CChainParams::nExtCoinType, Consensus::BIP9Deployment::nFalloffCoeff, CChainParams::nFulfilledRequestExpireTime, Consensus::Params::nGovernanceFilterElements, Consensus::Params::nGovernanceMinQuorum, Consensus::Params::nInstantSendConfirmationsRequired, Consensus::Params::nInstantSendKeepLock, CChainParams::nLLMQConnectionRetryTimeout, Consensus::Params::nMasternodeMinimumConfirmations, Consensus::Params::nMasternodePaymentsIncreaseBlock, Consensus::Params::nMasternodePaymentsIncreasePeriod, Consensus::Params::nMasternodePaymentsStartBlock, Consensus::Params::nMinerConfirmationWindow, Consensus::Params::nMinimumChainWork, CChainParams::nMinSporkKeys, CChainParams::nPoolMaxParticipants, CChainParams::nPoolMinParticipants, CChainParams::nPoolNewMaxParticipants, CChainParams::nPoolNewMinParticipants, Consensus::Params::nPowDGWHeight, Consensus::Params::nPowKGWHeight, Consensus::Params::nPowTargetSpacing, Consensus::Params::nPowTargetTimespan, CChainParams::nPruneAfterHeight, Consensus::Params::nRuleChangeActivationThreshold, Consensus::BIP9Deployment::nStartTime, Consensus::Params::nSubsidyHalvingInterval, Consensus::Params::nSuperblockCycle, Consensus::Params::nSuperblockStartBlock, Consensus::Params::nSuperblockStartHash, Consensus::BIP9Deployment::nThresholdMin, Consensus::BIP9Deployment::nThresholdStart, Consensus::BIP9Deployment::nTimeout, Consensus::BIP9Deployment::nWindowSize, CChainParams::pchMessageStart, pnSeed6_test, Consensus::Params::powLimit, CChainParams::PUBKEY_ADDRESS, CChainParams::SCRIPT_ADDRESS, CChainParams::SECRET_KEY, CChainParams::strNetworkID, uint256S(), Consensus::Params::vDeployments, CChainParams::vFixedSeeds, CChainParams::vSeeds, and CChainParams::vSporkAddresses.
The documentation for this class was generated from the following file:
src/chainparams.cpp
Released under the MIT license