Dash Core: CHMAC_SHA512 Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CHMAC_SHA512 Class Reference
A hasher class for HMAC-SHA-512.
#include <hmac_sha512.h>
Public Member Functions
CHMAC_SHA512 (const unsigned char *key, size_t keylen)
CHMAC_SHA512 & Write (const unsigned char *data, size_t len)
void Finalize (unsigned char hash[OUTPUT_SIZE])
Static Public Attributes
static const size_t OUTPUT_SIZE = 64
Private Attributes
CSHA512 outer
CSHA512 inner
Detailed Description
A hasher class for HMAC-SHA-512.
Definition at line 14 of file hmac_sha512.h.
Constructor & Destructor Documentation
CHMAC_SHA512()
CHMAC_SHA512::CHMAC_SHA512 (const unsigned char * key, size_t keylen)
Definition at line 9 of file hmac_sha512.cpp.
References CSHA512::Finalize(), inner, memcpy(), outer, and CSHA512::Write().
Member Function Documentation
Finalize()
void CHMAC_SHA512::Finalize (unsigned char hash[OUTPUT_SIZE])
Definition at line 29 of file hmac_sha512.cpp.
References CSHA512::Finalize(), inner, outer, and CSHA512::Write().
Referenced by BIP32Hash(), and CExtKey::SetMaster().
Write()
CHMAC_SHA512& CHMAC_SHA512::Write (const unsigned char * data, size_t len) inline
Definition at line 24 of file hmac_sha512.h.
References inner, and CSHA512::Write().
Referenced by BIP32Hash(), and CExtKey::SetMaster().
Member Data Documentation
inner
CSHA512 CHMAC_SHA512::inner private
Definition at line 18 of file hmac_sha512.h.
Referenced by CHMAC_SHA512(), Finalize(), and Write().
outer
CSHA512 CHMAC_SHA512::outer private
Definition at line 17 of file hmac_sha512.h.
Referenced by CHMAC_SHA512(), and Finalize().
OUTPUT_SIZE
const size_t CHMAC_SHA512::OUTPUT_SIZE = 64 static
Definition at line 21 of file hmac_sha512.h.
The documentation for this class was generated from the following files:
src/crypto/hmac_sha512.h
src/crypto/hmac_sha512.cpp
Released under the MIT license