Dash Core: RPCConsole Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
RPCConsole Class Reference
Local Bitcoin RPC console.
#include <rpcconsole.h>
Public Types
enum MessageClass {
MC_ERROR, MC_DEBUG, CMD_REQUEST, CMD_REPLY,
CMD_ERROR
}
enum TabTypes {
TAB_INFO = 0, TAB_CONSOLE = 1, TAB_GRAPH = 2, TAB_PEERS = 3,
TAB_REPAIR = 4
}
Public Slots
void clear (bool clearHistory=true)
void fontBigger ()
void fontSmaller ()
void setFontSize (int newSize)
void walletSalvage ()
Wallet repair options.
void walletRescan ()
Restart wallet with "-rescan".
void walletZaptxes1 ()
Restart wallet with "-zapwallettxes=1".
void walletZaptxes2 ()
Restart wallet with "-zapwallettxes=2".
void walletUpgrade ()
Restart wallet with "-upgradewallet".
void walletReindex ()
Restart wallet with "-reindex".
void message (int category, const QString &message, bool html=false)
Append the message to the message widget.
void setNumConnections (int count)
Set number of connections shown in the UI.
void setNetworkActive (bool networkActive)
Set network state shown in the UI.
void updateMasternodeCount ()
Update number of masternodes shown in the UI.
void setNumBlocks (int count, const QDateTime &blockDate, const QString &blockHash, double nVerificationProgress, bool headers)
Set number of blocks, last block date and last block hash shown in the UI.
void setMempoolSize (long numberOfTxs, size_t dynUsage)
Set size (number of transactions and memory usage) of the mempool in the UI.
void setInstantSendLockCount (size_t count)
Set number of InstantSend locks.
void browseHistory (int offset)
Go forward or back in history.
void scrollToEnd ()
Scroll console view to end.
void peerSelected (const QItemSelection &selected, const QItemSelection &deselected)
Handle selection of peer in peers list.
void peerLayoutAboutToChange ()
Handle selection caching before update.
void peerLayoutChanged ()
Handle updated peer information.
void disconnectSelectedNode ()
Disconnect a selected node on the Peers tab.
void banSelectedNode (int bantime)
Ban a selected node on the Peers tab.
void unbanSelectedNode ()
Unban a selected node on the Bans tab.
void setTabFocus (enum TabTypes tabType)
set which tab has the focus (is visible)
Signals
void stopExecutor ()
void cmdRequest (const QString &command)
void handleRestart (QStringList args)
Get restart command-line parameters and handle restart.
Public Member Functions
RPCConsole (QWidget *parent)
~RPCConsole ()
void setClientModel (ClientModel *model)
Static Public Member Functions
static bool RPCParseCommandLine (std::string &strResult, const std::string &strCommand, bool fExecute, std::string *const pstrFilteredOut=nullptr)
Split shell command line into a list of arguments and optionally execute the command(s).
static bool RPCExecuteCommandLine (std::string &strResult, const std::string &strCommand, std::string *const pstrFilteredOut=nullptr)
Protected Member Functions
virtual bool eventFilter (QObject *obj, QEvent *event)
void keyPressEvent (QKeyEvent *)
Private Types
enum ColumnWidths {
ADDRESS_COLUMN_WIDTH = 170, SUBVERSION_COLUMN_WIDTH = 150, PING_COLUMN_WIDTH = 80, BANSUBNET_COLUMN_WIDTH = 200,
BANTIME_COLUMN_WIDTH = 250
}
Private Slots
void showPage (int index)
custom tab buttons clicked
void on_lineEdit_returnPressed ()
void on_stackedWidgetRPC_currentChanged (int index)
void on_openDebugLogfileButton_clicked ()
open the debug.log from the current datadir
void on_sldGraphRange_valueChanged (int value)
change the time range of the network traffic graph
void resizeEvent (QResizeEvent *event)
void showEvent (QShowEvent *event)
void hideEvent (QHideEvent *event)
void changeEvent (QEvent *e)
void showPeersTableContextMenu (const QPoint &point)
Show custom context menu on Peers tab.
void showBanTableContextMenu (const QPoint &point)
Show custom context menu on Bans tab.
void showOrHideBanTableIfRequired ()
Hides ban table if no bans are present.
void clearSelectedNode ()
clear the selected node
Private Member Functions
void startExecutor ()
void setTrafficGraphRange (TrafficGraphData::GraphRange range)
void buildParameterlist (QString arg)
Build parameter list for restart.
void updateNodeDetail (const CNodeCombinedStats *stats)
show detailed information on ui about selected node
void setButtonIcons ()
Set required icons for buttons inside the dialog.
void updateNetworkState ()
Update UI with latest network info from model.
Private Attributes
Ui::RPCConsole * ui
QButtonGroup pageButtons
ClientModel * clientModel
QStringList history
int historyPtr
QString cmdBeforeBrowsing
QList< NodeId > cachedNodeids
RPCTimerInterface * rpcTimerInterface
QMenu * peersTableContextMenu
QMenu * banTableContextMenu
int consoleFontSize
QCompleter * autoCompleter
QThread thread
Detailed Description
Local Bitcoin RPC console.
Definition at line 32 of file rpcconsole.h.
Member Enumeration Documentation
ColumnWidths
enum RPCConsole::ColumnWidths private
Enumerator
ADDRESS_COLUMN_WIDTH
SUBVERSION_COLUMN_WIDTH
PING_COLUMN_WIDTH
BANSUBNET_COLUMN_WIDTH
BANTIME_COLUMN_WIDTH
Definition at line 153 of file rpcconsole.h.
MessageClass
enum RPCConsole::MessageClass
Enumerator
MC_ERROR
MC_DEBUG
CMD_REQUEST
CMD_REPLY
CMD_ERROR
Definition at line 47 of file rpcconsole.h.
TabTypes
enum RPCConsole::TabTypes
Enumerator
TAB_INFO
TAB_CONSOLE
TAB_GRAPH
TAB_PEERS
TAB_REPAIR
Definition at line 55 of file rpcconsole.h.
Constructor & Destructor Documentation
RPCConsole()
RPCConsole::RPCConsole (QWidget * parent) explicit
Definition at line 445 of file rpcconsole.cpp.
References GUIUtil::Bold, clear(), consoleFontSize, GUIUtil::disableMacFocusRect(), fontBigger(), fontSizeSettingsKey, fontSmaller(), gArgs, ArgsManager::GetArg(), GetDataDir(), GUIUtil::getFontNormal(), INITIAL_TRAFFIC_GRAPH_SETTING, pageButtons, RPCSetTimerInterfaceIfUnset(), rpcTimerInterface, setButtonIcons(), GUIUtil::setFont(), setTrafficGraphRange(), showPage(), ui, GUIUtil::updateFonts(), walletReindex(), walletRescan(), walletUpgrade(), walletZaptxes1(), and walletZaptxes2().
~RPCConsole()
RPCConsole::~RPCConsole ()
Definition at line 530 of file rpcconsole.cpp.
References rpcTimerInterface, RPCUnsetTimerInterface(), and ui.
Member Function Documentation
banSelectedNode
void RPCConsole::banSelectedNode (int bantime) slot
Ban a selected node on the Peers tab.
Definition at line 1286 of file rpcconsole.cpp.
References CNodeStats::addr, BanReasonManuallyAdded, clearSelectedNode(), clientModel, g_connman, ClientModel::getBanTableModel(), GUIUtil::getEntryData(), PeerTableModel::getNodeStats(), ClientModel::getPeerTableModel(), PeerTableModel::getRowByNodeId(), PeerTableModel::NetNodeId, CNodeCombinedStats::nodeStats, BanTableModel::refresh(), and ui.
Referenced by setClientModel().
browseHistory
void RPCConsole::browseHistory (int offset) slot
Go forward or back in history.
Definition at line 1010 of file rpcconsole.cpp.
References cmdBeforeBrowsing, history, historyPtr, and ui.
Referenced by eventFilter().
buildParameterlist()
void RPCConsole::buildParameterlist (QString arg) private
Build parameter list for restart.
Build command-line parameter list for restart.
Definition at line 805 of file rpcconsole.cpp.
References handleRestart(), REINDEX(), RESCAN(), SALVAGEWALLET(), UPGRADEWALLET(), ZAPTXES1(), and ZAPTXES2().
Referenced by walletReindex(), walletRescan(), walletSalvage(), walletUpgrade(), walletZaptxes1(), and walletZaptxes2().
changeEvent
void RPCConsole::changeEvent (QEvent * e) private slot
Definition at line 1243 of file rpcconsole.cpp.
References clear(), GUIUtil::dashThemeActive(), setButtonIcons(), and ui.
clear
void RPCConsole::clear (bool clearHistory = true) slot
Definition at line 826 of file rpcconsole.cpp.
References CMD_REPLY, consoleFontSize, GUIUtil::getFontNormal(), GUIUtil::getThemedStyleQString(), history, historyPtr, message(), GUIUtil::TS_COMMAND, GUIUtil::TS_ERROR, GUIUtil::TS_PRIMARY, GUIUtil::TS_SECONDARY, and ui.
Referenced by changeEvent(), RPCConsole(), and setFontSize().
clearSelectedNode
void RPCConsole::clearSelectedNode () private slot
clear the selected node
Definition at line 1335 of file rpcconsole.cpp.
References cachedNodeids, and ui.
Referenced by banSelectedNode(), disconnectSelectedNode(), on_stackedWidgetRPC_currentChanged(), peerLayoutChanged(), and setClientModel().
cmdRequest
void RPCConsole::cmdRequest (const QString & command) signal
Referenced by on_lineEdit_returnPressed(), and startExecutor().
disconnectSelectedNode
void RPCConsole::disconnectSelectedNode () slot
Disconnect a selected node on the Peers tab.
Definition at line 1269 of file rpcconsole.cpp.
References clearSelectedNode(), g_connman, GUIUtil::getEntryData(), PeerTableModel::NetNodeId, and ui.
Referenced by setClientModel().
eventFilter()
bool RPCConsole::eventFilter (QObject * obj, QEvent * event) protected virtual
Definition at line 539 of file rpcconsole.cpp.
References autoCompleter, browseHistory(), and ui.
fontBigger
void RPCConsole::fontBigger () slot
Definition at line 733 of file rpcconsole.cpp.
References consoleFontSize, and setFontSize().
Referenced by RPCConsole().
fontSmaller
void RPCConsole::fontSmaller () slot
Definition at line 738 of file rpcconsole.cpp.
References consoleFontSize, and setFontSize().
Referenced by RPCConsole().
handleRestart
void RPCConsole::handleRestart (QStringList args) signal
Get restart command-line parameters and handle restart.
Referenced by buildParameterlist().
hideEvent
void RPCConsole::hideEvent (QHideEvent * event) private slot
Definition at line 1232 of file rpcconsole.cpp.
References clientModel, ClientModel::getPeerTableModel(), and PeerTableModel::stopAutoRefresh().
keyPressEvent()
void RPCConsole::keyPressEvent (QKeyEvent * event) protected
Definition at line 865 of file rpcconsole.cpp.
message
void RPCConsole::message (int category, const QString & message, bool html = false) slot
Append the message to the message widget.
Definition at line 873 of file rpcconsole.cpp.
References categoryClass(), GUIUtil::HtmlEscape(), and ui.
Referenced by clear(), on_lineEdit_returnPressed(), and startExecutor().
on_lineEdit_returnPressed
void RPCConsole::on_lineEdit_returnPressed () private slot
Definition at line 968 of file rpcconsole.cpp.
References CMD_REQUEST, cmdBeforeBrowsing, cmdRequest(), CONSOLE_HISTORY, history, historyPtr, message(), RPCParseCommandLine(), scrollToEnd(), and ui.
on_openDebugLogfileButton_clicked
void RPCConsole::on_openDebugLogfileButton_clicked () private slot
open the debug.log from the current datadir
Definition at line 1060 of file rpcconsole.cpp.
References GUIUtil::openDebugLogfile().
on_sldGraphRange_valueChanged
void RPCConsole::on_sldGraphRange_valueChanged (int value) private slot
change the time range of the network traffic graph
Definition at line 1071 of file rpcconsole.cpp.
References setTrafficGraphRange().
on_stackedWidgetRPC_currentChanged
void RPCConsole::on_stackedWidgetRPC_currentChanged (int index) private slot
Definition at line 1052 of file rpcconsole.cpp.
References clearSelectedNode(), and ui.
peerLayoutAboutToChange
void RPCConsole::peerLayoutAboutToChange () slot
Handle selection caching before update.
Definition at line 1094 of file rpcconsole.cpp.
References cachedNodeids, clientModel, PeerTableModel::getNodeStats(), ClientModel::getPeerTableModel(), CNodeStats::nodeid, CNodeCombinedStats::nodeStats, and ui.
Referenced by setClientModel().
peerLayoutChanged
void RPCConsole::peerLayoutChanged () slot
Handle updated peer information.
Definition at line 1105 of file rpcconsole.cpp.
References cachedNodeids, clearSelectedNode(), clientModel, PeerTableModel::getNodeStats(), ClientModel::getPeerTableModel(), PeerTableModel::getRowByNodeId(), ui, and updateNodeDetail().
Referenced by setClientModel().
peerSelected
void RPCConsole::peerSelected (const QItemSelection & selected, const QItemSelection & deselected) slot
Handle selection of peer in peers list.
Definition at line 1082 of file rpcconsole.cpp.
References clientModel, PeerTableModel::getNodeStats(), ClientModel::getPeerTableModel(), and updateNodeDetail().
Referenced by setClientModel().
resizeEvent
void RPCConsole::resizeEvent (QResizeEvent * event) private slot
Definition at line 1216 of file rpcconsole.cpp.
RPCExecuteCommandLine()
static bool RPCConsole::RPCExecuteCommandLine (std::string & strResult, const std::string & strCommand, std::string *const pstrFilteredOut = nullptr) inline static
Definition at line 41 of file rpcconsole.h.
References RPCParseCommandLine().
Referenced by RPCExecutor::request().
RPCParseCommandLine()
bool RPCConsole::RPCParseCommandLine (std::string & strResult, const std::string & strCommand, bool fExecute, std::string *const pstrFilteredOut = nullptr) static
Split shell command line into a list of arguments and optionally execute the command(s).
Aims to emulate bash and friends.
Command nesting is possible with parenthesis; for example: validateaddress(getnewaddress())
Arguments are delimited with whitespace or comma
Extra whitespace at the beginning and end and between arguments will be ignored
Text can be "double" or 'single' quoted
The backslash \ is used as escape character
Outside quotes, any character can be escaped
Within double quotes, only escape " and backslashes before a \c " or another backslash
Within single quotes, no escaping is possible and no special interpretation takes place
Parameters
[out] result stringified Result from the executed command(chain)
[in] strCommand Command line to split
[in] fExecute set true if you want the command to be executed
[out] pstrFilteredOut Command line, filtered to remove any sensitive data
Definition at line 147 of file rpcconsole.cpp.
References atoi(), UniValue::clear(), CRPCTable::execute(), find_value(), UniValue::get_str(), GetWallets(), HasWallets(), UniValue::isArray(), UniValue::isObject(), UniValue::isStr(), JSONRPCRequest::params, UniValue::push_back(), RPCConvertValues(), JSONRPCRequest::strMethod, tableRPC, JSONRPCRequest::URI, and UniValue::write().
Referenced by on_lineEdit_returnPressed(), and RPCExecuteCommandLine().
scrollToEnd
void RPCConsole::scrollToEnd () slot
Scroll console view to end.
Definition at line 1065 of file rpcconsole.cpp.
References ui.
Referenced by on_lineEdit_returnPressed().
setButtonIcons()
void RPCConsole::setButtonIcons () private
Set required icons for buttons inside the dialog.
Definition at line 1208 of file rpcconsole.cpp.
References GUIUtil::BLUE, BUTTON_ICONSIZE, GUIUtil::RED, GUIUtil::setIcon(), and ui.
Referenced by changeEvent(), and RPCConsole().
setClientModel()
void RPCConsole::setClientModel (ClientModel * model)
Definition at line 584 of file rpcconsole.cpp.
References BanTableModel::Address, PeerTableModel::Address, ADDRESS_COLUMN_WIDTH, autoCompleter, banSelectedNode(), BANSUBNET_COLUMN_WIDTH, banTableContextMenu, BanTableModel::Bantime, BANTIME_COLUMN_WIDTH, clearSelectedNode(), clientModel, ClientModel::dataDir(), disconnectSelectedNode(), ClientModel::formatClientStartupTime(), ClientModel::formatFullVersion(), ClientModel::formatSubVersion(), ClientModel::getBanTableModel(), ClientModel::getLastBlockDate(), ClientModel::getLastBlockHash(), ClientModel::getNumBlocks(), ClientModel::getNumConnections(), ClientModel::getPeerTableModel(), ClientModel::getVerificationProgress(), CRPCTable::listCommands(), GUIUtil::loadStyleSheet(), Params(), peerLayoutAboutToChange(), peerLayoutChanged(), peerSelected(), peersTableContextMenu, PeerTableModel::Ping, PING_COLUMN_WIDTH, ClientModel::refreshMasternodeList(), setInstantSendLockCount(), setMempoolSize(), setNetworkActive(), setNumBlocks(), setNumConnections(), showBanTableContextMenu(), showOrHideBanTableIfRequired(), showPeersTableContextMenu(), startExecutor(), stopExecutor(), PeerTableModel::Subversion, SUBVERSION_COLUMN_WIDTH, tableRPC, thread, ui, unbanSelectedNode(), updateMasternodeCount(), and updateNetworkState().
Referenced by BitcoinGUI::setClientModel().
setFontSize
void RPCConsole::setFontSize (int newSize) slot
Definition at line 743 of file rpcconsole.cpp.
References clear(), consoleFontSize, FONT_RANGE(), fontSizeSettingsKey, and ui.
Referenced by fontBigger(), and fontSmaller().
setInstantSendLockCount
void RPCConsole::setInstantSendLockCount (size_t count) slot
Set number of InstantSend locks.
Definition at line 945 of file rpcconsole.cpp.
References count, and ui.
Referenced by setClientModel().
setMempoolSize
void RPCConsole::setMempoolSize (long numberOfTxs, size_t dynUsage) slot
Set size (number of transactions and memory usage) of the mempool in the UI.
Definition at line 935 of file rpcconsole.cpp.
References ui.
Referenced by setClientModel().
setNetworkActive
void RPCConsole::setNetworkActive (bool networkActive) slot
Set network state shown in the UI.
Definition at line 909 of file rpcconsole.cpp.
References updateNetworkState().
Referenced by setClientModel().
setNumBlocks
void RPCConsole::setNumBlocks (int count, const QDateTime & blockDate, const QString & blockHash, double nVerificationProgress, bool headers) slot
Set number of blocks, last block date and last block hash shown in the UI.
Definition at line 914 of file rpcconsole.cpp.
References count, and ui.
Referenced by setClientModel().
setNumConnections
void RPCConsole::setNumConnections (int count) slot
Set number of connections shown in the UI.
Definition at line 901 of file rpcconsole.cpp.
References clientModel, and updateNetworkState().
Referenced by setClientModel().
setTabFocus
void RPCConsole::setTabFocus (enum TabTypes tabType) slot
set which tab has the focus (is visible)
Definition at line 1353 of file rpcconsole.cpp.
References showPage().
Referenced by BitcoinGUI::showConsole(), BitcoinGUI::showGraph(), BitcoinGUI::showInfo(), BitcoinGUI::showPeers(), and BitcoinGUI::showRepair().
setTrafficGraphRange()
void RPCConsole::setTrafficGraphRange (TrafficGraphData::GraphRange range) private
Definition at line 1076 of file rpcconsole.cpp.
References GUIUtil::formatDurationStr(), TrafficGraphData::RangeMinutes, and ui.
Referenced by on_sldGraphRange_valueChanged(), and RPCConsole().
showBanTableContextMenu
void RPCConsole::showBanTableContextMenu (const QPoint & point) private slot
Show custom context menu on Bans tab.
Definition at line 1262 of file rpcconsole.cpp.
References banTableContextMenu, and ui.
Referenced by setClientModel().
showEvent
void RPCConsole::showEvent (QShowEvent * event) private slot
Definition at line 1221 of file rpcconsole.cpp.
References clientModel, ClientModel::getPeerTableModel(), and PeerTableModel::startAutoRefresh().
showOrHideBanTableIfRequired
void RPCConsole::showOrHideBanTableIfRequired () private slot
Hides ban table if no bans are present.
Definition at line 1343 of file rpcconsole.cpp.
References clientModel, ClientModel::getBanTableModel(), BanTableModel::shouldShow(), and ui.
Referenced by setClientModel().
showPage
void RPCConsole::showPage (int index) private slot
custom tab buttons clicked
Definition at line 950 of file rpcconsole.cpp.
References GUIUtil::Bold, GUIUtil::Normal, pageButtons, GUIUtil::setFont(), ui, and GUIUtil::updateFonts().
Referenced by RPCConsole(), and setTabFocus().
showPeersTableContextMenu
void RPCConsole::showPeersTableContextMenu (const QPoint & point) private slot
Show custom context menu on Peers tab.
Definition at line 1255 of file rpcconsole.cpp.
References peersTableContextMenu, and ui.
Referenced by setClientModel().
startExecutor()
void RPCConsole::startExecutor () private
Definition at line 1031 of file rpcconsole.cpp.
References cmdRequest(), message(), stopExecutor(), and thread.
Referenced by setClientModel().
stopExecutor
void RPCConsole::stopExecutor () signal
Referenced by setClientModel(), and startExecutor().
unbanSelectedNode
void RPCConsole::unbanSelectedNode () slot
Unban a selected node on the Bans tab.
Definition at line 1313 of file rpcconsole.cpp.
References BanTableModel::Address, clientModel, g_connman, ClientModel::getBanTableModel(), GUIUtil::getEntryData(), CSubNet::IsValid(), LookupSubNet(), BanTableModel::refresh(), and ui.
Referenced by setClientModel().
updateMasternodeCount
void RPCConsole::updateMasternodeCount () slot
Update number of masternodes shown in the UI.
Definition at line 923 of file rpcconsole.cpp.
References clientModel, ClientModel::getMasternodeList(), and ui.
Referenced by setClientModel().
updateNetworkState()
void RPCConsole::updateNetworkState () private
Update UI with latest network info from model.
Definition at line 888 of file rpcconsole.cpp.
References clientModel, CONNECTIONS_IN, CONNECTIONS_OUT, ClientModel::getNetworkActive(), ClientModel::getNumConnections(), and ui.
Referenced by setClientModel(), setNetworkActive(), and setNumConnections().
updateNodeDetail()
void RPCConsole::updateNodeDetail (const CNodeCombinedStats * stats) private
show detailed information on ui about selected node
Definition at line 1162 of file rpcconsole.cpp.
References CNodeStats::addrLocal, CNodeStats::addrName, CNodeStats::cleanSubVer, CNodeStats::dMinPing, CNodeStats::dPingTime, CNodeStats::dPingWait, CNodeStats::fInbound, CNodeCombinedStats::fNodeStateStatsAvailable, GUIUtil::formatBytes(), GUIUtil::formatDurationStr(), GUIUtil::formatPingTime(), GUIUtil::formatServicesStr(), GUIUtil::formatTimeOffset(), CNodeStats::fWhitelisted, GetSystemTimeInSeconds(), CNodeStateStats::nCommonHeight, CNodeStats::nLastRecv, CNodeStats::nLastSend, CNodeStateStats::nMisbehavior, CNodeStats::nodeid, CNodeCombinedStats::nodeStateStats, CNodeCombinedStats::nodeStats, CNodeStats::nRecvBytes, CNodeStats::nSendBytes, CNodeStats::nServices, CNodeStats::nStartingHeight, CNodeStateStats::nSyncHeight, CNodeStats::nTimeConnected, CNodeStats::nTimeOffset, CNodeStats::nVersion, and ui.
Referenced by peerLayoutChanged(), and peerSelected().
walletReindex
void RPCConsole::walletReindex () slot
Restart wallet with "-reindex".
Definition at line 799 of file rpcconsole.cpp.
References buildParameterlist(), and REINDEX().
Referenced by RPCConsole().
walletRescan
void RPCConsole::walletRescan () slot
Restart wallet with "-rescan".
Definition at line 775 of file rpcconsole.cpp.
References buildParameterlist(), and RESCAN().
Referenced by RPCConsole().
walletSalvage
void RPCConsole::walletSalvage () slot
Wallet repair options.
Restart wallet with "-salvagewallet".
Definition at line 769 of file rpcconsole.cpp.
References buildParameterlist(), and SALVAGEWALLET().
walletUpgrade
void RPCConsole::walletUpgrade () slot
Restart wallet with "-upgradewallet".
Definition at line 793 of file rpcconsole.cpp.
References buildParameterlist(), and UPGRADEWALLET().
Referenced by RPCConsole().
walletZaptxes1
void RPCConsole::walletZaptxes1 () slot
Restart wallet with "-zapwallettxes=1".
Definition at line 781 of file rpcconsole.cpp.
References buildParameterlist(), and ZAPTXES1().
Referenced by RPCConsole().
walletZaptxes2
void RPCConsole::walletZaptxes2 () slot
Restart wallet with "-zapwallettxes=2".
Definition at line 787 of file rpcconsole.cpp.
References buildParameterlist(), and ZAPTXES2().
Referenced by RPCConsole().
Member Data Documentation
autoCompleter
QCompleter* RPCConsole::autoCompleter private
Definition at line 174 of file rpcconsole.h.
Referenced by eventFilter(), and setClientModel().
banTableContextMenu
QMenu* RPCConsole::banTableContextMenu private
Definition at line 172 of file rpcconsole.h.
Referenced by setClientModel(), and showBanTableContextMenu().
cachedNodeids
QList<NodeId> RPCConsole::cachedNodeids private
Definition at line 169 of file rpcconsole.h.
Referenced by clearSelectedNode(), peerLayoutAboutToChange(), and peerLayoutChanged().
clientModel
ClientModel* RPCConsole::clientModel private
Definition at line 165 of file rpcconsole.h.
Referenced by banSelectedNode(), hideEvent(), peerLayoutAboutToChange(), peerLayoutChanged(), peerSelected(), setClientModel(), setNumConnections(), showEvent(), showOrHideBanTableIfRequired(), unbanSelectedNode(), updateMasternodeCount(), and updateNetworkState().
cmdBeforeBrowsing
QString RPCConsole::cmdBeforeBrowsing private
Definition at line 168 of file rpcconsole.h.
Referenced by browseHistory(), and on_lineEdit_returnPressed().
consoleFontSize
int RPCConsole::consoleFontSize private
Definition at line 173 of file rpcconsole.h.
Referenced by clear(), fontBigger(), fontSmaller(), RPCConsole(), and setFontSize().
history
QStringList RPCConsole::history private
Definition at line 166 of file rpcconsole.h.
Referenced by browseHistory(), clear(), and on_lineEdit_returnPressed().
historyPtr
int RPCConsole::historyPtr private
Definition at line 167 of file rpcconsole.h.
Referenced by browseHistory(), clear(), and on_lineEdit_returnPressed().
pageButtons
QButtonGroup RPCConsole::pageButtons private
Definition at line 164 of file rpcconsole.h.
Referenced by RPCConsole(), and showPage().
peersTableContextMenu
QMenu* RPCConsole::peersTableContextMenu private
Definition at line 171 of file rpcconsole.h.
Referenced by setClientModel(), and showPeersTableContextMenu().
rpcTimerInterface
RPCTimerInterface* RPCConsole::rpcTimerInterface private
Definition at line 170 of file rpcconsole.h.
Referenced by RPCConsole(), and ~RPCConsole().
thread
QThread RPCConsole::thread private
Definition at line 175 of file rpcconsole.h.
Referenced by setClientModel(), and startExecutor().
ui
Ui::RPCConsole* RPCConsole::ui private
Definition at line 163 of file rpcconsole.h.
Referenced by banSelectedNode(), browseHistory(), changeEvent(), clear(), clearSelectedNode(), disconnectSelectedNode(), eventFilter(), message(), on_lineEdit_returnPressed(), on_stackedWidgetRPC_currentChanged(), peerLayoutAboutToChange(), peerLayoutChanged(), RPCConsole(), scrollToEnd(), setButtonIcons(), setClientModel(), setFontSize(), setInstantSendLockCount(), setMempoolSize(), setNumBlocks(), setTrafficGraphRange(), showBanTableContextMenu(), showOrHideBanTableIfRequired(), showPage(), showPeersTableContextMenu(), unbanSelectedNode(), updateMasternodeCount(), updateNetworkState(), updateNodeDetail(), and ~RPCConsole().
The documentation for this class was generated from the following files:
src/qt/rpcconsole.h
src/qt/rpcconsole.cpp
Released under the MIT license