Dash Core: CCoinControl Class Reference
CCoinControl Class Reference
#include <coincontrol.h>
Public Member Functions
CCoinControl ()
void SetNull ()
bool HasSelected () const
bool IsSelected (const COutPoint &output) const
void Select (const COutPoint &output)
void UnSelect (const COutPoint &output)
void UnSelectAll ()
void ListSelected (std::vector< COutPoint > &vOutpoints) const
Public Attributes
CTxDestination destChange
bool fUsePrivateSend
bool fUseInstantSend
bool fAllowOtherInputs
If false, allows unselected inputs, but requires all selected inputs be used.
bool fAllowWatchOnly
Includes watch only addresses which match the ISMINE_WATCH_SOLVABLE criteria.
CAmount nMinimumTotalFee
Minimum absolute fee (not per kilobyte)
Private Attributes
std::set< COutPoint > setSelected
Detailed Description
Coin Control Features.
Definition at line 11 of file coincontrol.h.
Constructor & Destructor Documentation
CCoinControl()
CCoinControl::CCoinControl () inline
Definition at line 24 of file coincontrol.h.
Member Function Documentation
HasSelected()
bool CCoinControl::HasSelected () const inline
Definition at line 40 of file coincontrol.h.
Referenced by CWallet::AvailableCoins(), SendCoinsDialog::coinControlUpdateLabels(), CWallet::SelectCoins(), and SendCoinsDialog::updateFeeSectionControls().
IsSelected()
bool CCoinControl::IsSelected (const COutPoint & output) const inline
Definition at line 45 of file coincontrol.h.
Referenced by CWallet::AvailableCoins(), CWallet::FundTransaction(), and CoinControlDialog::updateView().
ListSelected()
void CCoinControl::ListSelected (std::vector< COutPoint > & vOutpoints) const inline
Definition at line 65 of file coincontrol.h.
Referenced by CWallet::SelectCoins(), and CoinControlDialog::updateLabels().
Select()
void CCoinControl::Select (const COutPoint & output) inline
Definition at line 50 of file coincontrol.h.
Referenced by CPrivateSendClient::CreateDenominated(), CWallet::FundTransaction(), CPrivateSendClient::MakeCollateralAmounts(), and CoinControlDialog::viewItemChanged().
SetNull()
void CCoinControl::SetNull () inline
Definition at line 29 of file coincontrol.h.
Referenced by CCoinControl(), and SendCoinsDialog::coinControlFeatureChanged().
UnSelect()
void CCoinControl::UnSelect (const COutPoint & output) inline
Definition at line 55 of file coincontrol.h.
Referenced by CoinControlDialog::updateLabels(), CoinControlDialog::updateView(), and CoinControlDialog::viewItemChanged().
UnSelectAll()
void CCoinControl::UnSelectAll () inline
Definition at line 60 of file coincontrol.h.
Referenced by CoinControlDialog::buttonSelectAllClicked(), and SendCoinsDialog::send().
Member Data Documentation
destChange
CTxDestination CCoinControl::destChange
Definition at line 14 of file coincontrol.h.
Referenced by SendCoinsDialog::coinControlChangeChecked(), SendCoinsDialog::coinControlChangeEdited(), CPrivateSendClient::CreateDenominated(), CWallet::CreateTransaction(), CPrivateSendClient::MakeCollateralAmounts(), and SetNull().
fAllowOtherInputs
bool CCoinControl::fAllowOtherInputs
If false, allows unselected inputs, but requires all selected inputs be used.
Definition at line 18 of file coincontrol.h.
Referenced by CWallet::AvailableCoins(), CPrivateSendClient::CreateDenominated(), CWallet::FundTransaction(), CPrivateSendClient::MakeCollateralAmounts(), CWallet::SelectCoins(), and SetNull().
fAllowWatchOnly
bool CCoinControl::fAllowWatchOnly
Includes watch only addresses which match the ISMINE_WATCH_SOLVABLE criteria.
Definition at line 20 of file coincontrol.h.
Referenced by CWallet::AvailableCoins(), CPrivateSendClient::CreateDenominated(), CWallet::FundTransaction(), CPrivateSendClient::MakeCollateralAmounts(), and SetNull().
fUseInstantSend
bool CCoinControl::fUseInstantSend
Definition at line 16 of file coincontrol.h.
Referenced by SendCoinsDialog::SendCoinsDialog(), SetNull(), SendCoinsDialog::updateInstantSend(), and CoinControlDialog::updateLabels().
fUsePrivateSend
bool CCoinControl::fUsePrivateSend
Definition at line 15 of file coincontrol.h.
Referenced by SendCoinsDialog::SendCoinsDialog(), SetNull(), SendCoinsDialog::updateDisplayUnit(), CoinControlDialog::updateLabels(), and CoinControlDialog::viewItemChanged().
nMinimumTotalFee
CAmount CCoinControl::nMinimumTotalFee
Minimum absolute fee (not per kilobyte)
Definition at line 22 of file coincontrol.h.
Referenced by CWallet::CreateTransaction(), SetNull(), SendCoinsDialog::updateGlobalFeeVariables(), and CoinControlDialog::updateLabels().
setSelected
std::set<COutPoint> CCoinControl::setSelected private
Definition at line 71 of file coincontrol.h.
Referenced by HasSelected(), IsSelected(), ListSelected(), Select(), SetNull(), UnSelect(), and UnSelectAll().
The documentation for this class was generated from the following file:
src/coincontrol.h