Dash Core: payments::PaymentRequest Class Reference
payments::PaymentRequest Class Reference
#include <paymentrequest.pb.h>
Public Member Functions
PaymentRequest ()
virtual ~PaymentRequest ()
PaymentRequest (const PaymentRequest &from)
PaymentRequest & operator= (const PaymentRequest &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline ::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PaymentRequest *other)
PaymentRequest * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PaymentRequest &from)
void MergeFrom (const PaymentRequest &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_payment_details_version () const
void clear_payment_details_version ()
inline ::google::protobuf::uint32 payment_details_version () const
void set_payment_details_version (::google::protobuf::uint32 value)
bool has_pki_type () const
void clear_pki_type ()
const ::std::string & pki_type () const
void set_pki_type (const ::std::string &value)
void set_pki_type (const char *value)
void set_pki_type (const char *value, size_t size)
inline ::std::string * mutable_pki_type ()
inline ::std::string * release_pki_type ()
void set_allocated_pki_type (::std::string *pki_type)
bool has_pki_data () const
void clear_pki_data ()
const ::std::string & pki_data () const
void set_pki_data (const ::std::string &value)
void set_pki_data (const char *value)
void set_pki_data (const void *value, size_t size)
inline ::std::string * mutable_pki_data ()
inline ::std::string * release_pki_data ()
void set_allocated_pki_data (::std::string *pki_data)
bool has_serialized_payment_details () const
void clear_serialized_payment_details ()
const ::std::string & serialized_payment_details () const
void set_serialized_payment_details (const ::std::string &value)
void set_serialized_payment_details (const char *value)
void set_serialized_payment_details (const void *value, size_t size)
inline ::std::string * mutable_serialized_payment_details ()
inline ::std::string * release_serialized_payment_details ()
void set_allocated_serialized_payment_details (::std::string *serialized_payment_details)
bool has_signature () const
void clear_signature ()
const ::std::string & signature () const
void set_signature (const ::std::string &value)
void set_signature (const char *value)
void set_signature (const void *value, size_t size)
inline ::std::string * mutable_signature ()
inline ::std::string * release_signature ()
void set_allocated_signature (::std::string *signature)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const PaymentRequest & default_instance ()
Static Public Attributes
static const int kPaymentDetailsVersionFieldNumber = 1
static const int kPkiTypeFieldNumber = 2
static const int kPkiDataFieldNumber = 3
static const int kSerializedPaymentDetailsFieldNumber = 4
static const int kSignatureFieldNumber = 5
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_payment_details_version ()
void clear_has_payment_details_version ()
void set_has_pki_type ()
void clear_has_pki_type ()
void set_has_pki_data ()
void clear_has_pki_data ()
void set_has_serialized_payment_details ()
void clear_has_serialized_payment_details ()
void set_has_signature ()
void clear_has_signature ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint32 _has_bits_ [1]
int _cached_size_
::std::string * pki_type_
::std::string * pki_data_
::std::string * serialized_payment_details_
::std::string * signature_
::google::protobuf::uint32 payment_details_version_
Static Private Attributes
::std::string * _default_pki_type_ = NULL
static PaymentRequest * default_instance_ = NULL
Friends
void protobuf_AddDesc_paymentrequest_2eproto ()
void protobuf_AssignDesc_paymentrequest_2eproto ()
void protobuf_ShutdownFile_paymentrequest_2eproto ()
Detailed Description
Definition at line 302 of file paymentrequest.pb.h.
Constructor & Destructor Documentation
PaymentRequest() [1/2]
payments::PaymentRequest::PaymentRequest ()
Definition at line 1080 of file paymentrequest.pb.cc.
Referenced by New().
~PaymentRequest()
payments::PaymentRequest::~PaymentRequest () virtual
Definition at line 1107 of file paymentrequest.pb.cc.
PaymentRequest() [2/2]
payments::PaymentRequest::PaymentRequest (const PaymentRequest & from)
Definition at line 1089 of file paymentrequest.pb.cc.
Member Function Documentation
ByteSize()
int payments::PaymentRequest::ByteSize () const
Definition at line 1371 of file paymentrequest.pb.cc.
Clear()
void payments::PaymentRequest::Clear ()
Definition at line 1150 of file paymentrequest.pb.cc.
Referenced by CopyFrom(), and PaymentRequestPlus::parse().
clear_has_payment_details_version()
void payments::PaymentRequest::clear_has_payment_details_version () inline private
Definition at line 1255 of file paymentrequest.pb.h.
Referenced by clear_payment_details_version().
clear_has_pki_data()
void payments::PaymentRequest::clear_has_pki_data () inline private
Definition at line 1355 of file paymentrequest.pb.h.
Referenced by clear_pki_data(), release_pki_data(), and set_allocated_pki_data().
clear_has_pki_type()
void payments::PaymentRequest::clear_has_pki_type () inline private
Definition at line 1279 of file paymentrequest.pb.h.
Referenced by clear_pki_type(), release_pki_type(), and set_allocated_pki_type().
clear_has_serialized_payment_details()
void payments::PaymentRequest::clear_has_serialized_payment_details () inline private
Definition at line 1431 of file paymentrequest.pb.h.
Referenced by clear_serialized_payment_details(), release_serialized_payment_details(), and set_allocated_serialized_payment_details().
clear_has_signature()
void payments::PaymentRequest::clear_has_signature () inline private
Definition at line 1507 of file paymentrequest.pb.h.
Referenced by clear_signature(), release_signature(), and set_allocated_signature().
clear_payment_details_version()
void payments::PaymentRequest::clear_payment_details_version () inline
Definition at line 1258 of file paymentrequest.pb.h.
clear_pki_data()
void payments::PaymentRequest::clear_pki_data () inline
Definition at line 1358 of file paymentrequest.pb.h.
clear_pki_type()
void payments::PaymentRequest::clear_pki_type () inline
Definition at line 1282 of file paymentrequest.pb.h.
clear_serialized_payment_details()
void payments::PaymentRequest::clear_serialized_payment_details () inline
Definition at line 1434 of file paymentrequest.pb.h.
clear_signature()
void payments::PaymentRequest::clear_signature () inline
Definition at line 1510 of file paymentrequest.pb.h.
CopyFrom() [1/2]
void payments::PaymentRequest::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1456 of file paymentrequest.pb.cc.
Referenced by operator=().
CopyFrom() [2/2]
void payments::PaymentRequest::CopyFrom (const PaymentRequest & from)
Definition at line 1462 of file paymentrequest.pb.cc.
default_instance()
const PaymentRequest & payments::PaymentRequest::default_instance () static
Definition at line 1139 of file paymentrequest.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * payments::PaymentRequest::descriptor () static
Definition at line 1134 of file paymentrequest.pb.cc.
GetCachedSize()
int payments::PaymentRequest::GetCachedSize () const inline
Definition at line 343 of file paymentrequest.pb.h.
GetMetadata()
google::protobuf::Metadata payments::PaymentRequest::GetMetadata () const
Definition at line 1487 of file paymentrequest.pb.cc.
has_payment_details_version()
bool payments::PaymentRequest::has_payment_details_version () const inline
Definition at line 1249 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_pki_data()
bool payments::PaymentRequest::has_pki_data () const inline
Definition at line 1349 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_pki_type()
bool payments::PaymentRequest::has_pki_type () const inline
Definition at line 1273 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_serialized_payment_details()
bool payments::PaymentRequest::has_serialized_payment_details () const inline
Definition at line 1425 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_signature()
bool payments::PaymentRequest::has_signature () const inline
Definition at line 1501 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
InitAsDefaultInstance()
void payments::PaymentRequest::InitAsDefaultInstance () private
Definition at line 1086 of file paymentrequest.pb.cc.
Referenced by payments::protobuf_AddDesc_paymentrequest_2eproto().
IsInitialized()
bool payments::PaymentRequest::IsInitialized () const
Definition at line 1468 of file paymentrequest.pb.cc.
Referenced by PaymentRequestPlus::IsInitialized().
MergeFrom() [1/2]
void payments::PaymentRequest::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 1422 of file paymentrequest.pb.cc.
Referenced by CopyFrom(), and PaymentRequest().
MergeFrom() [2/2]
void payments::PaymentRequest::MergeFrom (const PaymentRequest & from)
Definition at line 1434 of file paymentrequest.pb.cc.
MergePartialFromCodedStream()
bool payments::PaymentRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 1178 of file paymentrequest.pb.cc.
mutable_pki_data()
std::string * payments::PaymentRequest::mutable_pki_data () inline
Definition at line 1392 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_pki_type()
std::string * payments::PaymentRequest::mutable_pki_type () inline
Definition at line 1316 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_serialized_payment_details()
std::string * payments::PaymentRequest::mutable_serialized_payment_details () inline
Definition at line 1468 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_signature()
std::string * payments::PaymentRequest::mutable_signature () inline
Definition at line 1544 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_unknown_fields()
inline ::google::protobuf::UnknownFieldSet* payments::PaymentRequest::mutable_unknown_fields () inline
Definition at line 318 of file paymentrequest.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
New()
PaymentRequest * payments::PaymentRequest::New () const
Definition at line 1146 of file paymentrequest.pb.cc.
operator=()
PaymentRequest& payments::PaymentRequest::operator= (const PaymentRequest & from) inline
Definition at line 309 of file paymentrequest.pb.h.
payment_details_version()
google::protobuf::uint32 payments::PaymentRequest::payment_details_version () const inline
Definition at line 1262 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), PaymentRequestPlus::parse(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
pki_data()
const ::std::string & payments::PaymentRequest::pki_data () const inline
Definition at line 1364 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentRequestPlus::getMerchant(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_pki_data().
pki_type()
const ::std::string & payments::PaymentRequest::pki_type () const inline
Definition at line 1288 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentRequestPlus::getMerchant(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_pki_type().
release_pki_data()
std::string * payments::PaymentRequest::release_pki_data () inline
Definition at line 1400 of file paymentrequest.pb.h.
release_pki_type()
std::string * payments::PaymentRequest::release_pki_type () inline
Definition at line 1324 of file paymentrequest.pb.h.
release_serialized_payment_details()
std::string * payments::PaymentRequest::release_serialized_payment_details () inline
Definition at line 1476 of file paymentrequest.pb.h.
release_signature()
std::string * payments::PaymentRequest::release_signature () inline
Definition at line 1552 of file paymentrequest.pb.h.
serialized_payment_details()
const ::std::string & payments::PaymentRequest::serialized_payment_details () const inline
Definition at line 1440 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), PaymentRequestPlus::parse(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_serialized_payment_details().
SerializeWithCachedSizes()
void payments::PaymentRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 1280 of file paymentrequest.pb.cc.
SerializeWithCachedSizesToArray()
google::protobuf::uint8 * payments::PaymentRequest::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 1323 of file paymentrequest.pb.cc.
set_allocated_pki_data()
void payments::PaymentRequest::set_allocated_pki_data (::std::string * pki_data) inline
Definition at line 1410 of file paymentrequest.pb.h.
set_allocated_pki_type()
void payments::PaymentRequest::set_allocated_pki_type (::std::string * pki_type) inline
Definition at line 1334 of file paymentrequest.pb.h.
set_allocated_serialized_payment_details()
void payments::PaymentRequest::set_allocated_serialized_payment_details (::std::string * serialized_payment_details) inline
Definition at line 1486 of file paymentrequest.pb.h.
set_allocated_signature()
void payments::PaymentRequest::set_allocated_signature (::std::string * signature) inline
Definition at line 1562 of file paymentrequest.pb.h.
set_has_payment_details_version()
void payments::PaymentRequest::set_has_payment_details_version () inline private
Definition at line 1252 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream(), and set_payment_details_version().
set_has_pki_data()
void payments::PaymentRequest::set_has_pki_data () inline private
Definition at line 1352 of file paymentrequest.pb.h.
Referenced by mutable_pki_data(), set_allocated_pki_data(), and set_pki_data().
set_has_pki_type()
void payments::PaymentRequest::set_has_pki_type () inline private
Definition at line 1276 of file paymentrequest.pb.h.
Referenced by mutable_pki_type(), set_allocated_pki_type(), and set_pki_type().
set_has_serialized_payment_details()
void payments::PaymentRequest::set_has_serialized_payment_details () inline private
Definition at line 1428 of file paymentrequest.pb.h.
Referenced by mutable_serialized_payment_details(), set_allocated_serialized_payment_details(), and set_serialized_payment_details().
set_has_signature()
void payments::PaymentRequest::set_has_signature () inline private
Definition at line 1504 of file paymentrequest.pb.h.
Referenced by mutable_signature(), set_allocated_signature(), and set_signature().
set_payment_details_version()
void payments::PaymentRequest::set_payment_details_version (::google::protobuf::uint32 value) inline
Definition at line 1266 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_pki_data() [1/3]
void payments::PaymentRequest::set_pki_data (const ::std::string & value) inline
Definition at line 1368 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_pki_data() [2/3]
void payments::PaymentRequest::set_pki_data (const char * value) inline
Definition at line 1376 of file paymentrequest.pb.h.
set_pki_data() [3/3]
void payments::PaymentRequest::set_pki_data (const void * value, size_t size) inline
Definition at line 1384 of file paymentrequest.pb.h.
set_pki_type() [1/3]
void payments::PaymentRequest::set_pki_type (const ::std::string & value) inline
Definition at line 1292 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_pki_type() [2/3]
void payments::PaymentRequest::set_pki_type (const char * value) inline
Definition at line 1300 of file paymentrequest.pb.h.
set_pki_type() [3/3]
void payments::PaymentRequest::set_pki_type (const char * value, size_t size) inline
Definition at line 1308 of file paymentrequest.pb.h.
set_serialized_payment_details() [1/3]
void payments::PaymentRequest::set_serialized_payment_details (const ::std::string & value) inline
Definition at line 1444 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_serialized_payment_details() [2/3]
void payments::PaymentRequest::set_serialized_payment_details (const char * value) inline
Definition at line 1452 of file paymentrequest.pb.h.
set_serialized_payment_details() [3/3]
void payments::PaymentRequest::set_serialized_payment_details (const void * value, size_t size) inline
Definition at line 1460 of file paymentrequest.pb.h.
set_signature() [1/3]
void payments::PaymentRequest::set_signature (const ::std::string & value) inline
Definition at line 1520 of file paymentrequest.pb.h.
Referenced by PaymentRequestPlus::getMerchant(), and MergeFrom().
set_signature() [2/3]
void payments::PaymentRequest::set_signature (const char * value) inline
Definition at line 1528 of file paymentrequest.pb.h.
set_signature() [3/3]
void payments::PaymentRequest::set_signature (const void * value, size_t size) inline
Definition at line 1536 of file paymentrequest.pb.h.
SetCachedSize()
void payments::PaymentRequest::SetCachedSize (int size) const private
Definition at line 1129 of file paymentrequest.pb.cc.
SharedCtor()
void payments::PaymentRequest::SharedCtor () private
Definition at line 1096 of file paymentrequest.pb.cc.
Referenced by PaymentRequest().
SharedDtor()
void payments::PaymentRequest::SharedDtor () private
Definition at line 1112 of file paymentrequest.pb.cc.
Referenced by ~PaymentRequest().
signature()
const ::std::string & payments::PaymentRequest::signature () const inline
Definition at line 1516 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentRequestPlus::getMerchant(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_signature().
Swap()
void payments::PaymentRequest::Swap (PaymentRequest * other)
Definition at line 1474 of file paymentrequest.pb.cc.
unknown_fields()
const ::google::protobuf::UnknownFieldSet& payments::PaymentRequest::unknown_fields () const inline
Definition at line 314 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
protobuf_AddDesc_paymentrequest_2eproto
void protobuf_AddDesc_paymentrequest_2eproto () friend
Definition at line 201 of file paymentrequest.pb.cc.
Referenced by default_instance().
protobuf_AssignDesc_paymentrequest_2eproto
void protobuf_AssignDesc_paymentrequest_2eproto () friend
Definition at line 45 of file paymentrequest.pb.cc.
protobuf_ShutdownFile_paymentrequest_2eproto
void protobuf_ShutdownFile_paymentrequest_2eproto () friend
Definition at line 184 of file paymentrequest.pb.cc.
Member Data Documentation
_cached_size_
int payments::PaymentRequest::_cached_size_ mutable private
Definition at line 426 of file paymentrequest.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
_default_pki_type_
std::string * payments::PaymentRequest::_default_pki_type_ = NULL static private
Definition at line 427 of file paymentrequest.pb.h.
Referenced by Clear(), clear_pki_type(), mutable_pki_type(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), release_pki_type(), set_allocated_pki_type(), set_pki_type(), SharedCtor(), and SharedDtor().
_has_bits_
::google::protobuf::uint32 payments::PaymentRequest::_has_bits_[1] private
Definition at line 425 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), clear_has_payment_details_version(), clear_has_pki_data(), clear_has_pki_type(), clear_has_serialized_payment_details(), clear_has_signature(), has_payment_details_version(), has_pki_data(), has_pki_type(), has_serialized_payment_details(), has_signature(), IsInitialized(), MergeFrom(), set_has_payment_details_version(), set_has_pki_data(), set_has_pki_type(), set_has_serialized_payment_details(), set_has_signature(), SharedCtor(), and Swap().
_unknown_fields_
::google::protobuf::UnknownFieldSet payments::PaymentRequest::_unknown_fields_ private
Definition at line 423 of file paymentrequest.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
default_instance_
PaymentRequest * payments::PaymentRequest::default_instance_ = NULL static private
Definition at line 438 of file paymentrequest.pb.h.
Referenced by default_instance(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_AssignDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), and SharedDtor().
kPaymentDetailsVersionFieldNumber
const int payments::PaymentRequest::kPaymentDetailsVersionFieldNumber = 1 static
Definition at line 358 of file paymentrequest.pb.h.
kPkiDataFieldNumber
const int payments::PaymentRequest::kPkiDataFieldNumber = 3 static
Definition at line 377 of file paymentrequest.pb.h.
kPkiTypeFieldNumber
const int payments::PaymentRequest::kPkiTypeFieldNumber = 2 static
Definition at line 365 of file paymentrequest.pb.h.
kSerializedPaymentDetailsFieldNumber
const int payments::PaymentRequest::kSerializedPaymentDetailsFieldNumber = 4 static
Definition at line 389 of file paymentrequest.pb.h.
kSignatureFieldNumber
const int payments::PaymentRequest::kSignatureFieldNumber = 5 static
Definition at line 401 of file paymentrequest.pb.h.
payment_details_version_
::google::protobuf::uint32 payments::PaymentRequest::payment_details_version_ private
Definition at line 432 of file paymentrequest.pb.h.
Referenced by Clear(), clear_payment_details_version(), MergePartialFromCodedStream(), payment_details_version(), set_payment_details_version(), SharedCtor(), and Swap().
pki_data_
::std::string* payments::PaymentRequest::pki_data_ private
Definition at line 429 of file paymentrequest.pb.h.
Referenced by Clear(), clear_pki_data(), mutable_pki_data(), pki_data(), release_pki_data(), set_allocated_pki_data(), set_pki_data(), SharedCtor(), SharedDtor(), and Swap().
pki_type_
::std::string* payments::PaymentRequest::pki_type_ private
Definition at line 428 of file paymentrequest.pb.h.
Referenced by Clear(), clear_pki_type(), mutable_pki_type(), pki_type(), release_pki_type(), set_allocated_pki_type(), set_pki_type(), SharedCtor(), SharedDtor(), and Swap().
serialized_payment_details_
::std::string* payments::PaymentRequest::serialized_payment_details_ private
Definition at line 430 of file paymentrequest.pb.h.
Referenced by Clear(), clear_serialized_payment_details(), mutable_serialized_payment_details(), release_serialized_payment_details(), serialized_payment_details(), set_allocated_serialized_payment_details(), set_serialized_payment_details(), SharedCtor(), SharedDtor(), and Swap().
signature_
::std::string* payments::PaymentRequest::signature_ private
Definition at line 431 of file paymentrequest.pb.h.
Referenced by Clear(), clear_signature(), mutable_signature(), release_signature(), set_allocated_signature(), set_signature(), SharedCtor(), SharedDtor(), signature(), and Swap().
The documentation for this class was generated from the following files:
src/qt/paymentrequest.pb.h
src/qt/paymentrequest.pb.cc