Dash Core: payments::PaymentDetails Class Reference
payments::PaymentDetails Class Reference
#include <paymentrequest.pb.h>
Public Member Functions
PaymentDetails ()
virtual ~PaymentDetails ()
PaymentDetails (const PaymentDetails &from)
PaymentDetails & operator= (const PaymentDetails &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline ::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PaymentDetails *other)
PaymentDetails * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PaymentDetails &from)
void MergeFrom (const PaymentDetails &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_network () const
void clear_network ()
const ::std::string & network () const
void set_network (const ::std::string &value)
void set_network (const char *value)
void set_network (const char *value, size_t size)
inline ::std::string * mutable_network ()
inline ::std::string * release_network ()
void set_allocated_network (::std::string *network)
int outputs_size () const
void clear_outputs ()
const ::payments::Output & outputs (int index) const
inline ::payments::Output * mutable_outputs (int index)
inline ::payments::Output * add_outputs ()
const ::google::protobuf::RepeatedPtrField< ::payments::Output > & outputs () const
inline ::google::protobuf::RepeatedPtrField< ::payments::Output > * mutable_outputs ()
bool has_time () const
void clear_time ()
inline ::google::protobuf::uint64 time () const
void set_time (::google::protobuf::uint64 value)
bool has_expires () const
void clear_expires ()
inline ::google::protobuf::uint64 expires () const
void set_expires (::google::protobuf::uint64 value)
bool has_memo () const
void clear_memo ()
const ::std::string & memo () const
void set_memo (const ::std::string &value)
void set_memo (const char *value)
void set_memo (const char *value, size_t size)
inline ::std::string * mutable_memo ()
inline ::std::string * release_memo ()
void set_allocated_memo (::std::string *memo)
bool has_payment_url () const
void clear_payment_url ()
const ::std::string & payment_url () const
void set_payment_url (const ::std::string &value)
void set_payment_url (const char *value)
void set_payment_url (const char *value, size_t size)
inline ::std::string * mutable_payment_url ()
inline ::std::string * release_payment_url ()
void set_allocated_payment_url (::std::string *payment_url)
bool has_merchant_data () const
void clear_merchant_data ()
const ::std::string & merchant_data () const
void set_merchant_data (const ::std::string &value)
void set_merchant_data (const char *value)
void set_merchant_data (const void *value, size_t size)
inline ::std::string * mutable_merchant_data ()
inline ::std::string * release_merchant_data ()
void set_allocated_merchant_data (::std::string *merchant_data)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const PaymentDetails & default_instance ()
Static Public Attributes
static const int kNetworkFieldNumber = 1
static const int kOutputsFieldNumber = 2
static const int kTimeFieldNumber = 3
static const int kExpiresFieldNumber = 4
static const int kMemoFieldNumber = 5
static const int kPaymentUrlFieldNumber = 6
static const int kMerchantDataFieldNumber = 7
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_network ()
void clear_has_network ()
void set_has_time ()
void clear_has_time ()
void set_has_expires ()
void clear_has_expires ()
void set_has_memo ()
void clear_has_memo ()
void set_has_payment_url ()
void clear_has_payment_url ()
void set_has_merchant_data ()
void clear_has_merchant_data ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint32 _has_bits_ [1]
int _cached_size_
::std::string * network_
::google::protobuf::RepeatedPtrField< ::payments::Output > outputs_
::google::protobuf::uint64 time_
::google::protobuf::uint64 expires_
::std::string * memo_
::std::string * payment_url_
::std::string * merchant_data_
Static Private Attributes
::std::string * _default_network_ = NULL
static PaymentDetails * default_instance_ = NULL
Friends
void protobuf_AddDesc_paymentrequest_2eproto ()
void protobuf_AssignDesc_paymentrequest_2eproto ()
void protobuf_ShutdownFile_paymentrequest_2eproto ()
Detailed Description
Definition at line 139 of file paymentrequest.pb.h.
Constructor & Destructor Documentation
PaymentDetails() [1/2]
payments::PaymentDetails::PaymentDetails ()
Definition at line 539 of file paymentrequest.pb.cc.
Referenced by New().
~PaymentDetails()
payments::PaymentDetails::~PaymentDetails () virtual
Definition at line 567 of file paymentrequest.pb.cc.
PaymentDetails() [2/2]
payments::PaymentDetails::PaymentDetails (const PaymentDetails & from)
Definition at line 548 of file paymentrequest.pb.cc.
Member Function Documentation
add_outputs()
payments::Output * payments::PaymentDetails::add_outputs () inline
Definition at line 953 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
ByteSize()
int payments::PaymentDetails::ByteSize () const
Definition at line 922 of file paymentrequest.pb.cc.
Clear()
void payments::PaymentDetails::Clear ()
Definition at line 610 of file paymentrequest.pb.cc.
Referenced by CopyFrom().
clear_expires()
void payments::PaymentDetails::clear_expires () inline
Definition at line 1002 of file paymentrequest.pb.h.
clear_has_expires()
void payments::PaymentDetails::clear_has_expires () inline private
Definition at line 999 of file paymentrequest.pb.h.
Referenced by clear_expires().
clear_has_memo()
void payments::PaymentDetails::clear_has_memo () inline private
Definition at line 1023 of file paymentrequest.pb.h.
Referenced by clear_memo(), release_memo(), and set_allocated_memo().
clear_has_merchant_data()
void payments::PaymentDetails::clear_has_merchant_data () inline private
Definition at line 1175 of file paymentrequest.pb.h.
Referenced by clear_merchant_data(), release_merchant_data(), and set_allocated_merchant_data().
clear_has_network()
void payments::PaymentDetails::clear_has_network () inline private
Definition at line 869 of file paymentrequest.pb.h.
Referenced by clear_network(), release_network(), and set_allocated_network().
clear_has_payment_url()
void payments::PaymentDetails::clear_has_payment_url () inline private
Definition at line 1099 of file paymentrequest.pb.h.
Referenced by clear_payment_url(), release_payment_url(), and set_allocated_payment_url().
clear_has_time()
void payments::PaymentDetails::clear_has_time () inline private
Definition at line 975 of file paymentrequest.pb.h.
Referenced by clear_time().
clear_memo()
void payments::PaymentDetails::clear_memo () inline
Definition at line 1026 of file paymentrequest.pb.h.
clear_merchant_data()
void payments::PaymentDetails::clear_merchant_data () inline
Definition at line 1178 of file paymentrequest.pb.h.
clear_network()
void payments::PaymentDetails::clear_network () inline
Definition at line 872 of file paymentrequest.pb.h.
clear_outputs()
void payments::PaymentDetails::clear_outputs () inline
Definition at line 942 of file paymentrequest.pb.h.
clear_payment_url()
void payments::PaymentDetails::clear_payment_url () inline
Definition at line 1102 of file paymentrequest.pb.h.
clear_time()
void payments::PaymentDetails::clear_time () inline
Definition at line 978 of file paymentrequest.pb.h.
CopyFrom() [1/2]
void payments::PaymentDetails::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 1026 of file paymentrequest.pb.cc.
Referenced by operator=().
CopyFrom() [2/2]
void payments::PaymentDetails::CopyFrom (const PaymentDetails & from)
Definition at line 1032 of file paymentrequest.pb.cc.
default_instance()
const PaymentDetails & payments::PaymentDetails::default_instance () static
Definition at line 599 of file paymentrequest.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * payments::PaymentDetails::descriptor () static
Definition at line 594 of file paymentrequest.pb.cc.
expires()
google::protobuf::uint64 payments::PaymentDetails::expires () const inline
Definition at line 1006 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and PaymentServer::verifyExpired().
GetCachedSize()
int payments::PaymentDetails::GetCachedSize () const inline
Definition at line 180 of file paymentrequest.pb.h.
GetMetadata()
google::protobuf::Metadata payments::PaymentDetails::GetMetadata () const
Definition at line 1060 of file paymentrequest.pb.cc.
has_expires()
bool payments::PaymentDetails::has_expires () const inline
Definition at line 993 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and PaymentServer::verifyExpired().
has_memo()
bool payments::PaymentDetails::has_memo () const inline
Definition at line 1017 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_merchant_data()
bool payments::PaymentDetails::has_merchant_data () const inline
Definition at line 1169 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_network()
bool payments::PaymentDetails::has_network () const inline
Definition at line 863 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_payment_url()
bool payments::PaymentDetails::has_payment_url () const inline
Definition at line 1093 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), PaymentServer::fetchPaymentACK(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_time()
bool payments::PaymentDetails::has_time () const inline
Definition at line 969 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
InitAsDefaultInstance()
void payments::PaymentDetails::InitAsDefaultInstance () private
Definition at line 545 of file paymentrequest.pb.cc.
Referenced by payments::protobuf_AddDesc_paymentrequest_2eproto().
IsInitialized()
bool payments::PaymentDetails::IsInitialized () const
Definition at line 1038 of file paymentrequest.pb.cc.
memo()
const ::std::string & payments::PaymentDetails::memo () const inline
Definition at line 1032 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), MergePartialFromCodedStream(), PaymentServer::processPaymentRequest(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_memo().
merchant_data()
const ::std::string & payments::PaymentDetails::merchant_data () const inline
Definition at line 1184 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentServer::fetchPaymentACK(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_merchant_data().
MergeFrom() [1/2]
void payments::PaymentDetails::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 988 of file paymentrequest.pb.cc.
Referenced by CopyFrom(), and PaymentDetails().
MergeFrom() [2/2]
void payments::PaymentDetails::MergeFrom (const PaymentDetails & from)
Definition at line 1000 of file paymentrequest.pb.cc.
MergePartialFromCodedStream()
bool payments::PaymentDetails::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 653 of file paymentrequest.pb.cc.
mutable_memo()
std::string * payments::PaymentDetails::mutable_memo () inline
Definition at line 1060 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_merchant_data()
std::string * payments::PaymentDetails::mutable_merchant_data () inline
Definition at line 1212 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_network()
std::string * payments::PaymentDetails::mutable_network () inline
Definition at line 906 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_outputs() [1/2]
payments::Output * payments::PaymentDetails::mutable_outputs (int index) inline
Definition at line 949 of file paymentrequest.pb.h.
mutable_outputs() [2/2]
google::protobuf::RepeatedPtrField<::payments::Output > * payments::PaymentDetails::mutable_outputs () inline
Definition at line 963 of file paymentrequest.pb.h.
mutable_payment_url()
std::string * payments::PaymentDetails::mutable_payment_url () inline
Definition at line 1136 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_unknown_fields()
inline ::google::protobuf::UnknownFieldSet* payments::PaymentDetails::mutable_unknown_fields () inline
Definition at line 155 of file paymentrequest.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
network()
const ::std::string & payments::PaymentDetails::network () const inline
Definition at line 878 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentServer::ipcParseCommandLine(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), set_allocated_network(), and PaymentServer::verifyNetwork().
New()
PaymentDetails * payments::PaymentDetails::New () const
Definition at line 606 of file paymentrequest.pb.cc.
operator=()
PaymentDetails& payments::PaymentDetails::operator= (const PaymentDetails & from) inline
Definition at line 146 of file paymentrequest.pb.h.
outputs() [1/2]
const ::payments::Output & payments::PaymentDetails::outputs (int index) const inline
Definition at line 945 of file paymentrequest.pb.h.
Referenced by PaymentRequestPlus::getPayTo(), WalletModel::prepareTransaction(), and WalletModelTransaction::reassignAmounts().
outputs() [2/2]
const ::google::protobuf::RepeatedPtrField<::payments::Output > & payments::PaymentDetails::outputs () const inline
Definition at line 958 of file paymentrequest.pb.h.
Referenced by ByteSize(), IsInitialized(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
outputs_size()
int payments::PaymentDetails::outputs_size () const inline
Definition at line 939 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentRequestPlus::getPayTo(), WalletModel::prepareTransaction(), WalletModelTransaction::reassignAmounts(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
payment_url()
const ::std::string & payments::PaymentDetails::payment_url () const inline
Definition at line 1108 of file paymentrequest.pb.h.
Referenced by ByteSize(), PaymentServer::fetchPaymentACK(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_payment_url().
release_memo()
std::string * payments::PaymentDetails::release_memo () inline
Definition at line 1068 of file paymentrequest.pb.h.
release_merchant_data()
std::string * payments::PaymentDetails::release_merchant_data () inline
Definition at line 1220 of file paymentrequest.pb.h.
release_network()
std::string * payments::PaymentDetails::release_network () inline
Definition at line 914 of file paymentrequest.pb.h.
release_payment_url()
std::string * payments::PaymentDetails::release_payment_url () inline
Definition at line 1144 of file paymentrequest.pb.h.
SerializeWithCachedSizes()
void payments::PaymentDetails::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 792 of file paymentrequest.pb.cc.
SerializeWithCachedSizesToArray()
google::protobuf::uint8 * payments::PaymentDetails::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 854 of file paymentrequest.pb.cc.
set_allocated_memo()
void payments::PaymentDetails::set_allocated_memo (::std::string * memo) inline
Definition at line 1078 of file paymentrequest.pb.h.
set_allocated_merchant_data()
void payments::PaymentDetails::set_allocated_merchant_data (::std::string * merchant_data) inline
Definition at line 1230 of file paymentrequest.pb.h.
set_allocated_network()
void payments::PaymentDetails::set_allocated_network (::std::string * network) inline
Definition at line 924 of file paymentrequest.pb.h.
set_allocated_payment_url()
void payments::PaymentDetails::set_allocated_payment_url (::std::string * payment_url) inline
Definition at line 1154 of file paymentrequest.pb.h.
set_expires()
void payments::PaymentDetails::set_expires (::google::protobuf::uint64 value) inline
Definition at line 1010 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_has_expires()
void payments::PaymentDetails::set_has_expires () inline private
Definition at line 996 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream(), and set_expires().
set_has_memo()
void payments::PaymentDetails::set_has_memo () inline private
Definition at line 1020 of file paymentrequest.pb.h.
Referenced by mutable_memo(), set_allocated_memo(), and set_memo().
set_has_merchant_data()
void payments::PaymentDetails::set_has_merchant_data () inline private
Definition at line 1172 of file paymentrequest.pb.h.
Referenced by mutable_merchant_data(), set_allocated_merchant_data(), and set_merchant_data().
set_has_network()
void payments::PaymentDetails::set_has_network () inline private
Definition at line 866 of file paymentrequest.pb.h.
Referenced by mutable_network(), set_allocated_network(), and set_network().
set_has_payment_url()
void payments::PaymentDetails::set_has_payment_url () inline private
Definition at line 1096 of file paymentrequest.pb.h.
Referenced by mutable_payment_url(), set_allocated_payment_url(), and set_payment_url().
set_has_time()
void payments::PaymentDetails::set_has_time () inline private
Definition at line 972 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream(), and set_time().
set_memo() [1/3]
void payments::PaymentDetails::set_memo (const ::std::string & value) inline
Definition at line 1036 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_memo() [2/3]
void payments::PaymentDetails::set_memo (const char * value) inline
Definition at line 1044 of file paymentrequest.pb.h.
set_memo() [3/3]
void payments::PaymentDetails::set_memo (const char * value, size_t size) inline
Definition at line 1052 of file paymentrequest.pb.h.
set_merchant_data() [1/3]
void payments::PaymentDetails::set_merchant_data (const ::std::string & value) inline
Definition at line 1188 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_merchant_data() [2/3]
void payments::PaymentDetails::set_merchant_data (const char * value) inline
Definition at line 1196 of file paymentrequest.pb.h.
set_merchant_data() [3/3]
void payments::PaymentDetails::set_merchant_data (const void * value, size_t size) inline
Definition at line 1204 of file paymentrequest.pb.h.
set_network() [1/3]
void payments::PaymentDetails::set_network (const ::std::string & value) inline
Definition at line 882 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_network() [2/3]
void payments::PaymentDetails::set_network (const char * value) inline
Definition at line 890 of file paymentrequest.pb.h.
set_network() [3/3]
void payments::PaymentDetails::set_network (const char * value, size_t size) inline
Definition at line 898 of file paymentrequest.pb.h.
set_payment_url() [1/3]
void payments::PaymentDetails::set_payment_url (const ::std::string & value) inline
Definition at line 1112 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_payment_url() [2/3]
void payments::PaymentDetails::set_payment_url (const char * value) inline
Definition at line 1120 of file paymentrequest.pb.h.
set_payment_url() [3/3]
void payments::PaymentDetails::set_payment_url (const char * value, size_t size) inline
Definition at line 1128 of file paymentrequest.pb.h.
set_time()
void payments::PaymentDetails::set_time (::google::protobuf::uint64 value) inline
Definition at line 986 of file paymentrequest.pb.h.
Referenced by MergeFrom().
SetCachedSize()
void payments::PaymentDetails::SetCachedSize (int size) const private
Definition at line 589 of file paymentrequest.pb.cc.
SharedCtor()
void payments::PaymentDetails::SharedCtor () private
Definition at line 555 of file paymentrequest.pb.cc.
Referenced by PaymentDetails().
SharedDtor()
void payments::PaymentDetails::SharedDtor () private
Definition at line 572 of file paymentrequest.pb.cc.
Referenced by ~PaymentDetails().
Swap()
void payments::PaymentDetails::Swap (PaymentDetails * other)
Definition at line 1045 of file paymentrequest.pb.cc.
time()
google::protobuf::uint64 payments::PaymentDetails::time () const inline
Definition at line 982 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
unknown_fields()
const ::google::protobuf::UnknownFieldSet& payments::PaymentDetails::unknown_fields () const inline
Definition at line 151 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
protobuf_AddDesc_paymentrequest_2eproto
void protobuf_AddDesc_paymentrequest_2eproto () friend
Definition at line 201 of file paymentrequest.pb.cc.
Referenced by default_instance().
protobuf_AssignDesc_paymentrequest_2eproto
void protobuf_AssignDesc_paymentrequest_2eproto () friend
Definition at line 45 of file paymentrequest.pb.cc.
protobuf_ShutdownFile_paymentrequest_2eproto
void protobuf_ShutdownFile_paymentrequest_2eproto () friend
Definition at line 184 of file paymentrequest.pb.cc.
Member Data Documentation
_cached_size_
int payments::PaymentDetails::_cached_size_ mutable private
Definition at line 284 of file paymentrequest.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
_default_network_
std::string * payments::PaymentDetails::_default_network_ = NULL static private
Definition at line 285 of file paymentrequest.pb.h.
Referenced by Clear(), clear_network(), mutable_network(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), release_network(), set_allocated_network(), set_network(), SharedCtor(), and SharedDtor().
_has_bits_
::google::protobuf::uint32 payments::PaymentDetails::_has_bits_[1] private
Definition at line 283 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), clear_has_expires(), clear_has_memo(), clear_has_merchant_data(), clear_has_network(), clear_has_payment_url(), clear_has_time(), has_expires(), has_memo(), has_merchant_data(), has_network(), has_payment_url(), has_time(), IsInitialized(), MergeFrom(), set_has_expires(), set_has_memo(), set_has_merchant_data(), set_has_network(), set_has_payment_url(), set_has_time(), SharedCtor(), and Swap().
_unknown_fields_
::google::protobuf::UnknownFieldSet payments::PaymentDetails::_unknown_fields_ private
Definition at line 281 of file paymentrequest.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
default_instance_
PaymentDetails * payments::PaymentDetails::default_instance_ = NULL static private
Definition at line 298 of file paymentrequest.pb.h.
Referenced by default_instance(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_AssignDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), and SharedDtor().
expires_
::google::protobuf::uint64 payments::PaymentDetails::expires_ private
Definition at line 289 of file paymentrequest.pb.h.
Referenced by Clear(), clear_expires(), expires(), MergePartialFromCodedStream(), set_expires(), SharedCtor(), and Swap().
kExpiresFieldNumber
const int payments::PaymentDetails::kExpiresFieldNumber = 4 static
Definition at line 226 of file paymentrequest.pb.h.
kMemoFieldNumber
const int payments::PaymentDetails::kMemoFieldNumber = 5 static
Definition at line 233 of file paymentrequest.pb.h.
kMerchantDataFieldNumber
const int payments::PaymentDetails::kMerchantDataFieldNumber = 7 static
Definition at line 257 of file paymentrequest.pb.h.
kNetworkFieldNumber
const int payments::PaymentDetails::kNetworkFieldNumber = 1 static
Definition at line 195 of file paymentrequest.pb.h.
kOutputsFieldNumber
const int payments::PaymentDetails::kOutputsFieldNumber = 2 static
Definition at line 207 of file paymentrequest.pb.h.
kPaymentUrlFieldNumber
const int payments::PaymentDetails::kPaymentUrlFieldNumber = 6 static
Definition at line 245 of file paymentrequest.pb.h.
kTimeFieldNumber
const int payments::PaymentDetails::kTimeFieldNumber = 3 static
Definition at line 219 of file paymentrequest.pb.h.
memo_
::std::string* payments::PaymentDetails::memo_ private
Definition at line 290 of file paymentrequest.pb.h.
Referenced by Clear(), clear_memo(), memo(), mutable_memo(), release_memo(), set_allocated_memo(), set_memo(), SharedCtor(), SharedDtor(), and Swap().
merchant_data_
::std::string* payments::PaymentDetails::merchant_data_ private
Definition at line 292 of file paymentrequest.pb.h.
Referenced by Clear(), clear_merchant_data(), merchant_data(), mutable_merchant_data(), release_merchant_data(), set_allocated_merchant_data(), set_merchant_data(), SharedCtor(), SharedDtor(), and Swap().
network_
::std::string* payments::PaymentDetails::network_ private
Definition at line 286 of file paymentrequest.pb.h.
Referenced by Clear(), clear_network(), mutable_network(), network(), release_network(), set_allocated_network(), set_network(), SharedCtor(), SharedDtor(), and Swap().
outputs_
::google::protobuf::RepeatedPtrField< ::payments::Output > payments::PaymentDetails::outputs_ private
Definition at line 287 of file paymentrequest.pb.h.
Referenced by add_outputs(), Clear(), clear_outputs(), MergeFrom(), mutable_outputs(), outputs(), outputs_size(), and Swap().
payment_url_
::std::string* payments::PaymentDetails::payment_url_ private
Definition at line 291 of file paymentrequest.pb.h.
Referenced by Clear(), clear_payment_url(), mutable_payment_url(), payment_url(), release_payment_url(), set_allocated_payment_url(), set_payment_url(), SharedCtor(), SharedDtor(), and Swap().
time_
::google::protobuf::uint64 payments::PaymentDetails::time_ private
Definition at line 288 of file paymentrequest.pb.h.
Referenced by Clear(), clear_time(), MergePartialFromCodedStream(), set_time(), SharedCtor(), Swap(), and time().
The documentation for this class was generated from the following files:
src/qt/paymentrequest.pb.h
src/qt/paymentrequest.pb.cc