Dash Core: WalletFrame Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
WalletFrame Class Reference
A container for embedding all wallet-related controls into BitcoinGUI.
#include <walletframe.h>
Public Slots
void gotoOverviewPage ()
Switch to overview (home) page.
void gotoHistoryPage ()
Switch to history (transactions) page.
void gotoMasternodePage ()
Switch to masternode page.
void gotoReceiveCoinsPage ()
Switch to receive coins page.
void gotoSendCoinsPage (QString addr="")
Switch to send coins page.
void gotoPrivateSendCoinsPage (QString addr="")
Switch to PrivateSend coins page.
void gotoSignMessageTab (QString addr="")
Show Sign/Verify Message dialog and switch to sign message tab.
void gotoVerifyMessageTab (QString addr="")
Show Sign/Verify Message dialog and switch to verify message tab.
void encryptWallet (bool status)
Encrypt the wallet.
void backupWallet ()
Backup the wallet.
void changePassphrase ()
Change encrypted wallet passphrase.
void unlockWallet ()
Ask for passphrase to unlock wallet temporarily.
void lockWallet ()
Lock wallet.
void usedSendingAddresses ()
Show used sending addresses.
void usedReceivingAddresses ()
Show used receiving addresses.
void outOfSyncWarningClicked ()
Pass on signal over requested out-of-sync-warning information.
Signals
void requestedSyncWarningInfo ()
Notify that the user has requested more information about the out-of-sync warning.
Public Member Functions
WalletFrame (BitcoinGUI *_gui=0)
~WalletFrame ()
void setClientModel (ClientModel *clientModel)
bool addWallet (const QString &name, WalletModel *walletModel)
bool setCurrentWallet (const QString &name)
bool removeWallet (const QString &name)
void removeAllWallets ()
bool handlePaymentRequest (const SendCoinsRecipient &recipient)
void showOutOfSyncWarning (bool fShow)
WalletView * currentWalletView ()
Private Attributes
QStackedWidget * walletStack
BitcoinGUI * gui
ClientModel * clientModel
QMap< QString, WalletView * > mapWalletViews
bool bOutOfSync
Detailed Description
A container for embedding all wallet-related controls into BitcoinGUI.
The purpose of this class is to allow future refinements of the wallet controls with minimal need for further modifications to BitcoinGUI, thus greatly simplifying merges while reducing the risk of breaking top-level stuff.
Definition at line 28 of file walletframe.h.
Constructor & Destructor Documentation
WalletFrame()
WalletFrame::WalletFrame (BitcoinGUI * _gui = 0) explicit
Definition at line 16 of file walletframe.cpp.
References walletStack.
~WalletFrame()
WalletFrame::~WalletFrame ()
Definition at line 32 of file walletframe.cpp.
Member Function Documentation
addWallet()
bool WalletFrame::addWallet (const QString & name, WalletModel * walletModel)
Definition at line 41 of file walletframe.cpp.
References bOutOfSync, clientModel, WalletView::gotoOverviewPage(), gui, mapWalletViews, name, outOfSyncWarningClicked(), WalletView::setBitcoinGUI(), WalletView::setClientModel(), WalletView::setWalletModel(), WalletView::showOutOfSyncWarning(), and walletStack.
backupWallet
void WalletFrame::backupWallet () slot
Backup the wallet.
Definition at line 176 of file walletframe.cpp.
References WalletView::backupWallet(), and currentWalletView().
changePassphrase
void WalletFrame::changePassphrase () slot
Change encrypted wallet passphrase.
Definition at line 183 of file walletframe.cpp.
References WalletView::changePassphrase(), and currentWalletView().
currentWalletView()
WalletView * WalletFrame::currentWalletView ()
Definition at line 218 of file walletframe.cpp.
References walletStack.
Referenced by backupWallet(), changePassphrase(), encryptWallet(), gotoSignMessageTab(), gotoVerifyMessageTab(), handlePaymentRequest(), lockWallet(), unlockWallet(), usedReceivingAddresses(), and usedSendingAddresses().
encryptWallet
void WalletFrame::encryptWallet (bool status) slot
Encrypt the wallet.
Definition at line 169 of file walletframe.cpp.
References currentWalletView(), and WalletView::encryptWallet().
gotoHistoryPage
void WalletFrame::gotoHistoryPage () slot
Switch to history (transactions) page.
Definition at line 119 of file walletframe.cpp.
References mapWalletViews.
gotoMasternodePage
void WalletFrame::gotoMasternodePage () slot
Switch to masternode page.
Definition at line 126 of file walletframe.cpp.
References mapWalletViews.
gotoOverviewPage
void WalletFrame::gotoOverviewPage () slot
Switch to overview (home) page.
Definition at line 112 of file walletframe.cpp.
References mapWalletViews.
gotoPrivateSendCoinsPage
void WalletFrame::gotoPrivateSendCoinsPage (QString addr = "") slot
Switch to PrivateSend coins page.
Definition at line 147 of file walletframe.cpp.
References mapWalletViews.
gotoReceiveCoinsPage
void WalletFrame::gotoReceiveCoinsPage () slot
Switch to receive coins page.
Definition at line 133 of file walletframe.cpp.
References mapWalletViews.
gotoSendCoinsPage
void WalletFrame::gotoSendCoinsPage (QString addr = "") slot
Switch to send coins page.
Definition at line 140 of file walletframe.cpp.
References mapWalletViews.
gotoSignMessageTab
void WalletFrame::gotoSignMessageTab (QString addr = "") slot
Show Sign/Verify Message dialog and switch to sign message tab.
Definition at line 155 of file walletframe.cpp.
References currentWalletView(), and WalletView::gotoSignMessageTab().
gotoVerifyMessageTab
void WalletFrame::gotoVerifyMessageTab (QString addr = "") slot
Show Sign/Verify Message dialog and switch to verify message tab.
Definition at line 162 of file walletframe.cpp.
References currentWalletView(), and WalletView::gotoVerifyMessageTab().
handlePaymentRequest()
bool WalletFrame::handlePaymentRequest (const SendCoinsRecipient & recipient)
Definition at line 95 of file walletframe.cpp.
References currentWalletView(), and WalletView::handlePaymentRequest().
lockWallet
void WalletFrame::lockWallet () slot
Lock wallet.
Definition at line 197 of file walletframe.cpp.
References currentWalletView(), and WalletView::lockWallet().
outOfSyncWarningClicked
void WalletFrame::outOfSyncWarningClicked () slot
Pass on signal over requested out-of-sync-warning information.
Definition at line 223 of file walletframe.cpp.
References requestedSyncWarningInfo().
Referenced by addWallet().
removeAllWallets()
void WalletFrame::removeAllWallets ()
Definition at line 87 of file walletframe.cpp.
References mapWalletViews, and walletStack.
removeWallet()
bool WalletFrame::removeWallet (const QString & name)
Definition at line 77 of file walletframe.cpp.
References mapWalletViews, name, and walletStack.
requestedSyncWarningInfo
void WalletFrame::requestedSyncWarningInfo () signal
Notify that the user has requested more information about the out-of-sync warning.
Referenced by outOfSyncWarningClicked().
setClientModel()
void WalletFrame::setClientModel (ClientModel * clientModel)
Definition at line 36 of file walletframe.cpp.
References clientModel.
Referenced by BitcoinGUI::setClientModel().
setCurrentWallet()
bool WalletFrame::setCurrentWallet (const QString & name)
Definition at line 65 of file walletframe.cpp.
References mapWalletViews, name, WalletView::updateEncryptionStatus(), and walletStack.
showOutOfSyncWarning()
void WalletFrame::showOutOfSyncWarning (bool fShow)
Definition at line 104 of file walletframe.cpp.
References bOutOfSync, and mapWalletViews.
Referenced by BitcoinGUI::setAdditionalDataSyncProgress(), and BitcoinGUI::setNumBlocks().
unlockWallet
void WalletFrame::unlockWallet () slot
Ask for passphrase to unlock wallet temporarily.
Definition at line 190 of file walletframe.cpp.
References currentWalletView(), and WalletView::unlockWallet().
usedReceivingAddresses
void WalletFrame::usedReceivingAddresses () slot
Show used receiving addresses.
Definition at line 211 of file walletframe.cpp.
References currentWalletView(), and WalletView::usedReceivingAddresses().
usedSendingAddresses
void WalletFrame::usedSendingAddresses () slot
Show used sending addresses.
Definition at line 204 of file walletframe.cpp.
References currentWalletView(), and WalletView::usedSendingAddresses().
Member Data Documentation
bOutOfSync
bool WalletFrame::bOutOfSync private
Definition at line 57 of file walletframe.h.
Referenced by addWallet(), and showOutOfSyncWarning().
clientModel
ClientModel* WalletFrame::clientModel private
Definition at line 54 of file walletframe.h.
Referenced by addWallet(), and setClientModel().
gui
BitcoinGUI* WalletFrame::gui private
Definition at line 53 of file walletframe.h.
Referenced by addWallet().
mapWalletViews
QMap<QString, WalletView*> WalletFrame::mapWalletViews private
Definition at line 55 of file walletframe.h.
Referenced by addWallet(), gotoHistoryPage(), gotoMasternodePage(), gotoOverviewPage(), gotoPrivateSendCoinsPage(), gotoReceiveCoinsPage(), gotoSendCoinsPage(), removeAllWallets(), removeWallet(), setCurrentWallet(), and showOutOfSyncWarning().
walletStack
QStackedWidget* WalletFrame::walletStack private
Definition at line 52 of file walletframe.h.
Referenced by addWallet(), currentWalletView(), removeAllWallets(), removeWallet(), setCurrentWallet(), and WalletFrame().
The documentation for this class was generated from the following files:
src/qt/walletframe.h
src/qt/walletframe.cpp
Released under the MIT license