Dash Core: CPrivateSendQueue Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CPrivateSendQueue Class Reference
A currently in progress mixing merge and denomination information.
#include <privatesend.h>
Public Member Functions
CPrivateSendQueue ()
CPrivateSendQueue (int nDenom, COutPoint outpoint, int64_t nTime, bool fReady)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
uint256 GetSignatureHash () const
bool Sign ()
Sign this mixing transaction.
bool CheckSignature (const CBLSPublicKey &blsPubKey) const
Check if we have a valid Masternode address.
bool Relay (CConnman &connman)
bool IsTimeOutOfBounds () const
Check if a queue is too old or too far into the future.
std::string ToString () const
Public Attributes
int nDenom
COutPoint masternodeOutpoint
int64_t nTime
bool fReady
std::vector< unsigned char > vchSig
bool fTried
ADD_SERIALIZE_METHODS
Friends
bool operator== (const CPrivateSendQueue &a, const CPrivateSendQueue &b)
Detailed Description
A currently in progress mixing merge and denomination information.
Definition at line 215 of file privatesend.h.
Constructor & Destructor Documentation
CPrivateSendQueue() [1/2]
CPrivateSendQueue::CPrivateSendQueue () inline
Definition at line 226 of file privatesend.h.
CPrivateSendQueue() [2/2]
CPrivateSendQueue::CPrivateSendQueue (int nDenom, COutPoint outpoint, int64_t nTime, bool fReady) inline
Definition at line 236 of file privatesend.h.
Member Function Documentation
CheckSignature()
bool CPrivateSendQueue::CheckSignature (const CBLSPublicKey & blsPubKey) const
Check if we have a valid Masternode address.
Definition at line 60 of file privatesend.cpp.
References GetSignatureHash(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), LogPrint, BCLog::PRIVATESEND, CBLSWrapper< ImplType, _SerSize, C >::SetBuf(), vchSig, and CBLSSignature::VerifyInsecure().
GetSignatureHash()
uint256 CPrivateSendQueue::GetSignatureHash () const
Definition at line 40 of file privatesend.cpp.
References SerializeHash().
Referenced by CheckSignature(), and Sign().
IsTimeOutOfBounds()
bool CPrivateSendQueue::IsTimeOutOfBounds () const
Check if a queue is too old or too far into the future.
Definition at line 85 of file privatesend.cpp.
References GetAdjustedTime(), nTime, and PRIVATESEND_QUEUE_TIMEOUT.
Relay()
bool CPrivateSendQueue::Relay (CConnman & connman)
Definition at line 74 of file privatesend.cpp.
References NetMsgType::DSQUEUE, CConnman::ForEachNode(), CNode::fSendDSQueue, CNode::GetSendVersion(), MIN_PRIVATESEND_PEER_PROTO_VERSION, CNode::nVersion, and CConnman::PushMessage().
Referenced by CPrivateSendServer::CheckForCompleteQueue(), and CPrivateSendServer::CreateNewSession().
SerializationOp()
template<typename Stream , typename Operation > void CPrivateSendQueue::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 249 of file privatesend.h.
References fReady, masternodeOutpoint, nDenom, nTime, READWRITE, SER_GETHASH, and vchSig.
Sign()
bool CPrivateSendQueue::Sign ()
Sign this mixing transaction.
Returns
true if all conditions are met: 1) we have an active Masternode, 2) we have a valid Masternode private key, 3) we signed the message successfully, and 4) we verified the message successfully
Definition at line 45 of file privatesend.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsKeyOperator, fMasternodeMode, CBLSWrapper< ImplType, _SerSize, C >::GetBuf(), GetSignatureHash(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), and vchSig.
Referenced by CPrivateSendServer::CheckForCompleteQueue(), and CPrivateSendServer::CreateNewSession().
ToString()
std::string CPrivateSendQueue::ToString () const inline
Definition at line 277 of file privatesend.h.
References fReady, fTried, masternodeOutpoint, nDenom, nTime, strprintf, and COutPoint::ToStringShort().
Referenced by CPrivateSendServer::CheckForCompleteQueue(), CPrivateSendServer::CreateNewSession(), and CPrivateSendClientSession::JoinExistingQueue().
Friends And Related Function Documentation
operator==
bool operator== (const CPrivateSendQueue & a, const CPrivateSendQueue & b) friend
Definition at line 283 of file privatesend.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CPrivateSendQueue::ADD_SERIALIZE_METHODS
Definition at line 246 of file privatesend.h.
fReady
bool CPrivateSendQueue::fReady
Definition at line 221 of file privatesend.h.
Referenced by SerializationOp(), and ToString().
fTried
bool CPrivateSendQueue::fTried
Definition at line 224 of file privatesend.h.
Referenced by ToString().
masternodeOutpoint
COutPoint CPrivateSendQueue::masternodeOutpoint
Definition at line 219 of file privatesend.h.
Referenced by CPrivateSendClientSession::JoinExistingQueue(), SerializationOp(), and ToString().
nDenom
int CPrivateSendQueue::nDenom
Definition at line 218 of file privatesend.h.
Referenced by CPrivateSendClientSession::JoinExistingQueue(), SerializationOp(), and ToString().
nTime
int64_t CPrivateSendQueue::nTime
Definition at line 220 of file privatesend.h.
Referenced by IsTimeOutOfBounds(), SerializationOp(), and ToString().
vchSig
std::vector<unsigned char> CPrivateSendQueue::vchSig
Definition at line 222 of file privatesend.h.
Referenced by CheckSignature(), SerializationOp(), and Sign().
The documentation for this class was generated from the following files:
src/privatesend/privatesend.h
src/privatesend/privatesend.cpp
Released under the MIT license