Dash Core: TrafficGraphWidget Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
TrafficGraphWidget Class Reference
#include <trafficgraphwidget.h>
Public Slots
void updateRates ()
void setGraphRangeMins (int value)
void clear ()
Public Member Functions
TrafficGraphWidget (QWidget *parent=0)
void setClientModel (ClientModel *model)
int getGraphRangeMins () const
Protected Member Functions
void paintEvent (QPaintEvent *)
Private Types
typedef boost::function< float(const TrafficSample &)> SampleChooser
Private Member Functions
void paintPath (QPainterPath &path, const TrafficGraphData::SampleQueue &queue, SampleChooser chooser)
Private Attributes
QTimer * timer
float fMax
int nMins
ClientModel * clientModel
TrafficGraphData trafficGraphData
Detailed Description
Definition at line 22 of file trafficgraphwidget.h.
Member Typedef Documentation
SampleChooser
typedef boost::function<float(const TrafficSample&)> TrafficGraphWidget::SampleChooser private
Definition at line 40 of file trafficgraphwidget.h.
Constructor & Destructor Documentation
TrafficGraphWidget()
TrafficGraphWidget::TrafficGraphWidget (QWidget * parent = 0) explicit
Definition at line 21 of file trafficgraphwidget.cpp.
References TrafficGraphData::SMALLEST_SAMPLE_PERIOD, timer, and updateRates().
Member Function Documentation
clear
void TrafficGraphWidget::clear () slot
Definition at line 158 of file trafficgraphwidget.cpp.
References TrafficGraphData::clear(), clientModel, DEFAULT_SAMPLE_HEIGHT, fMax, ClientModel::getTotalBytesRecv(), ClientModel::getTotalBytesSent(), TrafficGraphData::setLastBytes(), and trafficGraphData.
getGraphRangeMins()
int TrafficGraphWidget::getGraphRangeMins () const
Definition at line 43 of file trafficgraphwidget.cpp.
References nMins.
paintEvent()
void TrafficGraphWidget::paintEvent (QPaintEvent *) protected
Definition at line 76 of file trafficgraphwidget.cpp.
References base, count, fMax, TrafficGraphData::getCurrentRangeQueueWithAverageBandwidth(), paintPath(), trafficGraphData, XMARGIN, and YMARGIN.
paintPath()
void TrafficGraphWidget::paintPath (QPainterPath & path, const TrafficGraphData::SampleQueue & queue, SampleChooser chooser) private
Definition at line 49 of file trafficgraphwidget.cpp.
References TrafficGraphData::DESIRED_DATA_SAMPLES, fMax, XMARGIN, and YMARGIN.
Referenced by paintEvent().
setClientModel()
void TrafficGraphWidget::setClientModel (ClientModel * model)
Definition at line 35 of file trafficgraphwidget.cpp.
References clientModel, ClientModel::getTotalBytesRecv(), ClientModel::getTotalBytesSent(), TrafficGraphData::setLastBytes(), and trafficGraphData.
setGraphRangeMins
void TrafficGraphWidget::setGraphRangeMins (int value) slot
Definition at line 152 of file trafficgraphwidget.cpp.
References TrafficGraphData::switchRange(), and trafficGraphData.
updateRates
void TrafficGraphWidget::updateRates () slot
Definition at line 135 of file trafficgraphwidget.cpp.
References clientModel, DEFAULT_SAMPLE_HEIGHT, fMax, TrafficGraphData::getCurrentRangeQueueWithAverageBandwidth(), ClientModel::getTotalBytesRecv(), ClientModel::getTotalBytesSent(), TrafficSample::in, TrafficSample::out, trafficGraphData, and TrafficGraphData::update().
Referenced by TrafficGraphWidget().
Member Data Documentation
clientModel
ClientModel* TrafficGraphWidget::clientModel private
Definition at line 46 of file trafficgraphwidget.h.
Referenced by clear(), setClientModel(), and updateRates().
fMax
float TrafficGraphWidget::fMax private
Definition at line 44 of file trafficgraphwidget.h.
Referenced by clear(), paintEvent(), paintPath(), and updateRates().
nMins
int TrafficGraphWidget::nMins private
Definition at line 45 of file trafficgraphwidget.h.
Referenced by getGraphRangeMins().
timer
QTimer* TrafficGraphWidget::timer private
Definition at line 43 of file trafficgraphwidget.h.
Referenced by TrafficGraphWidget().
trafficGraphData
TrafficGraphData TrafficGraphWidget::trafficGraphData private
Definition at line 47 of file trafficgraphwidget.h.
Referenced by clear(), paintEvent(), setClientModel(), setGraphRangeMins(), and updateRates().
The documentation for this class was generated from the following files:
src/qt/trafficgraphwidget.h
src/qt/trafficgraphwidget.cpp
Released under the MIT license