Dash Core: CDarkSendRelay Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CDarkSendRelay Class Reference
#include <darksend-relay.h>
Public Member Functions
CDarkSendRelay ()
CDarkSendRelay (CTxIn &vinMasternodeIn, vector< unsigned char > &vchSigIn, int nBlockHeightIn, int nRelayTypeIn, CTxIn &in2, CTxOut &out2)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
std::string ToString ()
bool Sign (std::string strSharedKey)
bool VerifyMessage (std::string strSharedKey)
void Relay ()
void RelayThroughNode (int nRank)
Public Attributes
CTxIn vinMasternode
vector< unsigned char > vchSig
vector< unsigned char > vchSig2
int nBlockHeight
int nRelayType
CTxIn in
CTxOut out
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 14 of file darksend-relay.h.
Constructor & Destructor Documentation
CDarkSendRelay() [1/2]
CDarkSendRelay::CDarkSendRelay ()
Definition at line 5 of file darksend-relay.cpp.
References in, nBlockHeight, nRelayType, out, and vinMasternode.
CDarkSendRelay() [2/2]
CDarkSendRelay::CDarkSendRelay (CTxIn & vinMasternodeIn, vector< unsigned char > & vchSigIn, int nBlockHeightIn, int nRelayTypeIn, CTxIn & in2, CTxOut & out2)
Definition at line 14 of file darksend-relay.cpp.
References in, nBlockHeight, nRelayType, out, vchSig, and vinMasternode.
Member Function Documentation
Relay()
void CDarkSendRelay::Relay ()
Definition at line 84 of file darksend-relay.cpp.
References CMasternodeMan::CountEnabled(), MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, and RelayThroughNode().
RelayThroughNode()
void CDarkSendRelay::RelayThroughNode (int nRank)
Definition at line 100 of file darksend-relay.cpp.
References masternode_info_t::addr, g_connman, CMasternodeMan::GetMasternodeByRank(), MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, and nBlockHeight.
Referenced by Relay().
SerializationOp()
template<typename Stream , typename Operation > void CDarkSendRelay::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 31 of file darksend-relay.h.
References in, nBlockHeight, nRelayType, out, READWRITE, vchSig, vchSig2, and vinMasternode.
Sign()
bool CDarkSendRelay::Sign (std::string strSharedKey)
Definition at line 37 of file darksend-relay.cpp.
References CMessageSigner::GetKeysFromSecret(), in, LogPrintf, out, CMessageSigner::SignMessage(), CTxIn::ToString(), CTxOut::ToString(), vchSig2, and CMessageSigner::VerifyMessage().
ToString()
std::string CDarkSendRelay::ToString ()
Definition at line 24 of file darksend-relay.cpp.
References in, nBlockHeight, nRelayType, out, CTxIn::ToString(), CTxOut::ToString(), and vinMasternode.
VerifyMessage()
bool CDarkSendRelay::VerifyMessage (std::string strSharedKey)
Definition at line 63 of file darksend-relay.cpp.
References CMessageSigner::GetKeysFromSecret(), in, LogPrintf, out, CTxIn::ToString(), CTxOut::ToString(), vchSig2, and CMessageSigner::VerifyMessage().
Member Data Documentation
ADD_SERIALIZE_METHODS
CDarkSendRelay::ADD_SERIALIZE_METHODS
Definition at line 28 of file darksend-relay.h.
in
CTxIn CDarkSendRelay::in
Definition at line 22 of file darksend-relay.h.
Referenced by CDarkSendRelay(), SerializationOp(), Sign(), ToString(), and VerifyMessage().
nBlockHeight
int CDarkSendRelay::nBlockHeight
Definition at line 20 of file darksend-relay.h.
Referenced by CDarkSendRelay(), RelayThroughNode(), SerializationOp(), and ToString().
nRelayType
int CDarkSendRelay::nRelayType
Definition at line 21 of file darksend-relay.h.
Referenced by CDarkSendRelay(), SerializationOp(), and ToString().
out
CTxOut CDarkSendRelay::out
Definition at line 23 of file darksend-relay.h.
Referenced by CDarkSendRelay(), SerializationOp(), Sign(), ToString(), and VerifyMessage().
vchSig
vector<unsigned char> CDarkSendRelay::vchSig
Definition at line 18 of file darksend-relay.h.
Referenced by CDarkSendRelay(), and SerializationOp().
vchSig2
vector<unsigned char> CDarkSendRelay::vchSig2
Definition at line 19 of file darksend-relay.h.
Referenced by SerializationOp(), Sign(), and VerifyMessage().
vinMasternode
CTxIn CDarkSendRelay::vinMasternode
Definition at line 17 of file darksend-relay.h.
Referenced by CDarkSendRelay(), SerializationOp(), and ToString().
The documentation for this class was generated from the following files:
src/darksend-relay.h
src/darksend-relay.cpp
Released under the MIT license