Dash Core: HelpMessageDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
HelpMessageDialog Class Reference
"Help message" dialog box
#include <utilitydialog.h>
Public Types
enum HelpMode { about, cmdline, pshelp }
Public Member Functions
HelpMessageDialog (QWidget *parent, HelpMode helpMode)
"Help message" or "About" dialog box
~HelpMessageDialog ()
void printToConsole ()
void showOrPrint ()
Private Slots
void on_okButton_accepted ()
Private Attributes
Ui::HelpMessageDialog * ui
QString text
Detailed Description
"Help message" dialog box
Definition at line 18 of file utilitydialog.h.
Member Enumeration Documentation
HelpMode
enum HelpMessageDialog::HelpMode
Enumerator
about
cmdline
pshelp
Definition at line 23 of file utilitydialog.h.
Constructor & Destructor Documentation
HelpMessageDialog()
HelpMessageDialog::HelpMessageDialog (QWidget * parent, HelpMode helpMode) explicit
"Help message" or "About" dialog box
HTML-format the license message from the core
Definition at line 36 of file utilitydialog.cpp.
References about, cmdline, DEFAULT_CHOOSE_DATADIR, DEFAULT_SELFSIGNED_ROOTCERTS, DEFAULT_SPLASHSCREEN, BitcoinGUI::DEFAULT_UIPLATFORM, GUIUtil::fontFamilyToString(), FormatFullVersion(), gArgs, ArgsManager::GetBoolArg(), GUIUtil::getFontFamilyDefault(), GUIUtil::getFontScaleDefault(), GUIUtil::getFontWeightBoldDefault(), GUIUtil::getFontWeightNormalDefault(), GUIUtil::getThemedStyleQString(), HelpMessage(), HelpMessageGroup(), HelpMessageOpt(), HMM_BITCOIN_QT, LicenseInfo(), pshelp, strprintf, text, GUIUtil::TS_COMMAND, ui, GUIUtil::updateFonts(), and GUIUtil::weightToArg().
~HelpMessageDialog()
HelpMessageDialog::~HelpMessageDialog ()
Definition at line 179 of file utilitydialog.cpp.
References ui.
Member Function Documentation
on_okButton_accepted
void HelpMessageDialog::on_okButton_accepted () private slot
Definition at line 201 of file utilitydialog.cpp.
printToConsole()
void HelpMessageDialog::printToConsole ()
Definition at line 184 of file utilitydialog.cpp.
References text.
Referenced by showOrPrint().
showOrPrint()
void HelpMessageDialog::showOrPrint ()
Definition at line 190 of file utilitydialog.cpp.
References printToConsole().
Member Data Documentation
text
QString HelpMessageDialog::text private
Definition at line 37 of file utilitydialog.h.
Referenced by HelpMessageDialog(), and printToConsole().
ui
Ui::HelpMessageDialog* HelpMessageDialog::ui private
Definition at line 36 of file utilitydialog.h.
Referenced by HelpMessageDialog(), and ~HelpMessageDialog().
The documentation for this class was generated from the following files:
src/qt/utilitydialog.h
src/qt/utilitydialog.cpp
Released under the MIT license