Dash Core: TransactionFilterProxy Class Reference
TransactionFilterProxy Class Reference
#include <transactionfilterproxy.h>
Public Types
enum WatchOnlyFilter { WatchOnlyFilter_All, WatchOnlyFilter_Yes, WatchOnlyFilter_No }
Public Member Functions
TransactionFilterProxy (QObject *parent=0)
void setDateRange (const QDateTime &from, const QDateTime &to)
void setAddressPrefix (const QString &addrPrefix)
void setTypeFilter (quint32 modes)
void setMinAmount (const CAmount &minimum)
void setWatchOnlyFilter (WatchOnlyFilter filter)
void setLimit (int limit)
void setShowInactive (bool showInactive)
int rowCount (const QModelIndex &parent=QModelIndex()) const
Static Public Member Functions
static quint32 TYPE (int type)
Static Public Attributes
static const QDateTime MIN_DATE = QDateTime::fromTime_t(0)
static const QDateTime MAX_DATE = QDateTime::fromTime_t(0xFFFFFFFF)
static const quint32 ALL_TYPES = 0xFFFFFFFF
static const quint32 COMMON_TYPES = 4223
Protected Member Functions
bool filterAcceptsRow (int source_row, const QModelIndex &source_parent) const
Private Attributes
QDateTime dateFrom
QDateTime dateTo
QString addrPrefix
quint32 typeFilter
WatchOnlyFilter watchOnlyFilter
CAmount minAmount
int limitRows
bool showInactive
Detailed Description
Filter the transaction list according to pre-specified rules.
Definition at line 14 of file transactionfilterproxy.h.
Member Enumeration Documentation
WatchOnlyFilter
enum TransactionFilterProxy::WatchOnlyFilter
Enumerator
WatchOnlyFilter_All
WatchOnlyFilter_Yes
WatchOnlyFilter_No
Definition at line 32 of file transactionfilterproxy.h.
Constructor & Destructor Documentation
TransactionFilterProxy()
TransactionFilterProxy::TransactionFilterProxy (QObject * parent = 0) explicit
Definition at line 19 of file transactionfilterproxy.cpp.
Member Function Documentation
filterAcceptsRow()
bool TransactionFilterProxy::filterAcceptsRow (int source_row, const QModelIndex & source_parent) const protected
Definition at line 32 of file transactionfilterproxy.cpp.
rowCount()
int TransactionFilterProxy::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 104 of file transactionfilterproxy.cpp.
setAddressPrefix()
void TransactionFilterProxy::setAddressPrefix (const QString & addrPrefix)
Definition at line 69 of file transactionfilterproxy.cpp.
Referenced by TransactionView::changedPrefix().
setDateRange()
void TransactionFilterProxy::setDateRange (const QDateTime & from, const QDateTime & to)
Definition at line 62 of file transactionfilterproxy.cpp.
Referenced by TransactionView::chooseDate(), and TransactionView::dateRangeChanged().
setLimit()
void TransactionFilterProxy::setLimit (int limit)
Set maximum number of rows returned, -1 if unlimited.
Definition at line 93 of file transactionfilterproxy.cpp.
setMinAmount()
void TransactionFilterProxy::setMinAmount (const CAmount & minimum)
Definition at line 81 of file transactionfilterproxy.cpp.
Referenced by TransactionView::changedAmount().
setShowInactive()
void TransactionFilterProxy::setShowInactive (bool showInactive)
Set whether to show conflicted transactions.
Definition at line 98 of file transactionfilterproxy.cpp.
setTypeFilter()
void TransactionFilterProxy::setTypeFilter (quint32 modes)
Note
Type filter takes a bit field created with TYPE() or ALL_TYPES
Definition at line 75 of file transactionfilterproxy.cpp.
Referenced by TransactionView::chooseType().
setWatchOnlyFilter()
void TransactionFilterProxy::setWatchOnlyFilter (WatchOnlyFilter filter)
Definition at line 87 of file transactionfilterproxy.cpp.
Referenced by TransactionView::chooseWatchonly().
TYPE()
static quint32 TransactionFilterProxy::TYPE (int type) inline static
Definition at line 30 of file transactionfilterproxy.h.
Referenced by filterAcceptsRow(), and TransactionView::TransactionView().
Member Data Documentation
addrPrefix
QString TransactionFilterProxy::addrPrefix private
Definition at line 62 of file transactionfilterproxy.h.
Referenced by filterAcceptsRow(), and setAddressPrefix().
ALL_TYPES
const quint32 TransactionFilterProxy::ALL_TYPES = 0xFFFFFFFF static
Type filter bit field (all types)
Definition at line 26 of file transactionfilterproxy.h.
Referenced by TransactionView::TransactionView().
COMMON_TYPES
const quint32 TransactionFilterProxy::COMMON_TYPES = 4223 static
Type filter bit field (all types but Darksend-SPAM)
Definition at line 28 of file transactionfilterproxy.h.
Referenced by TransactionView::TransactionView().
dateFrom
QDateTime TransactionFilterProxy::dateFrom private
Definition at line 60 of file transactionfilterproxy.h.
Referenced by setDateRange().
dateTo
QDateTime TransactionFilterProxy::dateTo private
Definition at line 61 of file transactionfilterproxy.h.
Referenced by filterAcceptsRow(), and setDateRange().
limitRows
int TransactionFilterProxy::limitRows private
Definition at line 66 of file transactionfilterproxy.h.
Referenced by rowCount(), and setLimit().
MAX_DATE
const QDateTime TransactionFilterProxy::MAX_DATE = QDateTime::fromTime_t(0xFFFFFFFF) static
Last date that can be represented (far in the future)
Definition at line 24 of file transactionfilterproxy.h.
Referenced by TransactionView::chooseDate().
MIN_DATE
const QDateTime TransactionFilterProxy::MIN_DATE = QDateTime::fromTime_t(0) static
Earliest date that can be represented (far in the past)
Definition at line 22 of file transactionfilterproxy.h.
Referenced by TransactionView::chooseDate().
minAmount
CAmount TransactionFilterProxy::minAmount private
Definition at line 65 of file transactionfilterproxy.h.
Referenced by filterAcceptsRow(), and setMinAmount().
showInactive
bool TransactionFilterProxy::showInactive private
Definition at line 67 of file transactionfilterproxy.h.
Referenced by filterAcceptsRow(), and setShowInactive().
typeFilter
quint32 TransactionFilterProxy::typeFilter private
Definition at line 63 of file transactionfilterproxy.h.
Referenced by filterAcceptsRow(), and setTypeFilter().
watchOnlyFilter
WatchOnlyFilter TransactionFilterProxy::watchOnlyFilter private
Definition at line 64 of file transactionfilterproxy.h.
Referenced by filterAcceptsRow(), and setWatchOnlyFilter().
The documentation for this class was generated from the following files:
src/qt/transactionfilterproxy.h
src/qt/transactionfilterproxy.cpp