Dash Core: llmq::CDKGDebugSessionStatus Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CDKGDebugSessionStatus Class Reference
#include <quorums_debug.h>
Public Member Functions
CDKGDebugSessionStatus ()
UniValue ToJson (int detailLevel) const
Public Attributes
Consensus::LLMQType llmqType {Consensus::LLMQ_NONE}
uint256 quorumHash
uint32_t quorumHeight {0}
uint8_t phase {0}
union {
struct {
bool sentContributions: 1
bool sentComplaint: 1
bool sentJustification: 1
bool sentPrematureCommitment: 1
bool aborted: 1
}
uint8_t statusBitset
};
std::vector< CDKGDebugMemberStatus > members
Detailed Description
Definition at line 48 of file quorums_debug.h.
Constructor & Destructor Documentation
CDKGDebugSessionStatus()
llmq::CDKGDebugSessionStatus::CDKGDebugSessionStatus () inline
Definition at line 73 of file quorums_debug.h.
Member Function Documentation
ToJson()
UniValue llmq::CDKGDebugSessionStatus::ToJson (int detailLevel) const
Definition at line 17 of file quorums_debug.cpp.
References aborted, count, cs_main, llmq::CLLMQUtils::GetAllQuorumMembers(), base_blob< BITS >::IsNull(), llmqType, LOCK, mapBlockIndex, members, name, Pair(), Params(), phase, UniValue::push_back(), quorumHash, quorumHeight, sentComplaint, sentContributions, sentJustification, sentPrematureCommitment, base_blob< BITS >::ToString(), UniValue::VARR, and UniValue::VOBJ.
Member Data Documentation
@15
union { ... }
aborted
bool llmq::CDKGDebugSessionStatus::aborted
Definition at line 65 of file quorums_debug.h.
Referenced by ToJson().
llmqType
Consensus::LLMQType llmq::CDKGDebugSessionStatus::llmqType {Consensus::LLMQ_NONE}
Definition at line 51 of file quorums_debug.h.
Referenced by ToJson().
members
std::vector<CDKGDebugMemberStatus> llmq::CDKGDebugSessionStatus::members
Definition at line 70 of file quorums_debug.h.
Referenced by ToJson().
phase
uint8_t llmq::CDKGDebugSessionStatus::phase {0}
Definition at line 54 of file quorums_debug.h.
Referenced by ToJson().
quorumHash
uint256 llmq::CDKGDebugSessionStatus::quorumHash
Definition at line 52 of file quorums_debug.h.
Referenced by ToJson().
quorumHeight
uint32_t llmq::CDKGDebugSessionStatus::quorumHeight {0}
Definition at line 53 of file quorums_debug.h.
Referenced by ToJson().
sentComplaint
bool llmq::CDKGDebugSessionStatus::sentComplaint
Definition at line 61 of file quorums_debug.h.
Referenced by ToJson().
sentContributions
bool llmq::CDKGDebugSessionStatus::sentContributions
Definition at line 60 of file quorums_debug.h.
Referenced by ToJson().
sentJustification
bool llmq::CDKGDebugSessionStatus::sentJustification
Definition at line 62 of file quorums_debug.h.
Referenced by ToJson().
sentPrematureCommitment
bool llmq::CDKGDebugSessionStatus::sentPrematureCommitment
Definition at line 63 of file quorums_debug.h.
Referenced by ToJson().
statusBitset
uint8_t llmq::CDKGDebugSessionStatus::statusBitset
Definition at line 67 of file quorums_debug.h.
The documentation for this class was generated from the following files:
src/llmq/quorums_debug.h
src/llmq/quorums_debug.cpp
Released under the MIT license