Dash Core: CKeePassIntegrator::CKeePassResponse Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CKeePassIntegrator::CKeePassResponse Class Reference
Public Member Functions
CKeePassResponse (const SecureString &sKey, const std::string &strResponse)
bool getSuccess ()
SecureString getSecureStr (const std::string &strName)
std::string getStr (const std::string &strName)
std::vector< CKeePassEntry > getEntries ()
SecureString decrypt (const std::string &strValue)
Public Attributes
UniValue responseObj
Private Member Functions
void parseResponse (const std::string &strResponse)
Private Attributes
bool bSuccess
std::string strType
std::string strIV
SecureString sKey
Detailed Description
Definition at line 88 of file keepass.h.
Constructor & Destructor Documentation
CKeePassResponse()
CKeePassIntegrator::CKeePassResponse::CKeePassResponse (const SecureString & sKey, const std::string & strResponse) inline
Definition at line 99 of file keepass.h.
References parseResponse(), and sKey.
Member Function Documentation
decrypt()
SecureString CKeePassIntegrator::CKeePassResponse::decrypt (const std::string & strValue)
Definition at line 194 of file keepass.cpp.
References DecodeBase64(), DecryptAES256(), and CKeePassIntegrator::sKey.
getEntries()
std::vector< CKeePassIntegrator::CKeePassEntry > CKeePassIntegrator::CKeePassResponse::getEntries ()
Definition at line 205 of file keepass.cpp.
References UniValue::get_array(), and UniValue::size().
Referenced by CKeePassIntegrator::rpcGetLogins().
getSecureStr()
SecureString CKeePassIntegrator::CKeePassResponse::getSecureStr (const std::string & strName)
Definition at line 177 of file keepass.cpp.
getStr()
std::string CKeePassIntegrator::CKeePassResponse::getStr (const std::string & strName)
Definition at line 172 of file keepass.cpp.
Referenced by CKeePassIntegrator::rpcAssociate().
getSuccess()
bool CKeePassIntegrator::CKeePassResponse::getSuccess () inline
Definition at line 104 of file keepass.h.
References bSuccess.
Referenced by CKeePassIntegrator::rpcAssociate(), CKeePassIntegrator::rpcGetLogins(), and CKeePassIntegrator::rpcSetLogin().
parseResponse()
void CKeePassIntegrator::CKeePassResponse::parseResponse (const std::string & strResponse) private
Definition at line 156 of file keepass.cpp.
References DecodeBase64(), UniValue::get_bool(), and UniValue::read().
Referenced by CKeePassResponse().
Member Data Documentation
bSuccess
bool CKeePassIntegrator::CKeePassResponse::bSuccess private
Definition at line 90 of file keepass.h.
Referenced by getSuccess().
responseObj
UniValue CKeePassIntegrator::CKeePassResponse::responseObj
Definition at line 98 of file keepass.h.
sKey
SecureString CKeePassIntegrator::CKeePassResponse::sKey private
Definition at line 93 of file keepass.h.
Referenced by CKeePassResponse().
strIV
std::string CKeePassIntegrator::CKeePassResponse::strIV private
Definition at line 92 of file keepass.h.
strType
std::string CKeePassIntegrator::CKeePassResponse::strType private
Definition at line 91 of file keepass.h.
The documentation for this class was generated from the following files:
src/keepass.h
src/keepass.cpp
Released under the MIT license