Dash Core: CMainSignals Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CMainSignals Class Reference
#include <validationinterface.h>
Public Member Functions
void RegisterBackgroundSignalScheduler (CScheduler &scheduler)
Register a CScheduler to give callbacks which should run in the background (may only be called once)
void UnregisterBackgroundSignalScheduler ()
Unregister a CScheduler to give callbacks which should run in the background - these callbacks will now be dropped!
void FlushBackgroundCallbacks ()
Call any remaining callbacks on the calling thread.
size_t CallbacksPending ()
void RegisterWithMempoolSignals (CTxMemPool &pool)
Register with mempool to call TransactionRemovedFromMempool callbacks.
void UnregisterWithMempoolSignals (CTxMemPool &pool)
Unregister with mempool.
void AcceptedBlockHeader (const CBlockIndex *pindexNew)
void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload)
void UpdatedBlockTip (const CBlockIndex *, const CBlockIndex *, bool fInitialDownload)
void SynchronousUpdatedBlockTip (const CBlockIndex *, const CBlockIndex *, bool fInitialDownload)
void TransactionAddedToMempool (const CTransactionRef &, int64_t)
void BlockConnected (const std::shared_ptr< const CBlock > &, const CBlockIndex *pindex, const std::shared_ptr< const std::vector< CTransactionRef >> &)
void BlockDisconnected (const std::shared_ptr< const CBlock > &, const CBlockIndex *pindexDisconnected)
void NotifyTransactionLock (const CTransaction &tx, const llmq::CInstantSendLock &islock)
void NotifyChainLock (const CBlockIndex *pindex, const llmq::CChainLockSig &clsig)
void NotifyGovernanceVote (const CGovernanceVote &vote)
void NotifyGovernanceObject (const CGovernanceObject &object)
void NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx)
void NotifyMasternodeListChanged (bool undo, const CDeterministicMNList &oldMNList, const CDeterministicMNListDiff &diff)
void SetBestChain (const CBlockLocator &)
void Broadcast (int64_t nBestBlockTime, CConnman *connman)
void BlockChecked (const CBlock &, const CValidationState &)
void NewPoWValidBlock (const CBlockIndex *, const std::shared_ptr< const CBlock > &)
Private Member Functions
friend void ::RegisterValidationInterface (CValidationInterface *)
friend void ::UnregisterValidationInterface (CValidationInterface *)
friend void ::UnregisterAllValidationInterfaces ()
friend void ::CallFunctionInValidationInterfaceQueue (std::function< void()> func)
void MempoolEntryRemoved (CTransactionRef tx, MemPoolRemovalReason reason)
Private Attributes
std::unique_ptr< MainSignalsInstance > m_internals
Detailed Description
Definition at line 139 of file validationinterface.h.
Member Function Documentation
AcceptedBlockHeader()
void CMainSignals::AcceptedBlockHeader (const CBlockIndex * pindexNew)
Definition at line 218 of file validationinterface.cpp.
References m_internals.
Referenced by CChainState::AcceptBlockHeader().
BlockChecked()
void CMainSignals::BlockChecked (const CBlock & block, const CValidationState & state)
Definition at line 210 of file validationinterface.cpp.
References m_internals.
Referenced by CChainState::ConnectTip(), and ProcessNewBlock().
BlockConnected()
void CMainSignals::BlockConnected (const std::shared_ptr< const CBlock > & pblock, const CBlockIndex * pindex, const std::shared_ptr< const std::vector< CTransactionRef >> & pvtxConflicted)
Definition at line 188 of file validationinterface.cpp.
References m_internals.
Referenced by CChainState::ActivateBestChain().
BlockDisconnected()
void CMainSignals::BlockDisconnected (const std::shared_ptr< const CBlock > & pblock, const CBlockIndex * pindexDisconnected)
Definition at line 194 of file validationinterface.cpp.
References m_internals.
Referenced by CChainState::DisconnectTip().
Broadcast()
void CMainSignals::Broadcast (int64_t nBestBlockTime, CConnman * connman)
Definition at line 206 of file validationinterface.cpp.
References m_internals.
Referenced by PeerLogicValidation::SendMessages().
CallbacksPending()
size_t CMainSignals::CallbacksPending ()
Definition at line 66 of file validationinterface.cpp.
References m_internals.
FlushBackgroundCallbacks()
void CMainSignals::FlushBackgroundCallbacks ()
Call any remaining callbacks on the calling thread.
Definition at line 60 of file validationinterface.cpp.
References m_internals.
Referenced by PrepareShutdown().
MempoolEntryRemoved()
void CMainSignals::MempoolEntryRemoved (CTransactionRef tx, MemPoolRemovalReason reason) private
Definition at line 164 of file validationinterface.cpp.
References BLOCK, CONFLICT, and m_internals.
Referenced by RegisterWithMempoolSignals(), and UnregisterWithMempoolSignals().
NewPoWValidBlock()
void CMainSignals::NewPoWValidBlock (const CBlockIndex * pindex, const std::shared_ptr< const CBlock > & block)
Definition at line 214 of file validationinterface.cpp.
References m_internals.
Referenced by CChainState::AcceptBlock().
NotifyChainLock()
void CMainSignals::NotifyChainLock (const CBlockIndex * pindex, const llmq::CChainLockSig & clsig)
Definition at line 230 of file validationinterface.cpp.
References m_internals.
Referenced by llmq::CChainLocksHandler::EnforceBestChainLock().
NotifyGovernanceObject()
void CMainSignals::NotifyGovernanceObject (const CGovernanceObject & object)
Definition at line 238 of file validationinterface.cpp.
References m_internals.
Referenced by CGovernanceManager::AddGovernanceObject().
NotifyGovernanceVote()
void CMainSignals::NotifyGovernanceVote (const CGovernanceVote & vote)
Definition at line 234 of file validationinterface.cpp.
References m_internals.
Referenced by CGovernanceManager::ProcessMessage().
NotifyHeaderTip()
void CMainSignals::NotifyHeaderTip (const CBlockIndex * pindexNew, bool fInitialDownload)
Definition at line 222 of file validationinterface.cpp.
References m_internals.
Referenced by NotifyHeaderTip().
NotifyInstantSendDoubleSpendAttempt()
void CMainSignals::NotifyInstantSendDoubleSpendAttempt (const CTransaction & currentTx, const CTransaction & previousTx)
Definition at line 242 of file validationinterface.cpp.
References m_internals.
Referenced by AcceptToMemoryPoolWorker().
NotifyMasternodeListChanged()
void CMainSignals::NotifyMasternodeListChanged (bool undo, const CDeterministicMNList & oldMNList, const CDeterministicMNListDiff & diff)
Definition at line 246 of file validationinterface.cpp.
References m_internals.
Referenced by CDeterministicMNManager::ProcessBlock(), and CDeterministicMNManager::UndoBlock().
NotifyTransactionLock()
void CMainSignals::NotifyTransactionLock (const CTransaction & tx, const llmq::CInstantSendLock & islock)
Definition at line 226 of file validationinterface.cpp.
References m_internals.
Referenced by llmq::CInstantSendManager::UpdateWalletTransaction().
RegisterBackgroundSignalScheduler()
void CMainSignals::RegisterBackgroundSignalScheduler (CScheduler & scheduler)
Register a CScheduler to give callbacks which should run in the background (may only be called once)
Definition at line 51 of file validationinterface.cpp.
References m_internals, and scheduler.
Referenced by AppInitMain().
RegisterWithMempoolSignals()
void CMainSignals::RegisterWithMempoolSignals (CTxMemPool & pool)
Register with mempool to call TransactionRemovedFromMempool callbacks.
Definition at line 71 of file validationinterface.cpp.
References MempoolEntryRemoved(), and CTxMemPool::NotifyEntryRemoved.
Referenced by AppInitMain().
SetBestChain()
void CMainSignals::SetBestChain (const CBlockLocator & locator)
Definition at line 200 of file validationinterface.cpp.
References m_internals.
Referenced by FlushStateToDisk().
SynchronousUpdatedBlockTip()
void CMainSignals::SynchronousUpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload)
Definition at line 178 of file validationinterface.cpp.
References m_internals.
Referenced by CChainState::ActivateBestChain(), and CChainState::InvalidateBlock().
TransactionAddedToMempool()
void CMainSignals::TransactionAddedToMempool (const CTransactionRef & ptx, int64_t nAcceptTime)
Definition at line 182 of file validationinterface.cpp.
References m_internals.
Referenced by AcceptToMemoryPoolWorker().
UnregisterBackgroundSignalScheduler()
void CMainSignals::UnregisterBackgroundSignalScheduler ()
Unregister a CScheduler to give callbacks which should run in the background - these callbacks will now be dropped!
Definition at line 56 of file validationinterface.cpp.
References m_internals.
Referenced by PrepareShutdown().
UnregisterWithMempoolSignals()
void CMainSignals::UnregisterWithMempoolSignals (CTxMemPool & pool)
Unregister with mempool.
Definition at line 75 of file validationinterface.cpp.
References MempoolEntryRemoved(), and CTxMemPool::NotifyEntryRemoved.
Referenced by PrepareShutdown().
UpdatedBlockTip()
void CMainSignals::UpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload)
Definition at line 172 of file validationinterface.cpp.
References m_internals.
Referenced by CChainState::ActivateBestChain(), and CChainState::InvalidateBlock().
void ::CallFunctionInValidationInterfaceQueue()
CMainSignals::void ::CallFunctionInValidationInterfaceQueue (std::function< void()> func) private
void ::RegisterValidationInterface()
CMainSignals::void ::RegisterValidationInterface (CValidationInterface *) private
void ::UnregisterAllValidationInterfaces()
CMainSignals::void ::UnregisterAllValidationInterfaces () private
void ::UnregisterValidationInterface()
CMainSignals::void ::UnregisterValidationInterface (CValidationInterface *) private
Member Data Documentation
m_internals
std::unique_ptr<MainSignalsInstance> CMainSignals::m_internals private
Definition at line 141 of file validationinterface.h.
Referenced by AcceptedBlockHeader(), BlockChecked(), BlockConnected(), BlockDisconnected(), Broadcast(), CallbacksPending(), CallFunctionInValidationInterfaceQueue(), FlushBackgroundCallbacks(), MempoolEntryRemoved(), NewPoWValidBlock(), NotifyChainLock(), NotifyGovernanceObject(), NotifyGovernanceVote(), NotifyHeaderTip(), NotifyInstantSendDoubleSpendAttempt(), NotifyMasternodeListChanged(), NotifyTransactionLock(), RegisterBackgroundSignalScheduler(), RegisterValidationInterface(), SetBestChain(), SynchronousUpdatedBlockTip(), TransactionAddedToMempool(), UnregisterAllValidationInterfaces(), UnregisterBackgroundSignalScheduler(), UnregisterValidationInterface(), and UpdatedBlockTip().
The documentation for this class was generated from the following files:
src/validationinterface.h
src/validationinterface.cpp
Released under the MIT license