Dash Core: ShutdownWindow Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
ShutdownWindow Class Reference
"Shutdown" window
#include <utilitydialog.h>
Public Member Functions
ShutdownWindow (QWidget *parent=0, Qt::WindowFlags f=0)
"Shutdown" window
Static Public Member Functions
static QWidget * showShutdownWindow (BitcoinGUI *window)
Protected Member Functions
void closeEvent (QCloseEvent *event)
Detailed Description
"Shutdown" window
Definition at line 46 of file utilitydialog.h.
Constructor & Destructor Documentation
ShutdownWindow()
ShutdownWindow::ShutdownWindow (QWidget * parent = 0, Qt::WindowFlags f = 0)
"Shutdown" window
Definition at line 201 of file utilitydialog.cpp.
Referenced by showShutdownWindow().
Member Function Documentation
closeEvent()
void ShutdownWindow::closeEvent (QCloseEvent * event) protected
Definition at line 227 of file utilitydialog.cpp.
showShutdownWindow()
QWidget * ShutdownWindow::showShutdownWindow (BitcoinGUI * window) static
Definition at line 211 of file utilitydialog.cpp.
References ShutdownWindow().
Referenced by BitcoinApplication::requestShutdown().
The documentation for this class was generated from the following files:
src/qt/utilitydialog.h
src/qt/utilitydialog.cpp
Released under the MIT license