Dash Core: DarksendConfig Class Reference
DarksendConfig Class Reference
#include <darksendconfig.h>
Public Member Functions
DarksendConfig (QWidget *parent=0)
~DarksendConfig ()
void setModel (WalletModel *model)
Private Slots
void clickBasic ()
void clickHigh ()
void clickMax ()
Private Member Functions
void configure (bool enabled, int coins, int rounds)
Private Attributes
Ui::DarksendConfig * ui
WalletModel * model
Detailed Description
Multifunctional dialog to ask for passphrases. Used for encryption, unlocking, and changing the passphrase.
Definition at line 13 of file darksendconfig.h.
Constructor & Destructor Documentation
DarksendConfig()
DarksendConfig::DarksendConfig (QWidget * parent = 0)
Definition at line 15 of file darksendconfig.cpp.
~DarksendConfig()
DarksendConfig::~DarksendConfig ()
Definition at line 27 of file darksendconfig.cpp.
Member Function Documentation
clickBasic
void DarksendConfig::clickBasic () private slot
Definition at line 37 of file darksendconfig.cpp.
Referenced by DarksendConfig().
clickHigh
void DarksendConfig::clickHigh () private slot
Definition at line 52 of file darksendconfig.cpp.
Referenced by DarksendConfig().
clickMax
void DarksendConfig::clickMax () private slot
Definition at line 67 of file darksendconfig.cpp.
Referenced by DarksendConfig().
configure()
void DarksendConfig::configure (bool enabled, int coins, int rounds) private
Definition at line 82 of file darksendconfig.cpp.
Referenced by clickBasic(), clickHigh(), and clickMax().
setModel()
void DarksendConfig::setModel (WalletModel * model)
Definition at line 32 of file darksendconfig.cpp.
Referenced by OverviewPage::togglePrivateSend().
Member Data Documentation
model
WalletModel* DarksendConfig::model private
Definition at line 27 of file darksendconfig.h.
Referenced by clickBasic(), clickHigh(), clickMax(), and setModel().
ui
Ui::DarksendConfig* DarksendConfig::ui private
Definition at line 26 of file darksendconfig.h.
Referenced by DarksendConfig(), and ~DarksendConfig().
The documentation for this class was generated from the following files:
src/qt/darksendconfig.h
src/qt/darksendconfig.cpp