Dash Core: CBase58Data Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CBase58Data Class Reference
Base class for all base58-encoded data.
#include <base58.h>
Public Member Functions
bool SetString (const char *psz, unsigned int nVersionBytes=1)
bool SetString (const std::string &str)
std::string ToString () const
int CompareTo (const CBase58Data &b58) const
bool operator== (const CBase58Data &b58) const
bool operator<= (const CBase58Data &b58) const
bool operator>= (const CBase58Data &b58) const
bool operator< (const CBase58Data &b58) const
bool operator> (const CBase58Data &b58) const
Protected Types
typedef std::vector< unsigned char, zero_after_free_allocator< unsigned char > > vector_uchar
the actually encoded data
Protected Member Functions
CBase58Data ()
void SetData (const std::vector< unsigned char > &vchVersionIn, const void *pdata, size_t nSize)
void SetData (const std::vector< unsigned char > &vchVersionIn, const unsigned char *pbegin, const unsigned char *pend)
Protected Attributes
std::vector< unsigned char > vchVersion
the version byte(s)
vector_uchar vchData
Detailed Description
Base class for all base58-encoded data.
Definition at line 71 of file base58.h.
Member Typedef Documentation
vector_uchar
typedef std::vector<unsigned char, zero_after_free_allocator<unsigned char> > CBase58Data::vector_uchar protected
the actually encoded data
Definition at line 78 of file base58.h.
Constructor & Destructor Documentation
CBase58Data()
CBase58Data::CBase58Data () protected
Definition at line 152 of file base58.cpp.
References vchData, and vchVersion.
Member Function Documentation
CompareTo()
int CBase58Data::CompareTo (const CBase58Data & b58) const
Definition at line 200 of file base58.cpp.
References vchData, and vchVersion.
Referenced by operator<(), operator<=(), operator==(), operator>(), and operator>=().
operator<()
bool CBase58Data::operator< (const CBase58Data & b58) const inline
Definition at line 94 of file base58.h.
References CompareTo().
operator<=()
bool CBase58Data::operator<= (const CBase58Data & b58) const inline
Definition at line 92 of file base58.h.
References CompareTo().
operator==()
bool CBase58Data::operator== (const CBase58Data & b58) const inline
Definition at line 91 of file base58.h.
References CompareTo().
operator>()
bool CBase58Data::operator> (const CBase58Data & b58) const inline
Definition at line 95 of file base58.h.
References CompareTo().
operator>=()
bool CBase58Data::operator>= (const CBase58Data & b58) const inline
Definition at line 93 of file base58.h.
References CompareTo().
SetData() [1/2]
void CBase58Data::SetData (const std::vector< unsigned char > & vchVersionIn, const void * pdata, size_t nSize) protected
Definition at line 158 of file base58.cpp.
References memcpy(), vchData, and vchVersion.
Referenced by CBitcoinAddress::Set(), SetData(), CBitcoinSecret::SetKey(), and CBitcoinExtKeyBase< K, Size, Type >::SetKey().
SetData() [2/2]
void CBase58Data::SetData (const std::vector< unsigned char > & vchVersionIn, const unsigned char * pbegin, const unsigned char * pend) protected
Definition at line 166 of file base58.cpp.
References SetData().
SetString() [1/2]
bool CBase58Data::SetString (const char * psz, unsigned int nVersionBytes = 1)
Definition at line 171 of file base58.cpp.
References DecodeBase58Check(), memcpy(), memory_cleanse(), vchData, and vchVersion.
Referenced by CBitcoinAddress::CBitcoinAddress(), CBitcoinExtKeyBase< K, Size, Type >::CBitcoinExtKeyBase(), dumpprivkey(), SetString(), and CBitcoinSecret::SetString().
SetString() [2/2]
bool CBase58Data::SetString (const std::string & str)
Definition at line 188 of file base58.cpp.
References SetString().
ToString()
std::string CBase58Data::ToString () const
Definition at line 193 of file base58.cpp.
References EncodeBase58Check(), vchData, and vchVersion.
Referenced by addmultisigaddress(), CGovernancePayment::CGovernancePayment(), CMasternodePayments::CheckPreviousBlockVotes(), createmultisig(), CSuperblockManager::CreateSuperblock(), CHDChain::Debug(), TransactionRecord::decomposeTransaction(), CWallet::DelAddressBook(), dumpprivkey(), dumpwallet(), CMasternodePayments::FillBlockPayee(), getaccountaddress(), getaddressesbyaccount(), getAddressFromIndex(), getblocktemplate(), getnewaddress(), getrawchangeaddress(), CSuperblockManager::GetRequiredPaymentsString(), CSuperblock::IsValid(), ListReceived(), CWallet::LoadCScript(), masternode(), masternodelist(), MaybePushAddress(), CSuperblock::ParsePaymentSchedule(), CMasternodePayments::ProcessBlock(), CMasternodePayments::ProcessMessage(), AddressTablePriv::refreshAddressTable(), CWallet::SelectCoinsGrouppedByAddresses(), TxToJSON(), and validateaddress().
Member Data Documentation
vchData
vector_uchar CBase58Data::vchData protected
Definition at line 79 of file base58.h.
Referenced by CBase58Data(), CompareTo(), CBitcoinAddress::Get(), CBitcoinAddress::GetIndexKey(), CBitcoinSecret::GetKey(), CBitcoinExtKeyBase< K, Size, Type >::GetKey(), CBitcoinAddress::GetKeyID(), CBitcoinAddress::IsValid(), CBitcoinSecret::IsValid(), SetData(), CBitcoinSecret::SetKey(), SetString(), and ToString().
vchVersion
std::vector<unsigned char> CBase58Data::vchVersion protected
the version byte(s)
Definition at line 75 of file base58.h.
Referenced by CBase58Data(), CompareTo(), CBitcoinAddress::Get(), CBitcoinAddress::GetIndexKey(), CBitcoinAddress::GetKeyID(), CBitcoinAddress::IsScript(), CBitcoinAddress::IsValid(), CBitcoinSecret::IsValid(), SetData(), SetString(), and ToString().
The documentation for this class was generated from the following files:
src/base58.h
src/base58.cpp
Released under the MIT license