Dash Core: BitcoinCore Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
BitcoinCore Class Reference
Class encapsulating Dash Core startup and shutdown.
Public Slots
void initialize ()
void shutdown ()
void restart (QStringList args)
Signals
void initializeResult (int retval)
void shutdownResult (int retval)
void runawayException (const QString &message)
Public Member Functions
BitcoinCore ()
Private Member Functions
void handleRunawayException (const std::exception *e)
Pass fatal exception message to UI thread.
Private Attributes
boost::thread_group threadGroup
CScheduler scheduler
bool execute_restart
Flag indicating a restart.
Detailed Description
Class encapsulating Dash Core startup and shutdown.
Allows running startup and shutdown in a different thread from the UI thread.
Definition at line 173 of file dash.cpp.
Constructor & Destructor Documentation
BitcoinCore()
BitcoinCore::BitcoinCore () explicit
Definition at line 264 of file dash.cpp.
Member Function Documentation
handleRunawayException()
void BitcoinCore::handleRunawayException (const std::exception * e) private
Pass fatal exception message to UI thread.
Definition at line 269 of file dash.cpp.
References PrintExceptionContinue(), runawayException(), and strMiscWarning.
Referenced by initialize(), restart(), and shutdown().
initialize
void BitcoinCore::initialize () slot
Definition at line 275 of file dash.cpp.
References AppInit2(), execute_restart, handleRunawayException(), initializeResult(), scheduler, and threadGroup.
initializeResult
void BitcoinCore::initializeResult (int retval) signal
Referenced by initialize().
restart
void BitcoinCore::restart (QStringList args) slot
Definition at line 291 of file dash.cpp.
References CExplicitNetCleanup::callCleanup(), execute_restart, handleRunawayException(), PrepareShutdown(), shutdownResult(), and threadGroup.
runawayException
void BitcoinCore::runawayException (const QString & message) signal
Referenced by handleRunawayException().
shutdown
void BitcoinCore::shutdown () slot
Definition at line 315 of file dash.cpp.
References handleRunawayException(), Interrupt(), Shutdown(), shutdownResult(), and threadGroup.
shutdownResult
void BitcoinCore::shutdownResult (int retval) signal
Referenced by restart(), and shutdown().
Member Data Documentation
execute_restart
bool BitcoinCore::execute_restart private
Flag indicating a restart.
Definition at line 194 of file dash.cpp.
Referenced by initialize(), and restart().
scheduler
CScheduler BitcoinCore::scheduler private
Definition at line 191 of file dash.cpp.
Referenced by initialize().
threadGroup
boost::thread_group BitcoinCore::threadGroup private
Definition at line 190 of file dash.cpp.
Referenced by initialize(), restart(), and shutdown().
The documentation for this class was generated from the following file:
src/qt/dash.cpp
Released under the MIT license