Dash Core: CZMQNotificationInterface Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CZMQNotificationInterface Class Reference final
#include <zmqnotificationinterface.h>
Public Member Functions
virtual ~CZMQNotificationInterface ()
Static Public Member Functions
static CZMQNotificationInterface * Create ()
Protected Member Functions
bool Initialize ()
void Shutdown ()
void TransactionAddedToMempool (const CTransactionRef &tx, int64_t nAcceptTime) override
Notifies listeners of a transaction having been added to mempool.
void BlockConnected (const std::shared_ptr< const CBlock > &pblock, const CBlockIndex *pindexConnected, const std::vector< CTransactionRef > &vtxConflicted) override
Notifies listeners of a block being connected.
void BlockDisconnected (const std::shared_ptr< const CBlock > &pblock, const CBlockIndex *pindexDisconnected) override
Notifies listeners of a block being disconnected.
void UpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload) override
Notifies listeners of updated block chain tip.
void NotifyChainLock (const CBlockIndex *pindex, const llmq::CChainLockSig &clsig) override
void NotifyTransactionLock (const CTransaction &tx, const llmq::CInstantSendLock &islock) override
void NotifyGovernanceVote (const CGovernanceVote &vote) override
void NotifyGovernanceObject (const CGovernanceObject &object) override
void NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx) override
Protected Member Functions inherited from CValidationInterface
virtual void AcceptedBlockHeader (const CBlockIndex *pindexNew)
virtual void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload)
virtual void SynchronousUpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload)
Same as UpdatedBlockTip, but called from the caller's thread.
virtual void TransactionRemovedFromMempool (const CTransactionRef &ptx)
Notifies listeners of a transaction leaving mempool.
virtual void NotifyMasternodeListChanged (bool undo, const CDeterministicMNList &oldMNList, const CDeterministicMNListDiff &diff)
virtual void SetBestChain (const CBlockLocator &locator)
Notifies listeners of the new active block chain on-disk.
virtual void ResendWalletTransactions (int64_t nBestBlockTime, CConnman *connman)
Tells listeners to broadcast their data.
virtual void BlockChecked (const CBlock &, const CValidationState &)
Notifies listeners of a block validation result.
virtual void NewPoWValidBlock (const CBlockIndex *pindex, const std::shared_ptr< const CBlock > &block)
Notifies listeners that a block which builds directly on our current tip has been received and connected to the headers tree, though not validated yet.
friend void ::RegisterValidationInterface (CValidationInterface *)
friend void ::UnregisterValidationInterface (CValidationInterface *)
friend void ::UnregisterAllValidationInterfaces ()
Private Member Functions
CZMQNotificationInterface ()
Private Attributes
void * pcontext
std::list< CZMQAbstractNotifier * > notifiers
Detailed Description
Definition at line 16 of file zmqnotificationinterface.h.
Constructor & Destructor Documentation
~CZMQNotificationInterface()
CZMQNotificationInterface::~CZMQNotificationInterface () virtual
Definition at line 22 of file zmqnotificationinterface.cpp.
References notifiers, and Shutdown().
CZMQNotificationInterface()
CZMQNotificationInterface::CZMQNotificationInterface () private
Definition at line 18 of file zmqnotificationinterface.cpp.
Referenced by Create().
Member Function Documentation
BlockConnected()
void CZMQNotificationInterface::BlockConnected (const std::shared_ptr< const CBlock > & block, const CBlockIndex * pindex, const std::vector< CTransactionRef > & txnConflicted) override protected virtual
Notifies listeners of a block being connected.
Provides a vector of transactions evicted from the mempool as a result.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 197 of file zmqnotificationinterface.cpp.
References TransactionAddedToMempool().
BlockDisconnected()
void CZMQNotificationInterface::BlockDisconnected (const std::shared_ptr< const CBlock > & block, const CBlockIndex * pindexDisconnected) override protected virtual
Notifies listeners of a block being disconnected.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 205 of file zmqnotificationinterface.cpp.
References TransactionAddedToMempool().
Create()
CZMQNotificationInterface * CZMQNotificationInterface::Create () static
Definition at line 32 of file zmqnotificationinterface.cpp.
References CZMQNotificationInterface(), gArgs, ArgsManager::GetArg(), Initialize(), ArgsManager::IsArgSet(), notifiers, CZMQAbstractNotifier::SetAddress(), and CZMQAbstractNotifier::SetType().
Referenced by AppInitMain().
Initialize()
bool CZMQNotificationInterface::Initialize () protected
Definition at line 85 of file zmqnotificationinterface.cpp.
References CZMQAbstractNotifier::GetAddress(), CZMQAbstractNotifier::GetType(), CZMQAbstractNotifier::Initialize(), LogPrint, notifiers, pcontext, BCLog::ZMQ, and zmqError().
Referenced by Create().
NotifyChainLock()
void CZMQNotificationInterface::NotifyChainLock (const CBlockIndex * pindex, const llmq::CChainLockSig & clsig) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 159 of file zmqnotificationinterface.cpp.
References notifiers, CZMQAbstractNotifier::NotifyChainLock(), and CZMQAbstractNotifier::Shutdown().
NotifyGovernanceObject()
void CZMQNotificationInterface::NotifyGovernanceObject (const CGovernanceObject & object) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 247 of file zmqnotificationinterface.cpp.
References notifiers, CZMQAbstractNotifier::NotifyGovernanceObject(), and CZMQAbstractNotifier::Shutdown().
NotifyGovernanceVote()
void CZMQNotificationInterface::NotifyGovernanceVote (const CGovernanceVote & vote) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 230 of file zmqnotificationinterface.cpp.
References notifiers, CZMQAbstractNotifier::NotifyGovernanceVote(), and CZMQAbstractNotifier::Shutdown().
NotifyInstantSendDoubleSpendAttempt()
void CZMQNotificationInterface::NotifyInstantSendDoubleSpendAttempt (const CTransaction & currentTx, const CTransaction & previousTx) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 264 of file zmqnotificationinterface.cpp.
References notifiers, CZMQAbstractNotifier::NotifyInstantSendDoubleSpendAttempt(), and CZMQAbstractNotifier::Shutdown().
NotifyTransactionLock()
void CZMQNotificationInterface::NotifyTransactionLock (const CTransaction & tx, const llmq::CInstantSendLock & islock) override protected virtual
Reimplemented from CValidationInterface.
Definition at line 213 of file zmqnotificationinterface.cpp.
References notifiers, CZMQAbstractNotifier::NotifyTransactionLock(), and CZMQAbstractNotifier::Shutdown().
Shutdown()
void CZMQNotificationInterface::Shutdown () protected
Definition at line 122 of file zmqnotificationinterface.cpp.
References CZMQAbstractNotifier::GetAddress(), CZMQAbstractNotifier::GetType(), LogPrint, notifiers, pcontext, CZMQAbstractNotifier::Shutdown(), and BCLog::ZMQ.
Referenced by ~CZMQNotificationInterface().
TransactionAddedToMempool()
void CZMQNotificationInterface::TransactionAddedToMempool (const CTransactionRef & ptxn, int64_t nAcceptTime) override protected virtual
Notifies listeners of a transaction having been added to mempool.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 176 of file zmqnotificationinterface.cpp.
References notifiers, CZMQAbstractNotifier::NotifyTransaction(), and CZMQAbstractNotifier::Shutdown().
Referenced by BlockConnected(), and BlockDisconnected().
UpdatedBlockTip()
void CZMQNotificationInterface::UpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload) override protected virtual
Notifies listeners of updated block chain tip.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 139 of file zmqnotificationinterface.cpp.
References notifiers, CZMQAbstractNotifier::NotifyBlock(), and CZMQAbstractNotifier::Shutdown().
Member Data Documentation
notifiers
std::list<CZMQAbstractNotifier*> CZMQNotificationInterface::notifiers private
Definition at line 43 of file zmqnotificationinterface.h.
Referenced by Create(), Initialize(), NotifyChainLock(), NotifyGovernanceObject(), NotifyGovernanceVote(), NotifyInstantSendDoubleSpendAttempt(), NotifyTransactionLock(), Shutdown(), TransactionAddedToMempool(), UpdatedBlockTip(), and ~CZMQNotificationInterface().
pcontext
void* CZMQNotificationInterface::pcontext private
Definition at line 42 of file zmqnotificationinterface.h.
Referenced by Initialize(), and Shutdown().
The documentation for this class was generated from the following files:
src/zmq/zmqnotificationinterface.h
src/zmq/zmqnotificationinterface.cpp
Released under the MIT license