Dash Core: WalletView Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
WalletView Class Reference
#include <walletview.h>
Public Slots
void gotoOverviewPage ()
Switch to overview (home) page.
void gotoHistoryPage ()
Switch to history (transactions) page.
void gotoMasternodePage ()
Switch to masternode page.
void gotoReceiveCoinsPage ()
Switch to receive coins page.
void gotoSendCoinsPage (QString addr="")
Switch to send coins page.
void gotoPrivateSendCoinsPage (QString addr="")
Switch to PrivateSend coins page.
void gotoSignMessageTab (QString addr="")
Show Sign/Verify Message dialog and switch to sign message tab.
void gotoVerifyMessageTab (QString addr="")
Show Sign/Verify Message dialog and switch to verify message tab.
void processNewTransaction (const QModelIndex &parent, int start, int)
Show incoming transaction notification for new transactions.
void encryptWallet (bool status)
Encrypt the wallet.
void backupWallet ()
Backup the wallet.
void changePassphrase ()
Change encrypted wallet passphrase.
void unlockWallet (bool fAnonymizeOnly=false)
Ask for passphrase to unlock wallet temporarily.
void lockWallet ()
Lock wallet.
void usedSendingAddresses ()
Show used sending addresses.
void usedReceivingAddresses ()
Show used receiving addresses.
void updateEncryptionStatus ()
Re-emit encryption status signal.
void showProgress (const QString &title, int nProgress)
Show progress dialog e.g.
void requestedSyncWarningInfo ()
User has requested more information about the out of sync state.
void trxAmount (QString amount)
Update selected DASH amount from transactionview.
Signals
void showNormalIfMinimized ()
Signal that we want to show the main window.
void message (const QString &title, const QString &message, unsigned int style)
Fired when a message should be reported to the user.
void encryptionStatusChanged (int status)
Encryption status of wallet changed.
void hdEnabledStatusChanged (int hdEnabled)
HD-Enabled status of wallet changed (only possible during startup)
void incomingTransaction (const QString &date, int unit, const CAmount &amount, const QString &type, const QString &address, const QString &label)
Notify that a new transaction appeared.
void outOfSyncWarningClicked ()
Notify that the out of sync warning icon has been pressed.
Public Member Functions
WalletView (QWidget *parent)
~WalletView ()
void setBitcoinGUI (BitcoinGUI *gui)
void setClientModel (ClientModel *clientModel)
Set the client model.
WalletModel * getWalletModel ()
void setWalletModel (WalletModel *walletModel)
Set the wallet model.
bool handlePaymentRequest (const SendCoinsRecipient &recipient)
void showOutOfSyncWarning (bool fShow)
Private Attributes
ClientModel * clientModel
WalletModel * walletModel
OverviewPage * overviewPage
QWidget * transactionsPage
ReceiveCoinsDialog * receiveCoinsPage
SendCoinsDialog * sendCoinsPage
SendCoinsDialog * privateSendCoinsPage
AddressBookPage * usedSendingAddressesPage
AddressBookPage * usedReceivingAddressesPage
MasternodeList * masternodeListPage
TransactionView * transactionView
QProgressDialog * progressDialog
QLabel * transactionSum
Detailed Description
Definition at line 35 of file walletview.h.
Constructor & Destructor Documentation
WalletView()
WalletView::WalletView (QWidget * parent) explicit
Definition at line 34 of file walletview.cpp.
References GUIUtil::Bold, GUIUtil::disableMacFocusRect(), AddressBookPage::ForEditing, masternodeListPage, message(), outOfSyncWarningClicked(), overviewPage, privateSendCoinsPage, receiveCoinsPage, AddressBookPage::ReceivingTab, requestedSyncWarningInfo(), sendCoinsPage, AddressBookPage::SendingTab, GUIUtil::setFont(), transactionsPage, transactionSum, transactionView, trxAmount(), GUIUtil::updateFonts(), usedReceivingAddressesPage, and usedSendingAddressesPage.
~WalletView()
WalletView::~WalletView ()
Definition at line 115 of file walletview.cpp.
Member Function Documentation
backupWallet
void WalletView::backupWallet () slot
Backup the wallet.
Definition at line 313 of file walletview.cpp.
References WalletModel::backupWallet(), GUIUtil::getSaveFileName(), message(), CClientUIInterface::MSG_ERROR, CClientUIInterface::MSG_INFORMATION, and walletModel.
Referenced by WalletFrame::backupWallet().
changePassphrase
void WalletView::changePassphrase () slot
Change encrypted wallet passphrase.
Definition at line 332 of file walletview.cpp.
References AskPassphraseDialog::ChangePass, AskPassphraseDialog::setModel(), and walletModel.
Referenced by WalletFrame::changePassphrase().
encryptionStatusChanged
void WalletView::encryptionStatusChanged (int status) signal
Encryption status of wallet changed.
Referenced by setBitcoinGUI(), setWalletModel(), and updateEncryptionStatus().
encryptWallet
void WalletView::encryptWallet (bool status) slot
Encrypt the wallet.
Definition at line 302 of file walletview.cpp.
References AskPassphraseDialog::Decrypt, AskPassphraseDialog::Encrypt, AskPassphraseDialog::setModel(), updateEncryptionStatus(), and walletModel.
Referenced by WalletFrame::encryptWallet().
getWalletModel()
WalletModel* WalletView::getWalletModel () inline
Definition at line 48 of file walletview.h.
References walletModel.
gotoHistoryPage
void WalletView::gotoHistoryPage () slot
Switch to history (transactions) page.
Definition at line 228 of file walletview.cpp.
References transactionsPage.
Referenced by setBitcoinGUI().
gotoMasternodePage
void WalletView::gotoMasternodePage () slot
Switch to masternode page.
Definition at line 233 of file walletview.cpp.
References masternodeListPage.
gotoOverviewPage
void WalletView::gotoOverviewPage () slot
Switch to overview (home) page.
Definition at line 223 of file walletview.cpp.
References overviewPage.
Referenced by WalletFrame::addWallet().
gotoPrivateSendCoinsPage
void WalletView::gotoPrivateSendCoinsPage (QString addr = "") slot
Switch to PrivateSend coins page.
Definition at line 255 of file walletview.cpp.
References privateSendCoinsPage, and SendCoinsDialog::setAddress().
gotoReceiveCoinsPage
void WalletView::gotoReceiveCoinsPage () slot
Switch to receive coins page.
Definition at line 241 of file walletview.cpp.
References receiveCoinsPage.
gotoSendCoinsPage
void WalletView::gotoSendCoinsPage (QString addr = "") slot
Switch to send coins page.
Definition at line 246 of file walletview.cpp.
References sendCoinsPage, and SendCoinsDialog::setAddress().
gotoSignMessageTab
void WalletView::gotoSignMessageTab (QString addr = "") slot
Show Sign/Verify Message dialog and switch to sign message tab.
Definition at line 263 of file walletview.cpp.
References SignVerifyMessageDialog::setAddress_SM(), SignVerifyMessageDialog::setModel(), SignVerifyMessageDialog::showTab_SM(), and walletModel.
Referenced by WalletFrame::gotoSignMessageTab().
gotoVerifyMessageTab
void WalletView::gotoVerifyMessageTab (QString addr = "") slot
Show Sign/Verify Message dialog and switch to verify message tab.
Definition at line 275 of file walletview.cpp.
References SignVerifyMessageDialog::setAddress_VM(), SignVerifyMessageDialog::setModel(), SignVerifyMessageDialog::showTab_VM(), and walletModel.
Referenced by WalletFrame::gotoVerifyMessageTab().
handlePaymentRequest()
bool WalletView::handlePaymentRequest (const SendCoinsRecipient & recipient)
Definition at line 287 of file walletview.cpp.
References SendCoinsDialog::handlePaymentRequest(), and sendCoinsPage.
Referenced by WalletFrame::handlePaymentRequest().
hdEnabledStatusChanged
void WalletView::hdEnabledStatusChanged (int hdEnabled) signal
HD-Enabled status of wallet changed (only possible during startup)
Referenced by setBitcoinGUI(), and setWalletModel().
incomingTransaction
void WalletView::incomingTransaction (const QString & date, int unit, const CAmount & amount, const QString & type, const QString & address, const QString & label) signal
Notify that a new transaction appeared.
Referenced by processNewTransaction(), and setBitcoinGUI().
lockWallet
void WalletView::lockWallet () slot
Lock wallet.
Definition at line 353 of file walletview.cpp.
References WalletModel::setWalletLocked(), and walletModel.
Referenced by WalletFrame::lockWallet().
message
void WalletView::message (const QString & title, const QString & message, unsigned int style) signal
Fired when a message should be reported to the user.
Referenced by backupWallet(), setBitcoinGUI(), setWalletModel(), and WalletView().
outOfSyncWarningClicked
void WalletView::outOfSyncWarningClicked () signal
Notify that the out of sync warning icon has been pressed.
Referenced by requestedSyncWarningInfo(), and WalletView().
processNewTransaction
void WalletView::processNewTransaction (const QModelIndex & parent, int start, int) slot
Show incoming transaction notification for new transactions.
The new items are those between start and end inclusive, under the given parent item.
Definition at line 194 of file walletview.cpp.
References TransactionTableModel::AddressRole, TransactionTableModel::Amount, clientModel, TransactionTableModel::data(), TransactionTableModel::Date, OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), WalletModel::getTransactionTableModel(), incomingTransaction(), TransactionTableModel::index(), ClientModel::inInitialBlockDownload(), TransactionTableModel::LabelRole, TransactionRecord::PrivateSendCollateralPayment, TransactionRecord::PrivateSendCreateDenominations, TransactionRecord::PrivateSendDenominate, TransactionRecord::PrivateSendMakeCollaterals, TransactionTableModel::processingQueuedTransactions(), TransactionTableModel::Type, TransactionTableModel::TypeRole, and walletModel.
Referenced by setWalletModel().
requestedSyncWarningInfo
void WalletView::requestedSyncWarningInfo () slot
User has requested more information about the out of sync state.
Definition at line 400 of file walletview.cpp.
References outOfSyncWarningClicked().
Referenced by WalletView().
setBitcoinGUI()
void WalletView::setBitcoinGUI (BitcoinGUI * gui)
Definition at line 119 of file walletview.cpp.
References encryptionStatusChanged(), gotoHistoryPage(), hdEnabledStatusChanged(), incomingTransaction(), message(), and overviewPage.
Referenced by WalletFrame::addWallet().
setClientModel()
void WalletView::setClientModel (ClientModel * clientModel)
Set the client model.
The client model represents the part of the core that communicates with the P2P network, and is wallet-agnostic.
Definition at line 140 of file walletview.cpp.
References clientModel, masternodeListPage, overviewPage, privateSendCoinsPage, sendCoinsPage, OverviewPage::setClientModel(), MasternodeList::setClientModel(), and SendCoinsDialog::setClientModel().
Referenced by WalletFrame::addWallet().
setWalletModel()
void WalletView::setWalletModel (WalletModel * walletModel)
Set the wallet model.
The wallet model represents a bitcoin wallet, and offers access to the list of transactions, address book and sending functionality.
Definition at line 153 of file walletview.cpp.
References encryptionStatusChanged(), WalletModel::getAddressTableModel(), WalletModel::getTransactionTableModel(), WalletModel::hdEnabled(), hdEnabledStatusChanged(), masternodeListPage, message(), overviewPage, privateSendCoinsPage, processNewTransaction(), receiveCoinsPage, sendCoinsPage, TransactionView::setModel(), SendCoinsDialog::setModel(), AddressBookPage::setModel(), ReceiveCoinsDialog::setModel(), OverviewPage::setWalletModel(), MasternodeList::setWalletModel(), showProgress(), transactionView, unlockWallet(), updateEncryptionStatus(), usedReceivingAddressesPage, usedSendingAddressesPage, and walletModel.
Referenced by WalletFrame::addWallet().
showNormalIfMinimized
void WalletView::showNormalIfMinimized () signal
Signal that we want to show the main window.
showOutOfSyncWarning()
void WalletView::showOutOfSyncWarning (bool fShow)
Definition at line 292 of file walletview.cpp.
References overviewPage, and OverviewPage::showOutOfSyncWarning().
Referenced by WalletFrame::addWallet().
showProgress
void WalletView::showProgress (const QString & title, int nProgress) slot
Show progress dialog e.g.
for rescan
Definition at line 377 of file walletview.cpp.
References progressDialog.
Referenced by setWalletModel().
trxAmount
void WalletView::trxAmount (QString amount) slot
Update selected DASH amount from transactionview.
Update wallet with the sum of the selected transactions.
Definition at line 406 of file walletview.cpp.
References transactionSum.
Referenced by WalletView().
unlockWallet
void WalletView::unlockWallet (bool fAnonymizeOnly = false) slot
Ask for passphrase to unlock wallet temporarily.
Definition at line 339 of file walletview.cpp.
References WalletModel::getEncryptionStatus(), WalletModel::Locked, AskPassphraseDialog::setModel(), AskPassphraseDialog::Unlock, WalletModel::UnlockedForMixingOnly, AskPassphraseDialog::UnlockMixing, and walletModel.
Referenced by setWalletModel(), and WalletFrame::unlockWallet().
updateEncryptionStatus
void WalletView::updateEncryptionStatus () slot
Re-emit encryption status signal.
Definition at line 297 of file walletview.cpp.
References encryptionStatusChanged(), WalletModel::getEncryptionStatus(), and walletModel.
Referenced by encryptWallet(), WalletFrame::setCurrentWallet(), and setWalletModel().
usedReceivingAddresses
void WalletView::usedReceivingAddresses () slot
Show used receiving addresses.
Definition at line 369 of file walletview.cpp.
References GUIUtil::bringToFront(), usedReceivingAddressesPage, and walletModel.
Referenced by WalletFrame::usedReceivingAddresses().
usedSendingAddresses
void WalletView::usedSendingAddresses () slot
Show used sending addresses.
Definition at line 361 of file walletview.cpp.
References GUIUtil::bringToFront(), usedSendingAddressesPage, and walletModel.
Referenced by WalletFrame::usedSendingAddresses().
Member Data Documentation
clientModel
ClientModel* WalletView::clientModel private
Definition at line 60 of file walletview.h.
Referenced by processNewTransaction(), and setClientModel().
masternodeListPage
MasternodeList* WalletView::masternodeListPage private
Definition at line 70 of file walletview.h.
Referenced by gotoMasternodePage(), setClientModel(), setWalletModel(), and WalletView().
overviewPage
OverviewPage* WalletView::overviewPage private
Definition at line 63 of file walletview.h.
Referenced by gotoOverviewPage(), setBitcoinGUI(), setClientModel(), setWalletModel(), showOutOfSyncWarning(), and WalletView().
privateSendCoinsPage
SendCoinsDialog* WalletView::privateSendCoinsPage private
Definition at line 67 of file walletview.h.
Referenced by gotoPrivateSendCoinsPage(), setClientModel(), setWalletModel(), and WalletView().
progressDialog
QProgressDialog* WalletView::progressDialog private
Definition at line 74 of file walletview.h.
Referenced by showProgress().
receiveCoinsPage
ReceiveCoinsDialog* WalletView::receiveCoinsPage private
Definition at line 65 of file walletview.h.
Referenced by gotoReceiveCoinsPage(), setWalletModel(), and WalletView().
sendCoinsPage
SendCoinsDialog* WalletView::sendCoinsPage private
Definition at line 66 of file walletview.h.
Referenced by gotoSendCoinsPage(), handlePaymentRequest(), setClientModel(), setWalletModel(), and WalletView().
transactionsPage
QWidget* WalletView::transactionsPage private
Definition at line 64 of file walletview.h.
Referenced by gotoHistoryPage(), and WalletView().
transactionSum
QLabel* WalletView::transactionSum private
Definition at line 75 of file walletview.h.
Referenced by trxAmount(), and WalletView().
transactionView
TransactionView* WalletView::transactionView private
Definition at line 72 of file walletview.h.
Referenced by setWalletModel(), and WalletView().
usedReceivingAddressesPage
AddressBookPage* WalletView::usedReceivingAddressesPage private
Definition at line 69 of file walletview.h.
Referenced by setWalletModel(), usedReceivingAddresses(), and WalletView().
usedSendingAddressesPage
AddressBookPage* WalletView::usedSendingAddressesPage private
Definition at line 68 of file walletview.h.
Referenced by setWalletModel(), usedSendingAddresses(), and WalletView().
walletModel
WalletModel* WalletView::walletModel private
Definition at line 61 of file walletview.h.
Referenced by backupWallet(), changePassphrase(), encryptWallet(), getWalletModel(), gotoSignMessageTab(), gotoVerifyMessageTab(), lockWallet(), processNewTransaction(), setWalletModel(), unlockWallet(), updateEncryptionStatus(), usedReceivingAddresses(), and usedSendingAddresses().
The documentation for this class was generated from the following files:
src/qt/walletview.h
src/qt/walletview.cpp
Released under the MIT license