Dash Core: CDBTransactionIterator< CDBTransaction > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CDBTransactionIterator< CDBTransaction > Class Template Reference
#include <dbwrapper.h>
Public Member Functions
CDBTransactionIterator (CDBTransaction &_transaction)
void SeekToFirst ()
template<typename K >
void Seek (const K &key)
void Seek (const CDataStream &ssKey)
bool Valid ()
void Next ()
template<typename K >
bool GetKey (K &key)
CDataStream GetKey ()
unsigned int GetKeySize ()
template<typename V >
bool GetValue (V &value)
Private Types
typedef std::remove_pointer< decltype(transaction.parent.NewIterator())>::type ParentIterator
Private Member Functions
void SkipDeletedAndOverwritten ()
void DecideCur ()
Private Attributes
CDBTransaction & transaction
CDBTransaction::WritesMap::iterator transactionIt
std::unique_ptr< ParentIterator > parentIt
CDataStream parentKey
bool curIsParent {false}
Detailed Description
template<typename CDBTransaction>
class CDBTransactionIterator< CDBTransaction >
Definition at line 401 of file dbwrapper.h.
Member Typedef Documentation
ParentIterator
template<typename CDBTransaction> typedef std::remove_pointer<decltype(transaction.parent.NewIterator())>::type CDBTransactionIterator< CDBTransaction >::ParentIterator private
Definition at line 406 of file dbwrapper.h.
Constructor & Destructor Documentation
CDBTransactionIterator()
template<typename CDBTransaction> CDBTransactionIterator< CDBTransaction >::CDBTransactionIterator (CDBTransaction & _transaction) inline explicit
Definition at line 418 of file dbwrapper.h.
References CDBTransaction< Parent, CommitTarget >::parent, CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::transaction, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransaction< Parent, CommitTarget >::writes.
Member Function Documentation
DecideCur()
template<typename CDBTransaction> void CDBTransactionIterator< CDBTransaction >::DecideCur () inline private
Definition at line 536 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::curIsParent, CDBTransaction< Parent, CommitTarget >::DataStreamCmp::less(), CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::parentKey, CDBTransactionIterator< CDBTransaction >::transaction, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransaction< Parent, CommitTarget >::writes.
Referenced by CDBTransactionIterator< CDBTransaction >::Next(), CDBTransactionIterator< CDBTransaction >::Seek(), and CDBTransactionIterator< CDBTransaction >::SeekToFirst().
GetKey() [1/2]
template<typename CDBTransaction> template<typename K > bool CDBTransactionIterator< CDBTransaction >::GetKey (K & key) inline
Definition at line 465 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::curIsParent, CDBTransactionIterator< CDBTransaction >::parentKey, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransactionIterator< CDBTransaction >::Valid().
GetKey() [2/2]
template<typename CDBTransaction> CDataStream CDBTransactionIterator< CDBTransaction >::GetKey () inline
Definition at line 491 of file dbwrapper.h.
References CLIENT_VERSION, CDBTransactionIterator< CDBTransaction >::curIsParent, CDBTransactionIterator< CDBTransaction >::parentKey, SER_DISK, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransactionIterator< CDBTransaction >::Valid().
GetKeySize()
template<typename CDBTransaction> unsigned int CDBTransactionIterator< CDBTransaction >::GetKeySize () inline
Definition at line 502 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::curIsParent, CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransactionIterator< CDBTransaction >::Valid().
GetValue()
template<typename CDBTransaction> template<typename V > bool CDBTransactionIterator< CDBTransaction >::GetValue (V & value) inline
Definition at line 514 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::curIsParent, CDBTransactionIterator< CDBTransaction >::parentKey, CDBTransaction< Parent, CommitTarget >::Read(), CDBTransactionIterator< CDBTransaction >::transaction, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransactionIterator< CDBTransaction >::Valid().
Next()
template<typename CDBTransaction> void CDBTransactionIterator< CDBTransaction >::Next () inline
Definition at line 449 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::curIsParent, CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten(), CDBTransactionIterator< CDBTransaction >::transaction, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransaction< Parent, CommitTarget >::writes.
Seek() [1/2]
template<typename CDBTransaction> template<typename K > void CDBTransactionIterator< CDBTransaction >::Seek (const K & key) inline
Definition at line 434 of file dbwrapper.h.
References CDBTransaction< Parent, CommitTarget >::KeyToDataStream().
Seek() [2/2]
template<typename CDBTransaction> void CDBTransactionIterator< CDBTransaction >::Seek (const CDataStream & ssKey) inline
Definition at line 438 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten(), CDBTransactionIterator< CDBTransaction >::transaction, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransaction< Parent, CommitTarget >::writes.
SeekToFirst()
template<typename CDBTransaction> void CDBTransactionIterator< CDBTransaction >::SeekToFirst () inline
Definition at line 426 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten(), CDBTransactionIterator< CDBTransaction >::transaction, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransaction< Parent, CommitTarget >::writes.
SkipDeletedAndOverwritten()
template<typename CDBTransaction> void CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten () inline private
Definition at line 526 of file dbwrapper.h.
References CDBTransaction< Parent, CommitTarget >::deletes, CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::parentKey, CDBTransactionIterator< CDBTransaction >::transaction, and CDBTransaction< Parent, CommitTarget >::writes.
Referenced by CDBTransactionIterator< CDBTransaction >::Next(), CDBTransactionIterator< CDBTransaction >::Seek(), and CDBTransactionIterator< CDBTransaction >::SeekToFirst().
Valid()
template<typename CDBTransaction> bool CDBTransactionIterator< CDBTransaction >::Valid () inline
Definition at line 445 of file dbwrapper.h.
References CDBTransactionIterator< CDBTransaction >::parentIt, CDBTransactionIterator< CDBTransaction >::transaction, CDBTransactionIterator< CDBTransaction >::transactionIt, and CDBTransaction< Parent, CommitTarget >::writes.
Referenced by CDBTransactionIterator< CDBTransaction >::GetKey(), CDBTransactionIterator< CDBTransaction >::GetKeySize(), and CDBTransactionIterator< CDBTransaction >::GetValue().
Member Data Documentation
curIsParent
template<typename CDBTransaction> bool CDBTransactionIterator< CDBTransaction >::curIsParent {false} private
Definition at line 415 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::GetKey(), CDBTransactionIterator< CDBTransaction >::GetKeySize(), CDBTransactionIterator< CDBTransaction >::GetValue(), and CDBTransactionIterator< CDBTransaction >::Next().
parentIt
template<typename CDBTransaction> std::unique_ptr<ParentIterator> CDBTransactionIterator< CDBTransaction >::parentIt private
Definition at line 413 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::CDBTransactionIterator(), CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::GetKeySize(), CDBTransactionIterator< CDBTransaction >::Next(), CDBTransactionIterator< CDBTransaction >::Seek(), CDBTransactionIterator< CDBTransaction >::SeekToFirst(), CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten(), and CDBTransactionIterator< CDBTransaction >::Valid().
parentKey
template<typename CDBTransaction> CDataStream CDBTransactionIterator< CDBTransaction >::parentKey private
Definition at line 414 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::GetKey(), CDBTransactionIterator< CDBTransaction >::GetValue(), and CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten().
transaction
template<typename CDBTransaction> CDBTransaction& CDBTransactionIterator< CDBTransaction >::transaction private
Definition at line 404 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::CDBTransactionIterator(), CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::GetValue(), CDBTransactionIterator< CDBTransaction >::Next(), CDBTransactionIterator< CDBTransaction >::Seek(), CDBTransactionIterator< CDBTransaction >::SeekToFirst(), CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten(), and CDBTransactionIterator< CDBTransaction >::Valid().
transactionIt
template<typename CDBTransaction> CDBTransaction::WritesMap::iterator CDBTransactionIterator< CDBTransaction >::transactionIt private
Definition at line 412 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::CDBTransactionIterator(), CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransactionIterator< CDBTransaction >::GetKey(), CDBTransactionIterator< CDBTransaction >::GetKeySize(), CDBTransactionIterator< CDBTransaction >::GetValue(), CDBTransactionIterator< CDBTransaction >::Next(), CDBTransactionIterator< CDBTransaction >::Seek(), CDBTransactionIterator< CDBTransaction >::SeekToFirst(), and CDBTransactionIterator< CDBTransaction >::Valid().
The documentation for this class was generated from the following file:
src/dbwrapper.h
Released under the MIT license