Dash Core: ArgsManagerHelper Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
ArgsManagerHelper Class Reference
Internal helper functions for ArgsManager.
Public Types
typedef std::map< std::string, std::vector< std::string > > MapArgs
Static Public Member Functions
static bool UseDefaultSection (const ArgsManager &am, const std::string &arg)
Determine whether to use config settings in the default section, See also comments around ArgsManager::ArgsManager() below.
static std::string NetworkArg (const ArgsManager &am, const std::string &arg)
Convert regular argument into the network-specific setting.
static void AddArgs (std::vector< std::string > &res, const MapArgs &map_args, const std::string &arg)
Find arguments in a map and add them to a vector.
static std::pair< bool, std::string > GetArgHelper (const MapArgs &map_args, const std::string &arg, bool getLast=false)
Return true/false if an argument is set in a map, and also return the first (or last) of the possibly multiple values it has.
static std::pair< bool, std::string > GetArg (const ArgsManager &am, const std::string &arg)
static bool GetNetBoolArg (const ArgsManager &am, const std::string &net_arg, bool interpret_bool)
Detailed Description
Internal helper functions for ArgsManager.
Definition at line 537 of file util.cpp.
Member Typedef Documentation
MapArgs
typedef std::map<std::string, std::vector<std::string> > ArgsManagerHelper::MapArgs
Definition at line 539 of file util.cpp.
Member Function Documentation
AddArgs()
static void ArgsManagerHelper::AddArgs (std::vector< std::string > & res, const MapArgs & map_args, const std::string & arg) inline static
Find arguments in a map and add them to a vector.
Definition at line 556 of file util.cpp.
Referenced by ArgsManager::GetArgs().
GetArg()
static std::pair<bool,std::string> ArgsManagerHelper::GetArg (const ArgsManager & am, const std::string & arg) inline static
Definition at line 586 of file util.cpp.
References ArgsManager::cs_args, GetArgHelper(), LOCK, ArgsManager::m_config_args, ArgsManager::m_network, ArgsManager::m_override_args, NetworkArg(), and UseDefaultSection().
Referenced by ArgsManager::GetArg(), ArgsManager::GetBoolArg(), and ArgsManager::IsArgSet().
GetArgHelper()
static std::pair<bool,std::string> ArgsManagerHelper::GetArgHelper (const MapArgs & map_args, const std::string & arg, bool getLast = false) inline static
Return true/false if an argument is set in a map, and also return the first (or last) of the possibly multiple values it has.
Definition at line 567 of file util.cpp.
Referenced by GetArg(), GetNetBoolArg(), and ArgsManager::WarnForSectionOnlyArgs().
GetNetBoolArg()
static bool ArgsManagerHelper::GetNetBoolArg (const ArgsManager & am, const std::string & net_arg, bool interpret_bool) inline static
Definition at line 622 of file util.cpp.
References GetArgHelper(), InterpretBool(), ArgsManager::m_config_args, and ArgsManager::m_override_args.
Referenced by ArgsManager::GetChainName().
NetworkArg()
static std::string ArgsManagerHelper::NetworkArg (const ArgsManager & am, const std::string & arg) inline static
Convert regular argument into the network-specific setting.
Definition at line 549 of file util.cpp.
References ArgsManager::m_network.
Referenced by ArgsManager::ForceRemoveArg(), GetArg(), ArgsManager::GetArgs(), ArgsManager::IsArgNegated(), and ArgsManager::WarnForSectionOnlyArgs().
UseDefaultSection()
static bool ArgsManagerHelper::UseDefaultSection (const ArgsManager & am, const std::string & arg) inline static
Determine whether to use config settings in the default section, See also comments around ArgsManager::ArgsManager() below.
Definition at line 543 of file util.cpp.
References ArgsManager::m_network, ArgsManager::m_network_only_args, and CBaseChainParams::MAIN.
Referenced by GetArg(), and ArgsManager::GetArgs().
The documentation for this class was generated from the following file:
src/util.cpp
Released under the MIT license