Dash Core: GetinfoRequestHandler Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
GetinfoRequestHandler Class Reference
Process getinfo requests.
Public Member Functions
UniValue PrepareRequest (const std::string &method, const std::vector< std::string > &args) override
Create a simulated getinfo request.
UniValue ProcessReply (const UniValue &batch_in) override
Collect values from the batch and form a simulated getinfo reply.
Public Attributes
const int ID_NETWORKINFO = 0
const int ID_BLOCKCHAININFO = 1
const int ID_WALLETINFO = 2
Detailed Description
Process getinfo requests.
Definition at line 220 of file dash-cli.cpp.
Member Function Documentation
PrepareRequest()
UniValue GetinfoRequestHandler::PrepareRequest (const std::string & method, const std::vector< std::string > & args) inline override virtual
Create a simulated getinfo request.
Implements BaseRequestHandler.
Definition at line 228 of file dash-cli.cpp.
References ID_BLOCKCHAININFO, ID_NETWORKINFO, ID_WALLETINFO, JSONRPCRequestObj(), NullUniValue, UniValue::push_back(), and UniValue::VARR.
ProcessReply()
UniValue GetinfoRequestHandler::ProcessReply (const UniValue & batch_in) inline override virtual
Collect values from the batch and form a simulated getinfo reply.
Implements BaseRequestHandler.
Definition at line 241 of file dash-cli.cpp.
References ID_BLOCKCHAININFO, ID_NETWORKINFO, ID_WALLETINFO, JSONRPCProcessBatchReply(), JSONRPCReplyObj(), NullUniValue, UniValue::pushKV(), and UniValue::VOBJ.
Member Data Documentation
ID_BLOCKCHAININFO
const int GetinfoRequestHandler::ID_BLOCKCHAININFO = 1
Definition at line 224 of file dash-cli.cpp.
Referenced by PrepareRequest(), and ProcessReply().
ID_NETWORKINFO
const int GetinfoRequestHandler::ID_NETWORKINFO = 0
Definition at line 223 of file dash-cli.cpp.
Referenced by PrepareRequest(), and ProcessReply().
ID_WALLETINFO
const int GetinfoRequestHandler::ID_WALLETINFO = 2
Definition at line 225 of file dash-cli.cpp.
Referenced by PrepareRequest(), and ProcessReply().
The documentation for this class was generated from the following file:
src/dash-cli.cpp
Released under the MIT license