Dash Core: llmq::SigShareMap< T > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::SigShareMap< T > Class Template Reference
#include <quorums_signing_shares.h>
Public Member Functions
bool Add (const SigShareKey &k, const T &v)
void Erase (const SigShareKey &k)
void Clear ()
bool Has (const SigShareKey &k) const
T * Get (const SigShareKey &k)
T & GetOrAdd (const SigShareKey &k)
const T * GetFirst () const
size_t Size () const
size_t CountForSignHash (const uint256 &signHash) const
bool Empty () const
const std::unordered_map< uint16_t, T > * GetAllForSignHash (const uint256 &signHash)
void EraseAllForSignHash (const uint256 &signHash)
template<typename F >
void EraseIf (F &&f)
template<typename F >
void ForEach (F &&f)
Private Attributes
std::unordered_map< uint256, std::unordered_map< uint16_t, T >, StaticSaltedHasher > internalMap
Detailed Description
template<typename T>
class llmq::SigShareMap< T >
Definition at line 150 of file quorums_signing_shares.h.
Member Function Documentation
Add()
template<typename T> bool llmq::SigShareMap< T >::Add (const SigShareKey & k, const T & v) inline
Definition at line 156 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::ForceReAnnouncement(), llmq::SigShareMap< bool >::GetOrAdd(), and llmq::CSigSharesManager::ProcessSigShare().
Clear()
template<typename T> void llmq::SigShareMap< T >::Clear () inline
Definition at line 174 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::CollectSigSharesToAnnounce().
CountForSignHash()
template<typename T> size_t llmq::SigShareMap< T >::CountForSignHash (const uint256 & signHash) const inline
Definition at line 230 of file quorums_signing_shares.h.
Empty()
template<typename T> bool llmq::SigShareMap< T >::Empty () const inline
Definition at line 239 of file quorums_signing_shares.h.
Erase()
template<typename T> void llmq::SigShareMap< T >::Erase (const SigShareKey & k) inline
Definition at line 162 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::BanNode(), llmq::CSigSharesManager::Cleanup(), and llmq::CSigSharesManager::RemoveBannedNodeStates().
EraseAllForSignHash()
template<typename T> void llmq::SigShareMap< T >::EraseAllForSignHash (const uint256 & signHash) inline
Definition at line 253 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesNodeState::RemoveSession(), and llmq::CSigSharesManager::RemoveSigSharesForSession().
EraseIf()
template<typename T> template<typename F > void llmq::SigShareMap< T >::EraseIf (F && f) inline
Definition at line 259 of file quorums_signing_shares.h.
ForEach()
template<typename T> template<typename F > void llmq::SigShareMap< T >::ForEach (F && f) inline
Definition at line 281 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::CollectSigSharesToAnnounce().
Get()
template<typename T> T* llmq::SigShareMap< T >::Get (const SigShareKey & k) inline
Definition at line 188 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::CollectSigSharesToRequest(), and llmq::SigShareMap< bool >::GetOrAdd().
GetAllForSignHash()
template<typename T> const std::unordered_map<uint16_t, T>* llmq::SigShareMap< T >::GetAllForSignHash (const uint256 & signHash) inline
Definition at line 244 of file quorums_signing_shares.h.
GetFirst()
template<typename T> const T* llmq::SigShareMap< T >::GetFirst () const inline
Definition at line 213 of file quorums_signing_shares.h.
GetOrAdd()
template<typename T> T& llmq::SigShareMap< T >::GetOrAdd (const SigShareKey & k) inline
Definition at line 203 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::CollectSigSharesToRequest().
Has()
template<typename T> bool llmq::SigShareMap< T >::Has (const SigShareKey & k) const inline
Definition at line 179 of file quorums_signing_shares.h.
Size()
template<typename T> size_t llmq::SigShareMap< T >::Size () const inline
Definition at line 221 of file quorums_signing_shares.h.
Member Data Documentation
internalMap
template<typename T> std::unordered_map<uint256, std::unordered_map<uint16_t, T>, StaticSaltedHasher> llmq::SigShareMap< T >::internalMap private
Definition at line 153 of file quorums_signing_shares.h.
Referenced by llmq::SigShareMap< bool >::Add(), llmq::SigShareMap< bool >::Clear(), llmq::SigShareMap< bool >::CountForSignHash(), llmq::SigShareMap< bool >::Empty(), llmq::SigShareMap< bool >::Erase(), llmq::SigShareMap< bool >::EraseAllForSignHash(), llmq::SigShareMap< bool >::EraseIf(), llmq::SigShareMap< bool >::ForEach(), llmq::SigShareMap< bool >::Get(), llmq::SigShareMap< bool >::GetAllForSignHash(), llmq::SigShareMap< bool >::GetFirst(), llmq::SigShareMap< bool >::Has(), and llmq::SigShareMap< bool >::Size().
The documentation for this class was generated from the following file:
src/llmq/quorums_signing_shares.h
Released under the MIT license