Dash Core: RPCExecutor Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
RPCExecutor Class Reference
Public Slots
void request (const QString &command)
Signals
void reply (int category, const QString &command)
Detailed Description
Definition at line 74 of file rpcconsole.cpp.
Member Function Documentation
reply
void RPCExecutor::reply (int category, const QString & command) signal
Referenced by request().
request
void RPCExecutor::request (const QString & command) slot
Definition at line 205 of file rpcconsole.cpp.
References RPCConsole::CMD_ERROR, RPCConsole::CMD_REPLY, CRPCTable::execute(), find_value(), UniValue::get_int(), UniValue::get_str(), UniValue::isNull(), UniValue::isStr(), parseCommandLine(), reply(), RPCConvertValues(), tableRPC, and UniValue::write().
The documentation for this class was generated from the following file:
src/qt/rpcconsole.cpp
Released under the MIT license