Dash Core: CBLSIESMultiRecipientObjects< Object > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSIESMultiRecipientObjects< Object > Class Template Reference
#include <bls_ies.h>
Public Types
typedef std::vector< Object > ObjectVector
Public Types inherited from CBLSIESMultiRecipientBlobs
typedef std::vector< unsigned char > Blob
typedef std::vector< Blob > BlobVector
Public Member Functions
bool Encrypt (const std::vector< CBLSPublicKey > &recipients, const ObjectVector &_objects, int nVersion)
bool Encrypt (size_t idx, const CBLSPublicKey &recipient, const Object &obj, int nVersion)
bool Decrypt (size_t idx, const CBLSSecretKey &sk, Object &objectRet, int nVersion) const
Public Member Functions inherited from CBLSIESMultiRecipientBlobs
bool Encrypt (const std::vector< CBLSPublicKey > &recipients, const BlobVector &_blobs)
void InitEncrypt (size_t count)
bool Encrypt (size_t idx, const CBLSPublicKey &recipient, const Blob &blob)
bool Decrypt (size_t idx, const CBLSSecretKey &sk, Blob &blobRet) const
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
Additional Inherited Members
Public Attributes inherited from CBLSIESMultiRecipientBlobs
CBLSPublicKey ephemeralPubKey
uint256 ivSeed
BlobVector blobs
CBLSSecretKey ephemeralSecretKey
std::vector< uint256 > ivVector
Detailed Description
template<typename Object>
class CBLSIESMultiRecipientObjects< Object >
Definition at line 113 of file bls_ies.h.
Member Typedef Documentation
ObjectVector
template<typename Object> typedef std::vector<Object> CBLSIESMultiRecipientObjects< Object >::ObjectVector
Definition at line 116 of file bls_ies.h.
Member Function Documentation
Decrypt()
template<typename Object> bool CBLSIESMultiRecipientObjects< Object >::Decrypt (size_t idx, const CBLSSecretKey & sk, Object & objectRet, int nVersion) const inline
Definition at line 147 of file bls_ies.h.
References CBLSIESMultiRecipientBlobs::Decrypt(), and SER_NETWORK.
Encrypt() [1/2]
template<typename Object> bool CBLSIESMultiRecipientObjects< Object >::Encrypt (const std::vector< CBLSPublicKey > & recipients, const ObjectVector & _objects, int nVersion) inline
Definition at line 119 of file bls_ies.h.
References CDataStream::begin(), CBLSIESMultiRecipientBlobs::blobs, CDataStream::clear(), CBLSIESMultiRecipientBlobs::Encrypt(), CDataStream::end(), and SER_NETWORK.
Encrypt() [2/2]
template<typename Object> bool CBLSIESMultiRecipientObjects< Object >::Encrypt (size_t idx, const CBLSPublicKey & recipient, const Object & obj, int nVersion) inline
Definition at line 139 of file bls_ies.h.
References CDataStream::begin(), CBLSIESMultiRecipientBlobs::Encrypt(), CDataStream::end(), and SER_NETWORK.
The documentation for this class was generated from the following file:
src/bls/bls_ies.h
Released under the MIT license