Dash Core: llmq::CBatchedSigShares Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CBatchedSigShares Class Reference
#include <quorums_signing_shares.h>
Public Member Functions
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
std::string ToInvString () const
Public Attributes
uint32_t sessionId {(uint32_t)-1}
std::vector< std::pair< uint16_t, CBLSLazySignature > > sigShares
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 130 of file quorums_signing_shares.h.
Member Function Documentation
SerializationOp()
template<typename Stream , typename Operation > void llmq::CBatchedSigShares::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 140 of file quorums_signing_shares.h.
References READWRITE, sessionId, sigShares, and VARINT.
ToInvString()
std::string llmq::CBatchedSigShares::ToInvString () const
Definition at line 93 of file quorums_signing_shares.cpp.
References llmq::CSigSharesInv::Init(), llmq::CSigSharesInv::inv, sigShares, and llmq::CSigSharesInv::ToString().
Member Data Documentation
ADD_SERIALIZE_METHODS
llmq::CBatchedSigShares::ADD_SERIALIZE_METHODS
Definition at line 137 of file quorums_signing_shares.h.
sessionId
uint32_t llmq::CBatchedSigShares::sessionId {(uint32_t)-1}
Definition at line 133 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::ProcessMessageBatchedSigShares(), and SerializationOp().
sigShares
std::vector<std::pair<uint16_t, CBLSLazySignature> > llmq::CBatchedSigShares::sigShares
Definition at line 134 of file quorums_signing_shares.h.
Referenced by llmq::CSigSharesManager::CollectSigSharesToSend(), llmq::CSigSharesManager::PreVerifyBatchedSigShares(), llmq::CSigSharesManager::RebuildSigShare(), SerializationOp(), and ToInvString().
The documentation for this class was generated from the following files:
src/llmq/quorums_signing_shares.h
src/llmq/quorums_signing_shares.cpp
Released under the MIT license