Dash Core: TransactionSignatureChecker Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
TransactionSignatureChecker Class Reference
#include <interpreter.h>
Public Member Functions
TransactionSignatureChecker (const CTransaction *txToIn, unsigned int nInIn, const CAmount &amountIn)
TransactionSignatureChecker (const CTransaction *txToIn, unsigned int nInIn, const CAmount &amountIn, const PrecomputedTransactionData &txdataIn)
bool CheckSig (const std::vector< unsigned char > &scriptSig, const std::vector< unsigned char > &vchPubKey, const CScript &scriptCode, SigVersion sigversion) const override
bool CheckLockTime (const CScriptNum &nLockTime) const override
bool CheckSequence (const CScriptNum &nSequence) const override
Public Member Functions inherited from BaseSignatureChecker
virtual ~BaseSignatureChecker ()
Protected Member Functions
virtual bool VerifySignature (const std::vector< unsigned char > &vchSig, const CPubKey &vchPubKey, const uint256 &sighash) const
Private Attributes
const CTransaction * txTo
unsigned int nIn
const CAmount amount
const PrecomputedTransactionData * txdata
Detailed Description
Definition at line 137 of file interpreter.h.
Constructor & Destructor Documentation
TransactionSignatureChecker() [1/2]
TransactionSignatureChecker::TransactionSignatureChecker (const CTransaction * txToIn, unsigned int nInIn, const CAmount & amountIn) inline
Definition at line 149 of file interpreter.h.
TransactionSignatureChecker() [2/2]
TransactionSignatureChecker::TransactionSignatureChecker (const CTransaction * txToIn, unsigned int nInIn, const CAmount & amountIn, const PrecomputedTransactionData & txdataIn) inline
Definition at line 150 of file interpreter.h.
Member Function Documentation
CheckLockTime()
bool TransactionSignatureChecker::CheckLockTime (const CScriptNum & nLockTime) const override virtual
Reimplemented from BaseSignatureChecker.
Definition at line 1205 of file interpreter.cpp.
References LOCKTIME_THRESHOLD, nIn, CTransaction::nLockTime, CTxIn::SEQUENCE_FINAL, txTo, and CTransaction::vin.
CheckSequence()
bool TransactionSignatureChecker::CheckSequence (const CScriptNum & nSequence) const override virtual
Reimplemented from BaseSignatureChecker.
Definition at line 1241 of file interpreter.cpp.
References nIn, CTransaction::nVersion, CTxIn::SEQUENCE_LOCKTIME_DISABLE_FLAG, CTxIn::SEQUENCE_LOCKTIME_MASK, CTxIn::SEQUENCE_LOCKTIME_TYPE_FLAG, txTo, and CTransaction::vin.
CheckSig()
bool TransactionSignatureChecker::CheckSig (const std::vector< unsigned char > & scriptSig, const std::vector< unsigned char > & vchPubKey, const CScript & scriptCode, SigVersion sigversion) const override virtual
Reimplemented from BaseSignatureChecker.
Definition at line 1184 of file interpreter.cpp.
References amount, CPubKey::IsValid(), nIn, SignatureHash(), txdata, txTo, and VerifySignature().
VerifySignature()
bool TransactionSignatureChecker::VerifySignature (const std::vector< unsigned char > & vchSig, const CPubKey & vchPubKey, const uint256 & sighash) const protected virtual
Reimplemented in CachingTransactionSignatureChecker.
Definition at line 1179 of file interpreter.cpp.
References CPubKey::Verify().
Referenced by CheckSig(), and CachingTransactionSignatureChecker::VerifySignature().
Member Data Documentation
amount
const CAmount TransactionSignatureChecker::amount private
Definition at line 142 of file interpreter.h.
Referenced by CheckSig().
nIn
unsigned int TransactionSignatureChecker::nIn private
Definition at line 141 of file interpreter.h.
Referenced by CheckLockTime(), CheckSequence(), and CheckSig().
txdata
const PrecomputedTransactionData* TransactionSignatureChecker::txdata private
Definition at line 143 of file interpreter.h.
Referenced by CheckSig().
txTo
const CTransaction* TransactionSignatureChecker::txTo private
Definition at line 140 of file interpreter.h.
Referenced by CheckLockTime(), CheckSequence(), and CheckSig().
The documentation for this class was generated from the following files:
src/script/interpreter.h
src/script/interpreter.cpp
Released under the MIT license