Dash Core: BaseSignatureCreator Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
BaseSignatureCreator Class Reference abstract
Virtual base class for signature creators.
#include <sign.h>
Public Member Functions
BaseSignatureCreator (const CKeyStore *keystoreIn)
const CKeyStore & KeyStore () const
virtual ~BaseSignatureCreator ()
virtual const BaseSignatureChecker & Checker () const =0
virtual bool CreateSig (std::vector< unsigned char > &vchSig, const CKeyID &keyid, const CScript &scriptCode) const =0
Create a singular (non-script) signature.
Protected Attributes
const CKeyStore * keystore
Detailed Description
Virtual base class for signature creators.
Definition at line 19 of file sign.h.
Constructor & Destructor Documentation
BaseSignatureCreator()
BaseSignatureCreator::BaseSignatureCreator (const CKeyStore * keystoreIn) inline
Definition at line 24 of file sign.h.
~BaseSignatureCreator()
virtual BaseSignatureCreator::~BaseSignatureCreator () inline virtual
Definition at line 26 of file sign.h.
Member Function Documentation
Checker()
virtual const BaseSignatureChecker& BaseSignatureCreator::Checker () const pure virtual
Implemented in DummySignatureCreator, and TransactionSignatureCreator.
Referenced by ProduceSignature().
CreateSig()
virtual bool BaseSignatureCreator::CreateSig (std::vector< unsigned char > & vchSig, const CKeyID & keyid, const CScript & scriptCode) const pure virtual
Create a singular (non-script) signature.
Implemented in DummySignatureCreator, and TransactionSignatureCreator.
Referenced by Sign1().
KeyStore()
const CKeyStore& BaseSignatureCreator::KeyStore () const inline
Definition at line 25 of file sign.h.
References keystore.
Referenced by SignStep().
Member Data Documentation
keystore
const CKeyStore* BaseSignatureCreator::keystore protected
Definition at line 21 of file sign.h.
Referenced by TransactionSignatureCreator::CreateSig(), and KeyStore().
The documentation for this class was generated from the following file:
src/script/sign.h
Released under the MIT license