Dash Core: CBLSIESEncryptedBlob Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSIESEncryptedBlob Class Reference
#include <bls_ies.h>
Public Member Functions
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
bool Encrypt (const CBLSPublicKey &peerPubKey, const void *data, size_t dataSize)
bool Decrypt (const CBLSSecretKey &secretKey, CDataStream &decryptedDataRet) const
Public Attributes
CBLSPublicKey ephemeralPubKey
unsigned char iv [16]
std::vector< unsigned char > data
bool valid {false}
Detailed Description
Definition at line 11 of file bls_ies.h.
Member Function Documentation
Decrypt()
bool CBLSIESEncryptedBlob::Decrypt (const CBLSSecretKey & secretKey, CDataStream & decryptedDataRet) const
Definition at line 52 of file bls_ies.cpp.
References data, CDataStream::data(), DecryptBlob(), CBLSPublicKey::DHKeyExchange(), ephemeralPubKey, CBLSWrapper< ImplType, _SerSize, C >::GetBuf(), and iv.
Referenced by CBLSIESEncryptedObject< Object >::Decrypt().
Encrypt()
bool CBLSIESEncryptedBlob::Encrypt (const CBLSPublicKey & peerPubKey, const void * data, size_t dataSize)
Definition at line 33 of file bls_ies.cpp.
References data, CBLSPublicKey::DHKeyExchange(), EncryptBlob(), ephemeralPubKey, CBLSWrapper< ImplType, _SerSize, C >::GetBuf(), CBLSSecretKey::GetPublicKey(), GetStrongRandBytes(), iv, and CBLSSecretKey::MakeNewKey().
Referenced by CBLSIESEncryptedObject< Object >::Encrypt().
SerializationOp()
template<typename Stream , typename Operation > ADD_SERIALIZE_METHODS void CBLSIESEncryptedBlob::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 24 of file bls_ies.h.
References data, ephemeralPubKey, FLATDATA, iv, READWRITE, and valid.
Member Data Documentation
data
std::vector<unsigned char> CBLSIESEncryptedBlob::data
Definition at line 16 of file bls_ies.h.
Referenced by Decrypt(), Encrypt(), and SerializationOp().
ephemeralPubKey
CBLSPublicKey CBLSIESEncryptedBlob::ephemeralPubKey
Definition at line 14 of file bls_ies.h.
Referenced by Decrypt(), Encrypt(), and SerializationOp().
iv
unsigned char CBLSIESEncryptedBlob::iv[16]
Definition at line 15 of file bls_ies.h.
Referenced by Decrypt(), Encrypt(), and SerializationOp().
valid
bool CBLSIESEncryptedBlob::valid {false}
Definition at line 18 of file bls_ies.h.
Referenced by SerializationOp().
The documentation for this class was generated from the following files:
src/bls/bls_ies.h
src/bls/bls_ies.cpp
Released under the MIT license