Dash Core: AddressTablePriv Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
AddressTablePriv Class Reference
Public Member Functions
AddressTablePriv (CWallet *_wallet, AddressTableModel *_parent)
void refreshAddressTable ()
void updateEntry (const QString &address, const QString &label, bool isMine, const QString &purpose, int status)
int size ()
AddressTableEntry * index (int idx)
Public Attributes
CWallet * wallet
QList< AddressTableEntry > cachedAddressTable
AddressTableModel * parent
Detailed Description
Definition at line 69 of file addresstablemodel.cpp.
Constructor & Destructor Documentation
AddressTablePriv()
AddressTablePriv::AddressTablePriv (CWallet * _wallet, AddressTableModel * _parent) inline
Definition at line 76 of file addresstablemodel.cpp.
Member Function Documentation
index()
AddressTableEntry* AddressTablePriv::index (int idx) inline
Definition at line 154 of file addresstablemodel.cpp.
References cachedAddressTable.
Referenced by AddressTableModel::index(), AddressTableModel::removeRows(), and AppearanceWidget::updateFontFamily().
refreshAddressTable()
void AddressTablePriv::refreshAddressTable () inline
Definition at line 79 of file addresstablemodel.cpp.
References cachedAddressTable, CWallet::cs_wallet, EncodeDestination(), IsMine(), LOCK, CWallet::mapAddressBook, translateTransactionType(), and wallet.
Referenced by AddressTableModel::AddressTableModel().
size()
int AddressTablePriv::size () inline
Definition at line 149 of file addresstablemodel.cpp.
References cachedAddressTable.
Referenced by AddressTableModel::rowCount().
updateEntry()
void AddressTablePriv::updateEntry (const QString & address, const QString & label, bool isMine, const QString & purpose, int status) inline
Definition at line 102 of file addresstablemodel.cpp.
References cachedAddressTable, CT_DELETED, CT_NEW, CT_UPDATED, AddressTableModel::emitDataChanged(), parent, and translateTransactionType().
Referenced by AddressTableModel::updateEntry().
Member Data Documentation
cachedAddressTable
QList<AddressTableEntry> AddressTablePriv::cachedAddressTable
Definition at line 73 of file addresstablemodel.cpp.
Referenced by index(), refreshAddressTable(), size(), and updateEntry().
parent
AddressTableModel* AddressTablePriv::parent
Definition at line 74 of file addresstablemodel.cpp.
Referenced by updateEntry().
wallet
CWallet* AddressTablePriv::wallet
Definition at line 72 of file addresstablemodel.cpp.
Referenced by refreshAddressTable().
The documentation for this class was generated from the following file:
src/qt/addresstablemodel.cpp
Released under the MIT license