Dash Core: AmountLineEdit Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
AmountLineEdit Class Reference
QLineEdit that uses fixed-point numbers internally and uses our own formatting/parsing functions.
Signals
void valueChanged ()
Public Member Functions
AmountLineEdit (QWidget *parent)
void fixup (const QString &input)
CAmount value (bool *valid_out=0) const
void setValue (const CAmount &value)
void setDisplayUnit (int unit)
QSize minimumSizeHint () const
Protected Member Functions
bool event (QEvent *event)
Private Attributes
AmountValidator * amountValidator
int currentUnit
Detailed Description
QLineEdit that uses fixed-point numbers internally and uses our own formatting/parsing functions.
Definition at line 65 of file bitcoinamountfield.cpp.
Constructor & Destructor Documentation
AmountLineEdit()
AmountLineEdit::AmountLineEdit (QWidget * parent) inline explicit
Definition at line 70 of file bitcoinamountfield.cpp.
References amountValidator, and valueChanged().
Member Function Documentation
event()
bool AmountLineEdit::event (QEvent * event) inline protected
Definition at line 130 of file bitcoinamountfield.cpp.
References fixup().
fixup()
void AmountLineEdit::fixup (const QString & input) inline
Definition at line 80 of file bitcoinamountfield.cpp.
References currentUnit, BitcoinUnits::format(), parse(), and BitcoinUnits::separatorAlways.
Referenced by event().
minimumSizeHint()
QSize AmountLineEdit::minimumSizeHint () const inline
Definition at line 115 of file bitcoinamountfield.cpp.
References BitcoinUnits::DASH, GUIUtil::dashThemeActive(), BitcoinUnits::format(), BitcoinUnits::maxMoney(), and BitcoinUnits::separatorAlways.
setDisplayUnit()
void AmountLineEdit::setDisplayUnit (int unit) inline
Definition at line 101 of file bitcoinamountfield.cpp.
References amountValidator, currentUnit, setValue(), AmountValidator::updateUnit(), and value().
Referenced by BitcoinAmountField::unitChanged().
setValue()
void AmountLineEdit::setValue (const CAmount & value) inline
Definition at line 95 of file bitcoinamountfield.cpp.
References currentUnit, BitcoinUnits::format(), BitcoinUnits::separatorAlways, value(), and valueChanged().
Referenced by setDisplayUnit(), and BitcoinAmountField::setValue().
value()
CAmount AmountLineEdit::value (bool * valid_out = 0) const inline
Definition at line 90 of file bitcoinamountfield.cpp.
References currentUnit, and parse().
Referenced by setDisplayUnit(), setValue(), and BitcoinAmountField::value().
valueChanged
void AmountLineEdit::valueChanged () signal
Referenced by AmountLineEdit(), and setValue().
Member Data Documentation
amountValidator
AmountValidator* AmountLineEdit::amountValidator private
Definition at line 68 of file bitcoinamountfield.cpp.
Referenced by AmountLineEdit(), and setDisplayUnit().
currentUnit
int AmountLineEdit::currentUnit private
Definition at line 127 of file bitcoinamountfield.cpp.
Referenced by fixup(), setDisplayUnit(), setValue(), and value().
The documentation for this class was generated from the following file:
src/qt/bitcoinamountfield.cpp
Released under the MIT license