Dash Core: TransactionView Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
TransactionView Class Reference
Widget showing the transaction list for a wallet, including a filter row.
#include <transactionview.h>
Public Types
enum DateEnum {
All, Today, ThisWeek, ThisMonth,
LastMonth, ThisYear, Range
}
enum ColumnWidths {
STATUS_COLUMN_WIDTH = 30, WATCHONLY_COLUMN_WIDTH = 23, DATE_COLUMN_WIDTH = 120, TYPE_COLUMN_WIDTH = 240,
AMOUNT_MINIMUM_COLUMN_WIDTH = 120, MINIMUM_COLUMN_WIDTH = 23
}
Public Slots
void chooseDate (int idx)
void chooseType (int idx)
void chooseWatchonly (int idx)
void changedAmount ()
void changedSearch ()
void exportClicked ()
void focusTransaction (const QModelIndex &)
void computeSum ()
Compute sum of all selected transactions.
Signals
void doubleClicked (const QModelIndex &)
void message (const QString &title, const QString &message, unsigned int style)
Fired when a message should be reported to the user.
void trxAmount (QString amount)
Send computed sum back to wallet-view.
Public Member Functions
TransactionView (QWidget *parent=0)
void setModel (WalletModel *model)
Private Slots
void contextualMenu (const QPoint &)
void dateRangeChanged ()
void showDetails ()
void showAddressQRCode ()
void copyAddress ()
void editLabel ()
void copyLabel ()
void copyAmount ()
void copyTxID ()
void copyTxHex ()
void copyTxPlainText ()
void openThirdPartyTxUrl (QString url)
void updateWatchOnlyColumn (bool fHaveWatchOnly)
void updatePrivateSendVisibility ()
void abandonTx ()
Private Member Functions
QWidget * createDateRangeWidget ()
void updateCalendarWidgets ()
virtual void resizeEvent (QResizeEvent *event) override
void changeEvent (QEvent *e) override
bool eventFilter (QObject *obj, QEvent *event) override
Private Attributes
WalletModel * model
TransactionFilterProxy * transactionProxyModel
QTableView * transactionView
QComboBox * dateWidget
QComboBox * typeWidget
QComboBox * watchOnlyWidget
QLineEdit * search_widget
QLineEdit * amountWidget
QMenu * contextMenu
QSignalMapper * mapperThirdPartyTxUrls
QFrame * dateRangeWidget
QDateTimeEdit * dateFrom
QDateTimeEdit * dateTo
QAction * abandonAction
GUIUtil::TableViewLastColumnResizingFixer * columnResizingFixer
Detailed Description
Widget showing the transaction list for a wallet, including a filter row.
Using the filter row, the user can view or export a subset of the transactions.
Definition at line 31 of file transactionview.h.
Member Enumeration Documentation
ColumnWidths
enum TransactionView::ColumnWidths
Enumerator
STATUS_COLUMN_WIDTH
WATCHONLY_COLUMN_WIDTH
DATE_COLUMN_WIDTH
TYPE_COLUMN_WIDTH
AMOUNT_MINIMUM_COLUMN_WIDTH
MINIMUM_COLUMN_WIDTH
Definition at line 52 of file transactionview.h.
DateEnum
enum TransactionView::DateEnum
Enumerator
All
Today
ThisWeek
ThisMonth
LastMonth
ThisYear
Range
Definition at line 41 of file transactionview.h.
Constructor & Destructor Documentation
TransactionView()
TransactionView::TransactionView (QWidget * parent = 0) explicit
Definition at line 46 of file transactionview.cpp.
References abandonAction, abandonTx(), All, TransactionFilterProxy::ALL_TYPES, amountWidget, changedAmount(), changedSearch(), chooseDate(), chooseType(), chooseWatchonly(), TransactionFilterProxy::COMMON_TYPES, computeSum(), contextMenu, contextualMenu(), copyAddress(), copyAmount(), copyLabel(), copyTxHex(), copyTxID(), copyTxPlainText(), createDateRangeWidget(), dateWidget, doubleClicked(), editLabel(), TransactionRecord::Generated, GUIUtil::getIcon(), LastMonth, mapperThirdPartyTxUrls, openThirdPartyTxUrl(), TransactionRecord::Other, TransactionRecord::PrivateSend, TransactionRecord::PrivateSendCollateralPayment, TransactionRecord::PrivateSendCreateDenominations, TransactionRecord::PrivateSendDenominate, TransactionRecord::PrivateSendMakeCollaterals, Range, TransactionRecord::RecvFromOther, TransactionRecord::RecvWithAddress, search_widget, TransactionRecord::SendToAddress, TransactionRecord::SendToOther, TransactionRecord::SendToSelf, showAddressQRCode(), showDetails(), STATUS_COLUMN_WIDTH, ThisMonth, ThisWeek, ThisYear, Today, transactionView, TransactionFilterProxy::TYPE(), TYPE_COLUMN_WIDTH, typeWidget, updatePrivateSendVisibility(), TransactionFilterProxy::WatchOnlyFilter_All, TransactionFilterProxy::WatchOnlyFilter_No, TransactionFilterProxy::WatchOnlyFilter_Yes, and watchOnlyWidget.
Member Function Documentation
abandonTx
void TransactionView::abandonTx () private slot
Definition at line 431 of file transactionview.cpp.
References WalletModel::abandonTransaction(), CT_UPDATED, base_blob< BITS >::data, WalletModel::getTransactionTableModel(), model, base_blob< BITS >::SetHex(), transactionView, TransactionTableModel::TxHashRole, and TransactionTableModel::updateTransaction().
Referenced by TransactionView().
changedAmount
void TransactionView::changedAmount () slot
Definition at line 354 of file transactionview.cpp.
References amountWidget, OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), model, BitcoinUnits::parse(), TransactionFilterProxy::setMinAmount(), and transactionProxyModel.
Referenced by TransactionView().
changedSearch
void TransactionView::changedSearch () slot
Definition at line 347 of file transactionview.cpp.
References search_widget, TransactionFilterProxy::setSearchString(), and transactionProxyModel.
Referenced by TransactionView().
changeEvent()
void TransactionView::changeEvent (QEvent * e) override private
Definition at line 675 of file transactionview.cpp.
References updateCalendarWidgets().
chooseDate
void TransactionView::chooseDate (int idx) slot
Definition at line 272 of file transactionview.cpp.
References All, dateFrom, dateRangeChanged(), dateRangeWidget, dateTo, dateWidget, LastMonth, TransactionFilterProxy::MAX_DATE, TransactionFilterProxy::MIN_DATE, PERSISTENCE_DATE_FORMAT, Range, TransactionFilterProxy::setDateRange(), ThisMonth, ThisWeek, ThisYear, Today, and transactionProxyModel.
Referenced by setModel(), and TransactionView().
chooseType
void TransactionView::chooseType (int idx) slot
Definition at line 328 of file transactionview.cpp.
References TransactionFilterProxy::setTypeFilter(), transactionProxyModel, and typeWidget.
Referenced by setModel(), and TransactionView().
chooseWatchonly
void TransactionView::chooseWatchonly (int idx) slot
Definition at line 339 of file transactionview.cpp.
References TransactionFilterProxy::setWatchOnlyFilter(), transactionProxyModel, and watchOnlyWidget.
Referenced by TransactionView().
computeSum
void TransactionView::computeSum () slot
Compute sum of all selected transactions.
Definition at line 556 of file transactionview.cpp.
References TransactionTableModel::AmountRole, BitcoinUnits::formatWithUnit(), OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), GUIUtil::getThemedStyleQString(), TransactionTablePriv::index(), model, BitcoinUnits::separatorAlways, transactionView, trxAmount(), and GUIUtil::TS_ERROR.
Referenced by focusTransaction(), setModel(), and TransactionView().
contextualMenu
void TransactionView::contextualMenu (const QPoint & point) private slot
Definition at line 411 of file transactionview.cpp.
References abandonAction, contextMenu, TransactionTablePriv::index(), model, base_blob< BITS >::SetHex(), WalletModel::transactionCanBeAbandoned(), transactionView, and TransactionTableModel::TxHashRole.
Referenced by TransactionView().
copyAddress
void TransactionView::copyAddress () private slot
Definition at line 449 of file transactionview.cpp.
References TransactionTableModel::AddressRole, GUIUtil::copyEntryData(), and transactionView.
Referenced by TransactionView().
copyAmount
void TransactionView::copyAmount () private slot
Definition at line 459 of file transactionview.cpp.
References GUIUtil::copyEntryData(), TransactionTableModel::FormattedAmountRole, and transactionView.
Referenced by TransactionView().
copyLabel
void TransactionView::copyLabel () private slot
Definition at line 454 of file transactionview.cpp.
References GUIUtil::copyEntryData(), TransactionTableModel::LabelRole, and transactionView.
Referenced by TransactionView().
copyTxHex
void TransactionView::copyTxHex () private slot
Definition at line 469 of file transactionview.cpp.
References GUIUtil::copyEntryData(), transactionView, and TransactionTableModel::TxHexRole.
Referenced by TransactionView().
copyTxID
void TransactionView::copyTxID () private slot
Definition at line 464 of file transactionview.cpp.
References GUIUtil::copyEntryData(), transactionView, and TransactionTableModel::TxIDRole.
Referenced by TransactionView().
copyTxPlainText
void TransactionView::copyTxPlainText () private slot
Definition at line 474 of file transactionview.cpp.
References GUIUtil::copyEntryData(), transactionView, and TransactionTableModel::TxPlainTextRole.
Referenced by TransactionView().
createDateRangeWidget()
QWidget * TransactionView::createDateRangeWidget () private
Definition at line 581 of file transactionview.cpp.
References dateFrom, dateRangeChanged(), dateRangeWidget, dateTo, PERSISTENCE_DATE_FORMAT, and updateCalendarWidgets().
Referenced by TransactionView().
dateRangeChanged
void TransactionView::dateRangeChanged () private slot
Definition at line 640 of file transactionview.cpp.
References dateFrom, dateTo, PERSISTENCE_DATE_FORMAT, TransactionFilterProxy::setDateRange(), and transactionProxyModel.
Referenced by chooseDate(), and createDateRangeWidget().
doubleClicked
void TransactionView::doubleClicked (const QModelIndex &) signal
Referenced by TransactionView().
editLabel
void TransactionView::editLabel () private slot
Definition at line 479 of file transactionview.cpp.
References TransactionTableModel::AddressRole, AddressTableModel::data(), EditAddressDialog::EditReceivingAddress, EditAddressDialog::EditSendingAddress, WalletModel::getAddressTableModel(), AddressTableModel::index(), EditAddressDialog::loadRow(), AddressTableModel::lookupAddress(), model, EditAddressDialog::NewSendingAddress, AddressTableModel::Receive, EditAddressDialog::setAddress(), EditAddressDialog::setModel(), transactionView, and AddressTableModel::TypeRole.
Referenced by TransactionView().
eventFilter()
bool TransactionView::eventFilter (QObject * obj, QEvent * event) override private
Definition at line 684 of file transactionview.cpp.
References GUIUtil::copyEntryData(), search_widget, transactionView, and TransactionTableModel::TxPlainTextRole.
exportClicked
void TransactionView::exportClicked () slot
Definition at line 373 of file transactionview.cpp.
References CSVModelWriter::addColumn(), TransactionTableModel::AddressRole, TransactionTableModel::ConfirmedRole, TransactionTableModel::DateRole, TransactionTableModel::FormattedAmountRole, BitcoinUnits::getAmountColumnTitle(), OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), GUIUtil::getSaveFileName(), WalletModel::haveWatchOnly(), TransactionTableModel::LabelRole, message(), model, CClientUIInterface::MSG_ERROR, CClientUIInterface::MSG_INFORMATION, CSVModelWriter::setModel(), transactionProxyModel, TransactionTableModel::TxIDRole, TransactionTableModel::Type, TransactionTableModel::Watchonly, and CSVModelWriter::write().
focusTransaction
void TransactionView::focusTransaction (const QModelIndex & idx) slot
Definition at line 655 of file transactionview.cpp.
References computeSum(), transactionProxyModel, and transactionView.
message
void TransactionView::message (const QString & title, const QString & message, unsigned int style) signal
Fired when a message should be reported to the user.
Referenced by exportClicked().
openThirdPartyTxUrl
void TransactionView::openThirdPartyTxUrl (QString url) private slot
Definition at line 572 of file transactionview.cpp.
References transactionView, and TransactionTableModel::TxHashRole.
Referenced by TransactionView().
resizeEvent()
void TransactionView::resizeEvent (QResizeEvent * event) override private virtual
Definition at line 669 of file transactionview.cpp.
References columnResizingFixer, GUIUtil::TableViewLastColumnResizingFixer::stretchColumnWidth(), and TransactionTableModel::ToAddress.
setModel()
void TransactionView::setModel (WalletModel * model)
Definition at line 205 of file transactionview.cpp.
References TransactionTableModel::Amount, AMOUNT_MINIMUM_COLUMN_WIDTH, chooseDate(), chooseType(), columnResizingFixer, computeSum(), contextMenu, TransactionTableModel::Date, DATE_COLUMN_WIDTH, WalletModel::getOptionsModel(), OptionsModel::getThirdPartyTxUrls(), WalletModel::getTransactionTableModel(), WalletModel::haveWatchOnly(), mapperThirdPartyTxUrls, MINIMUM_COLUMN_WIDTH, model, TransactionTableModel::Status, STATUS_COLUMN_WIDTH, transactionProxyModel, transactionView, TransactionTableModel::Type, TYPE_COLUMN_WIDTH, updatePrivateSendVisibility(), updateWatchOnlyColumn(), TransactionTableModel::Watchonly, and WATCHONLY_COLUMN_WIDTH.
Referenced by WalletView::setWalletModel().
showAddressQRCode
void TransactionView::showAddressQRCode () private slot
Definition at line 538 of file transactionview.cpp.
References TransactionTableModel::AddressRole, GUIUtil::getEntryData(), model, QRDialog::setInfo(), QRDialog::setModel(), and transactionView.
Referenced by TransactionView().
showDetails
void TransactionView::showDetails () private slot
Definition at line 525 of file transactionview.cpp.
References transactionView.
Referenced by TransactionView().
trxAmount
void TransactionView::trxAmount (QString amount) signal
Send computed sum back to wallet-view.
Referenced by computeSum().
updateCalendarWidgets()
void TransactionView::updateCalendarWidgets () private
Definition at line 626 of file transactionview.cpp.
References dateFrom, dateTo, GUIUtil::DEFAULT, tinyformat::format(), and GUIUtil::getThemedQColor().
Referenced by changeEvent(), and createDateRangeWidget().
updatePrivateSendVisibility
void TransactionView::updatePrivateSendVisibility () private slot
Definition at line 713 of file transactionview.cpp.
References CPrivateSendClientManager::fEnablePrivateSend, privateSendClient, and typeWidget.
Referenced by setModel(), and TransactionView().
updateWatchOnlyColumn
void TransactionView::updateWatchOnlyColumn (bool fHaveWatchOnly) private slot
Definition at line 707 of file transactionview.cpp.
References transactionView, TransactionTableModel::Watchonly, and watchOnlyWidget.
Referenced by setModel().
Member Data Documentation
abandonAction
QAction* TransactionView::abandonAction private
Definition at line 77 of file transactionview.h.
Referenced by contextualMenu(), and TransactionView().
amountWidget
QLineEdit* TransactionView::amountWidget private
Definition at line 69 of file transactionview.h.
Referenced by changedAmount(), and TransactionView().
columnResizingFixer
GUIUtil::TableViewLastColumnResizingFixer* TransactionView::columnResizingFixer private
Definition at line 82 of file transactionview.h.
Referenced by resizeEvent(), and setModel().
contextMenu
QMenu* TransactionView::contextMenu private
Definition at line 71 of file transactionview.h.
Referenced by contextualMenu(), setModel(), and TransactionView().
dateFrom
QDateTimeEdit* TransactionView::dateFrom private
Definition at line 75 of file transactionview.h.
Referenced by chooseDate(), createDateRangeWidget(), dateRangeChanged(), and updateCalendarWidgets().
dateRangeWidget
QFrame* TransactionView::dateRangeWidget private
Definition at line 74 of file transactionview.h.
Referenced by chooseDate(), and createDateRangeWidget().
dateTo
QDateTimeEdit* TransactionView::dateTo private
Definition at line 76 of file transactionview.h.
Referenced by chooseDate(), createDateRangeWidget(), dateRangeChanged(), and updateCalendarWidgets().
dateWidget
QComboBox* TransactionView::dateWidget private
Definition at line 65 of file transactionview.h.
Referenced by chooseDate(), and TransactionView().
mapperThirdPartyTxUrls
QSignalMapper* TransactionView::mapperThirdPartyTxUrls private
Definition at line 72 of file transactionview.h.
Referenced by setModel(), and TransactionView().
model
WalletModel* TransactionView::model private
Definition at line 62 of file transactionview.h.
Referenced by abandonTx(), changedAmount(), computeSum(), contextualMenu(), editLabel(), exportClicked(), setModel(), and showAddressQRCode().
search_widget
QLineEdit* TransactionView::search_widget private
Definition at line 68 of file transactionview.h.
Referenced by changedSearch(), eventFilter(), and TransactionView().
transactionProxyModel
TransactionFilterProxy* TransactionView::transactionProxyModel private
Definition at line 63 of file transactionview.h.
Referenced by changedAmount(), changedSearch(), chooseDate(), chooseType(), chooseWatchonly(), dateRangeChanged(), exportClicked(), focusTransaction(), and setModel().
transactionView
QTableView* TransactionView::transactionView private
Definition at line 64 of file transactionview.h.
Referenced by abandonTx(), computeSum(), contextualMenu(), copyAddress(), copyAmount(), copyLabel(), copyTxHex(), copyTxID(), copyTxPlainText(), editLabel(), eventFilter(), focusTransaction(), openThirdPartyTxUrl(), setModel(), showAddressQRCode(), showDetails(), TransactionView(), and updateWatchOnlyColumn().
typeWidget
QComboBox* TransactionView::typeWidget private
Definition at line 66 of file transactionview.h.
Referenced by chooseType(), TransactionView(), and updatePrivateSendVisibility().
watchOnlyWidget
QComboBox* TransactionView::watchOnlyWidget private
Definition at line 67 of file transactionview.h.
Referenced by chooseWatchonly(), TransactionView(), and updateWatchOnlyColumn().
The documentation for this class was generated from the following files:
src/qt/transactionview.h
src/qt/transactionview.cpp
Released under the MIT license