Dash Core: CActiveMasternode Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CActiveMasternode Class Reference
#include <activemasternode.h>
Public Types
enum masternode_type_enum_t { MASTERNODE_UNKNOWN = 0, MASTERNODE_REMOTE = 1 }
Public Member Functions
CActiveMasternode ()
void ManageState (CConnman &connman)
Manage state of active Masternode.
std::string GetStateString () const
std::string GetStatus () const
std::string GetTypeString () const
bool UpdateSentinelPing (int version)
Public Attributes
CPubKey pubKeyMasternode
CKey keyMasternode
COutPoint outpoint
CService service
int nState
std::string strNotCapableReason
Private Member Functions
bool SendMasternodePing (CConnman &connman)
Ping Masternode.
void ManageStateInitial (CConnman &connman)
void ManageStateRemote ()
Private Attributes
CCriticalSection cs
masternode_type_enum_t eType
bool fPingerEnabled
int64_t nSentinelPingTime
uint32_t nSentinelVersion
Detailed Description
Definition at line 24 of file activemasternode.h.
Member Enumeration Documentation
masternode_type_enum_t
enum CActiveMasternode::masternode_type_enum_t
Enumerator
MASTERNODE_UNKNOWN
MASTERNODE_REMOTE
Definition at line 27 of file activemasternode.h.
Constructor & Destructor Documentation
CActiveMasternode()
CActiveMasternode::CActiveMasternode () inline
Definition at line 60 of file activemasternode.h.
Member Function Documentation
GetStateString()
std::string CActiveMasternode::GetStateString () const
Definition at line 45 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_INITIAL, ACTIVE_MASTERNODE_INPUT_TOO_NEW, ACTIVE_MASTERNODE_NOT_CAPABLE, ACTIVE_MASTERNODE_STARTED, ACTIVE_MASTERNODE_SYNC_IN_PROCESS, and nState.
Referenced by ManageState(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
GetStatus()
std::string CActiveMasternode::GetStatus () const
Definition at line 57 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_INITIAL, ACTIVE_MASTERNODE_INPUT_TOO_NEW, ACTIVE_MASTERNODE_NOT_CAPABLE, ACTIVE_MASTERNODE_STARTED, ACTIVE_MASTERNODE_SYNC_IN_PROCESS, nState, Params(), strNotCapableReason, and strprintf.
Referenced by ManageState(), ManageStateInitial(), ManageStateRemote(), and masternode().
GetTypeString()
std::string CActiveMasternode::GetTypeString () const
Definition at line 69 of file activemasternode.cpp.
References eType, and MASTERNODE_REMOTE.
Referenced by ManageState(), ManageStateInitial(), and ManageStateRemote().
ManageState()
void CActiveMasternode::ManageState (CConnman & connman)
Manage state of active Masternode.
Definition at line 14 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_INITIAL, ACTIVE_MASTERNODE_SYNC_IN_PROCESS, eType, fMasterNode, fPingerEnabled, GetStateString(), GetStatus(), GetTypeString(), CMasternodeSync::IsBlockchainSynced(), LogPrint(), LogPrintf, ManageStateInitial(), ManageStateRemote(), MASTERNODE_REMOTE, MASTERNODE_UNKNOWN, masternodeSync, nState, Params(), CBaseChainParams::REGTEST, and SendMasternodePing().
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeSync::SwitchToNextAsset(), ThreadCheckPrivateSend(), and CMasternode::UpdateFromNewBroadcast().
ManageStateInitial()
void CActiveMasternode::ManageStateInitial (CConnman & connman) private
Definition at line 128 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_NOT_CAPABLE, CNode::addr, CConnman::AllNodes, CConnman::ConnectNode(), eType, fListen, CConnman::ForEachNodeContinueIf(), fPingerEnabled, CChainParams::GetDefaultPort(), GetLocal(), CService::GetPort(), GetStateString(), GetStatus(), GetTypeString(), CNetAddr::IsIPv4(), CMasternode::IsValidNetAddr(), LogPrint(), LogPrintf, CBaseChainParams::MAIN, MASTERNODE_REMOTE, NODE_NETWORK, nState, Params(), service, strNotCapableReason, strprintf, and CService::ToString().
Referenced by ManageState().
ManageStateRemote()
void CActiveMasternode::ManageStateRemote () private
Definition at line 198 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_NOT_CAPABLE, ACTIVE_MASTERNODE_STARTED, masternode_info_t::addr, CMasternodeMan::CheckMasternode(), fPingerEnabled, CPubKey::GetID(), CMasternodeMan::GetMasternodeInfo(), GetStateString(), GetStatus(), GetTypeString(), CMasternode::IsValidStateForAutoStart(), LogPrint(), LogPrintf, mnodeman, masternode_info_t::nActiveState, masternode_info_t::nProtocolVersion, nState, outpoint, CTxIn::prevout, PROTOCOL_VERSION, pubKeyMasternode, service, CMasternode::StateToString(), strNotCapableReason, strprintf, base_blob< BITS >::ToString(), and masternode_info_t::vin.
Referenced by ManageState().
SendMasternodePing()
bool CActiveMasternode::SendMasternodePing (CConnman & connman) private
Ping Masternode.
Definition at line 83 of file activemasternode.cpp.
References ACTIVE_MASTERNODE_NOT_CAPABLE, fPingerEnabled, CMasternodePing::fSentinelIsCurrent, GetAdjustedTime(), GetStateString(), CMasternodeMan::Has(), CMasternodeMan::IsMasternodePingedWithin(), keyMasternode, LogPrint(), LogPrintf, MASTERNODE_MIN_MNP_SECONDS, MASTERNODE_WATCHDOG_MAX_SECONDS, mnodeman, nSentinelPingTime, CMasternodePing::nSentinelVersion, nSentinelVersion, nState, outpoint, pubKeyMasternode, CMasternodePing::Relay(), CMasternodeMan::SetMasternodeLastPing(), CMasternodePing::Sign(), CMasternodePing::sigTime, strNotCapableReason, and COutPoint::ToStringShort().
Referenced by ManageState().
UpdateSentinelPing()
bool CActiveMasternode::UpdateSentinelPing (int version)
Definition at line 120 of file activemasternode.cpp.
References GetAdjustedTime(), nSentinelPingTime, and nSentinelVersion.
Referenced by sentinelping().
Member Data Documentation
cs
CCriticalSection CActiveMasternode::cs mutable private
Definition at line 34 of file activemasternode.h.
eType
masternode_type_enum_t CActiveMasternode::eType private
Definition at line 36 of file activemasternode.h.
Referenced by GetTypeString(), ManageState(), and ManageStateInitial().
fPingerEnabled
bool CActiveMasternode::fPingerEnabled private
Definition at line 38 of file activemasternode.h.
Referenced by ManageState(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
keyMasternode
CKey CActiveMasternode::keyMasternode
Definition at line 50 of file activemasternode.h.
Referenced by AppInit2(), gobject(), CMasternodeMan::ProcessVerifyReply(), SendMasternodePing(), CMasternodeMan::SendVerifyReply(), CMasternodePaymentVote::Sign(), CDarksendQueue::Sign(), CTxLockVote::Sign(), and CDarksendBroadcastTx::Sign().
nSentinelPingTime
int64_t CActiveMasternode::nSentinelPingTime private
Definition at line 44 of file activemasternode.h.
Referenced by SendMasternodePing(), and UpdateSentinelPing().
nSentinelVersion
uint32_t CActiveMasternode::nSentinelVersion private
Definition at line 45 of file activemasternode.h.
Referenced by SendMasternodePing(), and UpdateSentinelPing().
nState
int CActiveMasternode::nState
Definition at line 56 of file activemasternode.h.
Referenced by GetStateString(), GetStatus(), ManageState(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
outpoint
COutPoint CActiveMasternode::outpoint
Definition at line 53 of file activemasternode.h.
Referenced by CPrivateSendServer::CheckForCompleteQueue(), CMasternodeBroadcast::CheckOutpoint(), CPrivateSendServer::CommitFinalTransaction(), CPrivateSendServer::CreateNewSession(), CMasternodeMan::DoFullVerificationStep(), gobject(), ManageStateRemote(), masternode(), CMasternodePayments::ProcessBlock(), CPrivateSendServer::ProcessMessage(), CMasternodeMan::ProcessVerifyReply(), SendMasternodePing(), and CInstantSend::Vote().
pubKeyMasternode
CPubKey CActiveMasternode::pubKeyMasternode
Definition at line 49 of file activemasternode.h.
Referenced by AppInit2(), CMasternode::Check(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), gobject(), ManageStateRemote(), CMasternodeMan::ProcessVerifyReply(), SendMasternodePing(), CMasternodeMan::SendVerifyReply(), CMasternodePaymentVote::Sign(), CDarksendQueue::Sign(), CTxLockVote::Sign(), CDarksendBroadcastTx::Sign(), CMasternodeBroadcast::Update(), and CMasternode::UpdateFromNewBroadcast().
service
CService CActiveMasternode::service
Definition at line 54 of file activemasternode.h.
Referenced by ManageStateInitial(), ManageStateRemote(), masternode(), and CMasternodeMan::SendVerifyReply().
strNotCapableReason
std::string CActiveMasternode::strNotCapableReason
Definition at line 57 of file activemasternode.h.
Referenced by GetStatus(), ManageStateInitial(), ManageStateRemote(), and SendMasternodePing().
The documentation for this class was generated from the following files:
src/activemasternode.h
src/activemasternode.cpp
Released under the MIT license