Dash Core: BanTableModel Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
BanTableModel Class Reference
Qt model providing information about connected peers, similar to the "getpeerinfo" RPC call.
#include <bantablemodel.h>
Public Types
enum ColumnIndex { Address = 0, Bantime = 1 }
Public Slots
void refresh ()
Public Member Functions
BanTableModel (ClientModel *parent=0)
~BanTableModel ()
void startAutoRefresh ()
void stopAutoRefresh ()
Methods overridden from QAbstractTableModel
int rowCount (const QModelIndex &parent) const
int columnCount (const QModelIndex &parent) const
QVariant data (const QModelIndex &index, int role) const
QVariant headerData (int section, Qt::Orientation orientation, int role) const
QModelIndex index (int row, int column, const QModelIndex &parent) const
Qt::ItemFlags flags (const QModelIndex &index) const
void sort (int column, Qt::SortOrder order)
bool shouldShow ()
Private Attributes
ClientModel * clientModel
QStringList columns
std::unique_ptr< BanTablePriv > priv
Detailed Description
Qt model providing information about connected peers, similar to the "getpeerinfo" RPC call.
Used by the rpc console UI.
Definition at line 37 of file bantablemodel.h.
Member Enumeration Documentation
ColumnIndex
enum BanTableModel::ColumnIndex
Enumerator
Address
Bantime
Definition at line 47 of file bantablemodel.h.
Constructor & Destructor Documentation
BanTableModel()
BanTableModel::BanTableModel (ClientModel * parent = 0) explicit
Definition at line 85 of file bantablemodel.cpp.
References columns, priv, and refresh().
~BanTableModel()
BanTableModel::~BanTableModel ()
Definition at line 98 of file bantablemodel.cpp.
Member Function Documentation
columnCount()
int BanTableModel::columnCount (const QModelIndex & parent) const
Definition at line 109 of file bantablemodel.cpp.
References columns.
data()
QVariant BanTableModel::data (const QModelIndex & index, int role) const
Definition at line 115 of file bantablemodel.cpp.
References Address, CCombinedBan::banEntry, Bantime, index(), CBanEntry::nBanUntil, CCombinedBan::subnet, and CSubNet::ToString().
Referenced by index().
flags()
Qt::ItemFlags BanTableModel::flags (const QModelIndex & index) const
Definition at line 149 of file bantablemodel.cpp.
References index().
headerData()
QVariant BanTableModel::headerData (int section, Qt::Orientation orientation, int role) const
Definition at line 137 of file bantablemodel.cpp.
References columns.
index()
QModelIndex BanTableModel::index (int row, int column, const QModelIndex & parent) const
Definition at line 158 of file bantablemodel.cpp.
References data(), and priv.
Referenced by data(), and flags().
refresh
void BanTableModel::refresh () slot
Definition at line 168 of file bantablemodel.cpp.
References priv.
Referenced by RPCConsole::banSelectedNode(), BanTableModel(), sort(), RPCConsole::unbanSelectedNode(), and ClientModel::updateBanlist().
rowCount()
int BanTableModel::rowCount (const QModelIndex & parent) const
Definition at line 103 of file bantablemodel.cpp.
References priv.
shouldShow()
bool BanTableModel::shouldShow ()
Definition at line 182 of file bantablemodel.cpp.
References priv.
Referenced by RPCConsole::showOrHideBanTableIfRequired().
sort()
void BanTableModel::sort (int column, Qt::SortOrder order)
Definition at line 175 of file bantablemodel.cpp.
References priv, and refresh().
startAutoRefresh()
void BanTableModel::startAutoRefresh ()
stopAutoRefresh()
void BanTableModel::stopAutoRefresh ()
Member Data Documentation
clientModel
ClientModel* BanTableModel::clientModel private
Definition at line 68 of file bantablemodel.h.
columns
QStringList BanTableModel::columns private
Definition at line 69 of file bantablemodel.h.
Referenced by BanTableModel(), columnCount(), and headerData().
priv
std::unique_ptr<BanTablePriv> BanTableModel::priv private
Definition at line 70 of file bantablemodel.h.
Referenced by BanTableModel(), index(), refresh(), rowCount(), shouldShow(), and sort().
The documentation for this class was generated from the following files:
src/qt/bantablemodel.h
src/qt/bantablemodel.cpp
Released under the MIT license