Dash Core: CSHA512 Class Reference
CSHA512 Class Reference
#include <sha512.h>
Public Member Functions
CSHA512 ()
CSHA512 & Write (const unsigned char *data, size_t len)
void Finalize (unsigned char hash[OUTPUT_SIZE])
CSHA512 & Reset ()
Static Public Attributes
static const size_t OUTPUT_SIZE = 64
Private Attributes
uint64_t s [8]
unsigned char buf [128]
size_t bytes
Detailed Description
A hasher class for SHA-512.
Definition at line 12 of file sha512.h.
Constructor & Destructor Documentation
CSHA512()
CSHA512::CSHA512 ()
Definition at line 154 of file sha512.cpp.
Member Function Documentation
Finalize()
void CSHA512::Finalize (unsigned char hash[OUTPUT_SIZE])
Definition at line 185 of file sha512.cpp.
Referenced by CHMAC_SHA512::CHMAC_SHA512(), and CHMAC_SHA512::Finalize().
Reset()
CSHA512 & CSHA512::Reset ()
Definition at line 202 of file sha512.cpp.
Write()
CSHA512 & CSHA512::Write (const unsigned char * data, size_t len)
Definition at line 159 of file sha512.cpp.
Referenced by CHMAC_SHA512::CHMAC_SHA512(), Finalize(), CHMAC_SHA512::Finalize(), and CHMAC_SHA512::Write().
Member Data Documentation
buf
unsigned char CSHA512::buf[128] private
Definition at line 16 of file sha512.h.
Referenced by Write().
bytes
size_t CSHA512::bytes private
Definition at line 17 of file sha512.h.
Referenced by Finalize(), Reset(), and Write().
OUTPUT_SIZE
const size_t CSHA512::OUTPUT_SIZE = 64 static
Definition at line 20 of file sha512.h.
s
uint64_t CSHA512::s[8] private
Definition at line 15 of file sha512.h.
Referenced by CSHA512(), Finalize(), Reset(), and Write().
The documentation for this class was generated from the following files:
src/crypto/sha512.h
src/crypto/sha512.cpp