Dash Core: CMasternodeBlockPayees Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodeBlockPayees Class Reference
#include <masternode-payments.h>
Public Member Functions
CMasternodeBlockPayees ()
CMasternodeBlockPayees (int nBlockHeightIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
void AddPayee (const CMasternodePaymentVote &vote)
bool GetBestPayee (CScript &payeeRet)
bool HasPayeeWithVotes (const CScript &payeeIn, int nVotesReq)
bool IsTransactionValid (const CTransaction &txNew)
std::string GetRequiredPaymentsString ()
Public Attributes
int nBlockHeight
std::vector< CMasternodePayee > vecPayees
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 76 of file masternode-payments.h.
Constructor & Destructor Documentation
CMasternodeBlockPayees() [1/2]
CMasternodeBlockPayees::CMasternodeBlockPayees () inline
Definition at line 82 of file masternode-payments.h.
CMasternodeBlockPayees() [2/2]
CMasternodeBlockPayees::CMasternodeBlockPayees (int nBlockHeightIn) inline
Definition at line 86 of file masternode-payments.h.
Member Function Documentation
AddPayee()
void CMasternodeBlockPayees::AddPayee (const CMasternodePaymentVote & vote)
Definition at line 495 of file masternode-payments.cpp.
References CMasternodePayee::AddVoteHash(), cs_vecPayees, CMasternodePaymentVote::GetHash(), CMasternodePayee::GetPayee(), LOCK, CMasternodePaymentVote::payee, and vecPayees.
GetBestPayee()
bool CMasternodeBlockPayees::GetBestPayee (CScript & payeeRet)
Definition at line 509 of file masternode-payments.cpp.
References cs_vecPayees, CMasternodePayee::GetPayee(), CMasternodePayee::GetVoteCount(), LOCK, LogPrint(), and vecPayees.
GetRequiredPaymentsString()
std::string CMasternodeBlockPayees::GetRequiredPaymentsString ()
Definition at line 588 of file masternode-payments.cpp.
References cs_vecPayees, ExtractDestination(), CMasternodePayee::GetPayee(), CMasternodePayee::GetVoteCount(), LOCK, and vecPayees.
HasPayeeWithVotes()
bool CMasternodeBlockPayees::HasPayeeWithVotes (const CScript & payeeIn, int nVotesReq)
Definition at line 529 of file masternode-payments.cpp.
References cs_vecPayees, CMasternodePayee::GetPayee(), CMasternodePayee::GetVoteCount(), LOCK, LogPrint(), and vecPayees.
IsTransactionValid()
bool CMasternodeBlockPayees::IsTransactionValid (const CTransaction & txNew)
Definition at line 543 of file masternode-payments.cpp.
References COIN, cs_vecPayees, ExtractDestination(), GetMasternodePayment(), CMasternodePayee::GetPayee(), CTransaction::GetValueOut(), CMasternodePayee::GetVoteCount(), LOCK, LogPrint(), LogPrintf, MNPAYMENTS_SIGNATURES_REQUIRED, nBlockHeight, CTxOut::nValue, CTxOut::scriptPubKey, vecPayees, and CTransaction::vout.
SerializationOp()
template<typename Stream , typename Operation > void CMasternodeBlockPayees::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 94 of file masternode-payments.h.
References nBlockHeight, READWRITE, and vecPayees.
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodeBlockPayees::ADD_SERIALIZE_METHODS
Definition at line 91 of file masternode-payments.h.
nBlockHeight
int CMasternodeBlockPayees::nBlockHeight
Definition at line 79 of file masternode-payments.h.
Referenced by IsTransactionValid(), and SerializationOp().
vecPayees
std::vector<CMasternodePayee> CMasternodeBlockPayees::vecPayees
Definition at line 80 of file masternode-payments.h.
Referenced by AddPayee(), GetBestPayee(), GetRequiredPaymentsString(), HasPayeeWithVotes(), IsTransactionValid(), and SerializationOp().
The documentation for this class was generated from the following files:
src/masternode-payments.h
src/masternode-payments.cpp
Released under the MIT license