Dash Core: CBLSWorkerCache Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSWorkerCache Class Reference
#include <bls_worker.h>
Public Member Functions
CBLSWorkerCache (CBLSWorker &_worker)
BLSVerificationVectorPtr BuildQuorumVerificationVector (const uint256 &cacheKey, const std::vector< BLSVerificationVectorPtr > &vvecs)
CBLSSecretKey AggregateSecretKeys (const uint256 &cacheKey, const BLSSecretKeyVector &skShares)
CBLSPublicKey BuildPubKeyShare (const uint256 &cacheKey, const BLSVerificationVectorPtr &vvec, const CBLSId &id)
Private Member Functions
template<typename T , typename Builder >
T GetOrBuild (const uint256 &cacheKey, std::map< uint256, std::shared_future< T > > &cache, Builder &&builder)
Private Attributes
CBLSWorker & worker
std::mutex cacheCs
std::map< uint256, std::shared_future< BLSVerificationVectorPtr > > vvecCache
std::map< uint256, std::shared_future< CBLSSecretKey > > secretKeyShareCache
std::map< uint256, std::shared_future< CBLSPublicKey > > publicKeyShareCache
Detailed Description
Definition at line 150 of file bls_worker.h.
Constructor & Destructor Documentation
CBLSWorkerCache()
CBLSWorkerCache::CBLSWorkerCache (CBLSWorker & _worker) inline explicit
Definition at line 161 of file bls_worker.h.
Member Function Documentation
AggregateSecretKeys()
CBLSSecretKey CBLSWorkerCache::AggregateSecretKeys (const uint256 & cacheKey, const BLSSecretKeyVector & skShares) inline
Definition at line 170 of file bls_worker.h.
References CBLSWorker::AggregateSecretKeys(), GetOrBuild(), secretKeyShareCache, and worker.
Referenced by llmq::CDKGSession::SendCommitment().
BuildPubKeyShare()
CBLSPublicKey CBLSWorkerCache::BuildPubKeyShare (const uint256 & cacheKey, const BLSVerificationVectorPtr & vvec, const CBLSId & id) inline
Definition at line 176 of file bls_worker.h.
References CBLSWorker::BuildPubKeyShare(), GetOrBuild(), publicKeyShareCache, and worker.
Referenced by llmq::CQuorum::GetPubKeyShare(), and llmq::CDKGSession::ReceiveMessage().
BuildQuorumVerificationVector()
BLSVerificationVectorPtr CBLSWorkerCache::BuildQuorumVerificationVector (const uint256 & cacheKey, const std::vector< BLSVerificationVectorPtr > & vvecs) inline
Definition at line 164 of file bls_worker.h.
References CBLSWorker::BuildQuorumVerificationVector(), GetOrBuild(), vvecCache, and worker.
Referenced by llmq::CDKGSession::ReceiveMessage(), and llmq::CDKGSession::SendCommitment().
GetOrBuild()
template<typename T , typename Builder > T CBLSWorkerCache::GetOrBuild (const uint256 & cacheKey, std::map< uint256, std::shared_future< T > > & cache, Builder && builder) inline private
Definition at line 185 of file bls_worker.h.
References cacheCs.
Referenced by AggregateSecretKeys(), BuildPubKeyShare(), and BuildQuorumVerificationVector().
Member Data Documentation
cacheCs
std::mutex CBLSWorkerCache::cacheCs private
Definition at line 155 of file bls_worker.h.
Referenced by GetOrBuild().
publicKeyShareCache
std::map<uint256, std::shared_future<CBLSPublicKey> > CBLSWorkerCache::publicKeyShareCache private
Definition at line 158 of file bls_worker.h.
Referenced by BuildPubKeyShare().
secretKeyShareCache
std::map<uint256, std::shared_future<CBLSSecretKey> > CBLSWorkerCache::secretKeyShareCache private
Definition at line 157 of file bls_worker.h.
Referenced by AggregateSecretKeys().
vvecCache
std::map<uint256, std::shared_future<BLSVerificationVectorPtr> > CBLSWorkerCache::vvecCache private
Definition at line 156 of file bls_worker.h.
Referenced by BuildQuorumVerificationVector().
worker
CBLSWorker& CBLSWorkerCache::worker private
Definition at line 153 of file bls_worker.h.
Referenced by AggregateSecretKeys(), BuildPubKeyShare(), and BuildQuorumVerificationVector().
The documentation for this class was generated from the following file:
src/bls/bls_worker.h
Released under the MIT license