Dash Core: llmq::CFinalCommitment Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CFinalCommitment Class Reference
#include <quorums_commitment.h>
Public Member Functions
CFinalCommitment ()
CFinalCommitment (const Consensus::LLMQParams &params, const uint256 &_quorumHash)
int CountSigners () const
int CountValidMembers () const
bool Verify (const std::vector< CDeterministicMNCPtr > &members, bool checkSigs) const
bool VerifyNull () const
bool VerifySizes (const Consensus::LLMQParams &params) const
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
bool IsNull () const
void ToJson (UniValue &obj) const
Public Attributes
uint16_t nVersion {CURRENT_VERSION}
Consensus::LLMQType llmqType {Consensus::LLMQ_NONE}
uint256 quorumHash
std::vector< bool > signers
std::vector< bool > validMembers
CBLSPublicKey quorumPublicKey
uint256 quorumVvecHash
CBLSSignature quorumSig
CBLSSignature membersSig
Static Public Attributes
static const uint16_t CURRENT_VERSION = 1
Detailed Description
Definition at line 24 of file quorums_commitment.h.
Constructor & Destructor Documentation
CFinalCommitment() [1/2]
llmq::CFinalCommitment::CFinalCommitment () inline
Definition at line 43 of file quorums_commitment.h.
CFinalCommitment() [2/2]
llmq::CFinalCommitment::CFinalCommitment (const Consensus::LLMQParams & params, const uint256 & _quorumHash)
Definition at line 16 of file quorums_commitment.cpp.
Member Function Documentation
CountSigners()
int llmq::CFinalCommitment::CountSigners () const inline
Definition at line 46 of file quorums_commitment.h.
References count, and signers.
Referenced by llmq::CQuorumBlockProcessor::AddMinableCommitment(), llmq::CDKGSession::FinalizeCommitments(), llmq::CQuorumBlockProcessor::ProcessCommitment(), ToJson(), and Verify().
CountValidMembers()
int llmq::CFinalCommitment::CountValidMembers () const inline
Definition at line 50 of file quorums_commitment.h.
References count, and validMembers.
Referenced by llmq::CDKGSession::FinalizeCommitments(), llmq::CQuorumBlockProcessor::ProcessCommitment(), ToJson(), and Verify().
IsNull()
bool llmq::CFinalCommitment::IsNull () const inline
Definition at line 77 of file quorums_commitment.h.
References count, base_blob< BITS >::IsNull(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), membersSig, quorumPublicKey, quorumSig, quorumVvecHash, signers, and validMembers.
Referenced by CDeterministicMNManager::BuildNewListFromBlock(), CalcCbTxMerkleRootQuorums(), llmq::CheckLLMQCommitment(), llmq::CQuorumBlockProcessor::ProcessCommitment(), and VerifyNull().
SerializationOp()
template<typename Stream , typename Operation > ADD_SERIALIZE_METHODS void llmq::CFinalCommitment::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 63 of file quorums_commitment.h.
References DYNBITSET, llmqType, membersSig, nVersion, quorumHash, quorumPublicKey, quorumSig, quorumVvecHash, READWRITE, signers, and validMembers.
ToJson()
void llmq::CFinalCommitment::ToJson (UniValue & obj) const inline
Definition at line 92 of file quorums_commitment.h.
References CountSigners(), CountValidMembers(), llmqType, membersSig, nVersion, Pair(), UniValue::push_back(), quorumHash, quorumPublicKey, quorumSig, quorumVvecHash, UniValue::setObject(), signers, llmq::CLLMQUtils::ToHexStr(), base_blob< BITS >::ToString(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), and validMembers.
Referenced by quorum_dkgstatus(), and llmq::CFinalCommitmentTxPayload::ToJson().
Verify()
bool llmq::CFinalCommitment::Verify (const std::vector< CDeterministicMNCPtr > & members, bool checkSigs) const
Definition at line 28 of file quorums_commitment.cpp.
References llmq::CLLMQUtils::BuildCommitmentHash(), CountSigners(), CountValidMembers(), CURRENT_VERSION, CChainParams::GetConsensus(), base_blob< BITS >::IsNull(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), Consensus::Params::llmqs, llmqType, LogPrintfFinalCommitment, membersSig, nVersion, Params(), quorumHash, quorumPublicKey, quorumSig, quorumVvecHash, signers, validMembers, CBLSSignature::VerifyInsecure(), CBLSSignature::VerifySecureAggregated(), and VerifySizes().
Referenced by llmq::CheckLLMQCommitment(), and llmq::CQuorumBlockProcessor::ProcessCommitment().
VerifyNull()
bool llmq::CFinalCommitment::VerifyNull () const
Definition at line 106 of file quorums_commitment.cpp.
References CChainParams::GetConsensus(), IsNull(), Consensus::Params::llmqs, llmqType, LogPrintfFinalCommitment, Params(), and VerifySizes().
Referenced by llmq::CheckLLMQCommitment(), and llmq::CQuorumBlockProcessor::ProcessCommitment().
VerifySizes()
bool llmq::CFinalCommitment::VerifySizes (const Consensus::LLMQParams & params) const
Definition at line 121 of file quorums_commitment.cpp.
References LogPrintfFinalCommitment, signers, Consensus::LLMQParams::size, and validMembers.
Referenced by Verify(), and VerifyNull().
Member Data Documentation
CURRENT_VERSION
const uint16_t llmq::CFinalCommitment::CURRENT_VERSION = 1 static
Definition at line 27 of file quorums_commitment.h.
Referenced by Verify().
llmqType
Consensus::LLMQType llmq::CFinalCommitment::llmqType {Consensus::LLMQ_NONE}
Definition at line 31 of file quorums_commitment.h.
Referenced by llmq::CQuorumBlockProcessor::AddMinableCommitment(), CDeterministicMNManager::BuildNewListFromBlock(), llmq::CQuorumManager::BuildQuorumContributions(), llmq::CQuorumManager::BuildQuorumFromCommitment(), CalcCbTxMerkleRootQuorums(), llmq::CheckLLMQCommitment(), llmq::CDKGSession::FinalizeCommitments(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), CDeterministicMNManager::HandleQuorumCommitment(), llmq::CQuorumBlockProcessor::ProcessCommitment(), SerializationOp(), ToJson(), Verify(), and VerifyNull().
membersSig
CBLSSignature llmq::CFinalCommitment::membersSig
Definition at line 40 of file quorums_commitment.h.
Referenced by llmq::CDKGSession::FinalizeCommitments(), IsNull(), SerializationOp(), ToJson(), and Verify().
nVersion
uint16_t llmq::CFinalCommitment::nVersion {CURRENT_VERSION}
Definition at line 30 of file quorums_commitment.h.
Referenced by SerializationOp(), ToJson(), and Verify().
quorumHash
uint256 llmq::CFinalCommitment::quorumHash
Definition at line 32 of file quorums_commitment.h.
Referenced by llmq::CQuorumBlockProcessor::AddMinableCommitment(), CDeterministicMNManager::BuildNewListFromBlock(), llmq::CQuorumManager::BuildQuorumFromCommitment(), llmq::CheckLLMQCommitment(), llmq::CDKGSession::FinalizeCommitments(), llmq::MakeQuorumKey(), llmq::CQuorumBlockProcessor::ProcessCommitment(), SerializationOp(), ToJson(), and Verify().
quorumPublicKey
CBLSPublicKey llmq::CFinalCommitment::quorumPublicKey
Definition at line 36 of file quorums_commitment.h.
Referenced by llmq::CDKGSession::FinalizeCommitments(), IsNull(), llmq::CQuorumBlockProcessor::ProcessCommitment(), SerializationOp(), ToJson(), and Verify().
quorumSig
CBLSSignature llmq::CFinalCommitment::quorumSig
Definition at line 39 of file quorums_commitment.h.
Referenced by llmq::CDKGSession::FinalizeCommitments(), IsNull(), SerializationOp(), ToJson(), and Verify().
quorumVvecHash
uint256 llmq::CFinalCommitment::quorumVvecHash
Definition at line 37 of file quorums_commitment.h.
Referenced by llmq::CDKGSession::FinalizeCommitments(), IsNull(), SerializationOp(), ToJson(), and Verify().
signers
std::vector<bool> llmq::CFinalCommitment::signers
Definition at line 33 of file quorums_commitment.h.
Referenced by CountSigners(), llmq::CDKGSession::FinalizeCommitments(), IsNull(), SerializationOp(), ToJson(), Verify(), and VerifySizes().
validMembers
std::vector<bool> llmq::CFinalCommitment::validMembers
Definition at line 34 of file quorums_commitment.h.
Referenced by llmq::CQuorumManager::BuildQuorumContributions(), CountValidMembers(), llmq::CDKGSession::FinalizeCommitments(), llmq::CQuorum::GetPubKeyShare(), CDeterministicMNManager::HandleQuorumCommitment(), IsNull(), llmq::CQuorum::IsValidMember(), SerializationOp(), ToJson(), Verify(), and VerifySizes().
The documentation for this class was generated from the following files:
src/llmq/quorums_commitment.h
src/llmq/quorums_commitment.cpp
Released under the MIT license