Dash Core: FreespaceChecker Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
FreespaceChecker Class Reference
Public Types
enum Status { ST_OK, ST_ERROR }
Public Slots
void check ()
Signals
void reply (int status, const QString &message, quint64 available)
Public Member Functions
FreespaceChecker (Intro *intro)
Private Attributes
Intro * intro
Detailed Description
Definition at line 42 of file intro.cpp.
Member Enumeration Documentation
Status
enum FreespaceChecker::Status
Enumerator
ST_OK
ST_ERROR
Definition at line 49 of file intro.cpp.
Constructor & Destructor Documentation
FreespaceChecker()
FreespaceChecker::FreespaceChecker (Intro * intro) explicit
Definition at line 66 of file intro.cpp.
References intro.
Member Function Documentation
check
void FreespaceChecker::check () slot
Definition at line 71 of file intro.cpp.
References Intro::getPathToCheck(), intro, GUIUtil::qstringToBoostPath(), reply(), ST_ERROR, and ST_OK.
reply
void FreespaceChecker::reply (int status, const QString & message, quint64 available) signal
Referenced by check().
Member Data Documentation
intro
Intro* FreespaceChecker::intro private
Definition at line 61 of file intro.cpp.
Referenced by check(), and FreespaceChecker().
The documentation for this class was generated from the following file:
src/qt/intro.cpp
Released under the MIT license