Dash Core: CMasternodePing Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodePing Class Reference
#include <masternode.h>
Public Member Functions
CMasternodePing ()=default
CMasternodePing (const COutPoint &outpoint)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
uint256 GetHash () const
bool IsExpired () const
bool Sign (const CKey &keyMasternode, const CPubKey &pubKeyMasternode)
bool CheckSignature (CPubKey &pubKeyMasternode, int &nDos)
bool SimpleCheck (int &nDos)
bool CheckAndUpdate (CMasternode *pmn, bool fFromNewBroadcast, int &nDos, CConnman &connman)
void Relay (CConnman &connman)
Public Attributes
CTxIn vin {}
uint256 blockHash {}
int64_t sigTime {}
std::vector< unsigned char > vchSig {}
bool fSentinelIsCurrent = false
uint32_t nSentinelVersion {DEFAULT_SENTINEL_VERSION}
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 32 of file masternode.h.
Constructor & Destructor Documentation
CMasternodePing() [1/2]
CMasternodePing::CMasternodePing () default
CMasternodePing() [2/2]
CMasternodePing::CMasternodePing (const COutPoint & outpoint)
Definition at line 671 of file masternode.cpp.
References blockHash, chainActive, cs_main, GetAdjustedTime(), CChain::Height(), LOCK, sigTime, CChain::Tip(), and vin.
Member Function Documentation
CheckAndUpdate()
bool CMasternodePing::CheckAndUpdate (CMasternode * pmn, bool fFromNewBroadcast, int & nDos, CConnman & connman)
Definition at line 743 of file masternode.cpp.
References blockHash, CMasternodeSync::BumpAssetLastTime(), chainActive, CMasternode::Check(), CheckSignature(), cs_main, CMasternodeBroadcast::GetHash(), CChain::Height(), CMasternode::IsEnabled(), CMasternode::IsExpired(), CMasternodeSync::IsMasternodeListSynced(), CMasternode::IsNewStartRequired(), CMasternode::IsPingedWithin(), CMasternode::IsUpdateRequired(), CMasternode::IsWatchdogExpired(), CMasternode::lastPing, LOCK, LogPrint(), LogPrintf, mapBlockIndex, CMasternodeMan::mapSeenMasternodeBroadcast, MASTERNODE_EXPIRATION_SECONDS, MASTERNODE_MIN_MNP_SECONDS, masternodeSync, mnodeman, CTxIn::prevout, masternode_info_t::pubKeyMasternode, Relay(), sigTime, SimpleCheck(), base_blob< BITS >::ToString(), COutPoint::ToStringShort(), and vin.
Referenced by CMasternode::UpdateFromNewBroadcast().
CheckSignature()
bool CMasternodePing::CheckSignature (CPubKey & pubKeyMasternode, int & nDos)
Definition at line 703 of file masternode.cpp.
References blockHash, LogPrintf, CTxIn::prevout, sigTime, base_blob< BITS >::ToString(), CTxIn::ToString(), COutPoint::ToStringShort(), vchSig, CMessageSigner::VerifyMessage(), and vin.
Referenced by CheckAndUpdate().
GetHash()
uint256 CMasternodePing::GetHash () const inline
Definition at line 65 of file masternode.h.
References CHashWriter::GetHash(), PROTOCOL_VERSION, SER_GETHASH, sigTime, and vin.
Referenced by Relay(), CMasternodeMan::SetMasternodeLastPing(), CMasternode::UpdateFromNewBroadcast(), and CMasternodeMan::UpdateMasternodeList().
IsExpired()
bool CMasternodePing::IsExpired () const inline
Definition at line 73 of file masternode.h.
References GetAdjustedTime(), MASTERNODE_NEW_START_REQUIRED_SECONDS, and sigTime.
Relay()
void CMasternodePing::Relay (CConnman & connman)
Definition at line 824 of file masternode.cpp.
References GetHash(), MSG_MASTERNODE_PING, and CConnman::RelayInv().
Referenced by CheckAndUpdate(), and CActiveMasternode::SendMasternodePing().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodePing::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 50 of file masternode.h.
References blockHash, DEFAULT_SENTINEL_VERSION, fSentinelIsCurrent, nSentinelVersion, READWRITE, sigTime, vchSig, and vin.
Sign()
bool CMasternodePing::Sign (const CKey & keyMasternode, const CPubKey & pubKeyMasternode)
Definition at line 681 of file masternode.cpp.
References blockHash, GetAdjustedTime(), LogPrintf, CMessageSigner::SignMessage(), sigTime, base_blob< BITS >::ToString(), CTxIn::ToString(), vchSig, CMessageSigner::VerifyMessage(), and vin.
Referenced by CMasternodeBroadcast::Create(), and CActiveMasternode::SendMasternodePing().
SimpleCheck()
bool CMasternodePing::SimpleCheck (int & nDos)
Definition at line 718 of file masternode.cpp.
References AssertLockHeld, blockHash, cs_main, GetAdjustedTime(), LogPrint(), LogPrintf, mapBlockIndex, CTxIn::prevout, sigTime, base_blob< BITS >::ToString(), COutPoint::ToStringShort(), and vin.
Referenced by CheckAndUpdate(), and CMasternodeBroadcast::SimpleCheck().
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodePing::ADD_SERIALIZE_METHODS
Definition at line 47 of file masternode.h.
blockHash
uint256 CMasternodePing::blockHash {}
Definition at line 36 of file masternode.h.
Referenced by CheckAndUpdate(), CheckSignature(), CMasternodePing(), masternodebroadcast(), operator==(), SerializationOp(), Sign(), and SimpleCheck().
fSentinelIsCurrent
bool CMasternodePing::fSentinelIsCurrent = false
Definition at line 39 of file masternode.h.
Referenced by masternodelist(), CActiveMasternode::SendMasternodePing(), SerializationOp(), and CMasternodeMan::SetMasternodeLastPing().
nSentinelVersion
uint32_t CMasternodePing::nSentinelVersion {DEFAULT_SENTINEL_VERSION}
Definition at line 41 of file masternode.h.
Referenced by masternodelist(), CActiveMasternode::SendMasternodePing(), and SerializationOp().
sigTime
int64_t CMasternodePing::sigTime {}
Definition at line 37 of file masternode.h.
Referenced by CMasternode::Check(), CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CheckSignature(), CMasternodePing(), GetHash(), CMasternode::GetInfo(), IsExpired(), CMasternode::IsPingedWithin(), masternodebroadcast(), masternodelist(), CActiveMasternode::SendMasternodePing(), SerializationOp(), CMasternodeMan::SetMasternodeLastPing(), Sign(), SimpleCheck(), and MasternodeList::updateNodeList().
vchSig
std::vector<unsigned char> CMasternodePing::vchSig {}
Definition at line 38 of file masternode.h.
Referenced by CheckSignature(), masternodebroadcast(), SerializationOp(), and Sign().
vin
CTxIn CMasternodePing::vin {}
Definition at line 35 of file masternode.h.
Referenced by CheckAndUpdate(), CheckSignature(), CMasternodePing(), GetHash(), masternodebroadcast(), operator==(), SerializationOp(), CMasternodeMan::SetMasternodeLastPing(), Sign(), and SimpleCheck().
The documentation for this class was generated from the following files:
src/masternode.h
src/masternode.cpp
Released under the MIT license