Dash Core: CompareTxMemPoolEntryByScore Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CompareTxMemPoolEntryByScore Class Reference
Sort by score of entry ((fee+delta)/size) in descending order.
#include <txmempool.h>
Public Member Functions
bool operator() (const CTxMemPoolEntry &a, const CTxMemPoolEntry &b)
Detailed Description
Sort by score of entry ((fee+delta)/size) in descending order.
Definition at line 241 of file txmempool.h.
Member Function Documentation
operator()()
bool CompareTxMemPoolEntryByScore::operator() (const CTxMemPoolEntry & a, const CTxMemPoolEntry & b) inline
Definition at line 244 of file txmempool.h.
References CTransaction::GetHash(), CTxMemPoolEntry::GetModifiedFee(), CTxMemPoolEntry::GetTx(), and CTxMemPoolEntry::GetTxSize().
The documentation for this class was generated from the following file:
src/txmempool.h
Released under the MIT license