Dash Core: CMasternodeMetaMan Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CMasternodeMetaMan Class Reference
#include <masternode-meta.h>
Public Member Functions
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
CMasternodeMetaInfoPtr GetMetaInfo (const uint256 &proTxHash, bool fCreate=true)
int64_t GetDsqCount ()
int64_t GetDsqThreshold (const uint256 &proTxHash, int nMnCount)
void AllowMixing (const uint256 &proTxHash)
void DisallowMixing (const uint256 &proTxHash)
bool AddGovernanceVote (const uint256 &proTxHash, const uint256 &nGovernanceObjectHash)
void RemoveGovernanceObject (const uint256 &nGovernanceObjectHash)
std::vector< uint256 > GetAndClearDirtyGovernanceObjectHashes ()
void Clear ()
void CheckAndRemove ()
std::string ToString () const
Private Attributes
CCriticalSection cs
std::map< uint256, CMasternodeMetaInfoPtr > metaInfos
std::vector< uint256 > vecDirtyGovernanceObjectHashes
int64_t nDsqCount = 0
Static Private Attributes
static const std::string SERIALIZATION_VERSION_STRING = "CMasternodeMetaMan-Version-2"
Detailed Description
Definition at line 88 of file masternode-meta.h.
Member Function Documentation
AddGovernanceVote()
bool CMasternodeMetaMan::AddGovernanceVote (const uint256 & proTxHash, const uint256 & nGovernanceObjectHash)
Definition at line 93 of file masternode-meta.cpp.
References cs, GetMetaInfo(), and LOCK.
Referenced by CGovernanceObject::ProcessVote().
AllowMixing()
void CMasternodeMetaMan::AllowMixing (const uint256 & proTxHash)
Definition at line 74 of file masternode-meta.cpp.
References cs, GetMetaInfo(), LOCK, and nDsqCount.
Referenced by CPrivateSendServer::ProcessMessage(), and CPrivateSendClientManager::ProcessMessage().
CheckAndRemove()
void CMasternodeMetaMan::CheckAndRemove ()
Definition at line 124 of file masternode-meta.cpp.
Clear()
void CMasternodeMetaMan::Clear ()
Definition at line 117 of file masternode-meta.cpp.
References cs, LOCK, metaInfos, and vecDirtyGovernanceObjectHashes.
Referenced by SerializationOp().
DisallowMixing()
void CMasternodeMetaMan::DisallowMixing (const uint256 & proTxHash)
Definition at line 84 of file masternode-meta.cpp.
References cs, GetMetaInfo(), and LOCK.
Referenced by ProcessMessage().
GetAndClearDirtyGovernanceObjectHashes()
std::vector< uint256 > CMasternodeMetaMan::GetAndClearDirtyGovernanceObjectHashes ()
Definition at line 109 of file masternode-meta.cpp.
References cs, LOCK, and vecDirtyGovernanceObjectHashes.
Referenced by CGovernanceManager::UpdateCachesAndClean().
GetDsqCount()
int64_t CMasternodeMetaMan::GetDsqCount () inline
Definition at line 142 of file masternode-meta.h.
References cs, LOCK, and nDsqCount.
Referenced by CPrivateSendServer::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), and CPrivateSendClientSession::StartNewQueue().
GetDsqThreshold()
int64_t CMasternodeMetaMan::GetDsqThreshold (const uint256 & proTxHash, int nMnCount)
Definition at line 63 of file masternode-meta.cpp.
References cs, GetMetaInfo(), LOCK, and nDsqCount.
Referenced by CPrivateSendServer::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), and CPrivateSendClientSession::StartNewQueue().
GetMetaInfo()
CMasternodeMetaInfoPtr CMasternodeMetaMan::GetMetaInfo (const uint256 & proTxHash, bool fCreate = true)
Definition at line 45 of file masternode-meta.cpp.
References cs, LOCK, and metaInfos.
Referenced by AddGovernanceVote(), llmq::CLLMQUtils::AddQuorumProbeConnections(), AllowMixing(), BuildDMNListEntry(), DisallowMixing(), GetDsqThreshold(), CMNAuth::ProcessMessage(), CPrivateSendServer::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), ProcessMessage(), CPrivateSendClientSession::StartNewQueue(), CConnman::ThreadOpenMasternodeConnections(), and llmq::CDKGSession::VerifyConnectionAndMinProtoVersions().
RemoveGovernanceObject()
void CMasternodeMetaMan::RemoveGovernanceObject (const uint256 & nGovernanceObjectHash)
Definition at line 101 of file masternode-meta.cpp.
References cs, LOCK, and metaInfos.
Referenced by CGovernanceManager::UpdateCachesAndClean().
SerializationOp()
template<typename Stream , typename Operation > ADD_SERIALIZE_METHODS void CMasternodeMetaMan::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 105 of file masternode-meta.h.
References Clear(), cs, LOCK, metaInfos, nDsqCount, READWRITE, and SERIALIZATION_VERSION_STRING.
ToString()
std::string CMasternodeMetaMan::ToString () const
Definition at line 129 of file masternode-meta.cpp.
References metaInfos, and nDsqCount.
Member Data Documentation
cs
CCriticalSection CMasternodeMetaMan::cs private
Definition at line 93 of file masternode-meta.h.
Referenced by AddGovernanceVote(), AllowMixing(), Clear(), DisallowMixing(), GetAndClearDirtyGovernanceObjectHashes(), GetDsqCount(), GetDsqThreshold(), GetMetaInfo(), RemoveGovernanceObject(), and SerializationOp().
metaInfos
std::map<uint256, CMasternodeMetaInfoPtr> CMasternodeMetaMan::metaInfos private
Definition at line 95 of file masternode-meta.h.
Referenced by Clear(), GetMetaInfo(), RemoveGovernanceObject(), SerializationOp(), and ToString().
nDsqCount
int64_t CMasternodeMetaMan::nDsqCount = 0 private
Definition at line 99 of file masternode-meta.h.
Referenced by AllowMixing(), GetDsqCount(), GetDsqThreshold(), SerializationOp(), and ToString().
SERIALIZATION_VERSION_STRING
const std::string CMasternodeMetaMan::SERIALIZATION_VERSION_STRING = "CMasternodeMetaMan-Version-2" static private
Definition at line 91 of file masternode-meta.h.
Referenced by SerializationOp().
vecDirtyGovernanceObjectHashes
std::vector<uint256> CMasternodeMetaMan::vecDirtyGovernanceObjectHashes private
Definition at line 96 of file masternode-meta.h.
Referenced by Clear(), and GetAndClearDirtyGovernanceObjectHashes().
The documentation for this class was generated from the following files:
src/masternode/masternode-meta.h
src/masternode/masternode-meta.cpp
Released under the MIT license