Dash Core: CActiveMasternodeManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CActiveMasternodeManager Class Reference
#include <activemasternode.h>
Public Types
enum masternode_state_t {
MASTERNODE_WAITING_FOR_PROTX, MASTERNODE_POSE_BANNED, MASTERNODE_REMOVED, MASTERNODE_OPERATOR_KEY_CHANGED,
MASTERNODE_PROTX_IP_CHANGED, MASTERNODE_READY, MASTERNODE_ERROR
}
Public Member Functions
virtual void UpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload)
Notifies listeners of updated block chain tip.
void Init (const CBlockIndex *pindex)
std::string GetStateString () const
std::string GetStatus () const
Static Public Member Functions
static bool IsValidNetAddr (CService addrIn)
Private Member Functions
bool GetLocalAddress (CService &addrRet)
Private Attributes
masternode_state_t state {MASTERNODE_WAITING_FOR_PROTX}
std::string strError
Additional Inherited Members
Protected Member Functions inherited from CValidationInterface
virtual void AcceptedBlockHeader (const CBlockIndex *pindexNew)
virtual void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload)
virtual void SynchronousUpdatedBlockTip (const CBlockIndex *pindexNew, const CBlockIndex *pindexFork, bool fInitialDownload)
Same as UpdatedBlockTip, but called from the caller's thread.
virtual void TransactionAddedToMempool (const CTransactionRef &ptxn, int64_t nAcceptTime)
Notifies listeners of a transaction having been added to mempool.
virtual void TransactionRemovedFromMempool (const CTransactionRef &ptx)
Notifies listeners of a transaction leaving mempool.
virtual void BlockConnected (const std::shared_ptr< const CBlock > &block, const CBlockIndex *pindex, const std::vector< CTransactionRef > &txnConflicted)
Notifies listeners of a block being connected.
virtual void BlockDisconnected (const std::shared_ptr< const CBlock > &block, const CBlockIndex *pindexDisconnected)
Notifies listeners of a block being disconnected.
virtual void NotifyTransactionLock (const CTransaction &tx, const llmq::CInstantSendLock &islock)
virtual void NotifyChainLock (const CBlockIndex *pindex, const llmq::CChainLockSig &clsig)
virtual void NotifyGovernanceVote (const CGovernanceVote &vote)
virtual void NotifyGovernanceObject (const CGovernanceObject &object)
virtual void NotifyInstantSendDoubleSpendAttempt (const CTransaction &currentTx, const CTransaction &previousTx)
virtual void NotifyMasternodeListChanged (bool undo, const CDeterministicMNList &oldMNList, const CDeterministicMNListDiff &diff)
virtual void SetBestChain (const CBlockLocator &locator)
Notifies listeners of the new active block chain on-disk.
virtual void ResendWalletTransactions (int64_t nBestBlockTime, CConnman *connman)
Tells listeners to broadcast their data.
virtual void BlockChecked (const CBlock &, const CValidationState &)
Notifies listeners of a block validation result.
virtual void NewPoWValidBlock (const CBlockIndex *pindex, const std::shared_ptr< const CBlock > &block)
Notifies listeners that a block which builds directly on our current tip has been received and connected to the headers tree, though not validated yet.
friend void ::RegisterValidationInterface (CValidationInterface *)
friend void ::UnregisterValidationInterface (CValidationInterface *)
friend void ::UnregisterAllValidationInterfaces ()
Detailed Description
Definition at line 35 of file activemasternode.h.
Member Enumeration Documentation
masternode_state_t
enum CActiveMasternodeManager::masternode_state_t
Enumerator
MASTERNODE_WAITING_FOR_PROTX
MASTERNODE_POSE_BANNED
MASTERNODE_REMOVED
MASTERNODE_OPERATOR_KEY_CHANGED
MASTERNODE_PROTX_IP_CHANGED
MASTERNODE_READY
MASTERNODE_ERROR
Definition at line 38 of file activemasternode.h.
Member Function Documentation
GetLocalAddress()
bool CActiveMasternodeManager::GetLocalAddress (CService & addrRet) private
Definition at line 182 of file activemasternode.cpp.
References activeMasternodeInfo, CNode::addr, CConnman::AllNodes, immer::detail::dvektor::empty, g_connman, GetListenPort(), GetLocal(), CNetAddr::IsIPv4(), IsValidNetAddr(), LogPrintf, Lookup(), LookupHost(), Params(), CActiveMasternodeInfo::service, and strError.
Referenced by Init().
GetStateString()
std::string CActiveMasternodeManager::GetStateString () const
Definition at line 18 of file activemasternode.cpp.
References MASTERNODE_ERROR, MASTERNODE_OPERATOR_KEY_CHANGED, MASTERNODE_POSE_BANNED, MASTERNODE_PROTX_IP_CHANGED, MASTERNODE_READY, MASTERNODE_REMOVED, MASTERNODE_WAITING_FOR_PROTX, and state.
Referenced by masternode_status().
GetStatus()
std::string CActiveMasternodeManager::GetStatus () const
Definition at line 40 of file activemasternode.cpp.
References MASTERNODE_ERROR, MASTERNODE_OPERATOR_KEY_CHANGED, MASTERNODE_POSE_BANNED, MASTERNODE_PROTX_IP_CHANGED, MASTERNODE_READY, MASTERNODE_REMOVED, MASTERNODE_WAITING_FOR_PROTX, state, and strError.
Referenced by masternode_status().
Init()
void CActiveMasternodeManager::Init (const CBlockIndex * pindex)
Definition at line 62 of file activemasternode.cpp.
References activeMasternodeInfo, CActiveMasternodeInfo::blsPubKeyOperator, CloseSocket(), ConnectSocketDirectly(), CreateSocket(), cs_main, deterministicMNManager, fListen, fMasternodeMode, GetLocalAddress(), CDeterministicMNList::GetMNByOperatorKey(), INVALID_SOCKET, CDeterministicMNList::IsMNPoSeBanned(), CDeterministicMNList::IsMNValid(), IsSelectableSocket(), LOCK, LogPrintf, MASTERNODE_ERROR, MASTERNODE_POSE_BANNED, MASTERNODE_READY, MASTERNODE_REMOVED, nConnectTimeout, CBlockIndex::nHeight, CActiveMasternodeInfo::outpoint, Params(), CActiveMasternodeInfo::proTxHash, CChainParams::RequireRoutableExternalIP(), CActiveMasternodeInfo::service, state, strError, and CService::ToString().
Referenced by ThreadImport(), and UpdatedBlockTip().
IsValidNetAddr()
bool CActiveMasternodeManager::IsValidNetAddr (CService addrIn) static
Definition at line 217 of file activemasternode.cpp.
References CNetAddr::IsIPv4(), IsReachable(), CNetAddr::IsRoutable(), Params(), and CChainParams::RequireRoutableExternalIP().
Referenced by GetLocalAddress().
UpdatedBlockTip()
void CActiveMasternodeManager::UpdatedBlockTip (const CBlockIndex * pindexNew, const CBlockIndex * pindexFork, bool fInitialDownload) virtual
Notifies listeners of updated block chain tip.
Called on a background thread.
Reimplemented from CValidationInterface.
Definition at line 134 of file activemasternode.cpp.
References activeMasternodeInfo, cs_main, deterministicMNManager, fMasternodeMode, Init(), LOCK, MASTERNODE_OPERATOR_KEY_CHANGED, MASTERNODE_PROTX_IP_CHANGED, MASTERNODE_READY, MASTERNODE_REMOVED, CBlockIndex::nHeight, CActiveMasternodeInfo::outpoint, CBlockIndex::pprev, CActiveMasternodeInfo::proTxHash, COutPoint::SetNull(), and state.
Member Data Documentation
state
masternode_state_t CActiveMasternodeManager::state {MASTERNODE_WAITING_FOR_PROTX} private
Definition at line 49 of file activemasternode.h.
Referenced by GetStateString(), GetStatus(), Init(), and UpdatedBlockTip().
strError
std::string CActiveMasternodeManager::strError private
Definition at line 50 of file activemasternode.h.
Referenced by GetLocalAddress(), GetStatus(), and Init().
The documentation for this class was generated from the following files:
src/masternode/activemasternode.h
src/masternode/activemasternode.cpp
Released under the MIT license