Dash Core: QRGeneralImageWidget Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
QRGeneralImageWidget Class Reference
#include <qrdialog.h>
Public Slots
void saveImage ()
void copyImage ()
Public Member Functions
QRGeneralImageWidget (QWidget *parent=0)
QImage exportImage ()
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event)
virtual void contextMenuEvent (QContextMenuEvent *event)
Private Attributes
QMenu * contextMenu
Detailed Description
Definition at line 27 of file qrdialog.h.
Constructor & Destructor Documentation
QRGeneralImageWidget()
QRGeneralImageWidget::QRGeneralImageWidget (QWidget * parent = 0) explicit
Definition at line 33 of file qrdialog.cpp.
References contextMenu, copyImage(), and saveImage().
Member Function Documentation
contextMenuEvent()
void QRGeneralImageWidget::contextMenuEvent (QContextMenuEvent * event) protected virtual
Definition at line 86 of file qrdialog.cpp.
References contextMenu.
copyImage
void QRGeneralImageWidget::copyImage () slot
Definition at line 79 of file qrdialog.cpp.
References exportImage().
Referenced by QRGeneralImageWidget().
exportImage()
QImage QRGeneralImageWidget::exportImage ()
Definition at line 45 of file qrdialog.cpp.
Referenced by copyImage(), mousePressEvent(), and saveImage().
mousePressEvent()
void QRGeneralImageWidget::mousePressEvent (QMouseEvent * event) protected virtual
Definition at line 52 of file qrdialog.cpp.
References exportImage().
saveImage
void QRGeneralImageWidget::saveImage () slot
Definition at line 68 of file qrdialog.cpp.
References exportImage(), and GUIUtil::getSaveFileName().
Referenced by QRGeneralImageWidget().
Member Data Documentation
contextMenu
QMenu* QRGeneralImageWidget::contextMenu private
Definition at line 44 of file qrdialog.h.
Referenced by contextMenuEvent(), and QRGeneralImageWidget().
The documentation for this class was generated from the following files:
src/qt/qrdialog.h
src/qt/qrdialog.cpp
Released under the MIT license