Dash Core: CTxOutCompressor Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CTxOutCompressor Class Reference
wrapper for CTxOut that provides a more compact serialization
#include <compressor.h>
Public Member Functions
CTxOutCompressor (CTxOut &txoutIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
Static Public Member Functions
static uint64_t CompressAmount (uint64_t nAmount)
static uint64_t DecompressAmount (uint64_t nAmount)
Public Attributes
ADD_SERIALIZE_METHODS
Private Attributes
CTxOut & txout
Detailed Description
wrapper for CTxOut that provides a more compact serialization
Definition at line 93 of file compressor.h.
Constructor & Destructor Documentation
CTxOutCompressor()
CTxOutCompressor::CTxOutCompressor (CTxOut & txoutIn) inline explicit
Definition at line 102 of file compressor.h.
Member Function Documentation
CompressAmount()
uint64_t CTxOutCompressor::CompressAmount (uint64_t nAmount) static
Definition at line 142 of file compressor.cpp.
Referenced by SerializationOp().
DecompressAmount()
uint64_t CTxOutCompressor::DecompressAmount (uint64_t nAmount) static
Definition at line 161 of file compressor.cpp.
Referenced by SerializationOp().
SerializationOp()
template<typename Stream , typename Operation > void CTxOutCompressor::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 107 of file compressor.h.
References CompressAmount(), DecompressAmount(), CTxOut::nValue, READWRITE, REF(), CTxOut::scriptPubKey, txout, and VARINT.
Member Data Documentation
ADD_SERIALIZE_METHODS
CTxOutCompressor::ADD_SERIALIZE_METHODS
Definition at line 104 of file compressor.h.
txout
CTxOut& CTxOutCompressor::txout private
Definition at line 96 of file compressor.h.
Referenced by SerializationOp().
The documentation for this class was generated from the following files:
src/compressor.h
src/compressor.cpp
Released under the MIT license