Dash Core: CSuperblockManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CSuperblockManager Class Reference
Superblock Manager.
#include <governance-classes.h>
Static Public Member Functions
static bool IsSuperblockTriggered (int nBlockHeight)
Is Superblock Triggered.
static bool GetSuperblockPayments (int nBlockHeight, std::vector< CTxOut > &voutSuperblockRet)
Get Superblock Payments.
static void ExecuteBestSuperblock (int nBlockHeight)
static std::string GetRequiredPaymentsString (int nBlockHeight)
Get Required Payment String.
static bool IsValid (const CTransaction &txNew, int nBlockHeight, CAmount blockReward)
Static Private Member Functions
static bool GetBestSuperblock (CSuperblock_sptr &pSuperblockRet, int nBlockHeight)
Detailed Description
Superblock Manager.
Class for querying superblock information
Definition at line 55 of file governance-classes.h.
Member Function Documentation
ExecuteBestSuperblock()
void CSuperblockManager::ExecuteBestSuperblock (int nBlockHeight) static
Definition at line 376 of file governance-classes.cpp.
References CGovernanceManager::cs, GetBestSuperblock(), governance, and LOCK.
Referenced by CGovernanceManager::UpdatedBlockTip().
GetBestSuperblock()
bool CSuperblockManager::GetBestSuperblock (CSuperblock_sptr & pSuperblockRet, int nBlockHeight) static private
Definition at line 276 of file governance-classes.cpp.
References AssertLockHeld(), CGovernanceManager::cs, CGovernanceObject::GetAbsoluteYesCount(), CGovernanceTriggerManager::GetActiveTriggers(), governance, CSuperblock::IsValidBlockHeight(), triggerman, and VOTE_SIGNAL_FUNDING.
Referenced by ExecuteBestSuperblock(), GetRequiredPaymentsString(), GetSuperblockPayments(), and IsValid().
GetRequiredPaymentsString()
std::string CSuperblockManager::GetRequiredPaymentsString (int nBlockHeight) static
Get Required Payment String.
Get a string representing the payments required for a given superblock
Definition at line 700 of file governance-classes.cpp.
References CGovernanceManager::cs, EncodeDestination(), ExtractDestination(), GetBestSuperblock(), BCLog::GOBJECT, governance, LOCK, LogPrint, and CGovernancePayment::script.
Referenced by GetRequiredPaymentsString().
GetSuperblockPayments()
bool CSuperblockManager::GetSuperblockPayments (int nBlockHeight, std::vector< CTxOut > & voutSuperblockRet) static
Get Superblock Payments.
Returns payments for superblock
Definition at line 315 of file governance-classes.cpp.
References CGovernanceManager::cs, EncodeDestination(), ExtractDestination(), GetBestSuperblock(), BCLog::GOBJECT, governance, LOCK, LogPrint, CGovernancePayment::nAmount, and CGovernancePayment::script.
Referenced by FillBlockPayments().
IsSuperblockTriggered()
bool CSuperblockManager::IsSuperblockTriggered (int nBlockHeight) static
Is Superblock Triggered.
Does this block have a non-executed and actived trigger?
Definition at line 223 of file governance-classes.cpp.
References CGovernanceManager::cs, CGovernanceTriggerManager::GetActiveTriggers(), CGovernanceObject::GetDataAsPlainString(), BCLog::GOBJECT, governance, CGovernanceObject::IsSetCachedFunding(), CSuperblock::IsValidBlockHeight(), LOCK, LogPrint, LogPrintf, triggerman, and CGovernanceObject::UpdateSentinelVariables().
Referenced by FillBlockPayments(), GetRequiredPaymentsString(), IsBlockPayeeValid(), and IsBlockValueValid().
IsValid()
bool CSuperblockManager::IsValid (const CTransaction & txNew, int nBlockHeight, CAmount blockReward) static
Definition at line 363 of file governance-classes.cpp.
References CGovernanceManager::cs, GetBestSuperblock(), governance, and LOCK.
Referenced by IsBlockPayeeValid(), and IsBlockValueValid().
The documentation for this class was generated from the following files:
src/governance/governance-classes.h
src/governance/governance-classes.cpp
Released under the MIT license