Dash Core: CMasternodeConfig Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodeConfig Class Reference
#include <masternodeconfig.h>
Classes
class CMasternodeEntry
Public Member Functions
CMasternodeConfig ()
void clear ()
bool read (std::string &strErr)
void add (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex)
std::vector< CMasternodeEntry > & getEntries ()
int getCount ()
Private Attributes
std::vector< CMasternodeEntry > entries
Detailed Description
Definition at line 12 of file masternodeconfig.h.
Constructor & Destructor Documentation
CMasternodeConfig()
CMasternodeConfig::CMasternodeConfig () inline
Definition at line 76 of file masternodeconfig.h.
References entries.
Member Function Documentation
add()
void CMasternodeConfig::add (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex)
Definition at line 12 of file masternodeconfig.cpp.
References alias(), and entries.
Referenced by read().
clear()
void CMasternodeConfig::clear ()
getCount()
int CMasternodeConfig::getCount () inline
Definition at line 88 of file masternodeconfig.h.
References entries.
Referenced by AppInit2(), and OptionsModel::Init().
getEntries()
std::vector<CMasternodeEntry>& CMasternodeConfig::getEntries () inline
Definition at line 84 of file masternodeconfig.h.
References entries.
Referenced by AppInit2(), gobject(), masternode(), masternodebroadcast(), MasternodeList::StartAlias(), MasternodeList::StartAll(), and MasternodeList::updateMyNodeList().
read()
bool CMasternodeConfig::read (std::string & strErr)
Definition at line 17 of file masternodeconfig.cpp.
References _(), add(), alias(), CChainParams::GetDefaultPort(), GetMasternodeConfigFile(), CBaseChainParams::MAIN, Params(), SplitHostPort(), and strprintf.
Referenced by AppInit(), and main().
Member Data Documentation
entries
std::vector<CMasternodeEntry> CMasternodeConfig::entries private
Definition at line 93 of file masternodeconfig.h.
Referenced by add(), CMasternodeConfig(), getCount(), and getEntries().
The documentation for this class was generated from the following files:
src/masternodeconfig.h
src/masternodeconfig.cpp
Released under the MIT license