Dash Core: TestCrypter Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
TestCrypter Class Reference
Static Public Member Functions
static void TestPassphraseSingle (const std::vector< unsigned char > &vchSalt, const SecureString &passphrase, uint32_t rounds, const std::vector< unsigned char > &correctKey=std::vector< unsigned char >(), const std::vector< unsigned char > &correctIV=std::vector< unsigned char >())
static void TestPassphrase (const std::vector< unsigned char > &vchSalt, const SecureString &passphrase, uint32_t rounds, const std::vector< unsigned char > &correctKey=std::vector< unsigned char >(), const std::vector< unsigned char > &correctIV=std::vector< unsigned char >())
static void TestDecrypt (const CCrypter &crypt, const std::vector< unsigned char > &vchCiphertext, const std::vector< unsigned char > &vchPlaintext=std::vector< unsigned char >())
static void TestEncryptSingle (const CCrypter &crypt, const CKeyingMaterial &vchPlaintext, const std::vector< unsigned char > &vchCiphertextCorrect=std::vector< unsigned char >())
static void TestEncrypt (const CCrypter &crypt, const std::vector< unsigned char > &vchPlaintextIn, const std::vector< unsigned char > &vchCiphertextCorrect=std::vector< unsigned char >())
Detailed Description
Definition at line 28 of file crypto_tests.cpp.
Member Function Documentation
TestDecrypt()
static void TestCrypter::TestDecrypt (const CCrypter & crypt, const std::vector< unsigned char > & vchCiphertext, const std::vector< unsigned char > & vchPlaintext = std::vector<unsigned char>()) inline static
Definition at line 55 of file crypto_tests.cpp.
References BOOST_CHECK, and CCrypter::Decrypt().
Referenced by BOOST_AUTO_TEST_CASE(), and TestEncryptSingle().
TestEncrypt()
static void TestCrypter::TestEncrypt (const CCrypter & crypt, const std::vector< unsigned char > & vchPlaintextIn, const std::vector< unsigned char > & vchCiphertextCorrect = std::vector<unsigned char>()) inline static
Definition at line 77 of file crypto_tests.cpp.
References TestEncryptSingle().
Referenced by BOOST_AUTO_TEST_CASE().
TestEncryptSingle()
static void TestCrypter::TestEncryptSingle (const CCrypter & crypt, const CKeyingMaterial & vchPlaintext, const std::vector< unsigned char > & vchCiphertextCorrect = std::vector<unsigned char>()) inline static
Definition at line 64 of file crypto_tests.cpp.
References BOOST_CHECK, CCrypter::Encrypt(), and TestDecrypt().
Referenced by TestEncrypt().
TestPassphrase()
static void TestCrypter::TestPassphrase (const std::vector< unsigned char > & vchSalt, const SecureString & passphrase, uint32_t rounds, const std::vector< unsigned char > & correctKey = std::vector<unsigned char>(), const std::vector< unsigned char > & correctIV = std::vector<unsigned char>()) inline static
Definition at line 46 of file crypto_tests.cpp.
References TestPassphraseSingle().
Referenced by BOOST_AUTO_TEST_CASE().
TestPassphraseSingle()
static void TestCrypter::TestPassphraseSingle (const std::vector< unsigned char > & vchSalt, const SecureString & passphrase, uint32_t rounds, const std::vector< unsigned char > & correctKey = std::vector<unsigned char>(), const std::vector< unsigned char > & correctIV = std::vector<unsigned char>()) inline static
Definition at line 31 of file crypto_tests.cpp.
References HexStr(), CCrypter::SetKeyFromPassphrase(), CCrypter::vchIV, and CCrypter::vchKey.
Referenced by TestPassphrase().
The documentation for this class was generated from the following file:
src/wallet/test/crypto_tests.cpp
Released under the MIT license