Dash Core: PartiallyDownloadedBlock Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
PartiallyDownloadedBlock Class Reference
#include <blockencodings.h>
Public Member Functions
PartiallyDownloadedBlock (CTxMemPool *poolIn)
ReadStatus InitData (const CBlockHeaderAndShortTxIDs &cmpctblock, const std::vector< std::pair< uint256, CTransactionRef >> &extra_txn)
bool IsTxAvailable (size_t index) const
ReadStatus FillBlock (CBlock &block, const std::vector< CTransactionRef > &vtx_missing)
Public Attributes
CBlockHeader header
Protected Attributes
std::vector< CTransactionRef > txn_available
size_t prefilled_count = 0
size_t mempool_count = 0
size_t extra_count = 0
CTxMemPool * pool
Detailed Description
Definition at line 194 of file blockencodings.h.
Constructor & Destructor Documentation
PartiallyDownloadedBlock()
PartiallyDownloadedBlock::PartiallyDownloadedBlock (CTxMemPool * poolIn) inline explicit
Definition at line 201 of file blockencodings.h.
Member Function Documentation
FillBlock()
ReadStatus PartiallyDownloadedBlock::FillBlock (CBlock & block, const std::vector< CTransactionRef > & vtx_missing)
Definition at line 178 of file blockencodings.cpp.
References CheckBlock(), BCLog::CMPCTBLOCK, CValidationState::CorruptionPossible(), extra_count, CBlockHeader::GetHash(), header, CBlockHeader::IsNull(), LogPrint, mempool_count, Params(), prefilled_count, READ_STATUS_CHECKBLOCK_FAILED, READ_STATUS_FAILED, READ_STATUS_INVALID, READ_STATUS_OK, CBlockHeader::SetNull(), txn_available, and CBlock::vtx.
Referenced by ProcessMessage().
InitData()
ReadStatus PartiallyDownloadedBlock::InitData (const CBlockHeaderAndShortTxIDs & cmpctblock, const std::vector< std::pair< uint256, CTransactionRef >> & extra_txn)
Definition at line 50 of file blockencodings.cpp.
References CBlockHeaderAndShortTxIDs::BlockTxCount(), BCLog::CMPCTBLOCK, CTxMemPool::cs, extra_count, CBlockHeader::GetHash(), GetSerializeSize(), CBlockHeaderAndShortTxIDs::GetShortID(), CBlockHeaderAndShortTxIDs::header, header, CBlockHeader::IsNull(), LOCK, LogPrint, MaxBlockSize(), mempool_count, MIN_TRANSACTION_SIZE, pool, prefilled_count, CBlockHeaderAndShortTxIDs::prefilledtxn, PROTOCOL_VERSION, READ_STATUS_FAILED, READ_STATUS_INVALID, READ_STATUS_OK, SER_NETWORK, CBlockHeaderAndShortTxIDs::shorttxids, base_blob< BITS >::ToString(), txn_available, and CTxMemPool::vTxHashes.
Referenced by ProcessMessage().
IsTxAvailable()
bool PartiallyDownloadedBlock::IsTxAvailable (size_t index) const
Definition at line 172 of file blockencodings.cpp.
References header, CBlockHeader::IsNull(), and txn_available.
Referenced by ProcessMessage().
Member Data Documentation
extra_count
size_t PartiallyDownloadedBlock::extra_count = 0 protected
Definition at line 197 of file blockencodings.h.
Referenced by FillBlock(), and InitData().
header
CBlockHeader PartiallyDownloadedBlock::header
Definition at line 200 of file blockencodings.h.
Referenced by FillBlock(), InitData(), and IsTxAvailable().
mempool_count
size_t PartiallyDownloadedBlock::mempool_count = 0 protected
Definition at line 197 of file blockencodings.h.
Referenced by FillBlock(), and InitData().
pool
CTxMemPool* PartiallyDownloadedBlock::pool protected
Definition at line 198 of file blockencodings.h.
Referenced by InitData().
prefilled_count
size_t PartiallyDownloadedBlock::prefilled_count = 0 protected
Definition at line 197 of file blockencodings.h.
Referenced by FillBlock(), and InitData().
txn_available
std::vector<CTransactionRef> PartiallyDownloadedBlock::txn_available protected
Definition at line 196 of file blockencodings.h.
Referenced by FillBlock(), InitData(), and IsTxAvailable().
The documentation for this class was generated from the following files:
src/blockencodings.h
src/blockencodings.cpp
Released under the MIT license