Dash Core: CPendingDsaRequest Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CPendingDsaRequest Class Reference
#include <privatesend-client.h>
Public Member Functions
CPendingDsaRequest ()
CPendingDsaRequest (const CService &addr_, const CPrivateSendAccept &dsa_)
CService GetAddr ()
CPrivateSendAccept GetDSA ()
bool IsExpired ()
operator bool () const
Private Attributes
CService addr
CPrivateSendAccept dsa
int64_t nTimeCreated
Static Private Attributes
static const int TIMEOUT = 15
Friends
bool operator== (const CPendingDsaRequest &a, const CPendingDsaRequest &b)
bool operator!= (const CPendingDsaRequest &a, const CPendingDsaRequest &b)
Detailed Description
Definition at line 59 of file privatesend-client.h.
Constructor & Destructor Documentation
CPendingDsaRequest() [1/2]
CPendingDsaRequest::CPendingDsaRequest () inline
Definition at line 69 of file privatesend-client.h.
Referenced by operator bool().
CPendingDsaRequest() [2/2]
CPendingDsaRequest::CPendingDsaRequest (const CService & addr_, const CPrivateSendAccept & dsa_) inline
Definition at line 76 of file privatesend-client.h.
Member Function Documentation
GetAddr()
CService CPendingDsaRequest::GetAddr () inline
Definition at line 83 of file privatesend-client.h.
References addr.
Referenced by CPrivateSendClientSession::ProcessPendingDsaRequest().
GetDSA()
CPrivateSendAccept CPendingDsaRequest::GetDSA () inline
Definition at line 84 of file privatesend-client.h.
References dsa.
Referenced by CPrivateSendClientSession::ProcessPendingDsaRequest().
IsExpired()
bool CPendingDsaRequest::IsExpired () inline
Definition at line 85 of file privatesend-client.h.
References GetTime(), nTimeCreated, and TIMEOUT.
Referenced by CPrivateSendClientSession::ProcessPendingDsaRequest().
operator bool()
CPendingDsaRequest::operator bool () const inline explicit
Definition at line 95 of file privatesend-client.h.
References CPendingDsaRequest().
Friends And Related Function Documentation
operator!=
bool operator!= (const CPendingDsaRequest & a, const CPendingDsaRequest & b) friend
Definition at line 91 of file privatesend-client.h.
operator==
bool operator== (const CPendingDsaRequest & a, const CPendingDsaRequest & b) friend
Definition at line 87 of file privatesend-client.h.
Member Data Documentation
addr
CService CPendingDsaRequest::addr private
Definition at line 64 of file privatesend-client.h.
Referenced by GetAddr().
dsa
CPrivateSendAccept CPendingDsaRequest::dsa private
Definition at line 65 of file privatesend-client.h.
Referenced by GetDSA().
nTimeCreated
int64_t CPendingDsaRequest::nTimeCreated private
Definition at line 66 of file privatesend-client.h.
Referenced by IsExpired().
TIMEOUT
const int CPendingDsaRequest::TIMEOUT = 15 static private
Definition at line 62 of file privatesend-client.h.
Referenced by IsExpired().
The documentation for this class was generated from the following file:
src/privatesend/privatesend-client.h
Released under the MIT license