Dash Core: SendCoinsEntry Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
SendCoinsEntry Class Reference
A single entry in the dialog for sending bitcoins.
#include <sendcoinsentry.h>
Public Slots
void clear ()
void checkSubtractFeeFromAmount ()
Signals
void removeEntry (SendCoinsEntry *entry)
void useAvailableBalance (SendCoinsEntry *entry)
void payAmountChanged ()
void subtractFeeFromAmountChanged ()
Public Member Functions
SendCoinsEntry (QWidget *parent=0)
~SendCoinsEntry ()
void setModel (WalletModel *model)
bool validate ()
SendCoinsRecipient getValue ()
bool isClear ()
Return whether the entry is still empty and unedited.
void setValue (const SendCoinsRecipient &value)
void setAddress (const QString &address)
void setAmount (const CAmount &amount)
QWidget * setupTabChain (QWidget *prev)
Set up the tab chain manually, as Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907).
void setFocus ()
Protected Member Functions
void changeEvent (QEvent *e)
Private Slots
void deleteClicked ()
void useAvailableBalanceClicked ()
void on_payTo_textChanged (const QString &address)
void on_addressBookButton_clicked ()
void on_pasteButton_clicked ()
void updateDisplayUnit ()
Private Member Functions
void setButtonIcons ()
Set required icons for buttons inside the dialog.
bool updateLabel (const QString &address)
Private Attributes
SendCoinsRecipient recipient
Ui::SendCoinsEntry * ui
WalletModel * model
Detailed Description
A single entry in the dialog for sending bitcoins.
Stacked widget, with different UIs for payment requests with a strong payee identity.
Definition at line 23 of file sendcoinsentry.h.
Constructor & Destructor Documentation
SendCoinsEntry()
SendCoinsEntry::SendCoinsEntry (QWidget * parent = 0) explicit
Definition at line 17 of file sendcoinsentry.cpp.
References deleteClicked(), GUIUtil::disableMacFocusRect(), GUIUtil::Normal, payAmountChanged(), setButtonIcons(), GUIUtil::setFont(), GUIUtil::setupAddressWidget(), subtractFeeFromAmountChanged(), ui, GUIUtil::updateFonts(), and useAvailableBalanceClicked().
~SendCoinsEntry()
SendCoinsEntry::~SendCoinsEntry ()
Definition at line 53 of file sendcoinsentry.cpp.
References ui.
Member Function Documentation
changeEvent()
void SendCoinsEntry::changeEvent (QEvent * e) protected
Definition at line 274 of file sendcoinsentry.cpp.
References setButtonIcons().
checkSubtractFeeFromAmount
void SendCoinsEntry::checkSubtractFeeFromAmount () slot
Definition at line 122 of file sendcoinsentry.cpp.
References ui.
Referenced by SendCoinsDialog::useAvailableBalance().
clear
void SendCoinsEntry::clear () slot
Definition at line 99 of file sendcoinsentry.cpp.
References ui, and updateDisplayUnit().
Referenced by SendCoinsDialog::addEntry(), and setModel().
deleteClicked
void SendCoinsEntry::deleteClicked () private slot
Definition at line 127 of file sendcoinsentry.cpp.
References removeEntry().
Referenced by SendCoinsEntry().
getValue()
SendCoinsRecipient SendCoinsEntry::getValue ()
Definition at line 176 of file sendcoinsentry.cpp.
References SendCoinsRecipient::address, SendCoinsRecipient::amount, SendCoinsRecipient::fSubtractFeeFromAmount, PaymentRequestPlus::IsInitialized(), SendCoinsRecipient::label, SendCoinsRecipient::message, SendCoinsRecipient::paymentRequest, recipient, and ui.
Referenced by SendCoinsDialog::coinControlUpdateLabels(), SendCoinsDialog::on_sendButton_clicked(), and SendCoinsDialog::useAvailableBalance().
isClear()
bool SendCoinsEntry::isClear ()
Return whether the entry is still empty and unedited.
Definition at line 253 of file sendcoinsentry.cpp.
References ui.
Referenced by SendCoinsDialog::pasteEntry(), and SendCoinsDialog::setAddress().
on_addressBookButton_clicked
void SendCoinsEntry::on_addressBookButton_clicked () private slot
Definition at line 64 of file sendcoinsentry.cpp.
References AddressBookPage::ForSelection, WalletModel::getAddressTableModel(), AddressBookPage::getReturnValue(), model, AddressBookPage::SendingTab, AddressBookPage::setModel(), and ui.
on_pasteButton_clicked
void SendCoinsEntry::on_pasteButton_clicked () private slot
Definition at line 58 of file sendcoinsentry.cpp.
References ui.
on_payTo_textChanged
void SendCoinsEntry::on_payTo_textChanged (const QString & address) private slot
Definition at line 77 of file sendcoinsentry.cpp.
References GUIUtil::parseBitcoinURI(), setValue(), ui, and updateLabel().
payAmountChanged
void SendCoinsEntry::payAmountChanged () signal
Referenced by SendCoinsEntry().
removeEntry
void SendCoinsEntry::removeEntry (SendCoinsEntry * entry) signal
Referenced by deleteClicked().
setAddress()
void SendCoinsEntry::setAddress (const QString & address)
Definition at line 242 of file sendcoinsentry.cpp.
References ui.
Referenced by SendCoinsDialog::setAddress().
setAmount()
void SendCoinsEntry::setAmount (const CAmount & amount)
Definition at line 248 of file sendcoinsentry.cpp.
References ui.
Referenced by SendCoinsDialog::useAvailableBalance().
setButtonIcons()
void SendCoinsEntry::setButtonIcons () private
Set required icons for buttons inside the dialog.
Definition at line 283 of file sendcoinsentry.cpp.
References GUIUtil::RED, GUIUtil::setIcon(), and ui.
Referenced by changeEvent(), and SendCoinsEntry().
setFocus()
void SendCoinsEntry::setFocus ()
Definition at line 258 of file sendcoinsentry.cpp.
References ui.
Referenced by SendCoinsDialog::addEntry().
setModel()
void SendCoinsEntry::setModel (WalletModel * model)
Definition at line 89 of file sendcoinsentry.cpp.
References clear(), WalletModel::getOptionsModel(), model, and updateDisplayUnit().
Referenced by SendCoinsDialog::addEntry(), and SendCoinsDialog::setModel().
setupTabChain()
QWidget * SendCoinsEntry::setupTabChain (QWidget * prev)
Set up the tab chain manually, as Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907).
Definition at line 192 of file sendcoinsentry.cpp.
References ui.
Referenced by SendCoinsDialog::setupTabChain().
setValue()
void SendCoinsEntry::setValue (const SendCoinsRecipient & value)
Definition at line 204 of file sendcoinsentry.cpp.
References SendCoinsRecipient::address, SendCoinsRecipient::amount, SendCoinsRecipient::authenticatedMerchant, PaymentRequestPlus::IsInitialized(), SendCoinsRecipient::label, SendCoinsRecipient::message, SendCoinsRecipient::paymentRequest, recipient, ui, and updateLabel().
Referenced by on_payTo_textChanged(), and SendCoinsDialog::pasteEntry().
subtractFeeFromAmountChanged
void SendCoinsEntry::subtractFeeFromAmountChanged () signal
Referenced by SendCoinsEntry().
updateDisplayUnit
void SendCoinsEntry::updateDisplayUnit () private slot
Definition at line 263 of file sendcoinsentry.cpp.
References OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), model, and ui.
Referenced by clear(), and setModel().
updateLabel()
bool SendCoinsEntry::updateLabel (const QString & address) private
Definition at line 292 of file sendcoinsentry.cpp.
References WalletModel::getAddressTableModel(), AddressTableModel::labelForAddress(), model, and ui.
Referenced by on_payTo_textChanged(), and setValue().
useAvailableBalance
void SendCoinsEntry::useAvailableBalance (SendCoinsEntry * entry) signal
Referenced by useAvailableBalanceClicked().
useAvailableBalanceClicked
void SendCoinsEntry::useAvailableBalanceClicked () private slot
Definition at line 132 of file sendcoinsentry.cpp.
References useAvailableBalance().
Referenced by SendCoinsEntry().
validate()
bool SendCoinsEntry::validate ()
Definition at line 137 of file sendcoinsentry.cpp.
References GUIUtil::isDust(), PaymentRequestPlus::IsInitialized(), model, SendCoinsRecipient::paymentRequest, recipient, ui, and WalletModel::validateAddress().
Referenced by SendCoinsDialog::on_sendButton_clicked().
Member Data Documentation
model
WalletModel* SendCoinsEntry::model private
Definition at line 73 of file sendcoinsentry.h.
Referenced by on_addressBookButton_clicked(), setModel(), updateDisplayUnit(), updateLabel(), and validate().
recipient
SendCoinsRecipient SendCoinsEntry::recipient private
Definition at line 71 of file sendcoinsentry.h.
Referenced by getValue(), setValue(), and validate().
ui
Ui::SendCoinsEntry* SendCoinsEntry::ui private
Definition at line 72 of file sendcoinsentry.h.
Referenced by checkSubtractFeeFromAmount(), clear(), getValue(), isClear(), on_addressBookButton_clicked(), on_pasteButton_clicked(), on_payTo_textChanged(), SendCoinsEntry(), setAddress(), setAmount(), setButtonIcons(), setFocus(), setupTabChain(), setValue(), updateDisplayUnit(), updateLabel(), validate(), and ~SendCoinsEntry().
The documentation for this class was generated from the following files:
src/qt/sendcoinsentry.h
src/qt/sendcoinsentry.cpp
Released under the MIT license