Dash Core: CCoinsViewMemPool Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CCoinsViewMemPool Class Reference
CCoinsView that brings transactions from a memorypool into view.
#include <txmempool.h>
Public Member Functions
CCoinsViewMemPool (CCoinsView *baseIn, CTxMemPool &mempoolIn)
bool GetCoins (const uint256 &txid, CCoins &coins) const
Retrieve the CCoins (unspent transaction outputs) for a given txid.
bool HaveCoins (const uint256 &txid) const
Just check whether we have data for a given txid.
Public Member Functions inherited from CCoinsViewBacked
CCoinsViewBacked (CCoinsView *viewIn)
uint256 GetBestBlock () const
Retrieve the block hash whose state this CCoinsView currently represents.
void SetBackend (CCoinsView &viewIn)
bool BatchWrite (CCoinsMap &mapCoins, const uint256 &hashBlock)
Do a bulk modification (multiple CCoins changes + BestBlock change).
bool GetStats (CCoinsStats &stats) const
Calculate statistics about the unspent transaction output set.
Public Member Functions inherited from CCoinsView
virtual ~CCoinsView ()
As we use CCoinsViews polymorphically, have a virtual destructor.
Protected Attributes
CTxMemPool & mempool
Protected Attributes inherited from CCoinsViewBacked
CCoinsView * base
Detailed Description
CCoinsView that brings transactions from a memorypool into view.
It does not check for spendings by memory pool transactions.
Definition at line 638 of file txmempool.h.
Constructor & Destructor Documentation
CCoinsViewMemPool()
CCoinsViewMemPool::CCoinsViewMemPool (CCoinsView * baseIn, CTxMemPool & mempoolIn)
Definition at line 982 of file txmempool.cpp.
Member Function Documentation
GetCoins()
bool CCoinsViewMemPool::GetCoins (const uint256 & txid, CCoins & coins) const virtual
Retrieve the CCoins (unspent transaction outputs) for a given txid.
Reimplemented from CCoinsViewBacked.
Definition at line 984 of file txmempool.cpp.
References CCoinsViewBacked::base, CCoinsView::GetCoins(), CCoins::IsPruned(), CTxMemPool::lookup(), mempool, and MEMPOOL_HEIGHT.
Referenced by CheckSequenceLocks(), and gettxout().
HaveCoins()
bool CCoinsViewMemPool::HaveCoins (const uint256 & txid) const virtual
Just check whether we have data for a given txid.
This may (but cannot always) return true for fully spent transactions
Reimplemented from CCoinsViewBacked.
Definition at line 996 of file txmempool.cpp.
References CCoinsViewBacked::base, CTxMemPool::exists(), CCoinsView::HaveCoins(), and mempool.
Member Data Documentation
mempool
CTxMemPool& CCoinsViewMemPool::mempool protected
Definition at line 641 of file txmempool.h.
Referenced by GetCoins(), and HaveCoins().
The documentation for this class was generated from the following files:
src/txmempool.h
src/txmempool.cpp
Released under the MIT license