Dash Core: LockedPoolManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
LockedPoolManager Class Reference
Singleton class to keep track of locked (ie, non-swappable) memory, for use in std::allocator templates.
#include <lockedpool.h>
Static Public Member Functions
static LockedPoolManager & Instance ()
Return the current instance, or create it once.
Private Member Functions
LockedPoolManager (std::unique_ptr< LockedPageAllocator > allocator)
Static Private Member Functions
static void CreateInstance ()
Create a new LockedPoolManager specialized to the OS.
static bool LockingFailed ()
Called when locking fails, warn the user here.
Static Private Attributes
static LockedPoolManager * _instance = nullptr
static std::once_flag init_flag
Additional Inherited Members
Public Types inherited from LockedPool
typedef bool(* LockingFailed_Callback) ()
Callback when allocation succeeds but locking fails.
Public Member Functions inherited from LockedPool
LockedPool (std::unique_ptr< LockedPageAllocator > allocator, LockingFailed_Callback lf_cb_in=nullptr)
Create a new LockedPool.
~LockedPool ()
LockedPool (const LockedPool &other)=delete
LockedPool & operator= (const LockedPool &)=delete
void * alloc (size_t size)
Allocate size bytes from this arena.
void free (void *ptr)
Free a previously allocated chunk of memory.
Stats stats () const
Get pool usage statistics.
Static Public Attributes inherited from LockedPool
static const size_t ARENA_SIZE = 256*1024
Size of one arena of locked memory.
static const size_t ARENA_ALIGN = 16
Chunk alignment.
Detailed Description
Singleton class to keep track of locked (ie, non-swappable) memory, for use in std::allocator templates.
Some implementations of the STL allocate memory in some constructors (i.e., see MSVC's vector<T> implementation where it allocates 1 byte of memory in the allocator.) Due to the unpredictable order of static initializers, we have to make sure the LockedPoolManager instance exists before any other STL-based objects that use secure_allocator are created. So instead of having LockedPoolManager also be static-initialized, it is created on demand.
Definition at line 209 of file lockedpool.h.
Constructor & Destructor Documentation
LockedPoolManager()
LockedPoolManager::LockedPoolManager (std::unique_ptr< LockedPageAllocator > allocator) explicit private
Definition at line 361 of file lockedpool.cpp.
Member Function Documentation
CreateInstance()
void LockedPoolManager::CreateInstance () static private
Create a new LockedPoolManager specialized to the OS.
Definition at line 372 of file lockedpool.cpp.
References _instance, and LockedPool::allocator.
Referenced by Instance().
Instance()
static LockedPoolManager& LockedPoolManager::Instance () inline static
Return the current instance, or create it once.
Definition at line 213 of file lockedpool.h.
References _instance, CreateInstance(), and init_flag.
Referenced by secure_allocator< T >::allocate(), create_secure_allocator(), secure_allocator< T >::deallocate(), pooled_secure_allocator< T >::internal_secure_allocator::free(), pooled_secure_allocator< T >::internal_secure_allocator::malloc(), and RPCLockedMemoryInfo().
LockingFailed()
bool LockedPoolManager::LockingFailed () static private
Called when locking fails, warn the user here.
Definition at line 366 of file lockedpool.cpp.
Member Data Documentation
_instance
LockedPoolManager * LockedPoolManager::_instance = nullptr static private
Definition at line 227 of file lockedpool.h.
Referenced by CreateInstance(), and Instance().
init_flag
std::once_flag LockedPoolManager::init_flag static private
Definition at line 228 of file lockedpool.h.
Referenced by Instance().
The documentation for this class was generated from the following files:
src/support/lockedpool.h
src/support/lockedpool.cpp
Released under the MIT license