Dash Core: AppearanceWidget Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
AppearanceWidget Class Reference
#include <appearancewidget.h>
Public Slots
void accept ()
Signals
void appearanceChanged ()
Public Member Functions
AppearanceWidget (QWidget *parent=0)
~AppearanceWidget ()
void setModel (OptionsModel *model)
Private Slots
void updateTheme (const QString &toTheme=QString())
void updateFontFamily (int index)
void updateFontScale (int nScale)
void updateFontWeightNormal (int nValue, bool fForce=false)
void updateFontWeightBold (int nValue, bool fForce=false)
Private Member Functions
void updateWeightSlider ()
Private Attributes
Ui::AppearanceWidget * ui
QDataWidgetMapper * mapper
OptionsModel * model
bool fAcceptChanges
QString prevTheme
int prevScale
GUIUtil::FontFamily prevFontFamily
QFont::Weight prevWeightNormal
QFont::Weight prevWeightBold
Detailed Description
Definition at line 22 of file appearancewidget.h.
Constructor & Destructor Documentation
AppearanceWidget()
AppearanceWidget::AppearanceWidget (QWidget * parent = 0) explicit
Definition at line 21 of file appearancewidget.cpp.
References GUIUtil::fontFamilyToString(), GUIUtil::listThemes(), mapper, GUIUtil::Montserrat, GUIUtil::SystemDefault, ui, updateFontFamily(), updateFontScale(), updateFontWeightBold(), updateFontWeightNormal(), updateTheme(), and updateWeightSlider().
~AppearanceWidget()
AppearanceWidget::~AppearanceWidget ()
Definition at line 62 of file appearancewidget.cpp.
References fAcceptChanges, GUIUtil::getActiveTheme(), GUIUtil::getFontFamily(), GUIUtil::getFontScale(), GUIUtil::getFontWeightBold(), GUIUtil::getFontWeightNormal(), mapper, prevFontFamily, prevScale, prevTheme, prevWeightBold, prevWeightNormal, GUIUtil::setFontFamily(), GUIUtil::setFontScale(), GUIUtil::setFontWeightBold(), GUIUtil::setFontWeightNormal(), ui, and updateTheme().
Member Function Documentation
accept
void AppearanceWidget::accept () slot
Definition at line 101 of file appearancewidget.cpp.
References fAcceptChanges.
Referenced by OptionsDialog::on_okButton_clicked(), and GUIUtil::setupAppearance().
appearanceChanged
void AppearanceWidget::appearanceChanged () signal
Referenced by OptionsDialog::OptionsDialog().
setModel()
void AppearanceWidget::setModel (OptionsModel * model)
Definition at line 86 of file appearancewidget.cpp.
References OptionsModel::FontFamily, OptionsModel::FontScale, OptionsModel::FontWeightBold, OptionsModel::FontWeightNormal, mapper, model, OptionsModel::Theme, and ui.
Referenced by OptionsDialog::setModel(), and GUIUtil::setupAppearance().
updateFontFamily
void AppearanceWidget::updateFontFamily (int index) private slot
Definition at line 116 of file appearancewidget.cpp.
References AddressTablePriv::index(), GUIUtil::setFontFamily(), ui, and updateWeightSlider().
Referenced by AppearanceWidget().
updateFontScale
void AppearanceWidget::updateFontScale (int nScale) private slot
Definition at line 122 of file appearancewidget.cpp.
References GUIUtil::setFontScale().
Referenced by AppearanceWidget().
updateFontWeightBold
void AppearanceWidget::updateFontWeightBold (int nValue, bool fForce = false) private slot
Definition at line 138 of file appearancewidget.cpp.
References GUIUtil::setFontWeightBold(), GUIUtil::supportedWeightFromIndex(), and ui.
Referenced by AppearanceWidget(), and updateWeightSlider().
updateFontWeightNormal
void AppearanceWidget::updateFontWeightNormal (int nValue, bool fForce = false) private slot
Definition at line 127 of file appearancewidget.cpp.
References GUIUtil::setFontWeightNormal(), GUIUtil::supportedWeightFromIndex(), and ui.
Referenced by AppearanceWidget(), and updateWeightSlider().
updateTheme
void AppearanceWidget::updateTheme (const QString & toTheme = QString()) private slot
Definition at line 106 of file appearancewidget.cpp.
References GUIUtil::getActiveTheme(), GUIUtil::loadTheme(), and ui.
Referenced by AppearanceWidget(), and ~AppearanceWidget().
updateWeightSlider()
void AppearanceWidget::updateWeightSlider () private
Definition at line 149 of file appearancewidget.cpp.
References GUIUtil::getSupportedWeights(), ui, updateFontWeightBold(), and updateFontWeightNormal().
Referenced by AppearanceWidget(), and updateFontFamily().
Member Data Documentation
fAcceptChanges
bool AppearanceWidget::fAcceptChanges private
Definition at line 49 of file appearancewidget.h.
Referenced by accept(), and ~AppearanceWidget().
mapper
QDataWidgetMapper* AppearanceWidget::mapper private
Definition at line 47 of file appearancewidget.h.
Referenced by AppearanceWidget(), setModel(), and ~AppearanceWidget().
model
OptionsModel* AppearanceWidget::model private
Definition at line 48 of file appearancewidget.h.
Referenced by setModel().
prevFontFamily
GUIUtil::FontFamily AppearanceWidget::prevFontFamily private
Definition at line 52 of file appearancewidget.h.
Referenced by ~AppearanceWidget().
prevScale
int AppearanceWidget::prevScale private
Definition at line 51 of file appearancewidget.h.
Referenced by ~AppearanceWidget().
prevTheme
QString AppearanceWidget::prevTheme private
Definition at line 50 of file appearancewidget.h.
Referenced by ~AppearanceWidget().
prevWeightBold
QFont::Weight AppearanceWidget::prevWeightBold private
Definition at line 54 of file appearancewidget.h.
Referenced by ~AppearanceWidget().
prevWeightNormal
QFont::Weight AppearanceWidget::prevWeightNormal private
Definition at line 53 of file appearancewidget.h.
Referenced by ~AppearanceWidget().
ui
Ui::AppearanceWidget* AppearanceWidget::ui private
Definition at line 46 of file appearancewidget.h.
Referenced by AppearanceWidget(), setModel(), updateFontFamily(), updateFontWeightBold(), updateFontWeightNormal(), updateTheme(), updateWeightSlider(), and ~AppearanceWidget().
The documentation for this class was generated from the following files:
src/qt/appearancewidget.h
src/qt/appearancewidget.cpp
Released under the MIT license