Dash Core: CMnemonic Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMnemonic Class Reference
Copyright (c) 2013-2014 Tomas Dzetkulic Copyright (c) 2013-2014 Pavol Rusnak.
#include <bip39.h>
Static Public Member Functions
static SecureString Generate (int strength)
Copyright (c) 2013-2014 Tomas Dzetkulic Copyright (c) 2013-2014 Pavol Rusnak.
static SecureString FromData (const SecureVector &data, int len)
static bool Check (SecureString mnemonic)
static void ToSeed (SecureString mnemonic, SecureString passphrase, SecureVector &seedRet)
Detailed Description
Copyright (c) 2013-2014 Tomas Dzetkulic Copyright (c) 2013-2014 Pavol Rusnak.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 29 of file bip39.h.
Member Function Documentation
Check()
bool CMnemonic::Check (SecureString mnemonic) static
Definition at line 80 of file bip39.cpp.
References CSHA256::Finalize(), wordlist, and CSHA256::Write().
Referenced by CHDChain::SetMnemonic().
FromData()
SecureString CMnemonic::FromData (const SecureVector & data, int len) static
Definition at line 46 of file bip39.cpp.
References CSHA256::Finalize(), memcpy(), wordlist, and CSHA256::Write().
Referenced by Generate().
Generate()
SecureString CMnemonic::Generate (int strength) static
Copyright (c) 2013-2014 Tomas Dzetkulic Copyright (c) 2013-2014 Pavol Rusnak.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 34 of file bip39.cpp.
References FromData(), and GetRandBytes().
Referenced by CHDChain::SetMnemonic().
ToSeed()
void CMnemonic::ToSeed (SecureString mnemonic, SecureString passphrase, SecureVector & seedRet) static
Definition at line 152 of file bip39.cpp.
Referenced by CHDChain::SetMnemonic().
The documentation for this class was generated from the following files:
src/bip39.h
src/bip39.cpp
Released under the MIT license