Dash Core: CMasternodeMan Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodeMan Class Reference
#include <masternodeman.h>
Public Types
typedef std::pair< arith_uint256, CMasternode * > score_pair_t
typedef std::vector< score_pair_t > score_pair_vec_t
typedef std::pair< int, CMasternode > rank_pair_t
typedef std::vector< rank_pair_t > rank_pair_vec_t
Public Member Functions
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
CMasternodeMan ()
bool Add (CMasternode &mn)
Add an entry.
void AskForMN (CNode *pnode, const COutPoint &outpoint, CConnman &connman)
Ask (source) node for mnb.
void AskForMnb (CNode *pnode, const uint256 &hash)
bool PoSeBan (const COutPoint &outpoint)
bool AllowMixing (const COutPoint &outpoint)
bool DisallowMixing (const COutPoint &outpoint)
void Check ()
Check all Masternodes.
void CheckAndRemove (CConnman &connman)
Check all Masternodes and remove inactive.
void CheckAndRemove ()
This is dummy overload to be used for dumping/loading mncache.dat.
void Clear ()
Clear Masternode vector.
int CountMasternodes (int nProtocolVersion=-1)
Count Masternodes filtered by nProtocolVersion.
int CountEnabled (int nProtocolVersion=-1)
Count enabled Masternodes filtered by nProtocolVersion.
void DsegUpdate (CNode *pnode, CConnman &connman)
Count Masternodes by network type - NET_IPV4, NET_IPV6, NET_TOR.
bool Get (const COutPoint &outpoint, CMasternode &masternodeRet)
Versions of Find that are safe to use from outside the class.
bool Has (const COutPoint &outpoint)
bool GetMasternodeInfo (const COutPoint &outpoint, masternode_info_t &mnInfoRet)
bool GetMasternodeInfo (const CPubKey &pubKeyMasternode, masternode_info_t &mnInfoRet)
bool GetMasternodeInfo (const CScript &payee, masternode_info_t &mnInfoRet)
bool GetNextMasternodeInQueueForPayment (int nBlockHeight, bool fFilterSigTime, int &nCountRet, masternode_info_t &mnInfoRet)
Find an entry in the masternode list that is next to be paid.
bool GetNextMasternodeInQueueForPayment (bool fFilterSigTime, int &nCountRet, masternode_info_t &mnInfoRet)
Same as above but use current block height.
masternode_info_t FindRandomNotInVec (const std::vector< COutPoint > &vecToExclude, int nProtocolVersion=-1)
Find a random entry.
std::map< COutPoint, CMasternode > GetFullMasternodeMap ()
bool GetMasternodeRanks (rank_pair_vec_t &vecMasternodeRanksRet, int nBlockHeight=-1, int nMinProtocol=0)
bool GetMasternodeRank (const COutPoint &outpoint, int &nRankRet, int nBlockHeight=-1, int nMinProtocol=0)
void ProcessMasternodeConnections (CConnman &connman)
std::pair< CService, std::set< uint256 > > PopScheduledMnbRequestConnection ()
void ProcessMessage (CNode *pfrom, std::string &strCommand, CDataStream &vRecv, CConnman &connman)
void DoFullVerificationStep (CConnman &connman)
void CheckSameAddr ()
bool SendVerifyRequest (const CAddress &addr, const std::vector< CMasternode *> &vSortedByAddr, CConnman &connman)
void SendVerifyReply (CNode *pnode, CMasternodeVerification &mnv, CConnman &connman)
void ProcessVerifyReply (CNode *pnode, CMasternodeVerification &mnv)
void ProcessVerifyBroadcast (CNode *pnode, const CMasternodeVerification &mnv)
int size ()
Return the number of (unique) Masternodes.
std::string ToString () const
void UpdateMasternodeList (CMasternodeBroadcast mnb, CConnman &connman)
Update masternode list and maps using provided CMasternodeBroadcast.
bool CheckMnbAndUpdateMasternodeList (CNode *pfrom, CMasternodeBroadcast mnb, int &nDos, CConnman &connman)
Perform complete check and only then update list and maps.
bool IsMnbRecoveryRequested (const uint256 &hash)
void UpdateLastPaid (const CBlockIndex *pindex)
void AddDirtyGovernanceObjectHash (const uint256 &nHash)
std::vector< uint256 > GetAndClearDirtyGovernanceObjectHashes ()
bool IsWatchdogActive ()
void UpdateWatchdogVoteTime (const COutPoint &outpoint, uint64_t nVoteTime=0)
bool AddGovernanceVote (const COutPoint &outpoint, uint256 nGovernanceObjectHash)
void RemoveGovernanceObject (uint256 nGovernanceObjectHash)
void CheckMasternode (const CPubKey &pubKeyMasternode, bool fForce)
bool IsMasternodePingedWithin (const COutPoint &outpoint, int nSeconds, int64_t nTimeToCheckAt=-1)
void SetMasternodeLastPing (const COutPoint &outpoint, const CMasternodePing &mnp)
void UpdatedBlockTip (const CBlockIndex *pindex)
void NotifyMasternodeUpdates (CConnman &connman)
Called to notify CGovernanceManager that the masternode index has been updated.
Public Attributes
std::map< uint256, std::pair< int64_t, CMasternodeBroadcast > > mapSeenMasternodeBroadcast
std::map< uint256, CMasternodePing > mapSeenMasternodePing
std::map< uint256, CMasternodeVerification > mapSeenMasternodeVerification
int64_t nDsqCount
ADD_SERIALIZE_METHODS
Private Member Functions
CMasternode * Find (const COutPoint &outpoint)
Find an entry.
bool GetMasternodeScores (const uint256 &nBlockHash, score_pair_vec_t &vecMasternodeScoresRet, int nMinProtocol=0)
Private Attributes
CCriticalSection cs
int nCachedBlockHeight
std::map< COutPoint, CMasternode > mapMasternodes
std::map< CNetAddr, int64_t > mAskedUsForMasternodeList
std::map< CNetAddr, int64_t > mWeAskedForMasternodeList
std::map< COutPoint, std::map< CNetAddr, int64_t > > mWeAskedForMasternodeListEntry
std::map< CNetAddr, CMasternodeVerification > mWeAskedForVerification
std::map< uint256, std::pair< int64_t, std::set< CNetAddr > > > mMnbRecoveryRequests
std::map< uint256, std::vector< CMasternodeBroadcast > > mMnbRecoveryGoodReplies
std::list< std::pair< CService, uint256 > > listScheduledMnbRequestConnections
bool fMasternodesAdded
Set when masternodes are added, cleared when CGovernanceManager is notified.
bool fMasternodesRemoved
Set when masternodes are removed, cleared when CGovernanceManager is notified.
std::vector< uint256 > vecDirtyGovernanceObjectHashes
int64_t nLastWatchdogVoteTime
Static Private Attributes
static const std::string SERIALIZATION_VERSION_STRING = "CMasternodeMan-Version-7"
static const int DSEG_UPDATE_SECONDS = 3 * 60 * 60
static const int LAST_PAID_SCAN_BLOCKS = 100
static const int MIN_POSE_PROTO_VERSION = 70203
static const int MAX_POSE_CONNECTIONS = 10
static const int MAX_POSE_RANK = 10
static const int MAX_POSE_BLOCKS = 10
static const int MNB_RECOVERY_QUORUM_TOTAL = 10
static const int MNB_RECOVERY_QUORUM_REQUIRED = 6
static const int MNB_RECOVERY_MAX_ASK_ENTRIES = 10
static const int MNB_RECOVERY_WAIT_SECONDS = 60
static const int MNB_RECOVERY_RETRY_SECONDS = 3 * 60 * 60
Friends
class CMasternodeSync
Detailed Description
Definition at line 18 of file masternodeman.h.
Member Typedef Documentation
rank_pair_t
typedef std::pair<int, CMasternode> CMasternodeMan::rank_pair_t
Definition at line 23 of file masternodeman.h.
rank_pair_vec_t
typedef std::vector<rank_pair_t> CMasternodeMan::rank_pair_vec_t
Definition at line 24 of file masternodeman.h.
score_pair_t
typedef std::pair<arith_uint256, CMasternode*> CMasternodeMan::score_pair_t
Definition at line 21 of file masternodeman.h.
score_pair_vec_t
typedef std::vector<score_pair_t> CMasternodeMan::score_pair_vec_t
Definition at line 22 of file masternodeman.h.
Constructor & Destructor Documentation
CMasternodeMan()
CMasternodeMan::CMasternodeMan ()
Definition at line 52 of file masternodeman.cpp.
Member Function Documentation
Add()
bool CMasternodeMan::Add (CMasternode & mn)
Add an entry.
Definition at line 71 of file masternodeman.cpp.
References masternode_info_t::addr, cs, fMasternodesAdded, Has(), LOCK, LogPrint(), mapMasternodes, CTxIn::prevout, size(), CService::ToString(), and masternode_info_t::vin.
Referenced by CheckMnbAndUpdateMasternodeList(), and UpdateMasternodeList().
AddDirtyGovernanceObjectHash()
void CMasternodeMan::AddDirtyGovernanceObjectHash (const uint256 & nHash) inline
Definition at line 206 of file masternodeman.h.
References LOCK.
Referenced by CMasternode::FlagGovernanceItemsAsDirty().
AddGovernanceVote()
bool CMasternodeMan::AddGovernanceVote (const COutPoint & outpoint, uint256 nGovernanceObjectHash)
Definition at line 1483 of file masternodeman.cpp.
References CMasternode::AddGovernanceVote(), cs, Find(), and LOCK.
Referenced by CGovernanceObject::ProcessVote().
AllowMixing()
bool CMasternodeMan::AllowMixing (const COutPoint & outpoint)
Definition at line 112 of file masternodeman.cpp.
References cs, CMasternode::fAllowMixingTx, Find(), LOCK, nDsqCount, and masternode_info_t::nLastDsq.
Referenced by CPrivateSendServer::ProcessMessage(), and CPrivateSendClient::ProcessMessage().
AskForMN()
void CMasternodeMan::AskForMN (CNode * pnode, const COutPoint & outpoint, CConnman & connman)
Ask (source) node for mnb.
Definition at line 83 of file masternodeman.cpp.
References CNode::addr, cs, NetMsgType::DSEG, DSEG_UPDATE_SECONDS, GetTime(), LOCK, LogPrintf, mWeAskedForMasternodeListEntry, CConnman::PushMessage(), CService::ToString(), and COutPoint::ToStringShort().
Referenced by CMasternodePaymentVote::IsValid(), CTxLockVote::IsValid(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), ProcessMessage(), CMasternodePayments::ProcessMessage(), and CGovernanceObject::ProcessVote().
AskForMnb()
void CMasternodeMan::AskForMnb (CNode * pnode, const uint256 & hash)
Check()
void CMasternodeMan::Check ()
Check all Masternodes.
Definition at line 150 of file masternodeman.cpp.
References cs, IsWatchdogActive(), LOCK, LogPrint(), mapMasternodes, and nLastWatchdogVoteTime.
Referenced by CheckAndRemove(), and ThreadCheckPrivateSend().
CheckAndRemove() [1/2]
void CMasternodeMan::CheckAndRemove (CConnman & connman)
Check all Masternodes and remove inactive.
Definition at line 161 of file masternodeman.cpp.
References Check(), CheckMnbAndUpdateMasternodeList(), cs, cs_main, fMasternodesRemoved, CMasternodeBroadcast::GetHash(), GetMasternodeRanks(), GetRandInt(), GetTime(), CMasternodeSync::IsMasternodeListSynced(), IsMnbRecoveryRequested(), CMasternodeSync::IsSynced(), listScheduledMnbRequestConnections, LOCK, LOCK2, LogPrint(), LogPrintf, mapMasternodes, mapSeenMasternodeBroadcast, mapSeenMasternodePing, mapSeenMasternodeVerification, mAskedUsForMasternodeList, masternodeSync, MAX_POSE_BLOCKS, mMnbRecoveryGoodReplies, mMnbRecoveryRequests, MNB_RECOVERY_MAX_ASK_ENTRIES, MNB_RECOVERY_QUORUM_REQUIRED, MNB_RECOVERY_QUORUM_TOTAL, MNB_RECOVERY_RETRY_SECONDS, MNB_RECOVERY_WAIT_SECONDS, mWeAskedForMasternodeList, mWeAskedForMasternodeListEntry, mWeAskedForVerification, nCachedBlockHeight, NotifyMasternodeUpdates(), size(), and ToString().
Referenced by ThreadCheckPrivateSend().
CheckAndRemove() [2/2]
void CMasternodeMan::CheckAndRemove () inline
This is dummy overload to be used for dumping/loading mncache.dat.
Definition at line 143 of file masternodeman.h.
CheckMasternode()
void CMasternodeMan::CheckMasternode (const CPubKey & pubKeyMasternode, bool fForce)
Definition at line 1502 of file masternodeman.cpp.
References cs, LOCK, and mapMasternodes.
Referenced by CActiveMasternode::ManageStateRemote().
CheckMnbAndUpdateMasternodeList()
bool CMasternodeMan::CheckMnbAndUpdateMasternodeList (CNode * pfrom, CMasternodeBroadcast mnb, int & nDos, CConnman & connman)
Perform complete check and only then update list and maps.
Definition at line 1351 of file masternodeman.cpp.
References activeMasternode, Add(), masternode_info_t::addr, CNode::addr, CMasternodeSync::BumpAssetLastTime(), CMasternode::Check(), CMasternodeBroadcast::CheckOutpoint(), cs, cs_main, Find(), fMasterNode, CMasternodeBroadcast::fRecovery, GetAdjustedTime(), CMasternodeBroadcast::GetHash(), CMasternode::GetStateString(), GetTime(), IsMnbRecoveryRequested(), CMasternode::IsValidStateForAutoStart(), CMasternode::lastPing, LOCK, LogPrint(), LogPrintf, CActiveMasternode::ManageState(), mapSeenMasternodeBroadcast, MASTERNODE_MIN_MNP_SECONDS, MASTERNODE_NEW_START_REQUIRED_SECONDS, MASTERNODE_POSE_BAN_MAX_SCORE, masternodeSync, mMnbRecoveryGoodReplies, mMnbRecoveryRequests, masternode_info_t::nActiveState, CMasternode::nPoSeBanScore, masternode_info_t::nProtocolVersion, CTxIn::prevout, PROTOCOL_VERSION, CActiveMasternode::pubKeyMasternode, masternode_info_t::pubKeyMasternode, CMasternodeBroadcast::Relay(), CMasternodePing::sigTime, masternode_info_t::sigTime, CMasternodeBroadcast::SimpleCheck(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeBroadcast::Update(), and masternode_info_t::vin.
Referenced by CheckAndRemove(), masternodebroadcast(), and ProcessMessage().
CheckSameAddr()
void CMasternodeMan::CheckSameAddr ()
Definition at line 986 of file masternodeman.cpp.
References masternode_info_t::addr, cs, CMasternode::IncreasePoSeBanScore(), CMasternode::IsEnabled(), CMasternode::IsPoSeVerified(), CMasternode::IsPreEnabled(), CMasternodeSync::IsSynced(), LOCK, LogPrintf, mapMasternodes, masternodeSync, CTxIn::prevout, COutPoint::ToStringShort(), and masternode_info_t::vin.
Referenced by UpdatedBlockTip().
Clear()
void CMasternodeMan::Clear ()
Clear Masternode vector.
Definition at line 344 of file masternodeman.cpp.
References cs, LOCK, mapMasternodes, mapSeenMasternodeBroadcast, mapSeenMasternodePing, mAskedUsForMasternodeList, mWeAskedForMasternodeList, mWeAskedForMasternodeListEntry, nDsqCount, and nLastWatchdogVoteTime.
CountEnabled()
int CMasternodeMan::CountEnabled (int nProtocolVersion = -1)
Count enabled Masternodes filtered by nProtocolVersion.
Masternode nProtocolVersion should match or be above the one specified in param here.
Definition at line 371 of file masternodeman.cpp.
References cs, CMasternodePayments::GetMinMasternodePaymentsProto(), LOCK, mapMasternodes, and mnpayments.
Referenced by CPrivateSendClient::DoAutomaticDenominating(), FindRandomNotInVec(), ClientModel::getMasternodeCountString(), masternode(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), CPrivateSendClient::StartNewQueue(), and CGovernanceObject::UpdateSentinelVariables().
CountMasternodes()
int CMasternodeMan::CountMasternodes (int nProtocolVersion = -1)
Count Masternodes filtered by nProtocolVersion.
Masternode nProtocolVersion should match or be above the one specified in param here.
Definition at line 357 of file masternodeman.cpp.
References cs, CMasternodePayments::GetMinMasternodePaymentsProto(), LOCK, mapMasternodes, and mnpayments.
Referenced by GetNextMasternodeInQueueForPayment(), and CMasternodeSync::ProcessTick().
DisallowMixing()
bool CMasternodeMan::DisallowMixing (const COutPoint & outpoint)
Definition at line 126 of file masternodeman.cpp.
References cs, CMasternode::fAllowMixingTx, Find(), and LOCK.
Referenced by ProcessMessage().
DoFullVerificationStep()
void CMasternodeMan::DoFullVerificationStep (CConnman & connman)
Definition at line 905 of file masternodeman.cpp.
References activeMasternode, cs, cs_main, GetMasternodeRanks(), CMasternodeSync::IsSynced(), LOCK2, LogPrint(), mapMasternodes, masternodeSync, MAX_POSE_CONNECTIONS, MAX_POSE_RANK, MIN_POSE_PROTO_VERSION, nCachedBlockHeight, NODE_NETWORK, CActiveMasternode::outpoint, and SendVerifyRequest().
Referenced by ThreadCheckPrivateSend().
DsegUpdate()
void CMasternodeMan::DsegUpdate (CNode * pnode, CConnman & connman)
Count Masternodes by network type - NET_IPV4, NET_IPV6, NET_TOR.
Definition at line 402 of file masternodeman.cpp.
References CNode::addr, cs, NetMsgType::DSEG, DSEG_UPDATE_SECONDS, GetTime(), CNetAddr::IsLocal(), CNetAddr::IsRFC1918(), LOCK, LogPrint(), LogPrintf, CBaseChainParams::MAIN, mWeAskedForMasternodeList, Params(), CConnman::PushMessage(), and CService::ToString().
Referenced by CMasternodeSync::ProcessTick().
Find()
CMasternode * CMasternodeMan::Find (const COutPoint & outpoint) private
Find an entry.
Definition at line 423 of file masternodeman.cpp.
References cs, LOCK, and mapMasternodes.
Referenced by AddGovernanceVote(), AllowMixing(), CheckMnbAndUpdateMasternodeList(), DisallowMixing(), IsMasternodePingedWithin(), PoSeBan(), ProcessMessage(), ProcessVerifyBroadcast(), SetMasternodeLastPing(), UpdateMasternodeList(), and UpdateWatchdogVoteTime().
FindRandomNotInVec()
masternode_info_t CMasternodeMan::FindRandomNotInVec (const std::vector< COutPoint > & vecToExclude, int nProtocolVersion = -1)
Find a random entry.
Definition at line 569 of file masternodeman.cpp.
References CountEnabled(), cs, CMasternode::GetInfo(), CMasternodePayments::GetMinMasternodePaymentsProto(), CMasternode::IsEnabled(), LOCK, LogPrint(), LogPrintf, mapMasternodes, mnpayments, masternode_info_t::nProtocolVersion, CTxIn::prevout, COutPoint::ToStringShort(), and masternode_info_t::vin.
Referenced by CPrivateSendClient::StartNewQueue().
Get()
bool CMasternodeMan::Get (const COutPoint & outpoint, CMasternode & masternodeRet)
Versions of Find that are safe to use from outside the class.
Definition at line 430 of file masternodeman.cpp.
References cs, LOCK, and mapMasternodes.
Referenced by CGovernanceManager::GetCurrentVotes(), gobject(), masternode(), ProcessMessage(), and voteraw().
GetAndClearDirtyGovernanceObjectHashes()
std::vector<uint256> CMasternodeMan::GetAndClearDirtyGovernanceObjectHashes () inline
Definition at line 212 of file masternodeman.h.
References LOCK.
Referenced by CGovernanceManager::UpdateCachesAndClean().
GetFullMasternodeMap()
std::map<COutPoint, CMasternode> CMasternodeMan::GetFullMasternodeMap () inline
Definition at line 176 of file masternodeman.h.
Referenced by CGovernanceManager::GetCurrentVotes(), masternodelist(), and MasternodeList::updateNodeList().
GetMasternodeInfo() [1/3]
bool CMasternodeMan::GetMasternodeInfo (const COutPoint & outpoint, masternode_info_t & mnInfoRet)
Definition at line 443 of file masternodeman.cpp.
References cs, LOCK, and mapMasternodes.
Referenced by CTxLockVote::CheckSignature(), ComputeBlockVersion(), CGovernanceVote::IsValid(), CMasternodePaymentVote::IsValid(), CGovernanceObject::IsValidLocally(), CPrivateSendClient::JoinExistingQueue(), CActiveMasternode::ManageStateRemote(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), CMasternodePayments::ProcessMessage(), and MasternodeList::updateMyMasternodeInfo().
GetMasternodeInfo() [2/3]
bool CMasternodeMan::GetMasternodeInfo (const CPubKey & pubKeyMasternode, masternode_info_t & mnInfoRet)
Definition at line 454 of file masternodeman.cpp.
References cs, LOCK, and mapMasternodes.
GetMasternodeInfo() [3/3]
bool CMasternodeMan::GetMasternodeInfo (const CScript & payee, masternode_info_t & mnInfoRet)
Definition at line 466 of file masternodeman.cpp.
References cs, GetScriptForDestination(), LOCK, and mapMasternodes.
GetMasternodeRank()
bool CMasternodeMan::GetMasternodeRank (const COutPoint & outpoint, int & nRankRet, int nBlockHeight = -1, int nMinProtocol = 0)
Definition at line 635 of file masternodeman.cpp.
References cs, GetBlockHash(), GetMasternodeScores(), CMasternodeSync::IsMasternodeListSynced(), LOCK, LogPrintf, and masternodeSync.
Referenced by CMasternodePaymentVote::IsValid(), CTxLockVote::IsValid(), CMasternodePayments::ProcessBlock(), ProcessVerifyBroadcast(), and CInstantSend::Vote().
GetMasternodeRanks()
bool CMasternodeMan::GetMasternodeRanks (CMasternodeMan::rank_pair_vec_t & vecMasternodeRanksRet, int nBlockHeight = -1, int nMinProtocol = 0)
Definition at line 667 of file masternodeman.cpp.
References cs, GetBlockHash(), GetMasternodeScores(), CMasternodeSync::IsMasternodeListSynced(), LOCK, LogPrintf, and masternodeSync.
Referenced by CheckAndRemove(), CMasternodePayments::CheckPreviousBlockVotes(), DoFullVerificationStep(), and masternodelist().
GetMasternodeScores()
bool CMasternodeMan::GetMasternodeScores (const uint256 & nBlockHash, CMasternodeMan::score_pair_vec_t & vecMasternodeScoresRet, int nMinProtocol = 0) private
Definition at line 612 of file masternodeman.cpp.
References AssertLockHeld, cs, CMasternodeSync::IsMasternodeListSynced(), mapMasternodes, and masternodeSync.
Referenced by GetMasternodeRank(), and GetMasternodeRanks().
GetNextMasternodeInQueueForPayment() [1/2]
bool CMasternodeMan::GetNextMasternodeInQueueForPayment (int nBlockHeight, bool fFilterSigTime, int & nCountRet, masternode_info_t & mnInfoRet)
Find an entry in the masternode list that is next to be paid.
Definition at line 493 of file masternodeman.cpp.
References CMasternode::CalculateScore(), CountMasternodes(), cs, cs_main, masternode_info_t::fInfoValid, GetAdjustedTime(), GetBlockHash(), CMasternode::GetInfo(), CMasternodePayments::GetMinMasternodePaymentsProto(), GetUTXOConfirmations(), CMasternodePayments::IsScheduled(), CMasternodeSync::IsWinnersListSynced(), LOCK2, LogPrintf, mapMasternodes, masternodeSync, mnpayments, and PAIRTYPE.
Referenced by CMasternodePayments::FillBlockPayee(), GetNextMasternodeInQueueForPayment(), masternode(), and CMasternodePayments::ProcessBlock().
GetNextMasternodeInQueueForPayment() [2/2]
bool CMasternodeMan::GetNextMasternodeInQueueForPayment (bool fFilterSigTime, int & nCountRet, masternode_info_t & mnInfoRet)
Same as above but use current block height.
Definition at line 488 of file masternodeman.cpp.
References GetNextMasternodeInQueueForPayment(), and nCachedBlockHeight.
Has()
bool CMasternodeMan::Has (const COutPoint & outpoint)
Definition at line 479 of file masternodeman.cpp.
References cs, LOCK, and mapMasternodes.
Referenced by Add(), CGovernanceObject::CheckOrphanVotes(), CGovernanceObject::ClearMasternodeVotes(), gobject(), CTxLockVote::IsValid(), CGovernanceObject::ProcessVote(), CActiveMasternode::SendMasternodePing(), and MasternodeList::StartAll().
IsMasternodePingedWithin()
bool CMasternodeMan::IsMasternodePingedWithin (const COutPoint & outpoint, int nSeconds, int64_t nTimeToCheckAt = -1)
Definition at line 1513 of file masternodeman.cpp.
References cs, Find(), CMasternode::IsPingedWithin(), and LOCK.
Referenced by CActiveMasternode::SendMasternodePing().
IsMnbRecoveryRequested()
bool CMasternodeMan::IsMnbRecoveryRequested (const uint256 & hash) inline
Definition at line 202 of file masternodeman.h.
Referenced by AlreadyHave(), CheckAndRemove(), and CheckMnbAndUpdateMasternodeList().
IsWatchdogActive()
bool CMasternodeMan::IsWatchdogActive ()
Definition at line 1476 of file masternodeman.cpp.
References cs, GetTime(), LOCK, MASTERNODE_WATCHDOG_MAX_SECONDS, and nLastWatchdogVoteTime.
Referenced by Check(), and CMasternode::Check().
NotifyMasternodeUpdates()
void CMasternodeMan::NotifyMasternodeUpdates (CConnman & connman)
Called to notify CGovernanceManager that the masternode index has been updated.
Must be called while not holding the CMasternodeMan::cs mutex
Definition at line 1556 of file masternodeman.cpp.
References CGovernanceManager::CheckMasternodeOrphanObjects(), CGovernanceManager::CheckMasternodeOrphanVotes(), cs, fMasternodesAdded, fMasternodesRemoved, governance, LOCK, and CGovernanceManager::UpdateCachesAndClean().
Referenced by CheckAndRemove(), masternode(), masternodebroadcast(), ProcessMessage(), MasternodeList::StartAlias(), and MasternodeList::StartAll().
PopScheduledMnbRequestConnection()
std::pair< CService, std::set< uint256 > > CMasternodeMan::PopScheduledMnbRequestConnection ()
Definition at line 713 of file masternodeman.cpp.
References cs, listScheduledMnbRequestConnections, and LOCK.
Referenced by CConnman::ThreadMnbRequestConnections().
PoSeBan()
bool CMasternodeMan::PoSeBan (const COutPoint & outpoint)
Definition at line 138 of file masternodeman.cpp.
References cs, Find(), LOCK, and CMasternode::PoSeBan().
Referenced by CInstantSend::ProcessTxLockVote().
ProcessMasternodeConnections()
void CMasternodeMan::ProcessMasternodeConnections (CConnman & connman)
Definition at line 696 of file masternodeman.cpp.
References CNode::addr, CConnman::AllNodes, CNode::fDisconnect, CNode::fMasternode, CConnman::ForEachNode(), CNode::id, CPrivateSendClient::IsMixingMasternode(), LogPrintf, Params(), privateSendClient, CBaseChainParams::REGTEST, and CService::ToString().
Referenced by ThreadCheckPrivateSend().
ProcessMessage()
void CMasternodeMan::ProcessMessage (CNode * pfrom, std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 741 of file masternodeman.cpp.
References CConnman::AddNewAddress(), CNode::addr, AskForMN(), CheckMnbAndUpdateMasternodeList(), cs, cs_main, NetMsgType::DSEG, DSEG_UPDATE_SECONDS, Find(), fLiteMode, fMasternodesAdded, CMasternodePing::GetHash(), CNode::GetId(), GetTime(), CNode::id, CMasternodeSync::IsBlockchainSynced(), CNetAddr::IsLocal(), CMasternodeSync::IsMasternodeListSynced(), CNetAddr::IsRFC1918(), CMasternodeSync::IsSynced(), LOCK, LOCK2, LogPrint(), LogPrintf, CBaseChainParams::MAIN, mapMasternodes, mapSeenMasternodeBroadcast, mapSeenMasternodePing, mAskedUsForMasternodeList, MASTERNODE_SYNC_LIST, masternodeSync, Misbehaving(), NetMsgType::MNANNOUNCE, NetMsgType::MNPING, NetMsgType::MNVERIFY, MSG_MASTERNODE_ANNOUNCE, MSG_MASTERNODE_PING, CChainParams::NetworkIDString(), NODE_NETWORK, NotifyMasternodeUpdates(), Params(), ProcessVerifyBroadcast(), ProcessVerifyReply(), CNode::PushInventory(), CConnman::PushMessage(), SendVerifyReply(), CNode::setAskFor, NetMsgType::SYNCSTATUSCOUNT, and UpdateWatchdogVoteTime().
Referenced by ProcessMessage().
ProcessVerifyBroadcast()
void CMasternodeMan::ProcessVerifyBroadcast (CNode * pnode, const CMasternodeVerification & mnv)
Definition at line 1212 of file masternodeman.cpp.
References CMasternodeVerification::addr, cs, Find(), GetBlockHash(), CMasternodeVerification::GetHash(), GetMasternodeRank(), CNode::id, LOCK, LogPrint(), LogPrintf, mapMasternodes, mapSeenMasternodeVerification, MAX_POSE_BLOCKS, MAX_POSE_RANK, MIN_POSE_PROTO_VERSION, Misbehaving(), CMasternodeVerification::nBlockHeight, nCachedBlockHeight, CMasternodeVerification::nonce, CTxIn::prevout, masternode_info_t::pubKeyMasternode, CMasternodeVerification::Relay(), strprintf, base_blob< BITS >::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeVerification::vchSig1, CMasternodeVerification::vchSig2, CMessageSigner::VerifyMessage(), CMasternodeVerification::vin1, and CMasternodeVerification::vin2.
Referenced by ProcessMessage().
ProcessVerifyReply()
void CMasternodeMan::ProcessVerifyReply (CNode * pnode, CMasternodeVerification & mnv)
Definition at line 1103 of file masternodeman.cpp.
References activeMasternode, CNetFulfilledRequestManager::AddFulfilledRequest(), CMasternodeVerification::addr, CNode::addr, cs, CMasternode::DecreasePoSeBanScore(), GetBlockHash(), CMasternodeVerification::GetHash(), CNetFulfilledRequestManager::HasFulfilledRequest(), CNode::id, CMasternode::IncreasePoSeBanScore(), CActiveMasternode::keyMasternode, LOCK, LogPrint(), LogPrintf, mapMasternodes, mapSeenMasternodeVerification, Misbehaving(), NetMsgType::MNVERIFY, mWeAskedForVerification, CMasternodeVerification::nBlockHeight, netfulfilledman, NODE_NETWORK, CMasternodeVerification::nonce, CMasternode::nPoSeBanScore, CActiveMasternode::outpoint, CTxIn::prevout, CActiveMasternode::pubKeyMasternode, CMasternodeVerification::Relay(), CMessageSigner::SignMessage(), strprintf, base_blob< BITS >::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeVerification::vchSig1, CMasternodeVerification::vchSig2, CMessageSigner::VerifyMessage(), masternode_info_t::vin, CMasternodeVerification::vin1, and CMasternodeVerification::vin2.
Referenced by ProcessMessage().
RemoveGovernanceObject()
void CMasternodeMan::RemoveGovernanceObject (uint256 nGovernanceObjectHash)
Definition at line 1494 of file masternodeman.cpp.
References cs, LOCK, and mapMasternodes.
Referenced by CGovernanceManager::UpdateCachesAndClean().
SendVerifyReply()
void CMasternodeMan::SendVerifyReply (CNode * pnode, CMasternodeVerification & mnv, CConnman & connman)
Definition at line 1063 of file masternodeman.cpp.
References activeMasternode, CNetFulfilledRequestManager::AddFulfilledRequest(), CNode::addr, fMasterNode, GetBlockHash(), CNetFulfilledRequestManager::HasFulfilledRequest(), CNode::id, CActiveMasternode::keyMasternode, LogPrintf, Misbehaving(), NetMsgType::MNVERIFY, CMasternodeVerification::nBlockHeight, netfulfilledman, CMasternodeVerification::nonce, CActiveMasternode::pubKeyMasternode, CConnman::PushMessage(), CActiveMasternode::service, CMessageSigner::SignMessage(), strprintf, base_blob< BITS >::ToString(), CService::ToString(), CMasternodeVerification::vchSig1, and CMessageSigner::VerifyMessage().
Referenced by ProcessMessage().
SendVerifyRequest()
bool CMasternodeMan::SendVerifyRequest (const CAddress & addr, const std::vector< CMasternode *> & vSortedByAddr, CConnman & connman)
Definition at line 1039 of file masternodeman.cpp.
References CNetFulfilledRequestManager::AddFulfilledRequest(), CConnman::ConnectNode(), GetRandInt(), CNetFulfilledRequestManager::HasFulfilledRequest(), LogPrint(), LogPrintf, NetMsgType::MNVERIFY, mWeAskedForVerification, nCachedBlockHeight, netfulfilledman, CMasternodeVerification::nonce, CConnman::PushMessage(), strprintf, and CService::ToString().
Referenced by DoFullVerificationStep().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodeMan::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 97 of file masternodeman.h.
References LOCK, and READWRITE.
SetMasternodeLastPing()
void CMasternodeMan::SetMasternodeLastPing (const COutPoint & outpoint, const CMasternodePing & mnp)
Definition at line 1520 of file masternodeman.cpp.
References cs, Find(), CMasternodePing::fSentinelIsCurrent, CMasternodePing::GetHash(), CMasternodeBroadcast::GetHash(), CMasternode::lastPing, LOCK, mapSeenMasternodeBroadcast, mapSeenMasternodePing, CTxIn::prevout, CMasternodePing::sigTime, UpdateWatchdogVoteTime(), and CMasternodePing::vin.
Referenced by CActiveMasternode::SendMasternodePing().
size()
int CMasternodeMan::size () inline
Return the number of (unique) Masternodes.
Definition at line 194 of file masternodeman.h.
Referenced by Add(), AppInit2(), CMasternode::Check(), CheckAndRemove(), CPrivateSendClient::DoAutomaticDenominating(), ClientModel::getMasternodeCountString(), CMasternodePayments::GetStorageLimit(), masternode(), and CGovernanceManager::RequestGovernanceObjectVotes().
ToString()
std::string CMasternodeMan::ToString () const
Definition at line 1316 of file masternodeman.cpp.
References mapMasternodes, mAskedUsForMasternodeList, mWeAskedForMasternodeList, mWeAskedForMasternodeListEntry, and nDsqCount.
Referenced by CheckAndRemove().
UpdatedBlockTip()
void CMasternodeMan::UpdatedBlockTip (const CBlockIndex * pindex)
Definition at line 1543 of file masternodeman.cpp.
References CheckSameAddr(), fMasterNode, LogPrint(), nCachedBlockHeight, CBlockIndex::nHeight, and UpdateLastPaid().
Referenced by CDSNotificationInterface::UpdatedBlockTip().
UpdateLastPaid()
void CMasternodeMan::UpdateLastPaid (const CBlockIndex * pindex)
Definition at line 1444 of file masternodeman.cpp.
References cs, fLiteMode, fMasterNode, CMasternodePayments::GetStorageLimit(), CMasternodeSync::IsWinnersListSynced(), LAST_PAID_SCAN_BLOCKS, LOCK, mapMasternodes, masternodeSync, and mnpayments.
Referenced by masternode(), masternodelist(), and UpdatedBlockTip().
UpdateMasternodeList()
void CMasternodeMan::UpdateMasternodeList (CMasternodeBroadcast mnb, CConnman & connman)
Update masternode list and maps using provided CMasternodeBroadcast.
Definition at line 1329 of file masternodeman.cpp.
References Add(), masternode_info_t::addr, CMasternodeSync::BumpAssetLastTime(), cs, cs_main, Find(), CMasternodePing::GetHash(), CMasternodeBroadcast::GetHash(), GetTime(), CMasternode::lastPing, LOCK2, LogPrintf, mapSeenMasternodeBroadcast, mapSeenMasternodePing, masternodeSync, CTxIn::prevout, CService::ToString(), COutPoint::ToStringShort(), and masternode_info_t::vin.
Referenced by masternode(), masternodebroadcast(), MasternodeList::StartAlias(), and MasternodeList::StartAll().
UpdateWatchdogVoteTime()
void CMasternodeMan::UpdateWatchdogVoteTime (const COutPoint & outpoint, uint64_t nVoteTime = 0)
Definition at line 1465 of file masternodeman.cpp.
References cs, Find(), GetTime(), LOCK, nLastWatchdogVoteTime, and CMasternode::UpdateWatchdogVoteTime().
Referenced by ProcessMessage(), CGovernanceManager::ProcessVote(), and SetMasternodeLastPing().
Friends And Related Function Documentation
CMasternodeSync
friend class CMasternodeSync friend
Definition at line 77 of file masternodeman.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodeMan::ADD_SERIALIZE_METHODS
Definition at line 94 of file masternodeman.h.
cs
CCriticalSection CMasternodeMan::cs mutable private
Definition at line 46 of file masternodeman.h.
Referenced by Add(), AddGovernanceVote(), AllowMixing(), AskForMN(), Check(), CheckAndRemove(), CheckMasternode(), CheckMnbAndUpdateMasternodeList(), CheckSameAddr(), Clear(), CountEnabled(), CountMasternodes(), DisallowMixing(), DoFullVerificationStep(), DsegUpdate(), Find(), FindRandomNotInVec(), Get(), GetMasternodeInfo(), GetMasternodeRank(), GetMasternodeRanks(), GetMasternodeScores(), GetNextMasternodeInQueueForPayment(), Has(), IsMasternodePingedWithin(), IsWatchdogActive(), NotifyMasternodeUpdates(), PopScheduledMnbRequestConnection(), PoSeBan(), ProcessMessage(), ProcessVerifyBroadcast(), ProcessVerifyReply(), RemoveGovernanceObject(), SetMasternodeLastPing(), UpdateLastPaid(), UpdateMasternodeList(), and UpdateWatchdogVoteTime().
DSEG_UPDATE_SECONDS
const int CMasternodeMan::DSEG_UPDATE_SECONDS = 3 * 60 * 60 static private
Definition at line 29 of file masternodeman.h.
Referenced by AskForMN(), DsegUpdate(), and ProcessMessage().
fMasternodesAdded
bool CMasternodeMan::fMasternodesAdded private
Set when masternodes are added, cleared when CGovernanceManager is notified.
Definition at line 68 of file masternodeman.h.
Referenced by Add(), NotifyMasternodeUpdates(), and ProcessMessage().
fMasternodesRemoved
bool CMasternodeMan::fMasternodesRemoved private
Set when masternodes are removed, cleared when CGovernanceManager is notified.
Definition at line 71 of file masternodeman.h.
Referenced by CheckAndRemove(), and NotifyMasternodeUpdates().
LAST_PAID_SCAN_BLOCKS
const int CMasternodeMan::LAST_PAID_SCAN_BLOCKS = 100 static private
Definition at line 31 of file masternodeman.h.
Referenced by UpdateLastPaid().
listScheduledMnbRequestConnections
std::list< std::pair<CService, uint256> > CMasternodeMan::listScheduledMnbRequestConnections private
Definition at line 65 of file masternodeman.h.
Referenced by CheckAndRemove(), and PopScheduledMnbRequestConnection().
mapMasternodes
std::map<COutPoint, CMasternode> CMasternodeMan::mapMasternodes private
Definition at line 52 of file masternodeman.h.
Referenced by Add(), Check(), CheckAndRemove(), CheckMasternode(), CheckSameAddr(), Clear(), CountEnabled(), CountMasternodes(), DoFullVerificationStep(), Find(), FindRandomNotInVec(), Get(), GetMasternodeInfo(), GetMasternodeScores(), GetNextMasternodeInQueueForPayment(), Has(), ProcessMessage(), ProcessVerifyBroadcast(), ProcessVerifyReply(), RemoveGovernanceObject(), ToString(), and UpdateLastPaid().
mapSeenMasternodeBroadcast
std::map<uint256, std::pair<int64_t, CMasternodeBroadcast> > CMasternodeMan::mapSeenMasternodeBroadcast
Definition at line 85 of file masternodeman.h.
Referenced by AlreadyHave(), CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), Clear(), ProcessGetData(), ProcessMessage(), SetMasternodeLastPing(), and UpdateMasternodeList().
mapSeenMasternodePing
std::map<uint256, CMasternodePing> CMasternodeMan::mapSeenMasternodePing
Definition at line 87 of file masternodeman.h.
Referenced by AlreadyHave(), CheckAndRemove(), Clear(), ProcessGetData(), ProcessMessage(), SetMasternodeLastPing(), CMasternode::UpdateFromNewBroadcast(), and UpdateMasternodeList().
mapSeenMasternodeVerification
std::map<uint256, CMasternodeVerification> CMasternodeMan::mapSeenMasternodeVerification
Definition at line 89 of file masternodeman.h.
Referenced by AlreadyHave(), CheckAndRemove(), ProcessGetData(), ProcessVerifyBroadcast(), and ProcessVerifyReply().
mAskedUsForMasternodeList
std::map<CNetAddr, int64_t> CMasternodeMan::mAskedUsForMasternodeList private
Definition at line 54 of file masternodeman.h.
Referenced by CheckAndRemove(), Clear(), ProcessMessage(), and ToString().
MAX_POSE_BLOCKS
const int CMasternodeMan::MAX_POSE_BLOCKS = 10 static private
Definition at line 36 of file masternodeman.h.
Referenced by CheckAndRemove(), and ProcessVerifyBroadcast().
MAX_POSE_CONNECTIONS
const int CMasternodeMan::MAX_POSE_CONNECTIONS = 10 static private
Definition at line 34 of file masternodeman.h.
Referenced by DoFullVerificationStep().
MAX_POSE_RANK
const int CMasternodeMan::MAX_POSE_RANK = 10 static private
Definition at line 35 of file masternodeman.h.
Referenced by DoFullVerificationStep(), and ProcessVerifyBroadcast().
MIN_POSE_PROTO_VERSION
const int CMasternodeMan::MIN_POSE_PROTO_VERSION = 70203 static private
Definition at line 33 of file masternodeman.h.
Referenced by DoFullVerificationStep(), and ProcessVerifyBroadcast().
mMnbRecoveryGoodReplies
std::map<uint256, std::vector<CMasternodeBroadcast> > CMasternodeMan::mMnbRecoveryGoodReplies private
Definition at line 64 of file masternodeman.h.
Referenced by CheckAndRemove(), and CheckMnbAndUpdateMasternodeList().
mMnbRecoveryRequests
std::map<uint256, std::pair< int64_t, std::set<CNetAddr> > > CMasternodeMan::mMnbRecoveryRequests private
Definition at line 63 of file masternodeman.h.
Referenced by CheckAndRemove(), and CheckMnbAndUpdateMasternodeList().
MNB_RECOVERY_MAX_ASK_ENTRIES
const int CMasternodeMan::MNB_RECOVERY_MAX_ASK_ENTRIES = 10 static private
Definition at line 40 of file masternodeman.h.
Referenced by CheckAndRemove().
MNB_RECOVERY_QUORUM_REQUIRED
const int CMasternodeMan::MNB_RECOVERY_QUORUM_REQUIRED = 6 static private
Definition at line 39 of file masternodeman.h.
Referenced by CheckAndRemove().
MNB_RECOVERY_QUORUM_TOTAL
const int CMasternodeMan::MNB_RECOVERY_QUORUM_TOTAL = 10 static private
Definition at line 38 of file masternodeman.h.
Referenced by CheckAndRemove().
MNB_RECOVERY_RETRY_SECONDS
const int CMasternodeMan::MNB_RECOVERY_RETRY_SECONDS = 3 * 60 * 60 static private
Definition at line 42 of file masternodeman.h.
Referenced by CheckAndRemove().
MNB_RECOVERY_WAIT_SECONDS
const int CMasternodeMan::MNB_RECOVERY_WAIT_SECONDS = 60 static private
Definition at line 41 of file masternodeman.h.
Referenced by CheckAndRemove().
mWeAskedForMasternodeList
std::map<CNetAddr, int64_t> CMasternodeMan::mWeAskedForMasternodeList private
Definition at line 56 of file masternodeman.h.
Referenced by CheckAndRemove(), Clear(), DsegUpdate(), and ToString().
mWeAskedForMasternodeListEntry
std::map<COutPoint, std::map<CNetAddr, int64_t> > CMasternodeMan::mWeAskedForMasternodeListEntry private
Definition at line 58 of file masternodeman.h.
Referenced by AskForMN(), CheckAndRemove(), Clear(), and ToString().
mWeAskedForVerification
std::map<CNetAddr, CMasternodeVerification> CMasternodeMan::mWeAskedForVerification private
Definition at line 60 of file masternodeman.h.
Referenced by CheckAndRemove(), ProcessVerifyReply(), and SendVerifyRequest().
nCachedBlockHeight
int CMasternodeMan::nCachedBlockHeight private
Definition at line 49 of file masternodeman.h.
Referenced by CheckAndRemove(), DoFullVerificationStep(), GetNextMasternodeInQueueForPayment(), ProcessVerifyBroadcast(), SendVerifyRequest(), and UpdatedBlockTip().
nDsqCount
int64_t CMasternodeMan::nDsqCount
Definition at line 91 of file masternodeman.h.
Referenced by AllowMixing(), Clear(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), CPrivateSendClient::StartNewQueue(), and ToString().
nLastWatchdogVoteTime
int64_t CMasternodeMan::nLastWatchdogVoteTime private
Definition at line 75 of file masternodeman.h.
Referenced by Check(), Clear(), IsWatchdogActive(), and UpdateWatchdogVoteTime().
SERIALIZATION_VERSION_STRING
const std::string CMasternodeMan::SERIALIZATION_VERSION_STRING = "CMasternodeMan-Version-7" static private
Definition at line 27 of file masternodeman.h.
vecDirtyGovernanceObjectHashes
std::vector<uint256> CMasternodeMan::vecDirtyGovernanceObjectHashes private
Definition at line 73 of file masternodeman.h.
The documentation for this class was generated from the following files:
src/masternodeman.h
src/masternodeman.cpp
Released under the MIT license