Dash Core: CCoinsViewDB Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CCoinsViewDB Class Reference final
CCoinsView backed by the coin database (chainstate/)
#include <txdb.h>
Public Member Functions
CCoinsViewDB (size_t nCacheSize, bool fMemory=false, bool fWipe=false)
bool GetCoin (const COutPoint &outpoint, Coin &coin) const override
Retrieve the Coin (unspent transaction output) for a given outpoint.
bool HaveCoin (const COutPoint &outpoint) const override
Just check whether a given outpoint is unspent.
uint256 GetBestBlock () const override
Retrieve the block hash whose state this CCoinsView currently represents.
std::vector< uint256 > GetHeadBlocks () const override
Retrieve the range of blocks that may have been only partially written.
bool BatchWrite (CCoinsMap &mapCoins, const uint256 &hashBlock) override
Do a bulk modification (multiple Coin changes + BestBlock change).
CCoinsViewCursor * Cursor () const override
Get a cursor to iterate over the whole state.
bool Upgrade ()
Attempt to update from an older database format. Returns whether an error occurred.
size_t EstimateSize () const override
Estimate database size (0 if not implemented)
Public Member Functions inherited from CCoinsView
virtual ~CCoinsView ()
As we use CCoinsViews polymorphically, have a virtual destructor.
Protected Attributes
CDBWrapper db
Detailed Description
CCoinsView backed by the coin database (chainstate/)
Definition at line 71 of file txdb.h.
Constructor & Destructor Documentation
CCoinsViewDB()
CCoinsViewDB::CCoinsViewDB (size_t nCacheSize, bool fMemory = false, bool fWipe = false) explicit
Definition at line 61 of file txdb.cpp.
Member Function Documentation
BatchWrite()
bool CCoinsViewDB::BatchWrite (CCoinsMap & mapCoins, const uint256 & hashBlock) override virtual
Do a bulk modification (multiple Coin changes + BestBlock change).
The passed mapCoins can be modified.
Reimplemented from CCoinsView.
Definition at line 88 of file txdb.cpp.
References CDBBatch::Clear(), BCLog::COINDB, count, db, DB_BEST_BLOCK, DB_HEAD_BLOCKS, CCoinsCacheEntry::DIRTY, CDBBatch::Erase(), gArgs, ArgsManager::GetArg(), GetBestBlock(), GetHeadBlocks(), base_blob< BITS >::IsNull(), LogPrint, LogPrintf, nDefaultDbBatchSize, FastRandomContext::randrange(), CDBBatch::SizeEstimate(), CDBBatch::Write(), and CDBWrapper::WriteBatch().
Cursor()
CCoinsViewCursor * CCoinsViewDB::Cursor () const override virtual
Get a cursor to iterate over the whole state.
Reimplemented from CCoinsView.
Definition at line 177 of file txdb.cpp.
References db, DB_COIN, GetBestBlock(), CCoinsViewDBCursor::keyTmp, and CCoinsViewDBCursor::pcursor.
EstimateSize()
size_t CCoinsViewDB::EstimateSize () const override virtual
Estimate database size (0 if not implemented)
Reimplemented from CCoinsView.
Definition at line 149 of file txdb.cpp.
References db, DB_COIN, and CDBWrapper::EstimateSize().
GetBestBlock()
uint256 CCoinsViewDB::GetBestBlock () const override virtual
Retrieve the block hash whose state this CCoinsView currently represents.
Reimplemented from CCoinsView.
Definition at line 73 of file txdb.cpp.
References db, DB_BEST_BLOCK, and CDBWrapper::Read().
Referenced by BatchWrite(), and Cursor().
GetCoin()
bool CCoinsViewDB::GetCoin (const COutPoint & outpoint, Coin & coin) const override virtual
Retrieve the Coin (unspent transaction output) for a given outpoint.
Returns true only when an unspent coin was found, which is returned in coin. When false is returned, coin's value is unspecified.
Reimplemented from CCoinsView.
Definition at line 65 of file txdb.cpp.
References db, and CDBWrapper::Read().
GetHeadBlocks()
std::vector< uint256 > CCoinsViewDB::GetHeadBlocks () const override virtual
Retrieve the range of blocks that may have been only partially written.
If the database is in a consistent state, the result is the empty vector. Otherwise, a two-element vector is returned consisting of the new and the old block hash, in that order.
Reimplemented from CCoinsView.
Definition at line 80 of file txdb.cpp.
References db, DB_HEAD_BLOCKS, and CDBWrapper::Read().
Referenced by BatchWrite().
HaveCoin()
bool CCoinsViewDB::HaveCoin (const COutPoint & outpoint) const override virtual
Just check whether a given outpoint is unspent.
Reimplemented from CCoinsView.
Definition at line 69 of file txdb.cpp.
References db, and CDBWrapper::Exists().
Upgrade()
bool CCoinsViewDB::Upgrade ()
Attempt to update from an older database format. Returns whether an error occurred.
Upgrade the database from older formats.
Currently implemented: from the per-tx utxo model (0.8..0.14.x) to per-txout.
Definition at line 518 of file txdb.cpp.
References _(), CDBBatch::Clear(), CDBWrapper::CompactRange(), count, db, DB_COINS, CDBBatch::Erase(), error(), high, LogPrintf, COutPoint::n, CDBWrapper::NewIterator(), CClientUIInterface::ShowProgress, ShutdownRequested(), CDBBatch::SizeEstimate(), uiInterface, CDBBatch::Write(), and CDBWrapper::WriteBatch().
Member Data Documentation
db
CDBWrapper CCoinsViewDB::db protected
Definition at line 74 of file txdb.h.
Referenced by BatchWrite(), Cursor(), EstimateSize(), GetBestBlock(), GetCoin(), GetHeadBlocks(), HaveCoin(), and Upgrade().
The documentation for this class was generated from the following files:
src/txdb.h
src/txdb.cpp
Released under the MIT license