Dash Core: CBitcoinAddress Class Reference
CBitcoinAddress Class Reference
#include <base58.h>
Public Member Functions
bool Set (const CKeyID &id)
bool Set (const CScriptID &id)
bool Set (const CTxDestination &dest)
bool IsValid () const
bool IsValid (const CChainParams &params) const
CBitcoinAddress ()
CBitcoinAddress (const CTxDestination &dest)
CBitcoinAddress (const std::string &strAddress)
CBitcoinAddress (const char *pszAddress)
CTxDestination Get () const
bool GetKeyID (CKeyID &keyID) const
bool GetIndexKey (uint160 &hashBytes, int &type) const
bool IsScript () const
Public Member Functions inherited from CBase58Data
bool SetString (const char *psz, unsigned int nVersionBytes=1)
bool SetString (const std::string &str)
std::string ToString () const
int CompareTo (const CBase58Data &b58) const
bool operator== (const CBase58Data &b58) const
bool operator<= (const CBase58Data &b58) const
bool operator>= (const CBase58Data &b58) const
bool operator< (const CBase58Data &b58) const
bool operator> (const CBase58Data &b58) const
Additional Inherited Members
Protected Types inherited from CBase58Data
typedef std::vector< unsigned char, zero_after_free_allocator< unsigned char > > vector_uchar
the actually encoded data
Protected Member Functions inherited from CBase58Data
CBase58Data ()
void SetData (const std::vector< unsigned char > &vchVersionIn, const void *pdata, size_t nSize)
void SetData (const std::vector< unsigned char > &vchVersionIn, const unsigned char *pbegin, const unsigned char *pend)
Protected Attributes inherited from CBase58Data
std::vector< unsigned char > vchVersion
the version byte(s)
vector_uchar vchData
Detailed Description
base58-encoded Dash addresses. Public-key-hash-addresses have version 76 (or 140 testnet). The data vector contains RIPEMD160(SHA256(pubkey)), where pubkey is the serialized public key. Script-hash-addresses have version 16 (or 19 testnet). The data vector contains RIPEMD160(SHA256(cscript)), where cscript is the serialized redemption script.
Definition at line 104 of file base58.h.
Constructor & Destructor Documentation
CBitcoinAddress() [1/4]
CBitcoinAddress::CBitcoinAddress () inline
Definition at line 112 of file base58.h.
CBitcoinAddress() [2/4]
CBitcoinAddress::CBitcoinAddress (const CTxDestination & dest) inline
Definition at line 113 of file base58.h.
CBitcoinAddress() [3/4]
CBitcoinAddress::CBitcoinAddress (const std::string & strAddress) inline
Definition at line 114 of file base58.h.
CBitcoinAddress() [4/4]
CBitcoinAddress::CBitcoinAddress (const char * pszAddress) inline
Definition at line 115 of file base58.h.
Member Function Documentation
Get()
CTxDestination CBitcoinAddress::Get () const
Definition at line 260 of file base58.cpp.
Referenced by CGovernancePayment::CGovernancePayment(), SendCoinsDialog::coinControlChangeEdited(), createrawtransaction(), getaccount(), getreceivedbyaddress(), ImportAddress(), instantsendtoaddress(), ListReceived(), MutateTxAddOutAddr(), ReadKeyValue(), AddressTablePriv::refreshAddressTable(), WalletModel::saveReceiveRequest(), WalletModel::sendCoins(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), TransactionDesc::toHTML(), and validateaddress().
GetIndexKey()
bool CBitcoinAddress::GetIndexKey (uint160 & hashBytes, int & type) const
Definition at line 274 of file base58.cpp.
Referenced by getAddressesFromParams().
GetKeyID()
bool CBitcoinAddress::GetKeyID (CKeyID & keyID) const
Definition at line 291 of file base58.cpp.
Referenced by _createmultisig_redeemScript(), SendCoinsDialog::coinControlChangeEdited(), dumpprivkey(), CWallet::GetOutpointAndKeysFromOutput(), signmessage(), validateaddress(), and verifymessage().
IsScript()
bool CBitcoinAddress::IsScript () const
Definition at line 301 of file base58.cpp.
IsValid() [1/2]
bool CBitcoinAddress::IsValid () const
Definition at line 247 of file base58.cpp.
Referenced by _createmultisig_redeemScript(), SendCoinsDialog::coinControlChangeEdited(), createrawtransaction(), Get(), getaccount(), GetIndexKey(), GetKeyID(), getreceivedbyaddress(), ImportAddress(), importaddress(), instantsendtoaddress(), IsScript(), MutateTxAddOutAddr(), CSuperblock::ParsePaymentSchedule(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), signmessage(), TransactionDesc::toHTML(), WalletModel::validateAddress(), validateaddress(), CProposalValidator::ValidatePaymentAddress(), and verifymessage().
IsValid() [2/2]
bool CBitcoinAddress::IsValid (const CChainParams & params) const
Definition at line 252 of file base58.cpp.
Set() [1/3]
bool CBitcoinAddress::Set (const CKeyID & id)
Definition at line 230 of file base58.cpp.
Referenced by CBitcoinAddress(), and MaybePushAddress().
Set() [2/3]
bool CBitcoinAddress::Set (const CScriptID & id)
Definition at line 236 of file base58.cpp.
Set() [3/3]
bool CBitcoinAddress::Set (const CTxDestination & dest)
Definition at line 242 of file base58.cpp.
The documentation for this class was generated from the following files:
src/base58.h
src/base58.cpp