Dash Core: CBLSWrapper< ImplType, _SerSize, C > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSWrapper< ImplType, _SerSize, C > Class Template Reference abstract
#include <bls.h>
Public Member Functions
CBLSWrapper ()
CBLSWrapper (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper (CBLSWrapper &&ref)
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const C &r) const
bool operator!= (const C &r) const
bool IsValid () const
void SetBuf (const void *buf, size_t size)
void Reset ()
void GetBuf (void *buf, size_t size) const
template<typename T >
void SetBuf (const T &buf)
template<typename T >
void GetBuf (T &buf) const
const uint256 & GetHash () const
void UpdateHash () const
bool SetHexStr (const std::string &str)
void Serialize (CSizeComputer &s) const
template<typename Stream >
void Serialize (Stream &s) const
template<typename Stream >
void Unserialize (Stream &s, bool checkMalleable=true)
bool CheckMalleable (void *buf, size_t size) const
std::string ToString () const
Static Public Attributes
static const size_t SerSize = _SerSize
Protected Member Functions
constexpr size_t GetSerSize () const
virtual bool InternalSetBuf (const void *buf)=0
virtual bool InternalGetBuf (void *buf) const =0
Protected Attributes
ImplType impl
bool fValid {false}
uint256 cachedHash
Friends
class CBLSSecretKey
class CBLSPublicKey
class CBLSSignature
Detailed Description
template<typename ImplType, size_t _SerSize, typename C>
class CBLSWrapper< ImplType, _SerSize, C >
Definition at line 34 of file bls.h.
Constructor & Destructor Documentation
CBLSWrapper() [1/3]
template<typename ImplType, size_t _SerSize, typename C> CBLSWrapper< ImplType, _SerSize, C >::CBLSWrapper () inline
Definition at line 53 of file bls.h.
CBLSWrapper() [2/3]
template<typename ImplType, size_t _SerSize, typename C> CBLSWrapper< ImplType, _SerSize, C >::CBLSWrapper (const CBLSWrapper< ImplType, _SerSize, C > & ref) default
CBLSWrapper() [3/3]
template<typename ImplType, size_t _SerSize, typename C> CBLSWrapper< ImplType, _SerSize, C >::CBLSWrapper (CBLSWrapper< ImplType, _SerSize, C > && ref) inline
Definition at line 71 of file bls.h.
Member Function Documentation
CheckMalleable()
template<typename ImplType, size_t _SerSize, typename C> bool CBLSWrapper< ImplType, _SerSize, C >::CheckMalleable (void * buf, size_t size) const inline
Definition at line 197 of file bls.h.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::Unserialize().
GetBuf() [1/2]
template<typename ImplType, size_t _SerSize, typename C> void CBLSWrapper< ImplType, _SerSize, C >::GetBuf (void * buf, size_t size) const inline
Definition at line 122 of file bls.h.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::CheckMalleable(), CBLSIESEncryptedBlob::Decrypt(), CBLSIESMultiRecipientBlobs::Decrypt(), CBLSIESEncryptedBlob::Encrypt(), CBLSIESMultiRecipientBlobs::Encrypt(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::GetBuf(), llmq::CDKGSession::SendCommitment(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::Serialize(), CGovernanceVote::Sign(), CGovernanceObject::Sign(), CPrivateSendQueue::Sign(), CPrivateSendBroadcastTx::Sign(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::ToString().
GetBuf() [2/2]
template<typename ImplType, size_t _SerSize, typename C> template<typename T > void CBLSWrapper< ImplType, _SerSize, C >::GetBuf (T & buf) const inline
Definition at line 141 of file bls.h.
GetHash()
template<typename ImplType, size_t _SerSize, typename C> const uint256& CBLSWrapper< ImplType, _SerSize, C >::GetHash () const inline
Definition at line 147 of file bls.h.
Referenced by CTxMemPool::addUnchecked(), CTxMemPool::existsProviderTxConflict(), CTxMemPool::removeProTxPubKeyConflicts(), CTxMemPool::removeUnchecked(), and llmq::CRecoveredSig::ToJson().
GetSerSize()
template<typename ImplType, size_t _SerSize, typename C> constexpr size_t CBLSWrapper< ImplType, _SerSize, C >::GetSerSize () const inline protected
Definition at line 45 of file bls.h.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::GetBuf().
InternalGetBuf()
template<typename ImplType, size_t _SerSize, typename C> virtual bool CBLSWrapper< ImplType, _SerSize, C >::InternalGetBuf (void * buf) const protected pure virtual
Implemented in CBLSSignature, CBLSPublicKey, CBLSSecretKey, and CBLSId.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::GetBuf().
InternalSetBuf()
template<typename ImplType, size_t _SerSize, typename C> virtual bool CBLSWrapper< ImplType, _SerSize, C >::InternalSetBuf (const void * buf) protected pure virtual
Implemented in CBLSSignature, CBLSPublicKey, CBLSSecretKey, and CBLSId.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetBuf().
IsValid()
template<typename ImplType, size_t _SerSize, typename C> bool CBLSWrapper< ImplType, _SerSize, C >::IsValid () const inline
Definition at line 94 of file bls.h.
Referenced by CBLSSecretKey::AggregateInsecure(), CBLSPublicKey::AggregateInsecure(), CBLSSignature::AggregateInsecure(), AppInitMain(), CBLSWorker::AsyncVerifyContributionShare(), CBLSWorker::AsyncVerifyContributionShares(), CBLSWorker::AsyncVerifySig(), llmq::CQuorumManager::BuildQuorumContributions(), BuildQuorumInfo(), CheckProRegTx(), CheckProUpRegTx(), CPrivateSendQueue::CheckSignature(), CPrivateSendBroadcastTx::CheckSignature(), CBLSPublicKey::DHKeyExchange(), llmq::CFinalCommitment::IsNull(), llmq::CDKGSession::PreVerifyMessage(), CBLSPublicKey::PublicKeyShare(), CBLSBatchVerifier< SourceId, MessageId >::PushMessage(), llmq::CDKGSession::ReceiveMessage(), CBLSSecretKey::SecretKeyShare(), llmq::CDKGSession::SendCommitment(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetHexStr(), CGovernanceVote::Sign(), CGovernanceObject::Sign(), CPrivateSendQueue::Sign(), CPrivateSendBroadcastTx::Sign(), llmq::CSigSharesManager::Sign(), CBLSSignature::SubInsecure(), llmq::CFinalCommitment::Verify(), CBLSBatchVerifier< SourceId, MessageId >::VerifyBatchInsecure(), CBLSBatchVerifier< SourceId, MessageId >::VerifyBatchSecureStep(), CBLSSignature::VerifyInsecure(), and llmq::CQuorum::WriteContributions().
operator!=()
template<typename ImplType, size_t _SerSize, typename C> bool CBLSWrapper< ImplType, _SerSize, C >::operator!= (const C & r) const inline
Definition at line 89 of file bls.h.
operator=() [1/2]
template<typename ImplType, size_t _SerSize, typename C> CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= (const CBLSWrapper< ImplType, _SerSize, C > & ref) default
operator=() [2/2]
template<typename ImplType, size_t _SerSize, typename C> CBLSWrapper& CBLSWrapper< ImplType, _SerSize, C >::operator= (CBLSWrapper< ImplType, _SerSize, C > && ref) inline
Definition at line 77 of file bls.h.
operator==()
template<typename ImplType, size_t _SerSize, typename C> bool CBLSWrapper< ImplType, _SerSize, C >::operator== (const C & r) const inline
Definition at line 85 of file bls.h.
Reset()
template<typename ImplType, size_t _SerSize, typename C> void CBLSWrapper< ImplType, _SerSize, C >::Reset () inline
Definition at line 117 of file bls.h.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetBuf(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetHexStr().
Serialize() [1/2]
template<typename ImplType, size_t _SerSize, typename C> void CBLSWrapper< ImplType, _SerSize, C >::Serialize (CSizeComputer & s) const inline
Definition at line 173 of file bls.h.
Serialize() [2/2]
template<typename ImplType, size_t _SerSize, typename C> template<typename Stream > void CBLSWrapper< ImplType, _SerSize, C >::Serialize (Stream & s) const inline
Definition at line 179 of file bls.h.
SetBuf() [1/2]
template<typename ImplType, size_t _SerSize, typename C> void CBLSWrapper< ImplType, _SerSize, C >::SetBuf (const void * buf, size_t size) inline
Definition at line 99 of file bls.h.
Referenced by AppInitMain(), CGovernanceVote::CheckSignature(), CGovernanceObject::CheckSignature(), CPrivateSendQueue::CheckSignature(), CPrivateSendBroadcastTx::CheckSignature(), llmq::CDKGSession::SendCommitment(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetBuf(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetHexStr(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::Unserialize().
SetBuf() [2/2]
template<typename ImplType, size_t _SerSize, typename C> template<typename T > void CBLSWrapper< ImplType, _SerSize, C >::SetBuf (const T & buf) inline
Definition at line 135 of file bls.h.
SetHexStr()
template<typename ImplType, size_t _SerSize, typename C> bool CBLSWrapper< ImplType, _SerSize, C >::SetHexStr (const std::string & str) inline
Definition at line 157 of file bls.h.
Referenced by bls_fromsecret(), ParseBLSPubKey(), and ParseBLSSecretKey().
ToString()
template<typename ImplType, size_t _SerSize, typename C> std::string CBLSWrapper< ImplType, _SerSize, C >::ToString () const inline
Definition at line 210 of file bls.h.
Referenced by AppInitMain(), bls_fromsecret(), bls_generate(), BuildQuorumInfo(), llmq::CDKGSession::FinalizeCommitments(), llmq::CQuorumBlockProcessor::ProcessCommitment(), llmq::CDKGSession::SendCommitment(), llmq::CRecoveredSig::ToJson(), CProRegTx::ToJson(), CSimplifiedMNListEntry::ToJson(), llmq::CFinalCommitment::ToJson(), CDeterministicMNState::ToJson(), CProUpRegTx::ToJson(), CProRegTx::ToString(), CSimplifiedMNListEntry::ToString(), CDeterministicMNState::ToString(), and CProUpRegTx::ToString().
Unserialize()
template<typename ImplType, size_t _SerSize, typename C> template<typename Stream > void CBLSWrapper< ImplType, _SerSize, C >::Unserialize (Stream & s, bool checkMalleable = true) inline
Definition at line 186 of file bls.h.
UpdateHash()
template<typename ImplType, size_t _SerSize, typename C> void CBLSWrapper< ImplType, _SerSize, C >::UpdateHash () const inline
Definition at line 152 of file bls.h.
Referenced by CBLSSecretKey::AggregateInsecure(), CBLSPublicKey::AggregateInsecure(), CBLSSignature::AggregateInsecure(), CBLSSignature::AggregateSecure(), CBLSSecretKey::GetPublicKey(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetBuf(), and CBLSSecretKey::Sign().
Friends And Related Function Documentation
CBLSPublicKey
template<typename ImplType, size_t _SerSize, typename C> friend class CBLSPublicKey friend
Definition at line 37 of file bls.h.
CBLSSecretKey
template<typename ImplType, size_t _SerSize, typename C> friend class CBLSSecretKey friend
Definition at line 36 of file bls.h.
CBLSSignature
template<typename ImplType, size_t _SerSize, typename C> friend class CBLSSignature friend
Definition at line 38 of file bls.h.
Member Data Documentation
cachedHash
template<typename ImplType, size_t _SerSize, typename C> uint256 CBLSWrapper< ImplType, _SerSize, C >::cachedHash mutable protected
Definition at line 43 of file bls.h.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::CBLSWrapper(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::GetHash(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::operator=(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::UpdateHash().
fValid
template<typename ImplType, size_t _SerSize, typename C> bool CBLSWrapper< ImplType, _SerSize, C >::fValid {false} protected
Definition at line 42 of file bls.h.
Referenced by CBLSSecretKey::AggregateInsecure(), CBLSPublicKey::AggregateInsecure(), CBLSSignature::AggregateInsecure(), CBLSSignature::AggregateSecure(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::CBLSWrapper(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::GetBuf(), CBLSSecretKey::GetPublicKey(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::IsValid(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::operator=(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::operator==(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetBuf(), and CBLSSecretKey::Sign().
impl
template<typename ImplType, size_t _SerSize, typename C> ImplType CBLSWrapper< ImplType, _SerSize, C >::impl protected
Definition at line 41 of file bls.h.
Referenced by CBLSSecretKey::AggregateInsecure(), CBLSPublicKey::AggregateInsecure(), CBLSSignature::AggregateInsecure(), CBLSSignature::AggregateSecure(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::CBLSWrapper(), CBLSPublicKey::DHKeyExchange(), CBLSSecretKey::GetPublicKey(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::operator=(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::operator==(), CBLSPublicKey::PublicKeyShare(), CBLSSecretKey::SecretKeyShare(), CBLSSecretKey::Sign(), CBLSSignature::SubInsecure(), and CBLSSignature::VerifyInsecure().
SerSize
template<typename ImplType, size_t _SerSize, typename C> const size_t CBLSWrapper< ImplType, _SerSize, C >::SerSize = _SerSize static
Definition at line 51 of file bls.h.
Referenced by bls_fromsecret(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::CheckMalleable(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::GetBuf(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::GetSerSize(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::Serialize(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetBuf(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetHexStr(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::Unserialize().
The documentation for this class was generated from the following file:
src/bls/bls.h
Released under the MIT license