Dash Core: CChainParams Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CChainParams Class Reference
CChainParams defines various tweakable parameters of a given instance of the Dash system.
#include <chainparams.h>
Public Types
enum Base58Type {
PUBKEY_ADDRESS, SCRIPT_ADDRESS, SECRET_KEY, EXT_PUBLIC_KEY,
EXT_SECRET_KEY, MAX_BASE58_TYPES
}
Public Member Functions
const Consensus::Params & GetConsensus () const
const CMessageHeader::MessageStartChars & MessageStart () const
int GetDefaultPort () const
const CBlock & GenesisBlock () const
const CBlock & DevNetGenesisBlock () const
bool DefaultConsistencyChecks () const
Default value for -checkmempool and -checkblockindex argument.
bool RequireStandard () const
Policy: Filter transactions that do not match well-defined patterns.
bool RequireRoutableExternalIP () const
Require addresses specified with "-externalip" parameter to be routable.
uint64_t PruneAfterHeight () const
bool MineBlocksOnDemand () const
Make miner stop after a block is found.
bool AllowMultipleAddressesFromGroup () const
Allow multiple addresses to be selected from the same network group (e.g.
bool AllowMultiplePorts () const
Allow nodes with the same address and multiple ports.
int LLMQConnectionRetryTimeout () const
How long to wait until we allow retrying of a LLMQ connection.
std::string NetworkIDString () const
Return the BIP70 network string (main, test or regtest)
const std::vector< std::string > & DNSSeeds () const
Return the list of hostnames to look up for DNS seeds.
const std::vector< unsigned char > & Base58Prefix (Base58Type type) const
int ExtCoinType () const
const std::vector< SeedSpec6 > & FixedSeeds () const
const CCheckpointData & Checkpoints () const
const ChainTxData & TxData () const
void UpdateVersionBitsParameters (Consensus::DeploymentPos d, int64_t nStartTime, int64_t nTimeout, int64_t nWindowSize, int64_t nThresholdStart, int64_t nThresholdMin, int64_t nFalloffCoeff)
void UpdateDIP3Parameters (int nActivationHeight, int nEnforcementHeight)
void UpdateBudgetParameters (int nMasternodePaymentsStartBlock, int nBudgetPaymentsStartBlock, int nSuperblockStartBlock)
void UpdateSubsidyAndDiffParams (int nMinimumDifficultyBlocks, int nHighSubsidyBlocks, int nHighSubsidyFactor)
void UpdateLLMQChainLocks (Consensus::LLMQType llmqType)
void UpdateLLMQTestParams (int size, int threshold)
void UpdateLLMQDevnetParams (int size, int threshold)
int PoolMinParticipants () const
int PoolNewMinParticipants () const
int PoolMaxParticipants () const
int PoolNewMaxParticipants () const
int FulfilledRequestExpireTime () const
const std::vector< std::string > & SporkAddresses () const
int MinSporkKeys () const
bool BIP9CheckMasternodesUpgraded () const
Protected Member Functions
CChainParams ()
Protected Attributes
Consensus::Params consensus
CMessageHeader::MessageStartChars pchMessageStart
int nDefaultPort
uint64_t nPruneAfterHeight
std::vector< std::string > vSeeds
std::vector< unsigned char > base58Prefixes [MAX_BASE58_TYPES]
int nExtCoinType
std::string strNetworkID
CBlock genesis
CBlock devnetGenesis
std::vector< SeedSpec6 > vFixedSeeds
bool fDefaultConsistencyChecks
bool fRequireStandard
bool fRequireRoutableExternalIP
bool fMineBlocksOnDemand
bool fAllowMultipleAddressesFromGroup
bool fAllowMultiplePorts
int nLLMQConnectionRetryTimeout
CCheckpointData checkpointData
ChainTxData chainTxData
int nPoolMinParticipants
int nPoolNewMinParticipants
int nPoolMaxParticipants
int nPoolNewMaxParticipants
int nFulfilledRequestExpireTime
std::vector< std::string > vSporkAddresses
int nMinSporkKeys
bool fBIP9CheckMasternodesUpgraded
Detailed Description
CChainParams defines various tweakable parameters of a given instance of the Dash system.
There are three: the main network on which people trade goods and services, the public test network which gets reset from time to time and a regression test mode which is intended for private networks only. It has minimal difficulty to ensure that blocks can be found instantly.
Definition at line 41 of file chainparams.h.
Member Enumeration Documentation
Base58Type
enum CChainParams::Base58Type
Enumerator
PUBKEY_ADDRESS
SCRIPT_ADDRESS
SECRET_KEY
EXT_PUBLIC_KEY
EXT_SECRET_KEY
MAX_BASE58_TYPES
Definition at line 44 of file chainparams.h.
Constructor & Destructor Documentation
CChainParams()
CChainParams::CChainParams () inline protected
Definition at line 100 of file chainparams.h.
Member Function Documentation
AllowMultipleAddressesFromGroup()
bool CChainParams::AllowMultipleAddressesFromGroup () const inline
Allow multiple addresses to be selected from the same network group (e.g.
192.168.x.x)
Definition at line 70 of file chainparams.h.
References fAllowMultipleAddressesFromGroup.
AllowMultiplePorts()
bool CChainParams::AllowMultiplePorts () const inline
Allow nodes with the same address and multiple ports.
Definition at line 72 of file chainparams.h.
References fAllowMultiplePorts.
Referenced by CNetFulfilledRequestManager::AddFulfilledRequest(), CConnman::ConnectNode(), CNetFulfilledRequestManager::HasFulfilledRequest(), CConnman::OpenNetworkConnection(), CNetFulfilledRequestManager::RemoveAllFulfilledRequests(), CNetFulfilledRequestManager::RemoveFulfilledRequest(), and CConnman::ThreadOpenConnections().
Base58Prefix()
const std::vector<unsigned char>& CChainParams::Base58Prefix (Base58Type type) const inline
Definition at line 79 of file chainparams.h.
References base58Prefixes.
Referenced by CBitcoinExtKeyBase< K, Size, Type >::CBitcoinExtKeyBase(), GUIUtil::DummyAddress(), and CBitcoinSecret::IsValid().
BIP9CheckMasternodesUpgraded()
bool CChainParams::BIP9CheckMasternodesUpgraded () const inline
Definition at line 98 of file chainparams.h.
References fBIP9CheckMasternodesUpgraded.
Referenced by BlockAssembler::CreateNewBlock().
Checkpoints()
const CCheckpointData& CChainParams::Checkpoints () const inline
Definition at line 82 of file chainparams.h.
References checkpointData.
Referenced by ContextualCheckBlockHeader().
DefaultConsistencyChecks()
bool CChainParams::DefaultConsistencyChecks () const inline
Default value for -checkmempool and -checkblockindex argument.
Definition at line 61 of file chainparams.h.
References fDefaultConsistencyChecks.
Referenced by AppInitParameterInteraction().
DevNetGenesisBlock()
const CBlock& CChainParams::DevNetGenesisBlock () const inline
Definition at line 59 of file chainparams.h.
References devnetGenesis.
Referenced by CChainState::LoadGenesisBlock().
DNSSeeds()
const std::vector<std::string>& CChainParams::DNSSeeds () const inline
Return the list of hostnames to look up for DNS seeds.
Definition at line 78 of file chainparams.h.
References vSeeds.
Referenced by CConnman::ThreadDNSAddressSeed().
ExtCoinType()
int CChainParams::ExtCoinType () const inline
Definition at line 80 of file chainparams.h.
References nExtCoinType.
FixedSeeds()
const std::vector<SeedSpec6>& CChainParams::FixedSeeds () const inline
Definition at line 81 of file chainparams.h.
References vFixedSeeds.
FulfilledRequestExpireTime()
int CChainParams::FulfilledRequestExpireTime () const inline
Definition at line 95 of file chainparams.h.
References nFulfilledRequestExpireTime.
Referenced by CNetFulfilledRequestManager::AddFulfilledRequest().
GenesisBlock()
const CBlock& CChainParams::GenesisBlock () const inline
Definition at line 58 of file chainparams.h.
References genesis.
Referenced by CChainState::LoadGenesisBlock().
GetConsensus()
const Consensus::Params& CChainParams::GetConsensus () const inline
Definition at line 54 of file chainparams.h.
References consensus.
Referenced by CChainState::AcceptBlock(), CChainState::AcceptBlockHeader(), AcceptToMemoryPoolWorker(), CChainState::ActivateBestChain(), AppInitMain(), AppInitParameterInteraction(), llmq::CSigningManager::AsyncSignIfMember(), CDeterministicMNManager::BuildNewListFromBlock(), CalcCbTxMerkleRootQuorums(), llmq::CChainLocksHandler::CheckActiveState(), llmq::CheckLLMQCommitment(), CGovernanceManager::CheckPostponedObjects(), llmq::CSigSharesManager::CollectSigSharesToAnnounce(), llmq::CSigSharesManager::CollectSigSharesToRequest(), CChainState::ConnectBlock(), CChainState::ConnectTip(), ContextualCheckBlockHeader(), BlockAssembler::CreateNewBlock(), CChainState::DisconnectBlock(), CChainState::DisconnectTip(), llmq::CQuorumManager::EnsureQuorumConnections(), llmq::CLLMQUtils::GetAllQuorumMembers(), getblockchaininfo(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), getchaintxstats(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), CDeterministicMNManager::GetListForBlock(), GetMasternodePayment(), CSuperblock::GetNearestSuperblocksHeights(), GetNetworkHashPS(), CSuperblock::GetPaymentsLimit(), llmq::CQuorumManager::GetQuorum(), llmq::CQuorumBlockProcessor::GetQuorumBlockHash(), llmq::CLLMQUtils::GetQuorumConnections(), llmq::CInstantSendManager::HandleFullyConfirmedBlock(), llmq::CInstantSendManager::HandleNewRecoveredSig(), llmq::CDKGDebugManager::InitLocalSessionStatus(), llmq::CDKGSessionHandler::InitNewQuorum(), llmq::InitSession(), IsBlockPayeeValid(), IsBlockValueValid(), CDeterministicMNManager::IsDIP3Enforced(), CSuperblock::IsExpired(), llmq::CQuorumBlockProcessor::IsMiningPhase(), IsOldBudgetBlockValueValid(), llmq::CLLMQUtils::IsQuorumActive(), CSuperblock::IsValidBlockHeight(), LoadBlockIndexDB(), LoadExternalBlockFile(), CChainState::LoadGenesisBlock(), CGovernanceManager::MasternodeRateCheck(), CZMQPublishRawBlockNotifier::NotifyBlock(), CZMQPublishRawChainLockNotifier::NotifyChainLock(), CZMQPublishRawChainLockSigNotifier::NotifyChainLock(), PeerLogicValidation::PeerLogicValidation(), llmq::CSigningManager::PreVerifyRecoveredSig(), llmq::CQuorumBlockProcessor::ProcessBlock(), CDeterministicMNManager::ProcessBlock(), llmq::CQuorumBlockProcessor::ProcessCommitment(), ProcessGetBlockData(), ProcessHeadersMessage(), llmq::CQuorumBlockProcessor::ProcessMessage(), ProcessMessage(), llmq::CSigSharesManager::ProcessMessageSigSesAnn(), ProcessNewBlock(), llmq::CInstantSendManager::ProcessPendingInstantSendLocks(), llmq::CInstantSendManager::ProcessPendingRetryLockTxs(), quorum_info(), quorum_selectquorum(), quorum_sigs_cmd(), CChainState::ReplayBlocks(), CChainState::RollforwardBlock(), llmq::CQuorumManager::ScanQuorums(), llmq::CSigningManager::SelectQuorumForSigning(), PeerLogicValidation::SendMessages(), llmq::CDKGSessionHandler::SleepBeforePhase(), TestBlockValidity(), ModalOverlay::tipUpdate(), llmq::CDKGDebugStatus::ToJson(), llmq::CInstantSendManager::TruncateRecoveredSigsForInputs(), llmq::CInstantSendManager::TrySignInstantSendLock(), CDeterministicMNManager::UndoBlock(), CGovernanceManager::UpdateCachesAndClean(), CDSNotificationInterface::UpdatedBlockTip(), llmq::CDKGSessionManager::UpdatedBlockTip(), llmq::CQuorumManager::UpdatedBlockTip(), llmq::CInstantSendManager::UpdatedBlockTip(), BitcoinGUI::updateHeadersSyncProgressLabel(), UpdateTip(), llmq::CQuorumBlockProcessor::UpgradeDB(), CDeterministicMNManager::UpgradeDBIfNeeded(), llmq::CFinalCommitment::Verify(), CVerifyDB::VerifyDB(), llmq::CFinalCommitment::VerifyNull(), and llmq::CSigSharesManager::VerifySigSharesInv().
GetDefaultPort()
int CChainParams::GetDefaultPort () const inline
Definition at line 56 of file chainparams.h.
References nDefaultPort.
Referenced by CConnman::ConnectNode(), CConnman::GetAddedNodeInfo(), and CConnman::ThreadOpenConnections().
LLMQConnectionRetryTimeout()
int CChainParams::LLMQConnectionRetryTimeout () const inline
How long to wait until we allow retrying of a LLMQ connection.
Definition at line 74 of file chainparams.h.
References nLLMQConnectionRetryTimeout.
MessageStart()
const CMessageHeader::MessageStartChars& CChainParams::MessageStart () const inline
Definition at line 55 of file chainparams.h.
References pchMessageStart.
Referenced by LoadExternalBlockFile(), PeerLogicValidation::ProcessMessages(), SaveBlockToDisk(), and WriteUndoDataForBlock().
MineBlocksOnDemand()
bool CChainParams::MineBlocksOnDemand () const inline
Make miner stop after a block is found.
In RPC, don't return until nGenProcLimit blocks are generated
Definition at line 68 of file chainparams.h.
References fMineBlocksOnDemand.
Referenced by AppInitParameterInteraction(), BlockAssembler::CreateNewBlock(), setmocktime(), and llmq::CDKGSessionHandler::SleepBeforePhase().
MinSporkKeys()
int CChainParams::MinSporkKeys () const inline
Definition at line 97 of file chainparams.h.
References nMinSporkKeys.
NetworkIDString()
std::string CChainParams::NetworkIDString () const inline
Return the BIP70 network string (main, test or regtest)
Definition at line 76 of file chainparams.h.
References strNetworkID.
Referenced by AppInitMain(), AppInitParameterInteraction(), CPrivateSendClientSession::DoAutomaticDenominating(), CChainState::LoadGenesisBlock(), CMasternodeSync::ProcessTick(), CMNAuth::PushMNAUTH(), and PaymentServer::verifyNetwork().
PoolMaxParticipants()
int CChainParams::PoolMaxParticipants () const inline
Definition at line 93 of file chainparams.h.
References nPoolMaxParticipants.
Referenced by CPrivateSend::GetMaxPoolParticipants().
PoolMinParticipants()
int CChainParams::PoolMinParticipants () const inline
Definition at line 91 of file chainparams.h.
References nPoolMinParticipants.
Referenced by CPrivateSend::GetMinPoolParticipants().
PoolNewMaxParticipants()
int CChainParams::PoolNewMaxParticipants () const inline
Definition at line 94 of file chainparams.h.
References nPoolNewMaxParticipants.
Referenced by CPrivateSend::GetMaxPoolParticipants().
PoolNewMinParticipants()
int CChainParams::PoolNewMinParticipants () const inline
Definition at line 92 of file chainparams.h.
References nPoolNewMinParticipants.
Referenced by CPrivateSend::GetMinPoolParticipants().
PruneAfterHeight()
uint64_t CChainParams::PruneAfterHeight () const inline
Definition at line 66 of file chainparams.h.
References nPruneAfterHeight.
Referenced by FlushStateToDisk().
RequireRoutableExternalIP()
bool CChainParams::RequireRoutableExternalIP () const inline
Require addresses specified with "-externalip" parameter to be routable.
Definition at line 65 of file chainparams.h.
References fRequireRoutableExternalIP.
Referenced by AddLocal(), AppInitParameterInteraction(), CActiveMasternodeManager::Init(), and CActiveMasternodeManager::IsValidNetAddr().
RequireStandard()
bool CChainParams::RequireStandard () const inline
Policy: Filter transactions that do not match well-defined patterns.
Definition at line 63 of file chainparams.h.
References fRequireStandard.
Referenced by AppInitParameterInteraction().
SporkAddresses()
const std::vector<std::string>& CChainParams::SporkAddresses () const inline
Definition at line 96 of file chainparams.h.
References vSporkAddresses.
Referenced by AppInitMain().
TxData()
const ChainTxData& CChainParams::TxData () const inline
Definition at line 83 of file chainparams.h.
References chainTxData.
Referenced by LoadChainTip(), CWallet::ScanForWalletTransactions(), and UpdateTip().
UpdateBudgetParameters()
void CChainParams::UpdateBudgetParameters (int nMasternodePaymentsStartBlock, int nBudgetPaymentsStartBlock, int nSuperblockStartBlock)
Definition at line 109 of file chainparams.cpp.
References consensus, Consensus::Params::nBudgetPaymentsStartBlock, Consensus::Params::nMasternodePaymentsStartBlock, and Consensus::Params::nSuperblockStartBlock.
UpdateDIP3Parameters()
void CChainParams::UpdateDIP3Parameters (int nActivationHeight, int nEnforcementHeight)
Definition at line 103 of file chainparams.cpp.
References consensus, Consensus::Params::DIP0003EnforcementHeight, and Consensus::Params::DIP0003Height.
UpdateLLMQChainLocks()
void CChainParams::UpdateLLMQChainLocks (Consensus::LLMQType llmqType)
Definition at line 123 of file chainparams.cpp.
References consensus, and Consensus::Params::llmqTypeChainLocks.
UpdateLLMQDevnetParams()
void CChainParams::UpdateLLMQDevnetParams (int size, int threshold)
Definition at line 135 of file chainparams.cpp.
References consensus, Consensus::LLMQ_DEVNET, and Consensus::Params::llmqs.
UpdateLLMQTestParams()
void CChainParams::UpdateLLMQTestParams (int size, int threshold)
Definition at line 127 of file chainparams.cpp.
References consensus, Consensus::LLMQ_TEST, and Consensus::Params::llmqs.
UpdateSubsidyAndDiffParams()
void CChainParams::UpdateSubsidyAndDiffParams (int nMinimumDifficultyBlocks, int nHighSubsidyBlocks, int nHighSubsidyFactor)
Definition at line 116 of file chainparams.cpp.
References consensus, Consensus::Params::nHighSubsidyBlocks, Consensus::Params::nHighSubsidyFactor, and Consensus::Params::nMinimumDifficultyBlocks.
UpdateVersionBitsParameters()
void CChainParams::UpdateVersionBitsParameters (Consensus::DeploymentPos d, int64_t nStartTime, int64_t nTimeout, int64_t nWindowSize, int64_t nThresholdStart, int64_t nThresholdMin, int64_t nFalloffCoeff)
Definition at line 85 of file chainparams.cpp.
References consensus, Consensus::BIP9Deployment::nFalloffCoeff, Consensus::BIP9Deployment::nStartTime, Consensus::BIP9Deployment::nThresholdMin, Consensus::BIP9Deployment::nThresholdStart, Consensus::BIP9Deployment::nTimeout, Consensus::BIP9Deployment::nWindowSize, and Consensus::Params::vDeployments.
Member Data Documentation
base58Prefixes
std::vector<unsigned char> CChainParams::base58Prefixes[MAX_BASE58_TYPES] protected
Definition at line 107 of file chainparams.h.
Referenced by Base58Prefix(), CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), and CTestNetParams::CTestNetParams().
chainTxData
ChainTxData CChainParams::chainTxData protected
Definition at line 121 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and TxData().
checkpointData
CCheckpointData CChainParams::checkpointData protected
Definition at line 120 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), Checkpoints(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), and CTestNetParams::CTestNetParams().
consensus
Consensus::Params CChainParams::consensus protected
Definition at line 102 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), GetConsensus(), UpdateBudgetParameters(), UpdateDIP3Parameters(), UpdateLLMQChainLocks(), UpdateLLMQDevnetParams(), UpdateLLMQTestParams(), UpdateSubsidyAndDiffParams(), and UpdateVersionBitsParameters().
devnetGenesis
CBlock CChainParams::devnetGenesis protected
Definition at line 111 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), and DevNetGenesisBlock().
fAllowMultipleAddressesFromGroup
bool CChainParams::fAllowMultipleAddressesFromGroup protected
Definition at line 117 of file chainparams.h.
Referenced by AllowMultipleAddressesFromGroup(), CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), and CTestNetParams::CTestNetParams().
fAllowMultiplePorts
bool CChainParams::fAllowMultiplePorts protected
Definition at line 118 of file chainparams.h.
Referenced by AllowMultiplePorts(), CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), and CTestNetParams::CTestNetParams().
fBIP9CheckMasternodesUpgraded
bool CChainParams::fBIP9CheckMasternodesUpgraded protected
Definition at line 129 of file chainparams.h.
Referenced by BIP9CheckMasternodesUpgraded(), CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), and CTestNetParams::CTestNetParams().
fDefaultConsistencyChecks
bool CChainParams::fDefaultConsistencyChecks protected
Definition at line 113 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and DefaultConsistencyChecks().
fMineBlocksOnDemand
bool CChainParams::fMineBlocksOnDemand protected
Definition at line 116 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and MineBlocksOnDemand().
fRequireRoutableExternalIP
bool CChainParams::fRequireRoutableExternalIP protected
Definition at line 115 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and RequireRoutableExternalIP().
fRequireStandard
bool CChainParams::fRequireStandard protected
Definition at line 114 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and RequireStandard().
genesis
CBlock CChainParams::genesis protected
Definition at line 110 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and GenesisBlock().
nDefaultPort
int CChainParams::nDefaultPort protected
Definition at line 104 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and GetDefaultPort().
nExtCoinType
int CChainParams::nExtCoinType protected
Definition at line 108 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and ExtCoinType().
nFulfilledRequestExpireTime
int CChainParams::nFulfilledRequestExpireTime protected
Definition at line 126 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and FulfilledRequestExpireTime().
nLLMQConnectionRetryTimeout
int CChainParams::nLLMQConnectionRetryTimeout protected
Definition at line 119 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and LLMQConnectionRetryTimeout().
nMinSporkKeys
int CChainParams::nMinSporkKeys protected
Definition at line 128 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and MinSporkKeys().
nPoolMaxParticipants
int CChainParams::nPoolMaxParticipants protected
Definition at line 124 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and PoolMaxParticipants().
nPoolMinParticipants
int CChainParams::nPoolMinParticipants protected
Definition at line 122 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and PoolMinParticipants().
nPoolNewMaxParticipants
int CChainParams::nPoolNewMaxParticipants protected
Definition at line 125 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and PoolNewMaxParticipants().
nPoolNewMinParticipants
int CChainParams::nPoolNewMinParticipants protected
Definition at line 123 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and PoolNewMinParticipants().
nPruneAfterHeight
uint64_t CChainParams::nPruneAfterHeight protected
Definition at line 105 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and PruneAfterHeight().
pchMessageStart
CMessageHeader::MessageStartChars CChainParams::pchMessageStart protected
Definition at line 103 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and MessageStart().
strNetworkID
std::string CChainParams::strNetworkID protected
Definition at line 109 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and NetworkIDString().
vFixedSeeds
std::vector<SeedSpec6> CChainParams::vFixedSeeds protected
Definition at line 112 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and FixedSeeds().
vSeeds
std::vector<std::string> CChainParams::vSeeds protected
Definition at line 106 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and DNSSeeds().
vSporkAddresses
std::vector<std::string> CChainParams::vSporkAddresses protected
Definition at line 127 of file chainparams.h.
Referenced by CDevNetParams::CDevNetParams(), CMainParams::CMainParams(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), and SporkAddresses().
The documentation for this class was generated from the following files:
src/chainparams.h
src/chainparams.cpp
Released under the MIT license