Dash Core: BitcoinAmountField Class Reference
BitcoinAmountField Class Reference
#include <bitcoinamountfield.h>
Signals
void valueChanged ()
Public Member Functions
BitcoinAmountField (QWidget *parent=0)
CAmount value (bool *value=0) const
void setValue (const CAmount &value)
void setSingleStep (const CAmount &step)
void setReadOnly (bool fReadOnly)
void setValid (bool valid)
bool validate ()
void setDisplayUnit (int unit)
void clear ()
void setEnabled (bool fEnabled)
QWidget * setupTabChain (QWidget *prev)
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event)
Properties
qint64 value
Private Slots
void unitChanged (int idx)
Private Attributes
AmountSpinBox * amount
QValueComboBox * unit
Detailed Description
Widget for entering bitcoin amounts.
Definition at line 20 of file bitcoinamountfield.h.
Constructor & Destructor Documentation
BitcoinAmountField()
BitcoinAmountField::BitcoinAmountField (QWidget * parent = 0) explicit
Definition at line 193 of file bitcoinamountfield.cpp.
Member Function Documentation
clear()
void BitcoinAmountField::clear ()
Make field empty and ready for new input.
Definition at line 223 of file bitcoinamountfield.cpp.
Referenced by ReceiveCoinsDialog::clear(), and SendCoinsEntry::clear().
eventFilter()
bool BitcoinAmountField::eventFilter (QObject * object, QEvent * event) protected
Intercept focus-in event and ',' key presses
Definition at line 251 of file bitcoinamountfield.cpp.
setDisplayUnit()
void BitcoinAmountField::setDisplayUnit (int unit)
Change unit used to display amount.
Definition at line 294 of file bitcoinamountfield.cpp.
Referenced by SendCoinsEntry::updateDisplayUnit(), ReceiveCoinsDialog::updateDisplayUnit(), and SendCoinsDialog::updateDisplayUnit().
setEnabled()
void BitcoinAmountField::setEnabled (bool fEnabled)
Enable/Disable.
Definition at line 229 of file bitcoinamountfield.cpp.
Referenced by SendCoinsDialog::updateFeeSectionControls().
setReadOnly()
void BitcoinAmountField::setReadOnly (bool fReadOnly)
Make read-only
Definition at line 278 of file bitcoinamountfield.cpp.
Referenced by SendCoinsEntry::setValue().
setSingleStep()
void BitcoinAmountField::setSingleStep (const CAmount & step)
Set single step in satoshis
Definition at line 299 of file bitcoinamountfield.cpp.
Referenced by SendCoinsDialog::setModel().
setupTabChain()
QWidget * BitcoinAmountField::setupTabChain (QWidget * prev)
Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907), in these cases we have to set it up manually.
Definition at line 261 of file bitcoinamountfield.cpp.
Referenced by SendCoinsEntry::setupTabChain().
setValid()
void BitcoinAmountField::setValid (bool valid)
Mark current value as invalid in UI.
Definition at line 243 of file bitcoinamountfield.cpp.
Referenced by eventFilter(), SendCoinsEntry::validate(), and validate().
setValue()
void BitcoinAmountField::setValue (const CAmount & value)
Definition at line 273 of file bitcoinamountfield.cpp.
Referenced by SendCoinsDialog::SendCoinsDialog(), SendCoinsDialog::setMinimumFee(), and SendCoinsEntry::setValue().
unitChanged
void BitcoinAmountField::unitChanged (int idx) private slot
Definition at line 283 of file bitcoinamountfield.cpp.
Referenced by BitcoinAmountField().
validate()
bool BitcoinAmountField::validate ()
Perform input validation, mark field as invalid if entered value is not valid.
Definition at line 235 of file bitcoinamountfield.cpp.
Referenced by SendCoinsEntry::validate().
value()
CAmount BitcoinAmountField::value (bool * value = 0) const
Definition at line 268 of file bitcoinamountfield.cpp.
valueChanged
void BitcoinAmountField::valueChanged () signal
Definition at line 174 of file moc_bitcoinamountfield.cpp.
Referenced by BitcoinAmountField().
Member Data Documentation
amount
AmountSpinBox* BitcoinAmountField::amount private
Definition at line 67 of file bitcoinamountfield.h.
Referenced by BitcoinAmountField(), clear(), setEnabled(), setReadOnly(), setSingleStep(), setupTabChain(), setValid(), setValue(), unitChanged(), and value().
unit
QValueComboBox* BitcoinAmountField::unit private
Definition at line 68 of file bitcoinamountfield.h.
Referenced by BitcoinAmountField(), clear(), setDisplayUnit(), setEnabled(), setupTabChain(), and unitChanged().
Property Documentation
value
qint64 BitcoinAmountField::value read write
Definition at line 26 of file bitcoinamountfield.h.
Referenced by SendCoinsEntry::getValue(), ReceiveCoinsDialog::on_receiveButton_clicked(), setValue(), SendCoinsDialog::updateFeeMinimizedLabel(), SendCoinsDialog::updateGlobalFeeVariables(), SendCoinsEntry::validate(), validate(), and SendCoinsDialog::~SendCoinsDialog().
The documentation for this class was generated from the following files:
src/qt/bitcoinamountfield.h
src/qt/bitcoinamountfield.cpp
src/qt/moc_bitcoinamountfield.cpp