Dash Core: CKeePassIntegrator::CKeePassRequest Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CKeePassIntegrator::CKeePassRequest Class Reference
Public Member Functions
void addStrParameter (const std::string &strName, const std::string &strValue)
void addStrParameter (const std::string &strName, const SecureString &sValue)
std::string getJson ()
CKeePassRequest (const SecureString &sKey, const std::string &strType)
Private Member Functions
void init ()
Private Attributes
UniValue requestObj
std::string strType
std::string strIV
SecureString sKey
Detailed Description
Definition at line 34 of file keepass.h.
Constructor & Destructor Documentation
CKeePassRequest()
CKeePassIntegrator::CKeePassRequest::CKeePassRequest (const SecureString & sKey, const std::string & strType) inline
Definition at line 48 of file keepass.h.
References init(), sKey, and strType.
Member Function Documentation
addStrParameter() [1/2]
void CKeePassIntegrator::CKeePassRequest::addStrParameter (const std::string & strName, const std::string & strValue)
Definition at line 123 of file keepass.cpp.
References Pair(), UniValue::push_back(), and requestObj.
Referenced by CKeePassIntegrator::rpcAssociate(), CKeePassIntegrator::rpcGetLogins(), CKeePassIntegrator::rpcSetLogin(), and CKeePassIntegrator::rpcTestAssociation().
addStrParameter() [2/2]
void CKeePassIntegrator::CKeePassRequest::addStrParameter (const std::string & strName, const SecureString & sValue)
Definition at line 128 of file keepass.cpp.
References EncodeBase64(), EncryptAES256(), and CKeePassIntegrator::sKey.
getJson()
std::string CKeePassIntegrator::CKeePassRequest::getJson ()
Definition at line 140 of file keepass.cpp.
Referenced by CKeePassIntegrator::rpcAssociate(), CKeePassIntegrator::rpcGetLogins(), CKeePassIntegrator::rpcSetLogin(), and CKeePassIntegrator::rpcTestAssociation().
init()
void CKeePassIntegrator::CKeePassRequest::init () private
Definition at line 145 of file keepass.cpp.
References EncodeBase64Secure(), CKeePassIntegrator::generateRandomKey(), and CKeePassIntegrator::KEEPASS_CRYPTO_BLOCK_SIZE.
Referenced by CKeePassRequest().
Member Data Documentation
requestObj
UniValue CKeePassIntegrator::CKeePassRequest::requestObj private
Definition at line 36 of file keepass.h.
Referenced by addStrParameter().
sKey
SecureString CKeePassIntegrator::CKeePassRequest::sKey private
Definition at line 39 of file keepass.h.
Referenced by CKeePassRequest().
strIV
std::string CKeePassIntegrator::CKeePassRequest::strIV private
Definition at line 38 of file keepass.h.
strType
std::string CKeePassIntegrator::CKeePassRequest::strType private
Definition at line 37 of file keepass.h.
Referenced by CKeePassRequest().
The documentation for this class was generated from the following files:
src/keepass.h
src/keepass.cpp
Released under the MIT license