Dash Core: CMasternodePaymentVote Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodePaymentVote Class Reference
#include <masternode-payments.h>
Public Member Functions
CMasternodePaymentVote ()
CMasternodePaymentVote (COutPoint outpointMasternode, int nBlockHeight, CScript payee)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
uint256 GetHash () const
bool Sign ()
bool CheckSignature (const CPubKey &pubKeyMasternode, int nValidationHeight, int &nDos)
bool IsValid (CNode *pnode, int nValidationHeight, std::string &strError, CConnman &connman)
void Relay (CConnman &connman)
bool IsVerified ()
void MarkAsNotVerified ()
std::string ToString () const
Public Attributes
CTxIn vinMasternode
int nBlockHeight
CScript payee
std::vector< unsigned char > vchSig
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 109 of file masternode-payments.h.
Constructor & Destructor Documentation
CMasternodePaymentVote() [1/2]
CMasternodePaymentVote::CMasternodePaymentVote () inline
Definition at line 118 of file masternode-payments.h.
CMasternodePaymentVote() [2/2]
CMasternodePaymentVote::CMasternodePaymentVote (COutPoint outpointMasternode, int nBlockHeight, CScript payee) inline
Definition at line 125 of file masternode-payments.h.
Member Function Documentation
CheckSignature()
bool CMasternodePaymentVote::CheckSignature (const CPubKey & pubKeyMasternode, int nValidationHeight, int & nDos)
Definition at line 851 of file masternode-payments.cpp.
References error(), CMasternodeSync::IsMasternodeListSynced(), masternodeSync, nBlockHeight, payee, CTxIn::prevout, ScriptToAsmStr(), COutPoint::ToStringShort(), vchSig, CMessageSigner::VerifyMessage(), and vinMasternode.
GetHash()
uint256 CMasternodePaymentVote::GetHash () const inline
Definition at line 142 of file masternode-payments.h.
References CHashWriter::GetHash(), nBlockHeight, payee, CTxIn::prevout, PROTOCOL_VERSION, SER_GETHASH, and vinMasternode.
Referenced by CMasternodeBlockPayees::AddPayee(), CMasternodePayments::AddPaymentVote(), and Relay().
IsValid()
bool CMasternodePaymentVote::IsValid (CNode * pnode, int nValidationHeight, std::string & strError, CConnman & connman)
Definition at line 655 of file masternode-payments.cpp.
References CMasternodeMan::AskForMN(), fDIP0001WasLockedIn, fMasterNode, CNode::GetId(), CMasternodeMan::GetMasternodeInfo(), CMasternodeMan::GetMasternodeRank(), CMasternodePayments::GetMinMasternodePaymentsProto(), CMasternodeSync::IsMasternodeListSynced(), LogPrint(), LogPrintf, masternodeSync, MIN_MASTERNODE_PAYMENT_PROTO_VERSION_1, Misbehaving(), mnodeman, mnpayments, MNPAYMENTS_SIGNATURES_TOTAL, nBlockHeight, masternode_info_t::nProtocolVersion, CTxIn::prevout, strprintf, COutPoint::ToStringShort(), and vinMasternode.
IsVerified()
bool CMasternodePaymentVote::IsVerified () inline
Definition at line 156 of file masternode-payments.h.
References vchSig.
MarkAsNotVerified()
void CMasternodePaymentVote::MarkAsNotVerified () inline
Definition at line 157 of file masternode-payments.h.
References vchSig.
Relay()
void CMasternodePaymentVote::Relay (CConnman & connman)
Definition at line 842 of file masternode-payments.cpp.
References fDIP0001WasLockedIn, GetHash(), CMasternodePayments::GetMinMasternodePaymentsProto(), CMasternodeSync::IsWinnersListSynced(), masternodeSync, MIN_MASTERNODE_PAYMENT_PROTO_VERSION_2, mnpayments, MSG_MASTERNODE_PAYMENT_VOTE, and CConnman::RelayInv().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodePaymentVote::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 135 of file masternode-payments.h.
References nBlockHeight, payee, READWRITE, vchSig, and vinMasternode.
Sign()
bool CMasternodePaymentVote::Sign ()
Definition at line 416 of file masternode-payments.cpp.
References activeMasternode, CActiveMasternode::keyMasternode, LogPrintf, nBlockHeight, payee, CTxIn::prevout, CActiveMasternode::pubKeyMasternode, ScriptToAsmStr(), CMessageSigner::SignMessage(), COutPoint::ToStringShort(), vchSig, CMessageSigner::VerifyMessage(), and vinMasternode.
ToString()
std::string CMasternodePaymentVote::ToString () const
Definition at line 874 of file masternode-payments.cpp.
References nBlockHeight, payee, CTxIn::prevout, ScriptToAsmStr(), COutPoint::ToStringShort(), vchSig, and vinMasternode.
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodePaymentVote::ADD_SERIALIZE_METHODS
Definition at line 132 of file masternode-payments.h.
nBlockHeight
int CMasternodePaymentVote::nBlockHeight
Definition at line 114 of file masternode-payments.h.
Referenced by CMasternodePayments::AddPaymentVote(), CMasternodePayments::CheckAndRemove(), CheckSignature(), GetHash(), IsValid(), SerializationOp(), Sign(), and ToString().
payee
CScript CMasternodePaymentVote::payee
Definition at line 115 of file masternode-payments.h.
Referenced by CMasternodeBlockPayees::AddPayee(), CheckSignature(), GetHash(), SerializationOp(), Sign(), and ToString().
vchSig
std::vector<unsigned char> CMasternodePaymentVote::vchSig
Definition at line 116 of file masternode-payments.h.
Referenced by CheckSignature(), IsVerified(), MarkAsNotVerified(), SerializationOp(), Sign(), and ToString().
vinMasternode
CTxIn CMasternodePaymentVote::vinMasternode
Definition at line 112 of file masternode-payments.h.
Referenced by CheckSignature(), GetHash(), IsValid(), SerializationOp(), Sign(), and ToString().
The documentation for this class was generated from the following files:
src/masternode-payments.h
src/masternode-payments.cpp
Released under the MIT license