Dash Core: SendCoinsDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
SendCoinsDialog Class Reference
Dialog for sending bitcoins.
#include <sendcoinsdialog.h>
Public Slots
void clear ()
void reject ()
void accept ()
SendCoinsEntry * addEntry ()
void updateTabsAndLabels ()
void setBalance (const CAmount &balance, const CAmount &unconfirmedBalance, const CAmount &immatureBalance, const CAmount &anonymizedBalance, const CAmount &watchOnlyBalance, const CAmount &watchUnconfBalance, const CAmount &watchImmatureBalance)
Signals
void message (const QString &title, const QString &message, unsigned int style)
Public Member Functions
SendCoinsDialog (bool fPrivateSend=false, QWidget *parent=0)
~SendCoinsDialog ()
void setClientModel (ClientModel *clientModel)
void setModel (WalletModel *model)
QWidget * setupTabChain (QWidget *prev)
Set up the tab chain manually, as Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907).
void setAddress (const QString &address)
void pasteEntry (const SendCoinsRecipient &rv)
bool handlePaymentRequest (const SendCoinsRecipient &recipient)
Private Slots
void on_sendButton_clicked ()
void on_buttonChooseFee_clicked ()
void on_buttonMinimizeFee_clicked ()
void removeEntry (SendCoinsEntry *entry)
void useAvailableBalance (SendCoinsEntry *entry)
void updateDisplayUnit ()
void coinControlFeatureChanged (bool)
void coinControlButtonClicked ()
void coinControlChangeChecked (int)
void coinControlChangeEdited (const QString &)
void coinControlUpdateLabels ()
void coinControlClipboardQuantity ()
void coinControlClipboardAmount ()
void coinControlClipboardFee ()
void coinControlClipboardAfterFee ()
void coinControlClipboardBytes ()
void coinControlClipboardLowOutput ()
void coinControlClipboardChange ()
void setMinimumFee ()
void updateFeeSectionControls ()
void updateMinFeeLabel ()
void updateSmartFeeLabel ()
Private Member Functions
void send (QList< SendCoinsRecipient > recipients)
void processSendCoinsReturn (const WalletModel::SendCoinsReturn &sendCoinsReturn, const QString &msgArg=QString())
void minimizeFeeSection (bool fMinimize)
void updateFeeMinimizedLabel ()
void updateCoinControlState (CCoinControl &ctrl)
void showEvent (QShowEvent *event)
Private Attributes
Ui::SendCoinsDialog * ui
ClientModel * clientModel
WalletModel * model
bool fNewRecipientAllowed
bool fFeeMinimized
bool fPrivateSend
Detailed Description
Dialog for sending bitcoins.
Definition at line 31 of file sendcoinsdialog.h.
Constructor & Destructor Documentation
SendCoinsDialog()
SendCoinsDialog::SendCoinsDialog (bool fPrivateSend = false, QWidget * parent = 0) explicit
Definition at line 54 of file sendcoinsdialog.cpp.
References addEntry(), GUIUtil::Bold, clear(), coinControlButtonClicked(), coinControlChangeChecked(), coinControlChangeEdited(), coinControlClipboardAfterFee(), coinControlClipboardAmount(), coinControlClipboardBytes(), coinControlClipboardChange(), coinControlClipboardFee(), coinControlClipboardLowOutput(), coinControlClipboardQuantity(), DEFAULT_TRANSACTION_FEE, fPrivateSend, minimizeFeeSection(), GUIUtil::setFont(), GUIUtil::setupAddressWidget(), ui, and GUIUtil::updateFonts().
~SendCoinsDialog()
SendCoinsDialog::~SendCoinsDialog ()
Definition at line 239 of file sendcoinsdialog.cpp.
References fFeeMinimized, getConfTargetForIndex(), and ui.
Member Function Documentation
accept
void SendCoinsDialog::accept () slot
Definition at line 500 of file sendcoinsdialog.cpp.
References clear().
Referenced by send().
addEntry
SendCoinsEntry * SendCoinsDialog::addEntry () slot
Definition at line 505 of file sendcoinsdialog.cpp.
References SendCoinsEntry::clear(), coinControlUpdateLabels(), model, removeEntry(), SendCoinsEntry::setFocus(), SendCoinsEntry::setModel(), ui, updateTabsAndLabels(), and useAvailableBalance().
Referenced by clear(), pasteEntry(), removeEntry(), SendCoinsDialog(), and setAddress().
clear
void SendCoinsDialog::clear () slot
Definition at line 477 of file sendcoinsdialog.cpp.
References addEntry(), CoinControlDialog::coinControl(), coinControlUpdateLabels(), ui, CCoinControl::UnSelectAll(), and updateTabsAndLabels().
Referenced by accept(), reject(), and SendCoinsDialog().
coinControlButtonClicked
void SendCoinsDialog::coinControlButtonClicked () private slot
Definition at line 889 of file sendcoinsdialog.cpp.
References coinControlUpdateLabels(), model, and CoinControlDialog::setModel().
Referenced by SendCoinsDialog().
coinControlChangeChecked
void SendCoinsDialog::coinControlChangeChecked (int state) private slot
Definition at line 898 of file sendcoinsdialog.cpp.
References CoinControlDialog::coinControl(), coinControlChangeEdited(), CCoinControl::destChange, and ui.
Referenced by SendCoinsDialog().
coinControlChangeEdited
void SendCoinsDialog::coinControlChangeEdited (const QString & text) private slot
Definition at line 913 of file sendcoinsdialog.cpp.
References CoinControlDialog::coinControl(), DecodeDestination(), CCoinControl::destChange, WalletModel::getAddressTableModel(), GUIUtil::getThemedStyleQString(), WalletModel::IsSpendable(), IsValidDestination(), AddressTableModel::labelForAddress(), model, GUIUtil::TS_ERROR, GUIUtil::TS_PRIMARY, and ui.
Referenced by coinControlChangeChecked(), and SendCoinsDialog().
coinControlClipboardAfterFee
void SendCoinsDialog::coinControlClipboardAfterFee () private slot
Definition at line 854 of file sendcoinsdialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by SendCoinsDialog().
coinControlClipboardAmount
void SendCoinsDialog::coinControlClipboardAmount () private slot
Definition at line 842 of file sendcoinsdialog.cpp.
References GUIUtil::setClipboard(), and ui.
Referenced by SendCoinsDialog().
coinControlClipboardBytes
void SendCoinsDialog::coinControlClipboardBytes () private slot
Definition at line 860 of file sendcoinsdialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by SendCoinsDialog().
coinControlClipboardChange
void SendCoinsDialog::coinControlClipboardChange () private slot
Definition at line 872 of file sendcoinsdialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by SendCoinsDialog().
coinControlClipboardFee
void SendCoinsDialog::coinControlClipboardFee () private slot
Definition at line 848 of file sendcoinsdialog.cpp.
References ASYMP_UTF8, GUIUtil::setClipboard(), and ui.
Referenced by SendCoinsDialog().
coinControlClipboardLowOutput
void SendCoinsDialog::coinControlClipboardLowOutput () private slot
Definition at line 866 of file sendcoinsdialog.cpp.
References GUIUtil::setClipboard(), and ui.
Referenced by SendCoinsDialog().
coinControlClipboardQuantity
void SendCoinsDialog::coinControlClipboardQuantity () private slot
Definition at line 836 of file sendcoinsdialog.cpp.
References GUIUtil::setClipboard(), and ui.
Referenced by SendCoinsDialog().
coinControlFeatureChanged
void SendCoinsDialog::coinControlFeatureChanged (bool checked) private slot
Definition at line 878 of file sendcoinsdialog.cpp.
References CoinControlDialog::coinControl(), coinControlUpdateLabels(), model, CCoinControl::SetNull(), and ui.
Referenced by setModel().
coinControlUpdateLabels
void SendCoinsDialog::coinControlUpdateLabels () private slot
Definition at line 967 of file sendcoinsdialog.cpp.
References SendCoinsRecipient::amount, CoinControlDialog::coinControl(), CoinControlDialog::fSubtractFeeFromAmount, SendCoinsRecipient::fSubtractFeeFromAmount, WalletModel::getOptionsModel(), SendCoinsEntry::getValue(), model, CoinControlDialog::payAmounts, ui, updateCoinControlState(), and CoinControlDialog::updateLabels().
Referenced by addEntry(), clear(), coinControlButtonClicked(), coinControlFeatureChanged(), send(), setModel(), updateDisplayUnit(), and updateTabsAndLabels().
handlePaymentRequest()
bool SendCoinsDialog::handlePaymentRequest (const SendCoinsRecipient & recipient)
Definition at line 607 of file sendcoinsdialog.cpp.
References pasteEntry().
Referenced by WalletView::handlePaymentRequest().
message
void SendCoinsDialog::message (const QString & title, const QString & message, unsigned int style) signal
Referenced by processSendCoinsReturn().
minimizeFeeSection()
void SendCoinsDialog::minimizeFeeSection (bool fMinimize) private
Definition at line 698 of file sendcoinsdialog.cpp.
References fFeeMinimized, and ui.
Referenced by on_buttonChooseFee_clicked(), on_buttonMinimizeFee_clicked(), and SendCoinsDialog().
on_buttonChooseFee_clicked
void SendCoinsDialog::on_buttonChooseFee_clicked () private slot
Definition at line 708 of file sendcoinsdialog.cpp.
References minimizeFeeSection().
on_buttonMinimizeFee_clicked
void SendCoinsDialog::on_buttonMinimizeFee_clicked () private slot
Definition at line 713 of file sendcoinsdialog.cpp.
References minimizeFeeSection(), and updateFeeMinimizedLabel().
on_sendButton_clicked
void SendCoinsDialog::on_sendButton_clicked () private slot
Definition at line 251 of file sendcoinsdialog.cpp.
References ctx, fNewRecipientAllowed, WalletModel::getEncryptionStatus(), WalletModel::getOptionsModel(), SendCoinsEntry::getValue(), WalletModel::Locked, model, WalletModel::requestUnlock(), send(), ui, WalletModel::UnlockedForMixingOnly, and SendCoinsEntry::validate().
pasteEntry()
void SendCoinsDialog::pasteEntry (const SendCoinsRecipient & rv)
Definition at line 583 of file sendcoinsdialog.cpp.
References addEntry(), fNewRecipientAllowed, SendCoinsEntry::isClear(), SendCoinsEntry::setValue(), ui, and updateTabsAndLabels().
Referenced by handlePaymentRequest().
processSendCoinsReturn()
void SendCoinsDialog::processSendCoinsReturn (const WalletModel::SendCoinsReturn & sendCoinsReturn, const QString & msgArg = QString()) private
Definition at line 648 of file sendcoinsdialog.cpp.
References WalletModel::AbsurdFee, WalletModel::AmountExceedsBalance, WalletModel::AmountWithFeeExceedsBalance, WalletModel::DuplicateAddress, BitcoinUnits::formatWithUnit(), OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), WalletModel::InvalidAddress, WalletModel::InvalidAmount, maxTxFee, message(), model, CClientUIInterface::MSG_ERROR, CClientUIInterface::MSG_WARNING, WalletModel::OK, WalletModel::PaymentRequestExpired, WalletModel::SendCoinsReturn::reasonCommitFailed, WalletModel::SendCoinsReturn::status, WalletModel::TransactionCommitFailed, and WalletModel::TransactionCreationFailed.
Referenced by send().
reject
void SendCoinsDialog::reject () slot
Definition at line 495 of file sendcoinsdialog.cpp.
References clear().
removeEntry
void SendCoinsDialog::removeEntry (SendCoinsEntry * entry) private slot
Definition at line 534 of file sendcoinsdialog.cpp.
References addEntry(), ui, and updateTabsAndLabels().
Referenced by addEntry().
send()
void SendCoinsDialog::send (QList< SendCoinsRecipient > recipients) private
Definition at line 302 of file sendcoinsdialog.cpp.
References accept(), BitcoinUnits::availableUnits(), CoinControlDialog::coinControl(), coinControlUpdateLabels(), SendConfirmationDialog::exec(), fNewRecipientAllowed, BitcoinUnits::formatHtmlWithUnit(), BitcoinUnits::formatWithUnit(), fPrivateSend, OptionsModel::getCoinControlFeatures(), OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), WalletModelTransaction::getRecipients(), GUIUtil::getThemedStyleQString(), WalletModelTransaction::getTotalTransactionAmount(), WalletModelTransaction::getTransaction(), WalletModelTransaction::getTransactionFee(), WalletModelTransaction::getTransactionSize(), GUIUtil::HtmlEscape(), CCoinControl::IsUsingPrivateSend(), MAX_SEND_POPUP_ENTRIES, model, WalletModel::OK, WalletModel::prepareTransaction(), processSendCoinsReturn(), SEND_CONFIRM_DELAY, WalletModel::sendCoins(), WalletModel::SendCoinsReturn::status, GUIUtil::TS_ERROR, CMerkleTx::tx, CCoinControl::UnSelectAll(), updateCoinControlState(), and CCoinControl::UsePrivateSend().
Referenced by on_sendButton_clicked().
setAddress()
void SendCoinsDialog::setAddress (const QString & address)
Definition at line 563 of file sendcoinsdialog.cpp.
References addEntry(), SendCoinsEntry::isClear(), SendCoinsEntry::setAddress(), and ui.
Referenced by WalletView::gotoPrivateSendCoinsPage(), and WalletView::gotoSendCoinsPage().
setBalance
void SendCoinsDialog::setBalance (const CAmount & balance, const CAmount & unconfirmedBalance, const CAmount & immatureBalance, const CAmount & anonymizedBalance, const CAmount & watchOnlyBalance, const CAmount & watchUnconfBalance, const CAmount & watchImmatureBalance) slot
Definition at line 615 of file sendcoinsdialog.cpp.
References BitcoinUnits::formatWithUnit(), fPrivateSend, OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), model, and ui.
Referenced by setModel(), and updateDisplayUnit().
setClientModel()
void SendCoinsDialog::setClientModel (ClientModel * clientModel)
Definition at line 170 of file sendcoinsdialog.cpp.
References clientModel, and updateSmartFeeLabel().
Referenced by WalletView::setClientModel().
setMinimumFee
void SendCoinsDialog::setMinimumFee () private slot
Definition at line 750 of file sendcoinsdialog.cpp.
References GetRequiredFee(), and ui.
Referenced by setModel().
setModel()
void SendCoinsDialog::setModel (WalletModel * model)
Definition at line 179 of file sendcoinsdialog.cpp.
References coinControlFeatureChanged(), coinControlUpdateLabels(), confTargets, GUIUtil::formatNiceTimeOffset(), WalletModel::getAnonymizedBalance(), WalletModel::getBalance(), OptionsModel::getCoinControlFeatures(), WalletModel::getDefaultConfirmTarget(), WalletModel::getImmatureBalance(), getIndexForConfTarget(), WalletModel::getOptionsModel(), WalletModel::getUnconfirmedBalance(), WalletModel::getWatchBalance(), WalletModel::getWatchImmatureBalance(), WalletModel::getWatchUnconfirmedBalance(), model, Params(), setBalance(), setMinimumFee(), SendCoinsEntry::setModel(), ui, updateDisplayUnit(), updateFeeSectionControls(), updateMinFeeLabel(), and updateSmartFeeLabel().
Referenced by WalletView::setWalletModel().
setupTabChain()
QWidget * SendCoinsDialog::setupTabChain (QWidget * prev)
Set up the tab chain manually, as Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907).
Definition at line 547 of file sendcoinsdialog.cpp.
References SendCoinsEntry::setupTabChain(), and ui.
Referenced by updateTabsAndLabels().
showEvent()
void SendCoinsDialog::showEvent (QShowEvent * event) private
Definition at line 800 of file sendcoinsdialog.cpp.
References fPrivateSend, and CoinControlDialog::usePrivateSend().
updateCoinControlState()
void SendCoinsDialog::updateCoinControlState (CCoinControl & ctrl) private
Definition at line 788 of file sendcoinsdialog.cpp.
References getConfTargetForIndex(), CCoinControl::m_confirm_target, CCoinControl::m_feerate, and ui.
Referenced by coinControlUpdateLabels(), send(), and updateSmartFeeLabel().
updateDisplayUnit
void SendCoinsDialog::updateDisplayUnit () private slot
Definition at line 638 of file sendcoinsdialog.cpp.
References coinControlUpdateLabels(), WalletModel::getAnonymizedBalance(), WalletModel::getBalance(), OptionsModel::getDisplayUnit(), WalletModel::getImmatureBalance(), WalletModel::getOptionsModel(), WalletModel::getUnconfirmedBalance(), WalletModel::getWatchBalance(), WalletModel::getWatchImmatureBalance(), WalletModel::getWatchUnconfirmedBalance(), model, setBalance(), ui, updateMinFeeLabel(), and updateSmartFeeLabel().
Referenced by setModel().
updateFeeMinimizedLabel()
void SendCoinsDialog::updateFeeMinimizedLabel () private
Definition at line 768 of file sendcoinsdialog.cpp.
References BitcoinUnits::formatWithUnit(), OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), model, and ui.
Referenced by on_buttonMinimizeFee_clicked(), and updateSmartFeeLabel().
updateFeeSectionControls
void SendCoinsDialog::updateFeeSectionControls () private slot
Definition at line 755 of file sendcoinsdialog.cpp.
References ui.
Referenced by setModel().
updateMinFeeLabel
void SendCoinsDialog::updateMinFeeLabel () private slot
Definition at line 780 of file sendcoinsdialog.cpp.
References BitcoinUnits::formatWithUnit(), OptionsModel::getDisplayUnit(), WalletModel::getOptionsModel(), GetRequiredFee(), model, and ui.
Referenced by setModel(), and updateDisplayUnit().
updateSmartFeeLabel
void SendCoinsDialog::updateSmartFeeLabel () private slot
Definition at line 808 of file sendcoinsdialog.cpp.
References FALLBACK, feeEstimator, BitcoinUnits::formatWithUnit(), OptionsModel::getDisplayUnit(), CFeeRate::GetFeePerK(), GetMinimumFee(), WalletModel::getOptionsModel(), CCoinControl::m_feerate, mempool, model, FeeCalculation::reason, FeeCalculation::returnedTarget, ui, updateCoinControlState(), and updateFeeMinimizedLabel().
Referenced by setClientModel(), setModel(), and updateDisplayUnit().
updateTabsAndLabels
void SendCoinsDialog::updateTabsAndLabels () slot
Definition at line 528 of file sendcoinsdialog.cpp.
References coinControlUpdateLabels(), and setupTabChain().
Referenced by addEntry(), clear(), pasteEntry(), and removeEntry().
useAvailableBalance
void SendCoinsDialog::useAvailableBalance (SendCoinsEntry * entry) private slot
Definition at line 719 of file sendcoinsdialog.cpp.
References SendCoinsRecipient::amount, SendCoinsEntry::checkSubtractFeeFromAmount(), CoinControlDialog::coinControl(), fPrivateSend, WalletModel::getAnonymizedBalance(), WalletModel::getBalance(), OptionsModel::getCoinControlFeatures(), WalletModel::getOptionsModel(), SendCoinsEntry::getValue(), model, SendCoinsEntry::setAmount(), and ui.
Referenced by addEntry().
Member Data Documentation
clientModel
ClientModel* SendCoinsDialog::clientModel private
Definition at line 61 of file sendcoinsdialog.h.
Referenced by setClientModel().
fFeeMinimized
bool SendCoinsDialog::fFeeMinimized private
Definition at line 65 of file sendcoinsdialog.h.
Referenced by minimizeFeeSection(), and ~SendCoinsDialog().
fNewRecipientAllowed
bool SendCoinsDialog::fNewRecipientAllowed private
Definition at line 63 of file sendcoinsdialog.h.
Referenced by on_sendButton_clicked(), pasteEntry(), and send().
fPrivateSend
bool SendCoinsDialog::fPrivateSend private
Definition at line 66 of file sendcoinsdialog.h.
Referenced by send(), SendCoinsDialog(), setBalance(), showEvent(), and useAvailableBalance().
model
WalletModel* SendCoinsDialog::model private
Definition at line 62 of file sendcoinsdialog.h.
Referenced by addEntry(), coinControlButtonClicked(), coinControlChangeEdited(), coinControlFeatureChanged(), coinControlUpdateLabels(), on_sendButton_clicked(), processSendCoinsReturn(), send(), setBalance(), setModel(), updateDisplayUnit(), updateFeeMinimizedLabel(), updateMinFeeLabel(), updateSmartFeeLabel(), and useAvailableBalance().
ui
Ui::SendCoinsDialog* SendCoinsDialog::ui private
Definition at line 60 of file sendcoinsdialog.h.
Referenced by addEntry(), clear(), coinControlChangeChecked(), coinControlChangeEdited(), coinControlClipboardAfterFee(), coinControlClipboardAmount(), coinControlClipboardBytes(), coinControlClipboardChange(), coinControlClipboardFee(), coinControlClipboardLowOutput(), coinControlClipboardQuantity(), coinControlFeatureChanged(), coinControlUpdateLabels(), minimizeFeeSection(), on_sendButton_clicked(), pasteEntry(), removeEntry(), SendCoinsDialog(), setAddress(), setBalance(), setMinimumFee(), setModel(), setupTabChain(), updateCoinControlState(), updateDisplayUnit(), updateFeeMinimizedLabel(), updateFeeSectionControls(), updateMinFeeLabel(), updateSmartFeeLabel(), useAvailableBalance(), and ~SendCoinsDialog().
The documentation for this class was generated from the following files:
src/qt/sendcoinsdialog.h
src/qt/sendcoinsdialog.cpp
Released under the MIT license