Dash Core: BitcoinApplication Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
BitcoinApplication Class Reference
Main Dash application object.
Public Slots
void initializeResult (bool success)
void shutdownResult ()
void handleRunawayException (const QString &message)
Handle runaway exceptions. Shows a message box with the problem and quits the program.
Signals
void requestedInitialize ()
void requestedRestart (QStringList args)
void requestedShutdown ()
void stopThread ()
void splashFinished (QWidget *window)
Public Member Functions
BitcoinApplication (int &argc, char **argv)
~BitcoinApplication ()
void parameterSetup ()
parameter interaction/setup based on rules
void createOptionsModel (bool resetSettings)
Create options model.
void createWindow (const NetworkStyle *networkStyle)
Create main window.
void createSplashScreen (const NetworkStyle *networkStyle)
Create splash screen.
void requestInitialize ()
Request core initialization.
void requestShutdown ()
Request core shutdown.
int getReturnValue () const
Get process return value.
WId getMainWinId () const
Get window identifier of QMainWindow (BitcoinGUI)
Private Member Functions
void startThread ()
Private Attributes
QThread * coreThread
OptionsModel * optionsModel
ClientModel * clientModel
BitcoinGUI * window
QTimer * pollShutdownTimer
int returnValue
std::unique_ptr< QWidget > shutdownWindow
Detailed Description
Main Dash application object.
Definition at line 206 of file dash.cpp.
Constructor & Destructor Documentation
BitcoinApplication()
BitcoinApplication::BitcoinApplication (int & argc, char ** argv) explicit
Definition at line 350 of file dash.cpp.
~BitcoinApplication()
BitcoinApplication::~BitcoinApplication ()
Definition at line 366 of file dash.cpp.
References coreThread, optionsModel, OptionsModel::resetSettingsOnShutdown, stopThread(), and window.
Member Function Documentation
createOptionsModel()
void BitcoinApplication::createOptionsModel (bool resetSettings)
Create options model.
Definition at line 399 of file dash.cpp.
References optionsModel.
Referenced by main().
createSplashScreen()
void BitcoinApplication::createSplashScreen (const NetworkStyle * networkStyle)
Create splash screen.
Definition at line 414 of file dash.cpp.
References requestedShutdown(), and splashFinished().
Referenced by main().
createWindow()
void BitcoinApplication::createWindow (const NetworkStyle * networkStyle)
Create main window.
Definition at line 404 of file dash.cpp.
References GUIUtil::loadTheme(), pollShutdownTimer, and window.
Referenced by main().
getMainWinId()
WId BitcoinApplication::getMainWinId () const
Get window identifier of QMainWindow (BitcoinGUI)
Definition at line 560 of file dash.cpp.
References window.
Referenced by main().
getReturnValue()
int BitcoinApplication::getReturnValue () const inline
Get process return value.
Definition at line 232 of file dash.cpp.
References returnValue.
Referenced by main().
handleRunawayException
void BitcoinApplication::handleRunawayException (const QString & message) slot
Handle runaway exceptions. Shows a message box with the problem and quits the program.
Definition at line 554 of file dash.cpp.
Referenced by main(), and startThread().
initializeResult
void BitcoinApplication::initializeResult (bool success) slot
Definition at line 486 of file dash.cpp.
References clientModel, BitcoinGUI::DEFAULT_UIPLATFORM, BitcoinGUI::DEFAULT_WALLET, gArgs, ArgsManager::GetArg(), ArgsManager::GetBoolArg(), ClientModel::getOptionsModel(), GetWallets(), HasWallets(), PaymentServer::LoadRootCAs(), optionsModel, pollShutdownTimer, returnValue, BitcoinGUI::setClientModel(), GUIUtil::setupAppearance(), splashFinished(), and window.
Referenced by startThread().
parameterSetup()
void BitcoinApplication::parameterSetup ()
parameter interaction/setup based on rules
Definition at line 446 of file dash.cpp.
References InitLogging(), and InitParameterInteraction().
Referenced by main().
requestedInitialize
void BitcoinApplication::requestedInitialize () signal
Referenced by requestInitialize(), and startThread().
requestedRestart
void BitcoinApplication::requestedRestart (QStringList args) signal
Referenced by startThread().
requestedShutdown
void BitcoinApplication::requestedShutdown () signal
Referenced by createSplashScreen(), requestShutdown(), and startThread().
requestInitialize()
void BitcoinApplication::requestInitialize ()
Request core initialization.
Definition at line 452 of file dash.cpp.
References requestedInitialize(), and startThread().
Referenced by main().
requestShutdown()
void BitcoinApplication::requestShutdown ()
Request core shutdown.
Definition at line 459 of file dash.cpp.
References clientModel, pollShutdownTimer, requestedShutdown(), BitcoinGUI::setClientModel(), ShutdownWindow::showShutdownWindow(), shutdownWindow, StartShutdown(), startThread(), and window.
Referenced by main().
shutdownResult
void BitcoinApplication::shutdownResult () slot
Definition at line 549 of file dash.cpp.
Referenced by startThread().
splashFinished
void BitcoinApplication::splashFinished (QWidget * window) signal
Referenced by createSplashScreen(), and initializeResult().
startThread()
void BitcoinApplication::startThread () private
Definition at line 424 of file dash.cpp.
References coreThread, handleRunawayException(), initializeResult(), requestedInitialize(), requestedRestart(), requestedShutdown(), shutdownResult(), stopThread(), and window.
Referenced by requestInitialize(), and requestShutdown().
stopThread
void BitcoinApplication::stopThread () signal
Referenced by startThread(), and ~BitcoinApplication().
Member Data Documentation
clientModel
ClientModel* BitcoinApplication::clientModel private
Definition at line 253 of file dash.cpp.
Referenced by initializeResult(), and requestShutdown().
coreThread
QThread* BitcoinApplication::coreThread private
Definition at line 251 of file dash.cpp.
Referenced by startThread(), and ~BitcoinApplication().
optionsModel
OptionsModel* BitcoinApplication::optionsModel private
Definition at line 252 of file dash.cpp.
Referenced by createOptionsModel(), initializeResult(), and ~BitcoinApplication().
pollShutdownTimer
QTimer* BitcoinApplication::pollShutdownTimer private
Definition at line 255 of file dash.cpp.
Referenced by createWindow(), initializeResult(), and requestShutdown().
returnValue
int BitcoinApplication::returnValue private
Definition at line 260 of file dash.cpp.
Referenced by getReturnValue(), and initializeResult().
shutdownWindow
std::unique_ptr<QWidget> BitcoinApplication::shutdownWindow private
Definition at line 261 of file dash.cpp.
Referenced by requestShutdown().
window
BitcoinGUI* BitcoinApplication::window private
Definition at line 254 of file dash.cpp.
Referenced by createWindow(), getMainWinId(), initializeResult(), requestShutdown(), startThread(), and ~BitcoinApplication().
The documentation for this class was generated from the following file:
src/qt/dash.cpp
Released under the MIT license