Dash Core: BaseSignatureChecker Class Reference
BaseSignatureChecker Class Reference
#include <interpreter.h>
Public Member Functions
virtual bool CheckSig (const std::vector< unsigned char > &scriptSig, const std::vector< unsigned char > &vchPubKey, const CScript &scriptCode) const
virtual bool CheckLockTime (const CScriptNum &nLockTime) const
virtual bool CheckSequence (const CScriptNum &nSequence) const
virtual ~BaseSignatureChecker ()
Detailed Description
Definition at line 95 of file interpreter.h.
Constructor & Destructor Documentation
~BaseSignatureChecker()
virtual BaseSignatureChecker::~BaseSignatureChecker () inline virtual
Definition at line 113 of file interpreter.h.
Member Function Documentation
CheckLockTime()
virtual bool BaseSignatureChecker::CheckLockTime (const CScriptNum & nLockTime) const inline virtual
Reimplemented in TransactionSignatureChecker.
Definition at line 103 of file interpreter.h.
Referenced by EvalScript().
CheckSequence()
virtual bool BaseSignatureChecker::CheckSequence (const CScriptNum & nSequence) const inline virtual
Reimplemented in TransactionSignatureChecker.
Definition at line 108 of file interpreter.h.
Referenced by EvalScript().
CheckSig()
virtual bool BaseSignatureChecker::CheckSig (const std::vector< unsigned char > & scriptSig, const std::vector< unsigned char > & vchPubKey, const CScript & scriptCode) const inline virtual
Reimplemented in TransactionSignatureChecker.
Definition at line 98 of file interpreter.h.
Referenced by CombineMultisig(), and EvalScript().
The documentation for this class was generated from the following file:
src/script/interpreter.h