Dash Core: indirectmap< K, T > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
indirectmap< K, T > Class Template Reference
#include <indirectmap.h>
Public Types
typedef base::iterator iterator
typedef base::const_iterator const_iterator
typedef base::size_type size_type
typedef base::value_type value_type
Public Member Functions
std::pair< iterator, bool > insert (const value_type &value)
iterator find (const K &key)
const_iterator find (const K &key) const
iterator lower_bound (const K &key)
const_iterator lower_bound (const K &key) const
size_type erase (const K &key)
size_type count (const K &key) const
bool empty () const
size_type size () const
size_type max_size () const
void clear ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
Private Types
typedef std::map< const K *, T, DereferencingComparator< const K * > > base
Private Attributes
base m
Detailed Description
template<class K, class T>
class indirectmap< K, T >
Definition at line 22 of file indirectmap.h.
Member Typedef Documentation
base
template<class K, class T> typedef std::map<const K*, T, DereferencingComparator<const K*> > indirectmap< K, T >::base private
Definition at line 24 of file indirectmap.h.
const_iterator
template<class K, class T> typedef base::const_iterator indirectmap< K, T >::const_iterator
Definition at line 28 of file indirectmap.h.
iterator
template<class K, class T> typedef base::iterator indirectmap< K, T >::iterator
Definition at line 27 of file indirectmap.h.
size_type
template<class K, class T> typedef base::size_type indirectmap< K, T >::size_type
Definition at line 29 of file indirectmap.h.
value_type
template<class K, class T> typedef base::value_type indirectmap< K, T >::value_type
Definition at line 30 of file indirectmap.h.
Member Function Documentation
begin() [1/2]
template<class K, class T> iterator indirectmap< K, T >::begin () inline
Definition at line 48 of file indirectmap.h.
begin() [2/2]
template<class K, class T> const_iterator indirectmap< K, T >::begin () const inline
Definition at line 50 of file indirectmap.h.
cbegin()
template<class K, class T> const_iterator indirectmap< K, T >::cbegin () const inline
Definition at line 52 of file indirectmap.h.
Referenced by CTxMemPool::check().
cend()
template<class K, class T> const_iterator indirectmap< K, T >::cend () const inline
Definition at line 53 of file indirectmap.h.
Referenced by CTxMemPool::check().
clear()
template<class K, class T> void indirectmap< K, T >::clear () inline
Definition at line 47 of file indirectmap.h.
Referenced by CTxMemPool::_clear().
count()
template<class K, class T> size_type indirectmap< K, T >::count (const K & key) const inline
Definition at line 41 of file indirectmap.h.
Referenced by CTxMemPool::existsProviderTxConflict(), and CTxMemPool::isSpent().
empty()
template<class K, class T> bool indirectmap< K, T >::empty () const inline
Definition at line 44 of file indirectmap.h.
end() [1/2]
template<class K, class T> iterator indirectmap< K, T >::end () inline
Definition at line 49 of file indirectmap.h.
Referenced by AcceptToMemoryPoolWorker(), CTxMemPool::check(), CTxMemPool::removeConflicts(), llmq::CInstantSendManager::RemoveMempoolConflictsForLock(), CTxMemPool::removeRecursive(), and CTxMemPool::UpdateTransactionsFromBlock().
end() [2/2]
template<class K, class T> const_iterator indirectmap< K, T >::end () const inline
Definition at line 51 of file indirectmap.h.
erase()
template<class K, class T> size_type indirectmap< K, T >::erase (const K & key) inline
Definition at line 40 of file indirectmap.h.
Referenced by CTxMemPool::removeUnchecked().
find() [1/2]
template<class K, class T> iterator indirectmap< K, T >::find (const K & key) inline
Definition at line 36 of file indirectmap.h.
Referenced by AcceptToMemoryPoolWorker(), CTxMemPool::check(), CTxMemPool::removeConflicts(), llmq::CInstantSendManager::RemoveMempoolConflictsForLock(), and CTxMemPool::removeRecursive().
find() [2/2]
template<class K, class T> const_iterator indirectmap< K, T >::find (const K & key) const inline
Definition at line 37 of file indirectmap.h.
insert()
template<class K, class T> std::pair<iterator, bool> indirectmap< K, T >::insert (const value_type & value) inline
Definition at line 33 of file indirectmap.h.
Referenced by CTxMemPool::addUnchecked().
lower_bound() [1/2]
template<class K, class T> iterator indirectmap< K, T >::lower_bound (const K & key) inline
Definition at line 38 of file indirectmap.h.
Referenced by CTxMemPool::check(), and CTxMemPool::UpdateTransactionsFromBlock().
lower_bound() [2/2]
template<class K, class T> const_iterator indirectmap< K, T >::lower_bound (const K & key) const inline
Definition at line 39 of file indirectmap.h.
max_size()
template<class K, class T> size_type indirectmap< K, T >::max_size () const inline
Definition at line 46 of file indirectmap.h.
size()
template<class K, class T> size_type indirectmap< K, T >::size () const inline
Definition at line 45 of file indirectmap.h.
Referenced by CTxMemPool::check(), and memusage::DynamicUsage().
Member Data Documentation
m
template<class K, class T> base indirectmap< K, T >::m private
Definition at line 25 of file indirectmap.h.
Referenced by indirectmap< COutPoint, const CTransaction *>::begin(), indirectmap< COutPoint, const CTransaction *>::cbegin(), indirectmap< COutPoint, const CTransaction *>::cend(), indirectmap< COutPoint, const CTransaction *>::clear(), indirectmap< COutPoint, const CTransaction *>::count(), indirectmap< COutPoint, const CTransaction *>::empty(), indirectmap< COutPoint, const CTransaction *>::end(), indirectmap< COutPoint, const CTransaction *>::erase(), indirectmap< COutPoint, const CTransaction *>::find(), indirectmap< COutPoint, const CTransaction *>::insert(), indirectmap< COutPoint, const CTransaction *>::lower_bound(), indirectmap< COutPoint, const CTransaction *>::max_size(), and indirectmap< COutPoint, const CTransaction *>::size().
The documentation for this class was generated from the following file:
src/indirectmap.h
Released under the MIT license