Dash Core: test_framework.blockstore.BlockStore Class Reference
test_framework.blockstore.BlockStore Class Reference
Public Member Functions
def __init__ (self, datadir)
def close (self)
def get (self, blockhash)
def get_header (self, blockhash)
def headers_for (self, locator, hash_stop, current_tip=None)
def add_block (self, block)
def add_header (self, header)
def get_blocks (self, inv)
def get_locator (self, current_tip=None)
Public Attributes
blockDB
currentBlock
headers_map
Detailed Description
Definition at line 10 of file blockstore.py.
Constructor & Destructor Documentation
__init__()
def test_framework.blockstore.BlockStore.__init__ (self, datadir)
Definition at line 11 of file blockstore.py.
Member Function Documentation
add_block()
def test_framework.blockstore.BlockStore.add_block (self, block)
Definition at line 65 of file blockstore.py.
add_header()
def test_framework.blockstore.BlockStore.add_header (self, header)
Definition at line 74 of file blockstore.py.
close()
def test_framework.blockstore.BlockStore.close (self)
Definition at line 16 of file blockstore.py.
Referenced by test_framework.mininode.NodeConn.handle_close().
get()
def test_framework.blockstore.BlockStore.get (self, blockhash)
Definition at line 19 of file blockstore.py.
Referenced by test_framework.blockstore.BlockStore.get_blocks(), test_framework.blockstore.BlockStore.get_locator(), and test_framework.blockstore.TxStore.get_transactions().
get_blocks()
def test_framework.blockstore.BlockStore.get_blocks (self, inv)
Definition at line 77 of file blockstore.py.
get_header()
def test_framework.blockstore.BlockStore.get_header (self, blockhash)
Definition at line 31 of file blockstore.py.
Referenced by test_framework.blockstore.BlockStore.headers_for().
get_locator()
def test_framework.blockstore.BlockStore.get_locator (self, current_tip = None)
Definition at line 86 of file blockstore.py.
headers_for()
def test_framework.blockstore.BlockStore.headers_for (self, locator, hash_stop, current_tip = None)
Definition at line 40 of file blockstore.py.
Member Data Documentation
blockDB
test_framework.blockstore.BlockStore.blockDB
Definition at line 12 of file blockstore.py.
Referenced by test_framework.blockstore.BlockStore.add_block(), test_framework.blockstore.BlockStore.close(), and test_framework.blockstore.BlockStore.get().
currentBlock
test_framework.blockstore.BlockStore.currentBlock
Definition at line 13 of file blockstore.py.
Referenced by test_framework.blockstore.BlockStore.add_block(), test_framework.blockstore.BlockStore.get_locator(), and test_framework.blockstore.BlockStore.headers_for().
headers_map
test_framework.blockstore.BlockStore.headers_map
Definition at line 14 of file blockstore.py.
Referenced by test_framework.blockstore.BlockStore.add_block(), test_framework.blockstore.BlockStore.add_header(), and test_framework.blockstore.BlockStore.get_header().
The documentation for this class was generated from the following file:
qa/rpc-tests/test_framework/blockstore.py