Dash Core: AddressTableModel Class Reference
AddressTableModel Class Reference
#include <addresstablemodel.h>
Public Types
enum ColumnIndex { Label = 0, Address = 1 }
enum RoleIndex { TypeRole = Qt::UserRole }
enum EditStatus {
OK, NO_CHANGES, INVALID_ADDRESS, DUPLICATE_ADDRESS,
WALLET_UNLOCK_FAILURE, KEY_GENERATION_FAILURE
}
Public Slots
void updateEntry (const QString &address, const QString &label, bool isMine, const QString &purpose, int status)
Public Member Functions
AddressTableModel (CWallet *wallet, WalletModel *parent=0)
~AddressTableModel ()
QString addRow (const QString &type, const QString &label, const QString &address)
QString labelForAddress (const QString &address) const
int lookupAddress (const QString &address) const
EditStatus getEditStatus () const
Methods overridden from QAbstractTableModel
int rowCount (const QModelIndex &parent) const
int columnCount (const QModelIndex &parent) const
QVariant data (const QModelIndex &index, int role) const
bool setData (const QModelIndex &index, const QVariant &value, int role)
QVariant headerData (int section, Qt::Orientation orientation, int role) const
QModelIndex index (int row, int column, const QModelIndex &parent) const
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Qt::ItemFlags flags (const QModelIndex &index) const
Static Public Attributes
static const QString Send = "S"
static const QString Receive = "R"
Private Member Functions
void emitDataChanged (int index)
Private Attributes
WalletModel * walletModel
CWallet * wallet
AddressTablePriv * priv
QStringList columns
EditStatus editStatus
Friends
class AddressTablePriv
Detailed Description
Qt model of the address book in the core. This allows views to access and modify the address book.
Definition at line 19 of file addresstablemodel.h.
Member Enumeration Documentation
ColumnIndex
enum AddressTableModel::ColumnIndex
Enumerator
Label
User specified label
Address
Bitcoin address
Definition at line 27 of file addresstablemodel.h.
EditStatus
enum AddressTableModel::EditStatus
Return status of edit/insert operation
Enumerator
OK
Everything ok
NO_CHANGES
No changes were made during edit operation
INVALID_ADDRESS
Unparseable address
DUPLICATE_ADDRESS
Address already in address book
WALLET_UNLOCK_FAILURE
Wallet could not be unlocked to create new receiving address
KEY_GENERATION_FAILURE
Generating a new public key for a receiving address failed
Definition at line 37 of file addresstablemodel.h.
RoleIndex
enum AddressTableModel::RoleIndex
Enumerator
TypeRole
Type of address (Send or Receive)
Definition at line 32 of file addresstablemodel.h.
Constructor & Destructor Documentation
AddressTableModel()
AddressTableModel::AddressTableModel (CWallet * wallet, WalletModel * parent = 0) explicit
Definition at line 168 of file addresstablemodel.cpp.
~AddressTableModel()
AddressTableModel::~AddressTableModel ()
Definition at line 176 of file addresstablemodel.cpp.
Member Function Documentation
addRow()
QString AddressTableModel::addRow (const QString & type, const QString & label, const QString & address)
Definition at line 346 of file addresstablemodel.cpp.
Referenced by ReceiveCoinsDialog::on_receiveButton_clicked(), and EditAddressDialog::saveCurrentRow().
columnCount()
int AddressTableModel::columnCount (const QModelIndex & parent) const
Definition at line 187 of file addresstablemodel.cpp.
data()
QVariant AddressTableModel::data (const QModelIndex & index, int role) const
Definition at line 193 of file addresstablemodel.cpp.
Referenced by TransactionView::editLabel(), and index().
emitDataChanged()
void AddressTableModel::emitDataChanged (int index) private
Notify listeners that data changed.
Definition at line 452 of file addresstablemodel.cpp.
Referenced by AddressTablePriv::updateEntry().
flags()
Qt::ItemFlags AddressTableModel::flags (const QModelIndex & index) const
Definition at line 308 of file addresstablemodel.cpp.
getEditStatus()
EditStatus AddressTableModel::getEditStatus () const inline
Definition at line 75 of file addresstablemodel.h.
Referenced by EditAddressDialog::accept().
headerData()
QVariant AddressTableModel::headerData (int section, Qt::Orientation orientation, int role) const
Definition at line 296 of file addresstablemodel.cpp.
index()
QModelIndex AddressTableModel::index (int row, int column, const QModelIndex & parent) const
Definition at line 325 of file addresstablemodel.cpp.
Referenced by data(), TransactionView::editLabel(), emitDataChanged(), flags(), lookupAddress(), AddressBookPage::selectNewAddress(), and setData().
labelForAddress()
QString AddressTableModel::labelForAddress (const QString & address) const
Definition at line 424 of file addresstablemodel.cpp.
Referenced by TransactionTableModel::addressColor(), SendCoinsDialog::coinControlChangeEdited(), TransactionTableModel::data(), TransactionTableModel::lookupAddress(), ReceiveCoinsDialog::on_receiveButton_clicked(), SendCoinsEntry::updateLabel(), and CoinControlDialog::updateView().
lookupAddress()
int AddressTableModel::lookupAddress (const QString & address) const
Definition at line 438 of file addresstablemodel.cpp.
Referenced by TransactionView::editLabel().
removeRows()
bool AddressTableModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Definition at line 405 of file addresstablemodel.cpp.
rowCount()
int AddressTableModel::rowCount (const QModelIndex & parent) const
Definition at line 181 of file addresstablemodel.cpp.
setData()
bool AddressTableModel::setData (const QModelIndex & index, const QVariant & value, int role)
Definition at line 240 of file addresstablemodel.cpp.
updateEntry
void AddressTableModel::updateEntry (const QString & address, const QString & label, bool isMine, const QString & purpose, int status) slot
Definition at line 339 of file addresstablemodel.cpp.
Referenced by WalletModel::updateAddressBook().
Friends And Related Function Documentation
AddressTablePriv
friend class AddressTablePriv friend
Definition at line 92 of file addresstablemodel.h.
Referenced by AddressTableModel().
Member Data Documentation
columns
QStringList AddressTableModel::columns private
Definition at line 81 of file addresstablemodel.h.
Referenced by AddressTableModel(), columnCount(), emitDataChanged(), and headerData().
editStatus
EditStatus AddressTableModel::editStatus private
Definition at line 82 of file addresstablemodel.h.
Referenced by addRow(), getEditStatus(), and setData().
priv
AddressTablePriv* AddressTableModel::priv private
Definition at line 80 of file addresstablemodel.h.
Referenced by AddressTableModel(), index(), removeRows(), rowCount(), updateEntry(), and ~AddressTableModel().
Receive
const QString AddressTableModel::Receive = "R" static
Specifies receive address
Definition at line 47 of file addresstablemodel.h.
Referenced by addRow(), data(), TransactionView::editLabel(), ReceiveCoinsDialog::on_receiveButton_clicked(), EditAddressDialog::saveCurrentRow(), and AddressBookPage::setModel().
Send
const QString AddressTableModel::Send = "S" static
Specifies send address
Definition at line 46 of file addresstablemodel.h.
Referenced by addRow(), data(), EditAddressDialog::saveCurrentRow(), and AddressBookPage::setModel().
wallet
CWallet* AddressTableModel::wallet private
Definition at line 79 of file addresstablemodel.h.
walletModel
WalletModel* AddressTableModel::walletModel private
Definition at line 78 of file addresstablemodel.h.
Referenced by addRow().
The documentation for this class was generated from the following files:
src/qt/addresstablemodel.h
src/qt/addresstablemodel.cpp