Dash Core: UniValue Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
UniValue Class Reference
#include <univalue.h>
Public Types
enum VType {
VNULL, VOBJ, VARR, VSTR,
VNUM, VBOOL
}
Public Member Functions
UniValue ()
UniValue (UniValue::VType initialType, const std::string &initialStr="")
UniValue (uint64_t val_)
UniValue (int64_t val_)
UniValue (bool val_)
UniValue (int val_)
UniValue (double val_)
UniValue (const std::string &val_)
UniValue (const char *val_)
void clear ()
bool setNull ()
bool setBool (bool val)
bool setNumStr (const std::string &val)
bool setInt (uint64_t val)
bool setInt (int64_t val)
bool setInt (int val_)
bool setFloat (double val)
bool setStr (const std::string &val)
bool setArray ()
bool setObject ()
enum VType getType () const
const std::string & getValStr () const
bool empty () const
size_t size () const
bool getBool () const
void getObjMap (std::map< std::string, UniValue > &kv) const
bool checkObject (const std::map< std::string, UniValue::VType > &memberTypes) const
const UniValue & operator[] (const std::string &key) const
const UniValue & operator[] (size_t index) const
bool exists (const std::string &key) const
bool isNull () const
bool isTrue () const
bool isFalse () const
bool isBool () const
bool isStr () const
bool isNum () const
bool isArray () const
bool isObject () const
bool push_back (const UniValue &val)
bool push_back (const std::string &val_)
bool push_back (const char *val_)
bool push_back (uint64_t val_)
bool push_back (int64_t val_)
bool push_back (int val_)
bool push_back (double val_)
bool push_backV (const std::vector< UniValue > &vec)
void __pushKV (const std::string &key, const UniValue &val)
bool pushKV (const std::string &key, const UniValue &val)
bool pushKV (const std::string &key, const std::string &val_)
bool pushKV (const std::string &key, const char *val_)
bool pushKV (const std::string &key, int64_t val_)
bool pushKV (const std::string &key, uint64_t val_)
bool pushKV (const std::string &key, int val_)
bool pushKV (const std::string &key, double val_)
bool pushKVs (const UniValue &obj)
std::string write (unsigned int prettyIndent=0, unsigned int indentLevel=0) const
bool read (const char *raw, size_t len)
bool read (const char *raw)
bool read (const std::string &rawStr)
const std::vector< std::string > & getKeys () const
const std::vector< UniValue > & getValues () const
bool get_bool () const
const std::string & get_str () const
int get_int () const
int64_t get_int64 () const
double get_real () const
const UniValue & get_obj () const
const UniValue & get_array () const
enum VType type () const
bool push_back (std::pair< std::string, UniValue > pear)
Private Member Functions
bool findKey (const std::string &key, size_t &retIdx) const
void writeArray (unsigned int prettyIndent, unsigned int indentLevel, std::string &s) const
void writeObject (unsigned int prettyIndent, unsigned int indentLevel, std::string &s) const
Private Attributes
UniValue::VType typ
std::string val
std::vector< std::string > keys
std::vector< UniValue > values
Friends
const UniValue & find_value (const UniValue &obj, const std::string &name)
Detailed Description
Definition at line 20 of file univalue.h.
Member Enumeration Documentation
VType
enum UniValue::VType
Enumerator
VNULL
VOBJ
VARR
VSTR
VNUM
VBOOL
Definition at line 22 of file univalue.h.
Constructor & Destructor Documentation
UniValue() [1/9]
UniValue::UniValue () inline
Definition at line 24 of file univalue.h.
References typ, and VNULL.
UniValue() [2/9]
UniValue::UniValue (UniValue::VType initialType, const std::string & initialStr = "") inline
Definition at line 25 of file univalue.h.
References typ, and val.
UniValue() [3/9]
UniValue::UniValue (uint64_t val_) inline
Definition at line 29 of file univalue.h.
References setInt().
UniValue() [4/9]
UniValue::UniValue (int64_t val_) inline
Definition at line 32 of file univalue.h.
References setInt().
UniValue() [5/9]
UniValue::UniValue (bool val_) inline
Definition at line 35 of file univalue.h.
References setBool().
UniValue() [6/9]
UniValue::UniValue (int val_) inline
Definition at line 38 of file univalue.h.
References setInt().
UniValue() [7/9]
UniValue::UniValue (double val_) inline
Definition at line 41 of file univalue.h.
References setFloat().
UniValue() [8/9]
UniValue::UniValue (const std::string & val_) inline
Definition at line 44 of file univalue.h.
References setStr().
UniValue() [9/9]
UniValue::UniValue (const char * val_) inline
Definition at line 47 of file univalue.h.
References setStr().
Member Function Documentation
__pushKV()
void UniValue::__pushKV (const std::string & key, const UniValue & val)
Definition at line 129 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
checkObject()
bool UniValue::checkObject (const std::map< std::string, UniValue::VType > & memberTypes) const
Definition at line 181 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and MutateTxSign().
clear()
void UniValue::clear ()
Definition at line 17 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), CPrivateSendServer::GetJsonInfo(), CPrivateSendClientSession::GetJsonInfo(), CPrivateSendClientManager::GetJsonInfo(), importmulti(), listtransactions(), RPCConsole::RPCParseCommandLine(), CCbTx::ToJson(), CProRegTx::ToJson(), CSimplifiedMNListEntry::ToJson(), CDeterministicMNState::ToJson(), CProUpServTx::ToJson(), CProUpRegTx::ToJson(), CProUpRevTx::ToJson(), and CDeterministicMN::ToJson().
empty()
bool UniValue::empty () const inline
Definition at line 67 of file univalue.h.
References values.
Referenced by _bls(), BOOST_AUTO_TEST_CASE(), CallRPC(), CKeePassIntegrator::doHTTPPost(), protx(), quorum(), and signrawtransaction().
exists()
bool UniValue::exists (const std::string & key) const inline
Definition at line 76 of file univalue.h.
References findKey().
Referenced by BOOST_AUTO_TEST_CASE(), fundrawtransaction(), GetImportTimestamp(), importmulti(), listunspent(), MutateTxSign(), ProcessImport(), and signrawtransaction().
findKey()
bool UniValue::findKey (const std::string & key, size_t & retIdx) const private
Definition at line 169 of file univalue.cpp.
Referenced by exists().
get_array()
const UniValue & UniValue::get_array () const
Definition at line 141 of file univalue_get.cpp.
References typ, and VARR.
Referenced by addmultisigaddress(), combinerawtransaction(), createmultisig(), createrawtransaction(), getblockstats(), getCategoryMask(), CKeePassIntegrator::CKeePassResponse::getEntries(), gettxoutproof(), HTTPReq_JSONRPC(), listunspent(), ProcessImport(), sendmany(), and signrawtransaction().
get_bool()
bool UniValue::get_bool () const
Definition at line 90 of file univalue_get.cpp.
References getBool(), typ, and VBOOL.
Referenced by BOOST_AUTO_TEST_CASE(), fundrawtransaction(), getbalance(), getblock(), getblockheader(), getblockheaders(), getmempoolancestors(), getmempooldescendants(), getrawmempool(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), gettxout(), importaddress(), importmulti(), importprivkey(), importpubkey(), listaccounts(), ListReceived(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), ParseBoolV(), CKeePassIntegrator::CKeePassResponse::parseResponse(), ProcessImport(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), setnetworkactive(), and walletpassphrase().
get_int()
int UniValue::get_int () const
Definition at line 104 of file univalue_get.cpp.
References getValStr(), ParseInt32(), typ, and VNUM.
Referenced by addmultisigaddress(), CommandLineRPC(), createmultisig(), createrawtransaction(), CSuperblock::CSuperblock(), estimatefee(), fundrawtransaction(), getaddressdeltas(), getaddresstxids(), getbalance(), getblock(), getblockhash(), getblockhashes(), getblockheaders(), getblockstats(), getchaintips(), getchaintxstats(), getmerkleblocks(), getnetworkhashps(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), getspecialtxes(), getsuperblockbudget(), gettxout(), importelectrumwallet(), JSONErrorReply(), JSONRPCProcessBatchReply(), keypoolrefill(), listaccounts(), ListReceived(), listsinceblock(), listtransactions(), listunspent(), CGovernanceObject::LoadData(), lockunspent(), movecmd(), ParseBoolV(), ParseConfirmTarget(), pruneblockchain(), RPCExecutor::request(), rescanblockchain(), sendfrom(), sendmany(), setprivatesendamount(), setprivatesendrounds(), signrawtransaction(), stop(), verifychain(), voteraw(), waitforblock(), waitforblockheight(), and waitfornewblock().
get_int64()
int64_t UniValue::get_int64 () const
Definition at line 114 of file univalue_get.cpp.
References getValStr(), ParseInt64(), typ, and VNUM.
Referenced by createrawtransaction(), disconnectnode(), getblocktemplate(), CProposalValidator::GetDataValue(), GetImportTimestamp(), listunspent(), prioritisetransaction(), setban(), setmocktime(), spork(), voteraw(), and walletpassphrase().
get_obj()
const UniValue & UniValue::get_obj () const
Definition at line 134 of file univalue_get.cpp.
References typ, and VOBJ.
Referenced by createrawtransaction(), CKeePassIntegrator::doHTTPPost(), getaddressdeltas(), getaddresstxids(), getblocktemplate(), getspentinfo(), listunspent(), lockunspent(), JSONRPCRequest::parse(), DefaultRequestHandler::ProcessReply(), sendmany(), and signrawtransaction().
get_real()
double UniValue::get_real () const
Definition at line 124 of file univalue_get.cpp.
References getValStr(), ParseDouble(), typ, and VNUM.
Referenced by estimaterawfee(), and CProposalValidator::GetDataValue().
get_str()
const std::string & UniValue::get_str () const
Definition at line 97 of file univalue_get.cpp.
References getValStr(), typ, and VSTR.
Referenced by _bls(), abandontransaction(), AccountFromValue(), addmultisigaddress(), addnode(), backupwallet(), bls_fromsecret(), CommandLineRPC(), createmultisig(), CSuperblock::CSuperblock(), debug(), decoderawtransaction(), decodescript(), disconnectnode(), CKeePassIntegrator::doHTTPPost(), dumpprivkey(), dumpwallet(), encryptwallet(), estimatesmartfee(), fundrawtransaction(), getaccount(), getaddednodeinfo(), getbalance(), getblock(), getblockheader(), getblockheaders(), getblockstats(), getblocktemplate(), getCategoryMask(), getchaintxstats(), CProposalValidator::GetDataValue(), GetImportTimestamp(), getmemoryinfo(), getmerkleblocks(), getreceivedbyaddress(), getspecialtxes(), gettransaction(), gettxout(), gettxoutproof(), gobject(), gobject_check(), gobject_count(), gobject_deserialize(), gobject_diff(), gobject_getcurrentvotes(), gobject_list(), gobject_submit(), gobject_vote_conf(), help(), importaddress(), importelectrumwallet(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), invalidateblock(), keepass(), listsinceblock(), listtransactions(), listunspent(), loadwallet(), lockunspent(), masternode(), masternode_connect(), masternode_count(), masternode_winners(), masternodelist(), mnsync(), movecmd(), JSONRPCRequest::parse(), ParseBoolV(), ParseHashV(), ParseHexV(), preciousblock(), prioritisetransaction(), ProcessImport(), protx(), protx_list(), quorum(), quorum_dkgsimerror(), quorum_sigs_cmd(), reconsiderblock(), removeprunedfunds(), RPCExecutor::request(), RPCConsole::RPCParseCommandLine(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), setaccount(), setban(), signmessage(), signmessagewithprivkey(), signrawtransaction(), spork(), submitblock(), validateaddress(), verifymessage(), voteraw(), waitforblock(), walletpassphrase(), and walletpassphrasechange().
getBool()
bool UniValue::getBool () const inline
Definition at line 71 of file univalue.h.
References isTrue().
Referenced by BOOST_AUTO_TEST_CASE(), and get_bool().
getKeys()
const std::vector< std::string > & UniValue::getKeys () const
Definition at line 76 of file univalue_get.cpp.
References keys, typ, and VOBJ.
Referenced by createrawtransaction(), importelectrumwallet(), listunspent(), RPCTypeCheckObj(), sendmany(), and transformNamedArguments().
getObjMap()
void UniValue::getObjMap (std::map< std::string, UniValue > & kv) const
Definition at line 159 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
getType()
enum VType UniValue::getType () const inline
Definition at line 65 of file univalue.h.
References typ.
Referenced by BOOST_AUTO_TEST_CASE(), CProposalValidator::GetDataValue(), ProcessImport(), read(), and type().
getValStr()
const std::string& UniValue::getValStr () const inline
Definition at line 66 of file univalue.h.
References val.
Referenced by AmountFromValue(), BOOST_AUTO_TEST_CASE(), CommandLineRPC(), CPrivateSend::DenominationToString(), get_int(), get_int64(), get_real(), get_str(), ParseBlock(), ParseDoubleV(), ParseHashUV(), ParseHexUV(), ParseInt32V(), and ParseInt64V().
getValues()
const std::vector< UniValue > & UniValue::getValues () const
Definition at line 83 of file univalue_get.cpp.
References typ, values, VARR, and VOBJ.
Referenced by getAddressesFromParams(), CGovernanceObject::GetJSONObject(), importmulti(), listtransactions(), CProposalValidator::ParseJSONData(), and transformNamedArguments().
isArray()
bool UniValue::isArray () const inline
Definition at line 84 of file univalue.h.
References typ, and VARR.
Referenced by BOOST_AUTO_TEST_CASE(), getAddressesFromParams(), getblocktemplate(), HTTPReq_JSONRPC(), JSONRPCProcessBatchReply(), logging(), JSONRPCRequest::parse(), ParseNonRFCJSONValue(), and RPCConsole::RPCParseCommandLine().
isBool()
bool UniValue::isBool () const inline
Definition at line 81 of file univalue.h.
References typ, and VBOOL.
Referenced by BOOST_AUTO_TEST_CASE(), and ParseBoolV().
isFalse()
bool UniValue::isFalse () const inline
Definition at line 80 of file univalue.h.
References typ, val, and VBOOL.
Referenced by BOOST_AUTO_TEST_CASE().
isNull()
bool UniValue::isNull () const inline
Definition at line 78 of file univalue.h.
References typ, and VNULL.
Referenced by _bls(), addmultisigaddress(), addnode(), BOOST_AUTO_TEST_CASE(), CommandLineRPC(), createrawtransaction(), disconnectnode(), estimaterawfee(), estimatesmartfee(), fundrawtransaction(), getaddednodeinfo(), getbalance(), getblock(), getblockheader(), getblockheaders(), getblockstats(), getblocktemplate(), getchaintips(), getchaintxstats(), getmemoryinfo(), getmempoolancestors(), getmempooldescendants(), getmerkleblocks(), getnetworkhashps(), getnewaddress(), getrawmempool(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), getspecialtxes(), gettransaction(), gettxout(), gettxoutproof(), gobject(), gobject_count(), gobject_diff(), gobject_getcurrentvotes(), gobject_list(), gobject_submit(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importpubkey(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), masternode(), masternode_winners(), masternodelist(), movecmd(), JSONRPCRequest::parse(), protx(), protx_list(), quorum(), quorum_dkgstatus(), quorum_info(), quorum_list(), quorum_memberof(), quorum_sigs_cmd(), rescanblockchain(), RPCTypeCheck(), RPCTypeCheckObj(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), setaccount(), setban(), signrawtransaction(), verifychain(), waitforblock(), waitforblockheight(), waitfornewblock(), and walletpassphrase().
isNum()
bool UniValue::isNum () const inline
Definition at line 83 of file univalue.h.
References typ, and VNUM.
Referenced by AmountFromValue(), BOOST_AUTO_TEST_CASE(), CommandLineRPC(), createrawtransaction(), getaddressdeltas(), getaddresstxids(), getblock(), getblockstats(), getblocktemplate(), GetImportTimestamp(), getrawtransaction(), ParseBoolV(), and stop().
isObject()
bool UniValue::isObject () const inline
Definition at line 85 of file univalue.h.
References typ, and VOBJ.
Referenced by BOOST_AUTO_TEST_CASE(), CRPCTable::execute(), getaddressdeltas(), getaddresstxids(), CGovernanceObject::GetJSONObject(), getspentinfo(), HTTPReq_JSONRPC(), JSONRPCProcessBatchReply(), MutateTxSign(), JSONRPCRequest::parse(), CProposalValidator::ParseJSONData(), RPCConsole::RPCParseCommandLine(), and signrawtransaction().
isStr()
bool UniValue::isStr () const inline
Definition at line 82 of file univalue.h.
References typ, and VSTR.
Referenced by AmountFromValue(), BOOST_AUTO_TEST_CASE(), CommandLineRPC(), decodescript(), disconnectnode(), getblocktemplate(), GetImportTimestamp(), getspentinfo(), JSONRPCRequest::parse(), ParseBoolV(), ParseHashUV(), ParseHashV(), ParseHexUV(), ParseHexV(), and RPCConsole::RPCParseCommandLine().
isTrue()
bool UniValue::isTrue () const inline
Definition at line 79 of file univalue.h.
References typ, val, and VBOOL.
Referenced by BOOST_AUTO_TEST_CASE(), getBool(), and setban().
operator[]() [1/2]
const UniValue & UniValue::operator[] (const std::string & key) const
Definition at line 199 of file univalue.cpp.
References NullUniValue.
operator[]() [2/2]
const UniValue & UniValue::operator[] (size_t index) const
Definition at line 211 of file univalue.cpp.
References NullUniValue.
push_back() [1/8]
bool UniValue::push_back (const UniValue & val)
Definition at line 110 of file univalue.cpp.
Referenced by AcentryToJSON(), addmultisigaddress(), CKeePassIntegrator::CKeePassRequest::addStrParameter(), BIP9SoftForkDesc(), BIP9SoftForkDescPushBack(), blockheaderToJSON(), blockToJSON(), bls_fromsecret(), bls_generate(), BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), BuildDMNListEntry(), BuildQuorumInfo(), createmultisig(), decodescript(), dumphdinfo(), dumpwallet(), entryToJSON(), estimaterawfee(), estimatesmartfee(), fundrawtransaction(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getaddressesbyaccount(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getbestchainlock(), getblockchaininfo(), getblockhashes(), getblockheaders(), getblocktemplate(), getchaintips(), getchaintxstats(), getgovernanceinfo(), CPrivateSendServer::GetJsonInfo(), CPrivateSendClientSession::GetJsonInfo(), CPrivateSendClientManager::GetJsonInfo(), getmemoryinfo(), getmempoolancestors(), getmempooldescendants(), getmerkleblocks(), getmininginfo(), getnettotals(), getnetworkinfo(), GetNetworksInfo(), GetNextMasternodeForPayment(), getpeerinfo(), getprivatesendinfo(), getrawtransaction(), getspecialtxes(), getspentinfo(), gettransaction(), gettxout(), gettxoutsetinfo(), getwalletinfo(), gobject_check(), gobject_get(), gobject_getcurrentvotes(), gobject_vote_conf(), importmulti(), JSONRPCExecBatch(), JSONRPCReplyObj(), JSONRPCRequestObj(), listaccounts(), listaddressbalances(), listaddressgroupings(), listbanned(), listlockunspent(), ListObjects(), ListReceived(), listsinceblock(), ListTransactions(), listunspent(), listwallets(), masternode_count(), masternode_list(), masternode_status(), masternode_winners(), masternodelist(), MaybePushAddress(), mempoolInfoToJSON(), mempoolToJSON(), mnsync(), GetinfoRequestHandler::PrepareRequest(), protx_list(), push_back(), quorum_dkgstatus(), quorum_list(), quorum_memberof(), quorum_selectquorum(), read(), resendwallettransactions(), rest_getutxos(), rest_headers(), RPCConvertValues(), RPCLockedMemoryInfo(), RPCConsole::RPCParseCommandLine(), ScriptPubKeyToUniv(), signrawtransaction(), SoftForkDesc(), SoftForkMajorityDesc(), spork(), CCbTx::ToJson(), llmq::CRecoveredSig::ToJson(), CProRegTx::ToJson(), CMasternodeMetaInfo::ToJson(), CSimplifiedMNListEntry::ToJson(), llmq::CDKGDebugSessionStatus::ToJson(), llmq::CDKGDebugStatus::ToJson(), llmq::CFinalCommitment::ToJson(), CDeterministicMNState::ToJson(), CProUpServTx::ToJson(), llmq::CFinalCommitmentTxPayload::ToJson(), CSimplifiedMNListDiff::ToJson(), CProUpRegTx::ToJson(), CProUpRevTx::ToJson(), CDeterministicMN::ToJson(), CGovernanceManager::ToJson(), transformNamedArguments(), TxInErrorToJSON(), TxToJSON(), TxToUniv(), validateaddress(), verifytxoutproof(), VoteWithMasternodes(), waitforblock(), waitforblockheight(), waitfornewblock(), and WalletTxToJSON().
push_back() [2/8]
bool UniValue::push_back (const std::string & val_) inline
Definition at line 88 of file univalue.h.
References push_back(), and VSTR.
push_back() [3/8]
bool UniValue::push_back (const char * val_) inline
Definition at line 92 of file univalue.h.
References push_back().
push_back() [4/8]
bool UniValue::push_back (uint64_t val_) inline
Definition at line 96 of file univalue.h.
References push_back().
push_back() [5/8]
bool UniValue::push_back (int64_t val_) inline
Definition at line 100 of file univalue.h.
References push_back().
push_back() [6/8]
bool UniValue::push_back (int val_) inline
Definition at line 104 of file univalue.h.
References push_back().
push_back() [7/8]
bool UniValue::push_back (double val_) inline
Definition at line 108 of file univalue.h.
References push_back().
push_back() [8/8]
bool UniValue::push_back (std::pair< std::string, UniValue > pear) inline
Definition at line 175 of file univalue.h.
References pushKV().
push_backV()
bool UniValue::push_backV (const std::vector< UniValue > & vec)
Definition at line 119 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and listtransactions().
pushKV() [1/7]
bool UniValue::pushKV (const std::string & key, const UniValue & val)
Definition at line 135 of file univalue.cpp.
Referenced by addmultisigaddress(), BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), getblockstats(), importmulti(), loadwallet(), logging(), ProcessImport(), GetinfoRequestHandler::ProcessReply(), push_back(), pushKV(), rescanblockchain(), RPCConvertNamedValues(), ScriptPubKeyToUniv(), and TxToUniv().
pushKV() [2/7]
bool UniValue::pushKV (const std::string & key, const std::string & val_) inline
Definition at line 116 of file univalue.h.
References pushKV(), and VSTR.
pushKV() [3/7]
bool UniValue::pushKV (const std::string & key, const char * val_) inline
Definition at line 120 of file univalue.h.
References pushKV().
pushKV() [4/7]
bool UniValue::pushKV (const std::string & key, int64_t val_) inline
Definition at line 124 of file univalue.h.
References pushKV().
pushKV() [5/7]
bool UniValue::pushKV (const std::string & key, uint64_t val_) inline
Definition at line 128 of file univalue.h.
References pushKV().
pushKV() [6/7]
bool UniValue::pushKV (const std::string & key, int val_) inline
Definition at line 132 of file univalue.h.
References pushKV().
pushKV() [7/7]
bool UniValue::pushKV (const std::string & key, double val_) inline
Definition at line 136 of file univalue.h.
References pushKV().
pushKVs()
bool UniValue::pushKVs (const UniValue & obj)
Definition at line 148 of file univalue.cpp.
References keys, typ, and values.
Referenced by BOOST_AUTO_TEST_CASE(), and validateaddress().
read() [1/3]
bool UniValue::read (const char * raw, size_t len)
Definition at line 253 of file univalue_read.cpp.
References clearExpect, expect, getJsonToken(), getType(), jsonTokenIsValue(), JTOK_ARR_CLOSE, JTOK_ARR_OPEN, JTOK_COLON, JTOK_COMMA, JTOK_ERR, JTOK_KW_FALSE, JTOK_KW_NULL, JTOK_KW_TRUE, JTOK_NONE, JTOK_NUMBER, JTOK_OBJ_CLOSE, JTOK_OBJ_OPEN, JTOK_STRING, keys, push_back(), setBool(), setExpect, and values.
Referenced by BOOST_AUTO_TEST_CASE(), CallRPC(), CKeePassIntegrator::doHTTPPost(), CGovernanceObject::GetData(), HTTPReq_JSONRPC(), importelectrumwallet(), main(), CProposalValidator::ParseJSONData(), ParseNonRFCJSONValue(), CKeePassIntegrator::CKeePassResponse::parseResponse(), read(), RegisterSetJson(), runtest(), and unescape_unicode_test().
read() [2/3]
bool UniValue::read (const char * raw) inline
Definition at line 146 of file univalue.h.
References read().
Referenced by read().
read() [3/3]
bool UniValue::read (const std::string & rawStr) inline
Definition at line 147 of file univalue.h.
References read().
setArray()
bool UniValue::setArray ()
Definition at line 96 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), importmulti(), listtransactions(), and masternode_list().
setBool()
bool UniValue::setBool (bool val)
Definition at line 31 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), read(), and UniValue().
setFloat()
bool UniValue::setFloat (double val)
Definition at line 77 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and UniValue().
setInt() [1/3]
bool UniValue::setInt (uint64_t val)
Definition at line 59 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and UniValue().
setInt() [2/3]
bool UniValue::setInt (int64_t val)
Definition at line 68 of file univalue.cpp.
setInt() [3/3]
bool UniValue::setInt (int val_) inline
Definition at line 59 of file univalue.h.
References setInt().
Referenced by setInt().
setNull()
bool UniValue::setNull ()
Definition at line 25 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
setNumStr()
bool UniValue::setNumStr (const std::string & val)
Definition at line 48 of file univalue.cpp.
References validNumStr().
Referenced by BOOST_AUTO_TEST_CASE().
setObject()
bool UniValue::setObject ()
Definition at line 103 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), CPrivateSendServer::GetJsonInfo(), CPrivateSendClientSession::GetJsonInfo(), CPrivateSendClientManager::GetJsonInfo(), CCbTx::ToJson(), CProRegTx::ToJson(), CSimplifiedMNListEntry::ToJson(), llmq::CFinalCommitment::ToJson(), CDeterministicMNState::ToJson(), CProUpServTx::ToJson(), llmq::CFinalCommitmentTxPayload::ToJson(), CSimplifiedMNListDiff::ToJson(), CProUpRegTx::ToJson(), CProUpRevTx::ToJson(), and CDeterministicMN::ToJson().
setStr()
bool UniValue::setStr (const std::string & val)
Definition at line 88 of file univalue.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and UniValue().
size()
size_t UniValue::size () const inline
Definition at line 69 of file univalue.h.
References values.
Referenced by abandontransaction(), abortrescan(), addmultisigaddress(), addnode(), backupwallet(), bls_fromsecret(), bls_generate(), BOOST_AUTO_TEST_CASE(), BuildQuorumInfo(), llmq::CSigSharesManager::Cleanup(), clearbanned(), combinerawtransaction(), createmultisig(), createrawtransaction(), debug(), decoderawtransaction(), decodescript(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), estimatefee(), estimaterawfee(), estimatesmartfee(), fundrawtransaction(), getaccount(), getaccountaddress(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getaddressesbyaccount(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getbalance(), getbestblockhash(), getbestchainlock(), getblock(), getblockchaininfo(), getblockcount(), getblockhash(), getblockhashes(), getblockheader(), getblockheaders(), getblockstats(), getblocktemplate(), getCategoryMask(), getchaintips(), getchaintxstats(), getconnectioncount(), getdifficulty(), CKeePassIntegrator::CKeePassResponse::getEntries(), getgovernanceinfo(), getmemoryinfo(), getmempoolancestors(), getmempooldescendants(), getmempoolentry(), getmempoolinfo(), getmerkleblocks(), getmininginfo(), getnettotals(), getnetworkhashps(), getnetworkinfo(), getnewaddress(), getpeerinfo(), getprivatesendinfo(), getrawchangeaddress(), getrawmempool(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), getspecialtxes(), getspentinfo(), getsuperblockbudget(), gettransaction(), gettxout(), gettxoutproof(), gettxoutsetinfo(), getunconfirmedbalance(), getwalletinfo(), gobject_check(), gobject_count(), gobject_deserialize(), gobject_diff(), gobject_get(), gobject_getcurrentvotes(), gobject_list(), gobject_submit(), gobject_vote_conf(), help(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), invalidateblock(), JSONRPCExecBatch(), JSONRPCProcessBatchReply(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listbanned(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), listwallets(), loadwallet(), lockunspent(), logging(), masternode_connect(), masternode_count(), masternode_list(), masternode_winners(), mnsync(), movecmd(), MutateTxSign(), ParseNonRFCJSONValue(), ping(), preciousblock(), prioritisetransaction(), ProcessImport(), llmq::CSigSharesManager::ProcessMessageSigShare(), protx_diff(), protx_info(), protx_list(), pruneblockchain(), quorum_dkgsimerror(), quorum_dkgstatus(), quorum_info(), quorum_list(), quorum_memberof(), quorum_selectquorum(), quorum_sigs_cmd(), reconsiderblock(), removeprunedfunds(), rescanblockchain(), resendwallettransactions(), RPCTypeCheck(), savemempool(), llmq::CSigSharesManager::SelectMemberForRecovery(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), setaccount(), setban(), setmocktime(), setnetworkactive(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), signmessagewithprivkey(), signrawtransaction(), spork(), stop(), submitblock(), uptime(), validateaddress(), verifychain(), verifymessage(), verifytxoutproof(), voteraw(), waitforblock(), waitforblockheight(), waitfornewblock(), walletlock(), walletpassphrase(), and walletpassphrasechange().
type()
enum VType UniValue::type () const inline
Definition at line 174 of file univalue.h.
References getType().
Referenced by fundrawtransaction(), GetImportTimestamp(), llmq::CSigSharesManager::ProcessSigShare(), RPCTypeCheckArgument(), RPCTypeCheckObj(), llmq::CSigSharesManager::Sign(), and llmq::CSigSharesManager::TryRecoverSig().
write()
string UniValue::write (unsigned int prettyIndent = 0, unsigned int indentLevel = 0) const
Definition at line 31 of file univalue_write.cpp.
References json_escape().
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), CallRPC(), MasternodeList::extraInfoDIP3_clicked(), JSONRPCExecBatch(), JSONRPCReply(), main(), OutputTxJSON(), RPCExecutor::request(), rest_block(), rest_chaininfo(), rest_getutxos(), rest_headers(), rest_mempool_contents(), rest_mempool_info(), rest_tx(), RPCConsole::RPCParseCommandLine(), and runtest().
writeArray()
void UniValue::writeArray (unsigned int prettyIndent, unsigned int indentLevel, std::string & s) const private
Definition at line 70 of file univalue_write.cpp.
References indentStr().
writeObject()
void UniValue::writeObject (unsigned int prettyIndent, unsigned int indentLevel, std::string & s) const private
Definition at line 92 of file univalue_write.cpp.
References indentStr(), and json_escape().
Friends And Related Function Documentation
find_value
const UniValue& find_value (const UniValue & obj, const std::string & name) friend
Definition at line 236 of file univalue.cpp.
Member Data Documentation
keys
std::vector<std::string> UniValue::keys private
Definition at line 154 of file univalue.h.
Referenced by find_value(), getKeys(), pushKVs(), and read().
typ
UniValue::VType UniValue::typ private
Definition at line 152 of file univalue.h.
Referenced by get_array(), get_bool(), get_int(), get_int64(), get_obj(), get_real(), get_str(), getKeys(), getType(), getValues(), isArray(), isBool(), isFalse(), isNull(), isNum(), isObject(), isStr(), isTrue(), pushKVs(), and UniValue().
val
std::string UniValue::val private
Definition at line 153 of file univalue.h.
Referenced by getValStr(), isFalse(), isTrue(), and UniValue().
values
std::vector<UniValue> UniValue::values private
Definition at line 155 of file univalue.h.
Referenced by empty(), find_value(), getValues(), pushKVs(), read(), and size().
The documentation for this class was generated from the following files:
src/univalue/include/univalue.h
src/univalue/lib/univalue.cpp
src/univalue/lib/univalue_get.cpp
src/univalue/lib/univalue_read.cpp
src/univalue/lib/univalue_write.cpp
Released under the MIT license