Dash Core: llmq::CDKGDebugManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CDKGDebugManager Class Reference
#include <quorums_debug.h>
Public Member Functions
CDKGDebugManager ()
void GetLocalDebugStatus (CDKGDebugStatus &ret)
void ResetLocalSessionStatus (Consensus::LLMQType llmqType)
void InitLocalSessionStatus (Consensus::LLMQType llmqType, const uint256 &quorumHash, int quorumHeight)
void UpdateLocalSessionStatus (Consensus::LLMQType llmqType, std::function< bool(CDKGDebugSessionStatus &status)> &&func)
void UpdateLocalMemberStatus (Consensus::LLMQType llmqType, size_t memberIdx, std::function< bool(CDKGDebugMemberStatus &status)> &&func)
Private Attributes
CCriticalSection cs
CDKGDebugStatus localStatus
Detailed Description
Definition at line 89 of file quorums_debug.h.
Constructor & Destructor Documentation
CDKGDebugManager()
llmq::CDKGDebugManager::CDKGDebugManager ()
Definition at line 115 of file quorums_debug.cpp.
Member Function Documentation
GetLocalDebugStatus()
void llmq::CDKGDebugManager::GetLocalDebugStatus (llmq::CDKGDebugStatus & ret)
Definition at line 140 of file quorums_debug.cpp.
References cs, localStatus, and LOCK.
Referenced by quorum_dkgstatus().
InitLocalSessionStatus()
void llmq::CDKGDebugManager::InitLocalSessionStatus (Consensus::LLMQType llmqType, const uint256 & quorumHash, int quorumHeight)
Definition at line 159 of file quorums_debug.cpp.
References cs, CChainParams::GetConsensus(), Consensus::Params::llmqs, localStatus, LOCK, Params(), and llmq::CDKGDebugStatus::sessions.
Referenced by llmq::CDKGSession::Init().
ResetLocalSessionStatus()
void llmq::CDKGDebugManager::ResetLocalSessionStatus (Consensus::LLMQType llmqType)
Definition at line 146 of file quorums_debug.cpp.
References cs, GetAdjustedTime(), localStatus, LOCK, llmq::CDKGDebugStatus::nTime, and llmq::CDKGDebugStatus::sessions.
Referenced by llmq::CDKGSessionHandler::WaitForNextPhase().
UpdateLocalMemberStatus()
void llmq::CDKGDebugManager::UpdateLocalMemberStatus (Consensus::LLMQType llmqType, size_t memberIdx, std::function< bool(CDKGDebugMemberStatus &status)> && func)
Definition at line 193 of file quorums_debug.cpp.
References cs, GetAdjustedTime(), localStatus, LOCK, llmq::CDKGDebugStatus::nTime, and llmq::CDKGDebugStatus::sessions.
Referenced by llmq::CDKGSession::MarkBadMember(), llmq::CDKGSession::ReceiveMessage(), and llmq::CDKGSession::VerifyPendingContributions().
UpdateLocalSessionStatus()
void llmq::CDKGDebugManager::UpdateLocalSessionStatus (Consensus::LLMQType llmqType, std::function< bool(CDKGDebugSessionStatus &status)> && func)
Definition at line 179 of file quorums_debug.cpp.
References cs, GetAdjustedTime(), localStatus, LOCK, llmq::CDKGDebugStatus::nTime, and llmq::CDKGDebugStatus::sessions.
Referenced by llmq::CDKGSessionHandler::HandleDKGRound(), llmq::CDKGSessionHandler::PhaseHandlerThread(), llmq::CDKGSession::SendCommitment(), llmq::CDKGSession::SendComplaint(), llmq::CDKGSession::SendContributions(), llmq::CDKGSession::SendJustification(), and llmq::CDKGSessionHandler::WaitForNextPhase().
Member Data Documentation
cs
CCriticalSection llmq::CDKGDebugManager::cs private
Definition at line 92 of file quorums_debug.h.
Referenced by GetLocalDebugStatus(), InitLocalSessionStatus(), ResetLocalSessionStatus(), UpdateLocalMemberStatus(), and UpdateLocalSessionStatus().
localStatus
CDKGDebugStatus llmq::CDKGDebugManager::localStatus private
Definition at line 93 of file quorums_debug.h.
Referenced by GetLocalDebugStatus(), InitLocalSessionStatus(), ResetLocalSessionStatus(), UpdateLocalMemberStatus(), and UpdateLocalSessionStatus().
The documentation for this class was generated from the following files:
src/llmq/quorums_debug.h
src/llmq/quorums_debug.cpp
Released under the MIT license