Dash Core: CProRegTx Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CProRegTx Class Reference
#include <providertx.h>
Public Member Functions
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
std::string MakeSignString () const
std::string ToString () const
void ToJson (UniValue &obj) const
Public Attributes
uint16_t nVersion {CURRENT_VERSION}
uint16_t nType {0}
uint16_t nMode {0}
COutPoint collateralOutpoint {uint256(), (uint32_t)-1}
CService addr
CKeyID keyIDOwner
CBLSPublicKey pubKeyOperator
CKeyID keyIDVoting
uint16_t nOperatorReward {0}
CScript scriptPayout
uint256 inputsHash
std::vector< unsigned char > vchSig
ADD_SERIALIZE_METHODS
Static Public Attributes
static const uint16_t CURRENT_VERSION = 1
Detailed Description
Definition at line 19 of file providertx.h.
Member Function Documentation
MakeSignString()
std::string CProRegTx::MakeSignString () const
Definition at line 398 of file providertx.cpp.
References prevector< N, T, Size, Diff >::begin(), EncodeDestination(), prevector< N, T, Size, Diff >::end(), ExtractDestination(), HexStr(), keyIDOwner, keyIDVoting, nOperatorReward, scriptPayout, SerializeHash(), strprintf, and base_blob< BITS >::ToString().
SerializationOp()
template<typename Stream , typename Operation > void CProRegTx::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 42 of file providertx.h.
References addr, collateralOutpoint, inputsHash, keyIDOwner, keyIDVoting, nMode, nOperatorReward, nType, nVersion, pubKeyOperator, READWRITE, scriptPayout, SER_GETHASH, and vchSig.
ToJson()
void CProRegTx::ToJson (UniValue & obj) const inline
Definition at line 66 of file providertx.h.
References addr, UniValue::clear(), collateralOutpoint, EncodeDestination(), ExtractDestination(), COutPoint::hash, inputsHash, keyIDOwner, keyIDVoting, COutPoint::n, nOperatorReward, nVersion, Pair(), pubKeyOperator, UniValue::push_back(), scriptPayout, UniValue::setObject(), base_blob< BITS >::ToString(), CService::ToString(), and CBLSWrapper< ImplType, _SerSize, C >::ToString().
Referenced by TxToUniv().
ToString()
std::string CProRegTx::ToString () const
Definition at line 423 of file providertx.cpp.
References addr, collateralOutpoint, EncodeDestination(), ExtractDestination(), keyIDOwner, keyIDVoting, nOperatorReward, nVersion, pubKeyOperator, scriptPayout, strprintf, CService::ToString(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), and COutPoint::ToStringShort().
Referenced by CDeterministicMNManager::BuildNewListFromBlock().
Member Data Documentation
ADD_SERIALIZE_METHODS
CProRegTx::ADD_SERIALIZE_METHODS
Definition at line 39 of file providertx.h.
addr
CService CProRegTx::addr
Definition at line 29 of file providertx.h.
Referenced by CTxMemPool::addUnchecked(), CDeterministicMNManager::BuildNewListFromBlock(), CDeterministicMNState::CDeterministicMNState(), CheckProRegTx(), CTxMemPool::existsProviderTxConflict(), CTxMemPool::removeProTxConflicts(), CTxMemPool::removeUnchecked(), SerializationOp(), ToJson(), and ToString().
collateralOutpoint
COutPoint CProRegTx::collateralOutpoint {uint256(), (uint32_t)-1}
Definition at line 28 of file providertx.h.
Referenced by CTxMemPool::addUnchecked(), CDeterministicMNManager::BuildNewListFromBlock(), CheckProRegTx(), CBloomFilter::CheckSpecialTransactionMatchesAndUpdate(), CTxMemPool::existsProviderTxConflict(), CDeterministicMNManager::IsProTxWithCollateral(), CTxMemPool::removeProTxConflicts(), CTxMemPool::removeUnchecked(), SerializationOp(), ToJson(), and ToString().
CURRENT_VERSION
const uint16_t CProRegTx::CURRENT_VERSION = 1 static
Definition at line 22 of file providertx.h.
Referenced by CheckProRegTx().
inputsHash
uint256 CProRegTx::inputsHash
Definition at line 35 of file providertx.h.
Referenced by SerializationOp(), and ToJson().
keyIDOwner
CKeyID CProRegTx::keyIDOwner
Definition at line 30 of file providertx.h.
Referenced by CTxMemPool::addUnchecked(), CDeterministicMNManager::BuildNewListFromBlock(), CDeterministicMNState::CDeterministicMNState(), CheckProRegTx(), CBloomFilter::CheckSpecialTransactionMatchesAndUpdate(), CTxMemPool::existsProviderTxConflict(), MakeSignString(), CTxMemPool::removeProTxConflicts(), CTxMemPool::removeUnchecked(), SerializationOp(), ToJson(), and ToString().
keyIDVoting
CKeyID CProRegTx::keyIDVoting
Definition at line 32 of file providertx.h.
Referenced by CDeterministicMNState::CDeterministicMNState(), CheckProRegTx(), CBloomFilter::CheckSpecialTransactionMatchesAndUpdate(), MakeSignString(), SerializationOp(), ToJson(), and ToString().
nMode
uint16_t CProRegTx::nMode {0}
Definition at line 27 of file providertx.h.
Referenced by CheckProRegTx(), and SerializationOp().
nOperatorReward
uint16_t CProRegTx::nOperatorReward {0}
Definition at line 33 of file providertx.h.
Referenced by CDeterministicMNManager::BuildNewListFromBlock(), CheckProRegTx(), MakeSignString(), SerializationOp(), ToJson(), and ToString().
nType
uint16_t CProRegTx::nType {0}
Definition at line 26 of file providertx.h.
Referenced by CheckProRegTx(), and SerializationOp().
nVersion
uint16_t CProRegTx::nVersion {CURRENT_VERSION}
Definition at line 25 of file providertx.h.
Referenced by CheckProRegTx(), SerializationOp(), ToJson(), and ToString().
pubKeyOperator
CBLSPublicKey CProRegTx::pubKeyOperator
Definition at line 31 of file providertx.h.
Referenced by CTxMemPool::addUnchecked(), CDeterministicMNManager::BuildNewListFromBlock(), CDeterministicMNState::CDeterministicMNState(), CheckProRegTx(), CTxMemPool::existsProviderTxConflict(), CTxMemPool::removeProTxConflicts(), CTxMemPool::removeUnchecked(), SerializationOp(), ToJson(), and ToString().
scriptPayout
CScript CProRegTx::scriptPayout
Definition at line 34 of file providertx.h.
Referenced by CDeterministicMNState::CDeterministicMNState(), CheckProRegTx(), CBloomFilter::CheckSpecialTransactionMatchesAndUpdate(), MakeSignString(), SerializationOp(), ToJson(), and ToString().
vchSig
std::vector<unsigned char> CProRegTx::vchSig
Definition at line 36 of file providertx.h.
Referenced by CheckProRegTx(), and SerializationOp().
The documentation for this class was generated from the following files:
src/evo/providertx.h
src/evo/providertx.cpp
Released under the MIT license