Dash Core: TxViewDelegate Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
TxViewDelegate Class Reference
Public Member Functions
TxViewDelegate (const PlatformStyle *_platformStyle, QObject *parent=nullptr)
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Attributes
int unit
const PlatformStyle * platformStyle
Detailed Description
Definition at line 36 of file overviewpage.cpp.
Constructor & Destructor Documentation
TxViewDelegate()
TxViewDelegate::TxViewDelegate (const PlatformStyle * _platformStyle, QObject * parent = nullptr) inline
Definition at line 40 of file overviewpage.cpp.
Member Function Documentation
paint()
void TxViewDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const inline
Definition at line 47 of file overviewpage.cpp.
References TransactionTableModel::AmountRole, COLOR_NEGATIVE, COLOR_UNCONFIRMED, TransactionTableModel::ConfirmedRole, TransactionTableModel::DateRole, GUIUtil::dateTimeStr(), DECORATION_SIZE, BitcoinUnits::floorWithUnit(), ICON_OFFSET, platformStyle, TransactionTableModel::RawDecorationRole, BitcoinUnits::separatorAlways, PlatformStyle::SingleColorIcon(), unit, TransactionTableModel::WatchonlyDecorationRole, and TransactionTableModel::WatchonlyRole.
sizeHint()
QSize TxViewDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const inline
Definition at line 113 of file overviewpage.cpp.
References DECORATION_SIZE.
Member Data Documentation
platformStyle
const PlatformStyle* TxViewDelegate::platformStyle
Definition at line 119 of file overviewpage.cpp.
Referenced by paint().
unit
int TxViewDelegate::unit
Definition at line 118 of file overviewpage.cpp.
Referenced by paint(), and OverviewPage::updateDisplayUnit().
The documentation for this class was generated from the following file:
src/qt/overviewpage.cpp
Released under the MIT license