Dash Core: CNetFulfilledRequestManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CNetFulfilledRequestManager Class Reference
#include <netfulfilledman.h>
Public Member Functions
CNetFulfilledRequestManager ()
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
void AddFulfilledRequest (const CService &addr, const std::string &strRequest)
bool HasFulfilledRequest (const CService &addr, const std::string &strRequest)
void RemoveAllFulfilledRequests (const CService &addr)
void CheckAndRemove ()
void Clear ()
std::string ToString () const
void DoMaintenance ()
Public Attributes
ADD_SERIALIZE_METHODS
Private Types
typedef std::map< std::string, int64_t > fulfilledreqmapentry_t
typedef std::map< CService, fulfilledreqmapentry_t > fulfilledreqmap_t
Private Member Functions
void RemoveFulfilledRequest (const CService &addr, const std::string &strRequest)
Private Attributes
fulfilledreqmap_t mapFulfilledRequests
CCriticalSection cs_mapFulfilledRequests
Detailed Description
Definition at line 17 of file netfulfilledman.h.
Member Typedef Documentation
fulfilledreqmap_t
typedef std::map<CService, fulfilledreqmapentry_t> CNetFulfilledRequestManager::fulfilledreqmap_t private
Definition at line 21 of file netfulfilledman.h.
fulfilledreqmapentry_t
typedef std::map<std::string, int64_t> CNetFulfilledRequestManager::fulfilledreqmapentry_t private
Definition at line 20 of file netfulfilledman.h.
Constructor & Destructor Documentation
CNetFulfilledRequestManager()
CNetFulfilledRequestManager::CNetFulfilledRequestManager () inline
Definition at line 30 of file netfulfilledman.h.
Member Function Documentation
AddFulfilledRequest()
void CNetFulfilledRequestManager::AddFulfilledRequest (const CService & addr, const std::string & strRequest)
Definition at line 12 of file netfulfilledman.cpp.
References CChainParams::AllowMultiplePorts(), cs_mapFulfilledRequests, CChainParams::FulfilledRequestExpireTime(), GetTime(), LOCK, mapFulfilledRequests, and Params().
Referenced by CMasternodeSync::ProcessTick(), CMasternodeSync::SwitchToNextAsset(), and CGovernanceManager::SyncObjects().
CheckAndRemove()
void CNetFulfilledRequestManager::CheckAndRemove ()
Definition at line 52 of file netfulfilledman.cpp.
References cs_mapFulfilledRequests, GetTime(), LOCK, and mapFulfilledRequests.
Referenced by DoMaintenance().
Clear()
void CNetFulfilledRequestManager::Clear ()
Definition at line 76 of file netfulfilledman.cpp.
References cs_mapFulfilledRequests, LOCK, and mapFulfilledRequests.
DoMaintenance()
void CNetFulfilledRequestManager::DoMaintenance ()
Definition at line 89 of file netfulfilledman.cpp.
References CheckAndRemove(), and ShutdownRequested().
Referenced by AppInitMain().
HasFulfilledRequest()
bool CNetFulfilledRequestManager::HasFulfilledRequest (const CService & addr, const std::string & strRequest)
Definition at line 19 of file netfulfilledman.cpp.
References CChainParams::AllowMultiplePorts(), cs_mapFulfilledRequests, GetTime(), LOCK, mapFulfilledRequests, and Params().
Referenced by CMasternodeSync::ProcessTick(), and CGovernanceManager::SyncObjects().
RemoveAllFulfilledRequests()
void CNetFulfilledRequestManager::RemoveAllFulfilledRequests (const CService & addr)
Definition at line 41 of file netfulfilledman.cpp.
References CChainParams::AllowMultiplePorts(), cs_mapFulfilledRequests, LOCK, mapFulfilledRequests, and Params().
Referenced by CMasternodeSync::ProcessTick().
RemoveFulfilledRequest()
void CNetFulfilledRequestManager::RemoveFulfilledRequest (const CService & addr, const std::string & strRequest) private
Definition at line 30 of file netfulfilledman.cpp.
References CChainParams::AllowMultiplePorts(), cs_mapFulfilledRequests, LOCK, mapFulfilledRequests, and Params().
SerializationOp()
template<typename Stream , typename Operation > void CNetFulfilledRequestManager::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 35 of file netfulfilledman.h.
References cs_mapFulfilledRequests, LOCK, mapFulfilledRequests, and READWRITE.
ToString()
std::string CNetFulfilledRequestManager::ToString () const
Definition at line 82 of file netfulfilledman.cpp.
References mapFulfilledRequests.
Member Data Documentation
ADD_SERIALIZE_METHODS
CNetFulfilledRequestManager::ADD_SERIALIZE_METHODS
Definition at line 32 of file netfulfilledman.h.
cs_mapFulfilledRequests
CCriticalSection CNetFulfilledRequestManager::cs_mapFulfilledRequests private
Definition at line 25 of file netfulfilledman.h.
Referenced by AddFulfilledRequest(), CheckAndRemove(), Clear(), HasFulfilledRequest(), RemoveAllFulfilledRequests(), RemoveFulfilledRequest(), and SerializationOp().
mapFulfilledRequests
fulfilledreqmap_t CNetFulfilledRequestManager::mapFulfilledRequests private
Definition at line 24 of file netfulfilledman.h.
Referenced by AddFulfilledRequest(), CheckAndRemove(), Clear(), HasFulfilledRequest(), RemoveAllFulfilledRequests(), RemoveFulfilledRequest(), SerializationOp(), and ToString().
The documentation for this class was generated from the following files:
src/netfulfilledman.h
src/netfulfilledman.cpp
Released under the MIT license