Dash Core: CService Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CService Class Reference
A combination of a network address (CNetAddr) and a (TCP) port.
#include <netaddress.h>
Public Member Functions
CService ()
CService (const CNetAddr &ip, unsigned short port)
CService (const struct in_addr &ipv4Addr, unsigned short port)
CService (const struct sockaddr_in &addr)
void Init ()
void SetPort (unsigned short portIn)
unsigned short GetPort () const
bool GetSockAddr (struct sockaddr *paddr, socklen_t *addrlen) const
bool SetSockAddr (const struct sockaddr *paddr)
std::vector< unsigned char > GetKey () const
std::string ToString (bool fUseGetnameinfo=true) const
std::string ToStringPort () const
std::string ToStringIPPort (bool fUseGetnameinfo=true) const
CService (const struct in6_addr &ipv6Addr, unsigned short port)
CService (const struct sockaddr_in6 &addr)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
Public Member Functions inherited from CNetAddr
CNetAddr ()
CNetAddr (const struct in_addr &ipv4Addr)
void Init ()
void SetIP (const CNetAddr &ip)
void SetRaw (Network network, const uint8_t *data)
Set raw IPv4 or IPv6 address (in network byte order)
bool SetSpecial (const std::string &strName)
bool IsIPv4 () const
bool IsIPv6 () const
bool IsRFC1918 () const
bool IsRFC2544 () const
bool IsRFC6598 () const
bool IsRFC5737 () const
bool IsRFC3849 () const
bool IsRFC3927 () const
bool IsRFC3964 () const
bool IsRFC4193 () const
bool IsRFC4380 () const
bool IsRFC4843 () const
bool IsRFC4862 () const
bool IsRFC6052 () const
bool IsRFC6145 () const
bool IsTor () const
bool IsLocal () const
bool IsRoutable () const
bool IsValid () const
bool IsMulticast () const
enum Network GetNetwork () const
std::string ToString () const
std::string ToStringIP (bool fUseGetnameinfo=true) const
unsigned int GetByte (int n) const
uint64_t GetHash () const
bool GetInAddr (struct in_addr *pipv4Addr) const
std::vector< unsigned char > GetGroup () const
int GetReachabilityFrom (const CNetAddr *paddrPartner=NULL) const
Calculates a metric for how reachable (*this) is from a given partner.
CNetAddr (const struct in6_addr &pipv6Addr)
bool GetIn6Addr (struct in6_addr *pipv6Addr) const
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
Public Attributes
ADD_SERIALIZE_METHODS
Public Attributes inherited from CNetAddr
ADD_SERIALIZE_METHODS
Protected Attributes
unsigned short port
Protected Attributes inherited from CNetAddr
unsigned char ip [16]
Friends
bool operator== (const CService &a, const CService &b)
bool operator!= (const CService &a, const CService &b)
bool operator< (const CService &a, const CService &b)
Detailed Description
A combination of a network address (CNetAddr) and a (TCP) port.
Definition at line 132 of file netaddress.h.
Constructor & Destructor Documentation
CService() [1/6]
CService::CService ()
Definition at line 454 of file netaddress.cpp.
References Init().
Referenced by SetSockAddr().
CService() [2/6]
CService::CService (const CNetAddr & ip, unsigned short port)
Definition at line 459 of file netaddress.cpp.
CService() [3/6]
CService::CService (const struct in_addr & ipv4Addr, unsigned short port)
Definition at line 463 of file netaddress.cpp.
CService() [4/6]
CService::CService (const struct sockaddr_in & addr)
Definition at line 471 of file netaddress.cpp.
CService() [5/6]
CService::CService (const struct in6_addr & ipv6Addr, unsigned short port)
Definition at line 467 of file netaddress.cpp.
CService() [6/6]
CService::CService (const struct sockaddr_in6 & addr)
Definition at line 476 of file netaddress.cpp.
Member Function Documentation
GetKey()
std::vector< unsigned char > CService::GetKey () const
Definition at line 544 of file netaddress.cpp.
References CNetAddr::ip, memcpy(), and port.
Referenced by CNode::AddAddressKnown(), CAddrInfo::GetBucketPosition(), CAddrInfo::GetTriedBucket(), CNode::PushAddress(), and SendMessages().
GetPort()
unsigned short CService::GetPort () const
Definition at line 495 of file netaddress.cpp.
References port.
Referenced by AddLocal(), AppInit2(), ConnectSocket(), OptionsModel::getProxySettings(), CActiveMasternode::ManageStateInitial(), CMasternodeBroadcast::SimpleCheck(), and CConnman::ThreadOpenConnections().
GetSockAddr()
bool CService::GetSockAddr (struct sockaddr * paddr, socklen_t * addrlen) const
Definition at line 515 of file netaddress.cpp.
References CNetAddr::GetIn6Addr(), CNetAddr::GetInAddr(), CNetAddr::IsIPv4(), CNetAddr::IsIPv6(), and port.
Referenced by CConnman::BindListenPort(), ConnectSocketDirectly(), and CNetAddr::ToStringIP().
Init()
void CService::Init ()
Definition at line 449 of file netaddress.cpp.
References port.
Referenced by CService().
SerializationOp()
template<typename Stream , typename Operation > void CService::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 161 of file netaddress.h.
References FLATDATA, CNetAddr::ip, port, and READWRITE.
SetPort()
void CService::SetPort (unsigned short portIn)
Definition at line 573 of file netaddress.cpp.
References port.
SetSockAddr()
bool CService::SetSockAddr (const struct sockaddr * paddr)
Definition at line 481 of file netaddress.cpp.
References CService().
Referenced by CConnman::AcceptConnection().
ToString()
std::string CService::ToString (bool fUseGetnameinfo = true) const
Definition at line 568 of file netaddress.cpp.
References ToStringIPPort().
Referenced by CConnman::AcceptConnection(), CMasternodeMan::Add(), TorController::add_onion_cb(), AddLocal(), AdvertiseLocal(), CMasternodeMan::AskForMN(), CConnman::BindListenPort(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckOutpoint(), CMasternodeBroadcast::CheckSignature(), CConnman::ConnectNode(), ConnectSocketDirectly(), CNode::copyStats(), CMasternodeMan::DsegUpdate(), getpoolinfo(), CAddrMan::Good_(), HTTPReq_JSONRPC(), CActiveMasternode::ManageStateInitial(), masternode(), masternodebroadcast(), masternodelist(), CMasternodeMan::ProcessMasternodeConnections(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessMessage(), CMasternodeMan::ProcessVerifyBroadcast(), CMasternodeMan::ProcessVerifyReply(), RemoveLocal(), SendMessages(), CMasternodeMan::SendVerifyReply(), CMasternodeMan::SendVerifyRequest(), CMasternodeBroadcast::Sign(), CMasternodeBroadcast::SimpleCheck(), CPrivateSendClient::StartNewQueue(), CConnman::ThreadOpenConnections(), ThreadSendAlert(), CConnman::ThreadSocketHandler(), CMasternodeBroadcast::Update(), CMasternodeMan::UpdateMasternodeList(), MasternodeList::updateMyMasternodeInfo(), and MasternodeList::updateNodeList().
ToStringIPPort()
std::string CService::ToStringIPPort (bool fUseGetnameinfo = true) const
Definition at line 559 of file netaddress.cpp.
References CNetAddr::IsIPv4(), CNetAddr::IsTor(), CNetAddr::ToStringIP(), and ToStringPort().
Referenced by CAddrMan::Add(), CNode::CNode(), getinfo(), GetNetworksInfo(), and ToString().
ToStringPort()
std::string CService::ToStringPort () const
Definition at line 554 of file netaddress.cpp.
References port, and strprintf.
Referenced by ToStringIPPort(), and OptionsDialog::updateDefaultProxyNets().
Friends And Related Function Documentation
operator!=
bool operator!= (const CService & a, const CService & b) friend
Definition at line 505 of file netaddress.cpp.
operator<
bool operator< (const CService & a, const CService & b) friend
Definition at line 510 of file netaddress.cpp.
operator==
bool operator== (const CService & a, const CService & b) friend
Definition at line 500 of file netaddress.cpp.
Member Data Documentation
ADD_SERIALIZE_METHODS
CService::ADD_SERIALIZE_METHODS
Definition at line 158 of file netaddress.h.
port
unsigned short CService::port protected
Definition at line 135 of file netaddress.h.
Referenced by GetKey(), GetPort(), GetSockAddr(), Init(), operator!=(), operator<(), operator==(), SerializationOp(), SetPort(), and ToStringPort().
The documentation for this class was generated from the following files:
src/netaddress.h
src/netaddress.cpp
Released under the MIT license