Dash Core: PaymentRequestPlus Class Reference
PaymentRequestPlus Class Reference
#include <paymentrequestplus.h>
Public Member Functions
PaymentRequestPlus ()
bool parse (const QByteArray &data)
bool SerializeToString (std::string *output) const
bool IsInitialized () const
bool getMerchant (X509_STORE *certStore, QString &merchant) const
QList< std::pair< CScript, CAmount > > getPayTo () const
const payments::PaymentDetails & getDetails () const
Private Attributes
payments::PaymentRequest paymentRequest
payments::PaymentDetails details
Detailed Description
Definition at line 25 of file paymentrequestplus.h.
Constructor & Destructor Documentation
PaymentRequestPlus()
PaymentRequestPlus::PaymentRequestPlus () inline
Definition at line 28 of file paymentrequestplus.h.
Member Function Documentation
getDetails()
const payments::PaymentDetails& PaymentRequestPlus::getDetails () const inline
Definition at line 41 of file paymentrequestplus.h.
Referenced by PaymentServer::fetchPaymentACK(), PaymentServer::ipcParseCommandLine(), WalletModel::prepareTransaction(), PaymentServer::processPaymentRequest(), WalletModelTransaction::reassignAmounts(), and WalletModel::sendCoins().
getMerchant()
bool PaymentRequestPlus::getMerchant (X509_STORE * certStore, QString & merchant) const
Definition at line 60 of file paymentrequestplus.cpp.
Referenced by PaymentServer::processPaymentRequest(), and TransactionDesc::toHTML().
getPayTo()
QList< std::pair< CScript, CAmount > > PaymentRequestPlus::getPayTo () const
Definition at line 209 of file paymentrequestplus.cpp.
Referenced by PaymentServer::processPaymentRequest().
IsInitialized()
bool PaymentRequestPlus::IsInitialized () const
Definition at line 55 of file paymentrequestplus.cpp.
Referenced by getMerchant(), SendCoinsEntry::getValue(), WalletModel::prepareTransaction(), PaymentServer::processPaymentRequest(), WalletModelTransaction::reassignAmounts(), SendCoinsDialog::send(), WalletModel::sendCoins(), SendCoinsRecipient::SerializationOp(), SendCoinsEntry::setValue(), and SendCoinsEntry::validate().
parse()
bool PaymentRequestPlus::parse (const QByteArray & data)
Definition at line 28 of file paymentrequestplus.cpp.
Referenced by PaymentServer::netRequestFinished(), PaymentServer::readPaymentRequestFromFile(), SendCoinsRecipient::SerializationOp(), and TransactionDesc::toHTML().
SerializeToString()
bool PaymentRequestPlus::SerializeToString (std::string * output) const
Definition at line 50 of file paymentrequestplus.cpp.
Referenced by WalletModel::sendCoins(), and SendCoinsRecipient::SerializationOp().
Member Data Documentation
details
payments::PaymentDetails PaymentRequestPlus::details private
Definition at line 45 of file paymentrequestplus.h.
Referenced by getDetails(), getPayTo(), and parse().
paymentRequest
payments::PaymentRequest PaymentRequestPlus::paymentRequest private
Definition at line 44 of file paymentrequestplus.h.
Referenced by getMerchant(), IsInitialized(), parse(), and SerializeToString().
The documentation for this class was generated from the following files:
src/qt/paymentrequestplus.h
src/qt/paymentrequestplus.cpp