Dash Core: CBLSIESEncryptedObject< Object > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSIESEncryptedObject< Object > Class Template Reference
#include <bls_ies.h>
Public Member Functions
CBLSIESEncryptedObject ()
bool Encrypt (const CBLSPublicKey &peerPubKey, const Object &obj, int nVersion)
bool Decrypt (const CBLSSecretKey &secretKey, Object &objRet, int nVersion) const
Public Member Functions inherited from CBLSIESEncryptedBlob
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
bool Encrypt (const CBLSPublicKey &peerPubKey, const void *data, size_t dataSize)
bool Decrypt (const CBLSSecretKey &secretKey, CDataStream &decryptedDataRet) const
Additional Inherited Members
Public Attributes inherited from CBLSIESEncryptedBlob
CBLSPublicKey ephemeralPubKey
unsigned char iv [16]
std::vector< unsigned char > data
bool valid {false}
Detailed Description
template<typename Object>
class CBLSIESEncryptedObject< Object >
Definition at line 45 of file bls_ies.h.
Constructor & Destructor Documentation
CBLSIESEncryptedObject()
template<typename Object > CBLSIESEncryptedObject< Object >::CBLSIESEncryptedObject () inline
Definition at line 48 of file bls_ies.h.
Member Function Documentation
Decrypt()
template<typename Object > bool CBLSIESEncryptedObject< Object >::Decrypt (const CBLSSecretKey & secretKey, Object & objRet, int nVersion) const inline
Definition at line 63 of file bls_ies.h.
References CBLSIESEncryptedBlob::Decrypt(), and SER_NETWORK.
Encrypt()
template<typename Object > bool CBLSIESEncryptedObject< Object >::Encrypt (const CBLSPublicKey & peerPubKey, const Object & obj, int nVersion) inline
Definition at line 52 of file bls_ies.h.
References CDataStream::data(), CBLSIESEncryptedBlob::Encrypt(), SER_NETWORK, and CDataStream::size().
The documentation for this class was generated from the following file:
src/bls/bls_ies.h
Released under the MIT license