Dash Core: CDBTransaction< Parent, CommitTarget > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CDBTransaction< Parent, CommitTarget > Class Template Reference
#include <dbwrapper.h>
Classes
struct DataStreamCmp
struct ValueHolder
struct ValueHolderImpl
Public Member Functions
CDBTransaction (Parent &_parent, CommitTarget &_commitTarget)
template<typename K , typename V >
void Write (const K &key, const V &v)
template<typename V >
void Write (const CDataStream &ssKey, const V &v)
template<typename K , typename V >
bool Read (const K &key, V &value)
template<typename V >
bool Read (const CDataStream &ssKey, V &value)
template<typename K >
bool Exists (const K &key)
bool Exists (const CDataStream &ssKey)
template<typename K >
void Erase (const K &key)
void Erase (const CDataStream &ssKey)
void Clear ()
void Commit ()
bool IsClean ()
size_t GetMemoryUsage () const
CDBTransactionIterator< CDBTransaction > * NewIterator ()
std::unique_ptr< CDBTransactionIterator< CDBTransaction > > NewIteratorUniquePtr ()
Protected Types
typedef std::unique_ptr< ValueHolder > ValueHolderPtr
typedef std::map< CDataStream, ValueHolderPtr, DataStreamCmp > WritesMap
typedef std::set< CDataStream, DataStreamCmp > DeletesSet
Static Protected Member Functions
template<typename K >
static CDataStream KeyToDataStream (const K &key)
Protected Attributes
Parent & parent
CommitTarget & commitTarget
ssize_t memoryUsage {0}
WritesMap writes
DeletesSet deletes
Friends
class CDBTransactionIterator< CDBTransaction >
Detailed Description
template<typename Parent, typename CommitTarget>
class CDBTransaction< Parent, CommitTarget >
Definition at line 552 of file dbwrapper.h.
Member Typedef Documentation
DeletesSet
template<typename Parent, typename CommitTarget> typedef std::set<CDataStream, DataStreamCmp> CDBTransaction< Parent, CommitTarget >::DeletesSet protected
Definition at line 600 of file dbwrapper.h.
ValueHolderPtr
template<typename Parent, typename CommitTarget> typedef std::unique_ptr<ValueHolder> CDBTransaction< Parent, CommitTarget >::ValueHolderPtr protected
Definition at line 577 of file dbwrapper.h.
WritesMap
template<typename Parent, typename CommitTarget> typedef std::map<CDataStream, ValueHolderPtr, DataStreamCmp> CDBTransaction< Parent, CommitTarget >::WritesMap protected
Definition at line 599 of file dbwrapper.h.
Constructor & Destructor Documentation
CDBTransaction()
template<typename Parent, typename CommitTarget> CDBTransaction< Parent, CommitTarget >::CDBTransaction (Parent & _parent, CommitTarget & _commitTarget) inline
Definition at line 606 of file dbwrapper.h.
Member Function Documentation
Clear()
template<typename Parent, typename CommitTarget> void CDBTransaction< Parent, CommitTarget >::Clear () inline
Definition at line 686 of file dbwrapper.h.
Referenced by CDBTransaction< RootTransaction, RootTransaction >::Commit(), and CEvoDB::RollbackCurTransaction().
Commit()
template<typename Parent, typename CommitTarget> void CDBTransaction< Parent, CommitTarget >::Commit () inline
Definition at line 692 of file dbwrapper.h.
Referenced by CEvoDB::CommitCurTransaction(), and CEvoDB::CommitRootTransaction().
Erase() [1/2]
template<typename Parent, typename CommitTarget> template<typename K > void CDBTransaction< Parent, CommitTarget >::Erase (const K & key) inline
Definition at line 671 of file dbwrapper.h.
Referenced by CEvoDB::Erase(), and CDBTransaction< RootTransaction, RootTransaction >::Erase().
Erase() [2/2]
template<typename Parent, typename CommitTarget> void CDBTransaction< Parent, CommitTarget >::Erase (const CDataStream & ssKey) inline
Definition at line 675 of file dbwrapper.h.
Exists() [1/2]
template<typename Parent, typename CommitTarget> template<typename K > bool CDBTransaction< Parent, CommitTarget >::Exists (const K & key) inline
Definition at line 654 of file dbwrapper.h.
Referenced by CEvoDB::Exists(), and CDBTransaction< RootTransaction, RootTransaction >::Exists().
Exists() [2/2]
template<typename Parent, typename CommitTarget> bool CDBTransaction< Parent, CommitTarget >::Exists (const CDataStream & ssKey) inline
Definition at line 658 of file dbwrapper.h.
GetMemoryUsage()
template<typename Parent, typename CommitTarget> size_t CDBTransaction< Parent, CommitTarget >::GetMemoryUsage () const inline
Definition at line 706 of file dbwrapper.h.
Referenced by CEvoDB::GetMemoryUsage().
IsClean()
template<typename Parent, typename CommitTarget> bool CDBTransaction< Parent, CommitTarget >::IsClean () inline
Definition at line 702 of file dbwrapper.h.
Referenced by CEvoDB::CommitRootTransaction().
KeyToDataStream()
template<typename Parent, typename CommitTarget> template<typename K > static CDataStream CDBTransaction< Parent, CommitTarget >::KeyToDataStream (const K & key) inline static protected
Definition at line 592 of file dbwrapper.h.
Referenced by CDBTransaction< RootTransaction, RootTransaction >::Erase(), CDBTransaction< RootTransaction, RootTransaction >::Exists(), CDBTransaction< RootTransaction, RootTransaction >::Read(), CDBTransactionIterator< CDBTransaction >::Seek(), and CDBTransaction< RootTransaction, RootTransaction >::Write().
NewIterator()
template<typename Parent, typename CommitTarget> CDBTransactionIterator<CDBTransaction>* CDBTransaction< Parent, CommitTarget >::NewIterator () inline
Definition at line 719 of file dbwrapper.h.
NewIteratorUniquePtr()
template<typename Parent, typename CommitTarget> std::unique_ptr<CDBTransactionIterator<CDBTransaction> > CDBTransaction< Parent, CommitTarget >::NewIteratorUniquePtr () inline
Definition at line 722 of file dbwrapper.h.
Referenced by llmq::CQuorumBlockProcessor::GetMinedCommitmentsUntilBlock().
Read() [1/2]
template<typename Parent, typename CommitTarget> template<typename K , typename V > bool CDBTransaction< Parent, CommitTarget >::Read (const K & key, V & value) inline
Definition at line 630 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::GetValue(), CEvoDB::Read(), and CDBTransaction< RootTransaction, RootTransaction >::Read().
Read() [2/2]
template<typename Parent, typename CommitTarget> template<typename V > bool CDBTransaction< Parent, CommitTarget >::Read (const CDataStream & ssKey, V & value) inline
Definition at line 635 of file dbwrapper.h.
Write() [1/2]
template<typename Parent, typename CommitTarget> template<typename K , typename V > void CDBTransaction< Parent, CommitTarget >::Write (const K & key, const V & v) inline
Definition at line 609 of file dbwrapper.h.
Referenced by CEvoDB::Write(), and CDBTransaction< RootTransaction, RootTransaction >::Write().
Write() [2/2]
template<typename Parent, typename CommitTarget> template<typename V > void CDBTransaction< Parent, CommitTarget >::Write (const CDataStream & ssKey, const V & v) inline
Definition at line 614 of file dbwrapper.h.
Friends And Related Function Documentation
CDBTransactionIterator< CDBTransaction >
template<typename Parent, typename CommitTarget> friend class CDBTransactionIterator< CDBTransaction > friend
Definition at line 553 of file dbwrapper.h.
Member Data Documentation
commitTarget
template<typename Parent, typename CommitTarget> CommitTarget& CDBTransaction< Parent, CommitTarget >::commitTarget protected
Definition at line 557 of file dbwrapper.h.
Referenced by CDBTransaction< RootTransaction, RootTransaction >::Commit(), and CDBTransaction< Parent, CommitTarget >::ValueHolderImpl< V >::Write().
deletes
template<typename Parent, typename CommitTarget> DeletesSet CDBTransaction< Parent, CommitTarget >::deletes protected
Definition at line 603 of file dbwrapper.h.
Referenced by CDBTransaction< RootTransaction, RootTransaction >::Clear(), CDBTransaction< RootTransaction, RootTransaction >::Commit(), CDBTransaction< RootTransaction, RootTransaction >::Erase(), CDBTransaction< RootTransaction, RootTransaction >::Exists(), CDBTransaction< RootTransaction, RootTransaction >::IsClean(), CDBTransaction< RootTransaction, RootTransaction >::Read(), CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten(), and CDBTransaction< RootTransaction, RootTransaction >::Write().
memoryUsage
template<typename Parent, typename CommitTarget> ssize_t CDBTransaction< Parent, CommitTarget >::memoryUsage {0} protected
Definition at line 558 of file dbwrapper.h.
Referenced by CDBTransaction< RootTransaction, RootTransaction >::Clear(), CDBTransaction< RootTransaction, RootTransaction >::Erase(), CDBTransaction< RootTransaction, RootTransaction >::GetMemoryUsage(), and CDBTransaction< RootTransaction, RootTransaction >::Write().
parent
template<typename Parent, typename CommitTarget> Parent& CDBTransaction< Parent, CommitTarget >::parent protected
Definition at line 556 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::CDBTransactionIterator(), CDBTransaction< RootTransaction, RootTransaction >::Exists(), and CDBTransaction< RootTransaction, RootTransaction >::Read().
writes
template<typename Parent, typename CommitTarget> WritesMap CDBTransaction< Parent, CommitTarget >::writes protected
Definition at line 602 of file dbwrapper.h.
Referenced by CDBTransactionIterator< CDBTransaction >::CDBTransactionIterator(), CDBTransaction< RootTransaction, RootTransaction >::Clear(), CDBTransaction< RootTransaction, RootTransaction >::Commit(), CDBTransactionIterator< CDBTransaction >::DecideCur(), CDBTransaction< RootTransaction, RootTransaction >::Erase(), CDBTransaction< RootTransaction, RootTransaction >::Exists(), CDBTransaction< RootTransaction, RootTransaction >::IsClean(), CDBTransactionIterator< CDBTransaction >::Next(), CDBTransaction< RootTransaction, RootTransaction >::Read(), CDBTransactionIterator< CDBTransaction >::Seek(), CDBTransactionIterator< CDBTransaction >::SeekToFirst(), CDBTransactionIterator< CDBTransaction >::SkipDeletedAndOverwritten(), CDBTransactionIterator< CDBTransaction >::Valid(), and CDBTransaction< RootTransaction, RootTransaction >::Write().
The documentation for this class was generated from the following file:
src/dbwrapper.h
Released under the MIT license