Dash Core: CBitcoinExtKeyBase< K, Size, Type > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBitcoinExtKeyBase< K, Size, Type > Class Template Reference
#include <base58.h>
Public Member Functions
void SetKey (const K &key)
K GetKey ()
CBitcoinExtKeyBase (const K &key)
CBitcoinExtKeyBase (const std::string &strBase58c)
CBitcoinExtKeyBase ()
Public Member Functions inherited from CBase58Data
bool SetString (const char *psz, unsigned int nVersionBytes=1)
bool SetString (const std::string &str)
std::string ToString () const
int CompareTo (const CBase58Data &b58) const
bool operator== (const CBase58Data &b58) const
bool operator<= (const CBase58Data &b58) const
bool operator>= (const CBase58Data &b58) const
bool operator< (const CBase58Data &b58) const
bool operator> (const CBase58Data &b58) const
Additional Inherited Members
Protected Types inherited from CBase58Data
typedef std::vector< unsigned char, zero_after_free_allocator< unsigned char > > vector_uchar
the actually encoded data
Protected Member Functions inherited from CBase58Data
CBase58Data ()
void SetData (const std::vector< unsigned char > &vchVersionIn, const void *pdata, size_t nSize)
void SetData (const std::vector< unsigned char > &vchVersionIn, const unsigned char *pbegin, const unsigned char *pend)
Protected Attributes inherited from CBase58Data
std::vector< unsigned char > vchVersion
the version byte(s)
vector_uchar vchData
Detailed Description
template<typename K, int Size, CChainParams::Base58Type Type>
class CBitcoinExtKeyBase< K, Size, Type >
Definition at line 114 of file base58.h.
Constructor & Destructor Documentation
CBitcoinExtKeyBase() [1/3]
template<typename K , int Size, CChainParams::Base58Type Type> CBitcoinExtKeyBase< K, Size, Type >::CBitcoinExtKeyBase (const K & key) inline
Definition at line 132 of file base58.h.
References CBitcoinExtKeyBase< K, Size, Type >::SetKey().
CBitcoinExtKeyBase() [2/3]
template<typename K , int Size, CChainParams::Base58Type Type> CBitcoinExtKeyBase< K, Size, Type >::CBitcoinExtKeyBase (const std::string & strBase58c) inline
Definition at line 136 of file base58.h.
References CChainParams::Base58Prefix(), Params(), and CBase58Data::SetString().
CBitcoinExtKeyBase() [3/3]
template<typename K , int Size, CChainParams::Base58Type Type> CBitcoinExtKeyBase< K, Size, Type >::CBitcoinExtKeyBase () inline
Definition at line 140 of file base58.h.
Member Function Documentation
GetKey()
template<typename K , int Size, CChainParams::Base58Type Type> K CBitcoinExtKeyBase< K, Size, Type >::GetKey () inline
Definition at line 123 of file base58.h.
References CBase58Data::vchData.
SetKey()
template<typename K , int Size, CChainParams::Base58Type Type> void CBitcoinExtKeyBase< K, Size, Type >::SetKey (const K & key) inline
Definition at line 117 of file base58.h.
References Params(), and CBase58Data::SetData().
Referenced by CBitcoinExtKeyBase< K, Size, Type >::CBitcoinExtKeyBase(), CHDChain::Debug(), and dumpwallet().
The documentation for this class was generated from the following file:
src/base58.h
Released under the MIT license