Dash Core: CSizeComputer Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CSizeComputer Class Reference
#include <serialize.h>
Public Member Functions
CSizeComputer (int nTypeIn, int nVersionIn)
void write (const char *psz, size_t _nSize)
void seek (size_t _nSize)
Pretend _nSize bytes are written, without specifying them.
template<typename T >
CSizeComputer & operator<< (const T &obj)
size_t size () const
int GetVersion () const
int GetType () const
Protected Attributes
size_t nSize
const int nType
const int nVersion
Detailed Description
Definition at line 1199 of file serialize.h.
Constructor & Destructor Documentation
CSizeComputer()
CSizeComputer::CSizeComputer (int nTypeIn, int nVersionIn) inline
Definition at line 1207 of file serialize.h.
Member Function Documentation
GetType()
int CSizeComputer::GetType () const inline
Definition at line 1232 of file serialize.h.
References nType.
GetVersion()
int CSizeComputer::GetVersion () const inline
Definition at line 1231 of file serialize.h.
References nVersion.
operator<<()
template<typename T > CSizeComputer& CSizeComputer::operator<< (const T & obj) inline
Definition at line 1221 of file serialize.h.
References Serialize().
seek()
void CSizeComputer::seek (size_t _nSize) inline
Pretend _nSize bytes are written, without specifying them.
Definition at line 1215 of file serialize.h.
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::Serialize(), CExtPubKey::Serialize(), CBLSLazyWrapper< CBLSSignature >::Serialize(), WriteCompactSize(), and WriteVarInt().
size()
size_t CSizeComputer::size () const inline
Definition at line 1227 of file serialize.h.
References nSize.
write()
void CSizeComputer::write (const char * psz, size_t _nSize) inline
Definition at line 1209 of file serialize.h.
Member Data Documentation
nSize
size_t CSizeComputer::nSize protected
Definition at line 1202 of file serialize.h.
Referenced by GetSizeOfCompactSize(), size(), and WriteCompactSize().
nType
const int CSizeComputer::nType protected
Definition at line 1204 of file serialize.h.
Referenced by GetType().
nVersion
const int CSizeComputer::nVersion protected
Definition at line 1205 of file serialize.h.
Referenced by GetVersion().
The documentation for this class was generated from the following file:
src/serialize.h
Released under the MIT license