Dash Core: walletbackup.WalletBackupTest Class Reference
walletbackup.WalletBackupTest Class Reference
Public Member Functions
def setup_chain (self)
def setup_network (self, split=False)
def one_send (self, from_node, to_address)
def do_one_round (self)
def start_three (self)
def stop_three (self)
def erase_three (self)
def run_test (self)
Test restoring spender wallets from backups.
Public Member Functions inherited from test_framework.test_framework.BitcoinTestFramework
def run_test (self)
def add_options (self, parser)
def setup_chain (self)
def setup_nodes (self)
def setup_network (self, split=False)
def split_network (self)
def sync_all (self)
def join_network (self)
def main (self)
Public Attributes
nodes
is_network_split
Public Attributes inherited from test_framework.test_framework.BitcoinTestFramework
nodes
is_network_split
Detailed Description
Definition at line 42 of file walletbackup.py.
Member Function Documentation
do_one_round()
def walletbackup.WalletBackupTest.do_one_round (self)
Definition at line 65 of file walletbackup.py.
Referenced by walletbackup.WalletBackupTest.run_test().
erase_three()
def walletbackup.WalletBackupTest.erase_three (self)
Definition at line 97 of file walletbackup.py.
Referenced by walletbackup.WalletBackupTest.run_test().
one_send()
def walletbackup.WalletBackupTest.one_send (self, from_node, to_address)
Definition at line 60 of file walletbackup.py.
Referenced by walletbackup.WalletBackupTest.do_one_round().
run_test()
def walletbackup.WalletBackupTest.run_test (self)
Test restoring spender wallets from backups.
Definition at line 102 of file walletbackup.py.
setup_chain()
def walletbackup.WalletBackupTest.setup_chain (self)
Definition at line 44 of file walletbackup.py.
setup_network()
def walletbackup.WalletBackupTest.setup_network (self, split = False)
Definition at line 49 of file walletbackup.py.
start_three()
def walletbackup.WalletBackupTest.start_three (self)
Definition at line 83 of file walletbackup.py.
Referenced by walletbackup.WalletBackupTest.run_test().
stop_three()
def walletbackup.WalletBackupTest.stop_three (self)
Definition at line 92 of file walletbackup.py.
Referenced by walletbackup.WalletBackupTest.run_test().
Member Data Documentation
is_network_split
walletbackup.WalletBackupTest.is_network_split
Definition at line 57 of file walletbackup.py.
nodes
walletbackup.WalletBackupTest.nodes
Definition at line 52 of file walletbackup.py.
The documentation for this class was generated from the following file:
qa/rpc-tests/walletbackup.py