Dash Core: WalletInitInterface Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
WalletInitInterface Class Reference abstract
#include <walletinitinterface.h>
Public Member Functions
virtual std::string GetHelpString (bool showDebug)=0
Get wallet help string.
virtual bool ParameterInteraction ()=0
Check wallet parameter interaction.
virtual void RegisterRPC (CRPCTable &)=0
Register wallet RPC.
virtual bool Verify ()=0
Verify wallets.
virtual bool Open ()=0
Open wallets.
virtual void Start (CScheduler &scheduler)=0
Start wallets.
virtual void Flush ()=0
Flush Wallets.
virtual void Stop ()=0
Stop Wallets.
virtual void Close ()=0
Close wallets.
virtual void AutoLockMasternodeCollaterals ()=0
virtual void InitPrivateSendSettings ()=0
virtual void InitKeePass ()=0
virtual bool InitAutoBackup ()=0
virtual ~WalletInitInterface ()
Detailed Description
Definition at line 13 of file walletinitinterface.h.
Constructor & Destructor Documentation
~WalletInitInterface()
virtual WalletInitInterface::~WalletInitInterface () inline virtual
Definition at line 40 of file walletinitinterface.h.
Member Function Documentation
AutoLockMasternodeCollaterals()
virtual void WalletInitInterface::AutoLockMasternodeCollaterals () pure virtual
Implemented in DummyWalletInit, and WalletInit.
Referenced by ThreadImport().
Close()
virtual void WalletInitInterface::Close () pure virtual
Close wallets.
Implemented in DummyWalletInit, and WalletInit.
Referenced by Shutdown().
Flush()
virtual void WalletInitInterface::Flush () pure virtual
Flush Wallets.
Implemented in DummyWalletInit, and WalletInit.
Referenced by PrepareShutdown().
GetHelpString()
virtual std::string WalletInitInterface::GetHelpString (bool showDebug) pure virtual
Get wallet help string.
Implemented in DummyWalletInit, and WalletInit.
Referenced by HelpMessage().
InitAutoBackup()
virtual bool WalletInitInterface::InitAutoBackup () pure virtual
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitMain().
InitKeePass()
virtual void WalletInitInterface::InitKeePass () pure virtual
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitMain().
InitPrivateSendSettings()
virtual void WalletInitInterface::InitPrivateSendSettings () pure virtual
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitMain().
Open()
virtual bool WalletInitInterface::Open () pure virtual
Open wallets.
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitMain().
ParameterInteraction()
virtual bool WalletInitInterface::ParameterInteraction () pure virtual
Check wallet parameter interaction.
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitParameterInteraction().
RegisterRPC()
virtual void WalletInitInterface::RegisterRPC (CRPCTable &) pure virtual
Register wallet RPC.
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitMain().
Start()
virtual void WalletInitInterface::Start (CScheduler & scheduler) pure virtual
Start wallets.
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitMain().
Stop()
virtual void WalletInitInterface::Stop () pure virtual
Stop Wallets.
Implemented in DummyWalletInit, and WalletInit.
Referenced by PrepareShutdown().
Verify()
virtual bool WalletInitInterface::Verify () pure virtual
Verify wallets.
Implemented in DummyWalletInit, and WalletInit.
Referenced by AppInitMain().
The documentation for this class was generated from the following file:
src/walletinitinterface.h
Released under the MIT license