Dash Core: CPrivateSendClient Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CPrivateSendClient Class Reference
Used to keep track of current status of mixing pool.
#include <privatesend-client.h>
Public Member Functions
CPrivateSendClient ()
void ProcessMessage (CNode *pfrom, std::string &strCommand, CDataStream &vRecv, CConnman &connman)
void ClearSkippedDenominations ()
void SetMinBlocksToWait (int nMinBlocksToWaitIn)
void ResetPool ()
void UnlockCoins ()
std::string GetStatus ()
bool GetMixingMasternodeInfo (masternode_info_t &mnInfoRet)
bool IsMixingMasternode (const CNode *pnode)
bool DoAutomaticDenominating (CConnman &connman, bool fDryRun=false)
Passively run mixing in the background according to the configuration in settings.
void CheckTimeout ()
void UpdatedBlockTip (const CBlockIndex *pindex)
Public Member Functions inherited from CPrivateSendBase
CPrivateSendBase ()
int GetQueueSize () const
int GetState () const
std::string GetStateString () const
int GetEntriesCount () const
Public Attributes
int nPrivateSendRounds
int nPrivateSendAmount
int nLiquidityProvider
bool fEnablePrivateSend
bool fPrivateSendMultiSession
int nCachedNumBlocks
bool fCreateAutoBackups
Public Attributes inherited from CPrivateSendBase
int nSessionDenom
Private Member Functions
void CheckPool ()
Check for process.
void CompletedTransaction (PoolMessage nMessageID)
bool IsDenomSkipped (CAmount nDenomValue)
bool WaitForAnotherBlock ()
bool CheckAutomaticBackup ()
bool JoinExistingQueue (CAmount nBalanceNeedsAnonymized, CConnman &connman)
bool StartNewQueue (CAmount nValueMin, CAmount nBalanceNeedsAnonymized, CConnman &connman)
bool CreateDenominated (CConnman &connman)
Create denominations.
bool CreateDenominated (const CompactTallyItem &tallyItem, bool fCreateMixingCollaterals, CConnman &connman)
bool MakeCollateralAmounts (CConnman &connman)
Split up large inputs or make fee sized inputs.
bool MakeCollateralAmounts (const CompactTallyItem &tallyItem, bool fTryDenominated, CConnman &connman)
bool SubmitDenominate (CConnman &connman)
As a client, submit part of a future mixing transaction to a Masternode to start the process.
bool PrepareDenominate (int nMinRounds, int nMaxRounds, std::string &strErrorRet, std::vector< CTxDSIn > &vecTxDSInRet, std::vector< CTxOut > &vecTxOutRet)
step 1: prepare denominated inputs and outputs
bool SendDenominate (const std::vector< CTxDSIn > &vecTxDSIn, const std::vector< CTxOut > &vecTxOut, CConnman &connman)
step 2: send denominated inputs and outputs prepared in step 1
bool CheckPoolStateUpdate (PoolState nStateNew, int nEntriesCountNew, PoolStatusUpdate nStatusUpdate, PoolMessage nMessageID, int nSessionIDNew=0)
Get Masternode updates about the progress of mixing.
void SetState (PoolState nStateNew)
bool SignFinalTransaction (const CTransaction &finalTransactionNew, CNode *pnode, CConnman &connman)
As a client, check and sign the final transaction.
void RelayIn (const CDarkSendEntry &entry, CConnman &connman)
void SetNull ()
Private Attributes
std::vector< COutPoint > vecMasternodesUsed
std::vector< CAmount > vecDenominationsSkipped
std::vector< COutPoint > vecOutPointLocked
int nCachedLastSuccessBlock
int nMinBlocksToWait
int nCachedBlockHeight
int nEntriesCount
bool fLastEntryAccepted
std::string strLastMessage
std::string strAutoDenomResult
masternode_info_t infoMixingMasternode
CMutableTransaction txMyCollateral
CKeyHolderStorage keyHolderStorage
Additional Inherited Members
Protected Member Functions inherited from CPrivateSendBase
void SetNull ()
void CheckQueue ()
Protected Attributes inherited from CPrivateSendBase
CCriticalSection cs_darksend
std::vector< CDarksendQueue > vecDarksendQueue
std::vector< CDarkSendEntry > vecEntries
PoolState nState
int64_t nTimeLastSuccessfulStep
int nSessionID
CMutableTransaction finalMutableTransaction
Detailed Description
Used to keep track of current status of mixing pool.
Definition at line 34 of file privatesend-client.h.
Constructor & Destructor Documentation
CPrivateSendClient()
CPrivateSendClient::CPrivateSendClient () inline
Definition at line 112 of file privatesend-client.h.
References SetNull().
Member Function Documentation
CheckAutomaticBackup()
bool CPrivateSendClient::CheckAutomaticBackup () private
Definition at line 614 of file privatesend-client.cpp.
References _(), AutoBackupWallet(), fCreateAutoBackups, fEnablePrivateSend, LogPrint(), LogPrintf, CWallet::nKeysLeftSinceAutoBackup, nWalletBackups, PRIVATESEND_KEYS_THRESHOLD_STOP, PRIVATESEND_KEYS_THRESHOLD_WARNING, pwalletMain, strAutoDenomResult, and strprintf.
Referenced by DoAutomaticDenominating().
CheckPool()
void CPrivateSendClient::CheckPool () private
Check for process.
Definition at line 302 of file privatesend-client.cpp.
References GetTimeMillis(), CKeyHolderStorage::KeepAll(), keyHolderStorage, LogPrint(), CPrivateSendBase::nState, CPrivateSendBase::nTimeLastSuccessfulStep, POOL_STATE_ERROR, POOL_STATE_SUCCESS, CKeyHolderStorage::ReturnAll(), SetNull(), and UnlockCoins().
Referenced by CheckTimeout().
CheckPoolStateUpdate()
bool CPrivateSendClient::CheckPoolStateUpdate (PoolState nStateNew, int nEntriesCountNew, PoolStatusUpdate nStatusUpdate, PoolMessage nMessageID, int nSessionIDNew = 0) private
Get Masternode updates about the progress of mixing.
Definition at line 441 of file privatesend-client.cpp.
References _(), fLastEntryAccepted, fMasterNode, CPrivateSend::GetMessageByID(), GetTimeMillis(), keyHolderStorage, LogPrintf, nEntriesCount, CPrivateSendBase::nSessionID, CPrivateSendBase::nState, CPrivateSendBase::nTimeLastSuccessfulStep, POOL_STATE_ACCEPTING_ENTRIES, POOL_STATE_ERROR, POOL_STATE_IDLE, POOL_STATE_QUEUE, POOL_STATE_SUCCESS, CKeyHolderStorage::ReturnAll(), SetNull(), SetState(), STATUS_ACCEPTED, STATUS_REJECTED, strAutoDenomResult, strLastMessage, and UnlockCoins().
Referenced by ProcessMessage().
CheckTimeout()
void CPrivateSendClient::CheckTimeout ()
Definition at line 320 of file privatesend-client.cpp.
References _(), CheckPool(), CPrivateSendBase::CheckQueue(), fEnablePrivateSend, fMasterNode, GetTimeMillis(), keyHolderStorage, LogPrint(), CPrivateSendBase::nState, CPrivateSendBase::nTimeLastSuccessfulStep, POOL_STATE_ERROR, POOL_STATE_IDLE, POOL_STATE_SIGNING, POOL_STATE_SUCCESS, PRIVATESEND_QUEUE_TIMEOUT, PRIVATESEND_SIGNING_TIMEOUT, CKeyHolderStorage::ReturnAll(), SetNull(), SetState(), strLastMessage, and UnlockCoins().
Referenced by ThreadCheckPrivateSendClient().
ClearSkippedDenominations()
void CPrivateSendClient::ClearSkippedDenominations () inline
Definition at line 126 of file privatesend-client.h.
References vecDenominationsSkipped.
Referenced by CWallet::CreateTransaction().
CompletedTransaction()
void CPrivateSendClient::CompletedTransaction (PoolMessage nMessageID) private
Definition at line 586 of file privatesend-client.cpp.
References fMasterNode, CPrivateSend::GetMessageByID(), CKeyHolderStorage::KeepAll(), keyHolderStorage, LogPrintf, MSG_SUCCESS, nCachedBlockHeight, nCachedLastSuccessBlock, CKeyHolderStorage::ReturnAll(), SetNull(), strLastMessage, and UnlockCoins().
Referenced by ProcessMessage().
CreateDenominated() [1/2]
bool CPrivateSendClient::CreateDenominated (CConnman & connman) private
Create denominations.
Definition at line 1244 of file privatesend-client.cpp.
References cs_main, CWallet::cs_wallet, CWallet::HasCollateralInputs(), LOCK2, LogPrint(), LogPrintf, pwalletMain, and CWallet::SelectCoinsGrouppedByAddresses().
Referenced by DoAutomaticDenominating().
CreateDenominated() [2/2]
bool CPrivateSendClient::CreateDenominated (const CompactTallyItem & tallyItem, bool fCreateMixingCollaterals, CConnman & connman) private
Definition at line 1266 of file privatesend-client.cpp.
References _(), CKeyHolderStorage::AddKey(), COIN, CWallet::CommitTransaction(), CWallet::CountInputsWithAmount(), CWallet::CreateTransaction(), DENOMS_COUNT_MAX, CCoinControl::destChange, CCoinControl::fAllowOtherInputs, CCoinControl::fAllowWatchOnly, CPrivateSend::GetCollateralAmount(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), CPrivateSend::GetMaxCollateralAmount(), CKeyHolder::GetScriptForDestination(), CPrivateSend::GetStandardDenominations(), IsDenomSkipped(), CKeyHolderStorage::KeepAll(), LogPrintf, CompactTallyItem::nAmount, nCachedBlockHeight, nCachedLastSuccessBlock, ONLY_NONDENOMINATED, CTxIn::prevout, prevector< N, T, Size, Diff >::push_back(), pwalletMain, CKeyHolderStorage::ReturnAll(), CCoinControl::Select(), strAutoDenomResult, strprintf, CompactTallyItem::txdest, vecDenominationsSkipped, and CompactTallyItem::vecTxIn.
DoAutomaticDenominating()
bool CPrivateSendClient::DoAutomaticDenominating (CConnman & connman, bool fDryRun = false)
Passively run mixing in the background according to the configuration in settings.
Definition at line 682 of file privatesend-client.cpp.
References _(), CheckAutomaticBackup(), COIN, CMasternodeMan::CountEnabled(), CWallet::CreateCollateralTransaction(), CreateDenominated(), CPrivateSendBase::cs_darksend, fEnablePrivateSend, fMasterNode, fPrivateSendMultiSession, CWallet::GetAnonymizableBalance(), CPrivateSend::GetCollateralAmount(), CWallet::GetDenominatedBalance(), CPrivateSendBase::GetEntriesCount(), CPrivateSend::GetMaxCollateralAmount(), CWallet::GetNeedsToBeAnonymizedBalance(), GetRandInt(), CPrivateSend::GetSmallestDenomination(), CWallet::HasCollateralInputs(), CPrivateSend::IsCollateralValid(), CCryptoKeyStore::IsLocked(), CMasternodeSync::IsMasternodeListSynced(), JoinExistingQueue(), keyHolderStorage, LogPrint(), LogPrintf, MakeCollateralAmounts(), masternodeSync, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, nLiquidityProvider, nPrivateSendAmount, CPrivateSendBase::nSessionID, CPrivateSendBase::nState, POOL_STATE_IDLE, pwalletMain, CKeyHolderStorage::ReturnAll(), SetNull(), CMasternodeMan::size(), StartNewQueue(), strAutoDenomResult, TRY_LOCK, txMyCollateral, UnlockCoins(), vecMasternodesUsed, and WaitForAnotherBlock().
Referenced by OverviewPage::privateSendAuto(), and ThreadCheckPrivateSendClient().
GetMixingMasternodeInfo()
bool CPrivateSendClient::GetMixingMasternodeInfo (masternode_info_t & mnInfoRet)
Definition at line 288 of file privatesend-client.cpp.
References masternode_info_t::fInfoValid, and infoMixingMasternode.
Referenced by getpoolinfo().
GetStatus()
std::string CPrivateSendClient::GetStatus ()
Definition at line 239 of file privatesend-client.cpp.
References _(), fLastEntryAccepted, CPrivateSend::GetMaxPoolTransactions(), CMasternodeSync::IsBlockchainSynced(), masternodeSync, nEntriesCount, CPrivateSendBase::nState, POOL_STATE_ACCEPTING_ENTRIES, POOL_STATE_ERROR, POOL_STATE_IDLE, POOL_STATE_QUEUE, POOL_STATE_SIGNING, POOL_STATE_SUCCESS, strAutoDenomResult, strLastMessage, strprintf, and WaitForAnotherBlock().
Referenced by getpoolinfo(), and OverviewPage::privateSendStatus().
IsDenomSkipped()
bool CPrivateSendClient::IsDenomSkipped (CAmount nDenomValue) inline private
Definition at line 64 of file privatesend-client.h.
References vecDenominationsSkipped.
Referenced by CreateDenominated().
IsMixingMasternode()
bool CPrivateSendClient::IsMixingMasternode (const CNode * pnode)
Definition at line 294 of file privatesend-client.cpp.
References masternode_info_t::addr, CNode::addr, masternode_info_t::fInfoValid, and infoMixingMasternode.
Referenced by CMasternodeMan::ProcessMasternodeConnections().
JoinExistingQueue()
bool CPrivateSendClient::JoinExistingQueue (CAmount nBalanceNeedsAnonymized, CConnman & connman) private
Definition at line 832 of file privatesend-client.cpp.
References _(), masternode_info_t::addr, CConnman::AllNodes, CConnman::ConnectNode(), NetMsgType::DSACCEPT, CConnman::ForNode(), CDarksendQueue::fTried, CPrivateSend::GetDenominationsBits(), CPrivateSend::GetDenominationsToString(), CMasternodeMan::GetMasternodeInfo(), CPrivateSend::GetStandardDenominations(), GetTimeMillis(), infoMixingMasternode, CDarksendQueue::IsExpired(), LogPrint(), LogPrintf, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, CDarksendQueue::nDenom, NODE_NETWORK, nPrivateSendRounds, masternode_info_t::nProtocolVersion, CPrivateSendBase::nSessionDenom, CPrivateSendBase::nTimeLastSuccessfulStep, POOL_STATE_QUEUE, CTxIn::prevout, CConnman::PushMessage(), pwalletMain, CWallet::SelectCoinsByDenominations(), SetState(), strAutoDenomResult, CDarksendQueue::ToString(), COutPoint::ToStringShort(), txMyCollateral, CPrivateSendBase::vecDarksendQueue, vecMasternodesUsed, and CDarksendQueue::vin.
Referenced by DoAutomaticDenominating().
MakeCollateralAmounts() [1/2]
bool CPrivateSendClient::MakeCollateralAmounts (CConnman & connman) private
Split up large inputs or make fee sized inputs.
Definition at line 1147 of file privatesend-client.cpp.
References LogPrint(), LogPrintf, pwalletMain, and CWallet::SelectCoinsGrouppedByAddresses().
Referenced by DoAutomaticDenominating().
MakeCollateralAmounts() [2/2]
bool CPrivateSendClient::MakeCollateralAmounts (const CompactTallyItem & tallyItem, bool fTryDenominated, CConnman & connman) private
Definition at line 1173 of file privatesend-client.cpp.
References ALL_COINS, CWallet::CommitTransaction(), CWallet::CreateTransaction(), cs_main, CWallet::cs_wallet, CCoinControl::destChange, CCoinControl::fAllowOtherInputs, CCoinControl::fAllowWatchOnly, CTransaction::GetHash(), base_blob< BITS >::GetHex(), CPubKey::GetID(), CPrivateSend::GetMaxCollateralAmount(), CReserveKey::GetReservedKey(), GetScriptForDestination(), CPrivateSend::IsDenominatedAmount(), CReserveKey::KeepKey(), LOCK2, LogPrintf, CompactTallyItem::nAmount, nCachedBlockHeight, nCachedLastSuccessBlock, ONLY_NONDENOMINATED, CTxIn::prevout, prevector< N, T, Size, Diff >::push_back(), pwalletMain, CReserveKey::ReturnKey(), CCoinControl::Select(), CompactTallyItem::txdest, and CompactTallyItem::vecTxIn.
PrepareDenominate()
bool CPrivateSendClient::PrepareDenominate (int nMinRounds, int nMaxRounds, std::string & strErrorRet, std::vector< CTxDSIn > & vecTxDSInRet, std::vector< CTxOut > & vecTxOutRet) private
step 1: prepare denominated inputs and outputs
Definition at line 1026 of file privatesend-client.cpp.
References CKeyHolderStorage::AddKey(), COIN, CWallet::cs_wallet, CPrivateSend::GetDenominations(), CPrivateSend::GetDenominationsBits(), CPrivateSendBase::GetEntriesCount(), CPrivateSend::GetMaxPoolAmount(), GetRandInt(), CKeyHolder::GetScriptForDestination(), CPrivateSend::GetStandardDenominations(), CCryptoKeyStore::IsLocked(), keyHolderStorage, LOCK, CWallet::LockCoin(), LogPrintf, CPrivateSendBase::nSessionDenom, PRIVATESEND_ENTRY_MAX_SIZE, pwalletMain, CKeyHolderStorage::ReturnAll(), CWallet::SelectCoinsByDenominations(), CWallet::UnlockCoin(), and vCoins.
Referenced by SubmitDenominate().
ProcessMessage()
void CPrivateSendClient::ProcessMessage (CNode * pfrom, std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 21 of file privatesend-client.cpp.
References masternode_info_t::addr, CNode::addr, CMasternodeMan::AllowMixing(), CMasternodeMan::AskForMN(), CheckPoolStateUpdate(), CompletedTransaction(), CMasternodeMan::CountEnabled(), CPrivateSendBase::cs_darksend, NetMsgType::DSCOMPLETE, NetMsgType::DSFINALTX, NetMsgType::DSQUEUE, NetMsgType::DSSTATUSUPDATE, masternode_info_t::fInfoValid, fLiteMode, fMasterNode, CMasternodeMan::GetMasternodeInfo(), CPrivateSend::GetMessageByID(), infoMixingMasternode, CMasternodeSync::IsBlockchainSynced(), LogPrint(), LogPrintf, masternodeSync, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, MSG_POOL_MAX, CMasternodeMan::nDsqCount, nEntriesCount, masternode_info_t::nLastDsq, CPrivateSendBase::nSessionID, CPrivateSendBase::nState, CNode::nVersion, POOL_STATE_MAX, POOL_STATE_QUEUE, CTxIn::prevout, masternode_info_t::pubKeyMasternode, SignFinalTransaction(), STATUS_ACCEPTED, SubmitDenominate(), CService::ToString(), TRY_LOCK, CPrivateSendBase::vecDarksendQueue, masternode_info_t::vin, and CDarksendQueue::vin.
Referenced by ProcessMessage().
RelayIn()
void CPrivateSendClient::RelayIn (const CDarkSendEntry & entry, CConnman & connman) private
Definition at line 1372 of file privatesend-client.cpp.
References masternode_info_t::addr, masternode_info_t::fInfoValid, CConnman::ForNode(), and infoMixingMasternode.
Referenced by SendDenominate().
ResetPool()
void CPrivateSendClient::ResetPool ()
Definition at line 203 of file privatesend-client.cpp.
References keyHolderStorage, nCachedLastSuccessBlock, CKeyHolderStorage::ReturnAll(), SetNull(), txMyCollateral, UnlockCoins(), and vecMasternodesUsed.
Referenced by OverviewPage::privateSendReset().
SendDenominate()
bool CPrivateSendClient::SendDenominate (const std::vector< CTxDSIn > & vecTxDSIn, const std::vector< CTxOut > & vecTxOut, CConnman & connman) private
step 2: send denominated inputs and outputs prepared in step 1
Definition at line 361 of file privatesend-client.cpp.
References AcceptToMemoryPool(), CheckDiskSpace(), COIN, cs_main, fEnablePrivateSend, fMasterNode, CMutableTransaction::GetHash(), GetTimeMillis(), keyHolderStorage, LogPrint(), LogPrintf, mempool, CPrivateSendBase::nSessionID, CPrivateSendBase::nTimeLastSuccessfulStep, POOL_STATE_ACCEPTING_ENTRIES, CTxIn::prevout, CTxMemPool::PrioritiseTransaction(), RelayIn(), CKeyHolderStorage::ReturnAll(), SetNull(), SetState(), strLastMessage, base_blob< BITS >::ToString(), CTxOut::ToString(), CMutableTransaction::ToString(), TRY_LOCK, txMyCollateral, UnlockCoins(), CPrivateSendBase::vecEntries, vecOutPointLocked, CMutableTransaction::vin, and CMutableTransaction::vout.
Referenced by SubmitDenominate().
SetMinBlocksToWait()
void CPrivateSendClient::SetMinBlocksToWait (int nMinBlocksToWaitIn) inline
Definition at line 128 of file privatesend-client.h.
References nMinBlocksToWait.
Referenced by AppInit2().
SetNull()
void CPrivateSendClient::SetNull () private
Definition at line 213 of file privatesend-client.cpp.
References fLastEntryAccepted, infoMixingMasternode, nEntriesCount, and CPrivateSendBase::SetNull().
Referenced by CheckPool(), CheckPoolStateUpdate(), CheckTimeout(), CompletedTransaction(), CPrivateSendClient(), DoAutomaticDenominating(), ResetPool(), SendDenominate(), and SignFinalTransaction().
SetState()
void CPrivateSendClient::SetState (PoolState nStateNew) private
Definition at line 1383 of file privatesend-client.cpp.
References LogPrintf, and CPrivateSendBase::nState.
Referenced by CheckPoolStateUpdate(), CheckTimeout(), JoinExistingQueue(), SendDenominate(), SignFinalTransaction(), and StartNewQueue().
SignFinalTransaction()
bool CPrivateSendClient::SignFinalTransaction (const CTransaction & finalTransactionNew, CNode * pnode, CConnman & connman) private
As a client, check and sign the final transaction.
Definition at line 487 of file privatesend-client.cpp.
References NetMsgType::DSSIGNFINALTX, CPrivateSendBase::finalMutableTransaction, fMasterNode, CTransaction::GetHash(), CMutableTransaction::GetHash(), GetTimeMillis(), infoMixingMasternode, keyHolderStorage, LogPrint(), LogPrintf, CPrivateSendBase::nTimeLastSuccessfulStep, POOL_STATE_SIGNING, CTxIn::prevout, CTxDSIn::prevPubKey, CConnman::PushMessage(), pwalletMain, CKeyHolderStorage::ReturnAll(), ScriptToAsmStr(), SetNull(), SetState(), SIGHASH_ALL, SIGHASH_ANYONECANPAY, SignSignature(), CMutableTransaction::ToString(), COutPoint::ToStringShort(), UnlockCoins(), CPrivateSendBase::vecEntries, CDarkSendEntry::vecTxDSIn, CDarkSendEntry::vecTxOut, masternode_info_t::vin, CMutableTransaction::vin, and CMutableTransaction::vout.
Referenced by ProcessMessage().
StartNewQueue()
bool CPrivateSendClient::StartNewQueue (CAmount nValueMin, CAmount nBalanceNeedsAnonymized, CConnman & connman) private
Definition at line 916 of file privatesend-client.cpp.
References _(), masternode_info_t::addr, CConnman::AllNodes, CConnman::ConnectNode(), CWallet::ConvertList(), CMasternodeMan::CountEnabled(), NetMsgType::DSACCEPT, CMasternodeMan::FindRandomNotInVec(), masternode_info_t::fInfoValid, CConnman::ForNode(), CPrivateSend::GetDenominationsByAmounts(), CPrivateSend::GetDenominationsToString(), GetTimeMillis(), infoMixingMasternode, LogPrintf, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, CMasternodeMan::nDsqCount, masternode_info_t::nLastDsq, NODE_NETWORK, nPrivateSendRounds, CPrivateSendBase::nSessionDenom, CPrivateSendBase::nTimeLastSuccessfulStep, POOL_STATE_QUEUE, CTxIn::prevout, CConnman::PushMessage(), pwalletMain, CWallet::SelectCoinsDark(), SetState(), strAutoDenomResult, CService::ToString(), COutPoint::ToStringShort(), txMyCollateral, vecMasternodesUsed, and masternode_info_t::vin.
Referenced by DoAutomaticDenominating().
SubmitDenominate()
bool CPrivateSendClient::SubmitDenominate (CConnman & connman) private
As a client, submit part of a future mixing transaction to a Masternode to start the process.
Definition at line 998 of file privatesend-client.cpp.
References LogPrint(), LogPrintf, nPrivateSendRounds, PrepareDenominate(), SendDenominate(), and strAutoDenomResult.
Referenced by ProcessMessage().
UnlockCoins()
void CPrivateSendClient::UnlockCoins ()
Definition at line 226 of file privatesend-client.cpp.
References CWallet::cs_wallet, MilliSleep(), pwalletMain, TRY_LOCK, CWallet::UnlockCoin(), and vecOutPointLocked.
Referenced by CheckPool(), CheckPoolStateUpdate(), CheckTimeout(), CompletedTransaction(), DoAutomaticDenominating(), ResetPool(), SendDenominate(), SignFinalTransaction(), and OverviewPage::togglePrivateSend().
UpdatedBlockTip()
void CPrivateSendClient::UpdatedBlockTip (const CBlockIndex * pindex)
Definition at line 1389 of file privatesend-client.cpp.
References LogPrint(), nCachedBlockHeight, and CBlockIndex::nHeight.
Referenced by CDSNotificationInterface::UpdatedBlockTip().
WaitForAnotherBlock()
bool CPrivateSendClient::WaitForAnotherBlock () private
Definition at line 603 of file privatesend-client.cpp.
References fPrivateSendMultiSession, CMasternodeSync::IsMasternodeListSynced(), masternodeSync, nCachedBlockHeight, nCachedLastSuccessBlock, and nMinBlocksToWait.
Referenced by DoAutomaticDenominating(), and GetStatus().
Member Data Documentation
fCreateAutoBackups
bool CPrivateSendClient::fCreateAutoBackups
Definition at line 110 of file privatesend-client.h.
Referenced by CheckAutomaticBackup(), and OverviewPage::OverviewPage().
fEnablePrivateSend
bool CPrivateSendClient::fEnablePrivateSend
Definition at line 106 of file privatesend-client.h.
Referenced by AppInit2(), CheckAutomaticBackup(), CheckTimeout(), OverviewPage::DisablePrivateSendCompletely(), DoAutomaticDenominating(), CWallet::NewKeyPool(), OverviewPage::OverviewPage(), OverviewPage::privateSendStatus(), SendDenominate(), and OverviewPage::togglePrivateSend().
fLastEntryAccepted
bool CPrivateSendClient::fLastEntryAccepted private
Definition at line 50 of file privatesend-client.h.
Referenced by CheckPoolStateUpdate(), GetStatus(), and SetNull().
fPrivateSendMultiSession
bool CPrivateSendClient::fPrivateSendMultiSession
Definition at line 107 of file privatesend-client.h.
Referenced by AppInit2(), DoAutomaticDenominating(), getpoolinfo(), OptionsModel::Init(), OptionsModel::setData(), and WaitForAnotherBlock().
infoMixingMasternode
masternode_info_t CPrivateSendClient::infoMixingMasternode private
Definition at line 55 of file privatesend-client.h.
Referenced by GetMixingMasternodeInfo(), IsMixingMasternode(), JoinExistingQueue(), ProcessMessage(), RelayIn(), SetNull(), SignFinalTransaction(), and StartNewQueue().
keyHolderStorage
CKeyHolderStorage CPrivateSendClient::keyHolderStorage private
Definition at line 58 of file privatesend-client.h.
Referenced by CheckPool(), CheckPoolStateUpdate(), CheckTimeout(), CompletedTransaction(), DoAutomaticDenominating(), PrepareDenominate(), ResetPool(), SendDenominate(), and SignFinalTransaction().
nCachedBlockHeight
int CPrivateSendClient::nCachedBlockHeight private
Definition at line 47 of file privatesend-client.h.
Referenced by CompletedTransaction(), CreateDenominated(), MakeCollateralAmounts(), UpdatedBlockTip(), and WaitForAnotherBlock().
nCachedLastSuccessBlock
int CPrivateSendClient::nCachedLastSuccessBlock private
Definition at line 43 of file privatesend-client.h.
Referenced by CompletedTransaction(), CreateDenominated(), MakeCollateralAmounts(), ResetPool(), and WaitForAnotherBlock().
nCachedNumBlocks
int CPrivateSendClient::nCachedNumBlocks
Definition at line 109 of file privatesend-client.h.
Referenced by OptionsDialog::on_okButton_clicked(), OverviewPage::privateSendStatus(), and OverviewPage::togglePrivateSend().
nEntriesCount
int CPrivateSendClient::nEntriesCount private
Definition at line 49 of file privatesend-client.h.
Referenced by CheckPoolStateUpdate(), GetStatus(), ProcessMessage(), and SetNull().
nLiquidityProvider
int CPrivateSendClient::nLiquidityProvider
Definition at line 105 of file privatesend-client.h.
Referenced by AppInit2(), and DoAutomaticDenominating().
nMinBlocksToWait
int CPrivateSendClient::nMinBlocksToWait private
Definition at line 44 of file privatesend-client.h.
Referenced by SetMinBlocksToWait(), and WaitForAnotherBlock().
nPrivateSendAmount
int CPrivateSendClient::nPrivateSendAmount
Definition at line 104 of file privatesend-client.h.
Referenced by AppInit2(), DarksendConfig::configure(), DoAutomaticDenominating(), CWallet::GetNeedsToBeAnonymizedBalance(), OptionsModel::Init(), OptionsModel::setData(), OverviewPage::togglePrivateSend(), and OverviewPage::updatePrivateSendProgress().
nPrivateSendRounds
int CPrivateSendClient::nPrivateSendRounds
Definition at line 103 of file privatesend-client.h.
Referenced by AppInit2(), DarksendConfig::configure(), CWalletTx::GetAnonymizedCredit(), CWallet::GetNormalizedAnonymizedBalance(), CWallet::GetOutpointPrivateSendRounds(), OptionsModel::Init(), JoinExistingQueue(), WalletModel::pollBalanceChanged(), CWallet::SelectCoins(), CWallet::SelectCoinsGrouppedByAddresses(), OptionsModel::setData(), StartNewQueue(), SubmitDenominate(), OverviewPage::updatePrivateSendProgress(), and CoinControlDialog::viewItemChanged().
strAutoDenomResult
std::string CPrivateSendClient::strAutoDenomResult private
Definition at line 53 of file privatesend-client.h.
Referenced by CheckAutomaticBackup(), CheckPoolStateUpdate(), CreateDenominated(), DoAutomaticDenominating(), GetStatus(), JoinExistingQueue(), StartNewQueue(), and SubmitDenominate().
strLastMessage
std::string CPrivateSendClient::strLastMessage private
Definition at line 52 of file privatesend-client.h.
Referenced by CheckPoolStateUpdate(), CheckTimeout(), CompletedTransaction(), GetStatus(), and SendDenominate().
txMyCollateral
CMutableTransaction CPrivateSendClient::txMyCollateral private
Definition at line 56 of file privatesend-client.h.
Referenced by DoAutomaticDenominating(), JoinExistingQueue(), ResetPool(), SendDenominate(), and StartNewQueue().
vecDenominationsSkipped
std::vector<CAmount> CPrivateSendClient::vecDenominationsSkipped private
Definition at line 40 of file privatesend-client.h.
Referenced by ClearSkippedDenominations(), CreateDenominated(), and IsDenomSkipped().
vecMasternodesUsed
std::vector<COutPoint> CPrivateSendClient::vecMasternodesUsed private
Definition at line 38 of file privatesend-client.h.
Referenced by DoAutomaticDenominating(), JoinExistingQueue(), ResetPool(), and StartNewQueue().
vecOutPointLocked
std::vector<COutPoint> CPrivateSendClient::vecOutPointLocked private
Definition at line 41 of file privatesend-client.h.
Referenced by SendDenominate(), and UnlockCoins().
The documentation for this class was generated from the following files:
src/privatesend-client.h
src/privatesend-client.cpp
Released under the MIT license