Dash Core: llmq::CLLMQUtils Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CLLMQUtils Class Reference
#include <quorums_utils.h>
Static Public Member Functions
static std::vector< CDeterministicMNCPtr > GetAllQuorumMembers (Consensus::LLMQType llmqType, const CBlockIndex *pindexQuorum)
static uint256 BuildCommitmentHash (Consensus::LLMQType llmqType, const uint256 &blockHash, const std::vector< bool > &validMembers, const CBLSPublicKey &pubKey, const uint256 &vvecHash)
static uint256 BuildSignHash (Consensus::LLMQType llmqType, const uint256 &quorumHash, const uint256 &id, const uint256 &msgHash)
template<typename T >
static uint256 BuildSignHash (const T &s)
static bool IsAllMembersConnectedEnabled (Consensus::LLMQType llmqType)
static uint256 DeterministicOutboundConnection (const uint256 &proTxHash1, const uint256 &proTxHash2)
static std::set< uint256 > GetQuorumConnections (Consensus::LLMQType llmqType, const CBlockIndex *pindexQuorum, const uint256 &forMember, bool onlyOutbound)
static std::set< uint256 > GetQuorumRelayMembers (Consensus::LLMQType llmqType, const CBlockIndex *pindexQuorum, const uint256 &forMember, bool onlyOutbound)
static std::set< size_t > CalcDeterministicWatchConnections (Consensus::LLMQType llmqType, const CBlockIndex *pindexQuorum, size_t memberCount, size_t connectionCount)
static void EnsureQuorumConnections (Consensus::LLMQType llmqType, const CBlockIndex *pindexQuorum, const uint256 &myProTxHash, bool allowWatch)
static void AddQuorumProbeConnections (Consensus::LLMQType llmqType, const CBlockIndex *pindexQuorum, const uint256 &myProTxHash)
static bool IsQuorumActive (Consensus::LLMQType llmqType, const uint256 &quorumHash)
template<typename NodesContainer , typename Continue , typename Callback >
static void IterateNodesRandom (NodesContainer &nodeStates, Continue &&cont, Callback &&callback, FastRandomContext &rnd)
static std::string ToHexStr (const std::vector< bool > &vBits)
Detailed Description
Definition at line 18 of file quorums_utils.h.
Member Function Documentation
AddQuorumProbeConnections()
void llmq::CLLMQUtils::AddQuorumProbeConnections (Consensus::LLMQType llmqType, const CBlockIndex * pindexQuorum, const uint256 & myProTxHash) static
Definition at line 207 of file quorums_utils.cpp.
References deterministicMNManager, g_connman, GetAdjustedTime(), GetAllQuorumMembers(), CBlockIndex::GetBlockHash(), CMasternodeMetaMan::GetMetaInfo(), BCLog::LLMQ, LogAcceptCategory(), LogPrint, mmetaman, BCLog::NET_NETCONN, strprintf, and base_blob< BITS >::ToString().
Referenced by llmq::CDKGSessionHandler::HandleDKGRound().
BuildCommitmentHash()
uint256 llmq::CLLMQUtils::BuildCommitmentHash (Consensus::LLMQType llmqType, const uint256 & blockHash, const std::vector< bool > & validMembers, const CBLSPublicKey & pubKey, const uint256 & vvecHash) static
Definition at line 26 of file quorums_utils.cpp.
References DYNBITSET, CHashWriter::GetHash(), and SER_NETWORK.
Referenced by llmq::CDKGSession::FinalizeCommitments(), llmq::CDKGPrematureCommitment::GetSignHash(), llmq::CDKGSession::SendCommitment(), and llmq::CFinalCommitment::Verify().
BuildSignHash() [1/2]
uint256 llmq::CLLMQUtils::BuildSignHash (Consensus::LLMQType llmqType, const uint256 & quorumHash, const uint256 & id, const uint256 & msgHash) static
Definition at line 37 of file quorums_utils.cpp.
References CHashWriter::GetHash(), and SER_GETHASH.
Referenced by BuildSignHash(), llmq::CSigningManager::CollectPendingRecoveredSigsToVerify(), llmq::CSigSharesManager::ForceReAnnouncement(), llmq::CSigSharesNodeState::GetOrCreateSessionFromAnn(), llmq::CSigSharesManager::HandleNewRecoveredSig(), llmq::CSigningManager::ProcessMessageRecoveredSig(), llmq::CSigSharesManager::ProcessMessageSigSesAnn(), llmq::CInstantSendManager::ProcessPendingInstantSendLocks(), llmq::CSigningManager::ProcessPendingRecoveredSigs(), llmq::CRecoveredSigsDb::RemoveRecoveredSig(), llmq::CSigSharesManager::SendMessages(), llmq::CSigSharesManager::Sign(), llmq::CSigSharesManager::TryRecoverSig(), llmq::CSigShare::UpdateKey(), and llmq::CRecoveredSigsDb::WriteRecoveredSig().
BuildSignHash() [2/2]
template<typename T > static uint256 llmq::CLLMQUtils::BuildSignHash (const T & s) inline static
Definition at line 29 of file quorums_utils.h.
References BuildSignHash().
CalcDeterministicWatchConnections()
std::set< size_t > llmq::CLLMQUtils::CalcDeterministicWatchConnections (Consensus::LLMQType llmqType, const CBlockIndex * pindexQuorum, size_t memberCount, size_t connectionCount) static
Definition at line 149 of file quorums_utils.cpp.
References CBlockIndex::GetBlockHash(), GetRandHash(), base_blob< BITS >::GetUint64(), LOCK, and SerializeHash().
Referenced by EnsureQuorumConnections().
DeterministicOutboundConnection()
uint256 llmq::CLLMQUtils::DeterministicOutboundConnection (const uint256 & proTxHash1, const uint256 & proTxHash2) static
Definition at line 59 of file quorums_utils.cpp.
References SerializeHash().
Referenced by GetQuorumConnections().
EnsureQuorumConnections()
void llmq::CLLMQUtils::EnsureQuorumConnections (Consensus::LLMQType llmqType, const CBlockIndex * pindexQuorum, const uint256 & myProTxHash, bool allowWatch) static
Definition at line 171 of file quorums_utils.cpp.
References CalcDeterministicWatchConnections(), deterministicMNManager, g_connman, GetAllQuorumMembers(), CBlockIndex::GetBlockHash(), GetQuorumConnections(), BCLog::LLMQ, LogAcceptCategory(), LogPrint, BCLog::NET_NETCONN, strprintf, and base_blob< BITS >::ToString().
Referenced by llmq::CQuorumManager::EnsureQuorumConnections(), and llmq::CDKGSessionHandler::HandleDKGRound().
GetAllQuorumMembers()
std::vector< CDeterministicMNCPtr > llmq::CLLMQUtils::GetAllQuorumMembers (Consensus::LLMQType llmqType, const CBlockIndex * pindexQuorum) static
Definition at line 18 of file quorums_utils.cpp.
References deterministicMNManager, CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), Consensus::Params::llmqs, Params(), and SerializeHash().
Referenced by AddQuorumProbeConnections(), llmq::CQuorumManager::BuildQuorumFromCommitment(), llmq::CheckLLMQCommitment(), EnsureQuorumConnections(), GetQuorumConnections(), GetQuorumRelayMembers(), llmq::CDKGSessionManager::GetVerifiedContributions(), CDeterministicMNManager::HandleQuorumCommitment(), llmq::CDKGSessionHandler::InitNewQuorum(), llmq::CQuorumBlockProcessor::ProcessCommitment(), llmq::CQuorumBlockProcessor::ProcessMessage(), and llmq::CDKGDebugSessionStatus::ToJson().
GetQuorumConnections()
std::set< uint256 > llmq::CLLMQUtils::GetQuorumConnections (Consensus::LLMQType llmqType, const CBlockIndex * pindexQuorum, const uint256 & forMember, bool onlyOutbound) static
Definition at line 81 of file quorums_utils.cpp.
References DeterministicOutboundConnection(), GetAllQuorumMembers(), CChainParams::GetConsensus(), GetQuorumRelayMembers(), IsAllMembersConnectedEnabled(), Consensus::Params::llmqs, and Params().
Referenced by EnsureQuorumConnections(), and quorum_dkgstatus().
GetQuorumRelayMembers()
std::set< uint256 > llmq::CLLMQUtils::GetQuorumRelayMembers (Consensus::LLMQType llmqType, const CBlockIndex * pindexQuorum, const uint256 & forMember, bool onlyOutbound) static
Definition at line 107 of file quorums_utils.cpp.
References GetAllQuorumMembers().
Referenced by GetQuorumConnections(), and llmq::CDKGSession::Init().
IsAllMembersConnectedEnabled()
bool llmq::CLLMQUtils::IsAllMembersConnectedEnabled (Consensus::LLMQType llmqType) static
Definition at line 47 of file quorums_utils.cpp.
References CSporkManager::GetSporkValue(), Consensus::LLMQ_400_60, Consensus::LLMQ_400_85, SPORK_21_QUORUM_ALL_CONNECTED, and sporkManager.
Referenced by llmq::CSigSharesManager::CollectSigSharesToRequest(), llmq::CSigSharesManager::CollectSigSharesToSend(), llmq::CSigSharesManager::CollectSigSharesToSendConcentrated(), llmq::CSigSharesManager::ForceReAnnouncement(), GetQuorumConnections(), llmq::CDKGSessionHandler::HandleDKGRound(), llmq::CSigSharesManager::ProcessSigShare(), llmq::CSigSharesManager::Sign(), and llmq::CDKGSession::VerifyConnectionAndMinProtoVersions().
IsQuorumActive()
bool llmq::CLLMQUtils::IsQuorumActive (Consensus::LLMQType llmqType, const uint256 & quorumHash) static
Definition at line 243 of file quorums_utils.cpp.
References CChainParams::GetConsensus(), Consensus::Params::llmqs, Params(), llmq::quorumManager, and llmq::CQuorumManager::ScanQuorums().
Referenced by llmq::CSigSharesManager::Cleanup(), llmq::CSigningManager::CollectPendingRecoveredSigsToVerify(), llmq::CSigningManager::GetRecoveredSigForGetData(), llmq::CSigSharesManager::PreVerifyBatchedSigShares(), llmq::CSigningManager::PreVerifyRecoveredSig(), and llmq::CSigSharesManager::ProcessMessageSigShare().
IterateNodesRandom()
template<typename NodesContainer , typename Continue , typename Callback > static void llmq::CLLMQUtils::IterateNodesRandom (NodesContainer & nodeStates, Continue && cont, Callback && callback, FastRandomContext & rnd) inline static
Definition at line 46 of file quorums_utils.h.
Referenced by llmq::CSigningManager::CollectPendingRecoveredSigsToVerify(), and llmq::CSigSharesManager::CollectPendingSigSharesToVerify().
ToHexStr()
static std::string llmq::CLLMQUtils::ToHexStr (const std::vector< bool > & vBits) inline static
Definition at line 74 of file quorums_utils.h.
References HexStr().
Referenced by llmq::CFinalCommitment::ToJson().
The documentation for this class was generated from the following files:
src/llmq/quorums_utils.h
src/llmq/quorums_utils.cpp
Released under the MIT license