Dash Core: CBlockHeaderAndShortTxIDs Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBlockHeaderAndShortTxIDs Class Reference
#include <blockencodings.h>
Public Member Functions
CBlockHeaderAndShortTxIDs ()
CBlockHeaderAndShortTxIDs (const CBlock &block)
uint64_t GetShortID (const uint256 &txhash) const
size_t BlockTxCount () const
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
Public Attributes
CBlockHeader header
ADD_SERIALIZE_METHODS
Protected Attributes
std::vector< uint64_t > shorttxids
std::vector< PrefilledTransaction > prefilledtxn
Private Member Functions
void FillShortTxIDSelector () const
Private Attributes
uint64_t shorttxidk0
uint64_t shorttxidk1
uint64_t nonce
Static Private Attributes
static const int SHORTTXIDS_LENGTH = 6
Friends
class PartiallyDownloadedBlock
Detailed Description
Definition at line 131 of file blockencodings.h.
Constructor & Destructor Documentation
CBlockHeaderAndShortTxIDs() [1/2]
CBlockHeaderAndShortTxIDs::CBlockHeaderAndShortTxIDs () inline
Definition at line 149 of file blockencodings.h.
CBlockHeaderAndShortTxIDs() [2/2]
CBlockHeaderAndShortTxIDs::CBlockHeaderAndShortTxIDs (const CBlock & block)
Definition at line 20 of file blockencodings.cpp.
References FillShortTxIDSelector(), CTransaction::GetHash(), GetShortID(), prefilledtxn, shorttxids, and CBlock::vtx.
Member Function Documentation
BlockTxCount()
size_t CBlockHeaderAndShortTxIDs::BlockTxCount () const inline
Definition at line 155 of file blockencodings.h.
References prefilledtxn, and shorttxids.
Referenced by PartiallyDownloadedBlock::InitData().
FillShortTxIDSelector()
void CBlockHeaderAndShortTxIDs::FillShortTxIDSelector () const private
Definition at line 32 of file blockencodings.cpp.
References base_blob< BITS >::begin(), CDataStream::begin(), CDataStream::end(), CSHA256::Finalize(), base_blob< BITS >::GetUint64(), header, nonce, PROTOCOL_VERSION, SER_NETWORK, shorttxidk0, shorttxidk1, and CSHA256::Write().
Referenced by CBlockHeaderAndShortTxIDs(), and SerializationOp().
GetShortID()
uint64_t CBlockHeaderAndShortTxIDs::GetShortID (const uint256 & txhash) const
Definition at line 43 of file blockencodings.cpp.
References L, shorttxidk0, shorttxidk1, SHORTTXIDS_LENGTH, and SipHashUint256().
Referenced by CBlockHeaderAndShortTxIDs(), and PartiallyDownloadedBlock::InitData().
SerializationOp()
template<typename Stream , typename Operation > void CBlockHeaderAndShortTxIDs::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 160 of file blockencodings.h.
References COMPACTSIZE, FillShortTxIDSelector(), header, nonce, prefilledtxn, READWRITE, shorttxids, and SHORTTXIDS_LENGTH.
Friends And Related Function Documentation
PartiallyDownloadedBlock
friend class PartiallyDownloadedBlock friend
Definition at line 138 of file blockencodings.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CBlockHeaderAndShortTxIDs::ADD_SERIALIZE_METHODS
Definition at line 157 of file blockencodings.h.
header
CBlockHeader CBlockHeaderAndShortTxIDs::header
Definition at line 146 of file blockencodings.h.
Referenced by FillShortTxIDSelector(), PartiallyDownloadedBlock::InitData(), and SerializationOp().
nonce
uint64_t CBlockHeaderAndShortTxIDs::nonce private
Definition at line 134 of file blockencodings.h.
Referenced by FillShortTxIDSelector(), and SerializationOp().
prefilledtxn
std::vector<PrefilledTransaction> CBlockHeaderAndShortTxIDs::prefilledtxn protected
Definition at line 143 of file blockencodings.h.
Referenced by BlockTxCount(), CBlockHeaderAndShortTxIDs(), PartiallyDownloadedBlock::InitData(), and SerializationOp().
shorttxidk0
uint64_t CBlockHeaderAndShortTxIDs::shorttxidk0 mutable private
Definition at line 133 of file blockencodings.h.
Referenced by FillShortTxIDSelector(), and GetShortID().
shorttxidk1
uint64_t CBlockHeaderAndShortTxIDs::shorttxidk1 mutable private
Definition at line 133 of file blockencodings.h.
Referenced by FillShortTxIDSelector(), and GetShortID().
shorttxids
std::vector<uint64_t> CBlockHeaderAndShortTxIDs::shorttxids protected
Definition at line 142 of file blockencodings.h.
Referenced by BlockTxCount(), CBlockHeaderAndShortTxIDs(), PartiallyDownloadedBlock::InitData(), and SerializationOp().
SHORTTXIDS_LENGTH
const int CBlockHeaderAndShortTxIDs::SHORTTXIDS_LENGTH = 6 static private
Definition at line 140 of file blockencodings.h.
Referenced by GetShortID(), and SerializationOp().
The documentation for this class was generated from the following files:
src/blockencodings.h
src/blockencodings.cpp
Released under the MIT license