Dash Core: SendConfirmationDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
SendConfirmationDialog Class Reference
#include <sendcoinsdialog.h>
Public Member Functions
SendConfirmationDialog (const QString &title, const QString &text, int secDelay=0, QWidget *parent=0)
int exec ()
Private Slots
void countDown ()
void updateYesButton ()
Private Attributes
QAbstractButton * yesButton
QTimer countDownTimer
int secDelay
Detailed Description
Definition at line 110 of file sendcoinsdialog.h.
Constructor & Destructor Documentation
SendConfirmationDialog()
SendConfirmationDialog::SendConfirmationDialog (const QString & title, const QString & text, int secDelay = 0, QWidget * parent = 0)
Definition at line 1008 of file sendcoinsdialog.cpp.
References countDown(), countDownTimer, GUIUtil::updateFonts(), updateYesButton(), and yesButton.
Member Function Documentation
countDown
void SendConfirmationDialog::countDown () private slot
Definition at line 1026 of file sendcoinsdialog.cpp.
References countDownTimer, secDelay, and updateYesButton().
Referenced by SendConfirmationDialog().
exec()
int SendConfirmationDialog::exec ()
Definition at line 1019 of file sendcoinsdialog.cpp.
References countDownTimer, and updateYesButton().
Referenced by SendCoinsDialog::send().
updateYesButton
void SendConfirmationDialog::updateYesButton () private slot
Definition at line 1037 of file sendcoinsdialog.cpp.
References secDelay, and yesButton.
Referenced by countDown(), exec(), and SendConfirmationDialog().
Member Data Documentation
countDownTimer
QTimer SendConfirmationDialog::countDownTimer private
Definition at line 124 of file sendcoinsdialog.h.
Referenced by countDown(), exec(), and SendConfirmationDialog().
secDelay
int SendConfirmationDialog::secDelay private
Definition at line 125 of file sendcoinsdialog.h.
Referenced by countDown(), and updateYesButton().
yesButton
QAbstractButton* SendConfirmationDialog::yesButton private
Definition at line 123 of file sendcoinsdialog.h.
Referenced by SendConfirmationDialog(), and updateYesButton().
The documentation for this class was generated from the following files:
src/qt/sendcoinsdialog.h
src/qt/sendcoinsdialog.cpp
Released under the MIT license