Dash Core: CScriptNum Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CScriptNum Class Reference
#include <script.h>
Public Member Functions
CScriptNum (const int64_t &n)
Numeric opcodes (OP_1ADD, etc) are restricted to operating on 4-byte integers.
CScriptNum (const std::vector< unsigned char > &vch, bool fRequireMinimal, const size_t nMaxNumSize=nDefaultMaxNumSize)
bool operator== (const int64_t &rhs) const
bool operator!= (const int64_t &rhs) const
bool operator<= (const int64_t &rhs) const
bool operator< (const int64_t &rhs) const
bool operator>= (const int64_t &rhs) const
bool operator> (const int64_t &rhs) const
bool operator== (const CScriptNum &rhs) const
bool operator!= (const CScriptNum &rhs) const
bool operator<= (const CScriptNum &rhs) const
bool operator< (const CScriptNum &rhs) const
bool operator>= (const CScriptNum &rhs) const
bool operator> (const CScriptNum &rhs) const
CScriptNum operator+ (const int64_t &rhs) const
CScriptNum operator- (const int64_t &rhs) const
CScriptNum operator+ (const CScriptNum &rhs) const
CScriptNum operator- (const CScriptNum &rhs) const
CScriptNum & operator+= (const CScriptNum &rhs)
CScriptNum & operator-= (const CScriptNum &rhs)
CScriptNum operator & (const int64_t &rhs) const
CScriptNum operator & (const CScriptNum &rhs) const
CScriptNum & operator &= (const CScriptNum &rhs)
CScriptNum operator- () const
CScriptNum & operator= (const int64_t &rhs)
CScriptNum & operator+= (const int64_t &rhs)
CScriptNum & operator-= (const int64_t &rhs)
CScriptNum & operator &= (const int64_t &rhs)
int getint () const
std::vector< unsigned char > getvch () const
Static Public Member Functions
static std::vector< unsigned char > serialize (const int64_t &value)
Static Public Attributes
static const size_t nDefaultMaxNumSize = 4
Static Private Member Functions
static int64_t set_vch (const std::vector< unsigned char > &vch)
Private Attributes
int64_t m_value
Detailed Description
Definition at line 198 of file script.h.
Constructor & Destructor Documentation
CScriptNum() [1/2]
CScriptNum::CScriptNum (const int64_t & n) inline explicit
Numeric opcodes (OP_1ADD, etc) are restricted to operating on 4-byte integers.
The semantics are subtle, though: operands must be in the range [-2^31 +1...2^31 -1], but results may overflow (and are valid as long as they are not used in a subsequent numeric operation). CScriptNum enforces those semantics by storing results as an int64 and allowing out-of-range values to be returned as a vector of bytes but throwing an exception if arithmetic is done or the result is interpreted as an integer.
Definition at line 210 of file script.h.
References m_value.
Referenced by operator &(), operator+(), and operator-().
CScriptNum() [2/2]
CScriptNum::CScriptNum (const std::vector< unsigned char > & vch, bool fRequireMinimal, const size_t nMaxNumSize = nDefaultMaxNumSize) inline explicit
Definition at line 217 of file script.h.
References m_value, and set_vch().
Member Function Documentation
getint()
int CScriptNum::getint () const inline
Definition at line 305 of file script.h.
References m_value.
Referenced by EvalScript().
getvch()
std::vector<unsigned char> CScriptNum::getvch () const inline
Definition at line 314 of file script.h.
References m_value, and serialize().
Referenced by EvalScript(), and CScript::operator<<().
operator &() [1/2]
CScriptNum CScriptNum::operator& (const int64_t & rhs) const inline
Definition at line 266 of file script.h.
References CScriptNum(), and m_value.
Referenced by operator &().
operator &() [2/2]
CScriptNum CScriptNum::operator& (const CScriptNum & rhs) const inline
Definition at line 267 of file script.h.
References m_value, and operator &().
operator &=() [1/2]
CScriptNum& CScriptNum::operator&= (const CScriptNum & rhs) inline
Definition at line 269 of file script.h.
References m_value.
operator &=() [2/2]
CScriptNum& CScriptNum::operator&= (const int64_t & rhs) inline
Definition at line 299 of file script.h.
References m_value.
operator!=() [1/2]
bool CScriptNum::operator!= (const int64_t & rhs) const inline
Definition at line 245 of file script.h.
References m_value.
operator!=() [2/2]
bool CScriptNum::operator!= (const CScriptNum & rhs) const inline
Definition at line 252 of file script.h.
References m_value, and operator!=().
Referenced by operator!=().
operator+() [1/2]
CScriptNum CScriptNum::operator+ (const int64_t & rhs) const inline
Definition at line 258 of file script.h.
References CScriptNum(), and m_value.
operator+() [2/2]
CScriptNum CScriptNum::operator+ (const CScriptNum & rhs) const inline
Definition at line 260 of file script.h.
References m_value, and operator+().
Referenced by operator+().
operator+=() [1/2]
CScriptNum& CScriptNum::operator+= (const CScriptNum & rhs) inline
Definition at line 263 of file script.h.
References m_value, and operator+=().
Referenced by operator+=().
operator+=() [2/2]
CScriptNum& CScriptNum::operator+= (const int64_t & rhs) inline
Definition at line 283 of file script.h.
References m_value.
operator-() [1/3]
CScriptNum CScriptNum::operator- (const int64_t & rhs) const inline
Definition at line 259 of file script.h.
References CScriptNum(), and m_value.
operator-() [2/3]
CScriptNum CScriptNum::operator- (const CScriptNum & rhs) const inline
Definition at line 261 of file script.h.
References m_value, and operator-().
Referenced by operator-().
operator-() [3/3]
CScriptNum CScriptNum::operator- () const inline
Definition at line 271 of file script.h.
References CScriptNum(), and m_value.
operator-=() [1/2]
CScriptNum& CScriptNum::operator-= (const CScriptNum & rhs) inline
Definition at line 264 of file script.h.
References m_value, and operator-=().
Referenced by operator-=().
operator-=() [2/2]
CScriptNum& CScriptNum::operator-= (const int64_t & rhs) inline
Definition at line 291 of file script.h.
References m_value.
operator<() [1/2]
bool CScriptNum::operator< (const int64_t & rhs) const inline
Definition at line 247 of file script.h.
References m_value.
Referenced by operator<().
operator<() [2/2]
bool CScriptNum::operator< (const CScriptNum & rhs) const inline
Definition at line 254 of file script.h.
References m_value, and operator<().
operator<=() [1/2]
bool CScriptNum::operator<= (const int64_t & rhs) const inline
Definition at line 246 of file script.h.
References m_value.
operator<=() [2/2]
bool CScriptNum::operator<= (const CScriptNum & rhs) const inline
Definition at line 253 of file script.h.
References m_value, and operator<=().
Referenced by operator<=().
operator=()
CScriptNum& CScriptNum::operator= (const int64_t & rhs) inline
Definition at line 277 of file script.h.
References m_value.
operator==() [1/2]
bool CScriptNum::operator== (const int64_t & rhs) const inline
Definition at line 244 of file script.h.
References m_value.
operator==() [2/2]
bool CScriptNum::operator== (const CScriptNum & rhs) const inline
Definition at line 251 of file script.h.
References m_value, and operator==().
Referenced by operator==().
operator>() [1/2]
bool CScriptNum::operator> (const int64_t & rhs) const inline
Definition at line 249 of file script.h.
References m_value.
Referenced by operator>().
operator>() [2/2]
bool CScriptNum::operator> (const CScriptNum & rhs) const inline
Definition at line 256 of file script.h.
References m_value, and operator>().
operator>=() [1/2]
bool CScriptNum::operator>= (const int64_t & rhs) const inline
Definition at line 248 of file script.h.
References m_value.
operator>=() [2/2]
bool CScriptNum::operator>= (const CScriptNum & rhs) const inline
Definition at line 255 of file script.h.
References m_value, and operator>=().
Referenced by operator>=().
serialize()
static std::vector<unsigned char> CScriptNum::serialize (const int64_t & value) inline static
Definition at line 319 of file script.h.
Referenced by getvch(), and CScript::push_int64().
set_vch()
static int64_t CScriptNum::set_vch (const std::vector< unsigned char > & vch) inline static private
Definition at line 353 of file script.h.
Referenced by CScriptNum().
Member Data Documentation
m_value
int64_t CScriptNum::m_value private
Definition at line 370 of file script.h.
Referenced by CScriptNum(), getint(), getvch(), operator &(), operator &=(), operator!=(), operator+(), operator+=(), operator-(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), and operator>=().
nDefaultMaxNumSize
const size_t CScriptNum::nDefaultMaxNumSize = 4 static
Definition at line 215 of file script.h.
The documentation for this class was generated from the following file:
src/script/script.h
Released under the MIT license