Dash Core: UnitDisplayStatusBarControl Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
UnitDisplayStatusBarControl Class Reference
#include <bitcoingui.h>
Public Member Functions
UnitDisplayStatusBarControl ()
void setOptionsModel (OptionsModel *optionsModel)
Lets the control know about the Options Model (and its signals)
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
So that it responds to left-button clicks.
Private Slots
void updateDisplayUnit (int newUnits)
When Display Units are changed on OptionsModel it will refresh the display text of the control on the status bar.
void onMenuSelection (QAction *action)
Tells underlying optionsModel to update its current display unit.
Private Member Functions
void onDisplayUnitsClicked (const QPoint &point)
Shows context menu with Display Unit options by the mouse coordinates.
void createContextMenu ()
Creates context menu, its actions, and wires up all the relevant signals for mouse events.
Private Attributes
OptionsModel * optionsModel
QMenu * menu
Detailed Description
Definition at line 329 of file bitcoingui.h.
Constructor & Destructor Documentation
UnitDisplayStatusBarControl()
UnitDisplayStatusBarControl::UnitDisplayStatusBarControl () explicit
Definition at line 1820 of file bitcoingui.cpp.
References BitcoinUnits::availableUnits(), createContextMenu(), GUIUtil::getFontNormal(), and BitcoinUnits::name().
Member Function Documentation
createContextMenu()
void UnitDisplayStatusBarControl::createContextMenu () private
Creates context menu, its actions, and wires up all the relevant signals for mouse events.
Definition at line 1844 of file bitcoingui.cpp.
References BitcoinUnits::availableUnits(), menu, BitcoinUnits::name(), and onMenuSelection().
Referenced by UnitDisplayStatusBarControl().
mousePressEvent()
void UnitDisplayStatusBarControl::mousePressEvent (QMouseEvent * event) protected
So that it responds to left-button clicks.
So that it responds to button clicks.
Definition at line 1838 of file bitcoingui.cpp.
References onDisplayUnitsClicked().
onDisplayUnitsClicked()
void UnitDisplayStatusBarControl::onDisplayUnitsClicked (const QPoint & point) private
Shows context menu with Display Unit options by the mouse coordinates.
Definition at line 1878 of file bitcoingui.cpp.
References menu.
Referenced by mousePressEvent().
onMenuSelection
void UnitDisplayStatusBarControl::onMenuSelection (QAction * action) private slot
Tells underlying optionsModel to update its current display unit.
Definition at line 1885 of file bitcoingui.cpp.
References optionsModel, and OptionsModel::setDisplayUnit().
Referenced by createContextMenu().
setOptionsModel()
void UnitDisplayStatusBarControl::setOptionsModel (OptionsModel * optionsModel)
Lets the control know about the Options Model (and its signals)
Definition at line 1857 of file bitcoingui.cpp.
References OptionsModel::getDisplayUnit(), optionsModel, and updateDisplayUnit().
Referenced by BitcoinGUI::setClientModel().
updateDisplayUnit
void UnitDisplayStatusBarControl::updateDisplayUnit (int newUnits) private slot
When Display Units are changed on OptionsModel it will refresh the display text of the control on the status bar.
Definition at line 1872 of file bitcoingui.cpp.
References BitcoinUnits::name().
Referenced by setOptionsModel().
Member Data Documentation
menu
QMenu* UnitDisplayStatusBarControl::menu private
Definition at line 344 of file bitcoingui.h.
Referenced by createContextMenu(), and onDisplayUnitsClicked().
optionsModel
OptionsModel* UnitDisplayStatusBarControl::optionsModel private
Definition at line 343 of file bitcoingui.h.
Referenced by onMenuSelection(), and setOptionsModel().
The documentation for this class was generated from the following files:
src/qt/bitcoingui.h
src/qt/bitcoingui.cpp
Released under the MIT license