Dash Core: CGovernanceObject Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CGovernanceObject Class Reference abstract
Governance Object.
#include <governance-classes.h>
Public Types
typedef std::map< COutPoint, vote_rec_t > vote_m_t
typedef vote_m_t::iterator vote_m_it
typedef vote_m_t::const_iterator vote_m_cit
typedef CacheMultiMap< COutPoint, vote_time_pair_t > vote_mcache_t
Public Member Functions
virtual uint256 GetHash ()=0
CGovernanceObject ()
CGovernanceObject (uint256 nHashParentIn, int nRevisionIn, int64_t nTime, uint256 nCollateralHashIn, std::string strDataIn)
CGovernanceObject (const CGovernanceObject &other)
void swap (CGovernanceObject &first, CGovernanceObject &second)
int64_t GetCreationTime () const
int64_t GetDeletionTime () const
int GetObjectType () const
const uint256 & GetCollateralHash () const
const CTxIn & GetMasternodeVin () const
bool IsSetCachedFunding () const
bool IsSetCachedValid () const
bool IsSetCachedDelete () const
bool IsSetCachedEndorsed () const
bool IsSetDirtyCache () const
bool IsSetExpired () const
void InvalidateVoteCache ()
CGovernanceObjectVoteFile & GetVoteFile ()
void SetMasternodeVin (const COutPoint &outpoint)
bool Sign (CKey &keyMasternode, CPubKey &pubKeyMasternode)
bool CheckSignature (CPubKey &pubKeyMasternode)
std::string GetSignatureMessage () const
bool IsValidLocally (std::string &strError, bool fCheckCollateral)
bool IsValidLocally (std::string &strError, bool &fMissingMasternode, bool &fMissingConfirmations, bool fCheckCollateral)
bool IsCollateralValid (std::string &strError, bool &fMissingConfirmations)
Check the collateral transaction for the budget proposal/finalized budget.
void UpdateLocalValidity ()
void UpdateSentinelVariables ()
int GetObjectSubtype ()
CAmount GetMinCollateralFee ()
UniValue GetJSONObject ()
Return the actual object from the strData JSON structure.
void Relay (CConnman &connman)
uint256 GetHash () const
int CountMatchingVotes (vote_signal_enum_t eVoteSignalIn, vote_outcome_enum_t eVoteOutcomeIn) const
int GetAbsoluteYesCount (vote_signal_enum_t eVoteSignalIn) const
Get specific vote counts for each outcome (funding, validity, etc)
int GetAbsoluteNoCount (vote_signal_enum_t eVoteSignalIn) const
int GetYesCount (vote_signal_enum_t eVoteSignalIn) const
int GetNoCount (vote_signal_enum_t eVoteSignalIn) const
int GetAbstainCount (vote_signal_enum_t eVoteSignalIn) const
bool GetCurrentMNVotes (const COutPoint &mnCollateralOutpoint, vote_rec_t &voteRecord)
std::string GetDataAsHex ()
GetData - As
std::string GetDataAsString ()
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
CGovernanceObject & operator= (CGovernanceObject from)
Public Attributes
ADD_SERIALIZE_METHODS
Private Member Functions
void LoadData ()
LoadData
void GetData (UniValue &objResult)
GetData - Example usage:
bool ProcessVote (CNode *pfrom, const CGovernanceVote &vote, CGovernanceException &exception, CConnman &connman)
void ClearMasternodeVotes ()
Called when MN's which have voted on this object have been removed.
void CheckOrphanVotes (CConnman &connman)
Private Attributes
int nLevel
std::string strCategory
int nStatusID
std::string strStatusMessage
uint64_t nTimeValueOverrideCached
CCriticalSection cs
critical section to protect the inner data structures
int nObjectType
Object typecode.
uint256 nHashParent
parent object, 0 is root
int nRevision
object revision in the system
int64_t nTime
time this object was created
int64_t nDeletionTime
time this object was marked for deletion
uint256 nCollateralHash
fee-tx
std::string strData
Data field - can be used for anything.
CTxIn vinMasternode
Masternode info for signed objects.
std::vector< unsigned char > vchSig
bool fCachedLocalValidity
is valid by blockchain
std::string strLocalValidityError
bool fCachedFunding
true == minimum network support has been reached for this object to be funded (doesn't mean it will for sure though)
bool fCachedValid
true == minimum network has been reached flagging this object as a valid and understood governance object (e.g, the serialized data is correct format, etc)
bool fCachedDelete
true == minimum network support has been reached saying this object should be deleted from the system entirely
bool fCachedEndorsed
true == minimum network support has been reached flagging this object as endorsed by an elected representative body (e.g.
bool fDirtyCache
object was updated and cached values should be updated soon
bool fExpired
Object is no longer of interest.
bool fUnparsable
Failed to parse object data.
vote_m_t mapCurrentMNVotes
vote_mcache_t mapOrphanVotes
Limited map of votes orphaned by MN.
CGovernanceObjectVoteFile fileVotes
Friends
class CGovernanceManager
class CGovernanceTriggerManager
Detailed Description
Governance Object.
Definition at line 113 of file governance-classes.h.
Member Typedef Documentation
vote_m_cit
typedef vote_m_t::const_iterator CGovernanceObject::vote_m_cit
Definition at line 123 of file governance-object.h.
vote_m_it
typedef vote_m_t::iterator CGovernanceObject::vote_m_it
Definition at line 121 of file governance-object.h.
vote_m_t
typedef std::map<COutPoint, vote_rec_t> CGovernanceObject::vote_m_t
Definition at line 119 of file governance-object.h.
vote_mcache_t
typedef CacheMultiMap<COutPoint, vote_time_pair_t> CGovernanceObject::vote_mcache_t
Definition at line 125 of file governance-object.h.
Constructor & Destructor Documentation
CGovernanceObject() [1/3]
CGovernanceObject::CGovernanceObject ()
Definition at line 18 of file governance-object.cpp.
References LoadData().
CGovernanceObject() [2/3]
CGovernanceObject::CGovernanceObject (uint256 nHashParentIn, int nRevisionIn, int64_t nTime, uint256 nCollateralHashIn, std::string strDataIn)
Definition at line 46 of file governance-object.cpp.
References LoadData().
CGovernanceObject() [3/3]
CGovernanceObject::CGovernanceObject (const CGovernanceObject & other)
Definition at line 74 of file governance-object.cpp.
Member Function Documentation
CheckOrphanVotes()
void CGovernanceObject::CheckOrphanVotes (CConnman & connman) private
Definition at line 726 of file governance-object.cpp.
References CacheMultiMap< K, V, Size >::Erase(), GetAdjustedTime(), CacheMultiMap< K, V, Size >::GetItemList(), CGovernanceVote::GetMasternodeOutpoint(), CMasternodeMan::Has(), LogPrintf, mapOrphanVotes, mnodeman, ProcessVote(), CGovernanceVote::Relay(), and CGovernanceException::what().
CheckSignature()
bool CGovernanceObject::CheckSignature (CPubKey & pubKeyMasternode)
Definition at line 256 of file governance-object.cpp.
References cs, GetSignatureMessage(), LOCK, LogPrintf, vchSig, and CMessageSigner::VerifyMessage().
Referenced by IsValidLocally().
ClearMasternodeVotes()
void CGovernanceObject::ClearMasternodeVotes () private
Called when MN's which have voted on this object have been removed.
Definition at line 200 of file governance-object.cpp.
References fileVotes, CMasternodeMan::Has(), mapCurrentMNVotes, mnodeman, and CGovernanceObjectVoteFile::RemoveVotesFromMasternode().
CountMatchingVotes()
int CGovernanceObject::CountMatchingVotes (vote_signal_enum_t eVoteSignalIn, vote_outcome_enum_t eVoteOutcomeIn) const
Definition at line 597 of file governance-object.cpp.
References vote_instance_t::eOutcome, mapCurrentMNVotes, and vote_rec_t::mapInstances.
Referenced by GetAbstainCount(), GetNoCount(), and GetYesCount().
GetAbsoluteNoCount()
int CGovernanceObject::GetAbsoluteNoCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 623 of file governance-object.cpp.
References GetNoCount(), and GetYesCount().
Referenced by UpdateSentinelVariables().
GetAbsoluteYesCount()
int CGovernanceObject::GetAbsoluteYesCount (vote_signal_enum_t eVoteSignalIn) const
Get specific vote counts for each outcome (funding, validity, etc)
Definition at line 618 of file governance-object.cpp.
References GetNoCount(), and GetYesCount().
Referenced by CSuperblockManager::GetBestSuperblock(), gobject(), and UpdateSentinelVariables().
GetAbstainCount()
int CGovernanceObject::GetAbstainCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 638 of file governance-object.cpp.
References CountMatchingVotes(), and VOTE_OUTCOME_ABSTAIN.
Referenced by gobject().
GetCollateralHash()
const uint256& CGovernanceObject::GetCollateralHash () const inline
Definition at line 215 of file governance-object.h.
References nCollateralHash.
Referenced by gobject().
GetCreationTime()
int64_t CGovernanceObject::GetCreationTime () const inline
Definition at line 203 of file governance-object.h.
References nTime.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceManager::CheckPostponedObjects(), gobject(), CGovernanceManager::MasternodeRateCheck(), CGovernanceManager::MasternodeRateUpdate(), CGovernanceManager::UpdateCachesAndClean(), and CGovernanceManager::UpdateCurrentWatchdog().
GetCurrentMNVotes()
bool CGovernanceObject::GetCurrentMNVotes (const COutPoint & mnCollateralOutpoint, vote_rec_t & voteRecord)
Definition at line 643 of file governance-object.cpp.
References mapCurrentMNVotes.
Referenced by CGovernanceManager::GetCurrentVotes().
GetData()
void CGovernanceObject::GetData (UniValue & objResult) private
GetData - Example usage:
Decode governance object data into UniValue(VOBJ)
Definition at line 377 of file governance-object.cpp.
References GetDataAsString(), UniValue::read(), and UniValue::VOBJ.
Referenced by GetJSONObject(), and LoadData().
GetDataAsHex()
std::string CGovernanceObject::GetDataAsHex ()
GetData - As
Definition at line 391 of file governance-object.cpp.
References strData.
Referenced by gobject(), and CSuperblock::IsValid().
GetDataAsString()
std::string CGovernanceObject::GetDataAsString ()
Definition at line 396 of file governance-object.cpp.
References ParseHex(), and strData.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceTriggerManager::CleanAndRemove(), CGovernanceTriggerManager::GetActiveTriggers(), GetData(), gobject(), CSuperblockManager::IsSuperblockTriggered(), and LoadData().
GetDeletionTime()
int64_t CGovernanceObject::GetDeletionTime () const inline
Definition at line 207 of file governance-object.h.
References nDeletionTime.
Referenced by CGovernanceManager::UpdateCachesAndClean().
GetHash() [1/2]
virtual uint256 CGovernanceObject::GetHash () pure virtual
Implemented in CDashNetwork.
Referenced by CGovernanceManager::AddCachedTriggers(), CGovernanceManager::AddGovernanceObject(), CGovernanceManager::AddPostponedObject(), CGovernanceManager::CheckOrphanVotes(), CGovernanceManager::CheckPostponedObjects(), CGovernanceTriggerManager::CleanAndRemove(), gobject(), IsCollateralValid(), CGovernanceManager::MasternodeRateCheck(), CGovernanceManager::MasternodeRateUpdate(), ProcessVote(), Relay(), SerializationOp(), CGovernanceManager::UpdateCachesAndClean(), and CGovernanceManager::UpdateCurrentWatchdog().
GetHash() [2/2]
uint256 CGovernanceObject::GetHash () const
Definition at line 280 of file governance-object.cpp.
References DBG, CHashWriter::GetHash(), nHashParent, nRevision, nTime, PROTOCOL_VERSION, SER_GETHASH, strData, vchSig, and vinMasternode.
GetJSONObject()
UniValue CGovernanceObject::GetJSONObject ()
Return the actual object from the strData JSON structure.
Returns an empty object on error.
Definition at line 304 of file governance-object.cpp.
References GetData(), UniValue::getValues(), strData, and UniValue::VOBJ.
Referenced by LoadData().
GetMasternodeVin()
const CTxIn& CGovernanceObject::GetMasternodeVin () const inline
Definition at line 219 of file governance-object.h.
References vinMasternode.
Referenced by CGovernanceManager::CheckMasternodeOrphanObjects(), gobject(), CGovernanceManager::MasternodeRateCheck(), and CGovernanceManager::MasternodeRateUpdate().
GetMinCollateralFee()
CAmount CGovernanceObject::GetMinCollateralFee ()
Definition at line 492 of file governance-object.cpp.
References GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, GOVERNANCE_OBJECT_WATCHDOG, GOVERNANCE_PROPOSAL_FEE_TX, MAX_MONEY, and nObjectType.
Referenced by gobject(), and IsCollateralValid().
GetNoCount()
int CGovernanceObject::GetNoCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 633 of file governance-object.cpp.
References CountMatchingVotes(), and VOTE_OUTCOME_NO.
Referenced by GetAbsoluteNoCount(), GetAbsoluteYesCount(), and gobject().
GetObjectSubtype()
int CGovernanceObject::GetObjectSubtype ()
Definition at line 271 of file governance-object.cpp.
References GOVERNANCE_OBJECT_TRIGGER, nObjectType, and TRIGGER_SUPERBLOCK.
GetObjectType()
int CGovernanceObject::GetObjectType () const inline
Definition at line 211 of file governance-object.h.
References nObjectType.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceManager::CheckPostponedObjects(), CGovernanceTriggerManager::CleanAndRemove(), gobject(), CGovernanceManager::MasternodeRateCheck(), CGovernanceManager::MasternodeRateUpdate(), CGovernanceManager::ProcessVote(), and CGovernanceManager::UpdateCachesAndClean().
GetSignatureMessage()
std::string CGovernanceObject::GetSignatureMessage () const
Definition at line 214 of file governance-object.cpp.
References cs, LOCK, nCollateralHash, nHashParent, nRevision, nTime, CTxIn::prevout, strData, base_blob< BITS >::ToString(), COutPoint::ToStringShort(), and vinMasternode.
Referenced by CheckSignature(), and Sign().
GetVoteFile()
CGovernanceObjectVoteFile& CGovernanceObject::GetVoteFile () inline
Definition at line 251 of file governance-object.h.
References fileVotes.
Referenced by CGovernanceManager::GetMatchingVotes(), CGovernanceManager::HaveVoteForHash(), CGovernanceManager::RebuildIndexes(), CGovernanceManager::RequestGovernanceObject(), CGovernanceManager::SerializeVoteForHash(), and CGovernanceManager::Sync().
GetYesCount()
int CGovernanceObject::GetYesCount (vote_signal_enum_t eVoteSignalIn) const
Definition at line 628 of file governance-object.cpp.
References CountMatchingVotes(), and VOTE_OUTCOME_YES.
Referenced by GetAbsoluteNoCount(), GetAbsoluteYesCount(), and gobject().
InvalidateVoteCache()
void CGovernanceObject::InvalidateVoteCache () inline
Definition at line 247 of file governance-object.h.
References fDirtyCache.
IsCollateralValid()
bool CGovernanceObject::IsCollateralValid (std::string & strError, bool & fMissingConfirmations)
Check the collateral transaction for the budget proposal/finalized budget.
Definition at line 503 of file governance-object.cpp.
References AssertLockHeld, chainActive, CChain::Contains(), cs_main, DBG, CInstantSend::GetConfirmations(), GetHash(), GetMinCollateralFee(), GetTransaction(), GOVERNANCE_FEE_CONFIRMATIONS, GOVERNANCE_MIN_RELAY_FEE_CONFIRMATIONS, CChain::Height(), instantsend, CScript::IsPayToPublicKeyHash(), CScript::IsUnspendable(), LogPrintf, mapBlockIndex, nCollateralHash, CBlockIndex::nHeight, CTxOut::nValue, OP_RETURN, Params(), CTxOut::scriptPubKey, ScriptToAsmStr(), strprintf, ToByteVector(), base_blob< BITS >::ToString(), CTxOut::ToString(), CTransaction::ToString(), and CTransaction::vout.
Referenced by CGovernanceManager::CheckPostponedObjects(), and IsValidLocally().
IsSetCachedDelete()
bool CGovernanceObject::IsSetCachedDelete () const inline
Definition at line 231 of file governance-object.h.
References fCachedDelete.
Referenced by gobject(), CGovernanceManager::ProcessVote(), CGovernanceManager::Sync(), and CGovernanceManager::UpdateCachesAndClean().
IsSetCachedEndorsed()
bool CGovernanceObject::IsSetCachedEndorsed () const inline
Definition at line 235 of file governance-object.h.
References fCachedEndorsed.
Referenced by gobject().
IsSetCachedFunding()
bool CGovernanceObject::IsSetCachedFunding () const inline
Definition at line 223 of file governance-object.h.
References fCachedFunding.
Referenced by gobject(), and CSuperblockManager::IsSuperblockTriggered().
IsSetCachedValid()
bool CGovernanceObject::IsSetCachedValid () const inline
Definition at line 227 of file governance-object.h.
References fCachedValid.
Referenced by gobject().
IsSetDirtyCache()
bool CGovernanceObject::IsSetDirtyCache () const inline
Definition at line 239 of file governance-object.h.
References fDirtyCache.
Referenced by CGovernanceManager::UpdateCachesAndClean().
IsSetExpired()
bool CGovernanceObject::IsSetExpired () const inline
Definition at line 243 of file governance-object.h.
References fExpired.
Referenced by CGovernanceManager::ProcessVote(), CGovernanceManager::Sync(), and CGovernanceManager::UpdateCachesAndClean().
IsValidLocally() [1/2]
bool CGovernanceObject::IsValidLocally (std::string & strError, bool fCheckCollateral)
Definition at line 412 of file governance-object.cpp.
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceManager::CheckMasternodeOrphanObjects(), CGovernanceManager::CheckPostponedObjects(), gobject(), and UpdateLocalValidity().
IsValidLocally() [2/2]
bool CGovernanceObject::IsValidLocally (std::string & strError, bool & fMissingMasternode, bool & fMissingConfirmations, bool fCheckCollateral)
Definition at line 420 of file governance-object.cpp.
References CMasternode::CheckCollateral(), CheckSignature(), CMasternode::COLLATERAL_INVALID_AMOUNT, CMasternode::COLLATERAL_OK, CMasternode::COLLATERAL_UTXO_NOT_FOUND, fUnparsable, CPubKey::GetID(), CMasternodeMan::GetMasternodeInfo(), GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, GOVERNANCE_OBJECT_WATCHDOG, IsCollateralValid(), mnodeman, nObjectType, CTxIn::prevout, masternode_info_t::pubKeyMasternode, strprintf, base_blob< BITS >::ToString(), COutPoint::ToStringShort(), and vinMasternode.
LoadData()
void CGovernanceObject::LoadData () private
LoadData
Attempt to load data from strData
Definition at line 329 of file governance-object.cpp.
References DBG, fUnparsable, GetData(), GetDataAsString(), GetJSONObject(), LogPrintf, nObjectType, strData, and UniValue::VOBJ.
Referenced by CGovernanceObject().
operator=()
CGovernanceObject& CGovernanceObject::operator= (CGovernanceObject from) inline
Definition at line 333 of file governance-object.h.
References swap().
ProcessVote()
bool CGovernanceObject::ProcessVote (CNode * pfrom, const CGovernanceVote & vote, CGovernanceException & exception, CConnman & connman) private
Definition at line 99 of file governance-object.cpp.
References CMasternodeMan::AddGovernanceVote(), CGovernanceManager::AddInvalidVote(), CGovernanceObjectVoteFile::AddVote(), CGovernanceManager::AreRateChecksEnabled(), CMasternodeMan::AskForMN(), CGovernanceVoting::ConvertSignalToString(), fDirtyCache, fileVotes, GetAdjustedTime(), GetHash(), CGovernanceVote::GetHash(), CGovernanceVote::GetMasternodeOutpoint(), CGovernanceVote::GetOutcome(), CGovernanceVote::GetParentHash(), CGovernanceVote::GetSignal(), CGovernanceVote::GetTimestamp(), governance, GOVERNANCE_EXCEPTION_NONE, GOVERNANCE_EXCEPTION_PERMANENT_ERROR, GOVERNANCE_EXCEPTION_TEMPORARY_ERROR, GOVERNANCE_EXCEPTION_WARNING, GOVERNANCE_ORPHAN_EXPIRATION_TIME, GOVERNANCE_UPDATE_MIN, CMasternodeMan::Has(), CGovernanceObjectVoteFile::HasVote(), CacheMultiMap< K, V, Size >::Insert(), CGovernanceVote::IsValid(), LogPrint(), LogPrintf, mapCurrentMNVotes, vote_rec_t::mapInstances, mapOrphanVotes, MAX_SUPPORTED_VOTE_SIGNAL, mnodeman, vote_instance_t::nCreationTime, vote_instance_t::nTime, base_blob< BITS >::ToString(), COutPoint::ToStringShort(), and VOTE_SIGNAL_NONE.
Referenced by CheckOrphanVotes(), CGovernanceManager::CheckOrphanVotes(), and CGovernanceManager::ProcessVote().
Relay()
void CGovernanceObject::Relay (CConnman & connman)
Definition at line 653 of file governance-object.cpp.
References GetHash(), CMasternodeSync::IsSynced(), LogPrint(), masternodeSync, MIN_GOVERNANCE_PEER_PROTO_VERSION, MSG_GOVERNANCE_OBJECT, and CConnman::RelayInv().
Referenced by CGovernanceManager::AddGovernanceObject(), CGovernanceManager::CheckPostponedObjects(), and gobject().
SerializationOp()
template<typename Stream , typename Operation > void CGovernanceObject::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 308 of file governance-object.h.
References fExpired, fileVotes, GetHash(), CGovernanceObjectVoteFile::GetVoteCount(), LIMITED_STRING, LogPrint(), mapCurrentMNVotes, MAX_GOVERNANCE_OBJECT_DATA_SIZE, nCollateralHash, nDeletionTime, nHashParent, nObjectType, nRevision, nTime, READWRITE, SER_DISK, strData, vchSig, and vinMasternode.
SetMasternodeVin()
void CGovernanceObject::SetMasternodeVin (const COutPoint & outpoint)
Definition at line 227 of file governance-object.cpp.
References vinMasternode.
Referenced by gobject().
Sign()
bool CGovernanceObject::Sign (CKey & keyMasternode, CPubKey & pubKeyMasternode)
Definition at line 232 of file governance-object.cpp.
References cs, CPubKey::GetID(), GetSignatureMessage(), LOCK, LogPrint(), LogPrintf, CTxIn::prevout, CMessageSigner::SignMessage(), base_blob< BITS >::ToString(), COutPoint::ToStringShort(), vchSig, CMessageSigner::VerifyMessage(), and vinMasternode.
Referenced by gobject().
swap()
void CGovernanceObject::swap (CGovernanceObject & first, CGovernanceObject & second)
Definition at line 702 of file governance-object.cpp.
References fCachedDelete, fCachedEndorsed, fCachedFunding, fCachedValid, fDirtyCache, fExpired, nCollateralHash, nDeletionTime, nHashParent, nObjectType, nRevision, nTime, and strData.
Referenced by operator=().
UpdateLocalValidity()
void CGovernanceObject::UpdateLocalValidity ()
Definition at line 404 of file governance-object.cpp.
References cs_main, fCachedLocalValidity, IsValidLocally(), LOCK, and strLocalValidityError.
Referenced by CGovernanceManager::UpdateCachesAndClean().
UpdateSentinelVariables()
void CGovernanceObject::UpdateSentinelVariables ()
Definition at line 665 of file governance-object.cpp.
References CMasternodeMan::CountEnabled(), fCachedDelete, fCachedEndorsed, fCachedFunding, fCachedValid, fDirtyCache, GetAbsoluteNoCount(), GetAbsoluteYesCount(), GetAdjustedTime(), mnodeman, nDeletionTime, Params(), VOTE_SIGNAL_DELETE, VOTE_SIGNAL_ENDORSED, VOTE_SIGNAL_FUNDING, and VOTE_SIGNAL_VALID.
Referenced by CGovernanceManager::AddGovernanceObject(), CSuperblockManager::IsSuperblockTriggered(), and CGovernanceManager::UpdateCachesAndClean().
Friends And Related Function Documentation
CGovernanceManager
friend class CGovernanceManager friend
Definition at line 114 of file governance-object.h.
CGovernanceTriggerManager
friend class CGovernanceTriggerManager friend
Definition at line 116 of file governance-object.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CGovernanceObject::ADD_SERIALIZE_METHODS
Definition at line 305 of file governance-object.h.
cs
CCriticalSection CGovernanceObject::cs mutable private
critical section to protect the inner data structures
Definition at line 129 of file governance-object.h.
Referenced by CheckSignature(), GetSignatureMessage(), and Sign().
fCachedDelete
bool CGovernanceObject::fCachedDelete private
true == minimum network support has been reached saying this object should be deleted from the system entirely
Definition at line 169 of file governance-object.h.
Referenced by IsSetCachedDelete(), swap(), and UpdateSentinelVariables().
fCachedEndorsed
bool CGovernanceObject::fCachedEndorsed private
true == minimum network support has been reached flagging this object as endorsed by an elected representative body (e.g.
business review board / technecial review board /etc)
Definition at line 174 of file governance-object.h.
Referenced by IsSetCachedEndorsed(), swap(), and UpdateSentinelVariables().
fCachedFunding
bool CGovernanceObject::fCachedFunding private
true == minimum network support has been reached for this object to be funded (doesn't mean it will for sure though)
Definition at line 163 of file governance-object.h.
Referenced by IsSetCachedFunding(), swap(), and UpdateSentinelVariables().
fCachedLocalValidity
bool CGovernanceObject::fCachedLocalValidity private
is valid by blockchain
Definition at line 157 of file governance-object.h.
Referenced by UpdateLocalValidity().
fCachedValid
bool CGovernanceObject::fCachedValid private
true == minimum network has been reached flagging this object as a valid and understood governance object (e.g, the serialized data is correct format, etc)
Definition at line 166 of file governance-object.h.
Referenced by IsSetCachedValid(), swap(), and UpdateSentinelVariables().
fDirtyCache
bool CGovernanceObject::fDirtyCache private
object was updated and cached values should be updated soon
Definition at line 177 of file governance-object.h.
Referenced by InvalidateVoteCache(), IsSetDirtyCache(), ProcessVote(), swap(), and UpdateSentinelVariables().
fExpired
bool CGovernanceObject::fExpired private
Object is no longer of interest.
Definition at line 180 of file governance-object.h.
Referenced by CGovernanceTriggerManager::CleanAndRemove(), IsSetExpired(), SerializationOp(), and swap().
fileVotes
CGovernanceObjectVoteFile CGovernanceObject::fileVotes private
Definition at line 190 of file governance-object.h.
Referenced by ClearMasternodeVotes(), GetVoteFile(), ProcessVote(), and SerializationOp().
fUnparsable
bool CGovernanceObject::fUnparsable private
Failed to parse object data.
Definition at line 183 of file governance-object.h.
Referenced by IsValidLocally(), and LoadData().
mapCurrentMNVotes
vote_m_t CGovernanceObject::mapCurrentMNVotes private
Definition at line 185 of file governance-object.h.
Referenced by ClearMasternodeVotes(), CountMatchingVotes(), GetCurrentMNVotes(), ProcessVote(), and SerializationOp().
mapOrphanVotes
vote_mcache_t CGovernanceObject::mapOrphanVotes private
Limited map of votes orphaned by MN.
Definition at line 188 of file governance-object.h.
Referenced by CheckOrphanVotes(), and ProcessVote().
nCollateralHash
uint256 CGovernanceObject::nCollateralHash private
fee-tx
Definition at line 147 of file governance-object.h.
Referenced by GetCollateralHash(), GetSignatureMessage(), IsCollateralValid(), CDashNetwork::SerializationOp(), SerializationOp(), and swap().
nDeletionTime
int64_t CGovernanceObject::nDeletionTime private
time this object was marked for deletion
Definition at line 144 of file governance-object.h.
Referenced by CGovernanceTriggerManager::CleanAndRemove(), GetDeletionTime(), SerializationOp(), swap(), and UpdateSentinelVariables().
nHashParent
uint256 CGovernanceObject::nHashParent private
parent object, 0 is root
Definition at line 135 of file governance-object.h.
Referenced by GetHash(), GetSignatureMessage(), SerializationOp(), and swap().
nLevel
int CGovernanceObject::nLevel private
Definition at line 117 of file governance-classes.h.
nObjectType
int CGovernanceObject::nObjectType private
Object typecode.
Definition at line 132 of file governance-object.h.
Referenced by CGovernanceManager::AddCachedTriggers(), CGovernanceManager::AddGovernanceObject(), GetMinCollateralFee(), GetObjectSubtype(), GetObjectType(), IsValidLocally(), LoadData(), SerializationOp(), and swap().
nRevision
int CGovernanceObject::nRevision private
object revision in the system
Definition at line 138 of file governance-object.h.
Referenced by GetHash(), GetSignatureMessage(), SerializationOp(), and swap().
nStatusID
int CGovernanceObject::nStatusID private
Definition at line 121 of file governance-classes.h.
nTime
int64_t CGovernanceObject::nTime private
time this object was created
Definition at line 141 of file governance-object.h.
Referenced by GetCreationTime(), CDashNetwork::GetHash(), GetHash(), GetSignatureMessage(), CDashNetwork::SerializationOp(), SerializationOp(), and swap().
nTimeValueOverrideCached
uint64_t CGovernanceObject::nTimeValueOverrideCached private
Definition at line 125 of file governance-classes.h.
strCategory
std::string CGovernanceObject::strCategory private
Definition at line 118 of file governance-classes.h.
strData
std::string CGovernanceObject::strData private
Data field - can be used for anything.
Definition at line 150 of file governance-object.h.
Referenced by GetDataAsHex(), GetDataAsString(), GetHash(), GetJSONObject(), GetSignatureMessage(), LoadData(), SerializationOp(), and swap().
strLocalValidityError
std::string CGovernanceObject::strLocalValidityError private
Definition at line 158 of file governance-object.h.
Referenced by UpdateLocalValidity().
strStatusMessage
std::string CGovernanceObject::strStatusMessage private
Definition at line 122 of file governance-classes.h.
vchSig
std::vector<unsigned char> CGovernanceObject::vchSig private
Definition at line 154 of file governance-object.h.
Referenced by CheckSignature(), GetHash(), SerializationOp(), and Sign().
vinMasternode
CTxIn CGovernanceObject::vinMasternode private
Masternode info for signed objects.
Definition at line 153 of file governance-object.h.
Referenced by GetHash(), GetMasternodeVin(), GetSignatureMessage(), IsValidLocally(), SerializationOp(), SetMasternodeVin(), and Sign().
The documentation for this class was generated from the following files:
src/drafted/governance-classes.h
src/governance-object.h
src/governance-object.cpp
Released under the MIT license