Dash Core: CMasternodeSync Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CMasternodeSync Class Reference
#include <masternode-sync.h>
Public Member Functions
CMasternodeSync ()
void SendGovernanceSyncRequest (CNode *pnode, CConnman &connman)
bool IsFailed ()
bool IsBlockchainSynced ()
bool IsMasternodeListSynced ()
bool IsWinnersListSynced ()
bool IsSynced ()
int GetAssetID ()
int GetAttempt ()
void BumpAssetLastTime (std::string strFuncName)
int64_t GetAssetStartTime ()
std::string GetAssetName ()
std::string GetSyncStatus ()
void Reset ()
void SwitchToNextAsset (CConnman &connman)
void ProcessMessage (CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
void ProcessTick (CConnman &connman)
void AcceptedBlockHeader (const CBlockIndex *pindexNew)
void NotifyHeaderTip (const CBlockIndex *pindexNew, bool fInitialDownload, CConnman &connman)
void UpdatedBlockTip (const CBlockIndex *pindexNew, bool fInitialDownload, CConnman &connman)
Private Member Functions
void Fail ()
void ClearFulfilledRequests (CConnman &connman)
Private Attributes
int nRequestedMasternodeAssets
int nRequestedMasternodeAttempt
int64_t nTimeAssetSyncStarted
int64_t nTimeLastBumped
int64_t nTimeLastFailure
Detailed Description
Definition at line 35 of file masternode-sync.h.
Constructor & Destructor Documentation
CMasternodeSync()
CMasternodeSync::CMasternodeSync () inline
Definition at line 54 of file masternode-sync.h.
References Reset().
Member Function Documentation
AcceptedBlockHeader()
void CMasternodeSync::AcceptedBlockHeader (const CBlockIndex * pindexNew)
Definition at line 415 of file masternode-sync.cpp.
References BumpAssetLastTime(), IsBlockchainSynced(), LogPrint(), and CBlockIndex::nHeight.
Referenced by CDSNotificationInterface::AcceptedBlockHeader().
BumpAssetLastTime()
void CMasternodeSync::BumpAssetLastTime (std::string strFuncName)
Definition at line 36 of file masternode-sync.cpp.
References GetTime(), IsFailed(), IsSynced(), LogPrint(), and nTimeLastBumped.
Referenced by AcceptedBlockHeader(), CGovernanceManager::AddGovernanceObject(), CMasternodePing::CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), NotifyHeaderTip(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), SwitchToNextAsset(), CMasternodeBroadcast::Update(), UpdatedBlockTip(), and CMasternodeMan::UpdateMasternodeList().
ClearFulfilledRequests()
void CMasternodeSync::ClearFulfilledRequests (CConnman & connman) private
Definition at line 138 of file masternode-sync.cpp.
References CNode::addr, CConnman::AllNodes, CConnman::ForEachNode(), netfulfilledman, and CNetFulfilledRequestManager::RemoveFulfilledRequest().
Referenced by SwitchToNextAsset().
Fail()
void CMasternodeSync::Fail () private
Definition at line 21 of file masternode-sync.cpp.
References GetTime(), MASTERNODE_SYNC_FAILED, nRequestedMasternodeAssets, and nTimeLastFailure.
Referenced by ProcessTick().
GetAssetID()
int CMasternodeSync::GetAssetID () inline
Definition at line 65 of file masternode-sync.h.
References nRequestedMasternodeAssets.
Referenced by mnsync().
GetAssetName()
std::string CMasternodeSync::GetAssetName ()
Definition at line 43 of file masternode-sync.cpp.
References MASTERNODE_SYNC_FAILED, MASTERNODE_SYNC_FINISHED, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_INITIAL, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_WAITING, and nRequestedMasternodeAssets.
Referenced by mnsync(), ProcessTick(), and SwitchToNextAsset().
GetAssetStartTime()
int64_t CMasternodeSync::GetAssetStartTime () inline
Definition at line 68 of file masternode-sync.h.
References nTimeAssetSyncStarted.
Referenced by mnsync().
GetAttempt()
int CMasternodeSync::GetAttempt () inline
Definition at line 66 of file masternode-sync.h.
References nRequestedMasternodeAttempt.
Referenced by mnsync().
GetSyncStatus()
std::string CMasternodeSync::GetSyncStatus ()
Definition at line 109 of file masternode-sync.cpp.
References _(), MASTERNODE_SYNC_FAILED, MASTERNODE_SYNC_FINISHED, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_INITIAL, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_WAITING, masternodeSync, and nRequestedMasternodeAssets.
Referenced by BitcoinGUI::setAdditionalDataSyncProgress().
IsBlockchainSynced()
bool CMasternodeSync::IsBlockchainSynced () inline
Definition at line 60 of file masternode-sync.h.
References MASTERNODE_SYNC_WAITING, and nRequestedMasternodeAssets.
Referenced by AcceptedBlockHeader(), CMasternodePayments::CheckAndRemove(), CPrivateSendClient::GetStatus(), gobject(), CActiveMasternode::ManageState(), mnsync(), NotifyHeaderTip(), OverviewPage::privateSendStatus(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), CMasternodeMan::ProcessMessage(), CGovernanceManager::ProcessMessage(), BitcoinGUI::setAdditionalDataSyncProgress(), BitcoinGUI::setNumBlocks(), ThreadCheckPrivateSend(), ThreadCheckPrivateSendClient(), ThreadCheckPrivateSendServer(), UpdatedBlockTip(), and OverviewPage::updatePrivateSendProgress().
IsFailed()
bool CMasternodeSync::IsFailed () inline
Definition at line 59 of file masternode-sync.h.
References MASTERNODE_SYNC_FAILED, and nRequestedMasternodeAssets.
Referenced by BumpAssetLastTime(), mnsync(), NotifyHeaderTip(), ProcessMessage(), ProcessTick(), and UpdatedBlockTip().
IsMasternodeListSynced()
bool CMasternodeSync::IsMasternodeListSynced () inline
Definition at line 61 of file masternode-sync.h.
References MASTERNODE_SYNC_LIST, and nRequestedMasternodeAssets.
Referenced by CMasternode::Check(), CInstantSend::CheckAndRemove(), CMasternodeMan::CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CMasternodePaymentVote::CheckSignature(), CPrivateSendClient::DoAutomaticDenominating(), CMasternodeMan::GetMasternodeRank(), CMasternodeMan::GetMasternodeRanks(), CMasternodeMan::GetMasternodeScores(), CMasternodePayments::IsScheduled(), CMasternodePaymentVote::IsValid(), masternode(), mnsync(), MasternodeList::on_startMissingButton_clicked(), CMasternodePayments::ProcessBlock(), CInstantSend::ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), CMasternodePayments::RequestLowDataPaymentBlocks(), CPrivateSend::UpdatedBlockTip(), and CPrivateSendClient::WaitForAnotherBlock().
IsSynced()
bool CMasternodeSync::IsSynced () inline
Definition at line 63 of file masternode-sync.h.
References MASTERNODE_SYNC_FINISHED, and nRequestedMasternodeAssets.
Referenced by CConnman::AcceptConnection(), BitcoinMiner(), BumpAssetLastTime(), CMasternode::Check(), CMasternodeMan::CheckAndRemove(), CGovernanceManager::CheckPostponedObjects(), CMasternodeMan::CheckSameAddr(), CMasternodeMan::DoFullVerificationStep(), CGovernanceManager::DoMaintenance(), getblocktemplate(), IsBlockPayeeValid(), IsBlockValueValid(), CGovernanceManager::MasternodeRateCheck(), mnsync(), NotifyHeaderTip(), ProcessMessage(), CMasternodeMan::ProcessMessage(), CMasternodePayments::ProcessMessage(), CGovernanceManager::ProcessMessage(), ProcessTick(), CMasternodePing::Relay(), CGovernanceVote::Relay(), CMasternodePaymentVote::Relay(), CGovernanceObject::Relay(), CMasternodeBroadcast::Relay(), BitcoinGUI::setAdditionalDataSyncProgress(), CGovernanceManager::Sync(), and UpdatedBlockTip().
IsWinnersListSynced()
bool CMasternodeSync::IsWinnersListSynced () inline
Definition at line 62 of file masternode-sync.h.
References MASTERNODE_SYNC_MNW, and nRequestedMasternodeAssets.
Referenced by CMasternodePayments::CheckPreviousBlockVotes(), CGovernanceManager::ConfirmInventoryRequest(), getblocktemplate(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), mnsync(), CMasternodePayments::Sync(), and CMasternodeMan::UpdateLastPaid().
NotifyHeaderTip()
void CMasternodeSync::NotifyHeaderTip (const CBlockIndex * pindexNew, bool fInitialDownload, CConnman & connman)
Definition at line 425 of file masternode-sync.cpp.
References BumpAssetLastTime(), IsBlockchainSynced(), IsFailed(), IsSynced(), LogPrint(), CBlockIndex::nHeight, and pindexBestHeader.
Referenced by CDSNotificationInterface::NotifyHeaderTip().
ProcessMessage()
void CMasternodeSync::ProcessMessage (CNode * pfrom, std::string & strCommand, CDataStream & vRecv)
Definition at line 123 of file masternode-sync.cpp.
References CNode::id, IsFailed(), IsSynced(), LogPrintf, and NetMsgType::SYNCSTATUSCOUNT.
Referenced by ProcessMessage().
ProcessTick()
void CMasternodeSync::ProcessTick (CConnman & connman)
Definition at line 153 of file masternode-sync.cpp.
References CNetFulfilledRequestManager::AddFulfilledRequest(), CNode::addr, CConnman::CopyNodeVector(), CMasternodeMan::CountMasternodes(), CMasternodeMan::DsegUpdate(), Fail(), CNode::fDisconnect, CNode::fInbound, fMasterNode, CNode::fMasternode, GetAssetName(), CMasternodePayments::GetMinMasternodePaymentsProto(), NetMsgType::GETSPORKS, CMasternodePayments::GetStorageLimit(), GetTime(), CGovernanceManager::GetVoteCount(), governance, CNetFulfilledRequestManager::HasFulfilledRequest(), CNode::id, INIT_PROTO_VERSION, CMasternodePayments::IsEnoughData(), IsFailed(), IsSynced(), LogPrint(), LogPrintf, MASTERNODE_SYNC_FINISHED, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_TICK_SECONDS, MASTERNODE_SYNC_TIMEOUT_SECONDS, MASTERNODE_SYNC_WAITING, NetMsgType::MASTERNODEPAYMENTSYNC, MIN_GOVERNANCE_PEER_PROTO_VERSION, mnodeman, mnpayments, netfulfilledman, CClientUIInterface::NotifyAdditionalDataSyncProgressChanged, nRequestedMasternodeAssets, nRequestedMasternodeAttempt, nTimeLastBumped, nTimeLastFailure, CNode::nVersion, Params(), CConnman::PushMessage(), CConnman::PushMessageWithVersion(), CBaseChainParams::REGTEST, CConnman::ReleaseNodeVector(), CGovernanceManager::RequestGovernanceObjectVotes(), CMasternodePayments::RequestLowDataPaymentBlocks(), Reset(), SendGovernanceSyncRequest(), SwitchToNextAsset(), and uiInterface.
Referenced by ThreadCheckPrivateSend().
Reset()
void CMasternodeSync::Reset ()
Definition at line 27 of file masternode-sync.cpp.
References GetTime(), MASTERNODE_SYNC_INITIAL, nRequestedMasternodeAssets, nRequestedMasternodeAttempt, nTimeAssetSyncStarted, nTimeLastBumped, and nTimeLastFailure.
Referenced by CMasternodeSync(), mnsync(), ProcessTick(), and UpdatedBlockTip().
SendGovernanceSyncRequest()
void CMasternodeSync::SendGovernanceSyncRequest (CNode * pnode, CConnman & connman)
Definition at line 402 of file masternode-sync.cpp.
References CBloomFilter::clear(), GOVERNANCE_FILTER_PROTO_VERSION, NetMsgType::MNGOVERNANCESYNC, CNode::nVersion, and CConnman::PushMessage().
Referenced by ProcessTick().
SwitchToNextAsset()
void CMasternodeSync::SwitchToNextAsset (CConnman & connman)
Definition at line 58 of file masternode-sync.cpp.
References activeMasternode, CNetFulfilledRequestManager::AddFulfilledRequest(), CNode::addr, CConnman::AllNodes, BumpAssetLastTime(), ClearFulfilledRequests(), CConnman::ForEachNode(), GetAssetName(), GetTime(), LogPrintf, CActiveMasternode::ManageState(), MASTERNODE_SYNC_FAILED, MASTERNODE_SYNC_FINISHED, MASTERNODE_SYNC_GOVERNANCE, MASTERNODE_SYNC_INITIAL, MASTERNODE_SYNC_LIST, MASTERNODE_SYNC_MNW, MASTERNODE_SYNC_WAITING, netfulfilledman, CClientUIInterface::NotifyAdditionalDataSyncProgressChanged, nRequestedMasternodeAssets, nRequestedMasternodeAttempt, nTimeAssetSyncStarted, and uiInterface.
Referenced by mnsync(), ProcessTick(), and UpdatedBlockTip().
UpdatedBlockTip()
void CMasternodeSync::UpdatedBlockTip (const CBlockIndex * pindexNew, bool fInitialDownload, CConnman & connman)
Definition at line 438 of file masternode-sync.cpp.
References BumpAssetLastTime(), CBlockIndex::GetBlockHash(), IsBlockchainSynced(), IsFailed(), IsSynced(), LogPrint(), CBlockIndex::nHeight, pindexBestHeader, Reset(), and SwitchToNextAsset().
Referenced by CDSNotificationInterface::UpdatedBlockTip().
Member Data Documentation
nRequestedMasternodeAssets
int CMasternodeSync::nRequestedMasternodeAssets private
Definition at line 39 of file masternode-sync.h.
Referenced by Fail(), GetAssetID(), GetAssetName(), GetSyncStatus(), IsBlockchainSynced(), IsFailed(), IsMasternodeListSynced(), IsSynced(), IsWinnersListSynced(), ProcessTick(), Reset(), and SwitchToNextAsset().
nRequestedMasternodeAttempt
int CMasternodeSync::nRequestedMasternodeAttempt private
Definition at line 41 of file masternode-sync.h.
Referenced by GetAttempt(), ProcessTick(), Reset(), and SwitchToNextAsset().
nTimeAssetSyncStarted
int64_t CMasternodeSync::nTimeAssetSyncStarted private
Definition at line 44 of file masternode-sync.h.
Referenced by GetAssetStartTime(), Reset(), and SwitchToNextAsset().
nTimeLastBumped
int64_t CMasternodeSync::nTimeLastBumped private
Definition at line 46 of file masternode-sync.h.
Referenced by BumpAssetLastTime(), ProcessTick(), and Reset().
nTimeLastFailure
int64_t CMasternodeSync::nTimeLastFailure private
Definition at line 48 of file masternode-sync.h.
Referenced by Fail(), ProcessTick(), and Reset().
The documentation for this class was generated from the following files:
src/masternode-sync.h
src/masternode-sync.cpp
Released under the MIT license