Dash Core: QValueComboBox Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
QValueComboBox Class Reference
#include <qvaluecombobox.h>
Signals
void valueChanged ()
Public Member Functions
QValueComboBox (QWidget *parent=0)
QVariant value () const
void setValue (const QVariant &value)
void setRole (int role)
Specify model role to use as ordinal value (defaults to Qt::UserRole)
Properties
QVariant value
Private Slots
void handleSelectionChanged (int idx)
Private Attributes
int role
Detailed Description
Definition at line 12 of file qvaluecombobox.h.
Constructor & Destructor Documentation
QValueComboBox()
QValueComboBox::QValueComboBox (QWidget * parent = 0) explicit
Definition at line 7 of file qvaluecombobox.cpp.
References handleSelectionChanged().
Member Function Documentation
handleSelectionChanged
void QValueComboBox::handleSelectionChanged (int idx) private slot
Definition at line 28 of file qvaluecombobox.cpp.
References valueChanged().
Referenced by QValueComboBox().
setRole()
void QValueComboBox::setRole (int role)
Specify model role to use as ordinal value (defaults to Qt::UserRole)
Definition at line 23 of file qvaluecombobox.cpp.
References role.
setValue()
void QValueComboBox::setValue (const QVariant & value)
Definition at line 18 of file qvaluecombobox.cpp.
References role, and value().
value()
QVariant QValueComboBox::value () const
Referenced by setValue().
valueChanged
void QValueComboBox::valueChanged () signal
Referenced by handleSelectionChanged().
Member Data Documentation
role
int QValueComboBox::role private
Definition at line 31 of file qvaluecombobox.h.
Referenced by setRole(), and setValue().
Property Documentation
value
QVariant QValueComboBox::value read write
Definition at line 16 of file qvaluecombobox.h.
The documentation for this class was generated from the following files:
src/qt/qvaluecombobox.h
src/qt/qvaluecombobox.cpp
Released under the MIT license