Dash Core: WalletModelTransaction Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
WalletModelTransaction Class Reference
Data model for a walletmodel transaction.
#include <walletmodeltransaction.h>
Public Member Functions
WalletModelTransaction (const QList< SendCoinsRecipient > &recipients)
~WalletModelTransaction ()
QList< SendCoinsRecipient > getRecipients () const
CWalletTx * getTransaction () const
unsigned int getTransactionSize ()
void setTransactionFee (const CAmount &newFee)
CAmount getTransactionFee () const
CAmount getTotalTransactionAmount () const
void newPossibleKeyChange (CWallet *wallet)
CReserveKey * getPossibleKeyChange ()
void reassignAmounts ()
Private Attributes
QList< SendCoinsRecipient > recipients
CWalletTx * walletTransaction
std::unique_ptr< CReserveKey > keyChange
CAmount fee
Detailed Description
Data model for a walletmodel transaction.
Definition at line 21 of file walletmodeltransaction.h.
Constructor & Destructor Documentation
WalletModelTransaction()
WalletModelTransaction::WalletModelTransaction (const QList< SendCoinsRecipient > & recipients) explicit
Definition at line 9 of file walletmodeltransaction.cpp.
References walletTransaction.
~WalletModelTransaction()
WalletModelTransaction::~WalletModelTransaction ()
Definition at line 17 of file walletmodeltransaction.cpp.
References walletTransaction.
Member Function Documentation
getPossibleKeyChange()
CReserveKey * WalletModelTransaction::getPossibleKeyChange ()
Definition at line 101 of file walletmodeltransaction.cpp.
References keyChange.
Referenced by WalletModel::prepareTransaction(), and WalletModel::sendCoins().
getRecipients()
QList< SendCoinsRecipient > WalletModelTransaction::getRecipients () const
Definition at line 22 of file walletmodeltransaction.cpp.
References recipients.
Referenced by WalletModel::prepareTransaction(), SendCoinsDialog::send(), and WalletModel::sendCoins().
getTotalTransactionAmount()
CAmount WalletModelTransaction::getTotalTransactionAmount () const
Definition at line 86 of file walletmodeltransaction.cpp.
References recipients.
Referenced by SendCoinsDialog::send().
getTransaction()
CWalletTx * WalletModelTransaction::getTransaction () const
Definition at line 27 of file walletmodeltransaction.cpp.
References walletTransaction.
Referenced by WalletModel::prepareTransaction(), SendCoinsDialog::send(), and WalletModel::sendCoins().
getTransactionFee()
CAmount WalletModelTransaction::getTransactionFee () const
Definition at line 37 of file walletmodeltransaction.cpp.
References fee.
Referenced by SendCoinsDialog::send().
getTransactionSize()
unsigned int WalletModelTransaction::getTransactionSize ()
Definition at line 32 of file walletmodeltransaction.cpp.
References GetSerializeSize(), PROTOCOL_VERSION, SER_NETWORK, CMerkleTx::tx, and walletTransaction.
Referenced by SendCoinsDialog::send().
newPossibleKeyChange()
void WalletModelTransaction::newPossibleKeyChange (CWallet * wallet)
Definition at line 96 of file walletmodeltransaction.cpp.
References keyChange.
Referenced by WalletModel::prepareTransaction().
reassignAmounts()
void WalletModelTransaction::reassignAmounts ()
Definition at line 47 of file walletmodeltransaction.cpp.
References SendCoinsRecipient::address, SendCoinsRecipient::amount, DecodeDestination(), PaymentRequestPlus::getDetails(), GetScriptForDestination(), PaymentRequestPlus::IsInitialized(), SendCoinsRecipient::paymentRequest, recipients, CMerkleTx::tx, and walletTransaction.
Referenced by WalletModel::prepareTransaction().
setTransactionFee()
void WalletModelTransaction::setTransactionFee (const CAmount & newFee)
Definition at line 42 of file walletmodeltransaction.cpp.
References fee.
Referenced by WalletModel::prepareTransaction().
Member Data Documentation
fee
CAmount WalletModelTransaction::fee private
Definition at line 46 of file walletmodeltransaction.h.
Referenced by getTransactionFee(), and setTransactionFee().
keyChange
std::unique_ptr<CReserveKey> WalletModelTransaction::keyChange private
Definition at line 45 of file walletmodeltransaction.h.
Referenced by getPossibleKeyChange(), and newPossibleKeyChange().
recipients
QList<SendCoinsRecipient> WalletModelTransaction::recipients private
Definition at line 43 of file walletmodeltransaction.h.
Referenced by getRecipients(), getTotalTransactionAmount(), and reassignAmounts().
walletTransaction
CWalletTx* WalletModelTransaction::walletTransaction private
Definition at line 44 of file walletmodeltransaction.h.
Referenced by getTransaction(), getTransactionSize(), reassignAmounts(), WalletModelTransaction(), and ~WalletModelTransaction().
The documentation for this class was generated from the following files:
src/qt/walletmodeltransaction.h
src/qt/walletmodeltransaction.cpp
Released under the MIT license