Dash Core: CreateTransactionTestSetup Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CreateTransactionTestSetup Class Reference
Public Types
enum ChangeTest { Skip, NoChangeExpected, ChangeExpected }
Public Member Functions
CreateTransactionTestSetup ()
~CreateTransactionTestSetup ()
template<typename T >
bool CheckEqual (const T expected, const T actual)
bool CreateTransaction (const std::vector< std::pair< CAmount, bool >> &vecEntries, bool fCreateShouldSucceed=true, ChangeTest changeTest=ChangeTest::Skip)
bool CreateTransaction (const std::vector< std::pair< CAmount, bool >> &vecEntries, std::string strErrorExpected, bool fCreateShouldSucceed=true, ChangeTest changeTest=ChangeTest::Skip)
bool CreateTransaction (const std::vector< std::pair< CAmount, bool >> &vecEntries, std::string strErrorExpected, int nChangePosRequest=-1, bool fCreateShouldSucceed=true, ChangeTest changeTest=ChangeTest::Skip)
std::vector< CRecipient > GetRecipients (const std::vector< std::pair< CAmount, bool >> &vecEntries)
std::vector< COutPoint > GetCoins (const std::vector< std::pair< CAmount, bool >> &vecEntries)
Public Attributes
const std::string strInsufficientFunds = "Insufficient funds."
const std::string strAmountNotNegative = "Transaction amounts must not be negative"
const std::string strAtLeastOneRecipient = "Transaction must have at least one recipient"
const std::string strTooSmallToPayFee = "The transaction amount is too small to pay the fee"
const std::string strTooSmallAfterFee = "The transaction amount is too small to send after the fee has been deducted"
const std::string strTooSmall = "Transaction amount too small"
const std::string strUnableToLocatePrivateSend1 = "Unable to locate enough PrivateSend non-denominated funds for this transaction."
const std::string strUnableToLocatePrivateSend2 = "Unable to locate enough PrivateSend denominated funds for this transaction. PrivateSend uses exact denominated amounts to send funds, you might simply need to mix some more coins."
const std::string strTransactionTooLarge = "Transaction too large"
const std::string strTransactionTooLargeForFeePolicy = "Transaction too large for fee policy"
const std::string strChangeIndexOutOfRange = "Change index out of range"
const std::string strExceededMaxTries = "Exceeded max tries."
std::unique_ptr< CWallet > wallet
CCoinControl coinControl
Detailed Description
Definition at line 697 of file wallet_tests.cpp.
Member Enumeration Documentation
ChangeTest
enum CreateTransactionTestSetup::ChangeTest
Enumerator
Skip
NoChangeExpected
ChangeExpected
Definition at line 700 of file wallet_tests.cpp.
Constructor & Destructor Documentation
CreateTransactionTestSetup()
CreateTransactionTestSetup::CreateTransactionTestSetup () inline
Definition at line 720 of file wallet_tests.cpp.
References AddKey(), AddWallet(), chainActive, BerkeleyDatabase::CreateMock(), CChain::Genesis(), GetScriptForRawPubKey(), WalletRescanReserver::reserve(), and wallet.
~CreateTransactionTestSetup()
CreateTransactionTestSetup::~CreateTransactionTestSetup () inline
Definition at line 733 of file wallet_tests.cpp.
References RemoveWallet(), and wallet.
Member Function Documentation
CheckEqual()
template<typename T > bool CreateTransactionTestSetup::CheckEqual (const T expected, const T actual) inline
Definition at line 742 of file wallet_tests.cpp.
References BOOST_CHECK_EQUAL.
Referenced by CreateTransaction().
CreateTransaction() [1/3]
bool CreateTransactionTestSetup::CreateTransaction (const std::vector< std::pair< CAmount, bool >> & vecEntries, bool fCreateShouldSucceed = true, ChangeTest changeTest = ChangeTest::Skip) inline
Definition at line 748 of file wallet_tests.cpp.
Referenced by CreateTransaction().
CreateTransaction() [2/3]
bool CreateTransactionTestSetup::CreateTransaction (const std::vector< std::pair< CAmount, bool >> & vecEntries, std::string strErrorExpected, bool fCreateShouldSucceed = true, ChangeTest changeTest = ChangeTest::Skip) inline
Definition at line 752 of file wallet_tests.cpp.
References CreateTransaction().
CreateTransaction() [3/3]
bool CreateTransactionTestSetup::CreateTransaction (const std::vector< std::pair< CAmount, bool >> & vecEntries, std::string strErrorExpected, int nChangePosRequest = -1, bool fCreateShouldSucceed = true, ChangeTest changeTest = ChangeTest::Skip) inline
Definition at line 757 of file wallet_tests.cpp.
References BOOST_CHECK, CheckEqual(), coinControl, GetRecipients(), strExceededMaxTries, CMerkleTx::tx, and wallet.
GetCoins()
std::vector<COutPoint> CreateTransactionTestSetup::GetCoins (const std::vector< std::pair< CAmount, bool >> & vecEntries) inline
Definition at line 809 of file wallet_tests.cpp.
References BOOST_CHECK, chainActive, coinControl, cs_main, CMerkleTx::GetHash(), GetRecipients(), GetScriptForRawPubKey(), LOCK, CChain::Tip(), CMerkleTx::tx, and wallet.
GetRecipients()
std::vector<CRecipient> CreateTransactionTestSetup::GetRecipients (const std::vector< std::pair< CAmount, bool >> & vecEntries) inline
Definition at line 800 of file wallet_tests.cpp.
References DecodeDestination(), getnewaddress(), and GetScriptForDestination().
Referenced by CreateTransaction(), and GetCoins().
Member Data Documentation
coinControl
CCoinControl CreateTransactionTestSetup::coinControl
Definition at line 739 of file wallet_tests.cpp.
Referenced by CreateTransaction(), and GetCoins().
strAmountNotNegative
const std::string CreateTransactionTestSetup::strAmountNotNegative = "Transaction amounts must not be negative"
Definition at line 708 of file wallet_tests.cpp.
strAtLeastOneRecipient
const std::string CreateTransactionTestSetup::strAtLeastOneRecipient = "Transaction must have at least one recipient"
Definition at line 709 of file wallet_tests.cpp.
strChangeIndexOutOfRange
const std::string CreateTransactionTestSetup::strChangeIndexOutOfRange = "Change index out of range"
Definition at line 717 of file wallet_tests.cpp.
strExceededMaxTries
const std::string CreateTransactionTestSetup::strExceededMaxTries = "Exceeded max tries."
Definition at line 718 of file wallet_tests.cpp.
Referenced by CreateTransaction().
strInsufficientFunds
const std::string CreateTransactionTestSetup::strInsufficientFunds = "Insufficient funds."
Definition at line 707 of file wallet_tests.cpp.
strTooSmall
const std::string CreateTransactionTestSetup::strTooSmall = "Transaction amount too small"
Definition at line 712 of file wallet_tests.cpp.
strTooSmallAfterFee
const std::string CreateTransactionTestSetup::strTooSmallAfterFee = "The transaction amount is too small to send after the fee has been deducted"
Definition at line 711 of file wallet_tests.cpp.
strTooSmallToPayFee
const std::string CreateTransactionTestSetup::strTooSmallToPayFee = "The transaction amount is too small to pay the fee"
Definition at line 710 of file wallet_tests.cpp.
strTransactionTooLarge
const std::string CreateTransactionTestSetup::strTransactionTooLarge = "Transaction too large"
Definition at line 715 of file wallet_tests.cpp.
strTransactionTooLargeForFeePolicy
const std::string CreateTransactionTestSetup::strTransactionTooLargeForFeePolicy = "Transaction too large for fee policy"
Definition at line 716 of file wallet_tests.cpp.
strUnableToLocatePrivateSend1
const std::string CreateTransactionTestSetup::strUnableToLocatePrivateSend1 = "Unable to locate enough PrivateSend non-denominated funds for this transaction."
Definition at line 713 of file wallet_tests.cpp.
strUnableToLocatePrivateSend2
const std::string CreateTransactionTestSetup::strUnableToLocatePrivateSend2 = "Unable to locate enough PrivateSend denominated funds for this transaction. PrivateSend uses exact denominated amounts to send funds, you might simply need to mix some more coins."
Definition at line 714 of file wallet_tests.cpp.
wallet
std::unique_ptr<CWallet> CreateTransactionTestSetup::wallet
Definition at line 738 of file wallet_tests.cpp.
Referenced by CreateTransaction(), CreateTransactionTestSetup(), GetCoins(), and ~CreateTransactionTestSetup().
The documentation for this class was generated from the following file:
src/wallet/test/wallet_tests.cpp
Released under the MIT license