Dash Core: CPrivateSendBaseManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CPrivateSendBaseManager Class Reference
#include <privatesend.h>
Public Member Functions
CPrivateSendBaseManager ()
int GetQueueSize () const
bool GetQueueItemAndTry (CPrivateSendQueue &dsqRet)
Protected Member Functions
void SetNull ()
void CheckQueue ()
Protected Attributes
CCriticalSection cs_vecqueue
std::vector< CPrivateSendQueue > vecPrivateSendQueue
Detailed Description
Definition at line 397 of file privatesend.h.
Constructor & Destructor Documentation
CPrivateSendBaseManager()
CPrivateSendBaseManager::CPrivateSendBaseManager () inline
Definition at line 409 of file privatesend.h.
Member Function Documentation
CheckQueue()
void CPrivateSendBaseManager::CheckQueue () protected
Definition at line 174 of file privatesend.cpp.
References cs_vecqueue, LogPrint, BCLog::PRIVATESEND, TRY_LOCK, and vecPrivateSendQueue.
Referenced by CPrivateSendServer::CheckTimeout(), and CPrivateSendClientManager::CheckTimeout().
GetQueueItemAndTry()
bool CPrivateSendBaseManager::GetQueueItemAndTry (CPrivateSendQueue & dsqRet)
Definition at line 191 of file privatesend.cpp.
References cs_vecqueue, TRY_LOCK, and vecPrivateSendQueue.
Referenced by CPrivateSendClientSession::JoinExistingQueue().
GetQueueSize()
int CPrivateSendBaseManager::GetQueueSize () const inline
Definition at line 412 of file privatesend.h.
References vecPrivateSendQueue.
Referenced by CPrivateSendServer::GetJsonInfo(), and CPrivateSendClientManager::GetJsonInfo().
SetNull()
void CPrivateSendBaseManager::SetNull () protected
Definition at line 168 of file privatesend.cpp.
References cs_vecqueue, LOCK, and vecPrivateSendQueue.
Referenced by CPrivateSendServer::SetNull().
Member Data Documentation
cs_vecqueue
CCriticalSection CPrivateSendBaseManager::cs_vecqueue mutable protected
Definition at line 400 of file privatesend.h.
Referenced by CheckQueue(), GetQueueItemAndTry(), CPrivateSendServer::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), and SetNull().
vecPrivateSendQueue
std::vector<CPrivateSendQueue> CPrivateSendBaseManager::vecPrivateSendQueue protected
Definition at line 403 of file privatesend.h.
Referenced by CheckQueue(), CPrivateSendServer::CreateNewSession(), GetQueueItemAndTry(), GetQueueSize(), CPrivateSendServer::ProcessMessage(), CPrivateSendClientManager::ProcessMessage(), and SetNull().
The documentation for this class was generated from the following files:
src/privatesend/privatesend.h
src/privatesend/privatesend.cpp
Released under the MIT license