Dash Core: JSONRequest Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
JSONRequest Class Reference
#include <server.h>
Public Member Functions
JSONRequest ()
void parse (const UniValue &valRequest)
Public Attributes
UniValue id
std::string strMethod
UniValue params
Detailed Description
Definition at line 35 of file server.h.
Constructor & Destructor Documentation
JSONRequest()
JSONRequest::JSONRequest () inline
Definition at line 42 of file server.h.
References NullUniValue.
Member Function Documentation
parse()
void JSONRequest::parse (const UniValue & valRequest)
Definition at line 478 of file server.cpp.
References find_value(), UniValue::get_array(), UniValue::get_obj(), UniValue::get_str(), UniValue::isArray(), UniValue::isNull(), UniValue::isObject(), UniValue::isStr(), JSONRPCError(), LogPrint(), RPC_INVALID_REQUEST, SanitizeString(), and UniValue::VARR.
Referenced by HTTPReq_JSONRPC(), and JSONRPCExecOne().
Member Data Documentation
id
UniValue JSONRequest::id
Definition at line 38 of file server.h.
Referenced by HTTPReq_JSONRPC(), and JSONRPCExecOne().
params
UniValue JSONRequest::params
Definition at line 40 of file server.h.
Referenced by HTTPReq_JSONRPC(), and JSONRPCExecOne().
strMethod
std::string JSONRequest::strMethod
Definition at line 39 of file server.h.
Referenced by HTTPReq_JSONRPC(), and JSONRPCExecOne().
The documentation for this class was generated from the following files:
src/rpc/server.h
src/rpc/server.cpp
Released under the MIT license