Dash Core: BitcoinUnits Class Reference
BitcoinUnits Class Reference
#include <bitcoinunits.h>
Public Types
enum Unit { DASH, mDASH, uDASH, duffs }
enum SeparatorStyle { separatorNever, separatorStandard, separatorAlways }
Public Member Functions
BitcoinUnits (QObject *parent)
Static Public Member Functions
static QString removeSpaces (QString text)
static CAmount maxMoney ()
Return maximum number of base units (Satoshis)
Static API
Unit conversion and formatting
static QList< Unit > availableUnits ()
Get list of units, for drop-down box.
static bool valid (int unit)
Is unit ID valid?
static QString name (int unit)
Short name.
static QString description (int unit)
Longer description.
static qint64 factor (int unit)
Number of Satoshis (1e-8) per unit.
static int decimals (int unit)
Number of decimals left.
static QString format (int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
Format as string.
static QString simpleFormat (int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
static QString formatWithUnit (int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
Format as string (with unit)
static QString formatHtmlWithUnit (int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
Format as HTML string (with unit)
static QString floorWithUnit (int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
Format as string (with unit) but floor value up to "digits" settings.
static QString floorHtmlWithUnit (int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
static bool parse (int unit, const QString &value, CAmount *val_out)
Parse string to coin amount.
static QString getAmountColumnTitle (int unit)
Gets title for amount column including current display unit if optionsModel reference available */.
Private Attributes
QList< BitcoinUnits::Unit > unitlist
AbstractListModel implementation
List model for unit drop-down selection box.
enum RoleIndex { UnitRole = Qt::UserRole }
int rowCount (const QModelIndex &parent) const
QVariant data (const QModelIndex &index, int role) const
Detailed Description
Dash unit definitions. Encapsulates parsing and formatting and serves as list model for drop-down selection boxes.
Definition at line 48 of file bitcoinunits.h.
Member Enumeration Documentation
RoleIndex
enum BitcoinUnits::RoleIndex
Enumerator
UnitRole
Unit identifier
Definition at line 108 of file bitcoinunits.h.
SeparatorStyle
enum BitcoinUnits::SeparatorStyle
Enumerator
separatorNever
separatorStandard
separatorAlways
Definition at line 66 of file bitcoinunits.h.
Unit
enum BitcoinUnits::Unit
Dash units.
Note
Source: https://en.bitcoin.it/wiki/Units . Please add only sensible ones
Enumerator
DASH
mDASH
uDASH
duffs
Definition at line 58 of file bitcoinunits.h.
Constructor & Destructor Documentation
BitcoinUnits()
BitcoinUnits::BitcoinUnits (QObject * parent) explicit
Definition at line 13 of file bitcoinunits.cpp.
Member Function Documentation
availableUnits()
QList< BitcoinUnits::Unit > BitcoinUnits::availableUnits () static
Get list of units, for drop-down box.
Definition at line 19 of file bitcoinunits.cpp.
Referenced by UnitDisplayStatusBarControl::createContextMenu(), SendCoinsDialog::send(), and UnitDisplayStatusBarControl::UnitDisplayStatusBarControl().
data()
QVariant BitcoinUnits::data (const QModelIndex & index, int role) const
Definition at line 247 of file bitcoinunits.cpp.
decimals()
int BitcoinUnits::decimals (int unit) static
Number of decimals left.
Definition at line 107 of file bitcoinunits.cpp.
Referenced by floorWithUnit(), format(), parse(), and OverviewPage::updatePrivateSendProgress().
description()
QString BitcoinUnits::description (int unit) static
Longer description.
Definition at line 69 of file bitcoinunits.cpp.
Referenced by data().
factor()
qint64 BitcoinUnits::factor (int unit) static
Number of Satoshis (1e-8) per unit.
Definition at line 95 of file bitcoinunits.cpp.
Referenced by format(), and OverviewPage::updatePrivateSendProgress().
floorHtmlWithUnit()
QString BitcoinUnits::floorHtmlWithUnit (int unit, const CAmount & amount, bool plussign = false, SeparatorStyle separators = separatorStandard) static
Definition at line 185 of file bitcoinunits.cpp.
Referenced by OverviewPage::setBalance().
floorWithUnit()
QString BitcoinUnits::floorWithUnit (int unit, const CAmount & amount, bool plussign = false, SeparatorStyle separators = separatorStandard) static
Format as string (with unit) but floor value up to "digits" settings.
Definition at line 174 of file bitcoinunits.cpp.
Referenced by floorHtmlWithUnit(), and TxViewDelegate::paint().
format()
QString BitcoinUnits::format (int unit, const CAmount & amount, bool plussign = false, SeparatorStyle separators = separatorStandard) static
Format as string.
Definition at line 119 of file bitcoinunits.cpp.
Referenced by RecentRequestsTableModel::data(), AmountSpinBox::fixup(), floorWithUnit(), GUIUtil::formatBitcoinURI(), TransactionTableModel::formatTxAmount(), formatWithUnit(), AmountSpinBox::minimumSizeHint(), AmountSpinBox::setValue(), and CoinControlDialog::updateView().
formatHtmlWithUnit()
QString BitcoinUnits::formatHtmlWithUnit (int unit, const CAmount & amount, bool plussign = false, SeparatorStyle separators = separatorStandard) static
Format as HTML string (with unit)
Definition at line 167 of file bitcoinunits.cpp.
Referenced by SendCoinsDialog::send(), TransactionDesc::toHTML(), ReceiveRequestDialog::update(), and OverviewPage::updatePrivateSendProgress().
formatWithUnit()
QString BitcoinUnits::formatWithUnit (int unit, const CAmount & amount, bool plussign = false, SeparatorStyle separators = separatorStandard) static
Format as string (with unit)
Definition at line 162 of file bitcoinunits.cpp.
Referenced by DarksendConfig::clickBasic(), DarksendConfig::clickHigh(), DarksendConfig::clickMax(), TransactionView::computeSum(), formatHtmlWithUnit(), SendCoinsDialog::on_sendButton_clicked(), PaymentServer::processPaymentRequest(), SendCoinsDialog::processSendCoinsReturn(), SendCoinsDialog::send(), SendCoinsDialog::setBalance(), OverviewPage::togglePrivateSend(), SendCoinsDialog::updateFeeMinimizedLabel(), CoinControlDialog::updateLabels(), SendCoinsDialog::updateMinFeeLabel(), and SendCoinsDialog::updateSmartFeeLabel().
getAmountColumnTitle()
QString BitcoinUnits::getAmountColumnTitle (int unit) static
Gets title for amount column including current display unit if optionsModel reference available */.
Definition at line 231 of file bitcoinunits.cpp.
Referenced by TransactionView::exportClicked(), TransactionTableModel::TransactionTableModel(), and TransactionTableModel::updateAmountColumnTitle().
maxMoney()
CAmount BitcoinUnits::maxMoney () static
Return maximum number of base units (Satoshis)
Definition at line 267 of file bitcoinunits.cpp.
Referenced by AmountSpinBox::minimumSizeHint(), AmountSpinBox::parse(), AmountSpinBox::stepBy(), and AmountSpinBox::stepEnabled().
name()
QString BitcoinUnits::name (int unit) static
Short name.
Definition at line 43 of file bitcoinunits.cpp.
Referenced by UnitDisplayStatusBarControl::createContextMenu(), data(), floorWithUnit(), formatWithUnit(), getAmountColumnTitle(), RecentRequestsTableModel::getAmountTitle(), UnitDisplayStatusBarControl::UnitDisplayStatusBarControl(), and UnitDisplayStatusBarControl::updateDisplayUnit().
parse()
bool BitcoinUnits::parse (int unit, const QString & value, CAmount * val_out) static
Parse string to coin amount.
Definition at line 192 of file bitcoinunits.cpp.
Referenced by TransactionView::changedAmount(), AmountSpinBox::parse(), and GUIUtil::parseBitcoinURI().
removeSpaces()
static QString BitcoinUnits::removeSpaces (QString text) inline static
Definition at line 116 of file bitcoinunits.h.
Referenced by CoinControlDialog::copyAmount(), and parse().
rowCount()
int BitcoinUnits::rowCount (const QModelIndex & parent) const
Definition at line 241 of file bitcoinunits.cpp.
simpleFormat()
static QString BitcoinUnits::simpleFormat (int unit, const CAmount & amount, bool plussign = false, SeparatorStyle separators = separatorStandard) static
valid()
bool BitcoinUnits::valid (int unit) static
Is unit ID valid?
Definition at line 29 of file bitcoinunits.cpp.
Referenced by format(), getAmountColumnTitle(), and parse().
Member Data Documentation
unitlist
QList<BitcoinUnits::Unit> BitcoinUnits::unitlist private
Definition at line 130 of file bitcoinunits.h.
Referenced by availableUnits(), data(), and rowCount().
The documentation for this class was generated from the following files:
src/qt/bitcoinunits.h
src/qt/bitcoinunits.cpp