Dash Core: SignVerifyMessageDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
SignVerifyMessageDialog Class Reference
#include <signverifymessagedialog.h>
Public Member Functions
SignVerifyMessageDialog (QWidget *parent)
~SignVerifyMessageDialog ()
void setModel (WalletModel *model)
void setAddress_SM (const QString &address)
void setAddress_VM (const QString &address)
void showTab_SM (bool fShow)
void showTab_VM (bool fShow)
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event)
Private Slots
void showPage (int index)
custom tab buttons clicked
void on_addressBookButton_SM_clicked ()
void on_pasteButton_SM_clicked ()
void on_signMessageButton_SM_clicked ()
void on_copySignatureButton_SM_clicked ()
void on_clearButton_SM_clicked ()
void on_addressBookButton_VM_clicked ()
void on_verifyMessageButton_VM_clicked ()
void on_clearButton_VM_clicked ()
Private Attributes
Ui::SignVerifyMessageDialog * ui
WalletModel * model
QButtonGroup pageButtons
Detailed Description
Definition at line 17 of file signverifymessagedialog.h.
Constructor & Destructor Documentation
SignVerifyMessageDialog()
SignVerifyMessageDialog::SignVerifyMessageDialog (QWidget * parent) explicit
Definition at line 23 of file signverifymessagedialog.cpp.
References GUIUtil::Bold, GUIUtil::disableMacFocusRect(), GUIUtil::Normal, pageButtons, GUIUtil::setFont(), GUIUtil::setIcon(), GUIUtil::setupAddressWidget(), showPage(), ui, and GUIUtil::updateFonts().
~SignVerifyMessageDialog()
SignVerifyMessageDialog::~SignVerifyMessageDialog ()
Definition at line 64 of file signverifymessagedialog.cpp.
References ui.
Member Function Documentation
eventFilter()
bool SignVerifyMessageDialog::eventFilter (QObject * object, QEvent * event) protected
Definition at line 279 of file signverifymessagedialog.cpp.
References ui.
on_addressBookButton_SM_clicked
void SignVerifyMessageDialog::on_addressBookButton_SM_clicked () private slot
Definition at line 118 of file signverifymessagedialog.cpp.
References AddressBookPage::ForSelection, WalletModel::getAddressTableModel(), AddressBookPage::getReturnValue(), model, AddressBookPage::ReceivingTab, setAddress_SM(), and AddressBookPage::setModel().
on_addressBookButton_VM_clicked
void SignVerifyMessageDialog::on_addressBookButton_VM_clicked () private slot
Definition at line 207 of file signverifymessagedialog.cpp.
References AddressBookPage::ForSelection, WalletModel::getAddressTableModel(), AddressBookPage::getReturnValue(), model, AddressBookPage::SendingTab, setAddress_VM(), and AddressBookPage::setModel().
on_clearButton_SM_clicked
void SignVerifyMessageDialog::on_clearButton_SM_clicked () private slot
Definition at line 197 of file signverifymessagedialog.cpp.
References ui.
on_clearButton_VM_clicked
void SignVerifyMessageDialog::on_clearButton_VM_clicked () private slot
Definition at line 269 of file signverifymessagedialog.cpp.
References ui.
on_copySignatureButton_SM_clicked
void SignVerifyMessageDialog::on_copySignatureButton_SM_clicked () private slot
Definition at line 192 of file signverifymessagedialog.cpp.
References GUIUtil::setClipboard(), and ui.
on_pasteButton_SM_clicked
void SignVerifyMessageDialog::on_pasteButton_SM_clicked () private slot
Definition at line 131 of file signverifymessagedialog.cpp.
References setAddress_SM().
on_signMessageButton_SM_clicked
void SignVerifyMessageDialog::on_signMessageButton_SM_clicked () private slot
Definition at line 136 of file signverifymessagedialog.cpp.
References ctx, DecodeDestination(), EncodeBase64(), CHashWriter::GetHash(), WalletModel::getPrivKey(), GUIUtil::getThemedStyleQString(), IsValidDestination(), model, WalletModel::requestUnlock(), SER_GETHASH, CKey::SignCompact(), strMessageMagic, GUIUtil::TS_ERROR, GUIUtil::TS_SUCCESS, and ui.
on_verifyMessageButton_VM_clicked
void SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked () private slot
Definition at line 220 of file signverifymessagedialog.cpp.
References DecodeBase64(), DecodeDestination(), CHashWriter::GetHash(), CPubKey::GetID(), GUIUtil::getThemedStyleQString(), IsValidDestination(), CPubKey::RecoverCompact(), SER_GETHASH, strMessageMagic, GUIUtil::TS_ERROR, GUIUtil::TS_SUCCESS, and ui.
setAddress_SM()
void SignVerifyMessageDialog::setAddress_SM (const QString & address)
Definition at line 74 of file signverifymessagedialog.cpp.
References ui.
Referenced by WalletView::gotoSignMessageTab(), on_addressBookButton_SM_clicked(), and on_pasteButton_SM_clicked().
setAddress_VM()
void SignVerifyMessageDialog::setAddress_VM (const QString & address)
Definition at line 80 of file signverifymessagedialog.cpp.
References ui.
Referenced by WalletView::gotoVerifyMessageTab(), and on_addressBookButton_VM_clicked().
setModel()
void SignVerifyMessageDialog::setModel (WalletModel * model)
Definition at line 69 of file signverifymessagedialog.cpp.
References model.
Referenced by WalletView::gotoSignMessageTab(), and WalletView::gotoVerifyMessageTab().
showPage
void SignVerifyMessageDialog::showPage (int index) private slot
custom tab buttons clicked
Definition at line 100 of file signverifymessagedialog.cpp.
References GUIUtil::Bold, GUIUtil::Normal, pageButtons, GUIUtil::setFont(), ui, and GUIUtil::updateFonts().
Referenced by showTab_SM(), showTab_VM(), and SignVerifyMessageDialog().
showTab_SM()
void SignVerifyMessageDialog::showTab_SM (bool fShow)
Definition at line 86 of file signverifymessagedialog.cpp.
References showPage().
Referenced by WalletView::gotoSignMessageTab().
showTab_VM()
void SignVerifyMessageDialog::showTab_VM (bool fShow)
Definition at line 93 of file signverifymessagedialog.cpp.
References showPage().
Referenced by WalletView::gotoVerifyMessageTab().
Member Data Documentation
model
WalletModel* SignVerifyMessageDialog::model private
Definition at line 37 of file signverifymessagedialog.h.
Referenced by on_addressBookButton_SM_clicked(), on_addressBookButton_VM_clicked(), on_signMessageButton_SM_clicked(), and setModel().
pageButtons
QButtonGroup SignVerifyMessageDialog::pageButtons private
Definition at line 38 of file signverifymessagedialog.h.
Referenced by showPage(), and SignVerifyMessageDialog().
ui
Ui::SignVerifyMessageDialog* SignVerifyMessageDialog::ui private
Definition at line 36 of file signverifymessagedialog.h.
Referenced by eventFilter(), on_clearButton_SM_clicked(), on_clearButton_VM_clicked(), on_copySignatureButton_SM_clicked(), on_signMessageButton_SM_clicked(), on_verifyMessageButton_VM_clicked(), setAddress_SM(), setAddress_VM(), showPage(), SignVerifyMessageDialog(), and ~SignVerifyMessageDialog().
The documentation for this class was generated from the following files:
src/qt/signverifymessagedialog.h
src/qt/signverifymessagedialog.cpp
Released under the MIT license