Dash Core: CDBBatch Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CDBBatch Class Reference
Batch of changes queued to be written to a CDBWrapper.
#include <dbwrapper.h>
Public Member Functions
CDBBatch (const CDBWrapper &_parent)
void Clear ()
template<typename K , typename V >
void Write (const K &key, const V &value)
template<typename V >
void Write (const CDataStream &_ssKey, const V &value)
template<typename K >
void Erase (const K &key)
void Erase (const CDataStream &_ssKey)
size_t SizeEstimate () const
Private Attributes
const CDBWrapper & parent
leveldb::WriteBatch batch
CDataStream ssKey
CDataStream ssValue
size_t size_estimate
Friends
class CDBWrapper
Detailed Description
Batch of changes queued to be written to a CDBWrapper.
Definition at line 49 of file dbwrapper.h.
Constructor & Destructor Documentation
CDBBatch()
CDBBatch::CDBBatch (const CDBWrapper & _parent) inline explicit
Parameters
[in] parent CDBWrapper that this batch is to be submitted to
Definition at line 66 of file dbwrapper.h.
Member Function Documentation
Clear()
void CDBBatch::Clear () inline
Definition at line 68 of file dbwrapper.h.
References batch, and size_estimate.
Referenced by CCoinsViewDB::BatchWrite(), llmq::CRecoveredSigsDb::CleanupOldRecoveredSigs(), CEvoDB::CommitRootTransaction(), and CCoinsViewDB::Upgrade().
Erase() [1/2]
template<typename K > void CDBBatch::Erase (const K & key) inline
Definition at line 104 of file dbwrapper.h.
References CDataStream::clear(), DBWRAPPER_PREALLOC_KEY_SIZE, CDataStream::reserve(), and ssKey.
Referenced by CCoinsViewDB::BatchWrite(), llmq::CRecoveredSigsDb::CleanupOldRecoveredSigs(), llmq::CRecoveredSigsDb::CleanupOldVotes(), llmq::CRecoveredSigsDb::ConvertInvalidTimeKeys(), CDBWrapper::Erase(), CBlockTreeDB::EraseAddressIndex(), llmq::CInstantSendDb::RemoveArchivedInstantSendLocks(), llmq::CInstantSendDb::RemoveConfirmedInstantSendLocks(), llmq::CInstantSendDb::RemoveInstantSendLock(), llmq::CRecoveredSigsDb::RemoveRecoveredSig(), CBlockTreeDB::UpdateAddressUnspentIndex(), CBlockTreeDB::UpdateSpentIndex(), and CCoinsViewDB::Upgrade().
Erase() [2/2]
void CDBBatch::Erase (const CDataStream & _ssKey) inline
Definition at line 112 of file dbwrapper.h.
References batch, CDataStream::data(), CDataStream::size(), and size_estimate.
SizeEstimate()
size_t CDBBatch::SizeEstimate () const inline
Definition at line 123 of file dbwrapper.h.
References size_estimate.
Referenced by CCoinsViewDB::BatchWrite(), llmq::CRecoveredSigsDb::CleanupOldRecoveredSigs(), and CCoinsViewDB::Upgrade().
Write() [1/2]
template<typename K , typename V > void CDBBatch::Write (const K & key, const V & value) inline
Definition at line 75 of file dbwrapper.h.
References CDataStream::clear(), DBWRAPPER_PREALLOC_KEY_SIZE, CDataStream::reserve(), and ssKey.
Referenced by llmq::CRecoveredSigsDb::AddVoteTimeKeys(), CCoinsViewDB::BatchWrite(), llmq::CRecoveredSigsDb::ConvertInvalidTimeKeys(), CBlockTreeDB::UpdateAddressUnspentIndex(), CBlockTreeDB::UpdateSpentIndex(), CCoinsViewDB::Upgrade(), CDeterministicMNManager::UpgradeDiff(), CDBWrapper::Write(), CBlockTreeDB::WriteAddressIndex(), CBlockTreeDB::WriteBatchSync(), llmq::CInstantSendDb::WriteInstantSendLockArchived(), llmq::CInstantSendDb::WriteNewInstantSendLock(), llmq::CRecoveredSigsDb::WriteRecoveredSig(), CBlockTreeDB::WriteTimestampIndex(), CBlockTreeDB::WriteTxIndex(), and llmq::CRecoveredSigsDb::WriteVoteForId().
Write() [2/2]
template<typename V > void CDBBatch::Write (const CDataStream & _ssKey, const V & value) inline
Definition at line 84 of file dbwrapper.h.
References batch, CDataStream::clear(), CDataStream::data(), DBWRAPPER_PREALLOC_VALUE_SIZE, dbwrapper_private::GetObfuscateKey(), parent, CDataStream::reserve(), CDataStream::size(), size_estimate, ssValue, and CDataStream::Xor().
Friends And Related Function Documentation
CDBWrapper
friend class CDBWrapper friend
Definition at line 51 of file dbwrapper.h.
Member Data Documentation
batch
leveldb::WriteBatch CDBBatch::batch private
Definition at line 55 of file dbwrapper.h.
Referenced by Clear(), Erase(), Write(), and CDBWrapper::WriteBatch().
parent
const CDBWrapper& CDBBatch::parent private
Definition at line 54 of file dbwrapper.h.
Referenced by Write().
size_estimate
size_t CDBBatch::size_estimate private
Definition at line 60 of file dbwrapper.h.
Referenced by Clear(), Erase(), SizeEstimate(), and Write().
ssKey
CDataStream CDBBatch::ssKey private
Definition at line 57 of file dbwrapper.h.
Referenced by Erase(), and Write().
ssValue
CDataStream CDBBatch::ssValue private
Definition at line 58 of file dbwrapper.h.
Referenced by Write().
The documentation for this class was generated from the following file:
src/dbwrapper.h
Released under the MIT license