Dash Core: llmq::CSigSharesManager Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CSigSharesManager Class Reference
#include <quorums_signing_shares.h>
Public Member Functions
CSigSharesManager ()
~CSigSharesManager ()
void StartWorkerThread ()
void StopWorkerThread ()
void RegisterAsRecoveredSigsListener ()
void UnregisterAsRecoveredSigsListener ()
void InterruptWorkerThread ()
void ProcessMessage (CNode *pnode, const std::string &strCommand, CDataStream &vRecv, CConnman &connman)
void AsyncSign (const CQuorumCPtr &quorum, const uint256 &id, const uint256 &msgHash)
void Sign (const CQuorumCPtr &quorum, const uint256 &id, const uint256 &msgHash)
void ForceReAnnouncement (const CQuorumCPtr &quorum, Consensus::LLMQType llmqType, const uint256 &id, const uint256 &msgHash)
void HandleNewRecoveredSig (const CRecoveredSig &recoveredSig)
Public Member Functions inherited from llmq::CRecoveredSigsListener
virtual ~CRecoveredSigsListener ()
Static Public Member Functions
static CDeterministicMNCPtr SelectMemberForRecovery (const CQuorumCPtr &quorum, const uint256 &id, int attempt)
Private Member Functions
bool ProcessMessageSigSesAnn (CNode *pfrom, const CSigSesAnn &ann, CConnman &connman)
bool ProcessMessageSigSharesInv (CNode *pfrom, const CSigSharesInv &inv, CConnman &connman)
bool ProcessMessageGetSigShares (CNode *pfrom, const CSigSharesInv &inv, CConnman &connman)
bool ProcessMessageBatchedSigShares (CNode *pfrom, const CBatchedSigShares &batchedSigShares, CConnman &connman)
void ProcessMessageSigShare (NodeId fromId, const CSigShare &sigShare, CConnman &connman)
bool VerifySigSharesInv (NodeId from, Consensus::LLMQType llmqType, const CSigSharesInv &inv)
bool PreVerifyBatchedSigShares (NodeId nodeId, const CSigSharesNodeState::SessionInfo &session, const CBatchedSigShares &batchedSigShares, bool &retBan)
void CollectPendingSigSharesToVerify (size_t maxUniqueSessions, std::unordered_map< NodeId, std::vector< CSigShare >> &retSigShares, std::unordered_map< std::pair< Consensus::LLMQType, uint256 >, CQuorumCPtr, StaticSaltedHasher > &retQuorums)
bool ProcessPendingSigShares (CConnman &connman)
void ProcessPendingSigSharesFromNode (NodeId nodeId, const std::vector< CSigShare > &sigShares, const std::unordered_map< std::pair< Consensus::LLMQType, uint256 >, CQuorumCPtr, StaticSaltedHasher > &quorums, CConnman &connman)
void ProcessSigShare (NodeId nodeId, const CSigShare &sigShare, CConnman &connman, const CQuorumCPtr &quorum)
void TryRecoverSig (const CQuorumCPtr &quorum, const uint256 &id, const uint256 &msgHash, CConnman &connman)
bool GetSessionInfoByRecvId (NodeId nodeId, uint32_t sessionId, CSigSharesNodeState::SessionInfo &retInfo)
CSigShare RebuildSigShare (const CSigSharesNodeState::SessionInfo &session, const CBatchedSigShares &batchedSigShares, size_t idx)
void Cleanup ()
void RemoveSigSharesForSession (const uint256 &signHash)
void RemoveBannedNodeStates ()
void BanNode (NodeId nodeId)
bool SendMessages ()
void CollectSigSharesToRequest (std::unordered_map< NodeId, std::unordered_map< uint256, CSigSharesInv, StaticSaltedHasher >> &sigSharesToRequest)
void CollectSigSharesToSend (std::unordered_map< NodeId, std::unordered_map< uint256, CBatchedSigShares, StaticSaltedHasher >> &sigSharesToSend)
void CollectSigSharesToSendConcentrated (std::unordered_map< NodeId, std::vector< CSigShare >> &sigSharesToSend, const std::vector< CNode *> &vNodes)
void CollectSigSharesToAnnounce (std::unordered_map< NodeId, std::unordered_map< uint256, CSigSharesInv, StaticSaltedHasher >> &sigSharesToAnnounce)
bool SignPendingSigShares ()
void WorkThreadMain ()
Private Attributes
const size_t MAX_MSGS_CNT_QSIGSESANN = 100
const size_t MAX_MSGS_CNT_QGETSIGSHARES = 200
const size_t MAX_MSGS_CNT_QSIGSHARESINV = 200
const size_t MAX_MSGS_TOTAL_BATCHED_SIGS = 400
const int64_t EXP_SEND_FOR_RECOVERY_TIMEOUT = 2000
const int64_t MAX_SEND_FOR_RECOVERY_TIMEOUT = 10000
const size_t MAX_MSGS_SIG_SHARES = 32
CCriticalSection cs
std::thread workThread
CThreadInterrupt workInterrupt
SigShareMap< CSigShare > sigShares
std::unordered_map< uint256, CSignedSession, StaticSaltedHasher > signedSessions
std::unordered_map< uint256, int64_t, StaticSaltedHasher > timeSeenForSessions
std::unordered_map< NodeId, CSigSharesNodeState > nodeStates
SigShareMap< std::pair< NodeId, int64_t > > sigSharesRequested
SigShareMap< bool > sigSharesToAnnounce
std::vector< std::tuple< const CQuorumCPtr, uint256, uint256 > > pendingSigns
FastRandomContext rnd
int64_t lastCleanupTime {0}
std::atomic< uint32_t > recoveredSigsCounter {0}
Static Private Attributes
static const int64_t SESSION_NEW_SHARES_TIMEOUT = 60
static const int64_t SIG_SHARE_REQUEST_TIMEOUT = 5
Detailed Description
Definition at line 355 of file quorums_signing_shares.h.
Constructor & Destructor Documentation
CSigSharesManager()
llmq::CSigSharesManager::CSigSharesManager ()
Definition at line 185 of file quorums_signing_shares.cpp.
References CThreadInterrupt::reset(), and workInterrupt.
~CSigSharesManager()
llmq::CSigSharesManager::~CSigSharesManager ()
Definition at line 190 of file quorums_signing_shares.cpp.
Member Function Documentation
AsyncSign()
void llmq::CSigSharesManager::AsyncSign (const CQuorumCPtr & quorum, const uint256 & id, const uint256 & msgHash)
Definition at line 1537 of file quorums_signing_shares.cpp.
References cs, LOCK, pendingSigns, and quorum().
Referenced by llmq::CSigningManager::AsyncSignIfMember(), and quorum_sigs_cmd().
BanNode()
void llmq::CSigSharesManager::BanNode (NodeId nodeId) private
Definition at line 1474 of file quorums_signing_shares.cpp.
References cs, cs_main, llmq::SigShareMap< T >::Erase(), LOCK, Misbehaving(), nodeStates, and sigSharesRequested.
Referenced by ProcessMessage(), ProcessMessageSigShare(), and ProcessPendingSigShares().
Cleanup()
void llmq::CSigSharesManager::Cleanup () private
Definition at line 1314 of file quorums_signing_shares.cpp.
References count, cs, llmq::SigShareMap< T >::Erase(), g_connman, GetAdjustedTime(), CNode::GetId(), llmq::CQuorumManager::GetQuorum(), llmq::CSigShare::GetSignHash(), llmq::CSigningManager::HasRecoveredSigForSession(), llmq::CLLMQUtils::IsQuorumActive(), lastCleanupTime, BCLog::LLMQ_SIGS, llmq::CSigShare::llmqType, LOCK, LogAcceptCategory(), LogPrint, nodeStates, quorum(), llmq::CSigShare::quorumHash, llmq::quorumManager, llmq::quorumSigningManager, RemoveSigSharesForSession(), SESSION_NEW_SHARES_TIMEOUT, sigShares, sigSharesRequested, UniValue::size(), strprintf, and timeSeenForSessions.
Referenced by WorkThreadMain().
CollectPendingSigSharesToVerify()
void llmq::CSigSharesManager::CollectPendingSigSharesToVerify (size_t maxUniqueSessions, std::unordered_map< NodeId, std::vector< CSigShare >> & retSigShares, std::unordered_map< std::pair< Consensus::LLMQType, uint256 >, CQuorumCPtr, StaticSaltedHasher > & retQuorums) private
Definition at line 579 of file quorums_signing_shares.cpp.
References cs, cs_main, llmq::CQuorumManager::GetQuorum(), llmq::CLLMQUtils::IterateNodesRandom(), LOCK, nodeStates, quorum(), llmq::quorumManager, rnd, and sigShares.
Referenced by ProcessPendingSigShares().
CollectSigSharesToAnnounce()
void llmq::CSigSharesManager::CollectSigSharesToAnnounce (std::unordered_map< NodeId, std::unordered_map< uint256, CSigSharesInv, StaticSaltedHasher >> & sigSharesToAnnounce) private
Definition at line 1073 of file quorums_signing_shares.cpp.
References AssertLockHeld(), llmq::SigShareMap< T >::Clear(), cs, llmq::SigShareMap< T >::ForEach(), g_connman, CChainParams::GetConsensus(), Consensus::Params::llmqs, llmq::CSigShare::llmqType, nodeStates, Params(), llmq::CSigShare::quorumHash, sigShares, and sigSharesToAnnounce.
Referenced by SendMessages().
CollectSigSharesToRequest()
void llmq::CSigSharesManager::CollectSigSharesToRequest (std::unordered_map< NodeId, std::unordered_map< uint256, CSigSharesInv, StaticSaltedHasher >> & sigSharesToRequest) private
Definition at line 873 of file quorums_signing_shares.cpp.
References AssertLockHeld(), cs, llmq::SigShareMap< T >::Get(), GetAdjustedTime(), CChainParams::GetConsensus(), llmq::SigShareMap< T >::GetOrAdd(), llmq::CSigningManager::HasRecoveredSigForSession(), llmq::CLLMQUtils::IsAllMembersConnectedEnabled(), BCLog::LLMQ_SIGS, Consensus::Params::llmqs, LogPrint, nodeStates, Params(), llmq::quorumSigningManager, rnd, SIG_SHARE_REQUEST_TIMEOUT, sigShares, and sigSharesRequested.
Referenced by SendMessages().
CollectSigSharesToSend()
void llmq::CSigSharesManager::CollectSigSharesToSend (std::unordered_map< NodeId, std::unordered_map< uint256, CBatchedSigShares, StaticSaltedHasher >> & sigSharesToSend) private
Definition at line 973 of file quorums_signing_shares.cpp.
References AssertLockHeld(), cs, llmq::CSigningManager::HasRecoveredSigForSession(), llmq::CLLMQUtils::IsAllMembersConnectedEnabled(), nodeStates, llmq::quorumSigningManager, llmq::CSigShare::sigShare, llmq::CBatchedSigShares::sigShares, and sigShares.
Referenced by SendMessages().
CollectSigSharesToSendConcentrated()
void llmq::CSigSharesManager::CollectSigSharesToSendConcentrated (std::unordered_map< NodeId, std::vector< CSigShare >> & sigSharesToSend, const std::vector< CNode *> & vNodes) private
Definition at line 1029 of file quorums_signing_shares.cpp.
References AssertLockHeld(), count, cs, EXP_SEND_FOR_RECOVERY_TIMEOUT, llmq::CLLMQUtils::IsAllMembersConnectedEnabled(), BCLog::LLMQ_SIGS, LogPrint, MAX_SEND_FOR_RECOVERY_TIMEOUT, SelectMemberForRecovery(), and signedSessions.
Referenced by SendMessages().
ForceReAnnouncement()
void llmq::CSigSharesManager::ForceReAnnouncement (const CQuorumCPtr & quorum, Consensus::LLMQType llmqType, const uint256 & id, const uint256 & msgHash)
Definition at line 1610 of file quorums_signing_shares.cpp.
References llmq::SigShareMap< T >::Add(), llmq::CLLMQUtils::BuildSignHash(), cs, llmq::CSigSharesNodeState::GetSessionBySignHash(), llmq::CLLMQUtils::IsAllMembersConnectedEnabled(), llmq::CSigSharesNodeState::Session::knows, LOCK, nodeStates, quorum(), llmq::CSigSharesInv::SetAll(), sigShares, and sigSharesToAnnounce.
Referenced by llmq::CSigningManager::AsyncSignIfMember().
GetSessionInfoByRecvId()
bool llmq::CSigSharesManager::GetSessionInfoByRecvId (NodeId nodeId, uint32_t sessionId, CSigSharesNodeState::SessionInfo & retInfo) private
Definition at line 1293 of file quorums_signing_shares.cpp.
References cs, LOCK, and nodeStates.
Referenced by ProcessMessageBatchedSigShares(), ProcessMessageGetSigShares(), and ProcessMessageSigSharesInv().
HandleNewRecoveredSig()
void llmq::CSigSharesManager::HandleNewRecoveredSig (const CRecoveredSig & recoveredSig) virtual
Implements llmq::CRecoveredSigsListener.
Definition at line 1638 of file quorums_signing_shares.cpp.
References llmq::CLLMQUtils::BuildSignHash(), cs, LOCK, and RemoveSigSharesForSession().
InterruptWorkerThread()
void llmq::CSigSharesManager::InterruptWorkerThread ()
Definition at line 228 of file quorums_signing_shares.cpp.
References workInterrupt.
Referenced by llmq::InterruptLLMQSystem().
PreVerifyBatchedSigShares()
bool llmq::CSigSharesManager::PreVerifyBatchedSigShares (NodeId nodeId, const CSigSharesNodeState::SessionInfo & session, const CBatchedSigShares & batchedSigShares, bool & retBan) private
Definition at line 537 of file quorums_signing_shares.cpp.
References activeMasternodeInfo, llmq::CLLMQUtils::IsQuorumActive(), BCLog::LLMQ_SIGS, llmq::CSigSharesNodeState::SessionInfo::llmqType, LogPrint, CActiveMasternodeInfo::proTxHash, llmq::CSigSharesNodeState::SessionInfo::quorum, llmq::CSigSharesNodeState::SessionInfo::quorumHash, llmq::CBatchedSigShares::sigShares, and base_blob< BITS >::ToString().
Referenced by ProcessMessageBatchedSigShares().
ProcessMessage()
void llmq::CSigSharesManager::ProcessMessage (CNode * pnode, const std::string & strCommand, CDataStream & vRecv, CConnman & connman)
Definition at line 233 of file quorums_signing_shares.cpp.
References activeMasternodeInfo, BanNode(), fMasternodeMode, CNode::GetId(), base_blob< BITS >::IsNull(), CSporkManager::IsSporkActive(), BCLog::LLMQ_SIGS, LogPrint, MAX_MSGS_CNT_QGETSIGSHARES, MAX_MSGS_CNT_QSIGSESANN, MAX_MSGS_CNT_QSIGSHARESINV, MAX_MSGS_SIG_SHARES, MAX_MSGS_TOTAL_BATCHED_SIGS, ProcessMessageBatchedSigShares(), ProcessMessageGetSigShares(), ProcessMessageSigSesAnn(), ProcessMessageSigShare(), ProcessMessageSigSharesInv(), CActiveMasternodeInfo::proTxHash, NetMsgType::QBSIGSHARES, NetMsgType::QGETSIGSHARES, NetMsgType::QSIGSESANN, NetMsgType::QSIGSHARE, NetMsgType::QSIGSHARESINV, sigShares, CDataStream::size(), SPORK_21_QUORUM_ALL_CONNECTED, and sporkManager.
Referenced by ProcessMessage().
ProcessMessageBatchedSigShares()
bool llmq::CSigSharesManager::ProcessMessageBatchedSigShares (CNode * pfrom, const CBatchedSigShares & batchedSigShares, CConnman & connman) private
Definition at line 431 of file quorums_signing_shares.cpp.
References cs, CNode::GetId(), llmq::CSigShare::GetKey(), GetSessionInfoByRecvId(), llmq::CSigningManager::HasRecoveredSigForId(), llmq::CSigShare::id, BCLog::LLMQ_SIGS, llmq::CSigShare::llmqType, LOCK, LogPrint, nodeStates, PreVerifyBatchedSigShares(), llmq::quorumSigningManager, RebuildSigShare(), llmq::CBatchedSigShares::sessionId, llmq::CSigSharesNodeState::SessionInfo::signHash, sigShares, and base_blob< BITS >::ToString().
Referenced by ProcessMessage().
ProcessMessageGetSigShares()
bool llmq::CSigSharesManager::ProcessMessageGetSigShares (CNode * pfrom, const CSigSharesInv & inv, CConnman & connman) private
Definition at line 401 of file quorums_signing_shares.cpp.
References cs, CNode::GetId(), GetSessionInfoByRecvId(), llmq::CSigningManager::HasRecoveredSigForSession(), BCLog::LLMQ_SIGS, llmq::CSigSharesNodeState::SessionInfo::llmqType, LOCK, LogPrint, nodeStates, llmq::quorumSigningManager, llmq::CSigSharesInv::sessionId, llmq::CSigSharesNodeState::SessionInfo::signHash, base_blob< BITS >::ToString(), llmq::CSigSharesInv::ToString(), and VerifySigSharesInv().
Referenced by ProcessMessage().
ProcessMessageSigSesAnn()
bool llmq::CSigSharesManager::ProcessMessageSigSesAnn (CNode * pfrom, const CSigSesAnn & ann, CConnman & connman) private
Definition at line 320 of file quorums_signing_shares.cpp.
References llmq::CLLMQUtils::BuildSignHash(), cs, CChainParams::GetConsensus(), CNode::GetId(), llmq::CQuorumManager::GetQuorum(), llmq::CSigSesAnn::id, base_blob< BITS >::IsNull(), BCLog::LLMQ_SIGS, Consensus::Params::llmqs, llmq::CSigSesAnn::llmqType, LOCK, LogPrint, llmq::CSigSesAnn::msgHash, nodeStates, Params(), quorum(), llmq::CSigSesAnn::quorumHash, llmq::quorumManager, llmq::CSigSesAnn::sessionId, base_blob< BITS >::ToString(), and llmq::CSigSesAnn::ToString().
Referenced by ProcessMessage().
ProcessMessageSigShare()
void llmq::CSigSharesManager::ProcessMessageSigShare (NodeId fromId, const CSigShare & sigShare, CConnman & connman) private
Definition at line 486 of file quorums_signing_shares.cpp.
References activeMasternodeInfo, BanNode(), cs, llmq::CSigShare::GetKey(), llmq::CQuorumManager::GetQuorum(), llmq::CSigShare::GetSignHash(), llmq::CSigningManager::HasRecoveredSigForId(), llmq::CSigShare::id, llmq::CLLMQUtils::IsQuorumActive(), BCLog::LLMQ_SIGS, llmq::CSigShare::llmqType, LOCK, LogPrint, llmq::CSigShare::msgHash, nodeStates, CActiveMasternodeInfo::proTxHash, quorum(), llmq::CSigShare::quorumHash, llmq::quorumManager, llmq::CSigShare::quorumMember, llmq::quorumSigningManager, sigShares, UniValue::size(), and base_blob< BITS >::ToString().
Referenced by ProcessMessage().
ProcessMessageSigSharesInv()
bool llmq::CSigSharesManager::ProcessMessageSigSharesInv (CNode * pfrom, const CSigSharesInv & inv, CConnman & connman) private
Definition at line 364 of file quorums_signing_shares.cpp.
References cs, CNode::GetId(), GetSessionInfoByRecvId(), llmq::CSigningManager::HasRecoveredSigForSession(), BCLog::LLMQ_SIGS, llmq::CSigSharesNodeState::SessionInfo::llmqType, LOCK, LogPrint, nodeStates, llmq::CSigSharesNodeState::SessionInfo::quorum, llmq::CSigSharesNodeState::SessionInfo::quorumHash, llmq::quorumSigningManager, llmq::CSigSharesInv::sessionId, llmq::CSigSharesNodeState::SessionInfo::signHash, base_blob< BITS >::ToString(), llmq::CSigSharesInv::ToString(), and VerifySigSharesInv().
Referenced by ProcessMessage().
ProcessPendingSigShares()
bool llmq::CSigSharesManager::ProcessPendingSigShares (CConnman & connman) private
Definition at line 641 of file quorums_signing_shares.cpp.
References CBLSBatchVerifier< SourceId, MessageId >::badSources, BanNode(), CollectPendingSigSharesToVerify(), cxxtimer::Timer::count(), llmq::CSigningManager::HasRecoveredSigForId(), BCLog::LLMQ_SIGS, LogPrint, LogPrintf, ProcessPendingSigSharesFromNode(), CBLSBatchVerifier< SourceId, MessageId >::PushMessage(), quorum(), llmq::quorumSigningManager, cxxtimer::Timer::stop(), and CBLSBatchVerifier< SourceId, MessageId >::Verify().
Referenced by WorkThreadMain().
ProcessPendingSigSharesFromNode()
void llmq::CSigSharesManager::ProcessPendingSigSharesFromNode (NodeId nodeId, const std::vector< CSigShare > & sigShares, const std::unordered_map< std::pair< Consensus::LLMQType, uint256 >, CQuorumCPtr, StaticSaltedHasher > & quorums, CConnman & connman) private
Definition at line 715 of file quorums_signing_shares.cpp.
References cxxtimer::Timer::count(), BCLog::LLMQ_SIGS, LogPrint, nodeStates, ProcessSigShare(), sigShares, and cxxtimer::Timer::stop().
Referenced by ProcessPendingSigShares().
ProcessSigShare()
void llmq::CSigSharesManager::ProcessSigShare (NodeId nodeId, const CSigShare & sigShare, CConnman & connman, const CQuorumCPtr & quorum) private
Definition at line 734 of file quorums_signing_shares.cpp.
References activeMasternodeInfo, llmq::SigShareMap< T >::Add(), cs, GetAdjustedTime(), llmq::CSigShare::GetKey(), CConnman::GetMasternodeQuorumNodes(), llmq::CSigShare::GetSignHash(), llmq::CSigningManager::HasRecoveredSigForId(), llmq::CSigShare::id, llmq::CLLMQUtils::IsAllMembersConnectedEnabled(), llmq::CSigShare::llmqType, LOCK, llmq::CSigShare::msgHash, nodeStates, CActiveMasternodeInfo::proTxHash, quorum(), llmq::CSigShare::quorumHash, llmq::CSigShare::quorumMember, llmq::quorumSigningManager, sigShares, sigSharesToAnnounce, timeSeenForSessions, TryRecoverSig(), and UniValue::type().
Referenced by ProcessPendingSigSharesFromNode(), and Sign().
RebuildSigShare()
CSigShare llmq::CSigSharesManager::RebuildSigShare (const CSigSharesNodeState::SessionInfo & session, const CBatchedSigShares & batchedSigShares, size_t idx) private
Definition at line 1299 of file quorums_signing_shares.cpp.
References llmq::CSigShare::id, llmq::CSigSharesNodeState::SessionInfo::id, llmq::CSigShare::llmqType, llmq::CSigSharesNodeState::SessionInfo::llmqType, llmq::CSigShare::msgHash, llmq::CSigSharesNodeState::SessionInfo::msgHash, llmq::CSigShare::quorumHash, llmq::CSigSharesNodeState::SessionInfo::quorumHash, llmq::CSigShare::quorumMember, llmq::CSigShare::sigShare, llmq::CBatchedSigShares::sigShares, and llmq::CSigShare::UpdateKey().
Referenced by ProcessMessageBatchedSigShares().
RegisterAsRecoveredSigsListener()
void llmq::CSigSharesManager::RegisterAsRecoveredSigsListener ()
Definition at line 218 of file quorums_signing_shares.cpp.
References llmq::quorumSigningManager, and llmq::CSigningManager::RegisterRecoveredSigsListener().
Referenced by llmq::StartLLMQSystem().
RemoveBannedNodeStates()
void llmq::CSigSharesManager::RemoveBannedNodeStates () private
Definition at line 1455 of file quorums_signing_shares.cpp.
References cs, cs_main, llmq::SigShareMap< T >::Erase(), IsBanned(), LOCK2, nodeStates, and sigSharesRequested.
Referenced by WorkThreadMain().
RemoveSigSharesForSession()
void llmq::CSigSharesManager::RemoveSigSharesForSession (const uint256 & signHash) private
Definition at line 1441 of file quorums_signing_shares.cpp.
References llmq::SigShareMap< T >::EraseAllForSignHash(), nodeStates, signedSessions, sigShares, sigSharesRequested, sigSharesToAnnounce, and timeSeenForSessions.
Referenced by Cleanup(), and HandleNewRecoveredSig().
SelectMemberForRecovery()
CDeterministicMNCPtr llmq::CSigSharesManager::SelectMemberForRecovery (const CQuorumCPtr & quorum, const uint256 & id, int attempt) static
Definition at line 858 of file quorums_signing_shares.cpp.
References quorum(), SerializeHash(), and UniValue::size().
Referenced by CollectSigSharesToSendConcentrated(), and quorum_selectquorum().
SendMessages()
bool llmq::CSigSharesManager::SendMessages () private
Definition at line 1125 of file quorums_signing_shares.cpp.
References llmq::CLLMQUtils::BuildSignHash(), CollectSigSharesToAnnounce(), CollectSigSharesToRequest(), CollectSigSharesToSend(), CollectSigSharesToSendConcentrated(), cs, CConnman::FullyConnectedOnly, g_connman, llmq::CSigSesAnn::id, BCLog::LLMQ_SIGS, llmq::CSigSesAnn::llmqType, LOCK, LogPrint, MAX_MSGS_CNT_QGETSIGSHARES, MAX_MSGS_CNT_QSIGSESANN, MAX_MSGS_CNT_QSIGSHARESINV, MAX_MSGS_SIG_SHARES, MAX_MSGS_TOTAL_BATCHED_SIGS, llmq::CSigSesAnn::msgHash, nodeStates, NetMsgType::QBSIGSHARES, NetMsgType::QGETSIGSHARES, NetMsgType::QSIGSESANN, NetMsgType::QSIGSHARE, NetMsgType::QSIGSHARESINV, llmq::CSigSesAnn::quorumHash, llmq::CSigSesAnn::sessionId, and sigSharesToAnnounce.
Referenced by WorkThreadMain().
Sign()
void llmq::CSigSharesManager::Sign (const CQuorumCPtr & quorum, const uint256 & id, const uint256 & msgHash)
Definition at line 1558 of file quorums_signing_shares.cpp.
References activeMasternodeInfo, llmq::CLLMQUtils::BuildSignHash(), cxxtimer::Timer::count(), cs, g_connman, CBLSLazyWrapper< BLSObject >::Get(), llmq::CSigShare::GetSignHash(), llmq::CSigShare::id, llmq::CLLMQUtils::IsAllMembersConnectedEnabled(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), BCLog::LLMQ_SIGS, llmq::CSigShare::llmqType, LOCK, LogPrint, LogPrintf, llmq::CSigShare::msgHash, ProcessSigShare(), CActiveMasternodeInfo::proTxHash, quorum(), llmq::CSigShare::quorumHash, llmq::CSigShare::quorumMember, CBLSLazyWrapper< BLSObject >::Set(), CBLSSecretKey::Sign(), signedSessions, llmq::CSigShare::sigShare, base_blob< BITS >::ToString(), UniValue::type(), and llmq::CSigShare::UpdateKey().
Referenced by SignPendingSigShares().
SignPendingSigShares()
bool llmq::CSigSharesManager::SignPendingSigShares () private
Definition at line 1543 of file quorums_signing_shares.cpp.
References cs, LOCK, pendingSigns, and Sign().
Referenced by WorkThreadMain().
StartWorkerThread()
void llmq::CSigSharesManager::StartWorkerThread ()
Definition at line 194 of file quorums_signing_shares.cpp.
References TraceThread(), workThread, and WorkThreadMain().
Referenced by llmq::StartLLMQSystem().
StopWorkerThread()
void llmq::CSigSharesManager::StopWorkerThread ()
Definition at line 206 of file quorums_signing_shares.cpp.
References workInterrupt, and workThread.
Referenced by llmq::StopLLMQSystem().
TryRecoverSig()
void llmq::CSigSharesManager::TryRecoverSig (const CQuorumCPtr & quorum, const uint256 & id, const uint256 & msgHash, CConnman & connman) private
Definition at line 788 of file quorums_signing_shares.cpp.
References llmq::CLLMQUtils::BuildSignHash(), cxxtimer::Timer::count(), cs, CBLSId::FromHash(), llmq::CSigningManager::HasRecoveredSigForId(), BCLog::LLMQ_SIGS, llmq::CRecoveredSig::llmqType, LOCK, LogPrint, LogPrintf, llmq::CSigningManager::ProcessRecoveredSig(), quorum(), llmq::quorumSigningManager, CBLSSignature::Recover(), recoveredSigsCounter, sigShares, base_blob< BITS >::ToString(), UniValue::type(), and CBLSSignature::VerifyInsecure().
Referenced by ProcessSigShare().
UnregisterAsRecoveredSigsListener()
void llmq::CSigSharesManager::UnregisterAsRecoveredSigsListener ()
Definition at line 223 of file quorums_signing_shares.cpp.
References llmq::quorumSigningManager, and llmq::CSigningManager::UnregisterRecoveredSigsListener().
Referenced by llmq::StopLLMQSystem().
VerifySigSharesInv()
bool llmq::CSigSharesManager::VerifySigSharesInv (NodeId from, Consensus::LLMQType llmqType, const CSigSharesInv & inv) private
Definition at line 354 of file quorums_signing_shares.cpp.
References CChainParams::GetConsensus(), llmq::CSigSharesInv::inv, Consensus::Params::llmqs, and Params().
Referenced by ProcessMessageGetSigShares(), and ProcessMessageSigSharesInv().
WorkThreadMain()
void llmq::CSigSharesManager::WorkThreadMain () private
Definition at line 1501 of file quorums_signing_shares.cpp.
References llmq::CSigningManager::Cleanup(), Cleanup(), g_connman, GetTimeMillis(), llmq::CSigningManager::ProcessPendingRecoveredSigs(), ProcessPendingSigShares(), llmq::quorumSigningManager, RemoveBannedNodeStates(), SendMessages(), SignPendingSigShares(), CThreadInterrupt::sleep_for(), and workInterrupt.
Referenced by StartWorkerThread().
Member Data Documentation
cs
CCriticalSection llmq::CSigSharesManager::cs private
Definition at line 372 of file quorums_signing_shares.h.
Referenced by AsyncSign(), BanNode(), Cleanup(), CollectPendingSigSharesToVerify(), CollectSigSharesToAnnounce(), CollectSigSharesToRequest(), CollectSigSharesToSend(), CollectSigSharesToSendConcentrated(), ForceReAnnouncement(), GetSessionInfoByRecvId(), HandleNewRecoveredSig(), ProcessMessageBatchedSigShares(), ProcessMessageGetSigShares(), ProcessMessageSigSesAnn(), ProcessMessageSigShare(), ProcessMessageSigSharesInv(), ProcessSigShare(), RemoveBannedNodeStates(), SendMessages(), Sign(), SignPendingSigShares(), and TryRecoverSig().
EXP_SEND_FOR_RECOVERY_TIMEOUT
const int64_t llmq::CSigSharesManager::EXP_SEND_FOR_RECOVERY_TIMEOUT = 2000 private
Definition at line 367 of file quorums_signing_shares.h.
Referenced by CollectSigSharesToSendConcentrated().
lastCleanupTime
int64_t llmq::CSigSharesManager::lastCleanupTime {0} private
Definition at line 392 of file quorums_signing_shares.h.
Referenced by Cleanup().
MAX_MSGS_CNT_QGETSIGSHARES
const size_t llmq::CSigSharesManager::MAX_MSGS_CNT_QGETSIGSHARES = 200 private
Definition at line 362 of file quorums_signing_shares.h.
Referenced by ProcessMessage(), and SendMessages().
MAX_MSGS_CNT_QSIGSESANN
const size_t llmq::CSigSharesManager::MAX_MSGS_CNT_QSIGSESANN = 100 private
Definition at line 361 of file quorums_signing_shares.h.
Referenced by ProcessMessage(), and SendMessages().
MAX_MSGS_CNT_QSIGSHARESINV
const size_t llmq::CSigSharesManager::MAX_MSGS_CNT_QSIGSHARESINV = 200 private
Definition at line 363 of file quorums_signing_shares.h.
Referenced by ProcessMessage(), and SendMessages().
MAX_MSGS_SIG_SHARES
const size_t llmq::CSigSharesManager::MAX_MSGS_SIG_SHARES = 32 private
Definition at line 369 of file quorums_signing_shares.h.
Referenced by ProcessMessage(), and SendMessages().
MAX_MSGS_TOTAL_BATCHED_SIGS
const size_t llmq::CSigSharesManager::MAX_MSGS_TOTAL_BATCHED_SIGS = 400 private
Definition at line 365 of file quorums_signing_shares.h.
Referenced by ProcessMessage(), and SendMessages().
MAX_SEND_FOR_RECOVERY_TIMEOUT
const int64_t llmq::CSigSharesManager::MAX_SEND_FOR_RECOVERY_TIMEOUT = 10000 private
Definition at line 368 of file quorums_signing_shares.h.
Referenced by CollectSigSharesToSendConcentrated().
nodeStates
std::unordered_map<NodeId, CSigSharesNodeState> llmq::CSigSharesManager::nodeStates private
Definition at line 383 of file quorums_signing_shares.h.
Referenced by BanNode(), Cleanup(), CollectPendingSigSharesToVerify(), CollectSigSharesToAnnounce(), CollectSigSharesToRequest(), CollectSigSharesToSend(), ForceReAnnouncement(), GetSessionInfoByRecvId(), ProcessMessageBatchedSigShares(), ProcessMessageGetSigShares(), ProcessMessageSigSesAnn(), ProcessMessageSigShare(), ProcessMessageSigSharesInv(), ProcessPendingSigSharesFromNode(), ProcessSigShare(), RemoveBannedNodeStates(), RemoveSigSharesForSession(), and SendMessages().
pendingSigns
std::vector<std::tuple<const CQuorumCPtr, uint256, uint256> > llmq::CSigSharesManager::pendingSigns private
Definition at line 387 of file quorums_signing_shares.h.
Referenced by AsyncSign(), and SignPendingSigShares().
recoveredSigsCounter
std::atomic<uint32_t> llmq::CSigSharesManager::recoveredSigsCounter {0} private
Definition at line 393 of file quorums_signing_shares.h.
Referenced by TryRecoverSig().
rnd
FastRandomContext llmq::CSigSharesManager::rnd private
Definition at line 390 of file quorums_signing_shares.h.
Referenced by CollectPendingSigSharesToVerify(), and CollectSigSharesToRequest().
SESSION_NEW_SHARES_TIMEOUT
const int64_t llmq::CSigSharesManager::SESSION_NEW_SHARES_TIMEOUT = 60 static private
Definition at line 357 of file quorums_signing_shares.h.
Referenced by Cleanup().
SIG_SHARE_REQUEST_TIMEOUT
const int64_t llmq::CSigSharesManager::SIG_SHARE_REQUEST_TIMEOUT = 5 static private
Definition at line 358 of file quorums_signing_shares.h.
Referenced by CollectSigSharesToRequest().
signedSessions
std::unordered_map<uint256, CSignedSession, StaticSaltedHasher> llmq::CSigSharesManager::signedSessions private
Definition at line 378 of file quorums_signing_shares.h.
Referenced by CollectSigSharesToSendConcentrated(), RemoveSigSharesForSession(), and Sign().
sigShares
SigShareMap<CSigShare> llmq::CSigSharesManager::sigShares private
Definition at line 377 of file quorums_signing_shares.h.
Referenced by Cleanup(), CollectPendingSigSharesToVerify(), CollectSigSharesToAnnounce(), CollectSigSharesToRequest(), CollectSigSharesToSend(), ForceReAnnouncement(), ProcessMessage(), ProcessMessageBatchedSigShares(), ProcessMessageSigShare(), ProcessPendingSigSharesFromNode(), ProcessSigShare(), RemoveSigSharesForSession(), and TryRecoverSig().
sigSharesRequested
SigShareMap<std::pair<NodeId, int64_t> > llmq::CSigSharesManager::sigSharesRequested private
Definition at line 384 of file quorums_signing_shares.h.
Referenced by BanNode(), Cleanup(), CollectSigSharesToRequest(), RemoveBannedNodeStates(), and RemoveSigSharesForSession().
sigSharesToAnnounce
SigShareMap<bool> llmq::CSigSharesManager::sigSharesToAnnounce private
Definition at line 385 of file quorums_signing_shares.h.
Referenced by CollectSigSharesToAnnounce(), ForceReAnnouncement(), ProcessSigShare(), RemoveSigSharesForSession(), and SendMessages().
timeSeenForSessions
std::unordered_map<uint256, int64_t, StaticSaltedHasher> llmq::CSigSharesManager::timeSeenForSessions private
Definition at line 381 of file quorums_signing_shares.h.
Referenced by Cleanup(), ProcessSigShare(), and RemoveSigSharesForSession().
workInterrupt
CThreadInterrupt llmq::CSigSharesManager::workInterrupt private
Definition at line 375 of file quorums_signing_shares.h.
Referenced by CSigSharesManager(), InterruptWorkerThread(), StopWorkerThread(), and WorkThreadMain().
workThread
std::thread llmq::CSigSharesManager::workThread private
Definition at line 374 of file quorums_signing_shares.h.
Referenced by StartWorkerThread(), and StopWorkerThread().
The documentation for this class was generated from the following files:
src/llmq/quorums_signing_shares.h
src/llmq/quorums_signing_shares.cpp
Released under the MIT license