Dash Core: LimitedString< Limit > Class Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
LimitedString< Limit > Class Template Reference
#include <serialize.h>
Public Member Functions
LimitedString (std::string &string)
template<typename Stream >
void Unserialize (Stream &s, int, int=0)
template<typename Stream >
void Serialize (Stream &s, int, int=0) const
unsigned int GetSerializeSize (int, int=0) const
Protected Attributes
std::string & string
Detailed Description
template<size_t Limit>
class LimitedString< Limit >
Definition at line 460 of file serialize.h.
Constructor & Destructor Documentation
LimitedString()
template<size_t Limit> LimitedString< Limit >::LimitedString (std::string & string) inline
Definition at line 465 of file serialize.h.
Member Function Documentation
GetSerializeSize()
template<size_t Limit> unsigned int LimitedString< Limit >::GetSerializeSize (int , int = 0) const inline
Definition at line 487 of file serialize.h.
References GetSizeOfCompactSize().
Serialize()
template<size_t Limit> template<typename Stream > void LimitedString< Limit >::Serialize (Stream & s, int , int = 0) const inline
Definition at line 480 of file serialize.h.
References WriteCompactSize().
Unserialize()
template<size_t Limit> template<typename Stream > void LimitedString< Limit >::Unserialize (Stream & s, int , int = 0) inline
Definition at line 468 of file serialize.h.
References ReadCompactSize().
Member Data Documentation
string
template<size_t Limit> std::string& LimitedString< Limit >::string protected
Definition at line 463 of file serialize.h.
The documentation for this class was generated from the following file:
src/serialize.h
Released under the MIT license