Dash Core: CScriptCheck Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CScriptCheck Class Reference
Closure representing one script verification Note that this stores references to the spending transaction.
#include <validation.h>
Public Member Functions
CScriptCheck ()
CScriptCheck (const CCoins &txFromIn, const CTransaction &txToIn, unsigned int nInIn, unsigned int nFlagsIn, bool cacheIn)
bool operator() ()
void swap (CScriptCheck &check)
ScriptError GetScriptError () const
Private Attributes
CScript scriptPubKey
const CTransaction * ptxTo
unsigned int nIn
unsigned int nFlags
bool cacheStore
ScriptError error
Detailed Description
Closure representing one script verification Note that this stores references to the spending transaction.
Definition at line 686 of file validation.h.
Constructor & Destructor Documentation
CScriptCheck() [1/2]
CScriptCheck::CScriptCheck () inline
Definition at line 697 of file validation.h.
CScriptCheck() [2/2]
CScriptCheck::CScriptCheck (const CCoins & txFromIn, const CTransaction & txToIn, unsigned int nInIn, unsigned int nFlagsIn, bool cacheIn) inline
Definition at line 698 of file validation.h.
Member Function Documentation
GetScriptError()
ScriptError CScriptCheck::GetScriptError () const inline
Definition at line 713 of file validation.h.
References error.
Referenced by CheckInputs().
operator()()
bool CScriptCheck::operator() ()
Definition at line 1467 of file validation.cpp.
References error(), and VerifyScript().
swap()
void CScriptCheck::swap (CScriptCheck & check) inline
Definition at line 704 of file validation.h.
References cacheStore, error, nFlags, nIn, ptxTo, scriptPubKey, and prevector< N, T, Size, Diff >::swap().
Referenced by CheckInputs().
Member Data Documentation
cacheStore
bool CScriptCheck::cacheStore private
Definition at line 693 of file validation.h.
Referenced by swap().
error
ScriptError CScriptCheck::error private
Definition at line 694 of file validation.h.
Referenced by GetScriptError(), and swap().
nFlags
unsigned int CScriptCheck::nFlags private
Definition at line 692 of file validation.h.
Referenced by swap().
nIn
unsigned int CScriptCheck::nIn private
Definition at line 691 of file validation.h.
Referenced by swap().
ptxTo
const CTransaction* CScriptCheck::ptxTo private
Definition at line 690 of file validation.h.
Referenced by swap().
scriptPubKey
CScript CScriptCheck::scriptPubKey private
Definition at line 689 of file validation.h.
Referenced by swap().
The documentation for this class was generated from the following files:
src/validation.h
src/validation.cpp
Released under the MIT license