Dash Core: CSimplifiedMNListEntry Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CSimplifiedMNListEntry Class Reference
#include <simplifiedmns.h>
Public Member Functions
CSimplifiedMNListEntry ()
CSimplifiedMNListEntry (const CDeterministicMN &dmn)
bool operator== (const CSimplifiedMNListEntry &rhs) const
bool operator!= (const CSimplifiedMNListEntry &rhs) const
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
uint256 CalcHash () const
std::string ToString () const
void ToJson (UniValue &obj) const
Public Attributes
uint256 proRegTxHash
uint256 confirmedHash
CService service
CBLSLazyPublicKey pubKeyOperator
CKeyID keyIDVoting
bool isValid
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 24 of file simplifiedmns.h.
Constructor & Destructor Documentation
CSimplifiedMNListEntry() [1/2]
CSimplifiedMNListEntry::CSimplifiedMNListEntry () inline
Definition at line 35 of file simplifiedmns.h.
CSimplifiedMNListEntry() [2/2]
CSimplifiedMNListEntry::CSimplifiedMNListEntry (const CDeterministicMN & dmn) explicit
Definition at line 20 of file simplifiedmns.cpp.
Member Function Documentation
CalcHash()
uint256 CSimplifiedMNListEntry::CalcHash () const
Definition at line 30 of file simplifiedmns.cpp.
References CLIENT_VERSION, CHashWriter::GetHash(), and SER_GETHASH.
operator!=()
bool CSimplifiedMNListEntry::operator!= (const CSimplifiedMNListEntry & rhs) const inline
Definition at line 48 of file simplifiedmns.h.
operator==()
bool CSimplifiedMNListEntry::operator== (const CSimplifiedMNListEntry & rhs) const inline
Definition at line 38 of file simplifiedmns.h.
References confirmedHash, isValid, keyIDVoting, proRegTxHash, pubKeyOperator, and service.
SerializationOp()
template<typename Stream , typename Operation > void CSimplifiedMNListEntry::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 57 of file simplifiedmns.h.
References confirmedHash, isValid, keyIDVoting, proRegTxHash, pubKeyOperator, READWRITE, and service.
ToJson()
void CSimplifiedMNListEntry::ToJson (UniValue & obj) const
Definition at line 43 of file simplifiedmns.cpp.
References UniValue::clear(), confirmedHash, EncodeDestination(), CBLSLazyWrapper< BLSObject >::Get(), isValid, keyIDVoting, Pair(), proRegTxHash, pubKeyOperator, UniValue::push_back(), service, UniValue::setObject(), base_blob< BITS >::ToString(), CService::ToString(), and CBLSWrapper< ImplType, _SerSize, C >::ToString().
ToString()
std::string CSimplifiedMNListEntry::ToString () const
Definition at line 37 of file simplifiedmns.cpp.
References confirmedHash, EncodeDestination(), CBLSLazyWrapper< BLSObject >::Get(), isValid, keyIDVoting, proRegTxHash, pubKeyOperator, service, strprintf, base_blob< BITS >::ToString(), CService::ToString(), and CBLSWrapper< ImplType, _SerSize, C >::ToString().
Member Data Documentation
ADD_SERIALIZE_METHODS
CSimplifiedMNListEntry::ADD_SERIALIZE_METHODS
Definition at line 54 of file simplifiedmns.h.
confirmedHash
uint256 CSimplifiedMNListEntry::confirmedHash
Definition at line 28 of file simplifiedmns.h.
Referenced by operator==(), SerializationOp(), ToJson(), and ToString().
isValid
bool CSimplifiedMNListEntry::isValid
Definition at line 32 of file simplifiedmns.h.
Referenced by operator==(), SerializationOp(), ToJson(), and ToString().
keyIDVoting
CKeyID CSimplifiedMNListEntry::keyIDVoting
Definition at line 31 of file simplifiedmns.h.
Referenced by operator==(), SerializationOp(), ToJson(), and ToString().
proRegTxHash
uint256 CSimplifiedMNListEntry::proRegTxHash
Definition at line 27 of file simplifiedmns.h.
Referenced by operator==(), SerializationOp(), ToJson(), and ToString().
pubKeyOperator
CBLSLazyPublicKey CSimplifiedMNListEntry::pubKeyOperator
Definition at line 30 of file simplifiedmns.h.
Referenced by operator==(), SerializationOp(), ToJson(), and ToString().
service
CService CSimplifiedMNListEntry::service
Definition at line 29 of file simplifiedmns.h.
Referenced by operator==(), SerializationOp(), ToJson(), and ToString().
The documentation for this class was generated from the following files:
src/evo/simplifiedmns.h
src/evo/simplifiedmns.cpp
Released under the MIT license