Dash Core: QRDialog Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
QRDialog Class Reference
#include <qrdialog.h>
Public Member Functions
QRDialog (QWidget *parent=0)
~QRDialog ()
void setModel (OptionsModel *model)
void setInfo (QString strWindowtitle, QString strQRCode, QString strTextInfo, QString strQRCodeTitle)
Private Slots
void update ()
Private Attributes
Ui::QRDialog * ui
OptionsModel * model
QString strWindowtitle
QString strQRCode
QString strTextInfo
QString strQRCodeTitle
Detailed Description
Definition at line 47 of file qrdialog.h.
Constructor & Destructor Documentation
QRDialog()
QRDialog::QRDialog (QWidget * parent = 0) explicit
Definition at line 93 of file qrdialog.cpp.
References GUIUtil::Bold, GUIUtil::setFont(), ui, and GUIUtil::updateFonts().
~QRDialog()
QRDialog::~QRDialog ()
Definition at line 112 of file qrdialog.cpp.
References ui.
Member Function Documentation
setInfo()
void QRDialog::setInfo (QString strWindowtitle, QString strQRCode, QString strTextInfo, QString strQRCodeTitle)
Definition at line 128 of file qrdialog.cpp.
References strQRCode, strQRCodeTitle, strTextInfo, strWindowtitle, and update().
Referenced by AddressBookPage::on_showAddressQRCode_clicked(), and TransactionView::showAddressQRCode().
setModel()
void QRDialog::setModel (OptionsModel * model)
Definition at line 117 of file qrdialog.cpp.
References model, and update().
Referenced by AddressBookPage::on_showAddressQRCode_clicked(), and TransactionView::showAddressQRCode().
update
void QRDialog::update () private slot
Definition at line 137 of file qrdialog.cpp.
References GUIUtil::BACKGROUND_WIDGET, GUIUtil::BORDER_WIDGET, GUIUtil::getThemedQColor(), model, QR_IMAGE_SIZE, GUIUtil::QR_PIXEL, strQRCode, strQRCodeTitle, strTextInfo, strWindowtitle, and ui.
Referenced by setInfo(), and setModel().
Member Data Documentation
model
OptionsModel* QRDialog::model private
Definition at line 63 of file qrdialog.h.
Referenced by setModel(), and update().
strQRCode
QString QRDialog::strQRCode private
Definition at line 65 of file qrdialog.h.
Referenced by setInfo(), and update().
strQRCodeTitle
QString QRDialog::strQRCodeTitle private
Definition at line 67 of file qrdialog.h.
Referenced by setInfo(), and update().
strTextInfo
QString QRDialog::strTextInfo private
Definition at line 66 of file qrdialog.h.
Referenced by setInfo(), and update().
strWindowtitle
QString QRDialog::strWindowtitle private
Definition at line 64 of file qrdialog.h.
Referenced by setInfo(), and update().
ui
Ui::QRDialog* QRDialog::ui private
Definition at line 62 of file qrdialog.h.
Referenced by QRDialog(), update(), and ~QRDialog().
The documentation for this class was generated from the following files:
src/qt/qrdialog.h
src/qt/qrdialog.cpp
Released under the MIT license