Dash Core: CRIPEMD160 Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CRIPEMD160 Class Reference
A hasher class for RIPEMD-160.
#include <ripemd160.h>
Public Member Functions
CRIPEMD160 ()
CRIPEMD160 & Write (const unsigned char *data, size_t len)
void Finalize (unsigned char hash[OUTPUT_SIZE])
CRIPEMD160 & Reset ()
Static Public Attributes
static const size_t OUTPUT_SIZE = 20
Private Attributes
uint32_t s [5]
unsigned char buf [64]
uint64_t bytes
Detailed Description
A hasher class for RIPEMD-160.
Definition at line 12 of file ripemd160.h.
Constructor & Destructor Documentation
CRIPEMD160()
CRIPEMD160::CRIPEMD160 ()
Definition at line 242 of file ripemd160.cpp.
References s.
Member Function Documentation
Finalize()
void CRIPEMD160::Finalize (unsigned char hash[OUTPUT_SIZE])
Definition at line 273 of file ripemd160.cpp.
References bytes, s, Write(), WriteLE32(), and WriteLE64().
Referenced by CHash160::Finalize().
Reset()
CRIPEMD160 & CRIPEMD160::Reset ()
Definition at line 287 of file ripemd160.cpp.
References bytes, and s.
Write()
CRIPEMD160 & CRIPEMD160::Write (const unsigned char * data, size_t len)
Definition at line 247 of file ripemd160.cpp.
References buf, bytes, memcpy(), s, and sha256_shani::Transform().
Referenced by EvalScript(), Finalize(), CHash160::Finalize(), and HASH_RIPEMD160().
Member Data Documentation
buf
unsigned char CRIPEMD160::buf[64] private
Definition at line 16 of file ripemd160.h.
Referenced by Write().
bytes
uint64_t CRIPEMD160::bytes private
Definition at line 17 of file ripemd160.h.
Referenced by Finalize(), Reset(), and Write().
OUTPUT_SIZE
const size_t CRIPEMD160::OUTPUT_SIZE = 20 static
Definition at line 20 of file ripemd160.h.
Referenced by HASH_RIPEMD160().
s
uint32_t CRIPEMD160::s[5] private
Definition at line 15 of file ripemd160.h.
Referenced by CRIPEMD160(), Finalize(), Reset(), and Write().
The documentation for this class was generated from the following files:
src/crypto/ripemd160.h
src/crypto/ripemd160.cpp
Released under the MIT license