Dash Core: SplashScreen Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
SplashScreen Class Reference
Class for the splashscreen with information of the running client.
#include <splashscreen.h>
Public Slots
void slotFinish (QWidget *mainWin)
Slot to call finish() method as it's not defined as slot.
void showMessage (const QString &message, int alignment, const QColor &color)
Show message and progress.
Public Member Functions
SplashScreen (Qt::WindowFlags f, const NetworkStyle *networkStyle)
~SplashScreen ()
Protected Member Functions
void paintEvent (QPaintEvent *event)
void closeEvent (QCloseEvent *event)
bool eventFilter (QObject *obj, QEvent *ev)
Private Member Functions
void subscribeToCoreSignals ()
Connect core signals to splash screen.
void unsubscribeFromCoreSignals ()
Disconnect core signals to splash screen.
void ConnectWallet (CWallet *)
Connect wallet signals to splash screen.
Private Attributes
QPixmap pixmap
QString curMessage
QColor curColor
int curAlignment
QList< CWallet * > connectedWallets
Detailed Description
Class for the splashscreen with information of the running client.
Note
this is intentionally not a QSplashScreen. Dash Core initialization can take a long time, and in that case a progress window that cannot be moved around and minimized has turned out to be frustrating to the user.
Definition at line 20 of file splashscreen.h.
Constructor & Destructor Documentation
SplashScreen()
SplashScreen::SplashScreen (Qt::WindowFlags f, const NetworkStyle * networkStyle) explicit
Definition at line 30 of file splashscreen.cpp.
References GUIUtil::BACKGROUND_WIDGET, GUIUtil::BLUE, GUIUtil::BORDER_WIDGET, GUIUtil::DEFAULT, FormatFullVersion(), NetworkStyle::getBadgeColor(), GUIUtil::getFontBold(), GUIUtil::getFontNormal(), NetworkStyle::getSplashImage(), GUIUtil::getThemedQColor(), NetworkStyle::getTitleAddText(), pixmap, subscribeToCoreSignals(), and titleAddText.
~SplashScreen()
SplashScreen::~SplashScreen ()
Definition at line 137 of file splashscreen.cpp.
References unsubscribeFromCoreSignals().
Member Function Documentation
closeEvent()
void SplashScreen::closeEvent (QCloseEvent * event) protected
Definition at line 232 of file splashscreen.cpp.
References StartShutdown().
ConnectWallet()
void SplashScreen::ConnectWallet (CWallet *) private
Connect wallet signals to splash screen.
Referenced by subscribeToCoreSignals(), and unsubscribeFromCoreSignals().
eventFilter()
bool SplashScreen::eventFilter (QObject * obj, QEvent * ev) protected
Definition at line 142 of file splashscreen.cpp.
References StartShutdown().
paintEvent()
void SplashScreen::paintEvent (QPaintEvent * event) protected
Definition at line 220 of file splashscreen.cpp.
References curAlignment, curColor, curMessage, GUIUtil::getFontNormal(), and pixmap.
showMessage
void SplashScreen::showMessage (const QString & message, int alignment, const QColor & color) slot
Show message and progress.
Definition at line 212 of file splashscreen.cpp.
References curAlignment, curColor, and curMessage.
slotFinish
void SplashScreen::slotFinish (QWidget * mainWin) slot
Slot to call finish() method as it's not defined as slot.
Definition at line 152 of file splashscreen.cpp.
subscribeToCoreSignals()
void SplashScreen::subscribeToCoreSignals () private
Connect core signals to splash screen.
Definition at line 189 of file splashscreen.cpp.
References ConnectWallet(), CClientUIInterface::InitMessage, InitMessage(), CClientUIInterface::LoadWallet, CClientUIInterface::ShowProgress, ShowProgress(), and uiInterface.
Referenced by SplashScreen().
unsubscribeFromCoreSignals()
void SplashScreen::unsubscribeFromCoreSignals () private
Disconnect core signals to splash screen.
Definition at line 199 of file splashscreen.cpp.
References connectedWallets, ConnectWallet(), CClientUIInterface::InitMessage, InitMessage(), CClientUIInterface::LoadWallet, CClientUIInterface::ShowProgress, ShowProgress(), and uiInterface.
Referenced by ~SplashScreen().
Member Data Documentation
connectedWallets
QList<CWallet*> SplashScreen::connectedWallets private
Definition at line 55 of file splashscreen.h.
Referenced by unsubscribeFromCoreSignals().
curAlignment
int SplashScreen::curAlignment private
Definition at line 53 of file splashscreen.h.
Referenced by paintEvent(), and showMessage().
curColor
QColor SplashScreen::curColor private
Definition at line 52 of file splashscreen.h.
Referenced by paintEvent(), and showMessage().
curMessage
QString SplashScreen::curMessage private
Definition at line 51 of file splashscreen.h.
Referenced by paintEvent(), and showMessage().
pixmap
QPixmap SplashScreen::pixmap private
Definition at line 50 of file splashscreen.h.
Referenced by paintEvent(), and SplashScreen().
The documentation for this class was generated from the following files:
src/qt/splashscreen.h
src/qt/splashscreen.cpp
Released under the MIT license