Dash Core: llmq::CFinalCommitmentTxPayload Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
llmq::CFinalCommitmentTxPayload Class Reference
#include <quorums_commitment.h>
Public Member Functions
template<typename Stream , typename Operation >
ADD_SERIALIZE_METHODS void SerializationOp (Stream &s, Operation ser_action)
void ToJson (UniValue &obj) const
Public Attributes
uint16_t nVersion {CURRENT_VERSION}
uint32_t nHeight {(uint32_t)-1}
CFinalCommitment commitment
Static Public Attributes
static const uint16_t CURRENT_VERSION = 1
Detailed Description
Definition at line 109 of file quorums_commitment.h.
Member Function Documentation
SerializationOp()
template<typename Stream , typename Operation > ADD_SERIALIZE_METHODS void llmq::CFinalCommitmentTxPayload::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 123 of file quorums_commitment.h.
References commitment, nHeight, nVersion, and READWRITE.
ToJson()
void llmq::CFinalCommitmentTxPayload::ToJson (UniValue & obj) const inline
Definition at line 130 of file quorums_commitment.h.
References commitment, nHeight, nVersion, Pair(), UniValue::push_back(), UniValue::setObject(), and llmq::CFinalCommitment::ToJson().
Referenced by TxToUniv().
Member Data Documentation
commitment
CFinalCommitment llmq::CFinalCommitmentTxPayload::commitment
Definition at line 117 of file quorums_commitment.h.
Referenced by CDeterministicMNManager::BuildNewListFromBlock(), CalcCbTxMerkleRootQuorums(), llmq::CheckLLMQCommitment(), llmq::CQuorumBlockProcessor::GetCommitmentsFromBlock(), llmq::CQuorumBlockProcessor::GetMinableCommitmentTx(), SerializationOp(), and ToJson().
CURRENT_VERSION
const uint16_t llmq::CFinalCommitmentTxPayload::CURRENT_VERSION = 1 static
Definition at line 112 of file quorums_commitment.h.
Referenced by llmq::CheckLLMQCommitment().
nHeight
uint32_t llmq::CFinalCommitmentTxPayload::nHeight {(uint32_t)-1}
Definition at line 116 of file quorums_commitment.h.
Referenced by CDeterministicMNManager::BuildNewListFromBlock(), llmq::CheckLLMQCommitment(), llmq::CQuorumBlockProcessor::GetMinableCommitmentTx(), SerializationOp(), and ToJson().
nVersion
uint16_t llmq::CFinalCommitmentTxPayload::nVersion {CURRENT_VERSION}
Definition at line 115 of file quorums_commitment.h.
Referenced by llmq::CheckLLMQCommitment(), SerializationOp(), and ToJson().
The documentation for this class was generated from the following file:
src/llmq/quorums_commitment.h
Released under the MIT license