Dash Core: AES256CBCDecrypt Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
AES256CBCDecrypt Class Reference
#include <aes.h>
Public Member Functions
AES256CBCDecrypt (const unsigned char key[AES256_KEYSIZE], const unsigned char ivIn[AES_BLOCKSIZE], bool padIn)
~AES256CBCDecrypt ()
int Decrypt (const unsigned char *data, int size, unsigned char *out) const
Private Attributes
const AES256Decrypt dec
const bool pad
unsigned char iv [AES_BLOCKSIZE]
Detailed Description
Definition at line 79 of file aes.h.
Constructor & Destructor Documentation
AES256CBCDecrypt()
AES256CBCDecrypt::AES256CBCDecrypt (const unsigned char key[AES256_KEYSIZE], const unsigned char ivIn[AES_BLOCKSIZE], bool padIn)
Definition at line 169 of file aes.cpp.
References AES_BLOCKSIZE, iv, and memcpy().
~AES256CBCDecrypt()
AES256CBCDecrypt::~AES256CBCDecrypt ()
Definition at line 181 of file aes.cpp.
References iv.
Member Function Documentation
Decrypt()
int AES256CBCDecrypt::Decrypt (const unsigned char * data, int size, unsigned char * out) const
Definition at line 176 of file aes.cpp.
References CBCDecrypt(), dec, iv, and pad.
Referenced by CCrypter::Decrypt(), DecryptAES256(), and DecryptBlob().
Member Data Documentation
dec
const AES256Decrypt AES256CBCDecrypt::dec private
Definition at line 87 of file aes.h.
Referenced by Decrypt().
iv
unsigned char AES256CBCDecrypt::iv[AES_BLOCKSIZE] private
Definition at line 89 of file aes.h.
Referenced by AES256CBCDecrypt(), Decrypt(), and ~AES256CBCDecrypt().
pad
const bool AES256CBCDecrypt::pad private
Definition at line 88 of file aes.h.
Referenced by Decrypt().
The documentation for this class was generated from the following files:
src/crypto/aes.h
src/crypto/aes.cpp
Released under the MIT license