Dash Core: CBLSSignature Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CBLSSignature Class Reference
#include <bls.h>
Public Member Functions
CBLSSignature ()
CBLSSignature (const CBLSSignature &)=default
CBLSSignature & operator= (const CBLSSignature &)=default
void AggregateInsecure (const CBLSSignature &o)
void SubInsecure (const CBLSSignature &o)
bool VerifyInsecure (const CBLSPublicKey &pubKey, const uint256 &hash) const
bool VerifyInsecureAggregated (const std::vector< CBLSPublicKey > &pubKeys, const std::vector< uint256 > &hashes) const
bool VerifySecureAggregated (const std::vector< CBLSPublicKey > &pks, const uint256 &hash) const
bool Recover (const std::vector< CBLSSignature > &sigs, const std::vector< CBLSId > &ids)
bool operator== (const C &r) const
bool operator!= (const C &r) const
CBLSWrapper ()
CBLSWrapper (const CBLSWrapper &ref)=default
CBLSWrapper (CBLSWrapper &&ref)
Public Member Functions inherited from CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >
CBLSWrapper ()
CBLSWrapper (const CBLSWrapper &ref)=default
CBLSWrapper (CBLSWrapper &&ref)
CBLSWrapper & operator= (const CBLSWrapper &ref)=default
CBLSWrapper & operator= (CBLSWrapper &&ref)
bool operator== (const CBLSSignature &r) const
bool operator!= (const CBLSSignature &r) const
bool IsValid () const
void SetBuf (const void *buf, size_t size)
void SetBuf (const T &buf)
void Reset ()
void GetBuf (void *buf, size_t size) const
void GetBuf (T &buf) const
const uint256 & GetHash () const
void UpdateHash () const
bool SetHexStr (const std::string &str)
void Serialize (CSizeComputer &s) const
void Serialize (Stream &s) const
void Unserialize (Stream &s, bool checkMalleable=true)
bool CheckMalleable (void *buf, size_t size) const
std::string ToString () const
Static Public Member Functions
static CBLSSignature AggregateInsecure (const std::vector< CBLSSignature > &sigs)
static CBLSSignature AggregateSecure (const std::vector< CBLSSignature > &sigs, const std::vector< CBLSPublicKey > &pks, const uint256 &hash)
Protected Member Functions
bool InternalSetBuf (const void *buf)
bool InternalGetBuf (void *buf) const
Protected Member Functions inherited from CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >
constexpr size_t GetSerSize () const
Friends
class CBLSSecretKey
Additional Inherited Members
Static Public Attributes inherited from CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >
static const size_t SerSize
Protected Attributes inherited from CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >
bls::InsecureSignature impl
bool fValid
uint256 cachedHash
Detailed Description
Definition at line 286 of file bls.h.
Constructor & Destructor Documentation
CBLSSignature() [1/2]
CBLSSignature::CBLSSignature () inline
Definition at line 295 of file bls.h.
Referenced by AggregateInsecure(), and AggregateSecure().
CBLSSignature() [2/2]
CBLSSignature::CBLSSignature (const CBLSSignature &) default
Member Function Documentation
AggregateInsecure() [1/2]
void CBLSSignature::AggregateInsecure (const CBLSSignature & o)
Definition at line 277 of file bls.cpp.
References CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::IsValid(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::UpdateHash().
Referenced by llmq::BatchVerifyMessageSigs(), BLSVerify_Batched(), BLSVerify_LargeAggregatedBlock(), BLSVerify_LargeAggregatedBlock1000PreVerified(), BLSVerify_LargeBlockSelfAggregated(), CBLSWorker::PushSigVerifyBatch(), CBLSBatchVerifier< SourceId, MessageId >::VerifyBatchInsecure(), and CBLSBatchVerifier< SourceId, MessageId >::VerifyBatchSecureStep().
AggregateInsecure() [2/2]
CBLSSignature CBLSSignature::AggregateInsecure (const std::vector< CBLSSignature > & sigs) static
Definition at line 284 of file bls.cpp.
References CBLSSignature(), CBLSWrapper< ImplType, _SerSize, C >::fValid, CBLSWrapper< ImplType, _SerSize, C >::impl, and CBLSWrapper< ImplType, _SerSize, C >::UpdateHash().
AggregateSecure()
CBLSSignature CBLSSignature::AggregateSecure (const std::vector< CBLSSignature > & sigs, const std::vector< CBLSPublicKey > & pks, const uint256 & hash) static
Definition at line 304 of file bls.cpp.
References base_blob< BITS >::begin(), CBLSSignature(), CBLSWrapper< ImplType, _SerSize, C >::fValid, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl, and CBLSWrapper< ImplType, _SerSize, C >::UpdateHash().
Referenced by llmq::CDKGSession::FinalizeCommitments().
CBLSWrapper() [1/3]
CBLSWrapper< ImplType, _SerSize, C >::CBLSWrapper inline
Definition at line 71 of file bls.h.
CBLSWrapper() [2/3]
CBLSWrapper< ImplType, _SerSize, C >::CBLSWrapper inline
Definition at line 53 of file bls.h.
CBLSWrapper() [3/3]
CBLSWrapper< ImplType, _SerSize, C >::CBLSWrapper default
InternalGetBuf()
bool CBLSSignature::InternalGetBuf (void * buf) const protected virtual
Implements CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >.
Definition at line 271 of file bls.cpp.
References CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl.
InternalSetBuf()
bool CBLSSignature::InternalSetBuf (const void * buf) protected virtual
Implements CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >.
Definition at line 261 of file bls.cpp.
References CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl.
operator!=()
bool CBLSWrapper< ImplType, _SerSize, C >::operator!= inline
Definition at line 89 of file bls.h.
operator=()
CBLSSignature& CBLSSignature::operator= (const CBLSSignature &) default
operator==()
bool CBLSWrapper< ImplType, _SerSize, C >::operator== inline
Definition at line 85 of file bls.h.
Recover()
bool CBLSSignature::Recover (const std::vector< CBLSSignature > & sigs, const std::vector< CBLSId > & ids)
Definition at line 393 of file bls.cpp.
References CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::fValid, CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl, CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::IsValid(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::UpdateHash().
Referenced by llmq::CDKGSession::FinalizeCommitments(), and llmq::CSigSharesManager::TryRecoverSig().
SubInsecure()
void CBLSSignature::SubInsecure (const CBLSSignature & o)
Definition at line 328 of file bls.cpp.
References CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl, CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::IsValid(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::UpdateHash().
Referenced by BLSVerify_LargeAggregatedBlock1000PreVerified().
VerifyInsecure()
bool CBLSSignature::VerifyInsecure (const CBLSPublicKey & pubKey, const uint256 & hash) const
Definition at line 335 of file bls.cpp.
References base_blob< BITS >::begin(), CBLSWrapper< ImplType, _SerSize, C >::impl, CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl, CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::IsValid(), and CBLSWrapper< ImplType, _SerSize, C >::IsValid().
Referenced by CGovernanceVote::CheckSignature(), CGovernanceObject::CheckSignature(), CPrivateSendQueue::CheckSignature(), CPrivateSendBroadcastTx::CheckSignature(), llmq::CDKGSession::ReceiveMessage(), llmq::CSigSharesManager::TryRecoverSig(), llmq::CFinalCommitment::Verify(), and llmq::CSigningManager::VerifyRecoveredSig().
VerifyInsecureAggregated()
bool CBLSSignature::VerifyInsecureAggregated (const std::vector< CBLSPublicKey > & pubKeys, const std::vector< uint256 > & hashes) const
Definition at line 348 of file bls.cpp.
References CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl, and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::IsValid().
Referenced by llmq::BatchVerifyMessageSigs(), BLSVerify_Batched(), BLSVerify_LargeAggregatedBlock(), BLSVerify_LargeAggregatedBlock1000PreVerified(), BLSVerify_LargeBlockSelfAggregated(), CBLSWorker::PushSigVerifyBatch(), CBLSBatchVerifier< SourceId, MessageId >::VerifyBatchInsecure(), and CBLSBatchVerifier< SourceId, MessageId >::VerifyBatchSecureStep().
VerifySecureAggregated()
bool CBLSSignature::VerifySecureAggregated (const std::vector< CBLSPublicKey > & pks, const uint256 & hash) const
Definition at line 375 of file bls.cpp.
References base_blob< BITS >::begin(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::impl.
Referenced by llmq::CFinalCommitment::Verify().
Friends And Related Function Documentation
CBLSSecretKey
friend class CBLSSecretKey friend
Definition at line 288 of file bls.h.
The documentation for this class was generated from the following files:
src/bls/bls.h
src/bls/bls.cpp
Released under the MIT license