Dash Core: org.bitcoin.NativeSecp256k1 Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
org.bitcoin.NativeSecp256k1 Class Reference
Static Public Member Functions
static boolean verify (byte[] data, byte[] signature, byte[] pub) throws AssertFailException
Verifies the given secp256k1 signature in native code.
static byte [] sign (byte[] data, byte[] sec) throws AssertFailException
libsecp256k1 Create an ECDSA signature.
static boolean secKeyVerify (byte[] seckey)
libsecp256k1 Seckey Verify - returns 1 if valid, 0 if invalid
static byte [] computePubkey (byte[] seckey) throws AssertFailException
libsecp256k1 Compute Pubkey - computes public key from secret key
static synchronized void cleanup ()
libsecp256k1 Cleanup - This destroys the secp256k1 context object This should be called at the end of the program for proper cleanup of the context.
static long cloneContext ()
static byte [] privKeyTweakMul (byte[] privkey, byte[] tweak) throws AssertFailException
libsecp256k1 PrivKey Tweak-Mul - Tweak privkey by multiplying to it
static byte [] privKeyTweakAdd (byte[] privkey, byte[] tweak) throws AssertFailException
libsecp256k1 PrivKey Tweak-Add - Tweak privkey by adding to it
static byte [] pubKeyTweakAdd (byte[] pubkey, byte[] tweak) throws AssertFailException
libsecp256k1 PubKey Tweak-Add - Tweak pubkey by adding to it
static byte [] pubKeyTweakMul (byte[] pubkey, byte[] tweak) throws AssertFailException
libsecp256k1 PubKey Tweak-Mul - Tweak pubkey by multiplying to it
static byte [] createECDHSecret (byte[] seckey, byte[] pubkey) throws AssertFailException
libsecp256k1 create ECDH secret - constant time ECDH calculation
static synchronized boolean randomize (byte[] seed) throws AssertFailException
libsecp256k1 randomize - updates the context randomization
Static Private Member Functions
static native long secp256k1_ctx_clone (long context)
static native int secp256k1_context_randomize (ByteBuffer byteBuff, long context)
static native byte [][] secp256k1_privkey_tweak_add (ByteBuffer byteBuff, long context)
static native byte [][] secp256k1_privkey_tweak_mul (ByteBuffer byteBuff, long context)
static native byte [][] secp256k1_pubkey_tweak_add (ByteBuffer byteBuff, long context, int pubLen)
static native byte [][] secp256k1_pubkey_tweak_mul (ByteBuffer byteBuff, long context, int pubLen)
static native void secp256k1_destroy_context (long context)
static native int secp256k1_ecdsa_verify (ByteBuffer byteBuff, long context, int sigLen, int pubLen)
static native byte [][] secp256k1_ecdsa_sign (ByteBuffer byteBuff, long context)
static native int secp256k1_ec_seckey_verify (ByteBuffer byteBuff, long context)
static native byte [][] secp256k1_ec_pubkey_create (ByteBuffer byteBuff, long context)
static native byte [][] secp256k1_ec_pubkey_parse (ByteBuffer byteBuff, long context, int inputLen)
static native byte [][] secp256k1_ecdh (ByteBuffer byteBuff, long context, int inputLen)
Static Private Attributes
static final ReentrantReadWriteLock rwl = new ReentrantReadWriteLock()
static final Lock r = rwl.readLock()
static final Lock w = rwl.writeLock()
static ThreadLocal< ByteBuffer > nativeECDSABuffer = new ThreadLocal<ByteBuffer>()
Detailed Description
This class holds native methods to handle ECDSA verification.
You can find an example library that can be used for this at https://github.com/bitcoin/secp256k1
To build secp256k1 for use with bitcoinj, run ./configure --enable-jni --enable-experimental --enable-module-ecdh and make then copy .libs/libsecp256k1.so to your system library path or point the JVM to the folder containing it with -Djava.library.path
Definition at line 40 of file NativeSecp256k1.java.
Member Function Documentation
cleanup()
static synchronized void org.bitcoin.NativeSecp256k1.cleanup () inline static
libsecp256k1 Cleanup - This destroys the secp256k1 context object This should be called at the end of the program for proper cleanup of the context.
Definition at line 187 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.secp256k1_destroy_context(), and org.bitcoin.NativeSecp256k1.w.
Referenced by org.bitcoin.NativeSecp256k1Test.main().
cloneContext()
static long org.bitcoin.NativeSecp256k1.cloneContext () inline static
Definition at line 196 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_ctx_clone().
computePubkey()
static byte [] org.bitcoin.NativeSecp256k1.computePubkey (byte [] seckey) throws AssertFailException inline static
libsecp256k1 Compute Pubkey - computes public key from secret key
Parameters
seckey ECDSA Secret key, 32 bytes
Return values
Parameters
pubkey ECDSA Public key, 33 or 65 bytes
Definition at line 153 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_ec_pubkey_create().
Referenced by org.bitcoin.NativeSecp256k1Test.testPubKeyCreateNeg(), and org.bitcoin.NativeSecp256k1Test.testPubKeyCreatePos().
createECDHSecret()
static byte [] org.bitcoin.NativeSecp256k1.createECDHSecret (byte [] seckey, byte [] pubkey) throws AssertFailException inline static
libsecp256k1 create ECDH secret - constant time ECDH calculation
Parameters
seckey byte array of secret key used in exponentiaion
pubkey byte array of public key used in exponentiaion
Definition at line 365 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_ecdh().
Referenced by org.bitcoin.NativeSecp256k1Test.testCreateECDHSecret().
privKeyTweakAdd()
static byte [] org.bitcoin.NativeSecp256k1.privKeyTweakAdd (byte [] privkey, byte [] tweak) throws AssertFailException inline static
libsecp256k1 PrivKey Tweak-Add - Tweak privkey by adding to it
Parameters
tweak some bytes to tweak with
seckey 32-byte seckey
Definition at line 248 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_privkey_tweak_add().
Referenced by org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakAdd_1().
privKeyTweakMul()
static byte [] org.bitcoin.NativeSecp256k1.privKeyTweakMul (byte [] privkey, byte [] tweak) throws AssertFailException inline static
libsecp256k1 PrivKey Tweak-Mul - Tweak privkey by multiplying to it
Parameters
tweak some bytes to tweak with
seckey 32-byte seckey
Definition at line 209 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_privkey_tweak_mul().
Referenced by org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakMul_1().
pubKeyTweakAdd()
static byte [] org.bitcoin.NativeSecp256k1.pubKeyTweakAdd (byte [] pubkey, byte [] tweak) throws AssertFailException inline static
libsecp256k1 PubKey Tweak-Add - Tweak pubkey by adding to it
Parameters
tweak some bytes to tweak with
pubkey 32-byte seckey
Definition at line 287 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_pubkey_tweak_add().
Referenced by org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakAdd_2().
pubKeyTweakMul()
static byte [] org.bitcoin.NativeSecp256k1.pubKeyTweakMul (byte [] pubkey, byte [] tweak) throws AssertFailException inline static
libsecp256k1 PubKey Tweak-Mul - Tweak pubkey by multiplying to it
Parameters
tweak some bytes to tweak with
pubkey 32-byte seckey
Definition at line 326 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_pubkey_tweak_mul().
Referenced by org.bitcoin.NativeSecp256k1Test.testPrivKeyTweakMul_2().
randomize()
static synchronized boolean org.bitcoin.NativeSecp256k1.randomize (byte [] seed) throws AssertFailException inline static
libsecp256k1 randomize - updates the context randomization
Parameters
seed 32-byte random seed
Definition at line 400 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.secp256k1_context_randomize(), and org.bitcoin.NativeSecp256k1.w.
Referenced by org.bitcoin.NativeSecp256k1Test.testRandomize().
secKeyVerify()
static boolean org.bitcoin.NativeSecp256k1.secKeyVerify (byte [] seckey) inline static
libsecp256k1 Seckey Verify - returns 1 if valid, 0 if invalid
Parameters
seckey ECDSA Secret key, 32 bytes
Definition at line 123 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_ec_seckey_verify().
Referenced by org.bitcoin.NativeSecp256k1Test.testSecKeyVerifyNeg(), and org.bitcoin.NativeSecp256k1Test.testSecKeyVerifyPos().
secp256k1_context_randomize()
static native int org.bitcoin.NativeSecp256k1.secp256k1_context_randomize (ByteBuffer byteBuff, long context) static private
Referenced by org.bitcoin.NativeSecp256k1.randomize().
secp256k1_ctx_clone()
static native long org.bitcoin.NativeSecp256k1.secp256k1_ctx_clone (long context) static private
Referenced by org.bitcoin.NativeSecp256k1.cloneContext().
secp256k1_destroy_context()
static native void org.bitcoin.NativeSecp256k1.secp256k1_destroy_context (long context) static private
Referenced by org.bitcoin.NativeSecp256k1.cleanup().
secp256k1_ec_pubkey_create()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_ec_pubkey_create (ByteBuffer byteBuff, long context) static private
Referenced by org.bitcoin.NativeSecp256k1.computePubkey().
secp256k1_ec_pubkey_parse()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_ec_pubkey_parse (ByteBuffer byteBuff, long context, int inputLen) static private
secp256k1_ec_seckey_verify()
static native int org.bitcoin.NativeSecp256k1.secp256k1_ec_seckey_verify (ByteBuffer byteBuff, long context) static private
Referenced by org.bitcoin.NativeSecp256k1.secKeyVerify().
secp256k1_ecdh()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_ecdh (ByteBuffer byteBuff, long context, int inputLen) static private
Referenced by org.bitcoin.NativeSecp256k1.createECDHSecret().
secp256k1_ecdsa_sign()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_ecdsa_sign (ByteBuffer byteBuff, long context) static private
Referenced by org.bitcoin.NativeSecp256k1.sign().
secp256k1_ecdsa_verify()
static native int org.bitcoin.NativeSecp256k1.secp256k1_ecdsa_verify (ByteBuffer byteBuff, long context, int sigLen, int pubLen) static private
Referenced by org.bitcoin.NativeSecp256k1.verify().
secp256k1_privkey_tweak_add()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_privkey_tweak_add (ByteBuffer byteBuff, long context) static private
Referenced by org.bitcoin.NativeSecp256k1.privKeyTweakAdd().
secp256k1_privkey_tweak_mul()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_privkey_tweak_mul (ByteBuffer byteBuff, long context) static private
Referenced by org.bitcoin.NativeSecp256k1.privKeyTweakMul().
secp256k1_pubkey_tweak_add()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_pubkey_tweak_add (ByteBuffer byteBuff, long context, int pubLen) static private
Referenced by org.bitcoin.NativeSecp256k1.pubKeyTweakAdd().
secp256k1_pubkey_tweak_mul()
static native byte [][] org.bitcoin.NativeSecp256k1.secp256k1_pubkey_tweak_mul (ByteBuffer byteBuff, long context, int pubLen) static private
Referenced by org.bitcoin.NativeSecp256k1.pubKeyTweakMul().
sign()
static byte [] org.bitcoin.NativeSecp256k1.sign (byte [] data, byte [] sec) throws AssertFailException inline static
libsecp256k1 Create an ECDSA signature.
Parameters
data Message hash, 32 bytes
key Secret key, 32 bytes
Return values
Parameters
sig byte array of signature
Definition at line 87 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_ecdsa_sign().
Referenced by org.bitcoin.NativeSecp256k1Test.testSignNeg(), and org.bitcoin.NativeSecp256k1Test.testSignPos().
verify()
static boolean org.bitcoin.NativeSecp256k1.verify (byte [] data, byte [] signature, byte [] pub) throws AssertFailException inline static
Verifies the given secp256k1 signature in native code.
Calling when enabled == false is undefined (probably library not loaded)
Parameters
data The data which was signed, must be exactly 32 bytes
signature The signature
pub The public key which did the signing
Definition at line 54 of file NativeSecp256k1.java.
References org.bitcoin.Secp256k1Context.getContext(), org.bitcoin.NativeSecp256k1.nativeECDSABuffer, org.bitcoin.NativeSecp256k1.r, and org.bitcoin.NativeSecp256k1.secp256k1_ecdsa_verify().
Referenced by org.bitcoin.NativeSecp256k1Test.testVerifyNeg(), and org.bitcoin.NativeSecp256k1Test.testVerifyPos().
Member Data Documentation
nativeECDSABuffer
ThreadLocal<ByteBuffer> org.bitcoin.NativeSecp256k1.nativeECDSABuffer = new ThreadLocal<ByteBuffer>() static private
Definition at line 45 of file NativeSecp256k1.java.
Referenced by org.bitcoin.NativeSecp256k1.computePubkey(), org.bitcoin.NativeSecp256k1.createECDHSecret(), org.bitcoin.NativeSecp256k1.privKeyTweakAdd(), org.bitcoin.NativeSecp256k1.privKeyTweakMul(), org.bitcoin.NativeSecp256k1.pubKeyTweakAdd(), org.bitcoin.NativeSecp256k1.pubKeyTweakMul(), org.bitcoin.NativeSecp256k1.randomize(), org.bitcoin.NativeSecp256k1.secKeyVerify(), org.bitcoin.NativeSecp256k1.sign(), and org.bitcoin.NativeSecp256k1.verify().
r
final Lock org.bitcoin.NativeSecp256k1.r = rwl.readLock() static private
Definition at line 43 of file NativeSecp256k1.java.
Referenced by org.bitcoin.NativeSecp256k1.cloneContext(), org.bitcoin.NativeSecp256k1.computePubkey(), org.bitcoin.NativeSecp256k1.createECDHSecret(), org.bitcoin.NativeSecp256k1.privKeyTweakAdd(), org.bitcoin.NativeSecp256k1.privKeyTweakMul(), org.bitcoin.NativeSecp256k1.pubKeyTweakAdd(), org.bitcoin.NativeSecp256k1.pubKeyTweakMul(), org.bitcoin.NativeSecp256k1.secKeyVerify(), org.bitcoin.NativeSecp256k1.sign(), and org.bitcoin.NativeSecp256k1.verify().
rwl
final ReentrantReadWriteLock org.bitcoin.NativeSecp256k1.rwl = new ReentrantReadWriteLock() static private
Definition at line 42 of file NativeSecp256k1.java.
w
final Lock org.bitcoin.NativeSecp256k1.w = rwl.writeLock() static private
Definition at line 44 of file NativeSecp256k1.java.
Referenced by org.bitcoin.NativeSecp256k1.cleanup(), and org.bitcoin.NativeSecp256k1.randomize().
The documentation for this class was generated from the following file:
src/secp256k1/src/java/org/bitcoin/NativeSecp256k1.java
Released under the MIT license