Dash Core: payments::PaymentACK Class Reference
payments::PaymentACK Class Reference
#include <paymentrequest.pb.h>
Public Member Functions
PaymentACK ()
virtual ~PaymentACK ()
PaymentACK (const PaymentACK &from)
PaymentACK & operator= (const PaymentACK &from)
const ::google::protobuf::UnknownFieldSet & unknown_fields () const
inline ::google::protobuf::UnknownFieldSet * mutable_unknown_fields ()
void Swap (PaymentACK *other)
PaymentACK * New () const
void CopyFrom (const ::google::protobuf::Message &from)
void MergeFrom (const ::google::protobuf::Message &from)
void CopyFrom (const PaymentACK &from)
void MergeFrom (const PaymentACK &from)
void Clear ()
bool IsInitialized () const
int ByteSize () const
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const
::google::protobuf::uint8 * SerializeWithCachedSizesToArray (::google::protobuf::uint8 *output) const
int GetCachedSize () const
::google::protobuf::Metadata GetMetadata () const
bool has_payment () const
void clear_payment ()
const ::payments::Payment & payment () const
inline ::payments::Payment * mutable_payment ()
inline ::payments::Payment * release_payment ()
void set_allocated_payment (::payments::Payment *payment)
bool has_memo () const
void clear_memo ()
const ::std::string & memo () const
void set_memo (const ::std::string &value)
void set_memo (const char *value)
void set_memo (const char *value, size_t size)
inline ::std::string * mutable_memo ()
inline ::std::string * release_memo ()
void set_allocated_memo (::std::string *memo)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const PaymentACK & default_instance ()
Static Public Attributes
static const int kPaymentFieldNumber = 1
static const int kMemoFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const
void set_has_payment ()
void clear_has_payment ()
void set_has_memo ()
void clear_has_memo ()
void InitAsDefaultInstance ()
Private Attributes
::google::protobuf::UnknownFieldSet _unknown_fields_
::google::protobuf::uint32 _has_bits_ [1]
int _cached_size_
::payments::Payment * payment_
::std::string * memo_
Static Private Attributes
static PaymentACK * default_instance_ = NULL
Friends
void protobuf_AddDesc_paymentrequest_2eproto ()
void protobuf_AssignDesc_paymentrequest_2eproto ()
void protobuf_ShutdownFile_paymentrequest_2eproto ()
Detailed Description
Definition at line 657 of file paymentrequest.pb.h.
Constructor & Destructor Documentation
PaymentACK() [1/2]
payments::PaymentACK::PaymentACK ()
Definition at line 2090 of file paymentrequest.pb.cc.
Referenced by New().
~PaymentACK()
payments::PaymentACK::~PaymentACK () virtual
Definition at line 2115 of file paymentrequest.pb.cc.
PaymentACK() [2/2]
payments::PaymentACK::PaymentACK (const PaymentACK & from)
Definition at line 2100 of file paymentrequest.pb.cc.
Member Function Documentation
ByteSize()
int payments::PaymentACK::ByteSize () const
Definition at line 2281 of file paymentrequest.pb.cc.
Clear()
void payments::PaymentACK::Clear ()
Definition at line 2150 of file paymentrequest.pb.cc.
Referenced by CopyFrom().
clear_has_memo()
void payments::PaymentACK::clear_has_memo () inline private
Definition at line 1926 of file paymentrequest.pb.h.
Referenced by clear_memo(), release_memo(), and set_allocated_memo().
clear_has_payment()
void payments::PaymentACK::clear_has_payment () inline private
Definition at line 1885 of file paymentrequest.pb.h.
Referenced by clear_payment(), release_payment(), and set_allocated_payment().
clear_memo()
void payments::PaymentACK::clear_memo () inline
Definition at line 1929 of file paymentrequest.pb.h.
clear_payment()
void payments::PaymentACK::clear_payment () inline
Definition at line 1888 of file paymentrequest.pb.h.
CopyFrom() [1/2]
void payments::PaymentACK::CopyFrom (const ::google::protobuf::Message & from)
Definition at line 2336 of file paymentrequest.pb.cc.
Referenced by operator=().
CopyFrom() [2/2]
void payments::PaymentACK::CopyFrom (const PaymentACK & from)
Definition at line 2342 of file paymentrequest.pb.cc.
default_instance()
const PaymentACK & payments::PaymentACK::default_instance () static
Definition at line 2139 of file paymentrequest.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * payments::PaymentACK::descriptor () static
Definition at line 2134 of file paymentrequest.pb.cc.
GetCachedSize()
int payments::PaymentACK::GetCachedSize () const inline
Definition at line 698 of file paymentrequest.pb.h.
GetMetadata()
google::protobuf::Metadata payments::PaymentACK::GetMetadata () const
Definition at line 2367 of file paymentrequest.pb.cc.
has_memo()
bool payments::PaymentACK::has_memo () const inline
Definition at line 1920 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
has_payment()
bool payments::PaymentACK::has_payment () const inline
Definition at line 1879 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
InitAsDefaultInstance()
void payments::PaymentACK::InitAsDefaultInstance () private
Definition at line 2096 of file paymentrequest.pb.cc.
Referenced by payments::protobuf_AddDesc_paymentrequest_2eproto().
IsInitialized()
bool payments::PaymentACK::IsInitialized () const
Definition at line 2348 of file paymentrequest.pb.cc.
memo()
const ::std::string & payments::PaymentACK::memo () const inline
Definition at line 1935 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), MergePartialFromCodedStream(), PaymentServer::netRequestFinished(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_memo().
MergeFrom() [1/2]
void payments::PaymentACK::MergeFrom (const ::google::protobuf::Message & from)
Definition at line 2311 of file paymentrequest.pb.cc.
Referenced by CopyFrom(), and PaymentACK().
MergeFrom() [2/2]
void payments::PaymentACK::MergeFrom (const PaymentACK & from)
Definition at line 2323 of file paymentrequest.pb.cc.
MergePartialFromCodedStream()
bool payments::PaymentACK::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input)
Definition at line 2165 of file paymentrequest.pb.cc.
mutable_memo()
std::string * payments::PaymentACK::mutable_memo () inline
Definition at line 1963 of file paymentrequest.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_payment()
payments::Payment * payments::PaymentACK::mutable_payment () inline
Definition at line 1896 of file paymentrequest.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
mutable_unknown_fields()
inline ::google::protobuf::UnknownFieldSet* payments::PaymentACK::mutable_unknown_fields () inline
Definition at line 673 of file paymentrequest.pb.h.
Referenced by Clear(), MergeFrom(), and MergePartialFromCodedStream().
New()
PaymentACK * payments::PaymentACK::New () const
Definition at line 2146 of file paymentrequest.pb.cc.
operator=()
PaymentACK& payments::PaymentACK::operator= (const PaymentACK & from) inline
Definition at line 664 of file paymentrequest.pb.h.
payment()
const ::payments::Payment & payments::PaymentACK::payment () const inline
Definition at line 1892 of file paymentrequest.pb.h.
Referenced by ByteSize(), IsInitialized(), MergeFrom(), SerializeWithCachedSizes(), SerializeWithCachedSizesToArray(), and set_allocated_payment().
release_memo()
std::string * payments::PaymentACK::release_memo () inline
Definition at line 1971 of file paymentrequest.pb.h.
release_payment()
payments::Payment * payments::PaymentACK::release_payment () inline
Definition at line 1902 of file paymentrequest.pb.h.
SerializeWithCachedSizes()
void payments::PaymentACK::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const
Definition at line 2226 of file paymentrequest.pb.cc.
SerializeWithCachedSizesToArray()
google::protobuf::uint8 * payments::PaymentACK::SerializeWithCachedSizesToArray (::google::protobuf::uint8 * output) const
Definition at line 2252 of file paymentrequest.pb.cc.
set_allocated_memo()
void payments::PaymentACK::set_allocated_memo (::std::string * memo) inline
Definition at line 1981 of file paymentrequest.pb.h.
set_allocated_payment()
void payments::PaymentACK::set_allocated_payment (::payments::Payment * payment) inline
Definition at line 1908 of file paymentrequest.pb.h.
set_has_memo()
void payments::PaymentACK::set_has_memo () inline private
Definition at line 1923 of file paymentrequest.pb.h.
Referenced by mutable_memo(), set_allocated_memo(), and set_memo().
set_has_payment()
void payments::PaymentACK::set_has_payment () inline private
Definition at line 1882 of file paymentrequest.pb.h.
Referenced by mutable_payment(), and set_allocated_payment().
set_memo() [1/3]
void payments::PaymentACK::set_memo (const ::std::string & value) inline
Definition at line 1939 of file paymentrequest.pb.h.
Referenced by MergeFrom().
set_memo() [2/3]
void payments::PaymentACK::set_memo (const char * value) inline
Definition at line 1947 of file paymentrequest.pb.h.
set_memo() [3/3]
void payments::PaymentACK::set_memo (const char * value, size_t size) inline
Definition at line 1955 of file paymentrequest.pb.h.
SetCachedSize()
void payments::PaymentACK::SetCachedSize (int size) const private
Definition at line 2129 of file paymentrequest.pb.cc.
SharedCtor()
void payments::PaymentACK::SharedCtor () private
Definition at line 2107 of file paymentrequest.pb.cc.
Referenced by PaymentACK().
SharedDtor()
void payments::PaymentACK::SharedDtor () private
Definition at line 2120 of file paymentrequest.pb.cc.
Referenced by ~PaymentACK().
Swap()
void payments::PaymentACK::Swap (PaymentACK * other)
Definition at line 2357 of file paymentrequest.pb.cc.
unknown_fields()
const ::google::protobuf::UnknownFieldSet& payments::PaymentACK::unknown_fields () const inline
Definition at line 669 of file paymentrequest.pb.h.
Referenced by ByteSize(), MergeFrom(), SerializeWithCachedSizes(), and SerializeWithCachedSizesToArray().
Friends And Related Function Documentation
protobuf_AddDesc_paymentrequest_2eproto
void protobuf_AddDesc_paymentrequest_2eproto () friend
Definition at line 201 of file paymentrequest.pb.cc.
Referenced by default_instance().
protobuf_AssignDesc_paymentrequest_2eproto
void protobuf_AssignDesc_paymentrequest_2eproto () friend
Definition at line 45 of file paymentrequest.pb.cc.
protobuf_ShutdownFile_paymentrequest_2eproto
void protobuf_ShutdownFile_paymentrequest_2eproto () friend
Definition at line 184 of file paymentrequest.pb.cc.
Member Data Documentation
_cached_size_
int payments::PaymentACK::_cached_size_ mutable private
Definition at line 741 of file paymentrequest.pb.h.
Referenced by ByteSize(), GetCachedSize(), SetCachedSize(), SharedCtor(), and Swap().
_has_bits_
::google::protobuf::uint32 payments::PaymentACK::_has_bits_[1] private
Definition at line 740 of file paymentrequest.pb.h.
Referenced by ByteSize(), Clear(), clear_has_memo(), clear_has_payment(), has_memo(), has_payment(), IsInitialized(), MergeFrom(), set_has_memo(), set_has_payment(), SharedCtor(), and Swap().
_unknown_fields_
::google::protobuf::UnknownFieldSet payments::PaymentACK::_unknown_fields_ private
Definition at line 738 of file paymentrequest.pb.h.
Referenced by mutable_unknown_fields(), Swap(), and unknown_fields().
default_instance_
PaymentACK * payments::PaymentACK::default_instance_ = NULL static private
Definition at line 749 of file paymentrequest.pb.h.
Referenced by default_instance(), payment(), payments::protobuf_AddDesc_paymentrequest_2eproto(), payments::protobuf_AssignDesc_paymentrequest_2eproto(), payments::protobuf_ShutdownFile_paymentrequest_2eproto(), and SharedDtor().
kMemoFieldNumber
const int payments::PaymentACK::kMemoFieldNumber = 2 static
Definition at line 722 of file paymentrequest.pb.h.
kPaymentFieldNumber
const int payments::PaymentACK::kPaymentFieldNumber = 1 static
Definition at line 713 of file paymentrequest.pb.h.
memo_
::std::string* payments::PaymentACK::memo_ private
Definition at line 743 of file paymentrequest.pb.h.
Referenced by Clear(), clear_memo(), memo(), mutable_memo(), release_memo(), set_allocated_memo(), set_memo(), SharedCtor(), SharedDtor(), and Swap().
payment_
::payments::Payment* payments::PaymentACK::payment_ private
Definition at line 742 of file paymentrequest.pb.h.
Referenced by Clear(), clear_payment(), InitAsDefaultInstance(), mutable_payment(), payment(), release_payment(), set_allocated_payment(), SharedCtor(), SharedDtor(), and Swap().
The documentation for this class was generated from the following files:
src/qt/paymentrequest.pb.h
src/qt/paymentrequest.pb.cc