Dash Core: org.bitcoin.Secp256k1Context Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
org.bitcoin.Secp256k1Context Class Reference
This class holds the context reference used in native methods to handle ECDSA operations.
Static Public Member Functions
static boolean isEnabled ()
static long getContext ()
Static Private Member Functions
static native long secp256k1_init_context ()
Static Private Attributes
static final boolean enabled
static final long context
Detailed Description
This class holds the context reference used in native methods to handle ECDSA operations.
Definition at line 23 of file Secp256k1Context.java.
Member Function Documentation
getContext()
static long org.bitcoin.Secp256k1Context.getContext () inline static
Definition at line 45 of file Secp256k1Context.java.
References org.bitcoin.Secp256k1Context.context, and org.bitcoin.Secp256k1Context.enabled.
Referenced by org.bitcoin.NativeSecp256k1.cleanup(), org.bitcoin.NativeSecp256k1.cloneContext(), org.bitcoin.NativeSecp256k1.computePubkey(), org.bitcoin.NativeSecp256k1.createECDHSecret(), org.bitcoin.NativeSecp256k1.privKeyTweakAdd(), org.bitcoin.NativeSecp256k1.privKeyTweakMul(), org.bitcoin.NativeSecp256k1.pubKeyTweakAdd(), org.bitcoin.NativeSecp256k1.pubKeyTweakMul(), org.bitcoin.NativeSecp256k1.randomize(), org.bitcoin.NativeSecp256k1.secKeyVerify(), org.bitcoin.NativeSecp256k1.sign(), and org.bitcoin.NativeSecp256k1.verify().
isEnabled()
static boolean org.bitcoin.Secp256k1Context.isEnabled () inline static
Definition at line 41 of file Secp256k1Context.java.
References org.bitcoin.Secp256k1Context.enabled.
Referenced by org.bitcoin.NativeSecp256k1Test.main().
secp256k1_init_context()
static native long org.bitcoin.Secp256k1Context.secp256k1_init_context () static private
Member Data Documentation
context
final long org.bitcoin.Secp256k1Context.context static private
Definition at line 25 of file Secp256k1Context.java.
Referenced by org.bitcoin.Secp256k1Context.getContext().
enabled
final boolean org.bitcoin.Secp256k1Context.enabled static private
Definition at line 24 of file Secp256k1Context.java.
Referenced by org.bitcoin.Secp256k1Context.getContext(), and org.bitcoin.Secp256k1Context.isEnabled().
The documentation for this class was generated from the following file:
src/secp256k1/src/java/org/bitcoin/Secp256k1Context.java
Released under the MIT license