Dash Core: CSHA256 Class Reference
CSHA256 Class Reference
#include <sha256.h>
Public Member Functions
CSHA256 ()
CSHA256 & Write (const unsigned char *data, size_t len)
void Finalize (unsigned char hash[OUTPUT_SIZE])
CSHA256 & Reset ()
Static Public Attributes
static const size_t OUTPUT_SIZE = 32
Private Attributes
uint32_t s [8]
unsigned char buf [64]
size_t bytes
Detailed Description
A hasher class for SHA-256.
Definition at line 12 of file sha256.h.
Constructor & Destructor Documentation
CSHA256()
CSHA256::CSHA256 ()
Definition at line 136 of file sha256.cpp.
Member Function Documentation
Finalize()
void CSHA256::Finalize (unsigned char hash[OUTPUT_SIZE])
Definition at line 167 of file sha256.cpp.
Referenced by CNode::CalculateKeyedNetGroup(), CMnemonic::Check(), CHMAC_SHA256::CHMAC_SHA256(), CHMAC_SHA256::Finalize(), CHash256::Finalize(), CHash160::Finalize(), and CMnemonic::FromData().
Reset()
CSHA256 & CSHA256::Reset ()
Definition at line 184 of file sha256.cpp.
Referenced by CHash256::Finalize(), CHash256::Reset(), and CHash160::Reset().
Write()
CSHA256 & CSHA256::Write (const unsigned char * data, size_t len)
Definition at line 141 of file sha256.cpp.
Referenced by CNode::CalculateKeyedNetGroup(), CMnemonic::Check(), CHMAC_SHA256::CHMAC_SHA256(), EvalScript(), Finalize(), CHMAC_SHA256::Finalize(), CHash256::Finalize(), CMnemonic::FromData(), CHMAC_SHA256::Write(), CHash256::Write(), and CHash160::Write().
Member Data Documentation
buf
unsigned char CSHA256::buf[64] private
Definition at line 16 of file sha256.h.
Referenced by Write().
bytes
size_t CSHA256::bytes private
Definition at line 17 of file sha256.h.
Referenced by Finalize(), Reset(), and Write().
OUTPUT_SIZE
const size_t CSHA256::OUTPUT_SIZE = 32 static
Definition at line 20 of file sha256.h.
Referenced by CHash256::Finalize(), and CHash160::Finalize().
s
uint32_t CSHA256::s[8] private
Definition at line 15 of file sha256.h.
Referenced by CSHA256(), Finalize(), Reset(), and Write().
The documentation for this class was generated from the following files:
src/crypto/sha256.h
src/crypto/sha256.cpp