Dash Core: src/support/cleanse.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
cleanse.h File Reference
#include <stdlib.h>
Functions
void memory_cleanse (void *ptr, size_t len)
Function Documentation
memory_cleanse()
void memory_cleanse (void * ptr, size_t len)
Definition at line 31 of file cleanse.cpp.
Referenced by AddDataToRng(), CCrypter::BytesToKeySHA512AES(), CCrypter::CleanKey(), ChaCha20Poly1305AEAD::Crypt(), zero_after_free_allocator< T >::deallocate(), pooled_secure_allocator< uint8_t >::deallocate(), secure_allocator< T >::deallocate(), EncodeBase64Secure(), BerkeleyBatch::Erase(), BerkeleyBatch::Exists(), PosixLockedPageAllocator::FreeLocked(), GetStrongRandBytes(), RandAddSeed(), RandAddSeedPerfmon(), RandAddSeedSleep(), BerkeleyBatch::Read(), BerkeleyBatch::ReadAtCursor(), CCrypter::SetKeyFromPassphrase(), CBase58Data::SetString(), and BerkeleyBatch::Write().
Released under the MIT license