Dash Core: src/qt/clientmodel.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
clientmodel.cpp File Reference
#include <qt/clientmodel.h>
#include <qt/bantablemodel.h>
#include <qt/guiconstants.h>
#include <qt/guiutil.h>
#include <qt/peertablemodel.h>
#include <chain.h>
#include <chainparams.h>
#include <checkpoints.h>
#include <clientversion.h>
#include <validation.h>
#include <net.h>
#include <txmempool.h>
#include <ui_interface.h>
#include <util.h>
#include <warnings.h>
#include <masternode/masternode-sync.h>
#include <privatesend/privatesend.h>
#include <llmq/quorums_instantsend.h>
#include <stdint.h>
#include <QDebug>
#include <QTimer>
Functions
static void ShowProgress (ClientModel *clientmodel, const std::string &title, int nProgress)
static void NotifyNumConnectionsChanged (ClientModel *clientmodel, int newNumConnections)
static void NotifyNetworkActiveChanged (ClientModel *clientmodel, bool networkActive)
static void NotifyAlertChanged (ClientModel *clientmodel)
static void BannedListChanged (ClientModel *clientmodel)
static void BlockTipChanged (ClientModel *clientmodel, bool initialSync, const CBlockIndex *pIndex, bool fHeader)
static void NotifyMasternodeListChanged (ClientModel *clientmodel, const CDeterministicMNList &newList)
static void NotifyAdditionalDataSyncProgressChanged (ClientModel *clientmodel, double nSyncProgress)
Variables
static int64_t nLastHeaderTipUpdateNotification = 0
static int64_t nLastBlockTipUpdateNotification = 0
Function Documentation
BannedListChanged()
static void BannedListChanged (ClientModel * clientmodel) static
Definition at line 328 of file clientmodel.cpp.
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
BlockTipChanged()
static void BlockTipChanged (ClientModel * clientmodel, bool initialSync, const CBlockIndex * pIndex, bool fHeader) static
Definition at line 334 of file clientmodel.cpp.
References ClientModel::cachedBestHeaderHeight, ClientModel::cachedBestHeaderTime, CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockTime(), GetTimeMillis(), ClientModel::getVerificationProgress(), MODEL_UPDATE_DELAY, CBlockIndex::nHeight, nLastBlockTipUpdateNotification, nLastHeaderTipUpdateNotification, and base_blob< BITS >::ToString().
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyAdditionalDataSyncProgressChanged()
static void NotifyAdditionalDataSyncProgressChanged (ClientModel * clientmodel, double nSyncProgress) static
Definition at line 368 of file clientmodel.cpp.
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyAlertChanged()
static void NotifyAlertChanged (ClientModel * clientmodel) static
Definition at line 322 of file clientmodel.cpp.
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyMasternodeListChanged()
static void NotifyMasternodeListChanged (ClientModel * clientmodel, const CDeterministicMNList & newList) static
Definition at line 363 of file clientmodel.cpp.
References ClientModel::setMasternodeList().
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyNetworkActiveChanged()
static void NotifyNetworkActiveChanged (ClientModel * clientmodel, bool networkActive) static
Definition at line 316 of file clientmodel.cpp.
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
NotifyNumConnectionsChanged()
static void NotifyNumConnectionsChanged (ClientModel * clientmodel, int newNumConnections) static
Definition at line 309 of file clientmodel.cpp.
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
ShowProgress()
static void ShowProgress (ClientModel * clientmodel, const std::string & title, int nProgress) static
Definition at line 301 of file clientmodel.cpp.
Referenced by ClientModel::subscribeToCoreSignals(), and ClientModel::unsubscribeFromCoreSignals().
Variable Documentation
nLastBlockTipUpdateNotification
int64_t nLastBlockTipUpdateNotification = 0 static
Definition at line 37 of file clientmodel.cpp.
Referenced by BlockTipChanged().
nLastHeaderTipUpdateNotification
int64_t nLastHeaderTipUpdateNotification = 0 static
Definition at line 36 of file clientmodel.cpp.
Referenced by BlockTipChanged().
Released under the MIT license