Dash Core: src/rpc/client.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
client.h File Reference
#include <univalue.h>
Functions
UniValue RPCConvertValues (const std::string &strMethod, const std::vector< std::string > &strParams)
Convert positional arguments to command-specific RPC representation.
UniValue RPCConvertNamedValues (const std::string &strMethod, const std::vector< std::string > &strParams)
Convert named arguments to command-specific RPC representation.
UniValue ParseNonRFCJSONValue (const std::string &strVal)
Non-RFC4627 JSON parser, accepts internal values (such as numbers, true, false, null) as well as objects and arrays.
Function Documentation
ParseNonRFCJSONValue()
UniValue ParseNonRFCJSONValue (const std::string & strVal)
Non-RFC4627 JSON parser, accepts internal values (such as numbers, true, false, null) as well as objects and arrays.
Definition at line 221 of file client.cpp.
References UniValue::isArray(), UniValue::read(), and UniValue::size().
Referenced by RPCConvertNamedValues(), and RPCConvertValues().
RPCConvertNamedValues()
UniValue RPCConvertNamedValues (const std::string & strMethod, const std::vector< std::string > & strParams)
Convert named arguments to command-specific RPC representation.
Definition at line 249 of file client.cpp.
References CRPCConvertTable::convert(), name, ParseNonRFCJSONValue(), UniValue::pushKV(), rpcCvtTable, and UniValue::VOBJ.
Referenced by DefaultRequestHandler::PrepareRequest().
RPCConvertValues()
UniValue RPCConvertValues (const std::string & strMethod, const std::vector< std::string > & strParams)
Convert positional arguments to command-specific RPC representation.
Definition at line 230 of file client.cpp.
References CRPCConvertTable::convert(), ParseNonRFCJSONValue(), UniValue::push_back(), rpcCvtTable, and UniValue::VARR.
Referenced by DefaultRequestHandler::PrepareRequest(), and RPCConsole::RPCParseCommandLine().
Released under the MIT license