Dash Core: src/rpc/client.cpp File Reference
client.cpp File Reference
#include "rpc/client.h"
#include "rpc/protocol.h"
#include "util.h"
#include <set>
#include <stdint.h>
#include <boost/algorithm/string/case_conv.hpp>
#include <univalue.h>
Classes
class CRPCConvertParam
class CRPCConvertTable
Functions
UniValue ParseNonRFCJSONValue (const std::string &strVal)
UniValue RPCConvertValues (const std::string &strMethod, const std::vector< std::string > &strParams)
Variables
static const CRPCConvertParam vRPCConvertParams []
static CRPCConvertTable rpcCvtTable
Function Documentation
ParseNonRFCJSONValue()
UniValue ParseNonRFCJSONValue (const std::string & strVal)
Non-RFC4627 JSON parser, accepts internal values (such as numbers, true, false, null) as well as objects and arrays.
Definition at line 169 of file client.cpp.
Referenced by RPCConvertValues().
RPCConvertValues()
UniValue RPCConvertValues (const std::string & strMethod, const std::vector< std::string > & strParams)
Convert strings to command-specific RPC representation
Definition at line 179 of file client.cpp.
Referenced by CommandLineRPC(), and RPCExecutor::request().
Variable Documentation
rpcCvtTable
CRPCConvertTable rpcCvtTable static
Definition at line 164 of file client.cpp.
Referenced by RPCConvertValues().
vRPCConvertParams
const CRPCConvertParam vRPCConvertParams[] static
Definition at line 25 of file client.cpp.
Referenced by CRPCConvertTable::CRPCConvertTable().