Dash Core: src/bench/coin_selection.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
coin_selection.cpp File Reference
#include <bench/bench.h>
#include <wallet/wallet.h>
#include <set>
Functions
static void addCoin (const CAmount &nValue, const CWallet &wallet, std::vector< COutput > &vCoins)
static void CoinSelection (benchmark::State &state)
BENCHMARK (CoinSelection)
Function Documentation
addCoin()
static void addCoin (const CAmount & nValue, const CWallet & wallet, std::vector< COutput > & vCoins) static
Definition at line 10 of file coin_selection.cpp.
References MakeTransactionRef(), CMutableTransaction::nLockTime, vCoins, and CMutableTransaction::vout.
Referenced by CoinSelection().
BENCHMARK()
BENCHMARK (CoinSelection)
CoinSelection()
static void CoinSelection (benchmark::State & state) static
Definition at line 33 of file coin_selection.cpp.
References addCoin(), COIN, BerkeleyDatabase::CreateDummy(), CWallet::cs_wallet, benchmark::State::KeepRunning(), LOCK, CWallet::SelectCoinsMinConf(), and vCoins.
Released under the MIT license