Dash Core: src/coins.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
coins.h File Reference
#include <primitives/transaction.h>
#include <compressor.h>
#include <core_memusage.h>
#include <hash.h>
#include <memusage.h>
#include <serialize.h>
#include <uint256.h>
#include <assert.h>
#include <stdint.h>
#include <unordered_map>
Classes
class Coin
A UTXO entry.
class SaltedOutpointHasher
struct CCoinsCacheEntry
class CCoinsViewCursor
Cursor for iterating over CoinsView state.
class CCoinsView
Abstract view on the open txout dataset.
class CCoinsViewBacked
CCoinsView backed by another CCoinsView.
class CCoinsViewCache
CCoinsView that adds a memory cache for transactions to another CCoinsView.
Typedefs
typedef std::unordered_map< COutPoint, CCoinsCacheEntry, SaltedOutpointHasher > CCoinsMap
Functions
void AddCoins (CCoinsViewCache &cache, const CTransaction &tx, int nHeight, bool check=false)
Utility function to add all of a transaction's outputs to a cache.
const Coin & AccessByTxid (const CCoinsViewCache &cache, const uint256 &txid)
Utility function to find any unspent output with a given txid.
Typedef Documentation
CCoinsMap
typedef std::unordered_map<COutPoint, CCoinsCacheEntry, SaltedOutpointHasher> CCoinsMap
Definition at line 122 of file coins.h.
Function Documentation
AccessByTxid()
const Coin& AccessByTxid (const CCoinsViewCache & cache, const uint256 & txid)
Utility function to find any unspent output with a given txid.
Definition at line 249 of file coins.cpp.
References CCoinsViewCache::AccessCoin(), coinEmpty, Coin::IsSpent(), MAX_OUTPUTS_PER_BLOCK, and COutPoint::n.
Referenced by ApplyTxInUndo(), GetTransaction(), and gettxoutproof().
AddCoins()
void AddCoins (CCoinsViewCache & cache, const CTransaction & tx, int nHeight, bool check = false)
Utility function to add all of a transaction's outputs to a cache.
Definition at line 87 of file coins.cpp.
References CCoinsViewCache::AddCoin(), CTransaction::GetHash(), CCoinsViewCache::HaveCoin(), CTransaction::IsCoinBase(), and CTransaction::vout.
Referenced by CChainState::RollforwardBlock(), SetupDummyInputs(), and UpdateCoins().
Released under the MIT license