Dash Core: src/consensus/consensus.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
consensus.h File Reference
Functions
unsigned int MaxBlockSize (bool fDIP0001Active)
unsigned int MaxBlockSigOps (bool fDIP0001Active)
The maximum allowed number of signature check operations in a block (network rule)
Variables
static const unsigned int MAX_LEGACY_BLOCK_SIZE = 1000000
The maximum allowed size for a serialized block, in bytes (network rule)
static const unsigned int MAX_DIP0001_BLOCK_SIZE = 2000000
static const unsigned int MAX_TX_EXTRA_PAYLOAD = 10000
The maximum allowed size of version 3 extra payload.
static const int COINBASE_MATURITY = 100
Coinbase transaction outputs can only be spent after this number of new blocks (network rule)
static constexpr unsigned int LOCKTIME_VERIFY_SEQUENCE = (1 << 0)
Flags for nSequence and nLockTime locks.
static constexpr unsigned int LOCKTIME_MEDIAN_TIME_PAST = (1 << 1)
Use GetMedianTimePast() instead of nTime for end point timestamp.
Function Documentation
MaxBlockSigOps()
unsigned int MaxBlockSigOps (bool fDIP0001Active) inline
The maximum allowed number of signature check operations in a block (network rule)
Definition at line 17 of file consensus.h.
References MaxBlockSize().
Referenced by CheckBlock(), CChainState::ConnectBlock(), ContextualCheckBlock(), getblocktemplate(), and BlockAssembler::TestPackage().
MaxBlockSize()
unsigned int MaxBlockSize (bool fDIP0001Active) inline
Definition at line 12 of file consensus.h.
References MAX_DIP0001_BLOCK_SIZE, and MAX_LEGACY_BLOCK_SIZE.
Referenced by BlockAssembler::BlockAssembler(), CheckBlock(), ContextualCheckBlock(), CPartialMerkleTree::ExtractMatches(), getblockstats(), getblocktemplate(), PartiallyDownloadedBlock::InitData(), LoadExternalBlockFile(), MaxBlockSigOps(), MutateTxAddInput(), CConnman::OutboundTargetReached(), and PeerLogicValidation::SendMessages().
Variable Documentation
COINBASE_MATURITY
const int COINBASE_MATURITY = 100 static
Coinbase transaction outputs can only be spent after this number of new blocks (network rule)
Definition at line 24 of file consensus.h.
Referenced by Consensus::CheckTxInputs(), CMerkleTx::GetBlocksToMaturity(), CTxMemPool::removeForReorg(), and TransactionDesc::toHTML().
LOCKTIME_MEDIAN_TIME_PAST
constexpr unsigned int LOCKTIME_MEDIAN_TIME_PAST = (1 << 1) static
Use GetMedianTimePast() instead of nTime for end point timestamp.
Definition at line 30 of file consensus.h.
Referenced by CheckFinalTx(), ContextualCheckBlock(), and BlockAssembler::CreateNewBlock().
LOCKTIME_VERIFY_SEQUENCE
constexpr unsigned int LOCKTIME_VERIFY_SEQUENCE = (1 << 0) static
Flags for nSequence and nLockTime locks.
Interpret sequence numbers as relative lock-time constraints.
Definition at line 28 of file consensus.h.
Referenced by CalculateSequenceLocks(), and CChainState::ConnectBlock().
MAX_DIP0001_BLOCK_SIZE
const unsigned int MAX_DIP0001_BLOCK_SIZE = 2000000 static
Definition at line 11 of file consensus.h.
Referenced by MaxBlockSize().
MAX_LEGACY_BLOCK_SIZE
const unsigned int MAX_LEGACY_BLOCK_SIZE = 1000000 static
The maximum allowed size for a serialized block, in bytes (network rule)
Definition at line 10 of file consensus.h.
Referenced by CheckTransaction(), and MaxBlockSize().
MAX_TX_EXTRA_PAYLOAD
const unsigned int MAX_TX_EXTRA_PAYLOAD = 10000 static
The maximum allowed size of version 3 extra payload.
Definition at line 22 of file consensus.h.
Referenced by CheckTransaction().
Released under the MIT license