Dash Core: src/core_memusage.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
core_memusage.h File Reference
#include <primitives/transaction.h>
#include <primitives/block.h>
#include <memusage.h>
Functions
static size_t RecursiveDynamicUsage (const CScript &script)
static size_t RecursiveDynamicUsage (const COutPoint &out)
static size_t RecursiveDynamicUsage (const CTxIn &in)
static size_t RecursiveDynamicUsage (const CTxOut &out)
static size_t RecursiveDynamicUsage (const CTransaction &tx)
static size_t RecursiveDynamicUsage (const CMutableTransaction &tx)
static size_t RecursiveDynamicUsage (const CBlock &block)
static size_t RecursiveDynamicUsage (const CBlockLocator &locator)
template<typename X >
static size_t RecursiveDynamicUsage (const std::shared_ptr< X > &p)
Function Documentation
RecursiveDynamicUsage() [1/9]
static size_t RecursiveDynamicUsage (const CScript & script) inline static
Definition at line 12 of file core_memusage.h.
References memusage::DynamicUsage().
Referenced by DisconnectedBlockTransactions::addTransaction(), CTxMemPoolEntry::CTxMemPoolEntry(), ProcessMessage(), RecursiveDynamicUsage(), DisconnectedBlockTransactions::removeEntry(), and DisconnectedBlockTransactions::removeForBlock().
RecursiveDynamicUsage() [2/9]
static size_t RecursiveDynamicUsage (const COutPoint & out) inline static
Definition at line 16 of file core_memusage.h.
RecursiveDynamicUsage() [3/9]
static size_t RecursiveDynamicUsage (const CTxIn & in) inline static
Definition at line 20 of file core_memusage.h.
References CTxIn::prevout, RecursiveDynamicUsage(), and CTxIn::scriptSig.
RecursiveDynamicUsage() [4/9]
static size_t RecursiveDynamicUsage (const CTxOut & out) inline static
Definition at line 24 of file core_memusage.h.
References RecursiveDynamicUsage(), and CTxOut::scriptPubKey.
RecursiveDynamicUsage() [5/9]
static size_t RecursiveDynamicUsage (const CTransaction & tx) inline static
Definition at line 28 of file core_memusage.h.
References memusage::DynamicUsage(), RecursiveDynamicUsage(), CTransaction::vin, and CTransaction::vout.
RecursiveDynamicUsage() [6/9]
static size_t RecursiveDynamicUsage (const CMutableTransaction & tx) inline static
Definition at line 39 of file core_memusage.h.
References memusage::DynamicUsage(), RecursiveDynamicUsage(), CMutableTransaction::vin, and CMutableTransaction::vout.
RecursiveDynamicUsage() [7/9]
static size_t RecursiveDynamicUsage (const CBlock & block) inline static
Definition at line 50 of file core_memusage.h.
References memusage::DynamicUsage(), RecursiveDynamicUsage(), and CBlock::vtx.
RecursiveDynamicUsage() [8/9]
static size_t RecursiveDynamicUsage (const CBlockLocator & locator) inline static
Definition at line 58 of file core_memusage.h.
References memusage::DynamicUsage(), and CBlockLocator::vHave.
RecursiveDynamicUsage() [9/9]
template<typename X > static size_t RecursiveDynamicUsage (const std::shared_ptr< X > & p) inline static
Definition at line 63 of file core_memusage.h.
References memusage::DynamicUsage(), and RecursiveDynamicUsage().
Released under the MIT license