Dash Core: src/core_read.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
core_read.cpp File Reference
#include <core_io.h>
#include <primitives/block.h>
#include <primitives/transaction.h>
#include <script/script.h>
#include <serialize.h>
#include <streams.h>
#include <univalue.h>
#include <util.h>
#include <utilstrencodings.h>
#include <version.h>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/replace.hpp>
#include <boost/algorithm/string/split.hpp>
Functions
CScript ParseScript (const std::string &s)
bool DecodeHexTx (CMutableTransaction &tx, const std::string &strHexTx)
bool DecodeHexBlk (CBlock &block, const std::string &strHexBlk)
uint256 ParseHashUV (const UniValue &v, const std::string &strName)
uint256 ParseHashStr (const std::string &strHex, const std::string &strName)
std::vector< unsigned char > ParseHexUV (const UniValue &v, const std::string &strName)
Function Documentation
DecodeHexBlk()
bool DecodeHexBlk (CBlock & block, const std::string & strHexBlk)
Definition at line 109 of file core_read.cpp.
References IsHex(), ParseHex(), PROTOCOL_VERSION, and SER_NETWORK.
Referenced by getblocktemplate(), and submitblock().
DecodeHexTx()
bool DecodeHexTx (CMutableTransaction & tx, const std::string & strHexTx)
Definition at line 90 of file core_read.cpp.
References CDataStream::empty(), IsHex(), ParseHex(), PROTOCOL_VERSION, and SER_NETWORK.
Referenced by combinerawtransaction(), CommandLineRawTx(), decoderawtransaction(), fundrawtransaction(), importprunedfunds(), sendrawtransaction(), and signrawtransaction().
ParseHashStr()
uint256 ParseHashStr (const std::string & strHex, const std::string & strName)
Definition at line 134 of file core_read.cpp.
References IsHex(), and base_blob< BITS >::SetHex().
Referenced by ParseHashUV(), and prioritisetransaction().
ParseHashUV()
uint256 ParseHashUV (const UniValue & v, const std::string & strName)
Definition at line 126 of file core_read.cpp.
References UniValue::getValStr(), UniValue::isStr(), and ParseHashStr().
Referenced by MutateTxSign().
ParseHexUV()
std::vector<unsigned char> ParseHexUV (const UniValue & v, const std::string & strName)
Definition at line 144 of file core_read.cpp.
References UniValue::getValStr(), IsHex(), UniValue::isStr(), and ParseHex().
Referenced by MutateTxSign().
ParseScript()
CScript ParseScript (const std::string & s)
Definition at line 22 of file core_read.cpp.
References atoi64(), prevector< N, T, Size, Diff >::end(), GetOpName(), prevector< N, T, Size, Diff >::insert(), IsHex(), MAX_OPCODE, name, OP_NOP, OP_RESERVED, and ParseHex().
Referenced by MutateTxAddOutScript().
Released under the MIT license