Dash Core: src/bench/crypto_hash.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
crypto_hash.cpp File Reference
#include <iostream>
#include <bench/bench.h>
#include <bloom.h>
#include <hash.h>
#include <random.h>
#include <uint256.h>
#include <utiltime.h>
#include <crypto/ripemd160.h>
#include <crypto/sha1.h>
#include <crypto/sha256.h>
#include <crypto/sha512.h>
Functions
static void HASH_RIPEMD160 (benchmark::State &state)
static void HASH_SHA1 (benchmark::State &state)
static void HASH_SHA256 (benchmark::State &state)
static void HASH_SHA256_0032b (benchmark::State &state)
static void HASH_DSHA256 (benchmark::State &state)
static void HASH_DSHA256_0032b (benchmark::State &state)
static void HASH_SHA256D64_1024 (benchmark::State &state)
static void HASH_SHA512 (benchmark::State &state)
static void HASH_SipHash_0032b (benchmark::State &state)
static void FastRandom_32bit (benchmark::State &state)
static void FastRandom_1bit (benchmark::State &state)
static void HASH_DSHA256_0032b_single (benchmark::State &state)
static void HASH_DSHA256_0080b_single (benchmark::State &state)
static void HASH_DSHA256_0128b_single (benchmark::State &state)
static void HASH_DSHA256_0512b_single (benchmark::State &state)
static void HASH_DSHA256_1024b_single (benchmark::State &state)
static void HASH_DSHA256_2048b_single (benchmark::State &state)
static void HASH_X11 (benchmark::State &state)
static void HASH_X11_0032b_single (benchmark::State &state)
static void HASH_X11_0080b_single (benchmark::State &state)
static void HASH_X11_0128b_single (benchmark::State &state)
static void HASH_X11_0512b_single (benchmark::State &state)
static void HASH_X11_1024b_single (benchmark::State &state)
static void HASH_X11_2048b_single (benchmark::State &state)
BENCHMARK (HASH_RIPEMD160)
BENCHMARK (HASH_SHA1)
BENCHMARK (HASH_SHA256)
BENCHMARK (HASH_DSHA256)
BENCHMARK (HASH_SHA512)
BENCHMARK (HASH_X11)
BENCHMARK (HASH_SHA256_0032b)
BENCHMARK (HASH_DSHA256_0032b)
BENCHMARK (HASH_SipHash_0032b)
BENCHMARK (HASH_SHA256D64_1024)
BENCHMARK (HASH_DSHA256_0032b_single)
BENCHMARK (HASH_DSHA256_0080b_single)
BENCHMARK (HASH_DSHA256_0128b_single)
BENCHMARK (HASH_DSHA256_0512b_single)
BENCHMARK (HASH_DSHA256_1024b_single)
BENCHMARK (HASH_DSHA256_2048b_single)
BENCHMARK (HASH_X11_0032b_single)
BENCHMARK (HASH_X11_0080b_single)
BENCHMARK (HASH_X11_0128b_single)
BENCHMARK (HASH_X11_0512b_single)
BENCHMARK (HASH_X11_1024b_single)
BENCHMARK (HASH_X11_2048b_single)
BENCHMARK (FastRandom_32bit)
BENCHMARK (FastRandom_1bit)
Variables
static const uint64_t BUFFER_SIZE = 1000*1000
Function Documentation
BENCHMARK() [1/24]
BENCHMARK (HASH_RIPEMD160)
BENCHMARK() [2/24]
BENCHMARK (HASH_SHA1)
BENCHMARK() [3/24]
BENCHMARK (HASH_SHA256)
BENCHMARK() [4/24]
BENCHMARK (HASH_DSHA256)
BENCHMARK() [5/24]
BENCHMARK (HASH_SHA512)
BENCHMARK() [6/24]
BENCHMARK (HASH_X11)
BENCHMARK() [7/24]
BENCHMARK (HASH_SHA256_0032b)
BENCHMARK() [8/24]
BENCHMARK (HASH_DSHA256_0032b)
BENCHMARK() [9/24]
BENCHMARK (HASH_SipHash_0032b)
BENCHMARK() [10/24]
BENCHMARK (HASH_SHA256D64_1024)
BENCHMARK() [11/24]
BENCHMARK (HASH_DSHA256_0032b_single)
BENCHMARK() [12/24]
BENCHMARK (HASH_DSHA256_0080b_single)
BENCHMARK() [13/24]
BENCHMARK (HASH_DSHA256_0128b_single)
BENCHMARK() [14/24]
BENCHMARK (HASH_DSHA256_0512b_single)
BENCHMARK() [15/24]
BENCHMARK (HASH_DSHA256_1024b_single)
BENCHMARK() [16/24]
BENCHMARK (HASH_DSHA256_2048b_single)
BENCHMARK() [17/24]
BENCHMARK (HASH_X11_0032b_single)
BENCHMARK() [18/24]
BENCHMARK (HASH_X11_0080b_single)
BENCHMARK() [19/24]
BENCHMARK (HASH_X11_0128b_single)
BENCHMARK() [20/24]
BENCHMARK (HASH_X11_0512b_single)
BENCHMARK() [21/24]
BENCHMARK (HASH_X11_1024b_single)
BENCHMARK() [22/24]
BENCHMARK (HASH_X11_2048b_single)
BENCHMARK() [23/24]
BENCHMARK (FastRandom_32bit)
BENCHMARK() [24/24]
BENCHMARK (FastRandom_1bit)
FastRandom_1bit()
static void FastRandom_1bit (benchmark::State & state) static
Definition at line 111 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and FastRandomContext::randbool().
FastRandom_32bit()
static void FastRandom_32bit (benchmark::State & state) static
Definition at line 100 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and FastRandomContext::rand32().
HASH_DSHA256()
static void HASH_DSHA256 (benchmark::State & state) static
Definition at line 56 of file crypto_hash.cpp.
References BUFFER_SIZE, benchmark::State::KeepRunning(), CSHA256::OUTPUT_SIZE, and CHash256::Write().
HASH_DSHA256_0032b()
static void HASH_DSHA256_0032b (benchmark::State & state) static
Definition at line 64 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CHash256::Write().
HASH_DSHA256_0032b_single()
static void HASH_DSHA256_0032b_single (benchmark::State & state) static
Definition at line 122 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CHash256::Write().
HASH_DSHA256_0080b_single()
static void HASH_DSHA256_0080b_single (benchmark::State & state) static
Definition at line 129 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CHash256::Write().
HASH_DSHA256_0128b_single()
static void HASH_DSHA256_0128b_single (benchmark::State & state) static
Definition at line 136 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CHash256::Write().
HASH_DSHA256_0512b_single()
static void HASH_DSHA256_0512b_single (benchmark::State & state) static
Definition at line 143 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CHash256::Write().
HASH_DSHA256_1024b_single()
static void HASH_DSHA256_1024b_single (benchmark::State & state) static
Definition at line 150 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CHash256::Write().
HASH_DSHA256_2048b_single()
static void HASH_DSHA256_2048b_single (benchmark::State & state) static
Definition at line 157 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CHash256::Write().
HASH_RIPEMD160()
static void HASH_RIPEMD160 (benchmark::State & state) static
Definition at line 22 of file crypto_hash.cpp.
References BUFFER_SIZE, benchmark::State::KeepRunning(), CRIPEMD160::OUTPUT_SIZE, and CRIPEMD160::Write().
HASH_SHA1()
static void HASH_SHA1 (benchmark::State & state) static
Definition at line 30 of file crypto_hash.cpp.
References BUFFER_SIZE, benchmark::State::KeepRunning(), CSHA1::OUTPUT_SIZE, and CSHA1::Write().
HASH_SHA256()
static void HASH_SHA256 (benchmark::State & state) static
Definition at line 38 of file crypto_hash.cpp.
References BUFFER_SIZE, benchmark::State::KeepRunning(), CSHA256::OUTPUT_SIZE, and CSHA256::Write().
HASH_SHA256_0032b()
static void HASH_SHA256_0032b (benchmark::State & state) static
Definition at line 46 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and CSHA256::Write().
HASH_SHA256D64_1024()
static void HASH_SHA256D64_1024 (benchmark::State & state) static
Definition at line 74 of file crypto_hash.cpp.
References benchmark::State::KeepRunning(), and SHA256D64().
HASH_SHA512()
static void HASH_SHA512 (benchmark::State & state) static
Definition at line 82 of file crypto_hash.cpp.
References BUFFER_SIZE, benchmark::State::KeepRunning(), CSHA512::OUTPUT_SIZE, and CSHA512::Write().
HASH_SipHash_0032b()
static void HASH_SipHash_0032b (benchmark::State & state) static
Definition at line 90 of file crypto_hash.cpp.
References base_blob< BITS >::begin(), benchmark::State::KeepRunning(), and SipHashUint256().
HASH_X11()
static void HASH_X11 (benchmark::State & state) static
Definition at line 164 of file crypto_hash.cpp.
References BUFFER_SIZE, HashX11(), and benchmark::State::KeepRunning().
HASH_X11_0032b_single()
static void HASH_X11_0032b_single (benchmark::State & state) static
Definition at line 172 of file crypto_hash.cpp.
References HashX11(), and benchmark::State::KeepRunning().
HASH_X11_0080b_single()
static void HASH_X11_0080b_single (benchmark::State & state) static
Definition at line 180 of file crypto_hash.cpp.
References HashX11(), and benchmark::State::KeepRunning().
HASH_X11_0128b_single()
static void HASH_X11_0128b_single (benchmark::State & state) static
Definition at line 188 of file crypto_hash.cpp.
References HashX11(), and benchmark::State::KeepRunning().
HASH_X11_0512b_single()
static void HASH_X11_0512b_single (benchmark::State & state) static
Definition at line 196 of file crypto_hash.cpp.
References HashX11(), and benchmark::State::KeepRunning().
HASH_X11_1024b_single()
static void HASH_X11_1024b_single (benchmark::State & state) static
Definition at line 204 of file crypto_hash.cpp.
References HashX11(), and benchmark::State::KeepRunning().
HASH_X11_2048b_single()
static void HASH_X11_2048b_single (benchmark::State & state) static
Definition at line 212 of file crypto_hash.cpp.
References HashX11(), and benchmark::State::KeepRunning().
Variable Documentation
BUFFER_SIZE
const uint64_t BUFFER_SIZE = 1000*1000 static
Definition at line 20 of file crypto_hash.cpp.
Referenced by HASH_DSHA256(), HASH_RIPEMD160(), HASH_SHA1(), HASH_SHA256(), HASH_SHA512(), and HASH_X11().
Released under the MIT license