Dash Core: src/crypto/ctaes/ctaes.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
ctaes.h File Reference
#include <stdint.h>
#include <stdlib.h>
Classes
struct AES_state
struct AES128_ctx
struct AES192_ctx
struct AES256_ctx
Functions
void AES128_init (AES128_ctx *ctx, const unsigned char *key16)
void AES128_encrypt (const AES128_ctx *ctx, size_t blocks, unsigned char *cipher16, const unsigned char *plain16)
void AES128_decrypt (const AES128_ctx *ctx, size_t blocks, unsigned char *plain16, const unsigned char *cipher16)
void AES192_init (AES192_ctx *ctx, const unsigned char *key24)
void AES192_encrypt (const AES192_ctx *ctx, size_t blocks, unsigned char *cipher16, const unsigned char *plain16)
void AES192_decrypt (const AES192_ctx *ctx, size_t blocks, unsigned char *plain16, const unsigned char *cipher16)
void AES256_init (AES256_ctx *ctx, const unsigned char *key32)
void AES256_encrypt (const AES256_ctx *ctx, size_t blocks, unsigned char *cipher16, const unsigned char *plain16)
void AES256_decrypt (const AES256_ctx *ctx, size_t blocks, unsigned char *plain16, const unsigned char *cipher16)
Function Documentation
AES128_decrypt()
void AES128_decrypt (const AES128_ctx * ctx, size_t blocks, unsigned char * plain16, const unsigned char * cipher16)
Definition at line 509 of file ctaes.c.
References AES_decrypt(), and ctx.
Referenced by bench_AES128_decrypt(), AES128Decrypt::Decrypt(), and main().
AES128_encrypt()
void AES128_encrypt (const AES128_ctx * ctx, size_t blocks, unsigned char * cipher16, const unsigned char * plain16)
Definition at line 501 of file ctaes.c.
References AES_encrypt(), and ctx.
Referenced by bench_AES128_encrypt(), AES128Encrypt::Encrypt(), and main().
AES128_init()
void AES128_init (AES128_ctx * ctx, const unsigned char * key16)
Definition at line 497 of file ctaes.c.
References AES_setup(), and ctx.
Referenced by AES128Decrypt::AES128Decrypt(), AES128Encrypt::AES128Encrypt(), bench_AES128_encrypt_setup(), bench_AES128_init(), and main().
AES192_decrypt()
void AES192_decrypt (const AES192_ctx * ctx, size_t blocks, unsigned char * plain16, const unsigned char * cipher16)
Definition at line 530 of file ctaes.c.
References AES_decrypt(), and ctx.
Referenced by bench_AES192_decrypt(), and main().
AES192_encrypt()
void AES192_encrypt (const AES192_ctx * ctx, size_t blocks, unsigned char * cipher16, const unsigned char * plain16)
Definition at line 521 of file ctaes.c.
References AES_encrypt(), and ctx.
Referenced by bench_AES192_encrypt(), and main().
AES192_init()
void AES192_init (AES192_ctx * ctx, const unsigned char * key24)
Definition at line 517 of file ctaes.c.
References AES_setup(), and ctx.
Referenced by bench_AES192_encrypt_setup(), bench_AES192_init(), and main().
AES256_decrypt()
void AES256_decrypt (const AES256_ctx * ctx, size_t blocks, unsigned char * plain16, const unsigned char * cipher16)
Definition at line 550 of file ctaes.c.
References AES_decrypt(), and ctx.
Referenced by bench_AES256_decrypt(), AES256Decrypt::Decrypt(), and main().
AES256_encrypt()
void AES256_encrypt (const AES256_ctx * ctx, size_t blocks, unsigned char * cipher16, const unsigned char * plain16)
Definition at line 542 of file ctaes.c.
References AES_encrypt(), and ctx.
Referenced by bench_AES256_encrypt(), AES256Encrypt::Encrypt(), and main().
AES256_init()
void AES256_init (AES256_ctx * ctx, const unsigned char * key32)
Definition at line 538 of file ctaes.c.
References AES_setup(), and ctx.
Referenced by AES256Decrypt::AES256Decrypt(), AES256Encrypt::AES256Encrypt(), bench_AES256_encrypt_setup(), bench_AES256_init(), and main().
Released under the MIT license