Dash Core: src/qt/dash.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
dash.cpp File Reference
#include <qt/bitcoingui.h>
#include <chainparams.h>
#include <qt/clientmodel.h>
#include <fs.h>
#include <qt/guiconstants.h>
#include <qt/guiutil.h>
#include <qt/intro.h>
#include <net.h>
#include <qt/networkstyle.h>
#include <qt/optionsmodel.h>
#include <qt/splashscreen.h>
#include <qt/utilitydialog.h>
#include <qt/winshutdownmonitor.h>
#include <init.h>
#include <rpc/server.h>
#include <stacktraces.h>
#include <ui_interface.h>
#include <util.h>
#include <warnings.h>
#include <walletinitinterface.h>
#include <memory>
#include <stdint.h>
#include <boost/thread.hpp>
#include <QApplication>
#include <QDebug>
#include <QLibraryInfo>
#include <QLocale>
#include <QMessageBox>
#include <QProcess>
#include <QSettings>
#include <QThread>
#include <QTimer>
#include <QTranslator>
#include <QTextCodec>
#include <qt/dash.moc>
Classes
class BitcoinCore
Class encapsulating Dash Core startup and shutdown.
class BitcoinApplication
Main Dash application object.
Functions
static void InitMessage (const std::string &message)
static std::string Translate (const char *psz)
static QString GetLangTerritory ()
static void initTranslations (QTranslator &qtTranslatorBase, QTranslator &qtTranslator, QTranslator &translatorBase, QTranslator &translator)
Set up translations.
void DebugMessageHandler (QtMsgType type, const char *msg)
int main (int argc, char *argv[])
Function Documentation
DebugMessageHandler()
void DebugMessageHandler (QtMsgType type, const char * msg)
Definition at line 156 of file dash.cpp.
References LogPrint, LogPrintf, and BCLog::QT.
Referenced by main().
GetLangTerritory()
static QString GetLangTerritory () static
Definition at line 101 of file dash.cpp.
References gArgs, and ArgsManager::GetArg().
Referenced by initTranslations(), and main().
InitMessage()
static void InitMessage (const std::string & message) static
Definition at line 88 of file dash.cpp.
References LogPrintf.
Referenced by main().
initTranslations()
static void initTranslations (QTranslator & qtTranslatorBase, QTranslator & qtTranslator, QTranslator & translatorBase, QTranslator & translator) static
Set up translations.
Definition at line 117 of file dash.cpp.
References GetLangTerritory().
Referenced by main().
main()
int main (int argc, char * argv[])
Parse command-line options. These take precedence over anything else.
Basic Qt initialization (not dependent on parameters or configuration)
Application identification
Initialization of translations, so that intro dialog is in user's language
Now that settings and translations are available, ask user for data directory
Determine availability of data directory and parse dash.conf
Do not call GetDataDir(true) before this step finishes
Determine network (and switch to network specific options)
Main GUI initialization
Definition at line 569 of file dash.cpp.
References HelpMessageDialog::about, BitcoinCore::baseInitialize(), BITCOIN_CONF_FILENAME, HelpMessageDialog::cmdline, BitcoinApplication::createOptionsModel(), BitcoinApplication::createSplashScreen(), BitcoinApplication::createWindow(), DebugMessageHandler(), DEFAULT_SPLASHSCREEN, GUIUtil::fontFamilyFromString(), GUIUtil::fontFamilyToString(), gArgs, ArgsManager::GetArg(), ArgsManager::GetBoolArg(), ArgsManager::GetChainName(), GetCrashInfoStrFromSerializedStr(), GetDataDir(), GUIUtil::getFontFamilyDefault(), GUIUtil::getFontScale(), GUIUtil::getFontWeightBold(), GUIUtil::getFontWeightNormal(), GetLangTerritory(), BitcoinApplication::getMainWinId(), BitcoinApplication::getReturnValue(), GetWarnings(), BitcoinApplication::handleRunawayException(), help(), CClientUIInterface::InitMessage, InitMessage(), initTranslations(), NetworkStyle::instantiate(), PaymentServer::ipcParseCommandLine(), PaymentServer::ipcSendCommandLine(), ArgsManager::IsArgSet(), GUIUtil::listStyleSheets(), GUIUtil::loadFonts(), BitcoinApplication::parameterSetup(), Params(), ArgsManager::ParseParameters(), Intro::pickDataDirectory(), PrintExceptionContinue(), QAPP_APP_NAME_DEFAULT, QAPP_ORG_DOMAIN, QAPP_ORG_NAME, ArgsManager::ReadConfigFile(), RegisterPrettySignalHandlers(), RegisterPrettyTerminateHander(), BitcoinApplication::requestInitialize(), BitcoinApplication::requestShutdown(), SelectParams(), GUIUtil::setFontFamily(), GUIUtil::setFontScale(), GUIUtil::setFontWeightBold(), GUIUtil::setFontWeightNormal(), GUIUtil::setStyleSheetDirectory(), SetupEnvironment(), GUIUtil::SubstituteFonts(), TOOLTIP_WRAP_THRESHOLD, CTranslationInterface::Translate, Translate(), translationInterface, uiInterface, GUIUtil::weightFromArg(), and GUIUtil::weightToArg().
Translate()
static std::string Translate (const char * psz) static
Definition at line 96 of file dash.cpp.
Referenced by main().
Released under the MIT license