Dash Core: src/dashd.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
dashd.cpp File Reference
#include <chainparams.h>
#include <clientversion.h>
#include <compat.h>
#include <fs.h>
#include <rpc/server.h>
#include <init.h>
#include <noui.h>
#include <util.h>
#include <httpserver.h>
#include <httprpc.h>
#include <utilstrencodings.h>
#include <walletinitinterface.h>
#include <stacktraces.h>
#include <boost/thread.hpp>
#include <stdio.h>
Functions
void WaitForShutdown ()
bool AppInit (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
AppInit()
bool AppInit (int argc, char * argv[])
Definition at line 58 of file dashd.cpp.
References _(), AppInitBasicSetup(), AppInitLockDataDirectory(), AppInitMain(), AppInitParameterInteraction(), AppInitSanityChecks(), BITCOIN_CONF_FILENAME, FormatFullVersion(), FormatParagraph(), gArgs, ArgsManager::GetArg(), ArgsManager::GetBoolArg(), ArgsManager::GetChainName(), GetCrashInfoStrFromSerializedStr(), GetDataDir(), HelpMessage(), HMM_BITCOIND, InitLogging(), InitParameterInteraction(), Interrupt(), ArgsManager::IsArgSet(), IsSwitchChar(), LicenseInfo(), ArgsManager::ParseParameters(), PrintExceptionContinue(), ArgsManager::ReadConfigFile(), SelectParams(), Shutdown(), ArgsManager::SoftSetBoolArg(), strprintf, and WaitForShutdown().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 187 of file dashd.cpp.
References AppInit(), noui_connect(), RegisterPrettySignalHandlers(), RegisterPrettyTerminateHander(), and SetupEnvironment().
WaitForShutdown()
void WaitForShutdown ()
Definition at line 45 of file dashd.cpp.
References Interrupt(), MilliSleep(), and ShutdownRequested().
Referenced by AppInit().
Released under the MIT license