Dash Core: src/wallet/db.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
db.h File Reference
#include <clientversion.h>
#include <fs.h>
#include <serialize.h>
#include <streams.h>
#include <sync.h>
#include <util.h>
#include <version.h>
#include <atomic>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include <db_cxx.h>
Classes
class BerkeleyEnvironment
class BerkeleyDatabase
An instance of this class represents one database.
class BerkeleyBatch
RAII class that provides access to a Berkeley database.
Functions
BerkeleyEnvironment * GetWalletEnv (const fs::path &wallet_path, std::string &database_filename)
Get BerkeleyEnvironment and database filename given a wallet path.
Variables
static const unsigned int DEFAULT_WALLET_DBLOGSIZE = 100
static const bool DEFAULT_WALLET_PRIVDB = true
Function Documentation
GetWalletEnv()
BerkeleyEnvironment* GetWalletEnv (const fs::path & wallet_path, std::string & database_filename)
Get BerkeleyEnvironment and database filename given a wallet path.
Definition at line 60 of file db.cpp.
References LOCK.
Referenced by CWallet::AutoBackupWallet(), BerkeleyDatabase::BerkeleyDatabase(), BerkeleyBatch::Recover(), BerkeleyBatch::VerifyDatabaseFile(), and BerkeleyBatch::VerifyEnvironment().
Variable Documentation
DEFAULT_WALLET_DBLOGSIZE
const unsigned int DEFAULT_WALLET_DBLOGSIZE = 100 static
Definition at line 25 of file db.h.
Referenced by BerkeleyBatch::Flush(), and WalletInit::GetHelpString().
DEFAULT_WALLET_PRIVDB
const bool DEFAULT_WALLET_PRIVDB = true static
Definition at line 26 of file db.h.
Referenced by WalletInit::GetHelpString(), and BerkeleyEnvironment::Open().
Released under the MIT license