Dash Core: src/wallet/db.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
db.cpp File Reference
#include <wallet/db.h>
#include <addrman.h>
#include <hash.h>
#include <protocol.h>
#include <util.h>
#include <utilstrencodings.h>
#include <wallet/walletutil.h>
#include <stdint.h>
#include <sys/stat.h>
#include <boost/thread.hpp>
Functions
BerkeleyEnvironment * GetWalletEnv (const fs::path &wallet_path, std::string &database_filename)
Get BerkeleyEnvironment and database filename given a wallet path.
Variables
static const char * HEADER_END = "HEADER=END"
static const char * DATA_END = "DATA=END"
Function Documentation
GetWalletEnv()
BerkeleyEnvironment* GetWalletEnv (const fs::path & wallet_path, std::string & database_filename)
Get BerkeleyEnvironment and database filename given a wallet path.
Definition at line 60 of file db.cpp.
References LOCK.
Referenced by CWallet::AutoBackupWallet(), BerkeleyDatabase::BerkeleyDatabase(), BerkeleyBatch::Recover(), BerkeleyBatch::VerifyDatabaseFile(), and BerkeleyBatch::VerifyEnvironment().
Variable Documentation
DATA_END
const char* DATA_END = "DATA=END" static
Definition at line 371 of file db.cpp.
Referenced by BerkeleyEnvironment::Salvage().
HEADER_END
const char* HEADER_END = "HEADER=END" static
Definition at line 369 of file db.cpp.
Referenced by BerkeleyEnvironment::Salvage().
Released under the MIT license