Dash Core: src/dbwrapper.h File Reference
dbwrapper.h File Reference
#include "clientversion.h"
#include "serialize.h"
#include "streams.h"
#include "util.h"
#include "utilstrencodings.h"
#include "version.h"
#include <boost/filesystem/path.hpp>
#include <leveldb/db.h>
#include <leveldb/write_batch.h>
Classes
class dbwrapper_error
class CDBBatch
class CDBIterator
class CDBWrapper
Functions
void HandleError (const leveldb::Status &status) throw (dbwrapper_error)
Function Documentation
HandleError()
void HandleError (const leveldb::Status & status) throw (dbwrapper_error)
Definition at line 18 of file dbwrapper.cpp.
Referenced by CDBWrapper::CDBWrapper(), CDBWrapper::Exists(), CDBWrapper::Read(), and CDBWrapper::WriteBatch().