Dash Core: src/secp256k1/src/modules/ecdh/main_impl.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
main_impl.h File Reference
#include "include/secp256k1_ecdh.h"
#include "ecmult_const_impl.h"
Functions
static int ecdh_hash_function_sha256 (unsigned char *output, const unsigned char *x, const unsigned char *y, void *data)
int secp256k1_ecdh (const secp256k1_context *ctx, unsigned char *output, const secp256k1_pubkey *point, const unsigned char *scalar, secp256k1_ecdh_hash_function hashfp, void *data)
Compute an EC Diffie-Hellman secret in constant time Returns: 1: exponentiation was successful 0: scalar was invalid (zero or overflow) Args: ctx: pointer to a context object (cannot be NULL) Out: output: pointer to an array to be filled by the function In: pubkey: a pointer to a secp256k1_pubkey containing an initialized public key privkey: a 32-byte scalar with which to multiply the point hashfp: pointer to a hash function.
Variables
const secp256k1_ecdh_hash_function secp256k1_ecdh_hash_function_sha256 = ecdh_hash_function_sha256
An implementation of SHA256 hash function that applies to compressed public key.
const secp256k1_ecdh_hash_function secp256k1_ecdh_hash_function_default = ecdh_hash_function_sha256
A default ecdh hash function (currently equal to secp256k1_ecdh_hash_function_sha256).
Function Documentation
ecdh_hash_function_sha256()
static int ecdh_hash_function_sha256 (unsigned char * output, const unsigned char * x, const unsigned char * y, void * data) static
Definition at line 13 of file main_impl.h.
References secp256k1_sha256_finalize(), secp256k1_sha256_initialize(), and secp256k1_sha256_write().
secp256k1_ecdh()
int secp256k1_ecdh (const secp256k1_context * ctx, unsigned char * output, const secp256k1_pubkey * pubkey, const unsigned char * privkey, secp256k1_ecdh_hash_function hashfp, void * data)
Compute an EC Diffie-Hellman secret in constant time Returns: 1: exponentiation was successful 0: scalar was invalid (zero or overflow) Args: ctx: pointer to a context object (cannot be NULL) Out: output: pointer to an array to be filled by the function In: pubkey: a pointer to a secp256k1_pubkey containing an initialized public key privkey: a 32-byte scalar with which to multiply the point hashfp: pointer to a hash function.
If NULL, secp256k1_ecdh_hash_function_sha256 is used data: Arbitrary data pointer that is passed through
Definition at line 29 of file main_impl.h.
References ARG_CHECK, ctx, secp256k1_ecdh_hash_function_default, secp256k1_ecmult_const(), secp256k1_fe_get_b32(), secp256k1_fe_normalize(), secp256k1_ge_set_gej(), secp256k1_pubkey_load(), secp256k1_scalar_clear(), secp256k1_scalar_is_zero(), secp256k1_scalar_set_b32(), VERIFY_CHECK, secp256k1_ge::x, and secp256k1_ge::y.
Referenced by bench_ecdh(), Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdh(), test_bad_scalar(), test_ecdh_api(), and test_ecdh_generator_basepoint().
Variable Documentation
secp256k1_ecdh_hash_function_default
const secp256k1_ecdh_hash_function secp256k1_ecdh_hash_function_default = ecdh_hash_function_sha256
A default ecdh hash function (currently equal to secp256k1_ecdh_hash_function_sha256).
Definition at line 27 of file main_impl.h.
Referenced by secp256k1_ecdh().
secp256k1_ecdh_hash_function_sha256
const secp256k1_ecdh_hash_function secp256k1_ecdh_hash_function_sha256 = ecdh_hash_function_sha256
An implementation of SHA256 hash function that applies to compressed public key.
Definition at line 26 of file main_impl.h.
Released under the MIT license