Dash Core: src/secp256k1/src/ecdsa.h File Reference
ecdsa.h File Reference
#include <stddef.h>
#include "scalar.h"
#include "group.h"
#include "ecmult.h"
Functions
static int secp256k1_ecdsa_sig_parse (secp256k1_scalar *r, secp256k1_scalar *s, const unsigned char *sig, size_t size)
static int secp256k1_ecdsa_sig_serialize (unsigned char *sig, size_t *size, const secp256k1_scalar *r, const secp256k1_scalar *s)
static int secp256k1_ecdsa_sig_verify (const secp256k1_ecmult_context *ctx, const secp256k1_scalar *r, const secp256k1_scalar *s, const secp256k1_ge *pubkey, const secp256k1_scalar *message)
static int secp256k1_ecdsa_sig_sign (const secp256k1_ecmult_gen_context *ctx, secp256k1_scalar *r, secp256k1_scalar *s, const secp256k1_scalar *seckey, const secp256k1_scalar *message, const secp256k1_scalar *nonce, int *recid)
Function Documentation
secp256k1_ecdsa_sig_parse()
static int secp256k1_ecdsa_sig_parse (secp256k1_scalar * r, secp256k1_scalar * s, const unsigned char * sig, size_t size) static
Referenced by secp256k1_ecdsa_signature_parse_der().
secp256k1_ecdsa_sig_serialize()
static int secp256k1_ecdsa_sig_serialize (unsigned char * sig, size_t * size, const secp256k1_scalar * r, const secp256k1_scalar * s) static
Referenced by secp256k1_ecdsa_signature_serialize_der().
secp256k1_ecdsa_sig_sign()
static int secp256k1_ecdsa_sig_sign (const secp256k1_ecmult_gen_context * ctx, secp256k1_scalar * r, secp256k1_scalar * s, const secp256k1_scalar * seckey, const secp256k1_scalar * message, const secp256k1_scalar * nonce, int * recid) static
Referenced by random_sign(), run_context_tests(), secp256k1_ecdsa_sign(), and secp256k1_ecdsa_sign_recoverable().
secp256k1_ecdsa_sig_verify()
static int secp256k1_ecdsa_sig_verify (const secp256k1_ecmult_context * ctx, const secp256k1_scalar * r, const secp256k1_scalar * s, const secp256k1_ge * pubkey, const secp256k1_scalar * message) static
Referenced by run_context_tests(), secp256k1_ecdsa_verify(), test_ecdsa_edge_cases(), and test_ecdsa_sign_verify().