Dash Core: src/secp256k1/src/eckey_impl.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
eckey_impl.h File Reference
#include "eckey.h"
#include "scalar.h"
#include "field.h"
#include "group.h"
#include "ecmult_gen.h"
Functions
static int secp256k1_eckey_pubkey_parse (secp256k1_ge *elem, const unsigned char *pub, size_t size)
static int secp256k1_eckey_pubkey_serialize (secp256k1_ge *elem, unsigned char *pub, size_t *size, int compressed)
static int secp256k1_eckey_privkey_tweak_add (secp256k1_scalar *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_pubkey_tweak_add (const secp256k1_ecmult_context *ctx, secp256k1_ge *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_privkey_tweak_mul (secp256k1_scalar *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_pubkey_tweak_mul (const secp256k1_ecmult_context *ctx, secp256k1_ge *key, const secp256k1_scalar *tweak)
Function Documentation
secp256k1_eckey_privkey_tweak_add()
static int secp256k1_eckey_privkey_tweak_add (secp256k1_scalar * key, const secp256k1_scalar * tweak) static
Definition at line 55 of file eckey_impl.h.
References secp256k1_scalar_add(), and secp256k1_scalar_is_zero().
secp256k1_eckey_privkey_tweak_mul()
static int secp256k1_eckey_privkey_tweak_mul (secp256k1_scalar * key, const secp256k1_scalar * tweak) static
Definition at line 77 of file eckey_impl.h.
References secp256k1_scalar_is_zero(), and secp256k1_scalar_mul().
secp256k1_eckey_pubkey_parse()
static int secp256k1_eckey_pubkey_parse (secp256k1_ge * elem, const unsigned char * pub, size_t size) static
Definition at line 17 of file eckey_impl.h.
References secp256k1_fe_is_odd(), secp256k1_fe_set_b32(), secp256k1_ge_is_valid_var(), secp256k1_ge_set_xo_var(), secp256k1_ge_set_xy(), SECP256K1_TAG_PUBKEY_EVEN, SECP256K1_TAG_PUBKEY_HYBRID_EVEN, SECP256K1_TAG_PUBKEY_HYBRID_ODD, SECP256K1_TAG_PUBKEY_ODD, and SECP256K1_TAG_PUBKEY_UNCOMPRESSED.
secp256k1_eckey_pubkey_serialize()
static int secp256k1_eckey_pubkey_serialize (secp256k1_ge * elem, unsigned char * pub, size_t * size, int compressed) static
Definition at line 37 of file eckey_impl.h.
References secp256k1_fe_get_b32(), secp256k1_fe_is_odd(), secp256k1_fe_normalize_var(), secp256k1_ge_is_infinity(), SECP256K1_TAG_PUBKEY_EVEN, SECP256K1_TAG_PUBKEY_ODD, SECP256K1_TAG_PUBKEY_UNCOMPRESSED, secp256k1_ge::x, and secp256k1_ge::y.
secp256k1_eckey_pubkey_tweak_add()
static int secp256k1_eckey_pubkey_tweak_add (const secp256k1_ecmult_context * ctx, secp256k1_ge * key, const secp256k1_scalar * tweak) static
Definition at line 63 of file eckey_impl.h.
References ctx, secp256k1_ecmult(), secp256k1_ge_set_gej(), secp256k1_gej_is_infinity(), secp256k1_gej_set_ge(), and secp256k1_scalar_set_int().
secp256k1_eckey_pubkey_tweak_mul()
static int secp256k1_eckey_pubkey_tweak_mul (const secp256k1_ecmult_context * ctx, secp256k1_ge * key, const secp256k1_scalar * tweak) static
Definition at line 86 of file eckey_impl.h.
References ctx, secp256k1_ecmult(), secp256k1_ge_set_gej(), secp256k1_gej_set_ge(), secp256k1_scalar_is_zero(), and secp256k1_scalar_set_int().
Released under the MIT license