Dash Core: src/secp256k1/src/ecmult_const_impl.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
ecmult_const_impl.h File Reference
#include "scalar.h"
#include "group.h"
#include "ecmult_const.h"
#include "ecmult_impl.h"
Macros
#define ECMULT_CONST_TABLE_GET_GE(r, pre, n, w)
Functions
static int secp256k1_wnaf_const (int *wnaf, secp256k1_scalar s, int w, int size)
Convert a number to WNAF notation.
static void secp256k1_ecmult_const (secp256k1_gej *r, const secp256k1_ge *a, const secp256k1_scalar *scalar, int size)
Macro Definition Documentation
ECMULT_CONST_TABLE_GET_GE
#define ECMULT_CONST_TABLE_GET_GE (r, pre, n, w)
Value:
do { \
    int m; \
    int abs_n = (n) * (((n) > 0) * 2 - 1); \
    int idx_n = abs_n / 2; \
    secp256k1_fe neg_y; \
    VERIFY_CHECK(((n) & 1) == 1); \
    VERIFY_CHECK((n) >= -((1 << ((w)-1)) - 1)); \
    VERIFY_CHECK((n) <=  ((1 << ((w)-1)) - 1)); \
    VERIFY_SETUP(secp256k1_fe_clear(&(r)->x)); \
    VERIFY_SETUP(secp256k1_fe_clear(&(r)->y)); \
    for (m = 0; m < ECMULT_TABLE_SIZE(w); m++) { \
        /* This loop is used to avoid secret data in array indices. See
         * the comment in ecmult_gen_impl.h for rationale. */ \
        secp256k1_fe_cmov(&(r)->x, &(pre)[m].x, m == idx_n); \
        secp256k1_fe_cmov(&(r)->y, &(pre)[m].y, m == idx_n); \
    } \
    (r)->infinity = 0; \
    secp256k1_fe_negate(&neg_y, &(r)->y, 1); \
    secp256k1_fe_cmov(&(r)->y, &neg_y, (n) != abs_n); \
} while(0)
Definition at line 16 of file ecmult_const_impl.h.
Referenced by secp256k1_ecmult_const().
Function Documentation
secp256k1_ecmult_const()
static void secp256k1_ecmult_const (secp256k1_gej * r, const secp256k1_ge * a, const secp256k1_scalar * scalar, int size) static
Definition at line 120 of file ecmult_const_impl.h.
References ECMULT_CONST_TABLE_GET_GE, ECMULT_TABLE_SIZE, secp256k1_ecmult_odd_multiples_table_globalz_windowa(), secp256k1_fe_mul(), secp256k1_fe_normalize_weak(), secp256k1_ge_from_storage(), secp256k1_ge_neg(), secp256k1_ge_set_gej(), secp256k1_ge_storage_cmov(), secp256k1_ge_to_storage(), secp256k1_gej_add_ge(), secp256k1_gej_double_nonzero(), secp256k1_gej_double_var(), secp256k1_gej_set_ge(), secp256k1_wnaf_const(), VERIFY_CHECK, WINDOW_A, WNAF_SIZE, WNAF_SIZE_BITS, and secp256k1_gej::z.
secp256k1_wnaf_const()
static int secp256k1_wnaf_const (int * wnaf, secp256k1_scalar s, int w, int size) static
Convert a number to WNAF notation.
The number becomes represented by sum(2^{wi} * wnaf[i], i=0..WNAF_SIZE(w)+1) - return_val. It has the following guarantees:
each wnaf[i] an odd integer between -(1 << w) and (1 << w)
each wnaf[i] is nonzero
the number of words set is always WNAF_SIZE(w) + 1
Adapted from The Width-w NAF Method Provides Small Memory and Fast Elliptic Scalar Multiplications Secure against Side Channel Attacks, Okeya and Tagaki. M. Joye (Ed.) CT-RSA 2003, LNCS 2612, pp. 328-443, 2003. Springer-Verlagy Berlin Heidelberg 2003
Numbers reference steps of Algorithm SPA-resistant Width-w NAF with Odd Scalar on pp. 335
Definition at line 51 of file ecmult_const_impl.h.
References secp256k1_scalar_cadd_bit(), secp256k1_scalar_cond_negate(), secp256k1_scalar_is_even(), secp256k1_scalar_is_high(), secp256k1_scalar_is_one(), secp256k1_scalar_is_zero(), secp256k1_scalar_negate(), secp256k1_scalar_shr_int(), VERIFY_CHECK, and WNAF_SIZE_BITS.
Referenced by bench_wnaf_const(), secp256k1_ecmult_const(), and test_constant_wnaf().
Released under the MIT license