Dash Core: src/compat/endian.h File Reference
endian.h File Reference
#include <stdint.h>
#include "compat/byteswap.h"
Functions
uint16_t htole16 (uint16_t host_16bits)
uint16_t be16toh (uint16_t big_endian_16bits)
uint16_t le16toh (uint16_t little_endian_16bits)
uint32_t htobe32 (uint32_t host_32bits)
uint32_t htole32 (uint32_t host_32bits)
uint32_t be32toh (uint32_t big_endian_32bits)
uint32_t le32toh (uint32_t little_endian_32bits)
uint64_t htobe64 (uint64_t host_64bits)
uint64_t htole64 (uint64_t host_64bits)
uint64_t be64toh (uint64_t big_endian_64bits)
uint64_t le64toh (uint64_t little_endian_64bits)
Function Documentation
be16toh()
uint16_t be16toh (uint16_t big_endian_16bits) inline
Definition at line 125 of file endian.h.
be32toh()
uint32_t be32toh (uint32_t big_endian_32bits) inline
Definition at line 153 of file endian.h.
Referenced by ReadBE32(), and ser_readdata32be().
be64toh()
uint64_t be64toh (uint64_t big_endian_64bits) inline
Definition at line 181 of file endian.h.
Referenced by ReadBE64().
htobe32()
uint32_t htobe32 (uint32_t host_32bits) inline
Definition at line 139 of file endian.h.
Referenced by ser_writedata32be(), and WriteBE32().
htobe64()
uint64_t htobe64 (uint64_t host_64bits) inline
Definition at line 167 of file endian.h.
Referenced by WriteBE64().
htole16()
uint16_t htole16 (uint16_t host_16bits) inline
Definition at line 118 of file endian.h.
Referenced by ser_writedata16(), and WriteLE16().
htole32()
uint32_t htole32 (uint32_t host_32bits) inline
Definition at line 146 of file endian.h.
Referenced by ser_writedata32(), and WriteLE32().
htole64()
uint64_t htole64 (uint64_t host_64bits) inline
Definition at line 174 of file endian.h.
Referenced by ser_writedata64(), and WriteLE64().
le16toh()
uint16_t le16toh (uint16_t little_endian_16bits) inline
Definition at line 132 of file endian.h.
Referenced by ReadLE16(), and ser_readdata16().
le32toh()
uint32_t le32toh (uint32_t little_endian_32bits) inline
Definition at line 160 of file endian.h.
Referenced by ReadLE32(), and ser_readdata32().
le64toh()
uint64_t le64toh (uint64_t little_endian_64bits) inline
Definition at line 188 of file endian.h.
Referenced by ReadLE64(), and ser_readdata64().