Dash Core: src/support/events.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
events.h File Reference
#include <ios>
#include <memory>
#include <event2/event.h>
#include <event2/http.h>
Macros
#define MAKE_RAII(type)
Functions
MAKE_RAII (event_base)
MAKE_RAII (event)
MAKE_RAII (evhttp)
MAKE_RAII (evhttp_request)
MAKE_RAII (evhttp_connection)
raii_event_base obtain_event_base ()
raii_event obtain_event (struct event_base *base, evutil_socket_t s, short events, event_callback_fn cb, void *arg)
raii_evhttp obtain_evhttp (struct event_base *base)
raii_evhttp_request obtain_evhttp_request (void(*cb)(struct evhttp_request *, void *), void *arg)
raii_evhttp_connection obtain_evhttp_connection_base (struct event_base *base, std::string host, uint16_t port)
Macro Definition Documentation
MAKE_RAII
#define MAKE_RAII (type)
Value:
/* deleter */\
struct type##_deleter {\
    void operator()(struct type* ob) {\
        type##_free(ob);\
    }\
};\
/* unique ptr typedef */\
typedef std::unique_ptr<struct type, type##_deleter> raii_##type
Definition at line 14 of file events.h.
Function Documentation
MAKE_RAII() [1/5]
MAKE_RAII (event_base)
MAKE_RAII() [2/5]
MAKE_RAII (event)
MAKE_RAII() [3/5]
MAKE_RAII (evhttp)
MAKE_RAII() [4/5]
MAKE_RAII (evhttp_request)
MAKE_RAII() [5/5]
MAKE_RAII (evhttp_connection)
obtain_event()
raii_event obtain_event (struct event_base * base, evutil_socket_t s, short events, event_callback_fn cb, void * arg) inline
Definition at line 37 of file events.h.
obtain_event_base()
raii_event_base obtain_event_base () inline
Definition at line 30 of file events.h.
Referenced by CallRPC(), and InitHTTPServer().
obtain_evhttp()
raii_evhttp obtain_evhttp (struct event_base * base) inline
Definition at line 41 of file events.h.
Referenced by InitHTTPServer().
obtain_evhttp_connection_base()
raii_evhttp_connection obtain_evhttp_connection_base (struct event_base * base, std::string host, uint16_t port) inline
Definition at line 49 of file events.h.
Referenced by CallRPC().
obtain_evhttp_request()
raii_evhttp_request obtain_evhttp_request (void(*)(struct evhttp_request *, void *) cb, void * arg) inline
Definition at line 45 of file events.h.
Referenced by CallRPC().
Released under the MIT license