Dash Core: src/secp256k1/src/field.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
field.h File Reference
Functions
static void secp256k1_fe_normalize (secp256k1_fe *r)
Field element module.
static void secp256k1_fe_normalize_weak (secp256k1_fe *r)
Weakly normalize a field element: reduce it magnitude to 1, but don't fully normalize.
static void secp256k1_fe_normalize_var (secp256k1_fe *r)
Normalize a field element, without constant-time guarantee.
static int secp256k1_fe_normalizes_to_zero (secp256k1_fe *r)
Verify whether a field element represents zero i.e.
static int secp256k1_fe_normalizes_to_zero_var (secp256k1_fe *r)
Verify whether a field element represents zero i.e.
static void secp256k1_fe_set_int (secp256k1_fe *r, int a)
Set a field element equal to a small integer.
static int secp256k1_fe_is_zero (const secp256k1_fe *a)
Verify whether a field element is zero.
static int secp256k1_fe_is_odd (const secp256k1_fe *a)
Check the "oddness" of a field element.
static int secp256k1_fe_equal_var (const secp256k1_fe *a, const secp256k1_fe *b)
Compare two field elements.
static int secp256k1_fe_cmp_var (const secp256k1_fe *a, const secp256k1_fe *b)
Compare two field elements.
static int secp256k1_fe_set_b32 (secp256k1_fe *r, const unsigned char *a)
Set a field element equal to 32-byte big endian value.
static void secp256k1_fe_get_b32 (unsigned char *r, const secp256k1_fe *a)
Convert a field element to a 32-byte big endian value.
static void secp256k1_fe_negate (secp256k1_fe *r, const secp256k1_fe *a, int m)
Set a field element equal to the additive inverse of another.
static void secp256k1_fe_mul_int (secp256k1_fe *r, int a)
Multiplies the passed field element with a small integer constant.
static void secp256k1_fe_add (secp256k1_fe *r, const secp256k1_fe *a)
Adds a field element to another.
static void secp256k1_fe_mul (secp256k1_fe *r, const secp256k1_fe *a, const secp256k1_fe *SECP256K1_RESTRICT b)
Sets a field element to be the product of two others.
static void secp256k1_fe_sqr (secp256k1_fe *r, const secp256k1_fe *a)
Sets a field element to be the square of another.
static int secp256k1_fe_sqrt_var (secp256k1_fe *r, const secp256k1_fe *a)
If a has a square root, it is computed in r and 1 is returned.
static void secp256k1_fe_inv (secp256k1_fe *r, const secp256k1_fe *a)
Sets a field element to be the (modular) inverse of another.
static void secp256k1_fe_inv_var (secp256k1_fe *r, const secp256k1_fe *a)
Potentially faster version of secp256k1_fe_inv, without constant-time guarantee.
static void secp256k1_fe_inv_all_var (size_t len, secp256k1_fe *r, const secp256k1_fe *a)
Calculate the (modular) inverses of a batch of field elements.
static void secp256k1_fe_to_storage (secp256k1_fe_storage *r, const secp256k1_fe *a)
Convert a field element to the storage type.
static void secp256k1_fe_from_storage (secp256k1_fe *r, const secp256k1_fe_storage *a)
Convert a field element back from the storage type.
static void secp256k1_fe_storage_cmov (secp256k1_fe_storage *r, const secp256k1_fe_storage *a, int flag)
If flag is true, set *r equal to *a; otherwise leave it.
static void secp256k1_fe_cmov (secp256k1_fe *r, const secp256k1_fe *a, int flag)
If flag is true, set *r equal to *a; otherwise leave it.
Function Documentation
secp256k1_fe_add()
static void secp256k1_fe_add (secp256k1_fe * r, const secp256k1_fe * a) static
Adds a field element to another.
The result has the sum of the inputs' magnitudes as magnitude.
Referenced by bench_field_inverse(), bench_field_inverse_var(), bench_field_sqrt_var(), random_field_element_magnitude(), run_field_misc(), secp256k1_ecdsa_sig_recover(), secp256k1_ecdsa_sig_verify(), secp256k1_fe_equal_var(), secp256k1_fe_inv_var(), secp256k1_ge_is_valid_var(), secp256k1_ge_set_xquad_var(), secp256k1_gej_add_ge(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), secp256k1_gej_add_zinv_var(), secp256k1_gej_double_var(), secp256k1_gej_is_valid_var(), and test_sqrt().
secp256k1_fe_cmov()
static void secp256k1_fe_cmov (secp256k1_fe * r, const secp256k1_fe * a, int flag) static
If flag is true, set *r equal to *a; otherwise leave it.
Constant-time.
Referenced by run_field_misc(), and secp256k1_gej_add_ge().
secp256k1_fe_cmp_var()
static int secp256k1_fe_cmp_var (const secp256k1_fe * a, const secp256k1_fe * b) static
Compare two field elements.
Requires both inputs to be normalized
Referenced by gej_xyz_equals_gej(), run_field_misc(), secp256k1_ecdsa_sig_recover(), and secp256k1_ecdsa_sig_verify().
secp256k1_fe_equal_var()
static int secp256k1_fe_equal_var (const secp256k1_fe * a, const secp256k1_fe * b) static
Compare two field elements.
Requires magnitude-1 inputs.
Referenced by check_fe_equal(), ge_equals_ge(), ge_equals_gej(), run_field_convert(), run_field_misc(), run_point_times_order(), secp256k1_ge_is_valid_var(), secp256k1_gej_eq_x_var(), secp256k1_gej_is_valid_var(), secp256k1_schnorr_sig_verify(), test_ge(), and test_group_decompress().
secp256k1_fe_from_storage()
static void secp256k1_fe_from_storage (secp256k1_fe * r, const secp256k1_fe_storage * a) static
Convert a field element back from the storage type.
Referenced by run_field_convert(), run_field_misc(), and secp256k1_ge_from_storage().
secp256k1_fe_get_b32()
static void secp256k1_fe_get_b32 (unsigned char * r, const secp256k1_fe * a) static
Convert a field element to a 32-byte big endian value.
Requires the input to be normalized
Referenced by run_field_convert(), secp256k1_ecdh(), secp256k1_ecdsa_sig_sign(), secp256k1_eckey_pubkey_serialize(), secp256k1_fe_inv_var(), secp256k1_pubkey_save(), and secp256k1_schnorr_sig_sign().
secp256k1_fe_inv()
static void secp256k1_fe_inv (secp256k1_fe * r, const secp256k1_fe * a) static
Sets a field element to be the (modular) inverse of another.
Requires the input's magnitude to be at most 8. The output magnitude is 1 (but not guaranteed to be normalized).
Referenced by bench_field_inverse(), run_field_inv(), secp256k1_ge_set_gej(), and secp256k1_ge_set_table_gej_var().
secp256k1_fe_inv_all_var()
static void secp256k1_fe_inv_all_var (size_t len, secp256k1_fe * r, const secp256k1_fe * a) static
Calculate the (modular) inverses of a batch of field elements.
Requires the inputs' magnitudes to be at most 8. The output magnitudes are 1 (but not guaranteed to be normalized). The inputs and outputs must not overlap in memory.
Referenced by run_field_inv_all_var(), secp256k1_ge_set_all_gej_var(), and test_ge().
secp256k1_fe_inv_var()
static void secp256k1_fe_inv_var (secp256k1_fe * r, const secp256k1_fe * a) static
Potentially faster version of secp256k1_fe_inv, without constant-time guarantee.
Referenced by bench_field_inverse_var(), run_field_inv_var(), secp256k1_ge_set_gej_var(), and test_ge().
secp256k1_fe_is_odd()
static int secp256k1_fe_is_odd (const secp256k1_fe * a) static
Check the "oddness" of a field element.
Requires the input to be normalized.
Referenced by secp256k1_ecdh(), secp256k1_ecdsa_sig_sign(), secp256k1_eckey_pubkey_parse(), secp256k1_eckey_pubkey_serialize(), secp256k1_ge_set_xo_var(), secp256k1_schnorr_sig_sign(), secp256k1_schnorr_sig_verify(), and test_group_decompress().
secp256k1_fe_is_zero()
static int secp256k1_fe_is_zero (const secp256k1_fe * a) static
Verify whether a field element is zero.
Requires the input to be normalized.
Referenced by random_fe_non_zero(), random_group_element_jacobian_test(), secp256k1_ecmult_gen_blind(), secp256k1_gej_rescale(), secp256k1_pubkey_load(), test_ge(), and test_sqrt().
secp256k1_fe_mul()
static void secp256k1_fe_mul (secp256k1_fe * r, const secp256k1_fe * a, const secp256k1_fe *SECP256K1_RESTRICT b) static
Sets a field element to be the product of two others.
Requires the inputs' magnitudes to be at most 8. The output magnitude is 1 (but not guaranteed to be normalized).
Referenced by bench_field_mul(), check_fe_inverse(), ge_equals_gej(), random_group_element_jacobian_test(), run_field_misc(), run_sqrt(), secp256k1_ecmult(), secp256k1_ecmult_const(), secp256k1_ecmult_odd_multiples_table(), secp256k1_fe_inv(), secp256k1_fe_inv_all_var(), secp256k1_fe_inv_var(), secp256k1_fe_sqrt_var(), secp256k1_ge_globalz_set_table_gej(), secp256k1_ge_is_valid_var(), secp256k1_ge_set_gej(), secp256k1_ge_set_gej_var(), secp256k1_ge_set_gej_zinv(), secp256k1_ge_set_table_gej_var(), secp256k1_ge_set_xquad_var(), secp256k1_gej_add_ge(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), secp256k1_gej_add_zinv_var(), secp256k1_gej_double_var(), secp256k1_gej_eq_x_var(), secp256k1_gej_is_valid_var(), secp256k1_gej_rescale(), and test_ge().
secp256k1_fe_mul_int()
static void secp256k1_fe_mul_int (secp256k1_fe * r, int a) static
Multiplies the passed field element with a small integer constant.
Multiplies the magnitude by that small integer.
Referenced by random_field_element_magnitude(), run_field_misc(), run_sqr(), secp256k1_gej_add_ge(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), secp256k1_gej_add_zinv_var(), secp256k1_gej_double_var(), and secp256k1_gej_is_valid_var().
secp256k1_fe_negate()
static void secp256k1_fe_negate (secp256k1_fe * r, const secp256k1_fe * a, int m) static
Set a field element equal to the additive inverse of another.
Takes a maximum magnitude of the input as an argument. The magnitude of the output is one higher.
Referenced by random_fe_non_square(), random_field_element_magnitude(), run_field_misc(), run_sqr(), run_sqrt(), secp256k1_fe_equal_var(), secp256k1_ge_neg(), secp256k1_ge_set_xo_var(), secp256k1_gej_add_ge(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), secp256k1_gej_add_zinv_var(), secp256k1_gej_double_var(), secp256k1_gej_neg(), and test_sqrt().
secp256k1_fe_normalize()
static void secp256k1_fe_normalize (secp256k1_fe * r) static
Field element module.
Field elements can be represented in several ways, but code accessing it (and implementations) need to take certain properties into account:
Each field element can be normalized or not.
Each field element has a magnitude, which represents how far away its representation is away from normalization. Normalized elements always have a magnitude of 1, but a magnitude of 1 doesn't imply normality.Normalize a field element.
Referenced by bench_field_normalize(), gej_xyz_equals_gej(), random_fe_non_zero(), random_field_element_magnitude(), random_group_element_test(), run_sqr(), secp256k1_ecdh(), secp256k1_ecdsa_sig_sign(), secp256k1_ge_to_storage(), secp256k1_schnorr_sig_sign(), and test_sqrt().
secp256k1_fe_normalize_var()
static void secp256k1_fe_normalize_var (secp256k1_fe * r) static
Normalize a field element, without constant-time guarantee.
Referenced by check_fe_equal(), run_field_misc(), run_point_times_order(), secp256k1_eckey_pubkey_serialize(), secp256k1_fe_inv_var(), secp256k1_ge_set_xo_var(), secp256k1_pubkey_save(), secp256k1_schnorr_sig_verify(), and test_group_decompress().
secp256k1_fe_normalize_weak()
static void secp256k1_fe_normalize_weak (secp256k1_fe * r) static
Weakly normalize a field element: reduce it magnitude to 1, but don't fully normalize.
Referenced by bench_field_normalize_weak(), check_fe_equal(), ge_equals_gej(), secp256k1_ecmult_const(), secp256k1_ge_is_valid_var(), secp256k1_ge_neg(), secp256k1_gej_add_ge(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_zinv_var(), secp256k1_gej_double_var(), secp256k1_gej_eq_x_var(), secp256k1_gej_is_valid_var(), and secp256k1_gej_neg().
secp256k1_fe_normalizes_to_zero()
static int secp256k1_fe_normalizes_to_zero (secp256k1_fe * r) static
Verify whether a field element represents zero i.e.
would normalize to a zero value. The field implementation may optionally normalize the input, but this should not be relied upon.
Referenced by secp256k1_gej_add_ge().
secp256k1_fe_normalizes_to_zero_var()
static int secp256k1_fe_normalizes_to_zero_var (secp256k1_fe * r) static
Verify whether a field element represents zero i.e.
would normalize to a zero value. The field implementation may optionally normalize the input, but this should not be relied upon.
Referenced by secp256k1_fe_equal_var(), secp256k1_fe_inv_var(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), and secp256k1_gej_add_zinv_var().
secp256k1_fe_set_b32()
static int secp256k1_fe_set_b32 (secp256k1_fe * r, const unsigned char * a) static
Set a field element equal to 32-byte big endian value.
If successful, the resulting field element is normalized.
Referenced by bench_setup(), random_fe(), random_fe_test(), random_field_element_test(), run_field_convert(), secp256k1_ecdsa_sig_recover(), secp256k1_ecdsa_sig_verify(), secp256k1_eckey_pubkey_parse(), secp256k1_ecmult_gen_blind(), secp256k1_ecmult_gen_context_build(), secp256k1_fe_inv_var(), secp256k1_pubkey_load(), secp256k1_schnorr_sig_recover(), and secp256k1_schnorr_sig_verify().
secp256k1_fe_set_int()
static void secp256k1_fe_set_int (secp256k1_fe * r, int a) static
Set a field element equal to a small integer.
Resulting field element is normalized.
Referenced by run_sqr(), run_sqrt(), secp256k1_ge_is_valid_var(), secp256k1_ge_set_gej(), secp256k1_ge_set_gej_var(), secp256k1_ge_set_xquad_var(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), secp256k1_gej_add_zinv_var(), secp256k1_gej_double_var(), secp256k1_gej_set_ge(), and secp256k1_gej_set_infinity().
secp256k1_fe_sqr()
static void secp256k1_fe_sqr (secp256k1_fe * r, const secp256k1_fe * a) static
Sets a field element to be the square of another.
Requires the input's magnitude to be at most 8. The output magnitude is 1 (but not guaranteed to be normalized).
Referenced by bench_field_sqr(), ge_equals_gej(), random_group_element_jacobian_test(), run_point_times_order(), run_sqr(), run_sqrt(), secp256k1_fe_inv(), secp256k1_fe_sqrt_var(), secp256k1_ge_is_valid_var(), secp256k1_ge_set_gej(), secp256k1_ge_set_gej_var(), secp256k1_ge_set_gej_zinv(), secp256k1_ge_set_xquad_var(), secp256k1_gej_add_ge(), secp256k1_gej_add_ge_var(), secp256k1_gej_add_var(), secp256k1_gej_add_zinv_var(), secp256k1_gej_double_var(), secp256k1_gej_eq_x_var(), secp256k1_gej_is_valid_var(), secp256k1_gej_rescale(), test_ge(), and test_group_decompress().
secp256k1_fe_sqrt_var()
static int secp256k1_fe_sqrt_var (secp256k1_fe * r, const secp256k1_fe * a) static
If a has a square root, it is computed in r and 1 is returned.
If a does not have a square root, the root of its negation is computed and 0 is returned. The input's magnitude can be at most 8. The output magnitude is 1 (but not guaranteed to be normalized). The result in r will always be a square itself.
Referenced by bench_field_sqrt_var(), random_fe_non_square(), secp256k1_ge_set_xquad_var(), test_group_decompress(), and test_sqrt().
secp256k1_fe_storage_cmov()
static void secp256k1_fe_storage_cmov (secp256k1_fe_storage * r, const secp256k1_fe_storage * a, int flag) static
If flag is true, set *r equal to *a; otherwise leave it.
Constant-time.
Referenced by run_field_misc(), and secp256k1_ge_storage_cmov().
secp256k1_fe_to_storage()
static void secp256k1_fe_to_storage (secp256k1_fe_storage * r, const secp256k1_fe * a) static
Convert a field element to the storage type.
Referenced by run_field_convert(), run_field_misc(), and secp256k1_ge_to_storage().
Released under the MIT license