Dash Core: src/secp256k1/src/field_5x52_impl.h File Reference
field_5x52_impl.h File Reference
#include <string.h>
#include "util.h"
#include "num.h"
#include "field.h"
#include "field_5x52_int128_impl.h"
Functions
static void secp256k1_fe_verify (const secp256k1_fe *a)
static void secp256k1_fe_normalize (secp256k1_fe *r)
static void secp256k1_fe_normalize_weak (secp256k1_fe *r)
static void secp256k1_fe_normalize_var (secp256k1_fe *r)
static int secp256k1_fe_normalizes_to_zero (secp256k1_fe *r)
static int secp256k1_fe_normalizes_to_zero_var (secp256k1_fe *r)
static SECP256K1_INLINE void secp256k1_fe_set_int (secp256k1_fe *r, int a)
static SECP256K1_INLINE int secp256k1_fe_is_zero (const secp256k1_fe *a)
static SECP256K1_INLINE int secp256k1_fe_is_odd (const secp256k1_fe *a)
static SECP256K1_INLINE void secp256k1_fe_clear (secp256k1_fe *a)
static int secp256k1_fe_cmp_var (const secp256k1_fe *a, const secp256k1_fe *b)
static int secp256k1_fe_set_b32 (secp256k1_fe *r, const unsigned char *a)
static void secp256k1_fe_get_b32 (unsigned char *r, const secp256k1_fe *a)
static SECP256K1_INLINE void secp256k1_fe_negate (secp256k1_fe *r, const secp256k1_fe *a, int m)
static SECP256K1_INLINE void secp256k1_fe_mul_int (secp256k1_fe *r, int a)
static SECP256K1_INLINE void secp256k1_fe_add (secp256k1_fe *r, const secp256k1_fe *a)
static void secp256k1_fe_mul (secp256k1_fe *r, const secp256k1_fe *a, const secp256k1_fe *SECP256K1_RESTRICT b)
static void secp256k1_fe_sqr (secp256k1_fe *r, const secp256k1_fe *a)
static SECP256K1_INLINE void secp256k1_fe_cmov (secp256k1_fe *r, const secp256k1_fe *a, int flag)
static SECP256K1_INLINE void secp256k1_fe_storage_cmov (secp256k1_fe_storage *r, const secp256k1_fe_storage *a, int flag)
static void secp256k1_fe_to_storage (secp256k1_fe_storage *r, const secp256k1_fe *a)
static SECP256K1_INLINE void secp256k1_fe_from_storage (secp256k1_fe *r, const secp256k1_fe_storage *a)
Function Documentation
secp256k1_fe_add()
static SECP256K1_INLINE void secp256k1_fe_add (secp256k1_fe * r, const secp256k1_fe * a) static
Definition at line 362 of file field_5x52_impl.h.
secp256k1_fe_clear()
static SECP256K1_INLINE void secp256k1_fe_clear (secp256k1_fe * a) static
Definition at line 261 of file field_5x52_impl.h.
secp256k1_fe_cmov()
static SECP256K1_INLINE void secp256k1_fe_cmov (secp256k1_fe * r, const secp256k1_fe * a, int flag) static
Definition at line 407 of file field_5x52_impl.h.
secp256k1_fe_cmp_var()
static int secp256k1_fe_cmp_var (const secp256k1_fe * a, const secp256k1_fe * b) static
Definition at line 272 of file field_5x52_impl.h.
secp256k1_fe_from_storage()
static SECP256K1_INLINE void secp256k1_fe_from_storage (secp256k1_fe * r, const secp256k1_fe_storage * a) static
Definition at line 444 of file field_5x52_impl.h.
secp256k1_fe_get_b32()
static void secp256k1_fe_get_b32 (unsigned char * r, const secp256k1_fe * a) static
Convert a field element to a 32-byte big endian value. Requires the input to be normalized
Definition at line 314 of file field_5x52_impl.h.
secp256k1_fe_is_odd()
static SECP256K1_INLINE int secp256k1_fe_is_odd (const secp256k1_fe * a) static
Definition at line 253 of file field_5x52_impl.h.
secp256k1_fe_is_zero()
static SECP256K1_INLINE int secp256k1_fe_is_zero (const secp256k1_fe * a) static
Definition at line 244 of file field_5x52_impl.h.
secp256k1_fe_mul()
static void secp256k1_fe_mul (secp256k1_fe * r, const secp256k1_fe * a, const secp256k1_fe *SECP256K1_RESTRICT b) static
Definition at line 378 of file field_5x52_impl.h.
secp256k1_fe_mul_int()
static SECP256K1_INLINE void secp256k1_fe_mul_int (secp256k1_fe * r, int a) static
Definition at line 349 of file field_5x52_impl.h.
secp256k1_fe_negate()
static SECP256K1_INLINE void secp256k1_fe_negate (secp256k1_fe * r, const secp256k1_fe * a, int m) static
Definition at line 332 of file field_5x52_impl.h.
secp256k1_fe_normalize()
static void secp256k1_fe_normalize (secp256k1_fe * r) static
Definition at line 59 of file field_5x52_impl.h.
secp256k1_fe_normalize_var()
static void secp256k1_fe_normalize_var (secp256k1_fe * r) static
Definition at line 126 of file field_5x52_impl.h.
secp256k1_fe_normalize_weak()
static void secp256k1_fe_normalize_weak (secp256k1_fe * r) static
Definition at line 102 of file field_5x52_impl.h.
secp256k1_fe_normalizes_to_zero()
static int secp256k1_fe_normalizes_to_zero (secp256k1_fe * r) static
Definition at line 170 of file field_5x52_impl.h.
secp256k1_fe_normalizes_to_zero_var()
static int secp256k1_fe_normalizes_to_zero_var (secp256k1_fe * r) static
Definition at line 193 of file field_5x52_impl.h.
secp256k1_fe_set_b32()
static int secp256k1_fe_set_b32 (secp256k1_fe * r, const unsigned char * a) static
Definition at line 291 of file field_5x52_impl.h.
secp256k1_fe_set_int()
static SECP256K1_INLINE void secp256k1_fe_set_int (secp256k1_fe * r, int a) static
Definition at line 234 of file field_5x52_impl.h.
secp256k1_fe_sqr()
static void secp256k1_fe_sqr (secp256k1_fe * r, const secp256k1_fe * a) static
Definition at line 394 of file field_5x52_impl.h.
secp256k1_fe_storage_cmov()
static SECP256K1_INLINE void secp256k1_fe_storage_cmov (secp256k1_fe_storage * r, const secp256k1_fe_storage * a, int flag) static
Definition at line 424 of file field_5x52_impl.h.
secp256k1_fe_to_storage()
static void secp256k1_fe_to_storage (secp256k1_fe_storage * r, const secp256k1_fe * a) static
Definition at line 434 of file field_5x52_impl.h.
secp256k1_fe_verify()
static void secp256k1_fe_verify (const secp256k1_fe * a) static
Implements arithmetic modulo FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE FFFFFC2F, represented as 5 uint64_t's in base 2^52. The values are allowed to contain >52 each. In particular, each FieldElem has a 'magnitude' associated with it. Internally, a magnitude M means each element is at most M*(2^53-1), except the most significant one, which is limited to M*(2^49-1). All operations accept any input with magnitude at most M, and have different rules for propagating magnitude to their output.
Definition at line 54 of file field_5x52_impl.h.
Referenced by secp256k1_fe_add(), secp256k1_fe_cmp_var(), secp256k1_fe_get_b32(), secp256k1_fe_is_odd(), secp256k1_fe_is_zero(), secp256k1_fe_mul(), secp256k1_fe_mul_int(), secp256k1_fe_negate(), secp256k1_fe_normalize(), secp256k1_fe_normalize_var(), secp256k1_fe_normalize_weak(), secp256k1_fe_set_b32(), secp256k1_fe_set_int(), and secp256k1_fe_sqr().