Dash Core: src/compat/glibc_compat.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
glibc_compat.cpp File Reference
#include <cstddef>
#include <cstdint>
Functions
void * memmove (void *a, const void *b, size_t c)
void * memcpy (void *a, const void *b, size_t c)
void __chk_fail (void) __attribute__((__noreturn__))
FDELT_TYPE __fdelt_warn (FDELT_TYPE a)
FDELT_TYPE __fdelt_chk (FDELT_TYPE) __attribute__((weak
FDELT_TYPE alias ("__fdelt_warn")))
float log2f_old (float x)
float __wrap_log2f (float x)
Function Documentation
__chk_fail()
void __chk_fail (void)
Referenced by __fdelt_warn().
__fdelt_chk()
FDELT_TYPE __fdelt_chk (FDELT_TYPE)
__fdelt_warn()
FDELT_TYPE __fdelt_warn (FDELT_TYPE a)
Definition at line 24 of file glibc_compat.cpp.
References __chk_fail().
__wrap_log2f()
float __wrap_log2f (float x)
Definition at line 71 of file glibc_compat.cpp.
References log2f_old().
alias()
FDELT_TYPE alias ("__fdelt_warn")
log2f_old()
float log2f_old (float x)
Referenced by __wrap_log2f().
memcpy()
void* memcpy (void * a, const void * b, size_t c)
Definition at line 18 of file glibc_compat.cpp.
References memmove().
Referenced by AddDataToRng(), AES128CBCDecrypt::AES128CBCDecrypt(), AES128CBCEncrypt::AES128CBCEncrypt(), AES256CBCDecrypt::AES256CBCDecrypt(), AES256CBCEncrypt::AES256CBCEncrypt(), base_blob< 512 >::base_blob(), bench_setup(), blake32(), blake32_init(), bmw32(), bmw32_init(), buffer_append(), CCrypter::BytesToKeySHA512AES(), CBCEncrypt(), prevector< N, T, Size, Diff >::change_capacity(), CHMAC_SHA256::CHMAC_SHA256(), CHMAC_SHA512::CHMAC_SHA512(), CMessageHeader::CMessageHeader(), CScriptCompressor::Compress(), compress_big(), compress_small(), convertSeed6(), cubehash_core(), cubehash_init(), CExtKey::Decode(), CExtPubKey::Decode(), CScriptCompressor::Decompress(), DecryptSecret(), CKey::Derive(), CExtKey::Derive(), CPubKey::Derive(), CExtPubKey::Derive(), ec_privkey_export_der(), ec_privkey_import_der(), ec_pubkey_parse_pointtest(), ecdh_hash_function_custom(), ecdsa_signature_parse_der_lax(), echo_big_close(), echo_big_core(), echo_small_close(), echo_small_core(), CExtKey::Encode(), CExtPubKey::Encode(), EncryptSecret(), CMnemonic::FromData(), CNetAddr::GetHash(), CNetAddr::GetIn6Addr(), CNetAddr::GetInAddr(), CService::GetKey(), GetStrongRandBytes(), groestl_big_close(), groestl_big_core(), groestl_small_close(), groestl_small_core(), init_big(), init_small(), CDataStream::insert(), CBLSId::InternalGetBuf(), CBLSId::InternalSetBuf(), CScriptCompressor::IsToKeyID(), CScriptCompressor::IsToScriptID(), jh_close(), jh_core(), jh_init(), keccak_core(), luffa3(), luffa4(), luffa5(), memcpy_int(), CExtKey::Neuter(), nonce_function_test_retry(), SignatureCacheHasher::operator()(), CBLSLazyWrapper< CBLSSignature >::operator=(), precomputed_nonce_function(), CConnman::PushMessage(), FastRandomContext::rand256(), CDataStream::read(), CBufferedFile::read(), ReadBE32(), ReadBE64(), CNetMessage::readData(), CNetMessage::readHeader(), ReadLE16(), ReadLE32(), ReadLE64(), run_eckey_edge_case_test(), secp256k1_der_parse_integer(), secp256k1_ecdsa_recoverable_signature_load(), secp256k1_ecdsa_recoverable_signature_save(), secp256k1_ecdsa_sig_serialize(), secp256k1_ecdsa_signature_load(), secp256k1_ecdsa_signature_save(), secp256k1_ecmult_context_clone(), secp256k1_ecmult_gen_blind(), secp256k1_ecmult_gen_context_clone(), secp256k1_hmac_sha256_initialize(), secp256k1_num_get_bin(), secp256k1_pubkey_load(), secp256k1_pubkey_save(), secp256k1_rfc6979_hmac_sha256_generate(), secp256k1_sha256_finalize(), secp256k1_sha256_write(), CKey::Set(), CPubKey::Set(), CBase58Data::SetData(), CNetAddr::SetInternal(), CNetAddr::SetIP(), CCrypter::SetKey(), CExtKey::SetMaster(), CNetAddr::SetRaw(), CNetAddr::SetSpecial(), CBase58Data::SetString(), shavite_big_core(), shavite_big_init(), shavite_small_core(), shavite_small_init(), sph_luffa224_init(), sph_luffa256_init(), sph_luffa384_init(), sph_luffa512_init(), test_ecdsa_end_to_end(), test_ecdsa_recovery_api(), test_exhaustive_verify(), uint512::trim256(), update_big(), update_small(), CRIPEMD160::Write(), CSHA1::Write(), CSHA512::Write(), CSHA256::Write(), CVectorWriter::write(), WriteBE32(), WriteBE64(), WriteLE16(), WriteLE32(), WriteLE64(), and zmq_send_multipart().
memmove()
void* memmove (void * a, const void * b, size_t c)
Referenced by prevector< N, T, Size, Diff >::assign_to(), damage_array(), prevector< N, T, Size, Diff >::erase(), prevector< N, T, Size, Diff >::fill(), prevector< N, T, Size, Diff >::insert(), and memcpy().
Released under the MIT license