Dash Core: src/governance/governance-classes.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
governance-classes.cpp File Reference
#include <governance/governance-classes.h>
#include <core_io.h>
#include <init.h>
#include <utilstrencodings.h>
#include <validation.h>
#include <boost/algorithm/string.hpp>
#include <univalue.h>
Functions
std::vector< std::string > SplitBy (const std::string &strCommand, const std::string &strDelimit)
CAmount ParsePaymentAmount (const std::string &strAmount)
Variables
CGovernanceTriggerManager triggerman
Function Documentation
ParsePaymentAmount()
CAmount ParsePaymentAmount (const std::string & strAmount)
Definition at line 35 of file governance-classes.cpp.
References MoneyRange(), and ParseFixedPoint().
Referenced by CSuperblock::ParsePaymentSchedule().
SplitBy()
std::vector<std::string> SplitBy (const std::string & strCommand, const std::string & strDelimit)
Definition at line 20 of file governance-classes.cpp.
Referenced by CSuperblock::ParsePaymentSchedule().
Variable Documentation
triggerman
CGovernanceTriggerManager triggerman
Definition at line 16 of file governance-classes.cpp.
Referenced by CGovernanceManager::AddCachedTriggers(), CGovernanceManager::AddGovernanceObject(), CSuperblockManager::GetBestSuperblock(), CSuperblockManager::IsSuperblockTriggered(), and CGovernanceManager::UpdateCachesAndClean().
Released under the MIT license