Dash Core: Algorithm
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
Algorithm
Functions
template<typename Range , typename Fn >
void immer::for_each_chunk (const Range &r, Fn &&fn)
template<typename Iterator , typename Fn >
void immer::for_each_chunk (const Iterator &first, const Iterator &last, Fn &&fn)
template<typename T , typename Fn >
void immer::for_each_chunk (const T *first, const T *last, Fn &&fn)
template<typename Range , typename Fn >
bool immer::for_each_chunk_p (const Range &r, Fn &&fn)
template<typename Iterator , typename Fn >
bool immer::for_each_chunk_p (const Iterator &first, const Iterator &last, Fn &&fn)
template<typename T , typename Fn >
bool immer::for_each_chunk_p (const T *first, const T *last, Fn &&fn)
template<typename Range , typename T >
T immer::accumulate (Range &&r, T init)
template<typename Range , typename T , typename Fn >
T immer::accumulate (Range &&r, T init, Fn fn)
template<typename Iterator , typename T >
T immer::accumulate (Iterator first, Iterator last, T init)
template<typename Iterator , typename T , typename Fn >
T immer::accumulate (Iterator first, Iterator last, T init, Fn fn)
template<typename Range , typename Fn >
Fn && immer::for_each (Range &&r, Fn &&fn)
template<typename Iterator , typename Fn >
Fn && immer::for_each (Iterator first, Iterator last, Fn &&fn)
template<typename Range , typename OutIter >
OutIter immer::copy (Range &&r, OutIter out)
template<typename InIter , typename OutIter >
OutIter immer::copy (InIter first, InIter last, OutIter out)
template<typename Range , typename Pred >
bool immer::all_of (Range &&r, Pred p)
template<typename Iter , typename Pred >
bool immer::all_of (Iter first, Iter last, Pred p)
Detailed Description
Function Documentation
accumulate() [1/4]
template<typename Range , typename T > T immer::accumulate (Range && r, T init)
Equivalent of std::accumulate applied to the range r.
Definition at line 98 of file algorithm.hpp.
References immer::accumulate(), and immer::for_each_chunk().
accumulate() [2/4]
template<typename Range , typename T , typename Fn > T immer::accumulate (Range && r, T init, Fn fn)
Definition at line 107 of file algorithm.hpp.
References immer::accumulate(), and immer::for_each_chunk().
accumulate() [3/4]
template<typename Iterator , typename T > T immer::accumulate (Iterator first, Iterator last, T init)
Equivalent of std::accumulate applied to the range .
Definition at line 120 of file algorithm.hpp.
References immer::accumulate(), and immer::for_each_chunk().
accumulate() [4/4]
template<typename Iterator , typename T , typename Fn > T immer::accumulate (Iterator first, Iterator last, T init, Fn fn)
Definition at line 129 of file algorithm.hpp.
References immer::for_each_chunk().
Referenced by immer::accumulate().
all_of() [1/2]
template<typename Range , typename Pred > bool immer::all_of (Range && r, Pred p)
Equivalent of std::all_of applied to the range r.
Definition at line 193 of file algorithm.hpp.
References immer::all_of(), and immer::for_each_chunk_p().
Referenced by CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetBuf().
all_of() [2/2]
template<typename Iter , typename Pred > bool immer::all_of (Iter first, Iter last, Pred p)
Equivalent of std::all_of applied to the range .
Definition at line 205 of file algorithm.hpp.
References immer::for_each_chunk_p().
Referenced by immer::all_of().
copy() [1/2]
template<typename Range , typename OutIter > OutIter immer::copy (Range && r, OutIter out)
Equivalent of std::copy applied to the range r.
Definition at line 168 of file algorithm.hpp.
References immer::copy(), and immer::for_each_chunk().
Referenced by immer::detail::rbts::node< T, MemoryPolicy, B, BL >::do_copy_inner_r(), immer::detail::rbts::node< T, MemoryPolicy, B, BL >::do_copy_inner_sr(), immer::detail::rbts::node< T, MemoryPolicy, B, BL >::ensure_mutable_relaxed_n(), CConnman::GetAddedNodeInfo(), CMedianFilter< T >::input(), immer::detail::rbts::concat_merger_mut< Node >::merge_inner(), prevector< N, T, Size, Diff >::iterator::operator++(), prevector< N, T, Size, Diff >::reverse_iterator::operator++(), prevector< N, T, Size, Diff >::const_iterator::operator++(), prevector< N, T, Size, Diff >::const_reverse_iterator::operator++(), prevector< N, T, Size, Diff >::iterator::operator--(), prevector< N, T, Size, Diff >::reverse_iterator::operator--(), prevector< N, T, Size, Diff >::const_iterator::operator--(), prevector< N, T, Size, Diff >::const_reverse_iterator::operator--(), immer::detail::rbts::concat_center_pos< Node >::realize(), immer::detail::rbts::concat_center_pos< Node >::realize_e(), and RelayAddress().
copy() [2/2]
template<typename InIter , typename OutIter > OutIter immer::copy (InIter first, InIter last, OutIter out)
Equivalent of std::copy applied to the range .
Definition at line 181 of file algorithm.hpp.
References immer::for_each_chunk().
Referenced by immer::copy().
for_each() [1/2]
template<typename Range , typename Fn > Fn&& immer::for_each (Range && r, Fn && fn)
Equivalent of std::for_each applied to the range r.
Definition at line 141 of file algorithm.hpp.
References immer::for_each_chunk().
for_each() [2/2]
template<typename Iterator , typename Fn > Fn&& immer::for_each (Iterator first, Iterator last, Fn && fn)
Equivalent of std::for_each applied to the range .
Definition at line 155 of file algorithm.hpp.
References immer::for_each_chunk().
for_each_chunk() [1/3]
template<typename Range , typename Fn > void immer::for_each_chunk (const Range & r, Fn && fn)
Apply operation fn for every contiguous chunk of data in the range sequentially. Each time, Fn is passed two value_type pointers describing a range over a part of the vector. This allows iterating over the elements in the most efficient way.
.. tip:: This is a low level method. Most of the time, :doc:other wrapper algorithms <algorithms> should be used instead.
Definition at line 41 of file algorithm.hpp.
Referenced by immer::accumulate(), immer::copy(), and immer::for_each().
for_each_chunk() [2/3]
template<typename Iterator , typename Fn > void immer::for_each_chunk (const Iterator & first, const Iterator & last, Fn && fn)
Definition at line 47 of file algorithm.hpp.
for_each_chunk() [3/3]
template<typename T , typename Fn > void immer::for_each_chunk (const T * first, const T * last, Fn && fn)
Definition at line 55 of file algorithm.hpp.
for_each_chunk_p() [1/3]
template<typename Range , typename Fn > bool immer::for_each_chunk_p (const Range & r, Fn && fn)
Apply operation fn for every contiguous chunk of data in the range sequentially, until fn returns false. Each time, Fn is passed two value_type pointers describing a range over a part of the vector. This allows iterating over the elements in the most efficient way.
.. tip:: This is a low level method. Most of the time, :doc:other wrapper algorithms <algorithms> should be used instead.
Definition at line 75 of file algorithm.hpp.
Referenced by immer::all_of().
for_each_chunk_p() [2/3]
template<typename Iterator , typename Fn > bool immer::for_each_chunk_p (const Iterator & first, const Iterator & last, Fn && fn)
Definition at line 81 of file algorithm.hpp.
for_each_chunk_p() [3/3]
template<typename T , typename Fn > bool immer::for_each_chunk_p (const T * first, const T * last, Fn && fn)
Definition at line 89 of file algorithm.hpp.
Released under the MIT license