Dash Core: src/httprpc.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
httprpc.h File Reference
#include <string>
#include <map>
Functions
bool StartHTTPRPC ()
Start HTTP RPC subsystem.
void InterruptHTTPRPC ()
Interrupt HTTP RPC subsystem.
void StopHTTPRPC ()
Stop HTTP RPC subsystem.
bool StartREST ()
Start HTTP REST subsystem.
void InterruptREST ()
Interrupt RPC REST subsystem.
void StopREST ()
Stop HTTP REST subsystem.
Function Documentation
InterruptHTTPRPC()
void InterruptHTTPRPC ()
Interrupt HTTP RPC subsystem.
Definition at line 238 of file httprpc.cpp.
References LogPrint().
Referenced by Interrupt().
InterruptREST()
void InterruptREST ()
Interrupt RPC REST subsystem.
Definition at line 611 of file rest.cpp.
Referenced by Interrupt().
StartHTTPRPC()
bool StartHTTPRPC ()
Start HTTP RPC subsystem.
Precondition; HTTP and RPC has been started.
Definition at line 224 of file httprpc.cpp.
References EventBase(), HTTPReq_JSONRPC(), httpRPCTimerInterface, InitRPCAuthentication(), LogPrint(), RegisterHTTPHandler(), and RPCRegisterTimerInterface().
Referenced by AppInitServers().
StartREST()
bool StartREST ()
Start HTTP REST subsystem.
Precondition; HTTP and RPC has been started.
Definition at line 604 of file rest.cpp.
References ARRAYLEN, handler, prefix, RegisterHTTPHandler(), and uri_prefixes.
Referenced by AppInitServers().
StopHTTPRPC()
void StopHTTPRPC ()
Stop HTTP RPC subsystem.
Precondition; HTTP and RPC has been stopped.
Definition at line 243 of file httprpc.cpp.
References httpRPCTimerInterface, LogPrint(), RPCUnregisterTimerInterface(), and UnregisterHTTPHandler().
Referenced by PrepareShutdown().
StopREST()
void StopREST ()
Stop HTTP REST subsystem.
Precondition; HTTP and RPC has been stopped.
Definition at line 615 of file rest.cpp.
References ARRAYLEN, prefix, UnregisterHTTPHandler(), and uri_prefixes.
Referenced by PrepareShutdown().
Released under the MIT license