Dash Core: src/script/ismine.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
ismine.cpp File Reference
#include <script/ismine.h>
#include <key.h>
#include <keystore.h>
#include <script/script.h>
#include <script/sign.h>
Typedefs
typedef std::vector< unsigned char > valtype
Functions
unsigned int HaveKeys (const std::vector< valtype > &pubkeys, const CKeyStore &keystore)
isminetype IsMine (const CKeyStore &keystore, const CTxDestination &dest)
isminetype IsMine (const CKeyStore &keystore, const CScript &scriptPubKey)
Typedef Documentation
valtype
typedef std::vector<unsigned char> valtype
Definition at line 14 of file ismine.cpp.
Function Documentation
HaveKeys()
unsigned int HaveKeys (const std::vector< valtype > & pubkeys, const CKeyStore & keystore)
Definition at line 16 of file ismine.cpp.
References CPubKey::GetID(), and CKeyStore::HaveKey().
Referenced by IsMine().
IsMine() [1/2]
isminetype IsMine (const CKeyStore & keystore, const CTxDestination & dest)
Definition at line 28 of file ismine.cpp.
References GetScriptForDestination(), and IsMine().
Referenced by TransactionRecord::decomposeTransaction(), getreceivedbyaccount(), getreceivedbyaddress(), ImportScript(), IsMine(), CWallet::IsMine(), WalletModel::IsSpendable(), listaccounts(), ListReceived(), ListTransactions(), ProcessImport(), AddressTablePriv::refreshAddressTable(), setaccount(), TransactionDesc::toHTML(), and validateaddress().
IsMine() [2/2]
isminetype IsMine (const CKeyStore & keystore, const CScript & scriptPubKey)
Definition at line 34 of file ismine.cpp.
References CKeyStore::GetCScript(), CPubKey::GetID(), CKeyStore::HaveKey(), HaveKeys(), CKeyStore::HaveWatchOnly(), IsMine(), ISMINE_NO, ISMINE_SPENDABLE, ISMINE_WATCH_SOLVABLE, ISMINE_WATCH_UNSOLVABLE, ProduceSignature(), Solver(), TX_MULTISIG, TX_NONSTANDARD, TX_NULL_DATA, TX_PUBKEY, TX_PUBKEYHASH, and TX_SCRIPTHASH.
Released under the MIT license