Dash Core: src/keepass.cpp File Reference
keepass.cpp File Reference
#include "keepass.h"
#include "wallet/crypter.h"
#include "clientversion.h"
#include "protocol.h"
#include "random.h"
#include "rpc/protocol.h"
#include "script/script.h"
#include "script/standard.h"
#include "util.h"
#include "utilstrencodings.h"
#include <boost/foreach.hpp>
#include <event2/event.h>
#include <event2/http.h>
#include <event2/buffer.h>
#include <event2/keyvalq_struct.h>
#include <openssl/bio.h>
#include <openssl/evp.h>
#include <openssl/buffer.h>
#include "support/cleanse.h"
Classes
struct HTTPReply
Functions
SecureString DecodeBase64Secure (const SecureString &sInput)
SecureString EncodeBase64Secure (const SecureString &sInput)
static void http_request_done (struct evhttp_request *req, void *ctx)
Variables
CKeePassIntegrator keePassInt
Function Documentation
DecodeBase64Secure()
SecureString DecodeBase64Secure (const SecureString & sInput)
Definition at line 38 of file keepass.cpp.
Referenced by CKeePassIntegrator::init(), CKeePassIntegrator::rpcGetLogins(), and CKeePassIntegrator::rpcSetLogin().
EncodeBase64Secure()
SecureString EncodeBase64Secure (const SecureString & sInput)
Definition at line 67 of file keepass.cpp.
Referenced by CKeePassIntegrator::generateKeePassKey(), CKeePassIntegrator::CKeePassRequest::init(), and CKeePassIntegrator::rpcAssociate().
http_request_done()
static void http_request_done (struct evhttp_request * req, void * ctx) static
Definition at line 266 of file keepass.cpp.
Referenced by CKeePassIntegrator::doHTTPPost().
Variable Documentation
keePassInt
CKeePassIntegrator keePassInt
Definition at line 35 of file keepass.cpp.
Referenced by AppInit2(), CWallet::ChangeWalletPassphrase(), CWallet::EncryptWallet(), keepass(), and CWallet::Unlock().