Dash Core: src/key.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
key.h File Reference
#include "pubkey.h"
#include "serialize.h"
#include "support/allocators/secure.h"
#include "uint256.h"
#include <stdexcept>
#include <vector>
Classes
class CKey
An encapsulated private key.
struct CExtKey
Typedefs
typedef std::vector< unsigned char, secure_allocator< unsigned char > > CPrivKey
secp256k1: const unsigned int PRIVATE_KEY_SIZE = 279; const unsigned int PUBLIC_KEY_SIZE = 65; const unsigned int SIGNATURE_SIZE = 72;
Functions
void ECC_Start (void)
Initialize the elliptic curve support.
void ECC_Stop (void)
Deinitialize the elliptic curve support.
bool ECC_InitSanityCheck (void)
Check that required EC support is available at runtime.
Typedef Documentation
CPrivKey
typedef std::vector<unsigned char, secure_allocator<unsigned char> > CPrivKey
secp256k1: const unsigned int PRIVATE_KEY_SIZE = 279; const unsigned int PUBLIC_KEY_SIZE = 65; const unsigned int SIGNATURE_SIZE = 72;
see www.keylength.com script supports up to 75 for single byte push secure_allocator is defined in allocators.h CPrivKey is a serialized private key, with all parameters included (279 bytes)
Definition at line 32 of file key.h.
Function Documentation
ECC_InitSanityCheck()
bool ECC_InitSanityCheck (void)
Check that required EC support is available at runtime.
Definition at line 297 of file key.cpp.
References CKey::GetPubKey(), CKey::MakeNewKey(), and CKey::VerifyPubKey().
Referenced by InitSanityCheck().
ECC_Start()
void ECC_Start (void)
Initialize the elliptic curve support.
May not be called twice without calling ECC_Stop first.
Definition at line 304 of file key.cpp.
References ctx, GetRandBytes(), LockObject(), secp256k1_context_create(), secp256k1_context_randomize(), secp256k1_context_sign, SECP256K1_CONTEXT_SIGN, and UnlockObject().
Referenced by AppInit2(), main(), and Secp256k1Init::Secp256k1Init().
ECC_Stop()
void ECC_Stop (void)
Deinitialize the elliptic curve support.
No-op if ECC_Start wasn't called first.
Definition at line 323 of file key.cpp.
References ctx, secp256k1_context_destroy(), and secp256k1_context_sign.
Referenced by main(), Shutdown(), and Secp256k1Init::~Secp256k1Init().
Released under the MIT license