Dash Core: src/rpc/masternode.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
masternode.cpp File Reference
#include <masternode/activemasternode.h>
#include <base58.h>
#include <clientversion.h>
#include <init.h>
#include <netbase.h>
#include <validation.h>
#include <util.h>
#include <utilmoneystr.h>
#include <txmempool.h>
#include <evo/specialtx.h>
#include <evo/deterministicmns.h>
#include <masternode/masternode-payments.h>
#include <masternode/masternode-sync.h>
#include <rpc/server.h>
#include <wallet/coincontrol.h>
#include <wallet/rpcwallet.h>
#include <fstream>
#include <iomanip>
#include <univalue.h>
Functions
UniValue masternodelist (const JSONRPCRequest &request)
void masternode_list_help ()
UniValue masternode_list (const JSONRPCRequest &request)
void masternode_connect_help ()
UniValue masternode_connect (const JSONRPCRequest &request)
void masternode_count_help ()
UniValue masternode_count (const JSONRPCRequest &request)
UniValue GetNextMasternodeForPayment (int heightShift)
void masternode_winner_help ()
UniValue masternode_winner (const JSONRPCRequest &request)
void masternode_current_help ()
UniValue masternode_current (const JSONRPCRequest &request)
void masternode_status_help ()
UniValue masternode_status (const JSONRPCRequest &request)
void masternode_winners_help ()
UniValue masternode_winners (const JSONRPCRequest &request)
void masternode_help ()
UniValue masternode (const JSONRPCRequest &request)
void RegisterMasternodeRPCCommands (CRPCTable &t)
Register masternode RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
GetNextMasternodeForPayment()
UniValue GetNextMasternodeForPayment (int heightShift)
Definition at line 156 of file masternode.cpp.
References deterministicMNManager, EncodeDestination(), ExtractDestination(), IsValidDestination(), Pair(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by masternode_current(), and masternode_winner().
masternode()
UniValue masternode (const JSONRPCRequest & request)
Definition at line 346 of file masternode.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), UniValue::isNull(), masternode_connect(), masternode_count(), masternode_current(), masternode_help(), masternode_list(), masternode_status(), masternode_winner(), masternode_winners(), and JSONRPCRequest::params.
masternode_connect()
UniValue masternode_connect (const JSONRPCRequest & request)
Definition at line 86 of file masternode.cpp.
References CConnman::AllNodes, JSONRPCRequest::fHelp, g_connman, UniValue::get_str(), JSONRPCError(), Lookup(), masternode_connect_help(), NODE_NETWORK, JSONRPCRequest::params, RPC_INTERNAL_ERROR, UniValue::size(), and strprintf.
Referenced by masternode().
masternode_connect_help()
void masternode_connect_help ()
Definition at line 76 of file masternode.cpp.
Referenced by masternode_connect().
masternode_count()
UniValue masternode_count (const JSONRPCRequest & request)
Definition at line 123 of file masternode.cpp.
References deterministicMNManager, JSONRPCRequest::fHelp, UniValue::get_str(), JSONRPCError(), masternode_count_help(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), strprintf, and UniValue::VOBJ.
Referenced by masternode().
masternode_count_help()
void masternode_count_help ()
Definition at line 105 of file masternode.cpp.
Referenced by masternode_count().
masternode_current()
UniValue masternode_current (const JSONRPCRequest & request)
Definition at line 202 of file masternode.cpp.
References JSONRPCRequest::fHelp, GetNextMasternodeForPayment(), and masternode_current_help().
Referenced by masternode().
masternode_current_help()
void masternode_current_help ()
Definition at line 194 of file masternode.cpp.
Referenced by masternode_current().
masternode_help()
void masternode_help ()
Definition at line 326 of file masternode.cpp.
Referenced by masternode().
masternode_list()
UniValue masternode_list (const JSONRPCRequest & request)
Definition at line 63 of file masternode.cpp.
References JSONRPCRequest::fHelp, masternode_list_help(), masternodelist(), JSONRPCRequest::params, UniValue::push_back(), UniValue::setArray(), and UniValue::size().
Referenced by masternode().
masternode_list_help()
void masternode_list_help ()
Definition at line 35 of file masternode.cpp.
Referenced by masternode_list(), and masternodelist().
masternode_status()
UniValue masternode_status (const JSONRPCRequest & request)
Definition at line 252 of file masternode.cpp.
References activeMasternodeInfo, activeMasternodeManager, deterministicMNManager, JSONRPCRequest::fHelp, fMasternodeMode, CActiveMasternodeManager::GetStateString(), CActiveMasternodeManager::GetStatus(), JSONRPCError(), masternode_status_help(), CActiveMasternodeInfo::outpoint, Pair(), CActiveMasternodeInfo::proTxHash, UniValue::push_back(), RPC_INTERNAL_ERROR, CActiveMasternodeInfo::service, CService::ToString(), COutPoint::ToStringShort(), and UniValue::VOBJ.
Referenced by masternode().
masternode_status_help()
void masternode_status_help ()
Definition at line 244 of file masternode.cpp.
Referenced by masternode_status().
masternode_winner()
UniValue masternode_winner (const JSONRPCRequest & request)
Definition at line 186 of file masternode.cpp.
References JSONRPCRequest::fHelp, GetNextMasternodeForPayment(), and masternode_winner_help().
Referenced by masternode().
masternode_winner_help()
void masternode_winner_help ()
Definition at line 178 of file masternode.cpp.
Referenced by masternode_winner().
masternode_winners()
UniValue masternode_winners (const JSONRPCRequest & request)
Definition at line 292 of file masternode.cpp.
References atoi(), chainActive, cs_main, JSONRPCRequest::fHelp, UniValue::get_str(), GetRequiredPaymentsStrings(), UniValue::isNull(), LOCK, masternode_winners_help(), CBlockIndex::nHeight, NullUniValue, Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), strprintf, CChain::Tip(), and UniValue::VOBJ.
Referenced by masternode().
masternode_winners_help()
void masternode_winners_help ()
Definition at line 281 of file masternode.cpp.
Referenced by masternode_winners().
masternodelist()
UniValue masternodelist (const JSONRPCRequest & request)
Definition at line 380 of file masternode.cpp.
References chainActive, cs_main, deterministicMNManager, EncodeDestination(), ExtractDestination(), JSONRPCRequest::fHelp, UniValue::get_str(), GetUTXOCoin(), UniValue::isNull(), LOCK, masternode_list_help(), CBlockIndex::nTime, Coin::out, Pair(), JSONRPCRequest::params, UniValue::push_back(), CTxOut::scriptPubKey, and UniValue::VOBJ.
Referenced by masternode_list().
RegisterMasternodeRPCCommands()
void RegisterMasternodeRPCCommands (CRPCTable & t)
Register masternode RPC commands.
Definition at line 531 of file masternode.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "dash",               "masternode",             &masternode,             {} },
    { "dash",               "masternodelist",         &masternodelist,         {} },
}
Definition at line 524 of file masternode.cpp.
Referenced by RegisterMasternodeRPCCommands().
Released under the MIT license