Dash Core: src/consensus/merkle.h File Reference
merkle.h File Reference
#include <stdint.h>
#include <vector>
#include "primitives/transaction.h"
#include "primitives/block.h"
#include "uint256.h"
Functions
uint256 ComputeMerkleRoot (const std::vector< uint256 > &leaves, bool *mutated=NULL)
std::vector< uint256 > ComputeMerkleBranch (const std::vector< uint256 > &leaves, uint32_t position)
uint256 ComputeMerkleRootFromBranch (const uint256 &leaf, const std::vector< uint256 > &branch, uint32_t position)
uint256 BlockMerkleRoot (const CBlock &block, bool *mutated=NULL)
std::vector< uint256 > BlockMerkleBranch (const CBlock &block, uint32_t position)
Function Documentation
BlockMerkleBranch()
std::vector<uint256> BlockMerkleBranch (const CBlock & block, uint32_t position)
Definition at line 164 of file merkle.cpp.
BlockMerkleRoot()
uint256 BlockMerkleRoot (const CBlock & block, bool * mutated = NULL)
Definition at line 154 of file merkle.cpp.
Referenced by CheckBlock(), CreateGenesisBlock(), and IncrementExtraNonce().
ComputeMerkleBranch()
std::vector<uint256> ComputeMerkleBranch (const std::vector< uint256 > & leaves, uint32_t position)
Definition at line 135 of file merkle.cpp.
Referenced by BlockMerkleBranch().
ComputeMerkleRoot()
uint256 ComputeMerkleRoot (const std::vector< uint256 > & leaves, bool * mutated = NULL)
Definition at line 129 of file merkle.cpp.
Referenced by BlockMerkleRoot().
ComputeMerkleRootFromBranch()
uint256 ComputeMerkleRootFromBranch (const uint256 & leaf, const std::vector< uint256 > & branch, uint32_t position)
Definition at line 141 of file merkle.cpp.