Dash Core: src/miner.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
miner.h File Reference
#include "primitives/block.h"
#include <stdint.h>
Classes
struct CBlockTemplate
Namespaces
Consensus
Functions
void GenerateBitcoins (bool fGenerate, int nThreads, const CChainParams &chainparams, CConnman &connman)
Run the miner threads.
CBlockTemplate * CreateNewBlock (const CChainParams &chainparams, const CScript &scriptPubKeyIn)
Generate a new block, without valid proof-of-work.
void IncrementExtraNonce (CBlock *pblock, const CBlockIndex *pindexPrev, unsigned int &nExtraNonce)
Modify the extranonce in a block.
int64_t UpdateTime (CBlockHeader *pblock, const Consensus::Params &consensusParams, const CBlockIndex *pindexPrev)
Variables
static const bool DEFAULT_GENERATE = false
static const int DEFAULT_GENERATE_THREADS = 1
static const bool DEFAULT_PRINTPRIORITY = false
Function Documentation
CreateNewBlock()
CBlockTemplate* CreateNewBlock (const CChainParams & chainparams, const CScript & scriptPubKeyIn)
Generate a new block, without valid proof-of-work.
Definition at line 77 of file miner.cpp.
References AllowFree(), CTxMemPool::ApplyDeltas(), chainActive, ComputeBlockVersion(), CTxMemPool::cs, cs_main, DEFAULT_BLOCK_MAX_SIZE, DEFAULT_BLOCK_MIN_SIZE, DEFAULT_BLOCK_PRIORITY_SIZE, DEFAULT_PRINTPRIORITY, fDIP0001ActiveAtTip, FillBlockPayments(), FormatStateMessage(), GetAdjustedTime(), GetArg(), CBlockIndex::GetBlockHash(), GetBlockSubsidy(), CBlockHeader::GetBlockTime(), GetBoolArg(), CChainParams::GetConsensus(), CFeeRate::GetFee(), CTransaction::GetHash(), GetLegacySigOpCount(), CBlockIndex::GetMedianTimePast(), CTxMemPool::GetMemPoolChildren(), CTxMemPool::GetMemPoolParents(), GetNextWorkRequired(), CBlockHeader::hashPrevBlock, IsFinalTx(), LOCK, LOCKTIME_MEDIAN_TIME_PAST, LogPrintf, CTxMemPool::mapTx, MaxBlockSigOps(), MaxBlockSize(), mempool, CChainParams::MineBlocksOnDemand(), minRelayTxFee, CBlockHeader::nBits, CBlockIndex::nBits, CBlockIndex::nHeight, nLastBlockSize, nLastBlockTx, CBlockHeader::nNonce, CBlockHeader::nTime, CBlockHeader::nVersion, OP_0, Params(), STANDARD_LOCKTIME_VERIFY_FLAGS, strprintf, TestBlockValidity(), CChain::Tip(), base_blob< BITS >::ToString(), CBlock::txoutMasternode, UpdateTime(), CMutableTransaction::vin, CMutableTransaction::vout, CBlock::voutSuperblock, and CBlock::vtx.
Referenced by BitcoinMiner(), generate(), and getblocktemplate().
GenerateBitcoins()
void GenerateBitcoins (bool fGenerate, int nThreads, const CChainParams & chainparams, CConnman & connman)
Run the miner threads.
Definition at line 524 of file miner.cpp.
References BitcoinMiner(), and GetNumCores().
Referenced by AppInit2(), PrepareShutdown(), and setgenerate().
IncrementExtraNonce()
void IncrementExtraNonce (CBlock * pblock, const CBlockIndex * pindexPrev, unsigned int & nExtraNonce)
Modify the extranonce in a block.
Definition at line 322 of file miner.cpp.
References BlockMerkleRoot(), COINBASE_FLAGS, CBlockHeader::hashMerkleRoot, CBlockHeader::hashPrevBlock, CBlockIndex::nHeight, CMutableTransaction::vin, and CBlock::vtx.
Referenced by BitcoinMiner(), and generate().
UpdateTime()
int64_t UpdateTime (CBlockHeader * pblock, const Consensus::Params & consensusParams, const CBlockIndex * pindexPrev)
Definition at line 62 of file miner.cpp.
References Consensus::Params::fPowAllowMinDifficultyBlocks, GetAdjustedTime(), CBlockIndex::GetMedianTimePast(), GetNextWorkRequired(), CBlockHeader::nBits, and CBlockHeader::nTime.
Referenced by BitcoinMiner(), CreateNewBlock(), and getblocktemplate().
Variable Documentation
DEFAULT_GENERATE
const bool DEFAULT_GENERATE = false static
Definition at line 21 of file miner.h.
Referenced by AppInit2(), getgenerate(), and HelpMessage().
DEFAULT_GENERATE_THREADS
const int DEFAULT_GENERATE_THREADS = 1 static
Definition at line 22 of file miner.h.
Referenced by AppInit2(), getmininginfo(), HelpMessage(), and setgenerate().
DEFAULT_PRINTPRIORITY
const bool DEFAULT_PRINTPRIORITY = false static
Definition at line 24 of file miner.h.
Referenced by CreateNewBlock(), and HelpMessage().
Released under the MIT license