Dash Core: src/miner.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
miner.cpp File Reference
#include "miner.h"
#include "amount.h"
#include "chain.h"
#include "chainparams.h"
#include "coins.h"
#include "consensus/consensus.h"
#include "consensus/merkle.h"
#include "consensus/validation.h"
#include "hash.h"
#include "validation.h"
#include "net.h"
#include "policy/policy.h"
#include "pow.h"
#include "primitives/transaction.h"
#include "script/standard.h"
#include "timedata.h"
#include "txmempool.h"
#include "util.h"
#include "utilmoneystr.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "validationinterface.h"
#include <boost/thread.hpp>
#include <boost/tuple/tuple.hpp>
#include <queue>
Classes
class ScoreCompare
Functions
int64_t UpdateTime (CBlockHeader *pblock, const Consensus::Params &consensusParams, const CBlockIndex *pindexPrev)
CBlockTemplate * CreateNewBlock (const CChainParams &chainparams, const CScript &scriptPubKeyIn)
Generate a new block, without valid proof-of-work.
void IncrementExtraNonce (CBlock *pblock, const CBlockIndex *pindexPrev, unsigned int &nExtraNonce)
Modify the extranonce in a block.
static bool ProcessBlockFound (const CBlock *pblock, const CChainParams &chainparams)
static void BitcoinMiner (const CChainParams &chainparams, CConnman &connman)
void GenerateBitcoins (bool fGenerate, int nThreads, const CChainParams &chainparams, CConnman &connman)
Run the miner threads.
Variables
uint64_t nLastBlockTx = 0
uint64_t nLastBlockSize = 0
Function Documentation
BitcoinMiner()
static void BitcoinMiner (const CChainParams & chainparams, CConnman & connman) static
Definition at line 403 of file miner.cpp.
References chainActive, CConnman::CONNECTIONS_ALL, CreateNewBlock(), Consensus::Params::fPowAllowMinDifficultyBlocks, CChainParams::GetConsensus(), CBlockHeader::GetHash(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), GetMainSignals(), CConnman::GetNodeCount(), GetSerializeSize(), GetTime(), CTxMemPool::GetTransactionsUpdated(), IncrementExtraNonce(), IsInitialBlockDownload(), CMasternodeSync::IsSynced(), LogPrintf, masternodeSync, mempool, MilliSleep(), CChainParams::MineBlocksOnDemand(), CChainParams::MiningRequiresPeers(), CBlockHeader::nBits, CBlockHeader::nNonce, ProcessBlockFound(), PROTOCOL_VERSION, RenameThread(), CMainSignals::ScriptForMining, SER_NETWORK, arith_uint256::SetCompact(), SetThreadPriority(), THREAD_PRIORITY_LOWEST, THREAD_PRIORITY_NORMAL, CChain::Tip(), UintToArith256(), UpdateTime(), and CBlock::vtx.
Referenced by GenerateBitcoins().
CreateNewBlock()
CBlockTemplate* CreateNewBlock (const CChainParams & chainparams, const CScript & scriptPubKeyIn)
Generate a new block, without valid proof-of-work.
Definition at line 77 of file miner.cpp.
References AllowFree(), CTxMemPool::ApplyDeltas(), chainActive, ComputeBlockVersion(), CTxMemPool::cs, cs_main, DEFAULT_BLOCK_MAX_SIZE, DEFAULT_BLOCK_MIN_SIZE, DEFAULT_BLOCK_PRIORITY_SIZE, DEFAULT_PRINTPRIORITY, fDIP0001ActiveAtTip, FillBlockPayments(), FormatStateMessage(), GetAdjustedTime(), GetArg(), CBlockIndex::GetBlockHash(), GetBlockSubsidy(), CBlockHeader::GetBlockTime(), GetBoolArg(), CChainParams::GetConsensus(), CFeeRate::GetFee(), CTransaction::GetHash(), GetLegacySigOpCount(), CBlockIndex::GetMedianTimePast(), CTxMemPool::GetMemPoolChildren(), CTxMemPool::GetMemPoolParents(), GetNextWorkRequired(), CBlockHeader::hashPrevBlock, IsFinalTx(), LOCK, LOCKTIME_MEDIAN_TIME_PAST, LogPrintf, CTxMemPool::mapTx, MaxBlockSigOps(), MaxBlockSize(), mempool, CChainParams::MineBlocksOnDemand(), minRelayTxFee, CBlockHeader::nBits, CBlockIndex::nBits, CBlockIndex::nHeight, nLastBlockSize, nLastBlockTx, CBlockHeader::nNonce, CBlockHeader::nTime, CBlockHeader::nVersion, OP_0, Params(), STANDARD_LOCKTIME_VERIFY_FLAGS, strprintf, TestBlockValidity(), CChain::Tip(), base_blob< BITS >::ToString(), CBlock::txoutMasternode, UpdateTime(), CMutableTransaction::vin, CMutableTransaction::vout, CBlock::voutSuperblock, and CBlock::vtx.
Referenced by BitcoinMiner(), generate(), and getblocktemplate().
GenerateBitcoins()
void GenerateBitcoins (bool fGenerate, int nThreads, const CChainParams & chainparams, CConnman & connman)
Run the miner threads.
Definition at line 524 of file miner.cpp.
References BitcoinMiner(), and GetNumCores().
Referenced by AppInit2(), PrepareShutdown(), and setgenerate().
IncrementExtraNonce()
void IncrementExtraNonce (CBlock * pblock, const CBlockIndex * pindexPrev, unsigned int & nExtraNonce)
Modify the extranonce in a block.
Definition at line 322 of file miner.cpp.
References BlockMerkleRoot(), COINBASE_FLAGS, CBlockHeader::hashMerkleRoot, CBlockHeader::hashPrevBlock, CBlockIndex::nHeight, CMutableTransaction::vin, and CBlock::vtx.
Referenced by BitcoinMiner(), and generate().
ProcessBlockFound()
static bool ProcessBlockFound (const CBlock * pblock, const CChainParams & chainparams) static
Definition at line 380 of file miner.cpp.
References CMainSignals::BlockFound, chainActive, cs_main, error(), FormatMoney(), CBlockIndex::GetBlockHash(), CBlockHeader::GetHash(), GetMainSignals(), CBlockHeader::hashPrevBlock, LOCK, LogPrintf, ProcessNewBlock(), CChain::Tip(), CBlock::ToString(), and CBlock::vtx.
Referenced by BitcoinMiner().
UpdateTime()
int64_t UpdateTime (CBlockHeader * pblock, const Consensus::Params & consensusParams, const CBlockIndex * pindexPrev)
Definition at line 62 of file miner.cpp.
References Consensus::Params::fPowAllowMinDifficultyBlocks, GetAdjustedTime(), CBlockIndex::GetMedianTimePast(), GetNextWorkRequired(), CBlockHeader::nBits, and CBlockHeader::nTime.
Referenced by BitcoinMiner(), CreateNewBlock(), and getblocktemplate().
Variable Documentation
nLastBlockSize
uint64_t nLastBlockSize = 0
Definition at line 49 of file miner.cpp.
Referenced by CreateNewBlock(), and getmininginfo().
nLastBlockTx
uint64_t nLastBlockTx = 0
Definition at line 48 of file miner.cpp.
Referenced by CreateNewBlock(), and getmininginfo().
Released under the MIT license