Dash Core: src/rpc/mining.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
mining.h File Reference
#include <script/script.h>
#include <univalue.h>
Functions
UniValue generateBlocks (std::shared_ptr< CReserveScript > coinbaseScript, int nGenerate, uint64_t nMaxTries, bool keepScript)
Generate blocks (mine)
unsigned int ParseConfirmTarget (const UniValue &value)
Check bounds on a command line confirm target.
Function Documentation
generateBlocks()
UniValue generateBlocks (std::shared_ptr< CReserveScript > coinbaseScript, int nGenerate, uint64_t nMaxTries, bool keepScript)
Generate blocks (mine)
ParseConfirmTarget()
unsigned int ParseConfirmTarget (const UniValue & value)
Check bounds on a command line confirm target.
Definition at line 42 of file mining.cpp.
References feeEstimator, UniValue::get_int(), CBlockPolicyEstimator::HighestTargetTracked(), JSONRPCError(), LONG_HALFLIFE, RPC_INVALID_PARAMETER, and strprintf.
Referenced by estimaterawfee(), estimatesmartfee(), fundrawtransaction(), sendmany(), and sendtoaddress().
Released under the MIT license