Dash Core: dbwrapper_private Namespace Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
dbwrapper_private Namespace Reference
These should be considered an implementation detail of the specific database.
Functions
void HandleError (const leveldb::Status &status)
Handle database error by throwing dbwrapper_error exception.
const std::vector< unsigned char > & GetObfuscateKey (const CDBWrapper &w)
Work around circular dependency, as well as for testing in dbwrapper_tests.
Detailed Description
These should be considered an implementation detail of the specific database.
Function Documentation
GetObfuscateKey()
const std::vector< unsigned char > & dbwrapper_private::GetObfuscateKey (const CDBWrapper & w)
Work around circular dependency, as well as for testing in dbwrapper_tests.
Database obfuscation should be considered an implementation detail of the specific database.
Definition at line 213 of file dbwrapper.cpp.
References CDBWrapper::obfuscate_key.
Referenced by CDBIterator::GetValue(), and CDBBatch::Write().
HandleError()
void dbwrapper_private::HandleError (const leveldb::Status & status)
Handle database error by throwing dbwrapper_error exception.
Definition at line 199 of file dbwrapper.cpp.
References LogPrintf.
Referenced by CDBWrapper::CDBWrapper(), CDBWrapper::Exists(), CDBWrapper::Read(), and CDBWrapper::WriteBatch().
Released under the MIT license