Dash Core: test_framework.bignum Namespace Reference
test_framework.bignum Namespace Reference
Functions
def bn_bytes (v, have_ext=False)
def bn2bin (v)
def bin2bn (s)
def bn2mpi (v)
def mpi2bn (s)
def mpi2vch (s)
def bn2vch (v)
def vch2mpi (s)
def vch2bn (s)
Function Documentation
bin2bn()
def test_framework.bignum.bin2bn (s)
Definition at line 34 of file bignum.py.
Referenced by test_framework.bignum.mpi2bn().
bn2bin()
def test_framework.bignum.bn2bin (v)
Definition at line 26 of file bignum.py.
Referenced by test_framework.bignum.bn2mpi().
bn2mpi()
def test_framework.bignum.bn2mpi (v)
Definition at line 40 of file bignum.py.
Referenced by test_framework.bignum.bn2vch().
bn2vch()
def test_framework.bignum.bn2vch (v)
Definition at line 92 of file bignum.py.
Referenced by test_framework.script.CScript.__coerce_instance().
bn_bytes()
def test_framework.bignum.bn_bytes (v, have_ext = False)
Definition at line 20 of file bignum.py.
Referenced by test_framework.bignum.bn2bin(), and test_framework.bignum.bn2mpi().
mpi2bn()
def test_framework.bignum.mpi2bn (s)
Definition at line 62 of file bignum.py.
Referenced by test_framework.bignum.vch2bn().
mpi2vch()
def test_framework.bignum.mpi2vch (s)
Definition at line 87 of file bignum.py.
Referenced by test_framework.bignum.bn2vch().
vch2bn()
def test_framework.bignum.vch2bn (s)
Definition at line 100 of file bignum.py.
vch2mpi()
def test_framework.bignum.vch2mpi (s)
Definition at line 95 of file bignum.py.
Referenced by test_framework.bignum.vch2bn().