Dash Core: rpcbind_test Namespace Reference
rpcbind_test Namespace Reference
Functions
def run_bind_test (tmpdir, allow_ips, connect_to, addresses, expected)
def run_allowip_test (tmpdir, allow_ips, rpchost, rpcport)
def run_test (tmpdir)
def main ()
Function Documentation
main()
def rpcbind_test.main (void)
Definition at line 100 of file rpcbind_test.py.
run_allowip_test()
def rpcbind_test.run_allowip_test (tmpdir, allow_ips, rpchost, rpcport)
Start a node with rpcwallow IP, and request getinfo
at a non-localhost IP.
Definition at line 35 of file rpcbind_test.py.
Referenced by run_test().
run_bind_test()
def rpcbind_test.run_bind_test (tmpdir, allow_ips, connect_to, addresses, expected)
Start a node with requested rpcallowip and rpcbind parameters,
then try to connect, and check if the set of bound addresses
matches the expected set.
Definition at line 16 of file rpcbind_test.py.
Referenced by run_test().
run_test()
def rpcbind_test.run_test (tmpdir)
Definition at line 53 of file rpcbind_test.py.
Referenced by main().