Dash Core: getblocktemplate_proposals Namespace Reference
getblocktemplate_proposals Namespace Reference
Classes
class GetBlockTemplateProposalTest
Functions
def b2x (b)
def encodeUNum (n)
def varlenEncode (n)
def dblsha (b)
def genmrklroot (leaflist)
def template_to_bytes (tmpl, txlist)
def template_to_hex (tmpl, txlist)
def assert_template (node, tmpl, txlist, expect)
Function Documentation
assert_template()
def getblocktemplate_proposals.assert_template (node, tmpl, txlist, expect)
Definition at line 63 of file getblocktemplate_proposals.py.
Referenced by getblocktemplate_proposals.GetBlockTemplateProposalTest.run_test().
b2x()
def getblocktemplate_proposals.b2x (b)
Definition at line 13 of file getblocktemplate_proposals.py.
Referenced by getblocktemplate_proposals.GetBlockTemplateProposalTest.run_test(), and template_to_hex().
dblsha()
def getblocktemplate_proposals.dblsha (b)
Definition at line 35 of file getblocktemplate_proposals.py.
Referenced by genmrklroot(), and template_to_bytes().
encodeUNum()
def getblocktemplate_proposals.encodeUNum (n)
Definition at line 17 of file getblocktemplate_proposals.py.
Referenced by getblocktemplate_proposals.GetBlockTemplateProposalTest.run_test().
genmrklroot()
def getblocktemplate_proposals.genmrklroot (leaflist)
Definition at line 38 of file getblocktemplate_proposals.py.
Referenced by template_to_bytes().
template_to_bytes()
def getblocktemplate_proposals.template_to_bytes (tmpl, txlist)
Definition at line 49 of file getblocktemplate_proposals.py.
Referenced by getblocktemplate_proposals.GetBlockTemplateProposalTest.run_test(), and template_to_hex().
template_to_hex()
def getblocktemplate_proposals.template_to_hex (tmpl, txlist)
Definition at line 60 of file getblocktemplate_proposals.py.
Referenced by assert_template().
varlenEncode()
def getblocktemplate_proposals.varlenEncode (n)
Definition at line 26 of file getblocktemplate_proposals.py.
Referenced by template_to_bytes().