Dash Core: fsbridge Namespace Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
fsbridge Namespace Reference
Filesystem operations and types.
Functions
FILE * fopen (const fs::path &p, const char *mode)
FILE * freopen (const fs::path &p, const char *mode, FILE *stream)
Detailed Description
Filesystem operations and types.
Bridge operations to C stdio
Function Documentation
fopen()
FILE * fsbridge::fopen (const fs::path & p, const char * mode)
Definition at line 5 of file fs.cpp.
Referenced by AppInitMain(), CreatePidFile(), DumpMempool(), LoadMempool(), LockDirectory(), main(), BerkeleyEnvironment::Open(), OpenDebugLog(), OpenDiskFile(), PrepareShutdown(), CFlatDB< T >::Read(), ReadBinaryFile(), ArgsManager::ReadConfigFile(), RegisterLoad(), runtest_file(), ShrinkDebugFile(), ThreadImport(), CFlatDB< T >::Write(), and WriteBinaryFile().
freopen()
FILE * fsbridge::freopen (const fs::path & p, const char * mode, FILE * stream)
Definition at line 10 of file fs.cpp.
Referenced by LogPrintStr().
Released under the MIT license