Dash Core: payments Namespace Reference
payments Namespace Reference
Classes
class Output
class Payment
class PaymentACK
class PaymentDetails
class PaymentRequest
struct StaticDescriptorInitializer_paymentrequest_2eproto
class X509Certificates
Functions
void protobuf_AssignDesc_paymentrequest_2eproto ()
void protobuf_ShutdownFile_paymentrequest_2eproto ()
void protobuf_AddDesc_paymentrequest_2eproto ()
Variables
struct payments::StaticDescriptorInitializer_paymentrequest_2eproto static_descriptor_initializer_paymentrequest_2eproto_
Function Documentation
protobuf_AddDesc_paymentrequest_2eproto()
void payments::protobuf_AddDesc_paymentrequest_2eproto ()
Definition at line 201 of file paymentrequest.pb.cc.
Referenced by protobuf_AssignDesc_paymentrequest_2eproto(), and payments::StaticDescriptorInitializer_paymentrequest_2eproto::StaticDescriptorInitializer_paymentrequest_2eproto().
protobuf_AssignDesc_paymentrequest_2eproto()
void payments::protobuf_AssignDesc_paymentrequest_2eproto ()
Definition at line 45 of file paymentrequest.pb.cc.
protobuf_ShutdownFile_paymentrequest_2eproto()
void payments::protobuf_ShutdownFile_paymentrequest_2eproto ()
Definition at line 184 of file paymentrequest.pb.cc.
Referenced by protobuf_AddDesc_paymentrequest_2eproto().
Variable Documentation
static_descriptor_initializer_paymentrequest_2eproto_
struct payments::StaticDescriptorInitializer_paymentrequest_2eproto payments::static_descriptor_initializer_paymentrequest_2eproto_