Dash Core: spendfrom Namespace Reference
spendfrom Namespace Reference
Functions
def check_json_precision ()
def determine_db_dir ()
def read_bitcoin_config (dbdir)
def connect_JSON (config)
def unlock_wallet (dashd)
def list_available (dashd)
def select_coins (needed, inputs)
def create_tx (dashd, fromaddresses, toaddress, amount, fee)
def compute_amount_in (dashd, txinfo)
def compute_amount_out (txinfo)
def sanity_test_fee (dashd, txdata_hex, max_fee)
def main ()
Variables
BASE_FEE = Decimal("0.001")
fp
sechead
Function Documentation
check_json_precision()
def spendfrom.check_json_precision ()
Make sure json library being used does not lose precision converting BTC values
Definition at line 28 of file spendfrom.py.
Referenced by test_framework.test_framework.BitcoinTestFramework.main(), rpcbind_test.main(), and main().
compute_amount_in()
def spendfrom.compute_amount_in (dashd, txinfo)
Definition at line 182 of file spendfrom.py.
compute_amount_out()
def spendfrom.compute_amount_out (txinfo)
Definition at line 190 of file spendfrom.py.
connect_JSON()
def spendfrom.connect_JSON (config)
Connect to a Dash Core JSON-RPC server
Definition at line 65 of file spendfrom.py.
Referenced by main().
create_tx()
def spendfrom.create_tx (dashd, fromaddresses, toaddress, amount, fee)
Definition at line 142 of file spendfrom.py.
Referenced by main(), mempool_resurrect_test.MempoolCoinbaseTest.run_test(), mempool_reorg.MempoolCoinbaseTest.run_test(), and mempool_spendcoinbase.MempoolSpendCoinbaseTest.run_test().
determine_db_dir()
def spendfrom.determine_db_dir ()
Return the default location of the Dash Core data directory
Definition at line 35 of file spendfrom.py.
Referenced by main().
list_available()
def spendfrom.list_available (dashd)
Definition at line 99 of file spendfrom.py.
Referenced by create_tx(), and main().
main()
def spendfrom.main (void)
Definition at line 219 of file spendfrom.py.
read_bitcoin_config()
def spendfrom.read_bitcoin_config (dbdir)
Read the dash.conf file from dbdir, returns dictionary of settings
Definition at line 43 of file spendfrom.py.
Referenced by main().
sanity_test_fee()
def spendfrom.sanity_test_fee (dashd, txdata_hex, max_fee)
Definition at line 196 of file spendfrom.py.
Referenced by main().
select_coins()
def spendfrom.select_coins (needed, inputs)
Definition at line 131 of file spendfrom.py.
Referenced by create_tx().
unlock_wallet()
def spendfrom.unlock_wallet (dashd)
Definition at line 84 of file spendfrom.py.
Referenced by main().
Variable Documentation
BASE_FEE
spendfrom.BASE_FEE = Decimal("0.001")
Definition at line 26 of file spendfrom.py.
fp
spendfrom.fp
Definition at line 49 of file spendfrom.py.
Referenced by FileWriteStr(), and main().
sechead
spendfrom.sechead
Definition at line 50 of file spendfrom.py.