Dash Core: base58 Namespace Reference
base58 Namespace Reference
Classes
class SHA256
Functions
def ord (c)
def chr (n)
def b58encode (v)
def b58decode (v, length=None)
def checksum (v)
def b58encode_chk (v)
def b58decode_chk (v)
def get_bcaddress_version (strAddress)
Variables
string __b58chars = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
__b58base = len(__b58chars)
string b58chars = __b58chars
string _ohai = 'o hai'.encode('ascii')
def _tmp = b58encode(_ohai)
Detailed Description
Bitcoin base58 encoding and decoding.
Based on https://bitcointalk.org/index.php?topic=1026.0 (public domain)
Function Documentation
b58decode()
def base58.b58decode (v, length = None)
decode v into a string of len bytes
Definition at line 46 of file base58.py.
Referenced by b58decode_chk().
b58decode_chk()
def base58.b58decode_chk (v)
decode a base58 string, check and remove checksum
Definition at line 79 of file base58.py.
Referenced by get_bcaddress_version(), and gen_base58_test_vectors.is_valid().
b58encode()
def base58.b58encode (v)
encode v, which is a string of bytes, to base58.
Definition at line 23 of file base58.py.
Referenced by b58encode_chk().
b58encode_chk()
def base58.b58encode_chk (v)
b58encode a string, with 32-bit checksum
Definition at line 75 of file base58.py.
Referenced by gen_base58_test_vectors.gen_invalid_vector(), and gen_base58_test_vectors.gen_valid_vectors().
checksum()
def base58.checksum (v)
Return 32-bit checksum based on SHA256
Definition at line 71 of file base58.py.
Referenced by b58decode_chk(), b58encode_chk(), and CMnemonic.FromData().
chr()
def base58.chr (n)
Definition at line 16 of file base58.py.
Referenced by b58decode().
get_bcaddress_version()
def base58.get_bcaddress_version (strAddress)
Returns None if strAddress is invalid.  Otherwise returns integer version of address.
Definition at line 90 of file base58.py.
ord()
def base58.ord (c)
Definition at line 14 of file base58.py.
Referenced by b58encode(), and get_bcaddress_version().
Variable Documentation
__b58base
base58.__b58base = len(__b58chars) private
Definition at line 20 of file base58.py.
__b58chars
string base58.__b58chars = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz' private
Definition at line 19 of file base58.py.
_ohai
string base58._ohai = 'o hai'.encode('ascii') private
Definition at line 100 of file base58.py.
_tmp
def base58._tmp = b58encode(_ohai) private
Definition at line 101 of file base58.py.
b58chars
string base58.b58chars = __b58chars
Definition at line 21 of file base58.py.