Dash Core: rest Namespace Reference
rest Namespace Reference
Classes
class RESTTest
Functions
def deser_uint256 (f)
def http_get_call (host, port, path, response_object=0)
def http_post_call (host, port, path, requestdata='', response_object=0)
Function Documentation
deser_uint256()
def rest.deser_uint256 (f)
Definition at line 27 of file rest.py.
Referenced by rest.RESTTest.run_test().
http_get_call()
def rest.http_get_call (host, port, path, response_object = 0)
Definition at line 35 of file rest.py.
Referenced by rest.RESTTest.run_test().
http_post_call()
def rest.http_post_call (host, port, path, requestdata = '', response_object = 0)
Definition at line 45 of file rest.py.
Referenced by rest.RESTTest.run_test().