Dash Core: rpc-tests Namespace Reference
rpc-tests Namespace Reference
Classes
class RPCCoverage
Functions
def runtests ()
Variables
int ENABLE_WALLET = 0
int ENABLE_BITCOIND = 0
int ENABLE_UTILS = 0
int ENABLE_ZMQ = 0
int ENABLE_COVERAGE = 0
opts = set()
string passOn = ""
p = re.compile("^--")
tuple bold = ("","")
buildDir = BUILDDIR
list testScripts
list testScriptsExt
Function Documentation
runtests()
def rpc-tests.runtests ()
Definition at line 158 of file rpc-tests.py.
Referenced by rpc-tests.RPCCoverage._get_uncovered_rpc_commands().
Variable Documentation
bold
tuple rpc-tests.bold = ("","")
Definition at line 51 of file rpc-tests.py.
Referenced by HelpMessageDialog.HelpMessageDialog().
buildDir
rpc-tests.buildDir = BUILDDIR
Definition at line 64 of file rpc-tests.py.
ENABLE_BITCOIND
int rpc-tests.ENABLE_BITCOIND = 0
Definition at line 38 of file rpc-tests.py.
ENABLE_COVERAGE
int rpc-tests.ENABLE_COVERAGE = 0
Definition at line 44 of file rpc-tests.py.
ENABLE_UTILS
int rpc-tests.ENABLE_UTILS = 0
Definition at line 40 of file rpc-tests.py.
ENABLE_WALLET
int rpc-tests.ENABLE_WALLET = 0
Definition at line 36 of file rpc-tests.py.
ENABLE_ZMQ
int rpc-tests.ENABLE_ZMQ = 0
Definition at line 42 of file rpc-tests.py.
opts
rpc-tests.opts = set()
Definition at line 47 of file rpc-tests.py.
p
rpc-tests.p = re.compile("^--")
Definition at line 49 of file rpc-tests.py.
Referenced by secure_allocator< T >.allocate(), GUIUtil.checkPoint(), CMasternodePayments.CheckPreviousBlockVotes(), counting_illegal_callback_fn(), zero_after_free_allocator< T >.deallocate(), secure_allocator< T >.deallocate(), DecodeBase32(), DecodeBase64(), prevector< N, T, Size, Diff >.erase(), prevector< N, T, Size, Diff >.insert(), LockedPageManagerBase< MemoryPageLocker >.LockRange(), payments::Output.MergePartialFromCodedStream(), payments::PaymentDetails.MergePartialFromCodedStream(), payments::PaymentRequest.MergePartialFromCodedStream(), payments::X509Certificates.MergePartialFromCodedStream(), payments::Payment.MergePartialFromCodedStream(), payments::PaymentACK.MergePartialFromCodedStream(), ParseMoney(), run_point_times_order(), secp256k1_ec_pubkey_create(), secp256k1_ec_pubkey_tweak_add(), secp256k1_ec_pubkey_tweak_mul(), CPartialMerkleTree.SerializationOp(), signrawtransaction(), CConnman.ThreadMnbRequestConnections(), CPartialMerkleTree.TraverseAndBuild(), TryCreateDirectory(), uncounting_illegal_callback_fn(), LockedPageManagerBase< MemoryPageLocker >.UnlockRange(), CCoins.Unserialize(), and ReceiveRequestDialog.update().
passOn
string rpc-tests.passOn = ""
Definition at line 48 of file rpc-tests.py.
testScripts
list rpc-tests.testScripts
Definition at line 90 of file rpc-tests.py.
testScriptsExt
list rpc-tests.testScriptsExt
Initial value:
 =  [
     'bip9-softforks.py',
     'bip65-cltv.py',
     'bip65-cltv-p2p.py', # NOTE: needs dash_hash to pass
     'bip68-sequence.py',
     'bipdersig-p2p.py', # NOTE: needs dash_hash to pass
     'bipdersig.py',
     'getblocktemplate_longpoll.py', # FIXME: "socket.error: [Errno 54] Connection reset by peer" on my Mac, same as  https://github.com/bitcoin/bitcoin/issues/6651
     'getblocktemplate_proposals.py',
     'txn_doublespend.py',
     'txn_clone.py --mineblock',
     # 'pruning.py', # Prune mode is incompatible with -txindex.
     'forknotify.py',
     'invalidateblock.py',
 #    'rpcbind_test.py', #temporary, bug in libevent, see #6655
     'smartfees.py',
     'maxblocksinflight.py',
     'p2p-acceptblock.py', # NOTE: needs dash_hash to pass
     'mempool_packages.py',
     'maxuploadtarget.py',
     # 'replace-by-fee.py', # RBF is disabled in Dash Core
 ]
Definition at line 135 of file rpc-tests.py.