Dash Core: generate-seeds Namespace Reference
generate-seeds Namespace Reference
Functions
def name_to_ipv6 (addr)
def parse_spec (s, defaultport)
def process_nodes (g, f, structname, defaultport)
def main ()
Variables
pchIPv4 = bytearray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff, 0xff])
pchOnionCat = bytearray([0xFD,0x87,0xD8,0x7E,0xEB,0x43])
Function Documentation
main()
def generate-seeds.main (void)
Definition at line 114 of file generate-seeds.py.
name_to_ipv6()
def generate-seeds.name_to_ipv6 (addr)
Definition at line 45 of file generate-seeds.py.
Referenced by parse_spec().
parse_spec()
def generate-seeds.parse_spec (s, defaultport)
Definition at line 75 of file generate-seeds.py.
Referenced by process_nodes().
process_nodes()
def generate-seeds.process_nodes (g, f, structname, defaultport)
Definition at line 95 of file generate-seeds.py.
Referenced by main().
Variable Documentation
pchIPv4
generate-seeds.pchIPv4 = bytearray([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff, 0xff])
Definition at line 41 of file generate-seeds.py.
pchOnionCat
generate-seeds.pchOnionCat = bytearray([0xFD,0x87,0xD8,0x7E,0xEB,0x43])
Definition at line 43 of file generate-seeds.py.