Dash Core: memusage Namespace Reference
memusage Namespace Reference
Classes
struct boost_unordered_node
struct stl_tree_node
Functions
static size_t MallocUsage (size_t alloc)
static size_t DynamicUsage (const int8_t &v)
static size_t DynamicUsage (const uint8_t &v)
static size_t DynamicUsage (const int16_t &v)
static size_t DynamicUsage (const uint16_t &v)
static size_t DynamicUsage (const int32_t &v)
static size_t DynamicUsage (const uint32_t &v)
static size_t DynamicUsage (const int64_t &v)
static size_t DynamicUsage (const uint64_t &v)
static size_t DynamicUsage (const float &v)
static size_t DynamicUsage (const double &v)
template<typename X >
static size_t DynamicUsage (X *const &v)
template<typename X >
static size_t DynamicUsage (const X *const &v)
template<typename X >
static size_t DynamicUsage (const std::vector< X > &v)
template<unsigned int N, typename X , typename S , typename D >
static size_t DynamicUsage (const prevector< N, X, S, D > &v)
template<typename X , typename Y >
static size_t DynamicUsage (const std::set< X, Y > &s)
template<typename X , typename Y >
static size_t IncrementalDynamicUsage (const std::set< X, Y > &s)
template<typename X , typename Y , typename Z >
static size_t DynamicUsage (const std::map< X, Y, Z > &m)
template<typename X , typename Y , typename Z >
static size_t IncrementalDynamicUsage (const std::map< X, Y, Z > &m)
template<typename X , typename Y >
static size_t DynamicUsage (const boost::unordered_set< X, Y > &s)
template<typename X , typename Y , typename Z >
static size_t DynamicUsage (const boost::unordered_map< X, Y, Z > &m)
Function Documentation
DynamicUsage() [1/18]
static size_t memusage::DynamicUsage (const int8_t & v) inline static
Dynamic memory usage for built-in types is zero.
Definition at line 25 of file memusage.h.
Referenced by CTxMemPool::check(), CCoins::DynamicMemoryUsage(), CCoinsViewCache::DynamicMemoryUsage(), CTxMemPool::DynamicMemoryUsage(), RecursiveDynamicUsage(), and CTxMemPool::removeUnchecked().
DynamicUsage() [2/18]
static size_t memusage::DynamicUsage (const uint8_t & v) inline static
Definition at line 26 of file memusage.h.
DynamicUsage() [3/18]
static size_t memusage::DynamicUsage (const int16_t & v) inline static
Definition at line 27 of file memusage.h.
DynamicUsage() [4/18]
static size_t memusage::DynamicUsage (const uint16_t & v) inline static
Definition at line 28 of file memusage.h.
DynamicUsage() [5/18]
static size_t memusage::DynamicUsage (const int32_t & v) inline static
Definition at line 29 of file memusage.h.
DynamicUsage() [6/18]
static size_t memusage::DynamicUsage (const uint32_t & v) inline static
Definition at line 30 of file memusage.h.
DynamicUsage() [7/18]
static size_t memusage::DynamicUsage (const int64_t & v) inline static
Definition at line 31 of file memusage.h.
DynamicUsage() [8/18]
static size_t memusage::DynamicUsage (const uint64_t & v) inline static
Definition at line 32 of file memusage.h.
DynamicUsage() [9/18]
static size_t memusage::DynamicUsage (const float & v) inline static
Definition at line 33 of file memusage.h.
DynamicUsage() [10/18]
static size_t memusage::DynamicUsage (const double & v) inline static
Definition at line 34 of file memusage.h.
DynamicUsage() [11/18]
template<typename X > static size_t memusage::DynamicUsage (X *const & v) inline static
Definition at line 35 of file memusage.h.
DynamicUsage() [12/18]
template<typename X > static size_t memusage::DynamicUsage (const X *const & v) inline static
Definition at line 36 of file memusage.h.
DynamicUsage() [13/18]
template<typename X > static size_t memusage::DynamicUsage (const std::vector< X > & v) inline static
Definition at line 74 of file memusage.h.
DynamicUsage() [14/18]
template<unsigned int N, typename X , typename S , typename D > static size_t memusage::DynamicUsage (const prevector< N, X, S, D > & v) inline static
Definition at line 80 of file memusage.h.
DynamicUsage() [15/18]
template<typename X , typename Y > static size_t memusage::DynamicUsage (const std::set< X, Y > & s) inline static
Definition at line 86 of file memusage.h.
DynamicUsage() [16/18]
template<typename X , typename Y , typename Z > static size_t memusage::DynamicUsage (const std::map< X, Y, Z > & m) inline static
Definition at line 98 of file memusage.h.
DynamicUsage() [17/18]
template<typename X , typename Y > static size_t memusage::DynamicUsage (const boost::unordered_set< X, Y > & s) inline static
Definition at line 119 of file memusage.h.
DynamicUsage() [18/18]
template<typename X , typename Y , typename Z > static size_t memusage::DynamicUsage (const boost::unordered_map< X, Y, Z > & m) inline static
Definition at line 125 of file memusage.h.
IncrementalDynamicUsage() [1/2]
template<typename X , typename Y > static size_t memusage::IncrementalDynamicUsage (const std::set< X, Y > & s) inline static
Definition at line 92 of file memusage.h.
Referenced by CTxMemPool::UpdateChild(), and CTxMemPool::UpdateParent().
IncrementalDynamicUsage() [2/2]
template<typename X , typename Y , typename Z > static size_t memusage::IncrementalDynamicUsage (const std::map< X, Y, Z > & m) inline static
Definition at line 104 of file memusage.h.
MallocUsage()
static size_t memusage::MallocUsage (size_t alloc) inline static
Compute the total memory used by allocating alloc bytes.
Compute the memory used for dynamically allocated but owned data structures. For generic data types, this is not recursive. DynamicUsage(vector<vector<int> >) will compute the memory used for the vector<int>'s, but not for the ints inside. This is for efficiency reasons, as these functions are intended to be fast. If application data structures require more accurate inner accounting, they should iterate themselves, or use more efficient caching + updating on modification.
Definition at line 46 of file memusage.h.
Referenced by CTxMemPool::DynamicMemoryUsage(), DynamicUsage(), and IncrementalDynamicUsage().