Dash Core: makeseeds Namespace Reference
makeseeds Namespace Reference
Functions
def parseline (line)
def filtermultiport (ips)
def filterbyasn (ips, max_per_asn, max_total)
def main ()
Variables
int NSEEDS = 512
int MAX_SEEDS_PER_ASN = 2
int MIN_BLOCKS = 400000
SUSPICIOUS_HOSTS
PATTERN_IPV4 = re.compile(r"^((\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})):(\d+)$")
PATTERN_IPV6 = re.compile(r"^\[([0-9a-z:]+)\]:(\d+)$")
PATTERN_ONION = re.compile(r"^([abcdefghijklmnopqrstuvwxyz234567]{16}\.onion):(\d+)$")
PATTERN_AGENT = re.compile(r"^(\/Satoshi:0\.8\.6\/|\/Satoshi:0\.9\.(2|3|4|5)\/|\/Core:0.1(0|1|2).\d{1,2}.\d{1,2}\/)$")
Function Documentation
filterbyasn()
def makeseeds.filterbyasn (ips, max_per_asn, max_total)
Definition at line 107 of file makeseeds.py.
Referenced by main().
filtermultiport()
def makeseeds.filtermultiport (ips)
Filter out hosts with more nodes per IP
Definition at line 99 of file makeseeds.py.
Referenced by main().
main()
def makeseeds.main (void)
Definition at line 137 of file makeseeds.py.
parseline()
def makeseeds.parseline (line)
Definition at line 32 of file makeseeds.py.
Referenced by main().
Variable Documentation
MAX_SEEDS_PER_ASN
int makeseeds.MAX_SEEDS_PER_ASN = 2
Definition at line 8 of file makeseeds.py.
MIN_BLOCKS
int makeseeds.MIN_BLOCKS = 400000
Definition at line 10 of file makeseeds.py.
NSEEDS
int makeseeds.NSEEDS = 512
Definition at line 6 of file makeseeds.py.
PATTERN_AGENT
makeseeds.PATTERN_AGENT = re.compile(r"^(\/Satoshi:0\.8\.6\/|\/Satoshi:0\.9\.(2|3|4|5)\/|\/Core:0.1(0|1|2).\d{1,2}.\d{1,2}\/)$")
Definition at line 30 of file makeseeds.py.
PATTERN_IPV4
makeseeds.PATTERN_IPV4 = re.compile(r"^((\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})):(\d+)$")
Definition at line 27 of file makeseeds.py.
PATTERN_IPV6
makeseeds.PATTERN_IPV6 = re.compile(r"^\[([0-9a-z:]+)\]:(\d+)$")
Definition at line 28 of file makeseeds.py.
PATTERN_ONION
makeseeds.PATTERN_ONION = re.compile(r"^([abcdefghijklmnopqrstuvwxyz234567]{16}\.onion):(\d+)$")
Definition at line 29 of file makeseeds.py.
SUSPICIOUS_HOSTS
makeseeds.SUSPICIOUS_HOSTS
Initial value:
 =  set([
     "130.211.129.106", "178.63.107.226",
     "83.81.130.26", "88.198.17.7", "148.251.238.178", "176.9.46.6",
     "54.173.72.127", "54.174.10.182", "54.183.64.54", "54.194.231.211",
     "54.66.214.167", "54.66.220.137", "54.67.33.14", "54.77.251.214",
     "54.94.195.96", "54.94.200.247"
 ])
Definition at line 14 of file makeseeds.py.