Dash Core: tinyformat Namespace Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
tinyformat Namespace Reference
Namespaces
detail
Classes
class format_error
class FormatList
List of template arguments format(), held in a type-opaque way.
Typedefs
typedef const FormatList & FormatListRef
Reference to type-opaque format list for passing to vformat()
Functions
template<typename T >
void formatValue (std::ostream &out, const char *, const char *fmtEnd, int ntrunc, const T &value)
Format a value into a stream, delegating to operator<< by default.
template<typename... Args>
*detail::FormatListN< sizeof...(Args)> makeFormatList (const Args &... args)
Make type-agnostic format list from list of template arguments.
void vformat (std::ostream &out, const char *fmt, FormatListRef list)
Format list of arguments to the stream according to the given format string.
template<typename... Args>
void format (std::ostream &out, const char *fmt, const Args &... args)
Format list of arguments to the stream according to given format string.
template<typename... Args>
std::string format (const char *fmt, const Args &... args)
Format list of arguments according to the given format string and return the result as a string.
template<typename... Args>
void printf (const char *fmt, const Args &... args)
Format list of arguments to std::cout, according to the given format string.
template<typename... Args>
void printfln (const char *fmt, const Args &... args)
template<typename... Args>
std::string format (const std::string &fmt, const Args &... args)
Typedef Documentation
FormatListRef
typedef const FormatList& tinyformat::FormatListRef
Reference to type-opaque format list for passing to vformat()
Definition at line 870 of file tinyformat.h.
Function Documentation
format() [1/3]
template<typename... Args> void tinyformat::format (std::ostream & out, const char * fmt, const Args &... args)
Format list of arguments to the stream according to given format string.
Definition at line 967 of file tinyformat.h.
References makeFormatList(), and vformat().
Referenced by format(), CBitcoinLevelDBLogger::Logv(), printf(), printfln(), SafeStringFormat(), and TransactionView::updateCalendarWidgets().
format() [2/3]
template<typename... Args> std::string tinyformat::format (const char * fmt, const Args &... args)
Format list of arguments according to the given format string and return the result as a string.
Definition at line 975 of file tinyformat.h.
References format().
format() [3/3]
template<typename... Args> std::string tinyformat::format (const std::string & fmt, const Args &... args)
Definition at line 1057 of file tinyformat.h.
References format().
formatValue()
template<typename T > void tinyformat::formatValue (std::ostream & out, const char * , const char * fmtEnd, int ntrunc, const T & value) inline
Format a value into a stream, delegating to operator<< by default.
Users may override this for their own types. When this function is called, the stream flags will have been modified according to the format string. The format specification is provided in the range [fmtBegin, fmtEnd). For truncating conversions, ntrunc is set to the desired maximum number of characters, for example "%.7s" calls formatValue with ntrunc = 7.
By default, formatValue() uses the usual stream insertion operator operator<< to format the type T, with special cases for the c and p conversions.
Definition at line 315 of file tinyformat.h.
References tinyformat::detail::formatTruncated().
Referenced by tinyformat::detail::FormatArg::formatImpl().
makeFormatList()
template<typename... Args> * detail::FormatListN<sizeof...(Args)> tinyformat::makeFormatList (const Args &... args)
Make type-agnostic format list from list of template arguments.
The exact return type of this function is an implementation detail and shouldn't be relied upon. Instead it should be stored as a FormatListRef:
FormatListRef formatList = makeFormatList(/*...
Definition at line 931 of file tinyformat.h.
Referenced by format().
printf()
template<typename... Args> void tinyformat::printf (const char * fmt, const Args &... args)
Format list of arguments to std::cout, according to the given format string.
Definition at line 984 of file tinyformat.h.
References format().
Referenced by CWallet::EncryptWallet(), main(), outputEscape(), print_number(), and run_benchmark().
printfln()
template<typename... Args> void tinyformat::printfln (const char * fmt, const Args &... args)
Definition at line 990 of file tinyformat.h.
References format().
vformat()
void tinyformat::vformat (std::ostream & out, const char * fmt, FormatListRef list) inline
Format list of arguments to the stream according to the given format string.
The name vformat() is chosen for the semantic similarity to vprintf(): the list of format arguments is held in a single function argument.
Definition at line 957 of file tinyformat.h.
References tinyformat::detail::formatImpl(), tinyformat::FormatList::m_formatters, and tinyformat::FormatList::m_N.
Referenced by format().
Released under the MIT license