Dash Core: Checkpoints Namespace Reference
Checkpoints Namespace Reference
Functions
double GuessVerificationProgress (const CCheckpointData &data, CBlockIndex *pindex, bool fSigchecks)
Guess how far we are in the verification process at the given block index.
CBlockIndex * GetLastCheckpoint (const CCheckpointData &data)
Returns last CBlockIndex* in mapBlockIndex that is a checkpoint.
Variables
static const double SIGCHECK_VERIFICATION_FACTOR = 5.0
Detailed Description
Block-chain checkpoints are compiled-in sanity checks. They are updated every release or three.
Function Documentation
GetLastCheckpoint()
CBlockIndex * Checkpoints::GetLastCheckpoint (const CCheckpointData & data)
Returns last CBlockIndex* in mapBlockIndex that is a checkpoint.
Definition at line 59 of file checkpoints.cpp.
Referenced by CheckIndexAgainstCheckpoint().
GuessVerificationProgress()
double Checkpoints::GuessVerificationProgress (const CCheckpointData & data, CBlockIndex * pindex, bool fSigchecks)
Guess how far we are in the verification process at the given block index.
Definition at line 30 of file checkpoints.cpp.
Referenced by getblockchaininfo(), ClientModel::getVerificationProgress(), LoadBlockIndexDB(), CWallet::ScanForWalletTransactions(), and UpdateTip().
Variable Documentation
SIGCHECK_VERIFICATION_FACTOR
const double Checkpoints::SIGCHECK_VERIFICATION_FACTOR = 5.0 static
How many times slower we expect checking transactions after the last checkpoint to be (from checking signatures, which is skipped up to the last checkpoint). This number is a compromise, as it can't be accurate for every system. When reindexing from a fast disk with a slow CPU, it can be up to 20, while when downloading from a slow network with a fast multicore CPU, it won't be much higher than 1.
Definition at line 27 of file checkpoints.cpp.
Referenced by GuessVerificationProgress().