Dash Core: smartfees Namespace Reference
smartfees Namespace Reference
Classes
class DecimalEncoder
class EstimateFeeTest
Functions
def swap_outputs_in_rawtx (rawtx, outputs, inputnum)
def small_txpuzzle_randfee (from_node, conflist, unconflist, amount, min_fee, fee_increment)
def split_inputs (from_node, txins, txouts, initial_split=False)
def check_estimates (node, fees_seen, max_invalid, print_estimates=True)
Variables
string P2SH_1 = "8kctg1WWKdoLveifyNnDYtRAqBPpqgL8z2"
string P2SH_2 = "8xp4fcNB8rz9UbZC47tv6eui1ZSPMd3iYT"
list SCRIPT_SIG = ["0451025175", "0451025275"]
Function Documentation
check_estimates()
def smartfees.check_estimates (node, fees_seen, max_invalid, print_estimates = True)
This function calls estimatefee and verifies that the estimates
meet certain invariants.
Definition at line 119 of file smartfees.py.
small_txpuzzle_randfee()
def smartfees.small_txpuzzle_randfee (from_node, conflist, unconflist, amount, min_fee, fee_increment)
Create and send a transaction with a random fee.
The transaction pays to a trivial P2SH script, and assumes that its inputs
are of the same form.
The function takes a list of confirmed outputs and unconfirmed outputs
and attempts to use the confirmed list first for its inputs.
It adds the newly created outputs to the unconfirmed list.
Returns (raw transaction, fee)
Definition at line 43 of file smartfees.py.
Referenced by smartfees.EstimateFeeTest.transact_and_mine().
split_inputs()
def smartfees.split_inputs (from_node, txins, txouts, initial_split = False)
We need to generate a lot of very small inputs so we can generate a ton of transactions
and they will have low priority.
This function takes an input from txins, and creates and sends a transaction
which splits the value into 2 outputs which are appended to txouts.
Definition at line 94 of file smartfees.py.
swap_outputs_in_rawtx()
def smartfees.swap_outputs_in_rawtx (rawtx, outputs, inputnum)
Since dictionaries in python are unsorted make sure that our outputs are correctly ordered.
Note: comparing strings to get "correct order" is based on the fact that
P2SH_1 string is < P2SH_2 string in this particular case.
Definition at line 29 of file smartfees.py.
Referenced by small_txpuzzle_randfee(), and split_inputs().
Variable Documentation
P2SH_1
string smartfees.P2SH_1 = "8kctg1WWKdoLveifyNnDYtRAqBPpqgL8z2"
Definition at line 17 of file smartfees.py.
P2SH_2
string smartfees.P2SH_2 = "8xp4fcNB8rz9UbZC47tv6eui1ZSPMd3iYT"
Definition at line 18 of file smartfees.py.
SCRIPT_SIG
list smartfees.SCRIPT_SIG = ["0451025175", "0451025275"]
Definition at line 21 of file smartfees.py.