Dash Core: tinyformat::detail Namespace Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
tinyformat::detail Namespace Reference
Classes
struct convertToInt
struct convertToInt< T, true >
class FormatArg
class FormatListN
class FormatListN< 0 >
struct formatValueAsType
struct formatValueAsType< T, fmtT, true >
struct is_convertible
struct is_wchar
struct is_wchar< const wchar_t * >
struct is_wchar< const wchar_t[n]>
struct is_wchar< wchar_t * >
struct is_wchar< wchar_t[n]>
Functions
template<typename T >
void formatTruncated (std::ostream &out, const T &value, int ntrunc)
int parseIntAndAdvance (const char *&c)
const char * printFormatStringLiteral (std::ostream &out, const char *fmt)
const char * streamStateFromFormat (std::ostream &out, bool &spacePadPositive, int &ntrunc, const char *fmtStart, const detail::FormatArg *formatters, int &argIndex, int numFormatters)
void formatImpl (std::ostream &out, const char *fmt, const detail::FormatArg *formatters, int numFormatters)
Function Documentation
formatImpl()
void tinyformat::detail::formatImpl (std::ostream & out, const char * fmt, const detail::FormatArg * formatters, int numFormatters) inline
Definition at line 788 of file tinyformat.h.
References tinyformat::detail::FormatArg::format(), printFormatStringLiteral(), streamStateFromFormat(), and TINYFORMAT_ERROR.
Referenced by tinyformat::vformat().
formatTruncated()
template<typename T > void tinyformat::detail::formatTruncated (std::ostream & out, const T & value, int ntrunc) inline
Definition at line 274 of file tinyformat.h.
Referenced by tinyformat::formatValue().
parseIntAndAdvance()
int tinyformat::detail::parseIntAndAdvance (const char *& c) inline
Definition at line 549 of file tinyformat.h.
Referenced by streamStateFromFormat().
printFormatStringLiteral()
const char* tinyformat::detail::printFormatStringLiteral (std::ostream & out, const char * fmt) inline
Definition at line 563 of file tinyformat.h.
Referenced by formatImpl().
streamStateFromFormat()
const char* tinyformat::detail::streamStateFromFormat (std::ostream & out, bool & spacePadPositive, int & ntrunc, const char * fmtStart, const detail::FormatArg * formatters, int & argIndex, int numFormatters) inline
Definition at line 597 of file tinyformat.h.
References parseIntAndAdvance(), TINYFORMAT_ERROR, and tinyformat::detail::FormatArg::toInt().
Referenced by formatImpl().
Released under the MIT license