Dash Core: src/univalue/test/object.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
object.cpp File Reference
#include <stdint.h>
#include <vector>
#include <string>
#include <map>
#include <cassert>
#include <stdexcept>
#include <univalue.h>
Macros
#define BOOST_FIXTURE_TEST_SUITE(a, b)
#define BOOST_AUTO_TEST_CASE(funcName) void funcName()
#define BOOST_AUTO_TEST_SUITE_END()
#define BOOST_CHECK(expr) assert(expr)
#define BOOST_CHECK_EQUAL(v1, v2) assert((v1) == (v2))
#define BOOST_CHECK_THROW(stmt, excMatch)
#define BOOST_CHECK_NO_THROW(stmt)
Functions
BOOST_AUTO_TEST_CASE (univalue_constructor)
BOOST_AUTO_TEST_CASE (univalue_typecheck)
BOOST_AUTO_TEST_CASE (univalue_set)
BOOST_AUTO_TEST_CASE (univalue_array)
BOOST_AUTO_TEST_CASE (univalue_object)
BOOST_AUTO_TEST_CASE (univalue_readwrite)
int main (int argc, char *argv[])
Variables
static const char * json1
Macro Definition Documentation
BOOST_AUTO_TEST_CASE
#define BOOST_AUTO_TEST_CASE (funcName) void funcName()
Definition at line 15 of file object.cpp.
BOOST_AUTO_TEST_SUITE_END
#define BOOST_AUTO_TEST_SUITE_END ()
Definition at line 16 of file object.cpp.
BOOST_CHECK
#define BOOST_CHECK (expr) assert(expr)
Definition at line 17 of file object.cpp.
Referenced by ListCoinsTestingSetup::AddTx(), BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), CreateTransactionTestSetup::CreateTransaction(), CreateTransactionTestSetup::GetCoins(), GetResults(), TestCrypter::TestDecrypt(), and TestCrypter::TestEncryptSingle().
BOOST_CHECK_EQUAL
#define BOOST_CHECK_EQUAL (v1, v2) assert((v1) == (v2))
Definition at line 18 of file object.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), and CreateTransactionTestSetup::CheckEqual().
BOOST_CHECK_NO_THROW
#define BOOST_CHECK_NO_THROW (stmt)
Value:
{ \
        try { \
            (stmt); \
        } catch (...) { \
            assert(0); \
        } \
    }
Definition at line 28 of file object.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
BOOST_CHECK_THROW
#define BOOST_CHECK_THROW (stmt, excMatch)
Value:
{ \
        try { \
            (stmt); \
            assert(0 && "No exception caught"); \
        } catch (excMatch & e) { \
        } catch (...) { \
            assert(0 && "Wrong exception caught"); \
        } \
    }
Definition at line 19 of file object.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
BOOST_FIXTURE_TEST_SUITE
#define BOOST_FIXTURE_TEST_SUITE (a, b)
Definition at line 14 of file object.cpp.
Function Documentation
BOOST_AUTO_TEST_CASE() [1/6]
BOOST_AUTO_TEST_CASE (univalue_constructor)
Definition at line 38 of file object.cpp.
References BOOST_CHECK, BOOST_CHECK_EQUAL, UniValue::getValStr(), UniValue::isNull(), UniValue::isNum(), UniValue::isStr(), and UniValue::VSTR.
BOOST_AUTO_TEST_CASE() [2/6]
BOOST_AUTO_TEST_CASE (univalue_typecheck)
Definition at line 86 of file object.cpp.
References BOOST_CHECK, BOOST_CHECK_EQUAL, BOOST_CHECK_NO_THROW, BOOST_CHECK_THROW, UniValue::get_bool(), UniValue::isNum(), and UniValue::setNumStr().
BOOST_AUTO_TEST_CASE() [3/6]
BOOST_AUTO_TEST_CASE (univalue_set)
Definition at line 128 of file object.cpp.
References BOOST_CHECK, BOOST_CHECK_EQUAL, UniValue::clear(), UniValue::empty(), UniValue::getBool(), UniValue::getType(), UniValue::getValStr(), UniValue::isArray(), UniValue::isBool(), UniValue::isFalse(), UniValue::isNull(), UniValue::isNum(), UniValue::isObject(), UniValue::isStr(), UniValue::isTrue(), UniValue::setArray(), UniValue::setBool(), UniValue::setFloat(), UniValue::setInt(), UniValue::setNull(), UniValue::setNumStr(), UniValue::setObject(), UniValue::setStr(), UniValue::size(), UniValue::VOBJ, and UniValue::VSTR.
BOOST_AUTO_TEST_CASE() [4/6]
BOOST_AUTO_TEST_CASE (univalue_array)
Definition at line 187 of file object.cpp.
References BOOST_CHECK, BOOST_CHECK_EQUAL, UniValue::clear(), UniValue::empty(), UniValue::push_back(), UniValue::push_backV(), UniValue::setStr(), UniValue::size(), and UniValue::VARR.
BOOST_AUTO_TEST_CASE() [5/6]
BOOST_AUTO_TEST_CASE (univalue_object)
Definition at line 234 of file object.cpp.
References UniValue::__pushKV(), BOOST_CHECK, BOOST_CHECK_EQUAL, UniValue::checkObject(), UniValue::clear(), UniValue::empty(), UniValue::exists(), UniValue::getObjMap(), UniValue::getType(), UniValue::pushKV(), UniValue::pushKVs(), UniValue::setInt(), UniValue::setObject(), UniValue::size(), UniValue::VNULL, UniValue::VNUM, UniValue::VOBJ, and UniValue::VSTR.
BOOST_AUTO_TEST_CASE() [6/6]
BOOST_AUTO_TEST_CASE (univalue_readwrite)
Definition at line 341 of file object.cpp.
References BOOST_CHECK, BOOST_CHECK_EQUAL, UniValue::isArray(), UniValue::isObject(), json1, UniValue::read(), UniValue::size(), and UniValue::write().
main()
int main (int argc, char * argv[])
Definition at line 386 of file object.cpp.
Variable Documentation
json1
const char* json1 static
Initial value:
=
"[1.10000000,{\"key1\":\"str\\u0000\",\"key2\":800,\"key3\":{\"name\":\"martian http://test.com\"}}]"
Definition at line 338 of file object.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
Released under the MIT license