Dash Core: src/qt/optionsmodel.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
optionsmodel.cpp File Reference
#include <qt/optionsmodel.h>
#include <qt/bitcoinunits.h>
#include <qt/guiutil.h>
#include <init.h>
#include <validation.h>
#include <net.h>
#include <netbase.h>
#include <txdb.h>
#include <QNetworkProxy>
#include <QSettings>
#include <QStringList>
Classes
struct ProxySetting
Functions
static const QString GetDefaultProxyAddress ()
static void CopySettings (QSettings &dst, const QSettings &src)
Helper function to copy contents from one QSettings to another.
static void BackupSettings (const fs::path &filename, const QSettings &src)
Back up a QSettings to an ini-formatted file.
static ProxySetting GetProxySetting (QSettings &settings, const QString &name)
static void SetProxySetting (QSettings &settings, const QString &name, const ProxySetting &ip_port)
Variables
const char * DEFAULT_GUI_PROXY_HOST = "127.0.0.1"
Function Documentation
BackupSettings()
static void BackupSettings (const fs::path & filename, const QSettings & src) static
Back up a QSettings to an ini-formatted file.
Definition at line 236 of file optionsmodel.cpp.
References GUIUtil::boostPathToQString(), and CopySettings().
Referenced by OptionsModel::Reset().
CopySettings()
static void CopySettings (QSettings & dst, const QSettings & src) static
Helper function to copy contents from one QSettings to another.
By using allKeys this also covers nested settings in a hierarchy.
Definition at line 228 of file optionsmodel.cpp.
Referenced by BackupSettings().
GetDefaultProxyAddress()
static const QString GetDefaultProxyAddress () static
Definition at line 291 of file optionsmodel.cpp.
References DEFAULT_GUI_PROXY_HOST, and DEFAULT_GUI_PROXY_PORT.
Referenced by OptionsModel::checkAndMigrate(), and OptionsModel::Init().
GetProxySetting()
static ProxySetting GetProxySetting (QSettings & settings, const QString & name) static
Definition at line 270 of file optionsmodel.cpp.
References DEFAULT_GUI_PROXY_HOST, DEFAULT_GUI_PROXY_PORT, and name.
Referenced by OptionsModel::data(), and OptionsModel::setData().
SetProxySetting()
static void SetProxySetting (QSettings & settings, const QString & name, const ProxySetting & ip_port) static
Definition at line 286 of file optionsmodel.cpp.
References ProxySetting::ip, name, and ProxySetting::port.
Referenced by OptionsModel::setData().
Variable Documentation
DEFAULT_GUI_PROXY_HOST
const char* DEFAULT_GUI_PROXY_HOST = "127.0.0.1"
Definition at line 32 of file optionsmodel.cpp.
Referenced by GetDefaultProxyAddress(), and GetProxySetting().
Released under the MIT license