Dash Core: src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.c File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
org_bitcoin_NativeSecp256k1.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "org_bitcoin_NativeSecp256k1.h"
#include "include/secp256k1.h"
#include "include/secp256k1_ecdh.h"
#include "include/secp256k1_recovery.h"
Functions
SECP256K1_API jlong JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ctx_1clone (JNIEnv *env, jclass classObject, jlong ctx_l)
SECP256K1_API jint JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1context_1randomize (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
SECP256K1_API void JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1destroy_1context (JNIEnv *env, jclass classObject, jlong ctx_l)
SECP256K1_API jint JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1verify (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint siglen, jint publen)
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1sign (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
SECP256K1_API jint JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ec_1seckey_1verify (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ec_1pubkey_1create (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1privkey_1tweak_1add (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1privkey_1tweak_1mul (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1pubkey_1tweak_1add (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint publen)
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1pubkey_1tweak_1mul (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint publen)
SECP256K1_API jlong JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1pubkey_1combine (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint numkeys)
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdh (JNIEnv *env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint publen)
Function Documentation
Java_org_bitcoin_NativeSecp256k1_secp256k1_1context_1randomize()
SECP256K1_API jint JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1context_1randomize (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
Definition at line 24 of file org_bitcoin_NativeSecp256k1.c.
References ctx, and secp256k1_context_randomize().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1ctx_1clone()
SECP256K1_API jlong JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ctx_1clone (JNIEnv * env, jclass classObject, jlong ctx_l)
Definition at line 11 of file org_bitcoin_NativeSecp256k1.c.
References ctx, and secp256k1_context_clone().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1destroy_1context()
SECP256K1_API void JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1destroy_1context (JNIEnv * env, jclass classObject, jlong ctx_l)
Definition at line 37 of file org_bitcoin_NativeSecp256k1.c.
References ctx, and secp256k1_context_destroy().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1ec_1pubkey_1create()
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ec_1pubkey_1create (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
Definition at line 127 of file org_bitcoin_NativeSecp256k1.c.
References ctx, secp256k1_ec_pubkey_create(), secp256k1_ec_pubkey_serialize(), and SECP256K1_EC_UNCOMPRESSED.
Java_org_bitcoin_NativeSecp256k1_secp256k1_1ec_1seckey_1verify()
SECP256K1_API jint JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ec_1seckey_1verify (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
Definition at line 116 of file org_bitcoin_NativeSecp256k1.c.
References ctx, and secp256k1_ec_seckey_verify().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdh()
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdh (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint publen)
Definition at line 336 of file org_bitcoin_NativeSecp256k1.c.
References ctx, secp256k1_ec_pubkey_parse(), and secp256k1_ecdh().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1pubkey_1combine()
SECP256K1_API jlong JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1pubkey_1combine (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint numkeys)
Definition at line 328 of file org_bitcoin_NativeSecp256k1.c.
Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1sign()
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1sign (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
Definition at line 74 of file org_bitcoin_NativeSecp256k1.c.
References ctx, secp256k1_ecdsa_sign(), and secp256k1_ecdsa_signature_serialize_der().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1verify()
SECP256K1_API jint JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1verify (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint siglen, jint publen)
Definition at line 47 of file org_bitcoin_NativeSecp256k1.c.
References ctx, secp256k1_ec_pubkey_parse(), secp256k1_ecdsa_signature_parse_der(), and secp256k1_ecdsa_verify().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1privkey_1tweak_1add()
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1privkey_1tweak_1add (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
Definition at line 169 of file org_bitcoin_NativeSecp256k1.c.
References ctx, and secp256k1_ec_privkey_tweak_add().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1privkey_1tweak_1mul()
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1privkey_1tweak_1mul (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l)
Definition at line 204 of file org_bitcoin_NativeSecp256k1.c.
References ctx, and secp256k1_ec_privkey_tweak_mul().
Java_org_bitcoin_NativeSecp256k1_secp256k1_1pubkey_1tweak_1add()
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1pubkey_1tweak_1add (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint publen)
Definition at line 239 of file org_bitcoin_NativeSecp256k1.c.
References ctx, secp256k1_ec_pubkey_parse(), secp256k1_ec_pubkey_serialize(), secp256k1_ec_pubkey_tweak_add(), and SECP256K1_EC_UNCOMPRESSED.
Java_org_bitcoin_NativeSecp256k1_secp256k1_1pubkey_1tweak_1mul()
SECP256K1_API jobjectArray JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1pubkey_1tweak_1mul (JNIEnv * env, jclass classObject, jobject byteBufferObject, jlong ctx_l, jint publen)
Definition at line 284 of file org_bitcoin_NativeSecp256k1.c.
References ctx, secp256k1_ec_pubkey_parse(), secp256k1_ec_pubkey_serialize(), secp256k1_ec_pubkey_tweak_mul(), and SECP256K1_EC_UNCOMPRESSED.
Released under the MIT license