Dash Core: src/support/pagelocker.h File Reference
pagelocker.h File Reference
#include "support/cleanse.h"
#include <map>
#include <boost/thread/mutex.hpp>
#include <boost/thread/once.hpp>
Classes
class LockedPageManagerBase< Locker >
class MemoryPageLocker
class LockedPageManager
Functions
template<typename T >
void LockObject (const T &t)
template<typename T >
void UnlockObject (const T &t)
Function Documentation
LockObject()
template<typename T > void LockObject (const T & t)
Definition at line 165 of file pagelocker.h.
Referenced by CKey::CKey(), CKey::Derive(), ECC_Start(), and CExtKey::SetMaster().
UnlockObject()
template<typename T > void UnlockObject (const T & t)
Definition at line 171 of file pagelocker.h.
Referenced by CKey::Derive(), ECC_Start(), CExtKey::SetMaster(), and CKey::~CKey().