Dash Core: src/policy/fees.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
fees.h File Reference
#include <amount.h>
#include <policy/feerate.h>
#include <uint256.h>
#include <random.h>
#include <sync.h>
#include <map>
#include <memory>
#include <string>
#include <vector>
Classes
struct EstimatorBucket
struct EstimationResult
struct FeeCalculation
class CBlockPolicyEstimator
We want to be able to estimate feerates that are needed on tx's to be included in a certain number of blocks.
struct CBlockPolicyEstimator::TxStatsInfo
Enumerations
enum FeeEstimateHorizon { SHORT_HALFLIFE = 0, MED_HALFLIFE = 1, LONG_HALFLIFE = 2 }
enum FeeReason {
FeeReason::NONE, FeeReason::HALF_ESTIMATE, FeeReason::FULL_ESTIMATE, FeeReason::DOUBLE_ESTIMATE,
FeeReason::CONSERVATIVE, FeeReason::MEMPOOL_MIN, FeeReason::PAYTXFEE, FeeReason::FALLBACK,
FeeReason::REQUIRED, FeeReason::MAXTXFEE
}
enum FeeEstimateMode { FeeEstimateMode::UNSET, FeeEstimateMode::ECONOMICAL, FeeEstimateMode::CONSERVATIVE }
Functions
std::string StringForFeeEstimateHorizon (FeeEstimateHorizon horizon)
std::string StringForFeeReason (FeeReason reason)
bool FeeModeFromString (const std::string &mode_string, FeeEstimateMode &fee_estimate_mode)
Enumeration Type Documentation
FeeEstimateHorizon
enum FeeEstimateHorizon
Enumerator
SHORT_HALFLIFE
MED_HALFLIFE
LONG_HALFLIFE
Definition at line 72 of file fees.h.
FeeEstimateMode
enum FeeEstimateMode strong
Enumerator
UNSET
ECONOMICAL
Use default settings based on other criteria.
CONSERVATIVE
Force estimateSmartFee to use non-conservative estimates.
Definition at line 97 of file fees.h.
FeeReason
enum FeeReason strong
Enumerator
NONE
HALF_ESTIMATE
FULL_ESTIMATE
DOUBLE_ESTIMATE
CONSERVATIVE
MEMPOOL_MIN
PAYTXFEE
FALLBACK
REQUIRED
MAXTXFEE
Definition at line 81 of file fees.h.
Function Documentation
FeeModeFromString()
bool FeeModeFromString (const std::string & mode_string, FeeEstimateMode & fee_estimate_mode)
Definition at line 50 of file fees.cpp.
References CONSERVATIVE, ECONOMICAL, and UNSET.
Referenced by estimatesmartfee(), fundrawtransaction(), sendmany(), and sendtoaddress().
StringForFeeEstimateHorizon()
std::string StringForFeeEstimateHorizon (FeeEstimateHorizon horizon)
Definition at line 17 of file fees.cpp.
References LONG_HALFLIFE, MED_HALFLIFE, and SHORT_HALFLIFE.
Referenced by estimaterawfee().
StringForFeeReason()
std::string StringForFeeReason (FeeReason reason)
Definition at line 30 of file fees.cpp.
References CONSERVATIVE, DOUBLE_ESTIMATE, FALLBACK, FULL_ESTIMATE, HALF_ESTIMATE, MAXTXFEE, MEMPOOL_MIN, NONE, PAYTXFEE, and REQUIRED.
Referenced by CWallet::CreateTransaction().
Released under the MIT license