Dash Core: src/policy/fees.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
fees.cpp File Reference
#include <policy/fees.h>
#include <policy/policy.h>
#include <clientversion.h>
#include <primitives/transaction.h>
#include <streams.h>
#include <txmempool.h>
#include <util.h>
Classes
class TxConfirmStats
We will instantiate an instance of this class to track transactions that were included in a block.
Functions
std::string StringForFeeEstimateHorizon (FeeEstimateHorizon horizon)
std::string StringForFeeReason (FeeReason reason)
bool FeeModeFromString (const std::string &mode_string, FeeEstimateMode &fee_estimate_mode)
Variables
static constexpr double INF_FEERATE = 1e99
Function Documentation
FeeModeFromString()
bool FeeModeFromString (const std::string & mode_string, FeeEstimateMode & fee_estimate_mode)
Definition at line 50 of file fees.cpp.
References CONSERVATIVE, ECONOMICAL, and UNSET.
Referenced by estimatesmartfee(), fundrawtransaction(), sendmany(), and sendtoaddress().
StringForFeeEstimateHorizon()
std::string StringForFeeEstimateHorizon (FeeEstimateHorizon horizon)
Definition at line 17 of file fees.cpp.
References LONG_HALFLIFE, MED_HALFLIFE, and SHORT_HALFLIFE.
Referenced by estimaterawfee().
StringForFeeReason()
std::string StringForFeeReason (FeeReason reason)
Definition at line 30 of file fees.cpp.
References CONSERVATIVE, DOUBLE_ESTIMATE, FALLBACK, FULL_ESTIMATE, HALF_ESTIMATE, MAXTXFEE, MEMPOOL_MIN, NONE, PAYTXFEE, and REQUIRED.
Referenced by CWallet::CreateTransaction().
Variable Documentation
INF_FEERATE
constexpr double INF_FEERATE = 1e99 static
Definition at line 15 of file fees.cpp.
Referenced by CBlockPolicyEstimator::CBlockPolicyEstimator().
Released under the MIT license