Dash Core: src/crypto/poly1305.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
poly1305.h File Reference
#include <stdint.h>
#include <stdlib.h>
Macros
#define POLY1305_KEYLEN 32
#define POLY1305_TAGLEN 16
Functions
void poly1305_auth (unsigned char out[POLY1305_TAGLEN], const unsigned char *m, size_t inlen, const unsigned char key[POLY1305_KEYLEN])
Macro Definition Documentation
POLY1305_KEYLEN
#define POLY1305_KEYLEN 32
Definition at line 11 of file poly1305.h.
Referenced by ChaCha20Poly1305AEAD::Crypt(), and POLY1305().
POLY1305_TAGLEN
#define POLY1305_TAGLEN 16
Definition at line 12 of file poly1305.h.
Referenced by CHACHA20_POLY1305_AEAD(), ChaCha20Poly1305AEAD::Crypt(), and POLY1305().
Function Documentation
poly1305_auth()
void poly1305_auth (unsigned char out[POLY1305_TAGLEN], const unsigned char * m, size_t inlen, const unsigned char key[POLY1305_KEYLEN])
Definition at line 15 of file poly1305.cpp.
References mul32x32_64, ReadLE32(), and WriteLE32().
Referenced by ChaCha20Poly1305AEAD::Crypt(), and POLY1305().
Released under the MIT license