Dash Core: src/bench/prevector.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
prevector.cpp File Reference
#include <compat.h>
#include <prevector.h>
#include <bench/bench.h>
#include <vector>
Classes
struct nontrivial_t
Macros
#define PREVECTOR_TEST(name, nontrivops, trivops)
Typedefs
typedef unsigned char trivial_t
typedef prevector< 28, unsigned char > prevec
Functions
template<typename T >
static void PrevectorDestructor (benchmark::State &state)
template<typename T >
static void PrevectorClear (benchmark::State &state)
template<typename T >
void PrevectorResize (benchmark::State &state)
static void PrevectorAssign (benchmark::State &state)
static void PrevectorAssignTo (benchmark::State &state)
Macro Definition Documentation
PREVECTOR_TEST
#define PREVECTOR_TEST (name, nontrivops, trivops)
Value:
static void Prevector ## name ## Nontrivial(benchmark::State& state) { \
        PrevectorResize<nontrivial_t>(state);                           \
    }                                                                   \
    BENCHMARK(Prevector ## name ## Nontrivial/*, nontrivops*/);             \
    static void Prevector ## name ## Trivial(benchmark::State& state) { \
        PrevectorResize<trivial_t>(state);                              \
    }                                                                   \
    BENCHMARK(Prevector ## name ## Trivial/*, trivops*/);
Definition at line 65 of file prevector.cpp.
Typedef Documentation
prevec
typedef prevector<28, unsigned char> prevec
Definition at line 81 of file prevector.cpp.
trivial_t
typedef unsigned char trivial_t
Definition at line 15 of file prevector.cpp.
Function Documentation
PrevectorAssign()
static void PrevectorAssign (benchmark::State & state) static
Definition at line 83 of file prevector.cpp.
References prevector< N, T, Size, Diff >::begin(), benchmark::State::KeepRunning(), and prevector< N, T, Size, Diff >::resize().
PrevectorAssignTo()
static void PrevectorAssignTo (benchmark::State & state) static
Definition at line 97 of file prevector.cpp.
References prevector< N, T, Size, Diff >::assign_to(), prevector< N, T, Size, Diff >::begin(), benchmark::State::KeepRunning(), and prevector< N, T, Size, Diff >::resize().
PrevectorClear()
template<typename T > static void PrevectorClear (benchmark::State & state) static
Definition at line 35 of file prevector.cpp.
References prevector< N, T, Size, Diff >::clear(), benchmark::State::KeepRunning(), and prevector< N, T, Size, Diff >::resize().
PrevectorDestructor()
template<typename T > static void PrevectorDestructor (benchmark::State & state) static
Definition at line 22 of file prevector.cpp.
References benchmark::State::KeepRunning(), and prevector< N, T, Size, Diff >::resize().
PrevectorResize()
template<typename T > void PrevectorResize (benchmark::State & state)
Definition at line 51 of file prevector.cpp.
References benchmark::State::KeepRunning(), and prevector< N, T, Size, Diff >::resize().
Released under the MIT license