Dash Core: src/evo/providertx.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
providertx.h File Reference
#include <bls/bls.h>
#include <consensus/validation.h>
#include <primitives/transaction.h>
#include <base58.h>
#include <netaddress.h>
#include <pubkey.h>
#include <univalue.h>
Classes
class CProRegTx
class CProUpServTx
class CProUpRegTx
class CProUpRevTx
Functions
bool CheckProRegTx (const CTransaction &tx, const CBlockIndex *pindexPrev, CValidationState &state)
bool CheckProUpServTx (const CTransaction &tx, const CBlockIndex *pindexPrev, CValidationState &state)
bool CheckProUpRegTx (const CTransaction &tx, const CBlockIndex *pindexPrev, CValidationState &state)
bool CheckProUpRevTx (const CTransaction &tx, const CBlockIndex *pindexPrev, CValidationState &state)
Function Documentation
CheckProRegTx()
bool CheckProRegTx (const CTransaction & tx, const CBlockIndex * pindexPrev, CValidationState & state)
Definition at line 86 of file providertx.cpp.
References CProRegTx::addr, CheckInputsHash(), CheckService(), CheckStringSig(), COIN, CProRegTx::collateralOutpoint, CProRegTx::CURRENT_VERSION, deterministicMNManager, CValidationState::DoS(), ExtractDestination(), CTransaction::GetHash(), GetTxPayload(), GetUTXOCoin(), COutPoint::hash, base_blob< BITS >::IsNull(), CScript::IsPayToPublicKeyHash(), CScript::IsPayToScriptHash(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CProRegTx::keyIDOwner, CProRegTx::keyIDVoting, COutPoint::n, CBlockIndex::nHeight, CProRegTx::nMode, CProRegTx::nOperatorReward, CProRegTx::nType, CTransaction::nType, CTxOut::nValue, CProRegTx::nVersion, Coin::out, CProRegTx::pubKeyOperator, REJECT_DUPLICATE, REJECT_INVALID, CProRegTx::scriptPayout, CTxOut::scriptPubKey, TRANSACTION_PROVIDER_REGISTER, CProRegTx::vchSig, and CTransaction::vout.
Referenced by CheckSpecialTx().
CheckProUpRegTx()
bool CheckProUpRegTx (const CTransaction & tx, const CBlockIndex * pindexPrev, CValidationState & state)
Definition at line 274 of file providertx.cpp.
References CheckHashSig(), CheckInputsHash(), CProUpRegTx::CURRENT_VERSION, deterministicMNManager, CValidationState::DoS(), ExtractDestination(), GetTxPayload(), GetUTXOCoin(), base_blob< BITS >::IsNull(), CScript::IsPayToPublicKeyHash(), CScript::IsPayToScriptHash(), CBLSWrapper< ImplType, _SerSize, C >::IsValid(), CProUpRegTx::keyIDVoting, CBlockIndex::nHeight, CProUpRegTx::nMode, CTransaction::nType, CProUpRegTx::nVersion, Coin::out, CProUpRegTx::proTxHash, CProUpRegTx::pubKeyOperator, REJECT_DUPLICATE, REJECT_INVALID, CProUpRegTx::scriptPayout, CTxOut::scriptPubKey, and TRANSACTION_PROVIDER_UPDATE_REGISTRAR.
Referenced by CheckSpecialTx().
CheckProUpRevTx()
bool CheckProUpRevTx (const CTransaction & tx, const CBlockIndex * pindexPrev, CValidationState & state)
Definition at line 358 of file providertx.cpp.
References CheckHashSig(), CheckInputsHash(), CProUpRevTx::CURRENT_VERSION, deterministicMNManager, CValidationState::DoS(), GetTxPayload(), CProUpRevTx::nReason, CTransaction::nType, CProUpRevTx::nVersion, CProUpRevTx::proTxHash, CProUpRevTx::REASON_LAST, REJECT_INVALID, and TRANSACTION_PROVIDER_UPDATE_REVOKE.
Referenced by CheckSpecialTx().
CheckProUpServTx()
bool CheckProUpServTx (const CTransaction & tx, const CBlockIndex * pindexPrev, CValidationState & state)
Definition at line 218 of file providertx.cpp.
References CProUpServTx::addr, CheckHashSig(), CheckInputsHash(), CheckService(), CProUpServTx::CURRENT_VERSION, deterministicMNManager, CValidationState::DoS(), GetTxPayload(), CScript::IsPayToPublicKeyHash(), CScript::IsPayToScriptHash(), CTransaction::nType, CProUpServTx::nVersion, CProUpServTx::proTxHash, REJECT_DUPLICATE, REJECT_INVALID, CProUpServTx::scriptOperatorPayout, and TRANSACTION_PROVIDER_UPDATE_SERVICE.
Referenced by CheckSpecialTx().
Released under the MIT license