Dash Core: src/policy/rbf.h File Reference
rbf.h File Reference
#include "txmempool.h"
Functions
bool SignalsOptInRBF (const CTransaction &tx)
bool IsRBFOptIn (const CTxMemPoolEntry &entry, CTxMemPool &pool)
Function Documentation
IsRBFOptIn()
bool IsRBFOptIn (const CTxMemPoolEntry & entry, CTxMemPool & pool)
Definition at line 17 of file rbf.cpp.
Referenced by WalletTxToJSON().
SignalsOptInRBF()
bool SignalsOptInRBF (const CTransaction & tx)
Definition at line 7 of file rbf.cpp.
Referenced by IsRBFOptIn(), and WalletTxToJSON().