Dash Core: src/rpc/register.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
register.h File Reference
Functions
void RegisterBlockchainRPCCommands (CRPCTable &tableRPC)
Register block chain RPC commands.
void RegisterNetRPCCommands (CRPCTable &tableRPC)
Register P2P networking RPC commands.
void RegisterMiscRPCCommands (CRPCTable &tableRPC)
Register miscellaneous RPC commands.
void RegisterMiningRPCCommands (CRPCTable &tableRPC)
Register mining RPC commands.
void RegisterRawTransactionRPCCommands (CRPCTable &tableRPC)
Register raw transaction RPC commands.
void RegisterMasternodeRPCCommands (CRPCTable &tableRPC)
Register masternode RPC commands.
void RegisterPrivateSendRPCCommands (CRPCTable &tableRPC)
Register PrivateSend RPC commands.
void RegisterGovernanceRPCCommands (CRPCTable &tableRPC)
Register governance RPC commands.
void RegisterEvoRPCCommands (CRPCTable &tableRPC)
Register Evo RPC commands.
void RegisterQuorumsRPCCommands (CRPCTable &tableRPC)
Register Quorums RPC commands.
static void RegisterAllCoreRPCCommands (CRPCTable &t)
Function Documentation
RegisterAllCoreRPCCommands()
static void RegisterAllCoreRPCCommands (CRPCTable & t) inline static
Definition at line 33 of file register.h.
References RegisterBlockchainRPCCommands(), RegisterEvoRPCCommands(), RegisterGovernanceRPCCommands(), RegisterMasternodeRPCCommands(), RegisterMiningRPCCommands(), RegisterMiscRPCCommands(), RegisterNetRPCCommands(), RegisterPrivateSendRPCCommands(), RegisterQuorumsRPCCommands(), and RegisterRawTransactionRPCCommands().
Referenced by AppInitMain().
RegisterBlockchainRPCCommands()
void RegisterBlockchainRPCCommands (CRPCTable & tableRPC)
Register block chain RPC commands.
Definition at line 2293 of file blockchain.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RegisterEvoRPCCommands()
void RegisterEvoRPCCommands (CRPCTable & tableRPC)
Register Evo RPC commands.
Definition at line 1307 of file rpcevo.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, name, and tableRPC.
Referenced by RegisterAllCoreRPCCommands().
RegisterGovernanceRPCCommands()
void RegisterGovernanceRPCCommands (CRPCTable & tableRPC)
Register governance RPC commands.
Definition at line 1107 of file governance.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RegisterMasternodeRPCCommands()
void RegisterMasternodeRPCCommands (CRPCTable & tableRPC)
Register masternode RPC commands.
Definition at line 531 of file masternode.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RegisterMiningRPCCommands()
void RegisterMiningRPCCommands (CRPCTable & tableRPC)
Register mining RPC commands.
Definition at line 1020 of file mining.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RegisterMiscRPCCommands()
void RegisterMiscRPCCommands (CRPCTable & tableRPC)
Register miscellaneous RPC commands.
Definition at line 1231 of file misc.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RegisterNetRPCCommands()
void RegisterNetRPCCommands (CRPCTable & tableRPC)
Register P2P networking RPC commands.
Definition at line 670 of file net.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RegisterPrivateSendRPCCommands()
void RegisterPrivateSendRPCCommands (CRPCTable & tableRPC)
Register PrivateSend RPC commands.
Definition at line 162 of file privatesend.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
RegisterQuorumsRPCCommands()
void RegisterQuorumsRPCCommands (CRPCTable & tableRPC)
Register Quorums RPC commands.
Definition at line 528 of file rpcquorums.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, CRPCCommand::name, and tableRPC.
Referenced by RegisterAllCoreRPCCommands().
RegisterRawTransactionRPCCommands()
void RegisterRawTransactionRPCCommands (CRPCTable & tableRPC)
Register raw transaction RPC commands.
Definition at line 1070 of file rawtransaction.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
Released under the MIT license