Dash Core: src/rpc/masternode.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
masternode.cpp File Reference
#include "activemasternode.h"
#include "init.h"
#include "netbase.h"
#include "validation.h"
#include "masternode-payments.h"
#include "masternode-sync.h"
#include "masternodeconfig.h"
#include "masternodeman.h"
#include "privatesend-client.h"
#include "privatesend-server.h"
#include "rpc/server.h"
#include "util.h"
#include "utilmoneystr.h"
#include <fstream>
#include <iomanip>
#include <univalue.h>
Functions
void EnsureWalletIsUnlocked ()
UniValue privatesend (const UniValue &params, bool fHelp)
UniValue getpoolinfo (const UniValue &params, bool fHelp)
UniValue masternode (const UniValue &params, bool fHelp)
UniValue masternodelist (const UniValue &params, bool fHelp)
bool DecodeHexVecMnb (std::vector< CMasternodeBroadcast > &vecMnb, std::string strHexMnb)
UniValue masternodebroadcast (const UniValue &params, bool fHelp)
UniValue sentinelping (const UniValue &params, bool fHelp)
Function Documentation
DecodeHexVecMnb()
bool DecodeHexVecMnb (std::vector< CMasternodeBroadcast > & vecMnb, std::string strHexMnb)
Definition at line 590 of file masternode.cpp.
References IsHex(), ParseHex(), PROTOCOL_VERSION, and SER_NETWORK.
Referenced by masternodebroadcast().
EnsureWalletIsUnlocked()
void EnsureWalletIsUnlocked ()
Definition at line 54 of file rpcwallet.cpp.
Referenced by masternode(), masternodebroadcast(), privatesend(), and signrawtransaction().
getpoolinfo()
UniValue getpoolinfo (const UniValue & params, bool fHelp)
Definition at line 65 of file masternode.cpp.
References masternode_info_t::addr, masternode_info_t::fInfoValid, fMasterNode, CPrivateSendClient::fPrivateSendMultiSession, CPrivateSendBase::GetEntriesCount(), CPrivateSendBase::GetQueueSize(), CPrivateSendBase::GetStateString(), CPrivateSendClient::GetStatus(), CPrivateSendClient::infoMixingMasternode, CWallet::nKeysLeftSinceAutoBackup, Pair(), CTxIn::prevout, PRIVATESEND_KEYS_THRESHOLD_WARNING, privateSendClient, privateSendServer, UniValue::push_back(), pwalletMain, UniValue::size(), CService::ToString(), COutPoint::ToStringShort(), masternode_info_t::vin, and UniValue::VOBJ.
masternode()
UniValue masternode (const UniValue & params, bool fHelp)
Definition at line 96 of file masternode.cpp.
References ACTIVE_MASTERNODE_INITIAL, ACTIVE_MASTERNODE_STARTED, activeMasternode, masternode_info_t::addr, atoi(), CWallet::AvailableCoins(), chainActive, CMasternodeMan::CountEnabled(), CMasternodeBroadcast::Create(), cs_main, CWallet::cs_wallet, EnsureWalletIsUnlocked(), fMasterNode, g_connman, CMasternodeMan::Get(), UniValue::get_str(), CMasternodeConfig::CMasternodeEntry::getAlias(), CMasternodeConfig::getEntries(), CTransaction::GetHash(), CPubKey::GetID(), CMasternodeConfig::CMasternodeEntry::getIp(), CWallet::GetMasternodeOutpointAndKeys(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), CMasternodeConfig::CMasternodeEntry::getOutputIndex(), CMasternodeConfig::CMasternodeEntry::getPrivKey(), GetRequiredPaymentsString(), CActiveMasternode::GetStatus(), CMasternodeConfig::CMasternodeEntry::getTxHash(), COutput::i, CMasternodeSync::IsBlockchainSynced(), CMasternodeSync::IsMasternodeListSynced(), JSONRPCError(), LOCK, Lookup(), CKey::MakeNewKey(), CActiveMasternode::ManageState(), masternodeConfig, masternodelist(), masternodeSync, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, CBlockIndex::nHeight, NODE_NETWORK, CMasternodeMan::NotifyMasternodeUpdates(), masternode_info_t::nProtocolVersion, CActiveMasternode::nState, masternode_info_t::nTimeLastPing, NullUniValue, ONLY_1000, CActiveMasternode::outpoint, Pair(), CTxIn::prevout, masternode_info_t::pubKeyCollateralAddress, UniValue::push_back(), pwalletMain, CMasternodeBroadcast::Relay(), RPC_CLIENT_IN_INITIAL_DOWNLOAD, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, CActiveMasternode::service, masternode_info_t::sigTime, UniValue::size(), CMasternodeMan::size(), strprintf, CChain::Tip(), base_blob< BITS >::ToString(), CBase58Data::ToString(), CService::ToString(), COutPoint::ToStringShort(), COutput::tx, uint256S(), CMasternodeMan::UpdateLastPaid(), CMasternodeMan::UpdateMasternodeList(), UniValue::VARR, masternode_info_t::vin, and UniValue::VOBJ.
masternodebroadcast()
UniValue masternodebroadcast (const UniValue & params, bool fHelp)
Definition at line 607 of file masternode.cpp.
References masternode_info_t::addr, CDataStream::begin(), CMasternodePing::blockHash, CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckSignature(), CMasternodeBroadcast::Create(), CWallet::cs_wallet, DecodeHexVecMnb(), EncodeBase64(), CDataStream::end(), EnsureWalletIsUnlocked(), fImporting, fReindex, g_connman, UniValue::get_str(), CMasternodeConfig::CMasternodeEntry::getAlias(), CMasternodeConfig::getEntries(), CMasternodeBroadcast::GetHash(), CPubKey::GetID(), CMasternodeConfig::CMasternodeEntry::getIp(), CMasternodeConfig::CMasternodeEntry::getOutputIndex(), CMasternodeConfig::CMasternodeEntry::getPrivKey(), CMasternodeConfig::CMasternodeEntry::getTxHash(), HexStr(), JSONRPCError(), CMasternode::lastPing, LOCK, masternodeConfig, mnodeman, masternode_info_t::nLastDsq, CMasternodeMan::NotifyMasternodeUpdates(), masternode_info_t::nProtocolVersion, NullUniValue, Pair(), CTxIn::prevout, PROTOCOL_VERSION, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, UniValue::push_back(), pwalletMain, CMasternodeBroadcast::Relay(), RPC_DESERIALIZATION_ERROR, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, SER_NETWORK, CMasternodePing::sigTime, masternode_info_t::sigTime, UniValue::size(), strprintf, base_blob< BITS >::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeMan::UpdateMasternodeList(), CMasternodePing::vchSig, CMasternode::vchSig, CMasternodePing::vin, masternode_info_t::vin, and UniValue::VOBJ.
masternodelist()
UniValue masternodelist (const UniValue & params, bool fHelp)
Definition at line 454 of file masternode.cpp.
References masternode_info_t::addr, chainActive, cs_main, CMasternodePing::fSentinelIsCurrent, CMasternodeMan::GetFullMasternodeMap(), CPubKey::GetID(), CMasternode::GetLastPaidBlock(), CMasternode::GetLastPaidTime(), CMasternodeMan::GetMasternodeRanks(), CMasternode::GetStatus(), HexStr(), CMasternode::lastPing, LOCK, mnodeman, masternode_info_t::nProtocolVersion, CMasternodePing::nSentinelVersion, Pair(), PAIRTYPE, CTxIn::prevout, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, UniValue::push_back(), SafeIntVersionToString(), CMasternodePing::sigTime, masternode_info_t::sigTime, UniValue::size(), strprintf, CChain::Tip(), CBase58Data::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeMan::UpdateLastPaid(), masternode_info_t::vin, and UniValue::VOBJ.
Referenced by masternode().
privatesend()
UniValue privatesend (const UniValue & params, bool fHelp)
Definition at line 25 of file masternode.cpp.
References CWallet::cs_wallet, CPrivateSendClient::DoAutomaticDenominating(), EnsureWalletIsUnlocked(), CPrivateSendClient::fEnablePrivateSend, fMasterNode, g_connman, CPrivateSendClient::GetStatus(), LOCK, privateSendClient, pwalletMain, CPrivateSendClient::ResetPool(), and UniValue::size().
sentinelping()
UniValue sentinelping (const UniValue & params, bool fHelp)
Definition at line 836 of file masternode.cpp.
References activeMasternode, HelpExampleCli(), HelpExampleRpc(), UniValue::size(), StringVersionToInt(), and CActiveMasternode::UpdateSentinelPing().
Released under the MIT license