Dash Core: src/rpc/privatesend.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
privatesend.cpp File Reference
#include <validation.h>
#include <privatesend/privatesend-server.h>
#include <rpc/server.h>
#include <rpc/safemode.h>
#include <univalue.h>
Functions
UniValue getpoolinfo (const JSONRPCRequest &request)
UniValue getprivatesendinfo (const JSONRPCRequest &request)
void RegisterPrivateSendRPCCommands (CRPCTable &t)
Register PrivateSend RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
getpoolinfo()
UniValue getpoolinfo (const JSONRPCRequest & request)
Definition at line 75 of file privatesend.cpp.
getprivatesendinfo()
UniValue getprivatesendinfo (const JSONRPCRequest & request)
Definition at line 83 of file privatesend.cpp.
References CURRENCY_UNIT, JSONRPCRequest::fHelp, fMasternodeMode, CPrivateSendServer::GetJsonInfo(), CPrivateSendClientManager::GetJsonInfo(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CWallet::nKeysLeftSinceAutoBackup, Pair(), JSONRPCRequest::params, PRIVATESEND_KEYS_THRESHOLD_WARNING, privateSendClient, privateSendServer, UniValue::push_back(), UniValue::size(), and UniValue::VOBJ.
RegisterPrivateSendRPCCommands()
void RegisterPrivateSendRPCCommands (CRPCTable & t)
Register PrivateSend RPC commands.
Definition at line 162 of file privatesend.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by RegisterAllCoreRPCCommands().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
    {
        { "dash",               "getpoolinfo",            &getpoolinfo,            {} },
        { "dash",               "getprivatesendinfo",     &getprivatesendinfo,     {} },
}
Definition at line 152 of file privatesend.cpp.
Referenced by RegisterPrivateSendRPCCommands().
Released under the MIT license