Dash Core: src/rpc/util.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
util.h File Reference
#include <string>
#include <vector>
Functions
CPubKey HexToPubKey (const std::string &hex_in)
CPubKey AddrToPubKey (CKeyStore *const keystore, const std::string &addr_in)
CScript CreateMultisigRedeemscript (const int required, const std::vector< CPubKey > &pubkeys)
Function Documentation
AddrToPubKey()
CPubKey AddrToPubKey (CKeyStore *const keystore, const std::string & addr_in)
Definition at line 27 of file util.cpp.
References DecodeDestination(), CKeyStore::GetPubKey(), CPubKey::IsFullyValid(), IsValidDestination(), JSONRPCError(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, and strprintf.
Referenced by addmultisigaddress(), and createmultisig().
CreateMultisigRedeemscript()
CScript CreateMultisigRedeemscript (const int required, const std::vector< CPubKey > & pubkeys)
Definition at line 48 of file util.cpp.
References GetScriptForMultisig(), JSONRPCError(), MAX_SCRIPT_ELEMENT_SIZE, RPC_INVALID_PARAMETER, prevector< N, T, Size, Diff >::size(), and strprintf.
Referenced by addmultisigaddress(), and createmultisig().
HexToPubKey()
CPubKey HexToPubKey (const std::string & hex_in)
Definition at line 14 of file util.cpp.
References CPubKey::IsFullyValid(), IsHex(), JSONRPCError(), ParseHex(), and RPC_INVALID_ADDRESS_OR_KEY.
Referenced by addmultisigaddress(), and createmultisig().
Released under the MIT license