Dash Core: src/qt/rpcconsole.cpp File Reference
rpcconsole.cpp File Reference
#include "rpcconsole.h"
#include "ui_debugwindow.h"
#include "bantablemodel.h"
#include "clientmodel.h"
#include "guiutil.h"
#include "platformstyle.h"
#include "chainparams.h"
#include "netbase.h"
#include "rpc/server.h"
#include "rpc/client.h"
#include "util.h"
#include <openssl/crypto.h>
#include <univalue.h>
#include <QDir>
#include <QKeyEvent>
#include <QMenu>
#include <QScrollBar>
#include <QSettings>
#include <QSignalMapper>
#include <QThread>
#include <QTime>
#include <QTimer>
#include <QStringList>
#include <QUrl>
#include "rpcconsole.moc"
Classes
class RPCExecutor
class QtRPCTimerBase
class QtRPCTimerInterface
Functions
const QSize FONT_RANGE (4, 40)
const QString SALVAGEWALLET ("-salvagewallet")
const QString RESCAN ("-rescan")
const QString ZAPTXES1 ("-zapwallettxes=1")
const QString ZAPTXES2 ("-zapwallettxes=2")
const QString UPGRADEWALLET ("-upgradewallet")
const QString REINDEX ("-reindex")
bool parseCommandLine (std::vector< std::string > &args, const std::string &strCommand)
static QString categoryClass (int category)
Variables
const int CONSOLE_HISTORY = 50
const char fontSizeSettingsKey [] = "consoleFontSize"
const TrafficGraphData::GraphRange INITIAL_TRAFFIC_GRAPH_SETTING = TrafficGraphData::Range_30m
struct {
const char * url
const char * source
} ICON_MAPPING []
Function Documentation
categoryClass()
static QString categoryClass (int category) static
Definition at line 502 of file rpcconsole.cpp.
Referenced by RPCConsole::message().
FONT_RANGE()
const QSize FONT_RANGE (4 , 40)
Referenced by RPCConsole::setFontSize().
parseCommandLine()
bool parseCommandLine (std::vector< std::string > & args, const std::string & strCommand)
Split shell command line into a list of arguments. Aims to emulate bash and friends.
Arguments are delimited with whitespace
Extra whitespace at the beginning and end and between arguments will be ignored
Text can be "double" or 'single' quoted
The backslash \ is used as escape character
Outside quotes, any character can be escaped
Within double quotes, only escape " and backslashes before a \c " or another backslash
Within single quotes, no escaping is possible and no special interpretation takes place
Parameters
[out] args Parsed arguments will be appended to this list
[in] strCommand Command line to split
Definition at line 135 of file rpcconsole.cpp.
Referenced by RPCExecutor::request().
REINDEX()
const QString REINDEX ("-reindex")
Referenced by RPCConsole::buildParameterlist(), and RPCConsole::walletReindex().
RESCAN()
const QString RESCAN ("-rescan")
Referenced by RPCConsole::buildParameterlist(), and RPCConsole::walletRescan().
SALVAGEWALLET()
const QString SALVAGEWALLET ("-salvagewallet")
Referenced by RPCConsole::buildParameterlist(), and RPCConsole::walletSalvage().
UPGRADEWALLET()
const QString UPGRADEWALLET ("-upgradewallet")
Referenced by RPCConsole::buildParameterlist(), and RPCConsole::walletUpgrade().
ZAPTXES1()
const QString ZAPTXES1 ()
Referenced by RPCConsole::buildParameterlist(), and RPCConsole::walletZaptxes1().
ZAPTXES2()
const QString ZAPTXES2 ()
Referenced by RPCConsole::buildParameterlist(), and RPCConsole::walletZaptxes2().
Variable Documentation
CONSOLE_HISTORY
const int CONSOLE_HISTORY = 50
Definition at line 47 of file rpcconsole.cpp.
Referenced by RPCConsole::on_lineEdit_returnPressed().
fontSizeSettingsKey
const char fontSizeSettingsKey[] = "consoleFontSize"
Definition at line 49 of file rpcconsole.cpp.
Referenced by RPCConsole::RPCConsole(), and RPCConsole::setFontSize().
ICON_MAPPING
const { ... } ICON_MAPPING[]
Initial value:
= {
    {"cmd-request", "tx_input"},
    {"cmd-reply", "tx_output"},
    {"cmd-error", "tx_output"},
    {"misc", "tx_inout"},
    {NULL, NULL}
}
Referenced by RPCConsole::clear().
INITIAL_TRAFFIC_GRAPH_SETTING
const TrafficGraphData::GraphRange INITIAL_TRAFFIC_GRAPH_SETTING = TrafficGraphData::Range_30m
Definition at line 51 of file rpcconsole.cpp.
Referenced by RPCConsole::RPCConsole().
source
const char* source
Definition at line 63 of file rpcconsole.cpp.
Referenced by CAddrMan::Add(), CAddrMan::Add_(), AppInit2(), payments::Output::MergeFrom(), payments::PaymentDetails::MergeFrom(), payments::PaymentRequest::MergeFrom(), payments::X509Certificates::MergeFrom(), payments::Payment::MergeFrom(), and payments::PaymentACK::MergeFrom().
url
const char* url
Definition at line 62 of file rpcconsole.cpp.
Referenced by RPCConsole::clear(), PaymentServer::fetchRequest(), and TransactionView::openThirdPartyTxUrl().