Dash Core: src/rpc/rpcevo.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
rpcevo.cpp File Reference
#include <base58.h>
#include <consensus/validation.h>
#include <core_io.h>
#include <init.h>
#include <messagesigner.h>
#include <rpc/safemode.h>
#include <rpc/server.h>
#include <txmempool.h>
#include <utilmoneystr.h>
#include <validation.h>
#include <netbase.h>
#include <evo/specialtx.h>
#include <evo/providertx.h>
#include <evo/deterministicmns.h>
#include <evo/simplifiedmns.h>
#include <bls/bls.h>
#include "masternode/masternode-meta.h"
Functions
std::string GetHelpString (int nParamNum, std::string strParamName)
static CKey ParsePrivKey (CWallet *pwallet, const std::string &strKeyOrAddress, bool allowAddresses=true)
static CKeyID ParsePubKeyIDFromAddress (const std::string &strAddress, const std::string &paramName)
static CBLSPublicKey ParseBLSPubKey (const std::string &hexKey, const std::string &paramName)
static CBLSSecretKey ParseBLSSecretKey (const std::string &hexKey, const std::string &paramName)
void protx_list_help ()
static bool CheckWalletOwnsKey (CWallet *pwallet, const CKeyID &keyID)
static bool CheckWalletOwnsScript (CWallet *pwallet, const CScript &script)
UniValue BuildDMNListEntry (CWallet *pwallet, const CDeterministicMNCPtr &dmn, bool detailed)
UniValue protx_list (const JSONRPCRequest &request)
void protx_info_help ()
UniValue protx_info (const JSONRPCRequest &request)
void protx_diff_help ()
static uint256 ParseBlock (const UniValue &v, std::string strName)
UniValue protx_diff (const JSONRPCRequest &request)
void protx_help ()
UniValue protx (const JSONRPCRequest &request)
void bls_generate_help ()
UniValue bls_generate (const JSONRPCRequest &request)
void bls_fromsecret_help ()
UniValue bls_fromsecret (const JSONRPCRequest &request)
void bls_help ()
UniValue _bls (const JSONRPCRequest &request)
void RegisterEvoRPCCommands (CRPCTable &tableRPC)
Register Evo RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
_bls()
UniValue _bls (const JSONRPCRequest & request)
Definition at line 1280 of file rpcevo.cpp.
References bls_fromsecret(), bls_generate(), bls_help(), UniValue::empty(), JSONRPCRequest::fHelp, UniValue::get_str(), UniValue::isNull(), and JSONRPCRequest::params.
bls_fromsecret()
UniValue bls_fromsecret (const JSONRPCRequest & request)
Definition at line 1249 of file rpcevo.cpp.
References bls_fromsecret_help(), JSONRPCRequest::fHelp, UniValue::get_str(), CBLSSecretKey::GetPublicKey(), JSONRPCError(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_PARAMETER, CBLSWrapper< ImplType, _SerSize, C >::SerSize, CBLSWrapper< ImplType, _SerSize, C >::SetHexStr(), UniValue::size(), strprintf, CBLSWrapper< ImplType, _SerSize, C >::ToString(), and UniValue::VOBJ.
Referenced by _bls().
bls_fromsecret_help()
void bls_fromsecret_help ()
Definition at line 1232 of file rpcevo.cpp.
References HelpExampleCli().
Referenced by bls_fromsecret().
bls_generate()
UniValue bls_generate (const JSONRPCRequest & request)
Definition at line 1217 of file rpcevo.cpp.
References bls_generate_help(), JSONRPCRequest::fHelp, CBLSSecretKey::GetPublicKey(), CBLSSecretKey::MakeNewKey(), Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), and UniValue::VOBJ.
Referenced by _bls().
bls_generate_help()
void bls_generate_help ()
Definition at line 1202 of file rpcevo.cpp.
References HelpExampleCli().
Referenced by bls_generate().
bls_help()
void bls_help ()
Definition at line 1266 of file rpcevo.cpp.
Referenced by _bls().
BuildDMNListEntry()
UniValue BuildDMNListEntry (CWallet * pwallet, const CDeterministicMNCPtr & dmn, bool detailed)
Definition at line 933 of file rpcevo.cpp.
References CheckWalletOwnsKey(), CheckWalletOwnsScript(), CMasternodeMetaMan::GetMetaInfo(), GetTransaction(), GetUTXOConfirmations(), mmetaman, Pair(), Params(), UniValue::push_back(), and UniValue::VOBJ.
Referenced by protx_info(), and protx_list().
CheckWalletOwnsKey()
static bool CheckWalletOwnsKey (CWallet * pwallet, const CKeyID & keyID) static
Definition at line 904 of file rpcevo.cpp.
References CWallet::HaveKey().
Referenced by BuildDMNListEntry(), and protx_list().
CheckWalletOwnsScript()
static bool CheckWalletOwnsScript (CWallet * pwallet, const CScript & script) static
Definition at line 915 of file rpcevo.cpp.
References ExtractDestination(), CBasicKeyStore::HaveCScript(), and CWallet::HaveKey().
Referenced by BuildDMNListEntry(), and protx_list().
GetHelpString()
std::string GetHelpString (int nParamNum, std::string strParamName)
Definition at line 38 of file rpcevo.cpp.
References strprintf.
Referenced by protx_info_help().
ParseBlock()
static uint256 ParseBlock (const UniValue & v, std::string strName) static
Definition at line 1106 of file rpcevo.cpp.
References AssertLockHeld(), chainActive, cs_main, UniValue::getValStr(), CChain::Height(), ParseHashV(), ParseInt32V(), and strprintf.
Referenced by protx_diff().
ParseBLSPubKey()
static CBLSPublicKey ParseBLSPubKey (const std::string & hexKey, const std::string & paramName) static
Definition at line 159 of file rpcevo.cpp.
References JSONRPCError(), RPC_INVALID_PARAMETER, CBLSWrapper< ImplType, _SerSize, C >::SetHexStr(), and strprintf.
ParseBLSSecretKey()
static CBLSSecretKey ParseBLSSecretKey (const std::string & hexKey, const std::string & paramName) static
Definition at line 168 of file rpcevo.cpp.
References JSONRPCError(), RPC_INVALID_PARAMETER, CBLSWrapper< ImplType, _SerSize, C >::SetHexStr(), and strprintf.
ParsePrivKey()
static CKey ParsePrivKey (CWallet * pwallet, const std::string & strKeyOrAddress, bool allowAddresses = true) static
Definition at line 124 of file rpcevo.cpp.
References DecodeDestination(), EnsureWalletIsUnlocked(), CBitcoinSecret::GetKey(), CWallet::GetKey(), CBitcoinSecret::IsValid(), IsValidDestination(), CBitcoinSecret::SetString(), and strprintf.
ParsePubKeyIDFromAddress()
static CKeyID ParsePubKeyIDFromAddress (const std::string & strAddress, const std::string & paramName) static
Definition at line 149 of file rpcevo.cpp.
References DecodeDestination(), JSONRPCError(), RPC_INVALID_PARAMETER, and strprintf.
protx()
UniValue protx (const JSONRPCRequest & request)
Definition at line 1167 of file rpcevo.cpp.
References UniValue::empty(), JSONRPCRequest::fHelp, UniValue::get_str(), UniValue::isNull(), JSONRPCRequest::params, protx_diff(), protx_help(), protx_info(), and protx_list().
protx_diff()
UniValue protx_diff (const JSONRPCRequest & request)
Definition at line 1120 of file rpcevo.cpp.
References BuildSimplifiedMNListDiff(), cs_main, JSONRPCRequest::fHelp, LOCK, JSONRPCRequest::params, ParseBlock(), protx_diff_help(), UniValue::size(), and CSimplifiedMNListDiff::ToJson().
Referenced by protx().
protx_diff_help()
void protx_diff_help ()
Definition at line 1095 of file rpcevo.cpp.
Referenced by protx_diff().
protx_help()
void protx_help ()
Definition at line 1141 of file rpcevo.cpp.
Referenced by protx().
protx_info()
UniValue protx_info (const JSONRPCRequest & request)
Definition at line 1074 of file rpcevo.cpp.
References BuildDMNListEntry(), deterministicMNManager, JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), JSONRPCError(), JSONRPCRequest::params, ParseHashV(), protx_info_help(), RPC_INVALID_PARAMETER, UniValue::size(), strprintf, and base_blob< BITS >::ToString().
Referenced by protx().
protx_info_help()
void protx_info_help ()
Definition at line 1059 of file rpcevo.cpp.
References GetHelpString(), and HelpExampleCli().
Referenced by protx_info().
protx_list()
UniValue protx_list (const JSONRPCRequest & request)
Definition at line 976 of file rpcevo.cpp.
References BuildDMNListEntry(), chainActive, CheckWalletOwnsKey(), CheckWalletOwnsScript(), cs_main, CWallet::cs_wallet, deterministicMNManager, JSONRPCRequest::fHelp, CDeterministicMNList::ForEachMN(), UniValue::get_str(), GetWalletForJSONRPCRequest(), CChain::Height(), UniValue::isNull(), JSONRPCError(), CWallet::ListProTxCoins(), LOCK, LOCK2, JSONRPCRequest::params, ParseBoolV(), ParseInt32V(), protx_list_help(), UniValue::push_back(), RPC_INVALID_PARAMETER, UniValue::size(), and UniValue::VARR.
Referenced by protx().
protx_list_help()
void protx_list_help ()
Definition at line 885 of file rpcevo.cpp.
Referenced by protx_list().
RegisterEvoRPCCommands()
void RegisterEvoRPCCommands (CRPCTable & tableRPC)
Register Evo RPC commands.
Definition at line 1307 of file rpcevo.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, name, and tableRPC.
Referenced by RegisterAllCoreRPCCommands().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "evo",                "bls",                    &_bls,                   {}  },
    { "evo",                "protx",                  &protx,                  {}  },
}
Definition at line 1300 of file rpcevo.cpp.
Referenced by RegisterEvoRPCCommands().
Released under the MIT license