Dash Core: src/rpc/rpcquorums.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
rpcquorums.cpp File Reference
#include <chainparams.h>
#include <rpc/server.h>
#include <validation.h>
#include <masternode/activemasternode.h>
#include <llmq/quorums.h>
#include <llmq/quorums_blockprocessor.h>
#include <llmq/quorums_debug.h>
#include <llmq/quorums_dkgsession.h>
#include <llmq/quorums_signing.h>
#include <llmq/quorums_signing_shares.h>
Functions
void quorum_list_help ()
UniValue quorum_list (const JSONRPCRequest &request)
void quorum_info_help ()
UniValue BuildQuorumInfo (const llmq::CQuorumCPtr &quorum, bool includeMembers, bool includeSkShare)
UniValue quorum_info (const JSONRPCRequest &request)
void quorum_dkgstatus_help ()
UniValue quorum_dkgstatus (const JSONRPCRequest &request)
void quorum_memberof_help ()
UniValue quorum_memberof (const JSONRPCRequest &request)
void quorum_sign_help ()
void quorum_hasrecsig_help ()
void quorum_getrecsig_help ()
void quorum_isconflicting_help ()
UniValue quorum_sigs_cmd (const JSONRPCRequest &request)
void quorum_selectquorum_help ()
UniValue quorum_selectquorum (const JSONRPCRequest &request)
void quorum_dkgsimerror_help ()
UniValue quorum_dkgsimerror (const JSONRPCRequest &request)
void quorum_help ()
UniValue quorum (const JSONRPCRequest &request)
void RegisterQuorumsRPCCommands (CRPCTable &tableRPC)
Register Quorums RPC commands.
Variables
static const CRPCCommand commands []
Function Documentation
BuildQuorumInfo()
UniValue BuildQuorumInfo (const llmq::CQuorumCPtr & quorum, bool includeMembers, bool includeSkShare)
Definition at line 84 of file rpcquorums.cpp.
References CBLSWrapper< ImplType, _SerSize, C >::IsValid(), Pair(), UniValue::push_back(), quorum(), UniValue::size(), CBLSWrapper< ImplType, _SerSize, C >::ToString(), UniValue::VARR, and UniValue::VOBJ.
Referenced by quorum_info(), and quorum_memberof().
quorum()
UniValue quorum (const JSONRPCRequest & request)
Definition at line 492 of file rpcquorums.cpp.
References UniValue::empty(), JSONRPCRequest::fHelp, UniValue::get_str(), UniValue::isNull(), JSONRPCRequest::params, quorum_dkgsimerror(), quorum_dkgstatus(), quorum_help(), quorum_info(), quorum_list(), quorum_memberof(), quorum_selectquorum(), and quorum_sigs_cmd().
Referenced by llmq::CSigSharesManager::AsyncSign(), llmq::CSigningManager::AsyncSignIfMember(), llmq::CQuorumManager::BuildQuorumContributions(), llmq::CQuorumManager::BuildQuorumFromCommitment(), BuildQuorumInfo(), llmq::CSigSharesManager::Cleanup(), llmq::CSigningManager::CollectPendingRecoveredSigsToVerify(), llmq::CSigSharesManager::CollectPendingSigSharesToVerify(), llmq::CQuorumManager::EnsureQuorumConnections(), llmq::CSigSharesManager::ForceReAnnouncement(), llmq::CQuorumManager::GetQuorum(), llmq::CSigningManager::PreVerifyRecoveredSig(), llmq::CSigSharesManager::ProcessMessageSigSesAnn(), llmq::CSigSharesManager::ProcessMessageSigShare(), llmq::CInstantSendManager::ProcessPendingInstantSendLocks(), llmq::CSigningManager::ProcessPendingRecoveredSigs(), llmq::CSigSharesManager::ProcessPendingSigShares(), llmq::CSigSharesManager::ProcessSigShare(), llmq::CSigningManager::PushReconstructedRecoveredSig(), quorum_info(), quorum_memberof(), quorum_selectquorum(), quorum_sigs_cmd(), llmq::CQuorumManager::ScanQuorums(), llmq::CSigSharesManager::SelectMemberForRecovery(), llmq::CSigSharesManager::Sign(), llmq::CSigSharesManager::TryRecoverSig(), and llmq::CSigningManager::VerifyRecoveredSig().
quorum_dkgsimerror()
UniValue quorum_dkgsimerror (const JSONRPCRequest & request)
Definition at line 450 of file rpcquorums.cpp.
References JSONRPCRequest::fHelp, UniValue::get_str(), JSONRPCError(), JSONRPCRequest::params, ParseDoubleV(), quorum_dkgsimerror_help(), RPC_INVALID_PARAMETER, llmq::SetSimulatedDKGErrorRate(), and UniValue::size().
Referenced by quorum().
quorum_dkgsimerror_help()
void quorum_dkgsimerror_help ()
Definition at line 438 of file rpcquorums.cpp.
Referenced by quorum_dkgsimerror().
quorum_dkgstatus()
UniValue quorum_dkgstatus (const JSONRPCRequest & request)
Definition at line 160 of file rpcquorums.cpp.
References activeMasternodeInfo, CNode::addr, chainActive, cs_main, JSONRPCRequest::fHelp, fMasternodeMode, g_connman, llmq::CDKGDebugManager::GetLocalDebugStatus(), llmq::CLLMQUtils::GetQuorumConnections(), CChain::Height(), base_blob< BITS >::IsNull(), UniValue::isNull(), JSONRPCError(), LOCK, Pair(), JSONRPCRequest::params, Params(), ParseInt32V(), CActiveMasternodeInfo::proTxHash, UniValue::push_back(), quorum_dkgstatus_help(), llmq::quorumBlockProcessor, llmq::quorumDKGDebugManager, RPC_INVALID_PARAMETER, UniValue::size(), llmq::CDKGDebugStatus::ToJson(), llmq::CFinalCommitment::ToJson(), UniValue::VARR, CNode::verifiedProRegTxHash, and UniValue::VOBJ.
Referenced by quorum().
quorum_dkgstatus_help()
void quorum_dkgstatus_help ()
Definition at line 148 of file rpcquorums.cpp.
Referenced by quorum_dkgstatus().
quorum_getrecsig_help()
void quorum_getrecsig_help ()
Definition at line 313 of file rpcquorums.cpp.
Referenced by quorum_sigs_cmd().
quorum_hasrecsig_help()
void quorum_hasrecsig_help ()
Definition at line 301 of file rpcquorums.cpp.
Referenced by quorum_sigs_cmd().
quorum_help()
void quorum_help ()
Definition at line 470 of file rpcquorums.cpp.
Referenced by quorum().
quorum_info()
UniValue quorum_info (const JSONRPCRequest & request)
Definition at line 120 of file rpcquorums.cpp.
References BuildQuorumInfo(), cs_main, JSONRPCRequest::fHelp, CChainParams::GetConsensus(), llmq::CQuorumManager::GetQuorum(), UniValue::isNull(), JSONRPCError(), Consensus::Params::llmqs, LOCK, JSONRPCRequest::params, Params(), ParseBoolV(), ParseHashV(), ParseInt32V(), quorum(), quorum_info_help(), llmq::quorumManager, RPC_INVALID_PARAMETER, and UniValue::size().
Referenced by quorum().
quorum_info_help()
void quorum_info_help ()
Definition at line 72 of file rpcquorums.cpp.
Referenced by quorum_info().
quorum_isconflicting_help()
void quorum_isconflicting_help ()
Definition at line 325 of file rpcquorums.cpp.
Referenced by quorum_sigs_cmd().
quorum_list()
UniValue quorum_list (const JSONRPCRequest & request)
Definition at line 40 of file rpcquorums.cpp.
References chainActive, count, cs_main, JSONRPCRequest::fHelp, UniValue::isNull(), JSONRPCError(), LOCK, Pair(), JSONRPCRequest::params, Params(), ParseInt32V(), UniValue::push_back(), quorum_list_help(), llmq::quorumManager, RPC_INVALID_PARAMETER, llmq::CQuorumManager::ScanQuorums(), UniValue::size(), CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
Referenced by quorum().
quorum_list_help()
void quorum_list_help ()
Definition at line 18 of file rpcquorums.cpp.
References HelpExampleCli(), and HelpExampleRpc().
Referenced by quorum_list().
quorum_memberof()
UniValue quorum_memberof (const JSONRPCRequest & request)
Definition at line 239 of file rpcquorums.cpp.
References BuildQuorumInfo(), chainActive, count, cs_main, deterministicMNManager, JSONRPCRequest::fHelp, UniValue::isNull(), JSONRPCError(), LOCK, Pair(), JSONRPCRequest::params, Params(), ParseHashV(), ParseInt32V(), UniValue::push_back(), quorum(), quorum_memberof_help(), llmq::quorumManager, RPC_INVALID_PARAMETER, llmq::CQuorumManager::ScanQuorums(), UniValue::size(), CChain::Tip(), and UniValue::VARR.
Referenced by quorum().
quorum_memberof_help()
void quorum_memberof_help ()
Definition at line 227 of file rpcquorums.cpp.
Referenced by quorum_memberof().
quorum_selectquorum()
UniValue quorum_selectquorum (const JSONRPCRequest & request)
Definition at line 407 of file rpcquorums.cpp.
References JSONRPCRequest::fHelp, CChainParams::GetConsensus(), JSONRPCError(), Consensus::Params::llmqs, Pair(), JSONRPCRequest::params, Params(), ParseHashV(), ParseInt32V(), UniValue::push_back(), quorum(), quorum_selectquorum_help(), llmq::quorumSigningManager, llmq::quorumSigSharesManager, RPC_INVALID_PARAMETER, RPC_MISC_ERROR, llmq::CSigSharesManager::SelectMemberForRecovery(), llmq::CSigningManager::SelectQuorumForSigning(), UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
Referenced by quorum().
quorum_selectquorum_help()
void quorum_selectquorum_help ()
Definition at line 396 of file rpcquorums.cpp.
Referenced by quorum_selectquorum().
quorum_sign_help()
void quorum_sign_help ()
Definition at line 288 of file rpcquorums.cpp.
Referenced by quorum_sigs_cmd().
quorum_sigs_cmd()
UniValue quorum_sigs_cmd (const JSONRPCRequest & request)
Definition at line 337 of file rpcquorums.cpp.
References llmq::CSigSharesManager::AsyncSign(), llmq::CSigningManager::AsyncSignIfMember(), JSONRPCRequest::fHelp, UniValue::get_str(), CChainParams::GetConsensus(), llmq::CQuorumManager::GetQuorum(), llmq::CSigningManager::HasRecoveredSig(), llmq::CSigningManager::IsConflicting(), UniValue::isNull(), JSONRPCError(), Consensus::Params::llmqs, llmq::CRecoveredSig::msgHash, JSONRPCRequest::params, Params(), ParseHashV(), ParseInt32V(), quorum(), quorum_getrecsig_help(), quorum_hasrecsig_help(), quorum_isconflicting_help(), quorum_sign_help(), llmq::quorumManager, llmq::quorumSigningManager, llmq::quorumSigSharesManager, RPC_INVALID_PARAMETER, UniValue::size(), and llmq::CRecoveredSig::ToJson().
Referenced by quorum().
RegisterQuorumsRPCCommands()
void RegisterQuorumsRPCCommands (CRPCTable & tableRPC)
Register Quorums RPC commands.
Definition at line 528 of file rpcquorums.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, CRPCCommand::name, and tableRPC.
Referenced by RegisterAllCoreRPCCommands().
Variable Documentation
commands
const CRPCCommand commands[] static
Initial value:
=
{
    { "evo",                "quorum",                 &quorum,                 {}  },
}
Definition at line 522 of file rpcquorums.cpp.
Referenced by RegisterQuorumsRPCCommands().
Released under the MIT license