Dash Core: src/wallet/rpcwallet.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
rpcwallet.h File Reference
#include <string>
Functions
void RegisterWalletRPCCommands (CRPCTable &t)
CWallet * GetWalletForJSONRPCRequest (const JSONRPCRequest &request)
Figures out what wallet, if any, to use for a JSONRPCRequest.
std::string HelpRequiringPassphrase (CWallet *)
void EnsureWalletIsUnlocked (CWallet *)
bool EnsureWalletIsAvailable (CWallet *, bool avoidException)
Function Documentation
EnsureWalletIsAvailable()
bool EnsureWalletIsAvailable (CWallet * , bool avoidException)
Definition at line 66 of file rpcwallet.cpp.
References HasWallets(), JSONRPCError(), RPC_METHOD_NOT_FOUND, and RPC_WALLET_NOT_SPECIFIED.
Referenced by abandontransaction(), abortrescan(), addmultisigaddress(), backupwallet(), createmultisig(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), fundrawtransaction(), getaccount(), getaccountaddress(), getaddressesbyaccount(), getbalance(), getnewaddress(), getrawchangeaddress(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), getunconfirmedbalance(), getwalletinfo(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), listwallets(), lockunspent(), movecmd(), removeprunedfunds(), rescanblockchain(), resendwallettransactions(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), walletlock(), walletpassphrase(), and walletpassphrasechange().
EnsureWalletIsUnlocked()
void EnsureWalletIsUnlocked (CWallet *)
Definition at line 83 of file rpcwallet.cpp.
References CCryptoKeyStore::IsLocked(), JSONRPCError(), and RPC_WALLET_UNLOCK_NEEDED.
Referenced by dumphdinfo(), dumpprivkey(), dumpwallet(), importelectrumwallet(), importmulti(), importprivkey(), importwallet(), keypoolrefill(), ParsePrivKey(), sendfrom(), sendmany(), sendtoaddress(), signmessage(), and signrawtransaction().
GetWalletForJSONRPCRequest()
CWallet* GetWalletForJSONRPCRequest (const JSONRPCRequest & request)
Figures out what wallet, if any, to use for a JSONRPCRequest.
Parameters
[in] request JSONRPCRequest that wishes to access a wallet
Returns
nullptr if no wallet should be used, or a pointer to the CWallet
Definition at line 45 of file rpcwallet.cpp.
References JSONRPCRequest::fHelp, GetWallet(), GetWallets(), JSONRPCError(), RPC_WALLET_NOT_FOUND, JSONRPCRequest::URI, urlDecode(), and WALLET_ENDPOINT_BASE.
Referenced by abandontransaction(), abortrescan(), addmultisigaddress(), backupwallet(), createmultisig(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), fundrawtransaction(), getaccount(), getaccountaddress(), getaddressesbyaccount(), getbalance(), getnewaddress(), getprivatesendinfo(), getrawchangeaddress(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), getunconfirmedbalance(), getwalletinfo(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), movecmd(), protx_info(), protx_list(), removeprunedfunds(), rescanblockchain(), resendwallettransactions(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), signrawtransaction(), validateaddress(), walletlock(), walletpassphrase(), and walletpassphrasechange().
HelpRequiringPassphrase()
std::string HelpRequiringPassphrase (CWallet *)
Definition at line 59 of file rpcwallet.cpp.
References CCryptoKeyStore::IsCrypted().
Referenced by keypoolrefill(), sendfrom(), sendmany(), sendtoaddress(), signmessage(), and signrawtransaction().
RegisterWalletRPCCommands()
void RegisterWalletRPCCommands (CRPCTable & t)
Definition at line 3588 of file rpcwallet.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by WalletInit::RegisterRPC(), and WalletTestingSetup::WalletTestingSetup().
Released under the MIT license