Dash Core: src/wallet/rpcwallet.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
rpcwallet.cpp File Reference
#include <amount.h>
#include <base58.h>
#include <chain.h>
#include <consensus/validation.h>
#include <core_io.h>
#include <httpserver.h>
#include <keepass.h>
#include <net.h>
#include <policy/feerate.h>
#include <policy/fees.h>
#include <privatesend/privatesend-client.h>
#include <rpc/mining.h>
#include <rpc/safemode.h>
#include <rpc/server.h>
#include <rpc/util.h>
#include <timedata.h>
#include <txmempool.h>
#include <util.h>
#include <utilmoneystr.h>
#include <validation.h>
#include <wallet/coincontrol.h>
#include <wallet/wallet.h>
#include <wallet/walletdb.h>
#include <wallet/walletutil.h>
#include <init.h>
#include <llmq/quorums_chainlocks.h>
#include <llmq/quorums_instantsend.h>
#include <stdint.h>
#include <univalue.h>
#include <functional>
Classes
struct tallyitem
Functions
CWallet * GetWalletForJSONRPCRequest (const JSONRPCRequest &request)
Figures out what wallet, if any, to use for a JSONRPCRequest.
std::string HelpRequiringPassphrase (CWallet *const pwallet)
bool EnsureWalletIsAvailable (CWallet *const pwallet, bool avoidException)
void EnsureWalletIsUnlocked (CWallet *const pwallet)
void WalletTxToJSON (const CWalletTx &wtx, UniValue &entry)
std::string AccountFromValue (const UniValue &value)
UniValue getnewaddress (const JSONRPCRequest &request)
CTxDestination GetAccountDestination (CWallet *const pwallet, std::string strAccount, bool bForceNew=false)
UniValue getaccountaddress (const JSONRPCRequest &request)
UniValue getrawchangeaddress (const JSONRPCRequest &request)
UniValue setaccount (const JSONRPCRequest &request)
UniValue getaccount (const JSONRPCRequest &request)
UniValue getaddressesbyaccount (const JSONRPCRequest &request)
static void SendMoney (CWallet *const pwallet, const CTxDestination &address, CAmount nValue, bool fSubtractFeeFromAmount, CWalletTx &wtxNew, const CCoinControl &coin_control)
UniValue sendtoaddress (const JSONRPCRequest &request)
UniValue instantsendtoaddress (const JSONRPCRequest &request)
UniValue listaddressgroupings (const JSONRPCRequest &request)
UniValue listaddressbalances (const JSONRPCRequest &request)
UniValue signmessage (const JSONRPCRequest &request)
UniValue getreceivedbyaddress (const JSONRPCRequest &request)
UniValue getreceivedbyaccount (const JSONRPCRequest &request)
UniValue getbalance (const JSONRPCRequest &request)
UniValue getunconfirmedbalance (const JSONRPCRequest &request)
UniValue movecmd (const JSONRPCRequest &request)
UniValue sendfrom (const JSONRPCRequest &request)
UniValue sendmany (const JSONRPCRequest &request)
UniValue addmultisigaddress (const JSONRPCRequest &request)
UniValue ListReceived (CWallet *const pwallet, const UniValue &params, bool fByAccounts)
UniValue listreceivedbyaddress (const JSONRPCRequest &request)
UniValue listreceivedbyaccount (const JSONRPCRequest &request)
static void MaybePushAddress (UniValue &entry, const CTxDestination &dest)
void ListTransactions (CWallet *const pwallet, const CWalletTx &wtx, const std::string &strAccount, int nMinDepth, bool fLong, UniValue &ret, const isminefilter &filter)
List transactions based on the given criteria.
void AcentryToJSON (const CAccountingEntry &acentry, const std::string &strAccount, UniValue &ret)
UniValue listtransactions (const JSONRPCRequest &request)
UniValue listaccounts (const JSONRPCRequest &request)
UniValue listsinceblock (const JSONRPCRequest &request)
UniValue gettransaction (const JSONRPCRequest &request)
UniValue abandontransaction (const JSONRPCRequest &request)
UniValue backupwallet (const JSONRPCRequest &request)
UniValue keypoolrefill (const JSONRPCRequest &request)
static void LockWallet (CWallet *pWallet)
UniValue walletpassphrase (const JSONRPCRequest &request)
UniValue walletpassphrasechange (const JSONRPCRequest &request)
UniValue walletlock (const JSONRPCRequest &request)
UniValue encryptwallet (const JSONRPCRequest &request)
UniValue lockunspent (const JSONRPCRequest &request)
UniValue listlockunspent (const JSONRPCRequest &request)
UniValue settxfee (const JSONRPCRequest &request)
UniValue setprivatesendrounds (const JSONRPCRequest &request)
UniValue setprivatesendamount (const JSONRPCRequest &request)
UniValue getwalletinfo (const JSONRPCRequest &request)
UniValue listwallets (const JSONRPCRequest &request)
UniValue keepass (const JSONRPCRequest &request)
UniValue loadwallet (const JSONRPCRequest &request)
UniValue resendwallettransactions (const JSONRPCRequest &request)
UniValue listunspent (const JSONRPCRequest &request)
UniValue fundrawtransaction (const JSONRPCRequest &request)
UniValue rescanblockchain (const JSONRPCRequest &request)
UniValue abortrescan (const JSONRPCRequest &request)
UniValue dumpprivkey (const JSONRPCRequest &request)
UniValue importprivkey (const JSONRPCRequest &request)
UniValue importaddress (const JSONRPCRequest &request)
UniValue importpubkey (const JSONRPCRequest &request)
UniValue dumpwallet (const JSONRPCRequest &request)
UniValue importwallet (const JSONRPCRequest &request)
UniValue importprunedfunds (const JSONRPCRequest &request)
UniValue removeprunedfunds (const JSONRPCRequest &request)
UniValue importmulti (const JSONRPCRequest &request)
UniValue dumphdinfo (const JSONRPCRequest &request)
UniValue importelectrumwallet (const JSONRPCRequest &request)
void RegisterWalletRPCCommands (CRPCTable &t)
Variables
static const std::string WALLET_ENDPOINT_BASE = "/wallet/"
static const CRPCCommand commands []
Function Documentation
abandontransaction()
UniValue abandontransaction (const JSONRPCRequest & request)
Definition at line 2112 of file rpcwallet.cpp.
References CWallet::AbandonTransaction(), CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, CWallet::mapWallet, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, base_blob< BITS >::SetHex(), and UniValue::size().
abortrescan()
UniValue abortrescan (const JSONRPCRequest & request)
Definition at line 163 of file rpcdump.cpp.
References CWallet::AbortRescan(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CWallet::IsAbortingRescan(), CWallet::IsScanning(), NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, and UniValue::size().
AccountFromValue()
std::string AccountFromValue (const UniValue & value)
Definition at line 126 of file rpcwallet.cpp.
References UniValue::get_str(), JSONRPCError(), and RPC_WALLET_INVALID_ACCOUNT_NAME.
Referenced by addmultisigaddress(), getaccountaddress(), getaddressesbyaccount(), getnewaddress(), getreceivedbyaccount(), movecmd(), sendfrom(), sendmany(), and setaccount().
AcentryToJSON()
void AcentryToJSON (const CAccountingEntry & acentry, const std::string & strAccount, UniValue & ret)
Definition at line 1626 of file rpcwallet.cpp.
References CAccountingEntry::nCreditDebit, CAccountingEntry::nTime, Pair(), UniValue::push_back(), CAccountingEntry::strAccount, CAccountingEntry::strComment, CAccountingEntry::strOtherAccount, ValueFromAmount(), and UniValue::VOBJ.
Referenced by listtransactions().
addmultisigaddress()
UniValue addmultisigaddress (const JSONRPCRequest & request)
Definition at line 1208 of file rpcwallet.cpp.
References AccountFromValue(), CWallet::AddCScript(), AddrToPubKey(), prevector< N, T, Size, Diff >::begin(), CreateMultisigRedeemscript(), cs_main, CWallet::cs_wallet, EncodeDestination(), prevector< N, T, Size, Diff >::end(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_array(), UniValue::get_int(), UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HexStr(), HexToPubKey(), IsDeprecatedRPCEnabled(), IsHex(), UniValue::isNull(), LOCK2, NullUniValue, JSONRPCRequest::params, UniValue::push_back(), UniValue::pushKV(), CWallet::SetAddressBook(), UniValue::size(), and UniValue::VOBJ.
backupwallet()
UniValue backupwallet (const JSONRPCRequest & request)
Definition at line 2157 of file rpcwallet.cpp.
References CWallet::BackupWallet(), CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_WALLET_ERROR, and UniValue::size().
dumphdinfo()
UniValue dumphdinfo (const JSONRPCRequest & request)
Definition at line 773 of file rpcdump.cpp.
References CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, CWallet::GetDecryptedHDChain(), CCryptoKeyStore::GetHDChain(), CHDChain::GetMnemonic(), CHDChain::GetSeed(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, NullUniValue, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INTERNAL_ERROR, RPC_WALLET_ERROR, UniValue::size(), and UniValue::VOBJ.
dumpprivkey()
UniValue dumpprivkey (const JSONRPCRequest & request)
Definition at line 731 of file rpcdump.cpp.
References cs_main, CWallet::cs_wallet, DecodeDestination(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, UniValue::get_str(), CWallet::GetKey(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), IsValidDestination(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, RPC_WALLET_ERROR, UniValue::size(), and CBase58Data::ToString().
dumpwallet()
UniValue dumpwallet (const JSONRPCRequest & request)
Definition at line 817 of file rpcdump.cpp.
encryptwallet()
UniValue encryptwallet (const JSONRPCRequest & request)
Definition at line 2409 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, CWallet::EncryptWallet(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_WALLET_ENCRYPTION_FAILED, RPC_WALLET_WRONG_ENC_STATE, UniValue::size(), and StartShutdown().
EnsureWalletIsAvailable()
bool EnsureWalletIsAvailable (CWallet *const pwallet, bool avoidException)
Definition at line 66 of file rpcwallet.cpp.
References HasWallets(), JSONRPCError(), RPC_METHOD_NOT_FOUND, and RPC_WALLET_NOT_SPECIFIED.
Referenced by abandontransaction(), abortrescan(), addmultisigaddress(), backupwallet(), createmultisig(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), fundrawtransaction(), getaccount(), getaccountaddress(), getaddressesbyaccount(), getbalance(), getnewaddress(), getrawchangeaddress(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), getunconfirmedbalance(), getwalletinfo(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), listwallets(), lockunspent(), movecmd(), removeprunedfunds(), rescanblockchain(), resendwallettransactions(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), walletlock(), walletpassphrase(), and walletpassphrasechange().
EnsureWalletIsUnlocked()
void EnsureWalletIsUnlocked (CWallet *const pwallet)
Definition at line 83 of file rpcwallet.cpp.
References CCryptoKeyStore::IsLocked(), JSONRPCError(), and RPC_WALLET_UNLOCK_NEEDED.
Referenced by dumphdinfo(), dumpprivkey(), dumpwallet(), importelectrumwallet(), importmulti(), importprivkey(), importwallet(), keypoolrefill(), ParsePrivKey(), sendfrom(), sendmany(), sendtoaddress(), signmessage(), and signrawtransaction().
fundrawtransaction()
UniValue fundrawtransaction (const JSONRPCRequest & request)
Definition at line 3198 of file rpcwallet.cpp.
References AmountFromValue(), CWallet::BlockUntilSyncedToCurrentChain(), CURRENCY_UNIT, DecodeDestination(), DecodeHexTx(), CCoinControl::destChange, EncodeHexTx(), EnsureWalletIsAvailable(), UniValue::exists(), CCoinControl::fAllowWatchOnly, FeeModeFromString(), JSONRPCRequest::fHelp, CCoinControl::fOverrideFeeRate, CWallet::FundTransaction(), UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), UniValue::isNull(), IsValidDestination(), JSONRPCError(), CCoinControl::m_confirm_target, CCoinControl::m_fee_mode, CCoinControl::m_feerate, NullUniValue, ObserveSafeMode(), Pair(), JSONRPCRequest::params, ParseConfirmTarget(), UniValue::push_back(), RPC_DESERIALIZATION_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, RPCTypeCheck(), RPCTypeCheckObj(), UniValue::size(), strprintf, UniValue::type(), ValueFromAmount(), UniValue::VARR, UniValue::VBOOL, UniValue::VNUM, UniValue::VOBJ, CMutableTransaction::vout, and UniValue::VSTR.
getaccount()
UniValue getaccount (const JSONRPCRequest & request)
Definition at line 310 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, DecodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), IsValidDestination(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, NullUniValue, JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, and UniValue::size().
getaccountaddress()
UniValue getaccountaddress (const JSONRPCRequest & request)
Definition at line 190 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, EncodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetAccountDestination(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), LOCK2, NullUniValue, JSONRPCRequest::params, UniValue::size(), and UniValue::VSTR.
GetAccountDestination()
CTxDestination GetAccountDestination (CWallet *const pwallet, std::string strAccount, bool bForceNew = false)
Definition at line 180 of file rpcwallet.cpp.
References CWallet::GetAccountDestination(), JSONRPCError(), and RPC_WALLET_KEYPOOL_RAN_OUT.
Referenced by getaccountaddress(), and setaccount().
getaddressesbyaccount()
UniValue getaddressesbyaccount (const JSONRPCRequest & request)
Definition at line 346 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, EncodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), LOCK2, CWallet::mapAddressBook, NullUniValue, JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), and UniValue::VARR.
getbalance()
UniValue getbalance (const JSONRPCRequest & request)
Definition at line 824 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), CWallet::GetBalance(), CWallet::GetLegacyBalance(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, UniValue::isNull(), JSONRPCError(), LOCK2, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, RPC_INVALID_PARAMETER, UniValue::size(), and ValueFromAmount().
getnewaddress()
UniValue getnewaddress (const JSONRPCRequest & request)
Definition at line 134 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, EncodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CPubKey::GetID(), CWallet::GetKeyFromPool(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsLocked(), UniValue::isNull(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_WALLET_KEYPOOL_RAN_OUT, CWallet::SetAddressBook(), UniValue::size(), and CWallet::TopUpKeyPool().
Referenced by CreateTransactionTestSetup::GetRecipients().
getrawchangeaddress()
UniValue getrawchangeaddress (const JSONRPCRequest & request)
Definition at line 224 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EncodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CPubKey::GetID(), CReserveKey::GetReservedKey(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsLocked(), JSONRPCError(), CReserveKey::KeepKey(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_WALLET_KEYPOOL_RAN_OUT, UniValue::size(), and CWallet::TopUpKeyPool().
getreceivedbyaccount()
UniValue getreceivedbyaccount (const JSONRPCRequest & request)
Definition at line 757 of file rpcwallet.cpp.
References AccountFromValue(), CWallet::BlockUntilSyncedToCurrentChain(), CheckFinalTx(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), ExtractDestination(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), CWallet::GetAccountAddresses(), CMerkleTx::GetDepthInMainChain(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CMerkleTx::IsCoinBase(), CMerkleTx::IsLockedByInstantSend(), IsMine(), UniValue::isNull(), LOCK2, CWallet::mapWallet, NullUniValue, CTxOut::nValue, ObserveSafeMode(), JSONRPCRequest::params, CTxOut::scriptPubKey, UniValue::size(), CMerkleTx::tx, and ValueFromAmount().
getreceivedbyaddress()
UniValue getreceivedbyaddress (const JSONRPCRequest & request)
Definition at line 688 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), CheckFinalTx(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, DecodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), CMerkleTx::GetDepthInMainChain(), GetScriptForDestination(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CMerkleTx::IsCoinBase(), CMerkleTx::IsLockedByInstantSend(), IsMine(), UniValue::isNull(), IsValidDestination(), JSONRPCError(), LOCK2, CWallet::mapWallet, NullUniValue, CTxOut::nValue, ObserveSafeMode(), JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CTxOut::scriptPubKey, UniValue::size(), CMerkleTx::tx, and ValueFromAmount().
gettransaction()
UniValue gettransaction (const JSONRPCRequest & request)
Definition at line 2015 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EncodeHexTx(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_str(), CWalletTx::GetCredit(), CWalletTx::GetDebit(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CWalletTx::IsFromMe(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, UniValue::isNull(), JSONRPCError(), ListTransactions(), LOCK2, CWallet::mapWallet, NullUniValue, ObserveSafeMode(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, base_blob< BITS >::SetHex(), UniValue::size(), CMerkleTx::tx, ValueFromAmount(), UniValue::VARR, UniValue::VOBJ, and WalletTxToJSON().
getunconfirmedbalance()
UniValue getunconfirmedbalance (const JSONRPCRequest & request)
Definition at line 898 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CWallet::GetUnconfirmedBalance(), GetWalletForJSONRPCRequest(), LOCK2, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, UniValue::size(), and ValueFromAmount().
GetWalletForJSONRPCRequest()
CWallet* GetWalletForJSONRPCRequest (const JSONRPCRequest & request)
Figures out what wallet, if any, to use for a JSONRPCRequest.
Parameters
[in] request JSONRPCRequest that wishes to access a wallet
Returns
nullptr if no wallet should be used, or a pointer to the CWallet
Definition at line 45 of file rpcwallet.cpp.
References JSONRPCRequest::fHelp, GetWallet(), GetWallets(), JSONRPCError(), RPC_WALLET_NOT_FOUND, JSONRPCRequest::URI, urlDecode(), and WALLET_ENDPOINT_BASE.
Referenced by abandontransaction(), abortrescan(), addmultisigaddress(), backupwallet(), createmultisig(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), fundrawtransaction(), getaccount(), getaccountaddress(), getaddressesbyaccount(), getbalance(), getnewaddress(), getprivatesendinfo(), getrawchangeaddress(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), getunconfirmedbalance(), getwalletinfo(), importaddress(), importelectrumwallet(), importmulti(), importprivkey(), importprunedfunds(), importpubkey(), importwallet(), keepass(), keypoolrefill(), listaccounts(), listaddressbalances(), listaddressgroupings(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), movecmd(), protx_info(), protx_list(), removeprunedfunds(), rescanblockchain(), resendwallettransactions(), sendfrom(), sendmany(), sendtoaddress(), setaccount(), setprivatesendamount(), setprivatesendrounds(), settxfee(), signmessage(), signrawtransaction(), validateaddress(), walletlock(), walletpassphrase(), and walletpassphrasechange().
getwalletinfo()
UniValue getwalletinfo (const JSONRPCRequest & request)
Definition at line 2735 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), CHDChain::CountAccounts(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CHDChain::GetAccount(), CWallet::GetAnonymizedBalance(), CWallet::GetBalance(), CFeeRate::GetFeePerK(), CCryptoKeyStore::GetHDChain(), base_blob< BITS >::GetHex(), CHDChain::GetID(), CWallet::GetImmatureBalance(), CWallet::GetName(), CWallet::GetOldestKeyPoolTime(), CWallet::GetUnconfirmedBalance(), CWallet::GetVersion(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), CWallet::KeypoolCountExternalKeys(), CWallet::KeypoolCountInternalKeys(), LOCK2, CWallet::mapWallet, CHDAccount::nExternalChainCounter, CHDAccount::nInternalChainCounter, CWallet::nKeysLeftSinceAutoBackup, CWallet::nRelockTime, NullUniValue, ObserveSafeMode(), Pair(), JSONRPCRequest::params, payTxFee, UniValue::push_back(), UniValue::size(), strprintf, ValueFromAmount(), UniValue::VARR, and UniValue::VOBJ.
HelpRequiringPassphrase()
std::string HelpRequiringPassphrase (CWallet *const pwallet)
Definition at line 59 of file rpcwallet.cpp.
References CCryptoKeyStore::IsCrypted().
Referenced by keypoolrefill(), sendfrom(), sendmany(), sendtoaddress(), signmessage(), and signrawtransaction().
importaddress()
UniValue importaddress (const JSONRPCRequest & request)
Definition at line 224 of file rpcdump.cpp.
References cs_main, CWallet::cs_wallet, DecodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, fPruneMode, UniValue::get_bool(), UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), ImportAddress(), ImportScript(), IsHex(), UniValue::isNull(), IsValidDestination(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, ParseHex(), CWallet::ReacceptWalletTransactions(), CWallet::RescanFromTime(), WalletRescanReserver::reserve(), RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, UniValue::size(), and TIMESTAMP_MIN.
importelectrumwallet()
UniValue importelectrumwallet (const JSONRPCRequest & request)
Definition at line 593 of file rpcdump.cpp.
References _(), CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, EncodeDestination(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, fPruneMode, UniValue::get_int(), UniValue::get_str(), CPubKey::GetID(), CBitcoinSecret::GetKey(), UniValue::getKeys(), CKey::GetPubKey(), GetWalletForJSONRPCRequest(), CWallet::HaveKey(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), JSONRPCError(), LOCK2, LogPrintf, NullUniValue, JSONRPCRequest::params, UniValue::read(), RPC_INVALID_PARAMETER, RPC_TYPE_ERROR, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CBitcoinSecret::SetString(), CWallet::ShowProgress, UniValue::size(), CWallet::UpdateTimeFirstKey(), CKey::VerifyPubKey(), and UniValue::VOBJ.
importmulti()
UniValue importmulti (const JSONRPCRequest & request)
Definition at line 1306 of file rpcdump.cpp.
importprivkey()
UniValue importprivkey (const JSONRPCRequest & request)
Definition at line 74 of file rpcdump.cpp.
References CWallet::AddKeyPubKey(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, fPruneMode, UniValue::get_bool(), UniValue::get_str(), CPubKey::GetID(), CBitcoinSecret::GetKey(), CKey::GetPubKey(), GetWalletForJSONRPCRequest(), CWallet::HaveKey(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), CKey::IsValid(), JSONRPCError(), LOCK2, CWallet::mapKeyMetadata, CWallet::MarkDirty(), NullUniValue, JSONRPCRequest::params, CWallet::RescanFromTime(), WalletRescanReserver::reserve(), RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CWallet::SetAddressBook(), CBitcoinSecret::SetString(), UniValue::size(), TIMESTAMP_MIN, CWallet::UpdateTimeFirstKey(), and CKey::VerifyPubKey().
importprunedfunds()
UniValue importprunedfunds (const JSONRPCRequest & request)
Definition at line 302 of file rpcdump.cpp.
References CWallet::AddToWallet(), chainActive, CChain::Contains(), cs_main, CWallet::cs_wallet, DecodeHexTx(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), CMutableTransaction::GetHash(), GetWalletForJSONRPCRequest(), CMerkleTx::hashBlock, CWallet::IsMine(), JSONRPCError(), LOCK, LOCK2, MakeTransactionRef(), mapBlockIndex, CMerkleTx::nIndex, NullUniValue, JSONRPCRequest::params, ParseHexV(), PROTOCOL_VERSION, RPC_DESERIALIZATION_ERROR, RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, UniValue::size(), and CMerkleTx::tx.
importpubkey()
UniValue importpubkey (const JSONRPCRequest & request)
Definition at line 401 of file rpcdump.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, fPruneMode, UniValue::get_bool(), UniValue::get_str(), GetScriptForRawPubKey(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), ImportAddress(), ImportScript(), IsHex(), UniValue::isNull(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, ParseHex(), CWallet::ReacceptWalletTransactions(), CWallet::RescanFromTime(), WalletRescanReserver::reserve(), RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, UniValue::size(), and TIMESTAMP_MIN.
importwallet()
UniValue importwallet (const JSONRPCRequest & request)
Definition at line 468 of file rpcdump.cpp.
instantsendtoaddress()
UniValue instantsendtoaddress (const JSONRPCRequest & request)
Definition at line 517 of file rpcwallet.cpp.
References JSONRPCRequest::fHelp, LogPrintf, and sendtoaddress().
keepass()
UniValue keepass (const JSONRPCRequest & request)
Definition at line 2859 of file rpcwallet.cpp.
References EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CKeePassIntegrator::generateKeePassKey(), UniValue::get_str(), GetWalletForJSONRPCRequest(), UniValue::isNull(), keePassInt, NullUniValue, JSONRPCRequest::params, CKeePassIntegrator::rpcAssociate(), UniValue::size(), and CKeePassIntegrator::updatePassphrase().
keypoolrefill()
UniValue keypoolrefill (const JSONRPCRequest & request)
Definition at line 2190 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, DEFAULT_KEYPOOL_SIZE, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, UniValue::get_int(), CWallet::GetKeyPoolSize(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), CWallet::IsHDEnabled(), UniValue::isNull(), itostr(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, UniValue::size(), and CWallet::TopUpKeyPool().
listaccounts()
UniValue listaccounts (const JSONRPCRequest & request)
Definition at line 1780 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), CWalletTx::GetAmounts(), CMerkleTx::GetBlocksToMaturity(), CMerkleTx::GetDepthInMainChain(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CMerkleTx::IsLockedByInstantSend(), IsMine(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, UniValue::isNull(), CWallet::laccentries, LOCK2, CWallet::mapAddressBook, CWallet::mapWallet, NullUniValue, ObserveSafeMode(), Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), ValueFromAmount(), and UniValue::VOBJ.
listaddressbalances()
UniValue listaddressbalances (const JSONRPCRequest & request)
Definition at line 585 of file rpcwallet.cpp.
References AmountFromValue(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EncodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CWallet::GetAddressBalances(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), JSONRPCError(), LOCK2, NullUniValue, Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_TYPE_ERROR, UniValue::size(), ValueFromAmount(), and UniValue::VOBJ.
listaddressgroupings()
UniValue listaddressgroupings (const JSONRPCRequest & request)
Definition at line 526 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EncodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), LOCK2, CWallet::mapAddressBook, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), ValueFromAmount(), and UniValue::VARR.
listlockunspent()
UniValue listlockunspent (const JSONRPCRequest & request)
Definition at line 2598 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CWallet::ListLockedCoins(), LOCK2, NullUniValue, ObserveSafeMode(), Pair(), JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
ListReceived()
UniValue ListReceived (CWallet *const pwallet, const UniValue & params, bool fByAccounts)
Definition at line 1303 of file rpcwallet.cpp.
References CheckFinalTx(), EncodeDestination(), ExtractDestination(), tallyitem::fIsWatchonly, UniValue::get_bool(), UniValue::get_int(), CMerkleTx::GetDepthInMainChain(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), CMerkleTx::IsCoinBase(), CMerkleTx::IsLockedByInstantSend(), IsMine(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, CWallet::mapAddressBook, CWallet::mapWallet, tallyitem::nAmount, tallyitem::nConf, CTxOut::nValue, Pair(), UniValue::push_back(), CTxOut::scriptPubKey, CMerkleTx::tx, tallyitem::txids, ValueFromAmount(), UniValue::VARR, and UniValue::VOBJ.
Referenced by listreceivedbyaccount(), and listreceivedbyaddress().
listreceivedbyaccount()
UniValue listreceivedbyaccount (const JSONRPCRequest & request)
Definition at line 1481 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), ListReceived(), LOCK2, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, and UniValue::size().
listreceivedbyaddress()
UniValue listreceivedbyaddress (const JSONRPCRequest & request)
Definition at line 1428 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), ListReceived(), LOCK2, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, and UniValue::size().
listsinceblock()
UniValue listsinceblock (const JSONRPCRequest & request)
Definition at line 1872 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), chainActive, cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, CChain::FindFork(), UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), CBlockIndex::GetBlockHash(), CMerkleTx::GetDepthInMainChain(), base_blob< BITS >::GetHex(), GetWalletForJSONRPCRequest(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, UniValue::isNull(), JSONRPCError(), ListTransactions(), LOCK2, mapBlockIndex, CWallet::mapWallet, CBlockIndex::nHeight, NullUniValue, ObserveSafeMode(), Pair(), JSONRPCRequest::params, Params(), CBlockIndex::pprev, UniValue::push_back(), ReadBlockFromDisk(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, base_blob< BITS >::SetHex(), UniValue::size(), UniValue::VARR, UniValue::VOBJ, and CBlock::vtx.
ListTransactions()
void ListTransactions (CWallet *const pwallet, const CWalletTx & wtx, const std::string & strAccount, int nMinDepth, bool fLong, UniValue & ret, const isminefilter & filter)
List transactions based on the given criteria.
Parameters
pwallet The wallet.
wtx The wallet transaction.
strAccount The account, if any, or "*" for all.
nMinDepth The minimum confirmation depth.
fLong Whether to include the JSON version of the transaction.
ret The UniValue into which the result is stored.
filter The "is mine" filter bool.
Definition at line 1545 of file rpcwallet.cpp.
References CWalletTx::GetAmounts(), CMerkleTx::GetBlocksToMaturity(), CMerkleTx::GetDepthInMainChain(), CMerkleTx::isAbandoned(), CMerkleTx::IsCoinBase(), CWalletTx::IsFromMe(), CMerkleTx::IsLockedByInstantSend(), IsMine(), ISMINE_WATCH_ONLY, CWallet::mapAddressBook, CWalletTx::mapValue, MaybePushAddress(), Pair(), UniValue::push_back(), ValueFromAmount(), UniValue::VOBJ, and WalletTxToJSON().
Referenced by gettransaction(), listsinceblock(), and listtransactions().
listtransactions()
UniValue listtransactions (const JSONRPCRequest & request)
Definition at line 1643 of file rpcwallet.cpp.
References AcentryToJSON(), CWallet::BlockUntilSyncedToCurrentChain(), UniValue::clear(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), UniValue::getValues(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, UniValue::isNull(), JSONRPCError(), ListTransactions(), LOCK2, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, UniValue::push_backV(), RPC_INVALID_PARAMETER, UniValue::setArray(), UniValue::size(), UniValue::VARR, and CWallet::wtxOrdered.
listunspent()
UniValue listunspent (const JSONRPCRequest & request)
Definition at line 3002 of file rpcwallet.cpp.
References ALL_COINS, AmountFromValue(), CWallet::AvailableCoins(), prevector< N, T, Size, Diff >::begin(), CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, DecodeDestination(), EncodeDestination(), prevector< N, T, Size, Diff >::end(), EnsureWalletIsAvailable(), UniValue::exists(), ExtractDestination(), JSONRPCRequest::fHelp, UniValue::get_array(), UniValue::get_bool(), UniValue::get_int(), UniValue::get_int64(), UniValue::get_obj(), UniValue::get_str(), CBasicKeyStore::GetCScript(), UniValue::getKeys(), CWallet::GetRealOutpointPrivateSendRounds(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HexStr(), UniValue::isNull(), CScript::IsPayToScriptHash(), IsValidDestination(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, MAX_COIN_TYPE, MAX_MONEY, MIN_COIN_TYPE, CCoinControl::nCoinType, NullUniValue, ObserveSafeMode(), Pair(), JSONRPCRequest::params, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPCTypeCheckArgument(), UniValue::size(), strprintf, ValueFromAmount(), UniValue::VARR, UniValue::VBOOL, UniValue::VNUM, and UniValue::VOBJ.
listwallets()
UniValue listwallets (const JSONRPCRequest & request)
Definition at line 2827 of file rpcwallet.cpp.
References EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWallets(), HelpExampleCli(), HelpExampleRpc(), LOCK, NullUniValue, JSONRPCRequest::params, UniValue::push_back(), UniValue::size(), and UniValue::VARR.
loadwallet()
UniValue loadwallet (const JSONRPCRequest & request)
Definition at line 2913 of file rpcwallet.cpp.
References AddWallet(), CWallet::CreateWalletFromFile(), error(), JSONRPCRequest::fHelp, UniValue::get_str(), CWallet::GetName(), GetWalletDir(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), JSONRPCRequest::params, CWallet::postInitProcess(), UniValue::pushKV(), RPC_WALLET_ERROR, RPC_WALLET_NOT_FOUND, UniValue::size(), CWallet::Verify(), and UniValue::VOBJ.
lockunspent()
UniValue lockunspent (const JSONRPCRequest & request)
Definition at line 2471 of file rpcwallet.cpp.
References CWallet::BlockUntilSyncedToCurrentChain(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, find_value(), UniValue::get_bool(), UniValue::get_int(), UniValue::get_obj(), UniValue::get_str(), GetWalletForJSONRPCRequest(), COutPoint::hash, HelpExampleCli(), HelpExampleRpc(), IsHex(), CWallet::IsLockedCoin(), UniValue::isNull(), CWallet::IsSpent(), JSONRPCError(), LOCK2, CWallet::LockCoin(), CWallet::mapWallet, COutPoint::n, NullUniValue, JSONRPCRequest::params, RPC_INVALID_PARAMETER, RPCTypeCheckArgument(), RPCTypeCheckObj(), UniValue::size(), CMerkleTx::tx, uint256S(), CWallet::UnlockAllCoins(), CWallet::UnlockCoin(), UniValue::VARR, UniValue::VBOOL, UniValue::VNUM, and UniValue::VSTR.
LockWallet()
static void LockWallet (CWallet * pWallet) static
Definition at line 2230 of file rpcwallet.cpp.
References CWallet::cs_wallet, CCryptoKeyStore::Lock(), LOCK, and CWallet::nRelockTime.
Referenced by walletpassphrase().
MaybePushAddress()
static void MaybePushAddress (UniValue & entry, const CTxDestination & dest) static
Definition at line 1527 of file rpcwallet.cpp.
References EncodeDestination(), IsValidDestination(), Pair(), and UniValue::push_back().
Referenced by ListTransactions().
movecmd()
UniValue movecmd (const JSONRPCRequest & request)
Definition at line 922 of file rpcwallet.cpp.
References AccountFromValue(), CWallet::AccountMove(), AmountFromValue(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_int(), UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), JSONRPCError(), LOCK2, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, RPC_DATABASE_ERROR, RPC_TYPE_ERROR, and UniValue::size().
RegisterWalletRPCCommands()
void RegisterWalletRPCCommands (CRPCTable & t)
Definition at line 3588 of file rpcwallet.cpp.
References CRPCTable::appendCommand(), ARRAYLEN, commands, and CRPCCommand::name.
Referenced by WalletInit::RegisterRPC(), and WalletTestingSetup::WalletTestingSetup().
removeprunedfunds()
UniValue removeprunedfunds (const JSONRPCRequest & request)
Definition at line 363 of file rpcdump.cpp.
References cs_main, CWallet::cs_wallet, DB_LOAD_OK, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, base_blob< BITS >::SetHex(), UniValue::size(), and CWallet::ZapSelectTx().
rescanblockchain()
UniValue rescanblockchain (const JSONRPCRequest & request)
Definition at line 3422 of file rpcwallet.cpp.
References BLOCK_HAVE_DATA, chainActive, cs_main, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, fPruneMode, CChain::Genesis(), UniValue::get_int(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CWallet::IsAbortingRescan(), UniValue::isNull(), JSONRPCError(), LOCK, CBlockIndex::nHeight, CBlockIndex::nStatus, NullUniValue, JSONRPCRequest::params, CBlockIndex::pprev, UniValue::pushKV(), WalletRescanReserver::reserve(), RPC_INVALID_PARAMETER, RPC_MISC_ERROR, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), UniValue::size(), CChain::Tip(), and UniValue::VOBJ.
resendwallettransactions()
UniValue resendwallettransactions (const JSONRPCRequest & request)
Definition at line 2966 of file rpcwallet.cpp.
References CTxMemPool::cs, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, g_connman, CWallet::GetBroadcastTransactions(), GetTime(), GetWalletForJSONRPCRequest(), JSONRPCError(), LOCK, LOCK2, mempool, NullUniValue, JSONRPCRequest::params, UniValue::push_back(), CWallet::ResendWalletTransactionsBefore(), RPC_CLIENT_P2P_DISABLED, RPC_WALLET_ERROR, UniValue::size(), and UniValue::VARR.
sendfrom()
UniValue sendfrom (const JSONRPCRequest & request)
Definition at line 973 of file rpcwallet.cpp.
References AccountFromValue(), AmountFromValue(), CWallet::BlockUntilSyncedToCurrentChain(), CTxMemPool::cs, cs_main, CWallet::cs_wallet, CURRENCY_UNIT, DecodeDestination(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int(), UniValue::get_str(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), CWallet::GetLegacyBalance(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), ISMINE_SPENDABLE, UniValue::isNull(), IsValidDestination(), JSONRPCError(), LOCK, LOCK2, CWalletTx::mapValue, mempool, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, RPC_WALLET_INSUFFICIENT_FUNDS, SendMoney(), UniValue::size(), and CWalletTx::strFromAccount.
sendmany()
UniValue sendmany (const JSONRPCRequest & request)
Definition at line 1053 of file rpcwallet.cpp.
References AccountFromValue(), AmountFromValue(), CWallet::BlockUntilSyncedToCurrentChain(), CWallet::CommitTransaction(), CWallet::CreateTransaction(), CTxMemPool::cs, cs_main, CWallet::cs_wallet, CURRENCY_UNIT, DecodeDestination(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), FeeModeFromString(), JSONRPCRequest::fHelp, g_connman, UniValue::get_array(), UniValue::get_bool(), UniValue::get_int(), UniValue::get_obj(), UniValue::get_str(), CWallet::GetBroadcastTransactions(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), UniValue::getKeys(), CWallet::GetLegacyBalance(), CValidationState::GetRejectReason(), GetScriptForDestination(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), ISMINE_SPENDABLE, UniValue::isNull(), IsValidDestination(), JSONRPCError(), LOCK, LOCK2, CCoinControl::m_confirm_target, CCoinControl::m_fee_mode, CWalletTx::mapValue, mempool, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, ParseConfirmTarget(), prevector< N, T, Size, Diff >::push_back(), RPC_CLIENT_P2P_DISABLED, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPC_TYPE_ERROR, RPC_WALLET_ERROR, RPC_WALLET_INSUFFICIENT_FUNDS, UniValue::size(), CWalletTx::strFromAccount, strprintf, CCoinControl::UsePrivateSend(), and UniValue::VARR.
SendMoney()
static void SendMoney (CWallet *const pwallet, const CTxDestination & address, CAmount nValue, bool fSubtractFeeFromAmount, CWalletTx & wtxNew, const CCoinControl & coin_control) static
Definition at line 385 of file rpcwallet.cpp.
References CWallet::CommitTransaction(), CWallet::CreateTransaction(), FormatMoney(), g_connman, CWallet::GetBalance(), CWallet::GetBroadcastTransactions(), CValidationState::GetRejectReason(), GetScriptForDestination(), JSONRPCError(), prevector< N, T, Size, Diff >::push_back(), RPC_CLIENT_P2P_DISABLED, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, RPC_WALLET_INSUFFICIENT_FUNDS, and strprintf.
Referenced by sendfrom(), and sendtoaddress().
sendtoaddress()
UniValue sendtoaddress (const JSONRPCRequest & request)
Definition at line 424 of file rpcwallet.cpp.
References AmountFromValue(), CWallet::BlockUntilSyncedToCurrentChain(), CTxMemPool::cs, cs_main, CWallet::cs_wallet, CURRENCY_UNIT, DecodeDestination(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), FeeModeFromString(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_str(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), UniValue::isNull(), IsValidDestination(), JSONRPCError(), LOCK, LOCK2, CCoinControl::m_confirm_target, CCoinControl::m_fee_mode, CWalletTx::mapValue, mempool, NullUniValue, ObserveSafeMode(), JSONRPCRequest::params, ParseConfirmTarget(), RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPC_TYPE_ERROR, SendMoney(), UniValue::size(), and CCoinControl::UsePrivateSend().
Referenced by instantsendtoaddress().
setaccount()
UniValue setaccount (const JSONRPCRequest & request)
Definition at line 262 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, DecodeDestination(), EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), GetAccountDestination(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), IsMine(), UniValue::isNull(), IsValidDestination(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, NullUniValue, JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, RPC_MISC_ERROR, CWallet::SetAddressBook(), and UniValue::size().
setprivatesendamount()
UniValue setprivatesendamount (const JSONRPCRequest & request)
Definition at line 2707 of file rpcwallet.cpp.
References CURRENCY_UNIT, DEFAULT_PRIVATESEND_AMOUNT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_int(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), MAX_PRIVATESEND_AMOUNT, MIN_PRIVATESEND_AMOUNT, CPrivateSendClientManager::nPrivateSendAmount, NullUniValue, JSONRPCRequest::params, privateSendClient, RPC_INVALID_PARAMETER, and UniValue::size().
setprivatesendrounds()
UniValue setprivatesendrounds (const JSONRPCRequest & request)
Definition at line 2679 of file rpcwallet.cpp.
References DEFAULT_PRIVATESEND_ROUNDS, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_int(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), MAX_PRIVATESEND_ROUNDS, MIN_PRIVATESEND_ROUNDS, CPrivateSendClientManager::nPrivateSendRounds, NullUniValue, JSONRPCRequest::params, privateSendClient, RPC_INVALID_PARAMETER, and UniValue::size().
settxfee()
UniValue settxfee (const JSONRPCRequest & request)
Definition at line 2650 of file rpcwallet.cpp.
References AmountFromValue(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), LOCK2, NullUniValue, JSONRPCRequest::params, payTxFee, and UniValue::size().
signmessage()
UniValue signmessage (const JSONRPCRequest & request)
Definition at line 627 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, DecodeDestination(), EncodeBase64(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), JSONRPCRequest::fHelp, UniValue::get_str(), CHashWriter::GetHash(), CWallet::GetKey(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), IsValidDestination(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, RPC_WALLET_ERROR, SER_GETHASH, CKey::SignCompact(), UniValue::size(), and strMessageMagic.
walletlock()
UniValue walletlock (const JSONRPCRequest & request)
Definition at line 2369 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), JSONRPCError(), CCryptoKeyStore::Lock(), LOCK2, CWallet::nRelockTime, NullUniValue, JSONRPCRequest::params, RPC_WALLET_WRONG_ENC_STATE, and UniValue::size().
walletpassphrase()
UniValue walletpassphrase (const JSONRPCRequest & request)
Definition at line 2237 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_bool(), UniValue::get_int64(), UniValue::get_str(), CWallet::GetName(), GetTime(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), CCryptoKeyStore::IsLocked(), UniValue::isNull(), JSONRPCError(), LOCK2, LockWallet(), CWallet::nRelockTime, NullUniValue, JSONRPCRequest::params, RPC_INVALID_PARAMETER, RPC_WALLET_ALREADY_UNLOCKED, RPC_WALLET_PASSPHRASE_INCORRECT, RPC_WALLET_WRONG_ENC_STATE, RPCRunLater(), UniValue::size(), strprintf, CWallet::TopUpKeyPool(), and CWallet::Unlock().
walletpassphrasechange()
UniValue walletpassphrasechange (const JSONRPCRequest & request)
Definition at line 2318 of file rpcwallet.cpp.
References CWallet::ChangeWalletPassphrase(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), JSONRPCRequest::fHelp, UniValue::get_str(), GetWalletForJSONRPCRequest(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), JSONRPCError(), LOCK2, NullUniValue, JSONRPCRequest::params, RPC_WALLET_PASSPHRASE_INCORRECT, RPC_WALLET_WRONG_ENC_STATE, and UniValue::size().
WalletTxToJSON()
void WalletTxToJSON (const CWalletTx & wtx, UniValue & entry)
Definition at line 90 of file rpcwallet.cpp.
References AssertLockHeld(), llmq::chainLocksHandler, cs_main, CWalletTx::GetConflicts(), CMerkleTx::GetDepthInMainChain(), CMerkleTx::GetHash(), base_blob< BITS >::GetHex(), CWalletTx::GetTxTime(), llmq::CChainLocksHandler::HasChainLock(), CMerkleTx::hashBlock, CMerkleTx::IsCoinBase(), llmq::CInstantSendManager::IsLocked(), CWalletTx::IsTrusted(), mapBlockIndex, CWalletTx::mapValue, CMerkleTx::nIndex, CWalletTx::nTimeReceived, Pair(), UniValue::push_back(), llmq::quorumInstantSendManager, and UniValue::VARR.
Referenced by gettransaction(), and ListTransactions().
Variable Documentation
commands
const CRPCCommand commands[] static
Definition at line 3522 of file rpcwallet.cpp.
Referenced by RegisterWalletRPCCommands().
WALLET_ENDPOINT_BASE
const std::string WALLET_ENDPOINT_BASE = "/wallet/" static
Definition at line 43 of file rpcwallet.cpp.
Referenced by GetWalletForJSONRPCRequest().
Released under the MIT license