Dash Core: src/rpc/safemode.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
safemode.cpp File Reference
#include <rpc/safemode.h>
#include <rpc/protocol.h>
#include <util.h>
#include <warnings.h>
Functions
void ObserveSafeMode ()
Function Documentation
ObserveSafeMode()
void ObserveSafeMode ()
Definition at line 7 of file safemode.cpp.
References DEFAULT_DISABLE_SAFEMODE, gArgs, ArgsManager::GetBoolArg(), GetWarnings(), JSONRPCError(), and RPC_FORBIDDEN_BY_SAFE_MODE.
Referenced by abandontransaction(), abortrescan(), fundrawtransaction(), getbalance(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), getunconfirmedbalance(), getwalletinfo(), listaccounts(), listaddressgroupings(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), movecmd(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), and signrawtransaction().
Released under the MIT license