Dash Core: src/secp256k1/src/scalar_impl.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
scalar_impl.h File Reference
#include "group.h"
#include "scalar.h"
Functions
static void secp256k1_scalar_get_num (secp256k1_num *r, const secp256k1_scalar *a)
static void secp256k1_scalar_order_get_num (secp256k1_num *r)
secp256k1 curve order, see secp256k1_ecdsa_const_order_as_fe in ecdsa_impl.h
static void secp256k1_scalar_inverse (secp256k1_scalar *r, const secp256k1_scalar *x)
static SECP256K1_INLINE int secp256k1_scalar_is_even (const secp256k1_scalar *a)
static void secp256k1_scalar_inverse_var (secp256k1_scalar *r, const secp256k1_scalar *x)
Function Documentation
secp256k1_scalar_get_num()
static void secp256k1_scalar_get_num (secp256k1_num * r, const secp256k1_scalar * a) static
Definition at line 28 of file scalar_impl.h.
References secp256k1_num_set_bin(), and secp256k1_scalar_get_b32().
secp256k1_scalar_inverse()
static void secp256k1_scalar_inverse (secp256k1_scalar * r, const secp256k1_scalar * x) static
Definition at line 55 of file scalar_impl.h.
References EXHAUSTIVE_TEST_ORDER, and VERIFY_CHECK.
Referenced by secp256k1_scalar_inverse_var().
secp256k1_scalar_inverse_var()
static void secp256k1_scalar_inverse_var (secp256k1_scalar * r, const secp256k1_scalar * x) static
Definition at line 225 of file scalar_impl.h.
References CHECK, secp256k1_num_get_bin(), secp256k1_num_mod_inverse(), secp256k1_num_set_bin(), secp256k1_scalar_get_b32(), secp256k1_scalar_inverse(), secp256k1_scalar_is_one(), secp256k1_scalar_mul(), secp256k1_scalar_order_get_num(), and secp256k1_scalar_set_b32().
secp256k1_scalar_is_even()
static SECP256K1_INLINE int secp256k1_scalar_is_even (const secp256k1_scalar * a) static
Definition at line 220 of file scalar_impl.h.
References secp256k1_scalar::d.
secp256k1_scalar_order_get_num()
static void secp256k1_scalar_order_get_num (secp256k1_num * r) static
secp256k1 curve order, see secp256k1_ecdsa_const_order_as_fe in ecdsa_impl.h
Definition at line 35 of file scalar_impl.h.
References EXHAUSTIVE_TEST_ORDER, and secp256k1_num_set_bin().
Referenced by secp256k1_scalar_inverse_var().
Released under the MIT license