Dash Core: src/scheduler.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
scheduler.cpp File Reference
#include "scheduler.h"
#include "reverselock.h"
#include <assert.h>
#include <boost/bind.hpp>
#include <utility>
Functions
static boost::system_time toPosixTime (const boost::chrono::system_clock::time_point &t)
static void Repeat (CScheduler *s, CScheduler::Function f, int64_t deltaSeconds)
Function Documentation
Repeat()
static void Repeat (CScheduler * s, CScheduler::Function f, int64_t deltaSeconds) static
Definition at line 111 of file scheduler.cpp.
References CScheduler::scheduleFromNow().
Referenced by CScheduler::scheduleEvery().
toPosixTime()
static boost::system_time toPosixTime (const boost::chrono::system_clock::time_point & t) static
Definition at line 24 of file scheduler.cpp.
Referenced by CScheduler::serviceQueue().
Released under the MIT license