Dash Core: src/secp256k1/src/modules/schnorr/tests_impl.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
tests_impl.h File Reference
#include "include/secp256k1_schnorr.h"
Functions
void test_schnorr_end_to_end (void)
void test_schnorr_hash (unsigned char *h32, const unsigned char *r32, const unsigned char *msg32)
Horribly broken hash function.
void test_schnorr_sign_verify (void)
void test_schnorr_threshold (void)
void test_schnorr_recovery (void)
void run_schnorr_tests (void)
Function Documentation
run_schnorr_tests()
void run_schnorr_tests (void)
Definition at line 159 of file tests_impl.h.
References count, test_schnorr_end_to_end(), test_schnorr_recovery(), test_schnorr_sign_verify(), and test_schnorr_threshold().
Referenced by main().
test_schnorr_end_to_end()
void test_schnorr_end_to_end (void)
Definition at line 12 of file tests_impl.h.
References CHECK, ctx, random_scalar_order_test(), secp256k1_ec_pubkey_create(), secp256k1_ec_seckey_verify(), secp256k1_rand256_test(), secp256k1_rand_bits(), secp256k1_rand_int(), secp256k1_scalar_get_b32(), secp256k1_schnorr_recover(), secp256k1_schnorr_sign(), and secp256k1_schnorr_verify().
Referenced by run_schnorr_tests().
test_schnorr_hash()
void test_schnorr_hash (unsigned char * h32, const unsigned char * r32, const unsigned char * msg32)
Horribly broken hash function.
Do not use for anything but tests.
Definition at line 43 of file tests_impl.h.
Referenced by test_schnorr_recovery(), and test_schnorr_sign_verify().
test_schnorr_recovery()
void test_schnorr_recovery (void)
Definition at line 146 of file tests_impl.h.
References CHECK, ctx, secp256k1_context_struct::ecmult_ctx, secp256k1_rand256_test(), secp256k1_schnorr_sig_recover(), secp256k1_schnorr_sig_verify(), and test_schnorr_hash().
Referenced by run_schnorr_tests().
test_schnorr_sign_verify()
void test_schnorr_sign_verify (void)
Definition at line 50 of file tests_impl.h.
References CHECK, ctx, secp256k1_context_struct::ecmult_ctx, secp256k1_context_struct::ecmult_gen_ctx, random_scalar_order_test(), secp256k1_ecmult_gen(), secp256k1_ge_set_gej_var(), secp256k1_rand256_test(), secp256k1_rand_bits(), secp256k1_rand_int(), secp256k1_schnorr_sig_sign(), secp256k1_schnorr_sig_verify(), and test_schnorr_hash().
Referenced by run_schnorr_tests().
test_schnorr_threshold()
void test_schnorr_threshold (void)
Definition at line 85 of file tests_impl.h.
References CHECK, ctx, secp256k1_ec_pubkey_combine(), secp256k1_ec_pubkey_create(), secp256k1_ec_seckey_verify(), secp256k1_rand256_test(), secp256k1_rand_bits(), secp256k1_rand_int(), secp256k1_schnorr_generate_nonce_pair(), secp256k1_schnorr_partial_combine(), secp256k1_schnorr_partial_sign(), and secp256k1_schnorr_verify().
Referenced by run_schnorr_tests().
Released under the MIT license