Dash Core: src/secp256k1/src/modules/schnorr/schnorr.h File Reference
schnorr.h File Reference
#include "scalar.h"
#include "group.h"
Typedefs
typedef void(* secp256k1_schnorr_msghash) (unsigned char *h32, const unsigned char *r32, const unsigned char *msg32)
Functions
static int secp256k1_schnorr_sig_sign (const secp256k1_ecmult_gen_context *ctx, unsigned char *sig64, const secp256k1_scalar *key, const secp256k1_scalar *nonce, const secp256k1_ge *pubnonce, secp256k1_schnorr_msghash hash, const unsigned char *msg32)
static int secp256k1_schnorr_sig_verify (const secp256k1_ecmult_context *ctx, const unsigned char *sig64, const secp256k1_ge *pubkey, secp256k1_schnorr_msghash hash, const unsigned char *msg32)
static int secp256k1_schnorr_sig_recover (const secp256k1_ecmult_context *ctx, const unsigned char *sig64, secp256k1_ge *pubkey, secp256k1_schnorr_msghash hash, const unsigned char *msg32)
static int secp256k1_schnorr_sig_combine (unsigned char *sig64, size_t n, const unsigned char *const *sig64ins)
Typedef Documentation
secp256k1_schnorr_msghash
typedef void(* secp256k1_schnorr_msghash) (unsigned char *h32, const unsigned char *r32, const unsigned char *msg32)
Definition at line 13 of file schnorr.h.
Function Documentation
secp256k1_schnorr_sig_combine()
static int secp256k1_schnorr_sig_combine (unsigned char * sig64, size_t n, const unsigned char *const * sig64ins) static
Referenced by secp256k1_schnorr_partial_combine().
secp256k1_schnorr_sig_recover()
static int secp256k1_schnorr_sig_recover (const secp256k1_ecmult_context * ctx, const unsigned char * sig64, secp256k1_ge * pubkey, secp256k1_schnorr_msghash hash, const unsigned char * msg32) static
Referenced by secp256k1_schnorr_recover(), and test_schnorr_recovery().
secp256k1_schnorr_sig_sign()
static int secp256k1_schnorr_sig_sign (const secp256k1_ecmult_gen_context * ctx, unsigned char * sig64, const secp256k1_scalar * key, const secp256k1_scalar * nonce, const secp256k1_ge * pubnonce, secp256k1_schnorr_msghash hash, const unsigned char * msg32) static
Referenced by secp256k1_schnorr_partial_sign(), secp256k1_schnorr_sign(), and test_schnorr_sign_verify().
secp256k1_schnorr_sig_verify()
static int secp256k1_schnorr_sig_verify (const secp256k1_ecmult_context * ctx, const unsigned char * sig64, const secp256k1_ge * pubkey, secp256k1_schnorr_msghash hash, const unsigned char * msg32) static
Referenced by secp256k1_schnorr_verify(), test_schnorr_recovery(), and test_schnorr_sign_verify().