Dash Core: src/secp256k1/src/scratch.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
scratch.h File Reference
Classes
struct secp256k1_scratch_space_struct
Macros
#define SECP256K1_SCRATCH_MAX_FRAMES 5
Typedefs
typedef struct secp256k1_scratch_space_struct secp256k1_scratch
Functions
static secp256k1_scratch * secp256k1_scratch_create (const secp256k1_callback *error_callback, size_t max_size)
static void secp256k1_scratch_destroy (secp256k1_scratch *scratch)
static int secp256k1_scratch_allocate_frame (secp256k1_scratch *scratch, size_t n, size_t objects)
Attempts to allocate a new stack frame with n available bytes.
static void secp256k1_scratch_deallocate_frame (secp256k1_scratch *scratch)
Deallocates a stack frame.
static size_t secp256k1_scratch_max_allocation (const secp256k1_scratch *scratch, size_t n_objects)
Returns the maximum allocation the scratch space will allow.
static void * secp256k1_scratch_alloc (secp256k1_scratch *scratch, size_t n)
Returns a pointer into the most recently allocated frame, or NULL if there is insufficient available space.
Macro Definition Documentation
SECP256K1_SCRATCH_MAX_FRAMES
#define SECP256K1_SCRATCH_MAX_FRAMES 5
Definition at line 10 of file scratch.h.
Referenced by secp256k1_scratch_allocate_frame().
Typedef Documentation
secp256k1_scratch
typedef struct secp256k1_scratch_space_struct secp256k1_scratch
Function Documentation
secp256k1_scratch_alloc()
static void* secp256k1_scratch_alloc (secp256k1_scratch * scratch, size_t n) static
Returns a pointer into the most recently allocated frame, or NULL if there is insufficient available space.
Referenced by run_scratch_tests(), secp256k1_ecmult_pippenger_batch(), and secp256k1_ecmult_strauss_batch().
secp256k1_scratch_allocate_frame()
static int secp256k1_scratch_allocate_frame (secp256k1_scratch * scratch, size_t n, size_t objects) static
Attempts to allocate a new stack frame with n available bytes.
Returns 1 on success, 0 on failure
Referenced by run_scratch_tests(), secp256k1_ecmult_pippenger_batch(), secp256k1_ecmult_strauss_batch(), and test_ecmult_multi_pippenger_max_points().
secp256k1_scratch_create()
static secp256k1_scratch* secp256k1_scratch_create (const secp256k1_callback * error_callback, size_t max_size) static
Referenced by run_ecmult_multi_tests(), secp256k1_scratch_space_create(), test_ecmult_multi(), test_ecmult_multi_batching(), test_ecmult_multi_pippenger_max_points(), and test_exhaustive_ecmult_multi().
secp256k1_scratch_deallocate_frame()
static void secp256k1_scratch_deallocate_frame (secp256k1_scratch * scratch) static
Deallocates a stack frame.
Referenced by run_scratch_tests(), secp256k1_ecmult_pippenger_batch(), secp256k1_ecmult_strauss_batch(), and test_ecmult_multi_pippenger_max_points().
secp256k1_scratch_destroy()
static void secp256k1_scratch_destroy (secp256k1_scratch * scratch) static
Referenced by run_ecmult_multi_tests(), secp256k1_scratch_space_destroy(), test_ecmult_multi(), test_ecmult_multi_batching(), test_ecmult_multi_pippenger_max_points(), and test_exhaustive_ecmult_multi().
secp256k1_scratch_max_allocation()
static size_t secp256k1_scratch_max_allocation (const secp256k1_scratch * scratch, size_t n_objects) static
Returns the maximum allocation the scratch space will allow.
Referenced by run_scratch_tests(), secp256k1_pippenger_max_points(), and secp256k1_strauss_max_points().
Released under the MIT license