Dash Core: src/secp256k1/src/scratch_impl.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
scratch_impl.h File Reference
#include "scratch.h"
Macros
#define ALIGNMENT 16
Functions
static secp256k1_scratch * secp256k1_scratch_create (const secp256k1_callback *error_callback, size_t max_size)
static void secp256k1_scratch_destroy (secp256k1_scratch *scratch)
static size_t secp256k1_scratch_max_allocation (const secp256k1_scratch *scratch, size_t objects)
static int secp256k1_scratch_allocate_frame (secp256k1_scratch *scratch, size_t n, size_t objects)
static void secp256k1_scratch_deallocate_frame (secp256k1_scratch *scratch)
static void * secp256k1_scratch_alloc (secp256k1_scratch *scratch, size_t size)
Macro Definition Documentation
ALIGNMENT
#define ALIGNMENT 16
Definition at line 16 of file scratch_impl.h.
Referenced by run_ecmult_multi_tests(), secp256k1_scratch_alloc(), secp256k1_scratch_allocate_frame(), secp256k1_scratch_max_allocation(), and test_ecmult_multi_batching().
Function Documentation
secp256k1_scratch_alloc()
static void* secp256k1_scratch_alloc (secp256k1_scratch * scratch, size_t size) static
Definition at line 71 of file scratch_impl.h.
References ALIGNMENT, secp256k1_scratch_space_struct::data, secp256k1_scratch_space_struct::frame, secp256k1_scratch_space_struct::frame_size, and secp256k1_scratch_space_struct::offset.
secp256k1_scratch_allocate_frame()
static int secp256k1_scratch_allocate_frame (secp256k1_scratch * scratch, size_t n, size_t objects) static
Definition at line 47 of file scratch_impl.h.
References ALIGNMENT, checked_malloc(), secp256k1_scratch_space_struct::data, secp256k1_scratch_space_struct::error_callback, secp256k1_scratch_space_struct::frame, secp256k1_scratch_space_struct::frame_size, secp256k1_scratch_space_struct::offset, secp256k1_scratch_max_allocation(), SECP256K1_SCRATCH_MAX_FRAMES, and VERIFY_CHECK.
secp256k1_scratch_create()
static secp256k1_scratch* secp256k1_scratch_create (const secp256k1_callback * error_callback, size_t max_size) static
Definition at line 18 of file scratch_impl.h.
References checked_malloc(), secp256k1_scratch_space_struct::error_callback, and secp256k1_scratch_space_struct::max_size.
secp256k1_scratch_deallocate_frame()
static void secp256k1_scratch_deallocate_frame (secp256k1_scratch * scratch) static
Definition at line 65 of file scratch_impl.h.
References secp256k1_scratch_space_struct::data, secp256k1_scratch_space_struct::frame, and VERIFY_CHECK.
secp256k1_scratch_destroy()
static void secp256k1_scratch_destroy (secp256k1_scratch * scratch) static
Definition at line 28 of file scratch_impl.h.
References secp256k1_scratch_space_struct::frame, and VERIFY_CHECK.
secp256k1_scratch_max_allocation()
static size_t secp256k1_scratch_max_allocation (const secp256k1_scratch * scratch, size_t objects) static
Definition at line 35 of file scratch_impl.h.
References ALIGNMENT, secp256k1_scratch_space_struct::frame, secp256k1_scratch_space_struct::frame_size, and secp256k1_scratch_space_struct::max_size.
Referenced by secp256k1_scratch_allocate_frame().
Released under the MIT license