Dash Core: src/secp256k1/src/bench.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
bench.h File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "sys/time.h"
Functions
static double gettimedouble (void)
void print_number (double x)
void run_benchmark (char *name, void(*benchmark)(void *), void(*setup)(void *), void(*teardown)(void *), void *data, int count, int iter)
int have_flag (int argc, char **argv, char *flag)
Function Documentation
gettimedouble()
static double gettimedouble (void) static
Definition at line 15 of file bench.h.
Referenced by run_benchmark().
have_flag()
int have_flag (int argc, char ** argv, char * flag)
Definition at line 67 of file bench.h.
Referenced by main().
print_number()
void print_number (double x)
Definition at line 21 of file bench.h.
References tinyformat::printf().
Referenced by run_benchmark().
run_benchmark()
void run_benchmark (char * name, void(*)(void *) benchmark, void(*)(void *) setup, void(*)(void *) teardown, void * data, int count, int iter)
Definition at line 34 of file bench.h.
References count, gettimedouble(), name, print_number(), tinyformat::printf(), and sum.
Referenced by main(), and run_test().
Released under the MIT license