Dash Core: src/secp256k1/include/secp256k1_ecdh.h File Reference
secp256k1_ecdh.h File Reference
#include "secp256k1.h"
Functions
SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ecdh (const secp256k1_context *ctx, unsigned char *result, const secp256k1_pubkey *pubkey, const unsigned char *privkey) SECP256K1_ARG_NONNULL(1) SECP256K1_ARG_NONNULL(2) SECP256K1_ARG_NONNULL(3) SECP256K1_ARG_NONNULL(4)
Function Documentation
secp256k1_ecdh()
SECP256K1_API SECP256K1_WARN_UNUSED_RESULT int secp256k1_ecdh (const secp256k1_context * ctx, unsigned char * result, const secp256k1_pubkey * pubkey, const unsigned char * privkey)
Compute an EC Diffie-Hellman secret in constant time Returns: 1: exponentiation was successful 0: scalar was invalid (zero or overflow) Args: ctx: pointer to a context object (cannot be NULL) Out: result: a 32-byte array which will be populated by an ECDH secret computed from the point and scalar In: pubkey: a pointer to a secp256k1_pubkey containing an initialized public key privkey: a 32-byte scalar with which to multiply the point
Definition at line 13 of file main_impl.h.
Referenced by bench_ecdh(), test_bad_scalar(), and test_ecdh_generator_basepoint().