Dash Core: src/secp256k1/src/hash.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
hash.h File Reference
#include <stdlib.h>
#include <stdint.h>
Classes
struct secp256k1_sha256_t
struct secp256k1_hmac_sha256_t
struct secp256k1_rfc6979_hmac_sha256_t
Functions
static void secp256k1_sha256_initialize (secp256k1_sha256_t *hash)
static void secp256k1_sha256_write (secp256k1_sha256_t *hash, const unsigned char *data, size_t size)
static void secp256k1_sha256_finalize (secp256k1_sha256_t *hash, unsigned char *out32)
static void secp256k1_hmac_sha256_initialize (secp256k1_hmac_sha256_t *hash, const unsigned char *key, size_t size)
static void secp256k1_hmac_sha256_write (secp256k1_hmac_sha256_t *hash, const unsigned char *data, size_t size)
static void secp256k1_hmac_sha256_finalize (secp256k1_hmac_sha256_t *hash, unsigned char *out32)
static void secp256k1_rfc6979_hmac_sha256_initialize (secp256k1_rfc6979_hmac_sha256_t *rng, const unsigned char *key, size_t keylen)
static void secp256k1_rfc6979_hmac_sha256_generate (secp256k1_rfc6979_hmac_sha256_t *rng, unsigned char *out, size_t outlen)
static void secp256k1_rfc6979_hmac_sha256_finalize (secp256k1_rfc6979_hmac_sha256_t *rng)
Function Documentation
secp256k1_hmac_sha256_finalize()
static void secp256k1_hmac_sha256_finalize (secp256k1_hmac_sha256_t * hash, unsigned char * out32) static
Referenced by bench_hmac_sha256(), and run_hmac_sha256_tests().
secp256k1_hmac_sha256_initialize()
static void secp256k1_hmac_sha256_initialize (secp256k1_hmac_sha256_t * hash, const unsigned char * key, size_t size) static
Referenced by bench_hmac_sha256(), and run_hmac_sha256_tests().
secp256k1_hmac_sha256_write()
static void secp256k1_hmac_sha256_write (secp256k1_hmac_sha256_t * hash, const unsigned char * data, size_t size) static
Referenced by bench_hmac_sha256(), and run_hmac_sha256_tests().
secp256k1_rfc6979_hmac_sha256_finalize()
static void secp256k1_rfc6979_hmac_sha256_finalize (secp256k1_rfc6979_hmac_sha256_t * rng) static
Referenced by nonce_function_rfc6979(), run_rfc6979_hmac_sha256_tests(), and secp256k1_ecmult_gen_blind().
secp256k1_rfc6979_hmac_sha256_generate()
static void secp256k1_rfc6979_hmac_sha256_generate (secp256k1_rfc6979_hmac_sha256_t * rng, unsigned char * out, size_t outlen) static
Referenced by bench_rfc6979_hmac_sha256(), nonce_function_rfc6979(), run_rfc6979_hmac_sha256_tests(), secp256k1_ecmult_gen_blind(), secp256k1_rand256(), and secp256k1_rand32().
secp256k1_rfc6979_hmac_sha256_initialize()
static void secp256k1_rfc6979_hmac_sha256_initialize (secp256k1_rfc6979_hmac_sha256_t * rng, const unsigned char * key, size_t keylen) static
Referenced by bench_rfc6979_hmac_sha256(), nonce_function_rfc6979(), run_rfc6979_hmac_sha256_tests(), secp256k1_ecmult_gen_blind(), and secp256k1_rand_seed().
secp256k1_sha256_finalize()
static void secp256k1_sha256_finalize (secp256k1_sha256_t * hash, unsigned char * out32) static
Referenced by bench_sha256(), run_sha256_tests(), secp256k1_ecdh(), secp256k1_schnorr_msghash_sha256(), and test_ecdh_generator_basepoint().
secp256k1_sha256_initialize()
static void secp256k1_sha256_initialize (secp256k1_sha256_t * hash) static
Referenced by bench_sha256(), run_sha256_tests(), secp256k1_ecdh(), secp256k1_schnorr_msghash_sha256(), and test_ecdh_generator_basepoint().
secp256k1_sha256_write()
static void secp256k1_sha256_write (secp256k1_sha256_t * hash, const unsigned char * data, size_t size) static
Referenced by bench_sha256(), run_sha256_tests(), secp256k1_ecdh(), secp256k1_schnorr_msghash_sha256(), and test_ecdh_generator_basepoint().
Released under the MIT license