Dash Core: src/rpc/server.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
server.h File Reference
#include "amount.h"
#include "rpc/protocol.h"
#include "uint256.h"
#include <list>
#include <map>
#include <stdint.h>
#include <string>
#include <boost/function.hpp>
#include <univalue.h>
Classes
class JSONRequest
class RPCTimerBase
Opaque base class for timers returned by NewTimerFunc.
class RPCTimerInterface
RPC timer "driver".
class CRPCCommand
class CRPCTable
Dash RPC command dispatcher.
Namespaces
RPCServer
Typedefs
typedef UniValue(* rpcfn_type) (const UniValue &params, bool fHelp)
Functions
void RPCServer::OnStarted (boost::function< void()> slot)
void RPCServer::OnStopped (boost::function< void()> slot)
void RPCServer::OnPreCommand (boost::function< void(const CRPCCommand &)> slot)
void RPCServer::OnPostCommand (boost::function< void(const CRPCCommand &)> slot)
bool IsRPCRunning ()
Query whether RPC is running.
void SetRPCWarmupStatus (const std::string &newStatus)
Set the RPC warmup status.
void SetRPCWarmupFinished ()
bool RPCIsInWarmup (std::string *statusOut)
void RPCTypeCheck (const UniValue &params, const std::list< UniValue::VType > &typesExpected, bool fAllowNull=false)
Type-check arguments; throws JSONRPCError if wrong type given.
void RPCTypeCheckObj (const UniValue &o, const std::map< std::string, UniValue::VType > &typesExpected, bool fAllowNull=false)
void RPCRegisterTimerInterface (RPCTimerInterface *iface)
Register factory function for timers.
void RPCUnregisterTimerInterface (RPCTimerInterface *iface)
Unregister factory function for timers.
void RPCRunLater (const std::string &name, boost::function< void(void)> func, int64_t nSeconds)
Run func nSeconds from now.
uint256 ParseHashV (const UniValue &v, std::string strName)
Utilities: convert hex-encoded Values (throws error if not hex).
uint256 ParseHashO (const UniValue &o, std::string strKey)
std::vector< unsigned char > ParseHexV (const UniValue &v, std::string strName)
std::vector< unsigned char > ParseHexO (const UniValue &o, std::string strKey)
CAmount AmountFromValue (const UniValue &value)
UniValue ValueFromAmount (const CAmount &amount)
double GetDifficulty (const CBlockIndex *blockindex=NULL)
std::string HelpRequiringPassphrase ()
std::string HelpExampleCli (const std::string &methodname, const std::string &args)
std::string HelpExampleRpc (const std::string &methodname, const std::string &args)
void EnsureWalletIsUnlocked ()
UniValue getconnectioncount (const UniValue &params, bool fHelp)
UniValue getaddressmempool (const UniValue &params, bool fHelp)
UniValue getaddressutxos (const UniValue &params, bool fHelp)
UniValue getaddressdeltas (const UniValue &params, bool fHelp)
UniValue getaddresstxids (const UniValue &params, bool fHelp)
UniValue getaddressbalance (const UniValue &params, bool fHelp)
UniValue getpeerinfo (const UniValue &params, bool fHelp)
UniValue ping (const UniValue &params, bool fHelp)
UniValue addnode (const UniValue &params, bool fHelp)
UniValue disconnectnode (const UniValue &params, bool fHelp)
UniValue getaddednodeinfo (const UniValue &params, bool fHelp)
UniValue getnettotals (const UniValue &params, bool fHelp)
UniValue setban (const UniValue &params, bool fHelp)
UniValue listbanned (const UniValue &params, bool fHelp)
UniValue clearbanned (const UniValue &params, bool fHelp)
UniValue setnetworkactive (const UniValue &params, bool fHelp)
UniValue dumpprivkey (const UniValue &params, bool fHelp)
UniValue importprivkey (const UniValue &params, bool fHelp)
UniValue importaddress (const UniValue &params, bool fHelp)
UniValue importpubkey (const UniValue &params, bool fHelp)
UniValue dumphdinfo (const UniValue &params, bool fHelp)
UniValue dumpwallet (const UniValue &params, bool fHelp)
UniValue importwallet (const UniValue &params, bool fHelp)
UniValue importelectrumwallet (const UniValue &params, bool fHelp)
UniValue getgenerate (const UniValue &params, bool fHelp)
UniValue setgenerate (const UniValue &params, bool fHelp)
UniValue generate (const UniValue &params, bool fHelp)
UniValue getnetworkhashps (const UniValue &params, bool fHelp)
UniValue getmininginfo (const UniValue &params, bool fHelp)
UniValue prioritisetransaction (const UniValue &params, bool fHelp)
UniValue getblocktemplate (const UniValue &params, bool fHelp)
UniValue submitblock (const UniValue &params, bool fHelp)
UniValue estimatefee (const UniValue &params, bool fHelp)
UniValue estimatepriority (const UniValue &params, bool fHelp)
UniValue estimatesmartfee (const UniValue &params, bool fHelp)
UniValue estimatesmartpriority (const UniValue &params, bool fHelp)
UniValue instantsendtoaddress (const UniValue &params, bool fHelp)
UniValue keepass (const UniValue &params, bool fHelp)
UniValue getnewaddress (const UniValue &params, bool fHelp)
UniValue getaccountaddress (const UniValue &params, bool fHelp)
UniValue getrawchangeaddress (const UniValue &params, bool fHelp)
UniValue setaccount (const UniValue &params, bool fHelp)
UniValue getaccount (const UniValue &params, bool fHelp)
UniValue getaddressesbyaccount (const UniValue &params, bool fHelp)
UniValue sendtoaddress (const UniValue &params, bool fHelp)
UniValue signmessage (const UniValue &params, bool fHelp)
UniValue verifymessage (const UniValue &params, bool fHelp)
UniValue getreceivedbyaddress (const UniValue &params, bool fHelp)
UniValue getreceivedbyaccount (const UniValue &params, bool fHelp)
UniValue getbalance (const UniValue &params, bool fHelp)
UniValue getunconfirmedbalance (const UniValue &params, bool fHelp)
UniValue movecmd (const UniValue &params, bool fHelp)
UniValue sendfrom (const UniValue &params, bool fHelp)
UniValue sendmany (const UniValue &params, bool fHelp)
UniValue addmultisigaddress (const UniValue &params, bool fHelp)
UniValue createmultisig (const UniValue &params, bool fHelp)
UniValue listreceivedbyaddress (const UniValue &params, bool fHelp)
UniValue listreceivedbyaccount (const UniValue &params, bool fHelp)
UniValue listtransactions (const UniValue &params, bool fHelp)
UniValue listaddressgroupings (const UniValue &params, bool fHelp)
UniValue listaccounts (const UniValue &params, bool fHelp)
UniValue listsinceblock (const UniValue &params, bool fHelp)
UniValue gettransaction (const UniValue &params, bool fHelp)
UniValue abandontransaction (const UniValue &params, bool fHelp)
UniValue backupwallet (const UniValue &params, bool fHelp)
UniValue keypoolrefill (const UniValue &params, bool fHelp)
UniValue walletpassphrase (const UniValue &params, bool fHelp)
UniValue walletpassphrasechange (const UniValue &params, bool fHelp)
UniValue walletlock (const UniValue &params, bool fHelp)
UniValue encryptwallet (const UniValue &params, bool fHelp)
UniValue validateaddress (const UniValue &params, bool fHelp)
UniValue getinfo (const UniValue &params, bool fHelp)
UniValue debug (const UniValue &params, bool fHelp)
UniValue getwalletinfo (const UniValue &params, bool fHelp)
UniValue getblockchaininfo (const UniValue &params, bool fHelp)
UniValue getnetworkinfo (const UniValue &params, bool fHelp)
UniValue setmocktime (const UniValue &params, bool fHelp)
UniValue resendwallettransactions (const UniValue &params, bool fHelp)
UniValue getrawtransaction (const UniValue &params, bool fHelp)
UniValue listunspent (const UniValue &params, bool fHelp)
UniValue lockunspent (const UniValue &params, bool fHelp)
UniValue listlockunspent (const UniValue &params, bool fHelp)
UniValue createrawtransaction (const UniValue &params, bool fHelp)
UniValue decoderawtransaction (const UniValue &params, bool fHelp)
UniValue decodescript (const UniValue &params, bool fHelp)
UniValue fundrawtransaction (const UniValue &params, bool fHelp)
UniValue signrawtransaction (const UniValue &params, bool fHelp)
UniValue sendrawtransaction (const UniValue &params, bool fHelp)
UniValue gettxoutproof (const UniValue &params, bool fHelp)
UniValue verifytxoutproof (const UniValue &params, bool fHelp)
UniValue privatesend (const UniValue &params, bool fHelp)
UniValue getpoolinfo (const UniValue &params, bool fHelp)
UniValue spork (const UniValue &params, bool fHelp)
UniValue masternode (const UniValue &params, bool fHelp)
UniValue masternodelist (const UniValue &params, bool fHelp)
UniValue masternodebroadcast (const UniValue &params, bool fHelp)
UniValue gobject (const UniValue &params, bool fHelp)
UniValue getgovernanceinfo (const UniValue &params, bool fHelp)
UniValue getsuperblockbudget (const UniValue &params, bool fHelp)
UniValue voteraw (const UniValue &params, bool fHelp)
UniValue mnsync (const UniValue &params, bool fHelp)
UniValue getblockcount (const UniValue &params, bool fHelp)
UniValue getbestblockhash (const UniValue &params, bool fHelp)
UniValue getdifficulty (const UniValue &params, bool fHelp)
UniValue settxfee (const UniValue &params, bool fHelp)
UniValue getmempoolinfo (const UniValue &params, bool fHelp)
UniValue getrawmempool (const UniValue &params, bool fHelp)
UniValue getblockhashes (const UniValue &params, bool fHelp)
UniValue getblockhash (const UniValue &params, bool fHelp)
UniValue getblockheader (const UniValue &params, bool fHelp)
UniValue getblockheaders (const UniValue &params, bool fHelp)
UniValue getblock (const UniValue &params, bool fHelp)
UniValue gettxoutsetinfo (const UniValue &params, bool fHelp)
UniValue gettxout (const UniValue &params, bool fHelp)
UniValue verifychain (const UniValue &params, bool fHelp)
UniValue getchaintips (const UniValue &params, bool fHelp)
UniValue invalidateblock (const UniValue &params, bool fHelp)
UniValue reconsiderblock (const UniValue &params, bool fHelp)
UniValue getspentinfo (const UniValue &params, bool fHelp)
UniValue sentinelping (const UniValue &params, bool fHelp)
bool StartRPC ()
void InterruptRPC ()
void StopRPC ()
std::string JSONRPCExecBatch (const UniValue &vReq)
Variables
const CRPCTable tableRPC
int64_t nWalletUnlockTime
Typedef Documentation
rpcfn_type
typedef UniValue(* rpcfn_type) (const UniValue &params, bool fHelp)
Definition at line 114 of file server.h.
Function Documentation
abandontransaction()
UniValue abandontransaction (const UniValue & params, bool fHelp)
Definition at line 1902 of file rpcwallet.cpp.
References CWallet::AbandonTransaction(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, CWallet::mapWallet, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, base_blob< BITS >::SetHex(), and UniValue::size().
addmultisigaddress()
UniValue addmultisigaddress (const UniValue & params, bool fHelp)
Definition at line 1151 of file rpcwallet.cpp.
References _createmultisig_redeemScript(), AccountFromValue(), CWallet::AddCScript(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), HelpExampleCli(), HelpExampleRpc(), LOCK2, NullUniValue, pwalletMain, CWallet::SetAddressBook(), UniValue::size(), and CBase58Data::ToString().
addnode()
UniValue addnode (const UniValue & params, bool fHelp)
Definition at line 189 of file net.cpp.
References g_connman, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, RPC_CLIENT_NODE_ALREADY_ADDED, RPC_CLIENT_NODE_NOT_ADDED, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
AmountFromValue()
CAmount AmountFromValue (const UniValue & value)
Definition at line 110 of file server.cpp.
References UniValue::getValStr(), UniValue::isNum(), UniValue::isStr(), JSONRPCError(), MoneyRange(), ParseFixedPoint(), and RPC_TYPE_ERROR.
Referenced by createrawtransaction(), instantsendtoaddress(), movecmd(), sendfrom(), sendmany(), sendtoaddress(), and settxfee().
backupwallet()
UniValue backupwallet (const UniValue & params, bool fHelp)
Definition at line 1937 of file rpcwallet.cpp.
References BackupWallet(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, NullUniValue, pwalletMain, RPC_WALLET_ERROR, and UniValue::size().
clearbanned()
UniValue clearbanned (const UniValue & params, bool fHelp)
Definition at line 562 of file net.cpp.
References g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
createmultisig()
UniValue createmultisig (const UniValue & params, bool fHelp)
Definition at line 410 of file misc.cpp.
References _createmultisig_redeemScript(), prevector< N, T, Size, Diff >::begin(), prevector< N, T, Size, Diff >::end(), HelpExampleCli(), HelpExampleRpc(), HexStr(), Pair(), UniValue::push_back(), UniValue::size(), CBase58Data::ToString(), and UniValue::VOBJ.
createrawtransaction()
UniValue createrawtransaction (const UniValue & params, bool fHelp)
Definition at line 359 of file rawtransaction.cpp.
References AmountFromValue(), cs_main, CURRENCY_UNIT, EncodeHexTx(), find_value(), CBitcoinAddress::Get(), UniValue::get_array(), UniValue::get_int(), UniValue::get_int64(), UniValue::get_obj(), UniValue::getKeys(), GetScriptForDestination(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), UniValue::isNum(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK, CMutableTransaction::nLockTime, OP_RETURN, ParseHashO(), ParseHexV(), RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPCTypeCheck(), UniValue::size(), UniValue::VARR, CMutableTransaction::vin, UniValue::VNUM, UniValue::VOBJ, and CMutableTransaction::vout.
debug()
UniValue debug (const UniValue & params, bool fHelp)
Definition at line 120 of file misc.cpp.
References fDebug, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), mapArgs, mapMultiArgs, and UniValue::size().
decoderawtransaction()
UniValue decoderawtransaction (const UniValue & params, bool fHelp)
Definition at line 461 of file rawtransaction.cpp.
References cs_main, CURRENCY_UNIT, DecodeHexTx(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, RPC_DESERIALIZATION_ERROR, RPCTypeCheck(), UniValue::size(), TxToJSON(), UniValue::VOBJ, and UniValue::VSTR.
decodescript()
UniValue decodescript (const UniValue & params, bool fHelp)
Definition at line 527 of file rawtransaction.cpp.
References find_value(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), UniValue::isStr(), Pair(), ParseHexV(), UniValue::push_back(), RPCTypeCheck(), ScriptPubKeyToJSON(), UniValue::size(), UniValue::VOBJ, and UniValue::VSTR.
disconnectnode()
UniValue disconnectnode (const UniValue & params, bool fHelp)
Definition at line 234 of file net.cpp.
References g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, RPC_CLIENT_NODE_NOT_CONNECTED, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
dumphdinfo()
UniValue dumphdinfo (const UniValue & params, bool fHelp)
Definition at line 583 of file rpcdump.cpp.
References CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CWallet::GetDecryptedHDChain(), CCryptoKeyStore::GetHDChain(), CHDChain::GetMnemonic(), CHDChain::GetSeed(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, NullUniValue, Pair(), UniValue::push_back(), pwalletMain, RPC_INTERNAL_ERROR, UniValue::size(), and UniValue::VOBJ.
dumpprivkey()
UniValue dumpprivkey (const UniValue & params, bool fHelp)
Definition at line 546 of file rpcdump.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), UniValue::get_str(), CWallet::GetKey(), CBitcoinAddress::GetKeyID(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, RPC_WALLET_ERROR, CBase58Data::SetString(), UniValue::size(), and CBase58Data::ToString().
dumpwallet()
UniValue dumpwallet (const UniValue & params, bool fHelp)
Definition at line 629 of file rpcdump.cpp.
References chainActive, CLIENT_BUILD, CLIENT_DATE, CHDChain::CountAccounts(), cs_main, CWallet::cs_wallet, EncodeDumpString(), EncodeDumpTime(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CHDChain::GetAccount(), CWallet::GetAllReserveKeys(), CBlockIndex::GetBlockHash(), CBlockIndex::GetBlockTime(), CWallet::GetDecryptedHDChain(), CCryptoKeyStore::GetHDChain(), CWallet::GetKey(), CWallet::GetKeyBirthTimes(), CHDChain::GetMnemonic(), CHDChain::GetSeed(), GetTime(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, CWallet::mapHdPubKeys, CExtKey::Neuter(), CHDAccount::nExternalChainCounter, CHDAccount::nInternalChainCounter, NullUniValue, pwalletMain, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, CBitcoinExtKeyBase< K, Size, Type >::SetKey(), CExtKey::SetMaster(), UniValue::size(), strprintf, CChain::Tip(), base_blob< BITS >::ToString(), and CBase58Data::ToString().
encryptwallet()
UniValue encryptwallet (const UniValue & params, bool fHelp)
Definition at line 2159 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, CWallet::EncryptWallet(), EnsureWalletIsAvailable(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), JSONRPCError(), LOCK2, NullUniValue, pwalletMain, RPC_WALLET_ENCRYPTION_FAILED, RPC_WALLET_WRONG_ENC_STATE, UniValue::size(), and StartShutdown().
EnsureWalletIsUnlocked()
void EnsureWalletIsUnlocked ()
Definition at line 54 of file rpcwallet.cpp.
Referenced by masternode(), masternodebroadcast(), and signrawtransaction().
estimatefee()
UniValue estimatefee (const UniValue & params, bool fHelp)
Definition at line 824 of file mining.cpp.
References CTxMemPool::estimateFee(), UniValue::get_int(), CFeeRate::GetFeePerK(), HelpExampleCli(), mempool, RPCTypeCheck(), UniValue::size(), ValueFromAmount(), and UniValue::VNUM.
estimatepriority()
UniValue estimatepriority (const UniValue & params, bool fHelp)
Definition at line 855 of file mining.cpp.
References CTxMemPool::estimatePriority(), UniValue::get_int(), HelpExampleCli(), mempool, RPCTypeCheck(), UniValue::size(), and UniValue::VNUM.
estimatesmartfee()
UniValue estimatesmartfee (const UniValue & params, bool fHelp)
Definition at line 882 of file mining.cpp.
References CTxMemPool::estimateSmartFee(), UniValue::get_int(), CFeeRate::GetFeePerK(), HelpExampleCli(), mempool, Pair(), UniValue::push_back(), RPCTypeCheck(), UniValue::size(), ValueFromAmount(), UniValue::VNUM, and UniValue::VOBJ.
estimatesmartpriority()
UniValue estimatesmartpriority (const UniValue & params, bool fHelp)
Definition at line 918 of file mining.cpp.
References CTxMemPool::estimateSmartPriority(), UniValue::get_int(), HelpExampleCli(), mempool, Pair(), UniValue::push_back(), RPCTypeCheck(), UniValue::size(), UniValue::VNUM, and UniValue::VOBJ.
fundrawtransaction()
UniValue fundrawtransaction (const UniValue & params, bool fHelp)
Definition at line 2651 of file rpcwallet.cpp.
References DecodeHexTx(), EncodeHexTx(), EnsureWalletIsAvailable(), CWallet::FundTransaction(), HelpExampleCli(), JSONRPCError(), NullUniValue, Pair(), UniValue::push_back(), pwalletMain, RPC_DESERIALIZATION_ERROR, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, RPCTypeCheck(), UniValue::size(), ValueFromAmount(), UniValue::VBOOL, UniValue::VOBJ, CTransaction::vout, and UniValue::VSTR.
generate()
UniValue generate (const UniValue & params, bool fHelp)
Definition at line 123 of file mining.cpp.
References chainActive, CheckProofOfWork(), CreateNewBlock(), cs_main, UniValue::get_int(), CChainParams::GetConsensus(), CBlockHeader::GetHash(), base_blob< BITS >::GetHex(), GetMainSignals(), CChain::Height(), HelpExampleCli(), IncrementExtraNonce(), JSONRPCError(), LOCK, CChainParams::MineBlocksOnDemand(), CBlockHeader::nBits, CBlockHeader::nNonce, Params(), ProcessNewBlock(), UniValue::push_back(), RPC_INTERNAL_ERROR, RPC_METHOD_NOT_FOUND, RPC_WALLET_KEYPOOL_RAN_OUT, CMainSignals::ScriptForMining, UniValue::size(), CChain::Tip(), and UniValue::VARR.
getaccount()
UniValue getaccount (const UniValue & params, bool fHelp)
Definition at line 305 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), CBitcoinAddress::Get(), HelpExampleCli(), HelpExampleRpc(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, and UniValue::size().
getaccountaddress()
UniValue getaccountaddress (const UniValue & params, bool fHelp)
Definition at line 192 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), GetAccountAddress(), HelpExampleCli(), HelpExampleRpc(), LOCK2, NullUniValue, pwalletMain, UniValue::size(), CBase58Data::ToString(), and UniValue::VSTR.
getaddednodeinfo()
UniValue getaddednodeinfo (const UniValue & params, bool fHelp)
Definition at line 257 of file net.cpp.
References g_connman, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), Pair(), UniValue::push_back(), RPC_CLIENT_NODE_NOT_ADDED, RPC_CLIENT_P2P_DISABLED, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
getaddressbalance()
UniValue getaddressbalance (const UniValue & params, bool fHelp)
Definition at line 818 of file misc.cpp.
References getAddressesFromParams(), GetAddressIndex(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), Pair(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and UniValue::VOBJ.
getaddressdeltas()
UniValue getaddressdeltas (const UniValue & params, bool fHelp)
Definition at line 730 of file misc.cpp.
References find_value(), UniValue::get_int(), getAddressesFromParams(), getAddressFromIndex(), GetAddressIndex(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNum(), UniValue::isObject(), JSONRPCError(), Pair(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
getaddressesbyaccount()
UniValue getaddressesbyaccount (const UniValue & params, bool fHelp)
Definition at line 337 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), HelpExampleCli(), HelpExampleRpc(), LOCK2, CWallet::mapAddressBook, CAddressBookData::name, NullUniValue, PAIRTYPE, UniValue::push_back(), pwalletMain, UniValue::size(), CBase58Data::ToString(), and UniValue::VARR.
getaddressmempool()
UniValue getaddressmempool (const UniValue & params, bool fHelp)
Definition at line 592 of file misc.cpp.
References getAddressesFromParams(), getAddressFromIndex(), CTxMemPool::getAddressIndex(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), mempool, Pair(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), timestampSort(), UniValue::VARR, and UniValue::VOBJ.
getaddresstxids()
UniValue getaddresstxids (const UniValue & params, bool fHelp)
Definition at line 874 of file misc.cpp.
References find_value(), UniValue::get_int(), getAddressesFromParams(), GetAddressIndex(), HelpExampleCli(), HelpExampleRpc(), UniValue::isNum(), JSONRPCError(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and UniValue::VARR.
getaddressutxos()
UniValue getaddressutxos (const UniValue & params, bool fHelp)
Definition at line 663 of file misc.cpp.
References getAddressesFromParams(), getAddressFromIndex(), GetAddressUnspent(), heightSort(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), Pair(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
getbalance()
UniValue getbalance (const UniValue & params, bool fHelp)
Definition at line 792 of file rpcwallet.cpp.
References AccountFromValue(), COutputEntry::amount, CheckFinalTx(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), UniValue::get_bool(), GetAccountBalance(), CWalletTx::GetAmounts(), CWallet::GetBalance(), CMerkleTx::GetBlocksToMaturity(), CMerkleTx::GetDepthInMainChain(), HelpExampleCli(), HelpExampleRpc(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, LOCK2, CWallet::mapWallet, nInstantSendDepth, NullUniValue, pwalletMain, UniValue::size(), and ValueFromAmount().
getbestblockhash()
UniValue getbestblockhash (const UniValue & params, bool fHelp)
Definition at line 152 of file blockchain.cpp.
References chainActive, cs_main, CBlockIndex::GetBlockHash(), base_blob< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), LOCK, UniValue::size(), and CChain::Tip().
getblock()
UniValue getblock (const UniValue & params, bool fHelp)
Definition at line 487 of file blockchain.cpp.
References CDataStream::begin(), BLOCK_HAVE_DATA, blockToJSON(), cs_main, CDataStream::end(), fHavePruned, UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, mapBlockIndex, CBlockIndex::nStatus, CBlockIndex::nTx, Params(), PROTOCOL_VERSION, ReadBlockFromDisk(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, UniValue::size(), and uint256S().
getblockchaininfo()
UniValue getblockchaininfo (const UniValue & params, bool fHelp)
Definition at line 814 of file blockchain.cpp.
References BIP9SoftForkDesc(), BLOCK_HAVE_DATA, chainActive, cs_main, Consensus::DEPLOYMENT_CSV, Consensus::DEPLOYMENT_DIP0001, fPruneMode, CBlockIndex::GetBlockHash(), CChainParams::GetConsensus(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), Checkpoints::GuessVerificationProgress(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, CBlockIndex::nChainWork, CBlockIndex::nHeight, CBlockIndex::nStatus, Pair(), Params(), pindexBestHeader, CBlockIndex::pprev, UniValue::push_back(), UniValue::size(), SoftForkDesc(), CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
Referenced by rest_chaininfo().
getblockcount()
UniValue getblockcount (const UniValue & params, bool fHelp)
Definition at line 135 of file blockchain.cpp.
References chainActive, cs_main, CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, and UniValue::size().
getblockhash()
UniValue getblockhash (const UniValue & params, bool fHelp)
Definition at line 315 of file blockchain.cpp.
References chainActive, cs_main, UniValue::get_int(), CBlockIndex::GetBlockHash(), base_blob< BITS >::GetHex(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, RPC_INVALID_PARAMETER, and UniValue::size().
getblockhashes()
UniValue getblockhashes (const UniValue & params, bool fHelp)
Definition at line 281 of file blockchain.cpp.
References UniValue::get_int(), GetTimestampIndex(), HelpExampleCli(), HelpExampleRpc(), high, JSONRPCError(), low, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and UniValue::VARR.
getblockheader()
UniValue getblockheader (const UniValue & params, bool fHelp)
Definition at line 340 of file blockchain.cpp.
References CDataStream::begin(), blockheaderToJSON(), cs_main, CDataStream::end(), UniValue::get_str(), CBlockIndex::GetBlockHeader(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, mapBlockIndex, PROTOCOL_VERSION, RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, UniValue::size(), and uint256S().
getblockheaders()
UniValue getblockheaders (const UniValue & params, bool fHelp)
Definition at line 398 of file blockchain.cpp.
References CDataStream::begin(), blockheaderToJSON(), chainActive, cs_main, CDataStream::end(), UniValue::get_str(), CBlockIndex::GetBlockHeader(), HelpExampleCli(), HelpExampleRpc(), HexStr(), JSONRPCError(), LOCK, mapBlockIndex, MAX_HEADERS_RESULTS, CChain::Next(), PROTOCOL_VERSION, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, SER_NETWORK, UniValue::size(), strprintf, uint256S(), and UniValue::VARR.
getblocktemplate()
UniValue getblocktemplate (const UniValue & params, bool fHelp)
Definition at line 339 of file mining.cpp.
References atoi64(), prevector< N, T, Size, Diff >::begin(), BIP22ValidationResult(), Consensus::BIP9Deployment::bit, CBlockTemplate::block, BLOCK_FAILED_MASK, BLOCK_VALID_SCRIPTS, chainActive, COINBASE_FLAGS, CConnman::CONNECTIONS_ALL, CreateNewBlock(), cs_main, csBestBlock, cvBlockChange, DecodeHexBlk(), EncodeHexTx(), prevector< N, T, Size, Diff >::end(), ENTER_CRITICAL_SECTION, ExtractDestination(), fDIP0001ActiveAtTip, find_value(), g_connman, BIP9DeploymentInfo::gbt_force, gbt_vb_name(), UniValue::get_int64(), UniValue::get_obj(), UniValue::get_str(), CBlockIndex::GetBlockHash(), CMasternodePayments::GetBlockPayee(), CBlockHeader::GetBlockTime(), CChainParams::GetConsensus(), CBlockHeader::GetHash(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), CBlockIndex::GetMedianTimePast(), GetTime(), CTxMemPool::GetTransactionsUpdated(), COutPoint::hash, CBlockHeader::hashPrevBlock, CChain::Height(), HelpExampleCli(), HelpExampleRpc(), HexStr(), i64tostr(), UniValue::isArray(), CTransaction::IsCoinBase(), IsInitialBlockDownload(), UniValue::isNull(), UniValue::isNum(), IsRPCRunning(), CSporkManager::IsSporkActive(), UniValue::isStr(), CMasternodeSync::IsSynced(), CBlockIndex::IsValid(), CSuperblock::IsValidBlockHeight(), CMasternodeSync::IsWinnersListSynced(), JSONRPCError(), LEAVE_CRITICAL_SECTION, LOCK, mapBlockIndex, masternodeSync, Consensus::MAX_VERSION_BITS_DEPLOYMENTS, MaxBlockSigOps(), MaxBlockSize(), mempool, mnpayments, BIP9DeploymentInfo::name, CBlockHeader::nBits, CBlockIndex::nHeight, CBlockHeader::nNonce, CBlockIndex::nStatus, NullUniValue, CTxOut::nValue, CBlockHeader::nVersion, OP_TRUE, Pair(), Params(), CTxIn::prevout, UniValue::push_back(), RPC_CLIENT_IN_INITIAL_DOWNLOAD, RPC_CLIENT_NOT_CONNECTED, RPC_CLIENT_P2P_DISABLED, RPC_DESERIALIZATION_ERROR, RPC_INVALID_PARAMETER, RPC_OUT_OF_MEMORY, RPC_TYPE_ERROR, CTxOut::scriptPubKey, arith_uint256::SetCompact(), base_blob< BITS >::SetHex(), UniValue::size(), SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT, SPORK_9_SUPERBLOCKS_ENABLED, sporkManager, strprintf, TestBlockValidity(), THRESHOLD_ACTIVE, THRESHOLD_DEFINED, THRESHOLD_FAILED, THRESHOLD_LOCKED_IN, THRESHOLD_STARTED, CChain::Tip(), CBase58Data::ToString(), CBlock::txoutMasternode, UpdateTime(), UniValue::VARR, Consensus::Params::vDeployments, versionbitscache, VersionBitsDeploymentInfo, VersionBitsMask(), VersionBitsState(), CTransaction::vin, UniValue::VOBJ, CBlock::voutSuperblock, CBlock::vtx, CBlockTemplate::vTxFees, and CBlockTemplate::vTxSigOps.
getchaintips()
UniValue getchaintips (const UniValue & params, bool fHelp)
Definition at line 908 of file blockchain.cpp.
References BLOCK_FAILED_MASK, BLOCK_VALID_SCRIPTS, BLOCK_VALID_TREE, chainActive, CChain::Contains(), cs_main, CChain::FindFork(), GetDifficulty(), base_blob< BITS >::GetHex(), base_uint< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), CBlockIndex::IsValid(), LOCK, mapBlockIndex, CBlockIndex::nChainTx, CBlockIndex::nChainWork, CBlockIndex::nHeight, CBlockIndex::nStatus, Pair(), PAIRTYPE, CBlockIndex::phashBlock, CBlockIndex::pprev, UniValue::push_back(), UniValue::size(), CChain::Tip(), UniValue::VARR, and UniValue::VOBJ.
getconnectioncount()
UniValue getconnectioncount (const UniValue & params, bool fHelp)
Definition at line 28 of file net.cpp.
References CConnman::CONNECTIONS_ALL, g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), RPC_CLIENT_P2P_DISABLED, and UniValue::size().
GetDifficulty()
double GetDifficulty (const CBlockIndex * blockindex = NULL)
Definition at line 36 of file blockchain.cpp.
References chainActive, CBlockIndex::nBits, and CChain::Tip().
Referenced by blockheaderToJSON(), blockToJSON(), getblockchaininfo(), getchaintips(), getdifficulty(), getinfo(), and getmininginfo().
getdifficulty()
UniValue getdifficulty (const UniValue & params, bool fHelp)
Definition at line 169 of file blockchain.cpp.
References cs_main, GetDifficulty(), HelpExampleCli(), HelpExampleRpc(), LOCK, and UniValue::size().
getgenerate()
UniValue getgenerate (const UniValue & params, bool fHelp)
Definition at line 104 of file mining.cpp.
References BITCOIN_CONF_FILENAME, cs_main, DEFAULT_GENERATE, GetBoolArg(), HelpExampleCli(), HelpExampleRpc(), LOCK, and UniValue::size().
Referenced by getmininginfo().
getgovernanceinfo()
UniValue getgovernanceinfo (const UniValue & params, bool fHelp)
Definition at line 908 of file governance.cpp.
References chainActive, cs_main, CURRENCY_UNIT, CChainParams::GetConsensus(), GOVERNANCE_PROPOSAL_FEE_TX, CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, MASTERNODE_WATCHDOG_MAX_SECONDS, MAX_GOVERNANCE_OBJECT_DATA_SIZE, Consensus::Params::nSuperblockCycle, Consensus::Params::nSuperblockStartBlock, Pair(), Params(), UniValue::push_back(), UniValue::size(), ValueFromAmount(), and UniValue::VOBJ.
getinfo()
UniValue getinfo (const UniValue & params, bool fHelp)
Note
Do not add or change anything in the information returned by this method. getinfo exists for backwards-compatibility only. It combines information from wildly different sources in the program, which is a mess, and is thus planned to be deprecated eventually.
Based on the source of the information, new information should be added to:
getblockchaininfo,
getnetworkinfo or
getwalletinfo
Or alternatively, create a specific query method for the information.
Definition at line 48 of file misc.cpp.
References chainActive, CLIENT_VERSION, CConnman::CONNECTIONS_ALL, cs_main, CWallet::cs_wallet, CURRENCY_UNIT, fLiteMode, g_connman, CWallet::GetAnonymizedBalance(), CWallet::GetBalance(), GetDifficulty(), CFeeRate::GetFeePerK(), CWallet::GetKeyPoolSize(), CWallet::GetOldestKeyPoolTime(), GetProxy(), GetTimeOffset(), CWallet::GetVersion(), GetWarnings(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), proxyType::IsValid(), LOCK, LOCK2, minRelayTxFee, NET_IPV4, nWalletUnlockTime, Pair(), Params(), payTxFee, PROTOCOL_VERSION, proxyType::proxy, UniValue::push_back(), pwalletMain, UniValue::size(), CService::ToStringIPPort(), ValueFromAmount(), and UniValue::VOBJ.
getmempoolinfo()
UniValue getmempoolinfo (const UniValue & params, bool fHelp)
Definition at line 1032 of file blockchain.cpp.
References HelpExampleCli(), HelpExampleRpc(), mempoolInfoToJSON(), and UniValue::size().
getmininginfo()
UniValue getmininginfo (const UniValue & params, bool fHelp)
Definition at line 236 of file mining.cpp.
References chainActive, cs_main, DEFAULT_GENERATE_THREADS, GetArg(), GetDifficulty(), getgenerate(), getnetworkhashps(), GetWarnings(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), LOCK, mempool, nLastBlockSize, nLastBlockTx, Pair(), Params(), UniValue::push_back(), UniValue::size(), CTxMemPool::size(), and UniValue::VOBJ.
getnettotals()
UniValue getnettotals (const UniValue & params, bool fHelp)
Definition at line 326 of file net.cpp.
References g_connman, GetTimeMillis(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), Pair(), UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), and UniValue::VOBJ.
getnetworkhashps()
UniValue getnetworkhashps (const UniValue & params, bool fHelp)
Definition at line 82 of file mining.cpp.
References cs_main, UniValue::get_int(), GetNetworkHashPS(), HelpExampleCli(), HelpExampleRpc(), LOCK, and UniValue::size().
Referenced by getmininginfo().
getnetworkinfo()
UniValue getnetworkinfo (const UniValue & params, bool fHelp)
Definition at line 392 of file net.cpp.
References CLIENT_VERSION, CConnman::CONNECTIONS_ALL, cs_main, cs_mapLocalHost, CURRENCY_UNIT, fRelayTxes, g_connman, CFeeRate::GetFeePerK(), GetNetworksInfo(), GetTimeOffset(), GetWarnings(), HelpExampleCli(), HelpExampleRpc(), LOCK, mapLocalHost, minRelayTxFee, LocalServiceInfo::nPort, LocalServiceInfo::nScore, Pair(), PAIRTYPE, PROTOCOL_VERSION, UniValue::push_back(), UniValue::size(), strprintf, strSubVersion, ValueFromAmount(), UniValue::VARR, and UniValue::VOBJ.
getnewaddress()
UniValue getnewaddress (const UniValue & params, bool fHelp)
Definition at line 113 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), CPubKey::GetID(), CWallet::GetKeyFromPool(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsLocked(), JSONRPCError(), LOCK2, NullUniValue, pwalletMain, RPC_WALLET_KEYPOOL_RAN_OUT, CWallet::SetAddressBook(), UniValue::size(), CWallet::TopUpKeyPool(), and CBase58Data::ToString().
getpeerinfo()
UniValue getpeerinfo (const UniValue & params, bool fHelp)
Definition at line 70 of file net.cpp.
References CNodeStats::addrLocal, CNodeStats::addrName, CNodeStats::cleanSubVer, CNodeStats::dMinPing, CNodeStats::dPingTime, CNodeStats::dPingWait, CNodeStats::fInbound, CNodeStats::fRelayTxes, CNodeStats::fWhitelisted, g_connman, GetNodeStateStats(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), CNodeStats::mapRecvBytesPerMsgCmd, CNodeStats::mapSendBytesPerMsgCmd, CNodeStateStats::nCommonHeight, CNodeStats::nLastRecv, CNodeStats::nLastSend, CNodeStateStats::nMisbehavior, CNodeStats::nodeid, CNodeStats::nRecvBytes, CNodeStats::nSendBytes, CNodeStats::nServices, CNodeStats::nStartingHeight, CNodeStateStats::nSyncHeight, CNodeStats::nTimeConnected, CNodeStats::nTimeOffset, CNodeStats::nVersion, Pair(), UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), strprintf, UniValue::VARR, CNodeStateStats::vHeightInFlight, and UniValue::VOBJ.
getpoolinfo()
UniValue getpoolinfo (const UniValue & params, bool fHelp)
Definition at line 70 of file masternode.cpp.
References masternode_info_t::addr, fMasterNode, CPrivateSendClient::fPrivateSendMultiSession, CPrivateSendBase::GetEntriesCount(), CPrivateSendClient::GetMixingMasternodeInfo(), CPrivateSendBase::GetQueueSize(), CPrivateSendBase::GetStateString(), CPrivateSendClient::GetStatus(), CWallet::nKeysLeftSinceAutoBackup, Pair(), CTxIn::prevout, PRIVATESEND_KEYS_THRESHOLD_WARNING, privateSendClient, privateSendServer, UniValue::push_back(), pwalletMain, UniValue::size(), CService::ToString(), COutPoint::ToStringShort(), masternode_info_t::vin, and UniValue::VOBJ.
getrawchangeaddress()
UniValue getrawchangeaddress (const UniValue & params, bool fHelp)
Definition at line 224 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), CPubKey::GetID(), CReserveKey::GetReservedKey(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsLocked(), JSONRPCError(), CReserveKey::KeepKey(), LOCK2, NullUniValue, pwalletMain, RPC_WALLET_KEYPOOL_RAN_OUT, UniValue::size(), CWallet::TopUpKeyPool(), and CBase58Data::ToString().
getrawmempool()
UniValue getrawmempool (const UniValue & params, bool fHelp)
Definition at line 238 of file blockchain.cpp.
References CURRENCY_UNIT, HelpExampleCli(), HelpExampleRpc(), mempoolToJSON(), and UniValue::size().
getrawtransaction()
UniValue getrawtransaction (const UniValue & params, bool fHelp)
Definition at line 144 of file rawtransaction.cpp.
References cs_main, CURRENCY_UNIT, EncodeHexTx(), GetTransaction(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, Pair(), Params(), ParseHashV(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), TxToJSON(), and UniValue::VOBJ.
getreceivedbyaccount()
UniValue getreceivedbyaccount (const UniValue & params, bool fHelp)
Definition at line 701 of file rpcwallet.cpp.
References AccountFromValue(), CheckFinalTx(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), ExtractDestination(), UniValue::get_bool(), CWallet::GetAccountAddresses(), CMerkleTx::GetDepthInMainChain(), HelpExampleCli(), HelpExampleRpc(), CTransaction::IsCoinBase(), IsMine(), LOCK2, CWallet::mapWallet, nInstantSendDepth, NullUniValue, CTxOut::nValue, pwalletMain, CTxOut::scriptPubKey, UniValue::size(), ValueFromAmount(), and CTransaction::vout.
getreceivedbyaddress()
UniValue getreceivedbyaddress (const UniValue & params, bool fHelp)
Definition at line 641 of file rpcwallet.cpp.
References CheckFinalTx(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), CBitcoinAddress::Get(), UniValue::get_bool(), CMerkleTx::GetDepthInMainChain(), GetScriptForDestination(), HelpExampleCli(), HelpExampleRpc(), CTransaction::IsCoinBase(), IsMine(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, CWallet::mapWallet, nInstantSendDepth, NullUniValue, CTxOut::nValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, CTxOut::scriptPubKey, UniValue::size(), ValueFromAmount(), and CTransaction::vout.
getspentinfo()
UniValue getspentinfo (const UniValue & params, bool fHelp)
Definition at line 957 of file misc.cpp.
References CSpentIndexValue::blockHeight, find_value(), UniValue::get_int(), base_blob< BITS >::GetHex(), GetSpentIndex(), HelpExampleCli(), HelpExampleRpc(), CSpentIndexValue::inputIndex, UniValue::isNum(), UniValue::isObject(), UniValue::isStr(), JSONRPCError(), Pair(), ParseHashV(), UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), CSpentIndexValue::txid, and UniValue::VOBJ.
getsuperblockbudget()
UniValue getsuperblockbudget (const UniValue & params, bool fHelp)
Definition at line 968 of file governance.cpp.
References CURRENCY_UNIT, FormatMoney(), UniValue::get_int(), CSuperblock::GetPaymentsLimit(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), RPC_INVALID_PARAMETER, and UniValue::size().
gettransaction()
UniValue gettransaction (const UniValue & params, bool fHelp)
Definition at line 1821 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EncodeHexTx(), EnsureWalletIsAvailable(), CWalletTx::GetCredit(), CWalletTx::GetDebit(), CTransaction::GetValueOut(), HelpExampleCli(), HelpExampleRpc(), CWalletTx::IsFromMe(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, JSONRPCError(), ListTransactions(), LOCK2, CWallet::mapWallet, NullUniValue, Pair(), UniValue::push_back(), pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, base_blob< BITS >::SetHex(), UniValue::size(), ValueFromAmount(), UniValue::VARR, UniValue::VOBJ, and WalletTxToJSON().
gettxout()
UniValue gettxout (const UniValue & params, bool fHelp)
Definition at line 662 of file blockchain.cpp.
References CTxMemPool::cs, cs_main, CURRENCY_UNIT, Coin::fCoinBase, UniValue::get_int(), UniValue::get_str(), CCoinsViewCache::GetBestBlock(), CBlockIndex::GetBlockHash(), CCoinsViewCache::GetCoin(), CCoinsViewMemPool::GetCoin(), base_blob< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), CTxMemPool::isSpent(), LOCK, mapBlockIndex, mempool, MEMPOOL_HEIGHT, Coin::nHeight, CBlockIndex::nHeight, NullUniValue, CTxOut::nValue, Coin::out, Pair(), pcoinsTip, UniValue::push_back(), CTxOut::scriptPubKey, ScriptPubKeyToJSON(), UniValue::size(), uint256S(), ValueFromAmount(), and UniValue::VOBJ.
gettxoutproof()
UniValue gettxoutproof (const UniValue & params, bool fHelp)
Definition at line 235 of file rawtransaction.cpp.
References AccessByTxid(), CDataStream::begin(), chainActive, cs_main, CDataStream::end(), UniValue::get_array(), UniValue::get_str(), CTransaction::GetHash(), GetTransaction(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), HexStr(), IsHex(), base_blob< BITS >::IsNull(), Coin::IsSpent(), JSONRPCError(), LOCK, mapBlockIndex, Coin::nHeight, Params(), pcoinsTip, PROTOCOL_VERSION, ReadBlockFromDisk(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, SER_NETWORK, UniValue::size(), uint256S(), and CBlock::vtx.
gettxoutsetinfo()
UniValue gettxoutsetinfo (const UniValue & params, bool fHelp)
Definition at line 624 of file blockchain.cpp.
References FlushStateToDisk(), base_blob< BITS >::GetHex(), GetUTXOStats(), CCoinsStats::hashBlock, CCoinsStats::hashSerialized, HelpExampleCli(), HelpExampleRpc(), CCoinsStats::nDiskSize, CCoinsStats::nHeight, CCoinsStats::nTotalAmount, CCoinsStats::nTransactionOutputs, CCoinsStats::nTransactions, Pair(), pcoinsdbview, UniValue::push_back(), UniValue::size(), ValueFromAmount(), and UniValue::VOBJ.
getunconfirmedbalance()
UniValue getunconfirmedbalance (const UniValue & params, bool fHelp)
Definition at line 869 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), CWallet::GetUnconfirmedBalance(), LOCK2, NullUniValue, pwalletMain, UniValue::size(), and ValueFromAmount().
getwalletinfo()
UniValue getwalletinfo (const UniValue & params, bool fHelp)
Definition at line 2376 of file rpcwallet.cpp.
References CHDChain::CountAccounts(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), CHDChain::GetAccount(), CWallet::GetBalance(), CFeeRate::GetFeePerK(), CCryptoKeyStore::GetHDChain(), base_blob< BITS >::GetHex(), CHDChain::GetID(), CWallet::GetImmatureBalance(), CWallet::GetOldestKeyPoolTime(), CWallet::GetUnconfirmedBalance(), CWallet::GetVersion(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), CWallet::KeypoolCountExternalKeys(), CWallet::KeypoolCountInternalKeys(), LOCK2, CWallet::mapWallet, CHDAccount::nExternalChainCounter, CHDAccount::nInternalChainCounter, CWallet::nKeysLeftSinceAutoBackup, NullUniValue, nWalletUnlockTime, Pair(), payTxFee, UniValue::push_back(), pwalletMain, UniValue::size(), strprintf, ValueFromAmount(), UniValue::VARR, and UniValue::VOBJ.
gobject()
UniValue gobject (const UniValue & params, bool fHelp)
Definition at line 28 of file governance.cpp.
References activeMasternode, CGovernanceManager::AddGovernanceObject(), CGovernanceManager::AddPostponedObject(), CWallet::CommitTransaction(), CGovernanceVoting::ConvertVoteOutcome(), CGovernanceVoting::ConvertVoteSignal(), CGovernanceManager::cs, cs_main, DBG, ENABLE_WALLET, CGovernanceManager::FindGovernanceObject(), g_connman, CMasternodeMan::Get(), UniValue::get_str(), CGovernanceObject::GetAbsoluteYesCount(), CGovernanceObject::GetAbstainCount(), GetAdjustedTime(), CMasternodeConfig::CMasternodeEntry::getAlias(), CGovernanceManager::GetAllNewerThan(), CWallet::GetBudgetSystemCollateralTX(), CGovernanceObject::GetCollateralHash(), CGovernanceObject::GetCreationTime(), CGovernanceManager::GetCurrentVotes(), CGovernanceObject::GetDataAsHex(), CGovernanceObject::GetDataAsString(), CMasternodeConfig::getEntries(), CProposalValidator::GetErrorMessages(), CGovernanceObject::GetHash(), CGovernanceVote::GetHash(), CPubKey::GetHash(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), CMessageSigner::GetKeysFromSecret(), CGovernanceManager::GetLastDiffTime(), CGovernanceObject::GetMasternodeVin(), CGovernanceManager::GetMatchingVotes(), CGovernanceException::GetMessage(), CGovernanceObject::GetMinCollateralFee(), CGovernanceObject::GetNoCount(), CGovernanceObject::GetObjectType(), CMasternodeConfig::CMasternodeEntry::getOutputIndex(), CMasternodeConfig::CMasternodeEntry::getPrivKey(), GetTime(), CMasternodeConfig::CMasternodeEntry::getTxHash(), CGovernanceObject::GetYesCount(), governance, GOVERNANCE_OBJECT_PROPOSAL, GOVERNANCE_OBJECT_TRIGGER, GOVERNANCE_OBJECT_WATCHDOG, CMasternodeMan::Has(), CMasternodeSync::IsBlockchainSynced(), CGovernanceObject::IsSetCachedDelete(), CGovernanceObject::IsSetCachedEndorsed(), CGovernanceObject::IsSetCachedFunding(), CGovernanceObject::IsSetCachedValid(), CGovernanceObject::IsValidLocally(), JSONRPCError(), CActiveMasternode::keyMasternode, LOCK, LOCK2, LogPrintf, masternodeConfig, CGovernanceManager::MasternodeRateCheck(), masternodeSync, mnodeman, NullUniValue, CActiveMasternode::outpoint, Pair(), ParseHashV(), ParseHex(), ParseInt32(), CTxIn::prevout, CGovernanceManager::ProcessVoteAndRelay(), CActiveMasternode::pubKeyMasternode, UniValue::push_back(), pwalletMain, CGovernanceObject::Relay(), RPC_CLIENT_IN_INITIAL_DOWNLOAD, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, base_blob< BITS >::SetHex(), CGovernanceObject::SetMasternodeVin(), CGovernanceVote::Sign(), CGovernanceObject::Sign(), UniValue::size(), strprintf, base_blob< BITS >::ToString(), CGovernanceVote::ToString(), CGovernanceManager::ToString(), COutPoint::ToStringShort(), NetMsgType::TX, CGovernanceManager::UpdateLastDiffTime(), CProposalValidator::Validate(), masternode_info_t::vin, UniValue::VOBJ, VOTE_OUTCOME_NONE, VOTE_SIGNAL_DELETE, VOTE_SIGNAL_ENDORSED, VOTE_SIGNAL_FUNDING, VOTE_SIGNAL_NONE, and VOTE_SIGNAL_VALID.
HelpExampleCli()
std::string HelpExampleCli (const std::string & methodname, const std::string & args)
Definition at line 581 of file server.cpp.
Referenced by abandontransaction(), addmultisigaddress(), addnode(), backupwallet(), clearbanned(), createmultisig(), createrawtransaction(), debug(), decoderawtransaction(), decodescript(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), estimatefee(), estimatepriority(), estimatesmartfee(), estimatesmartpriority(), fundrawtransaction(), generate(), getaccount(), getaccountaddress(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getaddressesbyaccount(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getbalance(), getbestblockhash(), getblock(), getblockchaininfo(), getblockcount(), getblockhash(), getblockhashes(), getblockheader(), getblockheaders(), getblocktemplate(), getchaintips(), getconnectioncount(), getdifficulty(), getgenerate(), getgovernanceinfo(), getinfo(), getmempoolinfo(), getmininginfo(), getnettotals(), getnetworkhashps(), getnetworkinfo(), getnewaddress(), getpeerinfo(), getrawchangeaddress(), getrawmempool(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), getspentinfo(), getsuperblockbudget(), gettransaction(), gettxout(), gettxoutproof(), gettxoutsetinfo(), getwalletinfo(), importaddress(), importelectrumwallet(), importprivkey(), importpubkey(), importwallet(), instantsendtoaddress(), invalidateblock(), keypoolrefill(), listaccounts(), listaddressgroupings(), listbanned(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), movecmd(), ping(), prioritisetransaction(), reconsiderblock(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), sentinelping(), setaccount(), setban(), setgenerate(), settxfee(), signmessage(), signrawtransaction(), submitblock(), validateaddress(), verifychain(), verifymessage(), verifytxoutproof(), walletlock(), walletpassphrase(), and walletpassphrasechange().
HelpExampleRpc()
std::string HelpExampleRpc (const std::string & methodname, const std::string & args)
Definition at line 586 of file server.cpp.
Referenced by abandontransaction(), addmultisigaddress(), addnode(), backupwallet(), clearbanned(), createmultisig(), createrawtransaction(), debug(), decoderawtransaction(), decodescript(), disconnectnode(), dumphdinfo(), dumpprivkey(), dumpwallet(), encryptwallet(), getaccount(), getaccountaddress(), getaddednodeinfo(), getaddressbalance(), getaddressdeltas(), getaddressesbyaccount(), getaddressmempool(), getaddresstxids(), getaddressutxos(), getbalance(), getbestblockhash(), getblock(), getblockchaininfo(), getblockcount(), getblockhash(), getblockhashes(), getblockheader(), getblockheaders(), getblocktemplate(), getchaintips(), getconnectioncount(), getdifficulty(), getgenerate(), getgovernanceinfo(), getinfo(), getmempoolinfo(), getmininginfo(), getnettotals(), getnetworkhashps(), getnetworkinfo(), getnewaddress(), getpeerinfo(), getrawchangeaddress(), getrawmempool(), getrawtransaction(), getreceivedbyaccount(), getreceivedbyaddress(), getspentinfo(), getsuperblockbudget(), gettransaction(), gettxout(), gettxoutproof(), gettxoutsetinfo(), getwalletinfo(), importaddress(), importelectrumwallet(), importprivkey(), importpubkey(), importwallet(), instantsendtoaddress(), invalidateblock(), keypoolrefill(), listaccounts(), listaddressgroupings(), listbanned(), listlockunspent(), listreceivedbyaccount(), listreceivedbyaddress(), listsinceblock(), listtransactions(), listunspent(), lockunspent(), movecmd(), ping(), prioritisetransaction(), reconsiderblock(), sendfrom(), sendmany(), sendrawtransaction(), sendtoaddress(), sentinelping(), setaccount(), setban(), setgenerate(), settxfee(), signmessage(), signrawtransaction(), submitblock(), validateaddress(), verifychain(), verifymessage(), verifytxoutproof(), walletlock(), walletpassphrase(), and walletpassphrasechange().
HelpRequiringPassphrase()
std::string HelpRequiringPassphrase ()
Definition at line 35 of file rpcwallet.cpp.
References CCryptoKeyStore::IsCrypted(), and pwalletMain.
Referenced by instantsendtoaddress(), keypoolrefill(), sendfrom(), sendmany(), sendtoaddress(), signmessage(), signrawtransaction(), and spork().
importaddress()
UniValue importaddress (const UniValue & params, bool fHelp)
Definition at line 181 of file rpcdump.cpp.
References chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), fPruneMode, CChain::Genesis(), HelpExampleCli(), HelpExampleRpc(), ImportAddress(), ImportScript(), IsHex(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, NullUniValue, ParseHex(), pwalletMain, CWallet::ReacceptWalletTransactions(), RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), and UniValue::size().
importelectrumwallet()
UniValue importelectrumwallet (const UniValue & params, bool fHelp)
Definition at line 412 of file rpcdump.cpp.
References _(), CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), fPruneMode, UniValue::get_str(), CPubKey::GetID(), CBitcoinSecret::GetKey(), UniValue::getKeys(), CKey::GetPubKey(), CWallet::HaveKey(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, LogPrintf, CWallet::nTimeFirstKey, NullUniValue, pwalletMain, UniValue::read(), RPC_INVALID_PARAMETER, RPC_TYPE_ERROR, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CBitcoinSecret::SetString(), CWallet::ShowProgress, UniValue::size(), CKey::VerifyPubKey(), and UniValue::VOBJ.
importprivkey()
UniValue importprivkey (const UniValue & params, bool fHelp)
Definition at line 76 of file rpcdump.cpp.
References CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), fPruneMode, CChain::Genesis(), UniValue::get_str(), CPubKey::GetID(), CBitcoinSecret::GetKey(), CKey::GetPubKey(), CWallet::HaveKey(), HelpExampleCli(), HelpExampleRpc(), CKey::IsValid(), JSONRPCError(), LOCK2, CWallet::mapKeyMetadata, CWallet::MarkDirty(), CWallet::nTimeFirstKey, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CWallet::SetAddressBook(), CBitcoinSecret::SetString(), UniValue::size(), and CKey::VerifyPubKey().
importpubkey()
UniValue importpubkey (const UniValue & params, bool fHelp)
Definition at line 247 of file rpcdump.cpp.
References chainActive, cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), fPruneMode, CChain::Genesis(), GetScriptForRawPubKey(), HelpExampleCli(), HelpExampleRpc(), ImportAddress(), ImportScript(), IsHex(), JSONRPCError(), LOCK2, NullUniValue, ParseHex(), pwalletMain, CWallet::ReacceptWalletTransactions(), RPC_INVALID_ADDRESS_OR_KEY, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), and UniValue::size().
importwallet()
UniValue importwallet (const UniValue & params, bool fHelp)
Definition at line 305 of file rpcdump.cpp.
References _(), CWallet::AddKeyPubKey(), chainActive, cs_main, CWallet::cs_wallet, DecodeDumpString(), DecodeDumpTime(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), fPruneMode, CBlockIndex::GetBlockTime(), CPubKey::GetID(), CBitcoinSecret::GetKey(), CKey::GetPubKey(), CWallet::HaveKey(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK2, LogPrintf, CWallet::mapKeyMetadata, CWallet::MarkDirty(), CBlockIndex::nHeight, CWallet::nTimeFirstKey, NullUniValue, CBlockIndex::pprev, pwalletMain, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, CWallet::ScanForWalletTransactions(), CWallet::SetAddressBook(), CBitcoinSecret::SetString(), CWallet::ShowProgress, UniValue::size(), CChain::Tip(), and CKey::VerifyPubKey().
instantsendtoaddress()
UniValue instantsendtoaddress (const UniValue & params, bool fHelp)
Definition at line 476 of file rpcwallet.cpp.
References AmountFromValue(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CBitcoinAddress::Get(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), UniValue::isNull(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, CWalletTx::mapValue, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, SendMoney(), and UniValue::size().
InterruptRPC()
void InterruptRPC ()
Definition at line 438 of file server.cpp.
References fRPCRunning, and LogPrint().
Referenced by Interrupt().
invalidateblock()
UniValue invalidateblock (const UniValue & params, bool fHelp)
Definition at line 1054 of file blockchain.cpp.
References ActivateBestChain(), cs_main, UniValue::get_str(), CValidationState::GetRejectReason(), HelpExampleCli(), HelpExampleRpc(), InvalidateBlock(), CValidationState::IsValid(), JSONRPCError(), LOCK, mapBlockIndex, NullUniValue, Params(), RPC_DATABASE_ERROR, RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and uint256S().
IsRPCRunning()
bool IsRPCRunning ()
Query whether RPC is running.
Definition at line 452 of file server.cpp.
References fRPCRunning.
Referenced by getblocktemplate().
JSONRPCExecBatch()
std::string JSONRPCExecBatch (const UniValue & vReq)
Definition at line 532 of file server.cpp.
References JSONRPCExecOne(), UniValue::push_back(), UniValue::size(), UniValue::VARR, and UniValue::write().
Referenced by HTTPReq_JSONRPC().
keepass()
UniValue keepass (const UniValue & params, bool fHelp)
Definition at line 2455 of file rpcwallet.cpp.
References CKeePassIntegrator::generateKeePassKey(), keePassInt, CKeePassIntegrator::rpcAssociate(), UniValue::size(), and CKeePassIntegrator::updatePassphrase().
keypoolrefill()
UniValue keypoolrefill (const UniValue & params, bool fHelp)
Definition at line 1963 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, DEFAULT_KEYPOOL_SIZE, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CWallet::GetKeyPoolSize(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), CWallet::IsHDEnabled(), itostr(), JSONRPCError(), LOCK2, NullUniValue, pwalletMain, RPC_INVALID_PARAMETER, RPC_WALLET_ERROR, UniValue::size(), and CWallet::TopUpKeyPool().
listaccounts()
UniValue listaccounts (const UniValue & params, bool fHelp)
Definition at line 1645 of file rpcwallet.cpp.
References COutputEntry::amount, cs_main, CWallet::cs_wallet, COutputEntry::destination, EnsureWalletIsAvailable(), UniValue::get_bool(), CWalletTx::GetAmounts(), CMerkleTx::GetBlocksToMaturity(), CMerkleTx::GetDepthInMainChain(), HelpExampleCli(), HelpExampleRpc(), IsMine(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, CWallet::laccentries, LOCK2, CWallet::mapAddressBook, CWallet::mapWallet, CAddressBookData::name, CAccountingEntry::nCreditDebit, nInstantSendDepth, NullUniValue, Pair(), PAIRTYPE, UniValue::push_back(), pwalletMain, UniValue::size(), CAccountingEntry::strAccount, ValueFromAmount(), and UniValue::VOBJ.
listaddressgroupings()
UniValue listaddressgroupings (const UniValue & params, bool fHelp)
Definition at line 534 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), HelpExampleCli(), HelpExampleRpc(), LOCK2, CWallet::mapAddressBook, NullUniValue, UniValue::push_back(), pwalletMain, ValueFromAmount(), and UniValue::VARR.
listbanned()
UniValue listbanned (const UniValue & params, bool fHelp)
Definition at line 529 of file net.cpp.
References CBanEntry::banReasonToString(), g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), CBanEntry::nBanUntil, CBanEntry::nCreateTime, Pair(), UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
listlockunspent()
UniValue listlockunspent (const UniValue & params, bool fHelp)
Definition at line 2300 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), base_blob< BITS >::GetHex(), COutPoint::hash, HelpExampleCli(), HelpExampleRpc(), CWallet::ListLockedCoins(), LOCK2, COutPoint::n, NullUniValue, Pair(), UniValue::push_back(), pwalletMain, UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
listreceivedbyaccount()
UniValue listreceivedbyaccount (const UniValue & params, bool fHelp)
Definition at line 1380 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), HelpExampleCli(), HelpExampleRpc(), ListReceived(), LOCK2, nInstantSendDepth, NullUniValue, pwalletMain, and UniValue::size().
listreceivedbyaddress()
UniValue listreceivedbyaddress (const UniValue & params, bool fHelp)
Definition at line 1339 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), HelpExampleCli(), HelpExampleRpc(), ListReceived(), LOCK2, nInstantSendDepth, NullUniValue, pwalletMain, and UniValue::size().
listsinceblock()
UniValue listsinceblock (const UniValue & params, bool fHelp)
Definition at line 1726 of file rpcwallet.cpp.
References chainActive, cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), UniValue::get_int(), CBlockIndex::GetBlockHash(), CMerkleTx::GetDepthInMainChain(), base_blob< BITS >::GetHex(), CChain::Height(), HelpExampleCli(), HelpExampleRpc(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, JSONRPCError(), ListTransactions(), LOCK2, mapBlockIndex, CWallet::mapWallet, CBlockIndex::nHeight, NullUniValue, Pair(), UniValue::push_back(), pwalletMain, RPC_INVALID_PARAMETER, base_blob< BITS >::SetHex(), UniValue::size(), UniValue::VARR, and UniValue::VOBJ.
listtransactions()
UniValue listtransactions (const UniValue & params, bool fHelp)
Definition at line 1518 of file rpcwallet.cpp.
References AcentryToJSON(), UniValue::clear(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), UniValue::getValues(), HelpExampleCli(), HelpExampleRpc(), ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, JSONRPCError(), ListTransactions(), LOCK2, NullUniValue, UniValue::push_backV(), pwalletMain, RPC_INVALID_PARAMETER, UniValue::setArray(), UniValue::size(), UniValue::VARR, and CWallet::wtxOrdered.
listunspent()
UniValue listunspent (const UniValue & params, bool fHelp)
Definition at line 2533 of file rpcwallet.cpp.
References CWallet::AvailableCoins(), prevector< N, T, Size, Diff >::begin(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, prevector< N, T, Size, Diff >::end(), EnsureWalletIsAvailable(), ExtractDestination(), COutput::fSolvable, COutput::fSpendable, UniValue::get_array(), UniValue::get_str(), CBasicKeyStore::GetCScript(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), CWallet::GetOutpointPrivateSendRounds(), HelpExampleCli(), HelpExampleRpc(), HexStr(), COutput::i, CScript::IsPayToScriptHash(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, COutput::nDepth, NullUniValue, Pair(), UniValue::push_back(), pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPCTypeCheck(), UniValue::size(), COutput::tx, ValueFromAmount(), UniValue::VARR, UniValue::VNUM, UniValue::VOBJ, and CTransaction::vout.
lockunspent()
UniValue lockunspent (const UniValue & params, bool fHelp)
Definition at line 2216 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), find_value(), UniValue::get_array(), UniValue::get_bool(), UniValue::get_int(), UniValue::get_obj(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), IsHex(), UniValue::isObject(), JSONRPCError(), LOCK2, CWallet::LockCoin(), NullUniValue, pwalletMain, RPC_INVALID_PARAMETER, RPCTypeCheck(), RPCTypeCheckObj(), UniValue::size(), uint256S(), CWallet::UnlockAllCoins(), CWallet::UnlockCoin(), UniValue::VARR, UniValue::VBOOL, UniValue::VNUM, and UniValue::VSTR.
masternode()
UniValue masternode (const UniValue & params, bool fHelp)
Definition at line 109 of file masternode.cpp.
References activeMasternode, masternode_info_t::addr, atoi(), CWallet::AvailableCoins(), chainActive, CMasternodeMan::CountEnabled(), CMasternodeBroadcast::Create(), cs_main, CWallet::cs_wallet, ENABLE_WALLET, EnsureWalletIsUnlocked(), fMasterNode, g_connman, CMasternodeMan::Get(), UniValue::get_str(), CMasternodeConfig::CMasternodeEntry::getAlias(), CMasternodeConfig::getEntries(), CTransaction::GetHash(), CPubKey::GetID(), CMasternodeConfig::CMasternodeEntry::getIp(), CMasternodeMan::GetNextMasternodeInQueueForPayment(), CMasternodeConfig::CMasternodeEntry::getOutputIndex(), CMasternodeConfig::CMasternodeEntry::getPrivKey(), GetRequiredPaymentsString(), CActiveMasternode::GetStatus(), CMasternodeConfig::CMasternodeEntry::getTxHash(), COutput::i, CMasternodeSync::IsMasternodeListSynced(), JSONRPCError(), LOCK, Lookup(), CKey::MakeNewKey(), masternodeConfig, masternodelist(), masternodeSync, MIN_PRIVATESEND_PEER_PROTO_VERSION, mnodeman, CBlockIndex::nHeight, NODE_NETWORK, CMasternodeMan::NotifyMasternodeUpdates(), masternode_info_t::nProtocolVersion, masternode_info_t::nTimeLastPing, NullUniValue, ONLY_1000, CActiveMasternode::outpoint, Pair(), CTxIn::prevout, masternode_info_t::pubKeyCollateralAddress, UniValue::push_back(), pwalletMain, CMasternodeBroadcast::Relay(), RPC_CLIENT_IN_INITIAL_DOWNLOAD, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, CActiveMasternode::service, masternode_info_t::sigTime, UniValue::size(), CMasternodeMan::size(), strprintf, CChain::Tip(), base_blob< BITS >::ToString(), CBase58Data::ToString(), CService::ToString(), COutPoint::ToStringShort(), COutput::tx, uint256S(), CMasternodeMan::UpdateLastPaid(), CMasternodeMan::UpdateMasternodeList(), UniValue::VARR, masternode_info_t::vin, and UniValue::VOBJ.
masternodebroadcast()
UniValue masternodebroadcast (const UniValue & params, bool fHelp)
Definition at line 596 of file masternode.cpp.
References masternode_info_t::addr, CDataStream::begin(), CMasternodePing::blockHash, CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CMasternodeBroadcast::CheckSignature(), CMasternodeBroadcast::Create(), CWallet::cs_wallet, DecodeHexVecMnb(), ENABLE_WALLET, EncodeBase64(), CDataStream::end(), EnsureWalletIsUnlocked(), fImporting, fReindex, g_connman, UniValue::get_str(), CMasternodeConfig::CMasternodeEntry::getAlias(), CMasternodeConfig::getEntries(), CMasternodeBroadcast::GetHash(), CPubKey::GetID(), CMasternodeConfig::CMasternodeEntry::getIp(), CMasternodeConfig::CMasternodeEntry::getOutputIndex(), CMasternodeConfig::CMasternodeEntry::getPrivKey(), CMasternodeConfig::CMasternodeEntry::getTxHash(), HexStr(), JSONRPCError(), CMasternode::lastPing, LOCK, masternodeConfig, mnodeman, masternode_info_t::nLastDsq, CMasternodeMan::NotifyMasternodeUpdates(), masternode_info_t::nProtocolVersion, NullUniValue, Pair(), CTxIn::prevout, PROTOCOL_VERSION, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, UniValue::push_back(), pwalletMain, CMasternodeBroadcast::Relay(), RPC_DESERIALIZATION_ERROR, RPC_INTERNAL_ERROR, RPC_INVALID_PARAMETER, SER_NETWORK, CMasternodePing::sigTime, masternode_info_t::sigTime, UniValue::size(), strprintf, base_blob< BITS >::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeMan::UpdateMasternodeList(), CMasternodePing::vchSig, CMasternode::vchSig, CMasternodePing::vin, masternode_info_t::vin, and UniValue::VOBJ.
masternodelist()
UniValue masternodelist (const UniValue & params, bool fHelp)
Definition at line 443 of file masternode.cpp.
References masternode_info_t::addr, chainActive, cs_main, CMasternodePing::fSentinelIsCurrent, CMasternodeMan::GetFullMasternodeMap(), CPubKey::GetID(), CMasternode::GetLastPaidBlock(), CMasternode::GetLastPaidTime(), CMasternodeMan::GetMasternodeRanks(), CMasternode::GetStatus(), HexStr(), CMasternode::lastPing, LOCK, mnodeman, masternode_info_t::nProtocolVersion, CMasternodePing::nSentinelVersion, Pair(), PAIRTYPE, CTxIn::prevout, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, UniValue::push_back(), SafeIntVersionToString(), CMasternodePing::sigTime, masternode_info_t::sigTime, UniValue::size(), strprintf, CChain::Tip(), CBase58Data::ToString(), CService::ToString(), COutPoint::ToStringShort(), CMasternodeMan::UpdateLastPaid(), masternode_info_t::vin, and UniValue::VOBJ.
Referenced by masternode().
mnsync()
UniValue mnsync (const UniValue & params, bool fHelp)
Definition at line 144 of file misc.cpp.
References g_connman, UniValue::get_str(), CMasternodeSync::GetAssetID(), CMasternodeSync::GetAssetName(), CMasternodeSync::GetAssetStartTime(), CMasternodeSync::GetAttempt(), CMasternodeSync::IsBlockchainSynced(), CMasternodeSync::IsFailed(), CMasternodeSync::IsMasternodeListSynced(), CMasternodeSync::IsSynced(), CMasternodeSync::IsWinnersListSynced(), masternodeSync, Pair(), UniValue::push_back(), CMasternodeSync::Reset(), UniValue::size(), CMasternodeSync::SwitchToNextAsset(), and UniValue::VOBJ.
movecmd()
UniValue movecmd (const UniValue & params, bool fHelp)
Definition at line 885 of file rpcwallet.cpp.
References AccountFromValue(), CWallet::AddAccountingEntry(), AmountFromValue(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), UniValue::get_int(), GetAdjustedTime(), HelpExampleCli(), HelpExampleRpc(), CWallet::IncOrderPosNext(), JSONRPCError(), LOCK2, CAccountingEntry::nCreditDebit, CAccountingEntry::nOrderPos, CAccountingEntry::nTime, NullUniValue, pwalletMain, RPC_DATABASE_ERROR, RPC_TYPE_ERROR, UniValue::size(), CAccountingEntry::strAccount, CAccountingEntry::strComment, CAccountingEntry::strOtherAccount, CWallet::strWalletFile, CDB::TxnBegin(), and CDB::TxnCommit().
ParseHashO()
uint256 ParseHashO (const UniValue & o, std::string strKey)
ParseHashV()
uint256 ParseHashV (const UniValue & v, std::string strName)
Utilities: convert hex-encoded Values (throws error if not hex).
ParseHexO()
std::vector<unsigned char> ParseHexO (const UniValue & o, std::string strKey)
ParseHexV()
std::vector<unsigned char> ParseHexV (const UniValue & v, std::string strName)
ping()
UniValue ping (const UniValue & params, bool fHelp)
Definition at line 47 of file net.cpp.
References CNode::fPingQueued, g_connman, HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), NullUniValue, RPC_CLIENT_P2P_DISABLED, and UniValue::size().
prioritisetransaction()
UniValue prioritisetransaction (const UniValue & params, bool fHelp)
Definition at line 281 of file mining.cpp.
References cs_main, UniValue::get_int64(), HelpExampleCli(), HelpExampleRpc(), LOCK, mempool, ParseHashStr(), CTxMemPool::PrioritiseTransaction(), and UniValue::size().
privatesend()
UniValue privatesend (const UniValue & params, bool fHelp)
reconsiderblock()
UniValue reconsiderblock (const UniValue & params, bool fHelp)
Definition at line 1092 of file blockchain.cpp.
References ActivateBestChain(), cs_main, UniValue::get_str(), CValidationState::GetRejectReason(), HelpExampleCli(), HelpExampleRpc(), CValidationState::IsValid(), JSONRPCError(), LOCK, mapBlockIndex, NullUniValue, Params(), ReconsiderBlock(), RPC_DATABASE_ERROR, RPC_INVALID_ADDRESS_OR_KEY, UniValue::size(), and uint256S().
resendwallettransactions()
UniValue resendwallettransactions (const UniValue & params, bool fHelp)
Definition at line 2505 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), g_connman, GetTime(), JSONRPCError(), LOCK2, NullUniValue, UniValue::push_back(), pwalletMain, CWallet::ResendWalletTransactionsBefore(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), base_blob< BITS >::ToString(), and UniValue::VARR.
RPCIsInWarmup()
bool RPCIsInWarmup (std::string * statusOut)
Definition at line 470 of file server.cpp.
References cs_rpcWarmup, fRPCInWarmup, LOCK, and rpcWarmupStatus().
Referenced by CheckWarmup().
RPCRegisterTimerInterface()
void RPCRegisterTimerInterface (RPCTimerInterface * iface)
Register factory function for timers.
Definition at line 592 of file server.cpp.
References timerInterfaces.
Referenced by RPCConsole::RPCConsole(), and StartHTTPRPC().
RPCRunLater()
void RPCRunLater (const std::string & name, boost::function< void(void)> func, int64_t nSeconds)
Run func nSeconds from now.
Overrides previous timer <name> (if any).
Definition at line 604 of file server.cpp.
References deadlineTimers, JSONRPCError(), LogPrint(), name, RPCTimerInterface::Name(), RPCTimerInterface::NewTimer(), RPC_INTERNAL_ERROR, and timerInterfaces.
Referenced by walletpassphrase().
RPCTypeCheck()
void RPCTypeCheck (const UniValue & params, const std::list< UniValue::VType > & typesExpected, bool fAllowNull = false)
Type-check arguments; throws JSONRPCError if wrong type given.
Does not check that the right number of arguments are passed, just that any passed are the correct type. Use like: RPCTypeCheck(params, boost::assign::list_of(str_type)(int_type)(obj_type));
RPCTypeCheckObj()
void RPCTypeCheckObj (const UniValue & o, const std::map< std::string, UniValue::VType > & typesExpected, bool fAllowNull = false)
RPCUnregisterTimerInterface()
void RPCUnregisterTimerInterface (RPCTimerInterface * iface)
Unregister factory function for timers.
Definition at line 597 of file server.cpp.
References timerInterfaces.
Referenced by StopHTTPRPC(), and RPCConsole::~RPCConsole().
sendfrom()
UniValue sendfrom (const UniValue & params, bool fHelp)
Definition at line 958 of file rpcwallet.cpp.
References AccountFromValue(), AmountFromValue(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CBitcoinAddress::Get(), UniValue::get_bool(), UniValue::get_str(), GetAccountBalance(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), ISMINE_SPENDABLE, UniValue::isNull(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, CWalletTx::mapValue, nInstantSendDepth, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, RPC_WALLET_INSUFFICIENT_FUNDS, SendMoney(), UniValue::size(), and CWalletTx::strFromAccount.
sendmany()
UniValue sendmany (const UniValue & params, bool fHelp)
Definition at line 1024 of file rpcwallet.cpp.
References AccountFromValue(), ALL_COINS, AmountFromValue(), CWallet::CommitTransaction(), CWallet::CreateTransaction(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), g_connman, CBitcoinAddress::Get(), UniValue::get_bool(), UniValue::get_obj(), UniValue::get_str(), GetAccountBalance(), CWallet::GetBroadcastTransactions(), CTransaction::GetHash(), base_blob< BITS >::GetHex(), UniValue::getKeys(), GetScriptForDestination(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), ISMINE_SPENDABLE, UniValue::isNull(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, CWalletTx::mapValue, nInstantSendDepth, NullUniValue, ONLY_DENOMINATED, prevector< N, T, Size, Diff >::push_back(), pwalletMain, RPC_CLIENT_P2P_DISABLED, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPC_TYPE_ERROR, RPC_WALLET_ERROR, RPC_WALLET_INSUFFICIENT_FUNDS, UniValue::size(), CWalletTx::strFromAccount, NetMsgType::TX, NetMsgType::TXLOCKREQUEST, and UniValue::VARR.
sendrawtransaction()
UniValue sendrawtransaction (const UniValue & params, bool fHelp)
Definition at line 831 of file rawtransaction.cpp.
References AcceptToMemoryPool(), CCoinsViewCache::AccessCoin(), cs_main, DecodeHexTx(), CTxMemPool::exists(), g_connman, CTransaction::GetHash(), base_blob< BITS >::GetHex(), CValidationState::GetRejectCode(), CValidationState::GetRejectReason(), HelpExampleCli(), HelpExampleRpc(), instantsend, CValidationState::IsInvalid(), Coin::IsSpent(), JSONRPCError(), LOCK, mempool, pcoinsTip, CInstantSend::ProcessTxLockRequest(), RPC_CLIENT_P2P_DISABLED, RPC_DESERIALIZATION_ERROR, RPC_TRANSACTION_ALREADY_IN_CHAIN, RPC_TRANSACTION_ERROR, RPC_TRANSACTION_REJECTED, RPCTypeCheck(), UniValue::size(), strprintf, UniValue::VBOOL, CTransaction::vout, and UniValue::VSTR.
sendtoaddress()
UniValue sendtoaddress (const UniValue & params, bool fHelp)
Definition at line 409 of file rpcwallet.cpp.
References AmountFromValue(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), CBitcoinAddress::Get(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), UniValue::isNull(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, CWalletTx::mapValue, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, SendMoney(), and UniValue::size().
sentinelping()
UniValue sentinelping (const UniValue & params, bool fHelp)
Definition at line 833 of file masternode.cpp.
References activeMasternode, HelpExampleCli(), HelpExampleRpc(), UniValue::size(), StringVersionToInt(), and CActiveMasternode::UpdateSentinelPing().
setaccount()
UniValue setaccount (const UniValue & params, bool fHelp)
Definition at line 259 of file rpcwallet.cpp.
References AccountFromValue(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), CBitcoinAddress::Get(), GetAccountAddress(), HelpExampleCli(), HelpExampleRpc(), IsMine(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, CWallet::mapAddressBook, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_MISC_ERROR, CWallet::SetAddressBook(), and UniValue::size().
setban()
UniValue setban (const UniValue & params, bool fHelp)
Definition at line 465 of file net.cpp.
References BanReasonManuallyAdded, g_connman, HelpExampleCli(), HelpExampleRpc(), UniValue::isNull(), UniValue::isTrue(), CNetAddr::IsValid(), CSubNet::IsValid(), JSONRPCError(), LookupHost(), LookupSubNet(), NullUniValue, RPC_CLIENT_NODE_ALREADY_ADDED, RPC_CLIENT_P2P_DISABLED, RPC_MISC_ERROR, and UniValue::size().
setgenerate()
UniValue setgenerate (const UniValue & params, bool fHelp)
Definition at line 192 of file mining.cpp.
References DEFAULT_GENERATE_THREADS, g_connman, GenerateBitcoins(), UniValue::get_int(), GetArg(), HelpExampleCli(), HelpExampleRpc(), itostr(), JSONRPCError(), mapArgs, CChainParams::MineBlocksOnDemand(), NullUniValue, Params(), RPC_METHOD_NOT_FOUND, and UniValue::size().
setmocktime()
UniValue setmocktime (const UniValue & params, bool fHelp)
Definition at line 507 of file misc.cpp.
References cs_main, LOCK, CChainParams::MineBlocksOnDemand(), NullUniValue, Params(), RPCTypeCheck(), SetMockTime(), UniValue::size(), and UniValue::VNUM.
setnetworkactive()
UniValue setnetworkactive (const UniValue & params, bool fHelp)
Definition at line 580 of file net.cpp.
References g_connman, JSONRPCError(), RPC_CLIENT_P2P_DISABLED, and UniValue::size().
SetRPCWarmupFinished()
void SetRPCWarmupFinished ()
Definition at line 463 of file server.cpp.
References cs_rpcWarmup, fRPCInWarmup, and LOCK.
Referenced by AppInit2().
SetRPCWarmupStatus()
void SetRPCWarmupStatus (const std::string & newStatus)
Set the RPC warmup status.
When this is done, all RPC calls will error out immediately with RPC_IN_WARMUP.
Definition at line 457 of file server.cpp.
References cs_rpcWarmup, LOCK, and rpcWarmupStatus().
Referenced by AppInit2().
settxfee()
UniValue settxfee (const UniValue & params, bool fHelp)
Definition at line 2349 of file rpcwallet.cpp.
References AmountFromValue(), cs_main, CWallet::cs_wallet, CURRENCY_UNIT, EnsureWalletIsAvailable(), HelpExampleCli(), HelpExampleRpc(), LOCK2, NullUniValue, payTxFee, pwalletMain, and UniValue::size().
signmessage()
UniValue signmessage (const UniValue & params, bool fHelp)
Definition at line 585 of file rpcwallet.cpp.
References cs_main, CWallet::cs_wallet, EncodeBase64(), EnsureWalletIsAvailable(), EnsureWalletIsUnlocked(), UniValue::get_str(), CHashWriter::GetHash(), CWallet::GetKey(), CBitcoinAddress::GetKeyID(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK2, NullUniValue, pwalletMain, RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, RPC_WALLET_ERROR, SER_GETHASH, CKey::SignCompact(), UniValue::size(), and strMessageMagic.
signrawtransaction()
UniValue signrawtransaction (const UniValue & params, bool fHelp)
Definition at line 589 of file rawtransaction.cpp.
References CCoinsViewCache::AccessCoin(), CCoinsViewCache::AddCoin(), CBasicKeyStore::AddCScript(), CKeyStore::AddKey(), CScript::clear(), CombineSignatures(), CTxMemPool::cs, cs_main, CWallet::cs_wallet, UniValue::empty(), CDataStream::empty(), ENABLE_WALLET, EncodeHexTx(), EnsureWalletIsUnlocked(), find_value(), UniValue::get_array(), UniValue::get_int(), UniValue::get_obj(), UniValue::get_str(), CBitcoinSecret::GetKey(), HelpExampleCli(), HelpExampleRpc(), HelpRequiringPassphrase(), UniValue::isNull(), UniValue::isObject(), Coin::IsSpent(), CKey::IsValid(), JSONRPCError(), LOCK, LOCK2, mempool, Coin::nHeight, CTxOut::nValue, Coin::out, Pair(), ParseHashO(), ParseHexO(), ParseHexV(), pcoinsTip, CTxIn::prevout, PROTOCOL_VERSION, UniValue::push_back(), pwalletMain, RPC_DESERIALIZATION_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, RPCTypeCheck(), RPCTypeCheckObj(), SCRIPT_ERR_OK, ScriptErrorString(), CTxOut::scriptPubKey, CTxIn::scriptSig, ScriptToAsmStr(), SER_NETWORK, CCoinsViewBacked::SetBackend(), CBitcoinSecret::SetString(), SIGHASH_ALL, SIGHASH_ANYONECANPAY, SIGHASH_NONE, SIGHASH_SINGLE, SignSignature(), UniValue::size(), STANDARD_SCRIPT_VERIFY_FLAGS, TxInErrorToJSON(), UniValue::VARR, VerifyScript(), CMutableTransaction::vin, UniValue::VNUM, UniValue::VOBJ, CMutableTransaction::vout, and UniValue::VSTR.
spork()
UniValue spork (const UniValue & params, bool fHelp)
Definition at line 226 of file misc.cpp.
References CSporkManager::ExecuteSpork(), g_connman, UniValue::get_int64(), UniValue::get_str(), CSporkManager::GetSporkIDByName(), CSporkManager::GetSporkNameByID(), CSporkManager::GetSporkValue(), HelpRequiringPassphrase(), CSporkManager::IsSporkActive(), JSONRPCError(), Pair(), UniValue::push_back(), RPC_CLIENT_P2P_DISABLED, UniValue::size(), SPORK_END, SPORK_START, sporkManager, CSporkManager::UpdateSpork(), and UniValue::VOBJ.
Referenced by CSporkManager::ProcessSpork(), CSporkManager::SetPrivKey(), and CSporkManager::UpdateSpork().
StartRPC()
bool StartRPC ()
Definition at line 430 of file server.cpp.
References fRPCRunning, g_rpcSignals, LogPrint(), and CRPCSignals::Started.
Referenced by AppInitServers().
StopRPC()
void StopRPC ()
Definition at line 445 of file server.cpp.
References deadlineTimers, g_rpcSignals, LogPrint(), and CRPCSignals::Stopped.
Referenced by PrepareShutdown().
submitblock()
UniValue submitblock (const UniValue & params, bool fHelp)
Definition at line 768 of file mining.cpp.
References BIP22ValidationResult(), BLOCK_FAILED_MASK, BLOCK_VALID_SCRIPTS, cs_main, DecodeHexBlk(), CBlockHeader::GetHash(), HelpExampleCli(), HelpExampleRpc(), CBlockIndex::IsValid(), JSONRPCError(), LOCK, mapBlockIndex, CBlockIndex::nStatus, Params(), ProcessNewBlock(), RegisterValidationInterface(), RPC_DESERIALIZATION_ERROR, UniValue::size(), and UnregisterValidationInterface().
validateaddress()
UniValue validateaddress (const UniValue & params, bool fHelp)
Definition at line 279 of file misc.cpp.
References prevector< N, T, Size, Diff >::begin(), cs_main, CWallet::cs_wallet, prevector< N, T, Size, Diff >::end(), CBitcoinAddress::Get(), CCryptoKeyStore::GetHDChain(), base_blob< BITS >::GetHex(), CHDChain::GetID(), CBitcoinAddress::GetKeyID(), GetScriptForDestination(), HelpExampleCli(), HelpExampleRpc(), HexStr(), IsMine(), ISMINE_NO, ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, CBitcoinAddress::IsValid(), LOCK, LOCK2, CWallet::mapAddressBook, CWallet::mapHdPubKeys, Pair(), UniValue::push_back(), UniValue::pushKVs(), pwalletMain, UniValue::size(), CBase58Data::ToString(), and UniValue::VOBJ.
ValueFromAmount()
UniValue ValueFromAmount (const CAmount & amount)
Definition at line 122 of file server.cpp.
References COIN, strprintf, and UniValue::VNUM.
Referenced by AcentryToJSON(), estimatefee(), estimatesmartfee(), fundrawtransaction(), getbalance(), getgovernanceinfo(), getinfo(), getnetworkinfo(), getreceivedbyaccount(), getreceivedbyaddress(), gettransaction(), gettxout(), gettxoutsetinfo(), getunconfirmedbalance(), getwalletinfo(), listaccounts(), listaddressgroupings(), ListReceived(), ListTransactions(), listunspent(), mempoolInfoToJSON(), mempoolToJSON(), rest_getutxos(), and TxToJSON().
verifychain()
UniValue verifychain (const UniValue & params, bool fHelp)
Definition at line 742 of file blockchain.cpp.
References cs_main, DEFAULT_CHECKBLOCKS, DEFAULT_CHECKLEVEL, GetArg(), HelpExampleCli(), HelpExampleRpc(), LOCK, Params(), pcoinsTip, UniValue::size(), strprintf, and CVerifyDB::VerifyDB().
verifymessage()
UniValue verifymessage (const UniValue & params, bool fHelp)
Definition at line 453 of file misc.cpp.
References cs_main, DecodeBase64(), UniValue::get_str(), CHashWriter::GetHash(), CPubKey::GetID(), CBitcoinAddress::GetKeyID(), HelpExampleCli(), HelpExampleRpc(), CBitcoinAddress::IsValid(), JSONRPCError(), LOCK, CPubKey::RecoverCompact(), RPC_INVALID_ADDRESS_OR_KEY, RPC_TYPE_ERROR, SER_GETHASH, UniValue::size(), and strMessageMagic.
verifytxoutproof()
UniValue verifytxoutproof (const UniValue & params, bool fHelp)
Definition at line 322 of file rawtransaction.cpp.
References chainActive, CChain::Contains(), cs_main, base_blob< BITS >::GetHex(), HelpExampleCli(), HelpExampleRpc(), JSONRPCError(), LOCK, mapBlockIndex, ParseHexV(), PROTOCOL_VERSION, UniValue::push_back(), RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, UniValue::size(), and UniValue::VARR.
voteraw()
UniValue voteraw (const UniValue & params, bool fHelp)
Definition at line 847 of file governance.cpp.
References CGovernanceVoting::ConvertVoteOutcome(), CGovernanceVoting::ConvertVoteSignal(), DecodeBase64(), g_connman, CMasternodeMan::Get(), UniValue::get_int(), UniValue::get_int64(), UniValue::get_str(), CGovernanceException::GetMessage(), governance, CGovernanceVote::IsValid(), JSONRPCError(), mnodeman, ParseHashV(), CGovernanceManager::ProcessVoteAndRelay(), RPC_INTERNAL_ERROR, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, CGovernanceVote::SetSignature(), CGovernanceVote::SetTime(), UniValue::size(), COutPoint::ToStringShort(), VOTE_OUTCOME_NONE, and VOTE_SIGNAL_NONE.
walletlock()
UniValue walletlock (const UniValue & params, bool fHelp)
Definition at line 2120 of file rpcwallet.cpp.
References cs_main, cs_nWalletUnlockTime, CWallet::cs_wallet, EnsureWalletIsAvailable(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), JSONRPCError(), LOCK, CCryptoKeyStore::Lock(), LOCK2, NullUniValue, nWalletUnlockTime, pwalletMain, RPC_WALLET_WRONG_ENC_STATE, and UniValue::size().
walletpassphrase()
UniValue walletpassphrase (const UniValue & params, bool fHelp)
Definition at line 2007 of file rpcwallet.cpp.
References cs_main, cs_nWalletUnlockTime, CWallet::cs_wallet, EnsureWalletIsAvailable(), UniValue::get_int64(), UniValue::get_str(), GetTime(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), CCryptoKeyStore::IsLocked(), JSONRPCError(), LOCK, LOCK2, LockWallet(), NullUniValue, nWalletUnlockTime, pwalletMain, RPC_WALLET_ALREADY_UNLOCKED, RPC_WALLET_PASSPHRASE_INCORRECT, RPC_WALLET_WRONG_ENC_STATE, RPCRunLater(), UniValue::size(), CWallet::TopUpKeyPool(), and CWallet::Unlock().
walletpassphrasechange()
UniValue walletpassphrasechange (const UniValue & params, bool fHelp)
Definition at line 2074 of file rpcwallet.cpp.
References CWallet::ChangeWalletPassphrase(), cs_main, CWallet::cs_wallet, EnsureWalletIsAvailable(), UniValue::get_str(), HelpExampleCli(), HelpExampleRpc(), CCryptoKeyStore::IsCrypted(), JSONRPCError(), LOCK2, NullUniValue, pwalletMain, RPC_WALLET_PASSPHRASE_INCORRECT, RPC_WALLET_WRONG_ENC_STATE, and UniValue::size().
Variable Documentation
nWalletUnlockTime
int64_t nWalletUnlockTime
Definition at line 32 of file rpcwallet.cpp.
Referenced by getinfo(), getwalletinfo(), LockWallet(), walletlock(), and walletpassphrase().
tableRPC
const CRPCTable tableRPC
Definition at line 614 of file server.cpp.
Referenced by CRPCTable::execute(), help(), HTTPReq_JSONRPC(), JSONRPCExecOne(), RPCExecutor::request(), and RPCConsole::setClientModel().
Released under the MIT license