Dash Core: src/crypto/shavite.c File Reference
shavite.c File Reference
#include <stddef.h>
#include <string.h>
#include "sph_shavite.h"
#include "aes_helper.c"
Macros
#define C32 SPH_C32
#define AES_BIG_ENDIAN 0
#define AES_ROUND_NOKEY(x0, x1, x2, x3)
#define KEY_EXPAND_ELT(k0, k1, k2, k3)
Functions
static void c256 (sph_shavite_small_context *sc, const void *msg)
static void c512 (sph_shavite_big_context *sc, const void *msg)
static void shavite_small_init (sph_shavite_small_context *sc, const sph_u32 *iv)
static void shavite_small_core (sph_shavite_small_context *sc, const void *data, size_t len)
static void shavite_small_close (sph_shavite_small_context *sc, unsigned ub, unsigned n, void *dst, size_t out_size_w32)
static void shavite_big_init (sph_shavite_big_context *sc, const sph_u32 *iv)
static void shavite_big_core (sph_shavite_big_context *sc, const void *data, size_t len)
static void shavite_big_close (sph_shavite_big_context *sc, unsigned ub, unsigned n, void *dst, size_t out_size_w32)
void sph_shavite224_init (void *cc)
void sph_shavite224 (void *cc, const void *data, size_t len)
void sph_shavite224_close (void *cc, void *dst)
void sph_shavite224_addbits_and_close (void *cc, unsigned ub, unsigned n, void *dst)
void sph_shavite256_init (void *cc)
void sph_shavite256 (void *cc, const void *data, size_t len)
void sph_shavite256_close (void *cc, void *dst)
void sph_shavite256_addbits_and_close (void *cc, unsigned ub, unsigned n, void *dst)
void sph_shavite384_init (void *cc)
void sph_shavite384 (void *cc, const void *data, size_t len)
void sph_shavite384_close (void *cc, void *dst)
void sph_shavite384_addbits_and_close (void *cc, unsigned ub, unsigned n, void *dst)
void sph_shavite512_init (void *cc)
void sph_shavite512 (void *cc, const void *data, size_t len)
void sph_shavite512_close (void *cc, void *dst)
void sph_shavite512_addbits_and_close (void *cc, unsigned ub, unsigned n, void *dst)
Variables
static const sph_u32 IV224 []
static const sph_u32 IV256 []
static const sph_u32 IV384 []
static const sph_u32 IV512 []
Macro Definition Documentation
AES_BIG_ENDIAN
#define AES_BIG_ENDIAN 0
Definition at line 64 of file shavite.c.
AES_ROUND_NOKEY
#define AES_ROUND_NOKEY (x0, x1, x2, x3)
Value:
do { \
                sph_u32 t0 = (x0); \
                sph_u32 t1 = (x1); \
                sph_u32 t2 = (x2); \
                sph_u32 t3 = (x3); \
                AES_ROUND_NOKEY_LE(t0, t1, t2, t3, x0, x1, x2, x3); \
        } while (0)
Definition at line 91 of file shavite.c.
Referenced by c256(), and c512().
C32
#define C32 SPH_C32
Definition at line 50 of file shavite.c.
KEY_EXPAND_ELT
#define KEY_EXPAND_ELT (k0, k1, k2, k3)
Value:
do { \
                sph_u32 kt; \
                AES_ROUND_NOKEY(k1, k2, k3, k0); \
                kt = (k0); \
                (k0) = (k1); \
                (k1) = (k2); \
                (k2) = (k3); \
                (k3) = kt; \
        } while (0)
Definition at line 141 of file shavite.c.
Referenced by c256(), and c512().
Function Documentation
c256()
static void c256 (sph_shavite_small_context * sc, const void * msg) static
Definition at line 296 of file shavite.c.
Referenced by shavite_small_close(), and shavite_small_core().
c512()
static void c512 (sph_shavite_big_context * sc, const void * msg) static
Definition at line 900 of file shavite.c.
Referenced by shavite_big_close(), and shavite_big_core().
shavite_big_close()
static void shavite_big_close (sph_shavite_big_context * sc, unsigned ub, unsigned n, void * dst, size_t out_size_w32) static
Definition at line 1601 of file shavite.c.
Referenced by sph_shavite384_addbits_and_close(), sph_shavite384_close(), sph_shavite512_addbits_and_close(), and sph_shavite512_close().
shavite_big_core()
static void shavite_big_core (sph_shavite_big_context * sc, const void * data, size_t len) static
Definition at line 1565 of file shavite.c.
Referenced by sph_shavite384(), and sph_shavite512().
shavite_big_init()
static void shavite_big_init (sph_shavite_big_context * sc, const sph_u32 * iv) static
Definition at line 1554 of file shavite.c.
Referenced by sph_shavite384_addbits_and_close(), sph_shavite384_close(), sph_shavite384_init(), sph_shavite512_addbits_and_close(), sph_shavite512_close(), and sph_shavite512_init().
shavite_small_close()
static void shavite_small_close (sph_shavite_small_context * sc, unsigned ub, unsigned n, void * dst, size_t out_size_w32) static
Definition at line 1516 of file shavite.c.
Referenced by sph_shavite224_addbits_and_close(), sph_shavite224_close(), sph_shavite256_addbits_and_close(), and sph_shavite256_close().
shavite_small_core()
static void shavite_small_core (sph_shavite_small_context * sc, const void * data, size_t len) static
Definition at line 1488 of file shavite.c.
Referenced by sph_shavite224(), and sph_shavite256().
shavite_small_init()
static void shavite_small_init (sph_shavite_small_context * sc, const sph_u32 * iv) static
Definition at line 1479 of file shavite.c.
Referenced by sph_shavite224_addbits_and_close(), sph_shavite224_close(), sph_shavite224_init(), sph_shavite256_addbits_and_close(), sph_shavite256_close(), and sph_shavite256_init().
sph_shavite224()
void sph_shavite224 (void * cc, const void * data, size_t len)
Process some data bytes. It is acceptable that len is zero (in which case this function does nothing).
Parameters
cc the SHAvite-224 context
data the input data
len the input data length (in bytes)
Definition at line 1651 of file shavite.c.
sph_shavite224_addbits_and_close()
void sph_shavite224_addbits_and_close (void * cc, unsigned ub, unsigned n, void * dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (28 bytes). If bit number i in ub has value 2^i, then the extra bits are those numbered 7 downto 8-n (this is the big-endian convention at the byte level). The context is automatically reinitialized.
Parameters
cc the SHAvite-224 context
ub the extra bits
n the number of extra bits (0 to 7)
dst the destination buffer
Definition at line 1666 of file shavite.c.
sph_shavite224_close()
void sph_shavite224_close (void * cc, void * dst)
Terminate the current SHAvite-224 computation and output the result into the provided buffer. The destination buffer must be wide enough to accomodate the result (28 bytes). The context is automatically reinitialized.
Parameters
cc the SHAvite-224 context
dst the destination buffer
Definition at line 1658 of file shavite.c.
sph_shavite224_init()
void sph_shavite224_init (void * cc)
Initialize a SHAvite-224 context. This process performs no memory allocation.
Parameters
cc the SHAvite-224 context (pointer to a sph_shavite224_context)
Definition at line 1644 of file shavite.c.
sph_shavite256()
void sph_shavite256 (void * cc, const void * data, size_t len)
Process some data bytes. It is acceptable that len is zero (in which case this function does nothing).
Parameters
cc the SHAvite-256 context
data the input data
len the input data length (in bytes)
Definition at line 1681 of file shavite.c.
sph_shavite256_addbits_and_close()
void sph_shavite256_addbits_and_close (void * cc, unsigned ub, unsigned n, void * dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (32 bytes). If bit number i in ub has value 2^i, then the extra bits are those numbered 7 downto 8-n (this is the big-endian convention at the byte level). The context is automatically reinitialized.
Parameters
cc the SHAvite-256 context
ub the extra bits
n the number of extra bits (0 to 7)
dst the destination buffer
Definition at line 1696 of file shavite.c.
sph_shavite256_close()
void sph_shavite256_close (void * cc, void * dst)
Terminate the current SHAvite-256 computation and output the result into the provided buffer. The destination buffer must be wide enough to accomodate the result (32 bytes). The context is automatically reinitialized.
Parameters
cc the SHAvite-256 context
dst the destination buffer
Definition at line 1688 of file shavite.c.
sph_shavite256_init()
void sph_shavite256_init (void * cc)
Initialize a SHAvite-256 context. This process performs no memory allocation.
Parameters
cc the SHAvite-256 context (pointer to a sph_shavite256_context)
Definition at line 1674 of file shavite.c.
sph_shavite384()
void sph_shavite384 (void * cc, const void * data, size_t len)
Process some data bytes. It is acceptable that len is zero (in which case this function does nothing).
Parameters
cc the SHAvite-384 context
data the input data
len the input data length (in bytes)
Definition at line 1711 of file shavite.c.
sph_shavite384_addbits_and_close()
void sph_shavite384_addbits_and_close (void * cc, unsigned ub, unsigned n, void * dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (48 bytes). If bit number i in ub has value 2^i, then the extra bits are those numbered 7 downto 8-n (this is the big-endian convention at the byte level). The context is automatically reinitialized.
Parameters
cc the SHAvite-384 context
ub the extra bits
n the number of extra bits (0 to 7)
dst the destination buffer
Definition at line 1726 of file shavite.c.
sph_shavite384_close()
void sph_shavite384_close (void * cc, void * dst)
Terminate the current SHAvite-384 computation and output the result into the provided buffer. The destination buffer must be wide enough to accomodate the result (48 bytes). The context is automatically reinitialized.
Parameters
cc the SHAvite-384 context
dst the destination buffer
Definition at line 1718 of file shavite.c.
sph_shavite384_init()
void sph_shavite384_init (void * cc)
Initialize a SHAvite-384 context. This process performs no memory allocation.
Parameters
cc the SHAvite-384 context (pointer to a sph_shavite384_context)
Definition at line 1704 of file shavite.c.
sph_shavite512()
void sph_shavite512 (void * cc, const void * data, size_t len)
Process some data bytes. It is acceptable that len is zero (in which case this function does nothing).
Parameters
cc the SHAvite-512 context
data the input data
len the input data length (in bytes)
Definition at line 1741 of file shavite.c.
Referenced by HashX11().
sph_shavite512_addbits_and_close()
void sph_shavite512_addbits_and_close (void * cc, unsigned ub, unsigned n, void * dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (64 bytes). If bit number i in ub has value 2^i, then the extra bits are those numbered 7 downto 8-n (this is the big-endian convention at the byte level). The context is automatically reinitialized.
Parameters
cc the SHAvite-512 context
ub the extra bits
n the number of extra bits (0 to 7)
dst the destination buffer
Definition at line 1756 of file shavite.c.
sph_shavite512_close()
void sph_shavite512_close (void * cc, void * dst)
Terminate the current SHAvite-512 computation and output the result into the provided buffer. The destination buffer must be wide enough to accomodate the result (64 bytes). The context is automatically reinitialized.
Parameters
cc the SHAvite-512 context
dst the destination buffer
Definition at line 1748 of file shavite.c.
Referenced by HashX11().
sph_shavite512_init()
void sph_shavite512_init (void * cc)
Initialize a SHAvite-512 context. This process performs no memory allocation.
Parameters
cc the SHAvite-512 context (pointer to a sph_shavite512_context)
Definition at line 1734 of file shavite.c.
Referenced by HashX11().
Variable Documentation
IV224
const sph_u32 IV224[] static
Initial value:
= {
        C32(0x6774F31C), C32(0x990AE210), C32(0xC87D4274), C32(0xC9546371),
        C32(0x62B2AEA8), C32(0x4B5801D8), C32(0x1B702860), C32(0x842F3017)
}
Definition at line 67 of file shavite.c.
Referenced by sph_shavite224_addbits_and_close(), sph_shavite224_close(), and sph_shavite224_init().
IV256
const sph_u32 IV256[] static
Initial value:
= {
        C32(0x49BB3E47), C32(0x2674860D), C32(0xA8B392AC), C32(0x021AC4E6),
        C32(0x409283CF), C32(0x620E5D86), C32(0x6D929DCB), C32(0x96CC2A8B)
}
Definition at line 72 of file shavite.c.
Referenced by sph_shavite256_addbits_and_close(), sph_shavite256_close(), and sph_shavite256_init().
IV384
const sph_u32 IV384[] static
Initial value:
= {
        C32(0x83DF1545), C32(0xF9AAEC13), C32(0xF4803CB0), C32(0x11FE1F47),
        C32(0xDA6CD269), C32(0x4F53FCD7), C32(0x950529A2), C32(0x97908147),
        C32(0xB0A4D7AF), C32(0x2B9132BF), C32(0x226E607D), C32(0x3C0F8D7C),
        C32(0x487B3F0F), C32(0x04363E22), C32(0x0155C99C), C32(0xEC2E20D3)
}
Definition at line 77 of file shavite.c.
Referenced by sph_shavite384_addbits_and_close(), sph_shavite384_close(), and sph_shavite384_init().
IV512
const sph_u32 IV512[] static
Initial value:
= {
        C32(0x72FCCDD8), C32(0x79CA4727), C32(0x128A077B), C32(0x40D55AEC),
        C32(0xD1901A06), C32(0x430AE307), C32(0xB29F5CD1), C32(0xDF07FBFC),
        C32(0x8E45D73D), C32(0x681AB538), C32(0xBDE86578), C32(0xDD577E47),
        C32(0xE275EADE), C32(0x502D9FCD), C32(0xB9357178), C32(0x022A4B9A)
}
Definition at line 84 of file shavite.c.
Referenced by sph_shavite512_addbits_and_close(), sph_shavite512_close(), and sph_shavite512_init().