Dash Core: src/evo/simplifiedmns.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
simplifiedmns.cpp File Reference
#include <evo/cbtx.h>
#include <core_io.h>
#include <evo/deterministicmns.h>
#include <llmq/quorums.h>
#include <llmq/quorums_blockprocessor.h>
#include <llmq/quorums_commitment.h>
#include <evo/simplifiedmns.h>
#include <evo/specialtx.h>
#include <base58.h>
#include <chainparams.h>
#include <consensus/merkle.h>
#include <univalue.h>
#include <validation.h>
Functions
bool BuildSimplifiedMNListDiff (const uint256 &baseBlockHash, const uint256 &blockHash, CSimplifiedMNListDiff &mnListDiffRet, std::string &errorRet)
Function Documentation
BuildSimplifiedMNListDiff()
bool BuildSimplifiedMNListDiff (const uint256 & baseBlockHash, const uint256 & blockHash, CSimplifiedMNListDiff & mnListDiffRet, std::string & errorRet)
Definition at line 188 of file simplifiedmns.cpp.
References AssertLockHeld(), CSimplifiedMNListDiff::baseBlockHash, CSimplifiedMNListDiff::BuildQuorumsDiff(), CSimplifiedMNListDiff::cbTx, CSimplifiedMNListDiff::cbTxMerkleTree, chainActive, CChain::Contains(), cs_main, deterministicMNManager, CChain::Genesis(), base_blob< BITS >::IsNull(), LOCK, mapBlockIndex, CBlockIndex::nHeight, Params(), ReadBlockFromDisk(), strprintf, base_blob< BITS >::ToString(), and CBlock::vtx.
Referenced by ProcessMessage(), and protx_diff().
Released under the MIT license