Dash Core: src/stacktraces.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
stacktraces.h File Reference
#include <string>
#include <sstream>
#include <exception>
#include <cxxabi.h>
#include <tinyformat.h>
Functions
std::string DemangleSymbol (const std::string &name)
std::string GetPrettyExceptionStr (const std::exception_ptr &e)
std::string GetCrashInfoStrFromSerializedStr (const std::string &ciStr)
template<typename T >
std::string GetExceptionWhat (const T &e)
template<>
std::string GetExceptionWhat (const std::exception &e)
void RegisterPrettyTerminateHander ()
void RegisterPrettySignalHandlers ()
Function Documentation
DemangleSymbol()
std::string DemangleSymbol (const std::string & name)
Definition at line 51 of file stacktraces.cpp.
References name.
Referenced by GetCrashInfoFromException(), and my_backtrace_full_callback().
GetCrashInfoStrFromSerializedStr()
std::string GetCrashInfoStrFromSerializedStr (const std::string & ciStr)
Definition at line 422 of file stacktraces.cpp.
References crash_info::ConvertAddresses(), DecodeBase32(), crash_info_header::exeFileName, g_exeFileBaseName, GetBaseAddress(), GetCrashInfoStr(), GetStackFrameInfos(), crash_info_header::magic, SER_DISK, crash_info::stackframeInfos, crash_info::stackframes, and crash_info_header::version.
Referenced by AppInit(), AppInitRawTx(), AppInitRPC(), and main().
GetExceptionWhat() [1/2]
template<typename T > std::string GetExceptionWhat (const T & e) inline
Definition at line 32 of file stacktraces.h.
Referenced by GetCrashInfoFromException().
GetExceptionWhat() [2/2]
template<> std::string GetExceptionWhat (const std::exception & e) inline
Definition at line 25 of file stacktraces.h.
GetPrettyExceptionStr()
std::string GetPrettyExceptionStr (const std::exception_ptr & e)
Definition at line 732 of file stacktraces.cpp.
References GetCrashInfoFromException(), and GetCrashInfoStr().
Referenced by PrintExceptionContinue().
RegisterPrettySignalHandlers()
void RegisterPrettySignalHandlers ()
Definition at line 842 of file stacktraces.cpp.
References HandlePosixSignal().
Referenced by main().
RegisterPrettyTerminateHander()
void RegisterPrettyTerminateHander ()
Definition at line 762 of file stacktraces.cpp.
References terminate_handler().
Referenced by main().
Released under the MIT license