Dash Core: src/bench/string_cast.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
string_cast.cpp File Reference
#include <bench/bench.h>
#include <tinyformat.h>
#include <utilstrencodings.h>
#include <boost/lexical_cast.hpp>
#include <string>
Functions
template<typename T >
std::string NumberToString (T Number)
static void int_atoi (benchmark::State &state)
static void int_lexical_cast (benchmark::State &state)
static void strings_1_itostr (benchmark::State &state)
static void strings_1_lexical_cast (benchmark::State &state)
static void strings_1_numberToString (benchmark::State &state)
static void strings_1_to_string (benchmark::State &state)
static void strings_2_multi_itostr (benchmark::State &state)
static void strings_2_multi_lexical_cast (benchmark::State &state)
static void strings_2_multi_numberToString (benchmark::State &state)
static void strings_2_multi_to_string (benchmark::State &state)
static void strings_2_strptintf (benchmark::State &state)
BENCHMARK (int_atoi)
BENCHMARK (int_lexical_cast)
BENCHMARK (strings_1_itostr)
BENCHMARK (strings_1_lexical_cast)
BENCHMARK (strings_1_numberToString)
BENCHMARK (strings_1_to_string)
BENCHMARK (strings_2_multi_itostr)
BENCHMARK (strings_2_multi_lexical_cast)
BENCHMARK (strings_2_multi_numberToString)
BENCHMARK (strings_2_multi_to_string)
BENCHMARK (strings_2_strptintf)
Function Documentation
BENCHMARK() [1/11]
BENCHMARK (int_atoi)
BENCHMARK() [2/11]
BENCHMARK (int_lexical_cast)
BENCHMARK() [3/11]
BENCHMARK (strings_1_itostr)
BENCHMARK() [4/11]
BENCHMARK (strings_1_lexical_cast)
BENCHMARK() [5/11]
BENCHMARK (strings_1_numberToString)
BENCHMARK() [6/11]
BENCHMARK (strings_1_to_string)
BENCHMARK() [7/11]
BENCHMARK (strings_2_multi_itostr)
BENCHMARK() [8/11]
BENCHMARK (strings_2_multi_lexical_cast)
BENCHMARK() [9/11]
BENCHMARK (strings_2_multi_numberToString)
BENCHMARK() [10/11]
BENCHMARK (strings_2_multi_to_string)
BENCHMARK() [11/11]
BENCHMARK (strings_2_strptintf)
int_atoi()
static void int_atoi (benchmark::State & state) static
Definition at line 19 of file string_cast.cpp.
References atoi(), and benchmark::State::KeepRunning().
int_lexical_cast()
static void int_lexical_cast (benchmark::State & state) static
Definition at line 25 of file string_cast.cpp.
References benchmark::State::KeepRunning().
NumberToString()
template<typename T > std::string NumberToString (T Number)
Definition at line 13 of file string_cast.cpp.
Referenced by strings_1_numberToString(), and strings_2_multi_numberToString().
strings_1_itostr()
static void strings_1_itostr (benchmark::State & state) static
Definition at line 31 of file string_cast.cpp.
References itostr(), and benchmark::State::KeepRunning().
strings_1_lexical_cast()
static void strings_1_lexical_cast (benchmark::State & state) static
Definition at line 38 of file string_cast.cpp.
References benchmark::State::KeepRunning().
strings_1_numberToString()
static void strings_1_numberToString (benchmark::State & state) static
Definition at line 45 of file string_cast.cpp.
References benchmark::State::KeepRunning(), and NumberToString().
strings_1_to_string()
static void strings_1_to_string (benchmark::State & state) static
Definition at line 52 of file string_cast.cpp.
References benchmark::State::KeepRunning().
strings_2_multi_itostr()
static void strings_2_multi_itostr (benchmark::State & state) static
Definition at line 59 of file string_cast.cpp.
References itostr(), and benchmark::State::KeepRunning().
strings_2_multi_lexical_cast()
static void strings_2_multi_lexical_cast (benchmark::State & state) static
Definition at line 68 of file string_cast.cpp.
References benchmark::State::KeepRunning().
strings_2_multi_numberToString()
static void strings_2_multi_numberToString (benchmark::State & state) static
Definition at line 81 of file string_cast.cpp.
References benchmark::State::KeepRunning(), and NumberToString().
strings_2_multi_to_string()
static void strings_2_multi_to_string (benchmark::State & state) static
Definition at line 90 of file string_cast.cpp.
References benchmark::State::KeepRunning().
strings_2_strptintf()
static void strings_2_strptintf (benchmark::State & state) static
Definition at line 99 of file string_cast.cpp.
References benchmark::State::KeepRunning(), and strprintf.
Released under the MIT license