Dash Core: CDBTransaction< Parent, CommitTarget >::DataStreamCmp Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CDBTransaction< Parent, CommitTarget >::DataStreamCmp Struct Reference
#include <dbwrapper.h>
Public Member Functions
bool operator() (const CDataStream &a, const CDataStream &b) const
Static Public Member Functions
static bool less (const CDataStream &a, const CDataStream &b)
Detailed Description
template<typename Parent, typename CommitTarget>
struct CDBTransaction< Parent, CommitTarget >::DataStreamCmp
Definition at line 560 of file dbwrapper.h.
Member Function Documentation
less()
template<typename Parent, typename CommitTarget> static bool CDBTransaction< Parent, CommitTarget >::DataStreamCmp::less (const CDataStream & a, const CDataStream & b) inline static
Definition at line 561 of file dbwrapper.h.
References CDataStream::data(), and CDataStream::size().
Referenced by CDBTransactionIterator< CDBTransaction >::DecideCur(), and CDBTransaction< Parent, CommitTarget >::DataStreamCmp::operator()().
operator()()
template<typename Parent, typename CommitTarget> bool CDBTransaction< Parent, CommitTarget >::DataStreamCmp::operator() (const CDataStream & a, const CDataStream & b) const inline
Definition at line 566 of file dbwrapper.h.
References CDBTransaction< Parent, CommitTarget >::DataStreamCmp::less().
The documentation for this struct was generated from the following file:
src/dbwrapper.h
Released under the MIT license