Dash Core: CAddressIndexIteratorKey Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CAddressIndexIteratorKey Struct Reference
#include <spentindex.h>
Public Member Functions
size_t GetSerializeSize (int nType, int nVersion) const
template<typename Stream >
void Serialize (Stream &s, int nType, int nVersion) const
template<typename Stream >
void Unserialize (Stream &s, int nType, int nVersion)
CAddressIndexIteratorKey (unsigned int addressType, uint160 addressHash)
CAddressIndexIteratorKey ()
void SetNull ()
Public Attributes
unsigned int type
uint160 hashBytes
Detailed Description
Definition at line 301 of file spentindex.h.
Constructor & Destructor Documentation
CAddressIndexIteratorKey() [1/2]
CAddressIndexIteratorKey::CAddressIndexIteratorKey (unsigned int addressType, uint160 addressHash) inline
Definition at line 319 of file spentindex.h.
References hashBytes, and type.
CAddressIndexIteratorKey() [2/2]
CAddressIndexIteratorKey::CAddressIndexIteratorKey () inline
Definition at line 324 of file spentindex.h.
References SetNull().
Member Function Documentation
GetSerializeSize()
size_t CAddressIndexIteratorKey::GetSerializeSize (int nType, int nVersion) const inline
Definition at line 305 of file spentindex.h.
Serialize()
template<typename Stream > void CAddressIndexIteratorKey::Serialize (Stream & s, int nType, int nVersion) const inline
Definition at line 309 of file spentindex.h.
References hashBytes, ser_writedata8(), base_blob< BITS >::Serialize(), and type.
SetNull()
void CAddressIndexIteratorKey::SetNull () inline
Definition at line 328 of file spentindex.h.
References hashBytes, base_blob< BITS >::SetNull(), and type.
Referenced by CAddressIndexIteratorKey().
Unserialize()
template<typename Stream > void CAddressIndexIteratorKey::Unserialize (Stream & s, int nType, int nVersion) inline
Definition at line 314 of file spentindex.h.
References hashBytes, ser_readdata8(), type, and base_blob< BITS >::Unserialize().
Member Data Documentation
hashBytes
uint160 CAddressIndexIteratorKey::hashBytes
Definition at line 303 of file spentindex.h.
Referenced by CAddressIndexIteratorKey(), Serialize(), SetNull(), and Unserialize().
type
unsigned int CAddressIndexIteratorKey::type
Definition at line 302 of file spentindex.h.
Referenced by CAddressIndexIteratorKey(), Serialize(), SetNull(), and Unserialize().
The documentation for this struct was generated from the following file:
src/spentindex.h
Released under the MIT license