Dash Core: CDiskTxPos Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CDiskTxPos Struct Reference
#include <txdb.h>
Public Member Functions
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
CDiskTxPos (const CDiskBlockPos &blockIn, unsigned int nTxOffsetIn)
CDiskTxPos ()
void SetNull ()
Public Member Functions inherited from CDiskBlockPos
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action)
CDiskBlockPos ()
CDiskBlockPos (int nFileIn, unsigned int nPosIn)
void SetNull ()
bool IsNull () const
std::string ToString () const
Public Attributes
unsigned int nTxOffset
ADD_SERIALIZE_METHODS
Public Attributes inherited from CDiskBlockPos
int nFile
unsigned int nPos
ADD_SERIALIZE_METHODS
Detailed Description
Definition at line 45 of file txdb.h.
Constructor & Destructor Documentation
CDiskTxPos() [1/2]
CDiskTxPos::CDiskTxPos (const CDiskBlockPos & blockIn, unsigned int nTxOffsetIn) inline
Definition at line 57 of file txdb.h.
CDiskTxPos() [2/2]
CDiskTxPos::CDiskTxPos () inline
Definition at line 60 of file txdb.h.
References SetNull().
Member Function Documentation
SerializationOp()
template<typename Stream , typename Operation > void CDiskTxPos::SerializationOp (Stream & s, Operation ser_action) inline
Definition at line 52 of file txdb.h.
References nTxOffset, READWRITE, and VARINT.
SetNull()
void CDiskTxPos::SetNull () inline
Definition at line 64 of file txdb.h.
References nTxOffset, and CDiskBlockPos::SetNull().
Referenced by CDiskTxPos().
Member Data Documentation
ADD_SERIALIZE_METHODS
CDiskTxPos::ADD_SERIALIZE_METHODS
Definition at line 49 of file txdb.h.
nTxOffset
unsigned int CDiskTxPos::nTxOffset
Definition at line 47 of file txdb.h.
Referenced by GetTransaction(), SerializationOp(), SetNull(), and WriteTxIndexDataForBlock().
The documentation for this struct was generated from the following file:
src/txdb.h
Released under the MIT license