Dash Core: immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B > Struct Template Reference
#include <node.hpp>
Classes
struct collision_t
union data_t
struct impl_data_t
struct inner_t
struct values_data_t
Public Types
enum kind_t { kind_t::collision, kind_t::inner }
using node_t = node
using memory = MemoryPolicy
using heap_policy = typename memory::heap
using heap = typename heap_policy::type
using transience = typename memory::transience_t
using refs_t = typename memory::refcount
using ownee_t = typename transience::ownee
using edit_t = typename transience::edit
using value_t = T
using bitmap_t = typename get_bitmap_type< B >::type
using values_t = combine_standard_layout_t< values_data_t, refs_t >
using impl_t = combine_standard_layout_t< impl_data_t, refs_t >
Public Member Functions
kind_t kind () const
auto values ()
auto values () const
auto children ()
auto children () const
auto datamap () const
auto nodemap () const
auto collision_count () const
T * collisions ()
const T * collisions () const
node_t * inc ()
const node_t * inc () const
bool dec () const
void dec_unsafe () const
Static Public Member Functions
static constexpr std::size_t sizeof_values_n (count_t count)
static constexpr std::size_t sizeof_collision_n (count_t count)
static constexpr std::size_t sizeof_inner_n (count_t count)
static refs_t & refs (const values_t *x)
static const ownee_t & ownee (const values_t *x)
static ownee_t & ownee (values_t *x)
static refs_t & refs (const node_t *x)
static const ownee_t & ownee (const node_t *x)
static ownee_t & ownee (node_t *x)
static node_t * make_inner_n (count_t n)
static node_t * make_inner_n (count_t n, values_t *values)
static node_t * make_inner_n (count_t n, count_t nv)
static node_t * make_inner_n (count_t n, count_t idx, node_t *child)
static node_t * make_inner_n (count_t n, bitmap_t bitmap, T x)
static node_t * make_inner_n (count_t n, count_t idx1, T x1, count_t idx2, T x2)
static node_t * make_collision_n (count_t n)
static node_t * make_collision (T v1, T v2)
static node_t * copy_collision_insert (node_t *src, T v)
static node_t * copy_collision_remove (node_t *src, T *v)
static node_t * copy_collision_replace (node_t *src, T *pos, T v)
static node_t * copy_inner_replace (node_t *src, count_t offset, node_t *child)
static node_t * copy_inner_replace_value (node_t *src, count_t offset, T v)
static node_t * copy_inner_replace_merged (node_t *src, bitmap_t bit, count_t voffset, node_t *node)
static node_t * copy_inner_replace_inline (node_t *src, bitmap_t bit, count_t noffset, T value)
static node_t * copy_inner_remove_value (node_t *src, bitmap_t bit, count_t voffset)
static node_t * copy_inner_insert_value (node_t *src, bitmap_t bit, T v)
static node_t * make_merged (shift_t shift, T v1, hash_t hash1, T v2, hash_t hash2)
static void inc_nodes (node_t **p, count_t n)
static void delete_values (values_t *p, count_t n)
static void delete_inner (node_t *p)
static void delete_collision (node_t *p)
static void delete_deep (node_t *p, shift_t s)
static void delete_deep_shift (node_t *p, shift_t s)
static void deallocate_values (values_t *p, count_t n)
static void deallocate_collision (node_t *p, count_t n)
static void deallocate_inner (node_t *p, count_t n)
static void deallocate_inner (node_t *p, count_t n, count_t nv)
Public Attributes
impl_t impl
Detailed Description
template<typename T, typename Hash, typename Equal, typename MemoryPolicy, bits_t B>
struct immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >
Definition at line 32 of file node.hpp.
Member Typedef Documentation
bitmap_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::bitmap_t = typename get_bitmap_type<B>::type
Definition at line 44 of file node.hpp.
edit_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::edit_t = typename transience::edit
Definition at line 42 of file node.hpp.
heap
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::heap = typename heap_policy::type
Definition at line 38 of file node.hpp.
heap_policy
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::heap_policy = typename memory::heap
Definition at line 37 of file node.hpp.
impl_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl_t = combine_standard_layout_t< impl_data_t, refs_t>
Definition at line 89 of file node.hpp.
memory
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::memory = MemoryPolicy
Definition at line 36 of file node.hpp.
node_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::node_t = node
Definition at line 34 of file node.hpp.
ownee_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::ownee_t = typename transience::ownee
Definition at line 41 of file node.hpp.
refs_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs_t = typename memory::refcount
Definition at line 40 of file node.hpp.
transience
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::transience = typename memory::transience_t
Definition at line 39 of file node.hpp.
value_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::value_t = T
Definition at line 43 of file node.hpp.
values_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> using immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values_t = combine_standard_layout_t< values_data_t, refs_t>
Definition at line 64 of file node.hpp.
Member Enumeration Documentation
kind_t
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> enum immer::detail::hamts::node::kind_t strong
Enumerator
collision
inner
Definition at line 46 of file node.hpp.
Member Function Documentation
children() [1/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> auto immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children () inline
Definition at line 132 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep_shift(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::equals_tree(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::for_each_chunk_traversal(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::get().
children() [2/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> auto immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children () const inline
Definition at line 138 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
collision_count()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> auto immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_count () const inline
Definition at line 156 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_insert(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_remove(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_collision(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::equals_tree(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::for_each_chunk_traversal(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::get().
collisions() [1/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> T* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions () inline
Definition at line 162 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_insert(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_remove(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::equals_tree(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::for_each_chunk_traversal(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::get().
collisions() [2/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> const T* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions () const inline
Definition at line 168 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
copy_collision_insert()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_insert (node_t * src, T v) inline static
Definition at line 311 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_count(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision_n(), and immer::detail::uninitialized_copy().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update().
copy_collision_remove()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_remove (node_t * src, T * v) inline static
Definition at line 333 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_count(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision(), immer::detail::destroy(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision_n(), and immer::detail::uninitialized_copy().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub().
copy_collision_replace()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_replace (node_t * src, T * pos, T v) inline static
Definition at line 356 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_count(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision(), immer::detail::destroy(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision_n(), and immer::detail::uninitialized_copy().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update().
copy_inner_insert_value()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value (node_t * src, bitmap_t bit, T v) inline static
Definition at line 557 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::destroy_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::popcount(), immer::detail::uninitialized_copy(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update().
copy_inner_remove_value()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value (node_t * src, bitmap_t bit, count_t voffset) inline static
Definition at line 521 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::destroy_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::popcount(), immer::detail::uninitialized_copy(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub().
copy_inner_replace()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace (node_t * src, count_t offset, node_t * child) inline static
Definition at line 385 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::popcount(), and immer::detail::uninitialized_copy().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update().
copy_inner_replace_inline()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline (node_t * src, bitmap_t bit, count_t noffset, T value) inline static
Definition at line 473 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::destroy_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::popcount(), immer::detail::uninitialized_copy(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub().
copy_inner_replace_merged()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged (node_t * src, bitmap_t bit, count_t voffset, node_t * node) inline static
Definition at line 431 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::destroy_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::popcount(), immer::detail::uninitialized_copy(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update().
copy_inner_replace_value()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value (node_t * src, count_t offset, T v) inline static
Definition at line 402 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::destroy_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::popcount(), immer::detail::uninitialized_copy(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update().
datamap()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> auto immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap () const inline
Definition at line 144 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::equals_tree(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::for_each_chunk_traversal(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::get().
deallocate_collision()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision (node_t * p, count_t n) inline static
Definition at line 701 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions(), immer::detail::destroy_n(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_collision_n().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_insert(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_remove(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_collision(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision().
deallocate_inner() [1/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner (node_t * p, count_t n) inline static
Definition at line 707 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_inner_n().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
deallocate_inner() [2/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner (node_t * p, count_t n, count_t nv) inline static
Definition at line 712 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_inner_n(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_values_n().
deallocate_values()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_values (values_t * p, count_t n) inline static
Definition at line 695 of file node.hpp.
References immer::detail::destroy_n(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_values_n().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_values().
dec()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> bool immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::dec () const inline
Definition at line 634 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::dec().
dec_unsafe()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::dec_unsafe () const inline
Definition at line 635 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs().
delete_collision()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_collision (node_t * p) inline static
Definition at line 659 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_count(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep_shift().
delete_deep()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep (node_t * p, shift_t s) inline static
Definition at line 667 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_collision(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), and immer::detail::hamts::popcount().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::dec().
delete_deep_shift()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep_shift (node_t * p, shift_t s) inline static
Definition at line 681 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_collision(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), and immer::detail::hamts::popcount().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_merged().
delete_inner()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner (node_t * p) inline static
Definition at line 649 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_values(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::popcount(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep_shift().
delete_values()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_values (values_t * p, count_t n) inline static
Definition at line 643 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_values().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner().
inc() [1/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc () inline
Definition at line 622 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::inc().
inc() [2/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> const node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc () const inline
Definition at line 628 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs().
inc_nodes()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static void immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes (node_t ** p, count_t n) inline static
Definition at line 637 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value().
kind()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> kind_t immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind () const inline
Definition at line 112 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl.
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_count(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_insert(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_remove(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_collision(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
make_collision()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision (T v1, T v2) inline static
Definition at line 287 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_collision_n().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_merged().
make_collision_n()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision_n (count_t n) inline static
Definition at line 275 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_collision_n().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_insert(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_remove(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_collision_replace().
make_inner_n() [1/6]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n (count_t n) inline static
Definition at line 182 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_inner_n().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::empty(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_merged().
make_inner_n() [2/6]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n (count_t n, values_t * values) inline static
Definition at line 196 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
make_inner_n() [3/6]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n (count_t n, count_t nv) inline static
Definition at line 206 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_values_n().
make_inner_n() [4/6]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n (count_t n, count_t idx, node_t * child) inline static
Definition at line 222 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
make_inner_n() [5/6]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n (count_t n, bitmap_t bitmap, T x) inline static
Definition at line 231 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
make_inner_n() [6/6]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n (count_t n, count_t idx1, T x1, count_t idx2, T x2) inline static
Definition at line 246 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
make_merged()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static node_t* immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_merged (shift_t shift, T v1, hash_t hash1, T v2, hash_t hash2) inline static
Definition at line 595 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep_shift(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
Referenced by immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update().
nodemap()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> auto immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap () const inline
Definition at line 150 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_deep_shift(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::equals_tree(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::for_each_chunk_traversal(), and immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::get().
ownee() [1/4]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static const ownee_t& immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::ownee (const values_t * x) inline static
Definition at line 175 of file node.hpp.
ownee() [2/4]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static ownee_t& immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::ownee (values_t * x) inline static
Definition at line 176 of file node.hpp.
ownee() [3/4]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static const ownee_t& immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::ownee (const node_t * x) inline static
Definition at line 179 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl.
ownee() [4/4]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static ownee_t& immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::ownee (node_t * x) inline static
Definition at line 180 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl.
refs() [1/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static refs_t& immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs (const values_t * x) inline static
Definition at line 174 of file node.hpp.
References immer::detail::auto_const_cast().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::dec(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::dec_unsafe(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inc_nodes(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
refs() [2/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static refs_t& immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs (const node_t * x) inline static
Definition at line 178 of file node.hpp.
References immer::detail::auto_const_cast(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl.
sizeof_collision_n()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static constexpr std::size_t immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_collision_n (count_t count) inline static
Definition at line 99 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_t::buffer, count, and immer_offsetof.
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_collision(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision_n().
sizeof_inner_n()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static constexpr std::size_t immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_inner_n (count_t count) inline static
Definition at line 105 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner_t::buffer, count, and immer_offsetof.
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
sizeof_values_n()
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> static constexpr std::size_t immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::sizeof_values_n (count_t count) inline static
Definition at line 93 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values_data_t::buffer, count, and immer_offsetof.
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_values(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
values() [1/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> auto immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values () inline
Definition at line 118 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_insert_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_remove_value(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_inline(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_merged(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace_value(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_add(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_sub(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::do_update(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::equals_tree(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::for_each_chunk_traversal(), immer::detail::hamts::champ< value_t, hash_key, equal_key, MemoryPolicy, B >::get(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n().
values() [2/2]
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> auto immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values () const inline
Definition at line 125 of file node.hpp.
References immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl, immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::inner, and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind().
Member Data Documentation
impl
template<typename T , typename Hash , typename Equal , typename MemoryPolicy , bits_t B> impl_t immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::impl
Definition at line 91 of file node.hpp.
Referenced by immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::children(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collision_count(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::collisions(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::copy_inner_replace(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::datamap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::deallocate_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::delete_inner(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::kind(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_collision_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::make_inner_n(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::nodemap(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::ownee(), immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::refs(), and immer::detail::hamts::node< T, Hash, Equal, MemoryPolicy, B >::values().
The documentation for this struct was generated from the following file:
src/immer/detail/hamts/node.hpp
Released under the MIT license