Dash Core: immer::free_list_heap< Size, Limit, Base > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::free_list_heap< Size, Limit, Base > Struct Template Reference
#include <free_list_heap.hpp>
Classes
struct head_t
Public Types
using base_t = Base
Static Public Member Functions
template<typename... Tags>
static void * allocate (std::size_t size, Tags...)
template<typename... Tags>
static void deallocate (std::size_t size, void *data, Tags...)
Static Private Member Functions
static head_t & head ()
Detailed Description
template<std::size_t Size, std::size_t Limit, typename Base>
struct immer::free_list_heap< Size, Limit, Base >
Adaptor that does not release the memory to the parent heap but instead it keeps the memory in a thread-safe global free list. Must be preceded by a with_data<free_list_node, ...> heap adaptor.
Template Parameters
Size Maximum size of the objects to be allocated.
Base Type of the parent heap.
Definition at line 28 of file free_list_heap.hpp.
Member Typedef Documentation
base_t
template<std::size_t Size, std::size_t Limit, typename Base > using immer::free_list_heap< Size, Limit, Base >::base_t = Base
Definition at line 30 of file free_list_heap.hpp.
Member Function Documentation
allocate()
template<std::size_t Size, std::size_t Limit, typename Base > template<typename... Tags> static void* immer::free_list_heap< Size, Limit, Base >::allocate (std::size_t size, Tags...) inline static
Definition at line 33 of file free_list_heap.hpp.
References immer::free_list_heap< Size, Limit, Base >::head_t::count, immer::free_list_heap< Size, Limit, Base >::head_t::data, immer::free_list_heap< Size, Limit, Base >::head(), and immer::free_list_node::next.
deallocate()
template<std::size_t Size, std::size_t Limit, typename Base > template<typename... Tags> static void immer::free_list_heap< Size, Limit, Base >::deallocate (std::size_t size, void * data, Tags...) inline static
Definition at line 51 of file free_list_heap.hpp.
References count, immer::free_list_heap< Size, Limit, Base >::head_t::count, immer::free_list_heap< Size, Limit, Base >::head_t::data, immer::free_list_heap< Size, Limit, Base >::head(), and immer::free_list_node::next.
head()
template<std::size_t Size, std::size_t Limit, typename Base > static head_t& immer::free_list_heap< Size, Limit, Base >::head () inline static private
Definition at line 76 of file free_list_heap.hpp.
Referenced by immer::free_list_heap< Size, Limit, Base >::allocate(), and immer::free_list_heap< Size, Limit, Base >::deallocate().
The documentation for this struct was generated from the following file:
src/immer/heap/free_list_heap.hpp
Released under the MIT license