Dash Core: immer::detail::rbts::slice_right_visitor< NodeT, Collapse > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::rbts::slice_right_visitor< NodeT, Collapse > Struct Template Reference
#include <operations.hpp>
Public Types
using node_t = NodeT
using this_t = slice_right_visitor
using result_t = std::tuple< shift_t, NodeT *, count_t, NodeT * >
using no_collapse_t = slice_right_visitor< NodeT, false >
Static Public Member Functions
template<typename PosT >
static result_t visit_relaxed (PosT &&pos, size_t last)
template<typename PosT >
static result_t visit_regular (PosT &&pos, size_t last)
template<typename PosT >
static result_t visit_leaf (PosT &&pos, size_t last)
Static Public Member Functions inherited from immer::detail::rbts::visitor_base< slice_right_visitor< NodeT, Collapse > >
static decltype(auto) visit_node (Args &&...args)
static decltype(auto) visit_relaxed (Args &&...args)
static decltype(auto) visit_regular (Args &&...args)
static decltype(auto) visit_inner (Args &&...args)
static decltype(auto) visit_leaf (Args &&...args)
Static Public Attributes
static constexpr auto B = NodeT::bits
static constexpr auto BL = NodeT::bits_leaf
Detailed Description
template<typename NodeT, bool Collapse = true>
struct immer::detail::rbts::slice_right_visitor< NodeT, Collapse >
Definition at line 1024 of file operations.hpp.
Member Typedef Documentation
no_collapse_t
template<typename NodeT, bool Collapse = true> using immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::no_collapse_t = slice_right_visitor<NodeT, false>
Definition at line 1031 of file operations.hpp.
node_t
template<typename NodeT, bool Collapse = true> using immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::node_t = NodeT
Definition at line 1026 of file operations.hpp.
result_t
template<typename NodeT, bool Collapse = true> using immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::result_t = std::tuple<shift_t, NodeT*, count_t, NodeT*>
Definition at line 1030 of file operations.hpp.
this_t
template<typename NodeT, bool Collapse = true> using immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::this_t = slice_right_visitor
Definition at line 1027 of file operations.hpp.
Member Function Documentation
visit_leaf()
template<typename NodeT, bool Collapse = true> template<typename PosT > static result_t immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::visit_leaf (PosT && pos, size_t last) inline static
Definition at line 1113 of file operations.hpp.
visit_regular()
template<typename NodeT, bool Collapse = true> template<typename PosT > static result_t immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::visit_regular (PosT && pos, size_t last) inline static
Definition at line 1077 of file operations.hpp.
References immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::B, immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::BL, immer::detail::rbts::dec_leaf(), immer::detail::rbts::dec_regular(), and immer::detail::csl::get().
visit_relaxed()
template<typename NodeT, bool Collapse = true> template<typename PosT > static result_t immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::visit_relaxed (PosT && pos, size_t last) inline static
Definition at line 1037 of file operations.hpp.
References immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::B, immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::BL, count, immer::detail::rbts::dec_inner(), immer::detail::rbts::dec_leaf(), and immer::detail::csl::get().
Member Data Documentation
B
template<typename NodeT, bool Collapse = true> constexpr auto immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::B = NodeT::bits static
Definition at line 1033 of file operations.hpp.
Referenced by immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::visit_regular(), and immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::visit_relaxed().
BL
template<typename NodeT, bool Collapse = true> constexpr auto immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::BL = NodeT::bits_leaf static
Definition at line 1034 of file operations.hpp.
Referenced by immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::visit_regular(), and immer::detail::rbts::slice_right_visitor< NodeT, Collapse >::visit_relaxed().
The documentation for this struct was generated from the following file:
src/immer/detail/rbts/operations.hpp
Released under the MIT license