Dash Core: DKG Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
DKG Struct Reference
Public Member Functions
DKG (int quorumSize)
void ReceiveVvecs ()
void ReceiveShares (size_t whoAmI)
void BuildQuorumVerificationVector (bool parallel)
void Bench_BuildQuorumVerificationVectors (benchmark::State &state, bool parallel)
void VerifyContributionShares (size_t whoAmI, const std::set< size_t > &invalidIndexes, bool parallel, bool aggregated)
void Bench_VerifyContributionShares (benchmark::State &state, int invalidCount, bool parallel, bool aggregated)
Public Attributes
std::vector< Member > members
std::vector< CBLSId > ids
std::vector< BLSVerificationVectorPtr > receivedVvecs
BLSSecretKeyVector receivedSkShares
BLSVerificationVectorPtr quorumVvec
Detailed Description
Definition at line 18 of file bls_dkg.cpp.
Constructor & Destructor Documentation
DKG()
DKG::DKG (int quorumSize) inline
Definition at line 28 of file bls_dkg.cpp.
References blsWorker, CBLSWorker::GenerateContributions(), ids, and members.
Member Function Documentation
Bench_BuildQuorumVerificationVectors()
void DKG::Bench_BuildQuorumVerificationVectors (benchmark::State & state, bool parallel) inline
Definition at line 68 of file bls_dkg.cpp.
References BuildQuorumVerificationVector(), benchmark::State::KeepRunning(), and ReceiveVvecs().
Bench_VerifyContributionShares()
void DKG::Bench_VerifyContributionShares (benchmark::State & state, int invalidCount, bool parallel, bool aggregated) inline
Definition at line 89 of file bls_dkg.cpp.
References GetRandInt(), benchmark::State::KeepRunning(), members, receivedSkShares, ReceiveShares(), ReceiveVvecs(), and VerifyContributionShares().
BuildQuorumVerificationVector()
void DKG::BuildQuorumVerificationVector (bool parallel) inline
Definition at line 62 of file bls_dkg.cpp.
References blsWorker, CBLSWorker::BuildQuorumVerificationVector(), quorumVvec, and receivedVvecs.
Referenced by Bench_BuildQuorumVerificationVectors().
ReceiveShares()
void DKG::ReceiveShares (size_t whoAmI) inline
Definition at line 54 of file bls_dkg.cpp.
References members, and receivedSkShares.
Referenced by Bench_VerifyContributionShares().
ReceiveVvecs()
void DKG::ReceiveVvecs () inline
Definition at line 45 of file bls_dkg.cpp.
References blsWorker, CBLSWorker::BuildQuorumVerificationVector(), members, quorumVvec, and receivedVvecs.
Referenced by Bench_BuildQuorumVerificationVectors(), and Bench_VerifyContributionShares().
VerifyContributionShares()
void DKG::VerifyContributionShares (size_t whoAmI, const std::set< size_t > & invalidIndexes, bool parallel, bool aggregated) inline
Definition at line 77 of file bls_dkg.cpp.
References blsWorker, members, receivedSkShares, receivedVvecs, and CBLSWorker::VerifyContributionShares().
Referenced by Bench_VerifyContributionShares().
Member Data Documentation
ids
std::vector<CBLSId> DKG::ids
Definition at line 21 of file bls_dkg.cpp.
Referenced by DKG().
members
std::vector<Member> DKG::members
Definition at line 20 of file bls_dkg.cpp.
Referenced by Bench_VerifyContributionShares(), DKG(), ReceiveShares(), ReceiveVvecs(), and VerifyContributionShares().
quorumVvec
BLSVerificationVectorPtr DKG::quorumVvec
Definition at line 26 of file bls_dkg.cpp.
Referenced by BuildQuorumVerificationVector(), and ReceiveVvecs().
receivedSkShares
BLSSecretKeyVector DKG::receivedSkShares
Definition at line 24 of file bls_dkg.cpp.
Referenced by Bench_VerifyContributionShares(), ReceiveShares(), and VerifyContributionShares().
receivedVvecs
std::vector<BLSVerificationVectorPtr> DKG::receivedVvecs
Definition at line 23 of file bls_dkg.cpp.
Referenced by BuildQuorumVerificationVector(), ReceiveVvecs(), and VerifyContributionShares().
The documentation for this struct was generated from the following file:
src/bench/bls_dkg.cpp
Released under the MIT license