Dash Core: pooled_secure_allocator< T >::internal_secure_allocator Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
pooled_secure_allocator< T >::internal_secure_allocator Struct Reference
#include <pooled_secure.h>
Public Types
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
Static Public Member Functions
static char * malloc (const size_type bytes)
static void free (char *const block)
Detailed Description
template<typename T>
struct pooled_secure_allocator< T >::internal_secure_allocator
Definition at line 55 of file pooled_secure.h.
Member Typedef Documentation
difference_type
template<typename T> typedef std::ptrdiff_t pooled_secure_allocator< T >::internal_secure_allocator::difference_type
Definition at line 57 of file pooled_secure.h.
size_type
template<typename T> typedef std::size_t pooled_secure_allocator< T >::internal_secure_allocator::size_type
Definition at line 56 of file pooled_secure.h.
Member Function Documentation
free()
template<typename T> static void pooled_secure_allocator< T >::internal_secure_allocator::free (char *const block) inline static
Definition at line 64 of file pooled_secure.h.
References LockedPool::free(), and LockedPoolManager::Instance().
malloc()
template<typename T> static char* pooled_secure_allocator< T >::internal_secure_allocator::malloc (const size_type bytes) inline static
Definition at line 59 of file pooled_secure.h.
References LockedPool::alloc(), and LockedPoolManager::Instance().
The documentation for this struct was generated from the following file:
src/support/allocators/pooled_secure.h
Released under the MIT license