Dash Core: immer::detail::rbts::update_visitor< NodeT > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::rbts::update_visitor< NodeT > Struct Template Reference
#include <operations.hpp>
Public Types
using node_t = NodeT
using this_t = update_visitor
Static Public Member Functions
template<typename Pos , typename Fn >
static node_t * visit_relaxed (Pos &&pos, size_t idx, Fn &&fn)
template<typename Pos , typename Fn >
static node_t * visit_regular (Pos &&pos, size_t idx, Fn &&fn)
template<typename Pos , typename Fn >
static node_t * visit_leaf (Pos &&pos, size_t idx, Fn &&fn)
Static Public Member Functions inherited from immer::detail::rbts::visitor_base< update_visitor< NodeT > >
static decltype(auto) visit_node (Args &&...args)
static decltype(auto) visit_relaxed (Args &&...args)
static decltype(auto) visit_regular (Args &&...args)
static decltype(auto) visit_inner (Args &&...args)
static decltype(auto) visit_leaf (Args &&...args)
Detailed Description
template<typename NodeT>
struct immer::detail::rbts::update_visitor< NodeT >
Definition at line 447 of file operations.hpp.
Member Typedef Documentation
node_t
template<typename NodeT > using immer::detail::rbts::update_visitor< NodeT >::node_t = NodeT
Definition at line 449 of file operations.hpp.
this_t
template<typename NodeT > using immer::detail::rbts::update_visitor< NodeT >::this_t = update_visitor
Definition at line 450 of file operations.hpp.
Member Function Documentation
visit_leaf()
template<typename NodeT > template<typename Pos , typename Fn > static node_t* immer::detail::rbts::update_visitor< NodeT >::visit_leaf (Pos && pos, size_t idx, Fn && fn) inline static
Definition at line 489 of file operations.hpp.
References immer::detail::rbts::node< T, MemoryPolicy, B, BL >::leaf().
visit_regular()
template<typename NodeT > template<typename Pos , typename Fn > static node_t* immer::detail::rbts::update_visitor< NodeT >::visit_regular (Pos && pos, size_t idx, Fn && fn) inline static
Definition at line 471 of file operations.hpp.
References count, immer::detail::rbts::node< T, MemoryPolicy, B, BL >::dec_unsafe(), and immer::detail::rbts::node< T, MemoryPolicy, B, BL >::inner().
visit_relaxed()
template<typename NodeT > template<typename Pos , typename Fn > static node_t* immer::detail::rbts::update_visitor< NodeT >::visit_relaxed (Pos && pos, size_t idx, Fn && fn) inline static
Definition at line 453 of file operations.hpp.
References count, immer::detail::rbts::node< T, MemoryPolicy, B, BL >::dec_unsafe(), and immer::detail::rbts::node< T, MemoryPolicy, B, BL >::inner().
The documentation for this struct was generated from the following file:
src/immer/detail/rbts/operations.hpp
Released under the MIT license