Dash Core: CExtKey Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CExtKey Struct Reference
#include <key.h>
Public Member Functions
void Encode (unsigned char code[74]) const
void Decode (const unsigned char code[74])
bool Derive (CExtKey &out, unsigned int nChild) const
CExtPubKey Neuter () const
void SetMaster (const unsigned char *seed, unsigned int nSeedLen)
template<typename Stream >
void Serialize (Stream &s, int nType, int nVersion) const
template<typename Stream >
void Unserialize (Stream &s, int nType, int nVersion)
Public Attributes
unsigned char nDepth
unsigned char vchFingerprint [4]
unsigned int nChild
ChainCode chaincode
CKey key
Friends
bool operator== (const CExtKey &a, const CExtKey &b)
Detailed Description
Definition at line 154 of file key.h.
Member Function Documentation
Decode()
void CExtKey::Decode (const unsigned char code[74])
Definition at line 289 of file key.cpp.
References base_blob< BITS >::begin(), chaincode, key, memcpy(), nChild, nDepth, CKey::Set(), and vchFingerprint.
Referenced by Unserialize().
Derive()
bool CExtKey::Derive (CExtKey & out, unsigned int nChild) const
Definition at line 247 of file key.cpp.
References chaincode, CKey::Derive(), CPubKey::GetID(), CKey::GetPubKey(), key, memcpy(), nChild, nDepth, and vchFingerprint.
Referenced by CHDChain::DeriveChildExtKey().
Encode()
void CExtKey::Encode (unsigned char code[74]) const
Definition at line 278 of file key.cpp.
References base_blob< BITS >::begin(), CKey::begin(), chaincode, key, memcpy(), nChild, nDepth, CKey::size(), and vchFingerprint.
Referenced by Serialize().
Neuter()
CExtPubKey CExtKey::Neuter () const
Definition at line 268 of file key.cpp.
References chaincode, CExtPubKey::chaincode, CKey::GetPubKey(), key, memcpy(), nChild, CExtPubKey::nChild, nDepth, CExtPubKey::nDepth, CExtPubKey::pubkey, vchFingerprint, and CExtPubKey::vchFingerprint.
Referenced by CHDChain::Debug(), CWallet::DeriveNewChildKey(), and dumpwallet().
Serialize()
template<typename Stream > void CExtKey::Serialize (Stream & s, int nType, int nVersion) const inline
Definition at line 173 of file key.h.
References Encode(), and WriteCompactSize().
SetMaster()
void CExtKey::SetMaster (const unsigned char * seed, unsigned int nSeedLen)
Definition at line 255 of file key.cpp.
References base_blob< BITS >::begin(), chaincode, CHMAC_SHA512::Finalize(), key, LockObject(), memcpy(), nChild, nDepth, CKey::Set(), UnlockObject(), vchFingerprint, and CHMAC_SHA512::Write().
Referenced by CHDChain::Debug(), CHDChain::DeriveChildExtKey(), and dumpwallet().
Unserialize()
template<typename Stream > void CExtKey::Unserialize (Stream & s, int nType, int nVersion) inline
Definition at line 182 of file key.h.
References Decode(), and ReadCompactSize().
Friends And Related Function Documentation
operator==
bool operator== (const CExtKey & a, const CExtKey & b) friend
Definition at line 161 of file key.h.
Member Data Documentation
chaincode
ChainCode CExtKey::chaincode
Definition at line 158 of file key.h.
Referenced by Decode(), Derive(), Encode(), Neuter(), and SetMaster().
key
CKey CExtKey::key
Definition at line 159 of file key.h.
Referenced by Decode(), Derive(), CWallet::DeriveNewChildKey(), Encode(), CWallet::GetKey(), Neuter(), and SetMaster().
nChild
unsigned int CExtKey::nChild
Definition at line 157 of file key.h.
Referenced by Decode(), Derive(), Encode(), Neuter(), and SetMaster().
nDepth
unsigned char CExtKey::nDepth
Definition at line 155 of file key.h.
Referenced by Decode(), Derive(), Encode(), Neuter(), and SetMaster().
vchFingerprint
unsigned char CExtKey::vchFingerprint[4]
Definition at line 156 of file key.h.
Referenced by Decode(), Derive(), Encode(), Neuter(), and SetMaster().
The documentation for this struct was generated from the following files:
src/key.h
src/key.cpp
Released under the MIT license