Dash Core: immer::detail::iterator_core_access Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::iterator_core_access Struct Reference
#include <iterator_facade.hpp>
Static Public Member Functions
template<typename T >
static decltype(auto) dereference (T &&x)
template<typename T >
static decltype(auto) increment (T &&x)
template<typename T >
static decltype(auto) decrement (T &&x)
template<typename T1 , typename T2 >
static decltype(auto) equal (T1 &&x1, T2 &&x2)
template<typename T , typename D >
static decltype(auto) advance (T &&x, D d)
template<typename T1 , typename T2 >
static decltype(auto) distance_to (T1 &&x1, T2 &&x2)
Detailed Description
Definition at line 18 of file iterator_facade.hpp.
Member Function Documentation
advance()
template<typename T , typename D > static decltype(auto) immer::detail::iterator_core_access::advance (T && x, D d) inline static
Definition at line 37 of file iterator_facade.hpp.
Referenced by immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator+=(), and immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator-=().
decrement()
template<typename T > static decltype(auto) immer::detail::iterator_core_access::decrement (T && x) inline static
Definition at line 29 of file iterator_facade.hpp.
Referenced by immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator--().
dereference()
template<typename T > static decltype(auto) immer::detail::iterator_core_access::dereference (T && x) inline static
Definition at line 21 of file iterator_facade.hpp.
Referenced by immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator*(), and immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator->().
distance_to()
template<typename T1 , typename T2 > static decltype(auto) immer::detail::iterator_core_access::distance_to (T1 && x1, T2 && x2) inline static
Definition at line 41 of file iterator_facade.hpp.
Referenced by immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator-(), immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator<(), immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator<=(), immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator>(), and immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator>=().
equal()
template<typename T1 , typename T2 > static decltype(auto) immer::detail::iterator_core_access::equal (T1 && x1, T2 && x2) inline static
Definition at line 33 of file iterator_facade.hpp.
Referenced by immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator!=(), and immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator==().
increment()
template<typename T > static decltype(auto) immer::detail::iterator_core_access::increment (T && x) inline static
Definition at line 25 of file iterator_facade.hpp.
Referenced by immer::detail::iterator_facade< rrbtree_iterator< T, MP, B, BL >, std::random_access_iterator_tag, T, const T &, std::ptrdiff_t, const T *>::operator++().
The documentation for this struct was generated from the following file:
src/immer/detail/iterator_facade.hpp
Released under the MIT license