Dash Core: CAddressIndexIteratorHeightKey Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
CAddressIndexIteratorHeightKey Struct Reference
#include <spentindex.h>
Public Member Functions
size_t GetSerializeSize (int nType, int nVersion) const
template<typename Stream >
void Serialize (Stream &s) const
template<typename Stream >
void Unserialize (Stream &s)
CAddressIndexIteratorHeightKey (unsigned int addressType, uint160 addressHash, int height)
CAddressIndexIteratorHeightKey ()
void SetNull ()
Public Attributes
unsigned int type
uint160 hashBytes
int blockHeight
Detailed Description
Definition at line 340 of file spentindex.h.
Constructor & Destructor Documentation
CAddressIndexIteratorHeightKey() [1/2]
CAddressIndexIteratorHeightKey::CAddressIndexIteratorHeightKey (unsigned int addressType, uint160 addressHash, int height) inline
Definition at line 361 of file spentindex.h.
References blockHeight, hashBytes, and type.
CAddressIndexIteratorHeightKey() [2/2]
CAddressIndexIteratorHeightKey::CAddressIndexIteratorHeightKey () inline
Definition at line 367 of file spentindex.h.
References SetNull().
Member Function Documentation
GetSerializeSize()
size_t CAddressIndexIteratorHeightKey::GetSerializeSize (int nType, int nVersion) const inline
Definition at line 345 of file spentindex.h.
Serialize()
template<typename Stream > void CAddressIndexIteratorHeightKey::Serialize (Stream & s) const inline
Definition at line 349 of file spentindex.h.
References blockHeight, hashBytes, ser_writedata32be(), ser_writedata8(), base_blob< BITS >::Serialize(), and type.
SetNull()
void CAddressIndexIteratorHeightKey::SetNull () inline
Definition at line 371 of file spentindex.h.
References blockHeight, hashBytes, base_blob< BITS >::SetNull(), and type.
Referenced by CAddressIndexIteratorHeightKey().
Unserialize()
template<typename Stream > void CAddressIndexIteratorHeightKey::Unserialize (Stream & s) inline
Definition at line 355 of file spentindex.h.
References blockHeight, hashBytes, ser_readdata32be(), ser_readdata8(), type, and base_blob< BITS >::Unserialize().
Member Data Documentation
blockHeight
int CAddressIndexIteratorHeightKey::blockHeight
Definition at line 343 of file spentindex.h.
Referenced by CAddressIndexIteratorHeightKey(), Serialize(), SetNull(), and Unserialize().
hashBytes
uint160 CAddressIndexIteratorHeightKey::hashBytes
Definition at line 342 of file spentindex.h.
Referenced by CAddressIndexIteratorHeightKey(), Serialize(), SetNull(), and Unserialize().
type
unsigned int CAddressIndexIteratorHeightKey::type
Definition at line 341 of file spentindex.h.
Referenced by CAddressIndexIteratorHeightKey(), Serialize(), SetNull(), and Unserialize().
The documentation for this struct was generated from the following file:
src/spentindex.h
Released under the MIT license