Dash Core: immer::detail::rbts::equals_visitor Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::rbts::equals_visitor Struct Reference
#include <operations.hpp>
Classes
struct rrb
struct this_aux_t
Public Types
using this_t = equals_visitor
Static Public Member Functions
template<typename Iter >
static auto equal_chunk_p (Iter &&iter)
template<typename PosL , typename PosR , typename Iter >
static bool visit_relaxed (PosL &&posl, PosR &&posr, Iter &&first, size_t idx)
template<typename PosL , typename PosR , typename Iter >
static std::enable_if_t< is_relaxed_v< PosR >, bool > visit_regular (PosL &&posl, PosR &&posr, Iter &&first, size_t idx)
template<typename PosL , typename PosR , typename Iter >
static std::enable_if_t<!is_relaxed_v< PosR >, bool > visit_regular (PosL &&posl, PosR &&posr, Iter &&first, size_t idx)
template<typename PosL , typename PosR , typename Iter >
static bool visit_leaf (PosL &&posl, PosR &&posr, Iter &&first, size_t idx)
template<typename Pos , typename NodeT >
static bool visit_regular (Pos &&pos, NodeT *other)
template<typename Pos , typename NodeT >
static bool visit_leaf (Pos &&pos, NodeT *other)
Static Public Member Functions inherited from immer::detail::rbts::visitor_base< equals_visitor >
static decltype(auto) visit_node (Args &&...args)
static decltype(auto) visit_relaxed (Args &&...args)
static decltype(auto) visit_regular (Args &&...args)
static decltype(auto) visit_inner (Args &&...args)
static decltype(auto) visit_leaf (Args &&...args)
Detailed Description
Definition at line 320 of file operations.hpp.
Member Typedef Documentation
this_t
using immer::detail::rbts::equals_visitor::this_t = equals_visitor
Definition at line 322 of file operations.hpp.
Member Function Documentation
equal_chunk_p()
template<typename Iter > static auto immer::detail::rbts::equals_visitor::equal_chunk_p (Iter && iter) inline static
Definition at line 354 of file operations.hpp.
Referenced by visit_relaxed().
visit_leaf() [1/2]
template<typename PosL , typename PosR , typename Iter > static bool immer::detail::rbts::equals_visitor::visit_leaf (PosL && posl, PosR && posr, Iter && first, size_t idx) inline static
Definition at line 411 of file operations.hpp.
visit_leaf() [2/2]
template<typename Pos , typename NodeT > static bool immer::detail::rbts::equals_visitor::visit_leaf (Pos && pos, NodeT * other) inline static
Definition at line 437 of file operations.hpp.
References immer::detail::rbts::node< T, MemoryPolicy, B, BL >::leaf().
visit_regular() [1/3]
template<typename PosL , typename PosR , typename Iter > static std::enable_if_t<is_relaxed_v<PosR>, bool> immer::detail::rbts::equals_visitor::visit_regular (PosL && posl, PosR && posr, Iter && first, size_t idx) inline static
Definition at line 396 of file operations.hpp.
References visit_relaxed().
Referenced by visit_regular().
visit_regular() [2/3]
template<typename PosL , typename PosR , typename Iter > static std::enable_if_t<!is_relaxed_v<PosR>, bool> immer::detail::rbts::equals_visitor::visit_regular (PosL && posl, PosR && posr, Iter && first, size_t idx) inline static
Definition at line 403 of file operations.hpp.
References visit_regular().
visit_regular() [3/3]
template<typename Pos , typename NodeT > static bool immer::detail::rbts::equals_visitor::visit_regular (Pos && pos, NodeT * other) inline static
Definition at line 429 of file operations.hpp.
visit_relaxed()
template<typename PosL , typename PosR , typename Iter > static bool immer::detail::rbts::equals_visitor::visit_relaxed (PosL && posl, PosR && posr, Iter && first, size_t idx) inline static
Definition at line 369 of file operations.hpp.
References equal_chunk_p().
Referenced by visit_regular().
The documentation for this struct was generated from the following file:
src/immer/detail/rbts/operations.hpp
Released under the MIT license