Dash Core: secp256k1_callback Struct Reference
secp256k1_callback Struct Reference
#include <util.h>
Public Attributes
void(* fn)(const char *text, void *data)
const void * data
Detailed Description
Definition at line 18 of file util.h.
Member Data Documentation
data
const void* secp256k1_callback::data
Definition at line 20 of file util.h.
Referenced by secp256k1_callback_call(), secp256k1_context_set_error_callback(), and secp256k1_context_set_illegal_callback().
fn
void(* secp256k1_callback::fn) (const char *text, void *data)
Definition at line 19 of file util.h.
Referenced by run_context_tests(), secp256k1_callback_call(), secp256k1_context_set_error_callback(), and secp256k1_context_set_illegal_callback().
The documentation for this struct was generated from the following file:
src/secp256k1/src/util.h