Dash Core: immer::detail::rbts::regular_pos< NodeT > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::rbts::regular_pos< NodeT > Struct Template Reference
#include <position.hpp>
Public Types
using node_t = NodeT
Public Member Functions
count_t count () const
node_t * node () const
size_t size () const
shift_t shift () const
count_t index (size_t idx) const
count_t subindex (size_t idx) const
size_t this_size () const
template<typename Visitor , typename... Args>
void each (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred_zip (Visitor v, node_t *other, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred_i (Visitor v, count_t i, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred_right (Visitor v, count_t start, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred_left (Visitor v, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
void each_i (Visitor v, count_t i, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
void each_right (Visitor v, count_t start, Args &&... args)
template<typename Visitor , typename... Args>
void each_left (Visitor v, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards (Visitor v, size_t idx, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards_oh_ch (Visitor v, size_t idx, count_t offset_hint, count_t count_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards_sub_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) last_oh (Visitor v, count_t offset_hint, Args &&... args)
template<typename Visitor , typename ... Args>
decltype(auto) visit (Visitor v, Args &&...args)
Public Attributes
node_t * node_
shift_t shift_
size_t size_
Static Public Attributes
static constexpr auto B = NodeT::bits
static constexpr auto BL = NodeT::bits_leaf
Detailed Description
template<typename NodeT>
struct immer::detail::rbts::regular_pos< NodeT >
Definition at line 213 of file position.hpp.
Member Typedef Documentation
node_t
template<typename NodeT > using immer::detail::rbts::regular_pos< NodeT >::node_t = NodeT
Definition at line 218 of file position.hpp.
Member Function Documentation
count()
template<typename NodeT > count_t immer::detail::rbts::regular_pos< NodeT >::count () const inline
Definition at line 223 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::index(), and immer::detail::rbts::regular_pos< NodeT >::size_.
Referenced by immer::detail::rbts::regular_pos< NodeT >::towards(), immer::detail::rbts::regular_pos< NodeT >::towards_oh(), and immer::detail::rbts::regular_pos< NodeT >::towards_oh_ch().
each()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::regular_pos< NodeT >::each (Visitor v, Args &&... args) inline
Definition at line 232 of file position.hpp.
References immer::detail::rbts::each_regular().
each_i()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::regular_pos< NodeT >::each_i (Visitor v, count_t i, count_t n, Args &&... args) inline
Definition at line 256 of file position.hpp.
References immer::detail::rbts::each_i_regular().
each_left()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::regular_pos< NodeT >::each_left (Visitor v, count_t n, Args &&... args) inline
Definition at line 264 of file position.hpp.
References immer::detail::rbts::each_left_regular().
each_pred()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::regular_pos< NodeT >::each_pred (Visitor v, Args &&... args) inline
Definition at line 236 of file position.hpp.
References immer::detail::rbts::each_pred_regular().
each_pred_i()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::regular_pos< NodeT >::each_pred_i (Visitor v, count_t i, count_t n, Args &&... args) inline
Definition at line 244 of file position.hpp.
References immer::detail::rbts::each_pred_i_regular().
each_pred_left()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::regular_pos< NodeT >::each_pred_left (Visitor v, count_t n, Args &&... args) inline
Definition at line 252 of file position.hpp.
References immer::detail::rbts::each_pred_left_regular().
each_pred_right()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::regular_pos< NodeT >::each_pred_right (Visitor v, count_t start, Args &&... args) inline
Definition at line 248 of file position.hpp.
References immer::detail::rbts::each_pred_right_regular().
each_pred_zip()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::regular_pos< NodeT >::each_pred_zip (Visitor v, node_t * other, Args &&... args) inline
Definition at line 240 of file position.hpp.
References immer::detail::rbts::each_pred_zip_regular().
each_right()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::regular_pos< NodeT >::each_right (Visitor v, count_t start, Args &&... args) inline
Definition at line 260 of file position.hpp.
References immer::detail::rbts::each_right_regular().
index()
template<typename NodeT > count_t immer::detail::rbts::regular_pos< NodeT >::index (size_t idx) const inline
Definition at line 227 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::shift_.
Referenced by immer::detail::rbts::regular_pos< NodeT >::count(), and immer::detail::rbts::regular_pos< NodeT >::towards().
last_oh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::regular_pos< NodeT >::last_oh (Visitor v, count_t offset_hint, Args &&... args) inline
Definition at line 291 of file position.hpp.
References immer::detail::rbts::last_oh_regular().
node()
template<typename NodeT > node_t* immer::detail::rbts::regular_pos< NodeT >::node () const inline
Definition at line 224 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::node_.
shift()
template<typename NodeT > shift_t immer::detail::rbts::regular_pos< NodeT >::shift () const inline
Definition at line 226 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::shift_.
size()
template<typename NodeT > size_t immer::detail::rbts::regular_pos< NodeT >::size () const inline
Definition at line 225 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::size_.
subindex()
template<typename NodeT > count_t immer::detail::rbts::regular_pos< NodeT >::subindex (size_t idx) const inline
Definition at line 228 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::shift_.
this_size()
template<typename NodeT > size_t immer::detail::rbts::regular_pos< NodeT >::this_size () const inline
Definition at line 229 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::B, immer::detail::rbts::regular_pos< NodeT >::shift_, and immer::detail::rbts::regular_pos< NodeT >::size_.
towards()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::regular_pos< NodeT >::towards (Visitor v, size_t idx, Args &&... args) inline
Definition at line 268 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::count(), immer::detail::rbts::regular_pos< NodeT >::index(), and immer::detail::rbts::towards_oh_ch_regular().
towards_oh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::regular_pos< NodeT >::towards_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args) inline
Definition at line 272 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::count(), and immer::detail::rbts::towards_oh_ch_regular().
towards_oh_ch()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::regular_pos< NodeT >::towards_oh_ch (Visitor v, size_t idx, count_t offset_hint, count_t count_hint, Args &&... args) inline
Definition at line 278 of file position.hpp.
References immer::detail::rbts::regular_pos< NodeT >::count(), and immer::detail::rbts::towards_oh_ch_regular().
towards_sub_oh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::regular_pos< NodeT >::towards_sub_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args) inline
Definition at line 285 of file position.hpp.
References immer::detail::rbts::towards_sub_oh_regular().
visit()
template<typename NodeT > template<typename Visitor , typename ... Args> decltype(auto) immer::detail::rbts::regular_pos< NodeT >::visit (Visitor v, Args &&... args) inline
Definition at line 295 of file position.hpp.
Member Data Documentation
B
template<typename NodeT > constexpr auto immer::detail::rbts::regular_pos< NodeT >::B = NodeT::bits static
Definition at line 215 of file position.hpp.
Referenced by immer::detail::rbts::regular_pos< NodeT >::this_size().
BL
template<typename NodeT > constexpr auto immer::detail::rbts::regular_pos< NodeT >::BL = NodeT::bits_leaf static
Definition at line 216 of file position.hpp.
node_
template<typename NodeT > node_t* immer::detail::rbts::regular_pos< NodeT >::node_
Definition at line 219 of file position.hpp.
Referenced by immer::detail::rbts::regular_pos< NodeT >::node().
shift_
template<typename NodeT > shift_t immer::detail::rbts::regular_pos< NodeT >::shift_
Definition at line 220 of file position.hpp.
Referenced by immer::detail::rbts::regular_pos< NodeT >::index(), immer::detail::rbts::regular_pos< NodeT >::shift(), immer::detail::rbts::regular_pos< NodeT >::subindex(), and immer::detail::rbts::regular_pos< NodeT >::this_size().
size_
template<typename NodeT > size_t immer::detail::rbts::regular_pos< NodeT >::size_
Definition at line 221 of file position.hpp.
Referenced by immer::detail::rbts::regular_pos< NodeT >::count(), immer::detail::rbts::regular_pos< NodeT >::size(), and immer::detail::rbts::regular_pos< NodeT >::this_size().
The documentation for this struct was generated from the following file:
src/immer/detail/rbts/position.hpp
Released under the MIT license