Dash Core: immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL > Struct Template Reference
#include <position.hpp>
Public Types
using node_t = NodeT
using relaxed_t = typename NodeT::relaxed_t
Public Member Functions
count_t count () const
node_t * node () const
shift_t shift () const
size_t size () const
count_t index (size_t idx) const
template<typename Visitor >
decltype(auto) descend (Visitor v, size_t idx)
template<typename Visitor , typename ... Args>
decltype(auto) visit (Visitor v, Args &&...args)
Public Attributes
node_t * node_
relaxed_t * relaxed_
Detailed Description
template<typename NodeT, shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf>
struct immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >
Definition at line 1716 of file position.hpp.
Member Typedef Documentation
node_t
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> using immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::node_t = NodeT
Definition at line 1720 of file position.hpp.
relaxed_t
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> using immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::relaxed_t = typename NodeT::relaxed_t
Definition at line 1721 of file position.hpp.
Member Function Documentation
count()
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> count_t immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::count () const inline
Definition at line 1725 of file position.hpp.
References immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::relaxed_.
descend()
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> template<typename Visitor > decltype(auto) immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::descend (Visitor v, size_t idx) inline
Definition at line 1746 of file position.hpp.
References immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::index(), immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::node_, immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::relaxed_, immer::detail::rbts::regular_descent_pos< NodeT, Shift, B, BL >::visit(), and immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::visit().
index()
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> count_t immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::index (size_t idx) const inline
Definition at line 1730 of file position.hpp.
References immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::relaxed_.
Referenced by immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::descend(), and immer::detail::rbts::relaxed_descent_pos< NodeT, BL, B, BL >::descend().
node()
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> node_t* immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::node () const inline
Definition at line 1726 of file position.hpp.
References immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::node_.
shift()
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> shift_t immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::shift () const inline
Definition at line 1727 of file position.hpp.
size()
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> size_t immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::size () const inline
Definition at line 1728 of file position.hpp.
References immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::relaxed_.
visit()
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> template<typename Visitor , typename ... Args> decltype(auto) immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::visit (Visitor v, Args &&... args) inline
Definition at line 1759 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::descend().
Member Data Documentation
node_
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> node_t* immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::node_
Definition at line 1722 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::descend(), immer::detail::rbts::relaxed_descent_pos< NodeT, BL, B, BL >::descend(), immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::node(), and immer::detail::rbts::relaxed_descent_pos< NodeT, BL, B, BL >::node().
relaxed_
template<typename NodeT , shift_t Shift, bits_t B = NodeT::bits, bits_t BL = NodeT::bits_leaf> relaxed_t* immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::relaxed_
Definition at line 1723 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::count(), immer::detail::rbts::relaxed_descent_pos< NodeT, BL, B, BL >::count(), immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::descend(), immer::detail::rbts::relaxed_descent_pos< NodeT, BL, B, BL >::descend(), immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::index(), immer::detail::rbts::relaxed_descent_pos< NodeT, BL, B, BL >::index(), immer::detail::rbts::relaxed_descent_pos< NodeT, Shift, B, BL >::size(), and immer::detail::rbts::relaxed_descent_pos< NodeT, BL, B, BL >::size().
The documentation for this struct was generated from the following file:
src/immer/detail/rbts/position.hpp
Released under the MIT license