Dash Core: CMainSignals Struct Reference
CMainSignals Struct Reference
#include <validationinterface.h>
Public Attributes
boost::signals2::signal< void(const CBlockIndex *)> AcceptedBlockHeader
boost::signals2::signal< void(const CBlockIndex *, bool fInitialDownload)> NotifyHeaderTip
boost::signals2::signal< void(const CBlockIndex *, const CBlockIndex *, bool fInitialDownload)> UpdatedBlockTip
boost::signals2::signal< void(const CTransaction &, const CBlock *)> SyncTransaction
boost::signals2::signal< void(const CTransaction &)> NotifyTransactionLock
boost::signals2::signal< bool(const uint256 &)> UpdatedTransaction
boost::signals2::signal< void(const CBlockLocator &)> SetBestChain
boost::signals2::signal< void(const uint256 &)> Inventory
boost::signals2::signal< void(int64_t nBestBlockTime, CConnman *connman)> Broadcast
boost::signals2::signal< void(const CBlock &, const CValidationState &)> BlockChecked
boost::signals2::signal< void(boost::shared_ptr< CReserveScript > &)> ScriptForMining
boost::signals2::signal< void(const uint256 &)> BlockFound
Detailed Description
Definition at line 50 of file validationinterface.h.
Member Data Documentation
AcceptedBlockHeader
boost::signals2::signal<void (const CBlockIndex *)> CMainSignals::AcceptedBlockHeader
Notifies listeners of accepted block header
Definition at line 52 of file validationinterface.h.
Referenced by AcceptBlockHeader(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
BlockChecked
boost::signals2::signal<void (const CBlock&, const CValidationState&)> CMainSignals::BlockChecked
Notifies listeners of a block validation result
Definition at line 70 of file validationinterface.h.
Referenced by ConnectTip(), ProcessNewBlock(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
BlockFound
boost::signals2::signal<void (const uint256 &)> CMainSignals::BlockFound
Notifies listeners that a block has been successfully mined
Definition at line 74 of file validationinterface.h.
Referenced by ProcessBlockFound(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
Broadcast
boost::signals2::signal<void (int64_t nBestBlockTime, CConnman* connman)> CMainSignals::Broadcast
Tells listeners to broadcast their data.
Definition at line 68 of file validationinterface.h.
Referenced by RegisterValidationInterface(), SendMessages(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
Inventory
boost::signals2::signal<void (const uint256 &)> CMainSignals::Inventory
Notifies listeners about an inventory item being seen on the network.
Definition at line 66 of file validationinterface.h.
Referenced by ProcessGetData(), ProcessMessage(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
NotifyHeaderTip
boost::signals2::signal<void (const CBlockIndex *, bool fInitialDownload)> CMainSignals::NotifyHeaderTip
Notifies listeners of updated block header tip
Definition at line 54 of file validationinterface.h.
Referenced by NotifyHeaderTip(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
NotifyTransactionLock
boost::signals2::signal<void (const CTransaction &)> CMainSignals::NotifyTransactionLock
Notifies listeners of an updated transaction lock without new data.
Definition at line 60 of file validationinterface.h.
Referenced by RegisterValidationInterface(), UnregisterAllValidationInterfaces(), UnregisterValidationInterface(), and CInstantSend::UpdateLockedTransaction().
ScriptForMining
boost::signals2::signal<void (boost::shared_ptr<CReserveScript>&)> CMainSignals::ScriptForMining
Notifies listeners that a key for mining is required (coinbase)
Definition at line 72 of file validationinterface.h.
Referenced by BitcoinMiner(), generate(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
SetBestChain
boost::signals2::signal<void (const CBlockLocator &)> CMainSignals::SetBestChain
Notifies listeners of a new active block chain.
Definition at line 64 of file validationinterface.h.
Referenced by FlushStateToDisk(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
SyncTransaction
boost::signals2::signal<void (const CTransaction &, const CBlock *)> CMainSignals::SyncTransaction
Notifies listeners of updated transaction data (transaction, and optionally the block it is found in.
Definition at line 58 of file validationinterface.h.
Referenced by AcceptToMemoryPoolWorker(), ConnectTip(), DisconnectTip(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
UpdatedBlockTip
boost::signals2::signal<void (const CBlockIndex *, const CBlockIndex *, bool fInitialDownload)> CMainSignals::UpdatedBlockTip
Notifies listeners of updated block chain tip
Definition at line 56 of file validationinterface.h.
Referenced by ActivateBestChain(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
UpdatedTransaction
boost::signals2::signal<bool (const uint256 &)> CMainSignals::UpdatedTransaction
Notifies listeners of an updated transaction without new data (for now: a coinbase potentially becoming visible).
Definition at line 62 of file validationinterface.h.
Referenced by ConnectBlock(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
The documentation for this struct was generated from the following file:
src/validationinterface.h