Dash Core: immer::detail::arrays::no_capacity< T, MemoryPolicy > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::arrays::no_capacity< T, MemoryPolicy > Struct Template Reference
#include <no_capacity.hpp>
Public Types
using node_t = node< T, MemoryPolicy >
using edit_t = typename MemoryPolicy::transience_t::edit
using size_t = std::size_t
Public Member Functions
no_capacity (node_t *p, size_t s)
no_capacity (const no_capacity &other)
no_capacity (no_capacity &&other)
no_capacity & operator= (const no_capacity &other)
no_capacity & operator= (no_capacity &&other)
~no_capacity ()
void inc ()
void dec ()
T * data ()
const T * data () const
template<typename Fn >
void for_each_chunk (Fn &&fn) const
template<typename Fn >
bool for_each_chunk_p (Fn &&fn) const
const T & get (std::size_t index) const
const T & get_check (std::size_t index) const
bool equals (const no_capacity &other) const
no_capacity push_back (T value) const
no_capacity assoc (std::size_t idx, T value) const
template<typename Fn >
no_capacity update (std::size_t idx, Fn &&op) const
no_capacity take (std::size_t sz) const
Static Public Member Functions
static const no_capacity & empty ()
template<typename Iter , typename Sent , std::enable_if_t< is_forward_iterator_v< Iter > &&compatible_sentinel_v< Iter, Sent >, bool > = true>
static no_capacity from_range (Iter first, Sent last)
static no_capacity from_fill (size_t n, T v)
template<typename U >
static no_capacity from_initializer_list (std::initializer_list< U > values)
Public Attributes
node_t * ptr
size_t size
Friends
void swap (no_capacity &x, no_capacity &y)
Detailed Description
template<typename T, typename MemoryPolicy>
struct immer::detail::arrays::no_capacity< T, MemoryPolicy >
Definition at line 19 of file no_capacity.hpp.
Member Typedef Documentation
edit_t
template<typename T , typename MemoryPolicy > using immer::detail::arrays::no_capacity< T, MemoryPolicy >::edit_t = typename MemoryPolicy::transience_t::edit
Definition at line 22 of file no_capacity.hpp.
node_t
template<typename T , typename MemoryPolicy > using immer::detail::arrays::no_capacity< T, MemoryPolicy >::node_t = node<T, MemoryPolicy>
Definition at line 21 of file no_capacity.hpp.
size_t
template<typename T , typename MemoryPolicy > using immer::detail::arrays::no_capacity< T, MemoryPolicy >::size_t = std::size_t
Definition at line 23 of file no_capacity.hpp.
Constructor & Destructor Documentation
no_capacity() [1/3]
template<typename T , typename MemoryPolicy > immer::detail::arrays::no_capacity< T, MemoryPolicy >::no_capacity (node_t * p, size_t s) inline
Definition at line 37 of file no_capacity.hpp.
no_capacity() [2/3]
template<typename T , typename MemoryPolicy > immer::detail::arrays::no_capacity< T, MemoryPolicy >::no_capacity (const no_capacity< T, MemoryPolicy > & other) inline
Definition at line 41 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr, and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
no_capacity() [3/3]
template<typename T , typename MemoryPolicy > immer::detail::arrays::no_capacity< T, MemoryPolicy >::no_capacity (no_capacity< T, MemoryPolicy > && other) inline
Definition at line 47 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::empty().
~no_capacity()
template<typename T , typename MemoryPolicy > immer::detail::arrays::no_capacity< T, MemoryPolicy >::~no_capacity () inline
Definition at line 73 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::dec().
Member Function Documentation
assoc()
template<typename T , typename MemoryPolicy > no_capacity immer::detail::arrays::no_capacity< T, MemoryPolicy >::assoc (std::size_t idx, T value) const inline
Definition at line 162 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::copy_n(), immer::detail::arrays::node< T, MemoryPolicy >::delete_n(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr, and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
data() [1/2]
template<typename T , typename MemoryPolicy > T* immer::detail::arrays::no_capacity< T, MemoryPolicy >::data () inline
Definition at line 91 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::data(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr.
Referenced by immer::detail::arrays::no_capacity< T, MemoryPolicy >::equals(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::for_each_chunk(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::for_each_chunk_p(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::get(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::get_check().
data() [2/2]
template<typename T , typename MemoryPolicy > const T* immer::detail::arrays::no_capacity< T, MemoryPolicy >::data () const inline
Definition at line 92 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::data(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr.
dec()
template<typename T , typename MemoryPolicy > void immer::detail::arrays::no_capacity< T, MemoryPolicy >::dec () inline
Definition at line 84 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::delete_n(), immer::detail::csl::get(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr, immer::detail::arrays::node< T, MemoryPolicy >::refs(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
Referenced by immer::detail::arrays::no_capacity< T, MemoryPolicy >::~no_capacity().
empty()
template<typename T , typename MemoryPolicy > static const no_capacity& immer::detail::arrays::no_capacity< T, MemoryPolicy >::empty () inline static
Definition at line 28 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::make_n().
Referenced by immer::detail::arrays::no_capacity< T, MemoryPolicy >::no_capacity().
equals()
template<typename T , typename MemoryPolicy > bool immer::detail::arrays::no_capacity< T, MemoryPolicy >::equals (const no_capacity< T, MemoryPolicy > & other) const inline
Definition at line 143 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::data(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr, and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
for_each_chunk()
template<typename T , typename MemoryPolicy > template<typename Fn > void immer::detail::arrays::no_capacity< T, MemoryPolicy >::for_each_chunk (Fn && fn) const inline
Definition at line 120 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::data(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
for_each_chunk_p()
template<typename T , typename MemoryPolicy > template<typename Fn > bool immer::detail::arrays::no_capacity< T, MemoryPolicy >::for_each_chunk_p (Fn && fn) const inline
Definition at line 126 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::data(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
from_fill()
template<typename T , typename MemoryPolicy > static no_capacity immer::detail::arrays::no_capacity< T, MemoryPolicy >::from_fill (size_t n, T v) inline static
Definition at line 107 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::fill_n().
from_initializer_list()
template<typename T , typename MemoryPolicy > template<typename U > static no_capacity immer::detail::arrays::no_capacity< T, MemoryPolicy >::from_initializer_list (std::initializer_list< U > values) inline static
Definition at line 113 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::from_range().
from_range()
template<typename T , typename MemoryPolicy > template<typename Iter , typename Sent , std::enable_if_t< is_forward_iterator_v< Iter > &&compatible_sentinel_v< Iter, Sent >, bool > = true> static no_capacity immer::detail::arrays::no_capacity< T, MemoryPolicy >::from_range (Iter first, Sent last) inline static
Definition at line 98 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::copy_n(), count, and immer::detail::distance().
Referenced by immer::detail::arrays::no_capacity< T, MemoryPolicy >::from_initializer_list().
get()
template<typename T , typename MemoryPolicy > const T& immer::detail::arrays::no_capacity< T, MemoryPolicy >::get (std::size_t index) const inline
Definition at line 131 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::data().
get_check()
template<typename T , typename MemoryPolicy > const T& immer::detail::arrays::no_capacity< T, MemoryPolicy >::get_check (std::size_t index) const inline
Definition at line 136 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::data(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
inc()
template<typename T , typename MemoryPolicy > void immer::detail::arrays::no_capacity< T, MemoryPolicy >::inc () inline
Definition at line 78 of file no_capacity.hpp.
References immer::detail::csl::get(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr, and immer::detail::arrays::node< T, MemoryPolicy >::refs().
operator=() [1/2]
template<typename T , typename MemoryPolicy > no_capacity& immer::detail::arrays::no_capacity< T, MemoryPolicy >::operator= (const no_capacity< T, MemoryPolicy > & other) inline
Definition at line 53 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::swap.
operator=() [2/2]
template<typename T , typename MemoryPolicy > no_capacity& immer::detail::arrays::no_capacity< T, MemoryPolicy >::operator= (no_capacity< T, MemoryPolicy > && other) inline
Definition at line 60 of file no_capacity.hpp.
References immer::detail::arrays::no_capacity< T, MemoryPolicy >::swap.
push_back()
template<typename T , typename MemoryPolicy > no_capacity immer::detail::arrays::no_capacity< T, MemoryPolicy >::push_back (T value) const inline
Definition at line 150 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::copy_n(), immer::detail::arrays::node< T, MemoryPolicy >::delete_n(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr, and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
take()
template<typename T , typename MemoryPolicy > no_capacity immer::detail::arrays::no_capacity< T, MemoryPolicy >::take (std::size_t sz) const inline
Definition at line 188 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::copy_n(), and immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr.
update()
template<typename T , typename MemoryPolicy > template<typename Fn > no_capacity immer::detail::arrays::no_capacity< T, MemoryPolicy >::update (std::size_t idx, Fn && op) const inline
Definition at line 175 of file no_capacity.hpp.
References immer::detail::arrays::node< T, MemoryPolicy >::copy_n(), immer::detail::arrays::node< T, MemoryPolicy >::delete_n(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr, and immer::detail::arrays::no_capacity< T, MemoryPolicy >::size.
Friends And Related Function Documentation
swap
template<typename T , typename MemoryPolicy > void swap (no_capacity< T, MemoryPolicy > & x, no_capacity< T, MemoryPolicy > & y) friend
Definition at line 66 of file no_capacity.hpp.
Referenced by immer::detail::arrays::no_capacity< T, MemoryPolicy >::operator=().
Member Data Documentation
ptr
template<typename T , typename MemoryPolicy > node_t* immer::detail::arrays::no_capacity< T, MemoryPolicy >::ptr
Definition at line 25 of file no_capacity.hpp.
Referenced by immer::detail::arrays::no_capacity< T, MemoryPolicy >::assoc(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::data(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::dec(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::equals(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::inc(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::no_capacity(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::push_back(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::take(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::update(), and immer::detail::arrays::with_capacity< T, MemoryPolicy >::with_capacity().
size
template<typename T , typename MemoryPolicy > size_t immer::detail::arrays::no_capacity< T, MemoryPolicy >::size
Definition at line 26 of file no_capacity.hpp.
Referenced by immer::detail::arrays::no_capacity< T, MemoryPolicy >::assoc(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::dec(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::equals(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::for_each_chunk(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::for_each_chunk_p(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::get_check(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::no_capacity(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::push_back(), immer::detail::arrays::no_capacity< T, MemoryPolicy >::update(), and immer::detail::arrays::with_capacity< T, MemoryPolicy >::with_capacity().
The documentation for this struct was generated from the following file:
src/immer/detail/arrays/no_capacity.hpp
Released under the MIT license