Dash Core: immer::gc_transience_policy::apply< HeapPolicy >::type::owner Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::gc_transience_policy::apply< HeapPolicy >::type::owner Struct Reference
#include <gc_transience_policy.hpp>
Public Member Functions
void * make_token_ ()
operator edit ()
owner ()
owner (const owner &o)
owner (owner &&o) noexcept
owner & operator= (const owner &o)
owner & operator= (owner &&o) noexcept
Public Attributes
std::atomic< void * > token_
Detailed Description
template<typename HeapPolicy>
struct immer::gc_transience_policy::apply< HeapPolicy >::type::owner
Definition at line 48 of file gc_transience_policy.hpp.
Constructor & Destructor Documentation
owner() [1/3]
template<typename HeapPolicy > immer::gc_transience_policy::apply< HeapPolicy >::type::owner::owner () inline
Definition at line 59 of file gc_transience_policy.hpp.
References immer::gc_transience_policy::apply< HeapPolicy >::type::owner::make_token_().
owner() [2/3]
template<typename HeapPolicy > immer::gc_transience_policy::apply< HeapPolicy >::type::owner::owner (const owner & o) inline
Definition at line 62 of file gc_transience_policy.hpp.
References immer::gc_transience_policy::apply< HeapPolicy >::type::owner::make_token_().
owner() [3/3]
template<typename HeapPolicy > immer::gc_transience_policy::apply< HeapPolicy >::type::owner::owner (owner && o) inline noexcept
Definition at line 67 of file gc_transience_policy.hpp.
Member Function Documentation
make_token_()
template<typename HeapPolicy > void* immer::gc_transience_policy::apply< HeapPolicy >::type::owner::make_token_ () inline
Definition at line 50 of file gc_transience_policy.hpp.
Referenced by immer::gc_transience_policy::apply< HeapPolicy >::type::owner::operator=(), and immer::gc_transience_policy::apply< HeapPolicy >::type::owner::owner().
operator edit()
template<typename HeapPolicy > immer::gc_transience_policy::apply< HeapPolicy >::type::owner::operator edit () inline
Definition at line 57 of file gc_transience_policy.hpp.
References immer::gc_transience_policy::apply< HeapPolicy >::type::owner::token_.
operator=() [1/2]
template<typename HeapPolicy > owner& immer::gc_transience_policy::apply< HeapPolicy >::type::owner::operator= (const owner & o) inline
Definition at line 70 of file gc_transience_policy.hpp.
References immer::gc_transience_policy::apply< HeapPolicy >::type::owner::make_token_(), and immer::gc_transience_policy::apply< HeapPolicy >::type::owner::token_.
operator=() [2/2]
template<typename HeapPolicy > owner& immer::gc_transience_policy::apply< HeapPolicy >::type::owner::operator= (owner && o) inline noexcept
Definition at line 76 of file gc_transience_policy.hpp.
References immer::gc_transience_policy::apply< HeapPolicy >::type::owner::token_.
Member Data Documentation
token_
template<typename HeapPolicy > std::atomic<void*> immer::gc_transience_policy::apply< HeapPolicy >::type::owner::token_ mutable
Definition at line 53 of file gc_transience_policy.hpp.
Referenced by immer::gc_transience_policy::apply< HeapPolicy >::type::owner::operator edit(), and immer::gc_transience_policy::apply< HeapPolicy >::type::owner::operator=().
The documentation for this struct was generated from the following file:
src/immer/transience/gc_transience_policy.hpp
Released under the MIT license