Dash Core: immer::detail::rbts::relaxed_pos< NodeT > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::rbts::relaxed_pos< NodeT > Struct Template Reference
#include <position.hpp>
Public Types
using node_t = NodeT
using relaxed_t = typename NodeT::relaxed_t
Public Member Functions
count_t count () const
node_t * node () const
size_t size () const
shift_t shift () const
count_t subindex (size_t idx) const
relaxed_t * relaxed () const
size_t size_before (count_t offset) const
size_t size (count_t offset) const
size_t size_sbh (count_t offset, size_t size_before_hint) const
count_t index (size_t idx) const
void copy_sizes (count_t offset, count_t n, size_t init, size_t *sizes)
template<typename Visitor , typename... Args>
void each (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred_i (Visitor v, count_t i, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred_left (Visitor v, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
bool each_pred_right (Visitor v, count_t start, Args &&... args)
template<typename Visitor , typename... Args>
void each_i (Visitor v, count_t i, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
void each_sub (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
void each_left_sub (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
void each_left (Visitor v, count_t n, Args &&... args)
template<typename Visitor , typename... Args>
void each_right_sub (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
void each_right (Visitor v, count_t start, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards (Visitor v, size_t idx, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards_oh_sbh (Visitor v, size_t idx, count_t offset_hint, size_t left_size_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards_sub_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) towards_sub_oh_sbh (Visitor v, size_t idx, count_t offset_hint, size_t left_size_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) last_oh_csh (Visitor v, count_t offset_hint, size_t child_size_hint, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) last_sub (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) first_sub (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) first_sub_leaf (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) first_sub_inner (Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) nth_sub (count_t offset, Visitor v, Args &&... args)
template<typename Visitor , typename... Args>
decltype(auto) nth_sub_leaf (count_t offset, Visitor v, Args &&... args)
template<typename Visitor , typename ... Args>
decltype(auto) visit (Visitor v, Args &&...args)
Public Attributes
node_t * node_
shift_t shift_
relaxed_t * relaxed_
Static Public Attributes
static constexpr auto B = NodeT::bits
static constexpr auto BL = NodeT::bits_leaf
Detailed Description
template<typename NodeT>
struct immer::detail::rbts::relaxed_pos< NodeT >
Definition at line 1301 of file position.hpp.
Member Typedef Documentation
node_t
template<typename NodeT > using immer::detail::rbts::relaxed_pos< NodeT >::node_t = NodeT
Definition at line 1306 of file position.hpp.
relaxed_t
template<typename NodeT > using immer::detail::rbts::relaxed_pos< NodeT >::relaxed_t = typename NodeT::relaxed_t
Definition at line 1307 of file position.hpp.
Member Function Documentation
copy_sizes()
template<typename NodeT > void immer::detail::rbts::relaxed_pos< NodeT >::copy_sizes (count_t offset, count_t n, size_t init, size_t * sizes) inline
Definition at line 1338 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, and immer::detail::rbts::relaxed_pos< NodeT >::size_before().
count()
template<typename NodeT > count_t immer::detail::rbts::relaxed_pos< NodeT >::count () const inline
Definition at line 1312 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::relaxed_.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::each_pred(), and immer::detail::rbts::relaxed_pos< NodeT >::last_oh_csh().
each()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::relaxed_pos< NodeT >::each (Visitor v, Args &&... args) inline
Definition at line 1354 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::each_left(), and immer::detail::rbts::relaxed_pos< NodeT >::relaxed_.
each_i()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::relaxed_pos< NodeT >::each_i (Visitor v, count_t i, count_t n, Args &&... args) inline
Definition at line 1463 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, IMMER_PREFETCH, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
each_left()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::relaxed_pos< NodeT >::each_left (Visitor v, count_t n, Args &&... args) inline
Definition at line 1495 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, IMMER_PREFETCH, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::each(), immer::detail::rbts::relaxed_pos< NodeT >::each_left_sub(), and immer::detail::rbts::relaxed_pos< NodeT >::each_sub().
each_left_sub()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::relaxed_pos< NodeT >::each_left_sub (Visitor v, Args &&... args) inline
Definition at line 1491 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::each_left(), and immer::detail::rbts::relaxed_pos< NodeT >::relaxed_.
each_pred()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::relaxed_pos< NodeT >::each_pred (Visitor v, Args &&... args) inline
Definition at line 1358 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::relaxed_pos< NodeT >::count(), IMMER_PREFETCH, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
each_pred_i()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::relaxed_pos< NodeT >::each_pred_i (Visitor v, count_t i, count_t n, Args &&... args) inline
Definition at line 1384 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, IMMER_PREFETCH, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
each_pred_left()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::relaxed_pos< NodeT >::each_pred_left (Visitor v, count_t n, Args &&... args) inline
Definition at line 1411 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, IMMER_PREFETCH, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
each_pred_right()
template<typename NodeT > template<typename Visitor , typename... Args> bool immer::detail::rbts::relaxed_pos< NodeT >::each_pred_right (Visitor v, count_t start, Args &&... args) inline
Definition at line 1436 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, IMMER_PREFETCH, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
each_right()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::relaxed_pos< NodeT >::each_right (Visitor v, count_t start, Args &&... args) inline
Definition at line 1521 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, IMMER_PREFETCH, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::each_right_sub().
each_right_sub()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::relaxed_pos< NodeT >::each_right_sub (Visitor v, Args &&... args) inline
Definition at line 1517 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::each_right().
each_sub()
template<typename NodeT > template<typename Visitor , typename... Args> void immer::detail::rbts::relaxed_pos< NodeT >::each_sub (Visitor v, Args &&... args) inline
Definition at line 1487 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::each_left(), and immer::detail::rbts::relaxed_pos< NodeT >::relaxed_.
first_sub()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::first_sub (Visitor v, Args &&... args) inline
Definition at line 1624 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
first_sub_inner()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::first_sub_inner (Visitor v, Args &&... args) inline
Definition at line 1644 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
first_sub_leaf()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::first_sub_leaf (Visitor v, Args &&... args) inline
Definition at line 1635 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, and immer::detail::rbts::relaxed_pos< NodeT >::shift_.
index()
template<typename NodeT > count_t immer::detail::rbts::relaxed_pos< NodeT >::index (size_t idx) const inline
Definition at line 1331 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, and immer::detail::rbts::relaxed_pos< NodeT >::shift_.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::subindex(), immer::detail::rbts::relaxed_pos< NodeT >::towards_oh(), immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
last_oh_csh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::last_oh_csh (Visitor v, count_t offset_hint, size_t child_size_hint, Args &&... args) inline
Definition at line 1596 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::relaxed_pos< NodeT >::count(), immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, immer::detail::rbts::relaxed_pos< NodeT >::size(), and immer::detail::rbts::visit_maybe_relaxed_sub().
last_sub()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::last_sub (Visitor v, Args &&... args) inline
Definition at line 1612 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, immer::detail::rbts::relaxed_pos< NodeT >::size(), and immer::detail::rbts::visit_maybe_relaxed_sub().
node()
template<typename NodeT > node_t* immer::detail::rbts::relaxed_pos< NodeT >::node () const inline
Definition at line 1313 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::node_.
nth_sub()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::nth_sub (count_t offset, Visitor v, Args &&... args) inline
Definition at line 1653 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, immer::detail::rbts::relaxed_pos< NodeT >::size(), and immer::detail::rbts::visit_maybe_relaxed_sub().
nth_sub_leaf()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::nth_sub_leaf (count_t offset, Visitor v, Args &&... args) inline
Definition at line 1664 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::relaxed_pos< NodeT >::size().
relaxed()
template<typename NodeT > relaxed_t* immer::detail::rbts::relaxed_pos< NodeT >::relaxed () const inline
Definition at line 1317 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::relaxed_.
shift()
template<typename NodeT > shift_t immer::detail::rbts::relaxed_pos< NodeT >::shift () const inline
Definition at line 1315 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::shift_.
size() [1/2]
template<typename NodeT > size_t immer::detail::rbts::relaxed_pos< NodeT >::size () const inline
Definition at line 1314 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::relaxed_.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::last_oh_csh(), immer::detail::rbts::relaxed_pos< NodeT >::last_sub(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub(), and immer::detail::rbts::relaxed_pos< NodeT >::nth_sub_leaf().
size() [2/2]
template<typename NodeT > size_t immer::detail::rbts::relaxed_pos< NodeT >::size (count_t offset) const inline
Definition at line 1322 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::size_before(), and immer::detail::rbts::relaxed_pos< NodeT >::size_sbh().
size_before()
template<typename NodeT > size_t immer::detail::rbts::relaxed_pos< NodeT >::size_before (count_t offset) const inline
Definition at line 1319 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::relaxed_.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::copy_sizes(), immer::detail::rbts::relaxed_pos< NodeT >::size(), and immer::detail::rbts::relaxed_pos< NodeT >::size_sbh().
size_sbh()
template<typename NodeT > size_t immer::detail::rbts::relaxed_pos< NodeT >::size_sbh (count_t offset, size_t size_before_hint) const inline
Definition at line 1325 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, and immer::detail::rbts::relaxed_pos< NodeT >::size_before().
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::size().
subindex()
template<typename NodeT > count_t immer::detail::rbts::relaxed_pos< NodeT >::subindex (size_t idx) const inline
Definition at line 1316 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::index().
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::towards().
towards()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::towards (Visitor v, size_t idx, Args &&... args) inline
Definition at line 1545 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::subindex(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_oh().
towards_oh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::towards_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args) inline
Definition at line 1549 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::index(), immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, and immer::detail::rbts::relaxed_pos< NodeT >::towards_oh_sbh().
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::towards().
towards_oh_sbh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::towards_oh_sbh (Visitor v, size_t idx, count_t offset_hint, size_t left_size_hint, Args &&... args) inline
Definition at line 1559 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::towards_oh().
towards_sub_oh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh (Visitor v, size_t idx, count_t offset_hint, Args &&... args) inline
Definition at line 1566 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::index(), immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
towards_sub_oh_sbh()
template<typename NodeT > template<typename Visitor , typename... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh (Visitor v, size_t idx, count_t offset_hint, size_t left_size_hint, Args &&... args) inline
Definition at line 1576 of file position.hpp.
References immer::detail::rbts::relaxed_pos< NodeT >::B, immer::detail::rbts::relaxed_pos< NodeT >::BL, immer::detail::rbts::relaxed_pos< NodeT >::index(), immer::detail::rbts::make_leaf_sub_pos(), immer::detail::rbts::relaxed_pos< NodeT >::node_, immer::detail::rbts::relaxed_pos< NodeT >::relaxed_, immer::detail::rbts::relaxed_pos< NodeT >::shift_, and immer::detail::rbts::visit_maybe_relaxed_sub().
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::towards_oh_sbh(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh().
visit()
template<typename NodeT > template<typename Visitor , typename ... Args> decltype(auto) immer::detail::rbts::relaxed_pos< NodeT >::visit (Visitor v, Args &&... args) inline
Definition at line 1673 of file position.hpp.
Member Data Documentation
B
template<typename NodeT > constexpr auto immer::detail::rbts::relaxed_pos< NodeT >::B = NodeT::bits static
Definition at line 1303 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::each_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_right(), immer::detail::rbts::relaxed_pos< NodeT >::each_right(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_inner(), immer::detail::rbts::relaxed_pos< NodeT >::last_oh_csh(), immer::detail::rbts::relaxed_pos< NodeT >::last_sub(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
BL
template<typename NodeT > constexpr auto immer::detail::rbts::relaxed_pos< NodeT >::BL = NodeT::bits_leaf static
Definition at line 1304 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::each_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_right(), immer::detail::rbts::relaxed_pos< NodeT >::each_right(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_inner(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_leaf(), immer::detail::rbts::relaxed_pos< NodeT >::last_oh_csh(), immer::detail::rbts::relaxed_pos< NodeT >::last_sub(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub_leaf(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
node_
template<typename NodeT > node_t* immer::detail::rbts::relaxed_pos< NodeT >::node_
Definition at line 1308 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::each_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_right(), immer::detail::rbts::relaxed_pos< NodeT >::each_right(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_inner(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_leaf(), immer::detail::rbts::relaxed_pos< NodeT >::last_oh_csh(), immer::detail::rbts::relaxed_pos< NodeT >::last_sub(), immer::detail::rbts::relaxed_pos< NodeT >::node(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub_leaf(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
relaxed_
template<typename NodeT > relaxed_t* immer::detail::rbts::relaxed_pos< NodeT >::relaxed_
Definition at line 1310 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::copy_sizes(), immer::detail::rbts::relaxed_pos< NodeT >::count(), immer::detail::rbts::relaxed_pos< NodeT >::each(), immer::detail::rbts::relaxed_pos< NodeT >::each_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_left_sub(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_right(), immer::detail::rbts::relaxed_pos< NodeT >::each_right(), immer::detail::rbts::relaxed_pos< NodeT >::each_sub(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_inner(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_leaf(), immer::detail::rbts::relaxed_pos< NodeT >::index(), immer::detail::rbts::relaxed_pos< NodeT >::last_sub(), immer::detail::rbts::relaxed_pos< NodeT >::relaxed(), immer::detail::rbts::relaxed_pos< NodeT >::size(), immer::detail::rbts::relaxed_pos< NodeT >::size_before(), immer::detail::rbts::relaxed_pos< NodeT >::size_sbh(), immer::detail::rbts::relaxed_pos< NodeT >::towards_oh(), immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
shift_
template<typename NodeT > shift_t immer::detail::rbts::relaxed_pos< NodeT >::shift_
Definition at line 1309 of file position.hpp.
Referenced by immer::detail::rbts::relaxed_pos< NodeT >::each_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_i(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_left(), immer::detail::rbts::relaxed_pos< NodeT >::each_pred_right(), immer::detail::rbts::relaxed_pos< NodeT >::each_right(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_inner(), immer::detail::rbts::relaxed_pos< NodeT >::first_sub_leaf(), immer::detail::rbts::relaxed_pos< NodeT >::index(), immer::detail::rbts::relaxed_pos< NodeT >::last_oh_csh(), immer::detail::rbts::relaxed_pos< NodeT >::last_sub(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub(), immer::detail::rbts::relaxed_pos< NodeT >::nth_sub_leaf(), immer::detail::rbts::relaxed_pos< NodeT >::shift(), and immer::detail::rbts::relaxed_pos< NodeT >::towards_sub_oh_sbh().
The documentation for this struct was generated from the following file:
src/immer/detail/rbts/position.hpp
Released under the MIT license