Dash Core: immer::detail::rbts::get_mut_visitor< NodeT > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::rbts::get_mut_visitor< NodeT > Struct Template Reference
#include <operations.hpp>
Public Types
using node_t = NodeT
using this_t = get_mut_visitor
using value_t = typename NodeT::value_t
using edit_t = typename NodeT::edit_t
Static Public Member Functions
template<typename Pos >
static value_t & visit_relaxed (Pos &&pos, size_t idx, edit_t e, node_t **location)
template<typename Pos >
static value_t & visit_regular (Pos &&pos, size_t idx, edit_t e, node_t **location)
template<typename Pos >
static value_t & visit_leaf (Pos &&pos, size_t idx, edit_t e, node_t **location)
Static Public Member Functions inherited from immer::detail::rbts::visitor_base< get_mut_visitor< NodeT > >
static decltype(auto) visit_node (Args &&...args)
static decltype(auto) visit_relaxed (Args &&...args)
static decltype(auto) visit_regular (Args &&...args)
static decltype(auto) visit_inner (Args &&...args)
static decltype(auto) visit_leaf (Args &&...args)
Detailed Description
template<typename NodeT>
struct immer::detail::rbts::get_mut_visitor< NodeT >
Definition at line 572 of file operations.hpp.
Member Typedef Documentation
edit_t
template<typename NodeT > using immer::detail::rbts::get_mut_visitor< NodeT >::edit_t = typename NodeT::edit_t
Definition at line 577 of file operations.hpp.
node_t
template<typename NodeT > using immer::detail::rbts::get_mut_visitor< NodeT >::node_t = NodeT
Definition at line 574 of file operations.hpp.
this_t
template<typename NodeT > using immer::detail::rbts::get_mut_visitor< NodeT >::this_t = get_mut_visitor
Definition at line 575 of file operations.hpp.
value_t
template<typename NodeT > using immer::detail::rbts::get_mut_visitor< NodeT >::value_t = typename NodeT::value_t
Definition at line 576 of file operations.hpp.
Member Function Documentation
visit_leaf()
template<typename NodeT > template<typename Pos > static value_t& immer::detail::rbts::get_mut_visitor< NodeT >::visit_leaf (Pos && pos, size_t idx, edit_t e, node_t ** location) inline static
Definition at line 631 of file operations.hpp.
References immer::detail::rbts::node< T, MemoryPolicy, B, BL >::can_mutate(), and immer::detail::rbts::node< T, MemoryPolicy, B, BL >::leaf().
visit_regular()
template<typename NodeT > template<typename Pos > static value_t& immer::detail::rbts::get_mut_visitor< NodeT >::visit_regular (Pos && pos, size_t idx, edit_t e, node_t ** location) inline static
Definition at line 605 of file operations.hpp.
References immer::detail::rbts::node< T, MemoryPolicy, B, BL >::can_mutate(), count, immer::detail::rbts::dec_regular(), and immer::detail::rbts::node< T, MemoryPolicy, B, BL >::inner().
visit_relaxed()
template<typename NodeT > template<typename Pos > static value_t& immer::detail::rbts::get_mut_visitor< NodeT >::visit_relaxed (Pos && pos, size_t idx, edit_t e, node_t ** location) inline static
Definition at line 580 of file operations.hpp.
References immer::detail::rbts::node< T, MemoryPolicy, B, BL >::can_mutate(), count, immer::detail::rbts::dec_relaxed(), and immer::detail::rbts::node< T, MemoryPolicy, B, BL >::inner().
The documentation for this struct was generated from the following file:
src/immer/detail/rbts/operations.hpp
Released under the MIT license