Dash Core: DisconnectedBlockTransactions Struct Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
DisconnectedBlockTransactions Struct Reference
#include <txmempool.h>
Public Types
typedef boost::multi_index_container< CTransactionRef, boost::multi_index::indexed_by< boost::multi_index::hashed_unique< boost::multi_index::tag< txid_index >, mempoolentry_txid, SaltedTxidHasher >, boost::multi_index::sequenced< boost::multi_index::tag< insertion_order > > > > indexed_disconnected_transactions
Public Member Functions
~DisconnectedBlockTransactions ()
size_t DynamicMemoryUsage () const
void addTransaction (const CTransactionRef &tx)
void removeForBlock (const std::vector< CTransactionRef > &vtx)
void removeEntry (indexed_disconnected_transactions::index< insertion_order >::type::iterator entry)
void clear ()
Public Attributes
indexed_disconnected_transactions queuedTx
uint64_t cachedInnerUsage = 0
Detailed Description
Definition at line 768 of file txmempool.h.
Member Typedef Documentation
indexed_disconnected_transactions
typedef boost::multi_index_container< CTransactionRef, boost::multi_index::indexed_by< boost::multi_index::hashed_unique< boost::multi_index::tag<txid_index>, mempoolentry_txid, SaltedTxidHasher >, boost::multi_index::sequenced< boost::multi_index::tag<insertion_order> > > > DisconnectedBlockTransactions::indexed_disconnected_transactions
Definition at line 783 of file txmempool.h.
Constructor & Destructor Documentation
~DisconnectedBlockTransactions()
DisconnectedBlockTransactions::~DisconnectedBlockTransactions () inline
Definition at line 793 of file txmempool.h.
References queuedTx.
Member Function Documentation
addTransaction()
void DisconnectedBlockTransactions::addTransaction (const CTransactionRef & tx) inline
Definition at line 804 of file txmempool.h.
References cachedInnerUsage, queuedTx, and RecursiveDynamicUsage().
Referenced by CChainState::DisconnectTip().
clear()
void DisconnectedBlockTransactions::clear () inline
Definition at line 833 of file txmempool.h.
References cachedInnerUsage, and queuedTx.
DynamicMemoryUsage()
size_t DisconnectedBlockTransactions::DynamicMemoryUsage () const inline
Definition at line 800 of file txmempool.h.
References cachedInnerUsage, memusage::MallocUsage(), and queuedTx.
Referenced by CChainState::DisconnectTip().
removeEntry()
void DisconnectedBlockTransactions::removeEntry (indexed_disconnected_transactions::index< insertion_order >::type::iterator entry) inline
Definition at line 827 of file txmempool.h.
References cachedInnerUsage, queuedTx, and RecursiveDynamicUsage().
Referenced by CChainState::DisconnectTip().
removeForBlock()
void DisconnectedBlockTransactions::removeForBlock (const std::vector< CTransactionRef > & vtx) inline
Definition at line 811 of file txmempool.h.
References cachedInnerUsage, queuedTx, and RecursiveDynamicUsage().
Referenced by CChainState::ConnectTip().
Member Data Documentation
cachedInnerUsage
uint64_t DisconnectedBlockTransactions::cachedInnerUsage = 0
Definition at line 796 of file txmempool.h.
Referenced by addTransaction(), clear(), DynamicMemoryUsage(), removeEntry(), and removeForBlock().
queuedTx
indexed_disconnected_transactions DisconnectedBlockTransactions::queuedTx
Definition at line 795 of file txmempool.h.
Referenced by addTransaction(), clear(), CChainState::DisconnectTip(), DynamicMemoryUsage(), removeEntry(), removeForBlock(), UpdateMempoolForReorg(), and ~DisconnectedBlockTransactions().
The documentation for this struct was generated from the following file:
src/txmempool.h
Released under the MIT license