Dash Core: immer::detail::dvektor::ref< T, B, MP > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::dvektor::ref< T, B, MP > Struct Template Reference
#include <dvektor_impl.hpp>
Public Types
using inner_t = inner_node< T, B, MP >
using leaf_t = leaf_node< T, B >
using node_t = node< T, B, MP >
using node_ptr_t = node_ptr< T, B, MP >
Public Member Functions
const T & get_elem (std::size_t index, std::size_t xr) const
node_ptr_t null_slot_and_copy_inner (node_ptr_t &node, std::size_t idx)
node_ptr_t null_slot_and_copy_leaf (node_ptr_t &node, std::size_t idx)
node_ptr_t copy_of_inner (const node_ptr_t &n)
node_ptr_t copy_of_leaf (const node_ptr_t &n)
void stabilize (std::size_t index)
void goto_pos_writable_from_clean (std::size_t old_index, std::size_t index, std::size_t xr)
void goto_pos_writable_from_dirty (std::size_t old_index, std::size_t new_index, std::size_t xr)
void goto_fresh_pos_writable_from_clean (std::size_t old_index, std::size_t new_index, std::size_t xr)
void goto_fresh_pos_writable_from_dirty (std::size_t old_index, std::size_t new_index, std::size_t xr)
void goto_next_block_start (std::size_t index, std::size_t xr)
void goto_pos (std::size_t index, std::size_t xr)
Static Public Member Functions
template<typename ... Ts>
static auto make_node (Ts &&...xs)
Public Attributes
unsigned depth
std::array< node_ptr_t, max_depth< B > > display
Detailed Description
template<typename T, int B, typename MP>
struct immer::detail::dvektor::ref< T, B, MP >
Definition at line 133 of file dvektor_impl.hpp.
Member Typedef Documentation
inner_t
template<typename T, int B, typename MP> using immer::detail::dvektor::ref< T, B, MP >::inner_t = inner_node<T, B, MP>
Definition at line 135 of file dvektor_impl.hpp.
leaf_t
template<typename T, int B, typename MP> using immer::detail::dvektor::ref< T, B, MP >::leaf_t = leaf_node<T, B>
Definition at line 136 of file dvektor_impl.hpp.
node_ptr_t
template<typename T, int B, typename MP> using immer::detail::dvektor::ref< T, B, MP >::node_ptr_t = node_ptr<T, B, MP>
Definition at line 138 of file dvektor_impl.hpp.
node_t
template<typename T, int B, typename MP> using immer::detail::dvektor::ref< T, B, MP >::node_t = node<T, B, MP>
Definition at line 137 of file dvektor_impl.hpp.
Member Function Documentation
copy_of_inner()
template<typename T, int B, typename MP> node_ptr_t immer::detail::dvektor::ref< T, B, MP >::copy_of_inner (const node_ptr_t & n) inline
Definition at line 177 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_clean(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_dirty(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::null_slot_and_copy_inner(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::stabilize().
copy_of_leaf()
template<typename T, int B, typename MP> node_ptr_t immer::detail::dvektor::ref< T, B, MP >::copy_of_leaf (const node_ptr_t & n) inline
Definition at line 182 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_clean(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_dirty(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::null_slot_and_copy_leaf().
get_elem()
template<typename T, int B, typename MP> const T& immer::detail::dvektor::ref< T, B, MP >::get_elem (std::size_t index, std::size_t xr) const inline
Definition at line 149 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::impl< T, B, MemoryPolicy >::get().
goto_fresh_pos_writable_from_clean()
template<typename T, int B, typename MP> void immer::detail::dvektor::ref< T, B, MP >::goto_fresh_pos_writable_from_clean (std::size_t old_index, std::size_t new_index, std::size_t xr) inline
Definition at line 251 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::impl< T, B, MemoryPolicy >::goto_fresh_pos_writable(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_fresh_pos_writable_from_dirty().
goto_fresh_pos_writable_from_dirty()
template<typename T, int B, typename MP> void immer::detail::dvektor::ref< T, B, MP >::goto_fresh_pos_writable_from_dirty (std::size_t old_index, std::size_t new_index, std::size_t xr) inline
Definition at line 277 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::impl< T, B, MemoryPolicy >::goto_fresh_pos_writable().
goto_next_block_start()
template<typename T, int B, typename MP> void immer::detail::dvektor::ref< T, B, MP >::goto_next_block_start (std::size_t index, std::size_t xr) inline
Definition at line 285 of file dvektor_impl.hpp.
goto_pos()
template<typename T, int B, typename MP> void immer::detail::dvektor::ref< T, B, MP >::goto_pos (std::size_t index, std::size_t xr) inline
Definition at line 297 of file dvektor_impl.hpp.
goto_pos_writable_from_clean()
template<typename T, int B, typename MP> void immer::detail::dvektor::ref< T, B, MP >::goto_pos_writable_from_clean (std::size_t old_index, std::size_t index, std::size_t xr) inline
Definition at line 199 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::impl< T, B, MemoryPolicy >::goto_pos_writable().
goto_pos_writable_from_dirty()
template<typename T, int B, typename MP> void immer::detail::dvektor::ref< T, B, MP >::goto_pos_writable_from_dirty (std::size_t old_index, std::size_t new_index, std::size_t xr) inline
Definition at line 223 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::impl< T, B, MemoryPolicy >::goto_pos_writable().
make_node()
template<typename T, int B, typename MP> template<typename ... Ts> static auto immer::detail::dvektor::ref< T, B, MP >::make_node (Ts &&... xs) inline static
Definition at line 144 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::copy_of_inner(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::copy_of_leaf(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_fresh_pos_writable_from_clean().
null_slot_and_copy_inner()
template<typename T, int B, typename MP> node_ptr_t immer::detail::dvektor::ref< T, B, MP >::null_slot_and_copy_inner (node_ptr_t & node, std::size_t idx) inline
Definition at line 161 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_clean(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_dirty().
null_slot_and_copy_leaf()
template<typename T, int B, typename MP> node_ptr_t immer::detail::dvektor::ref< T, B, MP >::null_slot_and_copy_leaf (node_ptr_t & node, std::size_t idx) inline
Definition at line 169 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_clean(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_dirty().
stabilize()
template<typename T, int B, typename MP> void immer::detail::dvektor::ref< T, B, MP >::stabilize (std::size_t index) inline
Definition at line 187 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_fresh_pos_writable_from_dirty().
Member Data Documentation
depth
template<typename T, int B, typename MP> unsigned immer::detail::dvektor::ref< T, B, MP >::depth
Definition at line 140 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_fresh_pos_writable_from_clean(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_clean(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_dirty(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::stabilize().
display
template<typename T, int B, typename MP> std::array<node_ptr_t, max_depth<B> > immer::detail::dvektor::ref< T, B, MP >::display
Definition at line 141 of file dvektor_impl.hpp.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::get_elem(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_fresh_pos_writable_from_clean(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_next_block_start(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_clean(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::goto_pos_writable_from_dirty(), immer::detail::dvektor::impl< T, B, MemoryPolicy >::push_back(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::stabilize(), and immer::detail::dvektor::impl< T, B, MemoryPolicy >::update().
The documentation for this struct was generated from the following file:
src/immer/experimental/detail/dvektor_impl.hpp
Released under the MIT license