Dash Core: immer::detail::dvektor::node< T, B, MP > Struct Template Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
immer::detail::dvektor::node< T, B, MP > Struct Template Reference
#include <dvektor_impl.hpp>
Classes
union data_t
Public Types
enum { leaf_kind, inner_kind }
using leaf_node_t = leaf_node< T, B >
using inner_node_t = inner_node< T, B, MP >
Public Member Functions
~node ()
node (leaf_node< T, B > n)
node (inner_node< T, B, MP > n)
inner_node_t & inner () &
const inner_node_t & inner () const &
inner_node_t && inner () &&
leaf_node_t & leaf () &
const leaf_node_t & leaf () const &
leaf_node_t && leaf () &&
Public Member Functions inherited from immer::enable_intrusive_ptr< node< T, B, MP >, MP::refcount >
enable_intrusive_ptr ()
Public Attributes
enum immer::detail::dvektor::node:: { ... } kind
union immer::detail::dvektor::node::data_t data
Additional Inherited Members
Static Public Member Functions inherited from immer::enable_optimized_heap_policy< node< T, B, MP >, MP::heap >
static void * operator new (std::size_t size)
static void operator delete (void *data, std::size_t size)
Detailed Description
template<typename T, int B, typename MP>
struct immer::detail::dvektor::node< T, B, MP >
Definition at line 42 of file dvektor_impl.hpp.
Member Typedef Documentation
inner_node_t
template<typename T , int B, typename MP > using immer::detail::dvektor::node< T, B, MP >::inner_node_t = inner_node<T, B, MP>
Definition at line 58 of file dvektor_impl.hpp.
leaf_node_t
template<typename T , int B, typename MP > using immer::detail::dvektor::node< T, B, MP >::leaf_node_t = leaf_node<T, B>
Definition at line 57 of file dvektor_impl.hpp.
Member Enumeration Documentation
anonymous enum
template<typename T , int B, typename MP > anonymous enum
Enumerator
leaf_kind
inner_kind
Definition at line 60 of file dvektor_impl.hpp.
Constructor & Destructor Documentation
~node()
template<typename T , int B, typename MP > immer::detail::dvektor::node< T, B, MP >::~node () inline
Definition at line 75 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::data, immer::detail::dvektor::node< T, B, MP >::data_t::inner, immer::detail::dvektor::node< T, B, MP >::inner_kind, immer::detail::dvektor::node< T, B, MP >::kind, immer::detail::dvektor::node< T, B, MP >::data_t::leaf, and immer::detail::dvektor::node< T, B, MP >::leaf_kind.
node() [1/2]
template<typename T , int B, typename MP > immer::detail::dvektor::node< T, B, MP >::node (leaf_node< T, B > n) inline
Definition at line 87 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::leaf_kind.
node() [2/2]
template<typename T , int B, typename MP > immer::detail::dvektor::node< T, B, MP >::node (inner_node< T, B, MP > n) inline
Definition at line 92 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::inner_kind.
Member Function Documentation
inner() [1/3]
template<typename T , int B, typename MP > inner_node_t& immer::detail::dvektor::node< T, B, MP >::inner () & inline
Definition at line 97 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::data, immer::detail::dvektor::node< T, B, MP >::data_t::inner, immer::detail::dvektor::node< T, B, MP >::inner_kind, and immer::detail::dvektor::node< T, B, MP >::kind.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::get_elem(), immer::detail::dvektor::ref< T, B, MemoryPolicy >::null_slot_and_copy_inner(), and immer::detail::dvektor::ref< T, B, MemoryPolicy >::null_slot_and_copy_leaf().
inner() [2/3]
template<typename T , int B, typename MP > const inner_node_t& immer::detail::dvektor::node< T, B, MP >::inner () const & inline
Definition at line 101 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::data, immer::detail::dvektor::node< T, B, MP >::data_t::inner, immer::detail::dvektor::node< T, B, MP >::inner_kind, and immer::detail::dvektor::node< T, B, MP >::kind.
inner() [3/3]
template<typename T , int B, typename MP > inner_node_t&& immer::detail::dvektor::node< T, B, MP >::inner () && inline
Definition at line 105 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::data, immer::detail::dvektor::node< T, B, MP >::data_t::inner, immer::detail::dvektor::node< T, B, MP >::inner_kind, and immer::detail::dvektor::node< T, B, MP >::kind.
leaf() [1/3]
template<typename T , int B, typename MP > leaf_node_t& immer::detail::dvektor::node< T, B, MP >::leaf () & inline
Definition at line 110 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::data, immer::detail::dvektor::node< T, B, MP >::kind, immer::detail::dvektor::node< T, B, MP >::data_t::leaf, and immer::detail::dvektor::node< T, B, MP >::leaf_kind.
Referenced by immer::detail::dvektor::ref< T, B, MemoryPolicy >::get_elem().
leaf() [2/3]
template<typename T , int B, typename MP > const leaf_node_t& immer::detail::dvektor::node< T, B, MP >::leaf () const & inline
Definition at line 114 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::data, immer::detail::dvektor::node< T, B, MP >::kind, immer::detail::dvektor::node< T, B, MP >::data_t::leaf, and immer::detail::dvektor::node< T, B, MP >::leaf_kind.
leaf() [3/3]
template<typename T , int B, typename MP > leaf_node_t&& immer::detail::dvektor::node< T, B, MP >::leaf () && inline
Definition at line 118 of file dvektor_impl.hpp.
References immer::detail::dvektor::node< T, B, MP >::data, immer::detail::dvektor::node< T, B, MP >::kind, immer::detail::dvektor::node< T, B, MP >::data_t::leaf, and immer::detail::dvektor::node< T, B, MP >::leaf_kind.
Member Data Documentation
data
template<typename T , int B, typename MP > union immer::detail::dvektor::node::data_t immer::detail::dvektor::node< T, B, MP >::data
Referenced by immer::detail::dvektor::node< T, B, MP >::inner(), immer::detail::dvektor::node< T, B, MP >::leaf(), and immer::detail::dvektor::node< T, B, MP >::~node().
kind
enum { ... } immer::detail::dvektor::node< T, B, MP >::kind
Referenced by immer::detail::dvektor::node< T, B, MP >::inner(), immer::detail::dvektor::node< T, B, MP >::leaf(), and immer::detail::dvektor::node< T, B, MP >::~node().
The documentation for this struct was generated from the following file:
src/immer/experimental/detail/dvektor_impl.hpp
Released under the MIT license