Dash Core: CNodeSignals Struct Reference
CNodeSignals Struct Reference
#include <net.h>
Public Attributes
boost::signals2::signal< bool(CNode *, CConnman &, std::atomic< bool > &), CombinerAll > ProcessMessages
boost::signals2::signal< bool(CNode *, CConnman &, std::atomic< bool > &), CombinerAll > SendMessages
boost::signals2::signal< void(CNode *, CConnman &)> InitializeNode
boost::signals2::signal< void(NodeId, bool &)> FinalizeNode
Detailed Description
Definition at line 531 of file net.h.
Member Data Documentation
FinalizeNode
boost::signals2::signal<void (NodeId, bool&)> CNodeSignals::FinalizeNode
Definition at line 536 of file net.h.
Referenced by CConnman::DeleteNode(), RegisterNodeSignals(), and UnregisterNodeSignals().
InitializeNode
boost::signals2::signal<void (CNode*, CConnman&)> CNodeSignals::InitializeNode
Definition at line 535 of file net.h.
Referenced by CConnman::AcceptConnection(), CConnman::ConnectNode(), RegisterNodeSignals(), CConnman::Start(), and UnregisterNodeSignals().
ProcessMessages
boost::signals2::signal<bool (CNode*, CConnman&, std::atomic<bool>&), CombinerAll> CNodeSignals::ProcessMessages
Definition at line 533 of file net.h.
Referenced by RegisterNodeSignals(), CConnman::ThreadMessageHandler(), and UnregisterNodeSignals().
SendMessages
boost::signals2::signal<bool (CNode*, CConnman&, std::atomic<bool>&), CombinerAll> CNodeSignals::SendMessages
Definition at line 534 of file net.h.
Referenced by RegisterNodeSignals(), CConnman::ThreadMessageHandler(), and UnregisterNodeSignals().
The documentation for this struct was generated from the following file:
src/net.h