Dash Core: src/support/lockedpool.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
lockedpool.cpp File Reference
#include <support/lockedpool.h>
#include <support/cleanse.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <limits.h>
#include <unistd.h>
#include <algorithm>
#include <memory>
Classes
class PosixLockedPageAllocator
LockedPageAllocator specialized for OSes that don't try to be special snowflakes.
Macros
#define MAP_ANONYMOUS MAP_ANON
Functions
static size_t align_up (size_t x, size_t align)
Align up to power of 2.
template<class Iterator , class Pair >
bool extend (Iterator it, const Pair &other)
Macro Definition Documentation
MAP_ANONYMOUS
#define MAP_ANONYMOUS MAP_ANON
Definition at line 224 of file lockedpool.cpp.
Referenced by PosixLockedPageAllocator::AllocateLocked().
Function Documentation
align_up()
static size_t align_up (size_t x, size_t align) inline static
Align up to power of 2.
Definition at line 39 of file lockedpool.cpp.
Referenced by Arena::alloc(), PosixLockedPageAllocator::AllocateLocked(), and PosixLockedPageAllocator::FreeLocked().
extend()
template<class Iterator , class Pair > bool extend (Iterator it, const Pair & other)
Definition at line 81 of file lockedpool.cpp.
Referenced by Arena::free().
Released under the MIT license