Dash Core: src/secp256k1/src/testrand_impl.h File Reference
testrand_impl.h File Reference
#include <stdint.h>
#include <string.h>
#include "testrand.h"
#include "hash.h"
Functions
static SECP256K1_INLINE void secp256k1_rand_seed (const unsigned char *seed16)
static SECP256K1_INLINE uint32_t secp256k1_rand32 (void)
static uint32_t secp256k1_rand_bits (int bits)
static uint32_t secp256k1_rand_int (uint32_t range)
static void secp256k1_rand256 (unsigned char *b32)
static void secp256k1_rand_bytes_test (unsigned char *bytes, size_t len)
static void secp256k1_rand256_test (unsigned char *b32)
Variables
static secp256k1_rfc6979_hmac_sha256_t secp256k1_test_rng
static uint32_t secp256k1_test_rng_precomputed [8]
static int secp256k1_test_rng_precomputed_used = 8
static uint64_t secp256k1_test_rng_integer
static int secp256k1_test_rng_integer_bits_left = 0
Function Documentation
secp256k1_rand256()
static void secp256k1_rand256 (unsigned char * b32) static
Definition at line 86 of file testrand_impl.h.
secp256k1_rand256_test()
static void secp256k1_rand256_test (unsigned char * b32) static
Definition at line 106 of file testrand_impl.h.
secp256k1_rand32()
static SECP256K1_INLINE uint32_t secp256k1_rand32 (void) static
Definition at line 26 of file testrand_impl.h.
Referenced by secp256k1_rand_bits().
secp256k1_rand_bits()
static uint32_t secp256k1_rand_bits (int bits) static
Definition at line 34 of file testrand_impl.h.
Referenced by secp256k1_rand_bytes_test(), and secp256k1_rand_int().
secp256k1_rand_bytes_test()
static void secp256k1_rand_bytes_test (unsigned char * bytes, size_t len) static
Definition at line 90 of file testrand_impl.h.
Referenced by secp256k1_rand256_test().
secp256k1_rand_int()
static uint32_t secp256k1_rand_int (uint32_t range) static
Definition at line 47 of file testrand_impl.h.
secp256k1_rand_seed()
static SECP256K1_INLINE void secp256k1_rand_seed (const unsigned char * seed16) static
Definition at line 22 of file testrand_impl.h.
Variable Documentation
secp256k1_test_rng
secp256k1_rfc6979_hmac_sha256_t secp256k1_test_rng static
Definition at line 16 of file testrand_impl.h.
Referenced by secp256k1_rand256(), secp256k1_rand32(), and secp256k1_rand_seed().
secp256k1_test_rng_integer
uint64_t secp256k1_test_rng_integer static
Definition at line 19 of file testrand_impl.h.
Referenced by secp256k1_rand_bits().
secp256k1_test_rng_integer_bits_left
int secp256k1_test_rng_integer_bits_left = 0 static
Definition at line 20 of file testrand_impl.h.
Referenced by secp256k1_rand_bits().
secp256k1_test_rng_precomputed
uint32_t secp256k1_test_rng_precomputed[8] static
Definition at line 17 of file testrand_impl.h.
Referenced by secp256k1_rand32().
secp256k1_test_rng_precomputed_used
int secp256k1_test_rng_precomputed_used = 8 static
Definition at line 18 of file testrand_impl.h.
Referenced by secp256k1_rand32().