Dash Core: src/torcontrol.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
torcontrol.h File Reference
#include <scheduler.h>
Functions
void StartTorControl (boost::thread_group &threadGroup, CScheduler &scheduler)
void InterruptTorControl ()
void StopTorControl ()
Variables
const std::string DEFAULT_TOR_CONTROL
Functionality for communicating with Tor.
static const bool DEFAULT_LISTEN_ONION = true
Function Documentation
InterruptTorControl()
void InterruptTorControl ()
Definition at line 760 of file torcontrol.cpp.
References gBase, and LogPrintf.
Referenced by Interrupt().
StartTorControl()
void StartTorControl (boost::thread_group & threadGroup, CScheduler & scheduler)
Definition at line 743 of file torcontrol.cpp.
References gBase, LogPrintf, torControlThread, TorControlThread(), and TraceThread().
Referenced by AppInitMain().
StopTorControl()
void StopTorControl ()
Definition at line 768 of file torcontrol.cpp.
References gBase, and torControlThread.
Referenced by Shutdown().
Variable Documentation
DEFAULT_LISTEN_ONION
const bool DEFAULT_LISTEN_ONION = true static
Definition at line 14 of file torcontrol.h.
Referenced by AppInitMain(), and HelpMessage().
DEFAULT_TOR_CONTROL
const std::string DEFAULT_TOR_CONTROL
Functionality for communicating with Tor.
Functionality for communicating with Tor.
Definition at line 31 of file torcontrol.cpp.
Referenced by HelpMessage(), and TorControlThread().
Released under the MIT license