Dash Core: src/qt/transactiontablemodel.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
transactiontablemodel.cpp File Reference
#include <qt/transactiontablemodel.h>
#include <qt/addresstablemodel.h>
#include <qt/guiutil.h>
#include <qt/optionsmodel.h>
#include <qt/transactiondesc.h>
#include <qt/transactionrecord.h>
#include <qt/walletmodel.h>
#include <core_io.h>
#include <validation.h>
#include <sync.h>
#include <uint256.h>
#include <util.h>
#include <wallet/wallet.h>
#include <QColor>
#include <QDateTime>
#include <QDebug>
#include <QIcon>
#include <QList>
Classes
struct TxLessThan
class TransactionTablePriv
struct TransactionNotification
Functions
static void NotifyTransactionChanged (TransactionTableModel *ttm, CWallet *wallet, const uint256 &hash, ChangeType status)
static void NotifyAddressBookChanged (TransactionTableModel *ttm, CWallet *wallet, const CTxDestination &address, const std::string &label, bool isMine, const std::string &purpose, ChangeType status)
static void ShowProgress (TransactionTableModel *ttm, const std::string &title, int nProgress)
Variables
static int column_alignments []
static bool fQueueNotifications = false
static std::vector< TransactionNotification > vQueueNotifications
Function Documentation
NotifyAddressBookChanged()
static void NotifyAddressBookChanged (TransactionTableModel * ttm, CWallet * wallet, const CTxDestination & address, const std::string & label, bool isMine, const std::string & purpose, ChangeType status) static
Definition at line 812 of file transactiontablemodel.cpp.
References EncodeDestination().
Referenced by TransactionTableModel::subscribeToCoreSignals(), and TransactionTableModel::unsubscribeFromCoreSignals().
NotifyTransactionChanged()
static void NotifyTransactionChanged (TransactionTableModel * ttm, CWallet * wallet, const uint256 & hash, ChangeType status) static
Definition at line 794 of file transactiontablemodel.cpp.
References fQueueNotifications, TransactionNotification::invoke(), CWallet::mapWallet, TransactionRecord::showTransaction(), and vQueueNotifications.
Referenced by TransactionTableModel::subscribeToCoreSignals(), and TransactionTableModel::unsubscribeFromCoreSignals().
ShowProgress()
static void ShowProgress (TransactionTableModel * ttm, const std::string & title, int nProgress) static
Definition at line 822 of file transactiontablemodel.cpp.
References fQueueNotifications, and vQueueNotifications.
Referenced by TransactionTableModel::subscribeToCoreSignals(), and TransactionTableModel::unsubscribeFromCoreSignals().
Variable Documentation
column_alignments
int column_alignments[] static
Initial value:
= {
        Qt::AlignLeft|Qt::AlignVCenter,
        Qt::AlignLeft|Qt::AlignVCenter,
        Qt::AlignLeft|Qt::AlignVCenter,
        Qt::AlignLeft|Qt::AlignVCenter,
        Qt::AlignLeft|Qt::AlignVCenter,
        Qt::AlignRight|Qt::AlignVCenter
    }
Definition at line 28 of file transactiontablemodel.cpp.
Referenced by TransactionTableModel::data(), and TransactionTableModel::headerData().
fQueueNotifications
bool fQueueNotifications = false static
Definition at line 791 of file transactiontablemodel.cpp.
Referenced by NotifyTransactionChanged(), and ShowProgress().
vQueueNotifications
std::vector< TransactionNotification > vQueueNotifications static
Definition at line 792 of file transactiontablemodel.cpp.
Referenced by NotifyTransactionChanged(), and ShowProgress().
Released under the MIT license