Dash Core: src/primitives/transaction.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
transaction.h File Reference
#include <amount.h>
#include <script/script.h>
#include <serialize.h>
#include <uint256.h>
Classes
class COutPoint
An outpoint - a combination of a transaction hash and an index n into its vout.
class CTxIn
An input of a transaction.
class CTxOut
An output of a transaction.
class CTransaction
The basic transaction that is broadcasted on the network and contained in blocks.
struct CMutableTransaction
A mutable version of CTransaction.
struct CompareInputBIP69
Implementation of BIP69 https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki.
struct CompareOutputBIP69
Typedefs
typedef std::shared_ptr< const CTransaction > CTransactionRef
Enumerations
enum {
TRANSACTION_NORMAL = 0, TRANSACTION_PROVIDER_REGISTER = 1, TRANSACTION_PROVIDER_UPDATE_SERVICE = 2, TRANSACTION_PROVIDER_UPDATE_REGISTRAR = 3,
TRANSACTION_PROVIDER_UPDATE_REVOKE = 4, TRANSACTION_COINBASE = 5, TRANSACTION_QUORUM_COMMITMENT = 6
}
Transaction types.
Functions
static CTransactionRef MakeTransactionRef ()
template<typename Tx >
static CTransactionRef MakeTransactionRef (Tx &&txIn)
Typedef Documentation
CTransactionRef
typedef std::shared_ptr<const CTransaction> CTransactionRef
Definition at line 345 of file transaction.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Transaction types.
Enumerator
TRANSACTION_NORMAL
TRANSACTION_PROVIDER_REGISTER
TRANSACTION_PROVIDER_UPDATE_SERVICE
TRANSACTION_PROVIDER_UPDATE_REGISTRAR
TRANSACTION_PROVIDER_UPDATE_REVOKE
TRANSACTION_COINBASE
TRANSACTION_QUORUM_COMMITMENT
Definition at line 15 of file transaction.h.
Function Documentation
MakeTransactionRef() [1/2]
static CTransactionRef MakeTransactionRef () inline static
Definition at line 346 of file transaction.h.
Referenced by add_coin(), addCoin(), AddTx(), CPrivateSendServer::AddUserToExistingSession(), BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), CMerkleTx::CMerkleTx(), CPrivateSendServer::CommitFinalTransaction(), CreateDevNetGenesisBlock(), CreateGenesisBlock(), BlockAssembler::CreateNewBlock(), CPrivateSendServer::CreateNewSession(), CWallet::CreateTransaction(), llmq::CQuorumBlockProcessor::GetMinableCommitmentTx(), importprunedfunds(), IncrementExtraNonce(), CPrivateSend::IsCollateralValid(), and sendrawtransaction().
MakeTransactionRef() [2/2]
template<typename Tx > static CTransactionRef MakeTransactionRef (Tx && txIn) inline static
Definition at line 347 of file transaction.h.
Released under the MIT license