Dash Core: src/txdb.h File Reference
txdb.h File Reference
#include "coins.h"
#include "dbwrapper.h"
#include <map>
#include <string>
#include <utility>
#include <vector>
Classes
class CCoinsViewDB
class CBlockTreeDB
Variables
static const int64_t nDefaultDbCache = 100
-dbcache default (MiB)
static const int64_t nMaxDbCache = sizeof(void*) > 4 ? 16384 : 1024
max. -dbcache in (MiB)
static const int64_t nMinDbCache = 4
min. -dbcache in (MiB)
Variable Documentation
nDefaultDbCache
const int64_t nDefaultDbCache = 100 static
-dbcache default (MiB)
Definition at line 32 of file txdb.h.
Referenced by AppInit2(), HelpMessage(), and OptionsModel::Init().
nMaxDbCache
const int64_t nMaxDbCache = sizeof(void*) > 4 ? 16384 : 1024 static
max. -dbcache in (MiB)
Definition at line 34 of file txdb.h.
Referenced by AppInit2(), HelpMessage(), and OptionsDialog::OptionsDialog().
nMinDbCache
const int64_t nMinDbCache = 4 static
min. -dbcache in (MiB)
Definition at line 36 of file txdb.h.
Referenced by AppInit2(), HelpMessage(), and OptionsDialog::OptionsDialog().