Dash Core: src/txmempool.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
txmempool.cpp File Reference
#include <txmempool.h>
#include <consensus/consensus.h>
#include <consensus/tx_verify.h>
#include <consensus/validation.h>
#include <validation.h>
#include <policy/policy.h>
#include <policy/fees.h>
#include <random.h>
#include <reverse_iterator.h>
#include <streams.h>
#include <timedata.h>
#include <util.h>
#include <utilmoneystr.h>
#include <utiltime.h>
#include <hash.h>
#include <evo/specialtx.h>
#include <evo/providertx.h>
#include <llmq/quorums_instantsend.h>
Functions
static void CheckInputsAndUpdateCoins (const CTransaction &tx, CCoinsViewCache &mempoolDuplicate, const int64_t spendheight)
static TxMempoolInfo GetInfo (CTxMemPool::indexed_transaction_set::const_iterator it)
Function Documentation
CheckInputsAndUpdateCoins()
static void CheckInputsAndUpdateCoins (const CTransaction & tx, CCoinsViewCache & mempoolDuplicate, const int64_t spendheight) static
Definition at line 1004 of file txmempool.cpp.
References Consensus::CheckTxInputs(), CTransaction::IsCoinBase(), and UpdateCoins().
Referenced by CTxMemPool::check().
GetInfo()
static TxMempoolInfo GetInfo (CTxMemPool::indexed_transaction_set::const_iterator it) static
Definition at line 1193 of file txmempool.cpp.
References CFeeRate::GetFee().
Referenced by CTxMemPool::info(), and CTxMemPool::infoAll().
Released under the MIT license