Dash Core: src/txmempool.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
txmempool.h File Reference
#include <list>
#include <set>
#include "addressindex.h"
#include "spentindex.h"
#include "amount.h"
#include "coins.h"
#include "primitives/transaction.h"
#include "sync.h"
#include "boost/multi_index_container.hpp"
#include "boost/multi_index/ordered_index.hpp"
Classes
struct LockPoints
class CTxMemPoolEntry
CTxMemPoolEntry stores data about the correponding transaction, as well as data about all in-mempool transactions that depend on the transaction ("descendant" transactions).
struct update_descendant_state
struct set_dirty
struct update_fee_delta
struct update_lock_points
struct mempoolentry_txid
class CompareTxMemPoolEntryByDescendantScore
Sort an entry by max(score/size of entry's tx, score/size with all descendants).
class CompareTxMemPoolEntryByScore
Sort by score of entry ((fee+delta)/size) in descending order.
class CompareTxMemPoolEntryByEntryTime
class CInPoint
An inpoint - a combination of a transaction and an index n into its vin.
class CTxMemPool
CTxMemPool stores valid-according-to-the-current-best-chain transactions that may be included in the next block.
struct CTxMemPool::CompareIteratorByHash
struct CTxMemPool::TxLinks
class CCoinsViewMemPool
CCoinsView that brings transactions from a memorypool into view.
struct TxCoinAgePriorityCompare
Typedefs
typedef std::pair< double, CTxMemPool::txiter > TxCoinAgePriority
Functions
double AllowFreeThreshold ()
bool AllowFree (double dPriority)
Variables
static const unsigned int MEMPOOL_HEIGHT = 0x7FFFFFFF
Fake height value used in CCoins to signify they are only in the memory pool (since 0.8)
Typedef Documentation
TxCoinAgePriority
typedef std::pair<double, CTxMemPool::txiter> TxCoinAgePriority
Definition at line 650 of file txmempool.h.
Function Documentation
AllowFree()
bool AllowFree (double dPriority) inline
Definition at line 31 of file txmempool.h.
References AllowFreeThreshold().
Referenced by AcceptToMemoryPoolWorker(), CreateNewBlock(), and CWallet::CreateTransaction().
AllowFreeThreshold()
double AllowFreeThreshold () inline
Definition at line 26 of file txmempool.h.
References COIN.
Referenced by AllowFree(), CBlockPolicyEstimator::CBlockPolicyEstimator(), and CoinControlDialog::updateLabels().
Variable Documentation
MEMPOOL_HEIGHT
const unsigned int MEMPOOL_HEIGHT = 0x7FFFFFFF static
Fake height value used in CCoins to signify they are only in the memory pool (since 0.8)
Definition at line 40 of file txmempool.h.
Referenced by CheckSequenceLocks(), CCoinsViewMemPool::GetCoins(), and gettxout().
Released under the MIT license