Dash Core: src/univalue/lib/univalue_write.cpp File Reference
univalue_write.cpp File Reference
#include <iomanip>
#include <sstream>
#include <stdio.h>
#include "univalue.h"
#include "univalue_escapes.h"
Functions
static string json_escape (const string &inS)
static void indentStr (unsigned int prettyIndent, unsigned int indentLevel, string &s)
Function Documentation
indentStr()
static void indentStr (unsigned int prettyIndent, unsigned int indentLevel, string & s) static
Definition at line 65 of file univalue_write.cpp.
Referenced by UniValue::writeArray(), and UniValue::writeObject().
json_escape()
static string json_escape (const string & inS) static
Definition at line 13 of file univalue_write.cpp.
Referenced by UniValue::write(), and UniValue::writeObject().