Dash Core: src/univalue/lib/univalue_read.cpp File Reference
univalue_read.cpp File Reference
#include <string.h>
#include <vector>
#include <stdio.h>
#include "univalue.h"
#include "univalue_utffilter.h"
Macros
#define expect(bit) (expectMask & (EXP_##bit))
#define setExpect(bit) (expectMask |= EXP_##bit)
#define clearExpect(bit) (expectMask &= ~EXP_##bit)
Enumerations
enum expect_bits {
EXP_OBJ_NAME = (1U << 0), EXP_COLON = (1U << 1), EXP_ARR_VALUE = (1U << 2), EXP_VALUE = (1U << 3),
EXP_NOT_VALUE = (1U << 4)
}
Functions
static bool json_isdigit (int ch)
static const char * hatoui (const char *first, const char *last, unsigned int &out)
enum jtokentype getJsonToken (string &tokenVal, unsigned int &consumed, const char *raw)
Macro Definition Documentation
clearExpect
#define clearExpect (bit) (expectMask &= ~EXP_##bit)
Definition at line 247 of file univalue_read.cpp.
Referenced by UniValue::read().
expect
#define expect (bit) (expectMask & (EXP_##bit))
Definition at line 245 of file univalue_read.cpp.
Referenced by ContextualCheckBlock(), and UniValue::read().
setExpect
#define setExpect (bit) (expectMask |= EXP_##bit)
Definition at line 246 of file univalue_read.cpp.
Referenced by UniValue::read().
Enumeration Type Documentation
expect_bits
enum expect_bits
Enumerator
EXP_OBJ_NAME
EXP_COLON
EXP_ARR_VALUE
EXP_VALUE
EXP_NOT_VALUE
Definition at line 237 of file univalue_read.cpp.
Function Documentation
getJsonToken()
enum jtokentype getJsonToken (string & tokenVal, unsigned int & consumed, const char * raw)
Definition at line 45 of file univalue_read.cpp.
Referenced by UniValue::read().
hatoui()
static const char* hatoui (const char * first, const char * last, unsigned int & out) static
Definition at line 19 of file univalue_read.cpp.
Referenced by getJsonToken().
json_isdigit()
static bool json_isdigit (int ch) static
Definition at line 13 of file univalue_read.cpp.
Referenced by getJsonToken(), and hatoui().