Dash Core: src/utilmoneystr.h File Reference
utilmoneystr.h File Reference
#include <stdint.h>
#include <string>
#include "amount.h"
Functions
std::string FormatMoney (const CAmount &n)
bool ParseMoney (const std::string &str, CAmount &nRet)
bool ParseMoney (const char *pszIn, CAmount &nRet)
Function Documentation
FormatMoney()
std::string FormatMoney (const CAmount & n)
Money parsing/formatting utilities.
Definition at line 14 of file utilmoneystr.cpp.
Referenced by AcceptToMemoryPoolWorker(), Consensus::CheckTxInputs(), CPrivateSend::GetDenominationsToString(), getsuperblockbudget(), HelpMessage(), CTxMemPool::PrioritiseTransaction(), ProcessBlockFound(), CWallet::SelectCoinsMinConf(), SendMoney(), COutput::ToString(), and TxToUniv().
ParseMoney() [1/2]
bool ParseMoney (const std::string & str, CAmount & nRet)
ParseMoney() [2/2]
bool ParseMoney (const char * pszIn, CAmount & nRet)
Definition at line 41 of file utilmoneystr.cpp.