Dash Core: src/utilstrencodings.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
utilstrencodings.cpp File Reference
#include <utilstrencodings.h>
#include <tinyformat.h>
#include <cstdlib>
#include <cstring>
#include <errno.h>
#include <limits>
Functions
std::string SanitizeString (const std::string &str, int rule)
Remove unsafe chars.
signed char HexDigit (char c)
bool IsHex (const std::string &str)
bool IsHexNumber (const std::string &str)
Return true if the string is a hex number, optionally prefixed with "0x".
std::vector< unsigned char > ParseHex (const char *psz)
std::vector< unsigned char > ParseHex (const std::string &str)
void SplitHostPort (std::string in, int &portOut, std::string &hostOut)
std::string EncodeBase64 (const unsigned char *pch, size_t len)
std::string EncodeBase64 (const std::string &str)
std::vector< unsigned char > DecodeBase64 (const char *p, bool *pfInvalid)
std::string DecodeBase64 (const std::string &str)
std::string EncodeBase32 (const unsigned char *pch, size_t len)
std::string EncodeBase32 (const std::string &str)
std::vector< unsigned char > DecodeBase32 (const char *p, bool *pfInvalid)
std::string DecodeBase32 (const std::string &str)
static bool ParsePrechecks (const std::string &str)
bool ParseInt32 (const std::string &str, int32_t *out)
Convert string to signed 32-bit integer with strict parse error feedback.
bool ParseInt64 (const std::string &str, int64_t *out)
Convert string to signed 64-bit integer with strict parse error feedback.
bool ParseUInt32 (const std::string &str, uint32_t *out)
Convert decimal string to unsigned 32-bit integer with strict parse error feedback.
bool ParseUInt64 (const std::string &str, uint64_t *out)
Convert decimal string to unsigned 64-bit integer with strict parse error feedback.
bool ParseDouble (const std::string &str, double *out)
Convert string to double with strict parse error feedback.
std::string FormatParagraph (const std::string &in, size_t width, size_t indent)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.
std::string i64tostr (int64_t n)
std::string itostr (int n)
int64_t atoi64 (const char *psz)
int64_t atoi64 (const std::string &str)
int atoi (const std::string &str)
static bool ProcessMantissaDigit (char ch, int64_t &mantissa, int &mantissa_tzeros)
Helper function for ParseFixedPoint.
bool ParseFixedPoint (const std::string &val, int decimals, int64_t *amount_out)
Parse number as fixed point according to JSON number syntax.
Variables
static const std::string CHARS_ALPHA_NUM = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
static const std::string SAFE_CHARS []
const signed char p_util_hexdigit [256]
static const int64_t UPPER_BOUND = 1000000000000000000LL - 1LL
Upper bound for mantissa.
Function Documentation
atoi()
int atoi (const std::string & str)
Definition at line 612 of file utilstrencodings.cpp.
References atoi().
Referenced by atoi(), CleanupBlockRevFiles(), CWallet::GetMasternodeOutpointAndKeys(), gobject_getcurrentvotes(), gobject_submit(), int_atoi(), InterpretBool(), masternode_winners(), MutateTxAddInput(), MutateTxDelInput(), MutateTxDelOutput(), MutateTxSign(), TorControlConnection::readcb(), and RPCConsole::RPCParseCommandLine().
atoi64() [1/2]
int64_t atoi64 (const char * psz)
Definition at line 594 of file utilstrencodings.cpp.
Referenced by ArgsManager::GetArg(), getblocktemplate(), gobject_submit(), MutateTxLocktime(), MutateTxVersion(), ParseMoney(), ParseScript(), ReadOrderPos(), and CWalletTx::SerializationOp().
atoi64() [2/2]
int64_t atoi64 (const std::string & str)
Definition at line 603 of file utilstrencodings.cpp.
DecodeBase32() [1/2]
std::vector<unsigned char> DecodeBase32 (const char * p, bool * pfInvalid)
Definition at line 330 of file utilstrencodings.cpp.
Referenced by DecodeBase32(), GetCrashInfoStrFromSerializedStr(), and CNetAddr::SetSpecial().
DecodeBase32() [2/2]
std::string DecodeBase32 (const std::string & str)
Definition at line 447 of file utilstrencodings.cpp.
References DecodeBase32().
DecodeBase64() [1/2]
std::vector<unsigned char> DecodeBase64 (const char * p, bool * pfInvalid)
Definition at line 177 of file utilstrencodings.cpp.
Referenced by DecodeBase64(), CKeePassIntegrator::CKeePassResponse::decrypt(), SignVerifyMessageDialog::on_verifyMessageButton_VM_clicked(), CKeePassIntegrator::CKeePassResponse::parseResponse(), RPCAuthorized(), verifymessage(), and voteraw().
DecodeBase64() [2/2]
std::string DecodeBase64 (const std::string & str)
Definition at line 260 of file utilstrencodings.cpp.
References DecodeBase64().
EncodeBase32() [1/2]
std::string EncodeBase32 (const unsigned char * pch, size_t len)
Definition at line 266 of file utilstrencodings.cpp.
Referenced by EncodeBase32(), GetCrashInfoStrNoDebugInfo(), and CNetAddr::ToStringIP().
EncodeBase32() [2/2]
std::string EncodeBase32 (const std::string & str)
Definition at line 325 of file utilstrencodings.cpp.
References EncodeBase32().
EncodeBase64() [1/2]
std::string EncodeBase64 (const unsigned char * pch, size_t len)
Definition at line 126 of file utilstrencodings.cpp.
Referenced by CKeePassIntegrator::CKeePassRequest::addStrParameter(), CallRPC(), EncodeBase64(), SignVerifyMessageDialog::on_signMessageButton_SM_clicked(), signmessage(), signmessagewithprivkey(), and CHashSigner::VerifyHash().
EncodeBase64() [2/2]
std::string EncodeBase64 (const std::string & str)
Definition at line 172 of file utilstrencodings.cpp.
References EncodeBase64().
FormatParagraph()
std::string FormatParagraph (const std::string & in, size_t width, size_t indent)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.
Definition at line 543 of file utilstrencodings.cpp.
Referenced by AppInit(), and HelpMessageOpt().
HexDigit()
signed char HexDigit (char c)
Definition at line 53 of file utilstrencodings.cpp.
References p_util_hexdigit.
Referenced by IsHex(), IsHexNumber(), ParseHex(), and base_blob< 512 >::SetHex().
i64tostr()
std::string i64tostr (int64_t n)
Definition at line 584 of file utilstrencodings.cpp.
References strprintf.
Referenced by getblocktemplate(), and WriteOrderPos().
IsHex()
bool IsHex (const std::string & str)
Definition at line 58 of file utilstrencodings.cpp.
References HexDigit().
Referenced by addmultisigaddress(), createmultisig(), DecodeHexBlk(), DecodeHexTx(), CWallet::GenerateNewHDChain(), gettxoutproof(), HexToPubKey(), importaddress(), importpubkey(), importwallet(), lockunspent(), MutateTxAddInput(), MutateTxAddOutData(), WalletInit::ParameterInteraction(), ParseHashStr(), ParseHashV(), ParseHexUV(), ParseHexV(), ParseScript(), ProcessImport(), rest_getutxos(), and CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetHexStr().
IsHexNumber()
bool IsHexNumber (const std::string & str)
Return true if the string is a hex number, optionally prefixed with "0x".
Definition at line 68 of file utilstrencodings.cpp.
References HexDigit().
Referenced by AppInitParameterInteraction().
itostr()
std::string itostr (int n)
Definition at line 589 of file utilstrencodings.cpp.
References strprintf.
Referenced by keypoolrefill(), WalletInit::ParameterInteraction(), ParseBoolV(), ProcessMessage(), CKeePassIntegrator::rpcAssociate(), CKeePassIntegrator::rpcGetLogins(), CKeePassIntegrator::rpcSetLogin(), strings_1_itostr(), and strings_2_multi_itostr().
ParseDouble()
bool ParseDouble (const std::string & str, double * out)
Convert string to double with strict parse error feedback.
Returns
true if the entire string could be parsed as valid double, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 529 of file utilstrencodings.cpp.
References ParsePrechecks().
Referenced by UniValue::get_real(), and ParseDoubleV().
ParseFixedPoint()
bool ParseFixedPoint (const std::string & val, int decimals, int64_t * amount_out)
Parse number as fixed point according to JSON number syntax.
See http://json.org/number.gif
Returns
true on success, false on error.
Note
The result must be in the range (-10^18,10^18), otherwise an overflow error will trigger.
Definition at line 644 of file utilstrencodings.cpp.
References ProcessMantissaDigit(), and UPPER_BOUND.
Referenced by AmountFromValue(), and ParsePaymentAmount().
ParseHex() [1/2]
std::vector<unsigned char> ParseHex (const char * psz)
Definition at line 81 of file utilstrencodings.cpp.
References HexDigit().
Referenced by AppInitMain(), TorController::authchallenge_cb(), BOOST_AUTO_TEST_CASE(), CreateGenesisBlock(), DecodeHexBlk(), DecodeHexTx(), CWallet::GenerateNewHDChain(), getmerkleblocks(), gobject_deserialize(), HexToPubKey(), importaddress(), importpubkey(), importwallet(), MutateTxAddOutData(), MutateTxAddOutMultiSig(), MutateTxAddOutPubKey(), ParseHex(), ParseHexUV(), ParseHexV(), ParseScript(), CProposalValidator::ParseStrHexData(), ProcessImport(), rest_getutxos(), BerkeleyEnvironment::Salvage(), CBLSWrapper< bls::InsecureSignature, BLS_CURVE_SIG_SIZE, CBLSSignature >::SetHexStr(), and TestAES256CBC().
ParseHex() [2/2]
std::vector<unsigned char> ParseHex (const std::string & str)
Definition at line 102 of file utilstrencodings.cpp.
References ParseHex().
ParseInt32()
bool ParseInt32 (const std::string & str, int32_t * out)
Convert string to signed 32-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 464 of file utilstrencodings.cpp.
References ParsePrechecks().
Referenced by AppInitParameterInteraction(), UniValue::get_int(), LookupSubNet(), ParseInt32V(), rest_getutxos(), and SplitHostPort().
ParseInt64()
bool ParseInt64 (const std::string & str, int64_t * out)
Convert string to signed 64-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 480 of file utilstrencodings.cpp.
References ParsePrechecks().
Referenced by AppInitParameterInteraction(), UniValue::get_int64(), and ParseInt64V().
ParsePrechecks()
static bool ParsePrechecks (const std::string & str) static
Definition at line 453 of file utilstrencodings.cpp.
Referenced by ParseDouble(), ParseInt32(), ParseInt64(), ParseUInt32(), and ParseUInt64().
ParseUInt32()
bool ParseUInt32 (const std::string & str, uint32_t * out)
Convert decimal string to unsigned 32-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 495 of file utilstrencodings.cpp.
References ParsePrechecks().
ParseUInt64()
bool ParseUInt64 (const std::string & str, uint64_t * out)
Convert decimal string to unsigned 64-bit integer with strict parse error feedback.
Returns
true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
Definition at line 512 of file utilstrencodings.cpp.
References ParsePrechecks().
ProcessMantissaDigit()
static bool ProcessMantissaDigit (char ch, int64_t & mantissa, int & mantissa_tzeros) inline static
Helper function for ParseFixedPoint.
Definition at line 628 of file utilstrencodings.cpp.
References UPPER_BOUND.
Referenced by ParseFixedPoint().
SanitizeString()
std::string SanitizeString (const std::string & str, int rule = SAFE_CHARS_DEFAULT)
Remove unsafe chars.
Safe chars chosen to allow simple messages/URLs/email addresses, but avoid anything even possibly remotely dangerous like & or >
Parameters
[in] str The string to sanitize
[in] rule The set of safe chars to choose (default: least restrictive)
Returns
A new string without unsafe chars
Definition at line 24 of file utilstrencodings.cpp.
References SAFE_CHARS.
Referenced by TorController::add_onion_cb(), AlertNotify(), AppInitMain(), TorController::authchallenge_cb(), JSONRPCRequest::parse(), ProcessMessage(), PeerLogicValidation::ProcessMessages(), and CConnman::PushMessage().
SplitHostPort()
void SplitHostPort (std::string in, int & portOut, std::string & hostOut)
Definition at line 107 of file utilstrencodings.cpp.
References ParseInt32().
Referenced by CallRPC(), CConnman::ConnectNode(), HTTPBindAddresses(), and Lookup().
Variable Documentation
CHARS_ALPHA_NUM
const std::string CHARS_ALPHA_NUM = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" static
Definition at line 15 of file utilstrencodings.cpp.
p_util_hexdigit
const signed char p_util_hexdigit[256]
Initial value:
=
{ -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  0,1,2,3,4,5,6,7,8,9,-1,-1,-1,-1,-1,-1,
  -1,0xa,0xb,0xc,0xd,0xe,0xf,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,0xa,0xb,0xc,0xd,0xe,0xf,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
  -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, }
Definition at line 35 of file utilstrencodings.cpp.
Referenced by HexDigit().
SAFE_CHARS
const std::string SAFE_CHARS[] static
Initial value:
=
{
    CHARS_ALPHA_NUM + " .,;-_/:?@()",
    CHARS_ALPHA_NUM + " .,;-_?@",
    CHARS_ALPHA_NUM + ".-_",
}
Definition at line 17 of file utilstrencodings.cpp.
Referenced by SanitizeString().
UPPER_BOUND
const int64_t UPPER_BOUND = 1000000000000000000LL - 1LL static
Upper bound for mantissa.
10^18-1 is the largest arbitrary decimal that will fit in a signed 64-bit integer. Larger integers cannot consist of arbitrary combinations of 0-9:
999999999999999999 1^18-1 9223372036854775807 (1<<63)-1 (max int64_t) 9999999999999999999 1^19-1 (would overflow)
Definition at line 625 of file utilstrencodings.cpp.
Referenced by ParseFixedPoint(), and ProcessMantissaDigit().
Released under the MIT license