Dash Core: src/utilmoneystr.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
utilmoneystr.cpp File Reference
#include <utilmoneystr.h>
#include <primitives/transaction.h>
#include <tinyformat.h>
#include <utilstrencodings.h>
Functions
std::string FormatMoney (const CAmount &n)
Money parsing/formatting utilities.
bool ParseMoney (const std::string &str, CAmount &nRet)
bool ParseMoney (const char *pszIn, CAmount &nRet)
Function Documentation
FormatMoney()
std::string FormatMoney (const CAmount & n)
Money parsing/formatting utilities.
Definition at line 12 of file utilmoneystr.cpp.
References COIN, and strprintf.
Referenced by Consensus::CheckTxInputs(), CPrivateSendClientSession::DoAutomaticDenominating(), WalletInit::GetHelpString(), HelpMessage(), CTxMemPool::PrioritiseTransaction(), CWallet::SelectCoinsMinConf(), SendMoney(), and COutput::ToString().
ParseMoney() [1/2]
bool ParseMoney (const std::string & str, CAmount & nRet)
Definition at line 34 of file utilmoneystr.cpp.
References ParseMoney().
Referenced by AppInitParameterInteraction(), DefaultOptions(), ExtractAndValidateValue(), WalletInit::ParameterInteraction(), and ParseMoney().
ParseMoney() [2/2]
bool ParseMoney (const char * pszIn, CAmount & nRet)
Definition at line 39 of file utilmoneystr.cpp.
References atoi64(), CENT, and COIN.
Released under the MIT license