Dash Core: src/validationinterface.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
validationinterface.cpp File Reference
#include "validationinterface.h"
Functions
CMainSignals & GetMainSignals ()
void RegisterValidationInterface (CValidationInterface *pwalletIn)
Register a wallet to receive updates from core.
void UnregisterValidationInterface (CValidationInterface *pwalletIn)
Unregister a wallet from core.
void UnregisterAllValidationInterfaces ()
Unregister all wallets from core.
Variables
static CMainSignals g_signals
Function Documentation
GetMainSignals()
CMainSignals& GetMainSignals ()
Definition at line 10 of file validationinterface.cpp.
References g_signals.
Referenced by AcceptBlockHeader(), AcceptToMemoryPoolWorker(), ActivateBestChain(), BitcoinMiner(), ConnectBlock(), ConnectTip(), DisconnectTip(), FlushStateToDisk(), generate(), NotifyHeaderTip(), ProcessBlockFound(), ProcessGetData(), ProcessMessage(), ProcessNewBlock(), SendMessages(), and CInstantSend::UpdateLockedTransaction().
RegisterValidationInterface()
void RegisterValidationInterface (CValidationInterface * pwalletIn)
Register a wallet to receive updates from core.
Definition at line 15 of file validationinterface.cpp.
References CValidationInterface::AcceptedBlockHeader(), CMainSignals::AcceptedBlockHeader, CValidationInterface::BlockChecked(), CMainSignals::BlockChecked, CMainSignals::BlockFound, CMainSignals::Broadcast, g_signals, CValidationInterface::GetScriptForMining(), CValidationInterface::Inventory(), CMainSignals::Inventory, CValidationInterface::NotifyHeaderTip(), CMainSignals::NotifyHeaderTip, CValidationInterface::NotifyTransactionLock(), CMainSignals::NotifyTransactionLock, CValidationInterface::ResendWalletTransactions(), CValidationInterface::ResetRequestCount(), CMainSignals::ScriptForMining, CValidationInterface::SetBestChain(), CMainSignals::SetBestChain, CValidationInterface::SyncTransaction(), CMainSignals::SyncTransaction, CValidationInterface::UpdatedBlockTip(), CMainSignals::UpdatedBlockTip, CValidationInterface::UpdatedTransaction(), and CMainSignals::UpdatedTransaction.
Referenced by AppInit2(), and submitblock().
UnregisterAllValidationInterfaces()
void UnregisterAllValidationInterfaces ()
Unregister all wallets from core.
Definition at line 45 of file validationinterface.cpp.
References CMainSignals::AcceptedBlockHeader, CMainSignals::BlockChecked, CMainSignals::BlockFound, CMainSignals::Broadcast, g_signals, CMainSignals::Inventory, CMainSignals::NotifyHeaderTip, CMainSignals::NotifyTransactionLock, CMainSignals::ScriptForMining, CMainSignals::SetBestChain, CMainSignals::SyncTransaction, CMainSignals::UpdatedBlockTip, and CMainSignals::UpdatedTransaction.
Referenced by PrepareShutdown().
UnregisterValidationInterface()
void UnregisterValidationInterface (CValidationInterface * pwalletIn)
Unregister a wallet from core.
Definition at line 30 of file validationinterface.cpp.
References CValidationInterface::AcceptedBlockHeader(), CMainSignals::AcceptedBlockHeader, CValidationInterface::BlockChecked(), CMainSignals::BlockChecked, CMainSignals::BlockFound, CMainSignals::Broadcast, g_signals, CValidationInterface::GetScriptForMining(), CValidationInterface::Inventory(), CMainSignals::Inventory, CValidationInterface::NotifyHeaderTip(), CMainSignals::NotifyHeaderTip, CValidationInterface::NotifyTransactionLock(), CMainSignals::NotifyTransactionLock, CValidationInterface::ResendWalletTransactions(), CValidationInterface::ResetRequestCount(), CMainSignals::ScriptForMining, CValidationInterface::SetBestChain(), CMainSignals::SetBestChain, CValidationInterface::SyncTransaction(), CMainSignals::SyncTransaction, CValidationInterface::UpdatedBlockTip(), CMainSignals::UpdatedBlockTip, CValidationInterface::UpdatedTransaction(), and CMainSignals::UpdatedTransaction.
Referenced by PrepareShutdown(), and submitblock().
Variable Documentation
g_signals
CMainSignals g_signals static
Definition at line 8 of file validationinterface.cpp.
Referenced by GetMainSignals(), RegisterValidationInterface(), UnregisterAllValidationInterfaces(), and UnregisterValidationInterface().
Released under the MIT license