Dash Core: src/versionbits.h File Reference
versionbits.h File Reference
#include "chain.h"
#include <map>
Classes
struct BIP9DeploymentInfo
class AbstractThresholdConditionChecker
struct VersionBitsCache
Typedefs
typedef std::map< const CBlockIndex *, ThresholdState > ThresholdConditionCache
Enumerations
enum ThresholdState {
THRESHOLD_DEFINED, THRESHOLD_STARTED, THRESHOLD_LOCKED_IN, THRESHOLD_ACTIVE,
THRESHOLD_FAILED
}
Functions
ThresholdState VersionBitsState (const CBlockIndex *pindexPrev, const Consensus::Params &params, Consensus::DeploymentPos pos, VersionBitsCache &cache)
uint32_t VersionBitsMask (const Consensus::Params &params, Consensus::DeploymentPos pos)
Variables
static const int32_t VERSIONBITS_LAST_OLD_BLOCK_VERSION = 4
static const int32_t VERSIONBITS_TOP_BITS = 0x20000000UL
static const int32_t VERSIONBITS_TOP_MASK = 0xE0000000UL
static const int32_t VERSIONBITS_NUM_BITS = 29
const struct BIP9DeploymentInfo VersionBitsDeploymentInfo []
Typedef Documentation
ThresholdConditionCache
typedef std::map<const CBlockIndex*, ThresholdState> ThresholdConditionCache
Definition at line 31 of file versionbits.h.
Enumeration Type Documentation
ThresholdState
enum ThresholdState
Enumerator
THRESHOLD_DEFINED
THRESHOLD_STARTED
THRESHOLD_LOCKED_IN
THRESHOLD_ACTIVE
THRESHOLD_FAILED
Definition at line 20 of file versionbits.h.
Function Documentation
VersionBitsMask()
uint32_t VersionBitsMask (const Consensus::Params & params, Consensus::DeploymentPos pos)
Definition at line 143 of file versionbits.cpp.
Referenced by ComputeBlockVersion(), and getblocktemplate().
VersionBitsState()
ThresholdState VersionBitsState (const CBlockIndex * pindexPrev, const Consensus::Params & params, Consensus::DeploymentPos pos, VersionBitsCache & cache)
Definition at line 138 of file versionbits.cpp.
Referenced by ComputeBlockVersion(), ConnectBlock(), ContextualCheckBlock(), ContextualCheckTransaction(), getblocktemplate(), CDSNotificationInterface::UpdatedBlockTip(), and VersionBitsTipState().
Variable Documentation
VERSIONBITS_LAST_OLD_BLOCK_VERSION
const int32_t VERSIONBITS_LAST_OLD_BLOCK_VERSION = 4 static
What block version to use for new blocks (pre versionbits)
Definition at line 12 of file versionbits.h.
Referenced by UpdateTip().
VERSIONBITS_NUM_BITS
const int32_t VERSIONBITS_NUM_BITS = 29 static
Total bits available for versionbits
Definition at line 18 of file versionbits.h.
Referenced by UnloadBlockIndex(), and UpdateTip().
VERSIONBITS_TOP_BITS
const int32_t VERSIONBITS_TOP_BITS = 0x20000000UL static
What bits to set in version for versionbits blocks
Definition at line 14 of file versionbits.h.
Referenced by ComputeBlockVersion(), and WarningBitsConditionChecker::Condition().
VERSIONBITS_TOP_MASK
const int32_t VERSIONBITS_TOP_MASK = 0xE0000000UL static
What bitmask determines whether versionbits is in use
Definition at line 16 of file versionbits.h.
Referenced by WarningBitsConditionChecker::Condition().
VersionBitsDeploymentInfo
const struct BIP9DeploymentInfo VersionBitsDeploymentInfo[]
Definition at line 9 of file versionbits.cpp.
Referenced by ComputeBlockVersion(), gbt_vb_name(), and getblocktemplate().