Dash Core: src/versionbits.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
versionbits.cpp File Reference
#include <versionbits.h>
#include <consensus/params.h>
Functions
ThresholdState VersionBitsState (const CBlockIndex *pindexPrev, const Consensus::Params &params, Consensus::DeploymentPos pos, VersionBitsCache &cache)
BIP9Stats VersionBitsStatistics (const CBlockIndex *pindexPrev, const Consensus::Params &params, Consensus::DeploymentPos pos, VersionBitsCache &cache)
int VersionBitsStateSinceHeight (const CBlockIndex *pindexPrev, const Consensus::Params &params, Consensus::DeploymentPos pos, VersionBitsCache &cache)
uint32_t VersionBitsMask (const Consensus::Params &params, Consensus::DeploymentPos pos)
Variables
const struct VBDeploymentInfo VersionBitsDeploymentInfo [Consensus::MAX_VERSION_BITS_DEPLOYMENTS]
Function Documentation
VersionBitsMask()
uint32_t VersionBitsMask (const Consensus::Params & params, Consensus::DeploymentPos pos)
Definition at line 260 of file versionbits.cpp.
Referenced by ComputeBlockVersion(), and getblocktemplate().
VersionBitsState()
ThresholdState VersionBitsState (const CBlockIndex * pindexPrev, const Consensus::Params & params, Consensus::DeploymentPos pos, VersionBitsCache & cache)
Definition at line 245 of file versionbits.cpp.
References VersionBitsCache::caches.
Referenced by llmq::CChainLocksHandler::CheckActiveState(), CheckCbTx(), ComputeBlockVersion(), CChainState::ConnectBlock(), ContextualCheckBlock(), BlockAssembler::CreateNewBlock(), GetBlockScriptFlags(), getblocktemplate(), CMasternodePayments::GetBlockTxOuts(), llmq::CInstantSendManager::UpdatedBlockTip(), and VersionBitsTipState().
VersionBitsStateSinceHeight()
int VersionBitsStateSinceHeight (const CBlockIndex * pindexPrev, const Consensus::Params & params, Consensus::DeploymentPos pos, VersionBitsCache & cache)
Definition at line 255 of file versionbits.cpp.
References VersionBitsCache::caches.
Referenced by CMasternodePayments::GetBlockTxOuts(), and VersionBitsTipStateSinceHeight().
VersionBitsStatistics()
BIP9Stats VersionBitsStatistics (const CBlockIndex * pindexPrev, const Consensus::Params & params, Consensus::DeploymentPos pos, VersionBitsCache & cache)
Definition at line 250 of file versionbits.cpp.
References VersionBitsCache::caches.
Referenced by VersionBitsTipStatistics().
Variable Documentation
VersionBitsDeploymentInfo
const struct VBDeploymentInfo VersionBitsDeploymentInfo[Consensus::MAX_VERSION_BITS_DEPLOYMENTS]
Definition at line 8 of file versionbits.cpp.
Referenced by AppInitParameterInteraction(), BIP9SoftForkDescPushBack(), ComputeBlockVersion(), gbt_vb_name(), and getblocktemplate().
Released under the MIT license