Dash Core: src/wallet/walletutil.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
walletutil.h File Reference
#include <chainparamsbase.h>
#include <util.h>
Functions
fs::path GetWalletDir ()
Get the path of the wallet directory.
Function Documentation
GetWalletDir()
fs::path GetWalletDir ()
Get the path of the wallet directory.
Definition at line 7 of file walletutil.cpp.
References gArgs, ArgsManager::GetArg(), GetDataDir(), and ArgsManager::IsArgSet().
Referenced by loadwallet(), WalletInit::Open(), WalletInit::Verify(), and CWallet::Verify().
Released under the MIT license