Dash Core: src/wallet/fees.h File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
fees.h File Reference
#include <amount.h>
Functions
CAmount GetRequiredFee (unsigned int nTxBytes)
Return the minimum required fee taking into account the floating relay fee and user set minimum transaction fee.
CAmount GetMinimumFee (unsigned int nTxBytes, const CCoinControl &coin_control, const CTxMemPool &pool, const CBlockPolicyEstimator &estimator, FeeCalculation *feeCalc)
Estimate the minimum fee considering user set parameters and the required fee.
CFeeRate GetDiscardRate (const CBlockPolicyEstimator &estimator)
Return the maximum feerate for discarding change.
Function Documentation
GetDiscardRate()
CFeeRate GetDiscardRate (const CBlockPolicyEstimator & estimator)
Return the maximum feerate for discarding change.
Definition at line 78 of file fees.cpp.
References dustRelayFee, CBlockPolicyEstimator::estimateSmartFee(), CBlockPolicyEstimator::HighestTargetTracked(), LONG_HALFLIFE, and CWallet::m_discard_rate.
Referenced by CWallet::CreateTransaction(), and CTransactionBuilder::CTransactionBuilder().
GetMinimumFee()
CAmount GetMinimumFee (unsigned int nTxBytes, const CCoinControl & coin_control, const CTxMemPool & pool, const CBlockPolicyEstimator & estimator, FeeCalculation * feeCalc)
Estimate the minimum fee considering user set parameters and the required fee.
Definition at line 21 of file fees.cpp.
References CONSERVATIVE, DEFAULT_MAX_MEMPOOL_SIZE, ECONOMICAL, CBlockPolicyEstimator::estimateSmartFee(), FALLBACK, CWallet::fallbackFee, CCoinControl::fOverrideFeeRate, gArgs, ArgsManager::GetArg(), CFeeRate::GetFee(), CTxMemPool::GetMinFee(), GetRequiredFee(), CCoinControl::m_confirm_target, CCoinControl::m_fee_mode, CCoinControl::m_feerate, MAXTXFEE, maxTxFee, MEMPOOL_MIN, nTxConfirmTarget, PAYTXFEE, payTxFee, FeeCalculation::reason, and REQUIRED.
Referenced by CWallet::CreateTransaction(), CoinControlDialog::updateLabels(), and SendCoinsDialog::updateSmartFeeLabel().
GetRequiredFee()
CAmount GetRequiredFee (unsigned int nTxBytes)
Return the minimum required fee taking into account the floating relay fee and user set minimum transaction fee.
Definition at line 16 of file fees.cpp.
References CFeeRate::GetFee(), minRelayTxFee, and CWallet::minTxFee.
Referenced by CTransactionBuilder::GetFee(), GetMinimumFee(), SendCoinsDialog::setMinimumFee(), and SendCoinsDialog::updateMinFeeLabel().
Released under the MIT license