Dash Core: src/wallet/wallet_ismine.h File Reference
wallet_ismine.h File Reference
#include "script/standard.h"
#include <stdint.h>
Typedefs
typedef uint8_t isminefilter
Enumerations
enum isminetype {
ISMINE_NO = 0, ISMINE_WATCH_UNSOLVABLE = 1, ISMINE_WATCH_SOLVABLE = 2, ISMINE_WATCH_ONLY = ISMINE_WATCH_SOLVABLE | ISMINE_WATCH_UNSOLVABLE,
ISMINE_SPENDABLE = 4, ISMINE_ALL = ISMINE_WATCH_ONLY | ISMINE_SPENDABLE
}
Functions
isminetype IsMine (const CKeyStore &keystore, const CScript &scriptPubKey)
isminetype IsMine (const CKeyStore &keystore, const CTxDestination &dest)
Typedef Documentation
isminefilter
typedef uint8_t isminefilter
used for bitflags of isminetype
Definition at line 29 of file wallet_ismine.h.
Enumeration Type Documentation
isminetype
enum isminetype
IsMine() return codes
Enumerator
ISMINE_NO
ISMINE_WATCH_UNSOLVABLE
Indicates that we don't know how to create a scriptSig that would solve this if we were given the appropriate private keys.
ISMINE_WATCH_SOLVABLE
Indicates that we know how to create a scriptSig that would solve this if we were given the appropriate private keys.
ISMINE_WATCH_ONLY
ISMINE_SPENDABLE
ISMINE_ALL
Definition at line 17 of file wallet_ismine.h.
Function Documentation
IsMine() [1/2]
isminetype IsMine (const CKeyStore & keystore, const CScript & scriptPubKey)
Definition at line 38 of file wallet_ismine.cpp.
IsMine() [2/2]
isminetype IsMine (const CKeyStore & keystore, const CTxDestination & dest)
Definition at line 32 of file wallet_ismine.cpp.
Referenced by CWallet::AddToWallet(), CWallet::AddToWalletIfInvolvingMe(), CWallet::AvailableCoins(), CWallet::CountInputsWithAmount(), TransactionRecord::decomposeTransaction(), CWallet::DelAddressBook(), CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), CWallet::GetCredit(), CWallet::GetDebit(), CWallet::GetRealOutpointPrivateSendRounds(), getreceivedbyaccount(), getreceivedbyaddress(), ImportScript(), CWallet::IsChange(), IsMine(), CWallet::IsMine(), listaccounts(), ListReceived(), ListTransactions(), CWallet::LoadWallet(), AddressTablePriv::refreshAddressTable(), CWallet::SelectCoinsGrouppedByAddresses(), setaccount(), CWallet::SetAddressBook(), TransactionDesc::toHTML(), and validateaddress().