Dash Core: src/qt/walletmodel.cpp File Reference
walletmodel.cpp File Reference
#include "walletmodel.h"
#include "addresstablemodel.h"
#include "guiconstants.h"
#include "guiutil.h"
#include "paymentserver.h"
#include "recentrequeststablemodel.h"
#include "transactiontablemodel.h"
#include "base58.h"
#include "keystore.h"
#include "validation.h"
#include "net.h"
#include "sync.h"
#include "ui_interface.h"
#include "util.h"
#include "wallet/wallet.h"
#include "wallet/walletdb.h"
#include "instantx.h"
#include "spork.h"
#include "privatesend-client.h"
#include <stdint.h>
#include <QDebug>
#include <QSet>
#include <QTimer>
#include <boost/foreach.hpp>
Functions
static void NotifyKeyStoreStatusChanged (WalletModel *walletmodel, CCryptoKeyStore *wallet)
static void NotifyAddressBookChanged (WalletModel *walletmodel, CWallet *wallet, const CTxDestination &address, const std::string &label, bool isMine, const std::string &purpose, ChangeType status)
static void NotifyTransactionChanged (WalletModel *walletmodel, CWallet *wallet, const uint256 &hash, ChangeType status)
static void ShowProgress (WalletModel *walletmodel, const std::string &title, int nProgress)
static void NotifyWatchonlyChanged (WalletModel *walletmodel, bool fHaveWatchonly)
Function Documentation
NotifyAddressBookChanged()
static void NotifyAddressBookChanged (WalletModel * walletmodel, CWallet * wallet, const CTxDestination & address, const std::string & label, bool isMine, const std::string & purpose, ChangeType status) static
Definition at line 518 of file walletmodel.cpp.
Referenced by CWallet::DelAddressBook(), CWallet::SetAddressBook(), WalletModel::subscribeToCoreSignals(), and WalletModel::unsubscribeFromCoreSignals().
NotifyKeyStoreStatusChanged()
static void NotifyKeyStoreStatusChanged (WalletModel * walletmodel, CCryptoKeyStore * wallet) static
Definition at line 512 of file walletmodel.cpp.
Referenced by WalletModel::subscribeToCoreSignals(), and WalletModel::unsubscribeFromCoreSignals().
NotifyTransactionChanged()
static void NotifyTransactionChanged (WalletModel * walletmodel, CWallet * wallet, const uint256 & hash, ChangeType status) static
Definition at line 535 of file walletmodel.cpp.
Referenced by WalletModel::subscribeToCoreSignals(), and WalletModel::unsubscribeFromCoreSignals().
NotifyWatchonlyChanged()
static void NotifyWatchonlyChanged (WalletModel * walletmodel, bool fHaveWatchonly) static
Definition at line 551 of file walletmodel.cpp.
Referenced by CWallet::AddWatchOnly(), CWallet::RemoveWatchOnly(), WalletModel::subscribeToCoreSignals(), and WalletModel::unsubscribeFromCoreSignals().
ShowProgress()
static void ShowProgress (WalletModel * walletmodel, const std::string & title, int nProgress) static
Definition at line 543 of file walletmodel.cpp.
Referenced by WalletModel::subscribeToCoreSignals(), and WalletModel::unsubscribeFromCoreSignals().