Dash Core: src/wallet/wallet.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
wallet.cpp File Reference
#include <wallet/wallet.h>
#include <base58.h>
#include <checkpoints.h>
#include <chain.h>
#include <wallet/coincontrol.h>
#include <consensus/consensus.h>
#include <consensus/validation.h>
#include <fs.h>
#include <key.h>
#include <keystore.h>
#include <validation.h>
#include <net.h>
#include <policy/fees.h>
#include <policy/policy.h>
#include <primitives/block.h>
#include <primitives/transaction.h>
#include <script/script.h>
#include <script/sign.h>
#include <timedata.h>
#include <txmempool.h>
#include <util.h>
#include <utilmoneystr.h>
#include <wallet/fees.h>
#include <wallet/walletutil.h>
#include <governance/governance.h>
#include <keepass.h>
#include <privatesend/privatesend-client.h>
#include <spork.h>
#include <evo/providertx.h>
#include <llmq/quorums_instantsend.h>
#include <llmq/quorums_chainlocks.h>
#include <algorithm>
#include <assert.h>
#include <future>
#include <boost/algorithm/string/replace.hpp>
#include <boost/thread.hpp>
Classes
struct CompareValueOnly
class CAffectedKeysVisitor
struct CompareByPriority
Functions
static std::vector< CWallet * > vpwallets GUARDED_BY (cs_wallets)
bool AddWallet (CWallet *wallet)
bool RemoveWallet (CWallet *wallet)
bool HasWallets ()
std::vector< CWallet * > GetWallets ()
CWallet * GetWallet (const std::string &name)
static void ApproximateBestSubset (const std::vector< CInputCoin > &vValue, const CAmount &nTotalLower, const CAmount &nTargetValue, std::vector< char > &vfBest, CAmount &nBest, int iterations=1000)
bool less_then_denom (const COutput &out1, const COutput &out2)
static int64_t GetOldestKeyInPool (const std::set< int64_t > &setKeyPool, WalletBatch &batch)
Variables
static CCriticalSection cs_wallets
CFeeRate payTxFee (DEFAULT_TRANSACTION_FEE)
Transaction fee set by the user.
unsigned int nTxConfirmTarget = DEFAULT_TX_CONFIRM_TARGET
bool bSpendZeroConfChange = DEFAULT_SPEND_ZEROCONF_CHANGE
Function Documentation
AddWallet()
bool AddWallet (CWallet * wallet)
Definition at line 53 of file wallet.cpp.
References cs_wallets, and LOCK.
Referenced by BOOST_FIXTURE_TEST_CASE(), CreateTransactionTestSetup::CreateTransactionTestSetup(), loadwallet(), and WalletInit::Open().
GetWallet()
CWallet* GetWallet (const std::string & name)
Definition at line 85 of file wallet.cpp.
References cs_wallets, LOCK, and name.
Referenced by GetWalletForJSONRPCRequest().
GetWallets()
std::vector<CWallet*> GetWallets ()
Definition at line 79 of file wallet.cpp.
References cs_wallets, and LOCK.
Referenced by WalletInit::AutoLockMasternodeCollaterals(), CPrivateSendClientManager::CheckAutomaticBackup(), WalletInit::Close(), CPrivateSendClientSession::CreateDenominated(), CPrivateSendClientSession::DoAutomaticDenominating(), CPrivateSendClientManager::DoAutomaticDenominating(), WalletInit::Flush(), GetWalletForJSONRPCRequest(), BitcoinApplication::initializeResult(), WalletInit::InitPrivateSendSettings(), CPrivateSendClientSession::JoinExistingQueue(), listwallets(), CPrivateSendClientSession::MakeCollateralAmounts(), MaybeCompactWalletDB(), OptionsDialog::on_okButton_clicked(), CPrivateSendClientSession::PrepareDenominate(), RPCConsole::RPCParseCommandLine(), CPrivateSendClientSession::SelectDenominate(), CPrivateSendClientSession::SignFinalTransaction(), WalletInit::Start(), CPrivateSendClientSession::StartNewQueue(), WalletInit::Stop(), CPrivateSendClientSession::SubmitDenominate(), CPrivateSendClientSession::UnlockCoins(), and CWallet::Verify().
GUARDED_BY()
static std::vector<CWallet*> vpwallets GUARDED_BY (cs_wallets) static
HasWallets()
bool HasWallets ()
Definition at line 73 of file wallet.cpp.
References cs_wallets, and LOCK.
Referenced by EnsureWalletIsAvailable(), BitcoinApplication::initializeResult(), WalletInit::InitPrivateSendSettings(), OptionsDialog::on_okButton_clicked(), and RPCConsole::RPCParseCommandLine().
RemoveWallet()
bool RemoveWallet (CWallet * wallet)
Definition at line 63 of file wallet.cpp.
References cs_wallets, and LOCK.
Referenced by BOOST_FIXTURE_TEST_CASE(), WalletInit::Close(), and CreateTransactionTestSetup::~CreateTransactionTestSetup().
Variable Documentation
bSpendZeroConfChange
bool bSpendZeroConfChange = DEFAULT_SPEND_ZEROCONF_CHANGE
Definition at line 97 of file wallet.cpp.
Referenced by CWalletTx::IsTrusted(), WalletInit::ParameterInteraction(), and CWallet::SelectCoins().
cs_wallets
CCriticalSection cs_wallets static
Definition at line 50 of file wallet.cpp.
Referenced by AddWallet(), GetWallet(), GetWallets(), HasWallets(), RemoveWallet(), and CWallet::Verify().
nTxConfirmTarget
unsigned int nTxConfirmTarget = DEFAULT_TX_CONFIRM_TARGET
Definition at line 96 of file wallet.cpp.
Referenced by CTransactionBuilder::CTransactionBuilder(), WalletModel::getDefaultConfirmTarget(), GetMinimumFee(), and WalletInit::ParameterInteraction().
payTxFee
CFeeRate payTxFee(DEFAULT_TRANSACTION_FEE)
Transaction fee set by the user.
Settings.
Referenced by CTransactionBuilder::CTransactionBuilder(), WalletInit::GetHelpString(), GetMinimumFee(), getwalletinfo(), WalletInit::ParameterInteraction(), and settxfee().
Released under the MIT license