Dash Core: src/wallet/wallet_ismine.cpp File Reference
wallet_ismine.cpp File Reference
#include "wallet_ismine.h"
#include "key.h"
#include "keystore.h"
#include "script/script.h"
#include "script/standard.h"
#include "script/sign.h"
#include <boost/foreach.hpp>
Typedefs
typedef vector< unsigned char > valtype
Functions
unsigned int HaveKeys (const vector< valtype > &pubkeys, const CKeyStore &keystore)
isminetype IsMine (const CKeyStore &keystore, const CTxDestination &dest)
isminetype IsMine (const CKeyStore &keystore, const CScript &scriptPubKey)
Typedef Documentation
valtype
typedef vector<unsigned char> valtype
Definition at line 18 of file wallet_ismine.cpp.
Function Documentation
HaveKeys()
unsigned int HaveKeys (const vector< valtype > & pubkeys, const CKeyStore & keystore)
Definition at line 20 of file wallet_ismine.cpp.
Referenced by IsMine().
IsMine() [1/2]
isminetype IsMine (const CKeyStore & keystore, const CTxDestination & dest)
Definition at line 32 of file wallet_ismine.cpp.
Referenced by CWallet::AddToWallet(), CWallet::AddToWalletIfInvolvingMe(), CWallet::AvailableCoins(), CWallet::CountInputsWithAmount(), TransactionRecord::decomposeTransaction(), CWallet::DelAddressBook(), CWallet::GetAddressBalances(), CWallet::GetAddressGroupings(), CWallet::GetCredit(), CWallet::GetDebit(), CWallet::GetRealOutpointPrivateSendRounds(), getreceivedbyaccount(), getreceivedbyaddress(), ImportScript(), CWallet::IsChange(), IsMine(), CWallet::IsMine(), listaccounts(), ListReceived(), ListTransactions(), CWallet::LoadWallet(), AddressTablePriv::refreshAddressTable(), CWallet::SelectCoinsGrouppedByAddresses(), setaccount(), CWallet::SetAddressBook(), TransactionDesc::toHTML(), and validateaddress().
IsMine() [2/2]
isminetype IsMine (const CKeyStore & keystore, const CScript & scriptPubKey)
Definition at line 38 of file wallet_ismine.cpp.