Dash Core: src/wallet/walletdb.h File Reference
walletdb.h File Reference
#include "amount.h"
#include "wallet/db.h"
#include "hdchain.h"
#include "key.h"
#include <list>
#include <stdint.h>
#include <string>
#include <utility>
#include <vector>
Classes
class CKeyMetadata
class CWalletDB
Enumerations
enum DBErrors {
DB_LOAD_OK, DB_CORRUPT, DB_NONCRITICAL_ERROR, DB_TOO_NEW,
DB_LOAD_FAIL, DB_NEED_REWRITE
}
Functions
bool BackupWallet (const CWallet &wallet, const std::string &strDest)
void ThreadFlushWalletDB (const std::string &strFile)
bool AutoBackupWallet (CWallet *wallet, std::string strWalletFile, std::string &strBackupWarning, std::string &strBackupError)
Variables
static const bool DEFAULT_FLUSHWALLET = true
Enumeration Type Documentation
DBErrors
enum DBErrors
Error statuses for the wallet database
Enumerator
DB_LOAD_OK
DB_CORRUPT
DB_NONCRITICAL_ERROR
DB_TOO_NEW
DB_LOAD_FAIL
DB_NEED_REWRITE
Definition at line 34 of file walletdb.h.
Function Documentation
AutoBackupWallet()
bool AutoBackupWallet (CWallet * wallet, std::string strWalletFile, std::string & strBackupWarning, std::string & strBackupError)
Definition at line 946 of file walletdb.cpp.
Referenced by AppInit2(), CPrivateSendClient::CheckAutomaticBackup(), and OverviewPage::privateSendStatus().
BackupWallet()
bool BackupWallet (const CWallet & wallet, const std::string & strDest)
ThreadFlushWalletDB()
void ThreadFlushWalletDB (const std::string & strFile)
Variable Documentation
DEFAULT_FLUSHWALLET
const bool DEFAULT_FLUSHWALLET = true static
Definition at line 20 of file walletdb.h.
Referenced by HelpMessage(), and ThreadFlushWalletDB().