Dash Core: src/warnings.cpp File Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.16.0.1)
warnings.cpp File Reference
#include <sync.h>
#include <clientversion.h>
#include <util.h>
#include <warnings.h>
#include <hash.h>
Functions
void SetMiscWarning (const std::string &strWarning)
void SetfLargeWorkForkFound (bool flag)
bool GetfLargeWorkForkFound ()
void SetfLargeWorkInvalidChainFound (bool flag)
std::string GetWarnings (const std::string &strFor)
Format a string that describes several potential problems detected by the core.
Variables
CCriticalSection cs_warnings
std::string strMiscWarning
bool fLargeWorkForkFound = false
bool fLargeWorkInvalidChainFound = false
Function Documentation
GetfLargeWorkForkFound()
bool GetfLargeWorkForkFound ()
Definition at line 29 of file warnings.cpp.
References cs_warnings, fLargeWorkForkFound, and LOCK.
Referenced by CheckForkWarningConditions().
GetWarnings()
std::string GetWarnings (const std::string & strFor)
Format a string that describes several potential problems detected by the core.
strFor can have three values:
"rpc": get critical warnings, which should put the client in safe mode if non-empty
"statusbar": get all warnings
"gui": get all warnings, translated (where possible) for GUI This function only returns the highest priority warning of the set selected by strFor.
Definition at line 41 of file warnings.cpp.
References _(), cs_warnings, DEFAULT_TESTSAFEMODE, fLargeWorkForkFound, fLargeWorkInvalidChainFound, gArgs, ArgsManager::GetBoolArg(), LOCK, and strMiscWarning.
Referenced by getblockchaininfo(), getmininginfo(), getnetworkinfo(), ClientModel::getStatusBarWarnings(), BitcoinCore::handleRunawayException(), main(), and ObserveSafeMode().
SetfLargeWorkForkFound()
void SetfLargeWorkForkFound (bool flag)
Definition at line 23 of file warnings.cpp.
References cs_warnings, fLargeWorkForkFound, and LOCK.
Referenced by CheckForkWarningConditions().
SetfLargeWorkInvalidChainFound()
void SetfLargeWorkInvalidChainFound (bool flag)
Definition at line 35 of file warnings.cpp.
References cs_warnings, fLargeWorkInvalidChainFound, and LOCK.
Referenced by CheckForkWarningConditions().
SetMiscWarning()
void SetMiscWarning (const std::string & strWarning)
Definition at line 17 of file warnings.cpp.
References cs_warnings, LOCK, and strMiscWarning.
Referenced by AddTimeData(), and DoWarning().
Variable Documentation
cs_warnings
CCriticalSection cs_warnings
Definition at line 12 of file warnings.cpp.
Referenced by GetfLargeWorkForkFound(), GetWarnings(), SetfLargeWorkForkFound(), SetfLargeWorkInvalidChainFound(), and SetMiscWarning().
fLargeWorkForkFound
bool fLargeWorkForkFound = false
Definition at line 14 of file warnings.cpp.
Referenced by GetfLargeWorkForkFound(), GetWarnings(), and SetfLargeWorkForkFound().
fLargeWorkInvalidChainFound
bool fLargeWorkInvalidChainFound = false
Definition at line 15 of file warnings.cpp.
Referenced by GetWarnings(), and SetfLargeWorkInvalidChainFound().
strMiscWarning
std::string strMiscWarning
Definition at line 13 of file warnings.cpp.
Referenced by GetWarnings(), and SetMiscWarning().
Released under the MIT license