Dash Core: src/secp256k1/src/testrand.h File Reference
testrand.h File Reference
Functions
static SECP256K1_INLINE void secp256k1_rand_seed (const unsigned char *seed16)
Seed the pseudorandom number generator for testing.
static uint32_t secp256k1_rand32 (void)
Generate a pseudorandom number in the range [0..2**32-1].
static uint32_t secp256k1_rand_bits (int bits)
Generate a pseudorandom number in the range [0..2**bits-1].
static uint32_t secp256k1_rand_int (uint32_t range)
Generate a pseudorandom number in the range [0..range-1].
static void secp256k1_rand256 (unsigned char *b32)
Generate a pseudorandom 32-byte array.
static void secp256k1_rand256_test (unsigned char *b32)
Generate a pseudorandom 32-byte array with long sequences of zero and one bits.
static void secp256k1_rand_bytes_test (unsigned char *bytes, size_t len)
Generate pseudorandom bytes with long sequences of zero and one bits.
Function Documentation
secp256k1_rand256()
static void secp256k1_rand256 (unsigned char * b32) static
Generate a pseudorandom 32-byte array.
Referenced by main(), random_fe(), random_scalar_order(), test_ecmult_gen_blind(), and test_random_pubkeys().
secp256k1_rand256_test()
static void secp256k1_rand256_test (unsigned char * b32) static
Generate a pseudorandom 32-byte array with long sequences of zero and one bits.
Referenced by random_fe_test(), random_field_element_test(), random_scalar_order_test(), test_ecdsa_end_to_end(), test_schnorr_end_to_end(), test_schnorr_recovery(), test_schnorr_sign_verify(), and test_schnorr_threshold().
secp256k1_rand32()
static uint32_t secp256k1_rand32 (void) static
Generate a pseudorandom number in the range [0..2**32-1].
Referenced by test_rand_bits().
secp256k1_rand_bits()
static uint32_t secp256k1_rand_bits (int bits) static
Generate a pseudorandom number in the range [0..2**bits-1].
Bits must be 1 or more.
Referenced by damage_array(), main(), random_ber_signature(), random_group_element_test(), random_num_negate(), scalar_test(), test_ecdsa_end_to_end(), test_ecdsa_recovery_end_to_end(), test_ecdsa_sign_verify(), test_num_add_sub(), test_rand_bits(), test_random_pubkeys(), test_schnorr_end_to_end(), test_schnorr_sign_verify(), and test_schnorr_threshold().
secp256k1_rand_bytes_test()
static void secp256k1_rand_bytes_test (unsigned char * bytes, size_t len) static
Generate pseudorandom bytes with long sequences of zero and one bits.
Referenced by random_ber_signature().
secp256k1_rand_int()
static uint32_t secp256k1_rand_int (uint32_t range) static
Generate a pseudorandom number in the range [0..range-1].
Referenced by damage_array(), random_ber_signature(), random_field_element_magnitude(), run_field_inv_all_var(), run_hmac_sha256_tests(), run_sha256_tests(), scalar_test(), test_ecdsa_end_to_end(), test_ecdsa_recovery_end_to_end(), test_ge(), test_rand_int(), test_schnorr_end_to_end(), test_schnorr_sign_verify(), and test_schnorr_threshold().
secp256k1_rand_seed()
static SECP256K1_INLINE void secp256k1_rand_seed (const unsigned char * seed16) static
Seed the pseudorandom number generator for testing.
Referenced by main().