Dash Core: src/uint256.h File Reference
uint256.h File Reference
#include <assert.h>
#include <cstring>
#include <stdexcept>
#include <stdint.h>
#include <string>
#include <vector>
#include "crypto/common.h"
Classes
class base_blob< BITS >
Template base class for fixed-sized opaque blobs.
class uint160
160-bit opaque blob.
class uint256
256-bit opaque blob.
class uint512
512-bit unsigned big integer.
Functions
uint256 uint256S (const char *str)
uint256 uint256S (const std::string &str)
Function Documentation
uint256S() [1/2]
uint256 uint256S (const char * str) inline
Definition at line 148 of file uint256.h.
References base_blob< BITS >::SetHex().
Referenced by AppInit2(), CoinControlDialog::buttonToggleLockClicked(), CMainParams::CMainParams(), ConnectBlock(), CRegTestParams::CRegTestParams(), CTestNetParams::CTestNetParams(), getblock(), getblockheader(), getblockheaders(), CWallet::GetMasternodeOutpointAndKeys(), gettxout(), gettxoutproof(), invalidateblock(), CoinControlDialog::lockCoin(), lockunspent(), masternode(), MutateTxAddInput(), reconsiderblock(), base_uint< 256 >::SetHex(), CoinControlDialog::showMenu(), SignatureHash(), MasternodeList::StartAll(), CoinControlDialog::unlockCoin(), MasternodeList::updateMyNodeList(), and CoinControlDialog::viewItemChanged().
uint256S() [2/2]
uint256 uint256S (const std::string & str) inline
Definition at line 158 of file uint256.h.
References base_blob< BITS >::SetHex().