Dash Core: src/privatesend.h File Reference
privatesend.h File Reference
#include "chain.h"
#include "chainparams.h"
#include "primitives/transaction.h"
#include "pubkey.h"
#include "sync.h"
#include "tinyformat.h"
#include "timedata.h"
Classes
class CTxDSIn
Holds an mixing input.
class CDarkSendEntry
class CDarksendQueue
A currently inprogress mixing merge and denomination information.
class CDarksendBroadcastTx
Helper class to store mixing transaction (tx) information.
class CPrivateSendBase
class CPrivateSend
Enumerations
enum PoolMessage {
ERR_ALREADY_HAVE, ERR_DENOM, ERR_ENTRIES_FULL, ERR_EXISTING_TX,
ERR_FEES, ERR_INVALID_COLLATERAL, ERR_INVALID_INPUT, ERR_INVALID_SCRIPT,
ERR_INVALID_TX, ERR_MAXIMUM, ERR_MN_LIST, ERR_MODE,
ERR_NON_STANDARD_PUBKEY, ERR_NOT_A_MN, ERR_QUEUE_FULL, ERR_RECENT,
ERR_SESSION, ERR_MISSING_TX, ERR_VERSION, MSG_NOERR,
MSG_SUCCESS, MSG_ENTRIES_ADDED, MSG_POOL_MIN = ERR_ALREADY_HAVE, MSG_POOL_MAX = MSG_ENTRIES_ADDED
}
enum PoolState {
POOL_STATE_IDLE, POOL_STATE_QUEUE, POOL_STATE_ACCEPTING_ENTRIES, POOL_STATE_SIGNING,
POOL_STATE_ERROR, POOL_STATE_SUCCESS, POOL_STATE_MIN = POOL_STATE_IDLE, POOL_STATE_MAX = POOL_STATE_SUCCESS
}
enum PoolStatusUpdate { STATUS_REJECTED, STATUS_ACCEPTED }
Functions
void ThreadCheckPrivateSend (CConnman &connman)
Variables
static const int PRIVATESEND_AUTO_TIMEOUT_MIN = 5
static const int PRIVATESEND_AUTO_TIMEOUT_MAX = 15
static const int PRIVATESEND_QUEUE_TIMEOUT = 30
static const int PRIVATESEND_SIGNING_TIMEOUT = 15
static const int MIN_PRIVATESEND_PEER_PROTO_VERSION = 70208
minimum peer version accepted by mixing pool
static const CAmount PRIVATESEND_ENTRY_MAX_SIZE = 9
Enumeration Type Documentation
PoolMessage
enum PoolMessage
Enumerator
ERR_ALREADY_HAVE
ERR_DENOM
ERR_ENTRIES_FULL
ERR_EXISTING_TX
ERR_FEES
ERR_INVALID_COLLATERAL
ERR_INVALID_INPUT
ERR_INVALID_SCRIPT
ERR_INVALID_TX
ERR_MAXIMUM
ERR_MN_LIST
ERR_MODE
ERR_NON_STANDARD_PUBKEY
ERR_NOT_A_MN
ERR_QUEUE_FULL
ERR_RECENT
ERR_SESSION
ERR_MISSING_TX
ERR_VERSION
MSG_NOERR
MSG_SUCCESS
MSG_ENTRIES_ADDED
MSG_POOL_MIN
MSG_POOL_MAX
Definition at line 31 of file privatesend.h.
PoolState
enum PoolState
Enumerator
POOL_STATE_IDLE
POOL_STATE_QUEUE
POOL_STATE_ACCEPTING_ENTRIES
POOL_STATE_SIGNING
POOL_STATE_ERROR
POOL_STATE_SUCCESS
POOL_STATE_MIN
POOL_STATE_MAX
Definition at line 59 of file privatesend.h.
PoolStatusUpdate
enum PoolStatusUpdate
Enumerator
STATUS_REJECTED
STATUS_ACCEPTED
Definition at line 71 of file privatesend.h.
Function Documentation
ThreadCheckPrivateSend()
void ThreadCheckPrivateSend (CConnman & connman)
Definition at line 439 of file privatesend.cpp.
References activeMasternode, CMasternodeMan::Check(), CInstantSend::CheckAndRemove(), CMasternodeMan::CheckAndRemove(), CMasternodePayments::CheckAndRemove(), CMasternodeMan::DoFullVerificationStep(), CGovernanceManager::DoMaintenance(), fLiteMode, fMasterNode, governance, instantsend, CMasternodeSync::IsBlockchainSynced(), CActiveMasternode::ManageState(), MASTERNODE_MIN_MNP_SECONDS, masternodeSync, MilliSleep(), mnodeman, mnpayments, CMasternodeMan::ProcessMasternodeConnections(), CMasternodeSync::ProcessTick(), RenameThread(), and ShutdownRequested().
Referenced by AppInit2().
Variable Documentation
MIN_PRIVATESEND_PEER_PROTO_VERSION
const int MIN_PRIVATESEND_PEER_PROTO_VERSION = 70208 static
minimum peer version accepted by mixing pool
Definition at line 26 of file privatesend.h.
Referenced by CPrivateSendClient::DoAutomaticDenominating(), ClientModel::getMasternodeCountString(), CPrivateSendClient::JoinExistingQueue(), masternode(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), CDarksendQueue::Relay(), and CPrivateSendClient::StartNewQueue().
PRIVATESEND_AUTO_TIMEOUT_MAX
const int PRIVATESEND_AUTO_TIMEOUT_MAX = 15 static
Definition at line 21 of file privatesend.h.
Referenced by ThreadCheckPrivateSendClient().
PRIVATESEND_AUTO_TIMEOUT_MIN
const int PRIVATESEND_AUTO_TIMEOUT_MIN = 5 static
Definition at line 20 of file privatesend.h.
Referenced by ThreadCheckPrivateSendClient().
PRIVATESEND_ENTRY_MAX_SIZE
const CAmount PRIVATESEND_ENTRY_MAX_SIZE = 9 static
Definition at line 28 of file privatesend.h.
Referenced by CPrivateSend::GetMaxPoolAmount(), CPrivateSendClient::PrepareDenominate(), and CPrivateSendServer::ProcessMessage().
PRIVATESEND_QUEUE_TIMEOUT
const int PRIVATESEND_QUEUE_TIMEOUT = 30 static
Definition at line 22 of file privatesend.h.
Referenced by CPrivateSendServer::CheckTimeout(), CPrivateSendClient::CheckTimeout(), and CDarksendQueue::IsExpired().
PRIVATESEND_SIGNING_TIMEOUT
const int PRIVATESEND_SIGNING_TIMEOUT = 15 static
Definition at line 23 of file privatesend.h.
Referenced by CPrivateSendServer::CheckTimeout(), and CPrivateSendClient::CheckTimeout().