Dash Core: CMasternodeBroadcast Class Reference
CMasternodeBroadcast Class Reference
#include <masternode.h>
Public Member Functions
CMasternodeBroadcast ()
CMasternodeBroadcast (const CMasternode &mn)
CMasternodeBroadcast (CService addrNew, COutPoint outpointNew, CPubKey pubKeyCollateralAddressNew, CPubKey pubKeyMasternodeNew, int nProtocolVersionIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
uint256 GetHash () const
bool SimpleCheck (int &nDos)
bool Update (CMasternode *pmn, int &nDos, CConnman &connman)
bool CheckOutpoint (int &nDos)
bool Sign (const CKey &keyCollateralAddress)
bool CheckSignature (int &nDos)
void Relay (CConnman &connman)
Public Member Functions inherited from CMasternode
CMasternode ()
CMasternode (const CMasternode &other)
CMasternode (const CMasternodeBroadcast &mnb)
CMasternode (CService addrNew, COutPoint outpointNew, CPubKey pubKeyCollateralAddressNew, CPubKey pubKeyMasternodeNew, int nProtocolVersionIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
arith_uint256 CalculateScore (const uint256 &blockHash)
bool UpdateFromNewBroadcast (CMasternodeBroadcast &mnb, CConnman &connman)
void Check (bool fForce=false)
bool IsBroadcastedWithin (int nSeconds)
bool IsPingedWithin (int nSeconds, int64_t nTimeToCheckAt=-1)
bool IsEnabled ()
bool IsPreEnabled ()
bool IsPoSeBanned ()
bool IsPoSeVerified ()
bool IsExpired ()
bool IsOutpointSpent ()
bool IsUpdateRequired ()
bool IsWatchdogExpired ()
bool IsNewStartRequired ()
bool IsValidForPayment ()
bool IsInputAssociatedWithPubkey ()
Is the input associated with collateral public key? (and there is 1000 DASH - checking if valid masternode)
bool IsValidNetAddr ()
void IncreasePoSeBanScore ()
void DecreasePoSeBanScore ()
void PoSeBan ()
masternode_info_t GetInfo ()
std::string GetStateString () const
std::string GetStatus () const
int GetLastPaidTime ()
int GetLastPaidBlock ()
void UpdateLastPaid (const CBlockIndex *pindex, int nMaxBlocksToScanBack)
void AddGovernanceVote (uint256 nGovernanceObjectHash)
void FlagGovernanceItemsAsDirty ()
FLAG GOVERNANCE ITEMS AS DIRTY.
void RemoveGovernanceObject (uint256 nGovernanceObjectHash)
void UpdateWatchdogVoteTime (uint64_t nVoteTime=0)
CMasternode & operator= (CMasternode const &from)
Public Member Functions inherited from masternode_info_t
masternode_info_t ()=default
masternode_info_t (masternode_info_t const &)=default
masternode_info_t (int activeState, int protoVer, int64_t sTime)
masternode_info_t (int activeState, int protoVer, int64_t sTime, COutPoint const &outpoint, CService const &addr, CPubKey const &pkCollAddr, CPubKey const &pkMN, int64_t tWatchdogV=0)
Static Public Member Functions
static bool Create (const COutPoint &outpoint, const CService &service, const CKey &keyCollateralAddressNew, const CPubKey &pubKeyCollateralAddressNew, const CKey &keyMasternodeNew, const CPubKey &pubKeyMasternodeNew, std::string &strErrorRet, CMasternodeBroadcast &mnbRet)
Create Masternode broadcast, needs to be relayed manually after that.
static bool Create (std::string strService, std::string strKey, std::string strTxHash, std::string strOutputIndex, std::string &strErrorRet, CMasternodeBroadcast &mnbRet, bool fOffline=false)
Static Public Member Functions inherited from CMasternode
static CollateralStatus CheckCollateral (const COutPoint &outpoint)
static CollateralStatus CheckCollateral (const COutPoint &outpoint, int &nHeightRet)
static bool IsValidStateForAutoStart (int nActiveStateIn)
static bool IsValidNetAddr (CService addrIn)
static std::string StateToString (int nStateIn)
Public Attributes
bool fRecovery
ADD_SERIALIZE_METHODS
Public Attributes inherited from CMasternode
CMasternodePing lastPing {}
std::vector< unsigned char > vchSig {}
uint256 nCollateralMinConfBlockHash {}
int nBlockLastPaid {}
int nPoSeBanScore {}
int nPoSeBanHeight {}
bool fAllowMixingTx {}
bool fUnitTest = false
std::map< uint256, int > mapGovernanceObjectsVotedOn
ADD_SERIALIZE_METHODS
Public Attributes inherited from masternode_info_t
int nActiveState = 0
int nProtocolVersion = 0
int64_t sigTime = 0
CTxIn vin {}
CService addr {}
CPubKey pubKeyCollateralAddress {}
CPubKey pubKeyMasternode {}
int64_t nTimeLastWatchdogVote = 0
int64_t nLastDsq = 0
int64_t nTimeLastChecked = 0
int64_t nTimeLastPaid = 0
int64_t nTimeLastPing = 0
bool fInfoValid = false
Additional Inherited Members
Public Types inherited from CMasternode
enum state {
MASTERNODE_PRE_ENABLED, MASTERNODE_ENABLED, MASTERNODE_EXPIRED, MASTERNODE_OUTPOINT_SPENT,
MASTERNODE_UPDATE_REQUIRED, MASTERNODE_WATCHDOG_EXPIRED, MASTERNODE_NEW_START_REQUIRED, MASTERNODE_POSE_BAN
}
enum CollateralStatus { COLLATERAL_OK, COLLATERAL_UTXO_NOT_FOUND, COLLATERAL_INVALID_AMOUNT }
Detailed Description
Definition at line 313 of file masternode.h.
Constructor & Destructor Documentation
CMasternodeBroadcast() [1/3]
CMasternodeBroadcast::CMasternodeBroadcast () inline
Definition at line 319 of file masternode.h.
CMasternodeBroadcast() [2/3]
CMasternodeBroadcast::CMasternodeBroadcast (const CMasternode & mn) inline
Definition at line 320 of file masternode.h.
CMasternodeBroadcast() [3/3]
CMasternodeBroadcast::CMasternodeBroadcast (CService addrNew, COutPoint outpointNew, CPubKey pubKeyCollateralAddressNew, CPubKey pubKeyMasternodeNew, int nProtocolVersionIn) inline
Definition at line 321 of file masternode.h.
Member Function Documentation
CheckOutpoint()
bool CMasternodeBroadcast::CheckOutpoint (int & nDos)
Definition at line 533 of file masternode.cpp.
References activeMasternode, masternode_info_t::addr, chainActive, CMasternode::CheckCollateral(), CheckSignature(), CMasternode::COLLATERAL_INVALID_AMOUNT, CMasternode::COLLATERAL_UTXO_NOT_FOUND, cs_main, fMasterNode, CBlockIndex::GetBlockTime(), CChainParams::GetConsensus(), GetHash(), GetTransaction(), COutPoint::hash, CChain::Height(), CMasternode::IsInputAssociatedWithPubkey(), LOCK, LogPrint(), LogPrintf, mapBlockIndex, CMasternodeMan::mapSeenMasternodeBroadcast, mnodeman, CMasternode::nCollateralMinConfBlockHash, CBlockIndex::nHeight, Consensus::Params::nMasternodeMinimumConfirmations, CActiveMasternode::outpoint, Params(), CTxIn::prevout, CActiveMasternode::pubKeyMasternode, masternode_info_t::pubKeyMasternode, masternode_info_t::sigTime, CService::ToString(), COutPoint::ToStringShort(), TRY_LOCK, and masternode_info_t::vin.
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList().
CheckSignature()
bool CMasternodeBroadcast::CheckSignature (int & nDos)
Definition at line 634 of file masternode.cpp.
References masternode_info_t::addr, EncodeBase64(), CPubKey::GetID(), LogPrint(), LogPrintf, masternode_info_t::nProtocolVersion, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, masternode_info_t::sigTime, base_blob< BITS >::ToString(), CService::ToString(), CMasternode::vchSig, and CMessageSigner::VerifyMessage().
Referenced by CheckOutpoint(), masternodebroadcast(), and Update().
Create() [1/2]
static bool CMasternodeBroadcast::Create (const COutPoint & outpoint, const CService & service, const CKey & keyCollateralAddressNew, const CPubKey & pubKeyCollateralAddressNew, const CKey & keyMasternodeNew, const CPubKey & pubKeyMasternodeNew, std::string & strErrorRet, CMasternodeBroadcast & mnbRet) static
Create Masternode broadcast, needs to be relayed manually after that.
Referenced by masternode(), masternodebroadcast(), MasternodeList::StartAlias(), and MasternodeList::StartAll().
Create() [2/2]
static bool CMasternodeBroadcast::Create (std::string strService, std::string strKey, std::string strTxHash, std::string strOutputIndex, std::string & strErrorRet, CMasternodeBroadcast & mnbRet, bool fOffline = false) static
GetHash()
uint256 CMasternodeBroadcast::GetHash () const inline
Definition at line 338 of file masternode.h.
References CHashWriter::GetHash(), PROTOCOL_VERSION, masternode_info_t::pubKeyCollateralAddress, SER_GETHASH, masternode_info_t::sigTime, and masternode_info_t::vin.
Referenced by CMasternodeMan::CheckAndRemove(), CMasternodePing::CheckAndUpdate(), CMasternodeMan::CheckMnbAndUpdateMasternodeList(), CheckOutpoint(), masternodebroadcast(), Relay(), CMasternodeMan::SetMasternodeLastPing(), and CMasternodeMan::UpdateMasternodeList().
Relay()
void CMasternodeBroadcast::Relay (CConnman & connman)
Definition at line 655 of file masternode.cpp.
References GetHash(), CMasternodeSync::IsSynced(), LogPrint(), masternodeSync, MSG_MASTERNODE_ANNOUNCE, and CConnman::RelayInv().
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList(), masternode(), masternodebroadcast(), MasternodeList::StartAlias(), MasternodeList::StartAll(), and Update().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodeBroadcast::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 327 of file masternode.h.
References masternode_info_t::addr, CMasternode::lastPing, masternode_info_t::nProtocolVersion, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, READWRITE, masternode_info_t::sigTime, CMasternode::vchSig, and masternode_info_t::vin.
Sign()
bool CMasternodeBroadcast::Sign (const CKey & keyCollateralAddress)
Definition at line 610 of file masternode.cpp.
References masternode_info_t::addr, GetAdjustedTime(), CPubKey::GetID(), LogPrintf, masternode_info_t::nProtocolVersion, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, CMessageSigner::SignMessage(), masternode_info_t::sigTime, base_blob< BITS >::ToString(), CService::ToString(), CMasternode::vchSig, and CMessageSigner::VerifyMessage().
SimpleCheck()
bool CMasternodeBroadcast::SimpleCheck (int & nDos)
Definition at line 420 of file masternode.cpp.
References masternode_info_t::addr, prevector< N, T, Size, Diff >::empty(), GetAdjustedTime(), CChainParams::GetDefaultPort(), CPubKey::GetID(), CMasternodePayments::GetMinMasternodePaymentsProto(), CService::GetPort(), GetScriptForDestination(), CMasternode::IsValidNetAddr(), CMasternode::lastPing, LogPrintf, CBaseChainParams::MAIN, CMasternode::MASTERNODE_EXPIRED, mnpayments, masternode_info_t::nActiveState, masternode_info_t::nProtocolVersion, Params(), CTxIn::prevout, masternode_info_t::pubKeyCollateralAddress, masternode_info_t::pubKeyMasternode, CTxIn::scriptSig, masternode_info_t::sigTime, CMasternodePing::SimpleCheck(), prevector< N, T, Size, Diff >::size(), CTxIn::ToString(), CService::ToString(), COutPoint::ToStringShort(), and masternode_info_t::vin.
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList().
Update()
bool CMasternodeBroadcast::Update (CMasternode * pmn, int & nDos, CConnman & connman)
Definition at line 481 of file masternode.cpp.
References activeMasternode, masternode_info_t::addr, CMasternodeSync::BumpAssetLastTime(), CMasternode::Check(), CheckSignature(), fMasterNode, fRecovery, CMasternode::IsBroadcastedWithin(), CMasternode::IsPoSeBanned(), LogPrintf, MASTERNODE_MIN_MNB_SECONDS, masternodeSync, CTxIn::prevout, masternode_info_t::pubKeyCollateralAddress, CActiveMasternode::pubKeyMasternode, masternode_info_t::pubKeyMasternode, Relay(), masternode_info_t::sigTime, CService::ToString(), COutPoint::ToStringShort(), CMasternode::UpdateFromNewBroadcast(), and masternode_info_t::vin.
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList().
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodeBroadcast::ADD_SERIALIZE_METHODS
Definition at line 324 of file masternode.h.
fRecovery
bool CMasternodeBroadcast::fRecovery
Definition at line 317 of file masternode.h.
Referenced by CMasternodeMan::CheckMnbAndUpdateMasternodeList(), Update(), and CMasternode::UpdateFromNewBroadcast().
The documentation for this class was generated from the following files:
src/masternode.h
src/masternode.cpp