Dash Core: src/pow.cpp File Reference
pow.cpp File Reference
#include "pow.h"
#include "arith_uint256.h"
#include "chain.h"
#include "chainparams.h"
#include "primitives/block.h"
#include "uint256.h"
#include "util.h"
#include <math.h>
Functions
unsigned static int KimotoGravityWell (const CBlockIndex *pindexLast, const Consensus::Params &params)
unsigned static int DarkGravityWave (const CBlockIndex *pindexLast, const Consensus::Params &params)
unsigned int GetNextWorkRequiredBTC (const CBlockIndex *pindexLast, const CBlockHeader *pblock, const Consensus::Params &params)
unsigned int GetNextWorkRequired (const CBlockIndex *pindexLast, const CBlockHeader *pblock, const Consensus::Params &params)
unsigned int CalculateNextWorkRequired (const CBlockIndex *pindexLast, int64_t nFirstBlockTime, const Consensus::Params &params)
bool CheckProofOfWork (uint256 hash, unsigned int nBits, const Consensus::Params &params)
Check whether a block hash satisfies the proof-of-work requirement specified by nBits.
arith_uint256 GetBlockProof (const CBlockIndex &block)
int64_t GetBlockProofEquivalentTime (const CBlockIndex &to, const CBlockIndex &from, const CBlockIndex &tip, const Consensus::Params &params)
Return the time it would take to redo the work difference between from and to, assuming the current hashrate corresponds to the difficulty at tip, in seconds.
Function Documentation
CalculateNextWorkRequired()
unsigned int CalculateNextWorkRequired (const CBlockIndex * pindexLast, int64_t nFirstBlockTime, const Consensus::Params & params)
debug print
Definition at line 187 of file pow.cpp.
References Consensus::Params::fPowNoRetargeting, CBlockIndex::GetBlockTime(), arith_uint256::GetCompact(), LogPrintf, CBlockIndex::nBits, Consensus::Params::nPowTargetTimespan, Consensus::Params::powLimit, arith_uint256::SetCompact(), base_uint< BITS >::ToString(), and UintToArith256().
Referenced by GetNextWorkRequiredBTC().
CheckProofOfWork()
bool CheckProofOfWork (uint256 hash, unsigned int nBits, const Consensus::Params & params)
Check whether a block hash satisfies the proof-of-work requirement specified by nBits.
Definition at line 221 of file pow.cpp.
References error(), Consensus::Params::powLimit, arith_uint256::SetCompact(), and UintToArith256().
Referenced by CheckBlockHeader(), generate(), CBlockTreeDB::LoadBlockIndexGuts(), and ReadBlockFromDisk().
DarkGravityWave()
unsigned static int DarkGravityWave (const CBlockIndex * pindexLast, const Consensus::Params & params) static
Definition at line 83 of file pow.cpp.
References CBlockIndex::GetBlockTime(), arith_uint256::GetCompact(), CBlockIndex::nBits, CBlockIndex::nHeight, Consensus::Params::nPowTargetSpacing, Consensus::Params::powLimit, CBlockIndex::pprev, arith_uint256::SetCompact(), and UintToArith256().
Referenced by GetNextWorkRequired().
GetBlockProof()
arith_uint256 GetBlockProof (const CBlockIndex & block)
Definition at line 240 of file pow.cpp.
References CBlockIndex::nBits, and arith_uint256::SetCompact().
Referenced by AddToBlockIndex(), CheckForkWarningConditions(), CheckForkWarningConditionsOnNewFork(), GetBlockProofEquivalentTime(), and LoadBlockIndexDB().
GetBlockProofEquivalentTime()
int64_t GetBlockProofEquivalentTime (const CBlockIndex & to, const CBlockIndex & from, const CBlockIndex & tip, const Consensus::Params &)
Return the time it would take to redo the work difference between from and to, assuming the current hashrate corresponds to the difficulty at tip, in seconds.
Definition at line 255 of file pow.cpp.
References base_uint< BITS >::bits(), GetBlockProof(), base_uint< BITS >::GetLow64(), CBlockIndex::nChainWork, and Consensus::Params::nPowTargetSpacing.
Referenced by ConnectBlock(), and ProcessGetData().
GetNextWorkRequired()
unsigned int GetNextWorkRequired (const CBlockIndex * pindexLast, const CBlockHeader * pblock, const Consensus::Params & params)
Definition at line 172 of file pow.cpp.
References DarkGravityWave(), GetNextWorkRequiredBTC(), KimotoGravityWell(), CBlockIndex::nHeight, Consensus::Params::nPowDGWHeight, and Consensus::Params::nPowKGWHeight.
Referenced by ContextualCheckBlockHeader(), CreateNewBlock(), and UpdateTime().
GetNextWorkRequiredBTC()
unsigned int GetNextWorkRequiredBTC (const CBlockIndex * pindexLast, const CBlockHeader * pblock, const Consensus::Params & params)
Definition at line 133 of file pow.cpp.
References CalculateNextWorkRequired(), Consensus::Params::DifficultyAdjustmentInterval(), Consensus::Params::fPowAllowMinDifficultyBlocks, CBlockIndex::GetAncestor(), CBlockHeader::GetBlockTime(), CBlockIndex::GetBlockTime(), arith_uint256::GetCompact(), CBlockIndex::nBits, CBlockIndex::nHeight, Consensus::Params::nPowTargetSpacing, Consensus::Params::powLimit, CBlockIndex::pprev, and UintToArith256().
Referenced by GetNextWorkRequired().
KimotoGravityWell()
unsigned static int KimotoGravityWell (const CBlockIndex * pindexLast, const Consensus::Params & params) static
Definition at line 17 of file pow.cpp.
References CBlockIndex::GetBlockTime(), arith_uint256::GetCompact(), CBlockIndex::nBits, CBlockIndex::nHeight, Consensus::Params::nPowTargetSpacing, Consensus::Params::nPowTargetTimespan, Consensus::Params::powLimit, CBlockIndex::pprev, arith_uint256::SetCompact(), and UintToArith256().
Referenced by GetNextWorkRequired().