Dash Core: src/compat/sanity.h File Reference
sanity.h File Reference
Functions
bool glibc_sanity_test ()
bool glibcxx_sanity_test ()
Function Documentation
glibc_sanity_test()
bool glibc_sanity_test ()
Definition at line 61 of file glibc_sanity.cpp.
Referenced by InitSanityCheck().
glibcxx_sanity_test()
bool glibcxx_sanity_test ()
Definition at line 58 of file glibcxx_sanity.cpp.
References sanity_test_range_fmt().
Referenced by InitSanityCheck().