var searchData=
[
  ['valueholder',['ValueHolder',['../struct_c_d_b_transaction_1_1_value_holder.html',1,'CDBTransaction']]],
  ['valueholderimpl',['ValueHolderImpl',['../struct_c_d_b_transaction_1_1_value_holder_impl.html',1,'CDBTransaction']]],
  ['values_5fdata_5ft',['values_data_t',['../structimmer_1_1detail_1_1hamts_1_1node_1_1values__data__t.html',1,'immer::detail::hamts::node']]],
  ['vbdeploymentinfo',['VBDeploymentInfo',['../struct_v_b_deployment_info.html',1,'']]],
  ['vector',['vector',['../classimmer_1_1vector.html',1,'immer']]],
  ['vector_5ftransient',['vector_transient',['../classimmer_1_1vector__transient.html',1,'immer']]],
  ['vectoraggregator',['VectorAggregator',['../struct_vector_aggregator.html',1,'']]],
  ['versionbitscache',['VersionBitsCache',['../struct_version_bits_cache.html',1,'']]],
  ['visitor_5fbase',['visitor_base',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20array_5ffor_5fvisitor_3c_20t_20_3e_20_3e',['visitor_base&lt; array_for_visitor&lt; T &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fboth_5fmut_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_both_mut_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fboth_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_both_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fleft_5fmut_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_left_mut_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fleft_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_left_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fmerger_5fmut_5fvisitor_20_3e',['visitor_base&lt; concat_merger_mut_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fmerger_5fvisitor_20_3e',['visitor_base&lt; concat_merger_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5frebalance_5fplan_5ffill_5fvisitor_20_3e',['visitor_base&lt; concat_rebalance_plan_fill_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fright_5fmut_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_right_mut_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5fright_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_right_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5ftrees_5fleft_5fmut_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_trees_left_mut_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5ftrees_5fleft_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_trees_left_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5ftrees_5fright_5fmut_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_trees_right_mut_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20concat_5ftrees_5fright_5fvisitor_3c_20node_20_3e_20_3e',['visitor_base&lt; concat_trees_right_visitor&lt; Node &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20dec_5fleft_5fvisitor_20_3e',['visitor_base&lt; dec_left_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20dec_5fright_5fvisitor_20_3e',['visitor_base&lt; dec_right_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20dec_5fvisitor_20_3e',['visitor_base&lt; dec_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20equals_5fvisitor_20_3e',['visitor_base&lt; equals_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fi_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_i_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fleft_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_left_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fp_5fi_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_p_i_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fp_5fleft_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_p_left_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fp_5fright_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_p_right_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fp_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_p_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fright_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_right_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20for_5feach_5fchunk_5fvisitor_20_3e',['visitor_base&lt; for_each_chunk_visitor &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20get_5fmut_5fvisitor_3c_20nodet_20_3e_20_3e',['visitor_base&lt; get_mut_visitor&lt; NodeT &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20get_5fvisitor_3c_20t_20_3e_20_3e',['visitor_base&lt; get_visitor&lt; T &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20push_5ftail_5fmut_5fvisitor_3c_20nodet_2c_20mutating_20_3e_20_3e',['visitor_base&lt; push_tail_mut_visitor&lt; NodeT, Mutating &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20push_5ftail_5fvisitor_3c_20nodet_20_3e_20_3e',['visitor_base&lt; push_tail_visitor&lt; NodeT &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20region_5ffor_5fvisitor_3c_20t_20_3e_20_3e',['visitor_base&lt; region_for_visitor&lt; T &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20rrb_20_3e',['visitor_base&lt; rrb &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20slice_5fleft_5fmut_5fvisitor_3c_20nodet_2c_20collapse_2c_20mutating_20_3e_20_3e',['visitor_base&lt; slice_left_mut_visitor&lt; NodeT, Collapse, Mutating &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20slice_5fleft_5fvisitor_3c_20nodet_2c_20collapse_20_3e_20_3e',['visitor_base&lt; slice_left_visitor&lt; NodeT, Collapse &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20slice_5fright_5fmut_5fvisitor_3c_20nodet_2c_20collapse_2c_20mutating_20_3e_20_3e',['visitor_base&lt; slice_right_mut_visitor&lt; NodeT, Collapse, Mutating &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20slice_5fright_5fvisitor_3c_20nodet_2c_20collapse_20_3e_20_3e',['visitor_base&lt; slice_right_visitor&lt; NodeT, Collapse &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20this_5faux_5ft_20_3e',['visitor_base&lt; this_aux_t &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['visitor_5fbase_3c_20update_5fvisitor_3c_20nodet_20_3e_20_3e',['visitor_base&lt; update_visitor&lt; NodeT &gt; &gt;',['../structimmer_1_1detail_1_1rbts_1_1visitor__base.html',1,'immer::detail::rbts']]],
  ['vote_5finstance_5ft',['vote_instance_t',['../structvote__instance__t.html',1,'']]],
  ['vote_5frec_5ft',['vote_rec_t',['../structvote__rec__t.html',1,'']]]
];
