var searchData=
[
  ['rbtree',['rbtree',['../structimmer_1_1detail_1_1rbts_1_1rbtree.html',1,'immer::detail::rbts']]],
  ['rbtree_5fiterator',['rbtree_iterator',['../structimmer_1_1detail_1_1rbts_1_1rbtree__iterator.html',1,'immer::detail::rbts']]],
  ['rebind',['rebind',['../structzero__after__free__allocator_1_1rebind.html',1,'zero_after_free_allocator&lt; T &gt;::rebind&lt; _Other &gt;'],['../structsecure__allocator_1_1rebind.html',1,'secure_allocator&lt; T &gt;::rebind&lt; _Other &gt;']]],
  ['receivecoinsdialog',['ReceiveCoinsDialog',['../class_receive_coins_dialog.html',1,'']]],
  ['receiverequestdialog',['ReceiveRequestDialog',['../class_receive_request_dialog.html',1,'']]],
  ['recentrequestentry',['RecentRequestEntry',['../class_recent_request_entry.html',1,'']]],
  ['recentrequestentrylessthan',['RecentRequestEntryLessThan',['../class_recent_request_entry_less_than.html',1,'']]],
  ['recentrequeststablemodel',['RecentRequestsTableModel',['../class_recent_requests_table_model.html',1,'']]],
  ['ref',['ref',['../structimmer_1_1detail_1_1dvektor_1_1ref.html',1,'immer::detail::dvektor']]],
  ['ref_3c_20t_2c_20b_2c_20memorypolicy_20_3e',['ref&lt; T, B, MemoryPolicy &gt;',['../structimmer_1_1detail_1_1dvektor_1_1ref.html',1,'immer::detail::dvektor']]],
  ['ref_5fcount_5fbase',['ref_count_base',['../structimmer_1_1detail_1_1ref__count__base.html',1,'immer::detail']]],
  ['refcount_5fatom_5fimpl',['refcount_atom_impl',['../structimmer_1_1detail_1_1refcount__atom__impl.html',1,'immer::detail']]],
  ['refcount_5fpolicy',['refcount_policy',['../structimmer_1_1refcount__policy.html',1,'immer']]],
  ['reference_5fproxy',['reference_proxy',['../classimmer_1_1detail_1_1iterator__facade_1_1reference__proxy.html',1,'immer::detail::iterator_facade']]],
  ['region_5ffor_5fvisitor',['region_for_visitor',['../structimmer_1_1detail_1_1rbts_1_1region__for__visitor.html',1,'immer::detail::rbts']]],
  ['regular_5fdescent_5fpos',['regular_descent_pos',['../structimmer_1_1detail_1_1rbts_1_1regular__descent__pos.html',1,'immer::detail::rbts']]],
  ['regular_5fdescent_5fpos_3c_20nodet_2c_20bl_2c_20b_2c_20bl_20_3e',['regular_descent_pos&lt; NodeT, BL, B, BL &gt;',['../structimmer_1_1detail_1_1rbts_1_1regular__descent__pos_3_01_node_t_00_01_b_l_00_01_b_00_01_b_l_01_4.html',1,'immer::detail::rbts']]],
  ['regular_5fpos',['regular_pos',['../structimmer_1_1detail_1_1rbts_1_1regular__pos.html',1,'immer::detail::rbts']]],
  ['regular_5fsub_5fpos',['regular_sub_pos',['../structimmer_1_1detail_1_1rbts_1_1regular__sub__pos.html',1,'immer::detail::rbts']]],
  ['relaxed_5fdata_5ft',['relaxed_data_t',['../structimmer_1_1detail_1_1rbts_1_1node_1_1relaxed__data__t.html',1,'immer::detail::rbts::node']]],
  ['relaxed_5fdescent_5fpos',['relaxed_descent_pos',['../structimmer_1_1detail_1_1rbts_1_1relaxed__descent__pos.html',1,'immer::detail::rbts']]],
  ['relaxed_5fdescent_5fpos_3c_20nodet_2c_20bl_2c_20b_2c_20bl_20_3e',['relaxed_descent_pos&lt; NodeT, BL, B, BL &gt;',['../structimmer_1_1detail_1_1rbts_1_1relaxed__descent__pos_3_01_node_t_00_01_b_l_00_01_b_00_01_b_l_01_4.html',1,'immer::detail::rbts']]],
  ['relaxed_5fpos',['relaxed_pos',['../structimmer_1_1detail_1_1rbts_1_1relaxed__pos.html',1,'immer::detail::rbts']]],
  ['reverse_5fiterator',['reverse_iterator',['../classprevector_1_1reverse__iterator.html',1,'prevector']]],
  ['reverse_5flock',['reverse_lock',['../classreverse__lock.html',1,'']]],
  ['reverse_5frange',['reverse_range',['../classreverse__range.html',1,'']]],
  ['rpcconsole',['RPCConsole',['../class_r_p_c_console.html',1,'']]],
  ['rpcexecutor',['RPCExecutor',['../class_r_p_c_executor.html',1,'']]],
  ['rpctimerbase',['RPCTimerBase',['../class_r_p_c_timer_base.html',1,'']]],
  ['rpctimerinterface',['RPCTimerInterface',['../class_r_p_c_timer_interface.html',1,'']]],
  ['rrb',['rrb',['../structimmer_1_1detail_1_1rbts_1_1equals__visitor_1_1rrb.html',1,'immer::detail::rbts::equals_visitor']]],
  ['rrbtree',['rrbtree',['../structimmer_1_1detail_1_1rbts_1_1rrbtree.html',1,'immer::detail::rbts']]],
  ['rrbtree_5fiterator',['rrbtree_iterator',['../structimmer_1_1detail_1_1rbts_1_1rrbtree__iterator.html',1,'immer::detail::rbts']]]
];
