Dash Core: src/secp256k1/src/bench_schnorr_verify.c File Reference
bench_schnorr_verify.c File Reference
#include <stdio.h>
#include <string.h>
#include "include/secp256k1.h"
#include "include/secp256k1_schnorr.h"
#include "util.h"
#include "bench.h"
Classes
struct benchmark_schnorr_sig_t
struct benchmark_schnorr_verify_t
Functions
static void benchmark_schnorr_init (void *arg)
static void benchmark_schnorr_verify (void *arg)
int main (void)
Function Documentation
benchmark_schnorr_init()
static void benchmark_schnorr_init (void * arg) static
Definition at line 29 of file bench_schnorr_verify.c.
References CHECK, benchmark_schnorr_verify_t::ctx, benchmark_schnorr_sig_t::key, benchmark_schnorr_verify_t::msg, benchmark_schnorr_verify_t::numsigs, benchmark_schnorr_sig_t::pubkey, benchmark_schnorr_sig_t::pubkeylen, SECP256K1_EC_COMPRESSED, secp256k1_ec_pubkey_create(), secp256k1_ec_pubkey_serialize(), secp256k1_schnorr_sign(), benchmark_schnorr_sig_t::sig, and benchmark_schnorr_verify_t::sigs.
Referenced by main().
benchmark_schnorr_verify()
static void benchmark_schnorr_verify (void * arg) static
Definition at line 48 of file bench_schnorr_verify.c.
References CHECK, benchmark_schnorr_verify_t::ctx, benchmark_schnorr_verify_t::msg, benchmark_schnorr_verify_t::numsigs, benchmark_schnorr_sig_t::pubkey, benchmark_schnorr_sig_t::pubkeylen, secp256k1_ec_pubkey_parse(), secp256k1_schnorr_verify(), benchmark_schnorr_sig_t::sig, and benchmark_schnorr_verify_t::sigs.
Referenced by main().
main()
int main (void)
Definition at line 63 of file bench_schnorr_verify.c.
References benchmark_schnorr_init(), benchmark_schnorr_verify(), benchmark_schnorr_verify_t::ctx, benchmark_schnorr_verify_t::numsigs, run_benchmark(), secp256k1_context_create(), secp256k1_context_destroy(), SECP256K1_CONTEXT_SIGN, and SECP256K1_CONTEXT_VERIFY.