Dash Core: CDarksendQueue Class Reference
CDarksendQueue Class Reference
A currently inprogress mixing merge and denomination information.
#include <privatesend.h>
Public Member Functions
CDarksendQueue ()
CDarksendQueue (int nDenom, COutPoint outpoint, int64_t nTime, bool fReady)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
bool Sign ()
Sign this mixing transaction.
bool CheckSignature (const CPubKey &pubKeyMasternode)
Check if we have a valid Masternode address.
bool Relay (CConnman &connman)
bool IsExpired ()
Is this queue expired?
std::string ToString ()
Public Attributes
int nDenom
CTxIn vin
int64_t nTime
bool fReady
std::vector< unsigned char > vchSig
bool fTried
ADD_SERIALIZE_METHODS
Friends
bool operator== (const CDarksendQueue &a, const CDarksendQueue &b)
Detailed Description
A currently inprogress mixing merge and denomination information.
Definition at line 141 of file privatesend.h.
Constructor & Destructor Documentation
CDarksendQueue() [1/2]
CDarksendQueue::CDarksendQueue () inline
Definition at line 152 of file privatesend.h.
CDarksendQueue() [2/2]
CDarksendQueue::CDarksendQueue (int nDenom, COutPoint outpoint, int64_t nTime, bool fReady) inline
Definition at line 161 of file privatesend.h.
Member Function Documentation
CheckSignature()
bool CDarksendQueue::CheckSignature (const CPubKey & pubKeyMasternode)
Check if we have a valid Masternode address.
Definition at line 52 of file privatesend.cpp.
References fReady, LogPrintf, nDenom, nTime, CTxIn::ToString(), ToString(), vchSig, CMessageSigner::VerifyMessage(), and vin.
Referenced by Sign().
IsExpired()
bool CDarksendQueue::IsExpired () inline
Is this queue expired?
Definition at line 195 of file privatesend.h.
References GetAdjustedTime(), nTime, and PRIVATESEND_QUEUE_TIMEOUT.
Referenced by CPrivateSendClient::JoinExistingQueue().
Relay()
bool CDarksendQueue::Relay (CConnman & connman)
Definition at line 65 of file privatesend.cpp.
References CConnman::CopyNodeVector(), NetMsgType::DSQUEUE, MIN_PRIVATESEND_PEER_PROTO_VERSION, CNode::nVersion, CConnman::PushMessage(), and CConnman::ReleaseNodeVector().
Referenced by CPrivateSendServer::CheckForCompleteQueue(), and CPrivateSendServer::CreateNewSession().
SerializationOp()
template<typename Stream , typename Operation > void CDarksendQueue::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 173 of file privatesend.h.
References fReady, nDenom, nTime, READWRITE, vchSig, and vin.
Sign()
bool CDarksendQueue::Sign ()
Sign this mixing transaction.
Returns
true if all conditions are met: 1) we have an active Masternode, 2) we have a valid Masternode private key, 3) we signed the message successfully, and 4) we verified the message successfully
Definition at line 38 of file privatesend.cpp.
References activeMasternode, CheckSignature(), fMasterNode, fReady, CActiveMasternode::keyMasternode, LogPrintf, nDenom, nTime, CActiveMasternode::pubKeyMasternode, CMessageSigner::SignMessage(), CTxIn::ToString(), ToString(), vchSig, and vin.
Referenced by CPrivateSendServer::CheckForCompleteQueue(), and CPrivateSendServer::CreateNewSession().
ToString()
std::string CDarksendQueue::ToString () inline
Definition at line 197 of file privatesend.h.
References fReady, fTried, nDenom, nTime, CTxIn::prevout, strprintf, COutPoint::ToStringShort(), and vin.
Referenced by CPrivateSendServer::CheckForCompleteQueue(), CheckSignature(), CPrivateSendServer::CreateNewSession(), CPrivateSendClient::JoinExistingQueue(), and Sign().
Friends And Related Function Documentation
operator==
bool operator== (const CDarksendQueue & a, const CDarksendQueue & b) friend
Definition at line 203 of file privatesend.h.
Member Data Documentation
ADD_SERIALIZE_METHODS
CDarksendQueue::ADD_SERIALIZE_METHODS
Definition at line 170 of file privatesend.h.
fReady
bool CDarksendQueue::fReady
Definition at line 147 of file privatesend.h.
Referenced by CheckSignature(), SerializationOp(), Sign(), and ToString().
fTried
bool CDarksendQueue::fTried
Definition at line 150 of file privatesend.h.
Referenced by CPrivateSendClient::JoinExistingQueue(), and ToString().
nDenom
int CDarksendQueue::nDenom
Definition at line 144 of file privatesend.h.
Referenced by CheckSignature(), CPrivateSendClient::JoinExistingQueue(), SerializationOp(), Sign(), and ToString().
nTime
int64_t CDarksendQueue::nTime
Definition at line 146 of file privatesend.h.
Referenced by CheckSignature(), IsExpired(), SerializationOp(), Sign(), and ToString().
vchSig
std::vector<unsigned char> CDarksendQueue::vchSig
Definition at line 148 of file privatesend.h.
Referenced by CheckSignature(), SerializationOp(), and Sign().
vin
CTxIn CDarksendQueue::vin
Definition at line 145 of file privatesend.h.
Referenced by CheckSignature(), CPrivateSendClient::JoinExistingQueue(), CPrivateSendServer::ProcessMessage(), CPrivateSendClient::ProcessMessage(), SerializationOp(), Sign(), and ToString().
The documentation for this class was generated from the following files:
src/privatesend.h
src/privatesend.cpp