Dash Core: CCoinsViewBacked Class Reference
CCoinsViewBacked Class Reference
CCoinsView backed by another CCoinsView.
#include <coins.h>
Public Member Functions
CCoinsViewBacked (CCoinsView *viewIn)
bool GetCoin (const COutPoint &outpoint, Coin &coin) const override
Retrieve the Coin (unspent transaction output) for a given outpoint.
bool HaveCoin (const COutPoint &outpoint) const override
Just check whether a given outpoint is unspent.
uint256 GetBestBlock () const override
Retrieve the block hash whose state this CCoinsView currently represents.
void SetBackend (CCoinsView &viewIn)
bool BatchWrite (CCoinsMap &mapCoins, const uint256 &hashBlock) override
Do a bulk modification (multiple Coin changes + BestBlock change).
CCoinsViewCursor * Cursor () const override
Get a cursor to iterate over the whole state.
size_t EstimateSize () const override
Estimate database size (0 if not implemented)
Public Member Functions inherited from CCoinsView
virtual ~CCoinsView ()
As we use CCoinsViews polymorphically, have a virtual destructor.
Protected Attributes
CCoinsView * base
Detailed Description
CCoinsView backed by another CCoinsView.
Definition at line 177 of file coins.h.
Constructor & Destructor Documentation
CCoinsViewBacked()
CCoinsViewBacked::CCoinsViewBacked (CCoinsView * viewIn)
Definition at line 24 of file coins.cpp.
Member Function Documentation
BatchWrite()
bool CCoinsViewBacked::BatchWrite (CCoinsMap & mapCoins, const uint256 & hashBlock) override virtual
Do a bulk modification (multiple Coin changes + BestBlock change).
The passed mapCoins can be modified.
Reimplemented from CCoinsView.
Reimplemented in CCoinsViewCache.
Definition at line 29 of file coins.cpp.
References base, and CCoinsView::BatchWrite().
Cursor()
CCoinsViewCursor * CCoinsViewBacked::Cursor () const override virtual
Get a cursor to iterate over the whole state.
Reimplemented from CCoinsView.
Reimplemented in CCoinsViewCache.
Definition at line 30 of file coins.cpp.
References base, and CCoinsView::Cursor().
EstimateSize()
size_t CCoinsViewBacked::EstimateSize () const override virtual
Estimate database size (0 if not implemented)
Reimplemented from CCoinsView.
Definition at line 31 of file coins.cpp.
References base, and CCoinsView::EstimateSize().
GetBestBlock()
uint256 CCoinsViewBacked::GetBestBlock () const override virtual
Retrieve the block hash whose state this CCoinsView currently represents.
Reimplemented from CCoinsView.
Reimplemented in CCoinsViewCache.
Definition at line 27 of file coins.cpp.
References base, and CCoinsView::GetBestBlock().
GetCoin()
bool CCoinsViewBacked::GetCoin (const COutPoint & outpoint, Coin & coin) const override virtual
Retrieve the Coin (unspent transaction output) for a given outpoint.
Returns true only when an unspent coin was found, which is returned in coin. When false is returned, coin's value is unspecified.
Reimplemented from CCoinsView.
Reimplemented in CCoinsViewMemPool, CCoinsViewCache, and CCoinsViewErrorCatcher.
Definition at line 25 of file coins.cpp.
References base, and CCoinsView::GetCoin().
Referenced by CCoinsViewErrorCatcher::GetCoin().
HaveCoin()
bool CCoinsViewBacked::HaveCoin (const COutPoint & outpoint) const override virtual
Just check whether a given outpoint is unspent.
Reimplemented from CCoinsView.
Reimplemented in CCoinsViewCache.
Definition at line 26 of file coins.cpp.
References base, and CCoinsView::HaveCoin().
SetBackend()
void CCoinsViewBacked::SetBackend (CCoinsView & viewIn)
Definition at line 28 of file coins.cpp.
References base.
Referenced by AcceptToMemoryPoolWorker(), rest_getutxos(), and signrawtransaction().
Member Data Documentation
base
CCoinsView* CCoinsViewBacked::base protected
Definition at line 180 of file coins.h.
Referenced by BatchWrite(), Cursor(), EstimateSize(), CCoinsViewCache::FetchCoin(), CCoinsViewCache::Flush(), GetBestBlock(), CCoinsViewCache::GetBestBlock(), GetCoin(), CCoinsViewMemPool::GetCoin(), HaveCoin(), and SetBackend().
The documentation for this class was generated from the following files:
src/coins.h
src/coins.cpp