Dash Core: src/secp256k1/src/eckey.h File Reference
eckey.h File Reference
#include <stddef.h>
#include "group.h"
#include "scalar.h"
#include "ecmult.h"
#include "ecmult_gen.h"
Functions
static int secp256k1_eckey_pubkey_parse (secp256k1_ge *elem, const unsigned char *pub, size_t size)
static int secp256k1_eckey_pubkey_serialize (secp256k1_ge *elem, unsigned char *pub, size_t *size, int compressed)
static int secp256k1_eckey_privkey_tweak_add (secp256k1_scalar *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_pubkey_tweak_add (const secp256k1_ecmult_context *ctx, secp256k1_ge *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_privkey_tweak_mul (secp256k1_scalar *key, const secp256k1_scalar *tweak)
static int secp256k1_eckey_pubkey_tweak_mul (const secp256k1_ecmult_context *ctx, secp256k1_ge *key, const secp256k1_scalar *tweak)
Function Documentation
secp256k1_eckey_privkey_tweak_add()
static int secp256k1_eckey_privkey_tweak_add (secp256k1_scalar * key, const secp256k1_scalar * tweak) static
Referenced by secp256k1_ec_privkey_tweak_add().
secp256k1_eckey_privkey_tweak_mul()
static int secp256k1_eckey_privkey_tweak_mul (secp256k1_scalar * key, const secp256k1_scalar * tweak) static
Referenced by secp256k1_ec_privkey_tweak_mul().
secp256k1_eckey_pubkey_parse()
static int secp256k1_eckey_pubkey_parse (secp256k1_ge * elem, const unsigned char * pub, size_t size) static
Referenced by secp256k1_ec_pubkey_parse(), test_ecdsa_edge_cases(), and test_random_pubkeys().
secp256k1_eckey_pubkey_serialize()
static int secp256k1_eckey_pubkey_serialize (secp256k1_ge * elem, unsigned char * pub, size_t * size, int compressed) static
Referenced by secp256k1_ec_pubkey_serialize(), test_point_times_order(), and test_random_pubkeys().
secp256k1_eckey_pubkey_tweak_add()
static int secp256k1_eckey_pubkey_tweak_add (const secp256k1_ecmult_context * ctx, secp256k1_ge * key, const secp256k1_scalar * tweak) static
Referenced by secp256k1_ec_pubkey_tweak_add().
secp256k1_eckey_pubkey_tweak_mul()
static int secp256k1_eckey_pubkey_tweak_mul (const secp256k1_ecmult_context * ctx, secp256k1_ge * key, const secp256k1_scalar * tweak) static
Referenced by secp256k1_ec_pubkey_tweak_mul().