Dash Core: src/script/sign.h File Reference
sign.h File Reference
#include "script/interpreter.h"
Classes
class BaseSignatureCreator
Virtual base class for signature creators.
class TransactionSignatureCreator
A signature creator for transactions.
class DummySignatureCreator
A signature creator that just produces 72-byte empty signatyres.
Functions
bool ProduceSignature (const BaseSignatureCreator &creator, const CScript &scriptPubKey, CScript &scriptSig)
Produce a script signature using a generic signature creator.
bool SignSignature (const CKeyStore &keystore, const CScript &fromPubKey, CMutableTransaction &txTo, unsigned int nIn, int nHashType=SIGHASH_ALL)
Produce a script signature for a transaction.
bool SignSignature (const CKeyStore &keystore, const CTransaction &txFrom, CMutableTransaction &txTo, unsigned int nIn, int nHashType=SIGHASH_ALL)
CScript CombineSignatures (const CScript &scriptPubKey, const BaseSignatureChecker &checker, const CScript &scriptSig1, const CScript &scriptSig2)
Combine two script signatures using a generic signature checker, intelligently, possibly with OP_0 placeholders.
CScript CombineSignatures (const CScript &scriptPubKey, const CTransaction &txTo, unsigned int nIn, const CScript &scriptSig1, const CScript &scriptSig2)
Combine two script signatures on transactions.
Function Documentation
CombineSignatures() [1/2]
CScript CombineSignatures (const CScript & scriptPubKey, const BaseSignatureChecker & checker, const CScript & scriptSig1, const CScript & scriptSig2)
Combine two script signatures using a generic signature checker, intelligently, possibly with OP_0 placeholders.
Definition at line 265 of file sign.cpp.
References CombineSignatures(), EvalScript(), SCRIPT_VERIFY_STRICTENC, and Solver().
CombineSignatures() [2/2]
CScript CombineSignatures (const CScript & scriptPubKey, const CTransaction & txTo, unsigned int nIn, const CScript & scriptSig1, const CScript & scriptSig2)
Combine two script signatures on transactions.
Definition at line 258 of file sign.cpp.
References CombineSignatures().
ProduceSignature()
bool ProduceSignature (const BaseSignatureCreator & creator, const CScript & scriptPubKey, CScript & scriptSig)
Produce a script signature using a generic signature creator.
Definition at line 104 of file sign.cpp.
References prevector< N, T, Size, Diff >::begin(), BaseSignatureCreator::Checker(), prevector< N, T, Size, Diff >::end(), SignStep(), STANDARD_SCRIPT_VERIFY_FLAGS, TX_SCRIPTHASH, and VerifyScript().
Referenced by CWallet::CreateTransaction(), IsMine(), and SignSignature().
SignSignature() [1/2]
bool SignSignature (const CKeyStore & keystore, const CScript & fromPubKey, CMutableTransaction & txTo, unsigned int nIn, int nHashType = SIGHASH_ALL)
Produce a script signature for a transaction.
Definition at line 129 of file sign.cpp.
References ProduceSignature(), and CMutableTransaction::vin.
Referenced by CWallet::CreateCollateralTransaction(), MutateTxSign(), CPrivateSendClient::SignFinalTransaction(), signrawtransaction(), and SignSignature().
SignSignature() [2/2]
bool SignSignature (const CKeyStore & keystore, const CTransaction & txFrom, CMutableTransaction & txTo, unsigned int nIn, int nHashType = SIGHASH_ALL)
Definition at line 140 of file sign.cpp.
References SignSignature(), CMutableTransaction::vin, and CTransaction::vout.