Dash Core: src/crypto/sph_blake.h File Reference
sph_blake.h File Reference
BLAKE interface.
#include <stddef.h>
#include "sph_types.h"
Classes
struct sph_blake_small_context
This structure is a context for BLAKE-224 and BLAKE-256 computations: it contains the intermediate values and some data from the last entered block.
Macros
#define SPH_SIZE_blake224 224
Output size (in bits) for BLAKE-224.
#define SPH_SIZE_blake256 256
Output size (in bits) for BLAKE-256.
Typedefs
typedef sph_blake_small_context sph_blake224_context
This structure is a context for BLAKE-224 computations.
typedef sph_blake_small_context sph_blake256_context
This structure is a context for BLAKE-256 computations.
Functions
void sph_blake224_init (void *cc)
Initialize a BLAKE-224 context.
void sph_blake224 (void *cc, const void *data, size_t len)
Process some data bytes.
void sph_blake224_close (void *cc, void *dst)
Terminate the current BLAKE-224 computation and output the result into the provided buffer.
void sph_blake224_addbits_and_close (void *cc, unsigned ub, unsigned n, void *dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (28 bytes).
void sph_blake256_init (void *cc)
Initialize a BLAKE-256 context.
void sph_blake256 (void *cc, const void *data, size_t len)
Process some data bytes.
void sph_blake256_close (void *cc, void *dst)
Terminate the current BLAKE-256 computation and output the result into the provided buffer.
void sph_blake256_addbits_and_close (void *cc, unsigned ub, unsigned n, void *dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (32 bytes).
Detailed Description
BLAKE interface.
BLAKE is a family of functions which differ by their output size; this implementation defines BLAKE for output sizes 224, 256, 384 and 512 bits. This implementation conforms to the "third round" specification.
==========================(LICENSE BEGIN)============================
Copyright (c) 2007-2010 Projet RNRT SAPHIR
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
===========================(LICENSE END)=============================
Author
Thomas Pornin thoma.nosp@m.s.po.nosp@m.rnin@.nosp@m.cryp.nosp@m.tolog.nosp@m..com
Definition in file sph_blake.h.
Macro Definition Documentation
SPH_SIZE_blake224
#define SPH_SIZE_blake224 224
Output size (in bits) for BLAKE-224.
Definition at line 50 of file sph_blake.h.
SPH_SIZE_blake256
#define SPH_SIZE_blake256 256
Output size (in bits) for BLAKE-256.
Definition at line 55 of file sph_blake.h.
Typedef Documentation
sph_blake224_context
typedef sph_blake_small_context sph_blake224_context
This structure is a context for BLAKE-224 computations.
It is identical to the common sph_blake_small_context.
Definition at line 95 of file sph_blake.h.
sph_blake256_context
typedef sph_blake_small_context sph_blake256_context
This structure is a context for BLAKE-256 computations.
It is identical to the common sph_blake_small_context.
Definition at line 101 of file sph_blake.h.
Function Documentation
sph_blake224()
void sph_blake224 (void * cc, const void * data, size_t len)
Process some data bytes.
It is acceptable that len is zero (in which case this function does nothing).
Parameters
cc the BLAKE-224 context
data the input data
len the input data length (in bytes)
Definition at line 1007 of file blake.c.
References blake32().
sph_blake224_addbits_and_close()
void sph_blake224_addbits_and_close (void * cc, unsigned ub, unsigned n, void * dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (28 bytes).
If bit number i in ub has value 2^i, then the extra bits are those numbered 7 downto 8-n (this is the big-endian convention at the byte level). The context is automatically reinitialized.
Parameters
cc the BLAKE-224 context
ub the extra bits
n the number of extra bits (0 to 7)
dst the destination buffer
Definition at line 1021 of file blake.c.
References blake32_close(), and sph_blake224_init().
Referenced by sph_blake224_close().
sph_blake224_close()
void sph_blake224_close (void * cc, void * dst)
Terminate the current BLAKE-224 computation and output the result into the provided buffer.
The destination buffer must be wide enough to accomodate the result (28 bytes). The context is automatically reinitialized.
Parameters
cc the BLAKE-224 context
dst the destination buffer
Definition at line 1014 of file blake.c.
References sph_blake224_addbits_and_close().
sph_blake224_init()
void sph_blake224_init (void * cc)
Initialize a BLAKE-224 context.
This process performs no memory allocation.
Parameters
cc the BLAKE-224 context (pointer to a sph_blake224_context)
Definition at line 1000 of file blake.c.
References blake32_init(), IV224, and salt_zero_small.
Referenced by sph_blake224_addbits_and_close().
sph_blake256()
void sph_blake256 (void * cc, const void * data, size_t len)
Process some data bytes.
It is acceptable that len is zero (in which case this function does nothing).
Parameters
cc the BLAKE-256 context
data the input data
len the input data length (in bytes)
Definition at line 1036 of file blake.c.
References blake32().
sph_blake256_addbits_and_close()
void sph_blake256_addbits_and_close (void * cc, unsigned ub, unsigned n, void * dst)
Add a few additional bits (0 to 7) to the current computation, then terminate it and output the result in the provided buffer, which must be wide enough to accomodate the result (32 bytes).
If bit number i in ub has value 2^i, then the extra bits are those numbered 7 downto 8-n (this is the big-endian convention at the byte level). The context is automatically reinitialized.
Parameters
cc the BLAKE-256 context
ub the extra bits
n the number of extra bits (0 to 7)
dst the destination buffer
Definition at line 1050 of file blake.c.
References blake32_close(), and sph_blake256_init().
Referenced by sph_blake256_close().
sph_blake256_close()
void sph_blake256_close (void * cc, void * dst)
Terminate the current BLAKE-256 computation and output the result into the provided buffer.
The destination buffer must be wide enough to accomodate the result (32 bytes). The context is automatically reinitialized.
Parameters
cc the BLAKE-256 context
dst the destination buffer
Definition at line 1043 of file blake.c.
References sph_blake256_addbits_and_close().
sph_blake256_init()
void sph_blake256_init (void * cc)
Initialize a BLAKE-256 context.
This process performs no memory allocation.
Parameters
cc the BLAKE-256 context (pointer to a sph_blake256_context)
Definition at line 1029 of file blake.c.
References blake32_init(), IV256, and salt_zero_small.
Referenced by sph_blake256_addbits_and_close().