Dash Core: CDataStream Class Reference
CDataStream Class Reference
Double ended buffer combining vector and stream-like interfaces.
#include <streams.h>
Public Types
typedef vector_type::allocator_type allocator_type
typedef vector_type::size_type size_type
typedef vector_type::difference_type difference_type
typedef vector_type::reference reference
typedef vector_type::const_reference const_reference
typedef vector_type::value_type value_type
typedef vector_type::iterator iterator
typedef vector_type::const_iterator const_iterator
typedef vector_type::reverse_iterator reverse_iterator
Public Member Functions
CDataStream (int nTypeIn, int nVersionIn)
CDataStream (const_iterator pbegin, const_iterator pend, int nTypeIn, int nVersionIn)
CDataStream (const char *pbegin, const char *pend, int nTypeIn, int nVersionIn)
CDataStream (const vector_type &vchIn, int nTypeIn, int nVersionIn)
CDataStream (const std::vector< char > &vchIn, int nTypeIn, int nVersionIn)
CDataStream (const std::vector< unsigned char > &vchIn, int nTypeIn, int nVersionIn)
template<typename... Args>
CDataStream (int nTypeIn, int nVersionIn, Args &&... args)
void Init (int nTypeIn, int nVersionIn)
CDataStream & operator+= (const CDataStream &b)
std::string str () const
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
size_type size () const
bool empty () const
void resize (size_type n, value_type c=0)
void reserve (size_type n)
const_reference operator[] (size_type pos) const
reference operator[] (size_type pos)
void clear ()
iterator insert (iterator it, const char &x=char())
void insert (iterator it, size_type n, const char &x)
value_type * data ()
const value_type * data () const
void insert (iterator it, std::vector< char >::const_iterator first, std::vector< char >::const_iterator last)
void insert (iterator it, const char *first, const char *last)
iterator erase (iterator it)
iterator erase (iterator first, iterator last)
void Compact ()
bool Rewind (size_type n)
bool eof () const
CDataStream * rdbuf ()
int in_avail ()
void SetType (int n)
int GetType ()
void SetVersion (int n)
int GetVersion ()
void ReadVersion ()
void WriteVersion ()
CDataStream & read (char *pch, size_t nSize)
CDataStream & ignore (int nSize)
CDataStream & write (const char *pch, size_t nSize)
template<typename Stream >
void Serialize (Stream &s, int nType, int nVersion) const
template<typename T >
unsigned int GetSerializeSize (const T &obj)
template<typename T >
CDataStream & operator<< (const T &obj)
template<typename T >
CDataStream & operator>> (T &obj)
void GetAndClear (CSerializeData &data)
void Xor (const std::vector< unsigned char > &key)
XOR the contents of this stream with a certain key.
Public Attributes
int nType
int nVersion
Protected Types
typedef CSerializeData vector_type
Protected Attributes
vector_type vch
unsigned int nReadPos
Friends
CDataStream operator+ (const CDataStream &a, const CDataStream &b)
Detailed Description
Double ended buffer combining vector and stream-like interfaces.
and << read and write unformatted data using the above serialization templates.
Fills with data in linear time; some stringstream implementations take N^2 time.
Definition at line 30 of file streams.h.
Member Typedef Documentation
allocator_type
typedef vector_type::allocator_type CDataStream::allocator_type
Definition at line 40 of file streams.h.
const_iterator
typedef vector_type::const_iterator CDataStream::const_iterator
Definition at line 47 of file streams.h.
const_reference
typedef vector_type::const_reference CDataStream::const_reference
Definition at line 44 of file streams.h.
difference_type
typedef vector_type::difference_type CDataStream::difference_type
Definition at line 42 of file streams.h.
iterator
typedef vector_type::iterator CDataStream::iterator
Definition at line 46 of file streams.h.
reference
typedef vector_type::reference CDataStream::reference
Definition at line 43 of file streams.h.
reverse_iterator
typedef vector_type::reverse_iterator CDataStream::reverse_iterator
Definition at line 48 of file streams.h.
size_type
typedef vector_type::size_type CDataStream::size_type
Definition at line 41 of file streams.h.
value_type
typedef vector_type::value_type CDataStream::value_type
Definition at line 45 of file streams.h.
vector_type
typedef CSerializeData CDataStream::vector_type protected
Definition at line 33 of file streams.h.
Constructor & Destructor Documentation
CDataStream() [1/7]
CDataStream::CDataStream (int nTypeIn, int nVersionIn) inline explicit
Definition at line 50 of file streams.h.
References Init().
CDataStream() [2/7]
CDataStream::CDataStream (const_iterator pbegin, const_iterator pend, int nTypeIn, int nVersionIn) inline
Definition at line 55 of file streams.h.
References Init().
CDataStream() [3/7]
CDataStream::CDataStream (const char * pbegin, const char * pend, int nTypeIn, int nVersionIn) inline
Definition at line 60 of file streams.h.
References Init().
CDataStream() [4/7]
CDataStream::CDataStream (const vector_type & vchIn, int nTypeIn, int nVersionIn) inline
Definition at line 65 of file streams.h.
References Init().
CDataStream() [5/7]
CDataStream::CDataStream (const std::vector< char > & vchIn, int nTypeIn, int nVersionIn) inline
Definition at line 70 of file streams.h.
References Init().
CDataStream() [6/7]
CDataStream::CDataStream (const std::vector< unsigned char > & vchIn, int nTypeIn, int nVersionIn) inline
Definition at line 75 of file streams.h.
References Init().
CDataStream() [7/7]
template<typename... Args> CDataStream::CDataStream (int nTypeIn, int nVersionIn, Args &&... args) inline
Definition at line 81 of file streams.h.
References Init(), nType, nVersion, and SerializeMany().
Member Function Documentation
begin() [1/2]
const_iterator CDataStream::begin () const inline
Definition at line 116 of file streams.h.
References nReadPos, and vch.
Referenced by CBloomFilter::contains(), EncodeHexTx(), CConnman::EndMessage(), GetAndClear(), getblock(), getblockheader(), getblockheaders(), gettxoutproof(), CBloomFilter::insert(), masternodebroadcast(), CZMQPublishRawBlockNotifier::NotifyBlock(), operator+=(), ProcessMessages(), CConnman::PushMessage(), CFlatDB< T >::Read(), CAddrDB::Read(), CBanDB::Read(), rest_block(), rest_getutxos(), rest_headers(), rest_tx(), CAccountingEntry::SerializationOp(), CAlert::Sign(), str(), CFlatDB< T >::Write(), CAddrDB::Write(), and CBanDB::Write().
begin() [2/2]
iterator CDataStream::begin () inline
Definition at line 117 of file streams.h.
References nReadPos, and vch.
clear()
void CDataStream::clear () inline
Definition at line 126 of file streams.h.
References nReadPos, and vch.
Referenced by CDBBatch::Erase(), GetAndClear(), CDB::ReadAtCursor(), CDB::Rewrite(), and CDBBatch::Write().
Compact()
void CDataStream::Compact () inline
Definition at line 197 of file streams.h.
References nReadPos, and vch.
data() [1/2]
value_type* CDataStream::data () inline
Definition at line 129 of file streams.h.
References nReadPos, and vch.
Referenced by CDBWrapper::CompactRange(), CDBBatch::Erase(), CDB::Erase(), CDBWrapper::EstimateSize(), CDB::Exists(), CDBWrapper::Exists(), GetAndClear(), CDB::Read(), CDBWrapper::Read(), CDB::ReadAtCursor(), CDB::Rewrite(), CDBIterator::Seek(), CDBBatch::Write(), and CDB::Write().
data() [2/2]
const value_type* CDataStream::data () const inline
Definition at line 130 of file streams.h.
References nReadPos, and vch.
empty()
bool CDataStream::empty () const inline
Definition at line 121 of file streams.h.
References nReadPos, and vch.
Referenced by ProcessMessage(), CConnman::PushMessage(), ReadKeyValue(), and signrawtransaction().
end() [1/2]
const_iterator CDataStream::end () const inline
Definition at line 118 of file streams.h.
References vch.
Referenced by CBloomFilter::contains(), EncodeHexTx(), CConnman::EndMessage(), GetAndClear(), getblock(), getblockheader(), getblockheaders(), gettxoutproof(), CBloomFilter::insert(), masternodebroadcast(), operator+=(), CConnman::PushMessage(), CFlatDB< T >::Read(), CAddrDB::Read(), CBanDB::Read(), rest_block(), rest_getutxos(), rest_headers(), rest_tx(), CAccountingEntry::SerializationOp(), CAlert::Sign(), str(), CFlatDB< T >::Write(), CAddrDB::Write(), and CBanDB::Write().
end() [2/2]
iterator CDataStream::end () inline
Definition at line 119 of file streams.h.
References vch.
eof()
bool CDataStream::eof () const inline
Definition at line 216 of file streams.h.
References size().
erase() [1/2]
iterator CDataStream::erase (iterator it) inline
Definition at line 160 of file streams.h.
References nReadPos, and vch.
erase() [2/2]
iterator CDataStream::erase (iterator first, iterator last) inline
Definition at line 177 of file streams.h.
References nReadPos, and vch.
GetAndClear()
void CDataStream::GetAndClear (CSerializeData & data) inline
Definition at line 306 of file streams.h.
References begin(), clear(), data(), and end().
GetSerializeSize()
template<typename T > unsigned int CDataStream::GetSerializeSize (const T & obj) inline
Definition at line 284 of file streams.h.
References GetSerializeSize(), nType, and nVersion.
GetType()
int CDataStream::GetType () inline
Definition at line 221 of file streams.h.
References nType.
GetVersion()
int CDataStream::GetVersion () inline
Definition at line 223 of file streams.h.
References nVersion.
ignore()
CDataStream& CDataStream::ignore (int nSize) inline
Definition at line 249 of file streams.h.
References nReadPos, and vch.
in_avail()
int CDataStream::in_avail () inline
Definition at line 218 of file streams.h.
References size().
Referenced by ProcessMessage().
Init()
void CDataStream::Init (int nTypeIn, int nVersionIn) inline
Definition at line 87 of file streams.h.
References nReadPos, nType, and nVersion.
Referenced by CDataStream().
insert() [1/4]
iterator CDataStream::insert (iterator it, const char & x = char()) inline
Definition at line 127 of file streams.h.
References vch.
Referenced by CAccountingEntry::SerializationOp().
insert() [2/4]
void CDataStream::insert (iterator it, size_type n, const char & x) inline
Definition at line 128 of file streams.h.
References vch.
insert() [3/4]
void CDataStream::insert (iterator it, std::vector< char >::const_iterator first, std::vector< char >::const_iterator last) inline
Definition at line 132 of file streams.h.
References memcpy(), nReadPos, and vch.
insert() [4/4]
void CDataStream::insert (iterator it, const char * first, const char * last) inline
Definition at line 146 of file streams.h.
References memcpy(), nReadPos, and vch.
operator+=()
CDataStream& CDataStream::operator+= (const CDataStream & b) inline
Definition at line 94 of file streams.h.
References begin(), end(), and vch.
operator<<()
template<typename T > CDataStream& CDataStream::operator<< (const T & obj) inline
Definition at line 291 of file streams.h.
References nType, nVersion, and Serialize().
operator>>()
template<typename T > CDataStream& CDataStream::operator>> (T & obj) inline
Definition at line 299 of file streams.h.
References nType, nVersion, and Unserialize().
operator[]() [1/2]
const_reference CDataStream::operator[] (size_type pos) const inline
Definition at line 124 of file streams.h.
References nReadPos, and vch.
operator[]() [2/2]
reference CDataStream::operator[] (size_type pos) inline
Definition at line 125 of file streams.h.
References nReadPos, and vch.
rdbuf()
CDataStream* CDataStream::rdbuf () inline
Definition at line 217 of file streams.h.
read()
CDataStream& CDataStream::read (char * pch, size_t nSize) inline
Definition at line 227 of file streams.h.
References memcpy(), nReadPos, and vch.
ReadVersion()
void CDataStream::ReadVersion () inline
Definition at line 224 of file streams.h.
References nVersion.
reserve()
void CDataStream::reserve (size_type n) inline
Definition at line 123 of file streams.h.
References nReadPos, and vch.
Referenced by CDBWrapper::CompactRange(), CDBBatch::Erase(), CDB::Erase(), CDBWrapper::EstimateSize(), CDB::Exists(), CDBWrapper::Exists(), ProcessGetData(), CDB::Read(), CDBWrapper::Read(), CConnman::RelayTransaction(), CDBIterator::Seek(), CDBBatch::Write(), and CDB::Write().
resize()
void CDataStream::resize (size_type n, value_type c = 0) inline
Definition at line 122 of file streams.h.
References nReadPos, and vch.
Referenced by CNetMessage::CNetMessage(), and CNetMessage::readData().
Rewind()
bool CDataStream::Rewind (size_type n) inline
Definition at line 203 of file streams.h.
References nReadPos.
Serialize()
template<typename Stream > void CDataStream::Serialize (Stream & s, int nType, int nVersion) const inline
Definition at line 276 of file streams.h.
References vch.
Referenced by operator<<().
SetType()
void CDataStream::SetType (int n) inline
Definition at line 220 of file streams.h.
References nType.
Referenced by CDB::ReadAtCursor().
SetVersion()
void CDataStream::SetVersion (int n) inline
Definition at line 222 of file streams.h.
References nVersion.
Referenced by CNetMessage::SetVersion().
size()
size_type CDataStream::size () const inline
Definition at line 120 of file streams.h.
References nReadPos, and vch.
Referenced by CDBWrapper::CompactRange(), CConnman::EndMessage(), eof(), CDBBatch::Erase(), CDB::Erase(), CDBWrapper::EstimateSize(), CDB::Exists(), CDBWrapper::Exists(), in_avail(), CZMQPublishRawBlockNotifier::NotifyBlock(), ProcessMessage(), CConnman::PushMessage(), CDB::Read(), CDBWrapper::Read(), CDB::ReadAtCursor(), CNetMessage::readData(), CDB::Rewrite(), CDBIterator::Seek(), WalletModel::sendCoins(), CDBBatch::Write(), CDB::Write(), and Xor().
str()
std::string CDataStream::str () const inline
Definition at line 107 of file streams.h.
References begin(), and end().
Referenced by RecentRequestsTableModel::addNewRequest(), rest_block(), rest_getutxos(), rest_headers(), rest_tx(), and CAccountingEntry::SerializationOp().
write()
CDataStream& CDataStream::write (const char * pch, size_t nSize) inline
Definition at line 268 of file streams.h.
References vch.
Referenced by CDB::ReadAtCursor().
WriteVersion()
void CDataStream::WriteVersion () inline
Definition at line 225 of file streams.h.
References nVersion.
Xor()
void CDataStream::Xor (const std::vector< unsigned char > & key) inline
XOR the contents of this stream with a certain key.
Parameters
[in] key The key used to XOR the data in this stream.
Definition at line 316 of file streams.h.
References size(), and vch.
Referenced by CDBIterator::GetValue(), CDBWrapper::Read(), and CDBBatch::Write().
Friends And Related Function Documentation
operator+
CDataStream operator+ (const CDataStream & a, const CDataStream & b) friend
Definition at line 100 of file streams.h.
Member Data Documentation
nReadPos
unsigned int CDataStream::nReadPos protected
Definition at line 35 of file streams.h.
Referenced by begin(), clear(), Compact(), data(), empty(), erase(), ignore(), Init(), insert(), operator[](), read(), reserve(), resize(), Rewind(), and size().
nType
int CDataStream::nType
Definition at line 37 of file streams.h.
Referenced by CDataStream(), GetSerializeSize(), GetType(), Init(), operator<<(), operator>>(), and SetType().
nVersion
int CDataStream::nVersion
Definition at line 38 of file streams.h.
Referenced by CDataStream(), GetSerializeSize(), GetVersion(), Init(), operator<<(), operator>>(), ReadVersion(), SetVersion(), and WriteVersion().
vch
vector_type CDataStream::vch protected
Definition at line 34 of file streams.h.
Referenced by begin(), clear(), Compact(), data(), empty(), end(), erase(), ignore(), insert(), operator+=(), operator[](), read(), reserve(), resize(), Serialize(), size(), write(), and Xor().
The documentation for this class was generated from the following file:
src/streams.h