Dash Core: CMasternodePayee Class Reference
CMasternodePayee Class Reference
#include <masternode-payments.h>
Public Member Functions
CMasternodePayee ()
CMasternodePayee (CScript payee, uint256 hashIn)
template<typename Stream , typename Operation >
void SerializationOp (Stream &s, Operation ser_action, int nType, int nVersion)
CScript GetPayee ()
void AddVoteHash (uint256 hashIn)
std::vector< uint256 > GetVoteHashes ()
int GetVoteCount ()
Public Attributes
ADD_SERIALIZE_METHODS
Private Attributes
CScript scriptPubKey
std::vector< uint256 > vecVoteHashes
Detailed Description
Definition at line 41 of file masternode-payments.h.
Constructor & Destructor Documentation
CMasternodePayee() [1/2]
CMasternodePayee::CMasternodePayee () inline
Definition at line 48 of file masternode-payments.h.
CMasternodePayee() [2/2]
CMasternodePayee::CMasternodePayee (CScript payee, uint256 hashIn) inline
Definition at line 53 of file masternode-payments.h.
References vecVoteHashes.
Member Function Documentation
AddVoteHash()
void CMasternodePayee::AddVoteHash (uint256 hashIn) inline
Definition at line 70 of file masternode-payments.h.
References vecVoteHashes.
Referenced by CMasternodeBlockPayees::AddPayee().
GetPayee()
CScript CMasternodePayee::GetPayee () inline
Definition at line 68 of file masternode-payments.h.
References scriptPubKey.
Referenced by CMasternodeBlockPayees::AddPayee(), CMasternodeBlockPayees::GetBestPayee(), CMasternodeBlockPayees::GetRequiredPaymentsString(), CMasternodeBlockPayees::HasPayeeWithVotes(), and CMasternodeBlockPayees::IsTransactionValid().
GetVoteCount()
int CMasternodePayee::GetVoteCount () inline
Definition at line 72 of file masternode-payments.h.
References vecVoteHashes.
Referenced by CMasternodeBlockPayees::GetBestPayee(), CMasternodeBlockPayees::GetRequiredPaymentsString(), CMasternodeBlockPayees::HasPayeeWithVotes(), CMasternodeBlockPayees::IsTransactionValid(), and CMasternodePayments::RequestLowDataPaymentBlocks().
GetVoteHashes()
std::vector<uint256> CMasternodePayee::GetVoteHashes () inline
Definition at line 71 of file masternode-payments.h.
References vecVoteHashes.
Referenced by ProcessGetData(), and CMasternodePayments::Sync().
SerializationOp()
template<typename Stream , typename Operation > void CMasternodePayee::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion) inline
Definition at line 63 of file masternode-payments.h.
References READWRITE, scriptPubKey, and vecVoteHashes.
Member Data Documentation
ADD_SERIALIZE_METHODS
CMasternodePayee::ADD_SERIALIZE_METHODS
Definition at line 60 of file masternode-payments.h.
scriptPubKey
CScript CMasternodePayee::scriptPubKey private
Definition at line 44 of file masternode-payments.h.
Referenced by GetPayee(), and SerializationOp().
vecVoteHashes
std::vector<uint256> CMasternodePayee::vecVoteHashes private
Definition at line 45 of file masternode-payments.h.
Referenced by AddVoteHash(), CMasternodePayee(), GetVoteCount(), GetVoteHashes(), and SerializationOp().
The documentation for this class was generated from the following file:
src/masternode-payments.h